### ISSUE TITLE
Unable to find Account Expire extension attribute in Azure AD through Graph API

### ISSUE THREAD

**Issue by kalalsandeep** [microsoftgraph/msgraph-sdk-dotnet#1001]
We have synced Account Expire attribute from Local AD to Azure AD through AAD Connect Extension Attribute sync feature (Not with sync rule) but while using Graph API, we are unable to find this account expire attribute.
We are able to see all other attributes associated with user account.
We have created ticket with Microsoft Exchange and Microsoft Azure Support but they said we need to raise an issue here and they will not support it.
Support article https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fgraph%2Fsdks%2Fcreate-requests%3Ftabs%3DCS%23provide-custom-query-parameters&data=04%7C01%7Ckalal%40unhcr.org%7C1393809cd921446ea5f708d91619778c%7Ce5c37981666441348a0c6543d2af80be%7C0%7C0%7C637565120943531819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AnpTOxjSdGWvXbKTHon1IfkhbQEKOWoeSTI2WLAgk74%3D&reserved=0

Below is what Microsoft mentioned:
"In our last meeting we discussed about the situation, took another Fiddler and we saw that there are indeed requests for Microsoft Graph being done by your code, however the Graph SDK did not return anything.

And then I guided you towards the Microsoft Graph SDK Github where our engineering team supports issues with the SDK itself as this one seems to be: microsoftgraph/msgraph-sdk-dotnet: Microsoft Graph Client Library for .NET! (github.com)
" 
[AB#9486](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9486)

**Comment by andrueastman** [comment]
Hey @kalalsandeep, Thanks for opening this issue.

Are you able to provide more information on how you are trying to call the API? Are you able to provide example code of how you are trying to retrieve the data? 
This information will help us figure out where the problem would be.

**Comment by kalalsandeep** [comment]
++ Vinay and Ram from developer Team for more information.

Regards,
Sandeep ***@***.***>
Platform Support
O365 & Wintel
***@***.***D75E13.9BEF4DA0]   +91 9970911895
www.unhcr.org<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.unhcr.org%2F&data=02%7C01%7Ckalal%40unhcr.org%7C11b6f0d5d04b419880a008d82fb1ac05%7Ce5c37981666441348a0c6543d2af80be%7C0%7C0%7C637311787420282142&sdata=oop64F3nzOzxBYtnkvxEUTF6h4TlqS%2FL0RCcHUfrjlk%3D&reserved=0>
***@***.***D75E13.9BEF4DA0]
My working hours may not be your working hours. Please do not feel obligated to respond outside your working hours.

Please contact GSD ***@***.******@***.***>) to report any issue.  To follow-up on an existing ticket, please send email to ***@***.******@***.***>.

**Comment by kalalsandeep** [comment]
Hi Team,


We are using Graph API  client in the code ,please find the sample code.
Var data  = await graphClient?.Result?.Users?.Request().Filter(xyz)

Regards,
Vinay

From: Sandeep ***@***.***>
Sent: Thursday, June 10, 2021 4:14 PM
To: ***@***.***>; ***@***.***>; Appala ***@***.***>; Ram Reddy ***@***.***>
Cc: ***@***.***>; Amit ***@***.***>; Mohammad Zubair ***@***.***>
Subject: RE: [microsoftgraph/msgraph-sdk-dotnet] Unable to find Account Expire extension attribute in Azure AD through Graph API (#1001)

++ Vinay and Ram from developer Team for more information.

Regards,
Sandeep ***@***.***>
Platform Support
O365 & Wintel
***@***.***D75E13.9BEF4DA0]   +91 9970911895
www.unhcr.org<https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.unhcr.org%2F&data=04%7C01%7Cvinay%40unhcr.org%7C447167638d2241b4871408d92bfcc869%7Ce5c37981666441348a0c6543d2af80be%7C0%7C0%7C637589186957400737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mmYJv6TyG6SVVAEEROrMKzNFoKRSsiPL%2FXsyEI24Pss%3D&reserved=0>
***@***.***D75E13.9BEF4DA0]
My working hours may not be your working hours. Please do not feel obligated to respond outside your working hours.

Please contact GSD ***@***.******@***.***>) to report any issue.  To follow-up on an existing ticket, please send email to ***@***.******@***.***>.

**Comment by andrueastman** [comment]
Thanks for this. 
If you try to make this call for a specific user, are you able to view the extension attributes the response?

```cs
var extensions = await graphClient.Users["user-id"].Extensions
    .Request()
    .GetAsync();
```
