### ISSUE TITLE
Cannot install Newtonsoft.Json 10.0.1 with Microsoft.Graph 1.2.1

### ISSUE THREAD

**Issue by StuartMeeks** [microsoftgraph/msgraph-sdk-dotnet#101]
Output from Package Manager

Attempting to gather dependency information for package 'Newtonsoft.Json.10.0.1' with respect to project 'Tesla.XXXXX.XXXXX.XXXXX', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 1.4 sec
Attempting to resolve dependencies for package 'Newtonsoft.Json.10.0.1' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Newtonsoft.Json 10.0.1' is not compatible with 'Microsoft.Graph 1.2.1 constraint: Newtonsoft.Json (>= 6.0.1 && < 10.0.0)', 'Microsoft.Graph.Core 1.3.0 constraint: Newtonsoft.Json (>= 6.0.1 && < 10.0.0)'.
Time Elapsed: 00:00:02.8624708

**Comment by MIchaelMainer** [comment]
Hi Stuart, we've tested Microsoft.Graph 1.2.1 with NewtonSoft.Json 6 through 9. What scenario are you looking to enable with NewtonSoft.Json 10?

**Comment by alx-andru** [comment]
Hi @MIchaelMainer I had similar issue. 
NewtonSoftJSON 8.0.3 resulted in following message:
```
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.
```

Installing `NewtonSoftJSON 9.0.1` resolved it.

**Comment by StuartMeeks** [comment]
HI @MIchaelMainer - I'm just looking to use the latest version of Newtonsoft.Json throughout my solution. At the moment, having a dependency on Microsoft.Graph (and it's limitation on the version of Json.Net used with it) is preventing me from upgrading the Json.Net dependency in the rest of my projects.

**Comment by MIchaelMainer** [comment]
We need to add an assembly binding redirect to allow versions of Newtonsoft.Json other than the version referenced when the client library was built.

**Comment by searus** [comment]
Hi @MIchaelMainer , I also have this issue.  My use case is that I am trying to update to the latest aspnet core stuff (v2.0.0-preview2-*) and Microsoft.AspNetCore.Authentication.OAuth has a dependency on Newtonsoft.Json (>= 10.0.1).  So, I am unable to update.  Do you know if there is a workaround?

**Comment by MIchaelMainer** [comment]
Hi @searus , I don't know whether there is a workaround for that scenario. I was unaware that having one package take a dependency on a version range would block another package from installing its dependency if its version range fell outside of the first one. It would be unfortunate if that was the case as then different packages couldn't depend on different versions of the same dependency. 

I'll be updating the package to use >=10.0.1 after I test it. It should be fine.  I'll be adding an assembly binding redirect soon.

**Comment by MIchaelMainer** [comment]
This has been addressed with https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.3.0. Created another issue to track the binding redirect.
