### ISSUE TITLE
Content/File Type support for Preview?

### ISSUE THREAD

**Issue by TejendraPrasad** [microsoftgraph/msgraph-sdk-dotnet#1010]
Hi,

We have implemented file preview option from Drive Items. Not every file format are supported in preivew under various Browser IE, IE edge, Firefox and Chrome.

Example: CSV & XLS - For CSV its show error and download button. however, for XLS it show below error 

 **Sorry, something went wrong Item does not exist. It may have been deleted by another user.
TECHNICAL DETAILS
GO BACK TO SITE error message**

We are trying preivew of following files - csv, png, xls, xlsx, xlsb, xlsm, msg, ppt, pptx, potx, pps, ppsx, doc, docx, docm, pdf, mp4, mpeg, mpg, xlsx - Password protected, ..

Please let me know which file format are currently supported for preivew... In MS site (https://support.microsoft.com/en-us/office/file-types-supported-for-previewing-files-in-onedrive-sharepoint-and-teams-e054cd0f-8ef2-4ccb-937e-26e37419c5e4) it says everything supported but its not working.

thank you!
Tej 
[AB#9545](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9545)

**Comment by MIchaelMainer** [comment]
That support document only mentions Microsoft Teams, OneDrive, and SharePoint. It makes no mention of browser support. This repo is for the Microsoft Graph .NET client library; we are not familiar with the support story for file extensions and preview capability in browsers.
