### ISSUE TITLE
Creating Online Meeting Returns: Code: generalException, Message: An error occurred sending the request

### ISSUE THREAD

**Issue by xown-dev** [microsoftgraph/msgraph-sdk-dotnet#1013]
Hello. 

I'm trying to create an online meeting from asp net core web api, but I'm getting this "generalException" error.
See details below.

**AuthenticationProvider for configuring auth for the API call:**

`

    public class GraphAuthenticationProvider : IAuthenticationProvider
    {
        public const string GRAPH_URI = "https://graph.microsoft.com/v1.0/";

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="configuration"></param>
        public GraphAuthenticationProvider(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; set; }

        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            AuthenticationContext authContext = new AuthenticationContext($"https://login.microsoftonline.com/{Configuration["AzureAd:TenantId"]}");

            ClientCredential credentials = new ClientCredential(Configuration["AzureAd:ClientId"], Configuration["AzureAd:ClientSecret"]);

            AuthenticationResult authResult = await authContext.AcquireTokenAsync(GRAPH_URI, credentials);

            request.Headers.Add("Authorization", "Bearer " + authResult.AccessToken);
            request.Headers.Add("Content-type", "application/json");
        }
    }`

**GraphProvider for making the actual API request:**

`

    public class MicrosoftGraphProvider : IGraphProvider
    {
        private IGraphServiceClient _graph;

        public MicrosoftGraphProvider(IGraphServiceClient graph)
        {
            _graph = graph;
        }

        public async Task<CreateMeetingResult> CreateMeetingAsync(OnlineMeeting onlineMeeting)
        {
            // Initialize error message
            var errorMessage = default(string);

            // Initialize meeting result
            var meetingResult = default(OnlineMeeting);

            try
            {
                // Try creating the meeting
                meetingResult = await _graph.Me.OnlineMeetings
                    .Request()
                    .AddAsync(onlineMeeting);
            }
            catch (Exception ex)
            {
                // Set the error message
                errorMessage = ex.Message;
            }

            // Return the result
            return new CreateMeetingResult
            {
                ErrorPhrase = errorMessage,
                MeetingResult = meetingResult
            };
        }
    }`

**AuthenticationProvider, GraphServiceClient, and GraphProvider transient instances in StartUp.cs:**

`

            services.AddTransient<IAuthenticationProvider, GraphAuthenticationProvider>(provider => 
                new GraphAuthenticationProvider(provider.GetService<IConfiguration>()));

            // Add transient instance of the graph service client
            services.AddTransient<IGraphServiceClient, GraphServiceClient>(provider => 
                new GraphServiceClient(provider.GetService<IAuthenticationProvider>()));

            // Add transient instance of the graph provider
            services.AddTransient<IGraphProvider, MicrosoftGraphProvider>(provider => 
                new MicrosoftGraphProvider(provider.GetService<IGraphServiceClient>()));
`

**Setting OnlineMeeting data and Invoking CreatingMeeting:**

`

            var onlineMeeting = new OnlineMeeting
            {
                Subject = meetingDetails.Subject,
                AllowedPresenters = OnlineMeetingPresenters.Organizer,
                IsEntryExitAnnounced = true,
                Participants = new MeetingParticipants
                {
                    Attendees = new List<MeetingParticipantInfo>
                    {
                        new MeetingParticipantInfo
                        {
                            Role = OnlineMeetingRole.Attendee,
                            Identity = new IdentitySet
                            {
                                Application = new Identity
                                {
                                    Id = Guid.NewGuid().ToString(),
                                    DisplayName = "Attendee1"
                                }
                            }
                        },
                        new MeetingParticipantInfo
                        {
                            Role = OnlineMeetingRole.Presenter,
                            Identity = new IdentitySet
                            {
                                Application = new Identity
                                {
                                    Id = Guid.NewGuid().ToString(),
                                    DisplayName = "Attendee2"
                                }
                            }
                        },
                        new MeetingParticipantInfo
                        {
                            Role = OnlineMeetingRole.Presenter,
                            Identity = new IdentitySet
                            {
                                Application = new Identity
                                {
                                    Id = Guid.NewGuid().ToString(),
                                    DisplayName = "Attendee3"
                                }
                            }
                        }
                    },
                    Organizer = new MeetingParticipantInfo
                    {
                        Role = OnlineMeetingRole.Presenter,
                        Identity = new IdentitySet
                        {
                            Application = new Identity
                            {
                                Id = Guid.NewGuid().ToString(),
                                DisplayName = Framework.Construction.Configuration["OnlineMeeting:Organiser:DisplayName"]
                            }
                        }
                    }
                },
                EndDateTime = DateTimeOffset.Now.AddHours(1),
                StartDateTime = DateTimeOffset.Now.AddHours(2)
            };

            // Fire create meeting
            var meetingResult = await _graphProvider.CreateMeetingAsync(onlineMeeting);
`

**ApiResponse:**

`

    {
        "response": null,
        "successful": false,
        "errorMessage": "Code: generalException\r\nMessage: An error occurred sending the request.\r\n"
    }
`

I have created an application in azure app service and added all necessary permissions as well.

![perms](https://user-images.githubusercontent.com/76403404/119184492-57aba380-ba6d-11eb-8e8b-fdfe53833d05.png)

What is it that I'm not doing correctly?
If you require more info, please ask me.
Thanks in advance. 
[AB#9564](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9564)

**Comment by andrueastman** [comment]
Hey @xown-dev, 
Any chance you could check out this issues and see if the workarounds provided work out for you?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/566

**Comment by andrueastman** [comment]
ping @xown-dev

**Comment by xown-dev** [comment]
@andrueastman. Thank you for the suggestion.

They said that the fix is by specifying a property member 'ODataType' in the api data object, in their case is Team(), while in my case is OnlineMeeting(). 
There is no member such as 'ODataType' in the OnlineMeeting object.

**Comment by andrueastman** [comment]
`OnlineMeeting` derives from entity so it does have the `OdataType` property through inheritance. 

My suspicion is that one of the objects in the payload has the value set that the API side does not like similar to #566
You can try out something like this to ascertain that this is the cause of the issue. (Note the added lines to your example)

```cs
var onlineMeeting = new OnlineMeeting
{
    ODataType = null, // ADD THIS
    Subject = "Subject",
    AllowedPresenters = OnlineMeetingPresenters.Organizer,
    IsEntryExitAnnounced = true,
    Participants = new MeetingParticipants
    {
        ODataType = null, // ADD THIS
        Attendees = new List<MeetingParticipantInfo>
    {
        new MeetingParticipantInfo
        {
            ODataType = null,// ADD THIS
            Role = OnlineMeetingRole.Attendee,
            Identity = new IdentitySet
            {
                Application = new Identity
                {
                    Id = Guid.NewGuid().ToString(),
                    DisplayName = "Attendee1"
                }
            }
        },
        new MeetingParticipantInfo
        {
            ODataType = null, // ADD THIS
            Role = OnlineMeetingRole.Presenter,
            Identity = new IdentitySet
            {
                Application = new Identity
                {
                    Id = Guid.NewGuid().ToString(),
                    DisplayName = "Attendee2"
                }
            }
        },
        new MeetingParticipantInfo
        {
            ODataType = null, // ADD THIS
            Role = OnlineMeetingRole.Presenter,
            Identity = new IdentitySet
            {
                Application = new Identity
                {
                    Id = Guid.NewGuid().ToString(),
                    DisplayName = "Attendee3"
                }
            }
        }
    },
        Organizer = new MeetingParticipantInfo
        {
            ODataType = null,   // ADD THIS
            Role = OnlineMeetingRole.Presenter,
            Identity = new IdentitySet
            {
                Application = new Identity
                {
                    Id = Guid.NewGuid().ToString(),
                    DisplayName = Framework.Construction.Configuration["OnlineMeeting:Organiser:DisplayName"]
                }
            }
        }
    },
    EndDateTime = DateTimeOffset.Now.AddHours(1),
    StartDateTime = DateTimeOffset.Now.AddHours(2)
};
```
Alternatively, you can try out https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6 which may resolve the issue as this preview release involves fixing issues with the default setting of the OdataType property.

**Comment by xown-dev** [comment]
@andrueastman, I appreciate your response once again. 

I've tried your suggestions. I added the ODataType property members and upgraded the Graph package to version 4 preview-6, but I still have the same error: Code: generalException\r\nMessage: An error occurred sending the request.\r\n

What else do you suggest that I should  try?

**Comment by andrueastman** [comment]
Are you able to capture a trace of the response using Fiddler? 
We can extract the client-request-id headers and see if there is more information in the api logs for the specific request.
