### ISSUE TITLE
Support IHttpClientFactory - make the use of HttpClient more resilient

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#1016]
Reference:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/591
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests 
[AB#9594](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9594)

**Comment by andrueastman** [comment]
Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/318 and work to be tracked with that issue.
