### ISSUE TITLE
How to get Sharepoint site for a group? 

### ISSUE THREAD

**Issue by jaoord** [microsoftgraph/msgraph-sdk-dotnet#1018]
According to the docs it is possible via: `GET /groups/{group-id}/sites/root` (https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http)

When I try to convert that to a sdk request I get a bad/malformed request error.

I have tried:

`graphClient.Groups[groupId].Request().Expand("Sites").GetAsync()`
and
`graphClient.Groups[groupId].Request().Expand("Sites/Root").GetAsync()`

Also, `graphClient.Groups[groupId].Sites.Request().GetAsync()` returns all sites.

And `graphClient.HttpProvider.SendAsync(new HttpRequestMessage(HttpMethod.Get, $"groups/{groupId}/sites/root"));`

returns a lot of data such as authorization headers but not the sites (it does work in graph explorer though)
 
[AB#9610](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9610)

**Comment by pschaeflein** [comment]
I recommend using Graph Explorer (https://aka.ms/ge) to help here.

Using the page you reference, use the sample URL for a group team site. Then, in the bottom panel, select the Code snippets view.

![image](https://user-images.githubusercontent.com/8008013/119828853-34935080-bec0-11eb-83b4-730fc60fa8f3.png)
