### ISSUE TITLE
ListItem's Name property is null within IListItemsCollectionPage

### ISSUE THREAD

**Issue by mohamed-azhar** [microsoftgraph/msgraph-sdk-dotnet#1019]
**Describe the bug**
I'm trying to retrieve the items within a document library and used the following code. Note that this is a c# daemon console application made in .NET 5 
```
//get site
var site = await sdkClient.Sites.GetByPath("siteRelativePath", "hostname").Request().GetAsync();

//get all lists within the site
var allLists = await sdkClient.Sites[site.Id].Lists.Request().GetAsync();

//get a random list from allLists
var list = allLists.FirstOrDefault();

//get the items within the list
var listItemCollection = await sdkClient.Sites[site.Id].Lists[list.Id].Items.Request().GetAsync();
```
The result returns a ```IListItemsCollectionPage``` which contains multiple ```ListItem``` objects as expected.
When I iterate through this collection,  I can notice that the ```Name``` property is null for all the objects

**To Reproduce**
1. Create a new .NET 5 console application
2. Register the application under App Registrations in Azure portal. Make sure to set the following ```Application``` permissions
       ```
    "User.Read",
    "User.Read.All",
    "Mail.ReadBasic.All",
    "Files.ReadWrite.All",
    "Sites.FullControl.All"
       ```
3. Get access token and try to get the list items of a SharePoint site mentioned like in the **Describe the bug** section
4. Iterate through the items contained within the result and you can notice that the ```Name``` property is null

**Expected behavior**
```Name``` property is null for each ```ListItem``` of the ```IListItemsCollectionPage``` 
[AB#9633](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9633)

**Comment by pschaeflein** [comment]
In your code, how can you be sure that the first list returned is actually a Document library?

If you wish to access files, I would recommend using the Drive resource. For a SharePoint site, this would be:

```
var children = await graphClient.Sites[site.Id].Drive.Root.Children.Request().GetAsync();
```

(If this is a site that backs a Team, then the root drive will contain only folders. So you will need to get the children of those folders if you want actual files.)

**Comment by mohamed-azhar** [comment]
```var list = allLists.FirstOrDefault();``` is actually not the exact code I'm using in the program. It was there just to show the process of selecting a list and for the sake of showing the code. In the real program I made sure that a real document library is taken.

**Comment by pschaeflein** [comment]
OK. But still, the approach for reading documents, IMO, should be the Drive/DriveItems resource.

**Comment by mohamed-azhar** [comment]
Alright. Will try with Drive/DriveItems. Thanks for the information!
