### ISSUE TITLE
[Client bug]: GraphServiceClient.Communications..PostAsync() occasionally hangs forever

### ISSUE THREAD

**Issue by jurgenrapp** [microsoftgraph/msgraph-sdk-dotnet#1020]
graphClient.Communications.GetPresencesByUserId occasionally hangs forever.

The process can work for weeks and then suddenly hang forever on this call.
.ConfigureAwait( false ); didn't help. It still hangs.

The application suddenly just stops and won't return from:
```c#
var pollResult = await graphClient.Communications
                            .GetPresencesByUserId( oidsToPoll )
                            .Request()
                            .WithUsernamePassword( config.Credential.UserName, config.Credential.SecurePassword )
                            .PostAsync()
                            .ConfigureAwait( false );
```

The Client has an overalltimeout set but that doesn't work. And I have also tried to use a CancellationToken to no avail.
```c#
IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
                                                   .Create(clientId)
                                                   .WithTenantId(tenantId)
                                                   .Build();

UsernamePasswordProvider authProvider = new UsernamePasswordProvider(publicClientApplication);
theGraphServiceClient = new GraphServiceClient( authProvider ) { HttpProvider = { OverallTimeout = TimeSpan.FromSeconds( 10 ) } };
```

**To Reproduce**
Have a process running that keeps sending GetPresencesByUserId.

**Expected behavior**
The client should return a result or throw an exception.

**Client version**
Target framework is .Net 4.7.2

Present in multiple versions:
Microsoft.Graph 4.0.0-preview.5 
Microsoft.Graph 3.33
Microsoft.Graph 3.30

**Desktop (please complete the following information):**
This is a server process running in Azure

**Additional context**
 
[AB#9653](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9653)

**Comment by andrueastman** [comment]
@jurgenrapp Thanks for opening this issue. 
Any chance you could try using this guidance to log requests to help us figure out if the issue occurs before the request is sent out or if the response never comes back?
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md

**Comment by jurgenrapp** [comment]
@andrueastman I was finally able to get new binaries into the live systems but now I have the result.

We get the response from Graph so the hang is in the post processing after the HttpClient has received the data.
We have the same issue regardless if .ConfigureAwait( false ); is set or not.

43|2021-06-23 16:43:04.6338|DEBUG| Sending Graph request
36|2021-06-23 16:43:04.7030|DEBUG| Received Graph response StatusCode=OK, 77 ms
35|2021-06-23 16:43:51.2225|DEBUG| TheGraphPresenceWatchdog: 2021-06-23 14:43:04, PollUsers
35|2021-06-23 16:48:51.2414|WARN | TheGraphPresenceWatchdog: Stuck we are: 2021-06-23 14:43:04, PollUsers

```c#
pollerState = (DateTime.UtcNow, "PollUsers");
try
{
  var pollResult = await graphClient.Communications
                                  .GetPresencesByUserId( oidsToPoll )
                                  .Request()
                                  .WithUsernamePassword( config.Credential.UserName, config.Credential.SecurePassword )
                                  .PostAsync()
                                  .ConfigureAwait( false );
...
}
catch (Exception e)
{
    logger.Debug( $"PollUsers: Well that didn't work.{Environment.NewLine}{e}");
    pollFailed = true;
}
pollerState = (DateTime.UtcNow, "PollUsers got pollResult");
```
The pollerState doesn't change to "PollUsers got pollResult" so the PostAsync does not return.


The injected log module looks like this:
```c#
logger.Debug("Sending Graph request");// log the request before it goes out.
var sw = Stopwatch.StartNew();
// Always call base.SendAsync so that the request is forwarded through the pipeline.
try
{
    response = await base.SendAsync(httpRequest, cancellationToken);
    logger.Debug($"Received Graph response StatusCode={response.StatusCode}, {sw.ElapsedMilliseconds} ms");
}
catch ( Exception e )
{
    logger.Debug($"Received Graph: {e}");
    if (response?.Content != null)
    {
        await response.Content.ReadAsByteArrayAsync();// Drain response content to free connections.
    }
    throw;
}
```

**Comment by andrueastman** [comment]
Hey @jurgenrapp ,

We've made some improvements in the [2.0.8](https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.8) release with regard to trying to mitigate this. Any chance you could try this out and give feedback whether you are still encountering this?
