### ISSUE TITLE
Can not update PlannerExternalReferenceCollection

### ISSUE THREAD

**Issue by MaSchue46** [microsoftgraph/msgraph-sdk-dotnet#1026]
I am receiving a

Microsoft.Graph.ServiceException
  HResult=0x80131500
  Nachricht = Message: The request is invalid:
A type named 'microsoft.taskServices.plannerExternalReferenceCollection' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.

by updating 

           await graphClient.Planner.Tasks[taskId].Details
                .Request()
                .Header("Prefer", "return=representation")
                .Header("If-Match", etag)
                .UpdateAsync(dt);

tried with actual nuget version and V4 also 
[AB#9670](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9670)

**Comment by andrueastman** [comment]
@MaSchue46 Thanks for raising this issue. 
Are you able to provide code sample of how you are creating the object in the `UpdateAsync` method?

**Comment by MaSchue46** [comment]
Yes, of course:

            var details = await graphClient.Planner.Tasks[nt.Id].Details
                .Request()
                .GetAsync();

            var etag = details.GetEtag();

            var dt = new PlannerTaskDetails();

            dt.PreviewType = PlannerPreviewType.Description;
            dt.Description = "Hallo";
            dt.References = new PlannerExternalReferences
            {
                AdditionalData = new Dictionary<string, object>()
                {
                    {"http%3A//developer%2Emicrosoft%2Ecom", "{\"@odata.type\":\"microsoft.graph.plannerExternalReference\",\"alias\":\"Documentation\",\"previewPriority\":\" !\",\"type\":\"Other\"}"}
                }
            };
            await graphClient.Planner.Tasks[nt.Id].Details
                .Request()
                .Header("Prefer", "return=representation")
                .Header("If-Match", etag)
                .UpdateAsync(dt);
            
if I remove the "dt.References = new PlannerExternalReferences .. " section, I am able to change dt.Description and other Properties, but included the section I receive the above exception.

**Comment by andrueastman** [comment]
@MaSchue46 Thanks for this.
Does this modification work out for you?

```cs
dt.PreviewType = PlannerPreviewType.Description;
dt.Description = "Hallo";
dt.References = new PlannerExternalReferences
{
    ODataType = null, // Add this line
    AdditionalData = new Dictionary<string, object>()
    {
        {"http%3A//developer%2Emicrosoft%2Ecom", "{\"@odata.type\":\"microsoft.graph.plannerExternalReference\",\"alias\":\"Documentation\",\"previewPriority\":\" !\",\"type\":\"Other\"}"}
    }
};
```

**Comment by andrueastman** [comment]
ping @MaSchue46

**Comment by andrueastman** [comment]
@MaSchue46 Please reopen if necessary. Closing this for now.

**Comment by MaSchue46** [comment]
@andrueastman, sorry for the late reply, 

with following code 


            var tasks = await graphClient.Planner.Plans[plnId].Tasks
                .Request().GetAsync();

            var details = await graphClient.Planner.Tasks[tasks[0].Id].Details
                .Request()
                .GetAsync();

            var etag = details.AdditionalData["@odata.etag"].ToString();

            var dt = new PlannerTaskDetails();

            dt.PreviewType = PlannerPreviewType.Description;
            dt.Description = "Hallo";
            dt.References = new PlannerExternalReferences
            {
                ODataType = null, // Add this line
                AdditionalData = new Dictionary<string, object>
                {
                    {
                        "http%3A//developer%2Emicrosoft%2Ecom",
                        "{\"@odata.type\":\"microsoft.graph.plannerExternalReference\",\"alias\":\"Documentation\",\"previewPriority\":\" !\",\"type\":\"Other\"}"
                    }
                }
            };

            await graphClient.Planner.Tasks[tasks[0].Id].Details
                .Request()
                .Header("Prefer", "return=representation")
                .Header("If-Match", etag)
                .UpdateAsync(dt);

i receive:

Microsoft.Graph.ServiceException: "Message: An open type property has an invalid type.

when I comment out the dt.Reference... lines, the update works

Any idea?

Thank you,

**Comment by MaSchue46** [comment]
I think I found a solution for me:

            dt.References = new PlannerExternalReferences();
            dt.References.ODataType = null;
            dt.References.AddReference("https://www.porsche.de", "Porsche");

works.

**Comment by andrueastman** [comment]
Thanks for the reply @MaSchue46 

I believe this should be resolved with the latest [preview](https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6) of the SDK (there should be no need to set the ODataType to null) and the following code should work for you

```cs
        dt.References = new PlannerExternalReferences();
        dt.References.AddReference("https://www.porsche.de", "Porsche");
```
