### ISSUE TITLE
Interface for phoneMethods in Identity and sign-in

### ISSUE THREAD

**Issue by isKUL** [microsoftgraph/msgraph-sdk-dotnet#1028]
Hello!
The site says that using the Microsoft Graph library, you can access the interface "authentication/phoneMethods" - [Create phoneAuthenticationMethod](https://docs.microsoft.com/en-us/graph/api/authentication-post-phonemethods?view=graph-rest-beta&tabs=csharp#request)

But using even the most recent version "4.0.0-preview.5" it is not found there [IAuthenticationRequestBuilder.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d25a1292fb64959ed9d7e9e923b3e4533f0a8ab1/src/Microsoft.Graph/Generated/requests/IAuthenticationRequestBuilder.cs)

Don't fix the documentation - please, add an interface for working with phones! :)

p.s. I really want an interface for working with "Default method (Change a user's default MFA method)", which is not yet implemented in Graph API - [The following authentication methods are not yet supported in Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta#what-authentication-methods-can-be-managed-in-microsoft-graph) 
[AB#9752](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9752)

**Comment by andrueastman** [comment]
@isKUL 
Thanks for raising this issue.
That functionality is actually available in beta end point. You will therefore need to install the beta SDK library to get that.
The correct place to look at the interface would therefore be [here](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/requests/IAuthenticationRequestBuilder.cs).
You can download the nuget packages [here](https://www.nuget.org/packages/Microsoft.Graph.Beta). 

With regards to the feature request on the API side, you can raise it through the link below. 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
