### ISSUE TITLE
Scope 'Sites.Selected' does not include read/write to selected site's lists

### ISSUE THREAD

**Issue by jennynnguyen114** [microsoftgraph/msgraph-sdk-dotnet#1034]
**Describe the bug**
My app that has been given read/write permissions to a customer's Site. My app can read and write items in the selected site's default document library, but it cannot create lists for the selected site.

**To Reproduce**
Steps to reproduce the behaviour:
1. Register an app in Azure AD with "Sites.Selected" Graph API applications, not delegated, permissions. Ensure the UX app successfully gets access token to this AD app.
2. Use UX app to get customer's tenant ID to accept this AD app and its permissions (which is the required User.Read, and added Sites.Selected).
3. Sign in on Graph Explorer under customer's tenant to grant read/write permissions to this AD app.
   e.g. POST `https://graph.microsoft.com/v1.0/sites/<site-id>/permissions`
```
{
    "roles": [
        "write"
    ],
    "grantedToIdentities": [
        {
            "application": {
                "id": "<AD app id>",
                "displayName": "Jenny limited permissions"
            }
        }
    ]
}
```
4. Use the UX app to confirm it has access to the selected site, e.g. Site object returned successfully from `await graphServiceClient.Sites[siteId].Request().GetAsync()`
6. Use the UX app to confirm it can write items to selected site's default document library, e.g. 
```
var newFolder = new Folder
{
   Name = "Test folder",
   Folder = new Folder()
}
await graphServiceClient.Sites[siteId].Drive.Items.Request().AddAsync(newFolder)
```
7. Use the UX app to create lists, e.g. 
```
var newList = new List
{
   DisplayName = "new document library",
   ListInfo = new Info
   {
       Template = "documentLibrary"
   }
};

await graphServiceClient.Sites[siteId].Lists.Request().AddAsync(newList);
```

**Expected behaviour**
A document library called "new document library" for the selected site gets created.

**Screenshots**
Actual behaviour: Access Denied error
![image](https://user-images.githubusercontent.com/995356/121990620-6756a780-cde1-11eb-849f-3235b73e5941.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 89.0
 - Microsoft.Graph.Core version: 1.24.0.0 
[AB#9908](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9908)

**Comment by andrueastman** [comment]
Hey @jennynnguyen114,
Thanks for opening the issue. 
According to the documentation [here](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=http#permissions), You will need the `Sites.Manage.All` permissions added to the app as well.

Please reopen if you need any further clarification.

**Comment by jennynnguyen114** [comment]
@andrueastman Thanks for the reply. 
We think that this doesn't make sense - the goal of `sites.selected` is giving us full control on the site (including all document libraries). This doesn't work if we need sites.manage.all to access all drives (and sites) - we are losing the functionality of grained security (available with sites.selected)
