### ISSUE TITLE
Not able to create a query for a person name with '

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoftgraph/msgraph-sdk-dotnet#1036]
**Describe the bug**
We are looking for searching an email/calendar detail of a person (Specifically a person whose name contains a single quote eg. O'Brien)

We use the MicrosoftGraph SDK on C# for Bot Framework. The query throws an error while we create it. Would you be so kind to assist us with this issue? 
[AB#8358](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8358)

**Comment by andrueastman** [comment]
@aishwaryaumachandran Are you able to provide a code sample of the request you are trying to make with the SDK?
