### ISSUE TITLE
Include "sample" snippets in the SDK

### ISSUE THREAD

**Issue by DL-LiveTiles** [microsoftgraph/msgraph-sdk-dotnet#104]
Hello,

I don't understand why the basic sample snippets are not baked into the SDK.
All the below and more should be in the SDK without the need for additional code:

- https://github.com/microsoftgraph/aspnet-snippets-sample/tree/master/Graph-ASPNET-46-Snippets/Microsoft%20Graph%20ASPNET%20Snippets/Models
- https://github.com/microsoftgraph/aspnet-connect-sample/tree/master/Microsoft%20Graph%20SDK%20ASPNET%20Connect/Microsoft%20Graph%20SDK%20ASPNET%20Connect/Models
- https://github.com/microsoftgraph/botframework-csharp-excelbot-rest-sample/tree/master/ExcelBot/Workers

Regards,

Douw

**Comment by DL-LiveTiles** [comment]
It should be as easy as this:
[Create a contact in the default Contacts folder (Client)
](https://msdn.microsoft.com/en-au/office/office365/api/contacts-rest-operations#create-contacts)

NOT the current implementation of relying on additional helpers / workers / models / services (not even the naming conventions are standard) spread over a collection of scattered samples!

**Comment by MIchaelMainer** [comment]
Hello Douw,

Thank you for providing this feedback. We appreciate you taking the time to let us know what is working and not working well for you with our libraries, documentation, and samples. We will consider your feedback in the next planning cycle. We're looking at ways to better integrate our documentation and sample snippets, especially for our client libraries. Thank you.

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer Thank you, but the intent the improve something does not resolve the issue.
This should not be closed but instead lead to an active task that we can track.

**Comment by MIchaelMainer** [comment]
@DL-LiveTiles We appreciate your insistence on this matter and agree that the intent to improve something does not resolve your concern. This repository is for .Net client library code (this is not really an SDK as it only has the client library code; neither samples, docs, nor tools are included). The issues in this repo are used to track issues with the code in this repo. I highly suggest that you open your issue about the lack of code snippets in the documentation on [Office Developer Platform UserVoice page](https://officespdev.uservoice.com/) and then provide a link to it from here. 

Do you mind if we follow up with you in the future to ask you questions about documentation and sample snippets?

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer 
Ok, will log on UserVoice.
No, happy to answer questions.
