### ISSUE TITLE
Scope 'Sites.Selected' does not include read/write to selected site's lists #

### ISSUE THREAD

**Issue by amitkub** [microsoftgraph/msgraph-sdk-dotnet#1047]
see issue 1034 - https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1034

can we please reopen the issue?

last comment which I agree with 
======================
@andrueastman Thanks for the reply. 
We think that this doesn't make sense - the goal of `sites.selected` is giving us full control on the site (including all document libraries). This doesn't work if we need sites.manage.all to access all drives (and sites) - we are losing the functionality of grained security (available with sites.selected)

_Originally posted by @jennynnguyen114 in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1034#issuecomment-864668549_ 
[AB#10019](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10019)

**Comment by andrueastman** [comment]
Hey @amitkub,
Thanks again for raising this issue. 

Unfortunately, this repository only covers the working of the client library and the managing and operation of how permissions work on the API side are beyond its scope. 

To get further clarification on the working of the API side you can create a question on the link below.
https://docs.microsoft.com/en-us/answers/products/m365

Furthermore, to give feedback/ideas on the graph you can create an idea at the link below.
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
