### ISSUE TITLE
Unable to filter app roles assignment by user's display name (equality filter)

### ISSUE THREAD

**Issue by gmantri** [microsoftgraph/msgraph-sdk-dotnet#1049]
**Describe the bug**
According to the documentation [`here`](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0#properties), I should be able to filter app roles assignment by user's display name:

>The display name of the user, group, or service principal that was granted the app role assignment. Read-only. **Supports $filter (eq and startswith)**.

However when I try to apply `eq` filter, I am getting an invalid request error.

When I run the following code:

```
        private static async Task GetAppRoleAssignments(GraphServiceClient graphServiceClient)
        {
            var request = graphServiceClient.ServicePrincipals[servicePrincipalId].AppRoleAssignedTo.Request();
            request = request.Filter($"principalDisplayName eq 'John Smith");
            var response = await request.GetAsync();
        }
```
I get this error:

```
Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Invalid filter clause
Inner error:
	AdditionalData:
	date: 2021-06-24T02:21:35
	request-id: 09454bb9-5f12-4430-badf-c90996d8b93a
	client-request-id: 09454bb9-5f12-4430-badf-c90996d8b93a
ClientRequestId: 09454bb9-5f12-4430-badf-c90996d8b93a
```

However `startsWith` filter works perfectly fine:

```
        private static async Task GetAppRoleAssignments(GraphServiceClient graphServiceClient)
        {
            var request = graphServiceClient.ServicePrincipals[servicePrincipalId].AppRoleAssignedTo.Request();
            request = request.Filter($"startsWith(principalDisplayName, 'John')");
            var response = await request.GetAsync();
        }
```

I am wondering if its a documentation issue or there's an issue with the Graph REST API itself?
 
[AB#10031](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10031)

**Comment by andrueastman** [comment]
Hey @gmantri,
It looks like you are missing a closing quotation mark in your example code.

```cs
request = request.Filter("principalDisplayName eq 'John Smith");
```
should be this

```cs
request = request.Filter("principalDisplayName eq 'John Smith'");
```
