### ISSUE TITLE
unable to find drive of group

### ISSUE THREAD

**Issue by bartdotnet** [microsoftgraph/msgraph-sdk-dotnet#105]
- goal: obtain the drive of a Office 365 Group:

[](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_get)

Get the document library assocaited with a group
To access a Group's default document library, your app requests the drive relationship on the Group.
HTTP request
GET /groups/{idOrUserPrincipalName}/drive

- example code extract

```
dynamic groupPage = await graphserviceClient
.                      .Groups
.                      .Request()
.                      .Filter("groupTypes/any(c:c+eq+'Unified')")
.                      .Select("id,displayName,drive")
.                      //.Expand("drive")
.                      .GetAsync();
. 
. foreach (dynamic page in groupPage) {
.     Console.WriteLine(string.Format("Id: {0}, Name: {1}, Drive: {2}", page.Id, page.DisplayName, page.Drive ) );
. }
```

Id: c9what-cb9e-4270-bb88-beblabla67, Name: Microsoft Weekly Roundup, Drive:

```
> dynamic groupPage = await graphserviceClient
.                      .Groups
.                      //.Expand(Drive)
.                      .Request()
.                      .Filter("id eq 'c9what-cb9e-4270-bb88-beblabla67'")
.                      //.Select("id,displayName,drive")
.                      .Expand("drive")
.                      .GetAsync();
```
Exception of type 'Microsoft.Graph.ServiceException' was thrown.
```
> dynamic groupPage = await graphserviceClient
.                      .Groups
.                      //.Expand(Drive)
.                      .Request()
.                      .Filter("id eq 'c9what-cb9e-4270-bb88-beblabla67'")
.                      //.Select("id,displayName,drive")
.                      .Expand("drives")
.                      .GetAsync();
```

- observation

1. did not manage to get relation via property
2. did not manage to get relation via expand
3. not very verbose error "Exception of type 'Microsoft.Graph.ServiceException' was thrown."

- Question: 

1. is it possible to navigate through relationships?
2. is it possible to get the drive of an office 365 group?
3. do you have a code sample if it is possible or is this a bug or not yet implemented?

- note:
1. connected using client_credentials
2. library info via paket.lock file [paket.lock.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/922013/paket.lock.txt)
3. paket dependencies:

nuget Microsoft.Graph.Core 1.3.0.0
nuget System.Net.Http
nuget Microsoft.Graph

Thanks in advance,
Bart

**Comment by cbales** [comment]
Hi Bart,
Unfortunately, most of the Groups API is accessible only through delegated permissions and cannot be accessed via client credential flow. This is documented [here](https://developer.microsoft.com/en-us/graph/docs/overview/release_notes), but I am going to make a PR to the docs team to include this on the Groups doc as well. There are several other scenarios that do not yet support this flow. As for the vague error message, we are looking at providing more in-depth error messages soon since I realize they aren't very helpful in their current state! You should be able to see the response error coming back through the innerException at least.

**Comment by bartdotnet** [comment]
Hi,

Thank you for your quick reply and referral.

A compatibility matrix would help being more productive. Figuring this all out is a bit stressful, time and resource consuming.

The mix of authentication methods, old-, new portal, application registration page,  old and new (oauth2) endpoints, proliferation of old and new examples, examples not being linked to each other as a kind of (potentially evolving) best practice makes consuming the Microsoft Graph harder than it actually is.

I managed to get the desired result wrapping the HTTPS requests myself (based on code similar to MakeHttpRequest in https://github.com/mattleib/o365api-as-apponly-webapp ) as a workaround for the time being but would have preferred to use the SDK instead. 

I did manage to use the SDK with the client_credential workflow for parts of the scenario I was trying to implement. The SDK does not implement Graph traversal (example: from Office 365 Group to its associated Drive). I assume it does not work via the authorization_code workflow as well.

It would be nice to have a wrapper like the SDK for all existing Graph functionality avoiding lots of re-coding. The fact that the SDK is generated based on $metadata makes this particularly attractive. Please invest in this area as well.

**Comment by cbales** [comment]
This is great feedback. I will pass along your suggestions to our docs team to improve the experience in that area.
@MIchaelMainer can add some more information about the Graph traversal issue you were seeing.

**Comment by MIchaelMainer** [comment]
Thank you @bartdotnet for your feedback. If you don't mind, can you show us the URL calls that you want to make but that aren't generated for, and implemented, in the client library?

**Comment by bartdotnet** [comment]
Hi Michael,

- Please find below URL and documentation extract stating how to obtain the Drive associated with a Office 365 Groep via HTTP. This works via HTTP but not the SDK.

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_get

> Get the document library assocaited with a group
> To access a Group's default document library, your app requests the drive relationship on the Group.
> HTTP request
> GET /groups/{idOrUserPrincipalName}/drive

- Please note that both using a token obtained via both authorization_code or client_credentials the Drive Property is null. 

```
dynamic groupPage = await graphserviceClient
                     .Groups
                     .Request()
                     .Filter("groupTypes/any(c:c+eq+'Unified')")
                     .Select("id,displayName,drive")
                     //.Expand("drive")
                     .GetAsync();

foreach (dynamic page in groupPage)
{
    Console.WriteLine(string.Format("Id: {0}, Name: {1}, Drive: {2}", page.Id, page.DisplayName, page.Drive));
}
```

- my goal is to obtain to either figure a neat way to get the 

> * Office 365 Group 
> * then the Drive 
> * then the Drive Root
> * the Drive Items

I did not see a way to get the Drive associated with an Office 365 Group via the SDK

Maybe I overlooked it and I would be grateful if you would like to share how it can be done.

If the SDK does not allow to obtain this relationship, please put it on the agenda.

Please find enclosed a picture of the privileges granted in the application registration portal; https://apps.dev.microsoft.com (Text is in Dutch so here is a translation: Gedelegeerde Machtigingen = Delegated Privileges; Toepassingsmachtigingen   = Application Privileges)

The application is a (Dutch: Geconvergeerde toepassing ) (English: Converged Application) not an Azure AD only Application.

![privileges](https://cloud.githubusercontent.com/assets/27493449/25154413/d693c1ea-2490-11e7-932e-771e07bb808c.png)

**Comment by MIchaelMainer** [comment]
@bartdotnet Thank you for the thorough information! Happy to help! You can make the GET /groups/{id}/drive call with the client library.

```c#
// Get all unified groups in the organization.
// GET /v1.0/groups?$filter=groupTypes/any(c:c+eq+'Unified')
var groupPages = await graphClient.Groups
                                  .Request()
                                  .Filter("groupTypes/any(c:c+eq+'Unified')")
                                  .GetAsync();

// Get the drive items from root on the first group in groupPages.
// GET /v1.0/groups/a2d648bd-3a1d-49f4-88a0-8d728321d42a/drive/root/children
var driveItemsPage = await graphClient.Groups[groupPages[0].Id]
                                      .Drive
                                      .Root
                                      .Children
                                      .Request()
                                      .GetAsync();
```
One that last call, you can break it up to get information about the drive, and the root.

```c#
// I didn't test these but I'm 95% confident that they'll work.
var drive = await graphClient.Groups[groupPages[0].Id]
                                      .Drive
                                      .Request()
                                      .GetAsync();

var driveRoot = await graphClient.Groups[groupPages[0].Id]
                                      .Drive
                                      .Root
                                      .Request()
                                      .GetAsync();

```
Let us know whether this solves your scenario.

**Comment by bartdotnet** [comment]
Hi Michael,

This is the awesome stuff I was looking for 👍 

Thanks for these great examples, you put me back on track with these and solved many troubles I had.

I didn't see a lot of this power in the examples regarding collections and am not an expert C# coder yet allowing me to distill this from the source code. I suggest adding them in the examples regarding collections.

Many thanks,

Regards,

Bart,

**Comment by MIchaelMainer** [comment]
Thank you for the feedback. I'm glad I was able to help.
