### ISSUE TITLE
Uploading files > 2GB with ChunkedUploadProvider fails

### ISSUE THREAD

**Issue by wbreza** [microsoftgraph/msgraph-sdk-dotnet#106]
When calling `chunkedUploadProvider.GetUploadChunkRequests()` with a stream greater than 2GB (Int32.MaxValue), the returned `UploadChunkRequest` object have invalid ranges and cannot be used.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. We'll take a look at this and see if we can get in a fix with our next update.
