### ISSUE TITLE
ChatMessageMentionedIdentitySet missing

### ISSUE THREAD

**Issue by iot-dev01** [microsoftgraph/msgraph-sdk-dotnet#1065]
**Describe the bug**
The ChatMessageMentionedIdentitySet Class is not existing in SDK Version 3.35.0
If you check the docs for mentions at 

https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=csharp 

Microsoft recommend to use the ChatMessageMentionedIdentitySet class.

**To Reproduce**
Try using the sample code in a c# application.

**Expected behavior**
Possibility to use the GraphServiceClient to send a teams message with mentions.

**Desktop (please complete the following information):**
 - OS: Windows
 
[AB#10263](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10263)

**Comment by andrueastman** [comment]
Hey @iot-dev01,

Thanks for raising this issue. 

The [`ChatMessageMentionedIdentitySet`](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/model/ChatMessageMentionedIdentitySet.cs) is a new type introduced and should now be available through 4.x.x versions of the sdk. You can view the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4.0.0/docs/upgrade-to-v4.md)
