### ISSUE TITLE
Please add change log to this repository

### ISSUE THREAD

**Issue by gmantri** [microsoftgraph/msgraph-sdk-dotnet#1066]
**Is your feature request related to a problem? Please describe.**
Currently the repository is missing change log (or I am not able to find it). Whenever a new version of the SDK is released, it is not clear what new features are we getting and what bugs are fixed. As Forrest Gump would say, currently the update process is like a "box of chocolates, you don't know what you're getting" :).

**Describe the solution you'd like**
A changelog.md file with a description of all the new features and bug fixes in reverse chronological order (i.e. latest release is always on top). Please see [`this`](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md) for example.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
I noticed that SDKs for some other languages have a change log ([`msgraph-sdk-javascript`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/CHANGELOG.md), for example) however they have not been updated in quite some time. It would be really great if same practice can be followed across all SDKs.
 
[AB#10276](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10276)

**Comment by maisarissi** [comment]
Hi @gmantri ,
Thanks for reaching out and thanks for the feedback.
Right now, we do keep [release notes](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases) for all the Microsoft Graph SDKs and those are built using [this Azure DevOps task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) which by default takes the changelog and adds it as release notes.

As a note, bugfixes are listed, see [this release as an example](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/4.12.0), as long as the information is clearly indicated in the commit message.

The [API changelog](https://developer.microsoft.com/en-us/graph/changelog) is the central place to see additions and deprecations to the API. This repo is home to the generated service library that should track the API updates automatically. There should be almost no additional information in these release notes. The [core library](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/releases) is where you should expect to find release notes with the details of bugfixes and enhancements to the SDK.

**Comment by maisarissi** [comment]
We could standardize on [keep a changelog](https://keepachangelog.com/en/1.0.0/) as there's ton of tooling to write the release notes automatically from it, and it keeps a linear changelog anyone can refer to. See the examples on [java releases](https://github.com/microsoftgraph/msgraph-sdk-java/releases/tag/v5.22.0) that gets its information from [changelog](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/CHANGELOG.md#5220---2022-04-28). This is also how the [JavaScript SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/CHANGELOG.md) does, as you mentioned before.

The benefit of doing that (beside a standard open source approach that's familiar to a lot of people out there) is that the dependabot PRs (or other dependency management tooling) could extract the release notes when updating things. See the difference between [a PR that provides a standard changelog](https://github.com/microsoft/kiota/pull/515) and [one that doesn't](https://github.com/microsoftgraph/java-spring-webhooks-sample/pull/172).

@andrueastman this is something we should think about.

**Comment by maisarissi** [comment]
Hey @andrueastman . I decided to reopen the issue as I really think it's a good idea to have the keep a changelog here as I mentioned in the comment above.
Thoughts?

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1474
