### ISSUE TITLE
Error: an existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Loppone** [microsoftgraph/msgraph-sdk-dotnet#1069]
**Describe the bug**
I have problems when I try to connect with GraphServiceClient.
In local machine all works correctly, when I deploy on a server (not load balanced or on VM) i receive this error:

    an existing connection was forcibly closed by the remote host 

The job is built with .Net Framework 4.8

**To Reproduce**
The configuration code is:

            IConfidentialClientApplication app;
            var authority = String.Format(CultureInfo.InvariantCulture, _instance, _tenant);

            app = ConfidentialClientApplicationBuilder.Create(_clientId)
                .WithClientSecret(_clientSecret)
                .WithAuthority(new Uri(authority))
                .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(app);
            string[] scopes = new string[] { _clientSecret };

            var _graphClient = new GraphServiceClient(authProvider);

**Client version**
3.35.0

**Desktop (please complete the following information):**
Windows Server 2019 Standard
 
[AB#10324](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10324)

**Comment by andrueastman** [comment]
Thanks for raising this @Loppone.
Are you able to provide more information about the server environment? 
When you deploy the same application that does the simple request as below, does it work out for you?

```cs
HttpClient client = new HttpClient();
HttpResponseMessage response = await client.GetAsync("https://github.com/microsoftgraph/msgraph-sdk-dotnet"); //Call any valid url here.
if (response.IsSuccessStatusCode)
{
    var responseString = await response.Content.ReadAsStringAsync();
}
```

**Comment by Loppone** [comment]
We have finally found the issue. It was due to some restriction on the host. 
The server admin have enabled the microsoft online url and It starts to work.
