### ISSUE TITLE
Excel chart image request url generated incorrectly

### ISSUE THREAD

**Issue by DL-LiveTiles** [microsoftgraph/msgraph-sdk-dotnet#107]
Hello,
I am able to get the Excel charts, but when I try to get an image using:
`await ServiceClient.Me.Drive.Items[_workbookId].Workbook.Worksheets[_worksheetId].Charts[name].Image(400).Request(sessionOptions).GetAsync()`

I get the following error:
"The type 'microsoft.graph.image' specified in the URI is neither a base type nor a sub-type of the previously-specified type 'microsoft.graph.workbookChart'."

After debugging I found the request url is generated incorrectly:
https://graph.microsoft.com:443/v1.0/me/drive/items/.../workbook/worksheets.../charts/.../microsoft.graph.image(width=400)

**microsoft.graph.image** should be 'image' instead.

Regards,
Douw

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention.  This is the first scenario where we've seen an error caused when using the fully qualified name for an OData function. I believe that this is a service issue. I'll provide more information later.

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer Do you have an update on this issue? Thank you

**Comment by MIchaelMainer** [comment]
@DL-LiveTiles I don't have an update yet. I'll get back to you when I get an update on this.

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer This has not been fixed in the latest version (1.3.0). When can we expect a fix?

**Comment by DL-LiveTiles** [comment]
Same issue with microsoft.graph.range

**Comment by MIchaelMainer** [comment]
@DL-LiveTiles By the way, watched the Live Tiles video. Very cool product suite! The video back sound track was solid too.  

Anyways, whenever you face an issue where the generated client library doesn't produce the correct the URL or payload, you can still make use of the client library for access token injection and serialization of the payloads. Serialization isn't needed for this scenario. If it was, you'd use the GraphServiceClient.HttpProvider.Serializer to get objects. Anyways, here's how I'd make the call as a workaround:

```csharp

// Get the table range.
var tableRange = await graphClient.Me.Drive.Items[excelFileId]
                                            .Workbook
                                            .Tables["CreateChartFromTable"] // Set in excelTestResource.xlsx
                                            .Range()
                                            .Request()
                                            .GetAsync();

// Create a chart based on the table range.
var workbookChart = await graphClient.Me.Drive.Items[excelFileId]
                                                .Workbook
                                                .Worksheets["CreateChartFromTable"] // Set in excelTestResource.xlsx
                                                .Charts
                                                .Add("ColumnStacked", "Auto", tableRange.Address)
                                                .Request()
                                                .PostAsync();

// Sometimes the creation of the chart takes too long and the new chart resource isn't accessible.
await Task.Delay(1000);

// Workaround since the metadata description isn't correct as it states it returns a string and not the 
// actual JSON object, and since the service doesn't accept the fully qualified name that the client emits
// even though it should accept the FQN.
string chartResourceUrl = graphClient.Me.Drive.Items[excelFileId]
                                        .Workbook
                                        .Worksheets["CreateChartFromTable"] // Set in excelTestResource.xlsx
                                        .Charts[workbookChart.Name]
                                        .Request()
                                        .RequestUrl;

string urlToGetImageFromChart = String.Format("{0}/{1}", chartResourceUrl, "image(width=400)");

HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Get, urlToGetImageFromChart);

// Authenticate (add access token) our HttpRequestMessage
await graphClient.AuthenticationProvider.AuthenticateRequestAsync(hrm);

// Send the request and get the response.
HttpResponseMessage response = await graphClient.HttpProvider.SendAsync(hrm);

// Get the JsonObject page that we created.
if (response.IsSuccessStatusCode)
{
    string content = await response.Content.ReadAsStringAsync();

    JObject imageObject = JObject.Parse(content);
    JToken obj = imageObject.GetValue("value"); 
    // Now you have an object that contains the image contents.
}

```

By the way, this is still just a workaround and I'm hoping to see a service fix to make this workaround obsolete. Will this workaround solve the issue for you?

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer :) cool.
The workaround should do the trick for now, thanks.

**Comment by MIchaelMainer** [comment]
Excellent.
