### ISSUE TITLE
Support Graph BETA models and methods

### ISSUE THREAD

**Issue by DL-LiveTiles** [microsoftgraph/msgraph-sdk-dotnet#108]
Specifically looking for Planner and OneNote support.

**Comment by MIchaelMainer** [comment]
Thank you for creating this ask for Beta client support. While this is not currently in our plans, I'm going to keep this open so that we can hear other requests for this. 

I do have a question: would it ever be useful for you to have just the Beta models and not the beta request builder methods?

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer No, I don't think so, we need both the models and methods.

**Comment by DL-LiveTiles** [comment]
@MIchaelMainer Where can we get the  Swagger JSON spec to generate our own SDK?

**Comment by BenjaBobs** [comment]
I too would like Beta Client support. I'm currently using a self-generated SDK, but I'd much prefer to use the nuget package to get updates.

**Comment by MIchaelMainer** [comment]
@DL-LiveTiles We don't produce a Swagger spec at this point. It is something we've discussed. I suggest that you both open a request on [Office User Voice](https://officespdev.uservoice.com/) and link to it from your post on this thread.

**Comment by christophwille** [comment]
Definitely also would like to have a regular drop for the beta endpoint (myget? or even via semver officially on nuget)

**Comment by tonipohl** [comment]
A NuGet package for the /beta endpoint would help and simplify things a LOT!

**Comment by MIchaelMainer** [comment]
Keep this feedback rolling. Thank you community! One of the challenges with providing a beta library is that the beta endpoint metadata frequently changes. This means that at any point, we may need to update the generation templates and/or tools (see [generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator) and [VIPR](https://github.com/microsoft/vipr). In parallel, changes are being added to the v1.0 endpoint so we are focused on trying keep the client library up to date with the production endpoint. We aren't ready to take on beta client generation at this point.  I'd like to gauge your interest in if we provided guidance on how to effectively use the generation tools, debug/update the templates, and provided tools to prep and validate the beta metadata, would you be willing to run the generator against beta metadata and address the generation issues?

**Comment by christophwille** [comment]
Having a "build me a client library from the current endpoint" script would get me far enough (and including pointers for debugging et al like you mentioned would be beneficial for my using the library as well as providing good error reports if necessary).

**Comment by BenjaBobs** [comment]
@MIchaelMainer If nuget packages isn't feasible, I would very much like extra documentation on generating. I managed to generate a new SDK with beta functionality, but it took me a whole day to figure out, and I'm not sure I got everything right. The main obstacle for me IIRC was the XML config file. Do note that this was my first time using templates and generators, so more seasoned developers may have an easier time, but I certainly would love more documentation or a finished package with a build script.

**Comment by imaksikkar** [comment]
+1 to the request for beta client support. Has the beta endpoint metadata stabilized enough at this point that support would be feasible?

**Comment by christophwille** [comment]
Given the major presence at Ignite and number of additions (1.0 and especially /beta) - any news on either of the two options? (more automation for hand-crafting a custom dll for /beta or even build automation)

**Comment by MIchaelMainer** [comment]
We published a new package for v1.0: https://www.nuget.org/packages/Microsoft.Graph.

Regarding a beta Nuget package. I'd like to see us publish one. I'll make sure that we have this in a backlog.

**Comment by mrfatgoat** [comment]
+1, support for the beta endpoint would help a lot. Thanks!

**Comment by MIchaelMainer** [comment]
Hey folks, I wrote up a workflow for adding beta models to an existing Microsoft Graph v1.0 client application. 

https://github.com/MIchaelMainer/msgraph-sdk-dotnet-beta

Let me know if this is useful to you.

**Comment by andrewleader** [comment]
Building the beta models ourselves is a pain. I need to be able to simply install the beta NuGet package and use it.

**Comment by Zieg** [comment]
Thumbs up for beta support.
The API is in beta for quite a while. I assume it absolutely needs to move to prod with full support from official .NET clients.

**Comment by christophwille** [comment]
Actually there has been one for quite some time, you might have missed it: https://www.nuget.org/packages/Microsoft.Graph.Beta/

**Comment by Zieg** [comment]
Thanks a lot!
I think I have completely missed it, indeed
