### ISSUE TITLE
[Client bug]: .WithUsernamePassword not working in 4.0

### ISSUE THREAD

**Issue by jurgenrapp** [microsoftgraph/msgraph-sdk-dotnet#1083]
After upgrading to Microsoft.Graph 4.0.0 .WithUsernamePassword requests seems to be broken. Reverting to preview 7 solves the problem.

We would be much happier if we could use an Application but the GetPresencesByUserId only supports a "service account".
https://docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&tabs=http

```c#
var pollResult = await graphClient.Communications
                                                  .GetPresencesByUserId( oidsToPoll )
                                                  .Request()
                                                  .WithUsernamePassword( config.Credential.UserName, config.Credential.SecurePassword )
                                                  .PostAsync()
                                                  .ConfigureAwait( false );
```

Throws:
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Graph.Auth.BaseRequestExtensions.WithUsernamePassword[T](T baseRequest, String email, SecureString password)

```c#
    IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
                                                       .Create(clientId)
                                                       .WithTenantId(tenantId)
                                                       .Build();
  
    UsernamePasswordProvider authProvider = new UsernamePasswordProvider(publicClientApplication);
```
 
[AB#10450](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10450)

**Comment by andrueastman** [comment]
Hey @jurgenrapp,

Thanks for raising this issue with us.

For version 4 we encourage users to use TokenCredentials from [Azure.Identity](https://www.nuget.org/packages/Azure.Identity) rather than the Microsoft.Graph.Auth Library as it is no longer receiving updates/support and won't be moving to a major release. 

In this scenario then you could use the `UsernamePasswordCredential` with the example outlined [here](UsernamePasswordCredential). Other TokenCredentials samples are outlined there too.

```cs
string[] scopes = {"User.Read"};

UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredential("username@domain.com", "password", tenantId, clientId);

GraphServiceClient graphClient = new GraphServiceClient(usernamePasswordCredential, scopes); // you can pass the TokenCredential directly to the GraphServiceClient

var pollResult = await graphClient.Communications
                                                  .GetPresencesByUserId( oidsToPoll )
                                                  .Request()
                                                  .PostAsync()
                                                  .ConfigureAwait( false );
```
