### ISSUE TITLE
Unable to filter an Excel table in a WPF app using the Code snippet from Graph explorer, but it works in Graph explorer itself

### ISSUE THREAD

**Issue by gidrokolbaska** [microsoftgraph/msgraph-sdk-dotnet#1086]
The following works:
Request: https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}/workbook/tables/1/columns/9/filter/apply
Body:
```
{
    "criteria": {
        "filterOn": "Custom",
        "criterion1": "=Active"
    }
}
```
The following doesn't:
```csharp
 WorkbookFilterCriteria criteria = new()
            {
                
                FilterOn = "Custom",
                Criterion1 = "=Active"

            };

            await graphClient.Sites["site-id"].Drive.Items["item-id"].Workbook.Tables["table-name"].Columns["column-name"].Filter
                .Apply(criteria)
                .Request()
                .PostAsync();
```
I get an Microsoft.Graph.ServiceException saying that arguments were not correct
Bug or I'm just doing something wrong? 
[AB#10478](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10478)

**Comment by andrueastman** [comment]
Hey @gidrokolbaska. 

Thanks for raising this issue. Are you able to provide more information about the version of the SDK you are using?

**Comment by gidrokolbaska** [comment]
> Hey @gidrokolbaska.
> 
> Thanks for raising this issue. Are you able to provide more information about the version of the SDK you are using?

Hello! If you are referring to version of the NuGet package then I use beta 4.2.0
![image](https://user-images.githubusercontent.com/54116985/128017269-87f4b2d3-229a-4b8a-90c4-2ea69005c1be.png)

**Comment by andrueastman** [comment]
The beta package is ideally used for the beta endpoint. And therefore, the request URL would change from 
`https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}/workbook/tables/1/columns/9/filter/apply`
to 
`https://graph.microsoft.com/beta/sites/{site-id}/drive/items/{item-id}/workbook/tables/1/columns/9/filter/apply`

If you do indeed want to use the V1 endpoint. You would need to get the [`Microsoft.Graph`](https://www.nuget.org/packages/Microsoft.Graph/4.0.0) package.

Is it your intention to call the beta api or the V1.0 api?

**Comment by gidrokolbaska** [comment]
> The beta package is ideally used for the beta endpoint. And therefore, the request URL would change from
> `https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{item-id}/workbook/tables/1/columns/9/filter/apply`
> to
> `https://graph.microsoft.com/beta/sites/{site-id}/drive/items/{item-id}/workbook/tables/1/columns/9/filter/apply`
> 
> If you do indeed want to use the V1 endpoint. You would need to get the [`Microsoft.Graph`](https://www.nuget.org/packages/Microsoft.Graph/4.0.0) package.
> 
> Is it your intention to call the beta api or the V1.0 api?

I don't remember why I actually installed the beta package but I'm sure I need the beta one instead of a stable one. Anyway, everything is working after I've updated to the latest 4.6.0 version. So it was actually a bug.
