### ISSUE TITLE
Updating Win32Lob Application rules during republish‎

### ISSUE THREAD

**Issue by SangameshGouriFlexera** [microsoftgraph/msgraph-sdk-dotnet#1091]
Updating the rules is not working from Graph SDK.
Use case :
1. If i have 6 rules while creating Win32Lob Application out of which 2 are detection rules and 4 are requirement rules.
2. Again during Win32Lob Application update i will delete 2 requirement rules and 1 detection rules and add couple of new requirement rules and detection rules. Win32Lob application is not updated with these rules in Intune.
Note: Same scenario is working for return codes. Let's say i have 5 return codes during create and  i am keeping only one return code previous five are deleted and new one is added in Intune GUI for that application after update.

Is it supported from the Graph SDK. Please let me know if i am doing something here. 
[AB#10569](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10569)

**Comment by andrueastman** [comment]
Hey @SangameshGouriFlexera,

Thanks for raising this issue. 

Any chance you could provide more information as to how you are trying to make the requests and the response information?
Are you also able to achieve the desired operations using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)?

**Comment by SangameshGouriFlexera** [comment]
Hi @andrueastman ,

Thanks for the quick reply. I am trying the update request using Microsoft Graph Client Library version 3.19.0.0. I am trying to update rules of the Win32LobApp class.

**Comment by andrueastman** [comment]
Hey @SangameshGouriFlexera,

Are you able to try the same using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) and confirm if you receive similar results? Also share example request and response information.

This will help us understand if this is an issue with the client library or an issue with the API itself.

**Comment by SangameshGouriFlexera** [comment]
Sure  @andrueastman i will try using graph explorer and let you know the results.

**Comment by SangameshGouriFlexera** [comment]
I am still checking from the Graph Explorer about update request.

**Comment by SangameshGouriFlexera** [comment]
@andrueastman  I have tried run the Patch request from Graph explorer with below json body . It is throwing error,

{
    "@odata.type": "#microsoft.graph.win32LobApp",
    "displayName": "Display Name value",
    "description": "Description value",
    "publisher": "Publisher value",
    "largeIcon": null,
    "isFeatured": true,
    "privacyInformationUrl": "https://example.com/privacyInformationUrl/",
    "informationUrl": "https://example.com/informationUrl/",
    "owner": "Owner value",
    "developer": "Developer value",
    "notes": "Notes value",
    "size": 4,
    "installCommandLine": "Install Command Line value",
    "uninstallCommandLine": "Uninstall Command Line value",
    "applicableArchitectures": "x64",
    "minimumFreeDiskSpaceInMB": 8,
    "minimumMemoryInMB": 1,
    "minimumNumberOfProcessors": 9,
    "minimumCpuSpeedInMHz": 4,
    "rules": [
        {
            "@odata.type": "microsoft.graph.win32LobAppRegistryRule",
            "ruleType": "requirement",
            "check32BitOn64System": true,
            "keyPath": "C:",
            "valueName": "test",
            "operationType": "exists",
        }
    ],
    "installExperience": {
        "@odata.type": "microsoft.graph.win32LobAppInstallExperience",
        "runAsAccount": "user",
        "deviceRestartBehavior": "allow"
    },
    "returnCodes": [
        {
            "@odata.type": "microsoft.graph.win32LobAppReturnCode",
            "returnCode": 10,
            "type": "success"
        }
    ],
    "setupFilePath": "null",
    "minimumSupportedWindowsRelease": "1607"
}

**{
    "error": {
        "code": "BadRequest",
        "message": "{  \"_version\": 3,  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 50c5b850-bf11-bdb5-6770-863345ead465 - Url: https://fef.amsua0102.manage.microsoft.com/AppLifecycle_2108/StatelessAppMetadataFEService/deviceAppManagement/mobileApps%28%272646605a-14e2-4a61-a72b-c7586416eb71%27%29?api-version=2020-08-04\",  \"CustomApiErrorPhrase\": \"\",  \"RetryAfter\": null,  \"ErrorSourceService\": \"\",  \"HttpHeaders\": \"{}\"}",
        "innerError": {
            "date": "2021-08-18T07:13:00",
            "request-id": "e9780bb1-7396-4731-a641-9b53c76dc9e8",
            "client-request-id": "50c5b850-bf11-bdb5-6770-863345ead465"
        }
    }
}**

**Comment by andrueastman** [comment]
Hey @SangameshGouriFlexera,

Thanks for the extra information! 
Since it seems that we need more API info on this, I have forwarded the request to get more information about this from the relevant API owners at the link below. (You can follow the issue there and you can always add more details there as well).

https://docs.microsoft.com/en-us/answers/questions/518493/unable-to-update-win32lob-application-rules-during.html

For now, I will close this issue so that we may follow things there and if need be, we will re-open it, if need be, because of a client library related issue.
