### ISSUE TITLE
Error getting user by upn

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-dotnet#1101]
Trying to get user by UPN which has special characters, 
```csharp
var upn = "abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''#-_!^~@xpto.onmicrosoft.com"
var user = await Client.Users[upn].Request().GetAsync()
```

the error below is thrown:

`"Code: Request_ResourceNotFound\r\nMessage: Resource 'abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''' does not exist or one of its queried reference-property objects are not present.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2021-08-12T19:42:37\r\n\trequest-id: a5ec18cb-3b85-4641-85e2-963166ad1f8b\r\n\tclient-request-id: a5ec18cb-3b85-4641-85e2-963166ad1f8b\r\nClientRequestId: a5ec18cb-3b85-4641-85e2-963166ad1f8b\r\n"`

Using Graph Explorer, it's possible to retrieve the user with no errors:

https://graph.microsoft.com/v1.0/users/abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''#-_!^~@xpto.onmicrosoft.com

By encoding the pound character:
```csharp
userId = "abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''%23%-_!^~@xpto.onmicrosoft.com";
var users = await Client.Users[userId].Request().GetAsync();
```

I'm still getting an error:
`System.AggregateException: One or more errors occurred. ---> Microsoft.Graph.ServiceException: Code: Request_BadRequest
Message: Bad request. Please fix the request before retrying.`

**Expected behavior**
It's expected to successfully retrieve the user through the SDK 

**Client version**
Microsoft.Graph version 3.28.0.0
Microsoft.Graph.Core version 1.25.0.0

**Additional context**
It works through httpclient:

```csharp
userId = "abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''%23%-_!^~@xpto.onmicrosoft.com";
var graphUrl = $"https://graph.microsoft.com/v1.0/users/{userId}";
using (var httpClient = new HttpClient())
{
        httpClient.DefaultRequestHeaders.Authorization = await TokenProvider.GetAuthenticationHeaderAsync(CancellationToken.None);
    using (var response = await httpClient.GetAsync(graphUrl))
    {
        if (response.StatusCode == HttpStatusCode.NotFound)
        {
          return true;
        }
    }
}
```
 
[AB#10669](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10669)

**Comment by andrueastman** [comment]
When encoding the # becomes %23 not %23%. Fixing this makes the call work.

This can also be resolved with
```cs
var upn = "abcdefhijklnopqrstuwxyz.ABCDEGHIJKLMNOPQRSTVW0123456789'''#-_!^~@M365x638680.onmicrosoft.com";
var user = await graphServiceClient.Users[WebUtility.UrlEncode(upn)].Request().GetAsync();
```

Closing for now as this tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/539
