### ISSUE TITLE
[Client bug]: graphClient.Groups[group.Id].Members[user.Id].Request().DeleteAsync() deletes the user entirely

### ISSUE THREAD

**Issue by robertjf** [microsoftgraph/msgraph-sdk-dotnet#1106]
**Describe the bug**
According to the documentation, to remove a user from a group we should do something like this:

```
await graphClient.Groups[group.Id].Members[user.Id].Request().DeleteAsync();
```
which should equate to this:

```
DELETE /groups/<groupId>/members/<memberId>/$ref
```

However this seems to be deleting the user entirely.

**To Reproduce**
1. Use the above command to remove a user from a group
2. Verify that the user still exists in the Azure AD User Directory and has been removed from the group.

**Expected behavior**
The user still exists but has been removed from the group.

**Client version**

* Microsoft.Graph  Version=4.2.0
* Microsoft.Graph.Auth  Version=1.0.0-preview.7
* Microsoft.Graph.Core Version=2.0.2

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser N/A - Console App in dotnet 5
 
[AB#10763](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10763)

**Comment by andrueastman** [comment]
Hey @robertjf,
Thanks for raising this. 

According to the documentation the snippet example provided is actually this. Your examples is missing the `Reference` segment.
https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=csharp#request

```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.Groups["{group-id}"].Members["{directoryObject-id}"].Reference
	.Request()
	.DeleteAsync();
```

Please feel free to re-open if this doesn't resolve the issue.
