### ISSUE TITLE
GraphServiceClient instance throws an exception if the user has no photo on its profile picture

### ISSUE THREAD

**Issue by MarcoEnxuto** [microsoftgraph/msgraph-sdk-dotnet#1110]
If a user has its Microsoft Account without picture profile, the GraphServiceClient throws an execption indicating "Object reference not set to an instance of an object".
It shouldn't throw that error. Instead, it should return null.

**To reproduce**

1. Configure a new MSA account without a picture or remove the current one you're using
2. Run the following code `var photo= await graphServiceClient.Me.Photo.Content.Request().GetAsync();`
3. Throws exception

**Expected behavior**
It shouldn't throw that error. Instead, it should return null.

**Current workaround** 
Apply a Try Catch, to catch that exception type around this line of code.

**Desktop**
 - OS: Windows 10
 - Version 1.21.

 
[AB#10784](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10784)

**Comment by andrueastman** [comment]
Hey @MarcoEnxuto,

Thanks for raising this issue. Are you able to provide more information on the sdk version you are using?

**Comment by MarcoEnxuto** [comment]
Hi @andrueastman, i already provided. 1.21 and i cannot update to a more recent version now. Later i will. Please check if this happens with the latest version too. Thanks for asking details.

**Comment by andrueastman** [comment]
Thanks for the info. I believe this was resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/164

You would need to upgrade to at least version 1.23.0 of the core library and confirm if the issue replicates.

**Comment by MarcoEnxuto** [comment]
Alright, now it works. I didn't know i had to get Microsoft.Graph.Core, since Microsoft.Graph gets the previous library. But it seems, gets only the 1.21.
Anyway, you should update the enum [GraphErrorCode ]([https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Enums/GraphErrorCode.cs](url))with the following, value ImageNotFound. It's not included there.

Also, docs do not have it.
[https://docs.microsoft.com/en-us/graph/errors](url)

Sorry for being too boring.. 🙂
