### ISSUE TITLE
Creation checklist is not ordered properly in planner tasks

### ISSUE THREAD

**Issue by UmamaheshwariGolla** [microsoftgraph/msgraph-sdk-dotnet#1115]
**The Creation Checklist is not created in the same order as i pass the checklist items, it gets added in same order in tasks, but sometimes it does not work **

`          var checkListItems = new PlannerChecklistItems();
            var checkListItemId = checkListItems.AddChecklistItem("Update task details");
            checkListItems[checkListItemId].IsChecked = false; // update property

            // add a new item to the list using the title and get back a client generated id
            var checkListItemId2 = checkListItems.AddChecklistItem("Update task details1");
            checkListItems[checkListItemId2].IsChecked = false; // update property

            var plannerTaskDetails = new PlannerTaskDetails
            {
                PreviewType = PlannerPreviewType.Checklist,
                Description = taskDetails.Description,
                Checklist = checkListItems
            };

            await client.Planner.Tasks[taskDetails.TaskId].Details
                            .Request()
                            .Header("Prefer", "return=representation")
                            .Header("If-Match", taskDetails.Etag)
                            .UpdateAsync(plannerTaskDetails);
`
i have few tasks, trying to add the same in all tasks. for few tasks the order in which checklist has been added is different order, May I know the reason behind that.

**To Reproduce**

**Expected behavior**
checklist order is different for different tasks, 

**Screenshots**
![image](https://user-images.githubusercontent.com/82937760/130680297-bc7cf142-f868-46a2-9dd3-5fb41262e794.png)
each of this tasks call the same update methods, but y is the difference in adding it in the tasks.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#10854](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10854)

**Comment by andrueastman** [comment]
Hey @UmamaheshwariGolla,

Thanks for getting back. I was hoping the checklist ids would be something that would be consistent and not randomly generated on every run(as the SDK does the same thing at the moment).

```cs
checkListItems["95e27074-6c4a-447a-aa24-9d718a0b86fa"] = checkListItem;
checkListItems["d280ed1a-9f6b-4f9c-a962-fb4d00dc50ff"] = checkListItem1;
```

Does it work as expected if you consistently use similar guids for each `PlannerTaskDetails`(or ensure they are always in ascending order)?
