### ISSUE TITLE
Batch request truncating relative URL when email contains 'beta'

### ISSUE THREAD

**Issue by AlexBGitAtMe** [microsoftgraph/msgraph-sdk-dotnet#1119]
**Describe the bug**
When performing batch operations on Events, the request URL gets truncated on an email that contains the string 'beta'. For example the relative url will end up being '123@wonderemail.com/events' when it should be 'users/abcbeta123@wonderemail.com/events'

**To Reproduce**
```
GraphServiceClient graphClient = getGraphClient();
string email = "abcbeta123@wonderemail.com";
string reqId = Guid.NewGuid().ToString();
var request = graphClient.Users[email].Events.Request().Header("Prefer", "outlook.timezone=\"Central Standard Time\"").GetHttpRequestMessage();
request.Method = new HttpMethod("GET");
BatchRequestStep batchStep = new BatchRequestStep(reqId, request);

BatchRequestContent  req= new BatchRequestContent();
req.AddBatchRequestStep(batchStep);

var response = await graphClient.Batch.Request().PostAsync(req);
var responses = await response.GetResponsesAsync();

```

Responses contain the error message: "message=Resource not found for the segment '123@wonderemail.com'."

 
[AB#10932](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10932)

**Comment by andrueastman** [comment]
Hey @AlexBGitAtMe,

Thanks for raising this. This seems related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/310.

Closing this for now as it is will be resolved there.
