### ISSUE TITLE
User Update Request does not update user and return null for user without exception being thrown

### ISSUE THREAD

**Issue by ecolara3** [microsoftgraph/msgraph-sdk-dotnet#1123]
***Issue**
When calling `var updatedUser = await microsoftGraphApi.Users["{User's ObjectId}"].Request().UpdateAsync(patchUser)` user is not updated and UpdateAsync returns null;

**Steps to reproduce the behavior**
Created a Unit Test to show behavior: https://github.com/Moosara/MicrosoftGraphAPIBug

**Expected behavior**
User should be updated and call should return updated user, if something went wrong, an exception should be thrown.

**Screenshots**
Permissions for the account: 
![image](https://user-images.githubusercontent.com/3268879/131879376-73e462af-60ed-4f7b-82ba-29da0f3b48c3.png)

**Additional context**
I am able to get User information when I call: 
`var users = await microsoftGraphApi.GraphServiceClient.Users.Request().GetAsync();` but the update for some reason not work.

Note: I am able to retrieve the user and update the user information if I call the API endpoint directly via postman.

**Comment by MIchaelMainer** [comment]
updatedUser is expected to be null as the API returns a 204. https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#response. This is a general client generation defect -- nothing to determine whether the object is actually returned for this scenario. I'm sorry for the confusion.

I can't repro your issue of the user not being updated. Running the following code results in the user being updated. 

	User patchUser = new User() { AboutMe = "More info" };
	await client.Users[Chambele.V1.user].Request().UpdateAsync(patchUser);
	var updatedUser = await client.Users[Chambele.V1.user].Request().GetAsync();

**Comment by ecolara3** [comment]
> updatedUser is expected to be null as the API returns a 204. https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#response. This is a general client generation defect -- nothing to determine whether the object is actually returned for this scenario. I'm sorry for the confusion.
> 
> I can't repro your issue of the user not being updated. Running the following code results in the user being updated.
> 
> ```
> User patchUser = new User() { AboutMe = "More info" };
> await client.Users[Chambele.V1.user].Request().UpdateAsync(patchUser);
> var updatedUser = await client.Users[Chambele.V1.user].Request().GetAsync();
> ```

@MIchaelMainer I think the confusion comes in that the IntelliSense comments say a user is returned.

![image](https://user-images.githubusercontent.com/3268879/131908257-47c798c3-8eae-476b-8b17-8242e39c0251.png)

I saw the document you linked but was thinking well if the intelligence is telling me I should get a user, maybe I am just reading an old document or the wrong one.

Also, I wrote a service using an HttpClient and noticed if I do not include: ?$select=givenname,surname,postalCode,streetaddress,country,postalcode,state,city

Then these values come back null. So I am not sure if I need to do something special to request these properties using the SDK, but in the end, I don't see anything in the SDK that requires specifying these specific properties.

Note: The test case you are providing uses the AboutMe property, which is not a part of the code sample I provided. Issue may be in the properties, which is why I specified the specific ones I am looking at and not ones in general.

**Comment by andrueastman** [comment]
Hey @ecolara3,

By default, the API will only return a subset of the properties when calling `GetAsync()`. The properties covered are mentioned in the docs [here](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#example-1-standard-users-request).

You can therefore modify your test cases as follows to use the SDK to validate this.

```cs
  var patchUser = new Microsoft.Graph.User()
  {
      Surname = "Some Surname",
      GivenName = "Some GivenName",
      StreetAddress = "1111 8th Street",
      City = "El Dorado",
      Country = "Rawanda",
      State = "Mumbai",
      PostalCode = "7777777"
  };

  // Update the user object and validate we get a 204 response from the API
  var updateResponse = await microsoftGraphApi.Users["{User's ObjectId}"]
      .Request().UpdateResponseAsync(patchUser);

  Assert.Equal(updateResponse.StatusCode, HttpStatusCode.NoContent);

  // Select the properties we updated as they are not returned by default
  var updatedUser = await microsoftGraphApi.Users["{User's ObjectId}"]
      .Request().Select("surname,givenName,streetAddress,city,country,state,postalCode").GetAsync();

  Assert.True(updatedUser != null, "User is null");
  Assert.True(updatedUser.Surname == patchUser.Surname, "Surname is not correct");
  Assert.True(updatedUser.GivenName == patchUser.GivenName, "GivenName is not correct");
  Assert.True(updatedUser.StreetAddress == patchUser.StreetAddress, "StreetAddress is not correct");
  Assert.True(updatedUser.City == patchUser.City, "City is not correct");
  Assert.True(updatedUser.Country == patchUser.Country, "Country is not correct");
  Assert.True(updatedUser.State == patchUser.State, "State is not correct");
  Assert.True(updatedUser.PostalCode == patchUser.PostalCode, "PostalCode is not correct");
```
