### ISSUE TITLE
OneDrive Graph Client throwing System.TypeInitializationException in Xamarin.iOS project only

### ISSUE THREAD

**Issue by shantimohan** [microsoftgraph/msgraph-sdk-dotnet#1127]
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
OneDrive Graph Client throwing System.TypeInitializationException in Xamarin.iOS project only.

This was working till few days back. It appears one of the recent updates to Xamain.iOS has broken it.

I have implemented OneDrive client in my project as per Build Xamarin apps with Microsoft Graph.

This is a Xamarin Forms project. Installed **Microsoft.Graph** only in the common project and installed **Microsoft.Identity.Client** in all projects.

**To Reproduce**
1. After successful login into OneDrive service...
2. The error occurring is: System.TypeInitializationException Message=The type initializer for 'System.Text.Json.JsonSerializer' threw an exception
3. This error is produced when executing the code: IDriveItemChildrenCollectionPage files = await OdGraphClient.Me.Drive.Root.Children.Request().GetAsync();

**Expected behavior**
When the code mentioned in Step 3 above, it should return list of objects at the root directory.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS [e.g. iOS]
 - VS 2019 Version 16.11.2
 - Xamarin.Forms version 
 - Xamarin.iOS Version 14.20.0.25

**Dependency versions**
 - Authentication library (MSAL, etc.) version: Microsoft.Identity.Client Version 4.36.0
 - Graph library (Graph SDK, REST library, etc.) version:  Microsoft.Graph 4.4.0

**Additional context**
This occurs only in iOS and not in Android.

**Comment by jasonjoh** [comment]
Transferred over to SDK repository for triage.

**Comment by andrueastman** [comment]
Hey @shantimohan,

Thanks for raising this issue. This looks to be a related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1124.

Any chance you could confirm that the solution provided in the comment below works out for you?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1124#issuecomment-913355568

**Comment by shantimohan** [comment]
The reference to issue #1124 was useful. My issue was resolved by adding the two packages mentioned in the accepted answer of [https://docs.microsoft.com/en-us/answers/questions/302548/jsonserializer-throws-exception-in-xamarinios.html](url).
