### ISSUE TITLE
DriveItem permissions for Group/Team files (to write the permissions)

### ISSUE THREAD

**Issue by DakshPadiya** [microsoftgraph/msgraph-sdk-dotnet#1137]
Hii,

I am sharing the Group/Team files and folders with different users with different permission access, to some users I have given "write" access, and to some users only "read" permission access is given. 
The issue I am facing is after writing the permission, the read permission is not getting reflected on sites. The response result from API is getting proper.

I am trying to add the permission 
https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=csharp 
`
graphClient..Groups[groupId].Drives[DriveId].Items[itemId].Invite([{"email":"mig@domain.onmicrosoft.com"}], true, ["read"], false, null).Request()..PostAsync().Result;
`

and the response I'm getting for the same is;

```
[
  {
    "grantedTo": {
      "user": {
        "displayName": "mig",
        "id": "10c76447-a38f-4f04-b761-b8f201891b18",
        "@odata.type": "microsoft.graph.identity",
        "email": "mig@domain.onmicrosoft.com"
      },
      "@odata.type": "microsoft.graph.identitySet"
    },
    "roles": [
      "read"
    ],
    "id": "aTowIy5mfG1lbWJlcnNoaXB8bWlnNEBkZXYxc3lzdG9vbHMub25taWNyb3NvZnQuY29t",
    "@odata.type": "#microsoft.graph.permission"
  }
]
```

But still, it is not getting reflected at the SharePoint site.

**Comment by JeremyKelley** [comment]
Does it send the e-mail request to mig@domain.onmicrosoft.com?  It may not be reflected in the ACL list until after the user comes and redeems the link.

**Comment by DakshPadiya** [comment]
As I have set the "sendInvitation" to false. So it does not send any invitation to  mig@domain.onmicrosoft.com.
Is there a way to overcome this issue without sending the invitation?

**Comment by DakshPadiya** [comment]
> Does it send the e-mail request to [mig@domain.onmicrosoft.com](mailto:mig@domain.onmicrosoft.com)? It may not be reflected in the ACL list until after the user comes and redeems the link.

I have tried sending an email request, it works properly as you mentioned. 
But in my usecase, we do not have to send the request. So I am setting "sendInvitation" argument in the Invite method to false.

**Comment by andrueastman** [comment]
Hey @JeremyKelley,

Any chance you may know if the behavior reported by @DakshPadiya is as expected? Or is this something that maybe needed as a feature request?
