### ISSUE TITLE
[Client bug]: NextPageRequest doesn't work for chatmessages anymore

### ISSUE THREAD

**Issue by anne376** [microsoftgraph/msgraph-sdk-dotnet#1144]
The following code snipped runs with version 3.27, but not with 4.5 or 4.6

var request = _graphClient.Teams[teamId].Channels[channelId].Messages.Request();
var page = await request.GetAsync();
List<ChatMessage> elements = page.ToList();
while (page.NextPageRequest != null)
{
	page = await page.NextPageRequest.GetAsync();
	elements.AddRange(page.ToList());
}

While checking the objects more closely in the debugger, I noticed that "@odata.nextLink" is missing in version 4.6. Instead the url of NextPageRequest seems to include the nextLink data

**here my example**

Version 3.27:
- RequestUrl: https://graph.microsoft.com:443/v1.0/teams/<teamid>/channels/<channelId>/messages
- NextPageRequest RequestUrl: same as RequestUrl
- "@odata.nextLink": https://graph.microsoft.com/v1.0/teams/<teamid>/channels/<channelId>/messages?$skiptoken=%5b%7B%22token%22%3a%22%2bRID%3a~vpsQAJ9uAC3gaSUBAADYCA%3d%3d%23RT%3a1%23TRC%3a20%23RTD%3aAyAER1ygxSHVHGAn2S99BTI6O2c0MTZkNmUyOGMyMTU0Yjo6MTE3OWM5NjQzZjQ2MWVmQXVpc2ZiZS90bHpxZjwyNzIzNDcyOjk6Mzc1AA%3d%3d%23ISV%3a2%23IEO%3a65551%23QCF%3a4%23FPC%3aAgiHAAAAaCEAAHcFAABgIwAAhwAAAGghAAACAEePiAAAAGghAAAEAJunGpWJAAAAaCEAAAIA%2b5CMAAAAaCEAAAQAPrI3gY8AAABoIQAABgCUgIiBGoCQAAAAaCEAAAIAnqsJAQAAaCEAAAIAcL8KAQAAaCEAAAIAZpCGBAAAYCMAAAIArKaVBAAAYCMAAAQA3akAgNoEAABgIwAAAgDzu%2b0EAABgIwAAAgCbkzgFAABgIwAABAD9sHGKTQUAAGAjAAACAPW%2fTgUAAGAjAAAEABOABIN3BQAAYCMAAAYATKSHgK%2bK%22%2c%22range%22%3a%7B%22min%22%3a%2205C1E5B5CD5F5A%22%2c%22max%22%3a%2205C1E5BB7D4396%22%7D%7D%5d

Version 4.6:
- RequestUrl: https://graph.microsoft.com:443/v1.0/teams/<teamid>/channels/<channelId>/messages
- NextPageRequest RequestUrl: https://graph.microsoft.com:443/v1.0/teams/<teamid>/channels/<channelId>/messages#RT:1#TRC:20#RTD:AyAER1ygxSHVHGAn2S99BTI6O2c0MTZkNmUyOGMyMTU0Yjo6MTE3OWM5NjQzZjQ2MWVmQXVpc2ZiZS90bHpxZjwyNzIzNDcyOjk6Mzc1AA==#ISV:2#IEO:65551#QCF:4#FPC:AgiHAAAAaCEAAHcFAABgIwAAhwAAAGghAAACAEePiAAAAGghAAAEAJunGpWJAAAAaCEAAAIA+5CMAAAAaCEAAAQAPrI3gY8AAABoIQAABgCUgIiBGoCQAAAAaCEAAAIAnqsJAQAAaCEAAAIAcL8KAQAAaCEAAAIAZpCGBAAAYCMAAAIArKaVBAAAYCMAAAQA3akAgNoEAABgIwAAAgDzu+0EAABgIwAAAgCbkzgFAABgIwAABAD9sHGKTQUAAGAjAAACAPW/TgUAAGAjAAAEABOABIN3BQAAYCMAAAYATKSHgK+K%22,%22range%22:%7B%22min%22:%2205C1E5B5CD5F5A%22,%22max%22:%2205C1E5BB7D4396%22%7D%7D]
- "@odata.nextLink" is missing

**Comment by andrueastman** [comment]
Hey @anne376,
Thanks for raising this issue. 
Are you able to give more information on the exact error/exception you are experiencing?

> "@odata.nextLink" is missing

This is expected in version 4.x in the SDK as the url is now deserialized into string property that is passed over to the nextPageRequest as you observed(hence no need to show up in the AdditionalData). 
However, if `page.NextPageRequest` is not null, you should be able to iterate forward to the next page. Yes ?

**Comment by anne376** [comment]
Hi @andrueastman,

NextPageRequest is not null, but I'm not able to iterate forward. The code I provided is a never ending loop. There are always the same 20 chat messages in the page. It seems that the internal skip token does not go on.

**Comment by andrueastman** [comment]
Thanks for the patience @anne376.

This should now be resolved by https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/341 and by pulling https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.6
