### ISSUE TITLE
Naming policy

### ISSUE THREAD

**Issue by Afshin1980** [microsoftgraph/msgraph-sdk-dotnet#1153]
Hello All,

I'm using Microsoft.Graph 3.8.0 for creating groups and teams on Microsoft teams. Here is the code I'm using for creating a group

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var group = new Group
{
	DisplayName = "My displayName",
	Description = "My description",
	GroupTypes = new List<String>() { "Unified" },
	MailEnabled = true,
	MailNickname = Guid.NewGuid().ToString("N"),
	SecurityEnabled = false,
	Visibility = "Public",
	AdditionalData = new Dictionary<string, object>()
	{
		{
			"owners@odata.bind",new string[]
			{
				String.Format("https://graph.microsoft.com/v1.0/users/{0}",teamOwner.Id)
			}
		}
	}
};

await graphClient.Groups.Request().AddAsync(group);

The issue I'm having is that I have a naming policy in Azure AD. when the rule is enabled the code returns the following error even if you follow the policy but if I disable the naming policy It works fine. 

Code: Request_BadRequest
Message: The property is missing a required prefix/suffix per your organization's Group naming requirements.
Details:
	Detail0:
		Code: MissingPrefixSuffix
		Target: displayName
		AdditionalData:
	suggestedPropertyValue : - challenge-test-challenge-teams-integration55
Inner error:
	AdditionalData:
	date: 2021-07-23T13:19:00
	request-id: e01f0acb-a5fd-402f-a36d-16ce0985dfa7
	client-request-id: e01f0acb-a5fd-402f-a36d-16ce0985dfa7
ClientRequestId: e01f0acb-a5fd-402f-a36d-16ce0985dfa7

**Comment by pschaeflein** [comment]
@Afshin1980 - You may find this API helpful: https://docs.microsoft.com/en-us/graph/api/directoryobject-validateproperties

**Comment by Afshin1980** [comment]
@pschaeflein I have another question that you may help me with! My current issue is that I have a naming policy like this
<Department> - <Group name> and as I call the graph API for creating the group with my application identity and as I don't have any department for my app the department part is always empty. I would like to know if there is a way to set department or other attributes for the app in Azure.
Thank you in advance!
