### ISSUE TITLE
Visual Studio flags `GraphServiceClient.Users` as obsolete

### ISSUE THREAD

**Issue by Tiberriver256** [microsoftgraph/msgraph-sdk-dotnet#1161]
**Describe the bug**
Visual Studio flags `GraphServiceClient.Users` as obsolete but there is no explanation provided about what should be used instead.

**Expected behavior**
I'd like some detail in the obsoletion explaining what to use as an alternative

**Screenshots**
![image](https://user-images.githubusercontent.com/6989492/139495450-4d7d20c3-86e2-4b52-aa93-d712f86eb3ed.png)

**Comment by MIchaelMainer** [comment]
That's strange. We don't mark that member as obsolete.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/requests/GraphServiceClient.cs#L100

What version of the client are you using? I do wonder if you are using 3.x and whether VS consider it obsolete now that we have a version 4.x.

**Comment by Tiberriver256** [comment]
Oh sorry! I thought I posted this as an issue in the beta repo.

![image](https://user-images.githubusercontent.com/6989492/139508653-d797d161-45e9-47f8-a7f6-afb1e9442a7b.png)

Should I close this issue and open a new one over there?

**Comment by Tiberriver256** [comment]
Looks like there's already an issue over there actually:
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/353

I'll close this one out as a dupe
