### ISSUE TITLE
Expected capitalization of letter I in Error code ItemNotFound not being returned

### ISSUE THREAD

**Issue by MarcoEnxuto** [microsoftgraph/msgraph-sdk-dotnet#1162]
**Describe the bug**
When requesting an OneDrive resource (for example, a directory) that does not exist, the error code returns itemDoesNotExist, instead of ItemDoesNotExist.

**To Reproduce**
1. Request a folder that does not exist on OneDrive, and analyze the error code returned with a try catch.

**Expected behavior**
I was expecting the error code returned, matches the GraphErrorCode enumerate.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Graph SDK
 - Version 1.21

**Comment by MarcoEnxuto** [comment]
Any news?

**Comment by andrueastman** [comment]
Hey @MarcoEnxuto,

Thanks for raising this issue and apologies for the delay. 

It looks like the error returned by the service is consistent with the API documentation provided [here](https://docs.microsoft.com/en-us/graph/errors#code-property) starting with small caps. 

We have documented here how best to handle the error code [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#checking-the-error-code) by using code similar to what is below as changing the naming of the Enum member would violate C# code conventions as Enum members should be [pascal cased](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions#capitalization-rules-for-identifiers). 

```csharp
if (serviceException.IsMatch(GraphErrorCode.ItemDoesNotExist.ToString())
{
        // Handle access denied error
}
```

Hope this clears things up for you and let us know if you have any more questions.
