### ISSUE TITLE
Getting corrupted image on posting inline images in Microsoft Teams Channel message using Microsoft Graph API in C#

### ISSUE THREAD

**Issue by DakshPadiya** [microsoftgraph/msgraph-sdk-dotnet#1164]
I have tried to post the message having an inline image attachment in Microsoft Teams Channel Messages using Graph API but ended with the corrupted image after migration.

I have tried to post the message using the following code:

```
var chatMessage = new ChatMessage
{
	Body = new ItemBody
	{
		ContentType = BodyType.Html,
		Content = "<div><div>\n<div><span><img height=\"80\" src=\"../hostedContents/201/$value\" width=\"353\" style=\"vertical-align:bottom; width:353px; height:80px\"></span>\n<div>&nbsp;</div>\n</div>\n\n<div>screenshot</div>\n</div>\n</div>";
	},
	HostedContents = new ChatMessageHostedContentsCollectionPage()
	{
		new ChatMessageHostedContent
		{
			ContentBytes = Encoding.ASCII.GetBytes("YVdROWVGOHdMV05wYmkxa05DMHlZVEl6WXpOaE56UXhaakE1WVdJeU1tRmlaVFkyT1RNNU1UaGhaRFE1Tml4MGVYQmxQVEVzZFhKc1BXaDBkSEJ6T2k4dmFXNHRZWEJwTG1GemJTNXphM2x3WlM1amIyMHZkakV2YjJKcVpXTjBjeTh3TFdOcGJpMWtOQzB5WVRJell6TmhOelF4WmpBNVlXSXlNbUZpWlRZMk9UTTVNVGhoWkRRNU5pOTJhV1YzY3k5cGJXZHY="),
			ContentType = "image/png",
			AdditionalData = new Dictionary<string, object>() { {"@microsoft.graph.temporaryId", "201"} }
		}
	}
};

IChannelMessagesCollectionRequest messageRequest =
                       this.TeamService.Teams[TeamId].Channels[ChannelId].Messages.Request().AddAsync(chatMessage).Result;


```

The image is uploaded but it is showing as corrupted as below:

![image](https://user-images.githubusercontent.com/68002465/139866407-504aaa9b-576b-4b63-9e34-4bec0f627e26.png)

Reference: [https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http](url) Example 5

**Comment by andrueastman** [comment]
Hey @DakshPadiya,

Thanks for raising this issue.

For some reason I can't get it to work on my side using the `ContentBytes` Base64 data provided in your example and also testing it [here](https://www.base64decode.net/base64-image-decoder).

However, there is an issue with the snippet provided in the docs. 

Reading the `ContentBytes` property should actually be done as below using `Convert.FromBase64String` and not `Encoding.ASCII.GetBytes`

If the base64 string is correct and the `ContentType` property set to the correct extension, the image should be displayed correctly

```cs
// Example sourced from 
ContentBytes = Convert.FromBase64String("iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="),
```

We shall correct this in the docs and track this in a separate issue on the snippet generator.

**Comment by andrueastman** [comment]
Closing this and will be tracked via https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/751
