### ISSUE TITLE
Using GraphServiceClient not able to get request id on Exception

### ISSUE THREAD

**Issue by Vignesh3813** [microsoftgraph/msgraph-sdk-dotnet#1167]
I am using GraphServiceClient to enable Microsoft Teams, Channel and tabs.
Some time I am facing BadGateway error or TooManyRequest error but in that Exception message not able to get Request Id.

Sample Error Message:

type: Microsoft.Graph.ServiceException

assembly: Microsoft.Graph.Core, Version=1.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

Message: 
Code: BadGateway
Message: Failed to execute backend request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=CS#feedback)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Hey @Vignesh3813,

The version of Microsoft.Graph.Core, Version=1.15.0.0 seems a bit out of date. Some work has been done since then to enrich error information and also handle retrying of 429 responses.

Are you able to update to a later version to resolve this?
