### ISSUE TITLE
File size is always 0 in the items SharedWithMe from OneDrive Business

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#117]
I am retrieving the list of items shared with me using Graph SDK as shown below:

var response = await client.Me.Drive.SharedWithMe().Request().GetAsync();

I have verified the size property of DriveItem as well as RemoteItem. Size is always 0.

**Comment by MIchaelMainer** [comment]
Thank you for contacting us! Repo issues should be used for identifying issues with the Microsoft Graph .Net client library. Questions about how to do something should be directed to StackOverflow as more people will find the questions and answers. Please post to StackOverflow with the [microsoftgraph] and [OneDrive] tags. Make sure you post what you've tried and the repro steps. Once you've posted, please provide a link in this issue.

**Comment by Saket0911** [comment]
As suggested by you, posted the question StackOverflow in below link:
https://stackoverflow.com/questions/43995557/file-size-is-always-0-in-the-sharedwithme-items-in-onedrive-business

Need your help in resolving this issue.

**Comment by MIchaelMainer** [comment]
@Saket0911 The StackOverflow post stated that a fix was being worked on. Are you still seeing this issue? Otherwise, I'll close this issue in one week.
