### ISSUE TITLE
passing cancelation token to driveitemrequest does nothing

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/msgraph-sdk-dotnet#1175]
Using C#, .Net4.6.2, Graph v4.2.0, I'm creating a new CancellationTokenSource(20000) == a timeout of 20sec.

Passing that object's cancellation token to IDriveItemRequest.GetAsync(token) does not appear to work.  The timeout for the request is not complied with.

We are experiencing an issue where a DriveItemRequest for a document that was recently deleted is hanging indefinitely.  Sometimes we DO get the ServiceException with StatusCode == NotFound, which is what we would expect.  However, we are seeing issues where the request just hangs/does-not-return.  That's maybe a bug in Graph Service, but that is a different issue.

How is it the Http/DriveItem request is not canceled upon the token timeout as requested?

**Comment by ajweber** [comment]
Note that (Open) Issue #1020 also references attempting to use a cancelation token with no success.  (Related?)

**Comment by andrueastman** [comment]
Hey @ajweber,

We've made some improvements in the [2.0.8](https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.8) release with regard to trying to mitigate this. Any chance you could try this out and give feedback whether you are still encountering this?

**Comment by ajweber** [comment]
Bot needs to chill a little.  This issue had no movement on it for over 3 months, we get a comment that maybe, some other code change might have helped this issue, and then I get 3-7 days to re-test it?

Please standby for testing.  I will get to it ASAP.  It was easier to reproduce (due to the state of OneDrive) at the time.

**Comment by maisarissi** [comment]
Hi @ajweber . Did you get the chance to validate it?

**Comment by ajweber** [comment]
I have not been able to reproduce the issue, but that is because the service-bug doesn't seem to be present at this time.  So I can not confirm whether it is fixed or not, because I need to spend time to devise a new test to reproduce it.
