### ISSUE TITLE
OrderBy is not working on "name" property for OneDrive business SharedWithMe items

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#118]
The specs say that OneDrive business supports sorting only on name field. However, when I am trying to OrderBy "name" on SharedWithMe items, it throws exception as "Sorting on 'name' isn't supported.". I am using below code for OrderBy:

var response = await client.Me.Drive.SharedWithMe().Request().OrderBy("name").GetAsync();

**Comment by MIchaelMainer** [comment]
Thank you for contacting us! Repo issues should be used for identifying issues with the Microsoft Graph .Net client library. Questions about how to do something should be directed to StackOverflow as more people will find the questions and answers. Please post to StackOverflow with the [microsoftgraph] and [OneDrive] tags. Make sure you post what you've tried and the repro steps. Once you've posted, please provide a link in this issue.

**Comment by Saket0911** [comment]
@MIchaelMainer As suggested by you, posted the question StackOverflow in below link:
https://stackoverflow.com/questions/43995872/orderby-is-not-working-on-name-property-for-onedrive-business-sharedwithme-ite

Need your help in resolving this issue.

**Comment by MIchaelMainer** [comment]
Answered on SO
