### ISSUE TITLE
Bad request : update Group with schema extension value

### ISSUE THREAD

**Issue by lenain71** [microsoftgraph/msgraph-sdk-dotnet#1182]
I come to you on this post because I am exactly in this case : 
ref : https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/151

Groups resources are extended with a schema extension value (already in place ) : 
![image](https://user-images.githubusercontent.com/42752420/143475330-1939f2a7-2e17-4400-9ef4-b9582ac6e0a2.png)

I'm trying to update a resource group using .Net core 3.1 apps and MSgraphClient (through Pnp.Core SDK). I'm using exactly the same code structure, here for detail : 

```
var formatedGraphData = new M365ResourceTaggingResponse(this._m365ResourceToUpdate);
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName, JsonConvert.SerializeObject(formatedGraphData));

var groupUpdated = new Group
{
AdditionalData = extensionInstance
};

var groupItem = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().UpdateAsync(groupUpdated);
```

Declaration for the class M365ResourceTaggingResponse
 
```
[JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public class M365ResourceTaggingResponse
    {
        [JsonProperty(PropertyName = "ExpirationStatus")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ExpirationStatus Status { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "expirationDate")]
        public DateTime? ExpirationDate { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "ExpirationLastControlled")]
        public DateTime? ExpirationLastControlledDate { get; set; }

        public M365ResourceTaggingResponse(M365ResourceTaggingRequest request)
        {
            this.Status = request.Status;
            this.ExpirationDate = request.ExpirationDate;
            this.ExpirationLastControlledDate = request.ExpirationLastControlledDate;
        }
    }
```

Now the issue : no matter what, i'm alway have a bad request 400 :

Debug object send to MSGraph : 
![image](https://user-images.githubusercontent.com/42752420/143477079-9ce89503-174e-4335-a193-a699e149ddec.png)

Debug detail : 
![image](https://user-images.githubusercontent.com/42752420/143477141-41dbe246-4423-4761-a95b-b7f583eadfc2.png)

Error message:
![image](https://user-images.githubusercontent.com/42752420/143477209-67483b0e-d4a1-4611-b99e-7d2ea714faa7.png)

If i made the exact same query using graph Explorer, with the same data, all is good : 
![image](https://user-images.githubusercontent.com/42752420/143477441-186ea2ae-5301-44e3-8756-729d600ca9fe.png)

Is someone successfully update a Azure Resource (Groups, users...) with an schema extension value using the GraphAPI client ?

Regards

_Originally posted by @lenain71 in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/151#issuecomment-979351331_

**Comment by andrueastman** [comment]
Hey @lenain71,

Thanks for raising this.

I noticed that you serialize the object before placing it into the `additionalData`. This means that its now a string and will be serialized a second time to cause a different payload to be sent.

Any chance this will work if you change your code to this?

```cs
var formatedGraphData = new M365ResourceTaggingResponse(this._m365ResourceToUpdate);
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName, formatedGraphData); //undo the serialization here.

var groupUpdated = new Group
{
AdditionalData = extensionInstance
};

var groupItem = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().UpdateAsync(groupUpdated);
```

**Comment by lenain71** [comment]
@andrueastman thanks for the advice.

I confirm, after changing the code to avoid serialisation of the additionalData before sending to MSGraph. All is good. Many thnaks @andrueastman. I'm closing the ticket.

**Comment by lenain71** [comment]
@andrueastman  I'm closing the ticket too quickly !

Now that the call to the graphAPI seems to be good and I got a 204 code result, no update was made to the extended properties for the group ! 

I changed my code to get result of the call using `UpdateResponseAsync`, in order to have code result from GraphService. I also display `AdditionalData `properties before update, with data sent to update and after udpate complete. 

![image](https://user-images.githubusercontent.com/42752420/144067433-97583004-cdeb-40d1-ad3c-f188d0e59eb2.png)

All is good even if any update was made !! 

Please see code snippet used : 

```
 var formatedGraphData = new M365ResourceTaggingResponse(this._m365ResourceToUpdate);
                    IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
                    extensionInstance.Add(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName, formatedGraphData);

var groupUpdated = new Group
                    {
                        AdditionalData = extensionInstance
                    };

                    var groupBeforeUpdate = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().GetAsync();

                    if(groupBeforeUpdate.AdditionalData.ContainsKey(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName))
                    {
                        Console.WriteLine($"group properties befor update {groupBeforeUpdate.AdditionalData[GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName]}");

                    }
                    else
                    {
                        Console.WriteLine($"group properties befor update is empty");

                    }

                    Console.WriteLine($"group properties value for update " +
                        $"{ JsonConvert.SerializeObject(groupUpdated.AdditionalData[GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName])}");

                    var groupItemResponse = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().UpdateResponseAsync(groupUpdated);

                    Console.WriteLine($"graph api call status : {groupItemResponse.StatusCode}");

                    //verification
                    var updatedGroup = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request()
                        .Select(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName)
                        .GetAsync();

                    Console.WriteLine($"group proerties after update {updatedGroup.AdditionalData[GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName]}");
```

**Comment by andrueastman** [comment]
Hey @lenain71,

Any chance you could post what is produced when you do this? It'll show us the json payload that is built and sent to the API and confirm whether the extension is part of the payload.

```cs
var updateGroupJsonString = graphServiceClient.HttpProvider.Serializer.SerializeObject(groupUpdated);
Console.WriteLine(updateGroupJsonString);
```

**Comment by lenain71** [comment]
@andrueastman 

there is something wrong with the payload : 

![image](https://user-images.githubusercontent.com/42752420/144077534-a195dbc4-ad04-4cad-b811-e3233d37a59f.png)

the serialization set "expirationStatus" and not "ExpirationStatus" when sending data to graphAPI, without any error during the update, and even if the serializationAttribute of the object was explicitly set to : 

 ```
public class M365ResourceTaggingResponse
    {
        [JsonProperty(PropertyName = "ExpirationStatus")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ExpirationStatus ExpirationStatus { get; set; }
...}

```

**Comment by andrueastman** [comment]
Are you able to provide information on the version of the microsoft graph package are you currently using?

**Comment by lenain71** [comment]
Sure...

#region Assembly Microsoft.Graph, Version=4.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// ###########\.nuget\packages\microsoft.graph\4.10.0\lib\netstandard2.0\Microsoft.Graph.dll
#endregion

**Comment by andrueastman** [comment]
Version 4.x of the SDK uses System.Text.Json as the serializer and not NewtonSoft. So, the `JsonProperty` annotations will not work since they are NewtonSoft annotations.

To fix this, you can either
- Use System.Text.Json annotations like the ones existing in the Graph models. Example [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/16a36d91a9ce1d15e00828a76b4a458413e1364c/src/Microsoft.Graph/Generated/model/AccessReviewInstance.cs#L27).
- Serialize the instance of your class with Newtosoft and then place it into the AdditionalData as an instance of Sytem.Text.Json's JsonDocument like the example below

```cs
var formatedGraphData = new M365ResourceTaggingResponse(this._m365ResourceToUpdate);
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
var formatedGraphDataString = JsonConvert.SerializeObject(formatedGraphData);
extensionInstance.Add(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName, JsonDocument.Parse(formatedGraphDataString));

var groupUpdated = new Group
{
AdditionalData = extensionInstance
};

var groupItem = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().UpdateAsync(groupUpdated);
```

Please try out whichever option works better for you and let me know if it works out for you.
