### ISSUE TITLE
Task open extension - "Id is malformed"

### ISSUE THREAD

**Issue by danjrauch** [microsoftgraph/msgraph-sdk-dotnet#1183]
**Describe the bug**
I'm trying to add an open extension to a todo task.

`await graphClient.Me.Todo.Lists[listId].Tasks[taskId].Extensions.Request().AddAsync(extension);`

The code throws an InvalidRequest error saying the "**Id is malformed.**" The listId value is the generic list ID "Tasks". The taskId value is a seemingly valid ID of a freshly retrieved task. The extension is something very similar to the one given in the [docs](https://docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&tabs=csharp):

```
var extension = new OpenTypeExtension
{
	ExtensionName = "Com.Contoso.Referral",
	AdditionalData = new Dictionary<string, object>()
	{
		{"companyName", "Wingtip Toys"},
		{"dealValue", "500050"},
		{"expirationDate", "2015-12-03T10:00:00Z"}
	}
};
```

**Expected behavior**
I expect the extension to be added successfully. A test in ExtensionTests.cs might be helpful as well. 

**Additional context**
I'm using Microsoft.Graph version 4.11.0, but I think it happens in 4.10.0.

**Comment by andrueastman** [comment]
Hey @danjrauch,

I don't believe the listId value should be something readable like "Tasks". That would probably correlate to the displayName property.

If you query for the lists api should be able to read the id property of the task to see something similar to this when you run this query of graph explorer on the link below.

https://developer.microsoft.com/en-us/graph/graph-explorer?request=me%2Ftodo%2Flists&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

You could also take a look at the snippets tab at the bottom section of the page to see how to make the same call with the SDK.

**Comment by danjrauch** [comment]
Ok finding the actual ID of the task list worked. It seems that the trick of using the display name "Tasks" as shorthand for that list's ID works with all Task endpoints except the ones related to extensions.
