### ISSUE TITLE
[Client bug]: NextLink uri is not the same as the raw payload received

### ISSUE THREAD

**Issue by DOMZE** [microsoftgraph/msgraph-sdk-dotnet#1184]
**Describe the bug**
It seems that the internal library is not mapping the odata.NextLink properly. it seems that the skip token is split up

When using a tool like Fiddler to see the raw payload received, the odata.nextLink is seen as:
https://graph.microsoft.com/v1.0/teams/c7a2f0a6-bb37-40f2-b908-2305650b03ce/channels/19:7yFDiTCIS1sYT-rZ46tTn8PfZFTafi7pyhe1ml0RmhI1@thread.tacv2/messages?$skiptoken=%5b%7B%22token%22%3a%22%2bRID%3a~vpsQAJ9uAC0sBo8AAAC8DQ%3d%3d%23RT%3a1%23TRC%3a20%23RTD%3aAyAER1ygxSHVHJBn2S99BTI6Ozh6R0VqVURKVDJ0WlUuc1s1NnVVbzlRZ1dHVWJnajhtemlmMm5tMVNuaUoyQXVpc2ZiZS91YmR3MzwyNzQ5Mzo6NjU2MzI2AA%3d%3d%23ISV%3a2%23IEO%3a65551%23QCF%3a4%23FPC%3aAgg8AgAA8DYAADwCAADwNgAAPAIAAPA2AAASAMODRQIAN2U3Km0DAMEVAQQkAA%3d%3d%22%2c%22range%22%3a%7B%22min%22%3a%2205C1DB7BBFBDC008323A3B67373962653567633866636235353A316362633A663537333667653333383762417569736662652F756264773300%22%2c%22max%22%3a%2205C1DB8525A774%22%7D%7D%5d

The nextLink in the SDK returned by the nextLink object is:
https://graph.microsoft.com/v1.0/teams/c7a2f0a6-bb37-40f2-b908-2305650b03ce/channels/19:7yFDiTCIS1sYT-rZ46tTn8PfZFTafi7pyhe1ml0RmhI1@thread.tacv2/messages#RT:1#TRC:20#RTD:AyAER1ygxSHVHJBn2S99BTI6Ozh6R0VqVURKVDJ0WlUuc1s1NnVVbzlRZ1dHVWJnajhtemlmMm5tMVNuaUoyQXVpc2ZiZS91YmR3MzwyNzQ5Mzo6NjU2MzI2AA==#ISV:2#IEO:65551#QCF:4#FPC:Agg8AgAA8DYAADwCAADwNgAAPAIAAPA2AAASAMODRQIAN2U3Km0DAMEVAQQkAA==%22,%22range%22:%7B%22min%22:%2205C1DB7BBFBDC008323A3B67373962653567633866636235353A316362633A663537333667653333383762417569736662652F756264773300%22,%22max%22:%2205C1DB8525A774%22%7D%7D]?$skiptoken=%5B%7B%22token%22%3A%22%2BRID%3A~vpsQAJ9uAC0sBo8AAAC8DQ%3D%3D
(this is the output of `NextPageRequest.GetHttpRequestMessage().RequestUri.AbsoluteUri`)

As seen in the second link (link returned by the SDK), the skipToken seems to be split up.
This makes it that we have an infinite loop. If using the PageIterator, an exception is raised with Detected nextLink loop

**To Reproduce**

I am running the following request:
```csharp
var messages = await graphClient
	.Teams[teamId.ToString()]
	.Channels[channelInfo.ChannelId]
	.Messages
	.Request()
	.GetAsync();

var allMessages = new List<ChatMessage>();
string previousNextLink = null;
do
{
	allMessages.AddRange(messages);
	var nextLink = messages.NextPageRequest.GetHttpRequestMessage().RequestUri.AbsoluteUri;
	System.Diagnostics.Debug.WriteLine(string.Format("{0} : {1}", nextLink, nextLink == previousNextLink));
	previousNextLink = nextLink;
}
while (messages.NextPageRequest != null && (messages = await messages.NextPageRequest.GetAsync()).Count > 0);
```

where teamId and channelId are ids similar to:
teamId: c7a2f0a6-bb37-40f2-b908-2305650b03ce
channelId: 19:7yFDiTCIS1sYT-rZ46tTn8PfZFTafi7pyhe1ml0RmhI1@thread.tacv2

**Expected behavior**
The NextLink in the SDK should be the same as the raw payload received.

**Client version**
Microsoft.Graph.Core: 2.0.5
Microsoft.Graph: 4.11.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
None

**Comment by DOMZE** [comment]
For information, there seems that there's a similar issue opened https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1144

**Comment by DOMZE** [comment]
Seems to have been corrected in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/341. Waiting on the 2.0.6 release of Microsoft.Graph.Core

**Comment by andrueastman** [comment]
Thanks @DOMZE,

This should now be resolved by https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/341 and by pulling https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.6
