### ISSUE TITLE
Application is unable to read presence, even wtih Presence.ReadWrite.All permission

### ISSUE THREAD

**Issue by chrisbardon** [microsoftgraph/msgraph-sdk-dotnet#1185]
I created a graph application with the Presence.ReadWrite.All permission (admin consented).  I created an app-credential GraphServiceClient, and this worked as expected:

```
var availability = "Busy";
var activity = "InACall";
var expirationDuration = new Duration("PT5M");
graphClient.Users[userID].Presence.SetPresence(availability, activity, AppId, expirationDuration).Request().PostAsync().GetAwaiter().GetResult();`

```

however this, did not:

```
            var presence = graphClient.Users[userID].Presence.Request().GetAsync().GetAwaiter().GetResult();
```

I realize that the docs state that application permissions are not supported for Read, but the permission is literally called.Presence.**Read**Write.All.  This makes no sense, so either:
1-The permission should be changed to Presence.Write.All
2-Graph should allow getting presence as an application

Clearly #2 is the better choice here...

**Comment by zengin** [comment]
Closing in favor of: https://github.com/microsoftgraph/microsoft-graph-docs/issues/15165

**Comment by mkhribech** [comment]
Thank you for your feedback, get presence app token is something we are planning in H1. Thank you for you patience as we work on this feature ask.
