### ISSUE TITLE
Search on SharedWithMe items

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#119]
I have a lot of shared Files and Folders from different users in OneDrive (Personal or Business). I want to perform search on the shared items. As we can search on the personal resource by below code:

var response = await client.Me.Drive.Root.Search(searchText).Request().GetAsync();

How can we perform search on SharedWithMe items?

**Comment by MIchaelMainer** [comment]
Thank you for contacting us! Repo issues should be used for identifying issues with the Microsoft Graph .Net client library. Questions about how to do something should be directed to StackOverflow as more people will find the questions and answers. Please post to StackOverflow with the [microsoftgraph] and [OneDrive] tags. Make sure you post what you've tried and the repro steps. Once you've posted, please provide a link in this issue.

**Comment by Saket0911** [comment]
@MIchaelMainer As suggested by you, posted the question on StackOverflow in below link:
https://stackoverflow.com/questions/43997236/search-on-sharedwithme-items-using-onedrive-api-sdk

Need your help in resolving this issue.

**Comment by MIchaelMainer** [comment]
Answered on SO
