### ISSUE TITLE
BadRequest: Invalid filter clause when searching the Graph for Users

### ISSUE THREAD

**Issue by quadmiasmo** [microsoftgraph/msgraph-sdk-dotnet#1190]
**Describe the bug**
Executing a filtered request for users with the SDK targeting the MS Graph API is resulting in an error:

Code: BadRequest
Message: Invalid filter clause
AdditionalData:
- date: 2021-12-04T23:42:46
- request-id: a20d8b5a-f21e-42ce-8281-823f1bd96b56
- client-request-id: a20d8b5a-f21e-42ce-8281-823f1bd96b56

**To Reproduce**
1. Get an instance of GraphServiceClient. We are using the [`AddMicrosoftGraph`](https://github.com/AzureAD/microsoft-identity-web/blob/eb618181d42599ee45e6ddf44ed919e2fa2f71ec/src/Microsoft.Identity.Web.MicrosoftGraph/MicrosoftGraphExtensions.cs#L26) extension method during startup of an ASP.NET Core web app to generate the instance.
2. Request Users with:
```c#
var filterText = "(mailNickname+eq+'aliasofuser')+and+(userType+eq+'Member'+or+onPremisesSyncEnabled+eq+true)";
var result = await _graphClient.Users
    .Request()
    .Select(u => new
    {
        u.Id,
        u.DisplayName,
        u.GivenName,
        u.Surname,
        u.Mail,
        u.MailNickname,
        u.OnPremisesSecurityIdentifier
    })
    .Filter(filterText)
    .Top(50)
    .GetAsync();
```
3. Invalid filter clause exception is the result

**Expected behavior**
The user(s) that the filter matches

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: any, issue is in backend
 - Version: MS Graph SDK 4.11.0

**Additional context**
We are currently porting a legacy ASP.NET MVC 5 web app to .NET 6 and the issue happens in the .NET 6 version. 
The legacy app is using version 3.3.0 of the SDK and doesn't have this issue (using the same filterText generation logic).
The .NET 6 version is able to make other requests that don't use filtering without any issue, such as `GraphClient.Users[objectId].Request().GetAsync()`

**Comment by andrueastman** [comment]
Hey @quadmiasmo,

Thanks for raising this.
Do you have any luck if you do this?

```cs
var filterText = "(mailNickname eq 'aliasofuser') and (userType eq 'Member' or onPremisesSyncEnabled eq true)";
var result = await _graphClient.Users
    .Request()
    .Select(u => new
    {
        u.Id,
        u.DisplayName,
        u.GivenName,
        u.Surname,
        u.Mail,
        u.MailNickname,
        u.OnPremisesSecurityIdentifier
    })
    .Filter(filterText)
    .Top(50)
    .GetAsync();
```

For V4 of the SDK we do encode the URL for you so as to allow the passing of data with special characters (such as an email with `+`) in them. So there is no need to user + as a space character.

**Comment by quadmiasmo** [comment]
Hi @andrueastman,

Thanks for the quick response. It works! I was certain I'd already tried this without success but it's working now.

**Comment by quadmiasmo** [comment]
Hi @andrueastman,

Thanks for the quick response. It works! I was certain I'd already tried this without success but it's working now.

Closing this issue.
