### ISSUE TITLE
Setting resourceBehaviorOptions is not possible using the client library

### ISSUE THREAD

**Issue by is-dmartos** [microsoftgraph/msgraph-sdk-dotnet#1193]
We have a tool in place that provisions different types of groups using the Graph client library and, in order to set specific resourceBehaviorOptions we were using the Beta client because it was the only way to do it. Some days back this stopped working and, after reading some docs, it looked like this was now something provided by the official API.

https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http

Unfortunately, I have been unable to find this property in the Group model so, unless I missed something, it looks like it's not possible to specify this options now neither with the beta endpoint nor with the standard one.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/model/Group.cs

**Comment by zengin** [comment]
@is-dmartos could you please elaborate on how it stopped working? `resourceBehaviorOptions` is still available in the Beta SDK:
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/Group.cs#L252

**Comment by is-dmartos** [comment]
@zengin thanks for your quick feedback. We implemented the provisioning functionality a while ago and one day, without any implementation changes I was aware of, started failing on some customers. After investigating the issue we realized it was only happening when we were setting a value for WelcomeEmailDisabled within the resourceBehaviorOptions property. I debugged the code back then and verified that the call to the Graph API was failing with a 400 error when this setting was specified and assumed it was just because this option was added to the public API because I saw it's available when using the REST API. If this setting is not yet available using the client library I will go back to investigate why the beta library stopped working, but I would be more comfortable using the public one :).

**Comment by zengin** [comment]
@is-dmartos as far as I can tell this property is not in the V1 API yet. Documentation shows this property only in the response fields, which makes it not settable. According to the docs [here](https://docs.microsoft.com/en-us/graph/group-set-options#configuring-and-provisioning-groups), WelcomeEmailDisabled value should work. Please test with the Beta SDK and let us know if this doesn't work. I will then redirect the question to the service teams.

**Comment by is-dmartos** [comment]
Thanks again @zengin for your extremely quick response. Really appreciated. It's probably me not understanding the documentation properly but it looks to me that these settings were basically applicable when creating groups, where probably setting values is what makes sense.

![image](https://user-images.githubusercontent.com/85878792/145625935-0efd53b4-3d6b-441d-8ffe-f7a482e46c2d.png)

I will give it another try with the original code and try to see why it's failing with the beta client.

**Comment by zengin** [comment]
The title indicates that this is in preview:

> Set Microsoft 365 group behaviors and provisioning options **(preview)**

**Comment by is-dmartos** [comment]
You are totally right. I will troubleshoot it again with the beta client and will explore moving to the public endpoint once this is available.

**Comment by is-dmartos** [comment]
Hi @zengin. I just deployed the code that was using the beta endpoint to create groups requiring group behaviors and, when executing the POST operation, I get the following exception:

`Microsoft.Graph.Beta: Method not found: 'Void Microsoft.Graph.BaseRequest.set_Method(System.String)'`

The Group object I am passing is the same one I was passing some weeks ago so this is why I assumed something changed in the API and now I should use the 1.0 endpoint. Now that I know this should not be the root cause of the issue I have troubleshooted it by using Graph Explorer and I have started with the original body and narrowed it down to the setting that is actually causing the error. Some weeks ago I was using the following API body to create a group:

```
{
    "description": "description",
    "displayName": "displayName",
    "groupTypes": [
        "Unified"
    ],
    "mailEnabled": true,
    "mailNickname": "mailNickName",
    "resourceBehaviorOptions": [
        "WelcomeEmailDisabled"
    ],
    "securityEnabled": false,
    "additionalData": {
        "owners@odata.bind": [
            "https://graph.microsoft.com/v1.0/users/david.martos@mvp.onmicrosoft.com"
        ]
    }
}
```

If I change the way I set the owners to something like this, it works perfectly.

```
{
    "description": "description",
    "displayName": "displayName",
    "groupTypes": [
        "Unified"
    ],
    "mailEnabled": true,
    "mailNickname": "mailNickName",
    "resourceBehaviorOptions": [
        "WelcomeEmailDisabled"
    ],
    "securityEnabled": false,
    "owners@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/david.martos@mvp.onmicrosoft.com"
    ]
}
```

Using the 1.0 endpoint, the first snippet works without any issues, of course, removing the resourceBehaviorOptions attribute.

**Comment by is-dmartos** [comment]
@zengin I finally found one of our projects had a very updated version of the beta client library. Updated it and now the original code is working again. Sorry for the inconvenience.

**Comment by zengin** [comment]
@is-dmartos no worries, glad to hear that this works for you.
