### ISSUE TITLE
IPublicClientApplication.AcquireTokenInteractive.ExecuteAsync hangs If I add DateTimePicker on Windows Form.

### ISSUE THREAD

**Issue by Nasoki-Koide** [microsoftgraph/msgraph-sdk-dotnet#1197]
**Describe the bug**
I' m using C# on Visual Studio Express 2017, .NET Framework 4.8.
When I add DateTimePicker on Windows Form, IPublicClientApplication.AcquireTokenInteractive.ExecuteAsync hangs infinitely if I call such method from such Form. For reference, I' m using WebView2 for authentication.

I tested same method on the Form which does not contains DateTimePicker, it worked. And Even if the Form contains DateTimePicker, if I call ExecuteAsync in another thread (I wrapped it by Task), it works too.

**To Reproduce**
1. Add DateTimePicker to Windows Form.
2. Call IPublicClientApplication.AcquireTokenInteractive.ExecuteAsync from the Form mentioned above.
3. Never reach to following step.

**Expected behavior**
Reach to following step.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Nasoki-Koide** [comment]
Hi @andrueastman ,

Thank you very much! I tried the latest version of Microsoft.Graph (v4.18.0) and no error occurs! According to the description of microsoft.graph.nuspec, the version of Microsoft.Graph.Core is v2.0.7. So it's bit old, but no problem, it works fine!

**Comment by andrueastman** [comment]
Thanks for the feedback @Nasoki-Koide.

Closing this for now. Feel free to create a new issue in case of any issues/questions.
