### ISSUE TITLE
DriveItem permissions: Inconsistency between GrantedToV2 and GrantedTo resources for Personal account

### ISSUE THREAD

**Issue by 23W** [microsoftgraph/msgraph-sdk-dotnet#1199]
**Describe the bug**
Application code has been updated to use new recourse `GrantedToV2` instead of deprecated `GrantedTo`. But behavior of this recourse was changed. For personal account (Ms Live Account) and shared with user drive item, MS Graph request `client.Drives[DiskId].Items[ItemId].Permissions.GetAsync()` returns IDriveItemPermissionsCollectionPage collection with filled `GrantedTo` resource but `GrantedToV2` is null!

**To Reproduce**
1. Sign-in with credentials of personal account
2. Request permissions for some shared with this account drive item ()
3. `GrantedToV2` is null 

**Expected behavior**
When drive item was shared with this account explicitly,  `GrantedToV2` must not be null and should contain filled `user` identity.

**Desktop:**
 - OS: Windows 10
 
**Screenshots:**
![image](https://user-images.githubusercontent.com/11534020/146006551-1119ae29-a32c-4fa1-99db-be446d98e7f2.png)

**Comment by MIchaelMainer** [comment]
@23W Have you had the opportunity to observe this behavior for an organizational account? I suspect that we may have an unintentional difference in behavior between the personal and org account types.

This certainly conflicts with the docs. https://docs.microsoft.com/en-us/graph/api/permission-get?view=graph-rest-1.0&tabs=http. I'm not seeing the `@deprecated.GrantedTo` in your results as AdditionalData is null. 

@ificator In case you have insights here.

**Comment by 23W** [comment]
@MIchaelMainer 
Everything is ok with organizational accounts.

> I'm not seeing the @deprecated.GrantedTo in your results as AdditionalData is null.
Please look at https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0
In properties table:
> grantedTo (deprecated)
> grantedToIdentities (deprecated)

**Comment by andrueastman** [comment]
I've posted the query at the link below so that we may get feedback from the API owners on whether this is a known difference between the personal/organizational accounts as this is a query for the API side of things. 

https://learn.microsoft.com/en-us/answers/questions/1079737/inconsistency-between-grantedtov2-and-grantedto-re.html

We'll close this one for now so that it may be followed up from there.
