### ISSUE TITLE
Need total count while fetching the resources from OneDrive

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#120]
As per the specs, we can get a maximum of 200 item when we retrieve the list of files and folders from OneDrive(Personal or Business) along with the NextPageLink. However, I also need to get the total count of files available while getting the list of files and folders from:

1.) Root
2.) Shared With Me
3.) Inside the DriveItem
4.) Search

How can I achieve this?

**Comment by MIchaelMainer** [comment]
Thank you for contacting us! Repo issues should be used for identifying issues with the Microsoft Graph .Net client library. Questions about how to do something should be directed to StackOverflow as more people will find the questions and answers. Please post to StackOverflow with the [microsoftgraph] and [OneDrive] tags. Make sure you post what you've tried and the repro steps. Once you've posted, please provide a link in this issue.

**Comment by Saket0911** [comment]
@MIchaelMainer As suggested by you, posted the question on StackOverflow in below link:
https://stackoverflow.com/questions/43997455/need-total-count-while-fetching-the-resources-from-onedrive

Need your help regarding this.

**Comment by MIchaelMainer** [comment]
Answered on SO
