### ISSUE TITLE
Add support for updating the body of an email

### ISSUE THREAD

**Issue by maffer1** [microsoftgraph/msgraph-sdk-dotnet#1201]
**Is your feature request related to a problem? Please describe.**
We are migrating an application, that archives emails, from EWS to Microsoft Graph. After the application archives an email in our DMS system it deletes all attachments and adds a text like "E-Mail was archived on ..." to the body of the original email.
According to your documentation, this feature is not supported by Microsoft Graph: [UpdateMessage](https://docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-1.0&tabs=http)  

![image](https://user-images.githubusercontent.com/80394906/146152165-4f1d6133-3dfe-4b32-ac91-c9e11e1d734f.png)

I use the below code to make an update. Most of the time it is successful but intermittently the following exception is thrown:

> Status Code: PreconditionFailed
> Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
> Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
> ClientRequestId: 7512ab66-cb84-4e70-8d1e-44e2ee2acb61
> ...

**Describe the solution you'd like**
I want you to support the update of an email body by using the following (simplified) code that replaces the email body:

```
        private async Task<Message> UpdateMessageAsync()
        {
            Message updatedMessage = new Message();
            updatedMessage.Body = new ItemBody();
            updatedMessage.Body.ContentType = Microsoft.Graph.BodyType.Text;
            updatedMessage.Body.Content = "The email was archived on ...";

            return await GraphServiceClient
                .Users[CurrentUser.Id]
                .MailFolders[CurrentFolder.Id]
                .Messages[ItemId]
                .Request()
                .UpdateAsync(updatedMessage);
        }
```

**Describe alternatives you've considered**
I tried to delete the attachments and update the message body with a batch request, but got the notorious exception ErrorIrresolvableConflict.

**Additional context**
OS: Windows 11 on client-side
Microsoft Graph SDK 4.11.0

**Comment by MIchaelMainer** [comment]
It sounds like the message body is updateable and that the documentation is incorrect. I'm curious, in your batch request, do you order the delete attachment before the update message body? Also, do you use the dependsOn option so that 2nd operation occurs only after the first operation is successful?

Also, do you encounter this error when you don't use batch?

**Comment by maffer1** [comment]
1) Code without a batch request
I want that my code works without a batch request. Thus, I tested four scenarios with 100 emails.
A) I delete all attachments of an email, then I update the email body.
B) I update the email body, then I delete all attachments.
C) I only delete all attachments of an email.
D) I only update the email body.
In both scenarios, ErrorIrresolvableConflict is intermittently thrown.

I already submitted an issue to github reporting these problems: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1195

There I describe the problem in detail. Here a description of my test scenario in a nutshell: When trying to delete the attachments and update the body of about 100 emails in a loop, this will be successful in most cases, but in some cases (5-10), the exception ErrorIrresolvableConflict will be thrown – because either a delete attachment or the update of the email body fails.

My code how I delete the attachments:

                 public void DeleteAttachments(List<string> attachmentIds)
        {
            foreach (var attachmentId in attachmentIds)
            {
                Task.Run(() => DeleteAttachmentAsync(attachmentId)).GetAwaiter().GetResult();
            }
        }

                 private async Task DeleteAttachmentAsync(string id)
        {
            //await Task.Delay(1000);

           await GraphServiceClient
                .Users[CurrentUser.Id]
                .MailFolders[CurrentFolder.Id]
                .Messages[CurrentMessage.Id]
                .Attachments[id]
                .Request()
                .DeleteAsync();
        }

I do not see why this code could throw an ErrorIrresolvableConflict because I do not define the If-Unmodified-Since or If-None-Match headers.

2) Code with a batch request
I tested a batch request that only updates the body of one email. The ErrorIrresolvableConflict exception is intermittently thrown.



Paul Mafli
Softwareentwicklung

E-Mail:    ***@***.******@***.***>

Kendox AG · Bahnhof-Strasse 7 · CH-9463 Oberriet SG
www.kendox.com<http://www.kendox.com> · ***@***.******@***.***> · +41 (71) 552 34 00

***@***.***<https://www.linkedin.com/company/kendox-ag>    ***@***.*** <https://www.xing.com/companies/kendoxag>     ***@***.*** <https://www.youtube.com/channel/UCDZ3H4Kc_m_UMdjRvVoxYtA>     ***@***.*** <https://www.facebook.com/kendox.ag/>

Handelsregisteramt des Kantons St. Gallen · CH-020.3.027.687-4 Kendox AG · UID-Nummer CHE-110.625.426 MWST

**Comment by maffer1** [comment]
Test: Trying to delete four attachments with a batch request from an email returns as response ErrorIrresolvableException with the second,  third, and fourth attachment. What is wrong with this code?

```
        private async Task BatchDeleteAttachmentsAsync(List<string> attachmentIds)
        {
            // Total number of items per batch, supported is 20
            int maxNoBatchItems = 20;
            try
            {
                // if the requests are more than 20 limit, we need to create multiple batches of the BatchRequestContent
                List<BatchRequestContent> batches = new List<BatchRequestContent>();
                var batchRequestContent = new BatchRequestContent();
                for (int i = 0; i < attachmentIds.Count; i++)
                {
                    var httpRequestMessage = new HttpRequestMessage(HttpMethod.Delete, $"https://graph.microsoft.com/v1.0/users/{CurrentUser.Id}/mailfolders/{CurrentFolder.Id}/messages/{CurrentMessage.Id}/attachments/{attachmentIds[i]}")
                    {
                            };
                    httpRequestMessage.Headers.TryAddWithoutValidation("Content-Type", "application/json; charset=utf-8");

                    BatchRequestStep requestStep = new BatchRequestStep(attachmentIds[i], httpRequestMessage, null);
                    batchRequestContent.AddBatchRequestStep(requestStep);
                    if ((i + 1) % maxNoBatchItems == 0)
                    {
                        batches.Add(batchRequestContent);
                        batchRequestContent = new BatchRequestContent();
                    }
                }
                if (batchRequestContent.BatchRequestSteps.Count < maxNoBatchItems)
                {
                    batches.Add(batchRequestContent);
                }

                if (batches.Count == 0 && batchRequestContent != null)
                {
                    batches.Add(batchRequestContent);
                }

                foreach (BatchRequestContent batch in batches)
                {
                    BatchResponseContent response = null;
                    response = await GraphServiceClient.Batch.Request().PostAsync(batch);
                    Dictionary<string, HttpResponseMessage> responses = await response.GetResponsesAsync();
                    foreach (string key in responses.Keys)
                    {
                        HttpResponseMessage httpResponse = await response.GetResponseByIdAsync(key);
                        var responseContent = await httpResponse.Content.ReadAsStringAsync();
                        if (!string.IsNullOrEmpty(responseContent))
                        {
                            JObject response = JObject.Parse(responseContent);
                        }
                        //do something below
                    }
                }
            }
            catch (Exception ex)
            {
                LogWriter.WriteMessage(ex.Message + ex.StackTrace);
                throw;
            }

        } 
```

**Comment by MIchaelMainer** [comment]
I don't think there is anything wrong with your code or the client library. This looks like service issue. 

I'm curious, did you find support for If-Unmodified-Since or If-None-Match in the documentation? I wasn't aware that those headers are respected.

For the attachments not deleted when you get the ErrorIrresolvableConflict exception, are you able to delete them at later time, or do attempts to delete them always result in ErrorIrresolvableConflict? Also, are the attachments fileattachments or itemattachments, or a mix of both?

**Comment by maffer1** [comment]
“I don't think there is anything wrong with your code or the client library. This looks like service issue.”

I agree with you.

“I'm curious, did you find support for If-Unmodified-Since or If-None-Match in the documentation? I wasn't aware that those headers are respected.”

No, I did not find any documentation for these headers . And I do not use these headers as I confirmed with fiddler.

A Microsoft supporter told me that these headers could cause an ErrorIrresolvableConflict exception. But he could not help me.

“For the attachments not deleted when you get the ErrorIrresolvableConflict exception, are you able to delete them at later time, or do attempts to delete them always result in ErrorIrresolvableConflict? Also, are the attachments fileattachments or itemattachments, or a mix of both?”

I always test with the same scenario: 100 Copies of the same email that has six file attachments. Looping through all these emails and deleting attachments and updating email properties causes some ErrorIrresolvableConflict. Repeating this process once or more times, all attachments are removed and the properties are set correctly. My guess: The ErrorIrresolvableConflict exception is thrown intermittendly.

What can be done with this problem. It is vital for our MailArchiver application that deleting attachments and updating email properties works reliable, otherwise our application will be useless.






Paul Mafli
Softwareentwicklung

E-Mail:    ***@***.******@***.***>

Kendox AG · Bahnhof-Strasse 7 · CH-9463 Oberriet SG
www.kendox.com<http://www.kendox.com> · ***@***.******@***.***> · +41 (71) 552 34 00

***@***.***<https://www.linkedin.com/company/kendox-ag>    ***@***.*** <https://www.xing.com/companies/kendoxag>     ***@***.*** <https://www.youtube.com/channel/UCDZ3H4Kc_m_UMdjRvVoxYtA>     ***@***.*** <https://www.facebook.com/kendox.ag/>

Handelsregisteramt des Kantons St. Gallen · CH-020.3.027.687-4 Kendox AG · UID-Nummer CHE-110.625.426 MWST

**Comment by MIchaelMainer** [comment]
In the short-term, I advise that you add a retry routine.

I'm going to raise this issue with the team that owns the data access layer. Let's see if we can get this addressed. Can you provide timestamps and associated ClientRequestId from the exception?

> The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.

**Comment by maffer1** [comment]
In the last run the UpdateMessage() method threw only ErrorIrresolvableConflict exceptions. Here are the ClientRequestIds:

12/20/2021 10:10:31 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: ea1ca119-5dce-496a-bdee-f9a9d45a4509

12/20/2021 10:10:37 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: c8b41186-873a-4012-9e2f-264bb03036f9

12/20/2021 10:11:48 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: 0e122481-e02c-4b4b-a1d5-a699aee5b9a0

12/20/2021 10:11:57 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: 68096d6b-52b5-4f61-b871-1a8f51feb96b

12/20/2021 10:13:12 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: b412d6fc-bde5-4dd4-b166-2f6155a7be5d

12/20/2021 10:13:17 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: 45ac0ed4-dc9b-47cc-9d73-1048611ab061

12/20/2021 10:13:22 AM: Error while changing item subject [test 6 attachments 10-12-2021]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: 7de31183-5e4f-476a-a346-4fdaa4f2b174

And here is a ClientRequestId when deleting an exception threw an ErrorIrresolvableConflict exception:

12/10/2021 2:19:11 PM: Error while changing item subject [test 4 attachments]: Status Code: PreconditionFailed
Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item., Cannot save changes made to an item to store.SaveStatus: IrresolvableConflict
PropertyConflicts:

ClientRequestId: d0d350ba-4f58-41e3-9d40-8aee6b7cf1d9


Paul Mafli
Softwareentwicklung

E-Mail:    ***@***.******@***.***>

Kendox AG · Bahnhof-Strasse 7 · CH-9463 Oberriet SG
www.kendox.com<http://www.kendox.com> · ***@***.******@***.***> · +41 (71) 552 34 00

***@***.***<https://www.linkedin.com/company/kendox-ag>    ***@***.*** <https://www.xing.com/companies/kendoxag>     ***@***.*** <https://www.youtube.com/channel/UCDZ3H4Kc_m_UMdjRvVoxYtA>     ***@***.*** <https://www.facebook.com/kendox.ag/>

Handelsregisteramt des Kantons St. Gallen · CH-020.3.027.687-4 Kendox AG · UID-Nummer CHE-110.625.426 MWST
