### ISSUE TITLE
Support for onlineMeeting attendanceReports?

### ISSUE THREAD

**Issue by enkelmedia** [microsoftgraph/msgraph-sdk-dotnet#1203]
Hi!

I just noticed the official support for meeting attendance report in the API: https://docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-1.0

I can see that this docs-article was added 2021-12-15, the latest update of the SDK was 20212-12-14 - how does this process work? How often is the SDK updated and when will these new api-capabilities be included in the API?

Cheers!

**Comment by andrueastman** [comment]
Hey @enkelmedia,

Thanks for raising this. 

We typically update the SDKs once a week (around Tuesdays) where we pull the latest metadata from the APIs to generate the new SDK version. 
I can't speak for whether the onlineMeeting update will be there this week right now but you can check out for updates later in the week to confirm this.

**Comment by enkelmedia** [comment]
Thanks for getting back so fast! I get the process, I'll close the issue and look out for the update.

All the best!
