### ISSUE TITLE
[Client bug]: Get Teams channel message with pagination

### ISSUE THREAD

**Issue by rlodev67** [microsoftgraph/msgraph-sdk-dotnet#1204]
**Describe the bug**
When requesting the messages from a team channel, the method to get the next page result return the same result and ignore the "top" query parameter

**To Reproduce**
```
List<ChatMessage> toReturn = new List<ChatMessage>();
            if (this.graphClient != null && TeamId != null && ChannelId != null)
            {
                var res = this.graphClient.Teams[TeamId].Channels[ChannelId].Messages.Request().Top(50).GetAsync();
                res.Wait();
                while (res.Result != null && res.Result.Count > 0)
                {
                    toReturn.AddRange(res.Result.CurrentPage);
                    if(res.Result.NextPageRequest != null)
                    {
                        Console.WriteLine(res.Result.NextPageRequest.RequestUrl);
                        res.Result.InitializeNextPageRequest(this.graphClient,null);
                        res = res.Result.NextPageRequest.GetAsync();
                        res.Wait();
                    }
                    else 
                    {
                        break; 
                    }
                }
                return res.Result;

            }
            return null;
```

**Expected behavior**
Getting the next page

**Client version**
4.11.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser .NET

**Additional context**
I checked with fiddler and it looks like the correct URL is returned for the @odata.nextLink.

Does anyone have a workarround ?

**Comment by andrueastman** [comment]
Hey @rlodev67,

Thanks for raising this,

Any chance you are still able to replicate this using the latest version of the SDK v4.12.0? We had a similar issue resolved with the latest version at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1144

**Comment by rlodev67** [comment]
Hey @andrueastman,

Yes, this issue is resolved with Microsoft.Graph.Core (2.0.6)

Thanks for your feedback. :)
