### ISSUE TITLE
Some Internet Message Headers are not returning when retrieving Item Attachment content

### ISSUE THREAD

**Issue by piyumi25** [microsoftgraph/msgraph-sdk-dotnet#1208]
**Describe the bug**
I have a requirement to get all internet message headers belongs to an item attachment attached to an Outlook message. I have used following Graph API call to read item attachment content. https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#example-3-expand-and-get-the-properties-of-the-item-attached-to-a-message
I was able to get some internet message headers, but not all the headers of the item attachment.

I found this link https://stackoverflow.com/questions/60947499/get-message-using-graph-missing-some-internetmessageheaders explains about how to get missing internet message headers. but I got "Bad Request" error in my case.

**To Reproduce**
1. Go to 'MS Graph Explorer'
2. Try to retrieve item attachment content using /messages/message-id/attachments/attachment-id/?$expand=microsoft.graph.itemattachment/item
3. Double check with using MHA or File=>properties=>internet message headers in Outlook Desktop
4. You can see some missing headers

**Expected behavior**
Should be able to see all headers

**Screenshots**
`var itemAttachment = await graphServiceClient.Users["11805967-f79a-4e1e-aac9-08bca571dd9f"]
                    .Messages[messageId]
                    .Attachments[messageWithItemAttachment[0].Id]
                    .Request()
                    .Expand($"microsoft.graph.itemAttachment/item")
                    .GetAsync();`
`var item = itemAttachment.GetType().GetProperty("Item")?.GetValue(itemAttachment, null) as Microsoft.Graph.Message;`
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MIchaelMainer** [comment]
I've inquired about this issue. Let me see if I can get more information.

**Comment by hemakaranth** [comment]
We are hitting the same issue. Any updates ?

**Comment by andrueastman** [comment]
Hey @hemakaranth and @piyumi25,

Any chance this is still an issue? 
From our end comparing the internet headers from outlook and the graph response yield the same results now when checking a message or whether it's an attachment.

**Comment by erSitzt** [comment]
Hi, is this still an issue ?
Can anyone confirm if this happens all the time or if it is an intermittent issue ?

I'm using the `X-MS-Exchange-Generated-Message-Source: Antispam Quarantine Agent` header in Redmine to identify mails that have an `Auto-Submitted: auto-generated` header, but should still be processed as they were released from quarantine by a user...

This seems to work most of the time, but sometimes the header is just missing (accessing msgraph from redmine/ruby).
Checking the mail in Outlook i can verify they exist.
