### ISSUE TITLE
Please help: how to setup the timeout for InteractiveBrowserCredential and make it work with GraphServiceClient?

### ISSUE THREAD

**Issue by xiaomi7732** [microsoftgraph/msgraph-sdk-dotnet#1209]
Here's the scenario I am trying to implement (WPF, .NET 6):
1. GraphServiceClient is created with InteractiveBrowserCredential.
2. Start the application, using the graphClient to access OneDrive(File), browser prompt shows up for user sign in.
3. Instead of sign in normally, **close out the pop up for credential directly**.

I want to handle it - simple prompt that the user authentication didn't happen in given time and cancel the access to OneDrive will do.

However, I have 2 problems:

1. I can't seem to find out a way to specify the timeout;
2. There seems no way to catch the timeout exception or any exception, or is there?

Please help.

Code for creating GraphServiceClient:

```csharp
            InteractiveBrowserCredentialOptions options = new InteractiveBrowserCredentialOptions
            {
                TenantId = graphAPIOptions.TenantId,
                ClientId = graphAPIOptions.ClientId,
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
                RedirectUri = new Uri(graphAPIOptions.RedirectUri),
            };
            InteractiveBrowserCredential credential = new InteractiveBrowserCredential(options);
            GraphServiceClient graphClient = new GraphServiceClient(credential, graphAPIOptions.Scopes);

            return graphClient;
```

Code to consume the graphClient (hanging on user close the authentication pop up):

```csharp
            DriveItem appRootItem = await _graphServiceClient.Me.Drive.Special.AppRoot.Request().GetAsync(cancellationToken).ConfigureAwait(false);
```

FWIW, it works well when the user sign in with proper username/password in the pop up.

Packages:

```xml
    <PackageReference Include="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="Microsoft.Graph" Version="4.10.0" />
```

**Comment by xiaomi7732** [comment]
To leave a trace, here's a workaround I used for the scenario:
- invoking GetTokenAsync() in a separate step

It works, it is at best ... ugly:

```csharp
class GraphTokenCredential : TokenCredential
{
            public async Task SignInAsync(TimeSpan timeout, CancellationToken cancellationToken = default)
            {
                    _credential = _credential ?? new InteractiveBrowserCredential(_credentialTokenOptions);  // real token credential
                    TokenRequestContext context = new TokenRequestContext(_graphAPIOptions.Scopes!); // Provide scopes
                    using (CancellationTokenSource timeoutTokenSource = new CancellationTokenSource(timeout))
                    using (CancellationTokenSource linkedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutTokenSource.Token))
                    {
                         // Timeout access token will request cancel upon timeout when the user close the sign in window. Unfortunately, the same token with timeout doesn't work for graph client request, the request task will hang there, it looks like it just won't handle the cancellation token, and leads to leak.
                        _knownAccessToken = await _credential.GetTokenAsync(context, linkedTokenSource.Token);
                        ...
                    }
            }
}
```

**Comment by andrueastman** [comment]
Hey @xiaomi7732,

Thanks for raising this issue. 

There is an issue with the SDK where the cancellation token being used in the request is not forwarded to the tokenCredential as your example does.

I believe you can also work around this by doing something like what is below.

```cs
InteractiveBrowserCredentialOptions options = new InteractiveBrowserCredentialOptions
{
    TenantId = graphAPIOptions.TenantId,
    ClientId = graphAPIOptions.ClientId,
    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
    RedirectUri = new Uri(graphAPIOptions.RedirectUri),
};
InteractiveBrowserCredential credential = new InteractiveBrowserCredential(options);
GraphServiceClient graphClient = new GraphServiceClient(credential, graphAPIOptions.Scopes);

// Call the authenticate method with our own cancellation token first to get the auth credentials
CancellationToken cancellationToken = new CancellationToken();
await credential.AuthenticateAsync(new TokenRequestContext(_graphAPIOptions.Scopes),cancellationToken);

// Make the request as we already have the token info
DriveItem appRootItem = await graphClient.Me.Drive.Special.AppRoot.Request().GetAsync(cancellationToken).ConfigureAwait(false);
```

**Comment by andrueastman** [comment]
We've addressed this in preview of v5 of the SDK now.

The cancellation token is now passed to the authentication provider as seen [here](https://github.com/microsoft/kiota-http-dotnet/blob/9951711e0948609d3255faa04f553c9569614cf0/src/HttpClientRequestAdapter.cs#L310). This is then forwarded to the [AccessTokenProvider](https://github.com/microsoft/kiota-abstractions-dotnet/blob/8a136e509c7a71ef889643f047938bdbc3c752be/src/authentication/BaseBearerTokenAuthenticationProvider.cs#L42) which finally gets to the [tokencredential](https://github.com/microsoft/kiota-authentication-azure-dotnet/blob/8e5eecc03b947b2296b928632b2afd3ed298f206/src/AzureIdentityAccessTokenProvider.cs#L68).
