### ISSUE TITLE
@search.approximateCount not available in the search's response of SDK

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#121]
As per the specs, I should be getting @search.approximateCount field when I perform search in OneDrive. However, when I use below code:

var response = await client.Me.Drive.Root.Search(searchText).Request().GetAsync();

I am not able to find any approximate count attribute? How can I get this count?

**Comment by MIchaelMainer** [comment]
Thank you for contacting us! Repo issues should be used for identifying issues with the Microsoft Graph .Net client library. Questions about how to do something should be directed to StackOverflow as more people will find the questions and answers. Please post to StackOverflow with the [microsoftgraph] and [OneDrive] tags. Once you've posted, please provide a link in this issue.

**Comment by Saket0911** [comment]
@MIchaelMainer As suggested by you, posted the question on StackOverflow in below link:
https://stackoverflow.com/questions/43997598/approximatecount-not-available-in-the-searchs-response-of-onedrive-api-sdk

Need your help in resolving this issue.

**Comment by MIchaelMainer** [comment]
Not an issue with the Graph
