### ISSUE TITLE
UnknownError when creating an OnlineMeeting

### ISSUE THREAD

**Issue by rhalaly** [microsoftgraph/msgraph-sdk-dotnet#1215]
**Describe the bug**
Creating a new OnlineMeeting instance causes an "UnknownError" exception.

**To Reproduce**
1. Copy the C# example for creating an OnlineMeeting from [here](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=csharp)
2. Create an application with **Application** permission type and **OnlineMeetings.ReadWrite.All** permission.
3. Run the code using an existing user (instead of `Me`).

**Expected behavior**
The request should be succeeded.

**Screenshots**
(`organizerId` is the organizer email address)

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/8597700/148401730-83182e32-7662-4034-9d81-c275b355d634.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Not relevant
 - Version: Graph Client Nuget 4.13.0

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
None

**Comment by andrueastman** [comment]
Hey @rhalaly,

Thanks for raising this.

I have looked at the request logs and the API is returning a 404 error response suggesting the user could not be found.

According to the note in the docs [here](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=csharp#http-request), the `userId` should not be the email address. 

![image](https://user-images.githubusercontent.com/6464005/148501171-125322b1-e4ff-4e0b-be5c-493b58eda8ae.png)

Any chance you could use the correct userId and confirm this works out for you?

**Comment by rhalaly** [comment]
Thank you! I missed that note. I will try it soon. 

But, anyway, I think it worth to change the error to more meaningful one. You have the logs and you can see that it is 404, but on the client side it says "UnkownError" and I can't do nothing with such error.

**Comment by andrueastman** [comment]
No worries @rhalaly.

Unfortunately, that error code is simply the response the API responds with which the SDK presents back to the user. 
We try to help the user by adding more information to the [ServiceException](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/09f2fd05546d1d78b2660da9c001bdab1e8f1cef/src/Microsoft.Graph.Core/Exceptions/ServiceException.cs#L72) (such as the http status code) though which may have more information in its properties. 

Looking forward to hearing back if it works out.

**Comment by rhalaly** [comment]
@andrueastman it works with Object ID. Thansk! Closing...
