### ISSUE TITLE
Serialization Issues of Graph Objects

### ISSUE THREAD

**Issue by dkonyayev** [microsoftgraph/msgraph-sdk-dotnet#1219]
We have started to observe a serialization issue when upgrading from Microsoft.Graph version 3 to version 4+. Our project is using .NET Core 3.1

For our project we are using Graph to build Event object and then invoke a call to Microsoft Graph v1 to create new Outlook event. 

### Expected behavior

The object is serialized similar to following. This is working correctly in version 3.X
a) Properties with NULL values are ignored
b) Properties with ENUM are serialized as text values
c) Property "ODataType" is serialized as annotated property name "@odata.type"

{
  "isReminderOn": false,
  "subject": "PTO",
  "body": {
    "contentType": "text",
    "content": "PTO - 300004760084287",
    "@odata.type": "microsoft.graph.itemBody"
  },
  "bodyPreview": "Microsoft.Graph.ItemBody",
  "start": {
    "dateTime": "4/22/2022 12:00:00 AM",
    "timeZone": "UTC",
    "@odata.type": "microsoft.graph.dateTimeTimeZone"
  },
  "end": {
    "dateTime": "4/23/2022 12:00:00 AM",
    "timeZone": "UTC",
    "@odata.type": "microsoft.graph.dateTimeTimeZone"
  },
  "locations": [
    {
      "displayName": "300004760084287",
      "@odata.type": "microsoft.graph.location"
    }
  ],
  "isAllDay": true,
  "responseRequested": false,
  "showAs": "oof",
  "attendees": [
    {
      "type": "required",
      "emailAddress": {
        "address": "test@test.com",
        "@odata.type": "microsoft.graph.emailAddress"
      },
      "@odata.type": "microsoft.graph.attendee"
    }
  ],
  "@odata.type": "microsoft.graph.event"
}

### Actual behavior
After upgrading to version 4+ we observed the following behaviors during serialization:
a) Properties with NULL values are included
b) Properties with ENUM are serialized as numeric ENUM values
c) Property "ODataType" is serialized as "ODataType"

{
  "AllowNewTimeProposals": null,
  "Attendees": [
    {
      "ProposedNewTime": null,
      "Status": null,
      "Type": 0,
      "EmailAddress": {
        "Address": "test@test.com",
        "Name": null,
        "AdditionalData": null,
        "ODataType": null
      },
      "AdditionalData": null,
      "ODataType": "microsoft.graph.attendee"
    }
  ],
  "Body": {
    "Content": "PTO - 300004760056835",
    "ContentType": 0,
    "AdditionalData": null,
    "ODataType": null
  },
  "BodyPreview": "Microsoft.Graph.ItemBody",
  "End": {
    "DateTime": "4/23/2022 12:00:00 AM",
    "TimeZone": "Eastern Standard Time",
    "AdditionalData": null,
    "ODataType": null
  },
  "HasAttachments": null,
  "HideAttendees": null,
  "ICalUId": null,
  "Importance": null,
  "IsAllDay": true,
  "IsCancelled": null,
  "IsDraft": null,
  "IsOnlineMeeting": null,
  "IsOrganizer": null,
  "IsReminderOn": false,
  "Location": null,
  "Locations": [
    {
      "Address": null,
      "Coordinates": null,
      "DisplayName": "300004760056835",
      "LocationEmailAddress": null,
      "LocationType": null,
      "LocationUri": null,
      "UniqueId": null,
      "UniqueIdType": null,
      "AdditionalData": null,
      "ODataType": null
    }
  ],
  "OnlineMeeting": null,
  "OnlineMeetingProvider": null,
  "OnlineMeetingUrl": null,
  "Organizer": null,
  "OriginalEndTimeZone": null,
  "OriginalStart": null,
  "OriginalStartTimeZone": null,
  "Recurrence": null,
  "ReminderMinutesBeforeStart": null,
  "ResponseRequested": false,
  "ResponseStatus": null,
  "Sensitivity": null,
  "SeriesMasterId": null,
  "ShowAs": 3,
  "Start": {
    "DateTime": "4/22/2022 12:00:00 AM",
    "TimeZone": "Eastern Standard Time",
    "AdditionalData": null,
    "ODataType": null
  },
  "Subject": "PTO",
  "TransactionId": null,
  "Type": null,
  "WebLink": null,
  "Attachments": null,
  "AttachmentsNextLink": null,
  "Calendar": null,
  "Extensions": null,
  "ExtensionsNextLink": null,
  "Instances": null,
  "InstancesNextLink": null,
  "MultiValueExtendedProperties": null,
  "MultiValueExtendedPropertiesNextLink": null,
  "SingleValueExtendedProperties": null,
  "SingleValueExtendedPropertiesNextLink": null,
  "Categories": null,
  "ChangeKey": null,
  "CreatedDateTime": null,
  "LastModifiedDateTime": null,
  "Id": null,
  "ODataType": "microsoft.graph.event",
  "AdditionalData": null
}

### Steps to reproduce the behavior

In v3 the objects such as Entity.ODataType are annotated as 
[JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "@odata.type", Required = Required.Default)]

However, in v4  the objects are annotated with 
[JsonPropertyName("@odata.type")

As per stackoverflow post below the poster states the following:
I had the same problem (.Net Core 3.1) and the reason was that I was using JsonPropertyName annotation, which is in System.Text.Json.dll but using JsonConvert.Serialize(string), which is obviously in Newtonsoft.Json.dll. It seems the serialization functions only respect their own library annotations. Changing JsonPropertyName annoation to JsonProperty fixed it, as the latter is in Newtonsoft.Json.dll

https://stackoverflow.com/questions/8424151/json-net-serializer-ignoring-jsonproperty

For our Startup we do use Newtonsoft.Json.Dll with the following setup

services
                .AddControllers()
                .AddNewtonsoftJson(options =>
                {
                    options.SerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore;
                    options.SerializerSettings.DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore;
                    options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;

                });

Our biggest issue is the serialization of ODataType. NO matter what we tried the serializer does not pickup the annotated name.

**Comment by dkonyayev** [comment]
For our project we use Newtonsoft.Json v13.0.1

**Comment by andrueastman** [comment]
Hey @dkonyayev,

Thanks for raising this issue. 

Version 4 of the SDK drops support for NewtonSoft to use System.Text.Json as outlined in the guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#breaking-changes). 

As NewtonSoft does not support the System.Text.Json attributes, you would need to perform serialization by calling the System.Text.Json serializer

```
string jsonString = JsonSerializer.Serialize(jsonObject);
```

alternatively you could also use the preconfigured options in graphclient by doing this.

```
string jsonString = graphClient.HttpProvider.Serializer.Serialize(jsonObject);
```
