### ISSUE TITLE
Resumable Upload via ChunkedUploadProvider does not work on Shared Drives

### ISSUE THREAD

**Issue by alx-andru** [microsoftgraph/msgraph-sdk-dotnet#122]
Hi dear MSGraph Team,

The resumable upload on a sharepoint shared document library doesn't work.

As I'm following the [FileService.cs](https://github.com/microsoftgraph/aspnet-snippets-sample/blob/master/Graph-ASPNET-46-Snippets/Microsoft%20Graph%20ASPNET%20Snippets/Models/FilesService.cs) snippet from the [aspnet-snippets-sample](https://github.com/microsoftgraph/aspnet-snippets-sample/) I receive following error message:

> Code: -2147024891, System.UnauthorizedAccessException
> Message: Access denied. You do not have permission to perform this action or access this resource.

with following Response Header
```
{
  Transfer-Encoding: chunked
  X-SharePointHealthScore: 0
  X-Forms_Based_Auth_Required: https://[OUR_DOMAIN]app.sharepoint.com/_forms/default.aspx?ReturnUrl=/_layouts/15/error.aspx&Source=%2f_vti_bin%2fclient.svc%2fv2.0%2fdrives%2fb!eEeYn6nIlEK9ki9NJXvonE2KIkhnC19AkHf_FDjjSwxuKB5AIK_aQ7jskROzgOiv%2fitems%2f01ESOM2KV6Y2GOVW0075BZO354PWSELRRZ%2fuploadSession%3fguid%3d%273c1833ca-0fab-333c-8dff-809af2908f58%27%26path%3d%27%7etmp53_[OUR_DOMAIN]%27%26overwrite%3dTrue%26rename%3dFalse
  X-Forms_Based_Auth_Return_Url: https://[OUR_DOMAIN]app.sharepoint.com/_layouts/15/error.aspx
  X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically.
  ODATA-VERSION: 4.0
  X-IDCRL_AUTH_PARAMS_V1: IDCRL Type="BPOSIDCRL", EndPoint="/sites/dev/_vti_bin/idcrl.svc/", RootDomain="sharepoint.com", Policy="MBI"
  SPRequestGuid: 373bf29d-9019-3000-18fe-e3b4ab41d397
  request-id: 373bf29d-9019-3000-18fe-e3b4ab41d397
  Strict-Transport-Security: max-age=31536000
  X-FRAME-OPTIONS: SAMEORIGINMicrosoftSharePointTeamServices: 16.0.0.6504
  X-Content-Type-Options: nosniffX-MS-InvokeApp: 1; 
  RequireReadOnly
  X-MSEdge-Ref: Ref A: 856A2A6849B64D71BDEC01FBB2BB5F4C Ref B: CH1EDGE0222 Ref C: Tue May 16 06:50:52 2017 
  PSTCache-Control: max-age=0, privateDate: Tue, 16 May 2017 13:50:52 GMTP3P: CP="ALL IND DSP COR ADM CONo CUR CUSo IVAo IVDo PSA PSD TAI TELo OUR SAMo CNT COM INT NAV ONL PHY PRE PUR UNI"
  Server: Microsoft-IIS/10.0
  X-AspNet-Version: 4.0.30319X-Powered-By: ASP.NET
}
```
Looking at the BaseAuth:
`https://[OUR_DOMAIN]app.sharepoint.com/_forms/default.aspx?ReturnUrl=/_layouts/15/error.aspx&Source=/_vti_bin/client.svc/v2.0/drives/b!eEeYn6nIlEK9ki9NJXvonE2KIkhnC19AkHf_FDjjSwxuKB5AIK_aQ7jskROzgOiv/items/01ESOM2KV6Y2GOVW0075BZO354PWSELRRZ/uploadSession?guid='3c1833ca-0fab-333c-8dff-809af2908f58'&path='~tmp53_[OUR_DOMAIN]'&overwrite=True&rename=False`

The DriveId (b!eEeYn6nIlEK9ki9NJXvonE2KIkhnC19AkHf_FDjjSwxuKB5AIK_aQ7jskROzgOiv) is a **shared document folder in a sharepoint site**.  

The item (01ESOM2KV6Y2GOVW0075BZO354PWSELRRZ) is a subfolder within that drive.

The graph client uses **app only authentication** with the correct permissions. Regular file upload and any other file operation such as create, copy, rename, delete works.

I'm not certain what additional flag or option to set in regards to the response header message:

> Access denied. Before opening files in this location, you must first browse to the web site and select the option to login automatically.

I use following slightly modified code from the snippet:

```C#
 internal async Task<ApiResponse> UploadLargeFileAsync(string rootFolder, HttpPostedFileBase file, string relativePath)
        {
            try
            {
                using (Stream fileStream = file.InputStream)
                {
                    // Create the upload session. The access token is no longer required as you have session established for the upload.
                    // POST /v1.0/drive/root:/UploadLargeFile.bmp:/microsoft.graph.createUploadSession
                    var uploadSession = await _graph.Drives[ConfigurationHelper.DriveId]
                        .Root.ItemWithPath(rootFolder)
                        .CreateUploadSession().Request().PostAsync();

                    var maxChunkSize = 320 * 1024; // 320 KB - Change this to your chunk size. 5MB is the default.
                    var provider = new ChunkedUploadProvider(uploadSession, _graph, fileStream, maxChunkSize);

                    // Setup the chunk request necessities
                    var chunkRequests = provider.GetUploadChunkRequests();
                    var readBuffer = new byte[maxChunkSize];
                    var trackedExceptions = new List<Exception>();
                    DriveItem itemResult = null;

                    //upload the chunks
                    foreach (var request in chunkRequests)
                    {
                        // Do your updates here: update progress bar, etc.
                        // ...
                        // Send chunk request
                        var result = await provider.GetChunkRequestResponseAsync(request, readBuffer, trackedExceptions);

                        if (result.UploadSucceeded)
                        {
                            itemResult = result.ItemResponse;
                        }
                    }

                    // Check that upload succeeded
                    if (itemResult == null)
                    {
                        // Retry the upload
                        // ...
                    }

                    return new ApiResponse
                    {
                        Success = true,
                        Data = ""
                    };
                }
            }

            catch (ServiceException e)
            {
                // Debug.WriteLine("We could not upload the file: " + e.Error.Message);
                return null;
            }

        }
```

**Comment by alx-andru** [comment]
Just checking in if there are any recent updates or tipps how I could go around it. 

Thanks for the support!

**Comment by jmacneill** [comment]
I'm getting the same error.  However, it started working on 7/7/2017 and then stopped today (7/11/2017).

Here's my code:

Imports System.IO
Imports System.Web.Script.Serialization

Module Module1
    Private dtAccessToken As DateTime = "1/1/1900"
    Private strAccessToken As String = ""
    Private strUploadFile As String = "C:\Applications\OneDrive\test.pdf"
    Private strUserName As String = "REDACTED"
    Private strTokenURL As String = "https://login.microsoftonline.com/REDACTED/oauth2/v2.0/token"
    Private strAppSecret As String = "client_id=REDACTED&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=REDACTED&grant_type=client_credentials"

    Sub Main()
        GetAccessToken()

        Dim driveID As String = GetDriveID(strAccessToken, strUserName)
        Dim strURL As String = "https://graph.microsoft.com/v1.0/drives/" & driveID & "/root:/test.pdf:/createUploadSession"
        Dim rsp As String = ""
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Authorization", "Bearer " & strAccessToken)
        wc.Headers.Add("Content-Type", "application/json")

        rsp = wc.UploadString(strURL, "POST", "{""item"": {""@microsoft.graph.conflictBehavior"": ""rename""}}")

        Dim jss As New JavaScriptSerializer
        Dim objRsp As Object = jss.Deserialize(Of Object)(rsp)
        Dim strUploadUrl As String = ""

        If objRsp.TryGetValue("uploadUrl", strUploadUrl) Then
            Dim strm As New IO.FileStream(strUploadFile, FileMode.Open)
            Dim iLen As Integer = strm.Length
            Dim byt(iLen) As Byte

            strm.Read(byt, 0, strm.Length)

            Dim wr As Net.HttpWebRequest = Net.WebRequest.Create(strUploadUrl)

            wr.ContentLength = iLen
            wr.Headers.Add("Content-Range", "bytes 0-" & iLen - 1 & "/" & iLen)
            wr.Method = "PUT"

            Console.WriteLine("bytes 0-" & iLen - 1 & "/" & iLen)

            Dim rs As IO.Stream = wr.GetRequestStream
            rs.Write(byt, 0, iLen)

            Dim rspe As Net.WebResponse = wr.GetResponse

            rs.Close()
        End If
    End Sub

    Private Sub GetAccessToken()
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Content-Type", "application/x-www-form-urlencoded")

        Dim strReturn = wc.UploadString(strTokenURL, strAppSecret)
        Dim jss As New JavaScriptSerializer
        Dim objRet As Object = jss.Deserialize(Of Object)(strReturn)

        strAccessToken = objRet("access_token").Replace(vbCrLf, "").Replace(vbNewLine, "")
        dtAccessToken = Now()
    End Sub

    Private Function GetDriveID(strToken As String, strUser As String) As String
        Dim strDriveID As String = ""

        Try
            Dim wc As New Net.WebClient()

            wc.Headers.Add("Authorization", "Bearer " & strToken)

            Dim strResponse As String = wc.DownloadString("https://graph.microsoft.com/v1.0/users/" & strUser & "/drives")
            Dim jss As New JavaScriptSerializer
            Dim objContents As Object = jss.Deserialize(Of Object)(strResponse)

            For Each obj As Dictionary(Of String, Object) In objContents("value")
                Dim strContent As Object = Nothing

                If obj.TryGetValue("id", strContent) Then
                    strDriveID = obj.Item("id")
                End If
            Next
        Catch ex As Exception

        End Try

        Return strDriveID
    End Function

End Module

**Comment by ificator** [comment]
AppOnly scenarios via MS Graph were always problematic, and so were advertised as "limited support". Thankfully, as of early this month we've rectified the major issues and so resumable upload should now be working. Are you still seeing issues?

**Comment by alx-andru** [comment]
Hi @ificator thanks for letting us know. I just had a chance to test the Chunked Upload and it seems to be working fine.

**Comment by MIchaelMainer** [comment]
This appears to  have been resolved. Thank you all.
