### ISSUE TITLE
Forbidden error when accessing meeting recording URL 

### ISSUE THREAD

**Issue by omri08** [microsoftgraph/msgraph-sdk-dotnet#1224]
**Describe the bug**
Requesting for the meeting recording download link causing a Forbidden error 

**To Reproduce**
```
            var res = await graphClient.Chats[chatId].Messages[msgId].HostedContents[consetId].Request().GetResponseAsync().ConfigureAwait(false);
            var resBody = await res.Content.ReadAsStringAsync().ConfigureAwait(false);
            Console.WriteLine(res);
```

**Expected behavior**
The request should be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/54754198/149664635-7589501b-231b-49f7-af61-0970e37e4e42.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Not relevant
- Version: Graph Client Nuget 4.13.0

**Additional context**

- This way for accessing the download link was suggested here https://docs.microsoft.com/en-us/answers/questions/612555/how-to-get-meeting-recording-url-and-how-to-downlo.html
- The requester is a participant in the meeting
- Also, the requester can download the meeting through Teams files.

**Comment by andrueastman** [comment]
Hey @omri08,

Thanks for raising this. 

The forbidden error response usually suggests an issue with the permissions used to make the requests. Are you able to confirm the permissions requested are consistent with the permissions needed for the request? The permissions needed are outlined in the docs [here](https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http#permissions).

**Comment by omri08** [comment]
> 

Hi @andrueastman ,
Yes I can confirm that, also here's a picture from using the Graph explorer and the result is the same 
![image](https://user-images.githubusercontent.com/54754198/149735636-db4a2a26-9814-47ac-9ff5-ebe9200499be.png)

Also, I can access the recording from teams.

**Comment by andrueastman** [comment]
Hey @omri08,

Thanks for the extra info. Just to confirm are you able to list the chat members as described in [the docs](https://docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&tabs=http) using graph explorer?
If so, is the logged in user in the member list?
