### ISSUE TITLE
Regression: serialization of schema extensions changes property casing

### ISSUE THREAD

**Issue by zvrba** [microsoftgraph/msgraph-sdk-dotnet#1227]
**Describe the bug**
I have a class that defines a group schema extension, say 

```
class Ext
{
    [DataMember] public string A { get; set; }
}
```

which I add to group additional data upon group creation. The AD schema extension is also created and registered with "A" as the property name. With previous SDK (3.X), the group got created correctly with extension data. With 4.X, `A` is set to null in extension data (verified in graph explorer). This is caused by the new STJ serializer camel-casing properties by default, i.e., the json in the http request message contains `{"a": "something"}` instead of `{"A": "something"}`.

**Expected behavior**
Should be documented as a caveat when 4.X is using STJ instead of newtonsoft. Or the serializer should be configured to not mess with casing by default. Workaround: annotate the schema class with `[JsonPropertyName]`.

**Comment by andrueastman** [comment]
Hey @zvrba,

Thanks for raising this. 

This is documented in the upgrade [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#breaking-changes) and this is caused as System.Text.Json is does not support [System.Runtime.Seriazation](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-6-0#systemruntimeserialization-attributes) attributes.
