### ISSUE TITLE
[Client bug]: Token Caching

### ISSUE THREAD

**Issue by eluchsinger** [microsoftgraph/msgraph-sdk-dotnet#1229]
**Describe the bug**
Every time I call the Graph API, a GetToken call is made. We have response times of several hundred milliseconds (sometimes even > 1 second), which make it really inefficient. A caching of the tokens would be desirable.

**To Reproduce**
1. Create a `GraphServiceClient` using the `ClientSecretCredential`.
2. Execute a request like the one below.
3. See the application logs (especially Application Insights)

**Expected behavior**

I would expect the token to be retrieved only once and reused especially for subsequent calls. If there's any more setup to do, I would expect it to be clearly documented in a prominent place. So far I haven't been able to find any documentation about how the caching mechanism works at all with this SDK. In fact, I'm missing a big picture of best practices on how to set up the SDK in combination with ASP.NET Core, DI and the other libraries like `Microsoft.Identity`. The snippets available in the documentation do not convey the big picture of how everything is working together.

**Code**

Setup of the Graph Client

```csharp
var scopes = new[] { "https://graph.microsoft.com/.default" };
var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);
graphClient = new GraphServiceClient(clientSecretCredential, scopes);
```

Sample call

```csharp
var response = await graphClient.Users[userId].MemberOf.Request().GetAsync(cancellationToken);
```

**Client version**

- Microsoft.Graph `4.14.0`

**Additional context**

First I asked the question on StackOverflow, but afterwards, I've decided to raise an Issue here, because the behavior seems odd.

- Question on Stackoverflow: https://stackoverflow.com/questions/70821209/net-graph-sdk-token-caching

**Comment by andrueastman** [comment]
Hey @eluchsinger,

The token caching should be handled by the `TokenCredential` from `Azure.Identity` library you are using. 
Can you confirm that you replicate this issue while using the latest version of 1.5.0?

**Comment by dxynnez** [comment]
@andrueastman  AFAIK TokenCredential doesn't cache the token - they (azure sdk folks) had made it clear that a credential should do one job, which is to get a token when requested.

Usually the tokencache is done with the [BearerTokenAuthenticationPoilcy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs) in the client pipeline for v4 azure sdk.

**Comment by dxynnez** [comment]
Aha, so the MSAL usage was added in 1.2.1 but I was checking the 1.1.1 implementation and then we migrated to [ManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-net/blob/005d45407788a475002c7784fee45cb054609c59/sdk/identity/Azure.Identity/src/ManagedIdentityCredential.cs) which doesn't leverage MSAL so I didn't notice it.

But still, managed identity itself is also a service principal so it's possible one would want to use it to call graph, I think it's still better to apply a second level cache just like the one in the BearTokenAuthenticationPolicy which is basically the direct cache for all sorts of azure clients.

**Comment by pschaeflein** [comment]
Developers can configure the MSAL token cache when creating the [IClientApplication](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-instantiate-confidential-client-config-options#add-runtime-configuration).
