### ISSUE TITLE
How do I utilize the Open and Schema Extensions API surface through this SDK?

### ISSUE THREAD

**Issue by cveld** [microsoftgraph/msgraph-sdk-dotnet#123]
I would like to extend Group objects with custom data, query and filter them by these custom data by using this SDK. But I can't find the proper way. 

Straight through the REST API is documented over here - Open Extensions:
* Getting extensions: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/opentypeextension_get
* Creating extensions: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/opentypeextension_post_opentypeextension
* The specific request body: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/opentypeextension_post_opentypeextension#request-body

Schema Extensions:
* https://developer.microsoft.com/en-us/graph/docs/concepts/extensibility_schema_groups

What I have set up thus far; utilizing the BaseRequest class I can just pass full REST API urls:
```
var request = new BaseRequest($"https://graph.microsoft.com/v1.0/schemaExtensions", graphClient);
var response = await request.SendRequestAsync(null, CancellationToken.None);
var resultString = response.Content.ReadAsStringAsync().Result;
```

Can you help?

**Comment by MIchaelMainer** [comment]
Hello @cveld, the client library currently doesn't send what the service expects. The following code is what should work (adding in case we get this fixed):

```
IGraphServiceGroupsCollectionPage groupPage = await graphClient.Groups.Request().GetAsync();

Extension newExtension = new Extension()
{
    ODataType = "Microsoft.Graph.OpenTypeExtension",
};

newExtension.AdditionalData = new Dictionary<string, object>();
newExtension.AdditionalData.Add("extensionName", "com.contoso.trackingKey");
newExtension.AdditionalData.Add("trackingKeyMajor", "ABC");
newExtension.AdditionalData.Add("trackingKeyMinor", "123");

var extension = await graphClient.Groups[groupPage[0].Id].Extensions.Request().AddAsync(newExtension);
```
The issue is that the service expects the @odata.type property set to openTypeExtension and we serialize extension. This is based on the metadata description. For now, you'll need to do what you've already done or, you can use the client library for the serialization and authorization.

```
// Create the request message and add the content.
HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Post, requestUrl);
hrm.Content = new StringContent(extensionDefinitionAsJSON, System.Text.Encoding.UTF8, "application/json");

// Authenticate (add access token) our HttpRequestMessage
await graphClient.AuthenticationProvider.AuthenticateRequestAsync(hrm);

// Send the request and get the response.
HttpResponseMessage response = await graphClient.HttpProvider.SendAsync(hrm);

var content = await response.Content.ReadAsStringAsync();
var ext = graphClient.HttpProvider.Serializer.DeserializeObject<Extension>(content);
```

**Comment by MIchaelMainer** [comment]
Provided code example

**Comment by cveld** [comment]
Thanks! Is there also a way to work with schema extensions?

**Comment by VitorX** [comment]
@MIchaelMainer  What's version of SDK are you using? I am not able to find the `Extensions` property of `IGroupRequestBuilder`.

**Comment by MIchaelMainer** [comment]
Sorry about the confusion. It appears that open and schema extensions were not in the library when we last generated. They will be in the next version of the library. There's a commit of open extension tests in pull request #129 and a commit of schema extension tests in pull request #130 

You can try out both from the schemaExtension branch.

**Comment by MIchaelMainer** [comment]
Test for schema extension: https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/130/commits/2b377e41695d80ad40e6e64a74550439f82c84a9

**Comment by lordwardall** [comment]
Any example how to work with schema extension using the API ? I can't figure how to add extended property to an existing Group. The provided test, define the schema but does not actually use it to persist data on a Group.
