### ISSUE TITLE
Can't get specific transitiveMemberOf group

### ISSUE THREAD

**Issue by rhalaly** [microsoftgraph/msgraph-sdk-dotnet#1231]
**Describe the bug**
`TransitiveMemberOf` returns wrong item with `$filter`. When I list all my transitive memberships, I get the group that I was interested in. But when I use `$filter` with the specific id, I get an error.

**To Reproduce**
1. List all the transitive memberships with `Me.TrasitiveMemberOf`
2. Select one group
3. Get the specific group with `.Filter($"id eq '{groupId}'")`
4. Get an error

**Expected behavior**
No error

**Screenshots**
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/8597700/150973607-0df1219c-dad9-497d-b2af-6365273574fa.png">

The group ID I asked starts with `25a...` not `50f...`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 

**Smartphone (please complete the following information):**
Not relevant

**Additional context**

**Comment by maisarissi** [comment]
Hi @rhalaly 

Thanks for opening this issue.
Looking at the [documentation](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#optional-query-parameters), to be able to filter, the consistency level header eventual and $count=true is required.

Can you confirm if you are using them?

Here is how your code should look like:

```csharp
var options = new List<QueryOption>()
{ 
    new QueryOption("$count","true")
};
var queryResult = await graphClient.Me.TransitiveMemberOf
                .Request(options)
                .Header("ConsistencyLevel", "eventual")
                .Filter($"id eq '{groupId}'")
                .GetAsync();
```

Also, I'm curious, are you running Fiddler while this error occurs? Can you share the output?
