### ISSUE TITLE
Some users get `insufficient privileges to complete the operation.` from `memberOf` query

### ISSUE THREAD

**Issue by rhalaly** [microsoftgraph/msgraph-sdk-dotnet#1234]
**Describe the bug**
Following this tutorial: https://docs.microsoft.com/en-us/azure/static-web-apps/assign-roles-microsoft-graph
Some users get insufficient privileges to complete the operation. when calling Microsoft Graph.

**To Reproduce**
1. Follow the tutorial
2. Login with several users
3. Some of them will throw `insufficient privileges to complete the operation.` when calling Microsoft Graph.

**Expected behavior**
It will work for all the users

**Screenshots**
<img width="703" alt="image" src="https://user-images.githubusercontent.com/8597700/151207225-75229e83-5200-4dec-b50f-90ef15e54d17.png">

**Desktop (please complete the following information):**
 - OS: Windows 11/10, Mac
 - Browser Edge
 - Version 90

**Smartphone (please complete the following information):**
Not relevant

**Additional context**

**Comment by andrueastman** [comment]
Hey @rhalaly,

Thanks for raising this. 

It looks like the sample you are referring to is actually a JavaScript sample and does not use the dotnet SDK. 
In the event I am mistaken, could you please share the code in use that utilizes the dotnet SDK?

**Comment by rhalaly** [comment]
Hi @andrueastman,

I actually converted this sample to the .NET SDK. The error above is from the .NET SDK code.
Here is the converted code:

```
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Azure.Identity;
using Microsoft.Graph;

namespace Webapp
{
    public class GraphClient
    {
        private readonly GraphServiceClient _graphServiceClient;

        public GraphClient(string userToken)
        {
            _graphServiceClient = CreateGraphClient(userToken);
        }

        public async Task<bool> IsUserInGroup(string groupId)
        {
            var response = await _graphServiceClient.Me.MemberOf
                .Request()
                .Filter($"id eq '{groupId}'")
                .GetResponseAsync()
                .ConfigureAwait(false);

            return response.StatusCode == HttpStatusCode.OK;
        }

        private static GraphServiceClient CreateGraphClient(string token)
        {
            var options = new TokenCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            };

            var authProvider = new DelegateAuthenticationProvider((request) =>
            {
                request.Headers.Authorization =
                    new AuthenticationHeaderValue("Bearer", token);

                return Task.CompletedTask;
            });

            return new GraphServiceClient(authProvider);
        }
    }
}
```

Then we use this code in the GetRoles function:

```
...
var client = new GraphClient(request.accessToken);
var isIn = client.IsUserInGroup(AdminsGroupId);
...
```

**Comment by rhalaly** [comment]
Hi @andrueastman,

I actually converted this sample to the .NET SDK. The error above is from the .NET SDK code.
Here is the converted code:

```
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Azure.Identity;
using Microsoft.Graph;

namespace Webapp
{
    public class GraphClient
    {
        private readonly GraphServiceClient _graphServiceClient;

        public GraphClient(string userToken)
        {
            _graphServiceClient = CreateGraphClient(userToken);
        }

        public async Task<bool> IsUserInGroup(string groupId)
        {
            var response = await _graphServiceClient.Me.MemberOf
                .Request()
                .Filter($"id eq '{groupId}'")
                .GetResponseAsync()
                .ConfigureAwait(false);

            return response.StatusCode == HttpStatusCode.OK;
        }

        private static GraphServiceClient CreateGraphClient(string token)
        {
            var options = new TokenCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            };

            var authProvider = new DelegateAuthenticationProvider((request) =>
            {
                request.Headers.Authorization =
                    new AuthenticationHeaderValue("Bearer", token);

                return Task.CompletedTask;
            });

            return new GraphServiceClient(authProvider);
        }
    }
}
```

Then we use this code in the GetRoles function:

```
...

```

**Comment by andrueastman** [comment]
Hey @rhalaly,

Thanks for clarifying. 

Any chance you could also share the code sample that shows how you are acquiring the token as well?

**Comment by rhalaly** [comment]
Hi @andrueastman,

I don't have the code. As you can see in the example, the access token is provided by the Azure Static Webapp internally. They call our function with the access token in the body.

**Comment by andrueastman** [comment]
Any chance you are able to grab the access token string when it fails and paste it over to https://jwt.ms/?

As this seems to be an authentication issue, this will show us if the given token has an issue with the given scopes which should match the documentation specified [here](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#permissions).

**Comment by rhalaly** [comment]
Hi @andrueastman, sure.

I saw several tokens, for users that succeed to access and users that don't. 

All the users use Work account, and the token has a `User.Read` scope in their token. Which should be enough per the documentntation (`User.Read` for Work account in Delegate scope)

**Comment by rhalaly** [comment]
I think we found the issue.

```
public async Task<bool> IsUserInGroup(string groupId)
{
    var response = await _graphServiceClient.Me.MemberOf
        .Request()
        .Filter($"id eq '{groupId}'")
        .GetResponseAsync()
        .ConfigureAwait(false);

    return response.StatusCode == HttpStatusCode.OK;
}
```

When the user is **not** part of the group, instead of returning the correct status code, the call crashes with the exception of `insufficient privileges to complete the operation.` - very not intuitive.

Adding the scope "User.ReadBasic.All" to the application (in addition to `User.Read`), replaced the `insufficient privileges to complete the operation.` with a clearer message that the user cannot read and query the group. 

I don't know how it works in JS, but it seems that the .NET SDK is really not intuitive. Why `User.ReadBasic.All` is required to see a meaningful message?

**Comment by maisarissi** [comment]
Hi @rhalaly .

This seems to be related to how the API works and its response. 
Unfortunately, we in the Microsoft Graph SDK team do not have any ownership of the APIs that are causing you issues. If you report this issue in the Microsoft Q&A forum, it will get routed to the appropriate team for them to triage.
https://aka.ms/askgraph
