### ISSUE TITLE
[Client bug]: Filter method does not support $count (it worked in Graph v3 Microsoft.Graph.Core 1.25.1)

### ISSUE THREAD

**Issue by luismanez** [microsoftgraph/msgraph-sdk-dotnet#1236]
This query was working perfectly in Graph SDK v3 (Microsoft.Graph.Core 1.25.1)

```csharp
var groups = await _graphServiceClient
                .Me
                .TransitiveMemberOf
                .Request()
                .Header("ConsistencyLevel", "eventual")
                .Filter($"id eq '{groupId}'&$count=true")
                .Select("id")
                .GetAsync();
```

However, after upgrading to SDK v4 (Microsoft.Graph.Core 2.0.7), the query throws an exception:

_BadRequest\r\nMessage: Invalid filter clause_

**Client version**
Microsoft.Graph 4.11.0
Microsoft.Graph.Core 2.0.7

**Additional context**
As far as I´ve seen using Fiddler, the way the Filter method is encoding the request, makes it crash. This is the request sent to Graph API:

```
/v1.0/me/transitiveMemberOf?$filter=id%20eq%20%27{{GROUP_ID}}%27%26%24count%3Dtrue&$select=id
```

As you can see, the __$count=true__ is escaped, so the filter clause is invalid.

The workaround I´ve found, is to set the _$count_ param in the __QueryOptions__, so this code works:

```csharp
            var options = new List<QueryOption>
            {
                 new QueryOption("$count", "true")
            };

            var groups = await _graphServiceClient
                                .Me
                                .TransitiveMemberOf                                
                                .Request(options)
                                .Header("ConsistencyLevel", "eventual")
                                .Filter($"id eq '{_permissionsOptions.SuperAdminsGroupId}'&$count=true")
                                .Select("id")
                                .GetAsync();
```

If this is the way to go, it should be documented somewhere as breaking change. I haven´t found it here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md

Thanks!

**Comment by bradshaw84nz** [comment]
Can confirm i've struck the same issue and work around is correct.

**Comment by pschaeflein** [comment]
$count is an OData parameter, but it is not filtering the results.  IMO, the SDK behavior is correct and the docs should be updated.

(The Graph.Community library already has an [extension method for adding the ConsistencyLevel header](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/d7ea00a2633e754cd4a04dd185d56c678ab135f9/test/BaseRequestExtensionTests.cs#L59), and I would appreciate your thoughts on adding one for the $count parameter. For example:

```csharp
var groups = await _graphServiceClient
                                .Me
                                .TransitiveMemberOf                                
                                .Request(options)
                                .Filter($"id eq '{_permissionsOptions.SuperAdminsGroupId}'")
                                .WithEventualConsistency()    // <- Already exists
                                .Count(true)                  // <- New ??
                                .Select("id")
                                .GetAsync();
```

And I don't have an elegant solution for pulling the resulting count from AdditionalData. Again, thoughts appreciated.

**Comment by andrueastman** [comment]
As `$count` is a separate query parameter, it shouldn't really be expected to be placed in `Filter` clause but be separated out as the second example shows. This is indeed a documentation issue as v4 introduced the encoding of query options to resolve a number of open issues.

#1238 has been opened to update the documentation for clarity.

**Comment by luismanez** [comment]
Yeah, I agree is more a doc issue.

@pschaeflein , I can´t help much regarding Count extension. I think is a nice to have. What do you think about this note here https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties

> Specific usage of $filter and the $search query parameter is supported only when you use the ConsistencyLevel header set to eventual and $count. For more information, see [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#user-properties).

Cos, with just _WithEventualConsistency_ could be not enough to make it work if the $count is not present. In my custom code, I´ve created a similar method, but I´m including both, the Header, and the $count as QueryOption:

```csharp
public static TRequest WithEventualConsistency<TRequest>(
        this TRequest request) where TRequest : IBaseRequest
    {
        if (request == null)
        {
            throw new ArgumentNullException("request");
        }

        request.Headers.Add(new HeaderOption("ConsistencyLevel", "eventual"));
        request.QueryOptions.Add(new QueryOption("$count", "true"));

        return request;
    }
```

Thanks!
