### ISSUE TITLE
Roles and Permissions issue from OneDrive API/SDK

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#124]
I am trying to use OneDrive API/SDK to retrieve permissions of Shared with Me items in OneDrive for Business. Some of the files/folders have read only permission while others have read/write both. I observe that for resources having read only permission, I am getting "roles" field as empty after below call(s):

var preference = await client.Drives[driveId].Items[itemID].Permissions.Request().GetAsync();
GET:
https://graph.microsoft.com/v1.0/drives/driveId/items/itemID/permissions

Where as for the files/folders having read/write access, I am getting "roles" field with one item as "write". My expectation is for read only items, I should get "roles" field data as "read" as per this link.

Please suggest if my assumption is wrong. I have also posted his quest at SO here: https://stackoverflow.com/questions/44135569/roles-and-permissions-issue-from-onedrive-api-sdk

**Comment by MIchaelMainer** [comment]
Can you try this with the Microsoft Graph client library? Does it repro with it as well?
Can you share the request and response?

**Comment by MIchaelMainer** [comment]
I'm closing this as there isn't a response to my questions and this applies to the deemphasized OneDrive client library. If you feel that I'm in error, please reopen this issue.
