### ISSUE TITLE
Support for a non-async/await version of the library.

### ISSUE THREAD

**Issue by Whatty** [microsoftgraph/msgraph-sdk-dotnet#125]
I am trying to integrate this with a legacy application which has NOT been updated to support the async/await pattern

Will a version of the library be created that supports the traditional programming pattern ?

**Comment by MIchaelMainer** [comment]
Hello @Whatty, this will be the only .Net library that we will produce for Graph. With that said, what framework version does this legacy application target?

**Comment by Whatty** [comment]
My application code base is NOT based on the async / await pattern and I am having a tough time due to the size and age of my application code base to convert to the new paradigm. I have determined that mixing the two patterns is causing problems and I can't get the calls to the Graph SDK to work nicely in a non-async call stack

Ideally the Graph SDK could support both paradigm(s)

**Comment by MIchaelMainer** [comment]
Instead of awaiting the Task, can you use the result of the task?

`var result  = graphClient.me.GetAsync().Result`

That will block the thread until result is returned.

**Comment by Whatty** [comment]
Unfortunately that doesn't seem to work if I am using that call in a non-async .ashx handler. As far as I can tell the thread that is running the .ashx handler ends abruptly, it is as if the .Result() causes the parent thread to end - I have subsequently changed my ashx handler to a async/await pattern and it is behaving better and have successfully made the call in a test bed,  but converting all my handlers to that pattern is going to be very difficult in my legacy application of several thousand classes and is something I wish to avoid for now until I have time for a full update.
