### ISSUE TITLE
Do you have any Mock suggestions for following scenarios?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-dotnet#1251]
Hello,
in the Upgrade guide (https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graphserviceclient-no-longer-implements-the-igraphserviceclient), you show an example of how to mock a result returning a single object. I was exploring ways to speed up the mocking process. 

During these activities, I had some challenges in mocking CollectionPageObjects (results from multiple items). Do you have an example for that too?

On the last note, I had an idea how the testing/mocking process could be further improved. Ideally, I am going to use graph explorer to perform my calls. The results from these calls are valid JSON outputs that I could use for my mock methods. 
Do you have some suggestions on how I could achieve this goal? Maybe mocking the IHttpProvider in conjunction with some moq sequences (to test calls in a specific sequence).

Cheers,
Patrick

**Comment by plamber** [comment]
@andrueastman: this looks promising. I will have a look into this.

By chance do you know if the ChaosHandler accepts a sequence of calls? I am just thinking about the use case where you have to mock two consecutive calls that differ.

Thank you

**Comment by plamber** [comment]
Hi @andrueastman,
thank you. This helps.

Cheers

**Comment by andrueastman** [comment]
No worries @plamber.

Closing this for now. Feel free to reopen/create a new issue in the event of any more clarifications.
