### ISSUE TITLE
'Person' missing from EntityType.cs

### ISSUE THREAD

**Issue by daviesro** [microsoftgraph/msgraph-sdk-dotnet#1258]
Entity type 'Person' is missing from the generated model EntityType.cs. Example usage below:
```csharp
var requests = new List<SearchRequestObject>()
{
    new SearchRequestObject
    {
        EntityTypes = new List<EntityType>
        {
            EntityType.Person // Does not exist
        },
        Query = new SearchQuery
        {
           QueryString = "foobar"
        },
        Size = 5,
    }
};

**Comment by andrueastman** [comment]
Hey @daviesro,

Thanks for raising this.

We will follow this up with the relevant workload team so that the metadata can be updated to include the missing member and circle back to give you feedback on this.
