### ISSUE TITLE
Username/password provider throws an error

### ISSUE THREAD

**Issue by rhalaly** [microsoftgraph/msgraph-sdk-dotnet#1259]
**Describe the bug**
Following the sample code from this [Doc](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#usernamepassword-provider) doesn't work and throw an error.

**To Reproduce**
1. Use that piece of code (below) from the documentation example.
2. Sign in with username and password
3. Query `Me`
4. See error:
```
MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: a438f681-07a2-476c-94a6-be99c9f10100
Correlation ID: 82193f31-887f-4982-93af-e005922ee55b
Timestamp: 2022-02-24 10:38:51Z
```

**Expected behavior**
Work as expected with no errors.

**Screenshots**
<img width="849" alt="image" src="https://user-images.githubusercontent.com/8597700/155508773-208005a5-e0b8-4ab9-8978-0316a338b84e.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: None
 - Version: None

**Smartphone (please complete the following information):**
Not relevant

**Additional context**
The code:
```
private static async Task<User> GraphQuery()
{
    var scopes = new[] { "User.Read" };

    // Multi-tenant apps can use "common",
    // single-tenant apps must use the tenant ID from the Azure portal
    var tenantId = TenantId;

    // Value from app registration
    var clientId = AppId;

    // using Azure.Identity;
    var options = new TokenCredentialOptions
    {
        AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
    };

    // https://docs.microsoft.com/dotnet/api/azure.identity.usernamepasswordcredential
    var userNamePasswordCredential = new UsernamePasswordCredential(
        Email, Password, tenantId, clientId, options);

    var graphClient = new GraphServiceClient(userNamePasswordCredential, scopes);

    return await graphClient.Me.Request().GetAsync();
}
```

**Comment by andrueastman** [comment]
Hey @rhalaly,

Thanks for raising this. 

As the error suggests, there is an issue with the configuration of the Application that you have registered on the azure portal.

Are you able to confirm that the app is configured correctly? You can checkout step 5 at the link [here](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/walkthrough-register-app-azure-active-directory).

**Comment by rhalaly** [comment]
Thank you! It seems that it resolved the issue. Not sure how this step was skipped...
