### ISSUE TITLE
[Client bug]: sendMail fails silently

### ISSUE THREAD

**Issue by LegendaryB** [microsoftgraph/msgraph-sdk-dotnet#1260]
**Describe the bug**
We are using the the sendMail endpoint via the GraphServiceClient to send newsletters to a list of users. After a few operations it seems that this api "stops working". The mails will not be sent but the API call succeeds with 202 Accepted. 
Our service is running as a Azure AD app with application permissions. Permissions are the required ones so thats not a problem. We also not sending any attachments so that should also not be a problem.

**To Reproduce**
```csharp
var mail = new Message
{
   Subject = subject,
   Body = new ItemBody
   {
      ContentType = BodyType.Html,
      Content = content
   }
};

message.ToRecipients = recipients.Select(recipient => new Recipient
{
   EmailAddress = new EmailAddress
   {
      Address = recipient
   }
});

// sender is a predefined user in our case
var response = await _graphServiceClient.Users[sender.Id]
         .SendMail(mail, false)
         .Request()
         .PostResponseAsync();
```

**Expected behavior**
Error status code when sendMail fails.

**Client version**
4.18.0

**Desktop (please complete the following information):**
 - OS: latest Windows Server

**Comment by maisarissi** [comment]
Hi @LegendaryB .

Can you provide more details on how many emails you are sending? How many emails are you sending a minute/hour/day? Are you seeing delayed delivery in any of the emails that you see showing up? Have you confirmed that the emails are not landing in junk mail folders? Are the recipients within your organization or outside the organization? Have you previously verified the emails of the users outside of your organization?
