### ISSUE TITLE
SiteRequestBuilder.GetPath does the wrong thing

### ISSUE THREAD

**Issue by SGSmyth** [microsoftgraph/msgraph-sdk-dotnet#127]
I would expect client.Sites["someHostname"].GetByPath("somePath").Request() to build the URL https://graph.microsoft.com/beta/sites/someHostName:/somePath but, instead, it produces https://graph.microsoft.com/beta/sites/someHostName/microsoft.graph.getByPath(path='somePath') which then errors.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. We need to add a partial to enable this. That getByPath function does not properly emit the correct form.

For my reference, we'll need to add this to the SiteRequestBuilder class like what we did in DriveItemRequestBuilder. 

```
public partial class SiteRequestBuilder
        public ISiteRequestBuilder ItemWithPath(string path)
        {
            if (!string.IsNullOrEmpty(path))
            {
                if (!path.StartsWith("/"))
                {
                    path = string.Format("/{0}", path);
                }
            }

            return new SiteRequestBuilder(
                string.Format("{0}:{1}", this.RequestUrl, path),
                this.Client);
        }
```

**Comment by MIchaelMainer** [comment]
The issue on the service side is that the getByPath function bound to the site object is not what the service implements. We can add a partial to fix the client. The metadata should remove this function if not used.

**Comment by MIchaelMainer** [comment]
Added an extension to enable this. You'll call this like:

`await graphClient.Sites.GetSiteByPath(site.SiteCollection.Hostname, siteResource).Request().GetAsync();`

Will close this issue once this is published to Nuget
