### ISSUE TITLE
Resumable upload to OneDrive for Business does not work with long file names

### ISSUE THREAD

**Issue by pp111** [microsoftgraph/msgraph-sdk-dotnet#128]
Hi,

when uploading a file with a long file name (I tested 111 characters) the upload fails if it is done via resumable upload. The problem is that with file names in Chinese is quite easy to have 111 characters after url encoding the name for the request.

the upload session is created correctly with createUploadSession, but after the first chunk is uploaded the servers replies with a 404 error. 

The same file uploads ok with simple upload or via the web interface.

Steps to reproduce:
- Create a file with the following filename (or a 111 characters long filename):
V2345-數據恢復詳細說明版本1DDBBAA4E1.bin
- Do a resumable upload session via createUploadSession

Personal OneDrive accounts works ok, it fails for OneDrive for Business accounts

**Comment by MIchaelMainer** [comment]
Thank you for reporting this issue and providing the repro steps.

**Comment by pp111** [comment]
I think this issue is related to this OneDrive bug:

https://github.com/OneDrive/onedrive-api-docs/issues/593

**Comment by ificator** [comment]
We've made changes to shrink the size of the upload session URLs - hopefully this issue is now resolved.

**Comment by MIchaelMainer** [comment]
@ificator Thank you.
@pp111 Please let us know if this issue still persists. Otherwise, we'll close this issue after one week.
