### ISSUE TITLE
"Sync from now" not supported in outlook messages with $deltatoken=latest

### ISSUE THREAD

**Issue by SharonTancy** [microsoftgraph/msgraph-sdk-dotnet#1281]
**Describe the bug**
I attempt to get delta messages in outlook mailbox just from now on. I don't care those messages received before this request. In Graph Explorer I use `$deltatoken=latest` and it returns with `@odata.deltaLink` with a flaky behavior. But in SDK, no `@odata.deltaLink` is returned, I always receive `@odata.nextLink`.

**To Reproduce**
Code I use:
```
var queryOptions = new List<QueryOption>()
      {
          new QueryOption("$deltatoken", "latest"),
      };
      var deltaCollection = await this.graphClient.Me.MailFolders.Inbox
          .Messages
          .Delta()
          .Request(queryOptions)
          .GetAsync();

      // deltatoken=latest not works in this situation
      // It will throw exception
      var deltaLink = deltaCollection.AdditionalData["@odata.deltaLink"];
```

**Expected behavior**
`@odata.deltaLink` is returned.

**Client version**
Microsoft.Graph: v3.15.0

Any suggestions? Besides, my outlook mailbox belongs to Microsoft AAD.

**Comment by andrueastman** [comment]
Hey @SharonTancy,

According to the docs for tracking changes [here](https://docs.microsoft.com/en-us/graph/delta-query-messages#sample-initial-request), you'll notice that it is expected for the result to return `@odata.nextLink` as the number of results for the changes may not fit in a single response page. 

Ideally, you would then need to use the `@odata.nextLink` to get the next page of changes until you retrieve the list of all the changes. Once you retrieve all the changes, the last page should now contain the `@odata.deltaLink` once you have retrieved all the changes you requested for.

You can also take advantage of the SDKs [Page Iterator](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=csharp) to help you with this.

**Comment by SharonTancy** [comment]
Hi @andrueastman , 

Thanks for your reply, I've noticed in this [doc](https://docs.microsoft.com/en-us/graph/delta-query-overview) it says we can adopt `$deltaToken=latest` to support the "sync from now" scenario with `@odata.deltaLink` returned and no resource data. 

I'm wondering can we support such requests in mailboxes? Since I really don't need those changes occurred before, I just need the changes from now on.

**Comment by andrueastman** [comment]
Hey @SharonTancy.

> Note: Resources stored in Azure Active Directory (such as users and groups) support "sync from now" scenarios. This allows you to skip steps 1 and 2 (if you're not interested in retrieving the full state of the resource) and ask for the latest deltaLink instead. Append $deltaToken=latest to the delta function and the response will contain a deltaLink and no resource data. Resources in OneDrive and SharePoint also support this feature. For resources in OneDrive and SharePoint, append token=latest instead.

The documentation only mentions Sharepoint, Onedrive and AAD. It however does not mention whether Mail is supported for the scenario. Since this isn't an SDK related issue, we aren't in the best position to give a definitive answer on the API behavior. 

Are you able to create a question at the link below so that the relevant API owners may advise on what's the current state is? It would be great if you could post the link back here so that future users who come across this issue may also find it. 

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html

**Comment by SharonTancy** [comment]
I've posted a question [here](https://docs.microsoft.com/en-us/answers/questions/815318/may-mail-support-deltatokenlatest-request.html) to ask if graph api can support mailboxes in this scenario.

**Comment by andrueastman** [comment]
Thanks @SharonTancy.

I'll close this for now and we can re-open if any changes are needed in the SDK side.
