### ISSUE TITLE
Unable use C# to call the `users/{user id}/sendMail` endpoint to send emails.

### ISSUE THREAD

**Issue by CarlZhao-MSFT** [microsoftgraph/msgraph-sdk-dotnet#1286]
**Describe the bug**
Unable use C# to call the `users/{user id}/sendMail` endpoint to send emails.

**To Reproduce**
Here is my code snippet:
```
GraphServiceClient graphClient = new GraphServiceClient(authProvider);

            var message = new Message
            {
                Subject = "Meet for lunch?",
                Body = new ItemBody
                {
                    ContentType = BodyType.Text,
                    Content = "The new cafeteria is open."
                },
                ToRecipients = new List<Recipient>()
    {
        new Recipient
        {
            EmailAddress = new EmailAddress
            {
                Address = "{address1}"
            }
        }
    },
                CcRecipients = new List<Recipient>()
    {
        new Recipient
        {
            EmailAddress = new EmailAddress
            {
                Address = "{address2}"
            }
        }
    }
            };

            var saveToSentItems = false;

            await graphClient.Users["{user id}"]
                .SendMail(message, saveToSentItems)
                .Request()
                .PostAsync();
```

**Expected behavior**
My code is working fine, supposedly I should get the mail message in outlook, but it doesn't, I don't get any mail in outlook. By the way, the `/me` endpoint works, the bug seems to only target the `/users/{user id}` endpoint.  See the api doc: https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http

**Screenshots**

**Additional context**

**Comment by MIchaelMainer** [comment]
Does it work if you use Graph Explorer?
Is {user-id} the same user as 'me'?
If you run Fiddler, do you see any differences between the request and response for /me versus /users/userid?

**Comment by CarlZhao-MSFT** [comment]
@MIchaelMainer Yes, "{user-id}" is the same user as "me", in fact it works in postman, the problem seems to be only in the code, can you reproduce my problem locally?

**Comment by MIchaelMainer** [comment]
@CarlZhao-MSFT I can run this just fine. Can you turn on Fiddler and see what the request-response looks like? Can you confirm that you get a 202?

```csharp
static async Task SendMail(GraphServiceClient client)
{
    var subject = $"Subject {DateTime.Now.ToString()}";

    var message = new Message();
    message.Subject = subject;
    message.Body = new ItemBody() { Content = "mail body" };
    var recipients = new List<Recipient>()
    {
        new Recipient()
        {
            EmailAddress = new EmailAddress()
            {
                Address = Chambele.V1.useradele
            }
        }
    };

    message.ToRecipients = recipients;
	
    // Send email to the test user.
    await client.Users[Chambele.V1.user].SendMail(message).Request().PostAsync();
}
```

**Comment by CarlZhao-MSFT** [comment]
Hi @MIchaelMainer I've scraped the request and response and they don't seem to make any difference. After a few days of research I found that the "{user-id}" endpoint can actually send emails, but the emails I send are all classified as spam, why is this?

**Comment by MIchaelMainer** [comment]
@CarlZhao-MSFT I'm sorry that you've spent so much time on this. Are you sending emails to users in the same organization as the sender? 

I don't know what happens under the hood in Exchange and how it classifies emails as spam. Try setting the From field on the message to match the username of the sender.
