### ISSUE TITLE
Did you really wanted to release 5.0.0-preview.1 to NuGet?

### ISSUE THREAD

**Issue by schuettecarsten** [microsoftgraph/msgraph-sdk-dotnet#1289]
Did you really wanted to release 5.0.0-preview.1 to NuGet?
There seems to be no documentation about the changes, or I am too stupid to find it.

**Comment by andrueastman** [comment]
Hey @schuettecarsten,

Thanks for raising this. This can be found [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md). and we're working towards making it easier to find.
