### ISSUE TITLE
Can I use Graph to access this report?

### ISSUE THREAD

**Issue by MM-1010** [microsoftgraph/msgraph-sdk-dotnet#1297]
Can I access this report using Graph at all?

https://docs.microsoft.com/en-us/sharepoint/sharing-reports

If not are there any plans to expose it?

How could I use Graph to generate this report manually?

**Comment by andrueastman** [comment]
Hey @MM-1010,

Thanks for raising this. 

As this repository is mainly intended for client library issues, can you post the query at the link below for the Sharepoint API owners to give guidance on what is possible?
If possible, you could post the link to the question here for future users with the same query to be able to find the info.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html

Closing this for now and will re-open in the event of any client library issue.
