### ISSUE TITLE
Memory growth when using client side paging

### ISSUE THREAD

**Issue by sravya-datla** [microsoftgraph/msgraph-sdk-dotnet#1298]
**Describe the bug**
We are using Graph API SDK to retrieve mails in a user’s mailbox. Our application calls this API every 2 mins. 
We are observing a memory growth when this API is called. When the folder is empty, there is no memory growth. But, when there are mails present, we can see memory growth.

When we are not specifying the paging size, we are not seeing this issue. We only observe this growth when specify the page size in the TOP query. 

**Code Snippet**
```cs
List<IMessage> messages = new List<IMessage>();
            GraphAPI.IMailFolderMessagesCollectionPage items = null;
            try
            {
                if (searchFilter != "")
                {
                    items = Task.Run(() =>  m_service.GetUserClient().MailFolders[m_folder.Id]
                           .Messages.Request(m_service.HeaderOptons)
                           .Select(Constants.MSG_SELECTION)
                           .Expand(Constants.MESSAGE_CLASS)
                           .Filter(searchFilter.ToString()).Top(pageSize)
                           .OrderBy(reverseOrder ? Constants.ORDER_BY_RCVDDATE_DESC : Constants.ORDER_BY_RCVDDATE)
                           .GetAsync()).GetAwaiter().GetResult();
                }
                else
                {
                    items = Task.Run(() =>  m_service.GetUserClient().MailFolders[m_folder.Id]
                           .Messages.Request(m_service.HeaderOptons)
                           .Select(Constants.MSG_SELECTION)
                           .Expand(Constants.MESSAGE_CLASS)
                           .Top(pageSize)
                           .OrderBy(reverseOrder ? Constants.ORDER_BY_RCVDDATE_DESC : Constants.ORDER_BY_RCVDDATE)
                           .GetAsync()).GetAwaiter().GetResult();
                }
            }
            catch (GraphAPI.ServiceException e)
            {
                using (TraceContext.Mailbox.create(TraceTopics.MailboxContextAddress(m_service)))
                {
                    TraceTopics.Graph.error("Error recceived in response ({}):\nError Code: {}\nError Message: {}", e.Error.GetType(), e.Error.Code.ToString(), e.Error.Message);
                }
 
                throw;
            }
            catch (Exception e)
            {
                using (TraceContext.Mailbox.create(TraceTopics.MailboxContextAddress(m_service)))
                {
                    TraceTopics.Graph.error(e.ToString());
                }
                throw;
            }
            var pageIterator = GraphAPI.PageIterator<GraphAPI.Message>
            .CreatePageIterator(
                m_service.GraphClient,
                items,
                (m) =>
                {
                    //messages.Add(new Message(m, m_service, null));
                    return (messages.Count < messageCount);
                },
                // Used to configure subsequent page
                // requests
                (req) =>
                {
                    // Re-add the header to subsequent requests
                    req.Header("Prefer", "IdType =\"ImmutableId\"");
                    return req;
                }
            );
 
            try
            {
                Task.Run(() =>  pageIterator.IterateAsync()).GetAwaiter().GetResult();
 
            }
 
            catch (GraphAPI.ServiceException e)
            {
                using (TraceContext.Mailbox.create(TraceTopics.MailboxContextAddress(m_service)))
                {
                    TraceTopics.Graph.error("Error recceived in response ({}):\nError Code: {}\nError Message: {}", e.Error.GetType(), e.Error.Code.ToString(), e.Error.Message);
                }
 
                throw;
            }
            catch (Exception e)
            {
                using (TraceContext.Mailbox.create(TraceTopics.MailboxContextAddress(m_service)))
                {
                    TraceTopics.Graph.error(e.ToString());
                }
                throw;
            }
 
```

**Expected behavior**
The memory should not increase whether we specify page size or not.

**Versions**
Microsoft.Graph.dll – 4.10.0
Microsoft.Graph.Core.dll – 2.0.5

**Comment by sravya-datla** [comment]
any update on this?

**Comment by andrueastman** [comment]
Hey @sravya-datla,

We're currently investigating this and at the moment, we can't see differences when specifying the page size vs not specifying it.

Taking a look at your example below, 

```cs
            var pageIterator = GraphAPI.PageIterator<GraphAPI.Message>
            .CreatePageIterator(
                m_service.GraphClient,
                items,
                (m) =>
                {
                    //messages.Add(new Message(m, m_service, null));
                    return (messages.Count < messageCount);
                },
                // Used to configure subsequent page
                // requests
                (req) =>
                {
                    // Re-add the header to subsequent requests
                    req.Header("Prefer", "IdType =\"ImmutableId\"");
                    return req;
                }
            );
```

It looks like this line is commented out.  

```cs
//messages.Add(new Message(m, m_service, null));
```

Do you notice a difference on your side if the line is commented or not commented? I believe this results in the holding of the object handles for the items.
Any chance you could share the page sizes you are using when you replicate this?

**Comment by sravya-datla** [comment]
That line was commented just for our testing, we wanted to check if memory is increasing even if we are not holding the references of the objects anywhere. We are able to see memory increase even if we are not holding the references to Microsoft.Graph.Message anywhere and it keeps growing.

earlier we were using a page size of 1000. Now after we removed the page size from the request, there is no increase in memory.

**Comment by andrueastman** [comment]
Thanks for the feedback @sravya-datla.

Let me try to replicate this with the same page size and circle back to you.

**Comment by andrueastman** [comment]
Hey @sravya-datla,

It looks like not specifying the top query parameter results in the message pages to be retrieved 10 messages at a time. The `odata.NextLink` response value will automatically have a top parameter of 10.  e.g. `https://graph.microsoft.com/v1.0/me/messages?%24top=10&%24skip=20`. Hence not specifying a top parameter is functionally equivalent to specyfing a top parameter of 10.

Memory growth however seems to be a function of the size of the response body from the api, specifically the size of the message body as the message contents of 1000 messages (of varying size) are held in memory from the response. 

Optimizing the initial query with a select query parameter that excluded the message body from the request seems to be okay.

```cs
var messages = await graphServiceClient.Me.Messages.Request().Top(1000).Select("id,subject,toRecipients,sender,from").Header("Prefer", "IdType =\"ImmutableId\"").GetAsync();
```

Any chance you could confirm if the experience is the same for you?

**Comment by sravya-datla** [comment]
The number of mails we are testing with is the same when we are using default page size or page size 1000. These mails are automated mails(so small body). Why are we getting increase in memory when we are using 1000 pagesize and not when using default pagesize.  Using page iterator, we are iterating through all the messages in the mailbox ( so all the msgs are retrieved in both cases irrespective of page size).

**Comment by sravya-datla** [comment]
I will also test using the select query excluding body and attachments once and confirm

**Comment by sravya-datla** [comment]
I tested by excluding body, attachments from select query. Still seeing this issue. 
Please note: this method is called every 2 mins and we are sending mails to this mailbox paralelly (1 mail/second)

**Comment by andrueastman** [comment]
Thanks for the feedback @sravya-datla,

Just to confirm if the issue is related to the increased size of the response body when fetching 1000 results at a time instead of 10, can you confirm whether or not there is a difference in memory growth when you exclude the body, attachments from select query? Also, is there any chance you could share the parameters in the select query?

**Comment by sravya-datla** [comment]
The memory growth is pretty much the same even after excluding the body, attachments.

You can find the parameters of the Constants below:
MSG_SELECTION = "id,singleValueExtendedProperties,isRead,subject," +
                                             "importance,receivedDateTime,sentDateTime,toRecipients," +
                                             "ccRecipients,bccRecipients,replyTo,sender,from,parentFolderId,attachments,body,hasAttachments";

MESSAGE_CLASS = "singleValueExtendedProperties($filter = id eq 'String 0x001a')";
ORDER_BY_RCVDDATE = "receivedDateTime";
ORDER_BY_RCVDDATE_DESC = "receivedDateTime desc";

**Comment by andrueastman** [comment]
Thanks for this. 
I will circle back with more findings/conclusions once we test with this.  

> The memory growth is pretty much the same even after excluding the body, attachments.
> 
> You can find the parameters of the Constants below: MSG_SELECTION = "id,singleValueExtendedProperties,isRead,subject," + "importance,receivedDateTime,sentDateTime,toRecipients," + "ccRecipients,bccRecipients,replyTo,sender,from,parentFolderId,attachments,body,hasAttachments";
> 
> MESSAGE_CLASS = "singleValueExtendedProperties($filter = id eq 'String 0x001a')"; ORDER_BY_RCVDDATE = "receivedDateTime"; ORDER_BY_RCVDDATE_DESC = "receivedDateTime desc";

Thanks @sravya-datla. I will circle back with findings/conclusions once I test with this.

**Comment by andrueastman** [comment]
Hey @sravya-datla,

Any chance you can try pulling [Microsoft.Graph.Core version 2.0.9](https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.9) and confirm whether there are any improvements on this?
