### ISSUE TITLE
[BUG] graphClient.Subscriptions 

### ISSUE THREAD

**Issue by jsquire** [microsoftgraph/msgraph-sdk-dotnet#1309]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#28166](https://github.com/Azure/azure-sdk-for-net/issues/28166).

### Library name and version

Microsoft Graph 4.24

### Describe the bug

GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var subscriptions = await graphClient.Subscriptions
	.Request()
	.GetAsync();

returns subscriptions as null 

### Expected behavior

Should list all subscriptions 

### Actual behavior

@odata.context=https://graph.microsoft.com/v1.0/$metadata#subscriptions
value

### Reproduction Steps

GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var subscriptions = await graphClient.Subscriptions
	.Request()
	.GetAsync();

### Environment

Console Core application
Azure Identity 1.6.0
Microsoft Graph 4.24
dotnet 6.0 Windows 10

**Comment by andrueastman** [comment]
Hey @Vevish,

Thanks for raising this. 

I'm unable to replicate the null scenario when I have no subscriptions listed but instead obtain an. Any chance you could share the contents of the response body by changing your code to be something like this?

```cs
  var subscriptionsReponse = await graphServiceClient.Subscriptions
      .Request()
      .GetResponseAsync();

  var responseContentString = await subscriptionsReponse.Content.ReadAsStringAsync();
```

Also, to confirm, have you set the appropriate permissions/scopes based on the documentation [here](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#permissions)?

**Comment by Vevish** [comment]
> Hi Andru 
So I have already set the permissions for the application.
this is the print of the responseContentString 

{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#subscriptions","value":[]}

I do not receive a 401 error. I have granted Organization read, Directory Read, Subscription read. 
If i do some other query with the same application it works like below. he Subscription one is returning a null array even if i try nextpage with oData there is nothing.

Example code that works with the same application:
var doms=await graphServiceClient.Domains.Request().GetAsync();

foreach (var domain in doms)
{
    Console.WriteLine(domain.Id);
}

**Comment by andrueastman** [comment]
Thanks for clarifying @Vevish.

Are you using application permissions or delegated permissions when attempting to query the subscriptions?
Also, is there any chance that another app/person created the subscriptions other than the one querying?

According to [the documentation](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#basic-scenarios) the response will contain subscriptions made by the user/app.

**Comment by Vevish** [comment]
> Thanks for clarifying @Vevish.
> 
> Are you using application permissions or delegated permissions when attempting to query the subscriptions? Also, is there any chance that another app/person created the subscriptions other than the one querying?
> 
> According to [the documentation](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#basic-scenarios) the response will contain subscriptions made by the user/app.

Thanks, I am using Application permissions, I tried delegated also first. The subscriptions are created by another individual, we are trying to create automated reports. I have also granted the application permissions as reader on the Tenant Root Group. 
Subscription.Read.All can only be assigned as delegated. If i use the SDK list subscriptions works, but between using the SDK and graph i was thinking graph maybe better for long term, the SDK is also in beta and stuff does not work. we just want an API to work to read everything in azure for reporting.

**Comment by andrueastman** [comment]
> If i use the SDK list subscriptions works, but between using the SDK and graph i was thinking graph maybe better for long term, the SDK is also in beta and stuff does not work. we just want an API to work to read everything in azure for reporting.

Do you mean application permissions and delegated? Or what is the difference between SDK and graph in this scenario?

**Comment by Vevish** [comment]
> > If i use the SDK list subscriptions works, but between using the SDK and graph i was thinking graph maybe better for long term, the SDK is also in beta and stuff does not work. we just want an API to work to read everything in azure for reporting.
> 
> Do you mean application permissions and delegated? Or what is the difference between SDK and graph in this scenario?

I am Currently using application permissions, but Subscription.Read.All can only be assigned as delegated and can not be changed. Using the Azure SDK like below gets the subscriptions with the same application. 
 
  ArmClient armClient = new ArmClient(credential);

            var subs = armClient.GetSubscriptions();

            foreach (var v in subs)
            {
               Console.WriteLine(v.Id);
             }

**Comment by andrueastman** [comment]
I believe you cannot use Application permissions to list all the permissions created by any user by any app at the moment. 
This is covered in the documentation under the "Advanced Scenarios" section [here](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#advanced-scenarios). 

In this scenario, you would have to use the `Subscription.Read.All` delegated permissions just like the Azure SDK as well as this is a constraint on the API side.

**Comment by Vevish** [comment]
> I believe you cannot use Application permissions to list all the permissions created by any user by any app at the moment. This is covered in the documentation under the "Advanced Scenarios" section [here](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#advanced-scenarios).
> 
> In this scenario, you would have to use the `Subscription.Read.All` delegated permissions just like the Azure SDK as well as this is a constraint on the API side.

Hi Andru 
Thanks, We a large organization, one individual creates the Subscription and the application should be able to dynamically read that new subscription, can this not be fixed, instead of having this as a constraint, the Application ID was granted reader access to the whole tenant through management groups, this is fairly limiting us creating dynamic reporting

**Comment by andrueastman** [comment]
Hey @Vevish,

I hear you. Given the constraints one way would be to have the app create the subscription rather than the user or ensure the app used by the user to create the subscriptions is the same as the application reading them. 

Unfortunately, this is not a limitation on the SDK but rather on the API as the API dictates the permissions that can be used on an endpoint. I would also suggest creating a request at the link below with the API owners to look into supporting Application Permissions that support the scenario. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
