### ISSUE TITLE
Range download of an older version of a OneDrive with Graph API

### ISSUE THREAD

**Issue by akutsyk** [microsoftgraph/msgraph-sdk-dotnet#1319]
Hi,
I'm trying to improve download operations for OneDrive files with a big size. 
In case of using latest document version I'm able to use Range Header options and it is working fine.
But in case of using for all previous versions of the object it is returning only a whole stream no matter of what options are using.

For instance if you have two versions of file and want to download both with a range download. 
Version 2.0 will be downloaded fine and for version 1.0 it will return entire stream.

```
    long rangeFrom = 0L; 
    long rangeTo = 200L;
    var versionId = "1.0";
    var userId = "your user ID";
    var itemId = "your item ID";
   
    var options = new List<Option>
            {
                new HeaderOption("Range", $"bytes={rangeFrom}-{rangeTo}")
            };

    if (string.IsNullOrEmpty(versionId))
    {
        var request = client.Users[userId].Drive.Items[itemId].Content.Request(options);

        using var stream = await request.GetAsync(cancellationToken) as MemoryStream;
    }
    else 
    {
        var request = client.Users[userId].Drive.Items[objectId].Versions[versionId].Content.Request(options);

        using var result = await request.GetAsync(cancellationToken) as MemoryStream;

        return result.ToArray();
   }
```

I'm expecting to have an ability of range download for all versions not only for latest one.

PS: similar question https://stackoverflow.com/questions/62654777/is-range-download-of-an-older-version-of-a-onedrive-file-supported-using-microso

**Comment by andrueastman** [comment]
Hey @akutsyk,

Thanks for raising this. 

As this is a question regarding API behavior, any chance you can cross post this at the link below to get feedback from the API owners with regards to the status. It would also be great if you could post the link to the query here so that a future user may be able to find the information.

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html
