### ISSUE TITLE
Add open and schema extensions

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#132]
Respond to this thread when live in Nuget package
https://stackoverflow.com/questions/44203316/with-microsoftgraph-sdk-how-do-you-add-extension-property-to-user

**Comment by cveld** [comment]
1.4.0 seems to be live now! Thanks. What should also be provided is an example of how to enrich OOTB entities with schema extensions. E.g. how to read and write Group entities that encompass a schema extension?

**Comment by MIchaelMainer** [comment]
You make a great point. I'm going to leave this task open until I add a test case that shows how to access the schema extension property via the AdditionalData property bag.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.Test/Requests/Functional/SchemaExtensionTests.cs

**Comment by MIchaelMainer** [comment]
c63726b3 contains a write example of how to write an entity with a schema extension. You'll access the schema extension through the addtionalData property.
