### ISSUE TITLE
Odering ManagedDevices has no effect

### ISSUE THREAD

**Issue by DennisBergemann** [microsoftgraph/msgraph-sdk-dotnet#1322]
HI,

i try to get ordered managedevices but, all ordering will be ignored.

`var queryOptions = new List<QueryOption>
            {
                new QueryOption("$top",$"50"),
            };
             var orderBy = "deviceName";

            var managedDevices = await _graphServiceClient.DeviceManagement.ManagedDevices
                                                 .Request(queryOptions)
                                                 .Header("ConsistencyLevel", "eventual")
                                                 .OrderBy(orderBy)
                                                 .Select("deviceName")
                                                 .GetAsync();`

code above is an example.

Am I doing something wrong?
Is there another way for the intune queries?

thanks a lot

**Comment by MIchaelMainer** [comment]
I don't think you're doing anything wrong. I suspect that the endpoint doesn't support service-side ordering as I don't see an example in the documentation. Your experience would also confirm that.

https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0

The client libraries are generated which results in some operations being generated for service-side functionality that doesn't exist. 

You'll want to perform the ordering client-side.

**Comment by DennisBergemann** [comment]
Ok i think you right, the endpoint gives same results. The original intune is using same endpoint but an internaly key for internaly version. Here ordering works as aspected. So for external use ordering seems to be unsupported yet.
I hoped you knows a way out
