### ISSUE TITLE
Expose fax number in user contacts

### ISSUE THREAD

**Issue by slackerbob** [microsoftgraph/msgraph-sdk-dotnet#1325]
I'm presently migrating a program from EWS (.net framework/Windows) to Graph (.net6/Linux) that adds/modifies contacts (including office/mobile/fax numbers) for specific office365 users.

Perhaps I've missed something, but I don't see any way to add/modify a fax number for an office365 user contact in Graph.

I'm requesting, that in addition to:
Contact.BusinessPhones
Contact.MobilePhone

We add the following:
Contact.BusinessFax(es)

Or something similar, or some other way to access/modify Fax number in office365 contacts from Graph/.net6.

**Comment by andrueastman** [comment]
Hey @slackerbob,

Thanks for raising this.

As this is a request for the API workload team, we've raised the feature request at the link below for them to act upon. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-support-to-access-modify-fax-number-in-office365-contacts/idi-p/3384881

We'll close this for now as the issue can be followed up (an upvoted) there.
