### ISSUE TITLE
Graph SDK can't be used on MacCatalyst

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1329]
**Describe the bug**
I can't use the `Microsoft.Graph` package in a .NET 6 app that runs in MAUI with target MacCatalyst, it fails with the error that Xamarin.iOS is required but not found. If I do a custom build and explicitly specify MacCatalyst as target for `Microsoft.Graph.Core` and `Microsoft.Graph` and add a constant `iOS` I get the error that the compression mechanism used is not supported

**To Reproduce**
Create a .NET MAUI app for `net6.0-maccatalyst` and try to use graph sdk

**Expected behavior**
Graph sdk should work as it does in windows

**Comment by maisarissi** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/413

**Comment by andrueastman** [comment]
Closing this for now to be tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/413
