### ISSUE TITLE
Microsoft Graph endpoint doesn't work with MailKit (While Outlook Endpoint works)

### ISSUE THREAD

**Issue by Just1n** [microsoftgraph/msgraph-sdk-dotnet#1330]
This is a follow-up of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3234

The repro is pretty straight, just use below code, you'll get Authenticate Failed error.

```csharp
                      var publicClientApplication = PublicClientApplicationBuilder.Create("73e31e62-5fee-4eb5-8a07-d726ab53a62f")
				.WithLogging(MyLoggingMethod, LogLevel.Info, enablePiiLogging: true, enableDefaultPlatformLogging: false)
				.WithAuthority("https://login.microsoftonline.com/common") // SuppressCodeSmell Reason = No need translation
				.WithDefaultRedirectUri().Build();

			var scopes = new[] {
				"email",
				"offline_access",
				//"https://outlook.office.com/IMAP.AccessAsUser.All",
				"IMAP.AccessAsUser.All",
			};

			var authToken = publicClientApplication.AcquireTokenInteractive(scopes).ExecuteAsync().Result;

			var oauth2 = new SaslMechanismOAuth2(authToken.Account.Username, authToken.AccessToken);

			using (var client = new ImapClient())
			{
				client.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
				client.Authenticate(oauth2);
				Console.WriteLine("Authenticated");
				client.Disconnect(true);
			}
```
If I uncomment the scope `"https://outlook.office.com/IMAP.AccessAsUser.All"`, and comment `"IMAP.AccessAsUser.All"`, everything works fine. 
It means Outlook REST API endpoints works while Microsoft Graph endpoints doesn't work.
But according to this [link](https://docs.microsoft.com/en-us/outlook/rest/compare-graph), it says:
`The Outlook REST endpoints will be fully decommissioned in November 2022. Migrate existing apps to use Microsoft Graph.`, is this a  Graph ednpoints issue? Or can you guide me how could I migrate existing apps to use Microsoft Graph?

**Comment by MIchaelMainer** [comment]
@Just1n You haven't made a request to Microsoft Graph in your example.  You used the legacy endpoint Exchange. Please take a look at our [Getting Started](https://developer.microsoft.com/en-us/graph/get-started/dotnet-core) content to learn how to use Microsoft Graph.

**Comment by Just1n** [comment]
@MIchaelMainer I followed this [sample](https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2) for the coding.
The difference is, I use the authResult AccessToken to generate a SaslMechanismOAuth2 object to do the IMAP OAuth 2 Authentication by using MailKit library.
Code like below:
```csharp
var oauth2 = new SaslMechanismOAuth2(authResult.Account.Username, authResult.AccessToken);
client.Connect("outlook.office365.com", 993, SecureSocketOptions.SslOnConnect);
client.Authenticate(oauth2);
```
It got `Authentication failed` error.
According to your reply, can you pelase confirm whehter my understanding is correct?
1. The reason of `Authentication failed` by using `IMAP.AccessAsUser.All` scope for MailKit OAuth2 authentication is because the MailKit connection endpoint `outlook.office365.com` is a legacy one.
2. If I want to use Graph scope, I must connect to Graph endpoint https://graph.microsoft.com/v1.0/
3. Based on 1 and 2,  does that mean it's **impossible** to use Graph scopes for MailKit library?
4. And according to this [link](https://docs.microsoft.com/en-us/outlook/rest/compare-graph), the outlook rest api endpoints will be **fully decommissioned in November 2022**, does this mean MailKit won't support OAuth 2 authentication for Office 365 any more after November 2022?
5. If above is correct, any suggestion to MailKit author @Jstedfast to address the decommissioning of legacy endpoints? (I'll copy current link to this [thread](https://github.com/jstedfast/MailKit/issues/1126).)
6. We have a product that is using MailKit to do the email incoming & outgoing, and recently we have implemented the OAuth 2 authentication to address the another [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online), but we had to use legacy endpoints (something like `https://outlook.office.com/IMAP.AccessAsUser.All`) coz MailKit doesn't support using Graph scopes. Since the legacy endpoints will be decommissioned soon, any suggestion to me to address this case so that it won't affect our clients' business?

**Comment by MIchaelMainer** [comment]
Hello @Just1n 
1. - I believe it failed because Azure Identity needs the context of the targeted API. That would make sense why the fully-qualified scope name works. I'm curious, were you able to use the IMAP client to retrieve email with that token?
2. - Yes. 
3. - Correct. Graph scopes can't be used for MailKit. Microsoft Graph is not a IMAP, POP3, or SMTP server or gateway.
4. - The REST API endpoints will be decommissioned, I don't know about IMAP -- that article mentioned the need to use OAuth for IMAP. 
5. - I don't think IMAP is going anywhere based on the linked article, [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online). I think what might be confusing is that we no longer see the [Exchange API permissions](https://stackoverflow.com/questions/58914816/oauth2-imap-how-to-request-consent-for-imap-accessasuser-all-permission-for-a) any longer. So we have to use IMAP scopes defined as being under the Microsoft Graph. But in reality, those IMAP permissions are likely meant to be used against Exchange Online (like you have already). Users just need to qualify that the scope is for https://outlook.office.com/IMAP.AccessAsUser.All, and not https://graph.microsoft.com/IMAP.AccessAsUser.All
6. - I'd make a plan to use Microsoft Graph in the future for your product. IMAP is still a substantial protocol but should be replaced. Note that the docs say the legacy REST API will be decommissioned. It doesn't mention IMAP so I'm going to assume that it will continue to work if using OAuth2 tokens instead of whatever else it used before (probably NTLM).

**Comment by Just1n** [comment]
Hi @MIchaelMainer 
For 1,  Yes, MailKit OAuth2 authntication works perfectly while using scopes `https://outlook.office.com/IMAP.AccessAsUser.All`, `https://outlook.office.com/POP.AccessAsUser.All` and `https://outlook.office.com/SMTP.Send`.  But it doesn't work when I removed the prefix `https://outlook.office.com/`.
For 4, 5 & 6, actually these confused me a lot, I have more questions.
I followed this [link](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth) to authenticate an IMAP, POP & SMTP connection using OAuth, in this article it recommends to use scopes `https://outlook.office.com/IMAP.AccessAsUser.All`, `https://outlook.office.com/POP.AccessAsUser.All` and `https://outlook.office.com/SMTP.Send`. But in this [link](https://docs.microsoft.com/en-us/outlook/rest/compare-graph) which I mentioned earlier it says the scopes with prefix `https://outlook.office.com/` are legacy ones, and will be decommisioned. So questions are:
a. Are the **scopes** in the 2 links same thing?
b. If they are the same thing, does this mean that what is said in the 2 links contradicts each other?
c. If they are not the same thing, is it **safe** that I keep using `https://outlook.office.com/xxxx` as the scopes in MailKit OAuth2 authentication even after November 2022?

**Comment by MIchaelMainer** [comment]
I think I see the confusion. The REST API at https://outlook.office.com/ is legacy and will be decommissioned. The scopes are a separate concern. The scopes defined with the prefix `https://outlook.office.com/` are a different concept; there is no statement about those scopes being decommissioned.  
a. Yes, it appears that they are the same scopes. What is confusing is that the scopes are listed under Microsoft Graph, and are assumed to be for Microsoft Graph **unless** they are fully qualified with `https://outlook.office.com/`.
b. I don't see a contradiction as there isn't a mention of the scopes being decommissioned.
c. I have the same information as you. This is the first time I've seen that content. The only option that I can confidently deem safe is migrating to use Microsoft Graph for your mail scenarios. I can't speak to using https://outlook.office.com/xxxx as the scopes in MailKit OAuth2 authentication even after November 2022.
