### ISSUE TITLE
[Client bug]: ArgumentNullException for Select method on user's events

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1339]
**Describe the bug**
When `Select` method is used for user's events then `GetAsync()` throws `ArgumentNullException`.

**To Reproduce**
`var response = await graphServiceClient.Users[{upn}].Events.Request().Select("subject").GetAsync();`

or

```
var response = await graphServiceClient.Users[{upn}].Events.Request()
    .Select(e => new
    {
        e.Subject
    })
    .GetAsync();
```

**Expected behavior**
No exception is thrown.

**Additional context**
```
ExceptionMessage: "Value cannot be null.\r\nParameter name: source",
ExceptionType: "System.ArgumentNullException",
StackTrace:
at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
at MSGraphService.API.Controllers.v1_0_CalendarController.<>c.<TransformResult>b__6_0(Event e)
at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at MSGraphService.API.Controllers.v1_0_CalendarController.TransformResult(ICollectionPage`1 events)
at MSGraphService.API.Controllers.v1_0_CalendarController.<UserEvents>d__3.MoveNext()
```

**Comment by philipstratford** [comment]
I am also experiencing exactly this issue.

**Comment by andrueastman** [comment]
Hey @philipstratford, @MartinM85,

Thanks for raising this. Any chance you can confirm the SDK version in use when replicating this scenario?

**Comment by philipstratford** [comment]
> Thanks for raising this. Any chance you can confirm the SDK version in use when replicating this scenario?

In my case it's 4.24.0.0

**Comment by MartinM85** [comment]
> Hey @philipstratford, @MartinM85,
> 
> Thanks for raising this. Any chance you can confirm the SDK version in use when replicating this scenario?

The SDK version is 4.24.0.0

**Comment by andrueastman** [comment]
Hey @philipstratford, @MartinM85,

Unfortunately, I am unable to replicate this scenario on my end as I am able to retrieve a list of events with the version provided. 

Any chance you could share more information on the target runtime you are using?
I also notice that the exception stack trace does not reference the Graph SDK binaries. Any chance you can confirm that `response` variable is returned successfully with a log statement/debugger?

**Comment by philipstratford** [comment]
@andrueastman Prompted by your request I did some extra debugging and, as you suspected, the `response` does have a value after the Graph API is called. In my case, it seems that some of my own code that was working on the response from the Graph service was causing the error as it was expecting values in properties whose values were NULL because of the use of the `Select` method. Very much my mistake, sorry!
