### ISSUE TITLE
InvalidFormatException in RequestInformation.URI (5.0.0-preview.4)

### ISSUE THREAD

**Issue by tstojecki** [microsoftgraph/msgraph-sdk-dotnet#1346]
**Describe the bug**
Preview 5.x throws InvalidFormatException when calling RequestInformation.URI {get}

**To Reproduce**
```
var client = new GraphServiceClient(...);
var request = client.Users.CreateGetRequestInformation(); 
var uri = request.URI; // <- InvalidFormatException
```

**Expected behavior**
request.URI outputs request Uri

**Desktop (please complete the following information):**
 - OS: win-10 x64
 - Browser chrome
 - Version 5.0.0-preview.4

**Additional context**
{+baseuri} in [string]templateUri never gets replaced with a value. 

As a result, string is invalid when passed through to the Uri 
``` return new Uri(uriTemplate.Resolve()) ```

https://github.com/microsoft/kiota-abstractions-dotnet/blob/main/src/RequestInformation.cs#L57

**Comment by andrueastman** [comment]
Hey @tstojecki,

Thanks for raising this. It looks like the `baseUrl` is being added to the pathParameters just before the request is sent out and not when `CreateGetRequestInformation` is called.

For now, you can work around this by using the snippet below as we resolve this in the generator.

```cs
            var request = graphClient.Users.CreateGetRequestInformation(); 
            request.PathParameters.Add("baseurl", graphClient.RequestAdapter.BaseUrl); // add this
            var uri = request.URI;
```
