### ISSUE TITLE
Read email outlook with another account

### ISSUE THREAD

**Issue by mpamaral72** [microsoftgraph/msgraph-sdk-dotnet#1348]
I need to read a certain email but a different account.

The first example works

            string applicationClientID = "aaaaaaaaaaaaaaaaaaaa";
            string directoryTenantID = "dddddddddddddddddd";
            string secretID = "sssssssssssssssssssssss";

  //Example 01: OK
             
            string email = "emailRead@outlook.com"; //WORKS: account 
            that will read the email = emailRead@outlook.com

 

//Example 02: Error need to read emailRead@outlook with account countService@outlook.com

            string email = "emailRead@outlook.com"; // DOES NOT WORK: 
            account that has permission to read email:  
            countService@outlook.com

            var credentials = new ClientSecretCredential(
            directoryTenantID, applicationClientID, secretID,
            new TokenCredentialOptions { AuthorityHost = 
            AzureAuthorityHosts.AzurePublicCloud });

            GraphServiceClient graphServiceClient = new 
            GraphServiceClient(credentials);

            var inboxMessages = await graphServiceClient
                .Users[email]
                .MailFolders["inbox"]
                .messages
                .Request()
                .Expand("attachments")
                .Top(20)
                .GetAsync();

//I get the following message: Message: Access to OData is disabled.

**Comment by andrueastman** [comment]
Hey @mpamaral72,

Thanks for raising this. 

It looks like the issue may be related to limiting application permissions as described in the documentation below. Any chance you checked it out?

https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access

**Comment by mpamaral72** [comment]
Thank you for your attention!

My problem is that the company has an email to be read ex: emailCompany@outlook.com


And they created a corporate account with read permissions for the above email accountCompany@outlook.com

The question is whether it is possible to read the emailCompany@outlook.com through the accountCompany@outlook.com

**Comment by andrueastman** [comment]
Hey @mpamaral72,

I believe this should be possible if you read the emails from a shared mailFolder. Any chance you have checked out the documentation below? 

https://docs.microsoft.com/en-us/graph/outlook-share-messages-folders
