### ISSUE TITLE
Could not find Users[<id>].Chats.GetAllMessages method (5.0.0-preview 4)

### ISSUE THREAD

**Issue by Dessk** [microsoftgraph/msgraph-sdk-dotnet#1358]
Hi. I'm currently working on a new preview and I'm having trouble finding GetAllMessages for user chats. In v4 I was able to call this via client.Users[<id>].Chats.GetAllMessages().Request().GetAsync() and I cannot find any alternative in v5. As a quick solution I simply call "/users/{id}/chats/getAllMessages" using the http client and mapping response to GetAllMessagesResponse, but I don't know if I'm not missing something out. 

Any help or clarification would be very helpful!

**Comment by zengin** [comment]
It looks like this is generated for the top-level Microsoft.Graph.Chats.ChatsRequestBuilder:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/de957836a5ebea22878831da7488bb4a4f870f9e/src/Microsoft.Graph/Generated/Chats/ChatsRequestBuilder.cs#L103

but not in Microsoft.Graph.Users.Item.Chats.ChatsRequestBuilder:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/de957836a5ebea22878831da7488bb4a4f870f9e/src/Microsoft.Graph/Generated/Users/Item/Chats/ChatsRequestBuilder.cs#L13

@andrueastman @baywet, is this an OpenAPI conversion issue?

**Comment by andrueastman** [comment]
This looks to be a conversion issue. This has been raised here https://github.com/microsoft/OpenAPI.NET.OData/issues/201

**Comment by baywet** [comment]
yep, all actions/functions defined on collections are missing for navigation properties but are present for entity sets at the conversion stage.

**Comment by Dessk** [comment]
Thanks for the answer! I thought it might be something wrong with the code generation. I'll be waiting for updates on this as it was probably the only way to get user chats. I know there is a users/{id}/chats endpoint available in the beta, but it is currently quite buggy and unstable.

**Comment by andrueastman** [comment]
Closing this one for now. 

This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1379 and is available in the latest preview packages of the SDK.
