### ISSUE TITLE
 Only HTTP/1.0 and HTTP/1.1 version requests are currently supported

### ISSUE THREAD

**Issue by hannespreishuber** [microsoftgraph/msgraph-sdk-dotnet#1367]
get exception Code: generalException
Message: An error occurred sending the request. with followin codee

`   msgresponse = Await graphClient.Teams("1cccc") _
                .Channels("19:bd775xxxxx@thread.skype").Messages _
                .Request() _
                .AddAsync(ChatMessage)`

exact same code works in diffrent project

Windows 11
Visual Studio 22
asp.net webforms vb.net
.net 4.8
graph 4.29 (going to 5 code wont compile)
azrue core 1.42

https://github.com/hannespreishuber/GraphDemovonppedv
default.aspx.vb

**Comment by andrueastman** [comment]
Hey @hannespreishuber,

Thanks for raising this.

The latest versions of the library do try to perform http calls via HTTP/2, however it looks like you are using a custom http client to create the `GraphServiceClient`, any chance you have any like if you change this line 

https://github.com/hannespreishuber/GraphDemovonppedv/blob/master/GraphDemovonppedv/Default.aspx.vb#L45

to be something like

```cs
        Dim _httpClient = GraphClientFactory.Create(authenticationProvider:=Nothing)
```

**Comment by jdew73** [comment]
I am also having the same issue when uploading documents to Sharepoint.  Anything under 4 MB works fine as long as I set the RequestMessage's version to 1.1.  Anything above 4 MB -- where I need to use a LargeFileUploadTask -- returns the "Only HTTP/1.0 and HTTP/1.1 version requests are currently supported" message.  If I remove the RequestMessage 1.1 version, I get a general exception.  Please advise.  This has killed large file uploads in our app without a stitch of our code changing.  

Also, note, we can't set the authorizationprovider to nothing -- need to be able to pass the token along to send the document.

**Comment by andrueastman** [comment]
Hey @jdew73,

Thanks for raising this. 
Are you able to provide more information about the SDK version and dotnet Runtime information you are using in you app scenario as well as how the GraphClient is initialized?

**Comment by jdew73** [comment]
VB.NET
Microsoft Graph 4.24.0
.NET Framework 4.7.2 (we just upgraded from 4.6.1, which did work previously with the same code, except we did not have to specify the message version)

I have tried two different methods to initialize the GraphClient:

#1) client = New Microsoft.Graph.GraphServiceClient(New Microsoft.Graph.DelegateAuthenticationProvider(Function(requestMessage)
                                                                                                                       requestMessage.Headers.Authorization = New AuthenticationHeaderValue("Bearer", token)
                                                                                                                       requestMessage.Version = New Version(1, 1)
                                                                                                                       etc.
                                                                                                                   End Function))

#2) _httpclient = Microsoft.Graph.GraphClientFactory.Create(authenticationProvider:=Nothing)
client = New GraphServiceClient(_httpclient)
And then set the client.AuthenticationProvider after.

Neither works.

**Comment by jdew73** [comment]
At the moment, your first suggestion (the baseClient parameter) looks quite promising.  It has worked with a couple of tests.  I will do more testing, but I think that did the trick.  Thank you.  I will post again if I hit a stumbling block.

**Comment by romandres** [comment]
I ran into the same error in a different scenario so I'm not sure if they are related: Using Graph v4 to get all groups in a PowerShell module targeting .NET Standard 2.0 running in Windows PowerShell 5.1. This works when running in PowerShell 7. Using Graph v3 works for both PowerShell versions.

I created a little example to replicate the issue [here](https://github.com/romandres/graph-ps-http-version-issue-example). The README contains more details. I hope this helps.

**Comment by fzbm** [comment]
For anyone having the same issue when using .NET 4.7.2 and `HttpClientFactory`: Use `WinHttpHandler` as the primary `HttpMessageHandler`. The by default used `HttpClientHandler` implementation of 4.7.2 uses a `HttpWebRequest`, which does not support any other HTTP version than 1.0 and 1.1.

```csharp
services
    .AddHttpClient("Graph", ...)
    .ConfigurePrimaryHttpMessageHandler(() => new WinHttpHandler());
```
