### ISSUE TITLE
Send a Sharing Invitation for a DriveItem to a Group, using alias or objectId?

### ISSUE THREAD

**Issue by alx-andru** [microsoftgraph/msgraph-sdk-dotnet#137]
Hi everyone,

as I was adding a Group of type Security Group to a DriveItem, I was wondering if using the **alias** as a recipient instead of the **objectId** is correct.

Following 
POST `https://graph.microsoft.com/beta/drives/[DRIVE_ID]/items/[ITEM_ID]/invite`
```C#
{
  "recipients": [
    {
      "objectId": "[GROUP_OBJECT_ID]"
    }
  ],
  "message": "Here's the file that we're collaborating on.",
  "requireSignIn": true,
  "sendInvitation": false,
  "roles": [ "write" ]
}
```
results in the error response:
```C#
{
  "error": {
    "code": "invalidRequest",
    "message": "The request is malformed or incorrect.",
    "innerError": {
      "request-id": "115a1bc9-d0dd-44a1-adc4-0834054bbe10",
      "date": "2017-06-07T21:30:33"
    }
  }
}
```

However, if I use **alias** instead of **objectId**, I receive a success response and the group is granted permission to the DriveItem.

I'm not sure if it is a bug or if the documentation should be more specific in what cases an alias has to be used and in what cases an objectId can be used. 

The wording
> The alias of the domain object, for cases where an email address is unavailable (e.g. security groups).

provided me with a hint to just swap objectId with alias even though I wouldn't expect it.

**Comment by alx-andru** [comment]
I've also discovered that using the MicrosoftGraph dot.net SDK like following
```c#
DriveRecipient[] recipients = {
  new DriveRecipient {
    Alias = [GROUP_OBJECT_ID]
  }
};

string[] roles = { "write" };
bool requireSignIn = true;
bool sendInvite = false;
            
var invited = await _graph.Drives[DRIVE_ID]
  .Root.ItemWithPath("folder/path")
  .Invite(recipients, requireSignIn, roles, sendInvite, "")
  .Request().PostAsync();
            
```
results in not resolving the actual group, but treating it as a user and using a displayname like following:
`cbcf9ab2-24e5-4b41-8be3-15f6c4c00811 (/sharepoint/2009/08/claims/farmid)`
The Object_ID in the displayname is the actual GROUP_OBJECT_ID

Looking up the shared with of the folder at `tenant.sharepoint.com` I see under 'User Information" following information:
```
Account	c:0%.c|system|cbcf9ab2-24e5-4b41-8be3-15f6c4c00811
Name	cbcf9ab2-24e5-4b41-8be3-15f6c4c00822 (/sharepoint/2009/08/claims/farmid)
Work email	 
About me	
 
Picture	 
SIP Address
```
comparing it to a different group which as been added via REST, the account looks like following:
`Account	c:0-.f|rolemanager|s-1-5-21-4230953499-852882675-3159599270-21018052`

I'm not sure if I'm doing something wrong on using the SDK compared to the REST API.

**Comment by alx-andru** [comment]
As mentioned above, using the attribute "alias" instead of "objectId" results in a correct permission grant. Using the dot.net SKD like following:

```C#
DriveRecipient[] recipients = new DriveRecipient[1];
recipients[0] = new DriveRecipient
  {
    Alias = "GROUP_OBJECT_ID"
  };

string[] roles = { "write" };
bool requireSignIn = true;
bool sendInvite = false;
            
var invited = await _graph.Drives["DRIVE_ID"]
  .Root.ItemWithPath("/PATH/TO/FOLDER")
  .Invite(recipients, requireSignIn, roles, sendInvite, "")
  .Request().PostAsync();
```
The result "invited" contains an invalid DisplayName
 
`DisplayName "d2a25882-942a-42f7-9e3f-1de13bcf2e62 (/sharepoint/2009/08/claims/farmid)"` instead of the actual displayname of the group I'd like to add.
Here's a snapshot of the Object through a Watch
![invitegroup](https://user-images.githubusercontent.com/19511694/26993851-e5f76b6c-4d32-11e7-810f-adb980201e90.PNG)

In Sharepoint, looking at the granted permissions I see following:
```
Account	c:0%.c|system|d2a25882-942a-42f7-9e3f-1de13bcf2e62
Name	d2a25882-942a-42f7-9e3f-1de13bcf2e62 (/sharepoint/2009/08/claims/farmid)
```

I'm not quite sure what I'm doing wrong here. Funny enough, if I set a breakpoint after the PostAsync(), and run it again the proper DisplayName is being assigned.

**Comment by MIchaelMainer** [comment]
Are you saying that if you call this (below), you play it twice with a break in between, it sets the name correctly? What happens if you make the call twice without a breakpoint?

```csharp
var invited = await _graph.Drives["DRIVE_ID"]
  .Root.ItemWithPath("/PATH/TO/FOLDER")
  .Invite(recipients, requireSignIn, roles, sendInvite, "")
  .Request().PostAsync();
```

**Comment by alx-andru** [comment]
Hi @MIchaelMainer thanks for the reply, if I call them directly one after each other like this:
```
var invited = await _graph.Drives["DRIVE_ID"]
  .Root.ItemWithPath("/PATH/TO/FOLDER")
  .Invite(recipients, requireSignIn, roles, sendInvite, "")
  .Request().PostAsync();

var invited2 = await _graph.Drives["DRIVE_ID"]
  .Root.ItemWithPath("/PATH/TO/FOLDER")
  .Invite(recipients, requireSignIn, roles, sendInvite, "")
  .Request().PostAsync();
```
I do receive two invitations, both with the `GUID/farmid` format

However If I set a breakpoint right after the invite has been resolved, move the yellow pointer up to var invited and run it again, the proper Group Displayname is resolved.

**Comment by MIchaelMainer** [comment]
Can you share with us a Fiddler trace of this?

**Comment by alx-andru** [comment]
Absolutely, I tried to use the Diagnostic tools but the Application Insight search just shows me the sequence of calls with no way or at least obvious way to look into the request and response.
I assume you'd like me to use Fiddler as a proxy and record the request? If not, do you have a link to a tutorial handy so I provide you with the exact data you expect? 

Thanks for the support!

**Comment by MIchaelMainer** [comment]
Oh, I see. It isn't a mail enabled security group. I was going to ask to see what the results are if you use the groups email address.

That looks like a bug in the service. I will report this.

**Comment by MIchaelMainer** [comment]
@alx-andru What is the behavior you see if you use the **objectId** in stead of **alias** field for identifying the security group?

{"message":"","recipients":[{"**alias**":"24727938-a0b3-4242-a591-cdf52832d53b"}],"requireSignIn":true,"roles":["write"],"sendInvitation":false}

**Comment by alx-andru** [comment]
Hi @MIchaelMainer , 
I just send an invite again through a REST API call to confirm, it's simply saying **invalidRequest**.
```Javascript
{
  "error": {
    "code": "invalidRequest",
    "message": "One of the provided arguments is not acceptable.",
    "innerError": {
      "request-id": "b21f8a75-2b1e-46da-9d20-a8bd18d9e07c",
      "date": "2017-06-12T20:05:05"
    }
  }
}
```

I'm not sure if I'm reading the [DriveRecipient Documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driverecipient) wrong or if it is intended to be used as Alias.

**Comment by alx-andru** [comment]
Is there a way I could work around it?

**Comment by MIchaelMainer** [comment]
I'm not sure whether these is a way to workaround this. I've reported this defect and am waiting on action for it. So, if you use the alias, and despite the display name being incorrect, is the drive item correctly shared with the group?

**Comment by alx-andru** [comment]
Thanks for staying in engaged. Unfortunately the drive item is not correctly shared with the group. In my specific case the workaround is to manually correct it via sharepoint and and a few swift mouse clicks.

**Comment by alx-andru** [comment]
HI @MIchaelMainer just following up to know if there are any updates or workarounds to this issue.

**Comment by alx-andru** [comment]
For everyone running into similar issues. I might have the suspicion that the Microsoft User Profile Service has not completed yet to fully create and populate the full group information from Sharepoint to Onedrive. As the id itself is a valid id, "a" permission is granted and results in the technical looking name `(/sharepoint/2009/08/claims/farmid)` 

Basic **workaround** is to wait 15s and retry. In most cases the first permission grant fails, but succeeds the seconds time. The failed attempt has to be cleaned up afterwards.

**Comment by MIchaelMainer** [comment]
Checked on the service issue tracking. A fix hasn't been checked in as of today.

**Comment by MIchaelMainer** [comment]
A fix has been checked in for fixing the display name. Can you tell me whether you see this?

**Comment by alx-andru** [comment]
@MIchaelMainer  thanks for the update. I just did a clean test on our system and the same issue still remains as described. 
![farmid](https://user-images.githubusercontent.com/19511694/32555810-c3712ba4-c46b-11e7-94b0-998e22772978.png)

**Comment by MIchaelMainer** [comment]
@alx-andru Thank you for confirming the state. I will follow up later when I have more info.

**Comment by ificator** [comment]
The fix is currently deploying, and so it's possible that your farm just hasn't been upgraded yet. Let's give it until the beginning of next week to validate.

Here's what the change does:
1. We allow you to specify the value in the `objectId` property now. You should use this instead of `alias` for OID cases.
2. If you specify `objectId`, and the value is unrecognized, we'll now return a 404. For your scenario, since you know that the principal was just created, you can use this as an indicator that the required propagation has not yet occurred, and you should try again "soon".

**Comment by alx-andru** [comment]
@ificator Thanks for the detailed description, it does help us a lot to stabilize our system.
I'll try it again next week and keep you updated!

**Comment by alx-andru** [comment]
Just wanted to confirm, the roll-out seems to have been taken place by now. What I seen right now is that setting the `ObjectId` accordingly works as expected, but takes significant longer than using the `Alias` with the now correct Objectname (not as previously the ObjectId). 

Is there any confirmation of this behavior (adding permissions via alias rather than objectid is quicker) or was it most likely just coincidence for the times I tried it?

**Comment by ificator** [comment]
When you say significantly longer, are you referring to the execution of the invite call itself or the amount of time it takes before we succeed (as opposed to returning a 404)?

Under the covers there realistically isn't any difference between specifying `objectId` vs `alias` apart from some extra validation we can execute based on expect constraints for the values provided to each. Those validation steps should have a negligible impact on request execution time.

**Comment by alx-andru** [comment]
Hey @ificator, I am referring to the amount of time it takes until the group is invited. Currently we create the group and keep trying to invite that group with a delay of 20 seconds until we don't receive a 404 anymore. Playing around with it, referencing the group via the alias seemed to work reliable on the second attempt, whereas referencing to the group via the objectid seemed to work at about the 4-6th attempt. I was just wondering if this was just random coincidence or intended.

The API call and the permission invite is working as expected.

**Comment by subbiahkk** [comment]
Hi,

I am getting the same error while giving access to other user. It was working good and stop working all of a sudden. my payload is like this

{
  "recipients": [
    {
      "Alias": "frank@abcd.onmicrosoft.com"
    }
  ],
  "message": "Here's the file that we're collaborating on.",
  "requireSignIn": true,
  "sendInvitation": false,
  "roles": [
    "write"
  ]
}

and my response is 

{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "96f23f65-4463-4502-85a3-c227735e4a49",
            "date": "2018-05-15T02:53:11"
        }
    }
}
