### ISSUE TITLE
[Client bug]: Page iterator and messages delta query throw NullReferenceException

### ISSUE THREAD

**Issue by gaspik** [microsoftgraph/msgraph-sdk-dotnet#1376]
**Describe the bug**
I'm trying to upgrade from v4 to v5 beta API, currently running 5.5.0-preview nuget.

When trying to load messages using delta query, NullReferenceException is thrown in client library. Similar approach to iterate message folders results in valid response, but no delta query is used there. Stack trace:

```
   at Microsoft.Graph.PageIterator\`2.ExtractNextLinkFromParsable(TCollectionPage parsableCollection, String nextLinkPropertyName)
   at Microsoft.Graph.PageIterator\`2.IntrapageIterate()
   at Microsoft.Graph.PageIterator\`2.<IterateAsync>d__21.MoveNext()
```

I believe this is caused by DeltaResponse not having NextLink property

**To Reproduce**
Try to load messages from folder using delta query and iterate the page. My example code:

```
var mailDeltaRequest = GraphServiceClient.Me.MailFolders["validFolderId"]
	.Messages
	.Delta();

var firstPage = await mailDeltaRequest.GetAsync(
		rc => rc.Headers.Add("Prefer", "odata.maxpagesize=20"), null, cancellationToken);

var iterator = PageIterator<Message, Microsoft.Graph.Beta.Me.MailFolders.Item.Messages.Delta.DeltaResponse>.
	CreatePageIterator(GraphServiceClient, firstPage, (m) =>
		{
			return true;
		});

await iterator.IterateAsync(cancellationToken);
```

I can see via fiddler proxy that request is successful and first page is retrieved.

**Expected behavior**
No exception is thrown and messages are iterated through paging

**Client version**
5.5.0-preview nuget.

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser: N/A, WinForms application using standard HttpClient
 - Version: N/A

**Additional context**
I'm also interested on how to retrieve/supply deltaToken, as I see no option to properly specify it in DeltaRequest headers

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/441.
