### ISSUE TITLE
[Client bug]: 404 on PATCH OAuth2PermissionGrant

### ISSUE THREAD

**Issue by steventmayer** [microsoftgraph/msgraph-sdk-dotnet#1377]
**Describe the bug**
We have Applications that have multiple pages of OAuth2PermissionGrants. However, calling the Update OAuth2PermissionGrant endpoint using the SDK will throw a 404. I know the grant exists as I am able to see it in the List of grants, and am using the correct permission grant ID (as I paged through to get it).

**To Reproduce**
1. Create AAD Application with multiple pages of OAuth2PermissionGrants (ours was 5). This can also happen when the List endpoint returns empty pages but there is an NextUri exists. CosmosDB does this when querying across partitions.
2. Call List endpoint and find the appropriate grant you'd like to update (grab something on a later page)
3. Call Update endpoint, receive 404.

**Expected behavior**
It should update the grant and return 204. 

**Screenshots**

**Client version**
<PackageReference Include="Microsoft.Graph.Beta" Version="4.31.0-preview" />
<PackageReference Include="Microsoft.Graph.Core" Version="2.0.8" />

**Desktop (please complete the following information):**
Net 6.0 Function App

**Additional context**

**Comment by steventmayer** [comment]
Code looks like this:

    var result = await _graphClient.ServicePrincipals[clientId)].Oauth2PermissionGrants.Request().GetAsync(cancellationToken);
     OAuth2PermissionGrant grantForResource = result.CurrentPage.FirstOrDefault(g => g.ResourceId == resourceIdString && g.ConsentType == "AllPrincipals");
    while (grantForResource == null && result.NextPageRequest != null)
    {
        result = await result.NextPageRequest.GetAsync(cancellationToken);
        grantForResource = result.CurrentPage.FirstOrDefault(g => g.ResourceId == resourceIdString && g.ConsentType == "AllPrincipals");
    }

    var newScopeValue = "scope1 scope2";
    var grant = await _graphClient.Oauth2PermissionGrants[grantForResource.Id].Request().UpdateAsync(new OAuth2PermissionGrant { Scope = newScopeValue }, cancellationToken); // throws 404

Sadly, I will not have the ability to test this in Graph Explorer due to the high privilege nature of this. It is running using the Application.ReadWrite.All approle, not the delegated oauth permission.

**Comment by steventmayer** [comment]
If calling the GET OAuth2PermissionGrant endpoint directly, it also 404s in Graph. https://graph.microsoft.com/v1.0/oauth2PermissionGrants/{permissionGrantId}
However, calling the LIST endpoint for the v1.0/servicePrincipals/{id}/oauth2PermissionGrants, we'll find the grant on the Xth page - usually after some blank pages.

**Comment by steventmayer** [comment]
This is on the MSFT tenant so I can give reproducible examples if pinged internally.

**Comment by andrueastman** [comment]
Closing this one for now. 

This is being followed up with the relevant API team. Will re-open in the event anything SDK related is raised.

**Comment by SeanC2222** [comment]
@andrueastman Any linkable issues? Or is it internal? Thanks!

**Comment by andrueastman** [comment]
Hey @SeanC2222,

This one specifically is internal, any chance you are exhibiting the same scenario on your end?
