### ISSUE TITLE
LargeFileUploadTask for email attachments

### ISSUE THREAD

**Issue by jdew73** [microsoftgraph/msgraph-sdk-dotnet#1381]
Hello,

I recently received some resolution regarding a new issue uploading 4MB+ files (https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1367#issuecomment-1150226755).  

However, when trying to apply the same fix to large files uploading as email attachments, the upload consistently fails with "A task was canceled" message.  This differs from the error that had been raised when just uploading files.  

Our specs:
VB.NET
Microsoft Graph 4.24.0
.NET Framework 4.7.2 

Please advise.  It is inoperable at the moment.  Thank you.

**Comment by andrueastman** [comment]
Hey @jdew73,

Thanks for raising this. 

As you are passing in a customized version of the graphClient, do you notice any change if you pass in version of the graphClient that does not set the Authorization header for the scenario to upload the file?

**Comment by zengin** [comment]
@jdew73 thanks for confirming.
