### ISSUE TITLE
[Client bug]: Subscriptions response property NextPageRequest which unexpected value.

### ISSUE THREAD

**Issue by miguelhasse** [microsoftgraph/msgraph-sdk-dotnet#1386]
After calling a Subscriptions get request, NextPageRequest is supposed to be null when results are empty.
This behavior changed in one of the more recent releases, and now it is never null.

```
            var response = await graphServiceClient.Subscriptions.Request().GetAsync();

            while (response.NextPageRequest != null)
            {
                response = await response.NextPageRequest.GetAsync();
            }
```

NOTE: This may be an issue on the Graph API itself.

**Comment by andrueastman** [comment]
Hey @miguelhasse,

Thanks for raising this. 

Any chance you could provide more information on the version of the SDK you were using and upgraded to? 
In the event that it's a suspected issue on the API, any possible timelines on when this behavior started?

**Comment by miguelhasse** [comment]
Hi @andrueastman the version upgrade was from 4.29 to 4.31, and this behavior started started sometime last week.

**Comment by andrueastman** [comment]
Hey @miguelhasse,

Just to confirm, does this behavior replicate when you downgrade to 4.29 as well? Or is it just when using the latest package version as well?
