### ISSUE TITLE
[Client bug]: .CreateUploadSession() crashing application with exit code 0

### ISSUE THREAD

**Issue by GarMGarM** [microsoftgraph/msgraph-sdk-dotnet#1391]
**Describe the bug**
Calls to .CreateUploadSession() are crashing application with output message "has exited with code 0 (0x0)."

**To Reproduce**
 .NET Framework 4.7.2
 Microsoft.Graph v4.0.30319

Running the following code:

            string clientId = ConfigurationManager.AppSettings["sa:ServiceAppId"];
            string tenantId = ConfigurationManager.AppSettings["sa:TenantId"];
            string secretId = ConfigurationManager.AppSettings["sa:ClientSecret"];

            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(clientId)
                .WithTenantId(tenantId)
                .WithClientSecret(secretId)
                .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);
            GraphServiceClient graphClient = new GraphServiceClient(authProvider);

            var uploadProperties = new DriveItemUploadableProperties
            {
                ODataType = null,
                AdditionalData = new Dictionary<string, object>
                    {
                        { "@microsoft.graph.conflictBehavior", "replace" }
                    }
            };

            Console.WriteLine("Before session request");
            Console.ReadKey();

            var session = await graphClient.Drive.Items["{folderId}"].ItemWithPath("{fileName}").CreateUploadSession().Request().PostAsync();

            Console.WriteLine("Session: " + session.UploadUrl);
	    Console.ReadKey();

The Program exits unexpectedly at .CreateUploadSession() with following message:
The program '[20920] GraphSDKUploadSessionTest.exe' has exited with code 0 (0x0).
The execution does not reach the line - Console.WriteLine("Session: " + session.UploadUrl);

**Expected behavior**
Return either an upload session or an error message.

**Client version**
 Microsoft.Graph v4.0.30319

**Comment by andrueastman** [comment]
Hey @GarMGarM,

Thanks for raising this.

Any chance you could share what happens if you wrap the graph call in a try catch block?

```cs
try
{
    var session = await graphClient.Drive.Items["{folderId}"].ItemWithPath("{fileName}").CreateUploadSession().Request().PostAsync();
}
catch(Exception e)
{
    Console.WriteLine(e.Message);
}
```

**Comment by andrueastman** [comment]
Any chance you are able to share the results if you change your code to look something like this?

```cs
var sessionResponse = await graphClient.Drive.Items["{folderId}"].ItemWithPath("{fileName}").CreateUploadSession().Request().PostResponseAsync();

Console.WriteLine(sessionResponse.StatusCode);
var responseString = await sessionResponse.Content.ReadAsStringAsync();
Console.WriteLine(responseString);
```

**Comment by GarMGarM** [comment]
The result appears to be the same: The program '[15148] GraphSDKUploadSessionTest.exe' has exited with code 0 (0x0).

**Comment by GarMGarM** [comment]
@andrueastman
Yes - Visual Studio Professional 2019 in Debug mode.

**Comment by andrueastman** [comment]
Any chance you could share the output of the Debug window? From my end, you should at least be able to see or confirm if an exception is thrown like below.

![image](https://user-images.githubusercontent.com/6464005/176383171-418f6622-ba72-4b5d-8341-dbc41a6f4d50.png)

Alternatively, do you have any luck with setting a breakpoint in the catch block?

**Comment by GarMGarM** [comment]
This is the full output. I have replaced the initial parts of the repos path with ". . ." for brevity:
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\GraphSDKUploadSessionTest.exe'. Symbols loaded.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Identity.Client.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.Auth.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Text.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Net.Http.WinHttpHandler.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Bcl.AsyncInterfaces.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Text.Encodings.Web.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .\Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[11452] GraphSDKUploadSessionTest.exe' has exited with code 0 (0x0).

**Comment by GarMGarM** [comment]
For the breakpoints - I have tried adding break points before the end of the try block and inside the catch block, but the program crashes before it reaches either.

**Comment by andrueastman** [comment]
Thanks for this. It could possibly be that another dependency is causing the issue that is optimized out. I would suggest disabling `Just My Code` in visual studio to get more info on what could be going wrong in the stack trace.
![image](https://user-images.githubusercontent.com/6464005/176393104-21f04ea4-5632-49d2-acd1-63d07bb2a4fe.png)

You may also want to check if verify this option is disabled in Visual Studio as well.
![image](https://user-images.githubusercontent.com/6464005/176392268-7bbdf83a-17fc-4cb4-b9fe-af98e448dc2f.png)

**Comment by GarMGarM** [comment]
Unfortunately there is no difference after these changes.

**Comment by andrueastman** [comment]
Any chance you can share the updated trace from the Debug log as before?

**Comment by GarMGarM** [comment]
Without 'just my code' enabled:
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: DefaultDomain): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\GraphSDKUploadSessionTest.exe'. Symbols loaded.
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.Core.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Identity.Client.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Graph.Auth.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Text.Json.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Net.Http.WinHttpHandler.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Memory.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\Microsoft.Bcl.AsyncInterfaces.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Text.Encodings.Web.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Threading.Tasks.Extensions.dll'. 
'GraphSDKUploadSessionTest.exe' (CLR v4.0.30319: GraphSDKUploadSessionTest.exe): Loaded '. . .Repos\GraphSDKUploadSessionTest\GraphSDKUploadSessionTest\bin\Debug\System.Buffers.dll'. 
The program '[13884] GraphSDKUploadSessionTest.exe' has exited with code 0 (0x0).

**Comment by GarMGarM** [comment]
Hi @andrueastman,

I have pushed the app to a repo and added your account.

**Comment by andrueastman** [comment]
Hey @GarMGarM,

Thanks for this. Any chance of you letting me know if the suggested changes allow you to get more information on what could be happening at your end?

**Comment by GarMGarM** [comment]
There is now an error returned:
Exception thrown: 'Microsoft.Identity.Client.MsalServiceException' in Microsoft.Identity.Client.dll

**Comment by andrueastman** [comment]
Any chance you are now able to view the exception info using a breakpoint in the exception block? 
From my end it should be possible after the suggested changes are applied.

**Comment by GarMGarM** [comment]
Ok, I'm getting an error message now. Thanks.
