### ISSUE TITLE
How to serialize a ChatMessage to json. 

### ISSUE THREAD

**Issue by ymoona** [microsoftgraph/msgraph-sdk-dotnet#1395]
**Describe the bug**
A ChatMessage does not serialize well. 

**To Reproduce**
I am working with the ChatMessage entity in my project. In order to store it, I serialize it to json. This works fine 3.x (with newtonsoft) but started to become problematic with newer versions (4.x and 5). When I serialize with JsonSerializer.Serialize(cm) and graph client 4.x all the null values are left out. Is there a way to add those?

And when I serialize with 5.x (beta) the serialized format has changed again. Then the null values are included, but the property names have change to upper case and the "AdditionalData" is serialized as plain text instead of key/values it holds, 

`
"From": {
        "AdditionalData": {},
        "Application": null,
        "BackingStore": {
            "InitializationCompleted": true,
            "ReturnOnlyChangedValues": false
        },
        "Device": null,
        "User": {
            "AdditionalData": {
                "userIdentityType": "aadUser"
            },
            "BackingStore": {
                "InitializationCompleted": true,
                "ReturnOnlyChangedValues": false
            },
            "DisplayName": "theUser",
            "Id": "TheUSersGuid"
        }`

**Expected behavior**
When I serialize a ChatMessage with JsonSerializer.Serialize(cm) I get a fully serialized chat message in json format.
Including:

- "propery" = null if the value is null
- No additional data properties on nested properties
- Type information on root and sub properties (@odata.type)
- Enum values are serialized to string
- Properties are starting with lowercase

**Additional context**
What would be the stable way of serializing ChatMessages? Preferably in a way so it is formatted like comes directly from graph api using a GET request.

**Comment by andrueastman** [comment]
Hey @ymoona,

Thanks for raising this.

In version 4 of the SDK, one of t[he breaking changes](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#systemtextjson-replaces-newtonsoftjson) involved dropping support for Newtonsoft to migrate over to System.Text.Json and therefore using the NewtonSoft serializer would not necessarily work.

The GraphClient however exposes the configured serializer for graph payloads which you can use in both V3 and V4 which can be used as follows.

```cs
var chatMessageObject = graphClient.HttpProvider.Serializer.DeserializeObject<ChatMessage>(payload); // deserialize the object

var jsonString = graphClient.HttpProvider.Serializer.SerializeObject(chatMessage);            // serailize the object
```

**Comment by ymoona** [comment]
Yes that works, but the results on 4.x are quite similar. Only the null values are omitted. 
But on version 5.x beta, there seem to be no preconfigured serializers?

**Comment by ymoona** [comment]
I'll move the question to the beta issue: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1290
