### ISSUE TITLE
Teams Meeting Update Email Does Not Include Join URL

### ISSUE THREAD

**Issue by JLuciano75** [microsoftgraph/msgraph-sdk-dotnet#1402]
**Describe the bug**
When using the Microsoft.Graph.GraphServiceClient.UpdateAsync method to update an existing Teams meeting, if the email body is included in the Event object sent along in the UpdateAsync method the Join URL **is not** appended to the email body when sent to the attendee. If the email body property is removed from the Event object sent along with the UpdateAsync method call then the update invite email includes the email body from the **original** invite and the Join URL **is appended**.

**To Reproduce**
Using Microsoft.Graph, create a Teams meeting that includes an email body that is included in the invite email sent to the attendee. The Join URL will be appended to email body in the original invite email. Then send an update to the same Teams meeting that includes a different email body from the original invite and you will find that the Join URL is not appended to the email body of the update email to the attendee.

**Expected behavior**
Join URL should be appended to any update invite email sent to an attendee regardless of whether an email body is sent with the update request or not.

**Comment by ddyett** [comment]
Closing this as a service issue outside of sdk.
