### ISSUE TITLE
Error while trying to get members of the group of type Group

### ISSUE THREAD

**Issue by ilantom** [microsoftgraph/msgraph-sdk-dotnet#1405]
Error on running:

```

var _graphServiceClient = new GraphServiceClient(CreateAuthProviderFromSecret(creds));

var groupsInGroup = await _graphServiceClient.Groups[objectId.ToString()].Members.Group.GetAsync();


public static IAuthenticationProvider CreateAuthProviderFromSecret(GraphCredentials creds)
{
    var confidentialClientApplication = ConfidentialClientApplicationBuilder
    .Create(creds.ClientId)
    .WithTenantId(creds.TenantId)
    .WithClientSecret(creds.ClientSecret)
    .Build();

    return new ClientCredentialProvider(confidentialClientApplication);
}

```

![image](https://user-images.githubusercontent.com/6519992/177857713-5ee1fcc7-f9be-4271-9520-21ea5f41514a.png)

**Comment by andrueastman** [comment]
Hey @ilantom,

Are you able to confirm the version of the SDK you are using?

**Comment by ilantom** [comment]
5.0.409

**Comment by andrueastman** [comment]
Hey @ilantom,

I believe this could be the version of the dotnet SDK. Any chance you could clarify on the version of the `Microsoft.Graph` nuget package?

**Comment by ilantom** [comment]
3.6.0

**Comment by andrueastman** [comment]
Thanks @ilantom,

The functionality to get members of the group of type Group is currently only available in our preview packages of the v5 of the SDK. You would need to upgrade the SDK version to access this functionality. 

More information is available in our upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#support-for-odata-casts-in-request-builders).

**Comment by ilantom** [comment]
Thank you! I tried with the latest version as well (not preview version).  Could you please provide the exact version of nuget package? Also, could you please let me know if _graphServiceClient in my code looks correct?

**Comment by ilantom** [comment]
[andrueastman](https://github.com/andrueastman) do you work at Microsoft? Could we chat via Teams if possible?

**Comment by andrueastman** [comment]
You want to use the latest preview package [here ](https://www.nuget.org/packages/Microsoft.Graph/5.0.0-preview.8)

> [andrueastman](https://github.com/andrueastman) do you work at Microsoft? Could we chat via Teams if possible?

Sure thing, I'll reach out to you directly and then close this issue for now.
