### ISSUE TITLE
Microsoft Graph Client support .NET 6?

### ISSUE THREAD

**Issue by ward-horsfall** [microsoftgraph/msgraph-sdk-dotnet#1412]
Hi,

Does the Microsoft Graph client support .NET 6.

E.g if I write a C# console or .WPF app will it work properly or is it un-supported.

Thanks,

Ward

**Comment by andrueastman** [comment]
Hey @ward-horsfall,

The client library does target netstandard 2.0 which is supported by .NET 6 and you should be able to build the app.

Feel free to create an issue if you run into any problems in the event that you do.
