### ISSUE TITLE
For the Azure App Registration Quick Start - Please upgrade the sample to support .NET 6.

### ISSUE THREAD

**Issue by ward-horsfall** [microsoftgraph/msgraph-sdk-dotnet#1415]
*Hi,

From Microsoft Azure App Registration Portal:

At the moment when I choose the following app type:

App registrations - > (App Name) - Quickstart

Then: Mobile and desktop application - Windows desktop - Quickstart: Acquire a token and call Microsoft Graph API from a Windows desktop app

The sample works but it is built on a old version of .Net.

Can I suggest this is upgraded to .NET 6 (WPF).

Thanks,

Ward.

**Comment by andrueastman** [comment]
Closing this for now to be followed up on sample repository at  https://github.com/Azure-Samples/active-directory-dotnet-desktop-msgraph-v2/issues/102
