### ISSUE TITLE
[Client bug]: Unable to cast object of type NullableData[ExDateTime]' to type 'DateTimeData' when calling Me.MailFolders[id].Messages.Delta

### ISSUE THREAD

**Issue by g2petter** [microsoftgraph/msgraph-sdk-dotnet#1417]
**Describe the bug**

Two days ago we started getting the following error when using the Microsoft Graph SDK and calling `GraphServiceClient.Me.MailFolders[id].Messages.Delta()` for one of our customers:

>Unable to cast object of type 'Microsoft.Exchange.Data.Storage.NullableData`2[Microsoft.Exchange.Data.Storage.DateTimeData,Microsoft.Exchange.ExchangeSystem.ExDateTime]' to type 'Microsoft.Exchange.Data.Storage.DateTimeData'.

Initially we thought this was something wrong with this particular client's email folder, but yesterday and today the error started showing up with other customers as well.

Our code calling this method has been unchanged for more than a year, and we're unable to reproduce the error with any of our accounts or in the Graph Explorer. 

We've updated to the latest version of the `Microsoft.Graph` and `Microsoft.Graph.Core` packages (4.34.0 and 2.0.9 respectively) and the problem remains there.

**To Reproduce**
Unable to reproduce since this only seems to happen with specific accounts for certain email folders.

**Expected behavior**
Not getting an unhandled exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/5946832/179179208-05a8485b-8353-4563-abd2-031061a94c6d.png)

**Client version**
Microsoft.Graph: `3.35.0` and `4.34.0`
Microsoft.Graph.Core: `1.25.1` and `2.0.9`

**Desktop (please complete the following information):**
Windows 10, Windows 11 and Windows Server 2019

**Comment by g2petter** [comment]
> Thanks for raising this @g2petter
> 
> Any chance you can share the `client-request-id` from the exception trace when this error occurs?

Here's a few examples from different customers: 

`d6fb3e69-549a-425b-b57a-afc65cc0852c`  
`12430812-38aa-4d42-9f29-f620a4dacfc5`  
`476344a5-e3b2-4618-8df4-14797f489189`  
`3818823a-c312-43ab-a0f8-e48b8a7476d9`

**Comment by PaulDMendoza** [comment]
Adding more details. This bug started on Wednesday July 13th. 

![image](https://user-images.githubusercontent.com/1039795/179571037-ba2c5837-1ae0-4714-b15f-e3e13e8dff30.png)


Code: ErrorInternalServerError\nMessage: An internal server error occurred. The operation failed., Unable to cast object of type 'Microsoft.Exchange.Data.Storage.NullableData`2[Microsoft.Exchange.Data.Storage.DateTimeData,Microsoft.Exchange.ExchangeSystem.ExDateTime]' to type 'Microsoft.Exchange.Data.Storage.DateTimeData'.\nClientRequestId: f98961d6-adb5-4ef0-a928-1f10f975bdfc\n

**Comment by rodrimc** [comment]
We have identified the problem and are working to rollout a fix for it. I'll update this thread once the fix is deployed.

**Comment by rodrimc** [comment]
Hotifx has been deployed and we noticed a significant decrease in the # of occurrences of that error. Could you please let us know if you're still experiencing that error?

**Comment by jaredsohn** [comment]
We're still getting this error as of a half hour ago.

**Comment by rodrimc** [comment]
Has the # of erros dropped? The fix is still rolling out, but I already checked a huge drop in occurrences.

**Comment by pavelsmejkal** [comment]
@rodrimc our metrics are significantly better ~ 80% and going down org by org.

**Comment by jaredsohn** [comment]
We're still encountering errors. Is just one user that we cannot sync. Couldn't last week and still can't now.

**Comment by jaredsohn** [comment]
Seems to be working now. :)

**Comment by rodrimc** [comment]
Thanks for letting me know. Issue seems to be mitigated now.

**Comment by pavelsmejkal** [comment]
We have as well still two customer that we can't sync. Has the rollout finished? Or can you share the ETA ?

**Comment by rodrimc** [comment]
@pavelsmejkal the rollout is 99% complete. From our logs I'm seeing 98% reduction in the # of occurrences of that error (yesterday's metrics). I cannot give you with confidence an ETA for the rollout to reach 100% but it should be complete within the next few days.

**Comment by g2petter** [comment]
Apologies for not reporting back earlier, since I'm the one who opened the issue, but I've been on holiday.

The issue has 100% disappeared on our end, with none of our clients' mailboxes getting the error in August.

**Comment by andrueastman** [comment]
Thanks for getting back on this @g2petter.
We'll close this issue for now as it is now resolved.
