### ISSUE TITLE
Update to 4.35 throw exception "format of the executable (.exe) or library (.dll) is invalid"

### ISSUE THREAD

**Issue by premiaware** [microsoftgraph/msgraph-sdk-dotnet#1425]
I have UWP Windows Store App (x86 and x64), using  Microsoft.Graph 4.34 all working well in debug and release mode
now i have upgraded to 4.35 and in debug mode work well, in release (native compile x64 or x86) when install the App from Microsoft store and start it, immediately the exception is throw:

"format of the executable (.exe) or library (.dll) is invalid"

i think that you have inserted wrong x86 and x64 dll inside the nutget component.

If i downgrade to Microsoft.Graph 4.34 all working well.

you can check ?

UWP Windows Store App on windows 10 o 11.

**Comment by andrueastman** [comment]
Hey @premiaware,

Any chance you can still replicate this with the latest version 4.36.0?
