### ISSUE TITLE
[Client bug]: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported

### ISSUE THREAD

**Issue by pindla** [microsoftgraph/msgraph-sdk-dotnet#1429]
When an existing MVC 4.0 project with .net4.6.1 was upgraded to MVC 5 and .net4.8, the below call gives the error
await graphClient.Me.Request().GetAsync();

**Comment by andrueastman** [comment]
Thanks for raising this @pindla 

To help us understand the issue better, any chance you could share the version of the Microsoft Graph library you are using? Also could you share code samples on how the `GraphClient` is created/instantiated?
