### ISSUE TITLE
LargeFileUploadTask in graph SDK requires maxSliceSize to be a multiple of 320 KiB

### ISSUE THREAD

**Issue by nilakhan** [microsoftgraph/msgraph-sdk-dotnet#1436]
LargeFileUploadTask in graph SDK requires maxSliceSize to be a multiple of 320 KiB. 

Otherwise, we are getting the following error: 
    _System.ArgumentException: Max slice size must be a multiple of 320 KiB
    Parameter name: maxSliceSize_
    
For data type, PrintDocument (for Universal Print), using multiples of 200 KiB is more optimal. 
Hence, we would request graph SDK team to lift this requirement for PrintDocument data type in Graph SDK.

**Comment by MIchaelMainer** [comment]
The OneDrive page requirement, which was the initial requirement for large file upload, is being applied. https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#upload-bytes-to-the-upload-session. We may want to consider creating a OneDriveLargeFileUploadTask with this slice size requirement and then remove this requirement from LargeFileUploadTask. Existing integrations will continue to work and new integrations with OneDrive with the wrong page size will result in an error response, which is what should've probably happened in the first place. We shouldn't really be in the business of restricting slice anyways and let the service API be responsible for this. Then setting slice size can be enabled for the arbitrary API in LargeFileUploadTask.

**Comment by maisarissi** [comment]
I was discussing with @baywet and @ramsessanchez whether this affects Java SDK too and one of the things mentioned by Vincent, that I agree with, is that customers don't wanna know about API slicing constraints and which size slice they are required to use when calling LargeFileUploadTask or even know there is a OneDriveLargeFileUploadTask.
Users should be able to just call LargeFileUploadTask and the SDK should handle all the logic and slicing behind that.
Can we have a default slice size and have a way to easily change that configuration so users like @nilakhan could change it for 200 KiB?

**Comment by andrueastman** [comment]
> Can we have a default slice size and have a way to easily change that configuration so users like @nilakhan could change it for 200 KiB?

We already have a default slice size that makes the slice parameter optional. We just need remove the Exception we throw when the parameter isn't a multiple of 320KB. I'll author a PR to close this.

**Comment by baywet** [comment]
Thanks everyone for the discussion. @ramsessanchez @maisarissi this also needs to be changed for Java https://github.com/microsoftgraph/msgraph-sdk-java-core/blob/f14fc08176c4f08ff073dbcc24bf14123bd0f1e0/src/main/java/com/microsoft/graph/tasks/LargeFileUploadTask.java#L141

Can you create an issue and schedule that please?
