### ISSUE TITLE
Upgrade guide for v5?

### ISSUE THREAD

**Issue by VictorioBerra** [microsoftgraph/msgraph-sdk-dotnet#1438]
I see the docs have an upgrade guide for v4, is there one for v5? For example, this code now throws a compilation error on `5.10.0-preview`:

```csharp
  var usersPageRequest = this.graphServiceClient.Users
          .Request() // <------------ ERROR
          .Select("Id")
          .Filter("UserType eq 'Member'")
          .Top(999);
```

> 'UsersRequestBuilder' does not contain a definition for 'Request' and no accessible extension method 'Request' accepting a first argument of type 'UsersRequestBuilder' could be found (are you missing a using directive or an assembly reference?)	

Can someone tell me what the new API syntax is to get all users for v5+?

**Comment by Dean-NC** [comment]
@VictorioBerra here it is:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md

**Comment by VictorioBerra** [comment]
Not sure how I missed this, thanks.
