### ISSUE TITLE
[Client bug]: Could not load file or assembly Tavis.UriTemplates: A strongly-named assembly is required

### ISSUE THREAD

**Issue by cgontario** [microsoftgraph/msgraph-sdk-dotnet#1439]
**Describe the bug**
I have a .NET Framework 4.8 project and am trying to use the v5 SDK to search for users:

```
await client.Users
                .GetAsync(requestConfiguration => {
                    requestConfiguration.QueryParameters.Select = new string[] { "id,givenName,surname,displayName,mail" };
                    requestConfiguration.QueryParameters.Search = $"\"givenName:{searchTerms.FirstName}\" OR \"surname:{searchTerms.LastName}\" OR \"mail:{searchTerms.EmailAddress}\" OR \"displayName:{searchTerms.FirstName}\" OR \"surname:{searchTerms.LastName}\"";
                    requestConfiguration.QueryParameters.Count = true;
                    requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
                });
```

.GetAsync() throws an exception stating that Tavis.UriTemplates cannot be loaded because it is not strongly-named:

```Could not load file or assembly 'Tavis.UriTemplates, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.```

**Client version**
`Microsoft.Graph.Beta 5.10.0-preview` and `Microsoft.Kiota.Abstractions 1.0.0-preview.9` which references `Tavis.UriTemplates 1.1.1`.

**Desktop (please complete the following information):**
 - Windows 10 Enterprise 64-bit 21H2
 - Visual Studio Enterprise 2022 17.2.6

**Additional context**
The project is a service host for WCF (middle tier of a 3-tier app). There's a business logic assembly of ours in the solution that references to `Tavis.UriTemplates` and the ServiceHost project references the BusinessLogic project.

**Comment by andrueastman** [comment]
Thanks for raising this @cgontario 

We're already tracking this via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/444 and are looking to republish the `Tavis.UriTemplates` with a strong name to resolve this. We'll close this one for now and track this from there.
