### ISSUE TITLE
5.0 preview fails Communications.CallRecords.GetDirectRoutingCallsWithFromDateTimeWithToDateTime filter serialization

### ISSUE THREAD

**Issue by sopelt** [microsoftgraph/msgraph-sdk-dotnet#1443]
**Describe the bug**
Using [Microsoft.Graph/5.0.0-preview.10](https://www.nuget.org/packages/Microsoft.Graph/5.0.0-preview.10) to call [getDirectRoutingCalls](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&tabs=http) fails with `Bad Request - Error in query syntax.`.

It seems as if the [time range filter arguments](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&tabs=http#function-parameters) are not being serialized in a format acceptable to the service.

**To Reproduce**
Using a minimalistic console app (net6, Microsoft.Graph 5.0.0-preview.10 and Azure.Identity 1.6.1) with the following source can be used to repro:

```
var credential = new DefaultAzureCredential();
var client = new GraphServiceClient(credential);
var from = new DateTimeOffset(2022, 8, 1, 0, 0, 0, TimeSpan.Zero);
var to = new DateTimeOffset(2022, 8, 2, 0, 0, 0, TimeSpan.Zero);

var result = await client.Communications.CallRecords.GetDirectRoutingCallsWithFromDateTimeWithToDateTime(from, to).GetAsync();
```

**Expected behavior**
Call logs/HTTP 2xx should be returned.

**Additional context**
Looking at the innermost exception and the close by method `Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync` looks to have `Microsoft.Kiota.Abstractions.RequestInformation.URI.AbsoluteUri` as `https://graph.microsoft.com/v1.0/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime='01%2F08%2F2022%2000%3A00%3A00%20%2B00%3A00',toDateTime='02%2F08%2F2022%2000%3A00%3A00%20%2B00%3A00')` which does not seem quite right. The DateTimeOffsets seem to be just ToString + url encoded instead of something like `2022-08-01`.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoft/OpenAPI.NET.OData/issues/262

**Comment by sopelt** [comment]
Thank you for the swift action. Any idea in which release and when this might be shipped?
