### ISSUE TITLE
Creating a one-on-one chat using user principal name fails with error Failed to find users with user principal name

### ISSUE THREAD

**Issue by ReniKIcon17** [microsoftgraph/msgraph-sdk-dotnet#1444]
### Expected behavior
Create a one-on-one chat when giving userprincipalname as mentioned in documentation  [Microsoft Graph documentation for chat creation with userprincipalname](https://docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-1.0&tabs=csharp#example-3-create-a-one-on-one-chat-using-user-principal-name) you used to determine the expected behavior.

### Actual behavior
Errors out as Service exception.
Details:
{"Code: NotFound\r\nMessage: Failed to find users with user principal name ''\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2022-08-10T15:05:48\r\n\trequest-id: b0413fef-b33a-4e9c-b9fa-25f7055b5784\r\n\tclient-request-id: b0413fef-b33a-4e9c-b9fa-25f7055b5784\r\nClientRequestId: b0413fef-b33a-4e9c-b9fa-25f7055b5784\r\n"}

### Steps to reproduce the behavior
Try to create a chat with a user's principal name (instead of their uuid) as mentioned in the documentation. It will error out. 

Note: The calls with uuid work, and I am currently using the graph sdk to obtain the users uuid with the userprincipalname and then calling the graph sdk to create a chat with the uuid. I would like to directly use the userprincipalname instead as you have mentioned in the help docs.

**Comment by andrueastman** [comment]
Hey @ReniKIcon17,

Any chance you can still replicate this? If so, any chance you can share the update error details as you did before?
