### ISSUE TITLE
Syntax looks a bit odd in C#

### ISSUE THREAD

**Issue by JamesLear92** [microsoftgraph/msgraph-sdk-dotnet#1446]
While using this library I've come across some really weird syntax. For instance, if I were to retrieve my calendar permissions I'd do the following:

    `await graphServiceClient.Users["person@example.com"].Calendar.Request().GetAsync();`
    
In C#, square brackets are used as indexer operators, so if I were to see the code above, I'd assume that

    `graphServiceClient.Users`

is a collection like a dictionary/hashtable where "person@example.com" is a key. It also implies that the value returned from the dictionary has the properties "Calendar" which in turn which in turn has the method "Request" which returns an object which has "GetAsync".

In reality, 

    `graphServiceClient.Users`
    
is not a collection at all, is not being indexed, in fact I have never come across this before. What is being accessed? Why not have something like:

    `await graphServiceClient.Users.GetCalendarAsync("person@example.com");`
    
You can see exactly what it's doing at a glance

**Comment by darrelmiller** [comment]
The Microsoft Graph client SDKs use a pattern of "chained request builders" to help users construct HTTP requests, including the URL, that will allow them to access the data they are interested it.  The `graphServiceClient.Users` does represent a collection of users on the Microsoft Graph API.  Accessing the calendar of one of those users would be done by indexing into the collection and accessing the calendar property. e.g. `graphServiceClient.Users["person@example.com"].Calendar.Request.Get()

This "resource-oriented" pattern allows a developer to identify the resource they want to request and then describe the type of request they want to make.

The pattern you are suggesting takes a more procedural approach and creates effectively a namespace of user functions and a GetCalendar function that takes a userId as a parameter.

`await graphServiceClient.Users.GetCalendarAsync("person@example.com");`

This approach can work well for smaller APIs, but for large APIs that are deeply nested like Microsoft Graph, the number of functions can quickly become overwhelming and undiscoverable.  At last count there were 22914 operations in Microsoft Graph.
