### ISSUE TITLE
The assignments submissions are null in c# call

### ISSUE THREAD

**Issue by oscarfr96** [microsoftgraph/msgraph-sdk-dotnet#1447]
While using the library I'm not able to get the submissions of the assigments I'm calling. I dont have the assigments id´s at the moment where im doing the call:

`Task.Run(async () => await Service.Education.Classes[sincro.IdSync].Assignments.Request().Top(ConstTeams.MaxResultados).GetAsync())`

Looking the documentation, all I can see is that you need the submissions id´s:

```
var resources = await graphClient.Education.Classes["{educationClass-id}"].Assignments["{educationAssignment-id}"].Submissions["{educationSubmission-id}"].Resources
	.Request()
	.GetAsync();
```

I've tried to do the call with "*" parameter, but it does not work. I don't know if this simply cannot be done, or if exists a parameter I'm missing.

Thank you for your time!

**Comment by andrueastman** [comment]
Thanks for raising this @oscarfr96 

Any chance you have tried to list the submissions as outlined in the docs [here](https://docs.microsoft.com/en-us/graph/api/educationassignment-list-submissions?view=graph-rest-1.0&tabs=csharp#example-1-get-submissions)?


```cs
var submissions = await graphClient.Education.Classes["{educationClass-id}"].Assignments["{educationAssignment-id}"].Submissions
	.Request()
	.GetAsync();
```

This should ideally return a collection of submissions which you can extract the `Id` properties to use in the snippets you shared above.

**Comment by oscarfr96** [comment]
Hi!

Yeas @andrueastman, I was able to get the submissions doing that call. But, I have to do two calls:

1. The first one in order to get the full list with all the Assigments, so I can find their educationAssignment-id
`Task.Run(async () => await Service.Education.Classes[sincro.IdSync].Assignments.Request().GetAsync())`

2.  The full call as you suggested, with the assignments ids, that returns all the submissions and the $expand option, this is the one that brings the notes.
`Task.Run(async () => await Service.Education.Classes[sincro.IdSync].Assignments[guidAssigments].Submissions.Request().Expand("outcomes").GetAsync()`

I have to do this because at the begining I only have the synchronization Id. Maybe it could be a cool upgrate to return all the submissions and assigments in only one call.
