### ISSUE TITLE
Meeting requests are returned as `Message` instead of as `EventMeetingRequestObject`

### ISSUE THREAD

**Issue by KnapSac** [microsoftgraph/msgraph-sdk-dotnet#1449]
**Describe the bug**
I'm trying to get meeting requests from a mail folder, but the returned object is still a `Message` instead of an `EventMessageRequestObject`, despite the fact that `ODataType = #microsoft.graph.eventMessageRequest`. When testing using GraphExplorer, all the correct properties seem to be returned, so it looks to me like this is an issue with the SDK matching the response to the correct type.

Using `.Expand("microsoft.graph.eventMessage/event")` it's possible to get the associated event, but this is also not very convenient, as this doesn't play well with the expand expression overload, which only allows direct properties of `Message`, and using `.Expand` multiple times results in an error, instead of combining the expand expressions. Of course, I could create the expand query string myself without using the expand expression, but I'd rather not, as I find the expand expression syntax much more convenient.

**To Reproduce**
```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

IMailFolderMessagesCollectionPage messagePage = graphClient.Users["user-id"]
                                                           .MailFolders["folder-id"]
                                                           .Messages
                                                           .Request()
                                                           .GetAsync();
```

**Expected behavior**
The message page contains the meeting request as an `EventMeetingRequestObject`, instead of as a `Message`.

**Additional context**
- .NET version: `.NET Framework 4.8`
- SDK version: `4.36`

**Comment by KnapSac** [comment]
After some debugging I have found the problem, which stems from this line in the core library:
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/cbf7a958c96003267f81a947cf66749ed74da905/src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs#L55

Since the `ODataType` returned by the API is `microsoft.graph.eventMessageRequest`, the above line results in the type converter looking for the `Microsoft.Graph.EventMessageRequest` type, which does exists, but which is not the correct type (this type is for the request for `EventMessage`s, the correct type for this Graph resource is `Microsoft.Graph.EventMessageRequestObject`). In the end this leads to the type converter being unable to locate a constructor for the type (as it looks for a parameterless public constructor, which `Microsoft.Graph.EventMessageRequest` does not have) and then falling back to the base type. This also happens if a constructor had been found, as it is checked whether the found type is assignable to the type of the generic parameter of `DerivedTypeConverter`.

I see 2 solutions for this problem:
1. Swap the naming of the 2 `EventMessageRequest` objects, such that the type implementing `IEventMessageRequest` becomes `EventMessageRequestObject` (or some other more appropriate name) and the type which is generated for the Graph resource type becomes `EventMessageRequest`.
2. Check whether the `ODataType` ends with `Request`, and if that is the case, append `Object` to the type name.

Doing a quick search in the generated models folder, it seems like there are more Graph resources which have this issue, I suspect all resources ending with `Request` will face this problem, as they all have `Object` appended to their type. The fix for this problem should thus probably be for all these resource types.

I would be more than happy to contribute the fix for this, just let me know which solution you prefer (or any other solution you find more appropriate of course). Though the second solution I proposed would have to be implemented in the core library of course.

**Comment by andrueastman** [comment]
Thanks for this @KnapSac,

We're always happy to accept contributions to the project to fix this.

I believe due to the nature of option 1 causing a breaking change and causing a bunch of other models to break, it would be better to go for option 2 so that the DerivedTypeConveter is consistent with the expectation/assumption from the code generator.

**Comment by KnapSac** [comment]
Ok, I'll probably be able to open a PR sometime today.
