### ISSUE TITLE
403 (Forbidden) error when accessing management.azure.com API endpoint

### ISSUE THREAD

**Issue by wpiotrw** [microsoftgraph/msgraph-sdk-dotnet#1454]
**Describe the bug**
When hitting the Azure API endpoint from C#: https://management.azure.com 
We get 403 error in the new SDK. On previous SDK ver: 3.27.0 there are no issues at all.

**Example API CALL:** 
URI: https://management.azure.com /providers/Microsoft.ADHybridHealthService/services/AadSyncService-xxx.onmicrosoft.com/alerts?state=Active&api-version=2014-01-01

**C# code:**

    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get,
                $"{service.BaseUrl}/{url}");
            await service.GraphManagementClient.AuthenticationProvider.AuthenticateRequestAsync(request);
            
            HttpResponseMessage response = await service.GraphManagementClient.HttpProvider.SendAsync(request);
            return await response.Content.ReadAsStringAsync();

**To Reproduce**
1. Run the API in new SDK version
2. Error 403 is shown

**Expected behavior**
No 403 error

Wireshark shows that previous SDK is using proxy (so it is ok as on our proxy allows that api) and new SDK is trying to bypass it (no proxy information in the wireshark logs that is why Foribdden error is thrown). 

* we found also that DESTINATION IP and PORT for management.azure.com API also differs.

Something new to be added to the code? What exactly has been changed in new SDK ver comparing to previous one for management.azure.com API endpoint?

So how to force the XXX proxy now in the api calls?

**Comment by andrueastman** [comment]
Thanks for raising this @wpiotrw.

Just confirm, what is the exact version that is causing the issue? 
Also, any chance you could share details on the Authentication mechanism you are using? Are you using instances of `TokenCredential` from `Azure.Identity` to setup authentication?

**Comment by wpiotrw** [comment]
Working version: 3.27.0
Affected version: 4.34.0

Mechanism used: DelegateAuthenticationProvider

**Comment by andrueastman** [comment]
Hey @wpiotrw,

Any chance you are able to compare if the tokens from the two versions differ in any way? You can grab the token that you obtain while debugging and paste it over at https://jwt.ms/ and compare the two and share any differences?

Using the `DelegateAuthenticationProvider` suggests that you are acquiring the token using a customized mechanism so it would be helpful to see if the tokens indeed have the same claims.

**Comment by wpiotrw** [comment]
Token seems to be ok. 
When the same token is used for example in the POWERSHELL same API call - it is ok.
Seems something changed on how new SDK handles proxy...

**Comment by andrueastman** [comment]
Thanks for the extra information @wpiotrw 

Any chance you could share the .NET runtime in use for your scenario? Also, any chance you share if you have a code snippet for how the proxy configuration is being setup with the graph client?
