### ISSUE TITLE
bookingsBusiness: getStaffAvailability does not always return 'busy' timeslots

### ISSUE THREAD

**Issue by ConanAPK** [microsoftgraph/msgraph-sdk-dotnet#1455]
**Describe the bug**
In some cases, when getting the Availability of Staff of a bookingsBusiness, timeslots that are already marked as busy, come through as available, even though AvailabilityIsAffectedByPersonalCalendar  is set to true

**To Reproduce**
Steps to reproduce the behavior (In my case):
1. Get Staff Availability for a certain staffmember with graphClient.Solutions.BookingBusinesses(CALENDARID).GetStaffAvailability(STAFFMEMBERIDS, startDateTime, endDateTime).Request().PostAsync()
2. View available/busy timeslots
3. See that a timeslot that is already booked, is marked as available

**Expected behavior**
Timeslots that are already booked should not be marked as available, but as busy

**Screenshots**
StartDateTime and EndDateTime on the 24th of August (Available from 12:30-17:00):
![image](https://user-images.githubusercontent.com/40423709/185639977-a155966b-ea0b-453a-a792-040aef3742cd.png)

Booked Timeslots for this user: (Do note that the white is also displayed in the wrong parts here, but that's a problem for Booking, not for Graph)
So 16:00-17:00 are marked as busy here, but available in the response from graph.
![image](https://user-images.githubusercontent.com/40423709/185640175-797581fe-aee0-4ace-8337-aaa4f41e80db.png)

Availability for this user:
So for The 24th, a wednesday (woensdag) it should be in the afternoon.
![image](https://user-images.githubusercontent.com/40423709/185640421-28796e45-d733-45f7-bd74-33579acf090d.png)

Note that this DOES work on the 23rd: This is the expected behavior.
![image](https://user-images.githubusercontent.com/40423709/185640964-e53db9a9-4a0d-4401-8116-2be836a355a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Graph 4.36

I also noticed that Sunday the 28th is marked as available by colours as well. 
So maybe something might be wrong with mapping the availability to the weekdays, depending on what day is marked as the start of the week?
![image](https://user-images.githubusercontent.com/40423709/185643495-0ae50210-9954-492f-b7aa-bb20f7c73371.png)

**Comment by andrueastman** [comment]
Thanks for raising this @ConanAPK,

As this issue seems to suggest that the API is returning incorrect results, any chance you could also post the question at the link below so that we may get feedback from the API owners on the expected behavior?

https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-customer-booking.html

If you can, please post back the link to the question created so that in future anyone who comes across this issue may also be able to find the information.

**Comment by ConanAPK** [comment]
Alright, I duplicated the issue there:
https://docs.microsoft.com/en-us/answers/questions/976005/bookingsbusiness-getstaffavailability-does-not-alw.html

**Comment by andrueastman** [comment]
Thanks @ConanAPK 

We'll close this for now and re-open if anything SDK related is raised.

**Comment by ConanAPK** [comment]
Getting no answers at the link you posted.

**Comment by ConanAPK** [comment]
@andrueastman Any update?

**Comment by andrueastman** [comment]
Hey @ConanAPK,

I noticed that the question you created does not include any tags to help with assigning the query. Any chance you can update the question and add the following tag to it?  `Microsoft-graph-customer-booking`. This should help map the question correctly to the relevant API owner.

**Comment by ConanAPK** [comment]
You mean on the answers site?
The question there is tagged with the one you mentioned.

![image](https://user-images.githubusercontent.com/40423709/191236312-329912c8-fc4d-48cb-8652-f5e105af2d58.png)

**Comment by ConanAPK** [comment]
Problem seems to be solved. Not sure if anything changed but the data is correct now.
