### ISSUE TITLE
Collection was modified; enumartion operation may not execute

### ISSUE THREAD

**Issue by Doidjin** [microsoftgraph/msgraph-sdk-dotnet#1457]
I'm getting this error everytime i try to hit a graph endpoint.
Obs: i'm migrating the V4 -> V5 version of the Microsoft.Graph.Beta

example:
`var result = await GraphService
                    .Compliance
                    .Ediscovery
                    .Cases[caseId]
                    .GetAsync();;`

**Comment by andrueastman** [comment]
Thanks for raising this @Doidjin 

Any chance you can share the stack trace from the exception as well as the target runtime version to help us investigate this further?

**Comment by Doidjin** [comment]
> Thanks for raising this @Doidjin
> 
> Any chance you can share the stack trace from the exception as well as the target runtime version to help us investigate this further?

the error that i was having is because i was using .net 3.1, changing it to 6.0 fixed for me
