### ISSUE TITLE
Add support for DeleteAsync and UpdateAsync for Subscription entities

### ISSUE THREAD

**Issue by SteveWinward** [microsoftgraph/msgraph-sdk-dotnet#146]
The v 1.0 Graph Api supports updating (ie extending) and deleting subscriptions,

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/subscription

However, the .NET Graph Client does not support updating/deleting of subscriptions.  Can we add support for this in the client library?  I believe this would require this interface to have two new methods (DeleteAsync and UpdateAsync)

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/IGraphServiceSubscriptionsCollectionRequest.cs

**Comment by MIchaelMainer** [comment]
This is already in the library although I haven't tested to make sure it works as expected. Please try:

```csharp
await graphClient.Subscriptions["subscriptionId"].Request().DeleteAsync();
var patchSubscriptionObject = new Subscription();
patchSubscriptionObject.expiration = new DateTimeOffset(); 
await graphClient.Subscriptions["subscriptionId"].Request().UpdateAsync(patchSubscriptionObject);
```

**Comment by SteveWinward** [comment]
Awesome, that's exactly what I was looking for.  Thank you for providing the code sample!
