### ISSUE TITLE
GraphServiceClient - Only HTTP/1.0 and HTTP/1.1 version requests are currently supported

### ISSUE THREAD

**Issue by pnutbnb** [microsoftgraph/msgraph-sdk-dotnet#1460]
I am trying to use GraphServiceClient to be able to retrieve list items from our Sharepoint Online

Runtime: 
.NET Framework 4.6.2

Packages:
Azure.Identity 1.6.1
Microsoft.Graph 4.36.0
Microsoft.Graph.Core 2.0.11

Code:

`
var opt= new TokenCredentialOptions
{
   AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
};

var cred = new ClientSecretCredential(myTenantId, myClientId, myClientSecret, options);

var graphServiceClient = new GraphServiceClient(cred);

graphServiceClient.Sites[mySiteGuid].Lists[myListGuid].Items.Request(myQueryOptions).GetAsync()

`

**Comment by andrueastman** [comment]
Thanks for raising this @pnutbnb,

Any chance you can confirm if you can still replicate this on the latest 4.40.0 package of the SDK?
