### ISSUE TITLE
How can i filter by $SkipToken

### ISSUE THREAD

**Issue by Doidjin** [microsoftgraph/msgraph-sdk-dotnet#1461]
In the lasts days using 4.5 beta version, i was able to filter by SkipToken doing something like this:

`            var queryOptions = new List<QueryOption>()
            {
                new QueryOption("$skipToken", skiptoken)  // Parameter of the Function
            };
`

now using 5> version, i have the scenario:

`
                   requestConfiguration.QueryParameters.Count = true;
                    requestConfiguration.QueryParameters.Filter = filter;
                    requestConfiguration.QueryParameters.Top = pageSize;
                    requestConfiguration.QueryParameters.Orderby = new[] { "displayName" };
                    requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
`

how can i filter by $skipToken ?

**Comment by andrueastman** [comment]
Tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689
