### ISSUE TITLE
The origin property in PermissionScope cannot be set

### ISSUE THREAD

**Issue by JesperLeerberg** [microsoftgraph/msgraph-sdk-dotnet#1469]
**Describe the bug**
If you set this property and send it to the graph you will get an error. Not setting this or having null works. The graph Docs does not have this property in their docs. I assume it depends on what the backend API consumes.

**To Reproduce**
Update an application registration with the new scope where the model PermissionScope has the Origin property set to e.g. "Application".

**Expected behavior**
HTTP/1.1 204 No Content

**Screenshots**
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/bee6cabf551d4cddd066d31101892423dd659a8c/src/Microsoft.Graph/Generated/model/PermissionScope.cs#L52

Graph docs:  https://docs.microsoft.com/en-us/graph/api/resources/permissionscope?view=graph-rest-1.0

**SDK version: 4.35.0**

**Comment by andrueastman** [comment]
Thanks for raising this @JesperLeerberg 

We generate the client library from https://graph.microsoft.com/v1.0/$metadata and the property is present as shown below. Unfortunately, the metadata does not give info on whether a property can or cannot be set. 

![image](https://user-images.githubusercontent.com/6464005/188416962-67505e3f-e174-424e-ab39-783900e8a773.png)

Any chance you can share more information on the exact error you receive when you set the property (error message and client-request-id) to help feedback to the relevant API team?

**Comment by andrueastman** [comment]
API team has acknowledged this is a bug and have created https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2059105 to track and fix.

**Comment by BastienPerdriau** [comment]
Hi @andrueastman , do you have any news on this ?

This issue lasts for a few months now and despite some minor updates on the NuGet, it's still there.

Or maybe a turnaround to suggest ? Use directly the API without the SDK or anything else

**Comment by andrueastman** [comment]
> it can be done by removing this property directly from the call. But still strange to have a SDK more up-to-date than the API it calls.

Thanks for this as the API team is still yet to fix this.

**Comment by mikaelweave** [comment]
I'm unable to use the MsGraph SDK for my project and still must resort to using the Azure CLI from PowerShell. 😦 Yes, this is an uncommon case but is a huge quality issue that wastes developer time and encourages them to use different approaches.

**Comment by psignoret** [comment]
@mikaelweave Can you help me understand the specific issue you had that prevented you from using the SDK? What were you trying to do that you weren't able to do?

**Comment by mikaelweave** [comment]
@psignoret - has been a while since I looked at this code tbh. Last project. Essentially, I remember that I could not use the library because the types didn't match and the error I saw was like @JesperLeerberg. I did not see the workaround of just removing the property.
