### ISSUE TITLE
Object reference not set to an object while file upload in OneDrive

### ISSUE THREAD

**Issue by Saket0911** [microsoftgraph/msgraph-sdk-dotnet#147]
I am using Microsoft Graph SDK to upload file in chunks in OneDrive. I am using below code to upload the file:

```
try
{
    GraphServiceClient graphClient = this.GetGraphServiceClient(accessToken);

    string fileName = Path.GetFileName(srcFilePath);

    using (var fileContentStream = System.IO.File.Open(srcFilePath, System.IO.FileMode.Open))
    {
        var uploadSession = await graphClient.Me.Drive.Root.ItemWithPath(fileName).CreateUploadSession().Request().PostAsync();

        var maxChunkSize = 5 * 1024 * 1024;
        var provider = new ChunkedUploadProvider(uploadSession, graphClient, fileContentStream, maxChunkSize);

        var chunkRequests = provider.GetUploadChunkRequests();
        var readBuffer = new byte[maxChunkSize];
        var trackedExceptions = new List<Exception>();
        Microsoft.Graph.DriveItem itemResult = null;

        foreach (var request in chunkRequests)
        {
            var result = await provider.GetChunkRequestResponseAsync(request, readBuffer, trackedExceptions);

            if (result.UploadSucceeded)
            {
                itemResult = result.ItemResponse;
            }
        }
    }
}
catch (Microsoft.Graph.ServiceException e)
{
}
catch (Exception ex)
{ 
}
```
The above code works fine with normal file names. However, when I am trying to upload a file with name as Test#123.pdf, "Object reference not set to an object" exception is thrown at line `var provider = new ChunkedUploadProvider(uploadSession, graphClient, fileContentStream, maxChunkSize); `

Is this a limitation of OneDrive SDK, or am I not passing the parameters correctly?

I have asked the above question on SO at this link: https://stackoverflow.com/questions/44625083/object-reference-not-set-to-an-object-while-file-upload-in-onedrive 
[AB#7335](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7335)

**Comment by MIchaelMainer** [comment]
Mark provided the answer on StackOverflow. Please mark it as an answer. The client library should provide the URL encoding in this case to be consistent.

**Comment by pundj** [comment]
@darrelmiller This is happening again. There is a question for it on StackOverflow, asked yesterday by someone else, but I am experiencing it as well. https://stackoverflow.com/questions/60270128/createfileuploadsession-calls-result-in-object-reference-not-set-to-an-instan

**Comment by MIchaelMainer** [comment]
ChunkedUploadProvider has been deprecated. Please use the LargeFileUploadTask. 

https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp
