### ISSUE TITLE
Got an error: Unable to read data from the transport connection when trying to get the MIME content of a Outlook message which has more than 25MB size attachments 

### ISSUE THREAD

**Issue by piyumi25** [microsoftgraph/msgraph-sdk-dotnet#1477]
I am having a requirement to send an email by attaching an eml file using Graph API. To attach the eml file, I have to get the Mime content of the selected message.
I am using following code sample to get the Mime content of a message item.
`var content = await _graphServiceClient.Users[mailboxAddress].Messages[mailItemId].Content.Request().GetAsync();`

Above code works fine if the attachment size is less than 25MB.
If attachment is more than 25MB, I am getting following error response.

![image](https://user-images.githubusercontent.com/33615108/189811527-8332a340-03dc-4699-9e13-b7dd4065f546.png)
I need to know a recommended way to get the mime content of large message items.

**Comment by andrueastman** [comment]
Thankd for raising this @piyumi25,

In you scenario, do you notice any difference if you increase the timeout of the client as in the code sample below when initializing the graphServiceClient instance?

```cs
            _graphServiceClient.HttpProvider.OverallTimeout = TimeSpan.FromMinutes(5);
```

**Comment by piyumi25** [comment]
> Thankd for raising this @piyumi25,
> 
> In you scenario, do you notice any difference if you increase the timeout of the client as in the code sample below when initializing the graphServiceClient instance?
> 
> ```cs
>             _graphServiceClient.HttpProvider.OverallTimeout = TimeSpan.FromMinutes(5);
> ```

Thanks for the reply and I will check it.

**Comment by piyumi25** [comment]
> ```cs
> _graphServiceClient.HttpProvider.OverallTimeout = TimeSpan.FromMinutes(5);
> ```

@andrueastman Thank you very much for your suggestion it fixes my issue.
