### ISSUE TITLE
Add support for /me/MemberOf/$/Microsoft.Graph.Group

### ISSUE THREAD

**Issue by cveld** [microsoftgraph/msgraph-sdk-dotnet#148]
In one of the Microsoft Graph code examples I stumbled upon, I found this expression
`/me/MemberOf/$/Microsoft.Graph.Group`
It returns all directory items that the current user is member of that are of type `#Microsoft.Graph.Group`.

I can't seem to find a way how to query for this expression by using the SDK. And to be honest neither I can find this expression in the spec.

Nevertheless it would be a nice addition to the SDK. And additionally, it would be great to introduce support for specific types within a result collection. All specific `Group` properties now end up in the `AdditionalData` property bag.
We had to copy over a couple of model classes for the `/me/MemberOf` expression to accommodate for the specific `Group` type.

**Comment by MIchaelMainer** [comment]
Where did you find a an example that demonstrated that call? That doesn't look like a supported pattern.

Thank you for bringing this to our attention. I question whether this functionality is supposed to be exposed -- the documentation is the spec and if it isn't there, it shouldn't be expected to be supported (or implemented for that matter). Please don't take any production dependencies on this until it is documented and we know it is a supported pattern.

**Comment by MIchaelMainer** [comment]
This is published here:

https://github.com/microsoftgraph/microsoft-graph-docs/blob/c4a5dbb50c5c6945a2fb721bc95afdec74ee450c/content/overview/overview.md

This should be in the client library. In the meantime, you can create an httprequestmessage, use the client library to authenticate the request, and deserialize the response into group objects.

There is an example, [send arbitrary HTTP requests with the .Net client library.](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md#send-http-requests-with-the-net-microsoft-graph-client-library)

**Comment by blalonde** [comment]
Same for /$/microsoft.directory.role please

**Comment by cbales** [comment]
This $ calling pattern is being de-emphasized in the Graph API and will not get support in the client library. Moving forward, you can either use the HTTP request calling pattern from within the SDK, or use another calling pattern to achieve your desired response.
