### ISSUE TITLE
Returned AccessCatalog instances are not properly deserialized

### ISSUE THREAD

**Issue by stefanboerner** [microsoftgraph/msgraph-sdk-dotnet#1482]
An AccessCatalog instance read via identityGovernance/entitlementManagement/catalogs/<id> is not properly deserialized in Microsoft.Graph 4.40.0 (.Net Framework). The requested data is however stored in "AdditionalData" of the AccessCatalog instance.
dictionary key = "value"
dictionary value = System.Text.Json.JsonElement of valueKind "Array"

**To Reproduce**
Call graph API with Microsoft.Graph (4.40.0) as follows

```
var cat = GraphClient.IdentityGovernance.EntitlementManagement.Catalogs["<id>"].Request()
.Select("Id,DisplayName,Description,CatalogType,isExternallyVisible,ModifiedDateTime")
.GetAsync()
.Result;
```

**Expected behavior**
Properties "CatalogType", "Id", "DisplayName","IsExternallyVisible" and "ModifiedDateTime" of "cat" instance are populated

**Client version**
Microsoft.Graph 4.40.0
Microsoft.Graph.Core 2.0.12
Project Target Framework 4.8

![catalog](https://user-images.githubusercontent.com/23232060/190400775-7aef8fbe-33cf-4d98-9785-7ed927a304a5.png)

**Comment by andrueastman** [comment]
Hey @stefanboerner,

Thanks for raising this. 

The latest version of the SDK is [4.40.0](https://www.nuget.org/packages/Microsoft.Graph/4.40.0) from last week. Any chance you can confirm the reported version to help us investigate?

**Comment by stefanboerner** [comment]
Hi @andrueastman,
just saw the typo in my report. Sorry for the confusion. Yes, the version we use is 4.40.0.
![references](https://user-images.githubusercontent.com/23232060/191242112-7e5f6db4-aea2-4ec0-8cca-f9a734fca357.png)

**Comment by andrueastman** [comment]
Hey @stefanboerner,

Any chance you can replicate this with the latest version ([4.42.0](https://www.nuget.org/packages/Microsoft.Graph/4.42.0)) on your side? From my end, it looks like the properties are populated correctly.

![image](https://user-images.githubusercontent.com/6464005/192725614-bf3606f2-0097-45bf-a3ba-ff0b3275bf8e.png)

**Comment by stefanboerner** [comment]
Hi @andrueastman,
I have just upgraded to 4.42.0 and still have the same behavior.
![catalog3](https://user-images.githubusercontent.com/23232060/192741313-d2a5305b-cd51-4d4d-89f8-d84387a41a33.png)
