### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by ofthelit** [microsoftgraph/msgraph-sdk-dotnet#1485]
**Describe the bug**
The docs are not up to date with the latest version.

**To Reproduce**
For example the headers documentation https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/headers.md
```
var newObject = graphServiceClient
	.Object
	.Request(new HeaderOption("Etag", etag))
	.Patch(updatedObject);
```
This example does not work at all and I found out it is now structured like this after looking at the upgrade document:
```
var newObject = graphServiceClient
	.Request()
        .Header("ConsistencyLevel", "eventual")
	.Patch(updatedObject);
```

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/collections.md
The indentation of the examples is a mess.

**Expected behavior**
I expect the documentation an the examples to match the last stable version.

**Comment by andrueastman** [comment]
Docs have been updated to reflect this
