### ISSUE TITLE
Require SharePoint LargeFileUploadTask Code using Graph API 

### ISSUE THREAD

**Issue by R-LIBIN** [microsoftgraph/msgraph-sdk-dotnet#1486]
Kindly provide api code for SharePoint LargeFileUploadTask for uploading large files more than 3 MB in SharePoint using dotnet graph api.

**Comment by andrueastman** [comment]
Thanks for raising this @R-LIBIN 

We have sample code at the link below. Any chance this works out for you?

https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp#upload-large-file-to-onedrive

**Comment by R-LIBIN** [comment]
Hi @Eastman, I need code for SharePoint.

The code should looks different from code of SharePoint.

Kindly share it.

Thank you.

Had a little hard finding a way to target the Document Folder.

Also, we need the meaning of .ItemWithPath(itemPath) not well explained in
the documentation.

What in it means is still means a mystery.

Regards,
Libin
