### ISSUE TITLE
Bookings: Can't get staffmember details from staffmemberID

### ISSUE THREAD

**Issue by ConanAPK** [microsoftgraph/msgraph-sdk-dotnet#1488]
**Describe the bug**
When getting the staffmembers of a certain service, and then trying to get the details of each of these staffmembers, some staffmembers throw an error.

**To Reproduce**
1. Request staffmembers of a service within a calender (This calendar only has one service)
Dim Services = Await graphClient.Solutions.BookingBusinesses(calendar).Services.Request().GetAsync()
Services.FirstOrDefault.StaffMemberIds

2. Try to get details of the staffmembers
![image](https://user-images.githubusercontent.com/40423709/191200484-f4cf73fe-e1ba-4568-9c9e-2f1bc35c18ff.png)
![image](https://user-images.githubusercontent.com/40423709/191200663-40551367-2428-4930-864b-bb4af0936c0b.png)

3. For SOME users, an error is thrown
 
![image](https://user-images.githubusercontent.com/40423709/191201337-5f8eb501-c87a-4973-aeee-ee19b237bbaf.png)

Other users are returned as expected
![image](https://user-images.githubusercontent.com/40423709/191201511-ca37fc57-e18f-4e3e-8528-611e11cae015.png)

**Expected behavior**
If a staffmember is part of a service, and thus part of the calendar, I expect no errors while trying to get details using 
![image](https://user-images.githubusercontent.com/40423709/191201071-0b6f506e-0450-4747-bfff-a06a1c1ddff6.png)

Right now 2/12 members do not return an error:
![image](https://user-images.githubusercontent.com/40423709/191204981-26fd3984-28be-46d5-9492-c64a251dff54.png)

![image](https://user-images.githubusercontent.com/40423709/191205030-73b6a76f-3f4a-40b5-ac25-28cea7122def.png)

**Comment by ConanAPK** [comment]
I noticed that once I put all the staffmembers to 'Guest' instead of 'member' I see more (Still not all), but I don't see why I wouldn't be able to do this with 'members'
![image](https://user-images.githubusercontent.com/40423709/191206418-38ca53dd-dc59-46fe-ac22-8786f38726ef.png)

**Comment by ConanAPK** [comment]
I have also noticed, that after setting all 12 of the staffmembers to guest, that while getting availability using

Await graphClient.Solutions.BookingBusinesses(calendar).GetStaffAvailability(Services.FirstOrDefault.StaffMemberIds, startDateTime, endDateTime).Request().PostAsync()

for all of these staffmemberId's. results in only 7 availabilities being returned,  only those of the ones whose email I got while getting details for a staffmember

**Comment by ConanAPK** [comment]
Another update

When I request the staffId's of the whole bookingbusiness, I only get 10 staffmembers
![image](https://user-images.githubusercontent.com/40423709/191476917-d3211551-d7d6-4154-a272-818aa8bfbf41.png)

Of course, the 7 for whom I get availabilities and details are in here, the other 5 are not.

The complete calendar should also have 28 members, not 10

**Comment by ConanAPK** [comment]
Update 4:

I noticed that when I add a new Staffmember, I still get 10 members when calling
Await graphClient.Solutions.BookingBusinesses(calendar).StaffMembers.Request().GetAsync()
The newest staffmember is included in this result, but then another older one goes missing from the response.

Then, I only get 6 availabilities when trying to get the staffAvailability, as expected, because now one fewer staffmember matches with the 10 latest staffmembers of the bookingservice.

I hope to have now given you enough information to fix this bug.

Kind regards,
Conan

**Comment by ConanAPK** [comment]
StaffID's get returned now. Did something change on graph's end?

**Comment by andrueastman** [comment]
Hey @ConanAPK,

It looks like some changes were made in the API end side of things. 
We'll close this issue for now and feel free to re-open in the event anything new is raised.
