### ISSUE TITLE
Unable to successfully authenticate .NET application requests

### ISSUE THREAD

**Issue by nicbavetta** [microsoftgraph/msgraph-sdk-dotnet#150]
I am having great trouble implementing the Microsoft Graph SDK in my .Net Core application.

I registered an application in Microsoft's Application Registration Portal and am passing an implementation of IAuthenticationProvider to the GraphServiceClient constructor with those application secrets. My authentication provider is as so:

```
public class MicrosoftAuthenticationProvider : IAuthenticationProvider
    {
        private readonly string m_ClientId;
        private readonly string m_ClientSecret;
        private readonly string m_MicrosoftUrl;

        public MicrosoftAuthenticationProvider(string clientId, string clientSecret, string microsoftUrl)
        {
            m_ClientId = clientId;
            m_ClientSecret = clientSecret;
            m_MicrosoftUrl = microsoftUrl;
        }

        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            var authContext = new AuthenticationContext("https://login.windows.net/" + m_MicrosoftUrl + "/oauth2/token");
            var creds = new ClientCredential(m_ClientId, m_ClientSecret);

            AuthenticationResult authResult = await authContext.AcquireTokenAsync("https://graph.microsoft.com/", creds);

            request.Headers.Authorization = new AuthenticationHeaderValue("bearer", authResult.AccessToken);
        }
    }
```
For my initial interaction, I simply just want to verify that I can successfully retrieve data with the Graph client. Therefore, I make a simple call:

```
var authenticationProvider = new MicrosoftAuthenticationProvider(clientId, clientSecret, "example.onmicrosoft.com"); // "example" is replaced with my subdomain. Just using it for this post.

var graphServiceClient new GraphServiceClient(authenticationProvider);

var id = await graphServiceClient.Me.Request().Select("id").GetAsync();
```

Unfortunately, I receive the following response:

**ServiceException: Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.**

I have tried many different things with no luck. In an attempt to brute force this workflow, I added as many permissions as I could in the Application Registration Portal (no, these permissions are not permanent):

![image](https://user-images.githubusercontent.com/8139425/27364297-647dbcaa-55ff-11e7-8e7f-c4e26f97e44d.png)

I am obviously missing something here. Can anyone help me through this?

**Comment by MIchaelMainer** [comment]
Thank you for posting to our issues. Your best bet is to post this to StackOverflow and provide both the microsoftgraph and adal tags. You'll get more eyes on this and since this is an authorization issue, the ADAL people will be in a better position to answer. With that said, I think you are using the wrong authority endpoint. The one you're using may redirect to the correct one but I suggest you use login.microsoftonline.com ([reading](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios)).

Please provide a link to the StackOverflow post in this issue. Thank you.

**Comment by Mardoxx** [comment]
I was blindly copy pasting stuff from the internet to play around with the GraphAPI. The sample code I was looking at used login.microsoft.net, and kept failing even though correct claims were in the token. Changing the authority to login.microsoftonline.com made it work.

IOW.. `https://login.microsoft.net/{tenant}/oauth2/token` does not work, changing it to `https://login.microsoftonline.com/{tenant}/oauth2/token` is how to avoid hours of hair-pulling 😄
