### ISSUE TITLE
Extension Name and Id must be the same

### ISSUE THREAD

**Issue by jake-bauer** [microsoftgraph/msgraph-sdk-dotnet#151]
I am trying to run a query using the graph client to search user extensions without their username. I have been unable to find the methods required to query extensions by name without knowing the id of the extension or the user that it is attached to. I was wondering if that was a planned feature or already supported and I'm just not clear about the direction to go.

**Comment by MIchaelMainer** [comment]
Are you talking about open extensions?

I don't see that functionality in the docs for [open extensions](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/opentypeextension) so I assume that search isn't a feature of open extensions. I'll pass this along as feedback to the owners of open extensions.. Please go to the https://office365.uservoice.com/ and open this as a feature request.

**Comment by dkershaw10** [comment]
That is not supported for open extension.  If you want to search extensions, this is supported for schema extensions.  Please look at https://developer.microsoft.com/en-us/graph/docs/concepts/extensibility_schema_groups.  However this depends on what you are trying to search on.  Can you provide an example please?

**Comment by jake-bauer** [comment]
We need to be able to look up a seperate cached authentication token by the authentication token and get back a reference to a user.

**Comment by MIchaelMainer** [comment]
That's an interesting scenario. Does the vendor auth token have the user information inside of it?

**Comment by jake-bauer** [comment]
It is simply a guid, that is why we were struggling with the association through the graph client. If the schema extensions can return all based on having a same name that would allow me to search then we can use those assuming that schema extensions can be associated to users.

**Comment by jake-bauer** [comment]
Also as it is indicated via the http client what is the appropriate way to search schema extensions that is not via the user via the client

**Comment by MIchaelMainer** [comment]
Have you seen this: https://developer.microsoft.com/en-us/graph/docs/concepts/extensibility_schema_groups#5-get-a-group-and-its-extension-data

The example shows how to filter users based on a schema extension. The schema extension is associated with a entity type. The supported entities are stated in that topic I provided above.

**Comment by jake-bauer** [comment]
I think I figured out how to do it now I'm just trying to get the schema registered as we are using the graph client and i found sources stating you cannot create scchemas via the client and have to complete it via an http request. https://stackoverflow.com/questions/43889984/microsoft-graph-registering-a-schema-extension was my source for this information. If it is no longer correct could you inform me what permissions my application needs to have in azure to be able to create the schema extension via the graph client library

**Comment by MIchaelMainer** [comment]
Someone in the StackOverflow post stated that Directory.AccessAsUser.All is required for this. I can't verify that information. We'd need to check the documentation (hopefully this is documented).

```csharp
// Create a schema extension for groups.
SchemaExtension extensionDefinition = new SchemaExtension()
{
    Description = "This extension correlates a group with a foreign database.",
    Id = $"crmForeignKey", // Microsoft Graph will prepend 8 chars
    Properties = new List<ExtensionSchemaProperty>()
    {
        new ExtensionSchemaProperty() { Name = "fid", Type = "Integer" }
    },
    TargetTypes = new List<string>()
    {
        "Group"
    }
};

// Create the schema extension. This results in a call to Microsoft Graph.
SchemaExtension schemaExtension = await graphClient.SchemaExtensions.Request().AddAsync(extensionDefinition);
```

Then you'll need create a class for the extension:

```csharp
[JsonObject(MemberSerialization = MemberSerialization.OptIn)]
public class MyDBExtensionClass
{
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "fid", Required = Newtonsoft.Json.Required.Default)]
    public int FID { get; set; }

    public MyDBExtensionClass(int fid)
    {
        FID = fid;
    }
}
```

next, add the extension to a group. In this case, we'll create a new one:

```csharp
// Create a group with the schema extension defined earlier.
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add(schemaExtension.Id, new MyDBExtensionClass(123123));
Group group = new Group()
{
    DisplayName = $"Test group - {Guid.NewGuid().ToString()}",
    Description = "This group was created with a schema extension",
    MailEnabled = false,
    MailNickname = "nickname", // silly requirement since this isn't mail enabled.
    SecurityEnabled = false,
    GroupTypes = new List<string>() { "Unified"},
    AdditionalData = extensionInstance
};
await Async.Task.Delay(10000); // It takes some time for the schema extension def to be available for the creation of a group.
group = await graphClient.Groups.Request().AddAsync(group);
```

**Comment by jake-bauer** [comment]
I tried following the setup you gave which is very similar to what I had originally That results in the receiving of this error message. `{"Code: Authorization_RequestDenied\r\nMessage: Insufficient privileges to complete the operation.\r\n\r\nInner error\r\n"}` 

I have attached screen shots of the current permissions the azure app has, I think I have matched the permissions required correctly. If it helps I am attaching screen shots of my given permissions.

Graph Client:
Application Permissions:
![image](https://user-images.githubusercontent.com/25064605/27485150-9ca76e7c-57f9-11e7-9d51-98e4bff38813.png)
Delegated Permissions:
![image](https://user-images.githubusercontent.com/25064605/27485180-be10416a-57f9-11e7-84ed-4ff55b23e275.png)

Windows Azure Active Directory:
![image](https://user-images.githubusercontent.com/25064605/27485260-0d0329a4-57fa-11e7-8912-1965fd6f7ee2.png)

I have the ability to add any permissions required, but the documentation on the relationships between the scope permissions requested when making a http requested versus using the client, as the names are not exactly 1:1 the same.

**Comment by phazlett** [comment]
@jake-bauer, I had the same error. The only way I could add a schema extension was to use the old Azure Graph API. I followed this post:

https://msdn.microsoft.com/en-us/library/azure/ad/graph/howto/azure-ad-graph-api-directory-schema-extensions

Once added, I am now able to see the custom attribute with the Microsoft Graph Explorer as well as with the Microsoft.Graph C# client. What I've not been able to figure out is how to update the attribute and assign Office 365 licenses in the same C# client request.

**Comment by MIchaelMainer** [comment]
@phazlett Did you try my suggestion in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/151#issuecomment-310526300? Did that not work? @jake-bauer, can you grab the access token and inspect it for the Directory.AccessAsUser.All scope?

**Comment by phazlett** [comment]
@MIchaelMainer, my schema extension has been created. Thanks! Now not to hijack this thread, do you have a code snippet that shows how to use Microsoft.Graph.GraphServiceClient to set the value of the extension attribute?

**Comment by MIchaelMainer** [comment]
That linked comment has an example of that. That first code example shows the definition of the schema extension and then the call to register it. We get back the registered schema extension; it will have an identifier on it. 

The next example shows a custom class to represent your schema extension. Notice that the class defines a single property called FID; it matches the property of the schema extension we created (note to self, it would be useful to have an extension and base interface to automate the creation of a schema extension by passing in an extension Type).

The third example shows how to use the schema extension id we got back in step one, and the schema extension class in step 2, to add the extension to a group. In our case, we set the extension value in our constructor, `new MyDBExtensionClass(123123)` 

I hope this helps. Any more follow up questions should be directed at StackOverflow with the microsoftgraph tag.

**Comment by MIchaelMainer** [comment]
Please reopen if this is an issue with the client library.

**Comment by lenain71** [comment]
I come to you on this post because I am exactly in this case.

Groups resources are extended with a schema extension value (already in place ) : 
![image](https://user-images.githubusercontent.com/42752420/143475330-1939f2a7-2e17-4400-9ef4-b9582ac6e0a2.png)

I'm trying to update a resource group using .Net core 3.1 apps and MSgraphClient (through Pnp.Core SDK). I'm using exactly the same code structure, here for detail : 

```
var formatedGraphData = new M365ResourceTaggingResponse(this._m365ResourceToUpdate);
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add(GraphAPIConstant.XPO_Custom_Extension_Status.ExtensionStatusName, JsonConvert.SerializeObject(formatedGraphData));

var groupUpdated = new Group
{
AdditionalData = extensionInstance
};

var groupItem = await graphServiceClient.Groups[_m365ResourceToUpdate.Id].Request().UpdateAsync(groupUpdated);
```

Declaration for the class M365ResourceTaggingResponse
 
```
[JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    public class M365ResourceTaggingResponse
    {
        [JsonProperty(PropertyName = "ExpirationStatus")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ExpirationStatus Status { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "expirationDate")]
        public DateTime? ExpirationDate { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "ExpirationLastControlled")]
        public DateTime? ExpirationLastControlledDate { get; set; }

        public M365ResourceTaggingResponse(M365ResourceTaggingRequest request)
        {
            this.Status = request.Status;
            this.ExpirationDate = request.ExpirationDate;
            this.ExpirationLastControlledDate = request.ExpirationLastControlledDate;
        }
    }
```

Now the issue : no matter what, i'm alway have a bad request 400 :

Debug object send to MSGraph : 
![image](https://user-images.githubusercontent.com/42752420/143477079-9ce89503-174e-4335-a193-a699e149ddec.png)

Debug detail : 
![image](https://user-images.githubusercontent.com/42752420/143477141-41dbe246-4423-4761-a95b-b7f583eadfc2.png)

Error message:
![image](https://user-images.githubusercontent.com/42752420/143477209-67483b0e-d4a1-4611-b99e-7d2ea714faa7.png)


If i made the exact same query using grpha Explorer, ith the same data, all is good : 
![image](https://user-images.githubusercontent.com/42752420/143477441-186ea2ae-5301-44e3-8756-729d600ca9fe.png)

Is someone succesfully update a Azure Resource (Groups, users...) with an schema extension value using theGraphAPI client ?

Regards
