### ISSUE TITLE
Regression: The '$filter' parameter value is not supported for 'Messages' resource

### ISSUE THREAD

**Issue by kadukf-outreach** [microsoftgraph/msgraph-sdk-dotnet#1512]
**Describe the bug**
Delta sync on the resource 'Messages' doesn't support $filter. We use this feature for more than a year and it stopped to work on my email account. 

Example: 
```
https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$filter=receivedDateTime+ge+2022-10-05T10:07:09Z
```

Results in:

```
{
    "error": {
        "code": "ErrorInvalidUrlQuery",
        "message": "The '$filter' parameter value is not supported for 'Messages' resource; only a value of 'receivedDateTime ge value' is supported."
    }
}
```

**To Reproduce**

```
curl 'https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$filter=receivedDateTime+ge+2022-10-05T10:07:09Z' \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer .... ' \
  --compressed
```

**Expected behavior**
It should follow the contract: 
https://learn.microsoft.com/en-us/graph/delta-query-messages#use-query-parameters-in-a-delta-query-for-messages

**Screenshots**

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/70577857/194049312-bb2f12cc-ce86-41a3-8b9e-c198210b4dc3.png">

**Comment by andrueastman** [comment]
Hey @kadukf-outreach,

Any chance you can still replicate this? From my end the query works without issue on the Graph Explorer

**Comment by kadukf-outreach** [comment]
It looks like the issue was fixed or so. Closing the ticket.
