### ISSUE TITLE
[Client bug]: the library does not url-encode UPNs

### ISSUE THREAD

**Issue by zvrba** [microsoftgraph/msgraph-sdk-dotnet#1515]
**Describe the bug**
When looking up an external user by UPN (i.e., of the format `aaa.sdd_domain.com#EXT#@tenant.domain`) the library does not URL encode the UPN. I get a not found exception as if I requested then UPN with everything after '#' stripped.

**To Reproduce**
```
// var upn = System.Net.WebUtility.UrlEncode(upn); Must be un-commented for the request to work
var user = await groupGraphClient.Users[upn].Request().Select("id").GetAsync();
```

**Expected behavior**
That the library hides all of HTTP shenanigans from the user-programmer. Manually url-encoding the UPN for the call should not be necessary.

**Client version**
4.14.0

**Comment by Reikooters** [comment]
I just encountered this myself (version 4.45.0) and came here to report this.

I believe that this creates the possiblity where a malicious user of a web application using Microsoft Graph, may be able to impersonate another user - e.g. if a registered user `user1@domain.com` exists in the system and an attacker registers as `user1%40domain.com#whatever@email.com`, then if the server application doesn't escape the email address, they could trick the request to be sent on behalf of `user1@domain.com` instead.

Also I would suggest the use of `System.Uri.EscapeDataString` over `System.Net.WebUtility.UrlEncode` to remove any ambiguity with the + symbol and the like
