### ISSUE TITLE
In my aspnetcore application, I got error "CompactToken parsing failed with error code: -2147184105"

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/msgraph-sdk-dotnet#152]
Hi team
great work for this library, I use the library in several scenario now, You guys save my life sometime :)

recently, I want integrated this great function in my aspnetcore application, but something maybe wrong, I am stuck now , hope you guys can give me some suggestion, Thank you

In the aspnetcore mvc project, startup.cs file , Configure method , I add some code like this

```           

app.UseCookieAuthentication();

            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                ClientId = Configuration["Authentication:AzureAd:ClientId"],
                ClientSecret = Configuration["Authentication:AzureAd:ClientSecret"],
                Authority = Configuration["Authentication:AzureAd:AADInstance"] + Configuration["Authentication:AzureAd:TenantId"],
                CallbackPath = Configuration["Authentication:AzureAd:CallbackPath"],
                ResponseType = OpenIdConnectResponseType.CodeIdToken,
                SaveTokens =true 
            });

```

I had set the SaveTokens to true because I want to get the accesstoken in my controller class to setup the GraphServiceClient

```   
 
public IActionResult Index()
        {

            var client = new GraphServiceClient(new DelegateAuthenticationProvider(async request =>
            {
                var accessToken = HttpContext.Authentication.GetAuthenticateInfoAsync("OpenIdConnect").Result.Properties.Items[".Token.access_token"];
                request.Headers.Authorization = new AuthenticationHeaderValue("bearer", accessToken);
            }));

            var user = client.Me.Request().GetAsync().Result;

            return View();
        }

```

The code is nice，but unfortunately when I try to run this application , I got the error 

![image](https://user-images.githubusercontent.com/1996954/27412246-ef7266fe-5725-11e7-9ba5-57c2e5e5c3c4.png)

**Comment by MIchaelMainer** [comment]
Hello @chenxizhang, thank you for posting and we're happy to hear that this library has helped you. For situations like this, please post to StackOverflow with the microsoftgraph tag. That way more people will see, learn, and contribute to both the answer and question. Please add a link here in this issue to your StackOverflow post when you've posted it.

**Comment by MIchaelMainer** [comment]
Also, are you working off of any samples in either github.com/microsoftgraph or github.com/azuread?

**Comment by chenxizhang** [comment]
There is not dotnet core sample now, I think we are very happy to see who can provider the sample with dotnetcore? 

thank you @MIchaelMainer

**Comment by MIchaelMainer** [comment]
Have you seen this sample: https://github.com/microsoftgraph/aspnetcore-apponlytoken-webhooks-sample?

**Comment by chenxizhang** [comment]
Thank you @MIchaelMainer 
I will checkout it ASAP

**Comment by MIchaelMainer** [comment]
This isn't an issue with this client library.
