### ISSUE TITLE
AOT compile Microsoft.Graph.dll failure

### ISSUE THREAD

**Issue by stcmz** [microsoftgraph/msgraph-sdk-dotnet#1530]
**Describe the bug**

We have a net6.0-ios and net6.0-android app integrated with Graph SDK. In order to solve the **System.TypeLoadException** issue, we upgraded the SDK to 5.0 preview. When we tried to build and deploy the app to an iPhone in Visual Studio 17.3.6, the following error occurred:
> 1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.517\targets\Xamarin.Shared.Sdk.targets(1003,3): error : Failed to AOT compile Microsoft.Graph.dll, the AOT compiler exited with code 134

**To Reproduce**
1. Create an **iOS Application** in Visual Studio 17.3.6
2. Integrate Graph SDK 5.0 preview into the project
3. Install Xcode 14.0 in a Mac
4. Connect Visual Studio to the remote Mac
5. Connect a provisioned iPhone to the Mac
6. Choose the connected remote iPhone from the Debug dropdown list in Visual Studio
7. Build and run toward the remote iPhone
8. See error

**Expected behavior**
The app should be built and deployed to the connected iPhone, then launched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.675

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 16.0.3

**Additional context**

**Comment by ddyett** [comment]
closing as it's the preview version.  Please re-open if occurs with V5 official release.
