### ISSUE TITLE
[Client bug] IDriveItemInviteRequestBuilder with expirationDateTime returns InvalidRequest

### ISSUE THREAD

**Issue by dviry** [microsoftgraph/msgraph-sdk-dotnet#1535]
When trying to send an invitation to a DriveItem, setting ExpirationDateTime to anything but null will return an error.

Using latest Microsoft.Graph 4.45.0 NuGet, under net6 in a Windows environment.

```c#
var permissions = await graphClient.Drives[driveId].Items[itemId]
      .Invite(
          recipients,
          requireSignIn: false,
          roles: roles,
          sendInvitation: true,
          message: message,
          retainInheritedPermissions: null,
          expirationDateTime?.ToUniversalTime().ToString("u").Replace(" ", "T", StringComparison.OrdinalIgnoreCase),
          password: null)
      .Request()
      .PostAsync(cancellationToken);
```

Throws:

Message: Invalid request
Inner error:
        AdditionalData:
        date: 2022-10-26T21:29:46
        request-id: 13c7c729-3d90-4289-b4bb-a8bbe5d41f6d
        client-request-id: 13c7c729-3d90-4289-b4bb-a8bbe5d41f6d

This seems to be an older issue mentioned in a couple of places:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1055
https://github.com/microsoftgraph/microsoft-graph-docs/issues/8820

Also - why is the expirationDateTime of type string and not DateTimeOffset? like in CreateLink() - might be related to the issue.

**Comment by andrueastman** [comment]
Thanks for raising this @dviry,

It seems that this may be an issue with the service not supporting the `expirationDateTime` parameter despite it being present in the API metadata according to https://docs.microsoft.com/en-us/answers/questions/477533/unable-to-make-a-request-to-send-a-sharing-invitat.html and the operation may not be possible to use with the parameter at the moment.
