### ISSUE TITLE
Create teamworkTag gives 403

### ISSUE THREAD

**Issue by AlexSen** [microsoftgraph/msgraph-sdk-dotnet#1536]
In C# Azure function when I try to create Team Tag (using App permissions) I receive 401 code response despite fact that I have granted App permissions with message:
```Console
System.Private.CoreLib: Exception while executing function: ProjectGet. Microsoft.Graph.Core: Code: Forbidden
Message: Missing role permissions on the request. API requires one of 'TeamworkTag.ReadWrite'. Roles on the request 'Directory.ReadWrite.All, Group.ReadWrite.All, User.Read.All, TeamworkTag.ReadWrite.All'
```

**To Reproduce**
```C#
var teamworkTagMembersCollection = new Graph.TeamworkTagMembersCollectionPage();
teamworkTagMembersCollection.Add(new Graph.TeamworkTagMember
{
    UserId = "<User AzADObjectId>"
});

var result = await graph.Teams["MyTeam ObjectId"].Tags.Request()
.AddAsync(new Graph.TeamworkTag
{
    DisplayName = "Tag name",
    Description = "Tag description",
    Members = teamworkTagMembersCollection
});
```

### Application permissions
![image](https://user-images.githubusercontent.com/6735288/198227506-ccf05044-6c85-4c56-abb9-c79e5fc6e688.png)

### Token scopes (decoded from token)
![image](https://user-images.githubusercontent.com/6735288/198227746-85b3d6bf-0100-4f62-91b6-9b12fb280cb4.png)

### Packages used
```XML
<PackageReference Include="Azure.Core" Version="1.25.0" />
<PackageReference Include="Azure.Identity" Version="1.7.0" />
<PackageReference Include="Azure.Storage.Blobs" Version="12.14.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.8.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.0.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.33" />
<PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="5.1.0" />
<PackageReference Include="Microsoft.Graph" Version="4.45.0" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.47.2" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
<PackageReference Include="Newtonsoft.Json.Schema" Version="3.0.14" />
<PackageReference Include="PnP.Core" Version="1.7.0" />
<PackageReference Include="PnP.Core.Auth" Version="1.7.0" />
<PackageReference Include="PnP.Framework" Version="1.10.0" />
```

**Expected behavior**
OK response.

**Comment by andrueastman** [comment]
Thanks for raising this @AlexSen,

According to the documentation at the link below , it looks like to perform this specific error message, you have the correct app permission as `TeamworkTag.ReadWrite.All`.

https://learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-1.0

The error message from the API however suggests that you need the `TeamworkTag.ReadWrite` permission. Any chance you can add this permission to the request and validate that it works?

We can then feed this info back as a possible issue with the API documentation

**Comment by AlexSen** [comment]
@andrueastman , ```TeamworkTag.ReadWrite``` is type of delegate permission. But I'm using App permission (ClientID/Certificate).
Meanwhile, I've added this permission for app (see screen below). But as you understand I can't get user consent (it's Azure Dyrable Function). Maybe you can suggest how scope can be adjusted for such case? (via DI, using Startup, as I use this approach, see another screen below).

### Azure App Permission
![image](https://user-images.githubusercontent.com/6735288/198979301-d9b63049-b6e3-4cc3-a2b1-1452723da0a2.png)

### Graph injection in Durable Function
![image](https://user-images.githubusercontent.com/6735288/198980156-184ce81f-d280-4cbb-8b74-1867d9d0d25c.png)

**Comment by andrueastman** [comment]
Thanks for the detailed info @AlexSen,

It does indeed look like the `TeamworkTag.ReadWrite` permission does not exists for the Application flow which suggests that this is most likely a service issue.

Any chance you can get the `request-id`/`client-request-id` from the error response and share it so that we may use it to forward the issue to the relevant API team?

**Comment by AlexSen** [comment]
@andrueastman, sure. Here it is:
```Console
[2022-11-01T12:56:17.500Z]      date: 2022-11-01T12:56:16
[2022-11-01T12:56:17.502Z]      request-id: 3a6aee8a-4597-413b-bb5a-78795ba4fd77
[2022-11-01T12:56:17.504Z]      client-request-id: 3a6aee8a-4597-413b-bb5a-78795ba4fd77
```

**Comment by andrueastman** [comment]
We've raised this with the relevant team and will revert on any findings made with regards to this.

**Comment by AlexSen** [comment]
Hello, @andrueastman . Kindly would ask what's next step? Should I just wait for new release? any findings, ETAs?

**Comment by andrueastman** [comment]
@AlexSen Any chance this is still an issue for you?

**Comment by AlexSen** [comment]
Do confirm that it works now. Thanks for fixing ;)
