### ISSUE TITLE
OneDrive: Get permissions, invitation.email is null

### ISSUE THREAD

**Issue by phnx47** [microsoftgraph/msgraph-sdk-dotnet#154]
When I send direct request: 
```https://graph.microsoft.com/v1.0/me/drive/items/{fileId}/permissions```
Response is like:
```
{
    "value": [
        {
            "grantedTo": {
                "user": {
                    "displayName": "FirstName LastName",
                    "id": "id"
                }
            },
            "id": "id",
            "invitation": {
                "email": "login@outlook.com",
                "signInRequired": true
            },
            "link": {
                "webUrl": "url"
            },
            "roles": [
                "write"
            ],
            "shareId": "shareId
        }
    ]
}
```
**value[0].invitation.email != null**

but, when I use SDK:
**email == null**

**Comment by MIchaelMainer** [comment]
What does the code look like for generating that call with the client library?

**Comment by phnx47** [comment]
```
IGraphServiceClient graphServiceClient = new GraphServiceClient(BaseUrl, new DelegateAuthenticationProvider(requestMessage =>
                {
                    requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                    return Task.FromResult(0);
                }));

var permissionsPage = graphServiceClient.Me.Drive.Items[fileId].Permissions.Request().GetAsync(cancellationToken);
var permissions = new List<Permission>();
permissions.AddRange(permissionsPage.CurrentPage);

while (permissionsPage.NextPageRequest != null)
{
    permissionsPage = await permissionsPage.NextPageRequest.GetAsync(cancellationToken);
    permissions.AddRange(permissionsPage.CurrentPage);
}
foreach (var permission in permissions)
   {
	   // here
	   // permission.Invitation.Email == null
	   // permission.Invitation.SignInRequired == true
	   ...
   }
```
![2017-06-27_20-39-33](https://user-images.githubusercontent.com/1101691/27601731-09bf0de4-5b79-11e7-99af-18745757e497.png)

**Comment by MIchaelMainer** [comment]
When I send the request via the client library or raw rest, they look the same. But then I don't have the invitation property set on the target file. What's the setup for the invitation?

**Comment by phnx47** [comment]
This is a shared file. You need to create a link with an invitation. And accept it from another account.

**Comment by MIchaelMainer** [comment]
I'm not seeing the invitation property. Are you using OneDrive consumer or business?

**Comment by phnx47** [comment]
consumer OneDrive

**Comment by phnx47** [comment]
Docs from OneDrive: https://github.com/OneDrive/onedrive-api-docs/blob/master/resources/permission.md

**Comment by MIchaelMainer** [comment]
I'm unable to repro the missing email value. Attached image shows the email value is accessible from the client library.  This isn't an issue with the client library. I suggest that you post to StackOverflow with the microsoftgraph and onedrive tag to StackOverflow. Please provide full repro steps so we can figure out what's going on.

![image](https://user-images.githubusercontent.com/8527305/27712320-5946565c-5cdb-11e7-922a-c0a3f5972d01.png)

**Comment by phnx47** [comment]
Ok. I closed it. I'll try to better describe the problem if it exists in SO
