### ISSUE TITLE
Cannot use 'expand=extensions' on events

### ISSUE THREAD

**Issue by MrM40** [microsoftgraph/msgraph-sdk-dotnet#1540]
If I in Graph Explorer execute `https://graph.microsoft.com/v1.0/me/events?$select=id,subject&$expand=extensions` it will run for a long time (~5-10 sec) and eventually result in this error:
``` JSON
{
    "error": {
        "code": "UnknownError",
        "message": "Error while processing response.",
        "innerError": {
            "date": "2022-10-29T07:21:05",
            "request-id": "1dfa6b80-dd91-4770-9fd1-xxxxxxxxxxxx",
            "client-request-id": "9a8bda53-c2a2-26da-3c70-xxxxxxxxxxxxxx"
        }
    }
}
```
If I do the same on a user, i.e. `https://graph.microsoft.com/v1.0/me?$select=id,displayName&$expand=extensions` it execute fine.

Is this expected?

I am able to retrieve extensions on events if I apply a filter like:
`https://graph.microsoft.com/v1.0/me/events?select=id,subject&$expand=extensions($filter=id eq 'ExtID')`

**Comment by andrueastman** [comment]
Thanks for raising this @MrM40 

As this seems to be an issue from the API end, any chance you can share the `client-request-id` and `request-id` values so that we may forward this to the relevant API teams to investigate?

**Comment by MrM40** [comment]
Is it safe to send it here in public?
They change for every call so it might not provide any value?
I assume the error apply for everyone so the  relevant API team can just call the command themselves and get the error.

**Comment by andrueastman** [comment]
Hey @MrM40,
That is true, the values are unique and generated on every request and this will help with tracing the request to find out if it's an issue specific to the request or not.

**Comment by MrM40** [comment]
Anyone can within two 2 seconds determine if this is a general problem by throwing the command in Graph Explorer.
If they get the same error, they have all what the need. If they don't, close the issue, it cannot be more simple than that.

**Comment by MrM40** [comment]
Not an issues with the .Net API, but in the core Graph API, will close the issue, sorry for the noise.
(but I don't think learn.microsoft.com is the right place for bug-reports, I've create a support ticket instead, we'll see)
