### ISSUE TITLE
Adding/modifying new open-extension on an event preserve existing properties in the extension

### ISSUE THREAD

**Issue by MrM40** [microsoftgraph/msgraph-sdk-dotnet#1541]
I've not succeed using PATCH to modify an extension in  an event as described here on [learn.microsoft.com](https://learn.microsoft.com/en-us/graph/extensibility-overview#update-an-existing-open-extension) ([my stackoverview threath](https://stackoverflow.com/questions/74244593/modify-value-of-an-existing-open-extension-item-in-a-calendar-event-ms-graph-ap))

So I use POST but I would expect POST would completely overwrite the extension, since PATCH do (if it worked).
Documentation of PATCH says (from above link):

> To update an open extension, you must specify all its properties in the request body. Otherwise, the unspecified properties will be updated to null and deleted from the open extension.

I see POST to be more extensive than a PATCH action, so to see POST actually preserve those unspecified properties was a surprise to me an might be a bug?

Example, current properties of an extension by name `CustomData`:
```JSON
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('2c..2f')/events('AAM..AAA%3D')/extensions/$entity",
    "@odata.type": "#microsoft.graph.openTypeExtension",
    "id": "Microsoft.OutlookServices.OpenTypeExtension.CustomData",
    "extensionName": "CustomData",
    "WebCRM-ID": "WEvent-ID",
    "WebCRM-ID2": "WEventIDxx",
    "ExtID": "Wsdfawefawefawef"
}
```

I now modify/overwrite the `WebCRM-ID`  property
```URL
POST URL: https://graph.microsoft.com/v1.0/me/events('AAM..AAA=')/extensions
```
POST json data
```JSON
{
    "@odata.type": "microsoft.graph.openTypeExtension",
    "extensionName": "CustomData",
    "WebCRM-ID": "new value :-)"
}
```
Result hereafter if I request the extension from a GET action:
```JSON
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('2c....2f')/events('AAM..AAA%3D')/extensions/$entity",
    "@odata.type": "#microsoft.graph.openTypeExtension",
    "id": "Microsoft.OutlookServices.OpenTypeExtension.CustomData",
    "extensionName": "CustomData",
    "WebCRM-ID": "new value :-)",
    "WebCRM-ID2": "WEventIDxx",
    "ExtID": "Wsdfawefawefawef"
}
```
The properties `WebCRM-ID2` and `ExtID` was preserved.

Is this as expected? Can I trust this will stay that way in the future so I can depend my code on it?

**Comment by andrueastman** [comment]
Thanks for raising this @MrM40 

As this question seems to be related to the API side of things and this repository is mainly meant to issues related to the client library, any chance you can create the same question at the link below so that the relevant API owners may give feedback on this? It would be great if you could post back the link to the same so that in future anyone who comes across this may be able to follow it.

https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-calendar.html

**Comment by MrM40** [comment]
Ahh....that make sense, I will and thanks for the link.

**Comment by MrM40** [comment]
Not an issues with the .Net API, but in the core Graph API, will close the issue, sorry for the noise.
_(but I don't think learn.microsoft.com is the right place for bug-reports, I've create a support ticket instead, we'll see)_
