### ISSUE TITLE
Accessing a driveItem give a URL?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-sdk-dotnet#1545]
According to the doco you can access a driveItem by a dozen or so URLs: https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http

How would I for example use this format to request a driveItem from the C# SDK?

e.g. I have a URL https://whatever/sites/{site-id}/drive/items/{item-id}

Can I pass this directly to the C# SDK or do I need to parse the URL and stick it into the corresponding request?

**Comment by andrueastman** [comment]
Thanks for raising this @catmanjan 

If you head over to[ the Graph Explorer](https://aka.ms/ge) and build the desired url for the call you want to make, you can check the relevant snippet in the snippet tab to help you make the desired call you wish to make with the SDK as in the image below.

![image](https://user-images.githubusercontent.com/6464005/199952029-784d3f59-c5cd-44b5-85ed-df090698ed04.png)
