### ISSUE TITLE
Event.Instances always null

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#155]
Hi,
I'm trying to schedule recurring event using the dotnet SDK (currently using v1.4).
It seems that the .Instances property of the Event object never get initialized.
See my code bellow:
```
var updatingEvent = new Event
{
     Subject = "test",
     Location = new Location { DisplayName = "Montreal" },
     IsAllDay = false,
     Start = getTimeZoneFromDateTime(DateTime.Now, tzLabel),
     End = getTimeZoneFromDateTime(DateTime.Now.AddHours(1), tzLabel),
     OnlineMeetingUrl = "someurl",
     Body = new ItemBody { Content = emailBody.HtmlBody, ContentType = BodyType.Html },
     ShowAs = FreeBusyStatus.Busy,
     Recurrence = new PatternedRecurrence
            {
                Range = new RecurrenceRange
                {
                    StartDate = new Date(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day),
                    Type = RecurrenceRangeType.Numbered,
                    NumberOfOccurrences = 3
                },
                Pattern = new RecurrencePattern
                {
                     Interval = 1,
                    Type = RecurrencePatternType.Daily
                }
            };
};
var updatedEvent = await client.Users[Settings.SkypeUserEmail].Calendar.Events.Request().AddAsync(updatingEvent);
// updateEvent.Instances -> null
```

**Comment by MIchaelMainer** [comment]
At this point, you created the master event in the service. The instances are found via a navigation property.  You will need to make another request to get this information as the navigation properties aren't returned when the event is created. So, you should have two ways to get the instances:

1) Expand the instances on the item.

```csharp
var eventWithExpandedInstances = await graphClient.Users[Settings.SkypeUserEmail]
                                                  .Calendar
                                                  .Events[updatedEvent.id]
                                                  .Request()
                                                  .Expand("instances")
                                                  .GetAsync();
```

2) Navigate to the instances

```csharp
var instancesPage = await graphClient.Users[updatedEvent.id].Calendar
                                               .Events[Settings.SkypeUserEmail]
                                               .Instances
                                               .Request()
                                               .GetAsync();
Event firstEventInstance = instancesPage[0];
```

**Comment by baywet** [comment]
Hi @MIchaelMainer thanks for the quick reply.
With the first option the `Instances` property is still null.
With the second one I get a `ErrorInvalidParameter` return code.
The event's type properly shows up as a series master, and when I use the graph explorer to craft requests manually using the `/instances` endpoint on the same event, I get a listing of the instances.

**Comment by baywet** [comment]
Furthermore, when I look at the underneath requests here is what I get
First method:
https://graph.microsoft.com:443/v1.0/users/user@tenant.onmicrosoft.com/calendar/events/EventID
Second Method:
https://graph.microsoft.com:443/v1.0/users/user@tenant.onmicrosoft.com/calendar/events/EventID/instances

No query string or additional headers or so. It looks like in both cases the request is not being properly forged.

**Comment by baywet** [comment]
`var request = graphClient.Users[Settings.SkypeUserEmail].Calendar
                                               .Events[updatedEvent.id]
                                               .Instances
                                               .Request();
request.QueryOptions.Add(new QueryOption("startDateTime", DateTime.Now.AddDays(-1).ToString("s")));
request.QueryOptions.Add(new QueryOption("endDateTime", DateTime.Now.AddDays(5).ToString("s")));
var instancesPage = await request.GetAsync();`
Works with option 2, couldn't get option 1 to work properly.
Now the question is: how can I get the recurrence end date when the pattern was set with a number of occurrences?

**Comment by MIchaelMainer** [comment]
I'm glad that you got this working. Can you post your follow up questions to StackOverflow with the microsoftgraph tag? That way more people can see the question and answer.

**Comment by baywet** [comment]
Thanks, I posted the question here: https://stackoverflow.com/questions/44886447/getting-recurrence-last-occurence-end-date-of-meeting-series-in-graph

As option 1 is not crafting the proper request, should I leave this issue open?

**Comment by cbales** [comment]
It looks like the events endpoint does not support expanding on the instances property, so you will have to use method #2.
