### ISSUE TITLE
AOT compilation of Mac Catalyst (MAUI) app fails with graph preview SDK

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1550]
**Describe the bug**
The AOT build fails for target framework `net6.0-maccatalyst` in combination with RID `maccatalyst-arm64`

`/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.4.465/targets/Xamarin.Shared.Sdk.targets(3,3): Error: Failed to AOT compile Microsoft.Graph.dll, the AOT compiler exited with code 134 (repro-aot)`

**To Reproduce**
You can reproduce with this minimal example (console app, only a nuget reference and and 2 lines of code is included)
[repro-aot.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/9944289/repro-aot.zip)

**Expected behavior**
Graph SDK should not break RID `maccatalyst-arm64` for (MAUI) apps

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 5.0.0-preview13

Looks like this has already been an issue in the past: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/333

**Comment by andrueastman** [comment]
Thanks for raising this @edoust 

We're currently investigating this via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1530. We'll close this for now as a duplicate and track this from there.

**Comment by andrueastman** [comment]
Resolved with https://github.com/xamarin/xamarin-macios/issues/16604#issuecomment-1306400619

**Comment by edoust** [comment]
@andrueastman 
This issue is not resolved, there is only a workaround, namely disabling AOT compilation completely. That is not an option for MAUI apps which need to deploy to the Apple App Store (iOS/Catalyst)
