### ISSUE TITLE
Mac Catalyst (MAUI) app sends empty request bodies when using preview SDK

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1551]
**Describe the bug**
Mac Catalyst (MAUI) apps that use v5-preview13 NuGet send out requests with empty payloads, leading to 400 Bad Request responses from the server. The same code in a .NET app on Windows produces a valid request payload

**Desktop (please complete the following information):**
 - OS: macOS [Catalyst]
 - Version 5.0-preview13

**Comment by andrueastman** [comment]
Possibly related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1530

**Comment by edoust** [comment]
This happens on x64 builds

**Comment by andrueastman** [comment]
Hey @edoust,

The change in https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/547 was verified on MacCatalyst with post requests working without issue. Any chance you share a sample repro project to help us validate the issue from our end?

**Comment by edoust** [comment]
I can make one if it helps, is the change https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/547 already part of v5.0.0-rc.3?

**Comment by andrueastman** [comment]
> I can make one if it helps, is the change [microsoftgraph/msgraph-sdk-dotnet-core#547](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/547) already part of v5.0.0-rc.3?

Yes it is.
