### ISSUE TITLE
Cannot DeserializeObject IGraphServiceDrivesCollectionPage

### ISSUE THREAD

**Issue by XzaR90** [microsoftgraph/msgraph-sdk-dotnet#156]
Cannot DeserializeObject IGraphServiceDrivesCollectionPage or GraphServiceDrivesCollectionPage on api calls site/{site-id}/drives and /drives

I have also tried ISiteDrivesCollectionPage/SiteDrivesCollectionPage.

**Comment by cbales** [comment]
You should be able to deserialize /sites/id/drives to a SiteDrivesCollectionPage and /me/drives to a UserDrivesCollectionPage.

Can you share the code you use to request these collections?

**Comment by XzaR90** [comment]
I can just share part of the code

`        public async Task<string> SendRequestAsync(string requestUrl, HttpMethod method = null, HttpContent content = null)
        {
            method = method ?? HttpMethod.Get;

            using (HttpRequestMessage hrm = new HttpRequestMessage(method, requestUrl))
            {
                if (content != null)
                {
                    hrm.Content = content;
                }

                await Instance.AuthenticationProvider.AuthenticateRequestAsync(hrm);
                using (HttpResponseMessage response = await Instance.HttpProvider.SendAsync(hrm))
                {
                    if(response.IsSuccessStatusCode)
                    {
                        return await response.Content.ReadAsStringAsync();
                    }

                    throw new ServiceException
                    (
                        new Error
                        {
                        Code = response.StatusCode.ToString(),
                        Message = await response.Content.ReadAsStringAsync()
                        }
                    );
                }
            }
        }

        public async Task<T> SendRequestAsync<T>(string requestUrl, HttpMethod method = null, HttpContent content = null)
        {
            var ret = await SendRequestAsync(requestUrl,method,content);
            return Instance.HttpProvider.Serializer.DeserializeObject<T>(ret);
        }
    }`

Where T is the model.

**Comment by cbales** [comment]
You will want to deserialize the value of the "value" key, not the entire response

Instead of
``` json 
{
  "@odata.context": "value",
  "value": ["response values"]
}
```

send in
```
["response values"]
```

**Comment by cbales** [comment]
If you're still having issues with this, feel free to reopen
