### ISSUE TITLE
[Client bug]: provide a descriptive title here

### ISSUE THREAD

**Issue by dipikaGt** [microsoftgraph/msgraph-sdk-dotnet#1561]
I'm using SDK to call graph api and recently updated the version to latest which is 4.47. The problem is when I'm calling the message api i.e below I'm getting the result, but check the below attached images the object of EvenDetail that is returning as result and the one when I'm opening the Event Detail both are different .

`var messages = await graphClient.Chats[{chat-Id}].Messages
.Request()
.GetAsync();`
![image](https://user-images.githubusercontent.com/118358990/202177584-c68e6644-7f15-4bd0-9b9b-b33811cdd19b.png)

Image 2:
![image](https://user-images.githubusercontent.com/118358990/202177666-3c6af2ad-01dd-4973-a9e1-87d52a69b965.png)

**Comment by andrueastman** [comment]
Thanks for raising this @dipikaGt,

As `EventMessageDetail` is the base of `CallRecordingEventMessageDetail` at compile time, I believe that you will run into the exception as you're trying to directly cast the base type to the child type.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d98128f77b9b029f6dda800b455b2d43db436629/src/Microsoft.Graph/Generated/model/CallRecordingEventMessageDetail.cs#L21

Any chance it works out for you when you change to using the `as` keyword?

```cs
var derivedItem = c.EventDetail as CallRecordingEventMessageDetail;
```
