### ISSUE TITLE
[Client bug]: Copy().Request().PostAsync() doesn't return a DriveItem

### ISSUE THREAD

**Issue by anhtuan1412** [microsoftgraph/msgraph-sdk-dotnet#1566]
I'm using the Graph SDK version Graph-dotnet-2.0.7. I'm trying to copy a file to a new location on a different drive (from OneDrive Business to DocumentLibrary of a SharePoint site) using

`GraphServiceClient.Drives[driveId].Items[id].Copy(parentReference: newFolder.ParentReference).Request().PostAsync();`

From the definition of this method, it should return a DriveItem; however, it returned null (the file was actually copied). Is this an expected behavior or am I using this wrong?

Here is the POST request from Fiddler
`POST /v1.0/drives/b!8lbUXtl17kWF2iwRY1Nyd8fuvmEH1X9FuV51e05FSeu-0W0AcWFZT7c-f3ZLptwO/items/01IHDDMUVPFD7RDHAE4BG3JPFU5PL2XLJH/microsoft.graph.copy`

The request payload is 
`{"parentReference":{"driveId":"b!oHD1WJrN8kmOxybEUIGekmmJly6Qz0pGnABSN6_1PiFo9dDv6P3HQZ1XnjZ7IFfe","id":"01JZVVPH6U4SABGC5MOZCKJOTEV6XIQUKF"}}`

client-request-id: 85755fad-1957-4b24-8f29-e74b4eca2f7b
request-id: 85755fad-1957-4b24-8f29-e74b4eca2f7b
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US 2","Slice":"E","Ring":"1","ScaleUnit":"000","RoleInstance":"CO1PEPF000019C2"}}

The response is 200, and the response content is empty.

**Comment by andrueastman** [comment]
Thanks for raising this @anhtuan1412 

This is expected as from the API documentation the expected response is a 202 with no content. 

https://learn.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http#response-1

Unfortunately, due to the insufficient information from the metadata that is used to generate the v4 SDK, there is a return type generated as some other APIs do sometimes have a return type therefore causing inconsistency.  We are looking to resolve this using more accurate metadata descriptions which are taken advantage of in the [preview version of the SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md).

**Comment by anhtuan1412** [comment]
@andrueastman, Thanks for the reply. I have 2 more questions
1. I just want to confirm that the correct pattern is still to read the Location for a url and pinging the url to get the completion status?
2. I also want to confirm, that in order to move an item between drives, the recommended way is still to do copy and delete? Not using a PATCH request to update the parentReference.

**Comment by alvaroyurrita** [comment]
> Thanks for raising this @anhtuan1412
> 
> This is expected as from the API documentation the expected response is a 202 with no content.
> 
> https://learn.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http#response-1
> 
> Unfortunately, due to the insufficient information from the metadata that is used to generate the v4 SDK, there is a return type generated as some other APIs do sometimes have a return type therefore causing inconsistency. We are looking to resolve this using more accurate metadata descriptions which are taken advantage of in the [preview version of the SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md).

According to the link you provided, there should be a monito ID that can be used via a plain HTTP request to monitor the status of the copy command.  The process is alluded [here](https://stackoverflow.com/a/68754886/15178420). But even in the example from that link, the result of the PostAsync is not Null, but one where headers can be queried to get the monitor ID.
