### ISSUE TITLE
LargeFileUploadTask cannot take a byte array and requires the entire file?

### ISSUE THREAD

**Issue by nikki9696** [microsoftgraph/msgraph-sdk-dotnet#1578]
I have the same issue mentioned in a comment here, to which there was no reply.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/493

"this class encapsulates all the logic of breaking the file into chunks and sending them. In my project, the backend is a WEB API (REST) that receives the chunks sent by the frontend"

I too have an API that is getting chunks sent. I have large files (500MB) that are being streamed to an API in byte array chunks. How can I leverage this class to upload chunks properly?

Right now, if I try to get an UploadSession for the file in a controller, it does not appear to get an existing one. I see no method to get an existing one. Therefore, what ends up happening is that it just writes the chunk. My 25MB file ends up as 1MB and corrupted.
CreateUploadSession always creates it, which does make sense, but there is no GetUploadSession. My controller is API and stateless.

```
private async Task<UploadResult<DriveItem>> UploadChunk(string driveId,
            string fileName,
            long fileSizeInBytes,
            byte[] fileChunkBytes)
        {
            var graphClient = _graphServiceClientFactory.GetAuthenticatedGraphClient((ClaimsIdentity)User.Identity);

            var uploadProps = new DriveItemUploadableProperties
            {
                AdditionalData = new Dictionary<string, object>
                {
                    { "@microsoft.graph.conflictBehavior", "replace" }
                }
            };

            var uploadSession = await graphClient.Drives[driveId]
                .Root
                .ItemWithPath(fileName)
                .CreateUploadSession(uploadProps)
                .Request()
                .PostAsync();


            using MemoryStream stream = new MemoryStream(fileChunkBytes);
            // Max slice size must be a multiple of 320 KiB
            int maxSliceSize = 320 * 1024;
            var fileUploadTask =
                new LargeFileUploadTask<DriveItem>(uploadSession, stream, maxSliceSize);

            var totalLength = fileSizeInBytes;
            var uploadResult = await fileUploadTask.UploadAsync();
            return uploadResult;

        }
```

An attempt to just create the session and set the url did not work and resulted in a null reference.
![image](https://user-images.githubusercontent.com/8574321/206309675-8aa44610-fd88-4875-8e44-9ede077156cc.png)

Thanks!

**Comment by nikki9696** [comment]
Is this thing on?

**Comment by nikki9696** [comment]
Two months, folks? Commenting so it doesn't get closed.

**Comment by andrueastman** [comment]
Hey @nikki9696,

Apologies for the delayed response here. 

At the moment, the `LargeFileUploadTask` receives the whole file and does the job of splitting the file into chunks which is different from what you are trying to do here. We will be looking to adding the ability to expose the chunking via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1647

In the meantime, would it be a workable solution to try out the following?

Create an API endpoint for the frontend that creates the upload session. Maybe something like below.

```cs
private async Task<UploadSession> UploadChunk(string driveId,
            string filename)
        {
            var graphClient = _graphServiceClientFactory.GetAuthenticatedGraphClient((ClaimsIdentity)User.Identity);

            var uploadProps = new DriveItemUploadableProperties
            {
                AdditionalData = new Dictionary<string, object>
                {
                    { "@microsoft.graph.conflictBehavior", "replace" }
                }
            };

            var uploadSession = await graphClient.Drives[driveId]
                .Root
                .ItemWithPath(fileName)
                .CreateUploadSession(uploadProps)
                .Request()
                .PostAsync();

          return uploadSession ;
        }
```

The front end will then then get back an object with the url for where to upload the file. 

```json
{
  "uploadUrl": "https://sn3302.up.1drv.com/up/fe6987415ace7X4e1eF866337",
  "expirationDateTime": "2015-01-29T09:21:55.523Z",
  "nextExpectedRanges": ["0-"]
}
```
As the file is already split into chunks at the front end, you can push the files chunks directly to the `uploadUrl` in the response by making PUT requests as no authentication is needed here as the url is unique to you and will eventually expire. 

You will just need to make sure the `Content-Length` and `Content-Range` headers are present an example is [here](https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#example). 

Once the chunks are fully uploaded you should get back

**Comment by nikki9696** [comment]
@andrueastman - yes, this was the workaround we chose back when I created this thread, but obviously, it's not ideal.
Thank you for the reply.

**Comment by andrueastman** [comment]
Thanks @nikki9696 

As we will be looking to adding the ability to expose the chunking via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1647, we'll close this for now and track it through there
