### ISSUE TITLE
Graph calls returning outdated data

### ISSUE THREAD

**Issue by davidortinau** [microsoftgraph/msgraph-sdk-dotnet#1579]
**Describe the bug**

I added Microsoft.Identity and Microsoft.Graph to an app using Azure AD Basic auth based on the code from https://github.com/Azure-Samples/ms-identity-dotnetcore-maui/blob/57391671cc079fc7b08d02665c74d8b38a368256/MauiAppWithBroker/MSALClient/MSGraphHelper.cs#L80

The results I get in my .NET MAUI app on Android do not reflect the correct information.

1. The display name should be David, not Dave
2. The photo is empty and throws and image not found exception, but definitely exists

**To Reproduce**

Run the sample above. Make a change using the web to your profile (new name, new photo), and then run the sample comparing results to Graph Explorer results.

**Expected behavior**

Same content, including a photo. Notice in the screenshot there is no image, and the name is "Dave" on the mobile app upper right, but should be "David".

**Screenshots**

<img width="1052" alt="Screenshot 2022-12-08 at 2 57 40 PM" src="https://user-images.githubusercontent.com/41873/206586572-942d2c6c-2b3b-4383-8901-dc878551f524.png">

**Smartphone (please complete the following information):**
 - Device: Android emulator
 - OS: API 33
 - Browser: Chrome
 - Version: API 33

Project dependencies:

```
<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Maui" Version="3.0.0" />
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0-preview1" />
	  <PackageReference Include="Microcharts" Version="0.9.5.9" />
	  <PackageReference Include="Redth.ZXing.Net.Maui" Version="0.1.0-preview.4" />
	  <PackageReference Include="SkiaSharp.Extended.UI.Maui" Version="2.0.0-preview.61" />
	  <PackageReference Include="Ril.BlazorSignatureCanvas" Version="0.1.0-alpha" />
	  <PackageReference Include="Microsoft.Identity.Client" Version="4.48.1" />
	  <PackageReference Include="MonkeyCache" Version="2.0.0-beta" />
	  <PackageReference Include="MonkeyCache.FileStore" Version="2.0.0-beta" />
	  <PackageReference Include="AlohaKit.Animations" Version="1.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
	  
	  
	  <PackageReference Include="AsyncAwaitBestPractices" Version="6.0.6" />

	  <PackageReference Include="Microsoft.Graph" Version="5.0.0-preview.14" />
	  <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="2.25.0" />
</ItemGroup>
```

**Comment by andrueastman** [comment]
Thanks for raising this @davidortinau 

Any chance you have a different experience when you change the line at the link below?
https://github.com/Azure-Samples/ms-identity-dotnetcore-maui/blob/57391671cc079fc7b08d02665c74d8b38a368256/MauiAppWithBroker/MSALClient/MSGraphHelper.cs#L129

to 

```cs
HttpClient client = GraphClientFactory.Create();
```

The `GraphClientFactory` enables you to create a client with optimized defaults such as [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/52fe3a2f75bd0c7ed83a96030850a1b53587935d/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs#L105), which may explain prevent getting cached results from the client.

**Comment by darrelmiller** [comment]
@davidortinau It shouldn't be necessary to do all that CAE claims checking as our Kiota library handles getting a auth challenge with additional claims https://github.com/microsoft/kiota-http-dotnet/blob/main/src/HttpClientRequestAdapter.cs#L429
