### ISSUE TITLE
Uploading to SharePoint not working (LargeFileUploadTask)

### ISSUE THREAD

**Issue by sveinnthorarins** [microsoftgraph/msgraph-sdk-dotnet#1580]
**Describe the bug**
File is not uploaded.
No bytes are uploaded to the upload session.
The folder is created but not the file.
The upload task finishes and `uploadResult.UploadSucceeded` boolean is true, but logs show that no bytes were written (`Uploaded 0 bytes of 56192 bytes.`).
The `uploadResult.ItemResponse` shows a full item response to the best of my knowledge (size of file correct, modified timestamp like it was modified just this instant).
This issue seems very similar to #1522.
Not sure if bug lies in Microsoft.Graph package or the Graph API itself. Or if I'm doing something completely wrong.

**To Reproduce**
```cs
    string file = "<redacted_base64_string_of_file>";
    using (var fileStream = new MemoryStream(Convert.FromBase64String(file)))
    {
        _graphClient = new GraphServiceClient(new DefaultAzureCredential());
        var uploadSession = await _graphClient.Sites["<redacted_site_id>"].Drive.Root.ItemWithPath("testfolder/testfile.pdf").CreateUploadSession().Request().PostAsync();
        var totalLength = fileStream.Length;
        IProgress<long> progress = new Progress<long>(prog =>
        {
            log.LogInformation($"Uploaded {prog} bytes of {totalLength} bytes.");
        });
        var uploadResult = await (new LargeFileUploadTask<DriveItem>(uploadSession, fileStream, 320 * 1024)).UploadAsync(progress);
    
        return new ContentResult(){
            StatusCode = 200,
            ContentType = "application/json",
            Content = JsonConvert.SerializeObject(new { message = "ok", success = uploadResult.UploadSucceeded, itemResponse = uploadResult.ItemResponse }),
        };
    }
```

**Expected behavior**
The file should be uploaded, or the operation should fail (at least with `uploadResult.UploadSucceeded` boolean equaling false, possibly also an error/exception?).

**Additional context**
The code is being run in an Azure Function App using .NET 6.0 and Microsoft.Graph NuGet package version 4.48.0.

**Comment by andrueastman** [comment]
Thanks for raising this @sveinnthorarins 

Any chance you have different results if you specify a conflict behavior as below when creating the upload session?

```cs
// Use properties to specify the conflict behavior
// in this case, replace
var uploadProps = new DriveItemUploadableProperties
{
    AdditionalData = new Dictionary<string, object>
    {
        { "@microsoft.graph.conflictBehavior", "replace" }
    }
};

// Create the upload session
// itemPath does not need to be a path to an existing item
var uploadSession = await graphClient.Me.Drive.Root
    .ItemWithPath(itemPath)
    .CreateUploadSession(uploadProps)
    .Request()
    .PostAsync();
```

**Comment by sveinnthorarins** [comment]
The problem has been identified and solved, however I have some suggestions for improvements.

The problem was that the SharePoint site had versioning enabled and thus the file needed to be "checked in" after uploading. As a result the file was not visible to me, it was only visible to the "SharePoint App" which Microsoft Graph uses to upload files.

Perhaps this process could be improved by Microsoft Graph or this library automatically "checking in" the file after uploading? Or at least allow us to enable that action through an upload prop (like the conflict behavior)?

I'd also like to suggest for this SDK library to update the progress upon finishing. I'm not sure how it behaves when there are multiple slices being uploaded, as in my case it was only a single slice, but essentially the progress callback was only called at the start and not the finish.
That is, my log looks like this for a successful upload:
```
Uploaded 0 bytes of 56192 bytes.
```
While I would want it to look like this:
```
Uploaded 0 bytes of 56192 bytes.
Uploaded 56192 bytes of 56192 bytes.
```
