### ISSUE TITLE
[Client bug]: events and calendarView missing expand in request configuration

### ISSUE THREAD

**Issue by ahweis** [microsoftgraph/msgraph-sdk-dotnet#1581]
**Describe the bug**
Using the `GraphServiceClient` to query `events` or `calendarView` it is no longer possible to set expand option as query parameters. In previous versions (e.g. `4.22.0-preview`) the query builder itself had it as an option.

The following example is from the 4.22 client that works with the `Expand()` function:

```
client
    .Users[userId]
    .CalendarView
    .Request(queryOptions)
    .Filter(filterQuery)
    .Expand(expandOptions)
    .Select(SelectQuery)
    .GetAsync()
```

The following is re-written to 5.14 where the builder is replaced with request configuration, but missing an Expand option:

```
client
    .Users[userId]
    .CalendarView
    .GetAsync(cfg =>
    {
        cfg.QueryParameters.StartDateTime = from;
        cfg.QueryParameters.EndDateTime = to;
        cfg.QueryParameters.Filter = filterQuery;
        cfg.QueryParameters.Select = SelectQuery;
    })
```

**To Reproduce**
1. Try to add filter on `calendarView` on expanding `singleValueExtendedProperties` that is part of the filter (see URL example below)

https://graph.microsoft.com/beta/me/calendarView?startDateTime=2022-12-01T00:00:00&endDateTime=2022-12-31T00:00:00&$select=id&$filter=SingleValueExtendedProperties/any(c: c/Id eq 'String {643ec2fa-e468-4b54-be8e-787c70d4a79f} Name ParentEventId' and c/Value eq 'AAMkADJjASGFxZDVmLTViNDAtNGTjOS1hZjdkLWRlMjVlNTQwYzkzOABGAAAAAADJmx9AKBiKQoBAarsrrol5BwAZTSoj4SE7Rbx0wxVE_m1BAAAAAAENAAAZTSoj4SE7Rbx0wxVE_m1BAAADk9fzAAA=')&$expand=singleValueExtendedProperties($filter=id eq 'String {543ec2fa-e468-4b54-be8e-787c70d4a79f} Name ParentEventId')

**Expected behavior**
The clients request configuration on `events` and `calendarView` should support expand options.

**Client version**
Microsoft.Graph.Beta/5.14.0-preview

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by andrueastman** [comment]
Thanks for raising this @ahweis,

This will need to be fixed in the metadata as the metadata is disabling the `Expand` restrictions as below. 
![image](https://user-images.githubusercontent.com/6464005/207321139-e6354d9d-0010-4b01-ab52-48c507127104.png)


At the moment you maybe able to work around this as below as the metadata is resolved.

```cs
            var requestInfo = graphServiceClient
                .Users["user-id"]
                .CalendarView
                .CreateGetRequestInformation(cfg =>
                {
                    cfg.QueryParameters.StartDateTime = "EndDateTime";
                    cfg.QueryParameters.EndDateTime = "EndDateTime";
                    cfg.QueryParameters.Filter = "Filter";
                    cfg.QueryParameters.Select = new string[] { "select" };
                });

            requestInfo.UrlTemplate = requestInfo.UrlTemplate[..^1] + ",%24expand}";
            requestInfo.PathParameters.Add("%24expand", "expandQuery");

            var result = await graphServiceClient.RequestAdapter.SendAsync<EventCollectionResponse>(requestInfo, EventCollectionResponse.CreateFromDiscriminatorValue);
```
