### ISSUE TITLE
Graph API SDK Users endpoints not obeying retry policy with retry-after header returned from graph response.

### ISSUE THREAD

**Issue by bolt-io** [microsoftgraph/msgraph-sdk-dotnet#1589]
**Describe the bug**
When using .NET SDK, Microsoft.Graph.GraphServiceClient for Azure AD B2C tenants, the Graph API User requests are not adhering to the retry functionality.

**To Reproduce**

**Expected behavior**
A retry policy is in place for the .NET SDK as described in documentation and by Microsoft Support.

**Screenshots**
This is the initial wrapper around the SDK, where everything up to GetAsync() is using the underlying SDK (image attached further down).
![image](https://user-images.githubusercontent.com/10209663/208623983-b8257ae5-148a-41c5-aec9-19c2eea16d19.png)

Here is the UserFieldSelection from above.
![image](https://user-images.githubusercontent.com/10209663/208624073-80294bfb-914a-4921-848f-4482ec7f610d.png)

And the underlying SDK request builder:
![image](https://user-images.githubusercontent.com/10209663/208624096-d2d1dd68-07f3-4e04-8c95-6e5a70a7e796.png)

And finally, initialisation:
![image](https://user-images.githubusercontent.com/10209663/208624162-cb8314f6-9fc0-49a6-a5fe-3b93f5f4207f.png)

As depicted in the application insights, this call was only attempted once, even though the request got a 429 with a retry-after header:
![image](https://user-images.githubusercontent.com/10209663/208626017-35c515cc-d486-4c73-ac58-df126d6c5897.png)
I would expect to see multiple Graph API calls

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device:  N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

<PackageReference Include="Microsoft.Graph.Beta" Version="4.49.0-preview" />

Microsoft Support Ticket: #2211100050000634 for more info/context

**Comment by andrueastman** [comment]
This may be related to the httpClient timing out before the retry has chance to happen. Resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/591

@bolt-io Any chance you are able to replicate this after updating to the latest version of the SDK?
