### ISSUE TITLE
Creating AD group with length greater than 120 chars

### ISSUE THREAD

**Issue by aloysiustany** [microsoftgraph/msgraph-sdk-dotnet#159]
When I call _activeDirectoryClient.Groups.AddGroupAsync(group) where group's displayname is larger than 120 char, it throws the following exception:

Microsoft.Data.OData.ODataErrorException: Unsupported or invalid query filter clause specified for property 'displayName' of resource 'Group'. ---> System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: {"odata.error":{"code":"Request_UnsupportedQuery","message":{"lang":"en","value":"Unsupported or invalid query filter clause specified for property 'displayName' of resource 'Group'."}}} at System.Data.Services.Client.BaseAsyncResult.EndExecute[T](Object source, String method, IAsyncResult asyncResult) at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)

**Comment by cbales** [comment]
This looks like it might be an issue with AAD Graph, not Microsoft Graph: https://www.nuget.org/packages/Microsoft.Azure.ActiveDirectory.GraphClient/

Could you verify which package you are using?

**Comment by aloysiustany** [comment]
@cbales yes I am using AAD Graph client. Should I post this elsewhere ?

**Comment by cbales** [comment]
This is not the repository for the AAD Graph client. Unfortunately, I don't believe the AAD Graph repo is open sourced. Your best bet is to ask a question on StackOverflow and tag [azure-ad-graph-api](https://stackoverflow.com/questions/tagged/azure-ad-graph-api)

**Comment by aloysiustany** [comment]
Thanks.. Posted it [here](https://stackoverflow.com/questions/45042392/aad-graph-client-creating-ad-group-with-length-greater-than-120-chars).
