### ISSUE TITLE
The colon (":") is not added after siteRelativePath in .Sites.GetByPath()

### ISSUE THREAD

**Issue by lgiuliani80** [microsoftgraph/msgraph-sdk-dotnet#1592]
**Describe the bug**
Request based on a .Sites.GetByPath() with extra segments added after the GetByPath() [e.g. Drives, Lists, ...] are ill formed, so they fail if executed.  
The reason for that is that the ":" is NOT appended after the siteRelativePath, before the extra segments of the path.

**To Reproduce**

```csharp
var drives = await graphClient.Sites.GetByPath("/sites/MySite", "mytenant.sharepoint.com")
    .Drives
    .Request()
    .GetAsync();
```

**Expected behavior**
Extra segments should work as expected.

**Current behaviour**

    https://graph.microsoft.com/v1.0/sites/mytenant.sharepoint.com:/sites/MySite/drives

is requested instead of:

    https://graph.microsoft.com/v1.0/sites/mytenant.sharepoint.com:/sites/MySite:/drives

**Workaround**

```csharp
var drives = await graphClient.Sites.GetByPath("/sites/MySite:", "mytenant.sharepoint.com")
    .Drives
    .Request()
    .GetAsync();
```

**Comment by andrueastman** [comment]
Hey @lgiuliani80,

Thanks for raising this. Any chance you could confirm the version of the SDK with which you're experiencing this?

**Comment by lgiuliani80** [comment]
Microsoft.Graph v. 4.49.0
Microsoft.Graph.Core v. 2.0.14

**Comment by andrueastman** [comment]
Closing this for now as V4 is no longer getting fixes and workaround provided.
