### ISSUE TITLE
Cannot assign a manager to a user

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/msgraph-sdk-dotnet#16]
Please see https://stackoverflow.com/questions/36937093/assign-a-manager-using-microsoft-graph-net-client-library.  Looks like AddAsync() method is missing for manager:
`graphClient.Users[newUser.Id].Manager.Reference.Request().AddAsync(manager);`

It looks like we do have AddAsync() and DeleteAsync() for DirectReports - however that is not supported through the actual REST API.  Org hierarchy updates can ONLY be done through the Manager link.

BTW: Should double check that the same issue is not present in the other platform libraries.

**Comment by kevklam** [comment]
These are code generation issues, I'll open an issue in the appropriate repo.

**Comment by shiftylogic** [comment]
We are also in the process of implementing annotation support which should
solve this problem assuming the service annotations are correct.

--
Robert
