### ISSUE TITLE
Does not have option to retrieve metadata for any entity like User etc.

### ISSUE THREAD

**Issue by NitinWabale** [microsoftgraph/msgraph-sdk-dotnet#160]
we might need to something similar to https://graph.microsoft.com/v1.0/$metadata

**Comment by cbales** [comment]
Could you clarify what type of metadata you are looking for and the scenario you might use this?

Are you looking for metadata about the response made to Graph, or metadata about the properties that exist on an entity?

**Comment by NitinWabale** [comment]
Looking for thr metadata about the properties that exist on an entity.
e.g <EntityType Name="user" BaseType="microsoft.graph.directoryObject" OpenType="true">
        <Property Name="accountEnabled" Type="Edm.Boolean" />
        <Property Name="assignedLicenses" Type="Collection(microsoft.graph.assignedLicense)" Nullable="false" />
        <Property Name="assignedPlans" Type="Collection(microsoft.graph.assignedPlan)" Nullable="false" />
        <Property Name="businessPhones" Type="Collection(Edm.String)" Nullable="false" Unicode="false" />
        <Property Name="city" Type="Edm.String" Unicode="false" />
        <Property Name="companyName" Type="Edm.String" Unicode="false" />
        <Property Name="country" Type="Edm.String" Unicode="false" />
        <Property Name="department" Type="Edm.String" Unicode="false" />
        <Property Name="displayName" Type="Edm.String" Unicode="false" />
        <Property Name="givenName" Type="Edm.String" Unicode="false" />
        <Property Name="imAddresses" Type="Collection(Edm.String)" Unicode="false" />
        <Property Name="jobTitle" Type="Edm.String" Unicode="false" />
        <Property Name="mail" Type="Edm.String" Unicode="false" />
        <Property Name="mailNickname" Type="Edm.String" Unicode="false" />

**Comment by cbales** [comment]
All properties should be visible through Intellisense. Is there a scenario that you need this for?

**Comment by NitinWabale** [comment]
Yes, scenario is like get all fields of any Entity as service call and use that fields for CRUD of any Entity.

**Comment by cbales** [comment]
Could you use reflection to grab the methods of the type?
```csharp
Type type = (typeof(User));
var methods = type.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
```
Of course, then you would have to filter out the getters.

**Comment by cbales** [comment]
If you're still having issues with this, please reopen
