### ISSUE TITLE
(5.0.0-preview.14) Unable to add Chaos Handler

### ISSUE THREAD

**Issue by eduardomb08** [microsoftgraph/msgraph-sdk-dotnet#1601]
**Describe the bug**

I am evaluating the changes in for .Net SDK v5 and can’t figure out how to customize the behavior to add a ChaosHandler while still using a auth provider. Before, the GraphClientFactory.CreateDefaultHandlers method used to take the auth provider as a parameter and add a AuthenticationHandler, but that was removed in this [commit](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmsgraph-sdk-dotnet-core%2Fcommit%2F167f7801fbbd653c44f1444efd9c04104386ac9d%23diff-db67ef1996ec654dda09f590d1cf8559f2bf32163f7521aa10c75008c63ea2c1&data=05%7C01%7CBrian.Jackett%40microsoft.com%7Cb4aa64f1cf434202e94308dae9c71d69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638079338680162658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t3odN41ilZcSAt7nNOaLaEivaKFh2AJa%2FbHVipylT84%3D&reserved=0). And in order to get a GraphServiceClient instance that uses a customized list of DelegatingHandlers I need to use the constructor that takes in the HttpClient instance and not the one taking the auth provider.

The idea is to achieve the same as described in the article [How to use the Microsoft Graph SDK Chaos Handler to Simulate Graph API Errors](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcamerondwyer.com%2F2021%2F09%2F23%2Fhow-to-use-the-microsoft-graph-sdk-chaos-handler-to-simulate-graph-api-errors%2F&data=05%7C01%7CBrian.Jackett%40microsoft.com%7Cb4aa64f1cf434202e94308dae9c71d69%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638079338680162658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HX5Aw8ytQV0QFM0DSrDJUvQ5tvijiLrqNyQwyoNu5VQ%3D&reserved=0) using the new version of the SDK.

**Expected behavior**

Ability to introduce chaos.

**Desktop (please complete the following information):**
 - OS: Win 10 Version 21H2 (OS Build 19044.2251)
 - Browser Chrome Version 107.0.5304.123 (Official Build) (64-bit)

**Comment by andrueastman** [comment]
Thanks for raising this @eduardomb08,

As Authentication is no longer done in the http middleware pipeline, you should be able to achieve the same with the code below. 

```cs
var httpClient = GraphClientFactory.Create(handlers);
var authProvider = new AzureIdentityAuthenticationProvider(tokenCredential);
var requestAdapter = new HttpClientRequestAdapter(authProvider, httpClient: httpClient);// create token credential and requestAdapter
var graphClient = new GraphServiceClient(requestAdapter);// Then we construct the Graph Service Client using the requestAdapter
```

To close this issue, we will update the `GraphServiceClient` constructor to also take in an optional `IAuthenticationProvider` with the `HttpClient` to make this easier to achieve as shown below.

```cs
var httpClient = GraphClientFactory.Create(handlers);
var authProvider = new AzureIdentityAuthenticationProvider(tokenCredential); // create authProvider
var graphClient = new GraphServiceClient(httpClient, authProvider);// Then we construct the Graph Service Client using the HTTPClient and authprovider
```

**Comment by eduardomb08** [comment]
Thanks a lot, @andrueastman ! Will test that out and get back with comments if I have any troubles.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1611
