### ISSUE TITLE
[Microsoft.Graph 4.49.0] - Exception when reading "scheduleInfo" of "RoleEligibilitySchedule"

### ISSUE THREAD

**Issue by stefanboerner** [microsoftgraph/msgraph-sdk-dotnet#1603]
**Describe the bug**
The following exception is thrown when requesting the "scheduleInfo" property of a single "unifiedRoleEligibilitySchedule" using $select:

```
System.Text.Json.JsonReaderException: 
''{' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 0 | BytePositionInLine: 684.'
```

**To Reproduce**
```
var schedule = graphClient.RoleManagement.Directory.RoleEligibilitySchedules["<id>"].Request()
	.Select("scheduleInfo")
	.GetAsync()
	.Result;
```

**Expected behavior**
The schedule object with the ID <guid> is returned along with the scheduleInfo property

**Used libraries/environment:**

- .NET Framework 4.8
- Microsoft.Graph 4.49.0
- Microsoft.Graph.Core 2.0.14
- System.Text.JSon 6.0.6
- API Endpoint: 1.0

**Additional context**
To investigate the problem, I tried to run the call in the Graph Explorer

When retrieving the **list** of schedules and explicitly selecting "scheduleInfo", the call works:
`https://graph.microsoft.com/v1.0/roleManagement/directory/roleEligibilitySchedules?$select=scheduleInfo`

When trying to GET a **single** schedule by providing the guid, the call fails with 
**"400 - Bad Request"**
`https://graph.microsoft.com/v1.0/roleManagement/directory/roleEligibilitySchedules/<guid>?$select=scheduleInfo`

**Comment by andrueastman** [comment]
Thanks for raising this @stefanboerner,

Any chance you are able to extract the string response that causes the error and share it so that we can validate?

```cs
var schedule = await graphServiceClient.RoleManagement.Directory.RoleEligibilitySchedules["<id>"].Request()
    .Select("scheduleInfo")
    .GetResponseAsync();

var stringContents = await schedule.Content.ReadAsStringAsync();
```

**Comment by stefanboerner** [comment]
Sure, here is the result:

`{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#roleManagement/directory/roleEligibilitySchedules(id,scheduleInfo)/$entity","@odata.type":"#microsoft.graph.unifiedRoleAssignmentSchedule","id":"9d0a3cca-8b5c-4cc5-b92b-21ad9f6ae40d"{"error":{"code":"InternalServerError","message":"The type 'microsoft.graph.unifiedRoleAssignmentSchedule' does not inherit from and is not a base type of 'microsoft.graph.unifiedRoleEligibilitySchedule'. The type of 'KeySegments' must be related to the Type of the EntitySet.","innerError":{"date":"2023-01-05T06:38:07","request-id":"a8cf3291-6c45-44d5-9d65-cafd514c65c5","client-request-id":"a8cf3291-6c45-44d5-9d65-cafd514c65c5"}}}`

**Comment by andrueastman** [comment]
Thanks for this. The response from the API does look to be invalid json pointing to a API bug.

Any chance you can confirm the status response code you receive as well to help feedback to the relevant API team?

```cs
var statusCode = schedule.StatusCode;
```

**Comment by stefanboerner** [comment]
The StatusCode is "OK" 

[...] StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent [...]

**Comment by andrueastman** [comment]
Raised issue [here](https://portal.microsofticm.com/imp/v3/incidents/details/358789164/home)

**Comment by stefanboerner** [comment]
Does this issue here gets updated once this is resolved (cannot access the the link)
https://portal.microsofticm.com/imp/v3/incidents/details/358789164/home

**Comment by andrueastman** [comment]
Hey @stefanboerner,
We'll post an update once the service team gives an update on this front.

**Comment by andrueastman** [comment]
The service team confirms that this had been fixed from their end and update rolled out. 

We'll therefore close this for now.
