### ISSUE TITLE
[v5.0] invalid odata cast allowed by the SDK

### ISSUE THREAD

**Issue by Licantrop0** [microsoftgraph/msgraph-sdk-dotnet#1604]
these two lines of code:

`_graphClient.Groups[id].MemberOf.User.GetAsync();`
`_graphClient.Groups[id].TransitiveMemberOf.User.GetAsync();`

should throw a compile-time error because a `User` cannot be a member of a `Group`.

**Comment by andrueastman** [comment]
Resolved with https://github.com/microsoftgraph/msgraph-metadata/pull/286
