### ISSUE TITLE
The telemetry configuration should not include v1 for the v1 service lib

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#1609]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/345701690d81571b661db1aecc781af37a44f74d/src/Microsoft.Graph/GraphServiceClient.cs#L27

As counter intuitive as it sounds, we're not including v1 for the v1 service lib. Only beta for beta.

https://github.com/microsoftgraph/msgraph-sdk-go/blob/767c30e984b3fec03e6e5ca11b4c68c6db935249/graph_request_adapter.go#L12

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1611
