### ISSUE TITLE
[Client bug]: GraphServiceClient.Application doesn't support Request extension

### ISSUE THREAD

**Issue by Amritanand25** [microsoftgraph/msgraph-sdk-dotnet#1615]
**Describe the bug**
As per the following documentation -> https://learn.microsoft.com/en-us/graph/api/application-list?view=graph-rest-beta&tabs=csharp beta version should support a `Request` extension but it doesn't.

**To Reproduce**
1. Install Microsoft.Graph.Beta - version 5.11.0-preview
2. Trying to utilize `await graphClient.Applications.Request` shows Request as invalid extension

**Client version**
Microsoft.Graph.Beta - version 5.11.0-preview

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser - NA

**Comment by andrueastman** [comment]
Thanks for raising this @Amritanand25,

As you have pulled version 5 of the SDK, please check out the upgrade guide available at the link below. https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#removal-of-request-from-the-fluent-api

The documentation at the moment shows snippets  for version 4.x.x of the SDK and the snippets in the documentation will be updated once the new version is in GA.

**Comment by shyamal890** [comment]
Hi @andrueastman we are trying to utilize `application (client) id` to fetch the application instead of using `object id`. 

This [documentation](https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-beta&tabs=csharp) doesn't share enough information on how it can be achieved through C# beta sdk.

This is the reason why we were trying to utilize list to filter out applications based on `client id`

**Comment by andrueastman** [comment]
Hey @shyamal890,

I believe the example at the link below show how to use `Filter`,

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#query-options

So that you may be able to something like

```cs
        var applicationCollectionResponse = await graphClient.Applications.GetAsync(requestConfiguration =>
        {
            requestConfiguration.QueryParameters.Select = new[] { "id", "displayName" };// set select
            requestConfiguration.QueryParameters.Filter = "startswith(displayName, 'al')";// set filter for applications with displayName starting with 'al'
            requestConfiguration.QueryParameters.Count = true;
            requestConfiguration.Headers.Add("ConsistencyLevel","eventual");//set the header
        });
```

**Comment by Amritanand25** [comment]
@andrueastman we tried utilizing `requestConfiguration.QueryParameters.Filter` but `QueryParameters` doesn't support `Filter` extension. 

We even tried utilizing `requestConfiguration.QueryParameters.Search="appId:xxxxxx"` but that too is giving error saying ":" is not supported.

**Comment by andrueastman** [comment]
Hey @Amritanand25,

Any chance you could share the exact API you're trying to call? From my end, I am able to use `requestConfiguration.QueryParameters.Filter` when calling the `graphClient.Applications.GetAsync()`

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/cf2281b9c6bdc1044135360d322fcfde1a93df3d/src/Microsoft.Graph/Generated/Applications/ApplicationsRequestBuilder.cs#L167
