### ISSUE TITLE
[Client bug]: Update EmailAuthenticationMethod error 

### ISSUE THREAD

**Issue by s-summers** [microsoftgraph/msgraph-sdk-dotnet#1616]
**Describe the bug**
I was converting a project from `Microsoft.Graph.Beta v4.51.0-preview` to `Microsoft.Graph v4.50.0` where I came across an issue
with updating a user's authentication email method.

```
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll ("Code: badRequest
Message: Unable to parse request body as an authentication method.
```

**To Reproduce**
Running the following as per the [v1 docs](https://learn.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-1.0&tabs=csharp)
```cs
var newEmailAuth = new EmailAuthenticationMethod
{
    EmailAddress = email
};

await client
    .Users[user.Id] // User
    .Authentication
    .EmailMethods[emailAuthMethod.Id] // EmailAuthenticationMethod
    .Request()
    .UpdateAsync(newEmailAuth);
```

**Expected behavior**
To update the Email Authentication Method without error

**Client version**
Microsoft.Graph v4.50.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
After much searching without any luck I checked the [upgrade-to-v4](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#bug-fixes) guide to see if something had changed. I found that setting `ODataType = null` had been used as a workaround and gave that a go which correctly updated the email.

```cs
var newEmailAuth = new EmailAuthenticationMethod
{
    EmailAddress = email,
    ODataType = null
};
```

Original code in Beta version was using `.PutAsync` which was changed to `.UpdateAsync` since `PUT` request was not supported.

**Comment by Bletch1971** [comment]
Any update on this issue?
This issue still persists in the latest v5 SDK and would be nice to fix, as v5 does not allow the workaround mentioned above.

**Comment by andrueastman** [comment]
Hey @Bletch1971 

Just to confirm, does this mean that this does not work for you in V5?

```cs
            var newEmailAuth = new EmailAuthenticationMethod
            {
                EmailAddress = "email-address",
                OdataType = null
            };

            await graphClient
                .Users["user-id"] // User
                .Authentication
                .EmailMethods["method-id"] // EmailAuthenticationMethod
                .PatchAsync(newEmailAuth);
```

**Comment by Bletch1971** [comment]
@andrueastman 
Yes what you have above does not work in V5

**When using** 
`            var newEmailAuth = new EmailAuthenticationMethod
            {
                EmailAddress = "email-address"
            };

            await graphClient
                .Users["user-id"] // User
                .Authentication
                .EmailMethods["method-id"] // EmailAuthenticationMethod
                .PatchAsync(newEmailAuth);`

**This is the error**
Exception Message: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
Exception Error.Code: badRequest
Exception Error.Message: Unable to parse request body as an authentication method.


**When using** 
`            var newEmailAuth = new EmailAuthenticationMethod
            {
                EmailAddress = "email-address",
                OdataType = null
            };

            await graphClient
                .Users["user-id"] // User
                .Authentication
                .EmailMethods["method-id"] // EmailAuthenticationMethod
                .PatchAsync(newEmailAuth);`

**This is the error**
Exception Message:       Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
Exception Error.Code:    BadRequest
Exception Error.Message: The request is malformed or incorrect: expected a string for ODataType value.

**Comment by ErikdeWilde** [comment]
I have the same problem, the only way I got this to work is to get the ToPatchRequestInformation and post an anonymous object with a lowercase "emailAddress" property. 

Dictionary<string, ParsableFactory<IParsable>> errorMappings = new() {
                    { "4XX", Microsoft.Graph.Models.ODataErrors.ODataError.CreateFromDiscriminatorValue },
                    { "5XX", Microsoft.Graph.Models.ODataErrors.ODataError.CreateFromDiscriminatorValue }
                };

var newEmailAuth = new {
  emailAddress = "email-addres", // Works only with lowercase e
};

var request =  graphClient
.Users["user-id"]
.Authentication
.EmailMethods["method-id"]
.ToPatchRequestInformation(new Microsoft.Graph.Models.EmailAuthenticationMethod());

request.Content = new MemoryStream(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(newEmailAuth)));

var result = await graphClient.RequestAdapter.SendAsync(request, Microsoft.Graph.Models.EmailAuthenticationMethod.CreateFromDiscriminatorValue, errorMappings);


With the TemporaryAccessAuthentication method I had to use the same construction because something went wrong with the datetimeoffset serialization of the startdatetime property

**Comment by peereflits** [comment]
Using `Microsoft.Graph` library version 5.13.0 I have the same problem.
The solution by @ErikdeWilde worked for me.

**Comment by Harttech** [comment]
Is there still no solution to this, other than that workaround? I still have this error on version 5.28.0.

```csharp
await client.Users[upn].Authentication.EmailMethods[emailMethod.Id].PatchAsync(new EmailAuthenticationMethod
{
    EmailAddress = newMailAddress
});
```
