### ISSUE TITLE
FindMeetingTimes Gap

### ISSUE THREAD

**Issue by aowens430** [microsoftgraph/msgraph-sdk-dotnet#162]
Hopefully I'm not the only one having this issues. When I request meeting time suggestions, which includes an attendee and time constraints, I get a response of 5 meeting suggestions. The issues is, that the slots have a gap in time, some times several hours. However, all attendees have that time as free; additionally, if I change the duration or increment the time one direction or another, the missing time slots show up. On a related note, is there a way to request more than 5 meeting time suggestions?

**Comment by cbales** [comment]
This looks like an issue with the FindMeetingTimes service, not the library itself. Could you post this on StackOverflow with the tag [microsoftgraph]? This will allow the relevant engineers to follow up with you.
