### ISSUE TITLE
[Client bug]: SDK is missing option to provide $format QueryOption

### ISSUE THREAD

**Issue by sopelt** [microsoftgraph/msgraph-sdk-dotnet#1621]
**Describe the bug**
The Graph API provides a way to retrieve the binary content of a sharepoint drive item while converting its type (e.g. from docx to pdf, or other options when using beta instead of 1.0) as documented [here](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=http#query-parameters).
The current Microsoft Graph rc does not seem to provide any way of providing a format. I suspect the generated `ContentRequestBuilderGetRequestConfiguration` should have `QueryParameters.Format` to set that.

**To Reproduce**
`await GraphServiceClient.Drives[drive.Id].Items[item.Id].Content.GetAsync()`

**Expected behavior**
`await GraphServiceClient.Drives[drive.Id].Items[item.Id].Content.GetAsync(c => c.QueryParameters.Format = "PDF")`

**Client version**
Microsoft.Graph/5.0.0-rc.2

**Desktop (please complete the following information):**
Win 11

**Additional context**
In the 4.x SDK such parameters seem to have been available to manually add as `Microsoft.Graph.QueryOption` but that seems to have gone away in 5.x (core 3.x)

**Comment by Arash-Sabet** [comment]
@andrueastman Any updates on this issue? This is a roadblock for the document conversion application we have.

**Comment by Arash-Sabet** [comment]
@sopelt I tried the following approach but the converted/downloaded PDF File did not seem to have a right format. Acrobat reader failed to open the file after saving the content's stream:

```cs
var requestBuilder = graphClient
   .DirectoryObjects
   .ToGetRequestInformation(config => config.QueryParameters.Filter = "format=pdf");
var pdfStream = await graphClient.Drives[drive.Id].Items[item.Id].Content.GetAsync(c => c.Options = requestBuilder.RequestOptions.ToList(), cancellationToken);
```

Please feel free to try to see if you can make it work and keep me posted. Thanks.

**Comment by Arash-Sabet** [comment]
@andrueastman Thanks. Any ETA on when a permanent fix will be rolled out?

**Comment by erikmf12** [comment]
This is pretty substantial functionality to leave out of this new version. Any idea as to when this will be implemented correctly?

**Comment by mkoehlerstb** [comment]
Any updates on @erikmf12's last update?  I am seeing the same error:

> The server returned an unexpected status code and no error factory is registered for this code: 406

It seems he is using .NET 7.  My code is .NET 6

I have narrowed it down to Excel files that are "large"  So far I have narrowed the range to work at 6.21MB and lower and confirmed to fail at 12.89 MB or larger.  Where the cutoff is between the two sizes is something we are working on.

**Comment by erikmf12** [comment]
@mkoehlerstb My issue was due to the PDF conversion is limited to 250 pages. This means that if the PDF generated is over 250 pages it returns this error. I didn't find this initially since I was working with a template and the data being provided by the template was out of my control.

**Comment by mkoehlerstb** [comment]
@erikmf12 Thank you!  You probably just pulled days of work off my plate.

**Comment by nor0x** [comment]
> Any updates on @erikmf12's last update? I am seeing the same error:
> 
> > The server returned an unexpected status code and no error factory is registered for this code: 406
> 
> It seems he is using .NET 7. My code is .NET 6
> 
> I have narrowed it down to Excel files that are "large" So far I have narrowed the range to work at 6.21MB and lower and confirmed to fail at 12.89 MB or larger. Where the cutoff is between the two sizes is something we are working on.

Any updates on this issue?
I'm seeing the same issue with the code from @erikmf12 no exotic documents on my side here - I'm testing with a 10 page .docx and 10 page .pptx file


the following code works for me if the document is already in PDF format - so no conversion is happening.

> @sopelt I tried the following approach but the converted/downloaded PDF File did not seem to have a right format _(I renamed the file's extension to docx and MS Word was able to open it)_. Acrobat reader failed to open the file after saving the content's stream:
> 
> ```cs
> var requestBuilder = graphClient
>    .DirectoryObjects
>    .ToGetRequestInformation(config => config.QueryParameters.Filter = "format=pdf");
> var pdfStream = await graphClient.Drives[drive.Id].Items[item.Id].Content.GetAsync(c => c.Options = requestBuilder.RequestOptions.ToList(), cancellationToken);
> ```
> 
> Even using the filter like `config.QueryParameters.Filter ="format eq 'pdf'"` or `config.QueryParameters.Filter ="format eq pdf"` was not conclusive. Please feel free to try to see if you can make it work and keep me posted. Thanks.
> 
> /cc @andrueastman

**Comment by raeesgillani** [comment]
@andrueastman any updates on this since?

I am using:

`//Stream stream = await client.Drives[siteDriveId].Root.ItemWithPath(filePath).Content.GetAsync();
            RequestInformation requestInformation = client.Drives[siteDriveId].Root.ItemWithPath(filePath).Content.ToGetRequestInformation();
            requestInformation.UrlTemplate += "{?format}";
            requestInformation.QueryParameters.Add("format", "pdf");
            Stream stream = await client.RequestAdapter.SendPrimitiveAsync<Stream>(requestInformation);`

However, conversion is only working on one very small docx file (84.6KB), does not seem to work for pdf(628KB) to pdf, nor xlsx(438KB) to pdf.
