### ISSUE TITLE
Batch Request breaking change in v5.0.0-rc.2

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1622]
This method call does not work anymore:
`Microsoft.Graph.BatchRequest.AddBatchRequestStep(RequestInformation)`

Is there a workaround apart from creating the `HttpRequestMessage` manually?

**Comment by andrueastman** [comment]
Thanks for raising this @edoust 

You should still be able to do the same as outlined in the [guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#batch-requests). The change was brought about by the method changing to be an async method. 

```cs
var requestStepId = await batchRequestContent.AddBatchRequestStepAsync(requestInformation);
```
