### ISSUE TITLE
DirectoryRole Delta The requested media type is not supported

### ISSUE THREAD

**Issue by naama11** [microsoftgraph/msgraph-sdk-dotnet#1624]
Hi 
Using msGraph client to call directory roles delta I'm getting the following error:
The requested media type is not supported. The allowed values are json with minimalmetadata

_graphServiceClient.
                    DirectoryRoles.
                    Delta().
                    Request(options) 

I do manage to call Users delta, Groups delta with same version.

tried using Microsoft.Graph 4.51.0
and using Microsoft.Graph.Beta 4.52.0  
both fail.
from msgraph explorer I manage to call this API on v1.0. fail on beta with error on delta token not provided. 

Any suggestions for solution?

**To Reproduce**
1. use Microsft graph client to call PPE graph directory roles delta API. code written in c#.
here is the API called: "https://graph.microsoft-ppe.com:443/beta/directoryRoles/microsoft.graph.delta()"
2. error: The requested media type is not supported. The allowed values are json with minimalmetadata
3. add headers for "Prefer", "return=minimal", "Content-type", "application/json"
4. same error occur.
5. try calling v1.0 API. same error occur
6. groups delta, users delta APIs work as expected

**Expected behavior**
get directory roles delta data

**Comment by andrueastman** [comment]
Hey @naama11 

Any chance you can confirm if this error still persists if you do not target the PPE environment?

**Comment by naama11** [comment]
I can't because my app has to work with PPE. I have test tenant in this env

**Comment by naama11** [comment]
I can also mention that when accessing this API via PPE msGraph explorer (https://graphexplorerbetappe2.azurewebsites.net/#) in beta version:
https://graph.microsoft-ppe.com/beta/directoryroles/delta
 I get this error:
 "code": "Request_UnsupportedQuery",
        "message": "Unsupported query parameter(s). deltaLink is required.",
                "innerError": {
            "date": "2023-01-24T08:50:42",
            "request-id": "09e7c4db-8007-4720-8efb-a671b81471d4",
            "client-request-id": "09e7c4db-8007-4720-8efb-a671b81471d4"
        }

but when accessing v1.0 it works fine
https://graph.microsoft-ppe.com/v1.0/directoryroles/delta

**Comment by andrueastman** [comment]
https://portal.microsofticm.com/imp/v3/incidents/details/362655015/home raised for the relevant API team to follow up.

**Comment by naama11** [comment]
any update? currently in PPE using beta api version users few APIs don't work: users delta, directory roles delta.
it does work in v1.0.
But v1.0 is missing properties when calling users/<user_id> API. so seems we still need beta version

**Comment by andrueastman** [comment]
Closing this as the relevant API team confirms that this has now been fixed/resolved.
