### ISSUE TITLE
Generic paging made too hard compared to AAD Graph Client

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#163]
Previously in AAD we had the following (eg): IPagedCollection&lt;IUser&gt;
Now, we have (eg): IGraphServiceUsersCollectionPage
Problem: NextPageRequest sits directly on this interface, not on a base interface (and it itself is an interface that has all "interesting" methods et al on itself not a parent). 
Previously, we could write a generic method taking IPagedCollection&lt;T&gt; and nicely page/retry/log/time us through all collections that existed. Now, we have to make do with a nasty factory method approach for getFirst, hasNext, getNext. 
Would be nice to get the old / similar to old class hierarchy back.

**Comment by cbales** [comment]
This is great feedback. I'll put it in our backlog. We try to avoid introducing breaking changes unless absolutely necessary. This may have to wait until we are ready to ship a v2

**Comment by peombwa** [comment]
This is now supported in #423 .
