### ISSUE TITLE
Missing Post method for /drive/bundles

### ISSUE THREAD

**Issue by mitchcapper** [microsoftgraph/msgraph-sdk-dotnet#1630]
**Describe the bug**
Similar to #1524 

To add  a new bundle one needs to do:
```csharp
var new_bundle = new DriveItem {
	Name = bundle_name,
	Bundle = new Bundle(),
	Children = items.Select(i=>new DriveItem { Id=i.Id}).ToList(),
	AdditionalData = new Dictionary<string, object>() { { "@microsoft.graph.conflictBehavior", "rename" } }

};
var getInfo = graphClient.Drive.Bundles.ToGetRequestInformation();
getInfo.HttpMethod = Microsoft.Kiota.Abstractions.Method.POST;
getInfo.SetContentFromParsable(graphClient.RequestAdapter, "application/json", new_bundle);
var res = await graphClient.RequestAdapter.SendAsync<Bundle>(getInfo, factory: Bundle.CreateFromDiscriminatorValue);
```

Additionally with the new auto-magic backing store and auto-gen methods things that seem like they should work don't.  I don't know if this is a bug or needs more documentation but passing existing DriveItems to the Children list will fail.   It will just submit empty objects for the children `{}`.  Taking the drive items and creating new ones like above does fix.   

Another minor note, the Children object comment on DriveItem says read only which clearly not for posts:)

**Expected behavior**
`graphClient.Drive.Bundle.Post` exist to mirror the public api.

**Comment by andrueastman** [comment]
Resolved with https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1630 and should be available in next update
