### ISSUE TITLE
[Client bug]: BaseRequest and HttpProvider don't deal with 404 NotFound 

### ISSUE THREAD

**Issue by SharePointRadi** [microsoftgraph/msgraph-sdk-dotnet#1633]
**Describe the bug**
The implementation of the NotFound code is not working as you would typically expect from a dotnet SDK library.

The following request call doesn't give the developer the option to "check" if the non-existent user exists without going through a ServiceException.

```await _graphClient.Users["fake@user.com"].Request().GetAsync();```

Even if you work with the response, it still throws:
```
var request = _graphClient.Users["fake@user.com"].Request();
var result = await request.GetResponseAsync(cancellationToken);
```
The reason why it does that is in the HttpProvider implementation:

![image](https://user-images.githubusercontent.com/5693618/216767169-bd695632-ee26-4ede-8599-0e042db25d0f.png)

errorResponse.Error *is not* null, it contains a response message and code for the IUserRequest.

**To Reproduce**
To reproduce, try to check if a user exists and handle a NotFound response without causing a runtime exception.

**Expected behavior**
My expectation is for the Microsoft Graph dotnet library team to not throw exceptions when they can be avoided, just like the dotnet colleagues suggest: https://learn.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions

GetResponseAsync equivalents should give the developer the option to gracefully deal with an error codes if they choose to. 

The library does not provide the ability to issue a HEAD request either.

In my case, I am retrieving a user and I want to handle cases when the user doesn't exist without exceptions. It is recommended that exceptions are not used for expected scenarios.

**Client version**
4.52.0

**Desktop (please complete the following information):**

**Comment by jungjanos** [comment]
Bump.
Any updates on this? I strugle with the exact same issue.

**Comment by Koenocta** [comment]
This issue is still very much present in version 5. I need to wrap the calls in order to not crash on a 404. Also interesting side note. Why is the steam on the photo nullable if the client crashes on a 404? 

```
          try
            {
                using Stream? photoStream = await _gsClient.Me.Photo.Content.GetAsync();
                pbyte = photoStream == null ? [] : ((MemoryStream)photoStream).ToArray();
            }
            catch (ODataError e)
            {
                //do nothing, prevent the server from crashing on a 404
            }
            catch (Exception e)
            {
                throw;
            }
```
