### ISSUE TITLE
Unable to Read Bulk Emails with Expand Attachments filters Using Microsoft Graph API

### ISSUE THREAD

**Issue by v2mounish** [microsoftgraph/msgraph-sdk-dotnet#1634]
Description:

we are unable to Read bulk emails and we are getting the error below.

Reference Document Links:

https://learn.microsoft.com/en-us/training/modules/optimize-network-traffic/

Installed Packages are:

1) NuGet\Install-Package Microsoft.Identity.Client -Version 4.49.1
2) NuGet\Install-Package Microsoft.Graph -Version 4.50.0
3) NuGet\Install-Package Microsoft.Extensions.Configuration -Version 7.0.0
4) NuGet\Install-Package Microsoft.Extensions.Configuration.FileExtensions -Version 7.0.0
5) NuGet\Install-Package Microsoft.Extensions.Configuration.Json -Version 7.0.0

Error Message :

RailySend Email Failed. Send Email Failed One or more errors occurred.  Status Code: NotFound
Microsoft.Graph.ServiceException: Code: ErrorItemNotFound
Message: The specified object was not found in the store., Cannot create a message.
Inner error:
      AdditionalData:
      date: 2023-01-17T13:46:39
      request-id: 69a0f44c-ff5e-49b7-a618-048261f0c47a
      client-request-id: 69a0f44c-ff5e-49b7-a618-048261f0c47a
ClientRequestId: 69a0f44c-ff5e-49b7-a618-048261f0c47a

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__33.MoveNext()

Permission:

**Comment by andrueastman** [comment]
Thanks for raising this @v2mounish,

This looks to be 404 from the service suggesting that you are trying to access something that does not exist. Any chance you can share the snippet of the line of code that throws the error? This will help us understand if the request being made is structured incorrectly

**Comment by v2mounish** [comment]
No Its Not 404 Exception as per Microsoft API Teams told us we can read only 1000 emails per request.

when we use the ExpandAttachments its taking very long time.

Here is the sample code

 var inboxMessages = await graphClient
                                    .Users[emailRequest.ClientUserName]
                                    .MailFolders[mailFolder[a].DisplayName]
                                    .Messages
                                    .Request()
                                    //.Expand("attachments")
                                    .Top(1000).OrderBy("receivedDateTime asc")
                                    .GetAsync();

**Comment by andrueastman** [comment]
Hey @v2mounish,

> RailySend Email Failed. Send Email Failed One or more errors occurred.  Status Code: NotFound
Microsoft.Graph.ServiceException: Code: ErrorItemNotFound
Message: The specified object was not found in the store., Cannot create a message.
Inner error:
      AdditionalData:
      date: 2023-01-17T13:46:39
      request-id: 69a0f44c-ff5e-49b7-a618-048261f0c47a
      client-request-id: 69a0f44c-ff5e-49b7-a618-048261f0c47a
ClientRequestId: 69a0f44c-ff5e-49b7-a618-048261f0c47a

The error shared above suggests a 404 error and suggests a send mail operation. Any chance you mean this works out for you now?

**Comment by v2mounish** [comment]
Hi ,

I would like to reopen this issues because the issues is still exist as same as mention above.

**Comment by andrueastman** [comment]
Tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1775
