### ISSUE TITLE
Microsoft Graph OneDrive for business - create file fails(UnauthorizedAccessException) for AppOnly accessToken

### ISSUE THREAD

**Issue by brucewangkorea** [microsoftgraph/msgraph-sdk-dotnet#164]
as the Title suggests, I tried creating a file by calling Microsoft Graph API and it fails with 'Access Denied'. The access token is retrieved from the service by calling this [API.](https://developer.microsoft.com/en-us/graph/docs/authorization/app_only#use-the-access-token-in-a-request-to-the-microsoft-graph-api)

Can list files, download files, create a folder, but can not upload a file with this accessToken. The Azure App itself has all access permissions. The operation success when I use [the ordinary way](https://dev.onedrive.com/auth/aad_oauth.htm), using web-login. And with proper setting for the collection Admin.

Only couple of months ago the AppOnly token couldn't even download a file, so it's still under improvement, right? Do you have a plan to support this in near future, or is there any way to accomplish this with only an AppOnly token?

Thanks in advance.

**Comment by cbales** [comment]
This is a feature that the OneDrive team dictates. This would be a great question for StackOverflow, with the tags [microsoftgraph] and [onedrive]

**Comment by brucewangkorea** [comment]
Hi,
but the failure comes from this Graph API
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/item_createuploadsession

**Comment by cbales** [comment]
I should clarify my answer. The feature is on Graph but is a bug at the API level, not the SDK level. The OneDrive team works on submitting their APIs to Graph and should have insights on what is supported iwth the app-only flow.

**Comment by brucewangkorea** [comment]
Thanks!,
