### ISSUE TITLE
Regression on GraphServiceUsersCollectionResponse not using @odata.nextLink with link to the next page

### ISSUE THREAD

**Issue by rjardines** [microsoftgraph/msgraph-sdk-dotnet#1641]
I found that after upgrading to version 4.19, there was no more @odata.nextLink in the AdditionalData property of the class GraphServiceUsersCollectionResponse, even when the NextPageRequest had an instance to the next page.

I found a [commit ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/commit/834549348081869cc4b97d9ead6dbbf12a516264?diff=split) that introduced the property: 
`[JsonPropertyName("@odata.nextLink")]
public string NextLink { get; set; }`

Capturing the `odata.nextLink` in the above property removes it from:
`[JsonExtensionData]
public IDictionary<string, object> AdditionalData { get; set; }`

Did you guys miss this from the Release Notes?, or am I missing something?

Thanks in advance

**Comment by andrueastman** [comment]
Thanks for raising this @rjardines,

This is one of the breaking changes that occurred when updating from version 3.x.x to 4.x.x as the pulling of the nextLink is now done by the serailizer. 

We shall update [the documentation](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md) to capture this before closing this.
