### ISSUE TITLE
[Client bug]: C# Graph API - Get Site returns incorrect 'name' (vs graph explorer result)

### ISSUE THREAD

**Issue by dsiswadi** [microsoftgraph/msgraph-sdk-dotnet#1645]
**Describe the bug**
My application tries to return details of a Sharepoint Online site via C# .NET MS Graph API. Compared with Graph explorer the result especially on 'name' property is different. Name property in Graph explorer returns Sharepoint's 'internal name' whereas Name property in C# .NET returns Sharepoint's 'display name'.

**To Reproduce**
Prerequisites: 

- an active Sharepoint Online site
- The site has different display name and internal name for this bug purpose.

1. Go to Graph Explorer with sufficient Sites.Read.All
2. Select GET and V1. Type on API request field: https://graph.microsoft.com/v1.0/sites/{site-id}, replace {site-id} with known site id on your sharepoint end. 
3. Click 'Run query'
4. See result, the name and display name should be different as shown in (Screenshot A)
5. With C# , a fragment of code as following to show site Name and Display name for bug purpose
6. 
```
public async Task<string[]> ListSitesAsync()
        {
            var sites = await _graphServiceClient.Sites.Request().GetAsync();
            var allSites = new List<string>();
            allSites.AddRange(sites.CurrentPage.Select(site => 
                $"Name: {site.Name} , DisplayName: {site.DisplayName}, Id: {site.Id}, eTag {site.ETag}"));

            while (sites.NextPageRequest != null)
            {
                sites = await sites.NextPageRequest.GetAsync();
                allSites.AddRange(sites.CurrentPage.Select(site => 
                    $"Name: {site.Name} , DisplayName: {site.DisplayName}, Id: {site.Id}, eTag: {site.ETag}"));
            }

            return allSites.ToArray();
        }
```
7. When I run this C# code, the result is 'Name' and 'Display Name' have the same result.  Shown in (Screenshot B)

**Expected behavior**
Site.Name should display Sharepoint '_internal name_' as displayed in Graph API explorer's '_Name_' (this is the bug).
SIte.DisplayName should display Sharepoint '_display name_'  as displayed in Graph API explorer's '_Display Name_' (already correct)

**Screenshots**
Screenshot A: 
![graph-explorer-result](https://user-images.githubusercontent.com/1132972/219521927-03863ddb-3c0a-4221-a124-092249550a31.PNG)

Screenshot B:
![image](https://user-images.githubusercontent.com/1132972/219523352-dcbe9e93-1090-47be-9f74-c85e20e712c7.png)

**Client version**
Provide the client version number from the NuGet package.
 - Microsoft.Graph v.4.54.0
 - Microsoft.Graph.Core v.2.0.15
 - Microsoft.Identity.Client v.4.49.1
 - Microsoft.IdentityModel.Abstractions v.6.27
 - Microsoft.IdentityModel.JsonWebTokens v.6.27
 - Microsoft.IdentityModel.Tokens v.6.27
 - Azure.Core v.1.28
 - Azure Identity v.1.8.2
 - Microsoft.Bcl.AsynInterfaces v.7.0.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome running Graph API Explorer
 - Visual Studio Professional 2022
 - C# .NET app: .NET 4.8 Framework

**Additional context**
If there is workaround to get internal name via C#, I'd like to hear it.

**Comment by andrueastman** [comment]
Thanks for raising this @dsiswadi,

Out of curiosity, do you still get a different result if you call the same api called on graph explorer as below? 
Currently the C# code calls `https://graph.microsoft.com/v1.0/sites/` when the graph explorer example calls `https://graph.microsoft.com/v1.0/sites/{site-id}`

```cs
var site = await graphServiceClient.Sites["site-id"].Request().GetAsync();
Console.WriteLine($"Name: {site.Name} , DisplayName: {site.DisplayName}, Id: {site.Id}, eTag {site.ETag}");
```

**Comment by dsiswadi** [comment]
@andrueastman apology for delayed answer (australian time). I tested the code that similar to yours, basically retrieve the individual site with site-id, Name and Display Name are correct respectively. So, more returning all sites which is crucial in my code to compare internal name.
 
![image](https://user-images.githubusercontent.com/1132972/220224687-f3de500c-00ca-46a2-a9db-8b4960e4f6f3.png)

**Comment by andrueastman** [comment]
Thanks for the feedback here, this sounds like the API is returning inconsistent results for the API that lists the data vs the API for getting the individual site. 

If you can, are you able to pull the request id from the request id for listing the request as below and share so that we can follow up with the relevant API team? 
To do this make the request on Graph Explorer to `https://graph.microsoft.com/v1.0/sites/` and find the paged result with incorrect information, then simply share the screenshot/data on the `Response Header` tab. If you can, please also share the same when making the request for `https://graph.microsoft.com/v1.0/sites/{site-id}` that shows different results.

**Comment by dsiswadi** [comment]
@andrueastman hmmm, Graph Explorer seems not able to return all sites, not sure why
![image](https://user-images.githubusercontent.com/1132972/220839200-23ca52cd-b888-4561-9e43-fd393583a00b.png)

but correction on your previous reply, the one that incorrect is on C# code returning all sites.

**Comment by andrueastman** [comment]
Apologies for the delayed response @dsiswadi 

By any chance are you able to list the sites when you add the root domain as follows?

'''http
https://graph.microsoft.com/v1.0/sites?$select=siteCollection,webUrl&$filter=siteCollection/root%20ne%20null
```

https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0#example

**Comment by dsiswadi** [comment]
> Apologies for the delayed response @dsiswadi
> 
> By any chance are you able to list the sites when you add the root domain as follows?
> 
> '''http https://graph.microsoft.com/v1.0/sites?$select=siteCollection,webUrl&$filter=siteCollection/root%20ne%20null
> 
> ```
> 
> https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0#example
> ```

This is also return zero sites.

**Comment by andrueastman** [comment]
Hey @dsiswadi,

As the GraphExplorer route is giving trouble. Any chance you can update your code to as below so that we can obtain the raw response string of the data when making the collection request?

```cs
            var sitesResponse = await graphClient.Sites.Request().GetResponseAsync();

            var responseString = await sitesResponse.Content.ReadAsStringAsync();
            Console.WriteLine(responseString);
            var site = graphClient.HttpProvider.Serializer.DeserializeObject<GraphServiceSitesCollectionResponse>(responseString);
```
