### ISSUE TITLE
Property SharedWith of PlannerPlan always returns an empty result

### ISSUE THREAD

**Issue by alena-zhuk** [microsoftgraph/msgraph-sdk-dotnet#1646]
**Describe the bug**
Property SharedWith of PlannerPlan always returns an empty result. However AdditionalData contains all users.

**To Reproduce**
1. Get Plans for a group
2. Check enumerate SharedWith property (.ToList() for example)

**Expected behavior**
The property returns users ids

**Comment by andrueastman** [comment]
Thanks for raising this @alena-zhuk,

Any chance you could share the version of the SDK you are using to replicate this as well as a code sample of the executed request to help us understand this issue better?
