### ISSUE TITLE
[Client bug]: V4.54 requires System.Text.Json V7!

### ISSUE THREAD

**Issue by BartRennes** [microsoftgraph/msgraph-sdk-dotnet#1649]
Hi,

Using Microsoft.Graph NuGets, from a WPF .NET6 project, to update from 4.52 to latest version 4.54, my surprise was that the System.Text.Json is now in V7, which means using dotnet 7, even if all the project is using dotnet 6.
Do you think to rollback or it will not change and we have to use .NET 7?

Thank you,
Jean

**Comment by andrueastman** [comment]
Thanks for raising this @BartRennes 

I believe the targeted nuget package targets `netstandard2.0` according to the targeted frameworks
https://www.nuget.org/packages/System.Text.Json#supportedframeworks-body-tab. This means you should be able to use it in .NET 6 and netframework environments without issue.

Any chance you are running into challenges that you could provide more details with?

**Comment by BartRennes** [comment]
Thank you for your answer, i tested and it doesn't work without the application.deps.json file, basically this application is a distributed wpf app, so the application.deps.json is not distributed and it worked fine till it uses the v7.
I don't think i will be the only one to have this problem as it is a breaking change.
Thank you.

**Comment by tanieee28** [comment]
Hi, 
I am too facing this issue while using it in Azure Functions. should I downgrade the version for a workaround?

Error I am getting:
```
Exception has occurred: CLR/System.IO.FileNotFoundException
An exception of type 'System.IO.FileNotFoundException' occurred in Microsoft.Graph.Core.dll but was not handled in user code: 'Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'
   at Microsoft.Graph.Serializer..ctor()
   at Microsoft.Graph.BaseClient..ctor(String baseUrl, IAuthenticationProvider authenticationProvider, IHttpProvider httpProvider)
   at Microsoft.Graph.GraphServiceClient..ctor(String baseUrl, IAuthenticationProvider authenticationProvider, IHttpProvider httpProvider)
   at Microsoft.Graph.GraphServiceClient..ctor(IAuthenticationProvider authenticationProvider, IHttpProvider httpProvider)
```

**Comment by userr2232** [comment]
I am facing the same problem even though I have System.Text.Json 7.0.1

`
``
◢ | Exception | Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.Graph.Core.dll ("Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.") | System.IO.FileNotFoundException
```

**Comment by userr2232** [comment]
@tanieee28 I downgraded Microsoft.Graph to 4.53.0 and Microsoft.Graph.Core to 2.0.14 as a workaround.

**Comment by andrueastman** [comment]
This is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1670 as well.

We won't be making updates to the v4 of the SDK and the workaround would be to stick to 4.53.0 or upgrade to V5 of the SDK as there are only metadata updates between 4.53.0 and 4.54.0.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1643/files
