### ISSUE TITLE
Access to Response Headers

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#165]
Haven't seen anything on the response objects or GraphServiceClient itself (or HttpProvider for that matter) that would allow me to get at response headers, especially client-request-id and request-id (ie for reporting issues on requests, opening support cases). Am I missing the obvious, or is this not supported atm?

**Comment by cbales** [comment]
Response headers are available on the ServiceException class, as added in #102 
Are you looking for headers for successful calls?

**Comment by christophwille** [comment]
Yes, successful calls (should have mentioned that, because, yes ServiceException has this information)

**Comment by cbales** [comment]
In the meantime, you can use Fiddler to grab the header information for reporting the issue.

**Comment by christophwille** [comment]
That (Fiddler) works in dev, but not in prod. And I am more concerned with the latter for issues we do not see in dev.

**Comment by peombwa** [comment]
This is now supported via AdditionalData and we will soon wrap all responses in a response object.
