### ISSUE TITLE
Not able to SingleValueExtendedProperties to email message

### ISSUE THREAD

**Issue by mtryambake** [microsoftgraph/msgraph-sdk-dotnet#1654]
Not able to SingleValueExtendedProperties to email message

Code sample as below 

        private async Task UpdateMessage(GraphServiceClient graphClient, string email)
        {
            string g = Guid.NewGuid().ToString();
            var p = new SingleValueLegacyExtendedProperty
            {
                Id = "String " + "{" + g + "} " + "Name " + "MyId",
                Value = "Test"
            };
            Dictionary<string, object> additionalData = new Dictionary<string, object>();
            additionalData.Add("123", "Welcome");
           var messages = await graphClient.Users[email].MailFolders.Inbox.Messages.Request().Top(1).GetAsync();
            foreach (var message in messages)
            {
                var id = message.Id;
                try
                {
                    var extendedValueCollection = new MessageSingleValueExtendedPropertiesCollectionPage { p };
                    message.SingleValueExtendedProperties = extendedValueCollection;
                    await graphClient.Users[email].Messages[id].Request().UpdateAsync(message);
                }
                catch (Exception ex)
                {
                    var error = ex.Message;
                }
            }
        }
Error 
Code: ErrorInvalidPropertySet
Message: Set action is invalid for property.

Please suggest

**Comment by andrueastman** [comment]
Thanks for raising this @mtryambake 

Any chance you can share the version of the SDK you are using?

Are you also able to share the string contents when you do this so that we can confirm the json payload is as expected?

```cs
var jsonString = graphClient.HttpProvider.Serializer.SerializeObject(message);
```
