### ISSUE TITLE
LINQ Support for Filter

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#166]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/50 added support for Select/Expand. Is there anything planned for Filter? (we use .Where extensively in AAD Graph) 
[AB#7336](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7336)

**Comment by cbales** [comment]
Yes, we need to add support for all query options exposed through Graph. In the meantime, you can add a [custom option](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md#custom-query-options) in your request.

**Comment by christophwille** [comment]
Maybe a slight misunderstanding: the .Filter method is there already, but it only takes strings whereas in comparison .Select takes a lambda already.

**Comment by cbales** [comment]
Thanks for the clarification

**Comment by maisarissi** [comment]
Hi @christophwille 

With the new v5 version, we are now modifying all query parameters by using request configuration object.
You can find more information here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#query-options

Closing this.
