### ISSUE TITLE
Question: Trying out v5. How do I upgrade `DelegateAuthenticationProvider` with `AuthenticationHeaderValue` code to v5?

### ISSUE THREAD

**Issue by myokeeh** [microsoftgraph/msgraph-sdk-dotnet#1666]
Using this guide: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md

How do I upgrade `DelegateAuthenticationProvider` with `AuthenticationHeaderValue` code to v5? This is an access token that I obtain from MSAL.

```
                var clientddd = new GraphServiceClient(new DelegateAuthenticationProvider(
                            async request =>
                            {
                                request.Headers.Authorization =
                                  new AuthenticationHeaderValue("bearer", msalar.AccessToken);
                                await Task.CompletedTask;
                            }));
                return (await clientddd.Me.Request().GetAsync()).DisplayName;
```

I know I have to make the following changes:

- `DelegateAuthenticationProvider` -> `BaseBearerTokenAuthenticationProvider`
- Remove `Request()`

**Comment by andrueastman** [comment]
Thanks for raising this @myokeeh 

The `BaseBearerTokenAuthenticationProvider` automatically adds the token as `AuthenticationHeaderValue` instance with the bearer. All you need to do is create an `IAccessTokenProvider` as below that returns `msalar.AccessToken` in your case and it will be appended to the header.

```cs
public class TokenProvider : IAccessTokenProvider
{
    public Task<string> GetAuthorizationTokenAsync(Uri uri, Dictionary<string, object> additionalAuthenticationContext = default,
        CancellationToken cancellationToken = default)
    {
        var token = "token";
        // get the token and return it in your own way
        return Task.FromResult(token);
    }

    public AllowedHostsValidator AllowedHostsValidator { get; }
}
```

**Comment by myokeeh** [comment]
@andrueastman tried it out and getting this now:

```
'BackgroundTasks.TokenProvider' implements interface 'Microsoft.Kiota.Abstractions.Authentication.IAccessTokenProvider', which is not a Windows Runtime interface.  All interfaces that are implemented by exported types must be Windows Runtime interfaces.

```

**Comment by andrueastman** [comment]
Hey @myokeeh,

Any chance you can share the target runtime and enviroment that you are using to replicate this error?

**Comment by myokeeh** [comment]
@andrueastman, UWP (target W11, version 22H2, min W10, version 2004)

Visual Studio 2022 v17.5.1

**Comment by andrueastman** [comment]
Thanks for the extra info @myokeeh,
Out of curiosity are you also able to share a sample repro app that replicates this error to aid with investigating the error further?

**Comment by myokeeh** [comment]
[TokenRefreshBackgroundTask.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/10878869/TokenRefreshBackgroundTask.zip)

**Comment by andrueastman** [comment]
Hey @myokeeh,

Any chance you have any luck if you change the access modifier of the TokenProvider class from `public` to `internal`?

```cs
internal class TokenProvider : IAccessTokenProvider
```
Making the class public in this scenario implies the class is an exported type causing the error when building WinRT component.

**Comment by myokeeh** [comment]
@andrueastman. That got it building again. Although, I'm running into a different issue now. I'll file a new issue if needed.

Thanks for the help.
