### ISSUE TITLE
Any suggestion on Mocking for the new Fluent Objects in v5

### ISSUE THREAD

**Issue by MrKnapp** [microsoftgraph/msgraph-sdk-dotnet#1667]
I'm planing to upgrade to v5, but there is a problem with my Unit-tests.
In v4, all members in the Fluent object-tree was Interfaces, which made it posible to use Mock.Setup to mock the return of members like *.Messages.AddAsync(Message m). 
Any sugestions on Mocking-frameworks that can solve this?
I looked at Pose, but it is well out of development. 
Or should I use a different approach, to unit-test my MSGraph-Api classes?

**Comment by andrueastman** [comment]
Thanks for raising this @MrKnapp 

With regards to making such calls, its best to mock the IRequestAdapter interface that all the request builders now use.

An example test would look something like the one at the link below.


https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/7a2be45d2cf37f18a32cc9a60d0edf441fd23a08/tests/Microsoft.Graph.DotnetCore.Test/Requests/Generated/EntityCollectionRequestTests.cs#L83

```cs
        /// <summary>
        /// Tests the AddAsync() method on an entity collection request.
        /// </summary>
        [Fact]
        public async System.Threading.Tasks.Task AddAsync()
        {
            var mockRequestAdapter = new Mock<IRequestAdapter>();
            var graphServiceClient = new GraphServiceClient(mockRequestAdapter.Object);
            
            var addedCalendar = new Calendar();
            
            mockRequestAdapter.Setup(
                adapter => adapter.SendAsync(It.IsAny<RequestInformation>(),Calendar.CreateFromDiscriminatorValue, It.IsAny<Dictionary<string, ParsableFactory<IParsable>>>(),It.IsAny<CancellationToken>() )
            ).ReturnsAsync(addedCalendar);
            
            mockRequestAdapter.Setup(
                adapter => adapter.SerializationWriterFactory.GetSerializationWriter(It.IsAny<string>())
            ).Returns(new JsonSerializationWriter());
            
            var returnedCalendar = await graphServiceClient.Me.Calendars.PostAsync(addedCalendar);
            

            Assert.Equal(addedCalendar, returnedCalendar);
        }
```

**Comment by MrKnapp** [comment]
Great, that solved it.
Thanks.
