### ISSUE TITLE
When upgrading to v5, IGraphServiceUsersCollectionPage is missing and not deprecation notice found

### ISSUE THREAD

**Issue by OzBob** [microsoftgraph/msgraph-sdk-dotnet#1668]
**Describe the bug**
When upgrading the azure MS Graph samples to v5, there is no clear guidance on where the IGraphServiceUsersCollectionPage interface has moved to or been replaced by, in the v5 of the msgraph-sdk-dotnet

**To Reproduce**
https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/issues/150
1. clone 
2. upgrade nuget
3. build

**Expected behavior**
Expect no build errors.
On (line 141)[https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/blob/master/1-Call-MSGraph/daemon-console/Program.cs#L141] the attempt to get the count of Users fails to build.

**Comment by OzBob** [comment]
some guidance is provided in the (upgrade to v5 doc)[https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/7a2be45d2cf37f18a32cc9a60d0edf441fd23a08/docs/upgrade-to-v5.md]

**Comment by andrueastman** [comment]
Thanks for raising this @OzBob,

As mentioned, V5 of the SDK has a number of breaking changes that have been outlined in the guide at the link below which includes changes in the handling of collection responses. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md

```cs
var usersResponse = await graphServiceClient
    .Users
    .GetAsync();

Console.WriteLine($"Found {usersResponse.Value.Count()} users in the tenant"); 
```

We'll close this for now as the sample will be updated once the Identity library also adds support for V5.
