### ISSUE TITLE
Do we know when the conditionalAccessApplications resource's applicationFilter property will be available in the SDK?

### ISSUE THREAD

**Issue by merill** [microsoftgraph/msgraph-sdk-dotnet#1669]
The Graph REST API has an [applicationFilter](https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessfilter?view=graph-rest-beta) property for [conditionalAccessApplications](https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessapplications?view=graph-rest-beta) however this is not yet available in the .net SDK.

Do we know when it might be available? tx

**Comment by andrueastman** [comment]
Thanks for raising this @merill,

The property is not present in the metadata we use to generate from the SDK.
![image](https://user-images.githubusercontent.com/6464005/222644146-8bcab755-8861-40f5-ba39-7f5cf87068f7.png)

Any chance you can confirm that the property is currently returned from the API using [the Graph Explorer](https://aka.ms/ge) when calling the API?
