### ISSUE TITLE
Consideration for different cloud.

### ISSUE THREAD

**Issue by brucewangkorea** [microsoftgraph/msgraph-sdk-dotnet#167]
Hi,
one of my customer is running on GermanCloud.
So the Graph service endpoint url is different.
I tried pass different baseURL for 'GraphServiceClient()' constructor, but it fails.

can you please check this, and can you please share a sample code if it works?

Thanks in advance.

**Comment by cbales** [comment]
You should be able to set the base URL like so:
```csharp
graphClient.BaseUrl = "https://microsoft.com/";
```

or in the constructor:

```csharp
graphClient = new GraphServiceClient("https://microsoft.com/", AuthProvider);
```

If this is not working for you, could you provide a code snippet? What is the failure you are seeing?

**Comment by brucewangkorea** [comment]
Thanks,

`class AuthenticationProvider :  Microsoft.Graph.IAuthenticationProvider
{
  string sAzureAuthUrl = azure_authurl;
  string sAzureGraphUrl = azure_business_graphul;
  string _tenantname = "";
  string _clientid = "";
  string _clientsecret = "";
  public AuthenticationProvider(string tenantName, string clientId, string clientSecret)
  {
      _tenantname = tenantName;
      _clientid = clientId;
      _clientsecret = clientSecret;
  }
  public async Task AuthenticateRequestAsync(HttpRequestMessage request)
  {
      AuthenticationContext authContext = new AuthenticationContext(sAzureAuthUrl + _tenantname);
      ClientCredential creds = new ClientCredential(_clientid, _clientsecret);

      AuthenticationResult authResult = await authContext.AcquireTokenAsync(sAzureGraphUrl, creds);
      request.Headers.Add("Authorization", "Bearer " + authResult.AccessToken);
      //TODO check token validity
  }
}

public class GraphProvider
{
  static GraphServiceClient graphClient;

  /// <summary>
  /// Gets microsoft graph client object
  /// </summary>
  /// <param name="outGraphClient"></param>
  public static GraphServiceClient GetGraphServiceClient(string tenantName, string clientId, string clientSecret)
  {
      if (null == graphClient)
      {
          string strbaseurl = azure_business_graphul + "/currentServiceVersion";
          graphClient = new GraphServiceClient(strbaseurl, new AuthenticationProvider(tenantName, clientId, clientSecret));
      }

      return graphClient;
  }
}

public async Task<bool> GetAllGroups(string tenantName, string clientId, string clientSecret, cbGroupInfoRecieved callback = null)
{
  try
  {
      GraphServiceClient graphClient = GraphProvider.GetGraphServiceClient(tenantName, clientId, clientSecret);
      IGraphServiceGroupsCollectionPage pageOfGroups = await graphClient.Groups.Request().GetAsync();
      callGroupInfoRecievedCallback(pageOfGroups, callback);
      while (null != pageOfGroups.NextPageRequest)
      {
          pageOfGroups = await pageOfGroups.NextPageRequest.GetAsync();
          callGroupInfoRecievedCallback(pageOfGroups, callback);
      }
  }
  catch (ServiceException ex)
  {
      Console.WriteLine(ex.ToString());
      Logger.logMsg("GetAllGroups", ex.ToString());
      return false;
  }
  return true;
}`

**Comment by cbales** [comment]
I see. The URL you are using is for Azure's sovereign cloud for Germany. Unfortunately, Graph has not yet onboarded to this sovereign deployment yet. You can follow the progress on that [here](https://developer.microsoft.com/en-us/graph/docs/concepts/deployments) and submit a UserVoice request [here](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback).

**Comment by MIchaelMainer** [comment]
@dkershaw10, do you have information about accessing the German deployment?

**Comment by brucewangkorea** [comment]
Dear @cbales , 
can you give time line for the plan?
Not sure but I heard China cloud seems working, is China cloud and German cloud different?

Thanks

**Comment by cbales** [comment]
Yes, each cloud is handled a little bit differently. I do not have a timeline, but I know that it is currently being worked on.

**Comment by brucewangkorea** [comment]
Dear @cbales ,
It seems the API is finally deployed to German Cloud, but I still get the 'Bad request' response.
https://developer.microsoft.com/en-us/graph/docs/concepts/deployments

Do I have to physically on the German network?

Thanks.

**Comment by cbales** [comment]
Let me look into the specifics and get back to you on this.

**Comment by brucewangkorea** [comment]
This works,
closing the issue.
`
string strbaseurl = <sovereign cloud graph url> + "/v1.0";
graphClient = new GraphServiceClient(strbaseurl, new AuthenticationProvider(tenantName, clientId, clientSecret));
`

**Comment by paule96** [comment]
Hi @lockelost,

I have some trouble with your code in the german cloud. I must modify some peaces. Here are my solution:

The AuthenticationProvider class: 
```csharp
    class AuthenticationProvider : Microsoft.Graph.IAuthenticationProvider
    {
        private string sAzureAuthUrl = AzureEnvironment.AzureGermanCloud.AuthenticationEndpoint;
        private string sAzureGraphUrl = AzureEnvironment.AzureGermanCloud.GraphEndpoint;
        private string tenantId;
        private string _clientid;
        private string _clientsecret;

        public string GraphVersion = "1.6";
        public AuthenticationProvider(string tenantId, string ClientId, string ClientSecret)
        {
            this.tenantId = tenantId;
            _clientid = ClientId;
            _clientsecret = ClientSecret;
        }
        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            AuthenticationContext authContext = new AuthenticationContext(sAzureAuthUrl + tenantId);
            ClientCredential creds = new ClientCredential(_clientid, _clientsecret);
            AuthenticationResult authResult = await authContext.AcquireTokenAsync(sAzureGraphUrl, creds);
            request.Headers.Add("Authorization", "Bearer " + authResult.AccessToken);
            request.RequestUri = setVersionNumber(request.RequestUri);
        }

        private Uri setVersionNumber(Uri requestUri)
        {            
            if (requestUri.Query != null && requestUri.Query.Length > 1)
                return new Uri(getUriWithoutQuery(requestUri) + requestUri.Query + "&" + $"api-version={GraphVersion}");
            else
                return new Uri(getUriWithoutQuery(requestUri) + $"?api-version={GraphVersion}");
        }

        private string getUriWithoutQuery(Uri requestUri)
        {
            return requestUri.Scheme + "://" + requestUri.Host + ":" + requestUri.Port + requestUri.AbsolutePath;
        }
    }
```

And if you want use this you can simple do this:

```csharp
var graphClient = new GraphServiceClient(AzureEnvironment.AzureGermanCloud.GraphEndpoint + tenantId, 
                new AuthenticationProvider(
                    tenantId,
                    clientId,
                    clientSecret));

```
