### ISSUE TITLE
Cannot expand attachments for messages. There is no Expand property

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet#1672]
Cannot expand attachments for messages. There is no Expand property

```
var messagesResponse = await _client.Me.Messages.GetAsync(x=>
{
    x.QueryParameters.Select = new string[] { "id", "createdDateTime" };
    x.QueryParameters.Expand = new string[] { "attachments" };
});
```

@andrueastman

_Originally posted by @MartinM85 in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1290#issuecomment-1451378308_

**Comment by stukalin** [comment]
Same goes for `graphServiceClient.Users[User].Events[EventId].GetAsync()`. 

Just wondering whether there is any workaround? Like doing the `.ToGetRequestInformation()` then adjusting query parameters and then.... what?

**Comment by stukalin** [comment]
found a temp workaround for this one
```
        // obtain the request information to call the API manually later
        var getRequestInformation = graphServiceClient.Users[User].Events[EventId].ToGetRequestInformation();
        // use a custom class to define the parameter
        getRequestInformation.AddQueryParameters(
            new QueryParameters
            {
                Expand = new[]
                {
                    $"extensions($filter=Id eq 'Microsoft.OutlookServices.OpenTypeExtension.{MicrosoftGraphServiceLevel2.MsEventExtensionName}')"
                }
            }
        );

        // adjust the URL template so that it supports whatever we need
        getRequestInformation.UrlTemplate = getRequestInformation.UrlTemplate!.Replace(
            "{?%24select}",
            "{?%24select,%24expand}"
        );

        // perform the call (that's actually what the .GetAsync() does under the hood)
        return await graphServiceClient.RequestAdapter.SendAsync<Event>(
            getRequestInformation,
            Event.CreateFromDiscriminatorValue,
            new Dictionary<string, ParsableFactory<IParsable>>()
            {
                { "4XX", ODataError.CreateFromDiscriminatorValue },
                { "5XX", ODataError.CreateFromDiscriminatorValue }
            }
        );
```
where the `QueryParameters` definition might be

```
    class QueryParameters
    {
        /// <summary>Expand related entities</summary>
        [QueryParameter("%24expand")]
        public string[]? Expand { get; set; }
    }
```

**Comment by MartinM85** [comment]
@stukalin I'm using similar workaround with modifying UrlTemplate and adding `%24expand` to `QueryParameters`

**Comment by Freenex1911** [comment]
One more (and maybe shorter) workaround without the need to add a new class would be like [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689#issuecomment-1467738178):

```
var requestInformation = graphServiceClient.Users[User].Events[EventId].ToGetRequestInformation();
requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length - 1, ",Expand");
requestInformation.QueryParameters.Add("Expand", "Attachments");
```

And I think the Expand-property is missing for a few more things like `ContactFoldersRequestBuilderGetQueryParameters` for example.

**Comment by MartinM85** [comment]
> One more (and maybe shorter) workaround without the need to add a new class would be like [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689#issuecomment-1467738178):
> 
> ```
> var requestInformation = graphServiceClient.Users[User].Events[EventId].ToGetRequestInformation();
> requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length - 1, ",Expand");
> requestInformation.QueryParameters.Add("Expand", "Attachments");
> ```
> 
> And I think the Expand-property is missing for a few more things like `ContactFoldersRequestBuilderGetQueryParameters` for example.

Expand property is missing for a lot of things, so I would prefer the fix in SDK before workarounds. It's time consuming to write workarounds and refactor them later.

**Comment by CyanideMonkey** [comment]
> found a temp workaround for this one

Thanks so much for posting that!
