### ISSUE TITLE
[question] Calendarview call in c# not working with msgraph-sdk-dotnet 5 / visual studio

### ISSUE THREAD

**Issue by dirkoppenlaender** [microsoftgraph/msgraph-sdk-dotnet#1675]
Hi,

since calling the eventlist does not return reoccuring events from event series i am trying to get the calendarview with the new syntax requestConfiguration.QueryParameters.Filter.

in lack of documentation i am not able to get it to work - instead i geet an ODataError exception.

My Syntax (which worked fine for events) for the Calendarview ist as follows:

Please give me a hint what i am missing....

calendarEvents = await graphServiceClient
        .Users[mailid]
        .CalendarView
        .GetAsync(requestConfiguration =>
        {
            requestConfiguration.QueryParameters.Filter = "start/dateTime ge '2023-03-02T00:00:00.000Z' and end/dateTime le '2023-03-03T23:59:00.000Z'";
        });

**Comment by andrueastman** [comment]
Thanks for raising this @dirkoppenlaender  

Any chance you can look into the API error and confirm what you get when you follow the guidance on error handling at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by dirkoppenlaender** [comment]
found my error:

requestConfiguration.QueryParameters.StartDateTime = "2023-03-07T00:00:00";
requestConfiguration.QueryParameters.EndDateTime = "2023-03-09T23:59:00";

was the solution...
