### ISSUE TITLE
[Client bug]: Upload session not cancelled for large file upload to OneDrive

### ISSUE THREAD

**Issue by anhtuan1412** [microsoftgraph/msgraph-sdk-dotnet#1678]
**Describe the bug**
I'm using Graph SDK to upload large files to OneDrive. I'm following the pattern described in the documentation here, 
https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp#upload-large-file-to-onedrive

In order to add cancellation, I'm adding a cancellation token to the post request as follows

var uploadSession = await graphClient.Drive.Root
    .ItemWithPath(itemPath)
    .CreateUploadSession
    .PostAsync(**cancellationToken**);

During my testing, this doesn't actually cancel the post request (I've created a case where Progress is reported multiple times, and I made sure that a cancellation happens during one of those times).

Is this the correct way of handling cancellation for uploading large files? Or is there another way?

**Expected behavior**
The upload session should be cancelled

**Client version**
Graph SDK 4.15.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by anhtuan1412** [comment]
@andrueastman, thank you for the clarification. If that is the case, then is there a recommended pattern for cancelling the PostAsync request itself?

**Comment by andrueastman** [comment]
Passing the cancellationToken as `PostAsync(cancellationToken)` should be able to **only** cancel the http call made to create the uploadSession.

**Comment by anhtuan1412** [comment]
@andrueastman, how about cancelling the fileUploadTask?
var fileUploadTask = new LargeFileUploadTask<DriveItem>(uploadSession, fileStream, maxSliceSize, graphClient.RequestAdapter);

**Comment by andrueastman** [comment]
Hey @anhtuan1412, 
This functionality is not available in V4 of the SDK at the moment. 

However, if you are willing to upgrade to V5([upgrage guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md)), the upload task also should take in a cancellationtoken when the upload is initiated.

```cs
await fileUploadTask.UploadAsync(cancellationToken);
```

**Comment by anhtuan1412** [comment]
Thanks for the response!
