### ISSUE TITLE
Skiptoken property no longer available on QueryParameters

### ISSUE THREAD

**Issue by gsibleycollabware** [microsoftgraph/msgraph-sdk-dotnet#1679]
**Describe the bug**
The Skiptoken property is not available within UsersRequestBuilderGetQueryParameters (or any other QueryParameters implementations from what I can see).

**To Reproduce**
1. Create a new request like client.Users.GetAsync(config => config.QueryParameters.Skiptoken = "token")
2. Notice the Skiptoken property is not available.

**Expected behavior**
Skiptoken property should be available on QueryParameters to enable fetching of a specific positional result set.

**Screenshots**
For example, you can see in this screenshot from Graph Explorer that the code snippet is showing the presence of the property on the UsersRequestBuilderGetQueryParameters object:

![image](https://user-images.githubusercontent.com/8739250/222930795-c746b765-2908-42fc-8c47-2793eaeda168.png)

**Additional context**
We have been using Skiptoken (in combination with Top X) in our code base to support infinite scroll behavior for result fetching. There doesn't seem to be any way to support this in the v5.0 GA release.

**Comment by andrueastman** [comment]
We'll track this via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1689
