### ISSUE TITLE
Roadmap Document

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#168]
Many Microsoft projects on GitHub have a roadmap document (in the Wiki). Any plans to add such a document here?

**Comment by cbales** [comment]
I'll look into what we can do here

**Comment by cbales** [comment]
Currently, Graph does not publish a roadmap. This would be a great suggestion for [UserVoice](https://officespdev.uservoice.com/). The library's features try to shortly follow features as they are added to the Graph API. To get a general sense of new features being added, you can look at the new features that are available in the [Beta endpoint](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/beta-overview).
