### ISSUE TITLE
[Client bug]: Cannot query mail folder including hidden folders

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1680]
**Describe the bug**
To include hidden mail folders I can call

`GET https://graph.microsoft.com/v1.0/me/mailFolders/?includeHiddenFolders=true`

but in the SDK 5.0.0 there is no way to include hidden folder. Based on the [example](https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=csharp) there should be property `Includehiddenfolders` but no such property exists.

```
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Me.MailFolders.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Includehiddenfolders = true;
});
```

**To Reproduce**
1. Check Microsoft.Graph.Me.MailFolders.MailFoldersRequestBuilder.MailFoldersRequestBuilderGetQueryParameters

**Expected behavior**
Developers can specify whether the hidden folders are included or not

**Screenshots**

**Client version**
5.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
This can block a lot of existing applications to upgrade SDK to v5

**Comment by andrueastman** [comment]
This is caused by the metadata missing the query parameter and the request can be made as below as this is resolved. 

```cs
        var requestInformation = graphClient.Me.MailFolders.ToGetRequestInformation();
        requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length-1, ",includehiddenfolders");
        requestInformation.QueryParameters.Add("includehiddenfolders", "true");

        var result = await graphClient.RequestAdapter.SendAsync<MailFolderCollectionResponse>(requestInformation, MailFolderCollectionResponse.CreateFromDiscriminatorValue);
```
