### ISSUE TITLE
Question: Trying out v5. How do I Upgrade BaseUrl = "https://graph.microsoft.com/beta" code to v5?

### ISSUE THREAD

**Issue by myokeeh** [microsoftgraph/msgraph-sdk-dotnet#1685]
Using this guide: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md

```
var clientddd = new GraphServiceClient(new DelegateAuthenticationProvider(
                async request =>
                {
                    request.Headers.Authorization =
                      new AuthenticationHeaderValue("bearer", msalar?.AccessToken);
                    await Task.CompletedTask;
                }))
            {
                BaseUrl = "https://graph.microsoft.com/beta"
            };
```

The guide above seems to say I should be using `Microsoft.Graph.Beta`? Is that a separate NuGet package?

OR BETTER YET:

Is getting a tenant user's Photo still really beta in Graph? To clarify, this is not for a Microsoft account user. The code after above is this:

```
var udsers = await clientddd.Users[df.azureUserItemUserId].Photos.GetAsync();
```

**Comment by andrueastman** [comment]
> The guide above seems to say I should be using Microsoft.Graph.Beta? Is that a separate NuGet package?


Yes, there is a separate package at the link below to use for calling the Beta API. As the API shape and response for the V1 endpoint may differ, it may be advisable to use the package to make the calls.

https://www.nuget.org/packages/Microsoft.Graph.Beta

The GraphServiceClient constructor also takes in a string parameter which you may use as well

```cs
var graphServiceClient = new GraphServiceClient(authenticationProvider, "https://graph.microsoft.com/beta");
```

> Is getting a tenant user's Photo still really beta in Graph?

As this is an API related question and this repo is mainly intended for SDK related issues, I would suggest forwarding the query to https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by myokeeh** [comment]
I was able to get past this. It turns out I didn't have to use `Microsoft.Graph.Beta` or pass the parameter as you suggested. It's now able to get user photos as it did before v5.

I was copying some code from a different part of my app that didn't have `await` where it was needed.
