### ISSUE TITLE
Adding query parameters for delta queries in SDK v5

### ISSUE THREAD

**Issue by Freenex1911** [microsoftgraph/msgraph-sdk-dotnet#1689]
How do I add query parameters for a delta query? https://learn.microsoft.com/en-us/graph/delta-query-messages
Currently I cannot seem to find any way to do it in API v5. Previously I could do it by using:
``.Delta().Request(new List<Option>() { new QueryOption("changeType", "created") })``
What I've tried so far is to use `ToGetRequestInformation` and just add the query parameter by using `requestInformation.QueryParameters.AddOrReplace("changeType", "created")`, however the URI doesn't get updated and therefore the new query parameter isn't showing up when I check `requestInformation.URI.AbsoluteUri`.

**Comment by andrueastman** [comment]
Thanks for raising this @Freenex1911 

This can be done as follows as we fix this in the metadata.

```cs
        var requestInformation = graphClient.Users.Delta.ToGetRequestInformation((requestConfiguration) =>
        {
            requestConfiguration.QueryParameters.Count = true;
        });
        requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length - 1, ",%24skiptoken,%24deltatoken");
        requestInformation.QueryParameters.Add("%24skiptoken", "skiptoken");
        requestInformation.QueryParameters.Add("%24deltatoken", "deltatoken");

        var result = await graphClient.RequestAdapter.SendAsync<UserCollectionResponse>(requestInformation, UserCollectionResponse.CreateFromDiscriminatorValue);
```

**Comment by bkaankose** [comment]
The workaround mentioned above does not work for Messages resource.

```csharp
string latestDeltaToken = "latest_delta_token_here";

var deltaRequest = _graphClient.Me.Messages.Delta.ToGetRequestInformation((config) =>
{
    t.QueryParameters.Count = true;
});

deltaRequest.UrlTemplate = deltaRequest.UrlTemplate.Insert(deltaRequest.UrlTemplate.Length - 1, ",%24deltatoken");
deltaRequest.QueryParameters.Add("%24deltatoken", latestDeltaToken);

var response = await _graphClient.RequestAdapter.SendAsync(deltaRequest, MessageCollectionResponse.CreateFromDiscriminatorValue);
```

This code fails with an exception-status code 405.

`Microsoft.Kiota.Abstractions.ApiException : The server returned an unexpected status code and no error factory is registered for this code: 405`

Am I missing something here? Also, do we have an ETA for this fix in the metadata?

**Comment by Bletch1971** [comment]
@andrueastman can you please add the missing QueryParameters SkipToken and DeltaToken options are include for Groups as well as Users.

**Comment by sergiu-sbp** [comment]
> Thanks for raising this @Freenex1911
> 
> This can be done as follows as we fix this in the metadata.
> 
> ```cs
>         var requestInformation = graphClient.Users.Delta.ToGetRequestInformation((requestConfiguration) =>
>         {
>             requestConfiguration.QueryParameters.Count = true;
>         });
>         requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length - 1, ",%24skiptoken,%24deltatoken,changeType");
>         requestInformation.QueryParameters.Add("%24skiptoken", "skiptoken");
>         requestInformation.QueryParameters.Add("changeType", "created");
>      //requestInformation.QueryParameters.Add("%24deltatoken", "deltatoken");
> 
>         var result = await graphClient.RequestAdapter.SendAsync<UserCollectionResponse>(requestInformation, UserCollectionResponse.CreateFromDiscriminatorValue);
> ```

@andrueastman Unfortunately this work-around does not work at all for us, and all we could get from Graph API using this (and other variations that we've attempted) is an error.

Are there any other work-arounds that we can try here?

If these an official date for when this feature, which is still presented in the official documentation as a working feature of the Graph SDK, will actually be available? 

Thank you in advance for your assistance on this thread.

**Comment by GoodProgrammerMB** [comment]
Dates for events in calendars (startDate/endDate) and delta tokens in parameters do not work. Someone will tell me when it will be fixed.
Without it, the whole api is not suitable for production.
It's been 2 months since the release of v5 and the bug is chasing the bug.

**Comment by Nness** [comment]
Specifically for delta token, it is available for `client.Drives["xxx"].Items[""].DeltaWithToken()`. The request builder is `DeltaWithTokenRequestBuilder`. 

Like other has mentioned, for ordinary delta, it is still missing many query parameters, not saying the missing of `DeltaWithTokenRequestBuilder`. 

Overall I am not super pleased with the change of `RequestBuilder`, I can see it try to assist user from entering unexpected query parameter or header, but it seems restrictive but it is not type safe and it is not restrictive at all (you can still have typo in new syntax). It creates restriction without clearer context (delta query missing `DeltaWithToken` method is beyond my understanding, it is the basic of delta query.). It is like half baked.

The reason I call it half baked, following is the code I would expect.

```
client.Me.Messages.Delta.GetAsync(config => {
    config.QueryParameters
        .Select()
        .Select(m => Id)
        .Select(m => m.Subject)
        .Select(m => m.BodyPreview);
    config.QueryParameters
        .Expand(m => m.Attachments, attachmentSelect => attachmentSelect.Select(a => a.Id));
    config.OrderByDescending(m => m.ReceivedDateTime);
});
```

The reason I mentioned above is that, I don't feel the change from `RequestBuilder` gives much different than v4's `Option`. v4 at least allow us to define any query parameter or header without any struggle. In v5, it seems helpful but once have issue, it is hard to have workaround. The benefit compare to the downside I don't feel it is worth the effort.

Personally I have already created fluent helper for above syntax for v4, it only take few hours to change to v5 style, but missing required property and require more effort to workaround seems not enough reason for me to switch over yet.

**Comment by karthikd70** [comment]
@andrueastman ODataNextLink is same as Request Url.

**Comment by TheRealQuasae** [comment]
Same, QueryParameters does not contain a definition for 'SkipToken'

Is there a timeframe for a fix?

**Comment by paugusto76** [comment]
Still no luck on this... and the documentation continues to be misleading. 👌

**Comment by andrueastman** [comment]
Given the API guidance [here](https://github.com/microsoft/api-guidelines/blob/vNext/graph/patterns/change-tracking.md#considerations), the metadata used to generate the client libraries will not be updated to include the `$skipToken` and `$deltaToken` query parameters. The entire url is documented as opaque and the change of the url structure (e.g. moving to use alternative query parameters) is not considered a breaking change. This means adding them to the SDK would be misleading in the event an API changes the url structure. 

> API service should use $skipToken and $deltaToken within their implementations of nextLink and deltaLink, however the URLs are defined as being opaque and the existence of the tokens MUST NOT be documented. It is not a breaking change to modify the structure of nextLinks or deltaLinks.-

To resolve the misleading documentation, we will be updating the api documentation within the coming week to encourage the use of the entire URL and the existing request builders to make subsequent requests from the `@odata.nexlink`(OdataDeltaLink property) or `@odata.deltaLink`(OdataNextLink property) returned from the delta request. 

This can be used as below.
```cs
// make the first request
var deltaResponse = await graphClient.Groups.Delta.GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Select = new string[] { "displayName", "description", "mailNickname" };
});

// use the deltaResponse.OdataDeltaLink/deltaResponse.OdataNextLink to make the next request.
var deltaRequest = new Microsoft.Graph.Beta.Groups.Delta.DeltaRequestBuilder(deltaResponse.OdataDeltaLink, graphClient.RequestAdapter);
var secondDeltaResponse = await deltaRequest.GetAsync();
```

Alternatively, the PageIterator can be used to solve this as it will use the url and follow through the pages and pause when a deltaLink is reached and expose it for you as below

```cs
//fetch the first page of groups
var deltaResponse = await graphClient.Groups.Delta.GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Select = new string[] { "displayName", "description", "mailNickname" };
});

// create a list to hold the groups
var groups = new List<Group>();
// create a page iterator to iterate through the pages of the response
var pageIterator = PageIterator<Group, Microsoft.Graph.Beta.Groups.Delta.DeltaResponse>.CreatePageIterator(graphClient, deltaResponse, group => 
{
    groups.Add(group);
    return true;
});

// This will iterate follow through the odata.nextLink until the last page is reached with an odata.deltaLink
await pageIterator.IterateAsync();

if (pageIterator.State == PagingState.Delta) 
{
    await Task.Delay(30000);// wait for some time for changes to occur.
    // call delta again with the deltaLink to get the next page of results
    Console.WriteLine("Calling delta again with deltaLink");
    Console.WriteLine("DeltaLink url is: " + pageIterator.Deltalink);
    await pageIterator.IterateAsync();
}
```

The guide will be updated via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2087 and snippet generation updates via https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1702

**Comment by asbjornheid** [comment]
I might be dense but what about the `changeType` parameter[1]?

[1]: https://learn.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&tabs=http#query-parameters
