### ISSUE TITLE
Incorrect namespace assigned to 'UrlTemplate' in the Security RunHuntingQuery builder

### ISSUE THREAD

**Issue by udaykiranravuri** [microsoftgraph/msgraph-sdk-dotnet#1691]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

Post call to run hunting queries should work as expected.

### Actual behavior

Calls fail with the oDataError (using Graph v5 nuget) with code '400' and message 'Resource not found for segment 'security.runHuntingQuery''

### Steps to reproduce the behavior
try {
var requestBody = new RunHuntingQueryPostRequestBody() { Query = "<Query>" };
            var queryResults = await new GraphServiceClient(<TokenCredential>).Security.SecurityRunHuntingQuery.PostAsync(requestBody, cancellationToken: cancellationToken).ConfigureAwait(false);
}
catch (oDataError error) {
}

**Comment by udaykiranravuri** [comment]
the 'UrlTemplate' used seems to be incorrect here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/7a2be45d2cf37f18a32cc9a60d0edf441fd23a08/src/Microsoft.Graph/Generated/Security/SecurityRunHuntingQuery/SecurityRunHuntingQueryRequestBuilder.cs

**Comment by andrueastman** [comment]
Thanks for raising this @udaykiranravuri 

This can be worked around as the metadata issue is resolved.

```cs
var requestBody = new RunHuntingQueryPostRequestBody() { Query = "" };
                var requestInformation = graphClient.Security.SecurityRunHuntingQuery.ToPostRequestInformation(requestBody);
                requestInformation.UrlTemplate = "{+baseurl}/security/runHuntingQuery";

                var queryResults = await graphClient.RequestAdapter.SendAsync<HuntingQueryResults>(requestInformation, HuntingQueryResults.CreateFromDiscriminatorValue);
```
