### ISSUE TITLE
[Client bug]: Tavis.UriTemplates loading issue when using Microsoft.Graph@5.0.0 and net472

### ISSUE THREAD

**Issue by jairbubbles** [microsoftgraph/msgraph-sdk-dotnet#1692]
**Describe the bug**

When using [latest NuGet package](https://www.nuget.org/packages/Microsoft.Graph/5.0.0), it fails to load `Tavis.UriTemplates.dll`:

```
System.IO.FileLoadException: Could not load file or assembly 'Tavis.UriTemplates, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5be2d48fa8a60581' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

 It seems related to #1439.

It looks like the reference is:

![image](https://user-images.githubusercontent.com/15875066/223658549-a877ad4b-ef7d-482d-abbb-76845b1878ad.png)

But the assembly name in package is:

![image](https://user-images.githubusercontent.com/15875066/223658943-dafe6399-8836-4a93-8d94-ca6651603653.png)

**To Reproduce**
1. Use this .csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Graph" Version="5.0.0" />
    </ItemGroup>
</Project>
```
With program.cs:
```csharp
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Authentication;

var authProvider = new BaseBearerTokenAuthenticationProvider(new TokenProvider());
await authProvider.AuthenticateRequestAsync(new RequestInformation());

class TokenProvider : IAccessTokenProvider
{
    public Task<string> GetAuthorizationTokenAsync(Uri uri, Dictionary<string, object> additionalAuthenticationContext = null, CancellationToken cancellationToken = new())
        => Task.FromResult(string.Empty);

    public AllowedHostsValidator AllowedHostsValidator { get; } = new();
}
```
2.  Run
3.  Observe the loading exception

**Expected behavior**

No exception ;-)

**Client version**

5.0.0

**Comment by andrueastman** [comment]
Thanks for raising this @jairbubbles 

Just to confirm, any chance you can still replicate this with version 5.1.0?

**Comment by jairbubbles** [comment]
I'll check!

**Comment by jairbubbles** [comment]
Sadly yes, I can reproduce with version 5.1.0.

The package dependencies did not change so we get the exact same behavior.

**Comment by andrueastman** [comment]
Any chance you can share a sample repro project to help us understand this better? We are having trouble replicating this as the build works from our end.

**Comment by jairbubbles** [comment]
You mean in a zip file? The files in the description are enough to get it. I just hit F5 to get the exception.

**Comment by andrueastman** [comment]
> You mean in a zip file? The files in the description are enough to get it. I just hit F5 to get the exception.

That would be helpful. As from my end, the build runs successfully.

**Comment by jairbubbles** [comment]
Here you go:

[GraphApiTest.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/10939970/GraphApiTest.zip)

- Unzip
- `dotnet run`
- 💥


(My dotnet version is 7.0.102)

**Comment by andrueastman** [comment]
Thanks for this @jairbubbles,

Unfortunately, I'm still unable to replicate this. This builds fine on my end with VS 2022 and dotnet SDK 7.0.201. 

Any chance this could be resolved by deleting the contents of the `bin` directory? Or possibly updating the .NET version?

**Comment by jairbubbles** [comment]
It builds fine, the execution is problematic right ?

**Comment by andrueastman** [comment]
That's not the case, the code is able to execute without issue from my end.

**Comment by jairbubbles** [comment]
I'll check with my colleagues if they can reproduce and get back to you, thx !

**Comment by jairbubbles** [comment]
Ok so I finally understand what's going on, after removing `Tavis.UriTemplates` from my global package cache and use nuget.org as my main NuGet source I no longer have the issue. 

It seems that we have a different version cached in our internal NuGet package 😰

Version on nuget.org:  
![image](https://user-images.githubusercontent.com/15875066/224404621-90f42726-233c-4a2f-a4fb-d9f75a21b507.png)

Version on our internal Nuget server:  
![image](https://user-images.githubusercontent.com/15875066/224404689-905bda14-4fa8-4d27-8426-21d1a8fe87af.png)


Could it be that the package was republished?
I'll check if it wasn't republished internally as I've already seen that once. It shouldn't happen but you know, mistake happen 😉

Sorry for wasting your time!

**Comment by andrueastman** [comment]
No worries @jairbubbles,

Thanks for confirming
