### ISSUE TITLE
How to get a specific SharePoint site with its relative path in v5?

### ISSUE THREAD

**Issue by ivancavlek** [microsoftgraph/msgraph-sdk-dotnet#1693]
We are using **Sites.Selected** Permission and in v4 I used the following code to get the drive ID of the SharePoint site with its relative path:

```C#
var sharePointDrive = await GraphClient
   .Sites["company.sharepoint.com"]
   .SiteWithPath(relativePath)
   .Drive
   .Request()
   .GetAsync()
   .ConfigureAwait(false);
```

Unfortunately, I can't find an alternative in v5. Could you please help?

**Comment by MartinM85** [comment]
I think you need to make two calls. One to get site by using `GetByPathWithPath`. The second one to get drive of the site.

```
var site = await GraphClient.Sites["company.sharepoint.com"].GetByPathWithPath(relativePath).GetAsync();
var drive = await GraphClient.Sites[site.Id].Drive.GetAsync();
```

**Comment by ivancavlek** [comment]
I know I tried `GetByPathWith` earlier and didn't get any results. I keep getting an error on the first line of your example when trying to retrieve the `site`:

![image](https://user-images.githubusercontent.com/16662190/223749765-b9ab0551-e742-42d8-b7b4-dde25dae1fa0.png)

I tried various combinations:
`GetByPathWithPath(relativePath)`
`GetByPathWithPath($"path='{relativePath}'")`
`GetByPathWithPath("company.sharepoint.com/" + relativePath)`

And with and without leading `/` in `relativePath`. Nothing seems to be working.
I also believe that your solution is the way to go, but I don't know what is the syntax for the `GetByPathWithPath` method.

**Comment by andrueastman** [comment]
Thanks for rasing this.

Any chance this works out for you?

```cs
var domain = "company.sharepoint.com";
var path = "/sites/root";
var site = await graphClient.Sites[$"{domain}:{path}"].GetAsync();
```

**Comment by ivancavlek** [comment]
That did the trick, @andrueastman 😊!

So, in conclusion, combination of @andrueastman answer to get the site ID and @MartinM85 answer to get the site's drive id is the solution. It (unfortunately) requires two calls now in v5. 

Thank you both 😊!
