### ISSUE TITLE
Refrence of Microsoft.Graph version 5 in blazor client project causes the slowness in publish

### ISSUE THREAD

**Issue by rubeesh** [microsoftgraph/msgraph-sdk-dotnet#1699]
Refrence of Microsoft.Graph version 5 in blazor client project causes the slowness while pubshiling the project.
Slowness is while  Optimizing assemblies for size. 
Framework: Dot Net7

dotnet publish Test.Server.csproj --configuration Release --output publish

**Comment by rubeesh** [comment]
Refrence of Microsoft.Graph version 5 in blazor client project causes the slowness while pubshiling the project.
Slowness is while Optimizing assemblies for size.
Framework  .Net 7

**Comment by andrueastman** [comment]
Thanks for raising this @rubeesh 

We'll track this via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1702 for now as we look into optimizing the dll size to resolve this.

**Comment by rubeesh** [comment]
The issue still not resolved even after upgrading to version 5.2
