### ISSUE TITLE
Error when reading unexpected response

### ISSUE THREAD

**Issue by vko-insiders** [microsoftgraph/msgraph-sdk-dotnet#1701]
**Describe the bug**
Spontaneous Error: Graph SDK throwing when receiving incorrect JSON in response when calling mail list.
The error reads `'{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.value | LineNumber: 0 | BytePositionInLine: 315974.`.

**To Reproduce**
We did a heavy load test for graph API to check if we are handling Graph concurrency limits correctly.
We use .NET Graph API `v4.54.0`.
It does not matter if I have 1.000 times the same mail or different mails.
When listing mails we encountered and error that throws from time to time (maybe after ever 100, 1.000 or 10.000 operations).
After contacting Microsoft Support (Case #:35412026) over Azure Portal, we were adviced to raise a ticket here as it seems to be a Graph SDK related issue.
We do log Graph request and Graph response, see screenshots below.

Code for listing mails:
```
var request = user.MailFolders[_folder.Id].Messages.Request().Top(pageSize)
                    .Expand(GraphAdapter.MailExpandString()).Header("Prefer", contentType).Filter(CreateStateFilter(state))
                    .OrderBy("receivedDateTime");
Log.Message("Fetch mails");                 
IMailFolderMessagesCollectionPage resultPage = await GraphExceptionHandler.Call( async () =>
{
    return await request.GetAsync();
});
```
Where `GraphExceptionHandler.Call` is a wrapper for error handling like this:
```
public static async Task<T> Call<T>(Func<Task<T>> func)
{
    while (true)
    {
        try
        {
            var response = await func();
            return response;
        }
        catch (Microsoft.Graph.ServiceException ex)
        {
            if ((int)ex.StatusCode == 429)
            {
                int retryDuration = int.Parse(ex.ResponseHeaders.RetryAfter.ToString());
                Log.Warning(ex.Message);
                Log.Warning($"Waiting for {retryDuration}s until the next request.");
                Thread.Sleep((int)((1000 * retryDuration) * 1.1));
            }
            else
            {
                throw;
            }
        }
    }
}
```

**Expected behavior**
I expect a correcly parsed response from Graph SDK without spontanteous errors.

**Screenshots**
Example request:
![image](https://user-images.githubusercontent.com/55390255/224016354-5169d1a4-6168-4634-98d6-d12aa6c05277.png)

The response
![image](https://user-images.githubusercontent.com/55390255/224016906-4f64db6e-1eb4-4e94-ad50-9fe381813f72.png)

The last parts of the response
![image](https://user-images.githubusercontent.com/55390255/224023777-7d26fa33-99bd-4e6f-83a9-1db8027e73aa.png)
reading 
```
[...]
7Z42IHtYhKP7b5brgJ4Y8Y5/Tr/H30NV7lWc/857joOy2vQtvVWFVIB5bHwHUVwh/eHIAdEpLMZB/Yow=\\r\\nMIME-Version: 1.0\\r\\n"},{"id":"Integer 0x17","value":"1"}]}{"error":{"code":"ErrorItemNotFound","message":"The specified object was not found in the store., The process failed to get the correct properties."}}
```

with Graph SDK throwing `'{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.value | LineNumber: 0 | BytePositionInLine: 315974.`

For reference with this error:

- request-id: `3b0e1cb9-6a87-400c-bc4f-ef5f50f9dd7b`
- client-request-id: `3b0e1cb9-6a87-400c-bc4f-ef5f50f9dd7b`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Not applicable
 - Version: Not applicable

**Additional context**
I cannot post the full response, but I suspect the following issue:
In the last screenshot you can see the bottom of the response. There you can see a closing bracket and an opening bracket, which might not be correct JSON format.
In other responses (which did not produce this error), I did not see this behavior.

Because we list mails, process mails and then move mails with multiple threads, it might be possible that one process moves a mail while exactly at the same time another process tries to list mails. This should be handled either on Office365 site or with Graph SDK.
This is only an assumption.

**Comment by andrueastman** [comment]
Thanks for raising this @vko-insiders 

We've raised this with the API team to follow up on the issue of creating the invalid payload. 

https://portal.microsofticm.com/imp/v3/incidents/details/373869829/home

**Comment by andrueastman** [comment]
Hey @vko-insiders,

Tha API team confirms that a fix was rolled out with regards to this. Any chance you are still able to replicate this?

**Comment by vko-insiders** [comment]
Hi @andrueastman ,

was the fix applied to Graph API `v4.5.x` or to v `5.x`?
I am asking because the migration to `v5.x` is giving us some trouble and will take some time.

**Comment by andrueastman** [comment]
This was an API side issue that caused the returning of invalid json. The version of the SDK should not matter in this scenario.

**Comment by vko-insiders** [comment]
Thank you very much, that makes sense.
I will start a heavy load test right away and will give you an answer in around 8h or tomorrow.

**Comment by vko-insiders** [comment]
Hi @andrueastman,

I have bad news for you, the error still persists, the API fix did not solve this issue.

**Comment by Vixan** [comment]
Greetings,

I understand it is not related to the SDK, but I'm also encountering issues related to invalid Graph API responses. Trying to move or update some messages in a mailbox sometimes fail with the following error:
```shell
Code: generalException Message: An error occurred sending the request.

System.Net.Http.HttpRequestException: Received an invalid status line: '0'.
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.Graph.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Graph.RetryHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Microsoft.Graph.CompressionHandler.SendAsync(HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at Microsoft.Graph.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken) - "
   at Microsoft.Graph.HttpProvider.SendRequestAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.MessageRequest.UpdateAsync(Message messageToUpdate, CancellationToken cancellationToken)
```
Sometimes I'm also encountering this:
`The server returned an unexpected status code and the error registered for this code failed to deserialize: 500`.

If I'm not mistaken, it seems related to an invalid HTTP response header 🤔...

**Comment by andrueastman** [comment]
> Hi @andrueastman,
> 
> I have bad news for you, the error still persists, the API fix did not solve this issue.

Thanks for confirming @vko-insiders.  Any chance you are able to provide a link to the support case created before? 

In case the issue persisted, we were advised that would be the right channel to follow up on this specific issue.

**Comment by vko-insiders** [comment]
Hi @andrueastman 

The support case I created before in Azure Portal Developer Support is Support request ID `2303080050001076`.

**Comment by vko-insiders** [comment]
This issue was resolved by Microsoft in the Microsoft Graph backend by 03. April 2023.
