### ISSUE TITLE
Call Microsoft Graph with Graph SDK v5 from Visual Studio 2022 Managed Identity (VisualStudioCredential)

### ISSUE THREAD

**Issue by LockTar** [microsoftgraph/msgraph-sdk-dotnet#1703]
**Describe the bug**
I'm trying to call the Microsoft Graph from Visual Studio 2022 with managed identity permissions (so the logged in user in Visual Studio).
I'm using the Microsoft graph net SDK v5. 

I'm getting the token as follow as described [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#authentication) because I want to use MSI (and my application in the cloud as well):
```C#
var credential = new DefaultAzureCredential();
var tokenResult = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(new string[] { "https://graph.microsoft.com" }));

string token = tokenResult.Token;
```

The token only contains the following scopes:
`Application.ReadWrite.All Directory.Read.All email IdentityUserFlow.ReadWrite.All openid profile User.Read`.
I'm able to retrieve information that is related with those scopes.
I'm a global admin. 
How can I change the scopes?

I guess the problem is that AppId `04f0c124-f2bc-4f59-8241-bf6df9866bbd` (`VS with native MSA`) is not added by Microsoft on the Microsoft Graph API app registration.

I'm using Azure.Identity version 1.8.2. 

**To Reproduce**
1. Create new console app in VS2022 latest
2. Follow authentication steps https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#authentication for MSI.
3. Set the options in VS2022 to use your own account.
4. Try to get a user with the MS Graph SDK. => This will work!
5. Try to create a new `Group` with the MS Graph SDK. => This will not work and you will get 403.

**Expected behavior**
A token with more scopes.

**Comment by LockTar** [comment]
Maybe this [Comment](https://github.com/Azure/azure-sdk-for-net/issues/28563#issuecomment-1462815347) is related for a similar situation with the event grid?

**Comment by andrueastman** [comment]
Thanks for raising this @LockTar,

I believe the issue is that the `AppId` in use would need to be pre-authorized to have the appropriate scope in order for the call to succeed. 
Any chance you have the permissions to add the needed permissions for the app registration with the mentioned AppId?

**Comment by LockTar** [comment]
Hi @andrueastman,

The appid is `04f0c124-f2bc-4f59-8241-bf6df9866bbd` (`VS with native MSA`). This is Visual Studio 2022 17.5.1. 
I see that the token has the scopes `Application.ReadWrite.All Directory.Read.All email IdentityUserFlow.ReadWrite.All openid profile User.Read`.
I can of course create my own app registration, set the permissions and authenticate with client credentials (the application that I make is a background process) but I want to run this in Azure with the Managed Identity of the Azure Function. So I want the same development experience locally. 

I understand I need to set some permissions/scopes on my account but where can I do that.

**Comment by andrueastman** [comment]
I believe for this you can probably take a look at the first part of the tutorial at the link below to setup the application to assign the scopes to the managed identity.

https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-access-microsoft-graph-as-app?tabs=azure-cli 

You can then use the `ChainedTokenCredential` or `DefaultAzureCredential` and use the managed identity to make the call. 

https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#examples

**Comment by LockTar** [comment]
This would work for Azure resources or user managed identities. But I don't think it will work for [VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.visualstudiocredential?view=azure-dotnet) in combination with the MS Graph.

If you have an idea how, let me know.

**Comment by Ruud2000** [comment]
I ran into a similar issue, see https://github.com/Azure/azure-sdk-for-net/issues/34843#issuecomment-1464108992

In my case I can use the `ChainedTokenCredential` with `ManagedIdentityCredential` and `AzureCliCredential` as a workaround. Apparently the `AzureCliCredential` gets different scopes than the `VisualStudioCredential`, even when you do a `az login` in the Developer Powershell window within Visual Studio. I think it would be nice if the `AzureCliCredential` and `VisualStudioCredential` would return the same scopes - but not sure if that makes sense :)

**Comment by svrooij** [comment]
First of all those "flows" are different, the ManagedIdentityCredential is a client (as in application) flow, the others (AzureCliCredential, VisualSudioCredential) are all delegated flows, as in there is a user involved.

Why not use `ManagedIdentityCredential` in Azure and `new DefaultAzureCredential(true)` (allow interactive) in development. Then you can just ask for other scopes and the user is prompted to consent if those additional scopes are not consented just yet.

Then there still is a difference meaning it's still a delegated flow in development.

This [post](https://svrooij.io/2022/04/21/access-api-with-managed-identity/) describes how to get tokens for any api using managed identities. And this [post](https://svrooij.io/2021/07/20/managed-identity-without-azure/) shows you how you can mimic "the same flow" while not running in Azure.
