### ISSUE TITLE
only http/1.0 and http/1.1 version requests are currently supported. parameter name value

### ISSUE THREAD

**Issue by vhj1995** [microsoftgraph/msgraph-sdk-dotnet#1704]
**Describe the bug**
I am unable to use graph api due to this error.

**To Reproduce**
use graph client and query for groups

**Expected behavior**
only http/1.0 and http/1.1 version requests are currently supported. parameter name value

**Screenshots**
![image](https://user-images.githubusercontent.com/25062869/224283824-046afa63-b978-4cef-a685-5e64f5a772aa.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Windows Console App
 - .NET Framework 4.6.2

**Comment by andrueastman** [comment]
Thanks for raising this @vhj1995 

Any chance you can share the version of the sdk you are using as well as a sample of how the graphServiceClient is configured/intialized?

**Comment by vhj1995** [comment]
I was using older SDK version. Thanks. using Version 4.54 solved the problem.
