### ISSUE TITLE
No v5 guide for WithMaxRetry and WithShouldRetry option

### ISSUE THREAD

**Issue by erwinkramer** [microsoftgraph/msgraph-sdk-dotnet#1705]
There is the https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md doc, but there is no info about the `.WithMaxRetry` and `.WithShouldRetry` deprecation. 

How can we re-implement retry behaviour in v5?

**Comment by andrueastman** [comment]
Thanks for raising this @erwinkramer 

We'll update the docs to capture this but it should be possible to add the options to the request as below;

```cs

            var retryHandlerOption = new RetryHandlerOption
            {
                MaxRetry = 7,
                ShouldRetry = (delay,attempt,message) => true
            };
            var user = await graphClient.Me.GetAsync(requestConfiguration => requestConfiguration.Options.Add(retryHandlerOption));
```

**Comment by erwinkramer** [comment]
Thanks @andrueastman , i'm glad we can still handle it. 

By the way, is there a list of requestConfiguration Options somewhere as a reference?

**Comment by MartinM85** [comment]
@erwinkramer requestConfiguration Options must implement Microsoft.Kiota.Abstractions.IRequestOption.

Kiota is OpenAPI based HTTP Client code generator. Kiota for dotnet provides several implementations of IRequestOption:

https://github.com/microsoft/kiota-http-dotnet/tree/c98faf6c5a341f82b5e4f5b6e1b65f15df416c70/src/Middleware/Options

It would be nice to have more docs for end-user. Now developers spend a lot of time by searching and asking.
