### ISSUE TITLE
[v5.0] Include more details in error message

### ISSUE THREAD

**Issue by gmantri** [microsoftgraph/msgraph-sdk-dotnet#1711]
**Describe the bug**
In the previous versions of the SDK, we would always get a detailed error message when something went wrong with a request. With v5.0 all we get back is `Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown` with no details about the error.

**To Reproduce**
Try to get details about a user which does not exist in Azure AD by specifying incorrect user id.

```
var request = _graphServiceClient.Users["non-existent-user-id"];
// the following line of code will throw "Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown" error.
var result = await request.GetAsync(requestConfiguration =>
  {
      requestConfiguration.QueryParameters.Select =
          new[] { "id", "displayName", "mail", "userPrincipalName" };
  })
```
**Expected behavior**
When I execute the same request against Graph API directly (e.g. `https://graph.microsoft.com/v1.0/users/5ce7f6de-ff21-496e-a5a2-1e901bc2dbd7`), I get the following message back:

```
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource '5ce7f6de-ff21-496e-a5a2-1e901bc2dbd7' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2023-03-11T09:19:13",
            "request-id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "client-request-id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        }
    }
}
```

I am expecting the error message returned by the SDK to contain this information. Currently all we get is `Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown`.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by andrueastman** [comment]
Thanks for raising this @gmantri 

As captured in the guide, the error will be deserialized to an intance of `ODataError` and can be handled as documented to get more details. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling
