### ISSUE TITLE
[Client bug]: No way to update MailboxSettings in v5

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1712]
**Describe the bug**
According to the [documentation](https://learn.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=http#http-request) the endpoint to update mailbox settings is

```
PATCH /me/mailboxSettings
PATCH /users/{id|userPrincipalName}/mailboxSettings
```

But SDK v5 doesn't have any `MailboxSettings` property on either `UserItemRequestBuilder` or `MeRequestBuilder`

**To Reproduce**
1. Type either `graphClient.Me.MailboxSettings` or `graphClient.Users[""].MailboxSettings`

**Expected behavior**
Can access `MailboxSettings` property on either `UserItemRequestBuilder` or `MeRequestBuilder`

**Screenshots**

**Client version**
5.1.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @MartinM85 

Hi @SomebodyToLove1337,

Unfortunately, structural properties that can be accessed through the URI are not accessible through the SDK at the moment and should be resolved in future metadata updates. 
You can however workaround this by using the request builders as below. 

```cs
            var mailboxSettings = new MailboxSettings
            {
                AutomaticRepliesSetting = new AutomaticRepliesSetting
                {
                    ScheduledStartDateTime = new DateTimeTimeZone(),
                    ScheduledEndDateTime = new DateTimeTimeZone()
                }
            };
            var requestInformation = graphServiceClient.Users["{o365UserID}"].ToGetRequestInformation();
            requestInformation.HttpMethod = Method.PATCH;
            requestInformation.UrlTemplate = "{+baseurl}/users/{user%2Did}/mailboxSettings";//update the template to include /mailBoxSettings
            requestInformation.SetContentFromParsable<MailboxSettings>(graphServiceClient.RequestAdapter, "application/json", mailboxSettings);

            await graphServiceClient.RequestAdapter.SendNoContentAsync(requestInformation);
```
