### ISSUE TITLE
lastModifiedDateTime object is being ignored while uploading to OneDrive

### ISSUE THREAD

**Issue by kishanhathiwala** [microsoftgraph/msgraph-sdk-dotnet#1714]
**Describe the bug**
I am trying to upload the file using the following code and it seems that uploaded file is not using the `LastModifiedDateTime` object I have passed. Can someone please help me?

**To Reproduce**
```
    var props = new DriveItemUploadableProperties {
        Name = @$"{values.Item2}",
        FileSystemInfo = new FileSystemInfo {
            LastModifiedDateTime = new DateTimeOffset(item.LastModifiedDateTime.Value.UtcDateTime)
        },
        AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "rename" } },
        OdataType = "microsoft.graph.driveItemUploadableProperties"
    };

    var uploadSession = await destinationGraphServiceClient
        .Drives[driveId]
        .Items["root"]
        .ItemWithPath(@$"{values.Item1}/{values.Item2}")
        .CreateUploadSession.PostAsync(new CreateUploadSessionPostRequestBody { Item = props });

    var progress = new Progress<long>(p => {
        Console.WriteLine($"Uploaded {p} bytes of {item.Size} bytes");
    });

    using var fs = new FileStream(values.Item2, FileMode.Open);
    var largeFileUpload = new LargeFileUploadTask<DriveItem>(uploadSession, fs, 320 * 1024);
    var result = await largeFileUpload.UploadAsync(progress);

    Console.WriteLine(result.UploadSucceeded
        ? $"Uploaded completed for file: {result.ItemResponse.Name} with fileId: {result.ItemResponse.Id}"
        : $"Upload failed for file: {item.Name}");
```

**Expected behavior**
File is successfully getting upload with current datetime.
![image](https://user-images.githubusercontent.com/29030616/224608500-96834861-5c9a-4dc8-89ff-e678cb014fcf.png)

**Desktop (please complete the following information):**
 - OS: Docker (mcr.microsoft.com/dotnet/runtime:7.0)
 - Console application
 - Version [5.1.0]

**Smartphone (please complete the following information):**
N/A

**Additional context**
I tried using Microsoft Graph Explorer which worked.
![image](https://user-images.githubusercontent.com/29030616/224608871-396e75ed-08bc-423c-b2be-94e11fe9bd69.png)
![image](https://user-images.githubusercontent.com/29030616/224609457-0f7451b3-8711-4cd0-9017-208880e17c7c.png)

**Comment by andrueastman** [comment]
Thanks for raising this @kishanhathiwala,

I suspect in the dotnet sample, you are creating the uploadSession with the `LastModifiedDateTime` and then uploading the file which is a modification which would result in the API automatically updating the property as the file has been modified. 
Using graph explorer, you are only creating the uploadSession with the `LastModifiedDateTime` and hence there is no other modification happening as there is no subsequent upload. 

Any chance you are able to resolve the issue by updating the `LastModifiedDateTime` after the upload is completed to avoid the property updating due to the modification that is the upload?

**Comment by kishanhathiwala** [comment]
Thank you @andrueastman for your reply.

What my code is doing is to upload the file with local file's LastModifiedDateTime in just one go.

It seems my code is working fine. There seems to be an issue with Microsoft OneDrive's site. When I checked the uploaded file in my Android app, the LastModifiedDateTime is showing what I have set.

Many thanks and keep doing great work!
