### ISSUE TITLE
SignInActivity v4-beta to v5 migration

### ISSUE THREAD

**Issue by ivi-hamiti** [microsoftgraph/msgraph-sdk-dotnet#1716]
Hello, going through the migration guide to v5 i see that SignInActivity is missing in the User model, and i can not find any equivalent property for that. How will i be able to query that for users in v5?

**Comment by andrueastman** [comment]
Thanks for raising this @ivi-hamiti 

I believe `SignInActivity` is from the beta API. Any chance you have tried using the v5 beta package to access the property?

**Comment by ivi-hamiti** [comment]
@andrueastman you are right it is in the beta package. I mistakenly thought it should be in the stable package as it was a beta to major upgrade of the package and but the service behind is not yet stable
