### ISSUE TITLE
[v5.0.0] Small files upload returns a drive item, not nothing

### ISSUE THREAD

**Issue by olivermue** [microsoftgraph/msgraph-sdk-dotnet#1718]
**Describe the bug**
According to the [documenation](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#response-1), this call
```csharp
var driveItem = serviceClient.Drives["driveId"].Items["folderId"].ItemWithPath("SomeFilename.txt").Content.PutAsync(stream);
```
should return a drive item, [but the current signature of the `PutAsync()` method is](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/Drives/Item/Items/Item/Content/ContentRequestBuilder.cs#L75)
```csharp
public async Task PutAsync(Stream body, Action<ContentRequestBuilderPutRequestConfiguration>? requestConfiguration = default, CancellationToken cancellationToken = default)
```

**Expected behavior**
Please change the signature of the method to be `Task<DriveItem>` instead of `Task`.

**Comment by andrueastman** [comment]
Dependent on https://github.com/microsoft/OpenAPI.NET.OData/pull/357

**Comment by asgeirgs** [comment]
Evidently you need to make a second call to retrieve the DriveItem as such:

var driveItem = await serviceClient.Drives["driveId"].Items["folderId"].ItemWithPath("SomeFilename.txt").GetAsync();
