### ISSUE TITLE
Assigning AdditionalData to ListItem throws JSON exception when dictionary contains data types other than string

### ISSUE THREAD

**Issue by rajagsn** [microsoftgraph/msgraph-sdk-dotnet#1722]
Just Upgraded my project to Microsoft.Graph 5.1.0 from version 4.x and a runtime exception is thrown when passing different data types to AdditionalData dictionary to update SharePoint online list items.

Passing in date or int causes "CurrentDepth (1000) is equal to or larger than the maximum allowed depth of 1000. Cannot write the next JSON object or array." runtime exception to be thrown.

```
Dictionary<string, object> dict = new Dictionary<string, object>
{
	{ "InstanceID", "TST-2023-000069"},
	{ "Title", "TST-2023-000069 - test"},
	{ "Description", "Test"},
	{ "EventDate", new DateTime(2023,03,14)},
	{ "EndDate", new DateTime(2023,03,14)},
	{ "Attendees", 10}
};

GraphServiceClient graphServiceClient = new GraphServiceClient(clientSecretCredential, scopes);

var listItem = new ListItem()
{
	Fields = new FieldValueSet()
	{
		AdditionalData = dict 
	}
};

var retItem = await graphServiceClient.Sites[SiteID].Lists[ListID].Items.PostAsync(listItem);
```

### Expected behavior

Allow different data types to be passed into AdditionalData dictionary.

 
### Actual behavior

Exception is thrown "CurrentDepth (1000) is equal to or larger than the maximum allowed depth of 1000. Cannot write the next JSON object or array."

### Steps to reproduce the behavior

Execute code above in C# .NET 7.0

**Comment by Freenex1911** [comment]
Can confirm, currently using .NET6 and API v5 with the same problem. Anything besides `string` results in the same runtime exception as described above.

**Comment by andrueastman** [comment]
Thanks for raising this @rajagsn,

I believe the issues here is using the `DateTime` type in the AdditionalData. Any chance you have any luck when you use the Date from Kiota abstractions (or DateTimeOffset) type?

```cs
        Dictionary<string, object> dict = new Dictionary<string, object>
        {
            { "InstanceID", "TST-2023-000069"},
            { "Title", "TST-2023-000069 - test"},
            { "Description", "Test"},
            { "EventDate", new Date(2023,03,14)},
            { "EndDate", new Date(2023,03,14)},
            { "Attendees", 10}
        };
```

We'll be fixing the handling of the DateTime type in the serializer.

**Comment by rajagsn** [comment]
Hello @andrueastman,

Yes, changing the datatype to DateTimeOffset seems to resolve the issue. For now I will enumerate the dictionary and replace occurrences of DateTime with  DateTimeOffset before sending it to Graph API.

Thanks for implementing the fix.
