### ISSUE TITLE
Patching Extensions results in ODataError in SDK v5

### ISSUE THREAD

**Issue by Freenex1911** [microsoftgraph/msgraph-sdk-dotnet#1723]
I am trying to update an existing `OpenTypeExtension` of a `Contact` using the latest v5 SDK like this:
```
var extension = await Client
   .Users[userID]
   .ContactFolders[folderID]
   .Contacts[contactID]
   .Extensions["MyCustomExtension"]
   .PatchAsync(openTypeExtension);
```
.. which results in:
```
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
Cannot process input of abstract type 'microsoft.graph.extension'
```
This was possible in previous 4.x versions.

**Comment by andrueastman** [comment]
Thanks for rasing this @Freenex1911 

Any chance you are able to get more information on the error by following the guide below?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by Freenex1911** [comment]
Yea, sure.

_Console.WriteLine(ex);_
```
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Users.Item.ContactFolders.Item.Contacts.Item.Extensions.Item.ExtensionItemRequestBuilder.PatchAsync(Extension body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at MyApp.Graph.UpdateContacts(String folder, Dictionary`2 contacts) in E:\Graph.cs:line 166
```
_Console.WriteLine(ex.Error);_
`Microsoft.Graph.Models.ODataErrors.MainError`
_Console.WriteLine(ex.Error.Code);_
`UnprocessableType`
_Console.WriteLine(ex.Error.Message);_
`Cannot process input of abstract type 'microsoft.graph.extension'`

![Screenshot 2023-03-15 120302](https://user-images.githubusercontent.com/15677860/225290423-5d363f21-29d2-4ec5-bf12-04b2ec55214b.png)
![Screenshot 2023-03-15 120330](https://user-images.githubusercontent.com/15677860/225290610-70d89324-13ae-47c6-940c-b6f0aeaa4094.png)

**Comment by andrueastman** [comment]
Any chance you can share a code sample of how you are creating the `openTypeExtension` variable passed to the `PatchAsync` call?

**Comment by Freenex1911** [comment]
I just figured out that when I create a blank new `OpenTypeExtension` and fill out `ExtensionName` and some `AdditionalData` everything seems to work fine. However, when I create a new Contact with a new extension combined like this:
```
var contact = new Contact()
{
    GivenName = "name",
    Extensions = new List<Extension>()
    {
        new OpenTypeExtension()
        {
            ExtensionName = "MyExtension",
            AdditionalData = new Dictionary<string, object>()
            {
                { "foo", "bar" }
            }
        }
    }
};
```
.. and trying to update said extension like this `.PatchAsync(contact.Value.Extensions.First(x => x is OpenTypeExtension y && y.ExtensionName == "BGKS"))` I get the error. `contact` in this case is a newly (locally) created contact to update an existing contact.

```
var updatedContact = Client
     .Users[Configuration.GlobalMailbox]
     .ContactFolders[folder]
     .Contacts[contact.Key]
     .PatchAsync(contact);
var updatedContactExtension = Client
     .Users[Configuration.GlobalMailbox]
     .ContactFolders[folder]
     .Contacts[contact.Key]
     .Extensions["MyExtension"]
     .PatchAsync(contact.Value.Extensions.First(x => x is OpenTypeExtension y && y.ExtensionName == "MyExtension"));
```

**Comment by andrueastman** [comment]
Thanks for the extra information here. 

This is explained as the SDK employs the use of dirty tracking through the BackingStore to track what has been sent over to the server to avoid sending data that is already consistent with the server during an update. 

Thus, in this call, the entire contact object and its nested properties have been marked as "sent" and properties won't be serialized unless they are modified. 

```cs
var updatedContact = Client
     .Users[Configuration.GlobalMailbox]
     .ContactFolders[folder]
     .Contacts[contactID]
     .PatchAsync(contact);
```

Out of curiosity,since the contact object already contains the extension info, do you still need to make this second call to update the extension?

```cs
var updatedContactExtension = Client
     .Users[Configuration.GlobalMailbox]
     .ContactFolders[folder]
     .Contacts[contactID]
     .Extensions["MyExtension"]
     .PatchAsync(contact.Extensions.First(x => x is OpenTypeExtension y && y.ExtensionName == "MyExtension"));
```

If that's the case, due to the dirty tracking, you would need to do as you suggested.

**Comment by andrueastman** [comment]
Taking a look at the reference documentation at the link below, it would be incorrect to try to update the extension in the same call as updating the Contact.

https://learn.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-1.0&tabs=http

However, in some scenarios, you can create an extension in the same call as the call that creates the contact.

https://learn.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&tabs=http

As the dirty tracking is tied to the root object that is initialized (in this case the `Contact` object) and you need to make two calls the right thing to do would be as you suggested earlier. 

```cs
  //update the contact
  var contact = new Contact()
  {
      GivenName = "name"
  };
  var updatedContact = Client
      .Users[Configuration.GlobalMailbox]
      .ContactFolders[folder]
      .Contacts[contactID]
      .PatchAsync(contact);

  // update the extension
  var extension = new OpenTypeExtension()
  {
      ExtensionName = "MyExtension",
      AdditionalData = new Dictionary<string, object>()
      {
          { "foo", "bar" }
      }
  };
  var updatedContactExtension = Client
      .Users[Configuration.GlobalMailbox]
      .ContactFolders[folder]
      .Contacts[contactID]
      .Extensions["MyExtension"]
      .PatchAsync(extension);
```
