### ISSUE TITLE
Implicitly constructed BaseGraphRequestAdapter can't be disposed

### ISSUE THREAD

**Issue by NickDarvey** [microsoftgraph/msgraph-sdk-dotnet#1724]
**Is your feature request related to a problem? Please describe.**
Two constructors of `Microsoft.Graph.GraphServiceClient` [^1] create instances of `Microsoft.Graph.BaseGraphRequestAdapter`. `Microsoft.Graph.BaseGraphRequestAdapter` needs to be disposed because it inherits [^2] from `Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter` which needs to dispose its `System.Net.HttpClient` [^3].

**Describe the solution you'd like**
`Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter` is disposable, therefore `Microsoft.Graph.BaseGraphRequestAdapter` which inherits from the former is disposable, therefore `Microsoft.Graph.GraphServiceClient` which instantiates the former _should_ be disposable, following the cascading disposable pattern [^4].

**Describe alternatives you've considered**
Alternatively, the `GraphServiceClient` constructor overloads that implicitly create a `BaseGraphRequestAdapter` could be obsoleted, forcing the user to instantiate `BaseGraphRequestAdapter` and dispose of it directly.

**Additional context**
A workaround is to use the `GraphServiceClient` constructor overloads that accept a `BaseGraphRequestAdapter`, instantiating and disposing the `BaseGraphRequestAdapter` yourself.

[^1]: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/82d4f5d4b7a8216e787f2b227e08019773f6cc02/src/Microsoft.Graph/GraphServiceClient.cs#L59-L78
[^2]: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/3708629f91bc314a30d07e349cf6205f8ed30b52/src/Microsoft.Graph.Core/Requests/BaseGraphRequestAdapter.cs#LL16C68-L16C68
[^3]: https://github.com/microsoft/kiota-http-dotnet/blob/58fb5f4ad6edbaf54dfe184fa2d3b8538bc558f2/src/HttpClientRequestAdapter.cs#L530-L538
[^4]: https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#cascade-dispose-calls

**Comment by andrueastman** [comment]
Thanks for raising this @NickDarvey 

Just to add here. Another alternative would be to probably do something like this.

```cs
if (graphClient.RequestAdapter is IDisposable disposable)
{
    disposable. Dispose();
}
```
