### ISSUE TITLE
Shared Channel Creation

### ISSUE THREAD

**Issue by ncangeles1995** [microsoftgraph/msgraph-sdk-dotnet#1728]
When creating a shared channel, a channel is not being returned as the result. Furthermore, the response headers do not contain the channel ID as it does for team creation.

**Comment by ncangeles1995** [comment]
> Thanks for raising this @ncangeles1995
> 
> Any chance you can share more details/code sample you are using to help us understand this better?

Sure, see below is the code sample I am using:
var requestBody = new Channel
            {
                DisplayName = channelName,
                Description = channelName,
                MembershipType = ChannelMembershipType.Shared,
                Members = new List<ConversationMember>
                {
                    new ConversationMember
                    {
                        OdataType = "#microsoft.graph.aadUserConversationMember",
                        Roles = new List<string>
                        {
                            "owner"
                        },
                        AdditionalData = new Dictionary<string, object>
                        {
                            {
                                "user@odata.bind" , $"https://graph.microsoft.com/.default/users({userId})"
                            }
                        }
                    }
                }
            };
            var res = await graphClient.Teams[teamId].Channels.PostAsync(requestBody);

**Comment by andrueastman** [comment]
Thanks for this @ncangeles1995 

As the documentation shows, the API will not return a value for this specific API call. 
https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#example-5-create-a-shared-channel-on-behalf-of-a-user

You can however read the header in the response as documented in the guide.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object

```cs
        var nativeResponseHandler = new NativeResponseHandler();
        var res = await graphClient.Teams["teamId"].Channels.PostAsync(requestBody, requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler }));
        var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
        var contentLocation = responseMessage.Content.Headers.ContentLocation.ToString();
```

**Comment by ncangeles1995** [comment]
> Thanks for this @ncangeles1995
> 
> As the documentation shows, the API will not return a value for this specific API call. https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#example-5-create-a-shared-channel-on-behalf-of-a-user
> 
> You can however read the header in the response as documented in the guide. https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object
> 
> ```cs
>         var nativeResponseHandler = new NativeResponseHandler();
>         var res = await graphClient.Teams["teamId"].Channels.PostAsync(requestBody, requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler }));
>         var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
>         var contentLocation = responseMessage.Content.Headers.ContentLocation.ToString();
> ```

This seems to be throwing an error because ContentLocation is null. Is this a bug?

**Comment by andrueastman** [comment]
Any chance you have any luck logging the headers to see if returns the Location header instead?

```cs
            var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
            Console.WriteLine("Status code: "+ responseMessage.StatusCode.ToString());
            if (responseMessage.IsSuccessStatusCode)
            {
                foreach(var header in responseMessage.Headers)
                    Console.WriteLine("Header: "+ header.Key + " Value: " +header.Value.First());
                foreach (var header in responseMessage.Content.Headers)
                    Console.WriteLine("Header: " + header.Key + " Value: " + header.Value.First());
            }
```

**Comment by ncangeles1995** [comment]
> ```cs
>  var nativeResponseHandler = new NativeResponseHandler();
> ```

No luck, the header seems to only have the Teams ID that was passed in to create the Channel. Nothing that looks to be the Channel ID is returned.

**Comment by andrueastman** [comment]
Which header is returned in this situation? 
I believe if it is in the format like in the documentation,
`/teams/7640023f-fe43-4cc7-9bd3-84a9efe4acd6/operations/359d75f6-2bb8-4785-ab2d-377bf3d573fa` You may need to call the endpoint to check if the operation is complete.

https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#example-5-create-a-shared-channel-on-behalf-of-a-user
