### ISSUE TITLE
Create B2C user

### ISSUE THREAD

**Issue by Mardoxx** [microsoftgraph/msgraph-sdk-dotnet#173]
[`Microsoft.Azure.ActiveDirectory.GraphClient`](https://www.nuget.org/packages/Microsoft.Azure.ActiveDirectory.GraphClient/) says it should be possible to use `Microsoft.Graph` in its stead:

> NOTE: Azure AD Graph API functionality is also available through Microsoft Graph, a unified API that also includes APIs from other Microsoft services like Outlook, OneDrive, OneNote, Planner, and Office Graph, all accessed through a single endpoint with a single access token. Find out more about Microsoft Graph @ http://graph.microsoft.com, and find the Microsoft Graph .Net Client Library @ https://www.nuget.org/packages/Microsoft.Graph and the open source code and further documentation @ https://github.com/microsoftgraph/msgraph-sdk-dotnet

Several AAD samples say, going forward, to use the `Microsoft.Graph` SDK.

However! It does not seem possible to create a B2C user (local account) using the `Microsoft.Graph` client. The `AddAsync()` method on the `User.Request()` object does not appear to have [appropriate properties](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/users-operations#CreateLocalAccountUser) to set (namely `signInNames` and `creationType` are missing). 

Trying something like

    var res = graphClient.Users.Request().AddAsync(new User
    {
        AccountEnabled = true,
        DisplayName = "TestUser",
        PasswordProfile = new PasswordProfile
        {
            ForceChangePasswordNextSignIn = false,
            Password = "Abcd@1234"
        },
        UserPrincipalName = "testuser@test.com",
        MailNickname = "testuser@test.com",
    }).Result;

results in an exception of `ServiceException: Code: InternalServerError Message: The given key was not present in the dictionary.`

Is there a way to create a user in a B2C directory using this SDK?

**Comment by cbales** [comment]
This functionality is currently not available in Microsoft Graph. Although AAD is recommending developers to switch to Microsoft Graph, do note that there is a transition period during which Microsoft Graph is not at parity with AAD's Graph offerings. You should evaluate the scenarios you require and let that inform your decision of which library to use.

**Comment by Mardoxx** [comment]
>This functionality is currently not available in Microsoft Graph.

Thanks.

>Although AAD is recommending developers to switch to Microsoft Graph, do note that there is a transition period during which Microsoft Graph is not at parity with AAD's Graph offerings.

Any plans to bring them in sync?

>You should evaluate the scenarios you require and let that inform your decision of which library to use.

Clearly...

**Comment by garethrampton** [comment]
It would be useful to have some sort of indication on a timeframe in which B2C (local account creation) support will be implemented in Microsoft Graph. Can you provide any insight here?

Are we likely to see any support in the Graph API directly before the Graph SDK is updated? 

It seems pretty clear that at some point AAD Graph (and ADAL now that we have MSAL) will become deprecated given the clear advice to use Microsoft Graph wherever possible.

As of now it feels like B2C is in limbo between the two APIs, and therefore becomes a difficult sell-in to stakeholders in our business because of this.

**Comment by MIchaelMainer** [comment]
I do not know the timeframe for B2C account creation. The client library typically lags behind the service in terms of API support. 

Since this feature is important to you, please post the feature request to [Office Dev User Voice](https://officespdev.uservoice.com/).

**Comment by chaliy** [comment]
Just want add +1 to the thread. Timelines and full API support is important. Your users kill planet by spending their powers to learn your lib and finally stack to the point where just simple function is not implemented :(

**Comment by abhijitpatil1009** [comment]
@garethrampton 
Is it still not suppoting to create user with Microsoft Graph API in B2C Directory. please suggest sugest correct option for user management in B2C Microsoft Graph API Or Azure Graph API

**Comment by garethrampton** [comment]
@abhijitpatil1009 I'm afraid we've moved away from Graph and Azure AD due to the mess that the current different APIs are in. We're now using openiddict instead and managing identity ourselves.

**Comment by ggirard07** [comment]
I created an entry in uservoice https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/34793269-support-azure-ad-b2c-local-account

Feel free to add any information if I missed some points.

**Comment by sven5** [comment]
Just my comment:

You can use a different API for B2C: 
https://docs.microsoft.com/en-US/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet?tabs=applications

I wonder when standard Graph API will support B2C.

**Comment by ggirard07** [comment]
@sven5 The usage of this API for Azure AD B2C is still not advertised by Microsoft https://docs.microsoft.com/en-US/azure/active-directory/develop/active-directory-graph-api
Despite being the only solution available depending on the operation you want to perform (e.g. creating a user in this case).

Microsoft has recently pushed some [B2C support in the Microsoft Graph API](https://github.com/azure-ad-b2c/ief-wiki/wiki/Azure-AD-B2C-Change-log#october-2019), but apparently still nothing to be able to create users.
