### ISSUE TITLE
Expand property is missing for EventsRequestBuilderGetQueryParameters on 1.0 and beta

### ISSUE THREAD

**Issue by fwauquier** [microsoftgraph/msgraph-sdk-dotnet#1735]
_Microsoft Graph v5.2.0 - Microsoft Graph Beta 5.22.0-preview_

Cannot find '**Expand**' for Event request as indicate on Graph Explorer :because Expand property is missing on <code>EventsRequestBuilderGetQueryParameters </code>
Snippet : 
<code>...
var result = await graphClient.Users["{user-id}"].Calendar["{calendar-id}"].Events.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "singleValueExtendedProperties($filter=Id+eq+'...')" };
});</code>
or 
<code>...
var result = await graphClient.Users["{user-id}"].Events.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "singleValueExtendedProperties($filter=Id+eq+'...')" };
});</code>

**Comment by calebkiage** [comment]
Moved this here as it's related to the .NET SDK.

**Comment by kiainlogicdk** [comment]
I really need this as well
