### ISSUE TITLE
Re-include "Inbox" property when accessing mail folders

### ISSUE THREAD

**Issue by CollinAlpert** [microsoftgraph/msgraph-sdk-dotnet#1738]
**Is your feature request related to a problem? Please describe.**
In v4 it was possible to access the Inbox folder directly by accessing `user.MailFolders.Inbox`. This doesn't work anymore in v5.

**Describe the solution you'd like**
I'd like to be able to access the inbox without needing to know its ID or needing to loop over all of the folders.

**Comment by andrueastman** [comment]
Thanks for raising this @CollinAlpert 

We'll close this for now and are tracking this as via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1727
