### ISSUE TITLE
Newtonsoft.Json 10.0.3 not compatible with Microsoft.Graph 1.5.0

### ISSUE THREAD

**Issue by StuartMeeks** [microsoftgraph/msgraph-sdk-dotnet#174]
Looks like we have a repeat of issue 101 with Microsoft.Graph 1.5.0

Unable to resolve dependencies. 'Newtonsoft.Json 10.0.3' is not compatible with 'Microsoft.Graph 1.5.0 constraint: Newtonsoft.Json (>= 6.0.1 && <= 10.0.2)', 'Microsoft.Graph.Core 1.6.0 constraint: Newtonsoft.Json (>= 6.0.1 && <= 10.0.2)'.

**Comment by cbales** [comment]
Thanks for finding this. See #171 (it was closed prematurely)
