### ISSUE TITLE
Can't add members to a Team when it has not been activated

### ISSUE THREAD

**Issue by kiainlogicdk** [microsoftgraph/msgraph-sdk-dotnet#1743]
It comes up with an error.

This worked fine in 4.*

**Comment by andrueastman** [comment]
Thanks for raising this @kiainlogicdk 

Any chance you can provide more details on the error you are receiving? As well a sample of the working and non-working code?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by kiainlogicdk** [comment]
When trying to add a member on a team that has not been activated i get this error 

Team status:
![image](https://user-images.githubusercontent.com/127185821/226275595-02084b7e-6724-459e-b9bd-9bef79a233a2.png)

Error response;
An unexpected error(Type = OperationDeniedAsTeamIsLocked) occurred. Please try again.

Code:
 var member = new AadUserConversationMember
  {
      Roles = new List<string>() { "member" },
      AdditionalData = new Dictionary<string, object>
      {
          {"user@odata.bind" , $"https://graph.microsoft.com/v1.0/users/{UserID}"}
      },
  };

  await graphClient.Teams[GroupID].Members.PostAsync(member);

Steps to reproduce:
Create a group
Add an owner
Add a team to the group
Run the code above

This worked in version 4.*

**Comment by andrueastman** [comment]
Thanks for the extra information @kiainlogicdk 

Just to confirm, does this mean that using V4 you are able to add a member to team that has not been activated? Any chance you can share a code sample that works with v4?

**Comment by kiainlogicdk** [comment]
Yes it works in V4 with this code. I am using add async here.
In V5 i am using PostAsync since AddAsync 

This is what i use in V4
  ```
     var member = new AadUserConversationMember
      {
          Roles = new List<string>() { "member" },
          AdditionalData = new Dictionary<string, object>()
          {
              {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users('{UserID}')"}
          }
      };

      await graphClient.Teams[GroupID].Members.Request().AddAsync(member);
```

**Comment by andrueastman** [comment]
The two examples do make the identical requests to the API.

However, the only difference is the OdataType string. Any chance anything changes if you drop the `#` character?
```cs
OdataType = "microsoft.graph.aadUserConversationMember",
```

**Comment by kiainlogicdk** [comment]
I just tried  that and it makes no difference.

**Comment by andrueastman** [comment]
Any chance this works out? 

```cs
            var member = new AadUserConversationMember
            {
                Roles = new List<string>() { "member" },
                AdditionalData = new Dictionary<string, object>()
                {
                    {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users('UserID')"}
                }
            };

            await graphClient.Teams["team-id"].Members.PostAsync(member);
```

**Comment by kiainlogicdk** [comment]
It still comes up with the error
An unexpected error(Type = OperationDeniedAsTeamIsLocked) occurred. Please try again.

**Comment by andrueastman** [comment]
Any chance you are able to share the other properties in the odataError object? Specifically the ClientRequestId in the nested InnerError object as well as properties in the AdditionalData?

**Comment by kiainlogicdk** [comment]
Just made a new request :-)

Here is the info
ValueKind = Object : "{"message":"An unexpected error(Type = OperationDeniedAsTeamIsLocked) occurred. Please try again.","code":"AccessDenied","innerError":{},"date":"2023-03-29T09:35:14","request-id":"13ef5578-8d71-4b4e-b2d2-1045c7e4443c","client-request-id":"08f4fac5-9b3f-488f-8b07-88c053606a68"}"

**Comment by andrueastman** [comment]
Thanks @kiainlogicdk 

We're following up with the API team to understand the discrepancy as the payloads are the same and will revert with more information.

https://portal.microsofticm.com/imp/v3/incidents/details/378287094/home

**Comment by svrooij** [comment]
@kiainlogicdk just a quick question, are you sure you where using the `Teams` endpoint before? We literally sync thousands of teams, and we sync the members through the `Groups` endpoint. This is independent of the Teams Status. I recently did a [blogpost](https://svrooij.io/2023/03/03/batching-in-microsoft-graph/#adding-users-with-batching) on it. I hopes this helps unblocking you at the moment.

**Comment by kiainlogicdk** [comment]
Yes i am using the Teams endpoint for this scenario. I could add them to the group instead. But the case is the Teams endpoint is failing in V5 and not in V4 with the same code.

**Comment by andrueastman** [comment]
Hey @kiainlogicdk, 
Any chance this is still an issue on the latest version? 

>Steps to reproduce:
Create a group
Add an owner
Add a team to the group
Run the code above

I've tried replicating this but the member is added successfully from my end.

**Comment by kiainlogicdk** [comment]
This is still a problem.
Remember that the team cannot be activated

**Comment by andrueastman** [comment]
@kiainlogicdk 
Are you by any chance able to share the specific requests or a sample code/project used in making the requests when replicating this?

>Steps to reproduce:
Create a group
Add an owner
Add a team to the group
Run the code above

**Comment by kiainlogicdk** [comment]
Here is a project.
[azure_Graph New.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/13390117/azure_Graph.New.zip)

**Comment by andrueastman** [comment]
@kiainlogicdk As it seems that you are using the education APIs in your example, any chance the user reference that is in 
` {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users('UserID')"}` should have the user id as `https://graph.microsoft.com/v1.0/education/users('UserID')` instead of `https://graph.microsoft.com/v1.0/users('UserID')`

https://learn.microsoft.com/en-us/graph/api/educationuser-get?view=graph-rest-1.0&tabs=http
