### ISSUE TITLE
[Client bug]: A list of a site doesn't support $count

### ISSUE THREAD

**Issue by olivermue** [microsoftgraph/msgraph-sdk-dotnet#1749]
**Describe the bug**
The SDK contains the method
```csharp
var count = await serviceClient.Sites["root"].Lists[myList.Id].Items.Count.GetAsync();
```
This will be transformed into the following HTTP request
```
GET https://graph.microsoft.com/v1.0/sites/root/lists/f089c611-fc87-454d-a7f7-cee8ca9ed0c7/items/$count
```
and returns an 404 status with `"error.code": "itemNotFound"`. Also within the documentation I can't find any hint, that this method is currently supported.

**Expected behavior**
Either let the graph backend support this call to retrieve the number of elements (what I would prefer 😉) or remove this method from the SDK.

**Client version**
v5.2.0

**Comment by andrueastman** [comment]
Depends on to https://github.com/microsoft/OpenAPI.NET.OData/issues/364
