### ISSUE TITLE
GraphServiceClient .User[username].SendMail not recognized in v5.2.0

### ISSUE THREAD

**Issue by yogigrantz** [microsoftgraph/msgraph-sdk-dotnet#1750]
The following code used to work in Microsoft.Graph 4.45.0 - 4.54.0: 

`        
         string[] scopes = new[] { "Mail.Send", "SMTP.Send" };

        OAuth2DTO oauth = new OAuth2DTO()
        {
            ClientId = "***",
            TenantId = "***",
            UserName = "***@***.com",
            Password = "***"
        };

        ConsoleAppAuthenticationProvider cap = new ConsoleAppAuthenticationProvider(_cachedTokenFileName, scopes, oauth);
        cap.OnError += Cap_OnError;

        GraphServiceClient graphClient = new GraphServiceClient(cap);

        Message message = new Message()
        {
            Subject = "Email subject test"
        };
        message.Body = new ItemBody()
        {
            Content = "This is a <b>Test</b> Email",
            ContentType = BodyType.Html
        };

        message.ToRecipients = new List<Recipient>() { new Recipient() { EmailAddress = new EmailAddress() { Address = "tester111@mailinator.com" } } }; ;

        await graphClient.Users[_oAuth2DTO.UserName].SendMail(message, true).Request().PostAsync();
` 
In version 5.x.x: the .SendMail part of this statement is no longer recongnized:

` await graphClient.Users[_oAuth2DTO.UserName].SendMail(message, true).Request().PostAsync();` 

Please help! what would it take to make this work again?

**Comment by MartinM85** [comment]
In version 5 you can send mail this way

    var body = new SendMailPostRequestBody
    {
        Message = new Message()
        {
            Subject = "Email subject test",
            Body = new ItemBody
            {
                Content = "This is a <b>Test</b> Email",
                ContentType = BodyType.Html
            }
        },
        SaveToSentItems = true
    };
    await graphClient.Users[_oAuth2DTO.UserName].SendMail.PostAsync(body)

**Comment by andrueastman** [comment]
Thanks for raising this @yogigrantz

We'll close this for now as the example has been provided above and is available 

- https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#use-of-parameter-objects-calling-odata-functionsactions
- https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp#request

**Comment by yogigrantz** [comment]
Thank you @andrueastman , that works, you're the best! 

I may have a different problem in Graph email delete functionality, where occasionally it fails to delete, like 8 times out of 1000, but I will post this as a separate issue, just wanted to give a heads up. Thanks again!
