### ISSUE TITLE
v5 QueryOption for convertion to Pdf

### ISSUE THREAD

**Issue by gvanasco** [microsoftgraph/msgraph-sdk-dotnet#1753]
Hi

In v4, we could convert documents to pdf with this code:

`List<QueryOption> options = new List<QueryOption>
            {
                new QueryOption("format", "pdf"),
            };`

`Stream downloadedContentStream = EvGraph.GraphClient`
`  .Drives[DriveId]`
`  .List.Items[DriveItemId]`
`  .DriveItem`
`  .Content.Request(options)`
`  .GetAsync().GetAwaiter().GetResult();`

I looked for the new v5 way to do this, but there is any **IRequestOption** to do that.
I tried with headers:
`var document = await GraphClient.Drives[DriveId].Items[DriveItemId]`
`    .Content`
`    .GetAsync(requestConfiguration =>`
`            {`
`                requestConfiguration.Headers.Add("format", "pdf");`
`            });`
but it ignores Headers and returns the original document **Stream**.

Is there any way to pass QueryOption("format", "pdf") or it is not implemented yet?

Thanks,

**Comment by sopelt** [comment]
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1621 ?

**Comment by gvanasco** [comment]
Yes, it is.
I will close this.
Thanks.
