### ISSUE TITLE
V5 ODataError and ApiException do not expose the Response Headers (as ServiceException did in previous version)

### ISSUE THREAD

**Issue by hesperanca** [microsoftgraph/msgraph-sdk-dotnet#1755]
**Describe the bug**
In v4 we could access the ResponseHeaders via the ServiceException object. This was very useful when dealing with Throttling errors in batched requests (given that they are not handled by the SDK) because we could access the "retry-after" header to find out how long we should wait until trying again.

V5 uses the ODataError exception, which does not expose the response headers. So, if we get a throttling error, we have no way to get the value of the "retry-after" response header to find out how long we should wait before retrying.

**Expected behaviour**
I would expect the ODataError to expose the response header values (as we could do with the ServiceException in v4).

**Comment by vadrsa** [comment]
This is also a blocker for us to upgrade to V5, what are the plans for this enhancment?

**Comment by hesperanca** [comment]
We had to go back to V4 because of this. Some timescales would be nice.
