### ISSUE TITLE
Trying to add a member to an Education class when it's not activated fails.

### ISSUE THREAD

**Issue by kiainlogicdk** [microsoftgraph/msgraph-sdk-dotnet#1757]
This worked in V4 but not in V5.
When trying to add a member on an Education class that has not been activated i get this error
https://user-images.githubusercontent.com/127185821/226275595-02084b7e-6724-459e-b9bd-9bef79a233a2.png

Response
Code = InternalServerError
message = Unable to find target address

```
 var user = new ReferenceCreate
{
    OdataId = $"{BaseURL}/users/{UserID}"
};

await graphClient.Education.Classes[EducationClassID].Members.Ref.PostAsync(user);
```

Steps to reproduce:
Create a group
Add an owner
Add a team to the group
Run the code above

**Comment by andrueastman** [comment]
Thanks for raising this @kiainlogicdk,

The error seems to suggest an issue with the target/reference not being able to be found. 

Any chance `$"{BaseURL}/users/{UserID}"` is not valid and should be `$"{BaseURL}/education/users/{UserID}"`? 

Are you able to share a sample of the working V4 code?
