### ISSUE TITLE
V5 issue - The ChangeNotificationCollection class (used to receive push change notifications) does not exist in the V5 SDK

### ISSUE THREAD

**Issue by hesperanca** [microsoftgraph/msgraph-sdk-dotnet#1758]
**Describe the bug**
V5 issue - The ChangeNotificationCollection class, used to receive change notifications (as documented in the link below) no longer exists in the V5 SDK, and there is no documentation on what alternative approach we should take to receive notifications from MS Graph using V5.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/d6da4a13046e1f7b741ede7753a205e380892924/docs/upgrade-to-v4.md#added-support-for-encrypted-content-for-rich-notifications

**Expected behavior**
I would expect one of the following:

1) If there is an alternative way to receive change notifications using the SDK then that should be documented somewhere.

2) If we are still supposed to use the ChangeNotificationCollection class to receive push notifications using the SDK then that class should be in the SDK ( as it was in V4)

**Comment by stukalin** [comment]
@hesperanca I switched it to the `ChangeNotificationCollectionResponse` in my project

**Comment by andrueastman** [comment]
> @hesperanca I switched it to the `ChangeNotificationCollectionResponse` in my project

Any chance this is helpful? @hesperanca 

Collection objects now resemble [the shape of the API response](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#collections) and collection objects that are API responses would typicall have the `*Response` suffix

**Comment by hesperanca** [comment]
> @hesperanca I switched it to the `ChangeNotificationCollectionResponse` in my project

I did consider using it as well but assumed that it was only supposed to be used for API responses

**Comment by hesperanca** [comment]
> > @hesperanca I switched it to the `ChangeNotificationCollectionResponse` in my project
> 
> Any chance this is helpful? @hesperanca
> 
> Collection objects now resemble [the shape of the API response](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#collections) and collection objects that are API responses would typicall have the `*Response` suffix

Hi @andrueastman thanks for your reply. The documentation mentions "Querying for collections" so I'm assuming it only relates to responses from queries. In our case the collection is submitted by Grpah to our webhook endpoint (the information is pushed to us instead of us querying it) so it's not clear if what is in the documentation is applicable for this case.

**Comment by kfwalther** [comment]
We're in a similar situation for our project, and use a webhook to receive notification pushed from Graph (not manually queried). I had to dig through the unit tests in the v5 repo [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/f7f01eeb125d8ed0cb023852b587eb30a0bb39f8/tests/Microsoft.Graph.DotnetCore.Test/Models/ModelSerializationTests.cs#L36) to try to figure this out, along with how to _parse_ the received notifications (also different from v4). This workflow could definitely use some examples - I couldn't find any in official documentation.
