### ISSUE TITLE
Better support for 429er in Batches

### ISSUE THREAD

**Issue by olivermue** [microsoftgraph/msgraph-sdk-dotnet#1759]
**Is your feature request related to a problem? Please describe.**
The Graph SDK already makes 429er transparent due to the usage of the [`RetryHandler`](https://github.com/microsoft/kiota-http-dotnet/blob/main/src/Middleware/RetryHandler.cs) (except a maximum value is reached). Unfortunately this mechanism doesn't work in case of `BatchResponseContent` as this could happen as [documented](https://learn.microsoft.com/en-us/graph/throttling#throttling-and-batching). If a single request within a batch returns 429er and you try to access the response by calling `batchResponseContent.GetResponseByIdAsync<T>(stepId)` a `ServiceException` will be thrown and the values can be taken from `serviceException.ResponseStatusCode` and `serviceException.ResponseHeaders.RetryAfter`.

**Describe the solution you'd like**
Unfortunately I also don't have any _good solution_ to this problem. But it would be great if the `BatchResponseContent` has some _helper mehods_ to better filter the received responses within the batch for success and failure to easier handle these scenarios. Perfect would be, if these fails could be easily put into a new job and retried after the maximum wait time is reached, but that would mean, the response has some internal fields containing the original response or something similiar. Not easy to solve IMHO, but definitely something making the usage of batches easier. 

**Describe alternatives you've considered**
My current workaround is to wrap the `.GetResponseByIdAsync()` call into a `try-catch` block with a `when` clause for the 429er. Within that block memorize the corresponding request and aggregate the desired wait time with the maybe already set wait time to max. When all steps of the batch are taken, wait till the time max time is passed and retry the faulty requests as a new batch. This _works_ but it's not _simple to implement_ and having some helper within the SDK would be great.

**Comment by andrueastman** [comment]
Thanks for raising this @olivermue 

I believe you can do something close to 

```cs
var responses = await result.GetResponsesAsync();
            var allReponsesSuccessFull = responses.Any( response => !response.Value.IsSuccessStatusCode);//all the responses are successfull?

            var failedResponses = responses.Where(response => !response.Value.IsSuccessStatusCode);//the responses which do not have a success code.
```

Also latest updates have a new `GetResponsesStatusCodesAsync()` in the response content via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/626

**Comment by olivermue** [comment]
That sounds okay. It still doesn't help to _rerun_ the failing requests, but it makes it easier to find the failing request or in case when working with step ids maybe `.GetResponsesStatusCodesAsync()` is easier to link requests and responses.

Maybe it is possible to improve the code example in https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#batch-requests or add another one to illustrate the usage of this method?
