### ISSUE TITLE
DriveItem Delta is missing in v5

### ISSUE THREAD

**Issue by f1nzer** [microsoftgraph/msgraph-sdk-dotnet#1762]
It looks like this API is missing in the new SDK:

Track changes in a [driveItem](https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0):
https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http

v4 syntax: `graphServiceClient.Drives[driveId].Root.Delta(deltaToken)`

**Comment by andrueastman** [comment]
Thanks for raising this @f1nzer 

I believe you should be able to do this with V5

```cs
var delta = await graphClient.Drives["driveId"].Items["root"].DeltaWithToken("token").GetAsync();
```
