### ISSUE TITLE
Migrating from 4.53.0 to 5.3.0

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#1767]
Are there any code breaking changes to migrate from 4.53.0 to 5.3.0?

**Comment by ajtruckle** [comment]
This won't compile now:

```
        virtual public EventSingleValueExtendedPropertiesCollectionPage GetExtendedProperties(SettingsBase oSettings)
        {
            var extendedProperties = new EventSingleValueExtendedPropertiesCollectionPage
            {
                new SingleValueLegacyExtendedProperty
                {
                    Id = SettingsBase.Property_TruckleSoft1,
                    Value = oSettings.CalendarEntryType
                }
            };

            return extendedProperties;
        }
```

1>D:\My Programs\2022\OutlookCalIFConsole\OutlookCalIFConsole\Interface\Event\EventBase.cs(31,24,31,72): error CS0246: The type or namespace name 'EventSingleValueExtendedPropertiesCollectionPage' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ajtruckle** [comment]
I can change:

    Microsoft.Graph.SingleValueLegacyExtendedProperty

to

    Microsoft.Graph.Models.SingleValueLegacyExtendedProperty

That is suggested by Intellisense. But my functions return value of type `EventSingleValueExtendedPropertiesCollectionPage` is unknown.

**Comment by andrueastman** [comment]
Thanks for raising this @ajtruckle 

Breaking changes are outlined in the docs at link below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md

Collections are held in instances of `List<T>` instead of `ICollectionPage` instances from `System.Collections.Generic` and API responses resemble the API shape

**Comment by ajtruckle** [comment]
Hi @andrueastman ! Thank you for the link to the document detailing breaking changes, and I appreciate your explanation.
May I can ask you to tweak my existing function? As I still don't fully understand how to correctly update it. Thank you.

**Comment by andrueastman** [comment]
Hey @ajtruckle 

I believe your function should look something like this.

```cs
    virtual public List<SingleValueLegacyExtendedProperty> GetExtendedProperties(SettingsBase oSettings)
    {
        var extendedProperties = new List<SingleValueLegacyExtendedProperty>
        {
            new SingleValueLegacyExtendedProperty
            {
                Id = SettingsBase.Property_TruckleSoft1,
                Value = oSettings.CalendarEntryType
            }
        };

        return extendedProperties;
    }
```

**Comment by andrueastman** [comment]
Thanks for the follow up @ajtruckle 

In place of the `DelegateAuthenticationProvider` please checkout the upgrade guide in the Authentication section.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#authentication

**Comment by ajtruckle** [comment]
@andrueastman 
Apart from my existing query about the "token" and my existing code in my last comment, these also won't compile:

                // Add the event
                Event createdEvent = await _graphClient.Me.Calendars[oSettings.CalendarID].Events.Request().AddAsync(new Event
                {
                    Subject = oEvent.EventTitle,
                    Body = body,
                    Start = startTime,
                    End = endTime,
                    IsAllDay = oEvent.IsAllDayEvent(),
                    IsReminderOn = bSetReminder,
                    ReminderMinutesBeforeStart = bSetReminder ? iReminderMinutes : (int?)null,
                    Location = location,
                    SingleValueExtendedProperties = extendedProperties,
                    Sensitivity = oSettings.SetCalendarPrivate ? Sensitivity.Private : Sensitivity.Normal
                });

I tried to follow the docs as I see comments about `Request()`. I have one or two other build errors but want to deal with these two first (the var oken - xxx and this Request one.

**Comment by andrueastman** [comment]
@ajtruckle 

You can use your existing code and simply move into the `TokenProvider` class. Instead of the string `token` you function will return `_AuthResult.AccessToken` which is the string token. The `BaseBearerTokenAuthenticationProvider` will then take the token and append it to the Requestheader when executing the request.

Alternatively, as you are using interactive login, you can simply initialize the client as below using the interactiveBrowser credential.

https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#interactive-provider

**Comment by andrueastman** [comment]
Step 1. 
```cs
public Task<string> GetAuthorizationTokenAsync
```
can be made async 
```cs
public async Task<string> GetAuthorizationTokenAsync
```
and just 
```
return _AuthResult.AccessToken;
```

Step 2.
```cs
// Append the access token to the request.
requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", _AuthResult.AccessToken);
```
You don't this need this as the `BaseBearerTokenAuthenticationProvider` does this automatically.

While adding the header is done when making the reuqest as below. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#headers

**Comment by ajtruckle** [comment]
@andrueastman We certainly have progress and it is now operating. But it is no longer remembering the users chosen credentials.

I have moved the following into the constructor of the `TokenProvider` class:

```
TokenCacheHelper.CacheFilePath = Program.Options.TokenCachePath;
TokenCacheHelper.EnableSerialization(PublicClientApp.UserTokenCache);
```
That bit is fine. But the problem is that in my main application class I have functions like:

```
public async Task<bool> SignOut()
{
    var accounts = await PublicClientApp.GetAccountsAsync();
    if (accounts.Any())
    {
        try
        {
            await PublicClientApp.RemoveAsync(accounts.FirstOrDefault());
            return true;
        }
        catch (MsalException ex)
        {
            SimpleLog.Log(ex);
            Console.WriteLine("SignOut: See error log.");
            return false;
        }
    }

    return false;
}
```
The problem here is that `PublicClientApp` is now a member of the `TokenProvider` class. So it does not compile. As you know, this `TokenProvider` object is local to my initialization class:

```
public bool InitAuthenticatedClientAsync()
{
    bool bSuccess = true;
    var authenticationProvider = new BaseBearerTokenAuthenticationProvider(new TokenProvider());
    _graphClient = new GraphServiceClient(authenticationProvider);

    return bSuccess;
}
```
To get around this I made the token provider a member variable and used that instead:
```
public BaseBearerTokenAuthenticationProvider AuthenticationProvider { get { return _authenticationProvider; } }
_authenticationProvider = new BaseBearerTokenAuthenticationProvider(new TokenProvider());
```

Then I moved the `SignOut` function into the token provider class. But this does not work:

```
if (Program.Options.SignOut)
{
     if (!await oOutlook.AuthenticationProvider.AccessTokenProvider.SignOut())
             ReturnErrorCode = ErrorCode.SignOut;
     return;
}
```

It has no knowledge of signing out. What is the right way to support signing out on demand now?

**Comment by ajtruckle** [comment]
@andrueastman Update:

I tried making a token provider a member variable:

`TokenProvider _tokenProvider = null;`

And adjusting my initialize function:
```
_authenticationProvider = new BaseBearerTokenAuthenticationProvider(_tokenProvider);
```
And I moved `_tokenProvider = new TokenProvider();` into my main classes constructor. Now I can sign in / out. Might not be the best way but it works.

Leaves that header query.

**Comment by ajtruckle** [comment]
@andrueastman Alright. Then in that case I don't think I need to have the line anyway as it was only part of the Delegate code we replaced.

**Comment by ajtruckle** [comment]
Once again, thanks for all your help. I'll close this issue now and will start a new one if I encounter more issues.
