### ISSUE TITLE
Serialize to Json with v5

### ISSUE THREAD

**Issue by merill** [microsoftgraph/msgraph-sdk-dotnet#1769]
It is no longer possible to serialize a Graph object to the corresponding json that was returned from the Graph REST API.

Using the JsonSerializer like this

```C#
return JsonSerializer.Serialize<ConditionalAccessPolicy>(policy, new JsonSerializerOptions { WriteIndented = true });
```

Includes the AdditionalData, BackingStore and other nodes that were not part of the original response from the Graph API.

```json
{
  "Conditions": {
    "AdditionalData": {
      "times": null
    },
    "Applications": {
      "AdditionalData": {},
      "ApplicationFilter": null,
      "BackingStore": {
        "InitializationCompleted": true,
        "ReturnOnlyChangedValues": false
```

I have tried the code example mentioned by @andrueastman in this comment

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1290#issuecomment-1278576407

but haven't had luck. The response I receive is a string with the value "{}"

This is what I have tried.

```c#
    public string GetJsonFromPolicy(ConditionalAccessPolicy policy)
    {
        //Use standard serialization for now.
        //return JsonSerializer.Serialize<ConditionalAccessPolicy>(policy, new JsonSerializerOptions { WriteIndented = true });

        var seralizer = _graphHelper.GraphServiceClient.RequestAdapter.SerializationWriterFactory.GetSerializationWriter("application/json");
        seralizer.WriteObjectValue(string.Empty, policy);
        var serializedContent = seralizer.GetSerializedContent();

        using (var sr = new StreamReader(serializedContent))
        {
            return sr.ReadToEnd();
        }
    }
```

**Comment by andrueastman** [comment]
Thanks for raising this @merill 

Out of curiosity, is the `ConditionalAccessPolicy` received from the API? I believe the serializer is omitting values due to the BackingStore not emitting properties as they are consistent with the API(unchanged).

Any chance this works for you if you change  

```cs
var seralizer = _graphHelper.GraphServiceClient.RequestAdapter.SerializationWriterFactory.GetSerializationWriter("application/json");
```

to 
```cs
using var seralizer = new JsonSerializationWriter();
```

This will give you the JsonSerializer instance that will emit all properties. Not just changed ones.
