### ISSUE TITLE
v5.3.0 unable to send one on one chat message - Insufficient Privileges

### ISSUE THREAD

**Issue by ChrisGrove** [microsoftgraph/msgraph-sdk-dotnet#1770]
**Describe the bug**
I am trying to send a one on one teams chat message to a single user from a specific account. I was previously able to do this in V4.27.0, since moving to V5.3.0 I now get a permissions error using the same code.

The odata error code is 'Forbidden' and the message is 'Insufficient Privileges'. The Azure app, has all of the relevant permissons as far as I have been able to ascertain and they have all had Admin consent granted and the relevant users are all in the default role for the app.

The GraphServiceClient is instatiated as follows:

```
var options = new TokenCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
            };
            // https://docs.microsoft.com/dotnet/api/azure.identity.usernamepasswordcredential
            var userNamePasswordCredential = new UsernamePasswordCredential(
                userName, password, tenantId, clientId, options);

            _graphClient = new GraphServiceClient(userNamePasswordCredential, scopes);
```

Scopes is equal to the following (line breaks for readability):
```
"MicrosoftGraph": {
    "BaseUrl": "https://graph.microsoft.com/v1.0",
    "Scopes": "Chat.ReadBasic email offline_access openid profile Channel.ReadBasic.All ChannelMessage.Send Chat.Create
                     Chat.ReadWrite ChatMember.ReadWrite ChatMessage.Read ChatMessage.Send Directory.Read.All User.Read 
                     User.Read.All Chat.Read"
  },
```

I am unable to use other credential types as the app needs to able to send as this specific user regardless of who is logged into it at the time.

The Azure App api permissions are set as below:
![image](https://user-images.githubusercontent.com/25799273/227983216-2416beb0-2eb0-45ba-835f-1bef95ba2768.png)

I have recreated the process in Postman using http requestes for the same user logging into the same azure app and sending to the same target user. This worked as expected.

The environment is as follows:

- Windows 10 64 bit
- dot net sdk 7.04
- Visual Studio 2022 v17.5.3
- asp.net web app with mvc run in IIS express via Visual Studio debugging.

Installed Nuget Packages:
![image](https://user-images.githubusercontent.com/25799273/227988191-75f17995-7ea1-4c3c-82d6-c6b202ca66fd.png)

The graph service client as created above is able to post to a Team / channel but cannot post a one on one message.

This is the code that creates the message and sends it:
```
public async static Task<bool> SendChatMessageToUser(string _targetUser, ChatMessage message)
        {
            if (_appUser == null || _graphClient == null)
                return false;

            var targetUser = await _graphClient.Users[_targetUser]
                        .GetAsync(); //v5

            if (targetUser == null) return false;

            var chat = new Chat
            {
                ChatType = ChatType.OneOnOne,
                Members = new List<ConversationMember>() //v5
                {
                    new AadUserConversationMember
                    {
                        OdataType = "#microsoft.graph.aadUserConversationMember",
                        Roles = new List<string>()
                        {
                            "owner"
                        },
                        AdditionalData = new Dictionary<string, object>()
                        {
                            {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users('{_appUser.Id}')"}
                        }
                    },
                    new AadUserConversationMember
                    {
                        OdataType = "#microsoft.graph.aadUserConversationMember",
                        Roles = new List<string>()
                        {
                            "owner"
                        },
                        AdditionalData = new Dictionary<string, object>()
                        {
                            {"user@odata.bind", $"https://graph.microsoft.com/v1.0/users('{targetUser.Id}')"}
                        }
                    }
                }
            };

           //create or get chat with the target user
            var chatRef = await _graphClient.Chats
                 .PostAsync(chat); //v5

            if (chatRef == null) return false;

            //v5
            try
            {
                //Error thown here
                var res = await _graphClient.Chats[chatRef.Id].Messages.PostAsync(message);
            }
            catch (ODataError odataError)
            {
                Console.WriteLine(odataError.Error?.Code);
                Console.WriteLine(odataError.Error?.Message);
                throw;
            }
            return true;
        }
```

I have looked in the documentation and cannot see what permission / privilige I might be missing. 

Can you please advise if this is a bug or if I have missed something.

Thanks
Chris

**Comment by andrueastman** [comment]
Thanks for raising this @ChrisGrove 

Any chance you can confirm that the `scopes` values in

```
_graphClient = new GraphServiceClient(userNamePasswordCredential, scopes);
```
match what you expect by logging them?

**Comment by ChrisGrove** [comment]
@andrueastman 
Please see below for the parsed scopes string as used to create the GraphServiceClient. I have also included the scopes that are obtained when manually running the login http requests via postman.

![image](https://user-images.githubusercontent.com/25799273/228164158-2c871781-c4d9-417a-8b9f-7bcddd386edc.png)

![image](https://user-images.githubusercontent.com/25799273/228164242-c73714fa-07ad-4c31-a831-84d1b98be50b.png)

Is there a way to check the scopes or capture the jwt returned when the GraphServiceClient is created ? I looked for a way to do this but couldn't see anything obvious.

**Comment by ChrisGrove** [comment]
@andrueastman thank you so much for that code. I have logged and decoded the jwt and it appears to contain all of the relevant scopes for sending the chat message.

Updated code:
```
var requestInformationGet = _graphClient.Chats[chatRef.Id].Messages.ToGetRequestInformation();
var tokenGet = await _azureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(requestInformationGet.URI);

var requestInformationPost = _graphClient.Chats[chatRef.Id].Messages.ToPostRequestInformation(message);
var tokenPost = await _azureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(requestInformationPost.URI);

var postContent = new StreamReader(requestInformationPost.Content, Encoding.ASCII).ReadToEnd();

 //Error thown here
var res = await _graphClient.Chats[chatRef.Id].Messages.PostAsync(message);
```

Scopes from decoded tokenGet:
![image](https://user-images.githubusercontent.com/25799273/228196947-d15eaedf-cb27-469c-9ce4-d3dba1fc33f7.png)

I have also included the request info for both the Get and Post actions on Messages.

Get Request:
![image](https://user-images.githubusercontent.com/25799273/228203895-707ea83d-0a0f-485f-abc9-d662c96c005a.png)

Post Request:
![image](https://user-images.githubusercontent.com/25799273/228203991-f8f7adbe-c4ea-4f63-a84f-c914f31cc0bc.png)

Post Content:
![image](https://user-images.githubusercontent.com/25799273/228203068-c78e0622-eb59-4723-bf1b-9f0b17bb65ff.png)

**Comment by andrueastman** [comment]
Does the code still error out if you do this?

Any chance you are able to share the other properties in the `odataError` object? Specifically the `ClientRequestId` in the nested `InnerError` object as well as properties in the AdditionalData?

**Comment by ChrisGrove** [comment]
@andrueastman Yes it still fails with the same error.

Additional data from the odataError Object:

Error->AdditionalData[0]->Key = innerError
Error->AdditionalData[0]->Value = ValueKind = Object : "{"message":"AclCheckFailed-Send Message: Initiator (8:orgid:xxxxxx6cc5b1) is is not allowed to send message","code":"60011","innerError":{},"date":"2023-03-28T10:40:13","request-id":"c890dcc2-2a01-4479-9be4-0ae3268df170","client-request-id":"beebecd4-2064-4d55-9e95-e04ee604d1e1"}"

Note: 6cc5b1 is the correct guid for the user account singed in with the UsernamePasswordCredential

odataError object:
![image](https://user-images.githubusercontent.com/25799273/228213226-a04540f5-fe55-4389-acca-c9ce9ffb0169.png)

**Comment by andrueastman** [comment]
Thanks for this @ChrisGrove,

As it looks like the relevant permissions needed are present in the token, we've raised this with the relevant API team to get feedback on what's wrong with the request and will give feedback once we get more information on this. 

https://portal.microsofticm.com/imp/v3/incidents/details/378254123/home
