### ISSUE TITLE
ItemsRequestBuilder Query Options Expand Bug

### ISSUE THREAD

**Issue by timdipaula** [microsoftgraph/msgraph-sdk-dotnet#1771]
**Describe the bug**
There is a misconfigured url being generated using the ItemsRequestBuilder with the Expand query option in the 5.3 version.

To reproduce:

1.  Run this code in c# 5.3 version.

var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "fields(select=Title)" };
});

2.  Capture the resulting url with the misconfigured $ expand.
https://graph.microsoft.com/v1.0/sites/{MY SITE ID}/lists/{MY LIST ID}/items?$select=id,name,sharepointIds&$expand=fields(select=Title)

3.  Notice there is a $ prior to the expand key word that is causing the error.  
4. 
5. Running the URL in Graph Explorer and notice the error.  
6. Remove the $ infront of the Expand and it works.

https://graph.microsoft.com/v1.0/sites/{MY SITE ID}/lists/{MY LIST ID}/items?expand=fields(select=Title)

**Expected behavior**
The url is correctly produced.

**Comment by andrueastman** [comment]
Thanks for raising this @timdipaula 

I believe for this to work, the nested select statement should also align to the expand.

```cs
var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.GetAsync((requestConfiguration) =>
{
requestConfiguration.QueryParameters.Expand = new string []{ "fields($select=Title)" };
});
```

**Comment by timdipaula** [comment]
Thank you.  Adding the “$” in front of the “select” word did the trick.
