### ISSUE TITLE
GetByPath is not able on  Microsoft.Graph 5.3.0 or Exists a workaround?

### ISSUE THREAD

**Issue by JulioMunozc** [microsoftgraph/msgraph-sdk-dotnet#1772]
**Describe the bug**
The method `GetByPath`  is not able in the GraphServiceClient like in previous versions, the message got is `SiteRequestBuilder does not contain a definition for 'GetByPath' and no accessible extension method 'GetbyPath' accepting a first argument of type 'SiteRequestBuilder' could be found (are you missing a using directive or an assembly reference?`

**To Reproduce**
Have installed the version Microsoft.Graph version 5.3.0
use a code like this:
```C#
     site = GraphServiceClient.Sites.GetByPath(validator.SiteName, uriSite.Host).GetAsync().Result;
```

**Expected behavior**
Rertrieve an object Microsoft.Graph.Models.Site using GetByPath method

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @JulioMunozc 

Any chance this works out for you? https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1693
