### ISSUE TITLE
V5 Clone Team method doesn't have a return result

### ISSUE THREAD

**Issue by idealser** [microsoftgraph/msgraph-sdk-dotnet#1778]
I'm migrating from V4. Previously to clone a Team we could use this code:
```cs
var response =  GraphClient.Teams[team.Id].Clone(...params).Request().PostResponseAsync();
var location = response.HttpHeaders.Location.ToString();
// get the result from location URL
```

In V5 it's something like this:
```cs
var body = new Microsoft.Graph.Teams.Item.Clone.ClonePostRequestBody
{
// params
};
await GraphClient.Teams[team.Id].Clone.PostAsync(body);
```

The new V5 Clone method doesn't have a return result. By the fact, Create team request which also worked on V4 with location URL now returns us an instance of created Team. Clone request for some reason doesn't.

What is the recommended approach to get the cloned team in V5?

**Comment by andrueastman** [comment]
Thanks for raising this @idealser 

Any chance this works out for you?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object

```cs
        var nativeResponseHandler = new NativeResponseHandler();
        var body = new Microsoft.Graph.Teams.Item.Clone.ClonePostRequestBody
        {
            // params
        };
        await graphClient.Teams["team-id"].Clone.PostAsync(body, requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler }));

        var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
        var locationheader = responseMessage.Headers.Location.OriginalString;
```

**Comment by andrueastman** [comment]
Thanks for confirming. 
As the API response does not return an object at the moment, but an operation there is plans to add an long running operation handler at https://github.com/microsoftgraph/msgraph-sdk-design/issues/83

https://learn.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0&tabs=http#response-1

**Comment by idealser** [comment]
> Thanks for raising this @idealser
> 
> Any chance this works out for you? https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object
> 
> ```cs
>         var nativeResponseHandler = new NativeResponseHandler();
>         var body = new Microsoft.Graph.Teams.Item.Clone.ClonePostRequestBody
>         {
>             // params
>         };
>         await graphClient.Teams["team-id"].Clone.PostAsync(body, requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler }));
> 
>         var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
>         var locationheader = responseMessage.Headers.Location.OriginalString;
> ```

Also, in case you have a 400 error during the Post call, responseMessage.Headers.Location.will be null, and you will get an ObjectReference exception. So there is a need to add hadling of unsuccessful results since PostAsync won't throw you any error because we have a custom response handler
