### ISSUE TITLE
Drive item delta request is removed in Graph SDK V5

### ISSUE THREAD

**Issue by vadrsa** [microsoftgraph/msgraph-sdk-dotnet#1780]
I can't find the following endpoint in Graph SDK V5, `_client.Users[userId].Drives[driveId].Root.Delta().Request().`
What is the alternative when upgrading in v4 to v5?

**Comment by andrueastman** [comment]
Thanks for raising this @vadrsa 

We'll close this for now as this is covered in the upgrade guide

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths

**Comment by vadrsa** [comment]
@andrueastman With all due respect, I have gone over the upgrade doc multiple times before submitting this issue. There isn't a mention of delta request on the

**Comment by vadrsa** [comment]
@andrueastman this is the endpoint I want to call "GET /drives/{drive-id}/root/delta" if it's something I am missing from the doc just tell me before closing.

**Comment by andrueastman** [comment]
> @andrueastman With all due respect, I have gone over the upgrade doc multiple times before submitting this issue. There isn't a mention of delta request in the doc.

Apologies for this miscommunication @vadrsa 

Essentially, the nested paths would be accessed after accessing the user's drive id.  

```cs
// Get the user's driveId
var driveItem = await graphServiceClient.Users["user-id"].Drive.GetAsync();
var userDriveId = driveItem.Id;
// List the delta in the drive
var children = await graphServiceClient.Drives[userDriveId].Items["itemId"].Delta.GetAsync();
```

**Comment by vadrsa** [comment]
@andrueastman Thanks for the quick response, I saw that but wasn't sure its the same endpoint.
So basically the closest I can get to `/drives/{drive-id}/root/delta` is `/drives/{drive-id}/items/root/delta`.
Will this work?
