### ISSUE TITLE
[Client bug]: Microsoft.Graph 5.4.0 generates invalid request Uris for GetDirectRoutingCallsWithFromDateTimeWithToDateTime 

### ISSUE THREAD

**Issue by sopelt** [microsoftgraph/msgraph-sdk-dotnet#1787]
**Describe the bug**
When calling `CallRecordsGetDirectRoutingCallsWithFromDateTimeWithToDateTime` the current Microsoft.Graph SDK/client generates a wrong request URL (resulting in HTTP 404) and invalid filter parameter format (resulting in HTTP 404 as well as the route doesn't seem to match). This is a followup/related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1443 and potentially https://github.com/microsoft/OpenAPI.NET.OData/issues/262 and I hope @andrueastman will have a look at this as well.

As far as I can tell this did not work yet in any dotnet graph SDK version.

**To Reproduce**
```csharp
var response = await GraphServiceClient.Communications.CallRecords.CallRecordsGetDirectRoutingCallsWithFromDateTimeWithToDateTime(fromDateTime, toDateTime).GetAsync();
```

**Expected behavior**
Call records are being returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/738714/228643624-c3e261a7-634c-4893-83c3-87d6f00d9211.png)

**Client version**
https://www.nuget.org/packages/Microsoft.Graph/5.4.0

**Desktop (please complete the following information):**
 - Win11
 - .NET 6.0

**Workaround**

The following snippet shows how to override the url template and encode the parameters in the working format:

```csharp
var dateFormat = "yyyy-MM-dd";

var parameters = new Dictionary<string, object>
{
    { "fromDateTime", fromDateTime.ToString(dateFormat, CultureInfo.InvariantCulture) },
    { "toDateTime", toDateTime.ToString(dateFormat, CultureInfo.InvariantCulture) }
};

var requestBuilder = new CallRecordsGetDirectRoutingCallsWithFromDateTimeWithToDateTimeRequestBuilder(parameters, GraphServiceClient.RequestAdapter);
var requestInfo = requestBuilder.ToGetRequestInformation();
requestInfo.UrlTemplate = "{+baseurl}/communications/callRecords/getDirectRoutingCalls(fromDateTime={fromDateTime},toDateTime={toDateTime}){?%24top,%24skip,%24search,%24filter,%24count}";
var response = await GraphServiceClient.RequestAdapter.SendAsync(requestInfo, GetDirectRoutingCallsWithFromDateTimeWithToDateTimeResponse.CreateFromDiscriminatorValue);
```

**Comment by baywet** [comment]
As far as I can tell those are both bugs at the AGS/workload level. OData is format on that aspect: any method can be called with its fully qualified name, the aliased name, or the method name. The fact that the workload doesn't understand when we send the aliased name means that they are not OData compliant. AGS *could* help with that by replacing aliased names by the fully qualified one, or stripping the alias.

**Comment by baywet** [comment]
After further investigations:
```
GET https://graph.microsoft.com/v1.0/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)?$whatif

{
    "Description": "Execute HTTP request",
    "Uri": "https://plat.teams.microsoft.com/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)",
    "HttpMethod": "GET",
    "TargetWorkloadId": "Microsoft.IC3.DataPlatform"
}
```

```
GET https://graph.microsoft.com/v1.0/communications/callRecords/getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)?$whatif

{
    "Description": "Execute HTTP request",
    "Uri": "https://plat.teams.microsoft.com/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)",
    "HttpMethod": "GET",
    "TargetWorkloadId": "Microsoft.IC3.DataPlatform"
}
```

```
GET https://graph.microsoft.com/v1.0/communications/callRecords/callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)?$whatif

{
    "Description": "Execute HTTP request",
    "Uri": "https://plat.teams.microsoft.com/communications/callRecords('callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)')",
    "HttpMethod": "GET",
    "TargetWorkloadId": "Microsoft.IC3.DataPlatform"
}
```

So it's effectively AGS messing up the request. We should probably open an ICM on them.

**Comment by andrueastman** [comment]
Thanks for this @baywet 

Taking a look at the URI's above, it looks like the first two generate the same URI with the full namespace and with the whole namespace stripped.
`https://plat.teams.microsoft.com/communications/callRecords/microsoft.graph.callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)`

While the third one generates
`https://plat.teams.microsoft.com/communications/callRecords('callRecords.getDirectRoutingCalls(fromDateTime=2023-03-25,toDateTime=2023-03-29)')`

As the metadata does not have an alias for the `microsoft.graph.callRecords` namespace I suspect that it might be an error with the indiscriminate stripping of the `microsoft.graph` prefix for methods.

![image](https://user-images.githubusercontent.com/6464005/228874095-b7a00239-1a2e-4619-9be1-2df27e93f5b6.png)

**Comment by baywet** [comment]
ah, so there's no alias being defined? then yes, it's an issue of the conversion process. Thanks for colling this out.

**Comment by andrueastman** [comment]
This would be the same for https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1691 as the `microsoft.graph.security` namespace also does not have an alias.
