### ISSUE TITLE
Single Value Extended Property comes with null instead of the ID

### ISSUE THREAD

**Issue by ciprif** [microsoftgraph/msgraph-sdk-dotnet#179]
Hello,
I have the following code that used to work until a week ago or so.

`contactsResult = await graphClient.Me.ContactFolders[contactFolder].Contacts.Request().
                        Select("id,DisplayName,EmailAddresses,SingleValueExtendedProperties").
                        Expand("singleValueExtendedProperties($filter=id eq 'String 0x3a25' or id eq 'String 0x3a24')").
                        GetAsync();`

It returned a collection of contacts and under the each element from the **SingleValueExtendedProperties** property of the contact I used to have the following fields populated: **id** and **value**. 

Starting from today I noticed that the **value** comes unchanged but the **id** is always **null**.

It doesn't make much sense since the filter is done based on an **id** so , if I have the value present in the collection it must have matched a filter hence it has an **id**, hence **null** seems out of place.

Can anyone bring some light in this matter?

Kind regards,

Ciprian

**Comment by MIchaelMainer** [comment]
This is not expected by me.

Can you provide us the HTTP request and response for this? Please remove the authorization header before sharing.

**Comment by ciprif** [comment]
Hello Michael,

For simplicity reasons I removed the order and skip from my initial post. Those should not affect the properties returned. This is the Request URI where the GET goes.

`https://graph.microsoft.com/v1.0/me/contactFolders/Contacts/contacts?$skip=0&$select=id,DisplayName,EmailAddresses,SingleValueExtendedProperties&$expand=singleValueExtendedProperties($filter=id%20eq%20'String%200x3a25'%20or%20id%20eq%20'String%200x3a24')&$orderby=displayName`

The headers, excluding the Authorization, contain the SdkVersion:

`"SdkVersion":"Graph-dotnet-1.5.1"`

Method: GET

Version: 1.1

Content: null

Kind regards,

Ciprian

**Comment by MIchaelMainer** [comment]
Can you provide the response?

**Comment by ciprif** [comment]
Hello Michael,

I'm doing the call through the SDK so the response is de-serialized in a collection. May I ask why is this relevant? I get the columns I ask for in the select query but I'm not getting the proper values for the singleValueExtendedProperties queries. I only get the value, no ID. The ID is relevant in my code logic. 

Does the request I've posted above provide you with proper values for these? I feel like we are diverging from the initial question.

Kind regards,

Ciprian

**Comment by MIchaelMainer** [comment]
We aren't diverging from your initial ask. Asking for the response is relevant to help me understand whether the issue is caused by the service or the client library. We updated the client library about a week ago, and the service is being updated very often. I want to rule out the service at this point. Please provide me a partial response body that includes the first contact.

**Comment by ciprif** [comment]
Hello Michael,

Fair point :)

Is this helping?

```
{
   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('f4ot1%40outlook.com')/contactFolders('Contacts')/contacts(id,displayName,emailAddresses,singleValueExtendedProperties)",
   "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/contactFolders/Contacts/contacts?$skip=10&$select=id%2cDisplayName%2cEmailAddresses%2cSingleValueExtendedProperties&$expand=singleValueExtendedProperties(%24filter%3did+eq+%27String+0x3a25%27+or+id+eq+%27String+0x3a24%27)&$orderby=displayName",
   "value": [
      {
         "@odata.etag": "W/\"EQAAABYAAACcpGZocUNsQqdqKT/91UEAAAERLOmC\"",
         "id": "AQMkADAwATMwMAItZmMzZi0xOTViLTAwAi0wMAoARgAAA7gln3M15BlGjwgPvqQKjScHAJykZmhxQ2xCp2opP-3VQQAAAwEOAAAAnKRmaHFDbEKnaik--dVBAAAAAREZD7sAAAA=",
         "displayName": "0_Michelle_Test Test",
         "emailAddresses": [],
         "singleValueExtendedProperties@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('f4ot1%40outlook.com')/contactFolders('Contacts')/contacts('AQMkADAwATMwMAItZmMzZi0xOTViLTAwAi0wMAoARgAAA7gln3M15BlGjwgPvqQKjScHAJykZmhxQ2xCp2opP-3VQQAAAwEOAAAAnKRmaHFDbEKnaik--dVBAAAAAREZD7sAAAA%3D')/singleValueExtendedProperties",
         "singleValueExtendedProperties": [
            {
               "value": "00498912504001446"
            }
         ]
      }
```

**Comment by MIchaelMainer** [comment]
Yes, this is very helpful. The id property is not being sent by the service. The client library is correct. The response body should look more like this:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/singlevaluelegacyextendedproperty_get#request-body

I'll notify the service owners about this. Thank you for sharing this with us.

**Comment by ciprif** [comment]
Thank you for your responses and for your help.

**Comment by ciprif** [comment]
Hello again Michael,

Do we have an estimate from the Service Team? 

Kind reagards,

Ciprian

**Comment by MIchaelMainer** [comment]
I don't have an update for you right now. I'll update this issue when I have more information.

**Comment by MIchaelMainer** [comment]
This issue is being addressed. I don't yet have a time table

**Comment by ciprif** [comment]
Hello Michael,
I've noticed the Service started giving us the id again. I'm assuming the issue has been resolved. Thank you for your help and assistance.

Regards,

Ciprian

**Comment by MIchaelMainer** [comment]
Hello Ciprian, thank you for following up with us and letting us know that the issue has been resolved for you.
With regards,
Michael
