### ISSUE TITLE
Add custom query parameters in the latest version of Graph API (5.3.0)

### ISSUE THREAD

**Issue by shirkhanyanhripsime** [microsoftgraph/msgraph-sdk-dotnet#1790]
I am using Graph SDK. After upgrading Graph Api to the latest version (5.3.0), I can no longer use QueryOptions to include more specific behavior during a request that is not supported by the library (e.g., add payment model /Model A/ to the request).
What can I use instead?
![image](https://user-images.githubusercontent.com/129367500/228762073-923c4bce-d3bb-4cdb-ac78-005c269daa35.png)

**Comment by vadrsa** [comment]
@andrueastman Can you help with this?

**Comment by andrueastman** [comment]
Thanks for raising this @shirkhanyanhripsime 

This looks to be an issue with the metadata that needs to be fixed. In the meantime, the call can be made with the SDK as follows.

```cs
            var requestInformation = graphClient.Teams["{team-id}"].Channels.GetAllMessages.ToGetRequestInformation();
            requestInformation.UrlTemplate = requestInformation.UrlTemplate.Insert(requestInformation.UrlTemplate.Length-1,",model");
            requestInformation.QueryParameters.Add("model", "A"); //set the model parameter
            var result = await graphClient.RequestAdapter.SendAsync<GetAllMessagesResponse>(requestInformation, GetAllMessagesResponse.CreateFromDiscriminatorValue);
```

**Comment by andrueastman** [comment]
Closing this as this was resolved via https://github.com/microsoftgraph/msgraph-metadata/pull/370
