### ISSUE TITLE
Serializer mishandles dates inside strings

### ISSUE THREAD

**Issue by NeilWhite** [microsoftgraph/msgraph-sdk-dotnet#180]
When loading (for example) Events, or I suspect anything that contains a `DateTimeTimeZone` property, from a response, the serializer turns the ISO8061 date into a string formatted using the current locales settings. 

eg: this test will fail
```CS
        [Test]
        public void SerializerRoundTripsDates()
        {
            var eventIn = new Event { Start = new DateTimeTimeZone { DateTime = "2017-10-11T07:30:00.0000+00:00", TimeZone = "UTC" } };
            var serializer = new Serializer();
            var json = serializer.SerializeObject(eventIn);
            var eventRoundTrip = serializer.DeserializeObject<Event>(json);

            Assert.AreEqual(eventIn.Start.DateTime, eventRoundTrip.Start.DateTime);
        }
```
This can be resolved by updating the Serializers default settings to include `DateParseHandling = DateParseHandling.None`

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. We'll take at your pull request.
