### ISSUE TITLE
Shared OneDrives in v5

### ISSUE THREAD

**Issue by develerik** [microsoftgraph/msgraph-sdk-dotnet#1800]
Hi,

I'm trying to migrate from v4 to v5, but cannot find an equivalent for
```csharp
IDriveSharedWithMeCollectionPage sharedDrives = await graphClient.Me.Drive.SharedWithMe()
  .Request().GetAsync();
```

I use this function to find the id of a shared drive by its name.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths

Any chance this works out for you?
```
        var myDrive = await graphServiceClient.Me.Drive.GetAsync();
        var items = await graphServiceClient.Drives[myDrive.Id].SharedWithMe.GetAsync();
```

**Comment by develerik** [comment]
Yes, this works

Thank you very much :)
