### ISSUE TITLE
Filter not working Filter Event by Location

### ISSUE THREAD

**Issue by marcobeckergh** [microsoftgraph/msgraph-sdk-dotnet#1801]
**Describe the bug**

**To Reproduce**

until MSGRAPH v4.54 this was working:

var formattedFilterString = Location\DisplayName%20+eq%20'{filterValue}'");

List<QueryOption> options = new List<QueryOption>
                {
                     new QueryOption("$filter", formattedFilterString) // OK
                };

                var returnEvent = await exchangeClient
                                    .Users[userEmail]
                                    .Calendar
                                    .Events
                                    .Request(options)
                                    .Select(m => new
                                    {
                                        m.Id,
                                        m.Location,
                                        m.ResponseStatus
                                    })
                                    .GetAsync();

                returnValue = returnEvent;

Since v5:

var formattedFilterString = location\displayName%20+eq%20'{filterValue}'");

await exchangeClient
                    .Users[userEmail]
                    .Calendar
                    .Events
                    .GetAsync((requestConfiguration) => {
                        requestConfiguration.Options.Add(new ResponseHandlerOption() { ResponseHandler = nativeResponseHandler });
                        requestConfiguration.QueryParameters.Filter = formattedFilterString;
                        requestConfiguration.QueryParameters.Select = new string[] { "id", "location" };
                    });

**Expected behavior**
I would exprect the return of an Event matching the Filterstring
Instead i get an "invalid Filter Clause"

**Screenshots**
![gitmaspraph_mb](https://user-images.githubusercontent.com/129664982/229352356-20cbc077-d02c-4390-8c6b-719749f29dc7.png)

**Comment by andrueastman** [comment]
Thanks for raising this @marcobeckergh 

V5 uses URL templates which should provide consistent URL encoding and thus no need to do that before passing the parameter. Any chance it works for you if you simply pass an unencoded filter string? 

```
var formattedFilterString = $"location\\displayName eq '{filterValue}'";
```

**Comment by marcobeckergh** [comment]
@andrueastman 
Thank for your Response. Unfortunatly this does not work. If i leave the Filter out, i get the event i want inside the CollectionResponse. Wenn i use a Filter i get a bad Resquest Response.
Uniltered:
![unfiltered_response_http_response_msg](https://user-images.githubusercontent.com/129664982/229445845-70168f0b-a9d1-4586-b29c-7f9954d38223.png)
![unfiltered_response_01](https://user-images.githubusercontent.com/129664982/229446060-43d06cf5-ae68-4940-a8a8-a9527c4542df.png)



Filtred:

![example_unencoded_filterstring](https://user-images.githubusercontent.com/129664982/229445740-d5d05bfa-69ce-41a1-84d9-efb2f5b3be82.png)

**Comment by andrueastman** [comment]
Thanks for following up @marcobeckergh 

Taking a look at the documentation at the link below,
https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http

I believe it should be

```cs
var formattedFilterString = $"location/displayName eq '{filterValue}'";
```

**Comment by marcobeckergh** [comment]
@andrueastman 
Thank you. So far i get no more "invalid filter clause". But somehow the Filter does not work.
See result of the httpresponse 

OK but no value:

![01](https://user-images.githubusercontent.com/129664982/229795149-ade1517e-7901-45d1-b6c6-0c5cad59eee5.png)

but the event event exists:
![02](https://user-images.githubusercontent.com/129664982/229795323-9b6c3ba0-b30d-4577-b0c4-62c81f1028ef.png)

Returning the request as EventCollectionresponse is empty too.
Do you have any idea?

**Comment by andrueastman** [comment]
I created a similar event and used the same location to verify and was not able to replicate this as the result is in the response. Is there any chance the location name contains some whitespace characters around it?

Possibly any chance you can get the URI and paste in the graph explorer to replicate? 

https://developer.microsoft.com/en-us/graph/graph-explorer

```cs
         var requestInformation = graphClient
             .Users["user-id"]
             .Calendar
             .Events
             .ToGetRequestInformation((requestConfiguration) => {
                 requestConfiguration.QueryParameters.Filter = formattedFilterString;
                 requestConfiguration.QueryParameters.Select = new string[] { "id", "location" };
             });

         var uriString = requestInformation.URI.OriginalString; // paste result in GE
```

**Comment by marcobeckergh** [comment]
@andrueastman 

Sure. here it is: Unfiltered, the Event is there
![01](https://user-images.githubusercontent.com/129664982/230075918-523644b0-7db9-4a17-a393-b8dda843d1f3.png)

filtered result

![02](https://user-images.githubusercontent.com/129664982/230076250-d50ae145-9620-4618-acec-6e9a6555ef38.png)
