### ISSUE TITLE
Not possible to Create new Contact

### ISSUE THREAD

**Issue by trust11** [microsoftgraph/msgraph-sdk-dotnet#1803]
**Describe the bug**
Not possible to create a new contact in V4.54
Contact is form copied from here https://learn.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-1.0&tabs=http

**To Reproduce**
![image](https://user-images.githubusercontent.com/50418856/229702159-518a24db-3f79-4d3b-809a-037d7340b95e.png)

![image](https://user-images.githubusercontent.com/50418856/229702096-8e0d1889-af08-4a89-9fc5-af724a7f4728.png)
`{
  "BusinessPhones": [
    "+1 732 555 0102"
  ],
  "EmailAddresses": [
    {
      "Address": "pavelb@fabrikam.onmicrosoft.com",
      "Name": "Pavel Bansky"
    }
  ],
  "GivenName": "Pavel",
  "Surname": "Bansky",
  "ODataType": "microsoft.graph.contact"
}`

So i took the request body and run it in the ms graph explorer:
![image](https://user-images.githubusercontent.com/50418856/229702875-c6d34061-341c-4730-b86b-5b55a0281b0a.png)

After removing the ODataType and run it again - It works as expected:
![image](https://user-images.githubusercontent.com/50418856/229703102-baea497d-2861-476a-abaa-0d2ee7039c43.png)

**Expected behavior**
User created or at least throw an error

**Comment by andrueastman** [comment]
Thanks for raising this @trust11 

Just to confirm, is the error occuring when using the SDK or when you transfer the Json string from the SDK? 

The json string looks inconsistent with what the SDK would use, Any chance you get the same string when you do this.

```cs
var jsonString = graphServiceClient.HttpProvider.Serializer.SerializeObject(requestBody);
```

**Comment by trust11** [comment]
Thanks @andrueastman 
It is occuring when using the SDK.

The result of var jsonString
![image](https://user-images.githubusercontent.com/50418856/229727558-e3b7f921-58e0-4d38-9f2f-304509332147.png)

**Comment by trust11** [comment]
By the way, it also fails when I have only Surname and GivenName
![image](https://user-images.githubusercontent.com/50418856/229728433-b0513e94-f6ef-4f6e-b158-b2eb33bd3e1c.png)

**Comment by andrueastman** [comment]
Any chance you are able to share the error you get when you make the call using the SDK? From my end, the following creates the contact successfully with version 4.54.0

```cs
            var requestBody = new Contact
            {
                GivenName = "Pavel",
                Surname = "Bansky",
                EmailAddresses = new List<EmailAddress>
                {
                    new EmailAddress
                    {
                        Address = "pavelb@fabrikam.onmicrosoft.com",
                        Name = "Pavel Bansky",
                    },
                },
                            BusinessPhones = new List<string>
                {
                    "+1 732 555 0102",
                }
            };

            var result = await graphServiceClient.Me.Contacts.Request().AddAsync(requestBody);
```

**Comment by trust11** [comment]
I restarted now even my computer and as soon the last line of your code runs, the whole application stops without an Exception.
We have numerous places used the graphServiceClient without issues. So, I'm lost at the moment. Any advice?

**Comment by andrueastman** [comment]
Any chance you see anything logged in the console of the IDE you can share to help understand this?

**Comment by trust11** [comment]
The Problem is that there is not one character to read as the application just gets killed, withou dump or Error
________________________________
Von: Eastman ***@***.***>
Gesendet: Dienstag, 4. April 2023 11:38
An: microsoftgraph/msgraph-sdk-dotnet ***@***.***>
Cc: trust11 ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/msgraph-sdk-dotnet] Not possible to Create new Contact (Issue #1803)


Any chance you see anything logged in the console of the IDE you can share to help understand this?

**Comment by trust11** [comment]
Hi @andrueastman 
Now it runs. I use Application permissions, so Me is not working. 
But now it runs. I am not certain why, but I must have changed something right.
My bad sorry.

**Comment by andrueastman** [comment]
As you are using app permissions you would need to change the call to 

```cs
var result = await graphServiceClient.Users["user-id"].Contacts.Request().AddAsync(requestBody);
```

As the code works, we'll close this for now @trust11. Feel free to re-open/create new issue incase of anything else.
