### ISSUE TITLE
Read Hidden Emails from the users mailbox using Graph API 5.5.0

### ISSUE THREAD

**Issue by tejasonweb** [microsoftgraph/msgraph-sdk-dotnet#1814]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

#######################################################################

Using Graph API 5.5.0, How do I read associated items from the users mailbox. I am working on a project to remove/modify the hidden messages from the mailbox however I am not able to retrieve the associated emails from the users mailbox.

Currently, I am using EWS API which gets me the list of all associated items in the folder however as EWS might not be supported in future, I want to migrate my application to Graph API.

########################################################################

### Expected behavior

var itemstask = Task.Run(() => graphClient.Users[user.Id].MailFolders[mfolder.Id].Messages.GetAsync((reqConf) =>
                                        {
                                            reqConf.QueryParameters.IncludeHiddenMessages = true;
                                        }));

### Actual behavior

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters' does not contain a definition for 'IncludeHiddenMessages' and no accessible extension method 'IncludeHiddenMessages' accepting a first argument of type 'MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters' could be found (are you missing a using directive or an assembly reference?)	GraphTesting	C:\Users\tejas.rajput\OneDrive - Veritas Technologies LLC\Documents\source\repos\GraphTesting\Program.cs	108	Active

### Steps to reproduce the behavior

As mentioned in Expected Behavior.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1680#issuecomment-1467669668

**Comment by tejasonweb** [comment]
I do not seem to get it working. In Graph Explorer (V1.0), I do not see the hidden emails for user using below request:

https://graph.microsoft.com/v1.0/me/messages?Includehiddenmessages=true

My code with MSGraph 5.6.0 still erroring out with:

Error	CS1061	'MailFoldersRequestBuilder.MailFoldersRequestBuilderGetQueryParameters' does not contain a definition for 'Includehiddenfolders' and no accessible extension method 'Includehiddenfolders' accepting a first argument of type 'MailFoldersRequestBuilder.MailFoldersRequestBuilderGetQueryParameters' could be found (are you missing a using directive or an assembly reference?)	GraphTesting	\repos\GraphTesting\Program.cs	91	Active

Am I missing something?

**Comment by andrueastman** [comment]
As https://github.com/microsoftgraph/msgraph-metadata/pull/319 was merged after release of 5.6.0, we should see this in the next metadata release early(5.7.0) in the week.

**Comment by tejasonweb** [comment]
Great, Thanks for the update!
