### ISSUE TITLE
Documentation update for Intune calls, specific about IOS/DEP/ABM

### ISSUE THREAD

**Issue by DC-MORTR** [microsoftgraph/msgraph-sdk-dotnet#1818]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Better documentation of the .NET library

**Describe alternatives you've considered**
None

**Additional context**
I'm trying to write a small extension for an in-house developed management app for our world-wide helpdesk, to aid them assign profiles for ABM/DEP devices in Intune.
But I cannot figure out the correct call to assign a new profile with C#.

Currently I have this which does not work:

```
        public async void SetProfile(string DeviceID, string ProfileName)
        {
            ImportedAppleDeviceIdentity ii = new ImportedAppleDeviceIdentity();
            ii.SerialNumber = DeviceID;

            foreach (EnrollmentProfile profile in EnrollmentProfiles)
            {
                if (profile.DisplayName == ProfileName)
                {
                    ii.RequestedEnrollmentProfileId = profile.Id;
                    break;
                }
            }

            ImportedAppleDeviceIdentity result = await graphClient.DeviceManagement.DepOnboardingSettings["REDACTED"].ImportedAppleDeviceIdentities.PostAsync(ii);
        }

```

It just renders an OData error about no route.

**Comment by andrueastman** [comment]
Thanks for raising this @DC-MORTR 

Just to confirm, is there any chance you are able to also replicate this on the Graph Explorer when you make the call?
https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by DC-MORTR** [comment]
The problem is more like I have no idea which call to make as documentation is non-existing for this

**Comment by DC-MORTR** [comment]
Okay - this *might* be the correct call, but again I'm certainly not sure:

`https://graph.microsoft.com/beta/deviceManagement/depOnboardingSettings/{depOnboardingSetting-id}/importedAppleDeviceIdentities/{importedAppleDeviceIdentity-id}`

Request body:
```
{
    "requestedEnrollmentProfile": "ProfileID"
}
```

But this still just casts an error:

```
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation/key with http verb PATCH for request /DeviceEnrollmentFE_2303/StatelessDeviceEnrollmentFEService/deviceManagement/depOnboardingSettings('{depOnboardingSetting-id}')/importedAppleDeviceIdentities({importedAppleDeviceIdentity-id}).",
        "innerError": {
            "date": "2023-04-14T07:27:58",
            "request-id": "4308e47f-478d-482b-b3d5-a9c9c44bd986",
            "client-request-id": "5fea431c-2c67-ec49-9b7b-df441df716d0"
        }
    }
}
```

**Comment by DC-MORTR** [comment]
Figured it out during the day, how to make the calls
