### ISSUE TITLE
Serialise planner tasks fails if they have references or checklistitems

### ISSUE THREAD

**Issue by weshackett** [microsoftgraph/msgraph-sdk-dotnet#182]
I'm using the Planner API to pull in an existing planner plan and store it as a json template. Placing calls to each endpoint returns the expect Json.

Example call for the task details object

 var plannerTaskDetailsJson = await new HttpClient().GetWithAuthAsync(accessToken, "https://graph.microsoft.com/v1.0/planner/tasks/" + task.Id + "/details");

                        if (plannerTaskDetailsJson == null)
                        {
                            //return null;
                        }
                        else
                        {
                            var plannerTaskDetails = JsonConvert.DeserializeObject<PlannerTaskDetails>(plannerTaskDetailsJson.ToString());
}

Example json returned (plannerTaskDetailsJson)

{{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#planner/tasks('7MXRnMF-R0KZ9foqbpqgtZYAM5Qf')/details/$entity",
  "@odata.etag": "W/\"JzEtVGFza0RldGFpbHMgQEBAQEBAQEBAQEBAQEBAdCc=\"",
  "description": "Once the new Intranet content is completed they can be shared with the team.",
  "previewType": "checklist",
  "references": {
    "https%3A//**********%2Esharepoint%2Ecom/sites/guide/SitePages/Guide%2Easpx": {
      "@odata.type": "#microsoft.graph.plannerExternalReference",
      "alias": "Guide",
      "type": "Other",
      "previewPriority": "8586969008418952760PS",
      "lastModifiedBy": {
        "user": {
          "displayName": null,
          "id": "4c6e9f9b-4262-4ffa-b76d-bf5bd54f6ce0"
        }
      },
      "lastModifiedDateTime": "2017-09-06T13:55:03.738Z"
    }
  },
  "checklist": {
    "62264": {
      "@odata.type": "#microsoft.graph.plannerChecklistItem",
      "isChecked": false,
      "title": "Publish Intranet content",
      "orderHint": "8586969008263869086P;",
      "lastModifiedBy": {
        "user": {
          "displayName": null,
          "id": "4c6e9f9b-4262-4ffa-b76d-bf5bd54f6ce0"
        }
      },
      "lastModifiedDateTime": "2017-09-06T13:55:34.411Z"
    }
  },
  "id": "7MXRnMF-R0KZ9foqbpqgtZYAM5Qf"
}}

If that deserialised object is then re-serialised to Json an exception is thrown if either the references or checklist collections contain anything

Exception info:

'JsonConvert.SerializeObject(plannerTaskDetails)' threw an exception of type 'System.Reflection.TargetInvocationException'
"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)\r\n   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnSerializing(Object o, StreamingContext context)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(JsonWriter writer, JsonContract contract, Object value)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)\r\n   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)"

InnerException:
{"An item with the same key has already been added."}
"   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)\r\n   at Microsoft.Graph.PlannerExternalReference.AddODataType(StreamingContext context)"

**Comment by MIchaelMainer** [comment]
I think what's happening is that when it is deserialized, the @odata.type property is captured in the AdditionalData dictionary. Then, when you go to serialize it, [the AddODataType method ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Extensions/PlannerExternalReference.cs#L26)is trying to add the @odata.type property to the AdditionalData dictionary. That'd make the exception. This is an issue in the client library. 

We need to update AddODataType to check that the entry doesn't already.
