### ISSUE TITLE
client.Users["user@domain.com"].Messages.Request() is not available

### ISSUE THREAD

**Issue by yogigrantz** [microsoftgraph/msgraph-sdk-dotnet#1822]
when we try to get more than 10 emails at a time, coded this way:

`
          var client = new GraphServiceClient(authenticationProvider);
          var messages = await client.Users["user@domain.com"].Messages.Request().Top(100).GetAsync();
`

.Request() would show squiggly underneath, saying that the method is not available to use. Then, could someone please help me with .Top(maxNbrOfEmails) functionality? This squiggly is happening in Microsoft.Graph 5.2.0 and 5.6.0

I also posted my question in StackOverflow: https://stackoverflow.com/questions/75998992/get-all-email-messages-with-microsoft-graph-version-5-2-0-or-above

**Comment by MartinM85** [comment]
Check migration doc how to set query parameters: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#query-parameter-options

**Comment by yogigrantz** [comment]
Thank you @MartinM85 ! The new working syntax is: 

`            GraphServiceClient graphClient = new GraphServiceClient(cap);

            MessageCollectionResponse? messages = await graphClient.Users[_oAuth2DTO.UserName].MailFolders[emailFolderName].Messages.GetAsync(x => { x.QueryParameters.Top = nbrOfEmails; });
`
