### ISSUE TITLE
[Client bug]: Cannot create printJob for a printerShare in v5

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1823]
**Describe the bug**
There is an endpoint to create a `printJob` for a `printerShare`

    POST /print/shares/{printerShareId}/jobs

but there is no way to create `printJob` by using SDK v5

`Microsoft.Graph.Print.Shares.Item.PrinterShareItemRequestBuilder` does not contain any `Jobs` property

**To Reproduce**

    await _client.Print.Shares[$"{shareId}"].Jobs.PostAsync(...);

Fails to compile

**Expected behavior**
Can create a printJob for a printerShare in SDK v5

**Screenshots**

**Client version**
5.6.0

**Desktop (please complete the following information):**
 - OS: Win 11

**Additional context**

**Comment by SonOfJesseAsSnekithan** [comment]
Migrated my code to v5.0 sdk, now, I am having the same problem and looking for the fix. Thanks.
