### ISSUE TITLE
How to get all site collections using MS Graph .Net SDK ?  

### ISSUE THREAD

**Issue by Shmata** [microsoftgraph/msgraph-sdk-dotnet#1826]
Hi guys, 

I have a question, I am just wondering how I can get all Site Collection using MS Graph .Net SDK ? This is my code.
```
        public async Task<List<Site>> GetSitesAsync()
        {
            var graphClient = GetAuthenticatedClient();
            var result = new List<Site>();
            var sites = await graphClient.Sites.GetAsync(requestConfiguration =>
            {
                requestConfiguration.QueryParameters.Search = "sharepoint";
                requestConfiguration.QueryParameters.Select = new[] { "Id", "WebUrl", "Name", "DisplayName" };
                requestConfiguration.QueryParameters.Top = 200;
            });
            return sites.Value;
        }
```

I tried **'*'**  in my code but it made an error (I don't know why?). The term  'sharepoint' will return some results but It will return AppSites and SubSites, I just need all site collections. (As it is obviously shows in MS Graph explorer) . 
![ge](https://user-images.githubusercontent.com/2398297/232042133-20eec2e8-1261-4a86-8994-daace713470f.png)

Does anyone have any ideas to help me with this, I just wanna get all Site Collection using MS Graph .Net SDK ?

**Comment by Shmata** [comment]
Thanks @andrueastman for your reply, It raises bad request error (400) .

**Comment by andrueastman** [comment]
Hey @Shmata,

I notice in the Graph Explorer snapshot, the search query is made without the `$` character as
`https://graph.microsoft.com/v1.0/sites?search=*`

Any chance the query work with the `$` character included in the search parameter? By default the SDK makes search queries as

`https://graph.microsoft.com/v1.0/sites?$search=*`

**Comment by Shmata** [comment]
Hey @andrueastman, 

I will do that and let you know about the result. Thanks for your suggested solution.

**Comment by andrueastman** [comment]
Fow now you would probably need to pass the search without the `$` character as below. 

```cs
        var requestInformation = graphClient.Sites.ToGetRequestInformation(requestConfiguration =>
        {
            requestConfiguration.QueryParameters.Select = new[] { "Id", "WebUrl", "Name", "DisplayName" };
            requestConfiguration.QueryParameters.Top = 200;
        });
        requestInformation.UrlTemplate = requestInformation.UrlTemplate.Replace("%24search", "search");
        requestInformation.QueryParameters.Add("search", "*");
        var sites = await graphClient.RequestAdapter.SendAsync<SiteCollectionResponse>(requestInformation, SiteCollectionResponse.CreateFromDiscriminatorValue);
```

**Comment by Shmata** [comment]
Thanks @andrueastman that's perfect. My problem solved.

**Comment by Shmata** [comment]
Thanks @andrueastman that's perfect. My problem solved.
