### ISSUE TITLE
Use SDK object serialization in ASP.NET and Cosmos DB serialization pipelines

### ISSUE THREAD

**Issue by BrianWhiting** [microsoftgraph/msgraph-sdk-dotnet#1827]
Is there a way to use the SDK object serialization in the ASP.NET and Cosmos DB serialization pipelines?

I've been using the v4 SDK up to this point and the objects are being serialized in both of these frameworks the same way I see them being returned by the REST API. However, with v5, these frameworks are now serializing all the null values as well as the `additionalData` and `backingStore` properties. It looks like the `@odata.type` property is also not serializing the same.

As an example, here is a `Message` object from v4 and v5 being serialized with ASP.NET. The system stores the full `Message` object in Cosmos DB then selects a few of the properties when it needs it in the UI later and also adds a few properties to AdditionalData (`branchIndex`, `branchesTo`, and `isLastMessageInConversationBranch`) that are more easily calculated in C# code versus the JavaScript front-end.

v4
![image](https://user-images.githubusercontent.com/20689065/232075401-87dd3bdb-6700-4454-b1ca-1fff545757c9.png)

v5
![image](https://user-images.githubusercontent.com/20689065/232075806-22189ec0-4264-43f7-ba72-7201e3ef2d91.png)

I've looked at this suggestion, https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1769#issuecomment-1484925244, and tried to create a `JsonConverterFactory` to use in the pipelines, but didn't know how to get the SDK serializer to utilize the `Utf8JsonReader` and `Utf8JsonWriter` objects passed into the methods of `JsonConverter` created by the factory.

**Comment by andrueastman** [comment]
We'll close this for now. 

With the latest version of the Microsoft.Graph.Core, you should also be able to use the serialization helper methods available from Kiota abstractions. https://www.nuget.org/packages/Microsoft.Graph.Core/3.1.1

```cs
var serializedString = KiotaJsonSerializer.SerializeAsString(date);
```
and
```cs
var derivedType = KiotaJsonSerializer.Deserialize<DerivedTypeClass>(stringToDeserialize);
```
