### ISSUE TITLE
[Client bug]: How to upload small file with conflictBehavior rename using SDK 5

### ISSUE THREAD

**Issue by estalldecker** [microsoftgraph/msgraph-sdk-dotnet#1830]
Hello, I'm not sure how to use the latest version of the SDK (v5) to upload a small file to the user's root drive. 
Using this code: 
```
        var drive = await _userClient.Me.Drive.GetAsync();
        using var file = File.OpenRead(@"d:\test.xlsx");
        var test = await _userClient.Drives[drive.Id.ToString()].Root.ItemWithPath("test.xslx").Content.PutAsync(file);
```
I'm able to upload the file, but the default policy according to the docs is replace, and it's indeed what's happening. 

If I modify the example in [this](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=csharp#upload-large-file-to-onedrive) link from the official doc I'm able to automatically rename files.

I'd like to avoid using the above code since I know beforehand that all the files will be smaller than the 4mb specified in the docs. 
Is there a way to upload a small file using the new SDK? Any help is appreciated.

Regards

**Comment by andrueastman** [comment]
Thanks for raising this @estalldecker 

According to the docs, this should passed through the query parameter 
https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0#instance-attributes

Any chance this works for you as this is resolved in the metadata?

```cs
        var requestInformation = graphClient.Drives[drive.Id.ToString()].Root.ItemWithPath("MediaMeta.xml").Content.ToPutRequestInformation(file);
        requestInformation.URI = new Uri(requestInformation.URI.OriginalString +"?@microsoft.graph.conflictBehavior=rename");

        var result = await graphClient.RequestAdapter.SendAsync<DriveItem>(requestInformation, DriveItem.CreateFromDiscriminatorValue);
```

**Comment by andrueastman** [comment]
> Would it be worth it if I generate a PR for the new docs explaining a case like this?

We'd be happy to accept the contribution here @estalldecker 

> BTW, you can close it since it's not a bug

Feel free to close once the PR is created
