### ISSUE TITLE
SiteItemRequestBuilder: get root directories of sharepoint subsite

### ISSUE THREAD

**Issue by WolfgangHG** [microsoftgraph/msgraph-sdk-dotnet#1834]
I try to migrate a small app to 5.6, that is accessing files on a Office365 sharepoint server, and I am stuck at the point where I want to fetch the root directories in the "Drive" object for a sharepoint subsite.

I can request the "SiteItemRequestBuilder" with this code:

```
          Microsoft.Graph.Sites.Item.Sites.Item.SiteItemRequestBuilder builder = graphClient.Sites["myserver"].Sites["mySiteId"];
```

But here I am stuck: there are no properties on this "SiteItemRequestBuilder" to access the drives.
I can fetch the Site with this code:

```
         Site site = await builder.GetAsync();
```

But now, the property "site.Drives" is obviously null.

The request builder for the root drives of my sharepoint would work:

```
          Microsoft.Graph.Sites.Item.SiteItemRequestBuilder builder = graphClient.Sites["myserver"];          
          Microsoft.Graph.Sites.Item.Drives.DrivesRequestBuilder b = builder.Drives;
          DriveCollectionResponse driveResponse = await b.GetAsync();
```

So I would expect something like "graphClient.Sites["myserver"].Sites["mySiteId"].Drives"? Also, methods like "GetByPathWithPath" are not available.

**Comment by andrueastman** [comment]
Thanks for raising this @WolfgangHG 

This is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths

Any chance this works out for you?

```cs
        var siteResult  = await graphClient.Sites["myserver"].Sites["mySiteId"].GetAsync();
        var drives = await graphClient.Sites[siteResult.Id].Drives.GetAsync();
```

**Comment by WolfgangHG** [comment]
Thanks, I can confirm that this works. Amazing - I would have never thought you could use the root "Sites" property indexer also to get a subsite.

So, this issue can be closed I assume. Or is there any task for you left?

**Comment by andrueastman** [comment]
Thanks for the feedback @WolfgangHG 

We'll close this one for now. Feel free to create a new issue incase of anything else.
