### ISSUE TITLE
Microsoft.Graph version 5.6.0.0 Get Document Library Id

### ISSUE THREAD

**Issue by bidevg** [microsoftgraph/msgraph-sdk-dotnet#1836]
**Describe the bug**
currently using 4.54.0.0 version to download file from sharepoint. Some of the functionalities are not supported after i upgrade to 5.6.0.0. Need to know the alternate approach for the below line. 

Error	CS1061	'DriveItemRequestBuilder' does not contain a definition for 'Items' and no accessible extension method 'Items' accepting a first argument of type 'DriveItemRequestBuilder' could be found (are you missing a using directive or an assembly reference?)	

.request(), 
.root
.Items
 
**To Reproduce**
Have installed the version Microsoft.Graph version 5.6.0.0

Use following code to get document library id, drive id, items, 
 ` 

            public static async Task<string> GetDocumentLibraryIdAsync(GraphServiceClient graphClient, string siteId, string documentLibraryName)
        {
            var libraries = await graphClient.Sites[siteId].Lists.**Request()**.GetAsync();

            var targetLibrary = libraries.FirstOrDefault(library => library.DisplayName == documentLibraryName);

            return targetLibrary == null
                ? throw new ArgumentException($"Document library '{documentLibraryName}' not found.")
                : targetLibrary.Id;
        }

        public static async Task<string> GetDriveIdFromDocumentLibrary(GraphServiceClient graphClient, string siteId, string documentLibraryId)
        {
            var drive = await graphClient.Sites[siteId].Lists[documentLibraryId].Drive.**Request()**.GetAsync();
            return drive.Id;
        }
        
            public static async Task DownloadFilesFromDocumentLibrary(GraphServiceClient graphClient, string siteId, string driveId, string targetFolderPath, DownloadOptions options)
        {
            var folderItems = await graphClient.Sites[siteId].Drives[driveId].**Root**.Children.Request().GetAsync();
             ...
            .....
            var children = await graphClient.Sites[siteId].Drives[driveId].**Items**[currentFolder.Id].Children.Request().GetAsync();
        }`
         
        
**Expected behavior**
to retrieve document library id, drive id, files, folders 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bidevg** [comment]
got the solution

**Comment by Nate308** [comment]
Please share the solution.
