### ISSUE TITLE
PageIterator return type error

### ISSUE THREAD

**Issue by timmac-qmc** [microsoftgraph/msgraph-sdk-dotnet#1847]
**Describe the bug**
PageInterator is currently preventing a build with the strange error on return type
"CS0029	Cannot implicitly convert type 'bool' to 'System.Threading.Tasks.Task<bool>'"

**To Reproduce**
Use the following code

```
try
                {
                    var members = await GraphClient.Groups[groupId].Members.GetAsync(requestConfiguration =>
                    {
                        if (searchText != null)
                            requestConfiguration.QueryParameters.Search = $"\"displayName:{searchText}\"";
                        requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
                        requestConfiguration.QueryParameters.Count = true;
                        requestConfiguration.QueryParameters.Orderby = new string[] { "displayName" };
                    });
                    var pageIterator = PageIterator<Microsoft.Graph.Models.User, UserCollectionResponse>.CreatePageIterator(GraphClient, members, (m) =>
                    {  
                        return true;
                    });
                    await pageIterator.IterateAsync();
                }
                catch (ODataError ex)
                {
                    Console.WriteLine($"GetGraphUsersInGroups Error! Code {ex.Error?.Code ?? "-1"} Message: {ex.Error?.Message ?? "Unknown Error"}");
                }
```

**Expected behavior**
Project should build

**Screenshots**
![graph_error](https://user-images.githubusercontent.com/103250605/233389611-0b65a4b8-32b3-4bfb-ae53-f19e9e8a7042.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Microsoft Visual Studio Professional 2022
Version 17.6.0 Preview 4.0
 - .NET 7.0

**Comment by andrueastman** [comment]
Thanks for raising this @timmac-qmc 

The return type of the call `graphClient.Groups[""].Members.GetAsync()` is of type `DirectoryObjectCollectionResponse` as not only users can be member of a group. The page iterator would therefore need to be initialized as 

```cs
var pageIterator = PageIterator<Microsoft.Graph.Models.DirectoryObject, DirectoryObjectCollectionResponse>.CreatePageIterator(graphClient, members, m => true);
```

If you only wish to get members of the type user, you can use the GraphUser segment to use the odata cast functionality as and you should be able to use the `UserCollectionResponse` type for this.

```cs
var users = await graphClient.Groups[""].Members.GraphUser.GetAsync();
```
