### ISSUE TITLE
Getting root directories of drive

### ISSUE THREAD

**Issue by WolfgangHG** [microsoftgraph/msgraph-sdk-dotnet#1848]
I try to get a list of the root directories of a drive.

According to [https://learn.microsoft.com/en-us/graph/api/driveitem-list-children](https://learn.microsoft.com/en-us/graph/api/driveitem-list-children), I would expect something like this:
```
await graphClient.Drives[driveId].Root.Children.GetAsync()
```
But the property "Root.Children" does not exist.

So I tried 
```
await graphClient.Drives[driveId].Items.GetAsync()
```
But this fails with an error `The 'filter' query option must be provided.` - this seems to be the error from #1840. Should it work without filter?

It also fails when using
```
await graphClient.Drives[driveId].Root.ItemWithPath("/").GetAsync();
```
The error is `Resource not found for the segment 'root:'.`

An empty path results in a slightly different error.

How to get the content of a root directory?

**Comment by andrueastman** [comment]
Thanks for raising this @WolfgangHG 

Any chance this works out for you as the examples in the docs show?

```cs
 await graphClient.Drives["driveId"].Items["root"].Children.GetAsync();
```

**Comment by WolfgangHG** [comment]
Not really, because "driveId" is the ID for the root directory in a site. I think your code snippet would fetch the children of the folder named "root" of the site.

Using
```
await graphClient.Drives["driveId"].Items.GetAsync();
```
raises an error `"invalidRequest"` with message `"The 'filter' query option must be provided."`, as found in #1840

**Comment by estalldecker** [comment]
I had the same doubt and just tested the solution provided by @andrueastman  above and it does indeed work as expected. Just to verify it I created a folder named "root" and there was no issue at all. 

I'm capturing the requests with fiddler and in my case it generated this:
`GET /v1.0/drives/<my-drive-id>/items/root/children` and the results are correct, even the fake "root" folder I created was returned with no issues.

**Comment by WolfgangHG** [comment]
@estalldecker How did you manage to get the list of subdirectories of the drive root using this library? 

I finally managed to get them with this code:

```
          DriveItem itemRoot = await graphClient.Drives["driveId"].Root.GetAsync( (conf)=>
          {
            conf.QueryParameters.Expand = new string[] { "children" };
          });
          List<DriveItem> driveItems = itemRoot.Children;
```

But this feels way too cumbersome.

**Comment by estalldecker** [comment]
That way is correct @WolfgangHG, but let me share some screenshots, if you want to make a simple call you can use the one suggested by @andrueastman. As you can see results are the same.

Here are my 2 results:
----------------------------------------------------------

`var listItems = await _userClient.Drives[drive.Id].Items["root"].Children.GetAsync();` 
![image](https://user-images.githubusercontent.com/6700086/235006696-67a4a84a-0ca5-4c9c-a7bc-788b0617726b.png)

----------------------------------------------------------

```
  var listItems2 = await _userClient.Drives[drive.Id].Root.GetAsync((conf) =>
  {
      conf.QueryParameters.Expand = new string[] { "children" };
  });
```
![image](https://user-images.githubusercontent.com/6700086/235007078-c05042b8-badf-4f35-a677-96d834ab2a6d.png)

----------------------------------------------------------
![image](https://user-images.githubusercontent.com/6700086/235007899-8009d256-a82d-4845-b6f4-c0e24d1432a2.png)
----------------------------------------------------------

**Note:**
In the 2nd screenshot I just realized the `children@odata.count` is set to `16` but the `Children` array has `15` elements.

**Comment by WolfgangHG** [comment]
@estalldecker As far as I understand it, your first snippet gets the children of directory named "root" in the root folder of the drive?
Also, how did you manage to make this work - I always receive an error when using "Drives[<my-drive-id>].Items"? I use the code to fetch the items of a sharepoint sub site. Maybe you use it for OneDrive and here it works?

My own workaround (using "expand") results in this URI (gotten from "ToGetRequestInformation"):
```
https://graph.microsoft.com/v1.0/drives/<my-drive-id>/root?%24expand=children
```
which is not the same as the request URL that shall be used in [https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#list-children-in-the-root-of-the-current-users-drive](https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#list-children-in-the-root-of-the-current-users-drive) ("/me/drive/root/children").

**Comment by andrueastman** [comment]
@WolfgangHG 
To confirm, the `/root` is not present in the SDK due to the metadata changes in https://github.com/microsoftgraph/msgraph-metadata/issues/248#issue-1535318435. 

As described in the issue, the `root` property on driveItem is a simply shorthand to `.../items/root` and is omitted to avoid generating paths that have alternatives for the purposes of optimising metadata/sdk size.

**Comment by estalldecker** [comment]
> @estalldecker As far as I understand it, your first snippet gets the children of directory named "root" in the root folder of the drive?

No, it gets the content of the root folder of the drive....that's what I was trying to show in the 3rd screenshot...that both methods (your's and mine) were listing the same children.
 
> Also, how did you manage to make this work - I always receive an error when using "Drives[my-drive-id].Items"? I use the code to fetch the items of a sharepoint sub site. Maybe you use it for OneDrive and here it works?

I'm in fact using OneDrive, maybe that's a difference?

> 
> My own workaround (using "expand") results in this URI (gotten from "ToGetRequestInformation"):
> 
> ```
> https://graph.microsoft.com/v1.0/drives/<my-drive-id>/root?%24expand=children
> ```
> 
> which is not the same as the request URL that shall be used in https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#list-children-in-the-root-of-the-current-users-drive ("/me/drive/root/children").

You're right, it doesn't map to the same URL but it should give you the results you want.

**Comment by WolfgangHG** [comment]
@andrueastman To sum this up: So, I should use this code to get the children of a directory "myRootDir" on our sharepoint subsite?
```c#
DriveCollectionResponse driveResponse = await graphClient.Sites[<subsiteId>].Drives.GetAsync();
Drive driveFound = driveResponse.Value.First(d => d.Name == "myRootDir");
await graphClient.Drives[driveFound.Id].Items.GetAsync();
```
Could you confirm that this is the proper way to do it? 

It currently fails, see above. 

The other approach to use an "expand" property is just a workaround I think.

**Comment by cdrose** [comment]
The following works for me:

`var site = await _appClient.Sites[$"{domain}:{sitePath}"].GetAsync();
var siteDrives = await _appClient.Sites[site.Id].Drives.GetAsync();
var drive = await _appClient.Drives[siteDrives.Value.First().Id].GetAsync();
var rootFolders = await _appClient.Drives[drive.Id].Items["root"].Children.GetAsync();`

**Comment by andrueastman** [comment]
@WolfgangHG I believe the approach by @cdrose would be correct. 

```cs
var rootFolders = await _appClient.Drives[drive.Id].Items["root"].Children.GetAsync();
```

Ideally, you need to have the `/children` path segment to list the contents in a drive. 
https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http

**Comment by WolfgangHG** [comment]
@andrueastman I can confirm that this works.

Seems I did not test the approach of @cdrose because it sounded so weird ;-)

Just a bit of feedback: the old API was more intuitive - here this piece of code worked:
```
driveItems = await GetSiteRequest().Drives[strRootDirId].Root.Children.Request().GetAsync();
```
Probably there are good technical reasons for the new API, but from a users point of view, it feels quite horrible.

**Comment by WolfgangHG** [comment]
@andrueastman So this is a "won't fix" closing?
