### ISSUE TITLE
Support for strongly(-er?) typed select statements on element related properties

### ISSUE THREAD

**Issue by Mardoxx** [microsoftgraph/msgraph-sdk-dotnet#185]
`graphClient.Groups[group.Id].Members.Request()` returns `IGroupMembersCollectionWithReferencesRequest` so `.Select()` only has `string` and `Expression<Func<DirectoryObject, object>> expandExpression` overloads.

I would like something like...

```
IEnumerable<Microsoft.Graph.User> users = (await graphClient.Groups[group.Id].Members.Request().Select<Microsoft.Graph.User>(x => new {x .Id, x.GivenName}).GetAsync()).OfType<Microsoft.Graph.User>();
```

Which works similarly to:
```
IEnumerable<Microsoft.Graph.User> users = (await graphClient.Groups[group.Id].Members.Request().Select("id,givenName").GetAsync()).OfType<Microsoft.Graph.User>();
```

So sig for Select<T>() is something like this
```
I...WithReferencesRequest Select<T>(Expression<Func<T, object>> expandExpression) where T : DirectoryObject
```

.... Could be improved upon by rewriting some of the client API to return something like `IRequest<T> where T : DirectoryObject`? Surely this would cut down on the 2,646 or so specialised interfaces?

**Comment by MIchaelMainer** [comment]
If I understand correctly, I don't expect that we could consider this change as it would break existing scenarios.
