### ISSUE TITLE
[Client bug]: unable to add owner to private channel (v4.54.0)

### ISSUE THREAD

**Issue by felpel** [microsoftgraph/msgraph-sdk-dotnet#1852]
**Describe the bug**
With the NuGet package at version `4.54.0`, I'm trying to add a new owner to a private channel I've just created with delegated permissions.

However, when I try to add the desired member as an owner, I end up with the following error payload:
- Code: `UnknownError`
- Message: `404 page not found`

**To Reproduce**
1. Create a team from any source (Graph, REST API, etc.) with the following members: `User1`, `User2`
2. Note the team ID (`Guid`-like) for later
3. Create a private channel from any source as `User1`
4. Note the channel ID (opaque token) for later
5. Here is the code sample I am trying to use to add `User2` as the owner of the previously mentioned channel:

```csharp
    public async Task AddChannelOwner(Guid teamId, ChannelId channelId, Guid userId, CancellationToken cancellationToken)
    {
        var channelOwner = new AadUserConversationMember
        {
            Roles = new List<string> { "owner" },
            AdditionalData =
            {
                { "user@odata.bind",  $"https://graph.microsoft.com/v1.0/users('{userId}')" },
            },
        };

        try
        {
           // Assume this._client is properly initialized as GraphServiceClient
           // Also,  ChannelId is a value object holding the opaque string that I got 
           // following the channel creation in a separate method
            var request = this._client
                .Teams[teamId.ToString()]
                .Channels[channelId.RawValue]
                .Members
                .Add(new List<ConversationMember> { channelOwner })
                .Request();

            await request.PostAsync(cancellationToken);
        }
        catch (ServiceException ex)
        {
            // This is where I always end up with UnknownError / Page not found.
        }
    }
```
6. `ServiceException` will be thrown with the error code & message as mentioned above.

**Expected behavior**
I should be capable of adding a new member with an owner role to a private channel I've created if I have the proper delegated Graph API permissions.

**Screenshots**

**Client version**
4.54.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: N/A

**Additional context**
I've looked at the [official documentation](https://learn.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-beta&tabs=csharp), both with `beta` & `v1.0`, but none of them can be used with this NuGet package version.

`ConversationMember` is flagged as an `internal` class and can't be instantiated as shown in the example.

**Comment by andrueastman** [comment]
Thanks for raising this @felpel 

Any chance this is still the error you get when making the call using the Graph Explorer? Furthermore, does this error only occur when you add members to a private channel? What about a `standard` channel?

**Comment by andrueastman** [comment]
Thanks for following up. 

As this looks to be an API related question, and this repo is mainly intended for issues related to the SDK. Any chance you can post the same query at the link below so that API owners maybe be able to give feedback on whether it should be possible to do the operation in multiple calls? 

https://learn.microsoft.com/en-us/answers/tags/282/microsoft-graph-teamwork-api

It would be great if you could post back the link to the same so that anyone in future may also find the information.

**Comment by felpel** [comment]
Hi, here is a [quick link](https://learn.microsoft.com/en-us/answers/questions/1268151/unable-to-assign-owners-to-private-channels-with-g) for reference in case others stumble on this case.

**Comment by andrueastman** [comment]
Closing for now to be followed up at the link above. Will re-open incase anything sdk related is raised.
