### ISSUE TITLE
System.TypeLoadException:  Could not load type 'Microsoft.Graph.IAutehnticationProviderOption' from assembly 'Microsoft.Graph.Core'

### ISSUE THREAD

**Issue by dlgombert** [microsoftgraph/msgraph-sdk-dotnet#1854]
I've tried a million variations of the following code, implementing in services, directly in controllers, etc.  Everywhere I try leads to the same error:  

```csharp
 services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(configuration.GetSection("AzureAd"))
            .EnableTokenAcquisitionToCallDownstreamApi()
            .AddMicrosoftGraph(configuration.GetSection("MicrosoftGraph"))
            .AddInMemoryTokenCaches();
```

`System.TypeLoadException: Could not load type 'Microsoft.Graph.IAuthenticationProviderOption' from assembly 'Microsoft.Graph.Core, Version=3.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

**To Reproduce**
1.  Press play to start debugging.
2.  Go to the url I've setup in the controller.  

**Expected behavior**
I expect the graph query I call which is:  
```csharp
   var result = await _graphServiceClient.ServicePrincipals[
            servicePrincipal
        ].AppRoleAssignedTo.GetAsync();
```

to return the users for the app. 

I can show configuration if it helps.  

When I tried to create a scoped service, the service was unable to be resolved in the controller.  The debugger would never even make it that far, despite having registered it and confirmed that it was registered as scoped.

I'm still somewhat new to Csharp, so this could definitely be operator error, but as far as I can tell, I've followed the documentation, and I've tried enough changes that I ought to have hit on it by now, lol.

**Comment by dlgombert** [comment]
I've worked with the gist for awhile,, and I'm unable to make it work.  The underlying issue is that TokenProvider gets invoked before the user is Authenticated, and indeed the user is never authenticated.  The error here is: `MsalUiRequiredException` and ErrorCode is `user_null`.  Where before it would either use existing token or callup the login popup, it's now complaining about incremental authentication - something I had trouble with when working with Blazor as well.

I'm invoking  `EnableTokenAcquisitionForDownstreamApi`, but without `AddMicrosoftGraph`, as it looks like that get's handled during token acquisition.  If I do use AddMicrosoftGraph, I get `System.TypeLoadException: Could not load type 'Microsoft.Graph.IAuthenticationProviderOption' from assembly 'Microsoft.Graph.Core, Version=3.0.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.` again.

If I'm reading the back and forth correctly, it seems like my best option is to roll back to 4.5?  But I can't be the only one with this use case.  Any insight?

**Comment by viniciusfonseca-trt17** [comment]
I've managed to get it to work after replacing dependency **Microsoft.Identity.Web.MicrosoftGraph** with **Microsoft.Identity.Web.GraphServiceClient**.

https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.GraphServiceClient/Readme.md

**Comment by andrueastman** [comment]
Closing this for n
