### ISSUE TITLE
No ScheduleInformationCollectionResponse class in the models

### ISSUE THREAD

**Issue by CeBonVieuxZdoud** [microsoftgraph/msgraph-sdk-dotnet#1858]
**Is your feature request related to a problem? Please describe.**
The https://graph.microsoft.com/v1.0/me/calendar/getSchedule request need a [ScheduleInformation Collection as a response](https://learn.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http#response) but i can't seem to find one in the models package of graph.

**Describe the solution you'd like**
A ScheduleInformationCollectionResponse class in Microsoft.Graph.Models package

Thank you

**Comment by MartinM85** [comment]
The code from the [example](https://learn.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=csharp#request) returns `Microsoft.Graph.Me.Calendar.GetSchedule.GetScheduleResponse`. `GetScheduleResponse` object has the property `Value` of type List<`ScheduleInformation>` which is what you are probably looking for.

```
var graphClient = new GraphServiceClient(requestAdapter);

var requestBody = new Microsoft.Graph.Me.Calendar.GetSchedule.GetSchedulePostRequestBody
{
	Schedules = new List<string>
	{
		"adelev@contoso.onmicrosoft.com",
		"meganb@contoso.onmicrosoft.com",
	},
	StartTime = new DateTimeTimeZone
	{
		DateTime = "2019-03-15T09:00:00",
		TimeZone = "Pacific Standard Time",
	},
	EndTime = new DateTimeTimeZone
	{
		DateTime = "2019-03-15T18:00:00",
		TimeZone = "Pacific Standard Time",
	},
	AvailabilityViewInterval = 60,
};
var result = await graphClient.Me.Calendar.GetSchedule.PostAsync(requestBody, (requestConfiguration) =>
{
	requestConfiguration.Headers.Add("Prefer", "outlook.timezone=\"Pacific Standard Time\"");
});

var schedules = result.Value;

```

**Comment by andrueastman** [comment]
For context, 

https://graph.microsoft.com/v1.0/places/microsoft.graph.room - is an entity set and holds a collection while https://graph.microsoft.com/v1.0/me/calendar/getSchedule is an action hence the requestBody/responseBody types have inlined schemas like the path name. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#namespacesusings-changes

We'll close this as an available model is present for the given path.
