### ISSUE TITLE
Not able to call CalendarView Delta 

### ISSUE THREAD

**Issue by yansen-chandra** [microsoftgraph/msgraph-sdk-dotnet#1860]
sample code 
https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=csharp 

```
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Me.CalendarView.Delta.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Startdatetime = "{start_datetime}";
	requestConfiguration.QueryParameters.Enddatetime = "{end_datetime}";
	requestConfiguration.Headers.Add("Prefer", "odata.maxpagesize=2");
});
```

![image](https://user-images.githubusercontent.com/10176990/234909934-a22c9a3e-381f-47ce-a053-cf07248d02a2.png)

There are no Startdatetime and Enddatetime parameter, not specifying the parameter result in error below

`This request requires a time window specified by the query string parameters StartDateTime and EndDateTime.
`
![image](https://user-images.githubusercontent.com/10176990/234910497-c2372df5-b55a-477f-a8a7-2dbc750c369b.png)

but there is no way to set them, thus CalendarView.Delta is not usable 

library used: Microsoft.Graph 5.7.0

**Comment by andrueastman** [comment]
Depends on https://github.com/microsoftgraph/msgraph-metadata/issues/329
