### ISSUE TITLE
GDAP: DelegatedAdminRelationship Error

### ISSUE THREAD

**Issue by polks71** [microsoftgraph/msgraph-sdk-dotnet#1862]
Attempting to create a GDAP Relationship with Graph.
.Net 6, Visual Studio 2022, Nuget Microsoft.Graph v5.7

The code below produces this error:
500 : Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError'
One Note: On the documentation page (https://learn.microsoft.com/en-us/graph/api/tenantrelationship-post-delegatedadminrelationships?view=graph-rest-1.0&tabs=csharp) for the C# example it says to use "Duration = TimeSpan.Parse("P730D")," to calculate the Duration. However, "P730D" throws an error as an invalid TimeSpan.

`
var createRequest = JsonConvert.DeserializeObject<CreateRelationshipRequest>(await req.ReadAsStringAsync());          
var scopes = new[] { "https://graph.microsoft.com/.default" };
var tenantId = "TENANT_ID";
var clientId = "CLIENT_ID";
var clientSecret = "CLIENT_SECRET";
var options = new TokenCredentialOptions
{
    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
};

  var clientSecretCredential = new ClientSecretCredential(
      tenantId, clientId, clientSecret, options);
var graphClient = new GraphServiceClient(clientSecretCredential, scopes);

try
{
    var relationship = new DelegatedAdminRelationship();
    relationship.DisplayName = $"DISPLAY-NAME-OF-RELATIONSHIP";
    relationship.Duration = TimeSpan.FromDays(720);
    relationship.Customer = new DelegatedAdminRelationshipCustomerParticipant();
    relationship.Customer.DisplayName = CUSTOMER_NAME;
    relationship.Customer.TenantId = CUSTOMER_TENANTID;
    relationship.AccessDetails = new DelegatedAdminAccessDetails();
    var roles = new List<UnifiedRole>();
        roles.Add(new UnifiedRole()
        {
            RoleDefinitionId = "11648597-926c-4cf3-9c36-bcebb0ba8dcc"
        });
        roles.Add(new UnifiedRole()
        {
            RoleDefinitionId = "44367163-eba1-44c3-98af-f5787879f96a"
        });
    relationship.AccessDetails.UnifiedRoles = roles;
    var result = await graphClient .TenantRelationships.DelegatedAdminRelationships.PostAsync(relationship);
    return result;
}
catch (ODataError odataError)
{
    log.LogError(odataError, $"{odataError.ResponseStatusCode} : {odataError.Message}");
    throw;
}
`

**Comment by polks71** [comment]
I will add that using the same client and the same credentials I can read all GDAP Relationships.

**Comment by andrueastman** [comment]
Thanks for raising this @polks71 

The generated snippet is incorrect as `TimeSpan.Parse("P730D")` can't be used for ISO8601 duration strings.

Any chance it works out if you use `System.Xml.XmlConvert.ToTimeSpan("P730D")` instead to verify?

**Comment by polks71** [comment]
@andrueastman  
Yes, `System.Xml.XmlConvert.ToTimeSpan("P730D")` works. 
Using `TimeSpan.FromDays(730)` creates the same TimeSpan value as well.

**Comment by polks71** [comment]
I set up the same scenario using an HTTP call and some models generated by the samples in the docs. So it may not be a bug in the SDK?
This returns this error:
{"error":{"code":"unexpectedError","message":"An unexpected error occurred in the server.","innerError":{"date":"2023-04-28T10:43:11","request-id":"a2f32c04-eca8-4c3b-9f2b-f2dd5ebfaf5e","client-request-id":"a2f32c04-eca8-4c3b-9f2b-f2dd5ebfaf5e"}}}
`
using (var httpclient = CreateHttpClient())
                {
                    HttpRequestMessage requestMessage = GetRequest($"/v1.0/tenantRelationships/delegatedAdminRelationships", HttpMethod.Post);
                    var relationship = new Models.GdapRelationshipCreateRequest();
                    relationship.displayName = "DISPLAY_NAME";
                    relationship.duration = "P730D";
                    relationship.customer = new Models.Customer();
                    relationship.customer.displayName = CUSTOMER_NAME;
                    relationship.customer.tenantId = TENANT_ID;
                    relationship.accessDetails = new Models.AccessDetails();
                    
                    
                        relationship.accessDetails.unifiedRoles.Add(new Models.UnifiedRole()
                        {
                            roleDefinitionId = "11648597-926c-4cf3-9c36-bcebb0ba8dcc"
                        });
                    
                        relationship.accessDetails.unifiedRoles.Add(new Models.UnifiedRole()
                        {
                            roleDefinitionId = "44367163-eba1-44c3-98af-f5787879f96a"
                        });
                    
                    var content = new StringContent(JsonConvert.SerializeObject(relationship));
                    requestMessage.Content = content;
                    requestMessage.Content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");

                    HttpResponseMessage response = await httpclient.SendAsync(requestMessage);
                    if (response.IsSuccessStatusCode)
                    {
                        return  await response.Content.ReadAsStringAsync();
                    }
                    else
                    {
                        log.LogCritical(response.StatusCode.ToString());
                        log.LogCritical(await response.Content.ReadAsStringAsync());
                        return await response.Content.ReadAsStringAsync();
                    }
                }
`

**Comment by polks71** [comment]
When setting up a DGAP relationship in the UI the customer is not specified until they click the link to approve it. So, I thought maybe removing the customer would help but it did not.

**Comment by andrueastman** [comment]
Thanks for following up @polks71 

> Any chance it works out if you use System.Xml.XmlConvert.ToTimeSpan("P730D") instead to verify?
 
Just to confirm, after changing the timespan handling. Do you still get an error when making a call with the SDK? For this I believe we will need to fix the documentation. 

Or do you get an API error even after the `invalid Timespan` error is resolved? If so any chance you've tried making an API call with the Graph Explorer? https://aka.ms/ge
