### ISSUE TITLE
Unable to retrieve row values for workbook tables

### ISSUE THREAD

**Issue by nosenaoki** [microsoftgraph/msgraph-sdk-dotnet#1865]
**Describe the bug**
When listing table rows, the returned WorkbookTableRow does not hold cell values.

**To Reproduce**

execute following code snippet for any workbook table.

```csharp
 var rows = await client.Drives["drive id "]
            .Items["item id "]
            .Workbook.Tables["table name"].Rows.GetAsync();
```

There is no way to retrive cell value from WorkbookTableRow.

**Expected behavior**
There is any way to retrive cell value from WorkbookTableRow

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A 
 - Version: 5.8.0

**Additional context**

Investigating the source code, I found 
JsonParseNode nor Microsoft.Graph.Models.Json don't design to handle an array of primitive values whose type is unknown in advance. WorkbookTableRow must hold them.

**Comment by andrueastman** [comment]
Depends on https://github.com/microsoftgraph/msgraph-metadata/issues/596

**Comment by craig-blowfield** [comment]
This is still an issue in V5 of the SDK.
` cs
var excelRowsResponse = await graphClient.Drives["driveid"].Items["itemid"].Workbook.Tables["tablename"].Rows.GetAsync();
`

Returns rows in the `Value` but no cell Values

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1820629/ed24b1ba-b922-4b1e-bcc1-5852b70a681a)

Or maybe I'm missing something

Also row add and update are broke as the `Json.cs` provides no way to pass rows and values. Also the doc examples are incorrect for this.

It amazes me that MS don't have unit tests to catch such basic problems, especially as they were moving to new tooling to generate the SDK. This is really poor practice!!.

**Comment by andrueastman** [comment]
Closing as this is resolved in latest version of the SDK.

**Comment by craig-blowfield** [comment]
Great @andrueastman, but where is the documentation of how to work with the cell values in the UntypedArray on the WorkbookTableRow?

The SDK documentation is woefully inadequate, especially in the area of working with UntypedNodes.
