### ISSUE TITLE
Using Graph API creation of  Saml SSO instigation with assertion encryption fails on KeyCredentials with usage equal `Encrypt`

### ISSUE THREAD

**Issue by plachor** [microsoftgraph/msgraph-sdk-dotnet#1869]
Hi, I am trying to update Graph from `4.54.0` to `5.8.0`. In previous version I was able to setup an enterprise application with SAML SSO that would encrypt assertion with public key delivered by service provider.

Patch that I used to setup certificates looked like:

```csharp
graphClient.Applications[applicationReference.ApplicationId.ToString()].Request().UpdateAsync(new Application
{
    Web = new WebApplication
    {
        RedirectUris = ..,
        LogoutUrl = ..
    },
    IdentifierUris = new[]
    {
        ..
    },
    
    KeyCredentials = [KEY_CREDENTIALS],
    TokenEncryptionKeyId = [ENCRYPTION_KEY_ID]
});
```

Within `KEY_CREDENTIALS` I passed 3 `AsymmetricX509Cert`  keys with following usages:  `Sign`, `Verify` and `Encrypt`.  Id of last one was also configured as `ENCRYPTION_KEY_ID`.

This was working fine for me under `4.54.0` version. However after upgrade during patch  I end with `Request_BadRequest`:

> The value for the property "usage" in one of your credentials is invalid. Acceptable values are Sign, Verify.

Is it a bug ? Or after upgrade to v5 I should configure encryption key in different request ?

**Comment by andrueastman** [comment]
Thanks for raising this @plachor 

Any chance you could share a sample of how you are performing the request in V5 of the SDK?

**Comment by plachor** [comment]
Sure similar to v4,

```csharp
graphClient.Applications[applicationReference.ApplicationId.ToString()].PatchAsync(new Application
{
    Web = new WebApplication
    {
        RedirectUris = ..,
        LogoutUrl = ..
    },
    IdentifierUris = new List<string>
    {
        ..
    },

    KeyCredentials = [KEY_CREDENTIALS],
    TokenEncryptionKeyId = [ENCRYPTION_KEY_ID]
});
```

**Comment by andrueastman** [comment]
@plachor Any chance you can confirm if this is reproducible with the latest version of the SDK?
