### ISSUE TITLE
Cannot set GivenName/Surname to string.empty

### ISSUE THREAD

**Issue by khloroform187** [microsoftgraph/msgraph-sdk-dotnet#187]
GivenName and Surname are optional fields during the user creation process. 

If I create a user with those fields and then try to "reset" them (set to string.empty) using the update user, it crashes with a BadRequest (Code: Request_BadRequest Message: Invalid value specified for property 'givenName' of resource 'User'.)

And if I set them to null, it does not alter them.

Is this use case supported with the client library?

**Comment by cbales** [comment]
Currently null PATCHing is not supported in the library.

**Comment by christophwille** [comment]
Oh, this explains the behavior we saw with mobilePhone when we switched from AAD Graph to Microsoft Graph. That is definitely going to bite us a couple more times when we want to "delete" a property value. Is there a plan to fix this in the near-ish future?

**Comment by MIchaelMainer** [comment]
@khloroform187 That error you saw is based on the service, not the client library. You may want to consider asking for this feature via [Office Dev Uservoice](https://officespdev.uservoice.com/).

Null patching is somewhat supported by the client library. You set the property in the AdditionalData dictionary property and patch it. Then hopefully the service supports null patching. I'm unable to make a statement at this time about whether the underlying services support null or string.empty patching across all scenarios. That's many services with 100s of scenarios that would need to be accounted for to make a firm statement. 

                var groupToUpdate = new Group();
                var prop = new Dictionary<string, object>();
                prop.Add("description", null);
                groupToUpdate.AdditionalData = prop; 
                await graphClient.Groups[groupId].Request().UpdateAsync(groupToUpdate);
