### ISSUE TITLE
Customers list is coming empty in list of appointments 

### ISSUE THREAD

**Issue by pveliz** [microsoftgraph/msgraph-sdk-dotnet#1875]
**Describe the bug**

After calling Microsoft.Graph.Solutions.BookingBusinesses["id"].Appointments.GetAsync() I'm expecting to get the list of customers per appointment but the list comes empty.

Interesting: if I use Microsoft Graph Postman collection https://learn.microsoft.com/en-us/graph/use-postman I don't get all the appointments of a particular BookingBusiness object.

If I use C# I can get all of them but customers are not coming.

Am I missing a configuration somewhere?

**To Reproduce**

Use this example: https://learn.microsoft.com/en-us/graph/tutorials/dotnet?tabs=aad

Configure Microsoft 365 E5 instant sandbox.

Nuget Packages

```
<ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.8.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.9.0" />
  </ItemGroup>
```

C# code

```
GraphServiceClient client = new GraphServiceClient(_deviceCodeCredential, settings.GraphUserScopes);
var result = client.Solutions.BookingBusinesses[bookingBusinessId].Appointments.GetAsync();
```

**Expected behavior**
I'm expecting to get the list of appointments with its customers. 

like this one https://learn.microsoft.com/en-us/graph/api/bookingbusiness-list-appointments?view=graph-rest-1.0&tabs=http#response-1

**Screenshots**

![image](https://user-images.githubusercontent.com/33209561/236283839-5ac9516c-044b-40ed-a6cd-ccaf6aa37315.png)

![image](https://user-images.githubusercontent.com/33209561/236281841-00227720-d598-431c-9289-8cfe5e159415.png)

![image](https://user-images.githubusercontent.com/33209561/236282167-a428909b-72d3-43bf-82f5-ee0f24593ebe.png)

![image](https://user-images.githubusercontent.com/33209561/236283415-580344fb-7c90-4a73-8f32-45ed5ae3dd18.png)

**Comment by andrueastman** [comment]
Thanks for raising this @pveliz 

Any chance you have any luck if you fetch the specific appointment by Id?

```cs
var bookingAppointment = graphClient.Solutions.BookingBusinesses["business-id"].Appointments["appointment-id"].GetAsync();
```

**Comment by pveliz** [comment]
Hey @andrueastman,

Yes, I'm getting customer info if I ask appointments by id.

**Comment by andrueastman** [comment]
Thanks for confirming @pveliz. Any chance this resolves your issue?

**Comment by andrueastman** [comment]
Thanks for getting back to this @pveliz 

> I'm wondering if there is a way to get customers list in the list of appointments graphClient.Solutions.BookingBusinesses["business-id"].Appointments.GetAsync();

As this seems to be an API related question (as the response shape is what is in question) and this repo is intended for SDK related issues we may not be best placed to answer that. 

Any chance you can post the question at the link below to get feedback from the API team on whether the collection property is readable from the path? It would be great if you could post back the link here as a comment in case anyone who comes across this may be able to find it too. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
