### ISSUE TITLE
Configuring the HTTP proxy for the client using UsernamePasswordCredential

### ISSUE THREAD

**Issue by j-lehtim** [microsoftgraph/msgraph-sdk-dotnet#1879]
Hi guys,

I have a question. I am wondering is there a way to create GraphServiceClient that uses HTTP proxy such that authentication is achieved using UsernamePasswordCredential -class.

I am aware that there are instructions ( https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp ) for using ClientSecretCredential, and those instructions do work indeed.

Could someone provide similiar instructions about using UsernamePasswordCredential if they can be used in this context?

**Comment by andrueastman** [comment]
Thanks for raising this @j-lehtim 

I believe similar to the example to the link you shared, you can create an instance of `UsernamePasswordCredentialOptions` and update its `Transport` property(as it is done for the `ClientSecretCredential`) and initiliaze the client as is done in the example. 

```cs
        var options = new UsernamePasswordCredentialOptions
        {
            // Create a new Azure.Core.HttpClientTransport
            Transport = new HttpClientTransport(handler)
        };
        var usernamePasswordCredential = new UsernamePasswordCredential("username", "password", "tenantId", "clientId", options);

```

**Comment by j-lehtim** [comment]
Thank you sir, this worked well.
