### ISSUE TITLE
[Client bug]: BadRequest when using nested select inside expand

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#1881]
**Describe the bug**
When using `expand` with nested `select` for reading items in SharePoint site's list the SDK generates wrong query.

Let's say I have a request

    GET https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items?expand=fields(select=createdDateTime)

It works fines for example from Graph Explorer. Based on the documentation [here](https://learn.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http#http-request) and [here](https://learn.microsoft.com/en-us/graph/api/listitem-list?view=graph-rest-1.0&tabs=http#request) the query is correct and developers are familiar with this syntax and they are used to use this syntax.

The code for the query above is 

```
var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "fields(select=createdDateTime)" };
});
```
which looks fine but when executed it fails with the error

> Parsing OData Select and Expand failed: Term '(select=createdDateTime)' is not valid in a $select or $expand expression.

The root cause is that SDK generates wrong URL with `$expand` instead of `expand`

    https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items?$expand=fields(select=createdDateTime)

**Workaround**
The workaround is to use `$select` instead of `select` in `Expand`.
```
var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "fields($select=createdDateTime)" };
});
```

**Additional context**
I'm not sure if the issue requires a fix in SDK or in the documentation but if `https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items?expand=fields(select=name)` is correct syntax then SDK should be able to handle it.

It would be nice if SDK team can discuss the issue with Graph API team. 

What I remember the `$` prefix is optional only for beta version but `v1.0/sites/{site-id}/lists/{list-id}/items` endpoint supports both.

**Comment by andrueastman** [comment]
Closing this one for now. Documentation updates via https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9127 and upgrade guide includes information via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2275
