### ISSUE TITLE
Downloading attachment from mailbox greater than 35MB is causing OData

### ISSUE THREAD

**Issue by pooja10396** [microsoftgraph/msgraph-sdk-dotnet#1882]
**Describe the bug**
Getting **Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.** with ResponseStatusCode of 504 is getting while downloading attachment from Mailbox. The error is throwing when trying to download attachments that is greater than 35MB.

Following are the code that I had implemented to download the attachment.

```
var httpClient = new HttpClient
{
Timeout = TimeSpan.FromMinutes(45), // Set the timeout to 45 minutes
};
var clientCredentialAuthProvider = new ClientCredentialAuthProvider(configuration);
var graphClient = new Microsoft.Graph.GraphServiceClient(httpClient, clientCredentialAuthProvider);


var messages = await graphClient.Users[configuration.SharedMailBox].MailFolders[configuration.InboxFolderId].Messages
.GetAsync(requestConfig =>
{
requestConfig.QueryParameters.Select = configuration.FilterConfiguration.Properties;
requestConfig.QueryParameters.Filter = configuration?.FilterConfiguration?.Filters ?? string.Empty;
requestConfig.QueryParameters.Top = configuration?.FilterConfiguration?.MessageCount ?? 1;
requestConfig.QueryParameters.Expand = new string[] { "attachments" };
});

var latestMail = messages.Value.FirstOrDefault();
if (messages is not null)
{

_logger.LogInformation("{DownloadAttachmentFromMailByFileNameAsync}", "Email downloaded successfully.");
_logger.LogInformation("{DownloadAttachmentFromMailByFileNameAsync}", "Initiating attachment download.");

var cts = new System.Threading.CancellationTokenSource(TimeSpan.FromHours(1));
var attachment1 = await graphClient.Users[sharedMailbox].MailFolders[InboxFolderId].Messages[latestMail.Id].GetAsync((requestConfig) =>
{
requestConfig.QueryParameters.Expand = new string[] { "attachments" };

}, cancellationToken: cts.Token
);
```

Tried with the Microsoft Graph Versions 4.45.0, 5.8.0 and 5.9.0 

Unfortunately no documentation on setting timeout or retry can be found for version 5+

**To Reproduce**
Try to download any attachments from mailbox that is having size greater than 35 MB.

**Expected behavior**
Should Ideally download, with increased timeout.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Tried from a console application on .Net 6 Framework.

**Comment by andrueastman** [comment]
Thanks for raising this @pooja10396 

Just to confirm, do you still get at gateway timeout error if you call the attachements endpoint directly as opposed to using it in the select statement?

```cs
var attachmentCollectionResponse = await graphClient.Users[sharedMailbox].MailFolders[InboxFolderId].Messages[latestMailId].Attachments.GetAsync();
```

**Comment by pooja10396** [comment]
> Thanks for raising this @pooja10396
> 
> Just to confirm, do you still get at gateway timeout error if you call the attachements endpoint directly as opposed to using it in the select statement?
> 
> ```cs
> var attachmentCollectionResponse = await graphClient.Users[sharedMailbox].MailFolders[InboxFolderId].Messages[latestMailId].Attachments.GetAsync();
> ```

Yes, I had tried the same as well.
