### ISSUE TITLE
[Client bug]: Serializer Dropping Values

### ISSUE THREAD

**Issue by joshbinney** [microsoftgraph/msgraph-sdk-dotnet#1883]
Opened this before but it was closed as I was away.
Just wondering how we are meant to use .Serialize() on CallRecord class. I've checked the docs and can't find anything on it.

The following code throws this error:

`var callRecord = await graphClient.Communications.CallRecords[callId]
.GetAsync(
config => { config.QueryParameters.Expand = new[] { "sessions($expand=segments)" }; },
cancellationToken);

            using (var serializationWriter = new JsonSerializationWriter())
            {
                callRecord.Serialize(serializationWriter);
                using (StreamReader reader = new StreamReader(serializationWriter.GetSerializedContent()))
                {
                    var test = await reader.ReadToEndAsync();
                }
            }`
Cannot write a JSON property within an array or as the first JSON token. Current token type is 'None'.

Have also tried this:

var serializedData = JsonSerializer.Serialize(callRecord, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, PropertyNamingPolicy = JsonNamingPolicy.CamelCase } );

But this for some reason doesn't serialize some properties such as CallRecord.Sessions.Caller.Identity

This was suggested as a fix but it was no help as you can see I've already tried that above:
"Any chance the following suggestion works out for you? https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1769#issue-1640435111"

**Comment by joshbinney** [comment]
Hey any update on this?

**Comment by andrueastman** [comment]
Apologies for the delayed response @joshbinney 

Any chance you can confirm the received payload with this snippet?

```cs
                using var serializationWriter = new JsonSerializationWriter();
                serializationWriter.WriteObjectValue(string.Empty,user);
                using StreamReader reader = new StreamReader(serializationWriter.GetSerializedContent());
                var test = await reader.ReadToEndAsync();
```

Any chance you can confirm these properties are returned by the API when making the API call using the [Graph Explorer](https://aka.ms/ge)? The properties may be missing as they are not returned by default by the API and may be accessible using the the List Session API. 

https://learn.microsoft.com/en-us/graph/api/callrecords-session-list?view=graph-rest-1.0&tabs=http

**Comment by joshbinney** [comment]
Hey,

I'm calling Graph like this:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/48371670/3ffa1f6c-c288-4a03-a608-12ebe70cc380)

And can confirm that Sessions.Identity.User exists in the payload (debugged it and can see username etc).

**Comment by andrueastman** [comment]
Thanks for confirming @joshbinney 

To follow up, did the updated example still throw the error?

> Any chance you can confirm the received payload with this snippet?
> 
> ```cs
>                 using var serializationWriter = new JsonSerializationWriter();
>                 serializationWriter.WriteObjectValue(string.Empty,callRecord);
>                 using StreamReader reader = new StreamReader(serializationWriter.GetSerializedContent());
>                 var test = await reader.ReadToEndAsync();
> ```

**Comment by joshbinney** [comment]
Sorry I think my last comment was wrong. I'm looking at callrecord.sessions.caller.identity.user. 
This serialization method looks much better! The missing records from my previous snippets are back in the json data.

I'd consider this resolved now if you want to close :)

Is there documentation on this? I had a really thorough look all over the place and couldn't find anything on how to use the serializers correctly. Might be good to share here in case someone else stumbles upon this.

Thanks!

**Comment by joshbinney** [comment]
One last question, how can I set options on the serialization to remove null values and set casing?
