### ISSUE TITLE
[Client bug]: Cannot search for a Site with a number or *

### ISSUE THREAD

**Issue by tjkb** [microsoftgraph/msgraph-sdk-dotnet#1884]
**Describe the bug**
When I search for a Site and the search term contains a number or a asterisk, I get a Bad Request:

```csharp
const string token = "eyJ...";
var client = new GraphServiceClient(new BaseBearerTokenAuthenticationProvider(new TokenProvider(token)));
await client.Sites.GetAsync(r =>
{
  r.QueryParameters.Search = "a*"; // or "a1"
});
```
Response:
```
Syntax error: character '*' is not valid at position 1 in 'a*'.
```

Doing the same search in MS Graph Explorer works perfectly fine:
![image](https://user-images.githubusercontent.com/40162050/237048039-31b0be36-63e0-465c-8138-19799b1af189.png)

**To Reproduce**
Just run the code above

**Expected behavior**
It should not return a Bad Request but the matching sites. Just as the MS Graph Explorer does.

**Client version**
5.9.0

**Desktop (please complete the following information):**
 - .NET Core 7.0

**Comment by MartinM85** [comment]
I think the issue is similar to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1881

The query created by SDK is

    https://graph.microsoft.com/v1.0/sites?$search=a*

SDK adds `$` character before `search` query parameter but it's not accepted by Graph API

when executed in Graph Explorer it returns 

```
{
    "error": {
        "code": "BadRequest",
        "message": "Syntax error: character '*' is not valid at position 1 in 'a*'.",
        "innerError": {
            "date": "2023-05-09T09:51:17",
            "request-id": "177e8404-eee5-4746-9f01-31efe54ea669",
            "client-request-id": "6cf6d40e-ca5e-8fce-0e21-ed18029918a6"
        }
    }
}
```

According to the [doc](https://learn.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http) `search` query parameter should be without `$`.

SDK should be able to handle all query parameters for SharePoint endpoints. What I know only v1.0 SharePoint endpoints have query parameters without `$`.

**Comment by tjkb** [comment]
Yes, it must be related. And I found that it is also related to this #1826. The last comment contains a workaround that solved my problem.

**Comment by LMSSonos** [comment]
I tried the workaround https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1826#issuecomment-1531405983 but does not work for me, I still get no sites listed. Are there any special permissions required? I have the `Sites.Read.All` and `Sites.ReadWrite` Permission set

**Comment by GABRIELNGBTUC** [comment]
I had the same issue and the "fix" is to put your search term inside double quotes.

Using the issue creator example's:

```
const string token = "eyJ...";
var client = new GraphServiceClient(new BaseBearerTokenAuthenticationProvider(new TokenProvider(token)));
await client.Sites.GetAsync(r =>
{
  r.QueryParameters.Search = "\"a*\""; // or "a1"
});
```

Would create the following url: `https://graph.microsoft.com/v1.0/sites?$search="a*"`. Which returns a successful response on the graph explorer and in the .NET client.

In my opinion, an example should be added in the XML docs of the`SiteRequestBuilderGetRequestConfiguration.QueryParameters.Search` to show how to format the value to work with the `$search` query parameter if the maintainers do not want to fix `$search` to `search` in a reasonable timeframe.

No one should have to look for documentation hidden in 5 separate places just to find the correct format of what your SDK is expecting.

**Comment by HappyDump** [comment]
Hi,

I am currently facing the same issue using the following line of code:

` var sitesResponse = await _client.Sites.GetAsync((rc) => { rc.QueryParameters.Search = "\"*\""; }).ConfigureAwait(false);`

I cannot implement the fix because `GetAllSitesRequestBuilderGetRequestConfiguration.QueryParameters` does not have a definition for `Add()`.

**Comment by HappyDump** [comment]
> I had the same issue and the "fix" is to put your search term inside double quotes.
> 
> Using the issue creator example's:
> 
> ```cs
> const string token = "eyJ...";
> var client = new GraphServiceClient(new BaseBearerTokenAuthenticationProvider(new TokenProvider(token)));
> await client.Sites.GetAsync(r =>
> {
>   r.QueryParameters.Search = "\"a*\""; // or "%22a1%22"
> });
> ```
> 
> Would create the following url: `https://graph.microsoft.com/v1.0/sites?$search="a*"`. Which returns a successful response on the graph explorer and in the .NET client. ![image](https://private-user-images.githubusercontent.com/132353744/259682630-193b9311-57bc-4d63-9555-4e62c1cb121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzYxMTAsIm5iZiI6MTcwNDM3NTgxMCwicGF0aCI6Ii8xMzIzNTM3NDQvMjU5NjgyNjMwLTE5M2I5MzExLTU3YmMtNGQ2My05NTU1LTRlNjJjMWNiMTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMzQzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDA5NDE0NTIwZDk4YjJhZjdjYmRiNGNhNDQ4NjM4NTllYWI1NDBiN2QzM2JjYmEzYTdkYmI1YzNmZjM3YjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x_4TLgjiRyJPSjPR2vme3aJSDqCKVafOesuRG3yBhvs)
> 
> In my opinion, an example should be added in the XML docs of the`SiteRequestBuilderGetRequestConfiguration.QueryParameters.Search` to show how to format the value to work with the `$search` query parameter if the maintainers do not want to fix `$search` to `search` in a reasonable timeframe.
> 
> No one should have to look for documentation hidden in 5 separate places just to find the correct format of what your SDK is expecting.

This does return a successful request but in my tests the body is always empty.

**Comment by GABRIELNGBTUC** [comment]
> > I had the same issue and the "fix" is to put your search term inside double quotes.
> > Using the issue creator example's:
> > ```cs
> > const string token = "eyJ...";
> > var client = new GraphServiceClient(new BaseBearerTokenAuthenticationProvider(new TokenProvider(token)));
> > await client.Sites.GetAsync(r =>
> > {
> >   r.QueryParameters.Search = "\"a*\""; // or "%22a1%22"
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would create the following url: `https://graph.microsoft.com/v1.0/sites?$search="a*"`. Which returns a successful response on the graph explorer and in the .NET client. ![image](https://private-user-images.githubusercontent.com/132353744/259682630-193b9311-57bc-4d63-9555-4e62c1cb121c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzYxMTAsIm5iZiI6MTcwNDM3NTgxMCwicGF0aCI6Ii8xMzIzNTM3NDQvMjU5NjgyNjMwLTE5M2I5MzExLTU3YmMtNGQ2My05NTU1LTRlNjJjMWNiMTIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMzQzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDA5NDE0NTIwZDk4YjJhZjdjYmRiNGNhNDQ4NjM4NTllYWI1NDBiN2QzM2JjYmEzYTdkYmI1YzNmZjM3YjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x_4TLgjiRyJPSjPR2vme3aJSDqCKVafOesuRG3yBhvs)
> > In my opinion, an example should be added in the XML docs of the`SiteRequestBuilderGetRequestConfiguration.QueryParameters.Search` to show how to format the value to work with the `$search` query parameter if the maintainers do not want to fix `$search` to `search` in a reasonable timeframe.
> > No one should have to look for documentation hidden in 5 separate places just to find the correct format of what your SDK is expecting.
> 
> This does return a successful request but in my tests the body is always empty.

The `"*"` filter (and only the star alone) may not be supported in their OData API. Look into `graphServiceClient.Sites.GetAllSites()` as it should be the equivalent to the `/sites/getAllSites` endpoint.

**Comment by HappyDump** [comment]
> The `"*"` filter (and only the star alone) may not be supported in their OData API. Look into `graphServiceClient.Sites.GetAllSites()` as it should be the equivalent to the `/sites/getAllSites` endpoint.

The following request `https://graph.microsoft.com/v1.0/sites?search=*` is working on graph explorer :

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3336054/3e2ee89f-5fd0-4775-b985-f1416dbd80c5)

I already looked into `/sites/getAllSites` endpoint. It does not list all sites and subsites across geographies only "root" sites.

**Comment by GABRIELNGBTUC** [comment]
> > The `"*"` filter (and only the star alone) may not be supported in their OData API. Look into `graphServiceClient.Sites.GetAllSites()` as it should be the equivalent to the `/sites/getAllSites` endpoint.
> 
> The following request `https://graph.microsoft.com/v1.0/sites?search=*` is working on graph explorer :
> 
> ![image](https://private-user-images.githubusercontent.com/3336054/294210041-3e2ee89f-5fd0-4775-b985-f1416dbd80c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzODI1MjAsIm5iZiI6MTcwNDM4MjIyMCwicGF0aCI6Ii8zMzM2MDU0LzI5NDIxMDA0MS0zZTJlZTg5Zi01ZmQwLTQ3NzUtYjk4NS1mMTQxNmRiZDgwYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTUzMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjcwZmFiNGM0NTlhMzQ4OWZiNmJmMTBiM2NjMDc5NDAwMThjMTQwOWRmOTE3N2FlYWVhMWQxOTFlNWEzZTYxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.E3pirSMnhmtfk35TeDEGGB7Iah-YPJvDLj8Yo71oJ5E)
> 
> I already looked into `/sites/getAllSites` endpoint. It does not list all sites and subsites across geographies only "root" sites.

Because `search=*` works does not mean that `$search="*"` is guaranteed to work. The first is not an Odata filter and the later is (and is what is used by the MS Graph SDK v5). I honestly wish that MS would adress this issue and allow us to use either because pushing us to use MS Graph when it is such an undocumented pain is horrible.

Rant aside, there seems to have a workaround for the odata filter. Using `rq.QueryPamaters.Search = "\"id=*\"";` seems to recover all the sites.

**Comment by HappyDump** [comment]
> Because `search=*` works does not mean that `$search="*"` is guaranteed to work. The first is not an standard Odata query parameter and the later is (and is what is used by the MS Graph SDK v5).

Yes indeed I was trying to replicate the first syntax and not the latter.

>I honestly wish that MS would adress this issue and allow us to use either because pushing us to use MS Graph when it is such an undocumented pain is horrible.

I agree.

> Rant aside, there seems to have a workaround for the odata filter. Using `rq.QueryPamaters.Search = "\"id=*\"";` seems to recover all the sites.

Thanks I will look into this :)
