### ISSUE TITLE
MS Graph API Web Links for Inbox items no longer work

### ISSUE THREAD

**Issue by qiuzman** [microsoftgraph/msgraph-sdk-dotnet#1887]
**Describe the bug**
A clear and concise description of what the bug is:
When using the following request via MS Graph API results in the appropriate data being generated however the web links are unusable and do not allow a user to open the email via the browser as intended. I am using MS Graph 4.54 dependencies.

**To Reproduce**
`response = await _graphServiceClient.Users[EmailAccount].MailFolders[EmailFolder].Messages.Request().Top(100).GetAsync();`

**Expected behavior**
The links produced in the API request for web links should be able to open in the browser.

**Additional context**
There seems to be an ongoing issue with these web links and deep links but their issues have been closed. This is a new issue that has occurred specific to web links.

**Comment by andrueastman** [comment]
Thanks for raising this @qiuzman 

Any chance you can share more details on the issue with the weblinks? Are they not the valid URL format? Or does following the links result in an error response.

Also, as this seems to be an API response issue and this repo is mainly intended for SDK related issues, any chance you can also post the question at the link below to get feedback from the API owners?

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
