### ISSUE TITLE
Issue on adding OAuth2PermissionScope

### ISSUE THREAD

**Issue by BloodSeaker** [microsoftgraph/msgraph-sdk-dotnet#1888]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
When running a Patch on the Application, specifying 1 oauth2permissionscope, the scope should be added to the current list of scopes.
According to the docs, PatchAsync should be used to update properties of the Application object, with some exceptions as for Owners or PasswordCredentials
https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http

### Actual behavior
A 400 bad request is returned with 'permission (scope or role) cannot be deleted or updated unless disabled first'

### Steps to reproduce the behavior
I am working in a .NET6 application with the MS Graph SDK

Microsoft.Identity.Web.MicrosoftGraph package, version 2.10.0
Microsoft.Graph package, version 5.9.0

I first create an application, having defined 1 App Role and 1 OAuth2PermissionScope.

Next, I want to add an OAuth2PermissionScope and use the PatchAsync for it, as example shows
`await _client.Applications[applicationId].PatchAsync(patch)`
where 'patch' is defined as

```
var patch = new Application
{
    Api = new ApiApplication {
        Oauth2PermissionScopes = permissionScopesToAdd
    }
};
```
'permissionScopesToAdd is just a list with 1 item to be added. In this case, the exception that is given says that 'Permission (scope or role) cannot be deleted or updated unless disabled first'. This gave me the idea 'oh, it tries to delete the ones I did not pass', so in a next try, I included the existing ones as well, but then got an error saying 'Id already exists'.

In some articles on support tickets, I see advice on using UpdateAsync(), but this method just is not available in the package mentioned above. Only 'GetAsync', 'DeleteAsync' and 'PatchAsync' are available.

So, I'm a bit stuck here with this, as I don't seem to find any solution for it. In the beginning, I used Powershell, which did work, but used the Mg-UpdateApplication statement instead.

In the documentation, no mention is given on using a different path (which is required when adding owners or adding an application secret).

**EDIT**: The identically same behavior is visible for AppRoles (which would be expected to have the same behavior). So it seems the update must be done differently, but I don't see any other method described in the documentation.

**Comment by santo2** [comment]
any news on this? When can we expect a fix?
