### ISSUE TITLE
Event JSON payload cannot be deserialized by Microsoft Graph

### ISSUE THREAD

**Issue by dkonyayev** [microsoftgraph/msgraph-sdk-dotnet#1890]
**Describe the bug**
We have been using Microsoft.Graph nuget package version 4.X to create a JSON event payload to use with REST POST API call to Microsoft Graph. After we upgraded to version 5.X, the payload is no longer accepted by the graph service.

Specifically, some of the JSON attributes were removed from the models. In the example below, the version 5

"OdataType": "#microsoft.graph.attendee"

used to be

"@odata.type": "microsoft.graph.attendee"

{
    "Attendees": [
        {
            "Type": 0,
            "AdditionalData": {},
            "BackingStore": {
                "InitializationCompleted": true,
                "ReturnOnlyChangedValues": false
            },
            "EmailAddress": {
                "AdditionalData": {},
                "Address": "dkonyayev@metlife-qa.com",
                "BackingStore": {
                    "InitializationCompleted": true,
                    "ReturnOnlyChangedValues": false
                }
            },
            "OdataType": "#microsoft.graph.attendee"
        }
    ],
    "Body": {
        "AdditionalData": {},
        "BackingStore": {
            "InitializationCompleted": true,
            "ReturnOnlyChangedValues": false
        },
        "Content": "Paid Time Off - 12345",
        "ContentType": 0
    },
    "BodyPreview": "Microsoft.Graph.Models.ItemBody",
    "End": {
        "AdditionalData": {},
        "BackingStore": {
            "InitializationCompleted": true,
            "ReturnOnlyChangedValues": false
        },
        "DateTime": "5/11/2023 12:00:00 AM",
        "TimeZone": "Eastern Standard Time"
    },
    "IsAllDay": true,
    "IsReminderOn": false,
    "Locations": [
        {
            "AdditionalData": {},
            "BackingStore": {
                "InitializationCompleted": true,
                "ReturnOnlyChangedValues": false
            },
            "DisplayName": "12345"
        }
    ],
    "ResponseRequested": false,
    "ShowAs": 4,
    "Start": {
        "AdditionalData": {},
        "BackingStore": {
            "InitializationCompleted": true,
            "ReturnOnlyChangedValues": false
        },
        "DateTime": "5/10/2023 12:00:00 AM",
        "TimeZone": "Eastern Standard Time"
    },
    "Subject": "Konyayev, Dmitriy: Paid Time Off",
    "AdditionalData": {},
    "BackingStore": {
        "InitializationCompleted": true,
        "ReturnOnlyChangedValues": false
    },
    "OdataType": "#microsoft.graph.event"
}

**To Reproduce**
Create JSON payload from Event and POST to Microsoft Graph to create calendar event. 

**Expected behavior**
We expect the Event payload generated by version 5+ of nuget package to be consumable by Microsoft Graph service. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @dkonyayev,

Any chance you can share the method used to serialize the models in this case? The graph client library should handle serialization /deserialization and successful requests made as documented at the link below.

https://learn.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=csharp#request

**Comment by WadeTheFade** [comment]
This looks related to #1933 and #1729

**Comment by andrueastman** [comment]
We'll close this for now. 

With the latest version of the Microsoft.Graph.Core, you should also be able to use the serialization helper methods available from Kiota abstractions. https://www.nuget.org/packages/Microsoft.Graph.Core/3.1.1

```cs
var serializedString = KiotaJsonSerializer.SerializeAsString(date);
```

**Comment by bossbast1** [comment]
what was the solution for this, I am still facing the same issue, after migrating to Graph 5.x **Event** type is no longer serializable and accepted by API endpoint **v1.0/me/events**

class Event serialized from 4.x

![image](https://github.com/user-attachments/assets/8dce2bac-9a66-4d41-8e67-e6c24ead9067)

from 5.x (with many extra properties)

![image](https://github.com/user-attachments/assets/ccb85b74-52af-4667-aa25-33248ece4ed0)

I tried calling: _var content = await KiotaJsonSerializer.SerializeAsStringAsync(newEvent);_ , but it returns empty object

![image](https://github.com/user-attachments/assets/d34aa39c-f8df-400c-bf97-84c7d4678a48)

How I am suppose to get in 5.x Graph the 4x format json?
