### ISSUE TITLE
When editing a document online in SharePoint or OneDrive, the document shows that it was saved successfully, but there is a delay in calling the Graph API to get the latest information about the document after successful saving.

### ISSUE THREAD

**Issue by jacobyang1205** [microsoftgraph/msgraph-sdk-dotnet#1892]
**Describe the bug**
When editing a document online in SharePoint or OneDrive, the document shows that it was saved successfully, but there is a delay in calling the Graph API to get the latest information about the document after successful saving.

**To Reproduce**
In SharePoint
Site: TestSite02
Document Library: Documents
I have a document named a.docx, the current version number is 2.0.
edit this document online
  a. At this time, the page has been saved successfully.
  b. At this time I go to the history of the version, there is no real version changes.
  c. At this time to call Graph API, I get the document information is still the old information (such as CTag value is still the old value).
After a one-minute interval, check the history version, showing that the version changed from 2.0 to 3.0, at this time to call the Graph API to get the latest information on the document.

**Expected behavior**
After the page shows a successful save, the information from the Graph API can also be normal (no delay).

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/112697157/ec741f61-29e3-4479-8985-72c7e49823b2)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/112697157/d8897ae6-f35a-41e5-8905-264abaa2872a)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/112697157/6248d9b1-5ba0-49f8-a3cc-117e2f876388)

**Comment by MartinM85** [comment]
Not sure if it's related to Graph API itself. 

From my experience when you have opened SharePoint document library in the browser then edit some document and save it, the column "modified" is updated with a delay. It leads me to believe that the primary issue is a delay until the changes in a document are synced with SharePoint.

**Comment by wesleytan89** [comment]
yes. we met the same issue. maybe is there anyone who can explain the mechanism of the update?

**Comment by MartinM85** [comment]
@wesleytan89 It would be great and very useful. I didn't find any documentation, blog, etc. how the update works.

**Comment by andrueastman** [comment]
Any chance you can post the same question at the link below @jacobyang1205, @@wesleytan89 ?

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

As this is an API related question/behavior, and the repo is intended for SDK related issues, the API owners would be better placed to answer/give information about this. 
It would be great to post back the link of the question so that anyone who comes across this may find the info as well.
