### ISSUE TITLE
[Client bug]: TimeZoneNotSupportedException when retrieving users calendars schedules in a loop

### ISSUE THREAD

**Issue by HkonBj** [microsoftgraph/msgraph-sdk-dotnet#1893]
**Describe the bug**

When calling
`var response = await graphClient.Users[username].Calendar.GetSchedule.PostAsync(new Microsoft.Graph.Users.Item.Calendar.GetSchedule.GetSchedulePostRequestBody { AvailabilityViewInterval = minutes, EndTime = endTimeWithZone, StartTime = startTimeWithZone, Schedules = subEmailList }, x => { x.Headers.Add("Prefer", "outlook.timezone=\"Etc/GMT\""); });`
in a loop, you get an error back with code TimeZoneNotSupportedException and message"A valid TimeZone value must be specified. The following TimeZone value is not supported: ''." when the loop runs it second round. 

**To Reproduce**
```c#
public async Task<Schedule[]> GetSchedule(string[] emails, DateTime startDate, DateTime endDate, string timeZone = "Etc/GMT", int minutes = 30) {
var endTimeWithZone = new DateTimeTimeZone { DateTime = endDate.ToString("o"), TimeZone = timeZone };
var startTimeWithZone = new DateTimeTimeZone { DateTime = startDate.ToString("o"), TimeZone = timeZone };
// take the first 20 from emails array and add to subEmailList
while (subEmailList.Count() > 0 ) {
     using var graphClient = GetClient();
     var response = await graphClient.Users[username].Calendar.GetSchedule.PostAsync(new Microsoft.Graph.Users.Item.Calendar.GetSchedule.GetSchedulePostRequestBody { AvailabilityViewInterval = minutes, EndTime = endTimeWithZone, StartTime = startTimeWithZone, Schedules = subEmailList }, x => { x.Headers.Add("Prefer", "outlook.timezone=\"Etc/GMT\""); });
     var result = response.Value.Where(x => x.ScheduleItems != null).Select(x =>
    {
    // handle result
    }
    //add next set to subEmailsList from emails
}
``` 
```c#
        GraphServiceClient GetClient()
        {
           
            //Setup secret stuff
            return new GraphServiceClient(<insert secret stuff>,new[]{ "https://graph.microsoft.com/.default" });
        }
``` 

The function is called with only 3 parameters, using the default values for the 2 last parameters.
Note, subEmailList is email adresses with 20 or less in it. When the while loop runs for the second time, the exception happens. 
I tried having the client both inside and outside the loop. 
I tried with Parallel.ForEachAsync, with this, the error occurs only intermittently when client is created outside the loop, but it seems to always occur when inside.
We didn't use to have the header for timezone, but I added it as thinking that there might be something that required it, even though the docs says it is not required.

**Expected behavior**
I was expecting to get the next batch of user schedules.

**Client version**
Tried both 5.7.0 and 5.9.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by HkonBj** [comment]
That seemed to have done the trick @andrueastman, it passed testing.
Is this documented somewhere and I missed it? I followed the upgrade guide as best I could.

**Comment by andrueastman** [comment]
Apologies for the delayed response here. 

We've captured the backingstore in the upgrade guide [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#backing-store)but happy to take in contributions to make the documentation better.
