### ISSUE TITLE
Search does not correctly deserialize Resource property containing the search result item

### ISSUE THREAD

**Issue by edoust** [microsoftgraph/msgraph-sdk-dotnet#1899]
**Describe the bug**
When doing a search using `GraphServiceClient.Search.Query.PostAsync(...)` inside of a MAUI app on Mac Catalyst, the search results contain empty entities, they are not correctly deserialized even though the backing store has all the correct values.

The same code is working when being run inside of a Console App on the same machine. Requests being sent over the network do not differ for Console App and MAUI app.

**To Reproduce**
Use the attached project to reproduce.
[repro.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/11469956/repro.zip)

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 / maccatalyst

**Comment by andrueastman** [comment]
Possibly related to https://github.com/microsoft/kiota-serialization-json-dotnet/pull/86

**Comment by andrueastman** [comment]
Hey @edoust 

Any chance this works for you with the latest version after the fix applied via https://github.com/microsoft/kiota-serialization-json-dotnet/pull/86 ?

**Comment by edoust** [comment]
@andrueastman That fix is working for me
