### ISSUE TITLE
Suspected Bug - OneDrive Copy Item - GatewayTimeout at 10 seconds

### ISSUE THREAD

**Issue by jchilde** [microsoftgraph/msgraph-sdk-dotnet#190]
I am trying to copy files using onedrive copy using Microsoft Graph SDK (.net). I have found that files around 38mb fail with a gateway timeout status code.  This happens right at the 10 second mark.  

I expect an okay response with a location header.  

Files are being copied from and to a SharePoint document library. 

I am using the Microsoft graph .net sdk.   Smaller files copy without issue.

Here is my code:
``  
                try
            {
                var request = client.Drives[SourceDriveId].Root.ItemWithPath(itemFileName).Copy(parentReference: dest).Request();  //Path here is to parent folder. 

                HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Post, request.RequestUrl);
                hrm.Content = new StringContent(JsonConvert.SerializeObject(request.RequestBody), System.Text.Encoding.UTF8, "application/json");
                await client.AuthenticationProvider.AuthenticateRequestAsync(hrm);
           
                HttpResponseMessage response = await client.HttpProvider.SendAsync(hrm);
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                }
                
            }
            catch (Microsoft.Graph.ServiceException ex)
            {
                throw new Exception("Unknown Error");
            }

**Comment by MIchaelMainer** [comment]
@jchilde I'm going to ask about this and get back to you.

By the way, I find it interesting that you use the request builder to create the URL and body, and then HRM to send and get the response. What is your reason for that approach?

**Comment by jchilde** [comment]
I actually did it your way first.  Then shifted to the hrm approach to provide more granular control over he http client.  It has an overload to complete after receiving the header vice content. I also wanted to better see the response for troubleshooting.

My third try was pure httpclient.

All three have the exact same response.

I am not terribly good at c#, so I do a lot of things by trial and error

**Comment by MIchaelMainer** [comment]
That makes sense to me. There are times to drop back to HRM for sure. Okay, I got back information that this is a known issue. There's nothing we can do on the client-side. Still, while the web request fails with the Gateway Timeout, you should see that the copy operation still succeeds on OneDrive. Can you confirm that the drive item is still copied?

**Comment by jchilde** [comment]
It is still copied Most of the time, but it does seem like there is a max size around 50mb.

Why is this not listed as a known issue and why isn't a max file size declared?

Sent from my iPhone

On Oct 4, 2017, at 1:36 PM, Michael Mainer <notifications@github.com<mailto:notifications@github.com>> wrote:


That makes sense to me. There are times to drop back to HRM for sure. Okay, I got back information that this is a known issue. There's nothing we can do on the client-side. Still, while the web request fails with the Gateway Timeout, you should see that the copy operation still succeeds on OneDrive. Can you confirm that the drive item is still copied?

**Comment by MIchaelMainer** [comment]
@jchilde I've added this to the known issues doc with this pull request: https://github.com/microsoftgraph/microsoft-graph-docs/pull/1826. I've got a question out about the max file size.
