### ISSUE TITLE
graphServiceClient.Me.SendMail.PostAsync(requestBody) failed to send email

### ISSUE THREAD

**Issue by wengkit8039** [microsoftgraph/msgraph-sdk-dotnet#1902]
**Describe the bug**
Using latest Graph v5.10.0
The code run without returning error but email are not send to the recipient and was not save in sent box even though SaveToSentItems parameter set to true. Delegated permission "Mail.Send" been granted through user consent and tested with other function graphClient.Chats[chatId].Messages.PostAsync(requestBody) which working fine.
 
Below are my code:
UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredential("username@domain.com", "password", tenantId, clientId);
GraphServiceClient graphClient = new GraphServiceClient(usernamePasswordCredential, scopes); 

var requestBody = new Microsoft.Graph.Me.SendMail.SendMailPostRequestBody
{
	Message = new Message
	{
		Subject = "Meet for lunch?",
		Body = new ItemBody
		{
			ContentType = BodyType.Text,
			Content = "The new cafeteria is open.",
		},
		ToRecipients = new List<Recipient>
		{
			new Recipient
			{
				EmailAddress = new EmailAddress
				{
					Address = "frannis@contoso.onmicrosoft.com",
				},
			},
		},
		CcRecipients = new List<Recipient>
		{
			new Recipient
			{
				EmailAddress = new EmailAddress
				{
					Address = "danas@contoso.onmicrosoft.com",
				},
			},
		},
	},
	SaveToSentItems = true,
};
await graphClient.Me.SendMail.PostAsync(requestBody);

**Comment by andrueastman** [comment]
Thanks for raising this @wengkit8039,

To confirm, any chance this is replicated when you make a similar request using the Graph Explorer? http://aka.ms/ge

**Comment by wengkit8039** [comment]
Tested with both Graph Explorer and Postman, it working as expected.

**Comment by wengkit8039** [comment]
Found out the issue. The code was accidentally was reside in void function instead of async Task which causing this. Kindly close this. Thanks
