### ISSUE TITLE
Whether there are azure ad b2c, angular and asp.net core 2.0 example

### ISSUE THREAD

**Issue by HeMinzhang** [microsoftgraph/msgraph-sdk-dotnet#191]
Whether there are azure ad b2c, angular and asp.net core 2.0 example

**Comment by cbales** [comment]
Are you looking for auth samples?

Here are a couple samples that may help you out:
[AAD + ASP.NET Core](https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2)
[AAD + Angular.js](https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp)

**Comment by HeMinzhang** [comment]
Sorry for my poor English, I need Active Directory B2C, msgraph and Asp.net core 2.0 Json Web Token Sample.

**Comment by HeMinzhang** [comment]
I found the information I wanted, thank you very much

**Comment by Pato2790** [comment]
Hello!

Could you shared with me how you solved this problem? 

Thanks you
