### ISSUE TITLE
Is MS Graph SDK v5.0 is not supporting adding encrypted certificate to a subscription?

### ISSUE THREAD

**Issue by mohammadamer** [microsoftgraph/msgraph-sdk-dotnet#1911]
I've participated to MS Graph Hack Together. I wanted to achieve adding an encrypted certificate to a subscription then use this certificate to decrypt the chat message content, but I couldn't do that in MS Graph v5.0, I had to downgrade to v3.0 in order to achieve that.

Is MS Graph v5.0 is supporting this or not?
I wanted to give my [feedback](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-early-adopter-recognition-program/) as per my understanding and understand if it's supporting this or not. If it's supporting this, then how to do that.
Here you will find [my solution](https://github.com/mohammadamer/GraphDotNetHack/tree/main) that is using MS Graph SDK v3.0

I would appreciate if you can explain how can do that in my simple solution.

**Comment by andrueastman** [comment]
Closing this for now as a duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2237. Issue will be tracked there
