### ISSUE TITLE
Filter userName (issuerAssignedId) with 5.x for Azure B2C tenant

### ISSUE THREAD

**Issue by cBashTN** [microsoftgraph/msgraph-sdk-dotnet#1914]
**Describe the bug**
Not sure if this is a big or just by design.
When upgrading from 4.x to 5.x I fail to filter for a issuerAssignedId of a Azure B2C tenant. It worked with 4.53.
I might doing it wrong.

**To Reproduce**
1. I successfully used 4.54 and filtered the user with
```csharp            
// Get user id by sign-in name
var response = await _graphClient.Users
                           .Request()
                           .Filter($"identities/any(c:c/issuerAssignedId eq '{userName}' and c/issuer eq '{TenantId}')")
                           .Select(e => new { e.Id })
                           .GetAsync();
var userId = response .SingleOrDefault()?.Id;

//  private const string TenantId = something like "contoso.onmicrosoft.com";
//  Identities[].SignInType is "userName"
```

2. I upgraded to 5.x and various API calls are working ("Add user to group", "Get self-created attributs", "Get members of group",...)
I get this unhelpful expection 'Exception of type `Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.` using this
```csharp            
// Get user id by sign-in name
 var result = await _graphClient.Users.GetAsync((requestConfiguration) =>
      {
                    requestConfiguration.QueryParameters.Select = new string []{ "id" };
                    requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
                    requestConfiguration.QueryParameters.Filter = $"identities/any(c:c/issuerAssignedId eq '{userName}' and c/issuer eq '{TenantId}'";
      });
```

**Expected behavior**
- I would expect to not have an exception.

- I would hoped for better documentation.
  - The HTTP 'filter' example include the "admin@contoso.com" filter value:
 
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3204574/70b7c2f4-e657-4881-a9ed-8920f5c8925d)

  - The C# 'filter' example does not have a filter value:
 
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3204574/d0ff6b15-b0b2-4504-848c-6336b2be0abf)

**Comment by andrueastman** [comment]
Thanks for raising this @cBashTN 

> I upgraded to 5.x and various API calls are working ("Add user to group", "Get self-created attributs", "Get members of group",...)
I get this unhelpful expection 'Exception of type Microsoft.Graph.Models.ODataErrors.ODataError' was thrown. using this

Any chance you are able to share more details on the error by following the guidaince at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by cBashTN** [comment]
@andrueastman Of course:
Console.WriteLine(odataError.Error.Code);  ->  "BadRequest"
Console.WriteLine(odataError.Error.Message);  ->  "Invalid filter clause"
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3204574/15958243-4c67-46c8-b5a0-4a16cef08171)

**Comment by cBashTN** [comment]
@andrueastman I found the issue thanks to the better error handling.
I missed a `)` at the end of the filter command.

requestConfiguration.QueryParameters.Filter = $"identities/any(c:c/issuerAssignedId eq '{userName}' and c/issuer eq '{TenantId}'**)**";   <--

Before you close this 'issue'. Can you guys update the documentation of the C# filter?
See https://github.com/microsoftgraph/microsoft-graph-docs/issues/21388
