### ISSUE TITLE
[Client bug]: Enum Flag not supported

### ISSUE THREAD

**Issue by karthikd70** [microsoftgraph/msgraph-sdk-dotnet#1915]
**Describe the bug**
Enum Flags are not supporting and causing issues when we have to use combination of Enum values.

**To Reproduce**
Below code fails because ExportOptions enum does not have Flag attribute.
var graphClient = new GraphServiceClient(requestAdapter);

var requestBody = new Microsoft.Graph.Beta.Security.Cases.EdiscoveryCases.Item.ReviewSets.Item.MicrosoftGraphSecurityExport.ExportPostRequestBody
{
	OutputName = "Export via API",
	Description = "Export for the Contoso investigation",
	ExportOptions = **Microsoft.Graph.Beta.Models.Security.ExportOptions.OriginalFiles | Microsoft.Graph.Beta.Models.Security.ExportOptions.FileInfo | Microsoft.Graph.Beta.Models.Security.ExportOptions.Tags,**
	ExportStructure = Microsoft.Graph.Beta.Models.Security.ExportFileStructure.Directory,
};
await graphClient.Security.Cases.EdiscoveryCases["{ediscoveryCase-id}"].ReviewSets["{ediscoveryReviewSet-id}"].MicrosoftGraphSecurityExport.PostAsync(requestBody);

**Expected behavior**
Should support Enum Flags

**Screenshots**
ExportOptions enum is missing Flag attribute
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/029b2f62-4544-4aa1-96a8-3b811e13a5ff)

**Client version**
5.11.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Additional context**
Seems Open API does not support enum flags as per this link https://stackoverflow.com/questions/71171658/swagger-bitwise-enum-flags-handling. Need a workaround.

**Comment by karthikd70** [comment]
@andrueastman Can you please provide a workaround for this issue till it can be resolved. Thanks.

**Comment by karthikd70** [comment]
@andrueastman Please look into this. We are blocked. Thanks

**Comment by ddyett** [comment]
@rkodev is this similiar to the issue we're seeing with go as well.
