### ISSUE TITLE
Why doesn't the Microsoft Graph client library contain its own authentication provider?

### ISSUE THREAD

**Issue by HeMinzhang** [microsoftgraph/msgraph-sdk-dotnet#192]
Why msgraph-sdk-dotnet does not support Azure Active Directory B2C, or merge with microsoft-authentication-library-for-dotnet

**Comment by HeMinzhang** [comment]
Thanks a millon, MIchaelMainer,I use Graph client dotnet and Msal donet develop asp.net core 2.0 web app.I am confused about how to use Graph client donet and Msal donet api.Fortunately, the code is open source and  source sample.

**Comment by MIchaelMainer** [comment]
You're welcome @HeMinzhang. Have you seen this sample: https://github.com/microsoftgraph/aspnet-snippets-sample? It may be what you need.

With regards,
Michael
