### ISSUE TITLE
Base class for eg ContactsRequestBuilderGetRequestConfiguration

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#1921]
I'd like to set "common" properties (think page size) for a lot of GetAsync(requestBuilder => ...) calls. This however is made super-complicated because there is no interface or common base class, eg

```
        public class ContactsRequestBuilderGetRequestConfiguration {
            /// <summary>Request headers</summary>
            public RequestHeaders Headers { get; set; }
            /// <summary>Request options</summary>
            public IList<IRequestOption> Options { get; set; }
            /// <summary>Request query parameters</summary>
            public ContactsRequestBuilderGetQueryParameters QueryParameters { get; set; } = new ContactsRequestBuilderGetQueryParameters();
            /// <summary>
            /// Instantiates a new contactsRequestBuilderGetRequestConfiguration and sets the default values.
            /// </summary>
            public ContactsRequestBuilderGetRequestConfiguration() {
                Options = new List<IRequestOption>();
                Headers = new RequestHeaders();
            }
        }
```

Now I have to tease that object apart every time and pass on its internal properties to a common method (because RequestHeaders and friends ARE reused).

**Comment by andrueastman** [comment]
This will be part of the next major version  as this will be a breaking change and the configuration class should end inheriting from
the base class at the link below. 

https://github.com/microsoft/kiota-abstractions-dotnet/blob/main/src/RequestConfiguration.cs

**Comment by christophwille** [comment]
That is exactly what I was looking for (now looking forward to).
