### ISSUE TITLE
Batch operation in the Graph SDK failed with "Bad Request UnableToDeserializePostBody" error 

### ISSUE THREAD

**Issue by devdav2000** [microsoftgraph/msgraph-sdk-dotnet#1924]
**Describe the bug**
Batch operation in the GraphApi SDK failed with "Bad Request UnableToDeserializePostBody" error , when using it to create the meeting directly using the SDK (serialy not bath) , the operations succeeds correctly.

**To Reproduce**
1. open visual studio c# code
2. create reference to 4.43 GRAPH API SDK
3. used this code to create event in batching
4. Bug: Get "Bad Request"+ “UnableToDeserializePostBody” ERRORS
 
    var ev = new Event
     {
                Subject = "Let's go for lunch",
                Body = new ItemBody
                {
                    ContentType = BodyType.Html,
                    Content = "Does noon work for you?"
                },
                Start = new DateTimeTimeZone
                {
                    DateTime = "2022-11-27T12:00:00",
                    TimeZone = "Pacific Standard Time"
                },
                End = new DateTimeTimeZone
                {
                    DateTime = "2022-11-27T14:00:00",
                    TimeZone = "Pacific Standard Time"
                },
                Location = new Location
                {
                    DisplayName = "Harry's Bar"
                },
               
                AllowNewTimeProposals = true,
                TransactionId = "7E163156-7762-4BEB-A1C6-729EA81755A7"
       };
 
 
             var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, “[https://graph.microsoft.com:443/v1.0/users/someyser@mydomain/events](https://graph.microsoft.com/v1.0/users/someyser@mydomain/events)”)
                {
                    Content = new StringContent(JsonConvert.SerializeObject(event), Encoding.UTF8, "application/json")
                };
 
 
 
BatchRequestStep requestStep = new BatchRequestStep(userCalendarItems.EntityItems.IndexOf(calendarItem).ToString(), httpRequestMessage, null);
             batchRequestContent.AddBatchRequestStep(requestStep);
 
…
             batches.Add(batchRequestContent);
 
Graphapiclient.Batch.Request().PostAsync(batch);
 
 
I got this error:
 
"Bad Request"+ “UnableToDeserializePostBody”
 
 
Remark:
•         If I work without BATCH POST but  something like: Graphapiclient .Users[useremail].Events.Request().AddAsync(ev);  All works just good and Event created!

**Expected behavior**
Get success status from sdk, and event created successfully in calendar

**Desktop:**
Using  visual studio to run client call to Microsoft graph api sdk

**Additional context**
Deleting in batching works fine. Failed in Batch creation of new event.

**Comment by andrueastman** [comment]
Thanks for raising this @devdav2000 

I suspect the issue lies with the code below as it looks like the content is serialized with NewtonSoft.

```cs
var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, “[https://graph.microsoft.com:443/v1.0/users/someyser@mydomain/events](https://graph.microsoft.com/v1.0/users/someyser@mydomain/events)”)
 {
     Content = new StringContent(JsonConvert.SerializeObject(event), Encoding.UTF8, "application/json")
 };
```

Any chance you have a different result once you create the message as below by leveraging the `SerializeAsJsonContent` method?

```cs
var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, "https://graph.microsoft.com/v1.0/users/someyser@mydomain/events")
{
    Content = graphClient.HttpProvider.Serializer.SerializeAsJsonContent(eventExample)
};
```

**Comment by andrueastman** [comment]
Closing this for now. Errors due to trying to serialize non json content are fixed in the latest sdk versions via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/701
