### ISSUE TITLE
[Client bug]: v5 client generates invalid URL for the workbook sub-resource of a driveitem by path

### ISSUE THREAD

**Issue by nickwb** [microsoftgraph/msgraph-sdk-dotnet#1927]
**Describe the bug**
The URL generated by the WorkbookRequestBuilder is incorrect when DriveItem ItemByPath is used.

```csharp
var myDriveId = "xxx";
var myItemPath = "path/to/item.xlsx";
var myItemId = "yyy";

// This request produces an incorrect URL
var requestBroken = _graphClient.Drives[myDriveId].Root.ItemWithPath(myItemPath).Workbook;

// This request produces a correct URL
var requestWorking = _graphClient.Drives[myDriveId].Items[myItemId].Workbook;
```

**Expected behavior**
The SDK should generate a URL like this:

`https://graph.microsoft.com/v1.0/drives/xxx/root:/path/to/item.xlsx:/workbook`

But instead it generates a URL like this:
`https://graph.microsoft.com/v1.0/drives/xxx/items//workbook`

**Client version**
5.11.0

**Desktop:**
 - OS: Windows 10

**Comment by andrueastman** [comment]
Closing this as this is now working with the latest version 
https://www.nuget.org/packages/Microsoft.Graph/5.13.0
