### ISSUE TITLE
[Client bug]: Url template for ReviewSet export is wrong

### ISSUE THREAD

**Issue by karthikd70** [microsoftgraph/msgraph-sdk-dotnet#1932]
**Describe the bug**
ReviewSet export is failing because the url template is wrong.
The url working in graph explorere is https://graph.microsoft.com/beta/security/cases/ediscoveryCases/{caseId}/reviewSets/{reviewsetId}/export.
But the UrlTemplate in sdk is "{+baseurl}/security/cases/ediscoveryCases/{ediscoveryCase%2Did}/reviewSets/{ediscoveryReviewSet%2Did}/security.export".
We should remove "security.".

**To Reproduce**
var graphClient = new GraphServiceClient(requestAdapter);

var requestBody = new Microsoft.Graph.Beta.Security.Cases.EdiscoveryCases.Item.ReviewSets.Item.MicrosoftGraphSecurityExport.ExportPostRequestBody
{
	OutputName = "Export via API",
	Description = "Export for the Contoso investigation",
	ExportOptions = Microsoft.Graph.Beta.Models.Security.ExportOptions.OriginalFiles | Microsoft.Graph.Beta.Models.Security.ExportOptions.FileInfo | Microsoft.Graph.Beta.Models.Security.ExportOptions.Tags,
	ExportStructure = Microsoft.Graph.Beta.Models.Security.ExportFileStructure.Directory,
};
await graphClient.Security.Cases.EdiscoveryCases["{ediscoveryCase-id}"].ReviewSets["{ediscoveryReviewSet-id}"].MicrosoftGraphSecurityExport.PostAsync(requestBody);

**Expected behavior**
Export should not get failed.

**Screenshots**

**Client version**
5.11.0

**Desktop (please complete the following information):**

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @karthikd70 

Just to confirm, as the API call is made to the beta endpoint, is there a specific reason to not use the [beta package](https://www.nuget.org/packages/Microsoft.Graph.Beta)?

The beta repo has the relevant template as can be seen at the link below.

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/Security/Cases/EdiscoveryCases/Item/ReviewSets/Item/MicrosoftGraphSecurityExport/MicrosoftGraphSecurityExportRequestBuilder.cs#L27

**Comment by karthikd70** [comment]
@andrueastman - Thanks for the update. Seems it is corrected in latest beta package. I was using beta package for export, but accidentally posted here.
