### ISSUE TITLE
Microsoft Learn Student Ambassador Details Profiler

### ISSUE THREAD

**Issue by kelcho-spense** [microsoftgraph/msgraph-sdk-dotnet#1936]
I'm proposing a functionality that allows developers to visit MLSA profiles and view all approved events and activities they've completed. This feature is not available on the https://studentambassadors.microsoft.com website, therefore you can only view events and activities that have been starred by an MLSA. This number is restricted to no more than ten events.If this feature is available, it will allow MLSA developers to create applications on teams such as MLSA profiler, which will inspire new or Alpha MLSAs to be active and impactful because they will be able to see all of the achievements of the MLSAs who are ahead of them, such as the Beta and Gold MLSAs.
Furthermore, this feature can combine Microsoft activities such as the Imagine Cup competition, which if an MLSA has participated in, can be an excellent opportunity to showcase their accomplishments.

**Comment by andrueastman** [comment]
Thanks for raising this @kelcho-spense 

As this repository is intended for issues related to the Microsoft Graph SDK, this would not be the best place with regards to feedback for MLSA. 
However, it should be possible to contact `sa-help@microsoft.com` and provide information on the same. 

We'll close this issue for now and feel free to try out the SDK and Microsoft Graph.

**Comment by kelcho-spense** [comment]
Thank sir for your response, I really appreciate it.
