### ISSUE TITLE
Microsoft.Graph.Core mismatch

### ISSUE THREAD

**Issue by bertsinnema** [microsoftgraph/msgraph-sdk-dotnet#194]
When I install the NuGet package for 1.6.0 I get this error message:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1705	Assembly 'Microsoft.Graph' with identity 'Microsoft.Graph, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Graph.Core, Version=1.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Graph.Core' with identity 'Microsoft.Graph.Core, Version=1.6.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	CSOMTest	C:\Users\BertSinnema\Documents\Visual Studio 2017\Projects\CSOMTest\CSOMTest\CSC	1	Active

**Comment by MIchaelMainer** [comment]
You'll need to install Microsoft.Graph.Core 1.6.2 package. We'll be updating the package so that this error doesn't occur.

**Comment by MIchaelMainer** [comment]
Please install the Microsoft.Graph 1.6.2 Nuget package to resolve this.
