### ISSUE TITLE
 Issue Regarding MS Graph 4.35.0 AdditionalData property 

### ISSUE THREAD

**Issue by marzoukali** [microsoftgraph/msgraph-sdk-dotnet#1943]
Hello

I am writing to bring an issue to your attention that I have encountered in one of our applications using MS Graph 4.35.0. 

In this application, I utilize the method "DirectoryObjects.GetByIds", which requires two parameters - objectIds and types ("user") - the latter being a list of the user type.

Typically, the method returns an object with an **AdditionalData** property. However, from May 17th, the AdditionalData property was unexpectedly returning as null. This unexpected change caused issues in our code, which anticipates the presence of the AdditionalData response.

Interestingly, as of May 30th, the AdditionalData response has been coming through as expected once again, without any alteration to the code on our end.

Upon experimentation, I discovered that if I removed the "users" type, the AdditionalData was returned as expected during the problematic period. It's puzzling because there were no changes made to my code, yet the response contract fluctuated between May 17th and May 30th.

I have attempted to find any relevant information in the MS Graph changelog or in reported bug fixes, but to no avail.

Could you please provide some insight into this inconsistency? I'm particularly interested in knowing whether this is a potential ongoing issue that we may encounter again in the future. Any guidance or advice you could provide would be greatly appreciated.

Thank you for your time and assistance.

**Comment by andrueastman** [comment]
Thanks for raising this @marzoukali 

For context, the `AdditionalData` property is used by the serializer to hold properties that the API may return in the json object that are not described/mapped to properties in the relevant model which is being deserialized into. 

If API returns only properties that are mapped to the model, there will be no extra properties to be held in the  `AdditionalData` and therefore it won't be initialized by the deserializer. However, the property will always be initialized(not null) in V5 of the SDK and above. (It would be advisable to check if the property is not null before dereferencing it if using earlier SDK versions.)

As to the fluctuation of the API response shape, as this repo is intended for SDK related issues any chance you can post a question at the link below as the API owners would be better placed to explain what may have been occurring during that period.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by andrueastman** [comment]
@marzoukali If you can, any chance you could past back the link to the created query as a comment on this issue? It would be great so that anyone who comes across this may also be able to find the information from the API side. 

> https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by marzoukali** [comment]
Thanks @andrueastman . This is the link for the query: https://learn.microsoft.com/en-us/answers/questions/1296769/issue-regarding-ms-graph-api-when-using-the-sdk-4

**Comment by andrueastman** [comment]
We'll close this here so that it may be followed up at the link provided.
