### ISSUE TITLE
`sendActivityNotificationToRecipients` seemingly does not work

### ISSUE THREAD

**Issue by mzietlow** [microsoftgraph/msgraph-sdk-dotnet#1946]
**Describe the bug**
When sending Teams Activity Notifications to a single user by posting to the `/users/{userId}/teamwork/sendActivityNotification`-endpoint the notification is received in near real time.

When posting the (almost identical) request to the `/teamwork/sendActivityNotificationToRecipients` for a single user, the Activity Notification does not arrive at all, even after waiting for several hours. (Still waiting.) As a side note: both requests return `202` as a response.

This has a significant impact on the effectiveness of our Activity Notification Jobs, since we are forced to send out a new request for every single recipient, using the per-user-endpoint.

**To Reproduce**

For the sake of conciseness, I will post only the concrete json body. If required, I can also paste my C#-code.

**Bulk-Endpoint (Not Working)**
Endpoint: `POST https://graph.microsoft.com/v1.0/teamwork/sendActivityNotificationToRecipients` 
``` JSON
{
    "topic": {
        "source": "text",
        "value": "Test",
        "webUrl": "https://teams.microsoft.com/l/entity/f5234d0e-d010-4927-a=6f4-2bde252cee16/my-app"
    },
    "activityType": "myActivityType",
    "previewText": {
        "content": "Test"
    },
    "recipients": [
        {
            "@odata.type": "microsoft.graph.aadUserNotificationRecipient",
            "userId": "7c4a251f-7553-4ce2-8bce-96513a4ce30c"
        }
    ],
    "templateParameters": [
        {
            "name": "TestParam",
            "value": "Test"
        }
    ]
}
```

**User-Endpoint (Works like a charm)**
Endpoint: `POST https://graph.microsoft.com/v1.0/users/7c4a251f-7553-4ce2-8bce-96513a4ce30c/teamwork/sendActivityNotification` 
``` JSON
{
    "topic": {
        "source": "text",
        "value": "Test",
        "webUrl": "https://teams.microsoft.com/l/entity/f5234d0e-d010-4927-a=6f4-2bde252cee16/my-app"
    },
    "activityType": "myActivityType",
    "previewText": {
        "content": "Test"
    },
    "templateParameters": [
        {
            "name": "TestParam",
            "value": "Test"
        }
    ]
}
```
**Expected behavior**
I expect that activity feed notifications actually appear (in a reansonable timeframe, e.g. ≪ 60 minutes) for my users when `POST`ing to the endpoint `/teamwork/sendActivityNotificationToRecipients`.

**Desktop (please complete the following information):**

 - MSGraph .NET SDK v5.12.0
 - MSGraph v1.0

**Comment by andrueastman** [comment]
Thanks for raising this @mzietlow 

As the payload looks consistent with[ the documentation ](https://learn.microsoft.com/en-us/graph/api/teamwork-sendactivitynotificationtorecipients?view=graph-rest-1.0) and returns a success code, any chance you can post the issue at the link below to get feedback from the API owners? 
If you could post back the link to the same, that would be great as it would help anyone who comes across this find the information.

https://learn.microsoft.com/en-us/answers/tags/282/microsoft-graph-teamwork-api
