### ISSUE TITLE
[Client bug]: Problem with PageIterator

### ISSUE THREAD

**Issue by BraunJonathan** [microsoftgraph/msgraph-sdk-dotnet#1953]
**Describe the bug**
Compiltation problem when using PageIterator
error CS0029: Cannot implicitly convert type 'bool' to 'System.Threading.Tasks.Task<bool>'
error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

Same problem as issues #1847 and #1676  

**To Reproduce**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/35366413/15a4b284-7bf7-4d94-b838-f438b27466dc)

**Expected behavior**
The code compiles

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/35366413/77da0c95-2845-42ed-82e0-c5d36a82d29d)

**Client version**
I tried with several versions from 5.0.0 to 5.12.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2022

**Additional context**

**Comment by MartinM85** [comment]
You are missing `await` when calling `GetSync`

        public async void getNonCertifiedGroups()
        {
            var groups = await _client.Groups.GetAsync(cfg => { });

            var pageIterator = PageIterator<Group, GroupCollectionResponse>
                .CreatePageIterator(
                    _client,
                    groups,
                    (group) =>
                    {
                        return true;
                    }
                );

            await pageIterator.IterateAsync();
        }

**Comment by BraunJonathan** [comment]
Oh sh.. i'm an idiot 😅

Thank you so much !!

We can close this...
