### ISSUE TITLE
[Client bug]: Missing GetAsync for Teams v5

### ISSUE THREAD

**Issue by edwinvandriel** [microsoftgraph/msgraph-sdk-dotnet#1956]
When trying to get the collection of teams from the SDK the <client>.Teams.GetAsync() is missing. There is only a PostAsync available.

Graph url: https://graph.microsoft.com/v1.0/teams (GET)
Client SDK version: 5.12.0

**Comment by andrueastman** [comment]
Depends on https://github.com/microsoftgraph/msgraph-metadata/issues/356
