### ISSUE TITLE
CompactToken parsing failed with error code: -2147184105

### ISSUE THREAD

**Issue by HeMinzhang** [microsoftgraph/msgraph-sdk-dotnet#196]
this is my code:

>                    var identity = User.Identity as ClaimsIdentity;
>                     var userAccessToken = identity?.BootstrapContext as string;
>                   GraphServiceClient graphClient = _graphSdkHelper.GetAuthenticatedClient(userAccessToken);
>                   var groups = await graphClient.Groups.Request().GetAsync();

and

>   _graphClient = new GraphServiceClient(new DelegateAuthenticationProvider(
>                  async (requestMessage) =>                
>                 {
>                      await Task.Run(() => {
>                         requestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
> 
>                          // Get event times in the current time zone.
>                          requestMessage.Headers.Add("Prefer", "outlook.timezone=\"" + TimeZoneInfo.Local.Id + "\"");
> 
>                          // This header has been added to identify our sample in the Microsoft Graph service. If extracting this code for your project please remove.
>                       requestMessage.Headers.Add("SampleID", "Kop");
>                     });
>                 }));
> 
>              return _graphClient;
> 

I create a azure ad b2c name is B2CTest,and B2CTest based azure ad name is TestAd.

TestAd setting msgraph,and get  B2CTest user token pass to msgraph. and  msgraph get user own's group.

I get microsoftgraph post http packet.

address:

https://graph.microsoft.com/v1.0/groups

response:

{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "e715c5f9-5c2c-40d8-ad09-71c848205d2c",
      "date": "2017-10-09T16:10:20"
    }
  }
}

**Comment by MIchaelMainer** [comment]
Hello @HeMinzhang 

This is an issue with getting an access token. This is not an issue with the client library. I suggest that you post your question with clear repro steps to StackOverflow. Make sure you tag the post with the appropriate authentication library.

With regards,
Michael

**Comment by HeMinzhang** [comment]
![qq 20171012110557](https://user-images.githubusercontent.com/2683269/31477352-1e00b9b0-af3e-11e7-887b-05bc99862194.png)
  
![qq 20171012110505](https://user-images.githubusercontent.com/2683269/31477348-186ce294-af3e-11e7-8bef-a8c53ac6ee25.png)

@MIchaelMainer I found,that aad b2c access token and aad access token are not the same.Msgraph-sdk don't support aad b2c.

**Comment by MIchaelMainer** [comment]
@HeMinzhang Thank you for providing this information and closing the loop on this.
