### ISSUE TITLE
Regarding #1814 Read Hidden Emails from the users mailbox using Graph API 5.5.0 - Need example on how this can be done with SDK

### ISSUE THREAD

**Issue by tejasonweb** [microsoftgraph/msgraph-sdk-dotnet#1962]
I have attempted to use the property includeHiddenMessages to list out all the associated items from the inbox folder however I am unable to do it.

If I print requestInformation (var requestInformation = _userClient.Me.Messages.ToGetRequestInformation()), I see below:

`{+baseurl}/me/messages{?includeHiddenMessages*,%24top,%24skip,%24search,%24filter,%24count,%24orderby,%24select,%24expand}`

This means I now have property includeHiddenMessages available however how can I use it?

Moreover, with this, I also need to use other properties like select, top and orderby.

I am trying to do this with the sample application I have downloaded from below link:

[Microsoft Graph quick start](https://developer.microsoft.com/en-us/graph/quick-start)

Code I am using:

        var requestinformation = _userClient.Me.Messages.ToGetRequestInformation();
        requestinformation.QueryParameters.Add("includeHiddenMessages", "true");
        requestinformation.QueryParameters.Add("Top", "25");
        requestinformation.QueryParameters.Add("select", new[] { "from", "isRead", "receivedDateTime", "subject" });
        requestinformation.QueryParameters.Add("Orderby", new[] { "receivedDateTime DESC" });

If I try to add includeHiddenMessages to MessagesRequestBuilderGetQueryParameters object, it errors out as below:

MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters' does not contain a definition for 'includeHiddenMessages' and no accessible extension method 'includeHiddenMessages' accepting a first argument of type 'MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters' could be found (are you missing a using directive or an assembly reference?)

I am using Graph 5.13.0

**Comment by MartinM85** [comment]
When creating request information you can specify the value for `includeHiddenMessages` in request configuration

    var requestInfo = _client.Me.Messages.ToGetRequestInformation(requestConfiguration =>
   {
       requestConfiguration.QueryParameters.IncludeHiddenMessages = "true";
   });

Similar when creating request

   var result = await _client.Me.Messages.GetAsync((requestConfiguration) =>
   {
       requestConfiguration.QueryParameters.IncludeHiddenMessages = "true";
   });

@andrueastman I couldn't find any documentation for `includeHiddenMessages`. How does it work?

**Comment by andrueastman** [comment]
As @MartinM85 suggests, 

The code should be 

```cs
        var result = await graphClient.Me.Messages.GetAsync((requestConfiguration) =>
        {
            requestConfiguration.QueryParameters.IncludeHiddenMessages = "true";
        });
```

Any chance this works out for you @tejasonweb?

@MartinM85 Do you mean the query parameter is not documented or throws an error?

**Comment by MartinM85** [comment]
@andrueastman I mean that similar query parameter `includeHiddenFolders` is well [documented](https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http#optional-query-parameters) but there is no documentation for `includeHiddenMessages`. Not sure what hidden messages can be.

**Comment by tejasonweb** [comment]
Thank you @MartinM85 and @andrueastman, the above provided snippet allowed me to compile the program however I was still not able to see the associated items (hidden email items) from the inbox. If I open the exchange online mailbox using MFCMapi and open inbox for associated items, I see a bunch of items which are not shown in the result.

Previously, I was trying to fetch the hidden items from folder: Inbox using below code which is erroring out with the error I mentioned in issue description at the end:

```
var messages = await _userClient.Me.MailFolders["Inbox"].Messages.GetAsync((requestConfiguration) =>
        {
            requestConfiguration.QueryParameters.Top = 100;
            requestConfiguration.QueryParameters.IncludeHiddenMessages = "true";
        });
```

However if I use:

`var messages = await _userClient.Me.Messages.GetAsync((requestConfiguration)`

It allows me to use "IncludeHiddenMessages" query parameter.

**Comment by tejasonweb** [comment]
Hey Team,

Just wondering if you have any questions or need more information on this.

Thank you!

**Comment by MartinM85** [comment]
Hi @tejasonweb, maybe if you can explain me how includeHiddenMessages works? Cannot find any info what hidden messages are and how to hide some message (through Graph API or in the Outlook client). 🙂

**Comment by tejasonweb** [comment]
Hi @MartinM85,

I am really sorry for not providing all the details.

What I really want to achieve with Graph is to find an associated items (hidden items) from the given folder. 

These items are not visible when we open the folder in outlook or we specifically open the "contents table" via MFCMAPI.

We can view associated or hidden items via MFCMAPI using "Open associated contents table" option. It shows the hidden items like this:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/12368930/717226e4-7f13-435b-97c7-a220bd54e5e0)

I can view such items using EWS Managed API as well using below code:

                ItemView iv = new ItemView(ViewItemCount);

                iv.Traversal = ItemTraversal.Associated;

                FindItemsResults<Item> items = CurrentFolder.FindItems(EVSettingsItemsFilter, iv);

[ItemTraversal Enum](https://learn.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.itemtraversal?view=exchange-ews-api)

By settings ItemView objects Traversal property to ItemTraversal.Associated, I can fetch (only) the hidden items from any folder.

This is important for my application as it only works if I can fetch the hidden items from the given mailbox.

Is there a way I can currently do that in GRAPH? I have already tested includeHiddenMessages property which seems to not be fetching the results I am looking for.

**Comment by tejasonweb** [comment]
Guys, please let me know if you need any further details on this.

Thank you!

**Comment by andrueastman** [comment]
@tejasonweb Any chance you can confirm if this is still an issue?
