### ISSUE TITLE
Mail is not found when searched with filter

### ISSUE THREAD

**Issue by ElisaKonietzka** [microsoftgraph/msgraph-sdk-dotnet#1963]
Sometimes a mail can't be found, by using
```
var result = await graphClient.Me.Messages.GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Filter = $"Subject eq 'subject 1'";
});
```
even though a mail with subject "subject 1" is listed in
```
var resultMore = await graphClient.Me.Messages.GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Select = new string[] { "subject" };
});
```

This behaviour doesn't always occur.
It's independent of timing between the two calls. I have the issue regardless what I execute first.

I'm currently using Microsoft.Graph version 5.4.0

**Comment by andrueastman** [comment]
Thanks for raising this @ElisaKonietzka 

To confirm the result in the first call sometimes returns an empty list while sometimes it does not?

**Comment by ElisaKonietzka** [comment]
It depends on the mail. For some mails it returns a result. For others Value is a empty List.
Here is a little example. For x[4] and x[6] the first call returns an empty list. For the other subjects in x the first call returns one mail as value
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/98532219/ff46be22-c619-496b-b542-ee771f8882a7)

**Comment by andrueastman** [comment]
As the `eq` does an exact match on the subject title, I think there won't be a match for those items in the list. It looks like there is an extra space character at the end of x[4] which the search parameter does not.

Any chance you intend to use a contains filter?

```cs
var result = await graphClient.Me.Messages.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Filter = "contains(subject,'azure')";
});
```
