### ISSUE TITLE
Microsoft.Graph.Applications indexer does not work

### ISSUE THREAD

**Issue by Neutrino-Sunset** [microsoftgraph/msgraph-sdk-dotnet#1965]
**Describe the bug**

The indexer on the Microsoft.Graph.Applications class does not work.

The documentation here states the indexer should be passed an application ID and it will return the application.

https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=csharp#request

**To Reproduce**

``` csharp
[FunctionName("GraphApi2")]
public static async Task<IActionResult> Run(
      [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
      ILogger log)
{
   string[] scopes = new[] { "https://graph.microsoft.com/.default" };
   var graphServiceClient = new GraphServiceClient(new DefaultAzureCredential(), scopes);
   ApplicationCollectionResponse apps = await graphServiceClient.Applications.GetAsync();

   foreach (Application app in apps.Value)
   {
      log.LogInformation(app.AppId); // This works.
   }

   string appId = apps.Value.First().AppId; // This works.
   var app1 = await graphServiceClient.Applications[appId].GetAsync(); // This throws.
   return new OkResult();
}
```

Run from Visual Studio using developer Azure login credentials.

**Expected behavior**

The call to `graphServiceClient.Applications[appId].GetAsync()` should return the same application that was retrieved from `graphServiceClient.Applications.GetAsync()` in the first place.

What actually happens is that the call throws an exception:

> Resource '2e3b5800-70be-4eba-a6c2-2a012436596b' does not exist or one of its queried reference-property objects are not present

It's a bit daft for the API to claim that the requested object does not exist, when the appID used was obtained by enumerating the existing applications.

**Desktop**
 - OS: Win 10

**Additional context**
- Microsoft.Graph version 5.13.0
 - Visual Studio 2022 - .NET 6 Function App

**Comment by andrueastman** [comment]
Thanks for raising this @Neutrino-Sunset 

This seems to be related to the answer at the link below,
https://github.com/microsoftgraph/microsoft-graph-docs/issues/3539#issuecomment-445847716

The `AppId` and `Id` are two different things and the `AppId` shouldn't be used in the path but as a filter parameter. 

Any chance this works if you change your code to use the Id property? 

```cs
string appId = apps.Value.First().Id; // This works.
```

**Comment by Neutrino-Sunset** [comment]
My mistake, using `config.QueryParameters.Filter` does work, I must have been doing something wrong. That does solve my current issue.

The indexer does seem to be bugged though and it would be nice to have that fixed.

**Comment by andrueastman** [comment]
Thanks for confirming @Neutrino-Sunset 

As the use of the `Id` vs `AppId` in the path an API side functionality, I would suggest creating a feature request at the link below for the API team to action on(as this repo is intended mainly for SDK related issues). You can post back the link to the request at the link below so that anyone in future may also find it and upvote it. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

We'll close this issue and re-open in case anything SDK related arises.
