### ISSUE TITLE
[Client bug]: chats/getAllMessages() doesn't expose a way to set the "model" query string property

### ISSUE THREAD

**Issue by ddeloveh** [microsoftgraph/msgraph-sdk-dotnet#1972]
**Describe the bug**
When trying to use the v5 client for [chats: getallMessages](https://learn.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&tabs=http#optional-query-parameters) for which I need to be able to append the "model" query string parameter this format:
```
GET /users/{id | user-principal-name}/chats/getAllMessages?model=A
```

In v4 it would use the AppendSegmentToRequestUrl lihe

string userGuidString = ...
GraphServiceClient gsc = ...
var results = await new UserChatsCollectionRequestBuilder(
   gsc.Users[userGuidString].Chats.GetAllMessages().AppendSegmentToRequestUrl("?model=A")
   , gsc.Request().GetAsync();

Checking the [MS upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md) I see only one mention of the AppendSegmentToRequestUrl which was only how to stop using it for the $count piece and use a built in method.

string userGuidString = ...
GraphServiceClient gsc = ...
var results = await new Microsoft.Graph.Users.Item.Chats.GetAllMessages.GetAllMessagesRequestBuilder(
   new Uri(gsc.Users[userGuidString].Chats.GetAllMessages.ToGetRequestInformation().URI, "?model=A").ToString()
   , gsc.RequestAdapter).GetAsync();

Sure this works, but since they didn't call out this issue in the upgrade guide it seems like I must be missing how to do this in the v5 syntax.

**To Reproduce**
I had expected to be able to write something similar to v4 as shown in the description.  But someone on StackOverflow suggested that it is only an oversight and that is should be exposed on the GetAsync.  So the steps to reproduce is to try and find a way to add the "model" property with built in methods.

**Expected behavior**
Either an equivalent of the AppendSegmentToRequestUrl from v4, or as suggested by someone on SO an additional property on GetAsync like:
```
await new Microsoft.Graph.Users.Item.Chats.GetAllMessages.GetAsync(x=> {
  x.QueryParameters.Model = "A"
}
```

**Client version**
5.13.0

**Comment by andrueastman** [comment]
Thanks for raising this @ddeloveh 

This depends on https://github.com/microsoftgraph/msgraph-metadata/issues/314 and we'll track the fix via the duplicate issue at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1979
