### ISSUE TITLE
[Client bug]: SourceType value is different from Graph Explorer and SDK

### ISSUE THREAD

**Issue by karthikd70** [microsoftgraph/msgraph-sdk-dotnet#1982]
**Describe the bug**
Included Sources property value of eDiscovery user source is different from graph explorer and SDK.

**To Reproduce**
1. Create a custodian user source with "mailbox, site" using SDK 5.13.0
2. Get the same user source and it returns only "site". Graph explorer returns "mailbox, site". Please refer below screenshots.

**Expected behavior**
SDK should return "mailbox, site".

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/47561c71-ab7e-458d-bfd2-97a2e05a86b6)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/2f89ef70-39ce-460d-a6aa-9106aba621f5)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/f0e84677-ae5e-491f-8d43-ec82f338b700)

**Client version**
5.13.0

**Additional Context**
Observed that Enum SourceType is different from v4 SDK. 

v5
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/47381e1d-45a8-40a8-8f14-f5411e94aba5)

v4
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/108007450/0a7e14e8-6aad-4fdb-a8da-8becb98ebe8d)

v

**Comment by andrueastman** [comment]
This is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1915
