### ISSUE TITLE
v5 Missing method to delete owner from group

### ISSUE THREAD

**Issue by MarcoZimmermann** [microsoftgraph/msgraph-sdk-dotnet#1983]
With v5 of the client SDK I can't delete owners from groups. The DeleteAsync method is missing. I can only use GetAsync and PostAsync.

https://learn.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=csharp

Code example: 
await graphClient.Groups["{group-id}"]
   .Owners["{directoryObject-id}"]
   .Ref
   .DeleteAsync(); << missing

**Comment by andrueastman** [comment]
Thanks for raising this @MarcoZimmermann 

Any chance you can confirm the version of the sdk you are using?

I believe the latest version has the method as shown below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/4a2830067359f5d9f0812eda07db3ceb5c58fa9c/src/Microsoft.Graph/Generated/Groups/Item/Owners/Item/Ref/RefRequestBuilder.cs#L40

**Comment by MarcoZimmermann** [comment]
Thanks for the notice. It was my mistake. I forgot to put the OwnerID in the owners dictionary: 

Groups[groupId].Owners.Ref.DeleteAsync(); 

Thats why DeleteAsync was missing. I'm sorry for that. With correct syntax all works fine. Thank you!
