### ISSUE TITLE
Error "Content type application/octet-stream does not have a factory registered to be parsed" when trying to get Attachment Content of E-Mail

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#1984]
**Describe the bug**
Hello,

I am currently trying to get the Content of an attachment of an E-Mail.
There is no SDK example in the [documentation](https://learn.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http). The only info I've gotten from the documentation is that you have to add `/$value` to the end of the request. So I tried to do it myself like this:
```csharp
RequestInformation getRequest = graphServiceClient.Users["mail"].Messages["messageId"].Attachments["attachmentId"].ToGetRequestInformation();

UriBuilder builder = new UriBuilder(getRequest.URI);
builder.Path += "/$value";
getRequest.URI = builder.Uri;

byte[] contentResult = await graphServiceClient.RequestAdapter.SendPrimitiveAsync<byte[]>(getRequest, cancellationToken: cancellationToken);
```

The problem I'm facing right now is this exception, when I'm sending this request:
`Content type application/octet-stream does not have a factory registered to be parsed`

The StackTrace:
```
at Microsoft.Kiota.Abstractions.Serialization.ParseNodeFactoryRegistry.GetRootParseNode(String contentType, Stream content)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetRootParseNode(HttpResponseMessage response)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary 2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary 2 errorMapping, CancellationToken cancellationToken)
```

I am currently using the MS Graph SDK version 5.13

Is there any other way to get only the byte content of an attachment with the Graph SDK?  Or am I just using the wrong method? 

Thanks in advance

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

Any chance changing to stream works out?

```cs
var contentResult = await graphServiceClient.RequestAdapter.SendPrimitiveAsync<Stream>(getRequest, cancellationToken: cancellationToken);
```

**Comment by Danny4021** [comment]
Hey @andrueastman 
thank you very much for the fast response.
Yeah, this change fixed my problem.
I didn't expect it to work that way since I didn't expect a `Stream` to count as a `Primitive`.
Thank you for your help!
