### ISSUE TITLE
deviceRegistrationPolicy in policies is missing.

### ISSUE THREAD

**Issue by JanPieterKroeb** [microsoftgraph/msgraph-sdk-dotnet#1985]
**Describe the bug**
Field deviceRegistrationPolicy is missing within GraphClient.Policies, effectively making its endpoint inaccessible.

**To Reproduce**
1. Create a GraphClient
2. From policies try to get DeviceRegistrationPolicy.
3. See error

**Comment by andrueastman** [comment]
Thanks for raising this @JanPieterKroeb 

According to the docs, it looks like the endpoint is only available in beta. 
https://learn.microsoft.com/en-us/graph/api/deviceregistrationpolicy-get?view=graph-rest-beta&tabs=csharp

Any chance you could try out the latest beta package for this? 
https://www.nuget.org/packages/Microsoft.Graph.Beta
