### ISSUE TITLE
Get Case Requests failing as Forbidden

### ISSUE THREAD

**Issue by henry-filosa** [microsoftgraph/msgraph-sdk-dotnet#1987]
**Describe the bug**
[Get requests to fetch an ediscovery case](https://learn.microsoft.com/en-us/graph/api/security-ediscoverycase-get?view=graph-rest-1.0&tabs=http) are failing spuriously w/ `Forbidden: Request for case type  is not supported`. This is a V1.0 endpoint and should be supported.

We have taken the following troubleshooting steps that make us fairly certain that it is an issue w/ the graph itself:
1. Confirmed our app registrations and secrets are accurately configured and up to date.
2. Confirmed that the error occurs when the request is sent via the Java SDK or via Postman.
3. Confirmed that the same client can access the [List Cases](https://learn.microsoft.com/en-us/graph/api/security-casesroot-list-ediscoverycases?view=graph-rest-1.0&tabs=http) endpoint. The returned list contains the case we are attempting to fetch.
4. Confirmed that this endpoint fails for any case in our tenant.

Additionally, this error started suddenly today w/ no changes to our code or infrastructure.

**To Reproduce**
Java: make a request w/ `client.security().cases().ediscoveryCases(caseId).buildRequest().get()`
Postman: `https://graph.microsoft.com/v1.0/security/cases/ediscoveryCases/CASE_ID`

The app registration used for OAuth must have `eDiscovery.Read.All` or `eDiscovery.ReadWrite.All` permissions and be granted admin consent.

**Expected behavior**
Return the specified case.

**Screenshots**
Here is an example return value we have received:
```   
 "error": {
        "code": "Forbidden",
        "message": "Request for case type  is not supported",
        "innerError": {
            "date": "2023-06-27T22:37:03",
            "request-id": "a68ac7dd-d74b-4aea-818c-86783eb23052",
            "client-request-id": "a68ac7dd-d74b-4aea-818c-86783eb23052"
        }
    }
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 20.04.6

**Additional context**
This doesn't seem to be an issue w/ the SDK, but there was no other location we could find to file an issue. Additionally, none of the following health dashboards we could find indicated an applicable issue:
1. [Azure Status Page](https://azure.status.microsoft/en-us/status)
2. [Office Health Portal](https://portal.office.com/servicestatus)
3. [Admin Center Service Health](https://portal.office.com/adminportal/home#/servicehealth)

**Comment by mslosarek** [comment]
I am also getting this error message when trying to retrieve a case by id. The same case is retrievable at the `https://graph.microsoft.com/v1.0/compliance/ediscovery/cases/<caseId>` endpoint

**Comment by andrueastman** [comment]
Thanks for raising this @henry-filosa 

As this is an API/service related question, any chance you could post the same at the link below for the API owners to help out with this?

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by mslosarek** [comment]
@andrueastman I posted the question here:
https://learn.microsoft.com/en-us/answers/questions/1321169/request-for-case-type-is-not-supported-error-on-th

Is there any way to escalate this as it is an error on the MS Graph side and not with the individual requests.

**Comment by andrueastman** [comment]
@mslosarek Just to confirm, are you still experiencing this?

Are you able to share a fresh error response if this is the case?

**Comment by henry-filosa** [comment]
It is now working again on our end. Mysterious.

**Comment by drgnbear** [comment]
Govt cloud still erroring in the exact same way seems like for us it STARTED this am.
