### ISSUE TITLE
Common Base type for .Me and .Users[mail]

### ISSUE THREAD

**Issue by aersam** [microsoftgraph/msgraph-sdk-dotnet#1988]
**Is your feature request related to a problem? Please describe.**
In v4 I did something this:

```C#

    private GraphServiceClient client;
   private IUserRequestBuilder GetUser(string? emailOfUser)
    {
        if (emailOfUser == null)
        {
            return this.client.Me;
        }
        return this.client.Users[emailOfUser];
    }
```

**Describe the solution you'd like**
In v5 there is no meaningful basetype between .Me and .Users[mail], meaning I cannot easily switch those

**Describe alternatives you've considered**
Well I could use dynamic code, but that has it's own downsides. I have to stick with v4 for now

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @aersam 

This is tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1988 and will be part of the next major version of the SDK. Closing this for now as this is tracked above.

**Comment by aersam** [comment]
Hi guys
This seems still not be be addressed, right? also, there seems to be no tracking issue or so?
