### ISSUE TITLE
Suspected bug - Random 'Access Denied' errors on open extensions

### ISSUE THREAD

**Issue by LaurensAdema** [microsoftgraph/msgraph-sdk-dotnet#199]
When using extensions in the Graph API:

```cs
    graphUser = graphClient.Users.Request().AddAsync(graphUser).Result;
    
    OpenTypeExtension newExtension = new OpenTypeExtension()
    {
        ExtensionName = "CustomName",
        AdditionalData = new Dictionary<string, object>
        { { "CustomID", user.CustomID }
        }
    };

    graphClient.Users[graphUser.UserPrincipalName]
        .Extensions
        .Request()
        .AddAsync(newExtension)
        .Wait();
```

I randomly get these errors:

    Code: AccessDenied
    Message: Access Denied

Sometimes it works, sometimes it doesn't. I can't seem to find a correlation.
When I step trough the code in the debugger it works more often then if I run it without interruption. But if I add a sleep between the lines (to account for processing delay), it doesn't fix the issue.

I figured out that once the errors start showing, the user needs to be deleted. Errors on one user don't necessarily mean errors on another user. But once the error starts showing, it keeps happening. Sometimes waiting 10 minutes before recreating users temporarily fixes the error.

The application has all the required rights to access the API.

The issue isn't solely in the `POST`, but also on the `GET` as illustrated in the code sample below which results in the same error.

```cs
    User user = graphClient.Users[userName]
        .Request()
        .Expand("extensions")
        .GetAsync()
        .Result;
```

**Comment by LaurensAdema** [comment]
I never did this before so please tell me if I'm missing something, or added to much details.

This is a request that failed:
```
	HTTP/1.1 403 Forbidden
	Cache-Control: private
	Content-Type: application/json
	request-id: ecd8cbc8-fa7b-46c4-868e-13ac0d7741ab
	client-request-id: ecd8cbc8-fa7b-46c4-868e-13ac0d7741ab
	x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceB","ScaleUnit":"001","Host":"AGSFE_IN_6","ADSiteName":"AMS"}}
	Duration: 187.0138
	Date: Fri, 20 Oct 2017 12:23:40 GMT
	Content-Length: 211

	{
	  "error": {
		"code": "AccessDenied",
		"message": "Access Denied",
		"innerError": {
		  "request-id": "ecd8cbc8-fa7b-46c4-868e-13ac0d7741ab",
		  "date": "2017-10-20T12:23:41"
		}
	  }
	}
```

And this is a request that worked:

```
	HTTP/1.1 201 Created
	Cache-Control: private
	Transfer-Encoding: chunked
	Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
	Location: https://graph.microsoft.com
	request-id: 84f7c6b5-ada0-4999-b0b3-d4aafe70eb49
	client-request-id: 84f7c6b5-ada0-4999-b0b3-d4aafe70eb49
	x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceB","ScaleUnit":"001","Host":"AGSFE_IN_13","ADSiteName":"AMS"}}
	OData-Version: 4.0
	Duration: 1872.9993
	Date: Fri, 20 Oct 2017 12:23:23 GMT

	d0
	{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users('UnitTest%40CompanyName.onmicrosoft.com')/extensions/$entity","CustomID":123,"CustomName":"CompanyNameExtensions","id":"CompanyNameExtensions"}
	0
```

**Comment by MIchaelMainer** [comment]
I suspect that you are hitting a limit on the number of open extensions that you can have on a resource. In your case, a user. So that why it would fail on the Add. The error message needs work if that is the case. When the error starts on a user, can you reporthow many extensions the user has?

That doesn't explain the GET scenario. 

The Fiddler capture looks good. Are the 403 and 201 responses based on the same request?

**Comment by LaurensAdema** [comment]
They're both based on the same request. 

It's a freshly created user where 1 extension is added. This means that it couldn't be a limit issue.

**Comment by MIchaelMainer** [comment]
Okay, I just found this. 

https://developer.microsoft.com/en-us/graph/docs/concepts/extensibility_overview#data-limits

Does the extension have more than 2kb of info?

**Comment by LaurensAdema** [comment]
It shouldn't because it's just an int, and not even a big one at that, and the scheme itself is just a name and the name of the identifier. So it should fit with ease in 2kb.

**Comment by MIchaelMainer** [comment]
Okay, thank you for providing this information. This is a service issue. I'll pass this on to service owner.

**Comment by LaurensAdema** [comment]
Thank you!

**Comment by MIchaelMainer** [comment]
Hello @LaurensAdema can you tell me the work flow leading up and following the successful creation of the open extensions? Is creating and deleting users part of your workflow?

**Comment by LaurensAdema** [comment]
All workflows have been unit tests which start with creating a test user and end with deleting the created test user. The creating is always attempted. But if the creation would fail, no actions will be performed. If the creation was successful, a delete is also attempted even though an update for example would have failed. 

A test which creates a user, updates it and then deletes it would have a success rate on all actions of about 50%. More specifically: the first attempt will succeed, the two following will encounter the error and the fourth attempt will work again and repeating. This is the general pattern I have observed on further inspection.

Does this information answer your questions?

**Comment by MIchaelMainer** [comment]
I think that covers it. I assume that the update is only updating the user with an open extension, correct?

**Comment by MIchaelMainer** [comment]
Hello @LaurensAdema 

Can you try this and tell me if you still see the issue? Change the UPN to id.

    graphClient.Users[graphUser.Id]
        .Extensions
        .Request()
        .AddAsync(newExtension)
        .Wait();

**Comment by LaurensAdema** [comment]
Yes, you're right! When using the Id, I don't get the error message.
Thank you!

Could you tell me what the issue with the UPN is?

**Comment by MIchaelMainer** [comment]
There is a cache based on the UPN. It maintains a reference to the old user id through it. Since you were recreating the user with the same UPN in your tests, the cache was using the deleted user's reference. Not a normal scenario for a user to be deleted and recreated, but very normal for tests. I'm glad you are unblocked and thank you for finding the bug. It has been reported.

**Comment by LaurensAdema** [comment]
Makes sense, thanks again!
