### ISSUE TITLE
Disable privileged account does not work, anymore

### ISSUE THREAD

**Issue by anthonyvandenbossche** [microsoftgraph/msgraph-sdk-dotnet#1992]
I have a function app that creates user accounts in an Azure AD tenant using an app registration and application permissions. Since it is a PIM solution, it also adds newly created users to Role-Assigned groups (for example a group that is assigned to the Global Admins role). After an allotted amount of time, the tool will remove the user from the group (therefor removing the privilege), and then disable the account. This disable action fails since the beginning of this week with "Request_BadRequest Message: Property 'isSipEnabled' is read-only and cannot be set.". When an enable of that same user account is tried, the same error pops up. Deleting a privileged user is not a problem, strangely.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/45596161/ad0d201e-923a-48e7-b016-7683aab87443)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/45596161/bf6e20a8-f7c1-4ae1-a9f8-22a39acf2442)

The app has a number of application api perms (user.readwrite.all, group.readwrite.all and RoleManagement.ReadWrite.Directory). To facilitate enabling/disabling of the account, an Azure AD role was granted to the app registration: Privileged Authentication Administrator.

Extra info: the app is using:
- .NET 6
-  Microsoft.Graph 4.24.0

**Comment by anthonyvandenbossche** [comment]
The underlying question would be: how can I disable a (once) privileged account, using the client credential oauth flow?

**Comment by andrueastman** [comment]
Thanks for raising this @anthonyvandenbossche 

Is the user object being sent for the `UpdateAsync` the same object from a previous API request? Any chance you can confirm there is a `isSipEnabled` property present in the object or in the AdditionalData?

**Comment by anthonyvandenbossche** [comment]
Hi @andrueastman, I was indeed referencing an object from a previous request. This is not a good idea so it seems. Code was adapted to:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/45596161/8a594f4e-50c4-478a-b745-b27ea2b20d5f)

This seems to work! Thanks for your feedback!!
