### ISSUE TITLE
Adding More Than One Key to TodoTask AdditionalData causes PageIterator delegate to hang

### ISSUE THREAD

**Issue by gtwilliams03** [microsoftgraph/msgraph-sdk-dotnet#1994]
**Describe the bug**
I am loading our users task lists using the Graph API - during the PageIterator delegate, I am trying to add keys to each retrieved TodoTask AdditionalData dictionary.  If I add only one key, it works fine.  More than one key, it hangs.

**To Reproduce**
Steps to reproduce the behavior - see sample code below.

**Expected behavior**
I think it should allow me to add the additional keys?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A running in Visual Studio 2022
 - Version 2022

**Additional context**

```
                    var _items = new List<TodoTask>();
                    var _todoLists = await _graphClient.Users[_email].Todo.Lists.GetAsync();

                    foreach (TodoTaskList _todoTaskList in _todoLists.Value)
                    {
                        Console.WriteLine($@"List name: {_todoTaskList.DisplayName}");
                        try
                        {
                            var _todoListItems = await _graphClient.Users[_email].Todo.Lists[_todoTaskList.Id].Tasks.GetAsync();
                            var _pageIterator = PageIterator<TodoTask, TodoTaskCollectionResponse>
                                .CreatePageIterator(_graphClient, _todoListItems, (_todoListItem) => {

                                    if (_todoListItem.AdditionalData == null)
                                    {
                                        _todoListItem.AdditionalData = new Dictionary<string, object>();
                                    }

                                    _todoListItem.AdditionalData["ActualWork"] = 0.0;
                                   // _todoListItem.AdditionalData["TotalWork"] = 0.0; <-- uncommenting this line causes the delegate to hang
                                    _items.Add(_todoListItem);

                                    return true;

                                });
                            await _pageIterator.IterateAsync();
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine($@"Error getting task list {_todoTaskList.DisplayName}: {ex.Message}");
                        }
                    }

                    Console.WriteLine($@"Tasks loaded: {_items.Count}");

```

**Comment by andrueastman** [comment]
Thanks for raising this @gtwilliams03 

Any chance you can share version of the SDK you are using when you reproduce this?

**Comment by gtwilliams03** [comment]
I was using 5.15.0

**Comment by andrueastman** [comment]
Thanks for confirming this @gtwilliams03 

Any chance it completes if you limit the number of items in a page? We're currently looking into this.

```cs
var _todoListItems = await graphClient.Me.Todo.Lists[_todoTaskList.Id].Tasks.GetAsync( requestConfiguration => requestConfiguration.QueryParameters.Top = 10);
```

**Comment by gtwilliams03** [comment]
@andrueastman I don't believe that will help because this hangs even for users with very few Todo tasks. I am currently traveling but will try your test when I get back next week if that is OK.

**Comment by gtwilliams03** [comment]
@andrueastman Adding the following to the `.GetAsync()` call allows the call to complete with the custom fields added to the `AdditionalData` field:

```
requestConfiguration => requestConfiguration.QueryParameters.Top = 1
```

However, if I have the `Top` property to any value greater than `1`, it hangs again.

**Comment by gtwilliams03** [comment]
@andrueastman Hi!  Any update on this issue?

**Comment by gtwilliams03** [comment]
Updated to 5.20.0 and still get the error unless I have `requestConfiguration => requestConfiguration.QueryParameters.Top = 1` in the `GetAsync` call.

**Comment by gtwilliams03** [comment]
Still not working with `5.21.0`
