### ISSUE TITLE
Update GET /deviceManagement/managedDevices with correct information.

### ISSUE THREAD

**Issue by neckermann** [microsoftgraph/msgraph-sdk-dotnet#1995]
**Is your feature request related to a problem? Please describe.**
GET /deviceManagement/managedDevices or Get-MgDeviceManagementManagedDevice returns enrolling user and not current Primary User.

We are noticing that this query or cmdlet is not returning the correct details about the managed device. It is showing the enrolling user and not the current primary user for the device. Shouldn't it give the managedDevices current state?

When changing the primary user of the managed device
The Auzre object shows correct owner and upn.
The Intune shows the correct primary user upn.
But the GET /deviceManagement/managedDevices still shows the enrolling user details not current user details
userId returns enrolling user details not current primary user
userDisplayName returns enrolling user details not current primary user
userPrincipalName returns enrolling user details not current primary user

**Describe the solution you'd like**
Would like to see the GET /deviceManagement/managedDevices show the current primary users details when running the command.

**Describe alternatives you've considered**
We are current using a second loop to identify the correct user, but it seems like it shouldn't be required if the managedDevice object had the updated information. 

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @neckermann 

As this is an API related question and this repo is mainly intended for SDK related issues, we'll follow this up with the question created at the link below.

https://learn.microsoft.com/en-us/answers/questions/1321671/graph-devicemanagement-manageddevices-or-get-mgdev
