### ISSUE TITLE
Multiple Notifications sent When Graph API SDK Patch Sent

### ISSUE THREAD

**Issue by noelrfMcM** [microsoftgraph/msgraph-sdk-dotnet#1996]
**Describe the bug**
currently using Microsoft Graph v 5.3.0. I have a web service written in .net core 6.0
to update Events in outlook by adding an attendee or removing it as required. I am also forwarding events to other emails.
The attendee is a room location resource email which is set to auto accept if free and auto decline if busy.

The trigger is a room booking system database change so we know the attendee to add then run the code.

The code is very much as per Microsoft example:

 var graphClient = initialiseGraphClient(tenantId, clientId, secretName, keyVaultName, keyVaultURL);

                var requestBody = new Event
                {
                    Recurrence = null,
                    Attendees = attendees,
                    Location = location,
                    Locations = locations
                };

                var resultEvent = await graphClient
                   .Users[userEmail]
                   .Events[eventId]
                   .PatchAsync(requestBody);

When I do a patch to update the attendee list (remove or add an attendee), notifications are not only sent to the host but also 
all the attendees. In some cases this can be 3 notifications at once with the same status of the new attendee has accepted.

**To Reproduce**
1. Create room booking, change is detected in the database by the web service
2. Run the code as shown adding in the attendees plus the new attendee.
3. wait in outlook for notifications which appear.
4. 
**Expected behavior**
Only one notification should be sent.

**Screenshots**

**Server:**
 - OS: Web service sits on a windows 2012 server

**Comment by andrueastman** [comment]
Thanks for raising this @noelrfMcM 

According to the documentation, you want only to have the `attendees` property in the request payload for this to work as you wish. https://learn.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#notes-for-updating-specific-properties

Any chance you get a different result if you set the body as below to only update the specfied property?

```cs
var requestBody = new Event
{
    Attendees = attendees
};
```

**Comment by noelrfMcM** [comment]
Eastman,
                Thanks for coming back to me. I will check if just adding the attendees makes a difference regarding the notifications.

I'll let you know if that makes a difference.

Thanks

Noel

**Comment by ssougnez** [comment]
> Thanks for raising this @noelrfMcM
> 
> According to the documentation, you want only to have the `attendees` property in the request payload for this to work as you wish. https://learn.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#notes-for-updating-specific-properties
> 
> Any chance you get a different result if you set the body as below to only update the specfied property?
> 
> ```cs
> var requestBody = new Event
> {
>     Attendees = attendees
> };
> ```

I had the same issue and I can confirm that this works.
