### ISSUE TITLE
Users QueryParameters.Filter doesn't work

### ISSUE THREAD

**Issue by p-andy** [microsoftgraph/msgraph-sdk-dotnet#2002]
**Describe the bug**
I used [this](https://github.com/microsoftgraph/msgraph-training-dotnet/tree/main) tutorial to get started with AzureGraph.
This also works so far and I get the top 25 users output.
Working: 

```             
var graphUsers = await graphClient.Users.GetAsync((config) =>
    {
        // Only request specific properties
        config.QueryParameters.Select = new[] { "displayName", "id", "mail" };
        // Get at most 25 results
        config.QueryParameters.Top = 25;
        // Sort by display name
        config.QueryParameters.Orderby = new[] { "displayName" };
    });
return graphUsers;
```

However, as soon as I add a filter, I get no return, not even an exception. If you set a breakpoint on the return line, it will not be reached. It seems as if the program stops working at this point. What do i do wrong? Why do i get nothing returned?
P.S.: There is at least one user with an Mail-Address starting with BER (case-sensitive)

Not working:
```
var graphUsers = await graphClient.Users.GetAsync((config) =>
{
    // Only request specific properties
    config.QueryParameters.Select = new[] { "displayName", "id", "mail" };
    // Get at most 25 results
    config.QueryParameters.Top = 25;
    config.QueryParameters.Filter = "startswith(mail, 'BER')";
    // Sort by display name
    config.QueryParameters.Orderby = new[] { "displayName" };
});
return graphUsers;
```

**To Reproduce**
see above

**Expected behavior**
return at least one user entry

**Client version**
5.17.0
OS: Windows 11
Desktop C# console app
Version: dotnet core 7

**Comment by MartinM85** [comment]
If you add both `$filter` and `$orderby` query parameters to filter and sort users it's an [advanced query](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#:~:text=Using%20%24filter%20and%20%24orderby%20together%20is%20supported%20only%20with%20advanced%20queries) which requires `ConsistencyLevel:eventual `header and `$count` query parameter set to `true`

```
try
{
  var graphUsers = await graphClient.Users.GetAsync((config) =>
  {
      // Only request specific properties
      config.QueryParameters.Select = new[] { "displayName", "id", "mail" };
      // Get at most 25 results
      config.QueryParameters.Top = 25;
      config.QueryParameters.Filter = "startswith(mail, 'BER')";
      // Sort by display name
      config.QueryParameters.Orderby = new[] { "displayName" };
      config.QueryParameters.Count = true;
      config.Headers.Add("ConsistencyLevel", "eventual");
  });
  return graphUsers;
}
catch(ODataError odataError)
{
}
catch(Exception ex)
{
}
```

**Comment by p-andy** [comment]
Hi, thanks for the replay,

My statement that no exception is thrown was (of course) wrong. I missed the entries in the log. After doing some exception handling around the method I was able to find the exact error as well:

```
    try  {
      ....
    } 
    catch (ODataError ode)
    {
        Console.WriteLine(ode.Error.Message);
        ...
    }
```

The error was, if you use filter, you cannot use sort at once. After excluding OrderBy, it finds the filtered users

Thanks for your help
