### ISSUE TITLE
Missing blue Arrow when a mail has been forwarded with mime content

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#2007]
Hello,

I'm trying to forward an e-mail via MS Graph. But since I have to decrypt the Mail before forwarding it, I thought the best solutions would be to send the `Mime Content` of the message in order to forward it. I've been following [official Microsoft the docs](https://learn.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0&tabs=http) to forward a Message and I am forwarding the message like this:

```csharp
StringContent stringContent = new(base64String, Encoding.UTF8, MediaTypeNames.Text.Plain);

RequestInformation forwardRequest = _graphClient
			.Users[_graphSettings.MailAddress]
			.Messages[mailId]
			.Forward
			.ToPostRequestInformation(new ForwardPostRequestBody());
		
forwardRequest.Headers.Clear();
forwardRequest.Headers["Content-Type"] = new [] { MediaTypeNames.Text.Plain };
forwardRequest.Content = await stringContent.ReadAsStreamAsync(cancellationToken);
await _graphClient.RequestAdapter.SendNoContentAsync(forwardRequest, cancellationToken: cancellationToken);
```
This works and it forwards the Message to the recipients of the `MimeMessage` but the problem is, that Outlook does not mark the message as `Forwarded`.
Normally, when you forward a message via the other route like this:
```csharp
ForwardPostRequestBody body = new() {
			ToRecipients = new List<Recipient> {
				new() { EmailAddress = new EmailAddress { Address = forwardToMail } }
			}
		};

await _graphClient
		.Users[_graphSettings.MailAddress]
		.Messages[mailId]
		.Forward
		.PostAsync(body);
```
Outlook displays a small blue arrow next to the mail, signaling, that it has been forwarded:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/128810968/a06bd4ac-6910-4a66-b1f3-95c8a267e23d)
but this doesn't happen when you upload the `MimeContent` as seen in example one.
I've tried to update the MAPI Properties myself like this:

```csharp
await _graphClient.Users[_graphSettings.MailAddress].Messages[mailId].PatchAsync(new Message {
			SingleValueExtendedProperties = new List<SingleValueLegacyExtendedProperty> {
				new() {
					Id = "Integer {00062004-0000-0000-C000-000000000046} Id 0x1080",
					Value = Convert.ToString(0x00000106)
				}
			}
		}, cancellationToken: cancellationToken);
```
but this does not change the fact that the blue arrow is missing. I just add a custom `SingleValueExtendedLegacyProperty` which does not change the displayed icon.

And now to my question:
Is this intended? Is the blue arrow supposed to be missing when I forward a mail via uploading the mime content? Is there some other way to update the status of the mail to something like `IsForwarded` with the graph sdk or am I just supposed to use the other forwarding method in which I update the message instead of uploading the mime content? (I use Graph SDK Version 5.16)

Thanks in advance

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

Any chance you can post the same question at the link below to get feedback from the API owners? As the missing arrow seems likely to be an issue with the API end, we may not be best placed to give more information on this. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by Danny4021** [comment]
Thanks for the answer @andrueastman 
I'll try to ask the same question on the mentioned forum then.
Thank you!
