### ISSUE TITLE
[Client bug]: provide a descriptive title here

### ISSUE THREAD

**Issue by danimal521** [microsoftgraph/msgraph-sdk-dotnet#2011]
**Describe the bug**
Cannot query "MobilePhone", returns: Microsoft.Graph.Models.ODataErrors.ODataError: 'Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.'

**To Reproduce**
           var options = new ClientSecretCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            };

            var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret, options);

            var graphClient = new GraphServiceClient(clientSecretCredential, scopes);

            var result = await graphClient.Users.GetAsync((requestConfiguration) =>
            {
                 requestConfiguration.QueryParameters.Count = true;
                requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");

                //Works
                requestConfiguration.QueryParameters.Filter = "startswith(givenname, 'a')";
                
                //Does not work
                requestConfiguration.QueryParameters.Filter = "MobilePhone eq '8133620464'";
            });

            foreach (var item in result.Value)
            {
                Console.WriteLine(item.DisplayName + " " + item.MobilePhone);
            }

**Expected behavior**
be able to filter on MobilePhone 

**Screenshots**
<img width="669" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1771181/f55b600c-3f8d-4644-8e99-5fee2ac7b498">

**Client version**
Provide the client version number from the NuGet package.
5.17.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser edge

**Additional context**

**Comment by MartinM85** [comment]
Could you share the details of the ODataError? The same query works fine for me.

**Comment by andrueastman** [comment]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

**Comment by danimal521** [comment]
> Could you share the details of the ODataError? The same query works fine for me.


<img width="669" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1771181/297a892d-1c5f-4846-a06d-af8e92d05c7b">

is the error when I just reference the **MobilePhone** 

Try the code below with JUST the mobilephone

 var result = await graphClient.Users.GetAsync((requestConfiguration) =>
        {
             requestConfiguration.QueryParameters.Count = true;
            requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");

                     
            //Does not work
            requestConfiguration.QueryParameters.Filter = "MobilePhone eq '8133620464'";
        });

**Comment by MartinM85** [comment]
@danimal521 The window shows only the type of the error. When you click on **View Details** it will show you more details like an error message and an error code returned from the Graph API.

**Comment by danimal521** [comment]
> View Detail

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1771181/3f2aba73-70f6-4832-ab57-2fbeac8adbc7)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/1771181/1df63a1f-9f65-4065-bcd9-3518e4f9854b)

Unless I am missing something, it looks like there is a mobilephone. I have tried all cases.

**Comment by andrueastman** [comment]
The query works for me as well from my end.

Any chance you can share the url from your sample by doing something close to this?

```cs
        var requestInformation = graphClient.Users.ToGetRequestInformation((requestConfiguration) =>
        {
            requestConfiguration.QueryParameters.Filter = "MobilePhone eq '123'";
            requestConfiguration.QueryParameters.Count = true;
            requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
        });

        Console.WriteLine(requestInformation.URI.OriginalString);
```
