### ISSUE TITLE
'AttachmentsRequestBuilder.AttachmentsRequestBuilderGetQueryParameters' does not contain a definition for 'Top'

### ISSUE THREAD

**Issue by liy0na** [microsoftgraph/msgraph-sdk-dotnet#2012]
**Describe the bug**
After updating to 5.17.0 from 5.0.0 it seems that Top is not available in "AttachmentsRequestBuilder.AttachmentsRequestBuilderGetQueryParameters"

**To Reproduce**
```
AttachmentCollectionResponse? attachments = await _appClient.Users[userId].Messages[message.Id].Attachments.GetAsync( ( requestConfiguration ) =>
                        {
                            requestConfiguration.QueryParameters.Top = 100;
                        } );
```

The documentation says it should be there:
https://learn.microsoft.com/en-us/graph/query-parameters?tabs=csharp#top-parameter
From the documentations:
```
// Code snippets are only available for the latest version. Current version is 5.x

var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Me.Messages.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Top = 5;
});
```

**Comment by liy0na** [comment]
I have tested again, the problem happens if you update from 5.12.0 to any higher version.

**Comment by andrueastman** [comment]
> I think it is a bug and not just a documentation. The code above doesn't compile anymore.

I agree. The property is however generated from the metadata and this is where the data really needs to be fixed.

**Comment by liy0na** [comment]
Any update on fixing this? This prevents us to upgrade to latest version.

**Comment by andrueastman** [comment]
After testing this out on the Graph Explorer and the conversation at https://github.com/microsoftgraph/msgraph-metadata/issues/321, the API does not support the `$top` endpoint at the moment `/messages/{message-id}/attachments` (hence its removal) and updating the metadata would lead to suggesting a parameter that is not support. 

Any chance you can confirm this indeed works at @liy0na?
