### ISSUE TITLE
[Client bug]: Group delta is missing Skiptoken query parameter

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#2014]
**Describe the bug**
The following code won't compile, because `Skiptoken` property doesn't exist.
```
var graphClient = new GraphServiceClient(requestAdapter);

var result = await graphClient.Groups.Delta.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Skiptoken = "pqwSUjGYvb3jQpbwVAwEL7yuI3dU1LecfkkfLPtnIjvB7XnF_yllFsCrZJ";
});
```

**To Reproduce**
The code above

**Expected behavior**
Can set Skiptoken

**Screenshots**

**Client version**
5.17

**Desktop (please complete the following information):**

**Additional context**

**Comment by Nemeczek** [comment]
It is hapening also in [Python SDK](https://github.com/microsoftgraph/msgraph-sdk-python/issues/242). Microsft is completly silent about this for weeks now

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-metadata/issues/354
