### ISSUE TITLE
[Client bug]: code works when run from unit test project but not when run from NetCore6 MVC web app

### ISSUE THREAD

**Issue by tracy-hunt** [microsoftgraph/msgraph-sdk-dotnet#2016]
**Describe the bug**
Code to create an event works as expected when executed through a unit test project (.NET 6.0). Same code executed from .NET 6.0 MVC web app throws the following error

Microsoft.Graph.Models.ODataErrors.ODataError
  HResult=0x80131500
  Message=Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
  Source=Microsoft.Kiota.Http.HttpClientLibrary
  StackTrace:
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Graph.Users.Item.Events.EventsRequestBuilder.<PostAsync>d__9.MoveNext()
   at .....(my code)

**To Reproduce**
Here's the code
INCOMING PARAMS: string pUserEmailAddress, string pTitle, string pBody, DateTime pDue
INTERNAL CONFIG: tenantId, clientId, clientSecret

string[] scopes = new string[] { "https://graph.microsoft.com/.default" };
var options = new ClientSecretCredentialOptions { AuthorityHost = AzureAuthorityHosts.AzurePublicCloud, };
// https://learn.microsoft.com/dotnet/api/azure.identity.clientsecretcredential
var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret, options);
var graphServiceClient = new GraphServiceClient(clientSecretCredential, scopes);
var requestBody = new Event
            {
                Subject = pTitle,
                Body = new ItemBody
                {
                    ContentType = BodyType.Html,
                    Content = pBodyHtml
                },
                Start = pDue.ToDateTimeTimeZone(),
                End = pDue.AddMinutes(15).ToDateTimeTimeZone(),
                IsReminderOn = true,
                ReminderMinutesBeforeStart = 60
            };
await graphServiceClient.Users[pUserEmailAddress].Events.PostAsync(requestBody);

**Expected behavior**
The event shows up in the user's calendar. The event does show up when run from a unit test project. However, when run from the web app, it throws the above error.

**Screenshots**
N/A

**Client version**
Microsoft.Graph 5.17.0

**Desktop (please complete the following information):**
 - OS: Win11 Home 22H2
 - Browser Edge 114.0.1823.67 (Official build) (64-bit)
 - Visual Studio Pro 2022 v 17.6.4

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @tracy-hunt,

Any chance you can share details of the error by following the guidance at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

**Comment by tracy-hunt** [comment]
Well that's interesting. The ODataError code and message are:

code: TimeZoneNotSupportedException
message: A valid TimeZone value must be specified. The following TimeZone value is not supported: ''.

I can probably work around that...and...why would DateTime.ToDateTimeTimeZone() grab a default time zone from a unit test app but not a web app???

**Comment by tracy-hunt** [comment]
NOTE: adding ToLocalTime() ahead of ToDateTimeTimeZone() works. So the changes are:

Start = pDue.ToLocalTime().ToDateTimeTimeZone(),
End = pDue.ToLocalTime().AddMinutes(15).ToDateTimeTimeZone(),

I guess this can be closed - and I'm still curious as to why a unit test would pick up a default time zone but the web app doesn't.
