### ISSUE TITLE
[Client bug]: The WindowsArchitecture enum does not have the same values between V4 and V5

### ISSUE THREAD

**Issue by DCourtel** [microsoftgraph/msgraph-sdk-dotnet#2021]
**Describe the bug**
The Graph SDK V5 does not assign the same values to the WindowsArchitecture enum as the V4. The V5 does not apply the Flags attribute to the enum. Meaning that: WindowsArchitecture.Arm has a value of 4 in V4 and 3 in V5.
A Win32LobApp published with an applicableArchitectures equal to X86|X64 (1|2=3) will be translated into Arm with the V5 SDK.

**To Reproduce**
Graph SDK V4 use the Flags attribute:
``` C#
namespace Microsoft.Graph
{
    using System.Text.Json.Serialization;

    /// <summary>
    /// The enum WindowsArchitecture.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
	[System.Flags]
    public enum WindowsArchitecture
    {
    
        /// <summary>
        /// None
        /// </summary>
        None = 0,
	
        /// <summary>
        /// X86
        /// </summary>
        X86 = 1,
	
        /// <summary>
        /// X64
        /// </summary>
        X64 = 2,
	
        /// <summary>
        /// Arm
        /// </summary>
        Arm = 4,
	
        /// <summary>
        /// Neutral
        /// </summary>
        Neutral = 8,
	
    }
}
```

While the SDK V5 does not:
``` C#
namespace Microsoft.Graph.Models {
    /// <summary>Contains properties for Windows architecture.</summary>
    public enum WindowsArchitecture {
        /// <summary>No flags set.</summary>
        [EnumMember(Value = "none")]
        None,
        /// <summary>Whether or not the X86 Windows architecture type is supported.</summary>
        [EnumMember(Value = "x86")]
        X86,
        /// <summary>Whether or not the X64 Windows architecture type is supported.</summary>
        [EnumMember(Value = "x64")]
        X64,
        /// <summary>Whether or not the Arm Windows architecture type is supported.</summary>
        [EnumMember(Value = "arm")]
        Arm,
        /// <summary>Whether or not the Neutral Windows architecture type is supported.</summary>
        [EnumMember(Value = "neutral")]
        Neutral,
    }
}
```

**Expected behavior**
The Graph SDK V5 should apply the Flags attribute to the WindowsArchitecture to be compatible with already Win32LobApp packages.

**Screenshots**
V5:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/13787283/47615535-3062-4561-a373-947bf0464bbb)

V4:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/13787283/65288173-9455-4587-85b5-128b8261c96b)

**Client version**
5.17.0

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by andrueastman** [comment]
Depends on https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1915
