### ISSUE TITLE
Using v5 from Blazor WASM app fails with "Invalid Version" error.

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-dotnet#2023]
**Describe the bug**
The requests generated by Graph clients used in a Blazor WASM app omit the `/v1.0` segment from the request URL, resulting in errors like:

```json
{
  "error": {
      "code": "BadRequest",
      "message": "Invalid version.",
      "innerError": {
          "date": "2023-07-13T00:22:11",
          "request-id": "6fe204d7-5b75-4c36-8bf1-acaa8cd743da",
          "client-request-id": "6fe204d7-5b75-4c36-8bf1-acaa8cd743da"
      }
  }
}
```

Reported in https://github.com/microsoftgraph/msgraph-sample-blazor-clientside/issues/94

**To Reproduce**
1. Clone https://github.com/microsoftgraph/msgraph-sample-blazor-clientside, configure as per README
2. Run/debug the sample
3. Open dev tools in the browser and choose the "Network" tab
4. Try to sign in
5. Look at the failed request to Graph, notice that the URL is `https://graph.microsoft.com/me?%24select=displayName,mail,mailboxSettings,userPrincipalName` (no `/v1.0`).

**Expected behavior**
Request URL should be correct.

**Additional context**
You can work around this by manually setting the `BaseUrl` on the request adapter.

**Comment by andrueastman** [comment]
Thanks for raising this @jasonjoh 

Taking a look at the sample, the baseAddress for the httpClient is set as `https://graph.microsoft.com`. 

https://github.com/microsoftgraph/msgraph-sample-blazor-clientside/blob/ec59278d24ff530e679f422df3da6b3f1a781c1a/GraphSample/Program.cs#L15

As the HttpClientRequestAdapter uses the httpClient base address as a default, this explains the issue here. See https://github.com/microsoft/kiota-http-dotnet/issues/109. I believe we simply need to update the sample to use the expected base address now.

**Comment by jasonjoh** [comment]
Ah, that explains it. This did work previously, so I guess the change you linked is what introduced the problem to the sample. I verified updating the BaseAddress for HttpClient fixed the problem. Thanks for responding!

**Comment by lostmsu** [comment]
@jasonjoh @andrueastman I believe this should be reopened, perhaps in a different capacity though.

The way I see it when I use Graph SDK via a NuGet, I should not need to know what version of the API I must use beforehand.

E.g. either Graph SDK should append the version to all queries, or, if this is undesirable from the development standpoint (e.g. makes it annoying to develop SDK itself), the NuGet should provide a `TargetApiVersion` property of type `System.Version`, which I as a user of the NuGet would then use to format the `/v{Major}.{Minor}` substring that I pass to the `HttpClient.BaseAddress`.

That way if I update Graph SDK in my project, and Graph SDK internally switches to API v2.0, it would not break my existing code.
