### ISSUE TITLE
[Client bug]: Cannot find the deviceandappmanagementassignmentfilter class in Graph SDK V5

### ISSUE THREAD

**Issue by DCourtel** [microsoftgraph/msgraph-sdk-dotnet#2027]
**Describe the bug**
The deviceandappmanagementassignmentfilter class is missing from the Graph SDK V5 even though it is listed in the documentation: 
[deviceAndAppManagementAssignmentFilter](https://learn.microsoft.com/en-us/graph/api/resources/intune-policyset-deviceandappmanagementassignmentfilter?view=graph-rest-beta)

**To Reproduce**
N/C

**Expected behavior**
The Graph SDK should provide classes and methods to manage Assignment Filters.

**Screenshots**
N/C

**Client version**
Graph SDK v5.18.0

**Desktop (please complete the following information):**
N/C

**Additional context**
N/C

**Comment by MartinM85** [comment]
According to the doc, it's only for Beta. So, you need to use Microsoft.Graph.Beta nuget package instead of Microsoft.Graph.

**Comment by andrueastman** [comment]
Thanks for raising this @DCourtel,

As @MartinM85 this is available in the beta package at the moment as it is consumed in the beta API for now. 

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/Models/DeviceAndAppManagementAssignmentFilter.cs
