### ISSUE TITLE
Requests to get the access token do not go through the proxy

### ISSUE THREAD

**Issue by Yvand** [microsoftgraph/msgraph-sdk-dotnet#2032]
**Describe the bug**
When I configure the proxy [as documented](https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp#configuring-the-http-proxy-for-the-client), only the requests to graph.microsoft.com go through the proxy. The authentication requests (to login.microsoftonline.com) do not go through the proxy.

**To Reproduce**
I run [this sample](https://github.com/microsoftgraph/msgraph-training-dotnet/tree/main/app-auth/GraphAppOnlyTutorial), which works like a charm.
Then, I update it to use a prox, just [as documented here](https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp#configuring-the-http-proxy-for-the-client).
RESULT: Only the requests to graph.microsoft.com go through the proxy. The authentication requests (to login.microsoftonline.com) do not go through the proxy.

Relevant code which sets the proxy:
```cs
public static void InitializeGraphForAppOnlyAuth(Settings settings)
{
	_settings = settings;
	_clientSecretCredential = new ClientSecretCredential(_settings.TenantId, _settings.ClientId, _settings.ClientSecret);
	var handlers = GraphClientFactory.CreateDefaultHandlers();
	HttpClient httpClient = GraphClientFactory.Create(handlers: handlers, proxy: new WebProxy(new Uri("http://localhost:8888"), false));
	var authProvider = new Microsoft.Graph.Authentication.AzureIdentityAuthenticationProvider(credential: _clientSecretCredential, scopes: new[] { "https://graph.microsoft.com/.default", });
	_appClient = new GraphServiceClient(httpClient, authProvider);
}
```

This sample uses .NET 7.0 but I repro exactly the same issue using .NET Framework 4.8 in ASP.NET (my actual target)
(and I use a very simple localhost proxy for my tests)

**Expected behavior**
All requests, including requests to get the access token, go through the proxy

**Client version**
NuGet package Microsoft.Graph 5.19.0

**Comment by andrueastman** [comment]
Thanks for raising this @Yvand 

The proxy property also needs to be passed to the `ClientSecretCredential` as well to fix this. The documentation should be updated to resolve this. 

```cs
        // URI to proxy
        var proxyAddress = "http://localhost:8888";
        // Create a new System.Net.Http.HttpClientHandler with the proxy
        var handler = new HttpClientHandler
        {
            // Create a new System.Net.WebProxy
            // See WebProxy documentation for scenarios requiring
            // authentication to the proxy
            Proxy = new WebProxy(new Uri(proxyAddress))
        };
        // Create an options object for the credential being used
        // For example, here we're using a ClientSecretCredential so
        // we create a ClientSecretCredentialOptions object
        var options = new ClientSecretCredentialOptions
        {
            // Create a new Azure.Core.HttpClientTransport
            Transport = new HttpClientTransport(handler)
        };
        var credential = new ClientSecretCredential(
            "YOUR_TENANT_ID",
            "YOUR_CLIENT_ID",
            "YOUR_CLIENT_SECRET",
            options
        );
        var scopes = new[] { "https://graph.microsoft.com/.default" };
        // This example works with Microsoft.Graph 5+
        var httpClient = GraphClientFactory.Create(proxy: new WebProxy(new Uri(proxyAddress)));

        var graphClient = new GraphServiceClient(httpClient, new AzureIdentityAuthenticationProvider(credential, scopes: scopes));
```

This is tracked via https://github.com/microsoftgraph/msgraph-snippets-dotnet/issues/12

**Comment by andrueastman** [comment]
Thanks for confirming @Yvand 

We'll close this for now and track the documentation fix via https://github.com/microsoftgraph/msgraph-snippets-dotnet/issues/12
