### ISSUE TITLE
[Client bug]: Using ItemWithPath while getting/deleting specific permission generates incorrect URL

### ISSUE THREAD

**Issue by relair** [microsoftgraph/msgraph-sdk-dotnet#2034]
**Describe the bug**
Using ItemWithPath while getting (also deleting) specific permission generates incorrect URL and therefore doesn't work correctly.

**To Reproduce**
1. Get permission by ID while using ItemWithPath
Permission permission = await _graphServiceClient
                    .Drives[driveId].Items["root"].ItemWithPath(filePath)
                    .Permissions[permissionId].GetAsync();
2. See error "Permission was not found"

**Expected behavior**
Permission is returned without error

**Client version**
Microsoft.Graph 5.19.0

**Additional context**
Getting specific permission (graphServiceClient.Drives[driveId].Items["root"].ItemWithPath("FILE-NAME-HERE.pdf").Permissions[permissionId]) uses the following template:
{+baseurl}/drives/{drive-id}/items/{driveItem-id}/permissions/{permission-id}{?$select,$expand}
As you can see the file name is not referenced in the template at all.

Getting all permissions for item works and uses the following template:
graphServiceClient.Drives[driveId].Items["root"].ItemWithPath("FILE-NAME-HERE.pdf").Permissions
{+baseurl}/drives/{drive-id}/items/{driveItem-id}:/FILE-NAME-HERE.pdf:/permissions{?$top,$skip,$search,$filter,$count,$orderby,$select,$expand}
By the way it's interesting that file name is passed in template and not as parameter as with all the other parameters (that inconsistency is possibly connected with the bug)

**Comment by andrueastman** [comment]
Closing this to be tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2258
