### ISSUE TITLE
Consistency in code snippets comments

### ISSUE THREAD

**Issue by adhiambovivian** [microsoftgraph/msgraph-sdk-dotnet#2038]
From Graph Explorer

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/9458079/134223cc-6a0e-45bd-8860-1517fc3fbbb3)

Recently, additional information was added to the SDK snippets on version and the text is not consistent with the other comments eg information on downloading SDKs

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1048

**Comment by andrueastman** [comment]
Tracked via https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1048
