### ISSUE TITLE
Invalid .Me Request is being issued

### ISSUE THREAD

**Issue by yvrkarthik** [microsoftgraph/msgraph-sdk-dotnet#204]
Hi,
When I issue a `graph.Me.Request.GetAsync()` call to get the users details,I get a  
`"Message": "Code: BadRequest\r\nMessage: Unsupported segment type. ODataQuery: users/<Useremailaddress>/me` .
Upon debugging , I have noticed that the request URL which is being issued though the SDK is 
`https://graph.microsoft.com:443/v1.0/me/me` rather than `https://graph.microsoft.com:443/v1.0/me`

![screenshot 15](https://user-images.githubusercontent.com/1669197/32253834-f7cbf1a0-bf01-11e7-8fbf-cd9656750026.png)

Is this a known issue?

**Comment by MIchaelMainer** [comment]
Strange. What does your instantiation of the GraphServiceClient object look like? I suspect that you used "https://graph.microsoft.com:443/v1.0/me" as the baseUrl instead of "https://graph.microsoft.com/v1.0", which is the default.

**Comment by MIchaelMainer** [comment]
I'm fairly confident that you are setting the wrong URL. If this is not the case, please reopen this issue.
