### ISSUE TITLE
Microsoft Graph API Idempotency

### ISSUE THREAD

**Issue by jsquire** [microsoftgraph/msgraph-sdk-dotnet#2042]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#37877](https://github.com/Azure/azure-sdk-for-net/issues/37877).

### Library name and version

Microsoft.Graph 5.19.0

### Query/Question

Is there any guidance on how to create an app registration and service principal and how to configure those in an **idempotent way**?

Why are the Microsoft Graph APIs itself not idempotent like all the Azure.ResourceManager.* libraries?

**Comment by Rookian** [comment]
See also this Stackoverflow [thread](https://stackoverflow.com/questions/75731982/error-patch-app-roles-on-app-registration-using-graph-api-v5-app-role-with-iden)

**Comment by andrueastman** [comment]
Closing this. Will be followed up via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2044
