### ISSUE TITLE
Page Iterator causing 404 error during pagination

### ISSUE THREAD

**Issue by jvillanuevabt** [microsoftgraph/msgraph-sdk-dotnet#2045]
**Describe the bug**
During TeamworkTagMember enumeration with pagination, the initial request succeeds (with the max of 100 members returned). Subsequent requests initiated by the page iterator throw the following exception:

```
Microsoft.Kiota.Abstractions.ApiException: The server returned an unexpected status code and no error factory is registered for this code: 404
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.PageIterator`2.InterpageIterateAsync(CancellationToken token)
   at Microsoft.Graph.PageIterator`2.IterateAsync(CancellationToken token)
   at Microsoft.Graph.PageIterator`2.IterateAsync()

```

**To Reproduce**
Iterate multiple pages of Team Tag Members with a PageIterator.

**Expected behavior**
For the past few months this code has resolved pagination correctly, this exception began ~3 days ago with no code change on my end.

**Client version**
Originally reproduced on 5.5.0, updating to 5.19.0 (and now 5.20.0) have not resolved the issue.

**Desktop (please complete the following information):**
Windows 10 Enterprise

**Additional context**
My Page Iterator code is very straightforward, directly from documentation:

```
TeamworkTagMemberCollectionResponse members = await graphClient.Teams[tag.TeamId].Tags[$"{tag.Id}"].Members.GetAsync();

var pageIterator = PageIterator<TeamworkTagMember, TeamworkTagMemberCollectionResponse>
	.CreatePageIterator(graphClient, members, tagMember =>
	{
		users.Add(tagMember);
		return true;
	});

await pageIterator.IterateAsync();
```

The initial request is confirmed to succeed and retrieves 100 tag members but subsequent requests made by the page iterator do not succeed with the exception posted above. While investigating this, I noticed a difference in the Uri being used during the initial request and subsequent requests that may be causing the issue:
initial request uri: `/v1.0/teams/<guid>/tags/<redacted noise>%3D%3D/members`
page iterator uri: `/v1.0/teams/<guid>/tags/<redacted noise>==/members?$skiptoken=1.kscDYs0BBMYAAADb8CiBqlByb3BlcnRpZXOCsUNvbnRpbnVhdGlvblRva2Vu2dIrUklEOn5yRmR5QVBGMytuUng5M3dBAQDxI0RBPT0jUlQ6MSNUUkM6MTAwI0lTVjoyI0lFTzo2NTU1MSNRQ0Y6OCNGUEM6QWdqekFRNQBQQUFLa0NAAHBNQUFBOHdFCwAAUQDzDFFBSEUzL3ZzVFFQLzEvZjcvK3hGQWZ3QUdBZzgAeEFJQWE1bEEQAEhPb2x6EABINTRxRBAASE1LdXAQAPAGRnBNPaxMYXN0UGFnZVNpemWjMTAw
`

The skip token seems fine/reasonable, but note the unescaped `==` in the page iterator uri. This may be a red herring but it is my current best guess. I don't think I'm doing anything wrong since this has been working for several months, but please let me know if there is anything I should fix on my end.

**Comment by andrueastman** [comment]
Thanks for raising this @jvillanuevabt, 

To understand this further, does this fail on all sample tags `{tag.Id}` that you attempt to page through the members or does this fail only for specific tags?

**Comment by jvillanuevabt** [comment]
@andrueastman Unfortunately I only have exactly 1 `{tag.Id}` that requires pagination in the first place with more than 100 members.

**Comment by jvillanuevabt** [comment]
Update: my scheduled task that runs this (which has been getting the above exception for a little over 2 weeks now) just successfully ran with no code change on my part. I assume there is/was an error in the API somewhere that has possibly been rectified?
