### ISSUE TITLE
Batch support

### ISSUE THREAD

**Issue by gastart** [microsoftgraph/msgraph-sdk-dotnet#205]
The documentation says that batching is supported so I was wondering if it possible to do batch requests with the current version of the .Net sdk?  In June the situation was this #136.

**Comment by MIchaelMainer** [comment]
We don't have batching support in the client library. Closing as this is a duplicate

**Comment by MIchaelMainer** [comment]
@gastart I forgot one thing. Thank you for contacting us. Please add thumbs up reaction to the other issue so we can capture your request for this feature.
