### ISSUE TITLE
When getting MIME content of outlook message using graph SDK, in the stream response "Length", "Position", "CanSeek", "Capacity" properties are not supported after upgrading graph version to 5.21.0

### ISSUE THREAD

**Issue by DilukaDavton** [microsoftgraph/msgraph-sdk-dotnet#2052]
I am calling following graph call to get the message content using graph sdk

```
var graphClient = new GraphServiceClient(requestAdapter); 

await graphClient.Users["{mailbox-address}"].Messages["{message-id}"].Content.GetAsync();
```

As a response it gives a stream and that stream response not supporting for "Length", "Position", "Capacity", "CanSeek" properties.

This issue happened after I upgrade the graph version to 5.21.0 from 4.54.0.

This is how response looks like.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/114378226/379250be-5160-4670-8e71-338aa43a553b)

Can anyone help with this issue?

**Comment by ArturAdam** [comment]
+1

**Comment by DilukaDavton** [comment]
@andrueastman Thank you very much for your response and confirmation regarding this issue. I appreciate your contribution. Just to let you know, I've already been implementing the solution you mentioned.

**Comment by MAlabaster** [comment]
Likewise I appreciate this report and the repsonse as I was trying to convert the stream into a byte array to POST to a web service and getting "method not supported" on the length.
