### ISSUE TITLE
Weird Behavior in Graph API while Retrieving JoinedTeams Information of a User

### ISSUE THREAD

**Issue by UmamaheshwariGolla** [microsoftgraph/msgraph-sdk-dotnet#2053]
We have been encountering some peculiar behavior in the Graph API when attempting to retrieve JoinedTeams information for a specific user.

**To Reproduce**
we are able to replicate the issue in Graph explorer for the endpoint **https://graph.microsoft.com/v1.0/users/{user-id}/joinedTeams**

**Expected behavior**
return the all the teams that a user is part of

Please find the error information

**Code**: **NotFound** 

**Message**: Failed to execute MsGraph backend request GetUserGroupsS2SRequest. Workload MsGraph_DirectoryServices. Request Url: [https://graph.microsoft.com/edu/users/{id}/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(c:c+eq+'Unified')&$top=999](https://graph.microsoft.com/edu/users/%7Bid%7D/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(c:c+eq+%27Unified%27)&$top=999), Request Method: GET, Response Status Code: NotFound, Response Headers: Strict-Transport-Security: max-age=31536000

**Comment by andrueastman** [comment]
Thanks for raising this @UmamaheshwariGolla 

Does the issue affect all users? Or just a specific user in the organization/tenant?

**Comment by UmamaheshwariGolla** [comment]
Hello @andrueastman , 

We encountered an issue with a particular user when utilizing their user-email instead of their user-id. While we have been consistently using user-emails for all users, this approach failed for specific user. Interestingly, switching to the user-id resolved the problem. Despite using user-emails successfully in the past, the reason behind this sudden failure is unclear.

**Comment by andrueastman** [comment]
Posted query at the link below for feedback from the API team. 

https://learn.microsoft.com/en-us/answers/questions/1355085/list-joinedteams-fails-when-using-email-rather-tha

Closing this for now so this may be followed up there
