### ISSUE TITLE
Either Count is broken or I am using it wrong

### ISSUE THREAD

**Issue by Coder3333** [microsoftgraph/msgraph-sdk-dotnet#2054]
I cannot get the Count command to work, even though I can query for user objects successfully.  Am I doing it wrong or is it broken?

Microsoft.Graph 5.21.0
        
```
// without Count, I can successfully query for a user record
                var b = await graphClient.Users.GetAsync(con => {
                    con.QueryParameters.Filter = $"userPrincipalName eq '{upn}'"; 
                });

// Once I introduce "Count" I get an exception, whether I have a Filter or not
                var a = await graphClient.Users.Count.GetAsync(con => {
                    con.QueryParameters.Filter = $"userPrincipalName eq '{upn}'"; 
                });

                var c = await graphClient.Users.Count.GetAsync(con => {
                });
```

Exception Stack Trace:

> Message: 
> Microsoft.Graph.Models.ODataErrors.ODataError : Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
> 
>   Stack Trace: 
> HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
> HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
> HttpClientRequestAdapter.SendPrimitiveAsync[ModelType](RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
> CountRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)

**Comment by Coder3333** [comment]
@andrueastman , yes, adding the ConsistencyLevel works.  Is this considered a required parameter that I missed or is this a bug?

**Comment by andrueastman** [comment]
This is a required parameter for the specific endpoint. You can check out more at link below. 
https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http

**Comment by Coder3333** [comment]
So, the work around for this issue is to declare ConsistencyLevel as @andrueastman pointed out, but I have to say that this .Net SDK seems pretty poorly implemented that it doesn't automatically include this "required" header.

> var count = await graphClient.Users.Count.GetAsync((requestConfiguration) =>
> {
> 	requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
> });
