### ISSUE TITLE
[Client bug]: GraphClient.Users[userId].PatchAsync() does not return the updated user

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/msgraph-sdk-dotnet#2058]
When updating user's data/profile, calling `PatchAsync()` updates the user but does not return it.

```
string userId = "[SOME_USER_GUID]";
User existingUser = await _graphClient.Users[userId].GetAsync().ConfigureAwait(false);
existingUser.Surname = "A New Surname";
User updatedUser = await _graphClient.Users[userId].PatchAsync(existingUser).ConfigureAwait(false);
Assert.NotNull(updatedUser);
```

**Expected behavior**
updatedUser should not be null

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/131436682/f37b4d11-fbdb-4e70-b1df-2c06d4ec968f)

**Client version**
"Microsoft.Graph" Version="5.21.0"

**Desktop (please complete the following information):**

 - OS: Windows 11 22H2 (23516.1000)

**Additional context**
using B2C

**Comment by genadij-trimailov-flextools** [comment]
related to #1855, which probably means that .`PatchAsync(existingUser)` should not return a user, and instead the updated user should be queried separately.

**Comment by andrueastman** [comment]
Thanks for raising this @ghost, 

The API call returns no response body as captured in the documentation. However, the metadata used to generate the SDK suggest a response body is expected hence the existing return type. 
https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#response-1

Closing this for now to track the metadata issue via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1855
