### ISSUE TITLE
Unable to update contact with mobilephone

### ISSUE THREAD

**Issue by redhorseck** [microsoftgraph/msgraph-sdk-dotnet#206]
I can successfully add a contact with a string value in MobilePhone using 
client.Me.Contacts(id).Request().AddAsync(contact)

If I try to update a contact with a string value in MobilePhone using
client.[Me].Contacts(id).Request().UpdateAsync(c)

Specifically, the error happens when the contact did not have a mobile phone and I add one. If it has one and I do not change it, it updates ok. If it has one and I change it, it updates ok. If it didn't have one and set the string for a new one, it errors.

I get this error:
StatusCode: BadRequest {400}
Message: Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.

Since the string I am using in both is the same and all other data being passed is the same, I'm pretty sure there is an issue with the UpdateAsync method.

**Comment by MIchaelMainer** [comment]
I repro'd your scenario. 

```
var c = await client.Me.Contacts.Request().AddAsync(contact)
c.MobilePhone = "5559990000";
await client.[Me].Contacts(id).Request().UpdateAsync(c);
```

What ends up happening is that you end up patching the entire contact that you created in the first call. The service is not expecting some of the fields. There does look to be an issue in the service. With that said, the correct way for you to do this is:

```
var c1 = await client.Me.Contacts.Request().AddAsync(contact)
var contactMobile = new Contact()
{
    MobilePhone = "4252221111"
};
await client.[Me].Contacts(c1.id).Request().UpdateAsync(contactMobile );
```

This will PATCH just the mobile phone number.

**Comment by redhorseck** [comment]
Thanks for the tip. We will use that for the update to MobilePhone. Where there be an update to the service at some point so that we can do a normal patch?

**Comment by MIchaelMainer** [comment]
You don't need to make individual calls for each field. Set the department field at the same time as the mobilephone field. Think of the contact you use to update as a patch object. Your shouldn't pass in a Contact you got back from the service. I suggest that you don't use the objects returned by the client library calls as your models. This client library is just a pass through and a somewhat light abstraction over the HTTP calls. 

```
var c1 = await client.Me.Contacts.Request().AddAsync(contact)
var patchContact = new Contact()
{
    MobilePhone = "4252221111",
    Department = "Planning"
};
await client.[Me].Contacts(c1.id).Request().UpdateAsync(patchContact);
```

**Comment by redhorseck** [comment]
I get it. That made all the difference. Thanks so much!

**Comment by MIchaelMainer** [comment]
You're welcome!

**Comment by redhorseck** [comment]
Sorry one last question. If I need to set something to blank or nothing, how do you do that if this looks like you are only affecting data with a value?

**Comment by MIchaelMainer** [comment]
The client library will not serialize null. You can set empty strings. In the case that the service allows you to set something to null, you'll have to issue the request outside of the client library.

**Comment by MIchaelMainer** [comment]
@redhorseck I was wrong. If you want to try to set something to blank or null, use the additionalData property bag to set the property. The key being the property name, and the value to either null or ""
