### ISSUE TITLE
Meetingregistration object is not working in Graph Bata.

### ISSUE THREAD

**Issue by eqian12** [microsoftgraph/msgraph-sdk-dotnet#2061]
I create an online meeting by graph and retune a meeting ID. https://learn.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta
By this ID I create a meetingregistration, https://learn.microsoft.com/en-us/graph/api/resources/meetingregistration?view=graph-rest-beta, but that shows error. 
严重: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: Invalid request. Provide microsoft.graph.meetingRegistration or microsoft.graph.externalMeetingRegistration in request body.
![20230807144907](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14146429/3a87b63d-8cf0-4d88-a1a8-98438ee4f063)

**Comment by andrueastman** [comment]
Thanks for raising this @eqian12 

Any chance of you can share the code sample you are using to make the request? The screenshot provided does not seem to be a C# sample. 

Possibly related to https://github.com/microsoftgraph/msgraph-metadata/issues/405
