### ISSUE TITLE
Updating group not doing anything

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/msgraph-sdk-dotnet#2064]
I'm trying to update groups using the .NET SDK.

As per the [documentation](https://learn.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=csharp), I'm creating a new instance of the `Microsoft.Graph.Models.Group` object, then use `PatchAsync` to apply the change. I get success back, but nothing has been changed. Looking at the data over the wire, I see that the content of the request is an empty json.

here's the relevant code bits:

```
Microsoft.Graph.Models.Group updateGroup = new();
updateGroup.Description = "new Description";
updateGroup.DisplayName = "new displayname";
rollbackGroup.MailNickname = "newNickname";

var updatedGroup = await graphServiceClient.Groups[id].PatchAsync(updateGroup ).ConfigureAwait(false);
```

I would expect that the values `Description`, `DisplayName` and `MailNickname`would be changed. Instead, nothing changed.

If instead of creating a new group, I fetch the existing group first

`Microsoft.Graph.Models.Group updateGroup = await await graphServiceClient.Groups[id].GetAsync().ConfigureAwait(false);`

and then proceed with this group, the update works as expected.

My guess is that the backing store gets initialized differently, and the change tracking then yields these 3 modified props. But the documentation says nothing about this requirement. So.. how can I instantiate a new group, set the properties I want, and submit those?

My environment:
Windows 11 Pro
VS 17.7.0
.NET SDK 7.0.400
Microsoft.Graph 5.21.0

**Comment by andrueastman** [comment]
Thanks for raising this @ssteiner,

Just to confirm do you get a different result when you change

```cs
Microsoft.Graph.Models.Group updateGroup = new();
updateGroup.Description = "new Description";
updateGroup.DisplayName = "new displayname";
updateGroup.MailNickname = "newNickname";
```

to

```cs
Microsoft.Graph.Models.Group updateGroup = new()
{
    Description = "new Description",
    DisplayName = "new displayname",
    MailNickname = "newNickname"
};
```

**Comment by ssteiner** [comment]
changing the syntax does indeed make `PatchAsync` work

**Comment by andrueastman** [comment]
@ssteiner 
Any chance you can confirm this is still an issue on the latest version of the SDK?https://www.nuget.org/packages/Microsoft.Graph/5.36.0

**Comment by MaWa19** [comment]
@andrueastman I'm on 5.37.0 and I'm experiencing almost the same issue, besides the workarounds aren't working for me either.

Neither
`
await _graphServiceClient.Groups[group.Id].Team.PutAsync(team);
`

nor 
`
await _graphServiceClient.Teams[group.Id].PatchAsync(team);
`

are actually updating the team's settings, but both return success codes. However, creating the team via the PUT request works and patching the settings via HTTP call also works also works so I'd assume a bug in the SDK.

**Comment by andrueastman** [comment]
@MaWa19 Any chance you can share the way you are initialing the `team` object as well as the properties you are trying to update?

**Comment by MaWa19** [comment]
Sure, will do anything that can help.

1) Initial implementation that broke after updating to v5 was based on JSON templates that we defined internally:

template.json:
```
{
  "id": "0",
  "templateName": "basic",
  "visibility": "private",
  "memberSettings": {
    "allowCreateUpdateChannels": false,
    "allowCreatePrivateChannels": false,
    "allowDeleteChannels": false,
    "allowAddRemoveApps": false,
    "allowCreateUpdateRemoveTabs": false,
    "allowCreateUpdateRemoveConnectors": false
  },
  "guestSettings": {
    "allowCreateUpdateChannels": false,
    "allowDeleteChannels": false
  },
  "messagingSettings": {
    "allowUserEditMessages": true,
    "allowUserDeleteMessages": true,
    "allowOwnerDeleteMessages": true,
    "allowTeamMentions": true,
    "allowChannelMentions": true
  },
  "funSettings": {
    "allowGiphy": false,
    "giphyContentRating": "strict",
    "allowStickersAndMemes": true,
    "allowCustomMemes": false
  },
  "installedApps": [
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.planner')"
    },
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('0d820ecd-def2-4297-adad-78056cde7c78')"
    },
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('1542629c-01b3-4a6d-8f76-1938b779e48d')"
    },
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('2a527703-1f6f-4559-a332-d8a7d288cd88')"
    },
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.web')"
    },
    {
      "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('81fef3a6-72aa-4648-a763-de824aeafb7d')"
    }
  ],
  "searchable": false
}
```
Creating a Team object from template:
```
var templateContent = await Storage
    .BlobToString(_log, xRequestId, storageConnectionString, "templates", $"{template}.json");

Team team = templateContent.Deserialize<Team>();
```

2) Tried a hardcoded version for debugging reasons:
```
var team = new Team()
{
    MemberSettings = new TeamMemberSettings()
    {
        AllowCreateUpdateChannels = false,
        AllowDeleteChannels = false,
        AllowAddRemoveApps = false,
        AllowCreateUpdateRemoveTabs = false,
        AllowCreateUpdateRemoveConnectors = false,
        AllowCreatePrivateChannels = false
    },
    MessagingSettings = new TeamMessagingSettings()
    {
        AllowUserEditMessages = true,
        AllowUserDeleteMessages = true,
        AllowChannelMentions = true,
        AllowOwnerDeleteMessages = true,
        AllowTeamMentions = true
    },
    GuestSettings = new TeamGuestSettings()
    {
        AllowCreateUpdateChannels = false,
        AllowDeleteChannels = false
    },
    FunSettings = new TeamFunSettings()
    {
        AllowGiphy = false,
        GiphyContentRating = GiphyRatingType.Strict,
        AllowStickersAndMemes = true,
        AllowCustomMemes = false
    }
};

await _graphServiceClient.Teams[group.Id].PatchAsync(team);
```

**Comment by andrueastman** [comment]
@MaWa19 The second option does indeed work for me without issue. Any chance you can share how you are validating this?

For the first option, you many need to use the KiotaJsonSerializer as the v5 models use a custom serialization logic.

```cs
var team = KiotaJsonSerializer.Deserialize<Team>(json);
```
