### ISSUE TITLE
User $filter companyName is not working in combination whit $expand=manager

### ISSUE THREAD

**Issue by trust11** [microsoftgraph/msgraph-sdk-dotnet#2068]
**Describe the bug**
Filter on companyName does not work for Microsoft.Graph.Models.User object
In Doc https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
it is written:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/50418856/889b48f3-b9e5-44a3-ad21-f7cad659311d)

and here is written
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/50418856/818fec04-07f7-463f-8547-c8138b27fcf6)

That means that we need Consistencylevel eventual in the header and we need also to add $count=true then it works.

if we add also the $expand=manager then we get the error

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/50418856/0291e26c-ae96-4633-8cfb-b4b55fd1933b)

**To Reproduce**
Here the Link to the graph explorer this works
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DstartsWith(givenName%2C'henrietta')and%2BcompanyName%2Beq%2Bnull%26%24select%3Did%2Cdisplayname%2CcompanyName%2Cmanager&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

But if we add $expand=manager
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DstartsWith(givenName%2C'henrietta')and%2BcompanyName%2Beq%2Bnull%26%24select%3Did%2Cdisplayname%2CcompanyName%2Cmanager%26%24expand%3Dmanager&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

We get the same error as we have when for e.g. $count=false would be missing
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/50418856/8ac74821-4e95-42f1-815c-c89cf7ef5e78)

Henrietta is a default user who comes along with the test environment.

**Expected behavior**
It is supported, and so I expect that it is supported

**Client version**
No clue what MS Graph Explorer uses

**Comment by etcetera33** [comment]
Same problem here.

**Comment by trust11** [comment]
> Same problem here.

Can you check this out? Have added the $count and it works. 
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24select%3DdisplayName%2CcompanyName%26%24filter%3DcompanyName%2Beq%2Bnull%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d

**Comment by etcetera33** [comment]
Thanks for the update, but I still keep getting error 
`
Unsupported or invalid query filter clause specified for property 'companyName' of resource 'User'.
`

my code is 

```
var users = await graphClient.Users.GetAsync(requestConfiguration =>
    {
        requestConfiguration.QueryParameters.Select = new[]
        {
            "Id", "AccountEnabled", "DisplayName", "GivenName", "Surname", "Mail", "UserPrincipalName",
            "MobilePhone", "CreatedDateTime", "SignInActivity", "PasswordProfile", "Country"
        };
        requestConfiguration.QueryParameters.Filter = "companyName eq 'MSFT'";
        requestConfiguration.QueryParameters.Count = true;
        requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
    });
```

**Comment by andrueastman** [comment]
@etcetera33 Are you also able to replicate this on the Graph Explorer as @trust11 suggests?

**Comment by andrueastman** [comment]
Closing this for now as this similar to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2175#issuecomment-1774579699 as advanced queries on Microsoft Entra ID objects do not support `$expand` for now.
