### ISSUE TITLE
Support for Win32LobApp on `deviceAppManagement/mobileApps`

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/msgraph-sdk-dotnet#2073]
**Is your feature request related to a problem? Please describe.**
I want to use the SDK for all my graph commands, to my surprise even the beta version does not support the `microsoft.graph.win32LobApp` stuff.

**Describe the solution you'd like**
support for these endpoints:

- https://learn.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-create?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985
- https://learn.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-list?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985
- https://learn.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-get?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985
- https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappcontent-list?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985
- https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappcontent-create?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985
- https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappcontentfile-create?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985

**Describe alternatives you've considered**

I tried creating extension methods on the [MobileAppItemRequestBuilder](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/7c031dbc0fa9c753b64e3ef40aa1362deb51a21f/src/Microsoft.Graph/Generated/DeviceAppManagement/MobileApps/Item/MobileAppItemRequestBuilder.cs) but that does not work because it's [actively blocked from being extended](https://github.com/microsoft/kiota-abstractions-dotnet/issues/113) 

**Additional context**

**Microsoft.Graph.Beta**: `5.43.0-preview` (latest version as of 14-8-2023)

I've been messing with the raw http requests to get it working
```http
### Create a WinGetApp


POST https://{{host}}/{{endpoint}}/deviceAppManagement/mobileApps
Content-type: application/json
Authorization Bearer {{token}}

{
  "@odata.type": "#microsoft.graph.winGetApp",
  "displayName": "Oh My Posh",
  "description": "Prompt theme engine for any shell",
  "publisher": "Jan De Dobbeleer",
  "largeIcon": {
    "@odata.type": "microsoft.graph.mimeContent",
    "type": "String",
    "value": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsSAAALEgHS3X78AAAA0klEQVQ4y93TPwtBURjH8YfBYPBnVjeTmCziBZhsbtktvAGD4jWYpLB4HQYDSpHNYGeyid2f77k9ysB1GD31ubdO/X7n3FtHRCSEGOJPYpZMVoaYqDHmWGFpwWTlhhH6aGOtazYupuCKjTbOsMX+gx0Oj4ITysihiCQcfb/jaMZk5ajhFHpoIoOg+E9Bs96joIsRVDFFSf+yKezorm8L8oiiji4aSOgp0sgi7FeQ02PXdKeAfJ6Xn/DN/FPBGS24qFhyNWOyMsDiRyb78jrb8K7zHYaPWivChOFWAAAAAElFTkSuQmCC"
  },
  "isFeatured": true,
  "privacyInformationUrl": "https://github.com/JanDeDobbeleer/oh-my-posh/raw/main/COPYING",
  "informationUrl": "https://github.com/JanDeDobbeleer/oh-my-posh/",
  "owner": "Jan De Dobbeleer",
  "developer": "Jan De Dobbeleer",
  "notes": "Notes value",
  "uploadState": 2,
  "publishingState": "processing",
  "isAssigned": false,
  "roleScopeTagIds": [],
  "dependentAppCount": 0,
  "supersedingAppCount": 0,
  "supersededAppCount": 0,
  "manifestHash": "Manifest Hash value",
  "packageIdentifier": "JanDeDobbeleer.OhMyPosh",
  "installExperience": {
    "@odata.type": "microsoft.graph.winGetAppInstallExperience",
    "runAsAccount": "user"
  }
}

### Get an app by id

GET https://{{host}}/{{endpoint}}/deviceAppManagement/mobileApps/625fac12-63ea-482a-a811-2dba7f524998
Content-Type application/json
Authorization Bearer {{token}}

### Get App Content Versions
GET https://{{host}}/{{endpoint}}/deviceAppManagement/mobileApps/16ff30dc-d064-405e-a1e4-7b675a5a8625/microsoft.graph.win32LobApp/contentVersions
Content-Type application/json
Authorization Bearer {{token}}

### Commit app
POST https://{{host}}/{{endpoint}}/deviceAppManagement/mobileApps/66a1e76b-37b9-48a5-bc43-f55dd1e6bcad/microsoft.graph.win32LobApp/contentVersions/1/files/735718b0-5187-4c6a-8c7f-c10d68f3bed6/commit
Content-Type application/json
Authorization Bearer {{token}}

{
  "fileEncryptionInfo": {
    "encryptionKey": "zItIfv4tKhpfVFEAHQRJBNPHWe1y0HbHIksD5VNwscg=",
    "initializationVector": "mPxbxFv1PeGxMHmsUYTLJw==",
    "mac": "61FnckpV9Hla6CXLa2xUyzd2F5IaTO7KFln6RfOSSQ8=",
    "macKey": "H9DU/pt/cRPhDaGrriFTUYhQtSSomBXkRYGNY3zhwRQ=",
    "profileIdentifier": "ProfileVersion1",
    "fileDigest": "/O1hIjB5L/V2CqbNczKhHsUALm54xW6+jWRnIuKhuIM=",
    "fileDigestAlgorithm": "SHA256"
  }
}

### Get App Content File
GET https://{{host}}/{{endpoint}}/deviceAppManagement/mobileApps/66a1e76b-37b9-48a5-bc43-f55dd1e6bcad/microsoft.graph.win32LobApp/contentVersions/1/files/735718b0-5187-4c6a-8c7f-c10d68f3bed6
Content-Type application/json
Authorization Bearer {{token}}

### Patch app
PATCH https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/66a1e76b-37b9-48a5-bc43-f55dd1e6bcad
Content-Type application/json
Authorization Bearer {{token}}

{
  "@odata.type": "#microsoft.graph.win32LobApp",
  "committedContentVersion": "1"
}

```

**Comment by baywet** [comment]
Thanks for reporting this.
A quick look at this and it seems the metadata fixup process [is missing one or more entries](https://github.com/microsoftgraph/msgraph-metadata/blob/2580d71e8e6ae6a23816c0ac85a30d0267e147cd/transforms/csdl/preprocess_csdl.xsl#L372)

What would help is if you could help identify the other potential missing entries @svrooij 

@andrueastman to create a corresponding issue on the metadata side to address the gap.

**Comment by baywet** [comment]
Thanks for your patience on this issue.

Just as an update on the progress:
1. `POST /deviceAppManagement/mobileApps` [is now supported by the SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e34cbfc2b934f8844daac137e78e89b32947f2d2/src/Microsoft.Graph/Generated/DeviceAppManagement/MobileApps/MobileAppsRequestBuilder.cs#L86) including [with a win32LobApp](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e34cbfc2b934f8844daac137e78e89b32947f2d2/src/Microsoft.Graph/Generated/Models/Win32LobApp.cs#L11) since it derives from the accepted body type
2. `GET /deviceAppManagement/mobileApps` [is now supported](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e34cbfc2b934f8844daac137e78e89b32947f2d2/src/Microsoft.Graph/Generated/DeviceAppManagement/MobileApps/MobileAppsRequestBuilder.cs#L62) and assuming the service sends an odata type (which is should) the sdk [will downcast to the right type during deserialization](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e34cbfc2b934f8844daac137e78e89b32947f2d2/src/Microsoft.Graph/Generated/Models/MobileApp.cs#L214)
3. `GET /deviceAppManagement/mobileApps/{id}` [is now supported by the SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/e34cbfc2b934f8844daac137e78e89b32947f2d2/src/Microsoft.Graph/Generated/DeviceAppManagement/MobileApps/Item/MobileAppItemRequestBuilder.cs#L84), so is the downcast thanks to the logic above.
4. For contentVersions
    a. `GET /deviceAppManagement/mobileApps/{mobileAppId}/contentVersions` is not supported by the SDK since the contentVersions property is not present on mobileApp. This is not something that can be changed now since it'd be a breaking change to hoist the property
    b. `GET /deviceAppManagement/mobileApps/{mobileAppId}/microsoft.graph.mobileLobApp/contentVersions` (and equivalent for managementMobileLobApp) is missing from the SDK since the conversion process does not expand navigation properties on typecast segments (only methods). This might need to be fixed in the conversion library.
5. `POST .../contentVersions` same logic applies as the previous point.
6. `POST .../conentVersions/{id}/files` same logic applies as the previous point.

**Comment by svrooij** [comment]
@baywet I missed some things in the original issue:

- [Adding categories](https://github.com/svrooij/WingetIntune/blob/30b5f76fbaa043de94be29c4c05b692b19540b0e/src/WingetIntune/Graph/GraphServiceClientExtensions.cs#L114-L132) to an app also is not possible (so it seems).
- `POST .../contentVersions/{id}/files/{id}/commit` this also needs details documentation for other to be able to use it.
- I was talking about the `win32LobApp` are you saying that I can use the mobileLobApp instead? Because the `win32LobApp` is not yet available.
- The `GraphMobileLobApp` only has a relevant `.GetAsync()` it doesn't do anything.

> is missing from the SDK since the conversion process does not expand navigation properties on typecast segments (only methods). This might need to be fixed in the conversion library.

What does this mean? It that something that takes:

- 1 pr
- 1 week
- 1 month
- 1 year

to fix?

**Comment by baywet** [comment]
> What does this mean? It that something that takes:

At best 1 PR in the metadata repository, at worst 1 PR in the conversion repo and 1 PR in the metadata repo. Coordinating those things (among other priorities) can take a while as you've already experienced. We'll know more once the thread on metadata comes to a resolution. Thanks for your patience.

> I was talking about the win32LobApp are you saying that I can use the mobileLobApp instead?

You can use the win32LobApp model as the request body for POST/PATCH operations that accept a `MobileLobApp` or a `MobileApp`.

> Because the win32LobApp is not yet available.

Can you clarify what you mean by that? the model? some API path is not available as a code path?

> The GraphMobileLobApp only has a relevant .GetAsync() it doesn't do anything.

Can you clarify that? From an API standpoint it should filter the collection to only the items of that type (or derived). From an SDK perspective, it gives you a casted collection right away, no need for you to cast anymore.
