### ISSUE TITLE
Access Sharepoint to upload file

### ISSUE THREAD

**Issue by knight1219** [microsoftgraph/msgraph-sdk-dotnet#208]
I am having a very hard time trying to looking at the docs for this package and figuring out how to use this to Add/Retrieve files in sharepoint. I see is a "Site" object, but I'm just not seeing a way to do it. I have the asp.net Snippets sample I am trying to get working with getting folders and files from sharepoint.

Is this possible with this package or do I need to try something else?

**Comment by MIchaelMainer** [comment]
I expect that this is supported. You'll start by traversing the sites collection, selecting the site and then drill into the different drives under that site. Then you'll use the Drive API to access the files.

            // List of sites
            var sitesCollection = await graphClient.Sites.Request().GetAsync();

            // Get the first site in the site list. This step could be combined with the next.
            var site = await graphClient.Sites[sitesCollection[0].Id].Request().GetAsync();

            // Get the drives in the site.
            var driveCollection = await graphClient.Sites[site.Id].Drives.Request().GetAsync();

            // Get the first drive in the drive collection
            var drive = await graphClient.Drives[driveCollection[0].Id].Request().GetAsync();

            // List the files in the drive
            var filesCollection = await graphClient.Drives[drive.Id].Root.Children.Request().GetAsync();

The samples found under https://github.com/microsoftgraph will have some examples of accessing the DriveItems.

**Comment by knight1219** [comment]
Why would I be getting an error about `invalidRequest Cannot enumerate sites` error? Is there an special set of permissions I need to give to my app for this to work?

**Comment by MIchaelMainer** [comment]
That is a service error message. Please post questions/issues about the service to StackOverflow with the microsoftgraph tag. Add a link to to your Stackoverflow post to this issue so we can follow it. Make sure you capture the request and response and put it in your StackOverflow post. The error doesn't appear to a be based on permissions.

**Comment by courtenayf** [comment]
Posted here:
https://stackoverflow.com/questions/48147370/cannot-enumerate-sites
