### ISSUE TITLE
Code example in errors.md does not handle errors correctly

### ISSUE THREAD

**Issue by guanlx** [microsoftgraph/msgraph-sdk-dotnet#2085]
The current document suggests to check the status code that caused the error as below.

```csharp
catch (ODataError odataError) when (odataError.ResponseStatusCode.Equals(HttpStatusCode.NotFound))
{
        // Handle 404 status code
}
```
But ResponseStatusCode is int and HttpStatusCode.NotFound is HttpStatusCode, while int.Equals would compare the object type first and it would never be equal.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/16677937/11a3018b-a665-4ce3-a43b-2c0fcd94cf61)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/16677937/3749dcb7-84cb-470d-b708-35cce3e5896f)

**Comment by andrueastman** [comment]
Thanks for raising this @guanlx 

Any chance yould you be willing to submit a PR to update the docs to fix this?

**Comment by guanlx** [comment]
@andrueastman sure, submitted a PR for this.
