### ISSUE TITLE
Upload small files using batch error

### ISSUE THREAD

**Issue by eprach** [microsoftgraph/msgraph-sdk-dotnet#2089]
Hi Team,

I work on an app using the SDK and I would like to upload files from file system to SharePoint Online.

Below is part of my code:

`
BatchRequestContentCollection batch = new BatchRequestContentCollection(MSGraphService.graphClient, fileShareitems.Count());
using (FileStream fs = File.OpenRead(item.Path))
{

    var fileUploadRequest = graphClient.Drives[drive.Id]
        .Root
        .ItemWithPath(uploadInfo[1]).Content.ToPutRequestInformation(fs);
    fileUploadRequest.URI = new Uri(fileUploadRequest.URI.OriginalString + "?@microsoft.graph.conflictBehavior=rename");

    var result = await batch.AddBatchRequestStepAsync(fileUploadRequest);

    var returnedResponse = await MSGraphService.graphClient.Batch.PostAsync(batch);

    var fileResponse = await returnedResponse.GetResponseByIdAsync<DriveItem>(result);
}
`

I expect to have my files saved to the right document library but I get the following issue:

> 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
>    at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
>    at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
>    at Microsoft.Kiota.Serialization.Json.JsonParseNodeFactory.GetRootParseNode(String contentType, Stream content)
>    at Microsoft.Kiota.Abstractions.Serialization.ParseNodeProxyFactory.GetRootParseNode(String contentType, Stream content)
>    at Microsoft.Kiota.Abstractions.Serialization.ParseNodeFactoryRegistry.GetRootParseNode(String contentType, Stream content)
>    at Microsoft.Graph.ResponseHandler`1.<ValidateSuccessfulResponse>d__3.MoveNext()
>    at Microsoft.Graph.ResponseHandler`1.<HandleResponseAsync>d__2`2.MoveNext()
>    at Microsoft.Graph.BatchResponseContent.<GetResponseByIdAsync>d__7`1.MoveNext()

If I try to upload my files without batching by using these samples:

- https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#upload-a-small-file-with-conflictbehavior-set
- https://learn.microsoft.com/en-us/graph/sdks/batch-requests?tabs=csharp#simple-batching-example

It works well.

Could you please help me pointing what I am doing wrong?

My config:
- Windows 10
- Solution WinUI 3 in .NET 6.0
- MS Graph 5.22.0

**Comment by andrueastman** [comment]
Thanks for raising this @eprach 

The error seems to suggest the response is not valid json. Hence the error thrown. 

Any chance you can try the following and check the value of the StatusCode and Headers collection?

```cs
var fileResponse = await returnedResponse.GetResponseByIdAsync(result);
Console.WriteLine(fileResponse.StatusCode);
foreach (var header in fileResponse.Headers)
{
    Console.WriteLine($"{header.Key}: {header.Value}");
}
```

**Comment by eprach** [comment]
Hi @andrueastman,

Thank you for your answer. Here is what I get:
StatusCode => "NotImplemented"

For headers, almost all are empties:
![Annotation 2023-08-22 153536](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/4587475/fc7e7461-937c-4010-9ba1-c942107a5fe8)
![Annotation 2023-08-22 153607](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/4587475/b551b3de-cf4b-47c5-9429-5cff335118e0)

**Comment by andrueastman** [comment]
I also get a similar response making the file upload using batch(SDK and graph explorer). With the message `"code":"notSupported","message":"Cannot upload content to an item representing a folder."`
<img width="544" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6464005/4b6b56f6-1c1a-4e15-b038-09f8cfe2a5d9">

As this looks to be an API side issue, any chance you could post the query at the link below for the API owners to get visibly if small file uploads via batch are supported? It would be great if you could post back a link to the same here incase anyone comes across this and finds it helpful. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by eprach** [comment]
Thanks for your investigation!

I have created a post as requested. It is available here: https://learn.microsoft.com/en-us/answers/questions/1351135/upload-small-files-to-sharepoint-online-using-batc

Let's see!

**Comment by andrueastman** [comment]
Thanks @eprach 

I'll close this issue for now so that it can be followed up there. Will re-open in case anything SDK related arises.
