### ISSUE TITLE
Internal Compiler Error ILT0005

### ISSUE THREAD

**Issue by LucaZiegler** [microsoftgraph/msgraph-sdk-dotnet#2096]
**Describe the bug**
When using the Microsoft.Graph library in Xamarin Forms an internal compiler error appears on UWP release build.

**To Reproduce**
1. Create a new Xamarin Forms Project (only) with UWP
2. Add for example the Microsoft.Graph NuGet package to the shared Xamarin Forms Project
3. Right click on the UWP project => Publish => Create App Packages
4. Select Sideloading => No, signing =>Select e.g. only x64 and Release (x64) => Click create
5. Then I got following output and error message:
```
Build started...
1>------ Build started: Project: XamarinFormsTest, Configuration: Release Any CPU ------
1>XamarinFormsTest -> C:\Users\lucaz\Source\Repos\LucaZiegler\XamarinFormsTest\XamarinFormsTest\XamarinFormsTest\bin\Release\netstandard2.0\XamarinFormsTest.dll
2>------ Build started: Project: XamarinFormsTest.UWP, Configuration: Release x64 ------
2>  XamarinFormsTest.UWP -> C:\Users\lucaz\Source\Repos\LucaZiegler\XamarinFormsTest\XamarinFormsTest\XamarinFormsTest.UWP\bin\x64\Release\XamarinFormsTest.UWP.exe
2>  Processing application code
2>  Computing application closure and generating interop code
2>    Loading 131 modules...
2>    Generating code...
2>    Interop code generated.
2>  Generating serialization code
2>  Compiling interop code
2>  Generating System.Reflection.DispatchProxy proxy code.
2>  Cleaning up unreferenced code
2>  Generating native code
2>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : Internal Compiler Error
2>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Users\lucaz\Source\Repos\LucaZiegler\XamarinFormsTest\XamarinFormsTest\XamarinFormsTest.UWP\obj\x64\Release\ilc\intermediate\MDIL\XamarinFormsTest.UWP.rsp"' returned exit code 1
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 12:15 and took 17:52,604 minutes ==========
========== Package: 0 succeeded, 1 failed ===========
```

**Expected behavior**
The build should succeed and a package for Microsoft Store distribution should be created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 & 11
 - Visual Studio: 17.6.5 (latest)

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @LucaZiegler  

Any chance you can confirm this work out for you once you update to the latest SDK version with the trimming changes? 
https://www.nuget.org/packages/Microsoft.Graph/5.32.0

**Comment by LucaZiegler** [comment]
> Thanks for raising this @LucaZiegler
> 
> Any chance you can confirm this work out for you once you update to the latest SDK version with the trimming changes? https://www.nuget.org/packages/Microsoft.Graph/5.32.0

Yes, it's now working
