### ISSUE TITLE
Planner Plan can't be deleted

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/msgraph-sdk-dotnet#2097]
**Describe the bug**
I have a Microsoft 365 E5 Sandbox Tenant where I am developing an app that uses the MsGraph C# SDK. When I use the SDK to delete a PlannerPlan, the SDK does not throw any Exception, but the Plans still apear in the UI of https://tasks.office.com/. I can't click them and when I try to issue another DELETE request with that ID, then I get a 404 back, so Graph seems to think the Plans are deleted. Is the Problem with my Code? Do I need to use an older version of the SDK or write a service that calls the REST Api myself? Am I going to flood my customer's Planner with undeletable plans if I continue with this approach?

**To Reproduce**
I thought it was my code that produced the error, so I reduced it as much as I could. If I run this sample, then the bug happens. 

My Sample App is based on this Microsoft Sample: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/tree/master/1-Call-MSGraph

It uses `Microsoft.Identity.Web.GraphServiceClient` in version 2.13.1, which uses `Microsoft.Graph` in version 5.12.0.

The GroupId is from a Microsoft 365 Group with just mysself as member in that E5 Sandbox Tenant:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/94550470/14211572-a9cd-449e-bfe3-e218dda50b67)

```cs
        public async static Task RecreateBug()
        {
            TokenAcquirerFactory tokenAcquirerFactory = TokenAcquirerFactory.GetDefaultInstance();
            IServiceCollection services = tokenAcquirerFactory.Services;
            services.AddMicrosoftGraph();
            var serviceProvider = tokenAcquirerFactory.Build();

            var graphServiceClient = serviceProvider.GetRequiredService<GraphServiceClient>();
            var AdGroupId = "your-ad-group-id-here";

            // Create the minimum required object to create a PlannerPlan
            var plan = new PlannerPlan
            {
                Container = new PlannerPlanContainer
                {
                    ContainerId = AdGroupId,
                    Type = PlannerContainerType.Group
                },
                Title = "Try and delete me!",
            };

            // Use POST to create the PlannerPlan
            var createdPlan = await graphServiceClient
                .Planner
                .Plans
                .PostAsync(plan, r => r.Options.WithAppOnly());

            // Use GET to get the PlannerPlan, so we can supply the latest "Etag" value to delete
            var retrievedPlan = await graphServiceClient
                .Planner
                .Plans[createdPlan.Id]
                .GetAsync(r => r.Options.WithAppOnly());

            // Use DELETE to delete the PlannerPlan
            await graphServiceClient
                .Planner
                .Plans[retrievedPlan.Id]
                .DeleteAsync(r => {
                    r.Options.WithAppOnly();
                    r.Headers.Add("If-Match", retrievedPlan.AdditionalData["@odata.etag"].ToString());
                });
        }
```

**Expected behavior**
The Plans should disappear from the UI at https://tasks.office.com/. In fact, this was still working fine 2 days ago. The problem started yesterday. 

**Screenshots**
When I try to click one of the supposedly deleted plans in the UI, it opens a spinner popup which cant be closed. only page reload helps.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/94550470/e5416184-fd75-427d-a5a4-e7477b61d350)

When I try to click one of the supposedly deleted plans and check the network tab in the dev tools I get a 404.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/94550470/68a5f0f7-c39e-4815-b830-f745db013dc8)

When I reload the page and check the network tab in the dev tools, I get a lot of 404's.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/94550470/2f28d3b5-7ffe-4cd9-833e-c2c646fee06e)

**Desktop (please complete the following information):**
 - Windows 10
 - Edge
 - Version 116.0.1938.54 (Official build) (64-bit)

**Additional context**
As you can see, I'm using the Client Credentials Flow for Daemon Apps.

**Comment by andrueastman** [comment]
Thanks for raising this @RobertAdesso,

Just to confirm, do the deleted plans eventually stop showing on `https://tasks.office.com/` or do they still show up despite getting 404 error when trying to query them on the API?

**Comment by RobertAdesso** [comment]
The plans are still showing despite getting 404s. They can't be opened either to delete them in the UI. I found the only way to delete the plans is to use the "Pin" icon in the list on the left. Then I get a popup that the plan doesnt exist anymore and it offers me to delete it.

**Comment by andrueastman** [comment]
@ghost Any chance if you can confirm if the api behaviour is still occurring?
