### ISSUE TITLE
Microsoft.Graph.ServiceException: Code: -1, Microsoft.SharePoint.Client.UnknownErrorMessage

### ISSUE THREAD

**Issue by asierpn** [microsoftgraph/msgraph-sdk-dotnet#210]
We have an issue since last week accessing sharepoint online using microsoft graph, the issue is reported [here](https://stackoverflow.com/questions/47179161/microsoft-graph-exception-code-1-starting-this-week) and seems that is happening to more people.

Please, this issue has broken an important feature of our app, who should repair this? should I open a support ticket to Microsoft directly?

Thanks,
Asier

**Comment by ificator** [comment]
Hi @asierpn, the issue described in the StackOverflow should now be resolved. Can you confirm you're no longer seeing it?

If you are still seeing it, can you provide the body of one of the failure response so we can get the `request-id` and `date`?

**Comment by asierpn** [comment]
Hello, I've tested this and now is working fine again, thanks!
