### ISSUE TITLE
Is there an API that can obtain whether a file is in an editing state (locked)?

### ISSUE THREAD

**Issue by tomzhang-byte** [microsoftgraph/msgraph-sdk-dotnet#2101]
A file is being edited by the user in Onedrive. If we update the content of this file through the Graph SDK, we will encounter the following error "The resource you are attempting to access is locked".
To avoid encountering such errors during updates, we would like to know the editing status of this file in advance. How can we obtain this status?

**Comment by andrueastman** [comment]
Thanks for raising this @tomzhang-byte 

As this is an API related question, and this repo is mainly intended for SDK related issues, any chance you can post the query below to get guidance from the API owners. IT would be great if you could post back a link to the same here so anyone who has a similar query may also be able to find it in future. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
