### ISSUE TITLE
Unable to upgrade my library past 5.16 due to Microsoft.Extensions.Logging.Abstractions breaking function apps.

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoftgraph/msgraph-sdk-dotnet#2102]
**Describe the bug**
I have had to downgrade MSGraph5 Library to 5.16 from 5.24 due to bug for function apps. Microsoft.Extensions.Logging.Abstractions is tied to this and cannot be higher than 6.0.4. MSGraph above 5.16 requires 7.0.1 which in turn breaks the function apps. This was done to keep the MSGraph5 library universal.

**To Reproduce**
Just make a function app with the latest version of MSGraph for .Net being used. (Currently 5.24) or just drop the version you are using for logging abstractions.

**Expected behavior**
Microsoft.Extensions.Logging.Abstractions should be staying in 6.0. Only .Net 7 should be using 7.0+??

**Comment by wrharper-AASP** [comment]
I want to make it clear that changing from isolated to in-process or visa-versa is "not" a solution.
As you can see here, they are quite different on how they are handled:
https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences

**Comment by andrueastman** [comment]
Thanks for raising this @wrharper-AASP,
Just to confirm, does the issue still occur with version 5.21.0? It should have the same dependencies as 5.16.0 as well.

Are you able share the error/logs you are getting when building? Unfortunately, `Microsoft.Extensions.Logging.Abstractions` isn't a direct dependency in our packages and the trace may help us identify which is to blame.

**Comment by wrharper-AASP** [comment]
I am double checking now; I'll get back to you. Maybe this isn't an issue with function apps anymore.

**Comment by wrharper-AASP** [comment]
NU1605: Warning As Error: Detected package downgrade: System.IdentityModel.Tokens.Jwt from 6.32.1 to 6.31.0. Reference the package directly from the project to select a different version. 
Microsoft.Graph 5.24.0 -> Microsoft.Graph.Core 3.0.10 -> Microsoft.IdentityModel.Protocols.OpenIdConnect 6.32.1 -> System.IdentityModel.Tokens.Jwt (>= 6.32.1) 
 MYPROJECT -> System.IdentityModel.Tokens.Jwt (>= 6.31.0)
Package restore failed. Rolling back package changes for 'MYPROJECT'.
Time Elapsed: 00:00:00.5008881
========== Finished ==========
Maybe it was JWT?

**Comment by wrharper-AASP** [comment]
I just upgraded the JWT to the minimum requirement and it worked. Whatever the problem was, I can't replicate it now.
