### ISSUE TITLE
The internet message header name 'List-Unsubscribe' should start with 'x-' or 'X-'.

### ISSUE THREAD

**Issue by FahaoTang** [microsoftgraph/msgraph-sdk-dotnet#2105]
**Describe the bug**
When sending email message using Graph API, an ODataError exception will throw out if List-Unsubscribe header is added:
"The internet message header name 'List-Unsubscribe' should start with 'x-' or 'X-'."

**To Reproduce**
1. Create a message with internet message header:
```
var emailMessage = new Message
{
    Subject = subject,
    Body = new ItemBody
    {
        ContentType = BodyType.Html,
        Content = body
    },
    InternetMessageHeaders = new List<InternetMessageHeader>
    {
        new InternetMessageHeader { Name = "List-Unsubscribe", Value = listUnsubscribe }
    }
};
```
2. Send the email using Graph API and the exception will show up.

**Expected behavior**
Email sent successfully without exception.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by reksc** [comment]
I'm having exactly the same issue as of now. 

> InvalidInternetMessageHeader: The internet message header name 'List-Unsubscribe' should start with 'x-' or 'X-'.
