### ISSUE TITLE
Unable to unzip the code folder

### ISSUE THREAD

**Issue by Nibor0101** [microsoftgraph/msgraph-sdk-dotnet#2109]
Not able to unzip the code folder.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/143792256/85992aef-0d64-4ddd-b2c2-1f5d2bdf4d85)

**Comment by WolfgangHG** [comment]
Isn't this the same issue that was recently added to Readme.md of this project - see end of page:

`Additionally for Windows OS, set the value of the parameter HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled to 1, before opening the solution in VS`

Don't know whether this helps when unzipping the zip file - I don't have this setting active....

When opening the source zip with WinZip, I see this error message about an invalid filename, followed by a lot of others:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/138049/29af830a-b540-4e80-9e29-a3500c17e70e)

**Comment by MartinM85** [comment]
> Isn't this the same issue that was recently added to Readme.md of this project - see end of page:
> 
> `Additionally for Windows OS, set the value of the parameter HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled to 1, before opening the solution in VS`

I have enabled long paths and can extract files from the zip archive.

**Comment by WolfgangHG** [comment]
Similar issue with the request to create shorter filenames: #2071
