### ISSUE TITLE
Update of ListItem Fields adds foregin "id" field to PATCH request

### ISSUE THREAD

**Issue by ordinaryorange** [microsoftgraph/msgraph-sdk-dotnet#211]
trying to update one of the fields on a sharepoint listitem. But as per [this post on SO](https://stackoverflow.com/questions/47306935/add-field-information-to-file-before-upload-to-sharepoint-via-microsoft-graph) I'm getting an error.
I did a bit more digging and had a look at the Patch request sent to the server (via Fiddler) and the JSON payload contains a foreign 'id' field in the dictionary. Likely explaining the error I'm getting.

**Comment by MIchaelMainer** [comment]
Mark's answer on SO is correct. UpdateAsync calls should take an object that contains only the fields that you want to update.

**Comment by ordinaryorange** [comment]
Tried that. Updated the SO post.
