### ISSUE TITLE
Execution remains ideal for so long while accessing GraphServiceClient

### ISSUE THREAD

**Issue by VigneashSelvaraj** [microsoftgraph/msgraph-sdk-dotnet#2112]
**Describe the bug**
Execution seems to ideal and unresponsive in my local code setup while I query from GraphServiceClient. Any guidance will be appreciated.

**To Reproduce**
1. NA

**Expected behavior**
Expected the code to query Azure Active directory and return users data.

**Screenshots**
NA

**Client version**
4.31.0.0

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: Microsoft Edge
 - Version: 10

**Additional context**
Execution seems to ideal and unresponsive in my local code setup while I query from GraphServiceClient. Any guidance will be appreciated.

private async Task<string> GetUserFullName(string objectIdentifier)
{
    try
    {
        string fullName = string.Empty;
        string[] scopes = { "https://graph.microsoft.com/.default" };

        ClientSecretCredential clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);

        GraphServiceClient graphServiceClient = new GraphServiceClient(clientSecretCredential, scopes);

        **var user = await graphServiceClient.Users[objectIdentifier].Request()
            .Select(u => new
            {
                u.GivenName,
                u.Surname,
                u.Mail
            })
            .GetAsync();**
        if (user != null)
        {
            fullName = user.GivenName + " " + user.Surname + "(" + user.Mail + ")";
        }
        return fullName;
    }
    catch (Exception ex)
    {
        return ex.Message;
    }
}

**Comment by andrueastman** [comment]
Thanks for raising this @VigneashSelvaraj,

Any chance you can confirm the issue still occurs if you update to [v4.54.0](https://www.nuget.org/packages/Microsoft.Graph/4.54.0)?

**Comment by VigneashSelvaraj** [comment]
Issue seems to remain in v4.54.0

**Comment by andrueastman** [comment]
@VigneashSelvaraj Any chance you can share a sample repro project to help us understand the issue better?

**Comment by VigneashSelvaraj** [comment]
This is not happening in a test dummy app, however still a problem with my production app. I switched to use Microsoft Graph REST API instead of the library. This request can be closed and thanks for the support

**Comment by VigneashSelvaraj** [comment]
closing
