### ISSUE TITLE
LifecycleTaskCategory enum is missing the Flags attribute

### ISSUE THREAD

**Issue by ErikdeWilde** [microsoftgraph/msgraph-sdk-dotnet#2113]
**Describe the bug**
The Microsoft.Graph.Models.IdentityGovernance.LifecycleTaskCategory is missing the Flags attribute, which causes the SDK to return only one of the possible catorgories of a TaskDefinition

This is the description from the taskdefinition page:

The category of the HR function that the tasks created using this definition can be used with. The possible values are: joiner, mover, leaver, unknownFutureValue. This is a multi-valued enumeration whose allowed combinations are joiner, joiner,leaver, or leaver

**To Reproduce**
1. Go to 'https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance-taskdefinition?view=graph-rest-1.0'
2. Go to 'https://graph.microsoft.com/v1.0/identityGovernance/lifecycleWorkflows/taskDefinitions'
3. The first result contains:
            "category": "joiner,leaver,mover",
            "description": "Add user to selected groups",
            "displayName": "Add user to groups",

When you do this call with the SDK you get a category of Mover

**Expected behavior**
I would expect the Microsoft.Graph.Models.IdentityGovernance.LifecycleTaskCategory & Microsoft.Graph.Beta.Models.IdentityGovernance.LifecycleTaskCategory enums to be decorated with the Flags attribute so all the possible values are deserialized

**Additional context**
This happens in both the V1 & Beta  5.x versions of the SDK

**Comment by andrueastman** [comment]
Thanks for raising this @ErikdeWilde 

This should be fixed/available in the next service library release in the course of the week after the generator fix at https://github.com/microsoft/kiota/pull/3240
