### ISSUE TITLE
Update HideFromAddressLists, AllowExternalSenders, HideFromOutlookClients for Group

### ISSUE THREAD

**Issue by idealser** [microsoftgraph/msgraph-sdk-dotnet#2117]
How can I update one of these properties: HideFromAddressLists, AllowExternalSenders, HideFromOutlookClients? 
By docs I should be able to do it if I only specify them for the PATCH request. Works from REST API but using Graph SDK I always get a 403 error. 
**Group.ReadWrite.All** and **Directory.ReadWrite.All** permissions are granted.

 Is there something missing?

```csharp
var req = new Group
{
  AllowExternalSenders = false,
  HideFromAddressLists = false,
  HideFromOutlookClients = false,
};
await GraphClient.Groups[groupId].PatchAsync(req);
```

**Comment by andrueastman** [comment]
Thanks for raising this @idealser,

Any chance you can confirm whether you are using the same authentication mechanism for both scenarios? Is it app permissions or delegate permissions? 

Any chance you can graph the token from the SDK and paste it from JWT.ms to confirm if the right scopes are present?

```cs
var requestInformation = GraphClient.Groups["groupId"].ToPatchRequestInformation(req);
var httpRequestMessage = await GraphClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(requestInformation);
var authHeader = httpRequestMessage.Headers.Authorization.Parameter;
```

**Comment by idealser** [comment]
It's app permission on SDK. Just to clarify: a simple group update request works, unless I change any of above mentioned properties.

```json
{
...
 "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/ea111e75-d0dd-46c6-bab8-6895ec798378/",
  "iat": 1693991508,
  "nbf": 1693991508,
  "exp": 1693995408,
  "aio": "E2FgYPiy/EKDo7j9xYPecU0rJ+3jBAA=",
  "idp": "https://sts.windows.net/ea111e75-d0dd-46c6-bab8-6895ec798378/",
  "idtyp": "app",
  "oid": "de038e24-f874-42d1-b237-2618be40b672",
  "rh": "0.AXoAdR4R6t3Qxka6uGiV7HmDeAMAAAAAAAAAwAAAAAAAAAB6AAA.",
  "roles": [
    "TeamSettings.ReadWrite.All",
    "TeamMember.Read.All",
    "Channel.Delete.All",
    "User.ReadWrite.All",
    "SharePointTenantSettings.Read.All",
    "ChannelSettings.Read.All",
    "Channel.ReadBasic.All",
    "Group.Read.All",
    "Directory.ReadWrite.All",
    "Team.Create",
    "Group.Create",
    "Group.ReadWrite.All",
    "Directory.Read.All",
    "User.Read.All",
    "ChannelMember.Read.All",
    "GroupMember.Read.All",
    "TeamMember.ReadWrite.All",
    "TeamSettings.Read.All",
    "Organization.Read.All",
    "ChannelMember.ReadWrite.All",
    "GroupMember.ReadWrite.All",
    "ChannelSettings.ReadWrite.All",
    "Channel.Create",
    "Policy.Read.All",
    "Reports.Read.All"
  ]
}
```

**Comment by andrueastman** [comment]
Thanks for confirming @idealser 

Are you able to share the details of the 403 error(code, message, request id) when making the update following the guidance below? 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

**Comment by idealser** [comment]
Sure:
```
ODataError: User does not have permissions to execute this action.
Code: 403
Description: Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Groups.Item.GroupItemRequestBuilder.PatchAsync(Group body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

**Comment by andrueastman** [comment]
According to the documentation this could be case at the moment.

https://learn.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6464005/74833c61-5f7d-4454-a829-7520cfc321cc)

As this is an API feature request, any chance you can raise a feature request at the link below so that API owners may look into this? https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by idealser** [comment]
Probably is it the case. I've added a feedback request. Guess we could close this issue for now.
