### ISSUE TITLE
Incorrect request URL when retrieving site's drives

### ISSUE THREAD

**Issue by IlyaBezus** [microsoftgraph/msgraph-sdk-dotnet#212]
When I try to retrieve site's existing drives like this:
` var drivesCollectionPage = await graphClient.Sites.GetByPath(uri.PathAndQuery, uri.Host).Drives.Request().GetAsync();`

Request URL is `https://graph.microsoft.com:443/v1.0/sites/domain.sharepoint.com:/sites/testsite/drives`,
while the correct URL is `https://graph.microsoft.com:443/v1.0/sites/domain.sharepoint.com:/sites/testsite:/drives`
Missing colon after GetByPath method leads to request error.

However, calling request this way:
` var drivesCollectionPage = await graphClient.Sites.GetByPath(uri.PathAndQuery + ":", uri.Host).Drives.Request().GetAsync();`
fixes the error.

**Comment by MIchaelMainer** [comment]
Thank you for letting us know about this issue.

**Comment by StewartNutter1** [comment]
Additionally, the library does not support "Sites/Root". If I hand craft the request, or do it through the Explorer, it works. I tried "Sites.Top(1)" and got the same request error. If I use the Id returned from my direct call to the endpoint then "Sites[Id]" works as expected.

**Comment by MIchaelMainer** [comment]
@StewartNutter1 I opened a separate issue for tracking this. #258
