### ISSUE TITLE
V5: Patch on User uses Intune API instead of Users api

### ISSUE THREAD

**Issue by jjasloot** [microsoftgraph/msgraph-sdk-dotnet#2122]
**Describe the bug**
In my code I want to update a user's mobile phone number. For that I call PatchAsync on my user object as such:
`await _graphServiceClient.Users[adObjectId].PatchAsync(new User { MobilePhone = phoneNumber });`
This call returns an "Authorization_RequestDenied" error, "Insufficient privileges to complete the operation." Before update to v5 this call worked with my current setup. My application has the User.ReadWrite.All permission with admin consent.

The issue seems to be that this call uses this api: https://learn.microsoft.com/en-us/graph/api/intune-onboarding-user-update?view=graph-rest-1.0&tabs=http as opposed to this api: https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http.

**To Reproduce**
1. Create an application with the User.ReadWrite.All permission with admin consent.
2. Install Microsoft.Graph 5.26.0
3. Create a GraphServiceClient (using a client id and secret)
4. Attempt to update a user, for example using `await _graphServiceClient.Users[adObjectId].PatchAsync(new User { MobilePhone = phoneNumber });`

**Expected behavior**
I expect that the Patch operation uses the user-update api. I expect that when the intune-onboarding-user api is used the name of the operation also notes that the intune api is used.

**Additional context**
At this moment I'm unsure if this is only an SDK problem, or also a general Microsoft Graph problem. The URL for the user-update api is `PATCH /users/{usersId}` whereas the url for the intune-onboarding-user api is `PATCH /users/{id | userPrincipalName}`. Because these are the same once a userId has been filled conflicts could arise

**Comment by andrueastman** [comment]
Thanks for raising this @jjasloot 

As `mobilePhones` is classified as a sensitive property, any chance you can confirm that the app/user making the update meets the conditions specified in the note in the documentation?
https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#permissions

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6464005/bb8d310e-8f33-4cfe-99e6-ae0375eef684)

**Comment by jjasloot** [comment]
Hey @andrueastman, thank you for looking into my issue. 

I just checked again and the accounts I was testing with were, outside of my knowledge, all priviliged accounts. Testing with a fresh unpriviliged account works totally as intended. 

As a small point of improvement, my confusion was further increased by this help text on the PatchAsync method
![afbeelding](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/5612709/4a76217d-1127-41c6-80d8-ce08017f3ec3)
It explicitly mentioned the intune api, hence part of my confusion.

I'm sorry for the incorrect issue, I should have checked better. Once again thank you.
