### ISSUE TITLE
Groups["groupid"].Members is not returning all the details of the members.

### ISSUE THREAD

**Issue by RupenAnjaria** [microsoftgraph/msgraph-sdk-dotnet#2128]
**Describe the bug**
As per online documentation available [here ](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=csharp) the call for Groups[groupId].Members isn't returning selected user details (e.g. displayName, givenName etc. The response brings accurate items (if a group have 2 members then it will return two object) however, it just returns their IDs, while keeping other details hidden.

**To Reproduce (Assuming app registration part and permission setup is done)**
Create team and assign a member
Use Groups[groupId].Members.GetAsync to fetch all the details of members.

**Expected behavior**
This should bring all the details

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/17281745/f6284292-7d7e-40cf-914a-499956bf4318)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Using Postman to test API, see the code below:
 
` _clientSecretCredential = new ClientSecretCredential(tenantId, Helper.Tenant.Get(tenantId).ClientID, Helper.Tenant.Get(tenantId).ClientSecret);

_appClient = new GraphServiceClient(_clientSecretCredential,
                                  new[] { "https://graph.microsoft.com/.default" });

                return await _appClient.Groups[groupId].Members.GetAsync();
`

I tried https://developer.microsoft.com/en-us/graph/graph-explorer and it returns full properties.
I also checked the permissions:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/17281745/8a0fad27-9f94-4754-ac0a-e5b370149d42)

**Comment by andrueastman** [comment]
Thanks for raising this @RupenAnjaria,

Any chance you know the specific properties you wish to view? Do you get different results if you specify them in the query parameter as below?

```cs
var result = await graphClient.Groups["{group-id}"].Members.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Select = new string []{ "displayName","id","mail" };
});
```

**Comment by RupenAnjaria** [comment]
I wish to get givenName, surname, id and mail. I tried the snippet provided, but still the result is same.

**Comment by Pablo-Lopez-Ponce** [comment]
I was trying to do the same and ended up doing this, which sucks, but at least works:

```
var members = await graphClient.Groups[GroupId.ToString()].Members.GetAsync();
var allMembers = new List<DirectoryObject>();
var pageIterator = PageIterator<DirectoryObject,DirectoryObjectCollectionResponse>.CreatePageIterator(graphClient,members!, (user) => {
                allMembers.Add(user);
                return true; });
await pageIterator.IterateAsync();
var query = string.Join(separator: ',', allMembers.Select(obj => $"'{obj.Id}'"));
var users = await graphClient.Users.GetAsync(rc =>
     {
         rc.QueryParameters.Filter = $"id in ({query})";
         rc.QueryParameters.Select = new[]
         {
             "id", "displayName", "mail", "surname", "givenName", "externalUserState"
         };

     });
```

**Comment by RupenAnjaria** [comment]
Please see this for an easy way: https://stackoverflow.com/questions/77084567/groupsgroupid-members-is-not-returning-all-the-details-of-the-members
