### ISSUE TITLE
Graph API requesting user mailbox settings return "The process failed to get the correct properties."

### ISSUE THREAD

**Issue by xpandax76** [microsoftgraph/msgraph-sdk-dotnet#2141]
Hi,
**Describe the bug**
I am currently using graph api to query for user's mailbox settings. It is working for most users, however for some users, graph api returns 403 HTTP status with the response "The process failed to get the correct properties."

The request that is sent is: https://graph.microsoft.com/v1.0/users/[user-id]/mailboxSettings
The request is sent with an application with permission MailboxSettings.Read and the application was able to get some other user's mailbox settings so I don't think this is a permission issue even though the response return a 403 status code

**Expected behavior**
User's mailbox settings is returned

Thank you!

**Comment by andrueastman** [comment]
Thanks for raising this @xpandax76 

Any chance you can confirm whether you have application or delegated permissions on your app? Does any of the answers at the link below help out?
https://stackoverflow.com/questions/54767695/error-access-denied-on-mailboxsettings-for-users

**Comment by MartinM85** [comment]
Is the user a member or a guest? Is it a regular user or shared calendar, room, equipment, etc.?

Also check (probably your admin) if there are any restrictions on the mailboxes. Admin can [limit application permissions](https://learn.microsoft.com/en-us/graph/auth-limit-mailbox-access) to specific mailboxes, but in that case I would expect different error message (**Access to OData is disabled.**)

**Comment by elvanguyen** [comment]
sorry for the late reponse
@andrueastman the app has the correct app permission as it was able to pull mailbox settings for other users.
@MartinM85 the user run into the issue seem to be either a service account for shared mailbox or a disabled user.
However, my ap was able to get mailbox settings for other shared mailbox service account as well
