### ISSUE TITLE
Get MIME message with .content.GetAsync() no more working since 5.25

### ISSUE THREAD

**Issue by BartRennes** [microsoftgraph/msgraph-sdk-dotnet#2144]
Dear, 

Since updated to version 5.25 (and latest 5.28), the solution to get MIME message with **.Content.GetAsync()** is no more working, it is a real breaking change. Is there a workaround to get a message in MIME format?

Here the code with graph 5.15 (and previous):
var _responseStream = await m_graphClient.Users[Me].Messages[XXXX].Content.GetAsync();

With graph 5.15 it returns a stream with MIME message, that's perfect, but the error with 5.25 and latest is:
'((System.Net.Http.HttpBaseStream)_responseStream).Length' a levé une exception de type 'System.NotSupportedException'

Impossible to get the message in MIME format!

Regards,
jean

**Comment by MartinM85** [comment]
Could you please share the code how do you process the `_responseStream`

the simple code works fine for version > 5.25
```
var res = await graphServiceClient.Me.Messages["{message-id}"].Content.GetAsync();
var data = new StreamReader(res).ReadToEnd();
```

**Comment by BartRennes** [comment]
Ohh thank you, it works, , my code which was working with 5.15:

var res = await graphServiceClient.Me.Messages["{message-id}"].Content.GetAsync();
var _msgArray2 = ToByteArray(res);


      private static Byte[] ToByteArray(System.IO.Stream stream)
      {
          Int32 length = stream.Length > Int32.MaxValue ? Int32.MaxValue : Convert.ToInt32(stream.Length);
          Byte[] buffer = new Byte[length];
          stream.Read(buffer, 0, length);
          return buffer;
      }
