### ISSUE TITLE
Authentication fails when accessing site's drives

### ISSUE THREAD

**Issue by IlyaBezus** [microsoftgraph/msgraph-sdk-dotnet#215]
Hi. Today i have noticed Graph service issue - about a week ago request
`https://graph.microsoft.com/v1.0/sites/myorg.sharepoint.com:/sites/testsite:/drives`
returned me whole list of drives. I believe, something has been changed recently. Same request (even through Graph Explorer) returns an error:
`{
    "error": {
        "code": "unauthenticated",
        "message": "Access denied. You do not have permission to perform this action or access this resource.",
        "innerError": {
            "request-id": "7a0f1a4a-eb8e-427b-8e76-cb44ce4ae661",
            "date": "2017-11-24T13:59:40"
        }
    }
}`

None of my permissions were changed (I have access to Sites.ReadWrite.All, Files.ReadWrite.All and many more), even admin can't access this through Graph explorer, while being authorized. Every other operation with any drive by its ID works fine. Could this be a service bug?

**Comment by MIchaelMainer** [comment]
Does GET https://graph.microsoft.com/v1.0/sites/myorg.sharepoint.com work?

**Comment by IlyaBezus** [comment]
Yeah, it returns site's info with code 200.

**Comment by ificator** [comment]
Hi @IlyaBezus, this should hopefully be resolved now. We made a change to how document libraries were being detected and returned for the `/drives` enumeration, but it introduced some unexpected permission issues. That change has now been reverted.

**Comment by IlyaBezus** [comment]
Yes, this works now. Thanks a lot :)
