### ISSUE TITLE
Permissions Error? Can no longer get SharePoint Files after new APP Registration - 404 error

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoftgraph/msgraph-sdk-dotnet#2157]
For some reason I get a 404 even though everything checks out. I even over did it on the permissions:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/117128832/ddba15e7-dc87-4220-83e4-9735f27d7588)
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/117128832/863a2995-06c6-4472-87a9-1bc2dae79f46)

```
string path = "https://graph.microsoft.com/v1.0/users/" + userid + "/drive/items/root:/" + directory + ":/children";
//i can copy and paste the path and it works in ms graph explorer, it's not the path.....

HttpClient client = new();
client.DefaultRequestHeaders.Authorization = new("Bearer", oauthv2token); //tested token and it is valid, not the token...
SharePointFiles spf = await client.GetFromJsonAsync<SharePointFiles>(path); //even string comes back 404...not a JSON issue
```

I'm not seeing what could be missing?
Error:
[2023-10-11T04:52:41.980Z] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
[2023-10-11T04:52:41.980Z]    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
[2023-10-11T04:52:41.981Z]    at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
[2023-10-11T04:52:41.982Z]    at GetFiles(String userid, ILogger log) in C:\Users\USERID\source\repos\PROJECT.cs:line 175
which points to the path above when doing client.GETANYTHING(path);

**Comment by wrharper-AASP** [comment]
How i get the OAUTH:

```
                var data = new[]
                {
                    new KeyValuePair<string, string>("grant_type", "client_credentials"),
                    new KeyValuePair<string, string>("client_id", clientid),
                    new KeyValuePair<string, string>("scope", graphScope),
                    new KeyValuePair<string, string>("redirect_url", "https://login.microsoftonline.com/common/oauth2/nativeclient"),
                    new KeyValuePair<string, string>("client_secret", secret)
                };
FormUrlEncodedContent formurl = new(data);
```

**Comment by andrueastman** [comment]
Thanks for raising this @wrharper-AASP,

From the screenshot, the  `Files.Read.All, Files.ReadWrite.All` permissions are delegated permissions whereas the token is being acquired using a client secret. This means that the needed permissions should be Application permisions as the token is not tied to a user identity(which is the case when using the Graph Explorer).
Any chance you can confirm the right permissions are in the token by pasting the token at https://jwt.ms/ and confirming the scp property is as expected?

**Comment by wrharper-AASP** [comment]
This is what it was, thanks....
