### ISSUE TITLE
Cant use Skiptoken as a query parameter in TransitiveMembers

### ISSUE THREAD

**Issue by CardinPatson** [microsoftgraph/msgraph-sdk-dotnet#2158]
**Describe the bug**

I cant use Skiptoken as a query parameter when i try to get group member with transitivemembers. Does anyone have already use Skiptoken as a query parameters ?

**Expected behavior**
Accept the Skiptoken as QueryParameters

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/74672498/1fbb5e0d-7a05-4ea3-b1e0-aa0ed399c9b1)

**Client version**
5.29.0

**Desktop (please complete the following information):**
 - OS: Window 11
 - Version 22

**Comment by andrueastman** [comment]
Thanks for raising this @CardinPatson 

There is guidance on the same in the upgrade guide at the link below as how the entire url can be used. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests

There is an alternative as well to use the `WithUrl` request builder as well. 

```cs
var nextLinkUrl = "https://graph.microsoft.com/v1.0/"; //nextLink url from previous repsonse
var transitiveMembersResponse = await graphClient.Groups["{group-id}"].TransitiveMembers.WithUrl(nextLinkUrl).GetAsync();
```

**Comment by CardinPatson** [comment]
Thanks for the alternative andrueastman, it works perfectly with `withUrl`, so im going to close this issue
