### ISSUE TITLE
[Client bug]: provide a descriptive title here

### ISSUE THREAD

**Issue by RWSchwabXXX** [microsoftgraph/msgraph-sdk-dotnet#2162]
.net MAUI app with the Microsoft.Graph Nuget package fails on build in release configuration when targeting the Android platform.  The app compiles and runs successfully in the Debug configuration.

**To Reproduce**
Download the MAUI MSGraph example app https://github.com/microsoftgraph/msgraph-sample-maui/tree/main/
target Release build for the Android target.

**Expected behavior**
build fails with:
Precompiling failed for C:\Users\rws\Downloads\msgraph-sample-maui-main\msgraph-sample-maui-main\GraphMAUI\obj\Release\net7.0-android\android-x64\linked\Microsoft.Graph.dll with exit code -1073740791.	

Expected behavior is to successfully archive the app bundle for publishing.

**Client version**
5.30.0

**Desktop (please complete the following information):**
 - OS: Android

**Additional context**
I've reproduced this on multiple MAUI projects - in every case, once I add the Graph nuget package the application fails the release build - but they successfully build in debug mode.

**Comment by andrueastman** [comment]
Thanks for raising this @RWSchwabXXX 

Any chance you can confirm this work out for you once you update to the latest SDK version with the trimming changes? 
https://www.nuget.org/packages/Microsoft.Graph/5.32.0

**Comment by RWSchwabXXX** [comment]
Working!  Thanks, that fixed the problem!!

**Comment by andrueastman** [comment]
Thanks for confirming @RWSchwabXXX
