### ISSUE TITLE
500 Internal server error when creating GDAP relationship in Sandbox environment

### ISSUE THREAD

**Issue by OliverFrancis123** [microsoftgraph/msgraph-sdk-dotnet#2167]
**Describe the bug**
Microsoft.Graph.Models.ODataErrors.ODataError error when trying to create a GDAP relationship in the partner center integreation sandbox using a App Reg with the following permissions
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/107112244/7a86be84-5e8d-4170-966b-5fb6a1ed443b)

**To Reproduce**
Using the following code an error is thrown in the sandbox environment but works with the exact same permissions in the production environment
```
using Azure.Identity;
using Microsoft.Graph;
using Microsoft.Graph.Models;

namespace gdapconsoleapp
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var scopes = new[] { "https://graph.microsoft.com/.default" };
            //var clientId = "-----";
            //var tenantId = "-----";
            //var clientSecret = "-----";
            //var targetTenant = "-----";
            //var targetDisplayName = "-----";

            // using Azure.Identity;
            var options = new ClientSecretCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
            };

            var clientSecretCredential = new ClientSecretCredential(
                tenantId, clientId, clientSecret, options);

            var graphClient = new GraphServiceClient(clientSecretCredential, scopes);

            var displayName = $"NC-OTF-{Guid.NewGuid()}";

            var requestBody = new DelegatedAdminRelationship
            {
                DisplayName = displayName,
                Duration = TimeSpan.FromDays(730),
                Customer = new DelegatedAdminRelationshipCustomerParticipant
                {
                    TenantId = targetTenant,
                    DisplayName = targetDisplayName,
                },
                AccessDetails = new DelegatedAdminAccessDetails
                {
                    UnifiedRoles = new List<UnifiedRole>
                    {
                        new UnifiedRole
                        {
                            RoleDefinitionId = "29232cdf-9323-42fd-ade2-1d097af3e4de",
                        },
                        new UnifiedRole
                        {
                            RoleDefinitionId = "3a2c62db-5318-420d-8d74-23affee5d9d5",
                        },
                    },
                },
            };

            try
            {
                var createResult = await graphClient.TenantRelationships.DelegatedAdminRelationships.PostAsync(requestBody);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw;
            }
        }
    }
}
```

**Expected behavior**
a GDAP relationship is created and "createResult" is a Microsoft.Graph.Models.DelegatedAdminRelationship

**Additional context**
using Microsoft.Graph 5.30.0

Similar error in postman, and again the same postman request works in the production environment
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/107112244/240ac712-d9ae-4ec9-9d65-922f935e4e72)

**Comment by andrueastman** [comment]
Thanks for raising this @OliverFrancis123 

Any chance you can confirm if the tokens acquired for the two scenarios are the same and are being used for the same tenant?

**Comment by OliverFrancis123** [comment]
These are different tenants with different service principals and tokens but identical permissions.

The sandbox environment is the Partner Center Integration Sandbox

**Comment by andrueastman** [comment]
@OliverFrancis123 Any chance you can capture a fresh client-request-id and timestamp (as in the previous screenshot) so that we may try to follow up the error with the API team?
