### ISSUE TITLE
Delta CalenderView API generalException error with the message "Unexpected exception returned from the service"

### ISSUE THREAD

**Issue by raedaltaki** [microsoftgraph/msgraph-sdk-dotnet#2169]
Many users are getting the generalException error with the message "Unexpected exception returned from the service" and HTTP status "ServiceUnavailable" when doing the delta CalenderView API request. then after a few days, the error resolves itself for these users and it starts throwing for different users.

**To Reproduce**
Unable to reproduce it. It just throws randomly and it solves itself after a few days

**Expected behavior**
the delta calenderView API request works for all users

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/74080682/bcee7da0-4e92-4826-b647-b55be92e1bda)

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @raedaltaki 

The 503 response is a transient error that may be returned by the API in some situations and should be handled according to the guidance [here](https://learn.microsoft.com/en-us/graph/best-practices-concept#handling-expected-errors). 

From the feature flags in your trace it looks like the client has not enabled the `RetryHandler` that is used by the SDK to handle 503 responses from the API. Any chance you can confirm how you are initializing the client when making requests or do you have a custom retry mechanism?

**Comment by raedaltaki** [comment]
We have a custom retry mechanism that handles this error by doing 3 retries when the "Service unavailable error" is thrown and waiting 5 seconds between retries. This didn't fix the issue.  

Also, we tried adding the retry-after header to the API call and still have the same error.

This error happens randomly to different users and it fixes itself after some time (it can last for days)

**Comment by andrueastman** [comment]
@raedaltaki Any chance you can try adding the retry-handler from the SDK to your middleware pipeline to see if there is any difference in the resilience here? 

As this also sounds to be an API side issue due to service availability, any chance you can also follow up with support to create a service request to confirm if the API issue can be followed up? 

https://developer.microsoft.com/en-us/graph/support

**Comment by raedaltaki** [comment]
@andrueastman, I've opened a technical support ticket for this issue as you mentioned it sounds to be an API issue.

Also, I tried to add the retry-after in the header of the API requests but it didn't help.

**Comment by andrueastman** [comment]
Thanks for this @raedaltaki. We'll close this for now. 

Feel free to re-open/create a new issue in the event anything SDK related arises.
