### ISSUE TITLE
Working with sessions of Excel

### ISSUE THREAD

**Issue by DDAndyChen** [microsoftgraph/msgraph-sdk-dotnet#217]
I've been trying to open and close an Excel session with the SDK, I got an exception using one of the methods.

* IWorkbookRequestBuilder.CreateSession(bool persistChanges);
This method works as expected.

* IWorkbookCloseSessionRequestBuilder.CloseSession();
This method create a post request without the *workbook-session-id* header, which is not correct according to [this](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/workbook_closesession)
The error was:
`{
  "error": {
    "code": "UnknownError",
    "message": "Bad Request",
    "innerError": {
      "request-id": "73c3cd35-2c08-42c1-8d20-3b2040adb791",
      "date": "2017-11-29T03:02:54"
    }
  }
}
`

* Question is how to set header to a API call with the SDK? So that we can set *workbook-session-id* in order to work with Excel sessions.

**Comment by MIchaelMainer** [comment]
Take a look at some of these [functional tests](https://github.com/microsoftgraph/msgraph-sdk-dotnet/tree/dev/tests/Microsoft.Graph.Test/Requests/Functional). Here's an example of [adding a header](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.Test/Requests/Functional/OneDriveTests.cs#L269).
