### ISSUE TITLE
GET /places/graph.roomList fails, /places/microsoft.graph.roomList works

### ISSUE THREAD

**Issue by YouriT** [microsoftgraph/msgraph-sdk-dotnet#2170]
Seems like the endpoint construction of [this endpoint](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/bbee11fc36704691e21949b0e3f1b2d8e89a7263/src/Microsoft.Graph/Generated/Places/GraphRoomList/GraphRoomListRequestBuilder.cs#L27) is somewhat wrong.

When using the graph explorer, I properly get results for `/v1.0/places/microsoft.graph.roomlist` and an `UnknownError` for `/v1.0/places/graph.roomlist`

**Comment by YouriT** [comment]
Nevermind, it seems the endpoint is case sensitive and that GET `graph.roomList` works just fine

**Comment by andrueastman** [comment]
Thanks for raising this @YouriT 

Any chance you can confirm that the error is reproducible with the SDK as the casing looks correct from the link you shared? 
In the event there is a documentation issue, you can create an issue on [this repo](https://github.com/microsoftgraph/microsoft-graph-docs-contrib) and in the event there is an API related question, you can raise it at this link. 
https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
