### ISSUE TITLE
"Error getting value from 'ReadTimeout'" when adding DriveItem

### ISSUE THREAD

**Issue by NSouth** [microsoftgraph/msgraph-sdk-dotnet#218]
Hey, hopefully I'm just missing something simple, but I am getting an error when trying to create a DriveItem including a content stream.  Below is an example using a simple MemoryStream as the content source, for simplicity. 

```
GraphServiceClient graphClient = GraphSDKHelper.GetAuthenticatedClient();
using (var docStream = new MemoryStream(1024))
{   
   var doc = new DriveItem
   {
        Content = docStream,
        Name = "00_newDoc.docx",
        ParentReference = new ItemReference
        {
            Id = "<folderId"
        }
    };
    // Error occurs at CreateAsync()
    var resultItem = await graphClient.Drives["<driveId>"].Items["<folderId>"].Request().CreateAsync(driveItem);
}
```
I can upload the file content directly with the following, but I then lose the ability to specify more metadata in the DriveItem in a single call. 
`var resultItem = await graphClient.Drives["<driveId>"].Items["<folderId>"].ItemWithPath("00_newDoc.docx").content.Request().PutAsync<DriveItem(docStream);`

I have posted this [on StackOverflow as well](https://stackoverflow.com/q/47539979/3165621), but have not received an answer. 

Error: 

> Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'.
> at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty) at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType) at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer) at Microsoft.Graph.Serializer.SerializeObject(Object serializeableObject) at Microsoft.Graph.BaseRequest.d__36.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Graph.BaseRequest.d__321.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at
>   Microsoft.Graph.DriveItemRequest.<CreateAsync>d__2.MoveNext()
>   --- End of stack trace from previous location where exception was thrown ---    at
>   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
>   task)    at
>   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
>   task)    at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Informa.eDocs.AzureFunctions.Functions.PostDocToSharePoint.d__0.MoveNext()

Inner Exception:

> Timeouts are not supported on this stream. at System.IO.Stream.get_ReadTimeout() at GetReadTimeout(Object ) at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)

**Comment by MIchaelMainer** [comment]
The API is not intended to be used this way. I don't know the reason why it can't be done in a single call. I do know that you must first create the item with a [POST][1] (example shows a folder, but the idea is the same for a file), and then [PUT][2] the content stream in a subsequent call. 


  [1]: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_post_children
  [2]: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_put_content
