### ISSUE TITLE
[Client bug]: DriveRequestBuilder in V5 client is missing Root property.

### ISSUE THREAD

**Issue by adamijak** [microsoftgraph/msgraph-sdk-dotnet#2184]
**Describe the bug**
DriveRequestBuilder is missing Root property despite it is documented in README.md and [here](https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=csharp)

**Screenshots**

README.md
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/24510461/04c0915b-e8a1-4f58-ac89-c4d0db1c3410)

Code
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/24510461/b29d8e8e-41d0-47f7-aac3-87e791872038)

**Client version**
5.32.0

**Additional context**
Probably caused by this issue: microsoftgraph/msgraph-metadata#477

**Comment by andrueastman** [comment]
Thanks for raising this @adamijak 

The missing root path is documented in the upgrade guide at the link below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths

We will also correct the readme to capture this and close this.
