### ISSUE TITLE
How to choose to send/not send attachments when forwarding a mail

### ISSUE THREAD

**Issue by suryaraj1** [microsoftgraph/msgraph-sdk-dotnet#2185]
## Issue :thinking:  ##
Right now <a target="__blank" href="https://learn.microsoft.com/en-us/graph/api/message-forward?view=graph-rest-1.0">Forward</a> does not have a lot of flexibility rather than just adding a comment I guess. 
<br />
My use case involves creating a flag which when set would let me include attachments in the mail being forwarded. I have seen  **CreateForward** which is understandably more flexible, but still am failing to figure out how to remove the attachments from the draft forward mail. :thinking: 
Is there any API which allows me to do so? Or would I have to strictly delete attachments individually for the specific mail which I want to forward?

**Comment by MartinM85** [comment]
It requires more steps:

1. Create draft for forward

Specify either `comment` and `toRecipients` properties or `message` property

```
var requestBody = new Microsoft.Graph.Me.Messages.Item.CreateForward.CreateForwardPostRequestBody
{
	Message = new Message
	{
		Body = new ItemBody
		{
			ContentType = BodyType.Html,
			Content = "<text>",
		},
		ToRecipients = new List<Recipient>
		{
			new Recipient
			{
				EmailAddress = new EmailAddress
				{
					Address = "john.doe@contoso.com",
				},
			},
		}
	},
};
var result = await graphClient.Me.Messages["{message-id}"].CreateForward.PostAsync(requestBody);
```

2. Use message id of the draft to delete attachments

`await graphClient.Me.Messages["{forward-draft-message-id}"].Attachments["{attachment-id}"].DeleteAsync();`

3. Send the draft

`await graphClient.Me.Messages["{forward-draft-message-id}"].Send.PostAsync();`

**Comment by suryaraj1** [comment]
Thanks @MartinM85 for the answer! :rocket: Just have another question, why not use `forward` to finally send the draft mail we created, if my intention is to also add a comment to this mail? Would both the operations result in the same output?

**Comment by andrueastman** [comment]
I believe using `forward` involves sending an existing message in one operation. 
Whereas in this situation we are creating a forward draft mail which is sent by using the [send operation](https://learn.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http). 

If your intention is to add a comment you can still modify the suggestion by @MartinM85 to add a comment rather than create a message which should ideally have the same result as using `forward`. 

```cs
         var requestBody = new Microsoft.Graph.Me.Messages.Item.CreateForward.CreateForwardPostRequestBody
         {
             Comment = "Here's the email you asked for.",
             ToRecipients = new List<Recipient>()
             {
                 new Recipient()
                 {
                     EmailAddress = new EmailAddress()
                     {
                         Address = "john.doe@contoso.com"
                     }
                 }
             }
         };
         var result = await graphClient.Me.Messages["{message-id}"].CreateForward.PostAsync(requestBody);
```

**Comment by suryaraj1** [comment]
Thanks a lot! :smile: This does help me solve my issue. Can close this now.

**Comment by suryaraj1** [comment]
Thanks a lot! :smile: This does help me solve my issue. Can close this now.
