### ISSUE TITLE
[Client bug]: ODataError due to missing @odata.type

### ISSUE THREAD

**Issue by RytisLT** [microsoftgraph/msgraph-sdk-dotnet#2187]
I'm using following code to patch `OmaSettingStringXml`

```C#
var creds = new ClientSecretCredential(_config.TenantId, _config.ClientId, _config.ClientSecret);
var httpClient = GraphClientFactory.Create();
var client = new GraphServiceClient(httpClient, creds, new[] { "https://graph.microsoft.com/.default" });
var cfgReq = client.DeviceManagement.DeviceConfigurations[_config.DeviceConfigurationId];
var item = (Windows10CustomConfiguration)(await cfgReq.GetAsync())!;
var setting = item.OmaSettings?.OfType<OmaSettingStringXml>().First();

var xml = "<Group Id=\"{65fa649a-a111-4912-9294-fb6337a25038}\">\r\n  <MatchType>MatchAny</MatchType>\r\n</Group>";
setting.Value = Encoding.UTF8.GetBytes(xml);
var response = await client
        .DeviceManagement.DeviceConfigurations[_config.DeviceConfigurationId]
        .PatchAsync(item);  //
```

The `PatchAsync` method throws `Microsoft.Graph.Models.ODataErrors.ODataError`. After inspection of the payload I think the problem is a missing `@odata.type` property. The payload looks like this:

```json
{
    "omaSettings": [
        {
            "displayName": "Approved USBs Group",
            "@odata.type": "#microsoft.graph.omaSettingStringXml",
            "omaUri": "./Vendor/MSFT/Defender/Configuration/DeviceControl/PolicyGroups/%7b65fa649a-a111-4912-9294-fb6337a25038%7d/GroupData",
            "fileName": "ApprovedUSBGroup.xml",
            "value": "PEdyb3VwIElkPSJ7NjVmYTY0OWEtYTExMS00OTEyLTkyOTQtZmI2MzM3YTI1MDM4fSI\u002BDQogIDxNYXRjaFR5cGU\u002BTWF0Y2hBbnk8L01hdGNoVHlwZT4NCjwvR3JvdXA\u002B"
        }
    ]
}
```

whereas Graph API expects something like this:

```json
{
    "@odata.type": "#microsoft.graph.windows10CustomConfiguration",
    "omaSettings": [
        {
            "@odata.type": "#microsoft.graph.omaSettingStringXml",
            "displayName": "Approved USBs Group",
            "omaUri": "./Vendor/MSFT/Defender/Configuration/DeviceControl/PolicyGroups/%7b65fa649a-a111-4912-9294-fb6337a25038%7d/GroupData",
            "fileName": "ApprovedUSBGroup.xml",
            "value": "PEdyb3VwIElkPSJ7NjVmYTY0OWEtYTExMS00OTEyLTkyOTQtZmI2MzM3YTI1MDM4fSI+CiAgPE1hdGNoVHlwZT5NYXRjaEFueTwvTWF0Y2hUeXBlPgogIDxEZXNjcmlwdG9ySWRMaXN0PgogICAgPEluc3RhbmNlUGF0aElkPlVTQlNUT1JcRGlzayZhbXA7VmVuX19VU0ImYW1wO1Byb2RfX1NhbkRpc2tfMy4yR2VuMSZhbXA7UmV2XzEuMDBcMDEwMTE1NWQ3ZDVjMjU2Y2JkNTI0ZTc1ODVlNDM1MzZhMGY2NmJmM2M5M2IxNGQ1NGE0MWIxZTk1ODJhODI3IDwvSW5zdGFuY2VQYXRoSWQ+CiAgPC9EZXNjcmlwdG9ySWRMaXN0Pgo8L0dyb3VwPg=="
        }
    ]
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @RytisLT 

From the two payloads shared, it looks like the difference in the payload is the `description` property and not the `@odata.type` property as it is present in both situations. 

Any chance you can confirm the exact error from the API if you follow the guidance at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

**Comment by RytisLT** [comment]
@andrueastman no it's not the `description`.  The `description` is there because of my poor copy/paste skills, I've updated the original post. The issue is the missing `@odata.type` in the payload generated by the SDK. This is not API issue, this is an SDK issue

**Comment by andrueastman** [comment]
Hey @RytisLT 
Any chance you can re-share the payload sent by the SDK? From the description, both example payloads do seem to still have the `@odata.type` property. 

>Any chance you can confirm the exact error from the API if you follow the guidance at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

The reason I ask for this is to get the error message when `Microsoft.Graph.Models.ODataErrors.ODataError` is thrown to understand if the API was expecting something specific.

**Comment by RytisLT** [comment]
Here's the Pyload send by SDK:
```json
{
    "omaSettings": [
        {
            "displayName": "Approved USBs Group",
            "@odata.type": "#microsoft.graph.omaSettingStringXml",
            "omaUri": "./Vendor/MSFT/Defender/Configuration/DeviceControl/PolicyGroups/%7b65fa649a-a111-4912-9294-fb6337a25038%7d/GroupData",
            "fileName": "ApprovedUSBGroup.xml",
            "value": "PEdyb3VwIElkPSJ7NjVmYTY0OWEtYTExMS00OTEyLTkyOTQtZmI2MzM3YTI1MDM4fSI\u002BDQogIDxNYXRjaFR5cGU\u002BTWF0Y2hBbnk8L01hdGNoVHlwZT4NCjwvR3JvdXA\u002B"
        }
    ]
}
```

Error messages:

```C#
odataError.Error?.Code = "ModelValidationFailure"
odataError.Error?.Message = "Exception has been thrown by the target of an invocation."
```

The SDK sends @odata.type for the omaSetting but not for the parent object

**Comment by andrueastman** [comment]
Thanks for confirming @andrueastman 

```cs
var item = (Windows10CustomConfiguration)(await cfgReq.GetAsync())!;
```
Since the object being sent to the API was originally received from the API, only the changed values in the object will be sent back to the API on the Patch request. 

Any chance you have any luck if you add the line to set the OdataType property as well before sending back the value?

```cs
item.OdataType = "#microsoft.graph.windows10CustomConfiguration"; // set the value so it is included
var response = await client
        .DeviceManagement.DeviceConfigurations[_config.DeviceConfigurationId]
        .PatchAsync(item);  //
```

**Comment by RytisLT** [comment]
@andrueastman I didn't realize I can set `OdataType` myself. This gets past the model validation failure. Now I'm getting `InternalServerError` from the API 😞. Here's the full response JSON

```
{
    "error": {
        "code": "InternalServerError",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: c324de1c-e411-4f5b-a647-b4fdbfdbae5f - Url: https://fef.amsub0302.manage.microsoft.com/DeviceConfiguration_2310/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('6d6e40d1-c961-4e3e-b19f-41493ee4bf13')?api-version=2022-06-13\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
        "innerError": {
            "date": "2023-11-06T12:50:29",
            "request-id": "c324de1c-e411-4f5b-a647-b4fdbfdbae5f",
            "client-request-id": "c324de1c-e411-4f5b-a647-b4fdbfdbae5f"
        }
    }
}
```

**Comment by andrueastman** [comment]
@RytisLT Any chance you can confirm now that the payload sent to the API is as expected and is the same as the value with the raw request? Are you able to replicate the issue when not using the SDK?

**Comment by RytisLT** [comment]
@andrueastman I've been able to replicate the issue with raw request. It is not an SDK issue
