### ISSUE TITLE
[Client bug]: Only first page returned when listing rooms

### ISSUE THREAD

**Issue by jairbubbles** [microsoftgraph/msgraph-sdk-dotnet#2190]
**Describe the bug**

When trying to list rooms (https://learn.microsoft.com/en-us/graph/api/place-list) the API is only returning the first page with no `ODataNextLink`.

**To Reproduce**

You can use the following snippet:

```csharp
var rooms = new List<Room>();
var response = await graphServiceClient.Places.GraphRoom.GetAsync(configuration =>
{
    configuration.QueryParameters.Count = true;
}).ConfigureAwait(false);
var pageIterator = PageIterator<Room, RoomCollectionResponse>.CreatePageIterator(graphServiceClient, response, room =>
    {
        rooms.Add(room);
        return true;
    });
await pageIterator.IterateAsync().ConfigureAwait(false);

// rooms contain only 100 elements while response.OdataCount is 1535
```
**Expected behavior**

I would expect the code to iterate over the 1535 rooms.

**Workaround**

If I configure the top property in my query I get all the rooms:

```csharp
configuration.QueryParameters.Top = 10000;
```

**Client version**

`Microsoft.Graph.Beta@5.53.0-preview`

**Desktop (please complete the following information):**
 - OS:  Windows 11

**Comment by andrueastman** [comment]
Thanks for raising this @jairbubbles 

Any chance you can take a look at this example at the link below? If you want to collect all the items from subsequent requests made you will need to pass an action to do that. as the original response will remain unmodified. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#pageiterator

**Comment by jairbubbles** [comment]
Hi @andrueastman , isn't that what I am doing when I increment `count`?

In the example `QueryParameters.Top` is set to `1`. Is this needed for the page iterator to work?

**Comment by andrueastman** [comment]
Sorry I wasn't too clear there. What I mean is creating a collection and using the callback to add items to it as the `response` variable only holds values for the first request.

**Comment by jairbubbles** [comment]
Sure I understand but that's already what I'm doing, I updated the code sample so that it's less ambiguous. 
The initial response does not have a  OdataNextLink which I find suspicious.

**Comment by andrueastman** [comment]
@jairbubbles It looks like this specific API does not support paging through its response at the moment and therefore to get all the items, you would need to change the page size using the `$top` parameter to get all the items. 

As this is an API related feature request, I would suggest creating a feature request at the link below so that the API owners may prioritize adding this functionality to the API. It would be great if you could post back the link here as a comment so that anyone who comes accross this may find and upvote it. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by jairbubbles** [comment]
Thx @andrueastman for looking into it! I added a post on the tech community over [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/graph-api-automatic-paging-for-quot-list-places-quot/idi-p/3971884#M2081).

Shouldn't the `PageIterator` be able to iterate on endpoints that does not support paging through `OdataNextLink` by incrementing `$skip`? It's not the best as it would work only when the data does not change while getting all pages but still it would be more consistent.

**Comment by andrueastman** [comment]
Thanks for creating this @jairbubbles 

> Shouldn't the PageIterator be able to iterate on endpoints that does not support paging through OdataNextLink by incrementing $skip?

Unfortunately, that may lead to incorrect assumptions as an API could also not support `$skip` and maybe use something like `$skipToken` or not support it at all. The [API guidance](https://github.com/microsoft/api-guidelines/blob/vNext/graph/GuidelinesGraph.md#query-support) for paging support involves the returning an `@odata.nextLink` which will align with the API's patterns. 

We'll be closing this issue for now and follow up/re-open in the event anything SDK related is raised for this.
