### ISSUE TITLE
Reports.GetSharePointSiteUsageDetailWithDate throws ArgumentException

### ISSUE THREAD

**Issue by netclectic** [microsoftgraph/msgraph-sdk-dotnet#2193]
**Describe the bug**
Calling Reports.GetSharePointSiteUsageDetailWithDate results in an ArgumentException with the message: `Illegal class passed as substitution, found Microsoft.Kiota.Abstractions.Date at col:58`

**To Reproduce**
```cs
DateTime dateTime = DateTime.UtcNow;
var date = new Microsoft.Kiota.Abstractions.Date(dateTime.Date);
var report = await Client.Reports.GetSharePointSiteUsageDetailWithDate(date).GetAsync();
```

The exception actually occurs when trying to get the Uri from the request...
```cs
DateTime dateTime = DateTime.UtcNow;
var date = new Microsoft.Kiota.Abstractions.Date(dateTime.Date);
var request = Client.Reports
    .GetSharePointSiteUsageDetailWithDate(date)
    .ToGetRequestInformation();
var uri = request.URI;
```

**Expected behavior**
It should execute the request and return a stream containing the report data.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
using NuGet package: Microsoft.Graph, Version=5.32.0

**Comment by andrueastman** [comment]
Thanks for raising this @netclectic 

Any chance you can confirm the issue is resolved now if you add the package reference to the latest abstraction package to your project? 
https://www.nuget.org/packages/Microsoft.Kiota.Abstractions/1.6.1

Please re-open in the event of any issues.

**Comment by netclectic** [comment]
I can confirm that it is working now with v1.6.1

Thanks!
