### ISSUE TITLE
Mail Message Delta list missing change type query parameter in 5.x

### ISSUE THREAD

**Issue by idiotsky** [microsoftgraph/msgraph-sdk-dotnet#2195]
In 4.x we can write code like this.

` IMessageDeltaCollectionPage messageDeltaCollectionPage = await graphServiceClient
                .Me.MailFolders[folderId]
                .Messages.Delta()
                .Request(new List<Option>
                         {
                             new QueryOption("$select", "LastModifiedDateTime"),
                             new QueryOption("changeType", "created"),
                             new HeaderOption("Prefer", $"odata.maxpagesize={MaxPageSize.ToString()}")
                         })
                .Filter($"receivedDateTime ge {syncAfter:s}Z")
                .GetAsync();`

but in 5.x
`graphServiceClient.Me.MailFolders[folderId].Messages.Delta.GetAsDeltaGetResponseAsync(
                configuration =>
                {
                    configuration.QueryParameters.Select = new[] { "LastModifiedDateTime" };
                    configuration.QueryParameters.Filter = $"receivedDateTime ge {syncAfter:s}Z";
                    configuration.Headers.Add("Prefer", $"odata.maxpagesize={MaxPageSize.ToString()}");
                });`
there's no place to specify the changetype like this
`configuration.QueryParameters.ChangeType = new[] { "created", }; `

**Comment by andrueastman** [comment]
Depends on resolution of https://github.com/microsoftgraph/msgraph-metadata/issues/480

**Comment by baywet** [comment]
Update: the fix to metadata was just merged in today, which means the query parameter should show up in the next generation next week.
https://github.com/microsoftgraph/msgraph-metadata/pull/500
