### ISSUE TITLE
Error when reading unexpected response

### ISSUE THREAD

**Issue by AttackOnMorty** [microsoftgraph/msgraph-sdk-dotnet#2202]
Hi @andrueastman,

I have bad news for you, the error still persists, the API fix did not solve this issue.

_Originally posted by @vko-insiders in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1701#issuecomment-1469605850_

**Comment by AttackOnMorty** [comment]
Hey @vko-insiders,

I encountered the same error as you. Has your issue (https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1701) been resolved?

**Comment by andrueastman** [comment]
Thanks for raising this @AttackOnMorty 

As the issue reported in #1701 was resolved on the API side, any chance you can try creating a support ticket with the API team at the link below as was done before to resolve the issue? As this repo is mainly intended for issues related to the C# SDK we may not be the best placed to resolve issues with regards to API behavior. 

https://developer.microsoft.com/en-us/graph/support
