### ISSUE TITLE
Next Release for 1.0? Reports APIs

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#221]
Just saw that https://developer.microsoft.com/en-us/graph/docs/concepts/changelog#december-2017 includes the Reports APIs on the v1.0 endpoint - will there be and ~ when a NuGet that supports this?

**Comment by MIchaelMainer** [comment]
Since this went live on Monday, I'd like to see this put in the client library in January. We have another release lined up to publish for December: https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.7.0

**Comment by christophwille** [comment]
Given the deprecation of the old API is also in January - any ~ ideas when a version with Reports included will land?
