### ISSUE TITLE
OneDrive API calls doesnot have any provision for Delegated and Apponly authentication types. 

### ISSUE THREAD

**Issue by Neelabhra08** [microsoftgraph/msgraph-sdk-dotnet#2211]
https://graph.microsoft.com/v1.0/drives/Me/items/01J4YTV6BO73AXJWFW3JEZU3DYNCXMCWA7/permanentDelete - This call requires a DriveID which is "Me" here. I bypassed this call by modifying the the request URI - https://graph.microsoft.com/v1.0/me/drive/items/01J4YTV6BO73AXJWFW3JEZU3DYNCXMCWA7/permanentDelete and this works fine.

But cannot find any way around to work with the Apponly access where userID is needed as [https://graph.microsoft.com/v1.0/{userID}/drive/items/01J4YTV6BO73AXJWFW3JEZU3DYNCXMCWA7/permanentDelete](https://graph.microsoft.com/v1.0/%7BuserID%7D/drive/items/01J4YTV6BO73AXJWFW3JEZU3DYNCXMCWA7/permanentDelete) isn't working.

The main goal is to not do a extra call for fetching the driveId to execute OneDrive calls. Can anyone help with these please.

**Comment by andrueastman** [comment]
Thanks for raising this @Neelabhra08 

Taking a look at your url, the `users` segment looks to be missing. Any chance it works out if you use this by adding the `users` segment before the `user-id`?

`https://graph.microsoft.com/v1.0/users/{userId}/drive/items/{item-d}/permanentDelete`

**Comment by Neelabhra08** [comment]
@andrueastman Hey, thanks for responding. The call works fine in the graph explorer but doesnot support for C# SDK. Can you suggest what will be the call if we are implementing it in C#.

**Comment by andrueastman** [comment]
Thanks for the feedback, the path missing in the SDK is due to what is explained in the guidance at the link below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths

To resolve this you can either get the drive id and use the available requestbuilders as below.

```cs
         //get the user drive id
         var userDrive = await graphClient.Users["user-id"].Drive.GetAsync();
         await graphClient.Drives[userDrive.Id].Items["item-id"].PermanentDelete.PostAsync();// delete the item
```

or override the url as you desire using the `WithUrl` method as below.

```cs
         //use the url to override
         await graphClient.Drives[""].Items[""].PermanentDelete.WithUrl("https://graph.microsoft.com/v1.0/users/{userId}/drive/items/{item-d}/permanentDelete").PostAsync();// delete the item
```

**Comment by Neelabhra08** [comment]
@andrueastman the method worked fine. Thanks for quick response.
