### ISSUE TITLE
.NET 8 conflict  System.Text.Json

### ISSUE THREAD

**Issue by martinsura** [microsoftgraph/msgraph-sdk-dotnet#2214]
**Describe the bug**
Hi,

After upgrading project to .NET8 RTM got error

```
Error NU1107 : Version conflict detected for System.Text.Json. Install/reference System.Text.Json 8.0.0 directly to project [Project] to resolve this issue. 
 [Project] -> Microsoft.EntityFrameworkCore.Design 8.0.0 -> Microsoft.Extensions.DependencyModel 8.0.0 -> System.Text.Json (>= 8.0.0) 
 [Project] -> Microsoft.Graph 5.32.0 -> Microsoft.Graph.Core 3.1.0 -> Microsoft.Kiota.Http.HttpClientLibrary 1.2.0 -> System.Text.Json (>= 6.0.0 && < 8.0.0).
```

**To Reproduce**
```

<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
... etc
        <PackageReference Include="Microsoft.Graph" Version="5.32.0"/>
    </ItemGroup>
</Project>
```

**Expected behavior**
Build success without error

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0

**Comment by maxxacb** [comment]
This extends beyond just `System.Text.Json`, I am also seeing a conflict in `System.Diagnostics.DiagnosticSource` when trying to update to .NET 8.

```
[Project]: Error NU1107 : Version conflict detected for System.Diagnostics.DiagnosticSource. Install/reference System.Diagnostics.DiagnosticSource 8.0.0 directly to project [Project] to resolve this issue. 
[Project] -> Microsoft.Extensions.Http.Polly 8.0.0 -> Microsoft.Extensions.Http 8.0.0 -> Microsoft.Extensions.Diagnostics 8.0.0 -> Microsoft.Extensions.Diagnostics.Abstractions 8.0.0 -> System.Diagnostics.DiagnosticSource (>= 8.0.0) 
[Project] -> Microsoft.Graph 5.34.0 -> Microsoft.Graph.Core 3.1.1 -> Microsoft.Kiota.Abstractions 1.6.1 -> System.Diagnostics.DiagnosticSource (>= 6.0.0 && < 8.0.0).
1>------- Finished building project: [Project]. Succeeded: False. Errors: 1. Warnings: 1
```

This is on Windows 10 Enterprise, Version 22H2. Trying to add an explicit reference to version 8.0.0 of `System.Diagnostics.DiagnosticSource` fails when going through Rider's NuGet tool. I can manually add the reference in the csproj file and then run into the issue with `System.Text.Json`.

**Comment by markushaslinger** [comment]
Kiota update is out, so I hope this will follow soon.

**Comment by h3rmanj** [comment]
Microsoft.Kiota.Abstractions is not enough

[Microsoft.Kiota.Authentication.Azure](https://github.com/microsoft/kiota-authentication-azure-dotnet/pull/141)
[Microsoft.Kiota.Http.HttpClientLibrary](https://github.com/microsoft/kiota-http-dotnet/pull/168)
[Microsoft.Kiota.Serialization.Json](https://github.com/microsoft/kiota-serialization-json-dotnet/pull/147)

Is needed as well. Once those are in place, Microsoft.Graph.Core can be updated, followed by Microsoft.Graph.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/771

**Comment by jeffpardy** [comment]
@andrueastman do we still need a release here so that we pick up version 3.1.2 of `Microsoft.Graph.Core`?

**Comment by SeeUnsharp** [comment]
@jeffpardy  I installed 3.1.2 Microsoft.Graph.Core Nuget next to Microsoft.Graph 5.34.0 and it seems to work for now.

**Comment by andrueastman** [comment]
As confirmed by @SeeUnsharp you can simply pull 3.1.2 Microsoft.Graph.Core. We will be releasing a new version of Microsoft.Graph that pulls this version soon after we close https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2213
