### ISSUE TITLE
Download file. Length property of steam NotSupported after upgrade to v5

### ISSUE THREAD

**Issue by salladorets** [microsoftgraph/msgraph-sdk-dotnet#2218]
**Describe the bug**
On version 4.51.0 I was able to get stream and to fetch length of the stream

I've used the following code:
`graphServiceClient.Drives[driveId].Items[fileId].Content.Request().GetAsync();`

On version 5.34.0 Im not able to get Length 

`await graphServiceClient.Drives[driveId].Items[fileId].Content.GetAsync()`
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/16153445/574ef000-a105-4516-9c3c-65cbfd91910a)

**Comment by salladorets** [comment]
Workaround

```
                var getRequestInformation = graphServiceClient.Drives[driveId].Items[fileId].Content.ToGetRequestInformation();

                var httpRequest = await graphServiceClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(getRequestInformation);

                var response = await httpClient.SendAsync(httpRequest);
                return await response.Content.ReadAsStreamAsync();
```

**Comment by andrueastman** [comment]
Thanks for raising this @salladorets 

V5 of the SDK prevents the buffering of the entire stream into memory as the size of the response stream can be very large in scenarios where a large file/email can be downloaded, and to get these properties the stream would have to be loaded entirely. 

You can however buffer the stream into a memoryStream as older versions did as below and access the properties if you wish to. 

```cs
        using var stream = await graphClient.Users["{mailbox-address}"].Messages["{message-id}"].Content.GetAsync();
        using var memoryStream = new MemoryStream();
        stream!.CopyTo(memoryStream);

        var length = memoryStream.Length;
```

**Comment by salladorets** [comment]
Thank you for your answer @andrueastman

**Comment by mfeingol** [comment]
I'm not sure I follow why it's necessary to buffer large files in memory on the client side in order to determine their length. Wouldn't the underlying HTTP response provide a content-length, which could be relayed via the returned Stream instance?
