### ISSUE TITLE
Notebook IsDefault shows as { get; set; }, but is actually read only.

### ISSUE THREAD

**Issue by jchilde** [microsoftgraph/msgraph-sdk-dotnet#222]
I need to migrate a large number of Notebooks from subsites in one site collection to their respective Office 365 groups.  The OneDrive endpoint allows me to copy these notebooks into the default document library for the Office 365 group.  

The Graph also appears to allow me to set the copied notebook as IsDefault.

However, it actually is a read only property.  Seems like this should allow { get; } only, or it should allow me to change the "default" notebook.

Microsoft either needs to allow setting the default OneNote Notebook or provide the ability to copy OneNote Notebooks to the Default Location with the Default NoteBook name in order to support migration.

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. 

1) With regards to IsDefault, the client libraries are generated and we don't have enough metadata details to generate the models with the appropriate accessors - so we add both. 

2) I'll pass on your request to be able to set IsDefault.

**Comment by MIchaelMainer** [comment]
@jchilde It would be helpful if you opened a feature request on user voice. That way other users can vote on it. Here's a URL for your convenience:

https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?query=Support%20setting%20isDefault%20for%20OneNote%20Notebooks%20through%20the%20Graph%20API

**Comment by jchilde** [comment]
Done

Jeffrey A. Childers
Rumph Childers, LLC
(478) 471-8787 x 7


Confidentiality Notice: This e-mail message and any attachments are for the sole use of the intended recipient(s) and may contain confidential or privileged information.  Any unauthorized review, use, disclosure, or distribution is prohibited.  If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message and any attachments.  The receipt of this email alone does not create an attorney-client privilege.  Thank you.
