### ISSUE TITLE
Paging works wrong SDK V5 (PageIterator return duplicates) 

### ISSUE THREAD

**Issue by salladorets** [microsoftgraph/msgraph-sdk-dotnet#2221]
SDK version 5.34.0

Im using the following code that returns duplicates. 
      
       var responseTop = await graphServiceClient.Drives[folderInfo.DriveId].Items[folderInfo.FolderId].Delta.GetAsDeltaGetResponseAsync((requestConfiguration) =>
            {
                requestConfiguration.QueryParameters.Top = 2;
                requestConfiguration.QueryParameters.Select = propertiesToSelect;
            });

            List<DriveItem> items = new List<DriveItem>();
            var iterator = PageIterator<DriveItem, Microsoft.Graph.Drives.Item.Items.Item.Delta.DeltaGetResponse>
            .CreatePageIterator(
                graphServiceClient,
                responseTop,
                (driveItem) =>
                {
                    items.Add(driveItem);
                    return ContinuePageIteration;
                });

            await iterator.IterateAsync();

            var countIterator = items.Count;
            var countIteratorAfterGrouping = items
                .GroupBy(group => group.Id)
                .Select(group => group.First())
                .Count();
                

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/16153445/3893bd8d-29c3-4499-a593-dd40dd4ddc8a)

PS Also very strange namespace Microsoft.Graph.Drives.Item.Items.Item.Delta

**Comment by andrueastman** [comment]
Thanks for raising this @salladorets 

According to the drive API documentation, the guidance is that duplicates can occur in the delta feed

> The same item may appear more than once in a delta feed, for various reasons. You should use the last occurrence you see.

https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#remarks
