### ISSUE TITLE
Microsoft.Graph 5.34.0 The Parsable does not contain a collection property (Places.GraphRoomList.GetAsync)

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/msgraph-sdk-dotnet#2223]
**Describe the bug**
I get the following error when trying to get a list of rooms using the following with a pageIterator
https://learn.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=csharp#request-1

`The Parsable does not contain a collection property System.ArgumentException
The Parsable does not contain a collection property
   at Microsoft.Graph.PageIterator`2.ExtractEntityListFromParsable(TCollectionPage parsableCollection)
   at Microsoft.Graph.PageIterator`2.CreatePageIterator(IRequestAdapter requestAdapter, TCollectionPage page, Func`2 callback, Func`2 requestConfigurator, Dictionary`2 errorMapping)`

**To Reproduce**
Running the following gives me the above error
`var roomListCollectionResponse = await graphClient.Places.GraphRoomList.GetAsync();
var pageIterator = PageIterator<Room, RoomListCollectionResponse>.CreatePageIterator(Application.Client, roomListCollectionResponse, room =>
{
    return true;
});
await pageIterator.IterateAsync();`

**Expected behavior**
I should not encounter the error and a list of rooms should be returned. I can see in the initial response (roomListCollectionResponse) contains two rooms

**Additional context**
I'm currently using Microsoft.Graph 5.34.0

**Comment by andrueastman** [comment]
Thanks for raising this @ashleywb 

As calling `await graphClient.Places.GraphRoomList.GetAsync();` will return a collection of `RoomList` and not `Room` any chance your issue is resolved if you initialize the pageIterator as below with the right entity type?

```cs
var pageIterator = PageIterator<RoomList, RoomListCollectionResponse>.CreatePageIterator(graphClient, roomListCollectionResponse, room => { return true; });
```

**Comment by ashleywb** [comment]
> Thanks for raising this @ashleywb
> 
> As calling `await graphClient.Places.GraphRoomList.GetAsync();` will return a collection of `RoomList` and not `Room` any chance your issue is resolved if you initialize the pageIterator as below with the right entity type?
> 
> ```cs
> var pageIterator = PageIterator<RoomList, RoomListCollectionResponse>.CreatePageIterator(graphClient, roomListCollectionResponse, room => { return true; });
> ```

This looks to have resolved my issue, many thanks. Can#t believe I didn't spot/try this. Thanks again
