### ISSUE TITLE
PageIterator.CreateIterator missing method since v5.34

### ISSUE THREAD

**Issue by dawidgrey** [microsoftgraph/msgraph-sdk-dotnet#2226]
The PageIterator worked in v5.33 and stopped working in v5.34, including v5.35.

All my code that uses the PageIterator fails. Here is an example:
```C#
public async Task<List<AadUserModel>> GetAllUsers()
{
    var response = await _client.Users.GetAsync();
    var results = new List<AadUserModel>();

    var pageIterator = PageIterator<Microsoft.Graph.Models.User, UserCollectionResponse>
        .CreatePageIterator(_client, response, (u) =>
        {
              results.Add(new AadUserModel
              {
                  AzureId = Guid.Parse(u.Id),
                  DisplayName = u.DisplayName,
                 //... 
              });

            return true;
        });

    await pageIterator.IterateAsync();

    return results;
}
```

**Unexpected error**
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.Graph.PageIterator`2<!0,!1> Microsoft.Graph.PageIterator`2.CreatePageIterator(Microsoft.Graph.IBaseClient, !1, System.Func`2<!0,Boolean>, System.Func`2<Microsoft.Kiota.Abstractions.RequestInformation,Microsoft.Kiota.Abstractions.RequestInformation>)'.
 
```

**Comment by andrueastman** [comment]
Thanks for raising this @dawidgrey 

Any chance you are able to share the NET runtime you are using to build your app when this error occurs? Any chance you've also tried clearing you nuget cache as well on rebuilding?

**Comment by Charlie-Conte** [comment]
I have the same problem. both on local and on azure pipelines CICD.
Nuget cashes cleared and refreshed on every build.
using .Net 7 

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/15055377/9df5951d-9a4a-4ec8-8d30-d6ea742a195d)
Hope this helps

**Comment by dawidgrey** [comment]
v5.36.0 is working for me.
