### ISSUE TITLE
QueryParameters.Skiptoken definition missing in v1.0 and Beta

### ISSUE THREAD

**Issue by dansmitt** [microsoftgraph/msgraph-sdk-dotnet#2228]
**Describe the bug**
QueryParameters.Skiptoken definition missing in v1.0 and Beta as it is documented here:
https://learn.microsoft.com/en-us/graph/paging?tabs=csharp

Code:

``` csharp
var result = await graphClient.Users.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Top = 5;
	requestConfiguration.QueryParameters.Skiptoken = "skiptoken=RFNwdAIAAQAAAD8...AAAAAAAA";
});
```

**Expected behavior**
We expect that it works like it is documented

**Comment by andrueastman** [comment]
Thanks for raising this @dansmitt 

As caputured in the guidance at the link below, the $skipToken and $deltaToken parameters are not present as the nextLink url is treated as an Opaque url and shouldn't really be used as is.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests

With the SDK, the right thing to do would be to do would be use the PageIterator(as shown in the link above) or use the `OdataNextLink` property from the first page as below.

```cs
            var result = await graphClient.Users.GetAsync((requestConfiguration) =>
            {
                requestConfiguration.QueryParameters.Top = 5;
            });
            
            var nextResult = await graphClient.Users.WithUrl(result.OdataNextLink).GetAsync();
``` 

Keeping this open to resolve the snippet generation issue in docs to use `WithUrl` for the snippets generated in the page .
