### ISSUE TITLE
PageIterator Not Following DeltaLink

### ISSUE THREAD

**Issue by Freenex1911** [microsoftgraph/msgraph-sdk-dotnet#2232]
**Describe the bug**
The `PageIterator` is not following `DeltaLink` when I call `IterateAsync()` again.

**To Reproduce**
Run the following code and set a debug point at `foreach` and check the `DeltaLink`.
```
PageIterator<Message, DeltaGetResponse> pageIterator = null;
while (true)
{
	var messages = new List<Message>();

	if (pageIterator == null)
	{
		var response = await graphServiceClient.Users["..."].MailFolders["Inbox"].Messages.Delta.GetAsDeltaGetResponseAsync(x => x.Headers.Add("Prefer", "IdType=\"ImmutableId\""));
		pageIterator = PageIterator<Message, DeltaGetResponse>.CreatePageIterator(graphServiceClient, response, value =>
		{
			messages.Add(value);
			return true;
		});
	}

	await pageIterator.IterateAsync();

	foreach (var message in messages)
		await HandleMessage(message);

	await Task.Delay(10000);
}
```

**Expected behavior**
When I execute `IterateAsync()` again, I expect that it will follow `DeltaLink` to iterate over all pages again, as outlined in `upgrade-to-v5.md`.

**Client version**
5.36.0

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 120.0

**Comment by andrueastman** [comment]
Thanks for raising this @Freenex1911 

In the event that the page iterator encounters the `deltaLink` the paging will be paused as this means that the API has returned all the changes in the `delta` call. This therefore means that the client would need to wait for a bit for more changes to occur otherwise you may keep receiving a empty response(no changes since the last call) and another delta link. 

Similar to the example captured in the documentation below, the paging state will not be complete, so you will need to call something like below to capture further changes after waiting for a time that is convenient for you. 

```cs
await pageIterator.IterateAsync();

while (pageIterator.State != PagingState.Complete)// or while (pageIterator.State == PagingState.Delta)
{
    Console.WriteLine("Iteration paused for 5 seconds to wait for more changes...");
    await Task.Delay(5000);
    // Reset count
    await pageIterator.ResumeAsync();
}
```

https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp#stopping-and-resuming-the-iteration

**Comment by andrueastman** [comment]
Thanks for clarifying @Freenex1911 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2234 should make the documentation consistent. 

With regards to the headers, the pageIterator will need to be initialized with the `requestConfigurator` parameter as below to propagate the `Headers` parameter as below.

```cs
pageIterator = PageIterator<Message, DeltaGetResponse>.CreatePageIterator(graphServiceClient, response, value =>
                                                                            {
                                                                                messages.Add(value);
                                                                                return true;
                                                                            }, 
                                                                            requestInformation =>
                                                                            {
                                                                                requestInformation.Headers.Add("Prefer", "IdType=\"ImmutableId\"");
                                                                                return requestInformation;
                                                                            });
```

**Comment by Freenex1911** [comment]
It works perfectly! However I find it kind of odd to specify the Headers twice in my code even tho the request serves the same purpose. Thanks anyway, as always!
