### ISSUE TITLE
Upgrade guide from v4 to v5 link does not work

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-sdk-dotnet#2233]
I am trying to upgrade from 4 to 5 and to say that there are breaking changes is an understatement - anyway the nuget page links to an upgrade guide but clicking the link takes you nowhere see below

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/137350/3bdb6e11-44b4-44ba-ba57-4a3144699566)

**Comment by andrueastman** [comment]
Thanks for raising this @catmanjan 

The link to the guide is as below. We'll be looking into fixing the issue in the nuget page. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md
