### ISSUE TITLE
Cannot manage encrypted subscriptions via SDK due to missing interfaces.

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-dotnet#2237]
**Describe the bug**
Attempting to use `AddPublicEncryptionCertificate` on a `Subscription` results in an error:

```
'Subscription' does not contain a definition for 'AddPublicEncryptionCertificate' 
and the best extension method overload 
'IEncryptableSubscriptionExtensions.AddPublicEncryptionCertificate(IEncryptableSubscription, X509Certificate2)' 
requires a receiver of type 'Microsoft.Graph.IEncryptableSubscription'
```

Attempting to use `DecryptAsync` method on `ChangeNotification.EncryptedContent` results in an error:

```
'ChangeNotificationEncryptedContent' does not contain a definition for 'DecryptAsync' 
and the best extension method overload 'IDecryptableContentExtensions.DecryptAsync<ChatMessage>
(IDecryptableContent, Func<string, string, Task<X509Certificate2>>)' requires a 
receiver of type 'Microsoft.Graph.IDecryptableContent'
```

Attempting to use `AreTokensValid` on a `ChangeNotificationCollection` results in an error:

```
'ChangeNotificationCollection' does not contain a definition for 'AreTokensValid' and 
no accessible extension method 'AreTokensValid' accepting a first argument of type 
'ChangeNotificationCollection' could be found (are you missing a using directive or 
an assembly reference?)
```

**Expected behavior**
These methods should be available. This is a breaking change from v4 SDK.

**Comment by andrueastman** [comment]
@baywet Given that the `ChangeNotification` models are not generated by Kiota as they are not directly referenced by any endpoint(the openApi metadata would need to reference them using [callbacks](https://spec.openapis.org/oas/v3.0.2#callback-object) and then Kiota detects the models in them)

I think the last option would be the best here as the existing webhook models already use that approach.

**Comment by baywet** [comment]
ah I missed that aspect, so they are effectively defined in core I guess?
