### ISSUE TITLE
Values larger than Int32.Max are truncated when sent to Excel sheets

### ISSUE THREAD

**Issue by dinhnguyen92** [microsoftgraph/msgraph-sdk-dotnet#224]
I'm using the Microsoft Graph API to modify cells in Excel spreadsheets. When writing integer values larger than Int32.Max to the spreadsheet via the API, the upper 32 bits of the values appear to be truncated, and only the lower 32 bits seem to be written to the spreadsheet.

Below are the values that I have tested.

Test 1:

Value sent: 1,234,000,000,000 (0x11F5021B400)
Value written to cell: 1344386048 (0x5021B400)
The upper bits appear to have been truncated, leaving behind only the lower 32 bits.

Test 2:

Value sent: 2,147,483,648 (Int32.Max + 1) (0x80000000)
Value written to the cell: -2147483648
If 0x80000000 is interpreted as a signed Int32 number, then it is -2147483648

Test 3:

Value sent: 4294967296 (0x100000000)
Value written to the cell: 0
When the highest bit of 0x100000000 is truncated, the remaining 32 bits become 0 in signed Int32

Test 4:

Value sent: 4294967295 (0xFFFFFFFF)
Value written to the cell: -1
When interpreted as a signed Int32 value, 0xFFFFFFFF becomes -1

All of the values were sent using the .NET Microsoft Graph Client library, and were of type long. Specifically, the values were sent using the Microsoft.Graph.WorkbookRange class. Setting the value type of the cells in the WorkbookRange object to Double did not fix the`problem.

Thanks in advance for any help or suggestion.

**Comment by MIchaelMainer** [comment]
@dinhnguyen92 I'm sorry for the tardy response. Can you show the request and response that were sent? Since this is set with a JToken, I think this issue may be with the service.

**Comment by sumurthy** [comment]
I can't re-pro this issue. Please send the raw HTTP request. 
I only tested the first example directly using REST client. When I `PATCH` the range cell with a value of 
```


{
"values": [["1,234,000,000,000"]]
}
```
I get back the same value: 
```
{
    "values": [
        [
            1234000000000
        ]
    ]
}

```

**Comment by dinhnguyen92** [comment]
I'm afraid I can't provide the exact code that we used, as it is proprietary. However, I've created the code snippet below, which mimics the source code as closely as possible and should reproduce the problem.

```
        // IAuthenticationProvider interface comes from Microsoft.Graph
        public class MicrosoftGraphOAuthProvider : IAuthenticationProvider
        {
            private string _accessToken;
            public MicrosoftGraphOAuthProvider(string accessToken)
            {
                _accessToken = accessToken;
            }
            public Task AuthenticateRequestAsync(HttpRequestMessage request)
            {
                return Task.Run(() =>
                {
                    request.Headers.Add("Authorization", $"Bearer {_accessToken}");
                });
            }
        }

        public void Test()
        {
            // Microsoft.Graph version 1.40
            // Microsoft.Graph.Core version 1.50
            // Newtonsoft.Json version 10.0.2
            // .NET Framework 4.5

            // Create the Graph service client
            string accessToken = “yourAccessTokenHere”;
            MicrosoftGraphOAuthProvider OAuthProvider = new MicrosoftGraphOAuthProvider(accessToken);
            Microsoft.Graph.GraphServiceClient graphClient = new GraphServiceClient(OAuthProvider);
           
            // Create the worksheet request builder
            string path = "Debug//TruncateTest.xlsx";
            string worksheetName = "Sheet1";
            Microsoft.Graph.IWorkbookWorksheetRequestBuilder sheetRequestBuilder = graphClient.Me.Drive.Root.ItemWithPath(path).Workbook.Worksheets[worksheetName];
            
            // The test table has 2 columns
            // For each row, we write an int32 value to the first column, and a long int value to the 2nd column
            // In the payload, each row consists of 2 JArrays: 1 JArray of cell values, and 1 JArray of cell formulas
            // The payload itself has 2 JArrays: 1 JArray of the rows' cell value JArrays, and 1 JArray of the rows' cell formula JArrays
            
            List<object> row1Values = new List<object>();
            int row1Col1 = 1;
            long row1Col2 = 1234000000000;
            row1Values.Add(row1Col1);
            row1Values.Add(row1Col2);
            
            List<object> row2Values = new List<object>();
            int row2Col1 = 2;
            long row2Col2 = 2147483648; // Int32.Max + 1
            row2Values.Add(row2Col1);
            row2Values.Add(row2Col2);
            
            // The columns have no formula
            List<string> row1Formulas = new List<string>();
            row1Formulas.Add(null);
            row1Formulas.Add(null);
            List<string> row2Formulas = new List<string>();
            row2Formulas.Add(null);
            row2Formulas.Add(null);
            
            // Create the row JArrays
            Newtonsoft.Json.Linq.JArray row1ValueArray = new JArray(row1Values);
            Newtonsoft.Json.Linq.JArray row1FormulaArray = new JArray(row1Formulas);
            Newtonsoft.Json.Linq.JArray row2ValueArray = new JArray(row2Values);
            Newtonsoft.Json.Linq.JArray row2FormulaArray = new JArray(row2Formulas);
            
            // Create the payload JArrays
            Newtonsoft.Json.Linq.JArray values = new JArray();
            values.Add(row1ValueArray);
            values.Add(row2ValueArray);
            Newtonsoft.Json.Linq.JArray formulas = new JArray();
            formulas.Add(row1FormulaArray);
            formulas.Add(row2FormulaArray);
            
            // Create the WorkbookRange payload
            Microsoft.Graph.WorkbookRange workbookRange = new WorkbookRange();
            workbookRange.Address = "'Sheet1'!A2:B3";
            workbookRange.Values = values;
            workbookRange.Formulas = formulas;
            
            // Build the request using the payload and the request builder
            Microsoft.Graph.IWorkbookWorksheetRangeRequest request = sheetRequestBuilder.Range(workbookRange.Address).Request();
            
            // Execute the request
            request.PatchAsync(workbookRange).Wait();
        }
```

**Comment by MIchaelMainer** [comment]
I'd like to understand where the truncation occurs. Can you inspect with Fiddler see if it is truncated in the request? Please report that back.

**Comment by dinhnguyen92** [comment]
Using the exact code snippet that I posted above, here's the JSON payload that I've captured with Fiddler. As you can see, the int long value in the first row was truncated from 1234000000000 to 1344386048, and the int long value in the second row was truncated from 2147483648 to -2147483648. Also, this result was obtained after I had updated both Microsoft.Graph and Microsoft.Graph.Core to the latest stable version 1.7.0

```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#workbookRange",
	"@odata.type": "#microsoft.graph.workbookRange",
	"@odata.id": "/users('709f2030-aed9-4540-8d10-4a58a7a69c88')/drive/root/workbook/worksheets(%27%7B00000000-0001-0000-0000-000000000000%7D%27)/range(address=%27%27%27Sheet1%27%27!A2:B3%27)",
	"address": "Sheet1!A2:B3",
	"addressLocal": "Sheet1!A2:B3",
	"cellCount": 4,
	"columnCount": 2,
	"columnHidden": false,
	"columnIndex": 0,
	"formulas": [
		[
			1,
			1344386048
		],
		[
			2,
			-2147483648
		]
	],
	"formulasLocal": [
		[
			1,
			1344386048
		],
		[
			2,
			-2147483648
		]
	],
	"formulasR1C1": [
		[
			1,
			1344386048
		],
		[
			2,
			-2147483648
		]
	],
	"hidden": false,
	"numberFormat": [
		[
			"General",
			"General"
		],
		[
			"General",
			"General"
		]
	],
	"rowCount": 2,
	"rowHidden": false,
	"rowIndex": 1,
	"text": [
		[
			"1",
			"1344386048"
		],
		[
			"2",
			"-2147483648"
		]
	],
	"values": [
		[
			1,
			1344386048
		],
		[
			2,
			-2147483648
		]
	],
	"valueTypes": [
		[
			"Double",
			"Double"
		],
		[
			"Double",
			"Double"
		]
	]
}
```

**Comment by MIchaelMainer** [comment]
Is that the response you got back? If so, what's the request that was sent?

**Comment by dinhnguyen92** [comment]
Like I said, that was not the response. That was the payload of the Patch request sent to the Graph Excel API. I did not handcraft the request. It was constructed using the Graph sdk, as shown in the code snippet I posted.

**Comment by MIchaelMainer** [comment]
Unless I'm missing something very obvious, that can't be the request from the code snippet. The code snippet is only PATCHing the address, values, and formulas properties. The JSON you share is showing a lot more information, including the@odata properties which signal to me that is the response.

            // Create the WorkbookRange payload
            Microsoft.Graph.WorkbookRange workbookRange = new WorkbookRange();
            workbookRange.Address = "'Sheet1'!A2:B3";
            workbookRange.Values = values;
            workbookRange.Formulas = formulas;
            
            // Build the request using the payload and the request builder
            Microsoft.Graph.IWorkbookWorksheetRangeRequest request = sheetRequestBuilder.Range(workbookRange.Address).Request();
            
            // Execute the request
            request.PatchAsync(workbookRange).Wait();

**Comment by dinhnguyen92** [comment]
Hi Michael, I apologize. Yes I made a mistake, the JSON I posted earlier was indeed the response payload. Below is the request payload that I captured. It appears that the long int values are not truncated in the request, which suggests that the problem might actually be in the Excel API service itself, not the sdk.

```
{
	"address": "'Sheet1'!A2:B3",
	"formulas": [
		[
			null,
			null
		],
		[
			null,
			null
		]
	],
	"values": [
		[
			1,
			1234000000000
		],
		[
			2,
			2147483648
		]
	]
}
```

**Comment by MIchaelMainer** [comment]
Hi Dinh,

Okay, the advice is to use strings instead of numbers in the PATCH request. Excel will handle the string value as a number when it processes the request. I understand that Excel will return it as a number and is not being consistent. I don't think this can fixed as it could be breaking change for existing client.

Michael

**Comment by dinhnguyen92** [comment]
Hi Michael, I was able to verify that your solution worked. Thank you!
