### ISSUE TITLE
DriveItem Copy endpoint has incorrect return type

### ISSUE THREAD

**Issue by hazzinator1** [microsoftgraph/msgraph-sdk-dotnet#2240]
**Describe the bug**
The current implementation of Copy endpoint for drive items is incorrect, as it tries to return a DriveItem as the result. The Graph API documentation shows that it instead sends back a [URI in the Location response header](https://learn.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http#response-1).
#768 seemed to show that it was possible to access the response headers, however this ability is either hidden to me or has been changed and is therefore no longer accessible.

**To Reproduce**
```
var copyResponse = this.GraphServiceClient
                .Drives[driveId]
                .Items[driveItemId]
                .Copy.PostAsync(copyRequestBody);
```

**Expected behavior**
Rather than trying to find "workarounds" to get the Location URI, why can't the Copy method just return the URI as the result?

No other relevant information

**Comment by andrueastman** [comment]
Thanks for raising this @hazzinator1 

At the moment this is possible to do as below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#native-response-object

```cs
            var nativeResponseHandler = new NativeResponseHandler();
            await graphClient.Drives["drive-id"]
                .Items["item-id"]
                .Copy.PostAsync(copyRequestBody,
                    requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption
                        { ResponseHandler = nativeResponseHandler }));

            var responseMessage = nativeResponseHandler.Value as HttpResponseMessage;
            var locationheader = responseMessage.Headers.Location.OriginalString;
```

As this falls under the polling of long running operations, this work is currently pending the resolution of https://github.com/microsoftgraph/msgraph-sdk-design/issues/83. We'll close this issue for now to be tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1366

**Comment by DonjPhanvi** [comment]
Just an FYI for other who come across this issue.

If you use the aforementioned code you can build something like this, to monitor the progress:

It will wait for completion and fetch the DriveItem by it's ID once returned. The example also includes the usage of the conflictBehavior.

```
var nativeResponseHandler = new NativeResponseHandler();

var requestInformation = graphServiceClient.Drives["drive-id"].Items["item-id"].Copy.ToPostRequestInformation(
        copyPostRequestBody,
        requestConfiguration => requestConfiguration.Options.Add(new ResponseHandlerOption { ResponseHandler = nativeResponseHandler }
    ));
requestInformation.URI = new Uri(requestInformation.URI.OriginalString + "?@microsoft.graph.conflictBehavior=rename");

await graphServiceClient.RequestAdapter.SendAsync<DriveItem>(requestInformation, DriveItem.CreateFromDiscriminatorValue);

AsyncOperationStatus result;
string strProgressLocationURL = (nativeResponseHandler.Value as HttpResponseMessage).Headers.Location.OriginalString;
IProgress<AsyncOperationStatus> progress = new Progress<AsyncOperationStatus>();

var asyncMonitor = new AsyncMonitor<AsyncOperationStatus>(graphServiceClient, strProgressLocationURL);

do // Keep polling until fulfilled or failed.
{
    await Task.Delay(4000);
    result = await asyncMonitor.PollForOperationCompletionAsync(progress, CancellationToken.None)
}
while (result.Status.ToLower() != "completed" && result.Status.ToLower() != "failed" && result.Status.ToLower() != "deleteFailed");

if(result != null && result.AdditionalData != null && result.AdditionalData.ContainsKey("resourceId"))
{
    return await graphServiceClient.Drives["drive-id"].Items[result.AdditionalData["resourceId"].ToString()].GetAsync();
}
else
{
    // Oops
}

```

Hope it's helpful. Have a nice day!
