### ISSUE TITLE
Ability to Delete profilePhotos

### ISSUE THREAD

**Issue by m33p** [microsoftgraph/msgraph-sdk-dotnet#2247]
Please add support for "Delete" on the photo endpoints.

[https://learn.microsoft.com/en-us/graph/api/profilephoto-delete?view=graph-rest-1.0&tabs=http](https://learn.microsoft.com/en-us/graph/api/profilephoto-delete?view=graph-rest-1.0&tabs=http)

Support was added on November 2nd
[https://developer.microsoft.com/en-us/graph/changelog/?search=profilephoto](https://developer.microsoft.com/en-us/graph/changelog/?search=profilephoto)

**Comment by Balkoth** [comment]
The corresponding Exchange Online PowerShell UserPhoto cmdlets are getting deactivated soon. Can we please have a working alternative with enough time to test and port our apps to the new supported mehtod?

https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-exchange-online-powershell-userphoto-cmdlets/ba-p/3955744
