### ISSUE TITLE
[Client bug]: CustomDriveItemItemRequestBuilder doesn't override all members

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#2252]
**Describe the bug**
`CustomDriveItemItemRequestBuilder` inherits from `Microsoft.Graph.Drives.Item.Items.Item.DriveItemItemRequestBuilder` and overrides members of `DriveItemItemRequestBuilder`.

`CustomDriveItemItemRequestBuilder` is returned when the extension method `ItemWithPath` is used

Currently, these members are not overridden:
```
AssignSensitivityLabel
CreatedByUser
Delta
GetActivitiesByInterval
LastModifiedByUser
PermanentDelete
RetentionLabel
DeltaWithToken
GetActivitiesByIntervalWithStartDateTimeWithEndDateTimeWithInterval
SearchWithQ
```

When using members above together with `ItemWithPath` extension, like
```
await client.Drives["{drive_id}"].Root.ItemWithPath("...").SearchWithQ("{filename}").GetAsync();
```

The request fails because wrong URL is generated.

**To Reproduce**
```
await client.Drives["{drive_id}"].Root.ItemWithPath("...").SearchWithQ("{filename}").GetAsync();
```

fails because the wrong URL is generated

**Expected behavior**
When `ItemWithPath("...")` is used then correct URL is generated.

**Screenshots**

**Client version**
5.36

**Desktop (please complete the following information):**

**Additional context**

**Comment by MartinM85** [comment]
@andrueastman Can I take it?

**Comment by andrueastman** [comment]
No worries @MartinM85

**Comment by Sidesprang** [comment]
Who made this GetActivitiesByIntervalWithStartDateTimeWithEndDateTimeWithInterval?! crazy!
