### ISSUE TITLE
Directory_ExpiredPageToken error when paginating users

### ISSUE THREAD

**Issue by Semptra** [microsoftgraph/msgraph-sdk-dotnet#2254]
**Describe the bug**
We are using the following request to list all users with specified filter:

```csharp
var usersResponse = await graphServiceClient.Users.GetAsync(requestConfiguration =>
{
    requestConfiguration.QueryParameters.Select = new string[] { "id", "displayName", "userPrincipalName" };
    requestConfiguration.QueryParameters.Filter = "accountEnabled eq true";
    requestConfiguration.QueryParameters.Top = 50;
});

var users = new List<User>();

var usersPageIterator = PageIterator<User, UserCollectionResponse>.CreatePageIterator(
    graphServiceClient,
    usersResponse,
    (user) =>
    {
        users.Add(user);
        return true;
    });

await usersPageIterator.IterateAsync();
```

Sometimes, on large tenants, we are getting the following error:

```json
{
    "code":"Directory_ExpiredPageToken",
    "message":"The specified page token value has expired and can no longer be included in your request."
}
```

I cannot find any Microsoft documentation that specifies in which case `Directory_ExpiredPageToken` error code can be returned.

Based on [Advanced query capabilities on Microsoft Entra ID objects](https://learn.microsoft.com/en-us/graph/aad-advanced-queries) article, using the `$filter` query parameter does not require setting the `ConsistencyLevel = eventual` header when used with the non-advanced queries:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/43088712/bcf414ed-d3c9-4e5b-a3a2-517c9d6ef065)

It is also stated in the same article that the `$filter` operator works by default for `accountEnabled` property of User with the combination of `eq` operator:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/43088712/7f71111b-7e8f-4f37-b8be-61ddb715fde6)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/43088712/b83c6062-4a7b-430f-967e-b1749a00f72d)

I also searched thought the Microsoft documentation about the lifecycle of the `skiptoken`, but it seems like it doesn't have one.

I cannot consistently reproduce this error, since the request with pagination seems to be working fine on some tenants and fail on others.

So, what am I missing? Is the documentation wrong or missing some information about `$filter` and pagination combination? Should I include the `ConsistencyLevel = eventual` header and `$count=true` query parameter to my request to fix this issue?

Thanks.

**Comment by andrueastman** [comment]
Thanks for raising this @Semptra 

As this question is related to API functionality/behaviour, we may not be best placed to answer this as this repo is mainly intended for client/SDK related issues. Any chance you can post the question at the link below so as to get feedback from the API owners who may be better placed to answer? 
It would be great if you could post a link of the question as a comment back here so that anyone who has a similar question may be able to find it too. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by Semptra** [comment]
Here is the link to the question I asked on Microsoft Learn portal - https://learn.microsoft.com/en-us/answers/questions/1462649/directory-expiredpagetoken-error-when-paginating-u

**Comment by andrueastman** [comment]
Thanks for this @Semptra. We'll close this for now so that it may be followed up on that side.
