### ISSUE TITLE
Get and List deviceEnrollmentPlatformRestrictionsConfiguration v1.0 not returning odatatype

### ISSUE THREAD

**Issue by Dethras** [microsoftgraph/msgraph-sdk-dotnet#2259]
**Describe the bug**
When calling the Get/List deviceEnrollmentPlatformRestrictionsConfiguration (Rest call:" **GET /deviceManagement/deviceEnrollmentConfigurations**) a list of deviceEnrollmentConfigurations are being returned. I have observed the following:

- Beta (correct): deviceEnrollmentPlatformRestrictionsConfigurations objects are returned **with** an odatatype
- V1.0 (incorrect): deviceEnrollmentPlatformRestrictionsConfigurations objects are returned **without** an odatatype

Note: I have also tested this using Graph Explorer, and the same happened there so I presume the issue is within the Graph API (Opened ticket here since I didn't know where to open the ticket for the Graph API)

**To Reproduce**
1. Go to Graph Explorer and login to your tenant
2. Call : https://graph.microsoft.com/beta/devicemanagement/DeviceEnrollmentConfigurations
3. Check that you have an object with deviceEnrollmentPlatformRestrictionsConfiguration  odatatype
4. Note down the Id of above deviceEnrollmentPlatformRestrictionsConfiguration 
5. Call : https://graph.microsoft.com/v1.0/devicemanagement/DeviceEnrollmentConfigurations
6. Search for the deviceEnrollmentPlatformRestrictionsConfiguration Id noted in step 4
7. Look for the odatatype, which for me it is not being returned

**Expected behavior**
The v1.0 call should return the odatatype for ALL deviceEnrollmentConfiguration objects (In this case I only found that the only one missing is deviceEnrollmentPlatformRestrictionsConfiguration )

**Screenshots**
Beta (correct):
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/5582989/b3b9f31a-4252-4bb1-b4a7-49225e2b6df5)

V1.0 (incorrect):
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/5582989/ca1ddb63-3d9a-4c7e-9f4f-2b68dea0e036)

**Comment by andrueastman** [comment]
Thanks for raising this @Dethras 

As this is indeed an API issue and this repo is mainly intended for SDK related issues, any chance you can create an issue at the link below so that the API owners may get visibility into this. It would be great if you could post back the link to the same here so that anyone else who has a similar issue may find it. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by Dethras** [comment]
Feedback opened: https://feedbackportal.microsoft.com/feedback/idea/b2a6ed65-699e-ee11-92bd-0022484eec36
