### ISSUE TITLE
[Client bug]: Microsoft.Graph.Users.Item.CalendarGroups.Item.Calendars.Item.CalendarView.CalendarViewRequestBuilder.CalendarViewRequestBuilderGetQueryParameters no StartTime/EndTime option

### ISSUE THREAD

**Issue by cyuz** [microsoftgraph/msgraph-sdk-dotnet#2263]
I'm using 5.37.0 graph sdk

To get a user's calendar in a specific calendarGroup.
`
GET /users/{id | userPrincipalName}/calendarGroups/{id}/calendars/{id}/calendarView?startDateTime={start_datetime}&endDateTime={end_datetime}
`
If I do same behavior via c# 
`
client.Users[idOrEmail].CalendarGroups[group.ID].Calendars[calendarId].CalendarView.GetAsync();
`
I will got "This request requires a time window specified by the query string parameters StartDateTime and EndDateTime." exception

But Microsoft.Graph.Users.Item.CalendarGroups.Item.Calendars.Item.CalendarView.CalendarViewRequestBuilder.CalendarViewRequestBuilderGetQueryParameters Class do not have StartDateTime and EndDateTime options

**Comment by andrueastman** [comment]
Thanks for raising this @cyuz 

This is a metadata issue that is causing the missing query parameters in the SDK. Tracking this via https://github.com/microsoftgraph/msgraph-metadata/issues/538
