### ISSUE TITLE
[Question] Reading in runtime access tokens from table, and then calling api calls with different tokens/users

### ISSUE THREAD

**Issue by stefancvetkovic** [microsoftgraph/msgraph-sdk-dotnet#2264]
Hello,

I want to sync my .net calendar to office365 calendar. 
I will use:
- standard http endpoint and authorization code flow for obtaining access token and refresh token
- these token then I will store at my db
- after that, when it comes request (because its azure function), I need to perform some operation, for example to create a new Event on Calendar365.
- I will get my token, or refresh token from db and use GraphApi SDK in order to obtain these data.

Now I discovered how to pass accessToken and initialize a GraphServiceClient:
```
public GraphServiceClient GetAuthenticatedGraphClient(string accessToken)
{
    if (!string.IsNullOrEmpty(accessToken))
    {
        return new GraphServiceClient(new AuthenticationProvider(accessToken));
    }
    else
    {
        throw new Exception("AccessToken is not populated.");
    }
}
```

So for each recevied event from my local queue, I need to trigger some method which will for some particular user grab the token, and call GraphAPI.
Should I go for Singleton instance and then just re-enter the access token? any concerns about that?
Is there a way to put in builder service some code which tells application to obtain the code automaticaly?
Thanks

**Comment by andrueastman** [comment]
Apologise for the delayed response @stefancvetkovic 

I believe the Identity.Web library is best suited for such scenarios as it supports token serialization and intergrates well with this library. 

Any chance you've taken a look at the docs at https://github.com/AzureAD/microsoft-identity-web/wiki
