### ISSUE TITLE
IncludeTargets missing from Fido2AuthenticationMethodConfiguration

### ISSUE THREAD

**Issue by delepster** [microsoftgraph/msgraph-sdk-dotnet#2279]
**Describe the bug**
Property `Fido2AuthenticationMethodConfiguration.IncludeTargets` lost when updating from version 5.50.0-preview to 5.60.0-preview. Even though the odata property is present in the HTTP request

**To Reproduce**
1. update the package
2. rebuild the application which accesses `IncludeTargets

**Expected behavior**
The property should be accessible.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version 5.60.0-preview

**Comment by andrueastman** [comment]
Thanks for raising this @delepster 

We'll close this for now as this does not affect the v1 sdk. Property is available in v1 models at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/29c7e1e1146fc2c2ce84ebe96e5cf825562ddada/src/Microsoft.Graph/Generated/Models/Fido2AuthenticationMethodConfiguration.cs#L18

Tracking beta issue via https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/788
