### ISSUE TITLE
LargeFileUploadTask - How to get error if UploadSucceeded is "false"

### ISSUE THREAD

**Issue by eprach** [microsoftgraph/msgraph-sdk-dotnet#2282]
Hi Team,

I develop an application to save files to SharePoint. Below part of my code:

```
int maxSliceSize = 320 * 1024;
var fileUploadTask = new LargeFileUploadTask<DriveItem>(
    uploadSession, fileStream, maxSliceSize, graphClient.RequestAdapter);

var totalLength = fileStream.Length;

// Upload the file
var uploadResult = await fileUploadTask.UploadAsync();
```

In my environment it works well, uploadResult.UploadSuceeded is true, wonderful world. But, sometimes uploadResult.UploadSuceeded is false and file is not uploaded.

My question is: How can I get the reason why the upload didn't work well to log it or take actions accordingly? Try/catch doesn't work as my request is properly formatted.

By checking the post here => https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp it logs only "Upload failed" which is, from a user / debug point of view, totally not useful.

I know that I can do a retry with ResumeAsync() method but it changes nothing.

Thanks a lot for your help!

**Comment by andrueastman** [comment]
Thanks for raising this @eprach 

Just to confirm, there is no exception thrown in the event that  `uploadResult.UploadSuceeded` is false? Ideally, an API error should  have occured to result in a 4xx or 5xx status code to cause this. 
Any chance you can share the values of the other properties in the `uploadResult ` object when the result is false?
