### ISSUE TITLE
Getting an Invalid Request when creating UploadSession

### ISSUE THREAD

**Issue by BugmanMasterXTR** [microsoftgraph/msgraph-sdk-dotnet#2283]
We are using the LargeFileUpoloadTask code upload a file to SharePoint.  When PostAsync is called, this exception is returned;

[22:01:01 ERR] An unhandled exception has occurred while executing the request.
Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
2
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
 
We got the same error when we coded the upload without using LargeFileUploadTask.  

```
    public async Task<UploadFileResult> UploadFile(UploadFileRequest request)
    {
.....
        Dictionary<string, object> additionalData = new Dictionary<string, object>
        {
            { "@microsoft.graph.conflictBehavior", "replace" },
            { "Title", "New Title" }
        };

        var uploadSessionRequestBody = new CreateUploadSessionPostRequestBody
        {
            Item = new Microsoft.Graph.Models.DriveItemUploadableProperties
            {
                AdditionalData = additionalData
            }
        };

        var uploadSession = await graphClient.Drives[driveId]
            .Items[itemId]
            .ItemWithPath(request.FileName)
            .CreateUploadSession
            .PostAsync(uploadSessionRequestBody);
```
If we use this additionalData, PostAsync returns the expected result, and the file is uploaded.
```
        Dictionary<string, object> additionalData = new Dictionary<string, object>
        {
            { "@microsoft.graph.conflictBehavior", "replace" },
            { "title", "New Title" }
        };
```
If we put any of our custom SharePoint columns in as additionalData, we get the exception. The request passed to the method has the file embedded as a memory stream so there is path for the file.

I've tried every combination of @microsoft and @odata entries and various different column names, none have made a difference.

We are using Microsoft.Graph version 5.36.0 and .NET6

**Comment by andrueastman** [comment]
Thanks for raising this @BugmanMasterXTR 

According to the documentation, I don't think it's expected to pass any extra properties to the `CreateUploadSession` request except the ones outlined in the docs. 

```json
{
  "@microsoft.graph.conflictBehavior": "fail (default) | replace | rename",
  "description": "description",
  "fileSize": 1234,
  "name": "filename.txt"
}
```

- https://learn.microsoft.com/en-us/graph/api/resources/driveitemuploadableproperties?view=graph-rest-1.0
- https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request-body

Any chance you can confirm what the intent would be to pass the columns as the properties here are meant for the upload session?

**Comment by BugmanMasterXTR** [comment]
I want to attach metadata to the file and was thinking that seemed like the logical place to do it.  When uploading a file without the LargeFileUploadTask it takes a second step to push the metadata.  I was trying to use this additionalData object to pass in the files details, accomplishing both the file upload and metadata upload at the same time.

From your comment and reading through the docs, again, it looks like I've going at this wrong.  I think that I need to look at Item Update as a second step the file upload.

using Microsoft.Graph.Models;

var requestBody = new FieldValueSet
{
	AdditionalData = new Dictionary<string, object>
	{
            { "Title", "New Title" },
            { "Source", "Sourec1New Title" },
	},
};

var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items["{listItem-id}"].Fields.PatchAsync(requestBody);

**Comment by andrueastman** [comment]
I'm not sure it would be possible to do this in one step. However, you can post the question at the link below to get guidance from the API owners. As this repo is mainly intended for SDK related issues, we may not be best placed to answer all API related questions.

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

We'll close this for now. Please re-open incase of any issue.
