### ISSUE TITLE
CVE fix in dependency: Update msgraph-sdk-dotnet-core to 3.1.5 

### ISSUE THREAD

**Issue by SymbioticKilla** [microsoftgraph/msgraph-sdk-dotnet#2292]
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/releases/tag/3.1.5

Hi,

can you please release a new version with updated msgraph-sdk-dotnet-core?

Thanks!

**Comment by andrueastman** [comment]
Thanks for raising this @SymbioticKilla 

This will be resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2293
