### ISSUE TITLE
Null values are included in the request body

### ISSUE THREAD

**Issue by hadrian625** [microsoftgraph/msgraph-sdk-dotnet#2298]
**Describe the bug**
We are using the dotnet core library Microsoft.Graph 5.38.0 to update user data in a Azure B2C tenant
According to documentation, if we use null values for fields in User entity, those values should not be changed.
But it is not correct. Instead the null values are actually set on the fields in question (ex. GivenName, Surname), which results in resetting the values for those fields

**To Reproduce**
1. Create a User entity for a partial update like 
     var user = new User { Surname = null, City = "MyCity"  }
2. Execute a patch operation with this user like
    _graphServiceClient
      .Users[<userid>]
      .PatchAsync(user);
3. Retrieve the updated user from B2C with a GetAsync call. The returned User has the Surname now set to null, thus losing the non-null value previously set.

**Expected behavior**
The null values should not be passed in the request body for the PATCH operation, in order to keep the values that are not intended to be changed during the PATCH requests

**Desktop (please complete the following information):**
 - OS: Window 11
 - Browser N/A
 - Version Microsoft.Graph 5.38.0

**Additional information**
Looking in source code I saw that the User model is backed by a IBackingStore, which I assume that will include the null values for each set of a property, thus when the PATCH request body is composed from that IBackingStore, the fields that were set with null values will be included in the body of request. 
I found that I have to not set at all the fields that are null, in order to have the expected behaviour
Ex:
User user = new User();
if (givenName != null) {
  user.GivenName = givenName
}
I think this is counter intuitive and not mentioned anywhere in a documentation
Either the behavior should be changed, or add proper visible documentation for it.

**Comment by hadrian625** [comment]
Thanks a lot for the quick reply.
In the light of what I found looking into how the User model is using the IBackingStore, the provided link makes total sense.
My concern is that for a developer that uses documentation like https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http might not see this as obvious.
It is said for the http request
_"In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance you shouldn't include existing values that haven't changed_."

But it does not clearly says that if you actually assign a null to such a field, that null value will actually be set on the field. This is particularly misleading for C# at least.
I don't know if you want to add a express remark for this scenario. Something like: "Important: Setting any field to a null value, will actually set that field to null in Graph API. If you don't want to change the existing value of a field, do not do any assignment to it."

In the end, even this issue, with your reply might prove useful for others in the future.

**Comment by andrueastman** [comment]
> I don't know if you want to add a express remark for this scenario. Something like: "Important: Setting any field to a null value, will actually set that field to null in Graph API. If you don't want to change the existing value of a field, do not do any assignment to it."

I'm not sure about putting a global statement like this as an API endpoint may have properties that do not support setting null values on them. At the moment, I believe it may be best to keep the documentation of the SDK behavior elaborated in the guide and we are happy to take contributions/improvements to it. 

We'll close this issue for now. Please re-open/create new one incase of any other questions issues.

**Comment by stijnherreman** [comment]
For reference purposes: this can cause issues when sending an email (reply). If you set set `Message.Body` to something, then set it to `null` and include `Comment` in the request, you will get the following error:

> Multiple parameters pointing to the same property were found in the request payload. Specifiy either 'Comment' or 'Body' property of the message object.

In v4 this worked because there was no backing store. The fix is to set either `Body` or `Comment` correctly from the get-go, instead of clearing it later in the flow.
