### ISSUE TITLE
Storing/Retrieving Messages Delta Token for later use

### ISSUE THREAD

**Issue by RickL1234** [microsoftgraph/msgraph-sdk-dotnet#2299]
I am struggling to figure out how to use the Graph client to store a Messages Delta Token in a database and then retrieve it and send it to the Graph API to retrieve any messages with attachments that have come in since the last time the console app I am writing was run.  The console app will be the first step in a Microsoft SQL Server job agent job that will run once a day.

I can get the Messages delta token, store it and retrieve it, but I can't figure out what to do with it after that.

I am using:

Visual Studio 2022 - 17.4.15

Microsoft.Graph - 5.39.0

Microsoft.Graph.Core 3.1.5

This is a portion of the code I am having trouble with:

`// Get email attachments

            //var messagesResponse = graphClient.Users[strUser].MailFolders[strMailFolder].Messages.GetAsync((requestConfiguration) =>
            var messagesResponse = await graphClient.Users[strUser].MailFolders[strMailFolder].Messages.Delta.GetAsDeltaGetResponseAsync(requestConfiguration =>
            {

                    requestConfiguration.QueryParameters.Filter = "hasAttachments eq true";

                    requestConfiguration.QueryParameters.Expand = new string[] { "attachments" };

                    requestConfiguration.QueryParameters.Select = new string[] { "ReceivedDateTime", "hasAttachments", "Subject" };

                    //requestConfiguration.QueryParameters.Top = 2;

                }).Result;

            var messageList = new List<Message>();

            var pageIterator = PageIterator<Message, MessageCollectionResponse>.CreatePageIterator(graphClient, messagesResponse, (message) =>
                                                                                {

                                                                                    //Console.WriteLine(message.Subject);

                                                                                    messageList.Add(message);

                                                                                    return true;

                                                                                });

            await pageIterator.IterateAsync();

            while (pageIterator.State != PagingState.Complete)

            {

                await pageIterator.IterateAsync();

            }`

I do not see any QueryParameters methods that would take a delta token.  It also appears that QueryParameters.Expand is not supported for Messages delta calls.  Can anyone suggest a solution?

Thanks,
Rick L.

**Comment by andrueastman** [comment]
Thanks for raising this @RickL1234 

As captured in the guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests), the $deltaToken isn't a query parameter and the entire nextlink/deltaLink url is meant to be opaque. 

Using the url(that contains the token and other params), you can use the `WithUrl` method in the request builder to get a new page of results and use it with the PageIterator. 

```cs
var messagesResponse = await graphClient.Users["user-d"].MailFolders["mailfolder"].Messages.Delta.WithUrl("https://graph.microsoft.com/v1.0/me/mailFolders/delta?$skiptoken={_skipToken_}").GetAsync();
```

**Comment by RickL1234** [comment]
requestConfiguration.QueryParameters.Expand is not supported when using the delta endpoint.  How do I get the attachments?

Thanks,
Rick L.

**Comment by andrueastman** [comment]
> Two issues with this:
> 
> 1. The syntax you used is being marked as Obsolete.  What is the correct syntax?
> 2. requestConfiguration.QueryParameters.Expand is not supported when using the delta endpoint.  How do I get the attachments?
> 
> Thanks, Rick L.

1. You're right. The `GetAsync` method should be replaced with `GetAsDeltaGetResponseAsync`.
```cs
var messagesResponse = await graphClient.Users["user-d"].MailFolders["mailfolder"].Messages.Delta.WithUrl("https://graph.microsoft.com/v1.0/me/mailFolders/delta?$skiptoken={_skipToken_}").GetAsDeltaGetResponseAsync();
```
2. Looks like the metadata is missing the expand parameter for the path. https://github.com/microsoftgraph/msgraph-metadata/issues/562 should resolve this. In the meantime, you can still create a URL string with the parameters you need and still use the `WithUrl` method as describe above.

**Comment by MartinM85** [comment]
The same issue is probably for user delta, no way to set skipToken

**Comment by RickL1234** [comment]
I figured out how to get the attachments, but it requires another call to the API with the Message.id retrieved during the initial Messages.Delta call.  Seems inefficient to me, but it works.  $Expand should really be available when using Messages.Delta.

Thanks for your help, Rick L.
