### ISSUE TITLE
[Client bug]: Users.GetAsync behave differently for v4 and v5 sdk 

### ISSUE THREAD

**Issue by dmytro-formpipe** [microsoftgraph/msgraph-sdk-dotnet#2302]
**Describe the bug**
Same code for v4 and v5 results in different behavior. Its simple snippet for search of user by its email.

Auth details:
Scopes: "User.ReadBasic.All", "Mail.ReadWrite"
var interactiveCredential = new InteractiveBrowserCredential(options);
graphClient = new GraphServiceClient(interactiveCredential, clientScopes);

-----

code for SDK v4. It works and finds user successfully.
```
string[] usersSelectProperties = new string[] { "id","mail","proxyAddresses" };
var res = await graphClient.Users
.Request()
.Select(usersSelectProperties)
.Filter("mail eq 'test@test.test' or proxyAddresses/any(c:c eq 'smtp:test@test.test')")
.GetAsync();
```

code for SDK v5. **Throws**:
"Insufficient privileges to complete the operation." Authorization_RequestDenied
```
string[] usersSelectProperties = new string[] { "id","mail","proxyAddresses" };

var res = await graphClient.Users
                    .GetAsync(requestConfiguration =>
                    {
                        requestConfiguration.QueryParameters.Select = usersSelectProperties;
                        requestConfiguration.QueryParameters.Filter = "mail eq 'test@test.test' or proxyAddresses/any(c:c eq 'smtp:test@test.test')";
                        requestConfiguration.QueryParameters.Count = true;
                        requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
                    }
                    )

```
Tried both with and without:
```
requestConfiguration.QueryParameters.Count = true;
requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
```

**Expected behavior**
Same for v4 and v5

**Client version**
Microsoft.Graph 5.40 vs Microsoft.Graph 4.54.0

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
RequestId: 9bd113b5-1420-4f22-86be-6b7ecfe35845
Client RequestId: e012a0be-3228-41bd-a03f-f7e5c5ca5cf1

**Comment by andrueastman** [comment]
Thanks for raising this @dmytro-formpipe 

Just to confirm, in both apps, are you using the same account to login as well as the same `clientid` parameters for the `InteractiveBrowserCredential`?

**Comment by dmytro-formpipe** [comment]
@andrueastman, thanks for response.
Yes, same account, same clientId.

**Comment by andrueastman** [comment]
Are you able to obatin the token as below and paste it over to http://jwt.ms and confirm if the right scopes are available in the `scp` property? 

```cs
            var res = graphClient.Users
                    .ToGetRequestInformation(requestConfiguration =>
                    {
                        requestConfiguration.QueryParameters.Select = usersSelectProperties;
                        requestConfiguration.QueryParameters.Filter = "mail eq 'test@test.test' or proxyAddresses/any(c:c eq 'smtp:test@test.test')";
                        requestConfiguration.QueryParameters.Count = true;
                        requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
                    }
                    );

            var nativeRequest = await graphClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(res);
            var token = nativeRequest.Headers.Authorization.Parameter;

```
