### ISSUE TITLE
NullReferenceException when calling ServiceException.IsMatch(string) 

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#2303]
Hello,

When the ClientSecret is expired and I call `serviceException.IsMatch("Error")` I get an uncaught NullReferenceException. I guess either the `Message` or the `RawResponseData` is missing (probably the latter) since they're called without a `null` check first.  Is this intended?
(I'm using Graph SDK Version 5.38.0)

Trace:
```
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Graph.ServiceException.IsMatch(String errorCode)
```

My Call:
```csharp
serviceException.IsMatch(ErrorCodeConstants.ITEM_NOT_FOUND) //this can't be null
```

Thanks in advance.

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

Out of curiosity any chance you can share a code sample of the context in which the `ServiceException` is thrown? Are you using the pageIterator/LargeFileUploadTask?

**Comment by Danny4021** [comment]
Hello @andrueastman 
Thanks for the quick response.
I throw the `ServiceException` myself, since I have to wrap an unexpected `HttpRequestException` thrown by the `TokenProvider`.
Upon further investigation I found that the constructor I use (`string message, Exception innerException`) for the `ServiceException` sets the `RawResponseData` to `null`, which is something I didn't expect, so I guess this one is my bad.
Still, I wouldn't expect this to throw a `NullReferenceException` when I call the `IsMatch` method.
So wouldn't it be better to check `RawResponseData` for `null` in the `IsMatch` method, if it can be `null` sometimes?
If this isn't possible I'll use another constructor.

Thanks in advance!

**Comment by andrueastman** [comment]
Thanks for the feedback here @Danny4021 

Would you be willing to submit a PR to add those validations? The relevant code is available at https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/797c7308c95a9b8b02de24733096c764a82a4ee0/src/Microsoft.Graph.Core/Exceptions/ServiceException.cs#L79

**Comment by Danny4021** [comment]
Hello @andrueastman 
I've tried to create a new branch (namely `bugfix/2303-fix-nre-in-service-exception`) and push the changes I've made to it. But I get an unauthorized error:
```
remote: Permission to microsoftgraph/msgraph-sdk-dotnet-core.git denied to Danny4021.
fatal: unable to access 'https://github.com/microsoftgraph/msgraph-sdk-dotnet-core.git/': The requested URL returned error: 403
```
Did I do something wrong or is it possible to provide me the necessary permissions?

Thanks in advance!

**Comment by andrueastman** [comment]
@Danny4021 You should be able to [fork](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/fork) the repo and then create a PR from you own fork.
