### ISSUE TITLE
GraphServiceClient.Users.GetAsync() returns null for Identities and onPremisesExtensionAttributes

### ISSUE THREAD

**Issue by drewid** [microsoftgraph/msgraph-sdk-dotnet#2305]
**Describe the bug**
For the same UserId in both cases...

When doing a regular/default query GraphServiceClient.Users.GetAsync() it is returning a value of **null** for onPremisesExtensionAttributes when there are known existing values. 

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/0b171eca-de74-4ee9-a2e7-191f5c1be871)

Only when using QueryParameter.Select that explicitly includes the field onPremisesExtensionAttributes do the existing results display

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/bf0a96c8-9dd9-4467-9a43-ce94fbd05af1)

**To Reproduce**

**IDE Setup**
- Visual Studio 17.8.3
- .NET 8.0 C# command line project

**Expected behavior**
If data exists in onPremisesExtensionAttributes then the data is displayed when getting user information instead of null.  

Should not require explicitly returning that field to display the data. Is already returning that field but with null (bug).

**Steps**
- Created a GraphClient _graphClient (success)
- Added values to a user for ExtensionAttribute1 and ExtensionAttribute2 (success)

- Run GraphClient.Users[UserId].GetAsync() - returns null for onPremisesExtensionAttributes (_failure_)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/62582f24-48bb-4cf2-957f-c77f039c7dd6)

- Run GraphClient.Users[UserId].GetAsync() with onPremisesExtensionAttributes explicitly supplied in QueryParameters.Select (_success_)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/215cb376-c819-41a2-ad16-fc8c6c7ff2a8)

**Code**
The following code returns **null** for onPremisesExtensionAttributes when running the basic user query:

`_graphClient.Users[UserId].GetAsync();`

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/0b171eca-de74-4ee9-a2e7-191f5c1be871)

The following code returns expected values for onPremisesExtensionAttributes when adding the explicitly select parameter (_but has the bug where every field is returned_)

`requestConfiguration.QueryParameters.Select = new string[] { "id", "displayName", "onPremisesExtensionAttributes" };`

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/bf0a96c8-9dd9-4467-9a43-ce94fbd05af1)

**Comment by drewid** [comment]
This is also occurring for **Identities** as well.  Seeing the same exact symptoms/results.

When running the default query **Identities** says null; when explicitly selecting the values the results are displayed.

**Comment by drewid** [comment]
Select logic in general seems to be broken for returning user details.

1) Granular details are not being returned when running a general user details query.
2) All fields are being returned when you do select query parameters (ticket 2304). Is not respecting the "only return the values selected" logic that is described in the documentation.
3) But for some reason when you do specify the particular fields it is pulling the full details for the field.

Something visible to relate to.  When in the Azure portal and looking at user details.  For the Identity field it displays something like **mail** or **google.com** when there is an Identity, as opposed to just null/empty.  I would expect there to be at least "something" besides a null value to return on a general query.  It is extremely misleading, and dangerous.

**Comment by andrueastman** [comment]
Thanks for raising this @drewid 

The API will only return a[ limited number](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#optional-query-parameters) of properties by default and thus the $select parameter is required to fetch those properties. 
With regards to displaying the results, the models used by the SDK should be serialized as pointed at [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2304#issuecomment-1914088425)due to the custom serialization.

**Comment by drewid** [comment]
@andrueastman thank you for the information but this behavior "does" need to be corrected.

**Returning a null value for OnPremisesExtensionAttributes and Identities**:
This is not correct behavior and is misleading.  It should either a) not be returned at all or b) return something other than null to indicate there is data present. That is standard practice for indicating further querying is needed for details.

**Identities** should also be called out then in Optional Query Parameters as well.

**Comment by andrueastman** [comment]
> Identities should also be called out then in Optional Query Parameters as well.

I believe the API docs state that only `businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, userPrincipalName` are returned by default. 

> This is not correct behavior and is misleading. It should either a) not be returned at all or b) return something other than null to indicate there is data present. That is standard practice for indicating further querying is needed for details.

Any chance you can replicate this on [the graph explorer](http://aka.ms/ge)?
