### ISSUE TITLE
GraphServiceClient.Users.GetAsync() returns nothing or non-helpful value for Schema Extension Data

### ISSUE THREAD

**Issue by drewid** [microsoftgraph/msgraph-sdk-dotnet#2308]
**Describe the bug**
Very related to Issue #2305 when running the standard query and "not" explicitly including the schema extension data, nothing is returned for the schema extension data.  One step more problematic than #2305 is when the schema extension **_is_** explicitly requested it returns non-helpful data instead of the actual data stored and that the documentation is referring to.

When doing a regular/default query **GraphServiceClient.Users.GetAsync()** it is returning no extension data field/value/reference of any kind and only non-helpful data when the Schema Extension item is explicitly supplied by **QueryParameter.Select** 

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/e247dd17-066f-4137-af05-7e43302c8089)

**To Reproduce**

**IDE Setup**
- Visual Studio 17.8.3
- .NET 8.0 C# command line project

**Expected behavior**
**Issue 1**
If data exists in the specified Schema Extension for the user, the data should be returned by the default query. 
Should not require explicitly returning that field to display the data.

**Issue 2**
If data exists in the specified Schema Extension for the user, the actual field values should be returned when explicitly requesting the schema extension data using QueryParameter.Select

**Steps**
- Created a GraphClient _graphClient (success)
- Added values to a user for the Schema Extension (success)

- Run GraphClient.Users[UserId].GetAsync() - returns nothing for schema extension (_failure_)

- Run GraphClient.Users[UserId].GetAsync() with schema extension explicitly supplied in QueryParameters.Select (_success_ but also _failure_)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/e247dd17-066f-4137-af05-7e43302c8089)

**Code**
The following code returns no field/value/reference for an existing schema extension data when running the basic user query:

`_graphClient.Users[UserId].GetAsync();`

The following code returns a non-helpful, non-informational value for the schema extension data when adding the explicitly select parameter (_but has the bug where every field is returned_)

`requestConfiguration.QueryParameters.Select = new string[] { "id", "displayName", "domain_schemaextensionname" };`

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/375184/e247dd17-066f-4137-af05-7e43302c8089)

**Comment by drewid** [comment]
Linked and directly related to #2305

**Comment by andrueastman** [comment]
Thanks for raising this @drewid 

The API will only return a[ limited number](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#optional-query-parameters) of properties by default and thus the $select parameter is required to fetch those properties. 
With regards to displaying the results, the models used by the SDK should be serialized as pointed at [here ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2304#issuecomment-1914088425)due to the custom serialization.

Any chance you can confirm this resolves it?

**Comment by drewid** [comment]
I will look into things further but if more work/serialization is needed then core graph documentation and examples needs to be seriously updated as it is very wrong.

**Comment by drewid** [comment]
Is strange that regular serialization does not work and only works with KiotaJsonSerializer.  This is not documented anywhere obvious.

**Comment by andrueastman** [comment]
Thanks for confirming @drewid . Since this is related to the discussion in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2304. We will close this and follow this up there
