### ISSUE TITLE
Post/Patch requests do not work when using Automapper / setting manually properties to null

### ISSUE THREAD

**Issue by OrestLegin** [microsoftgraph/msgraph-sdk-dotnet#2314]
**Describe the bug**
When I try to map my entity to Microsoft.Graph.User and perform POST/PATCH Request
E.g. ODataError is thrown with exception "The following properties cannot be set in the initial POST request. Please set them in a subsequent PATCH request: mySite."
Or in case with PATCH - "The request is currently not supported on the targeted entity set"

After some time, I found out about BackingStore object inside User object, which had all of the properties included in my mapping inside the "store" property, despite most of them were null in the User's properties.
In case of POST request, this object in store `{[mySite, {(True, )}]}` causes the error (the MySite property is null in User object).

**To Reproduce**
1. Prepare the mapping from model to Microsoft.Graph.User using Automapper
2. Perform the request like this:
```
 var msGraphUser = new User
  {
      AccountEnabled = true,
      PasswordProfile = new PasswordProfile
      {
          ForceChangePasswordNextSignIn = true,
          Password = Guid.NewGuid().ToString()
      },
      DisplayName = entity.DisplayName,
      MailNickname = entity.ExternalId,
      UserPrincipalName = entity.UserName,
  };
  _mapper.Map(entity, msGraphUser); //mapping other properties

  var adUser = await _graphClient
      .Users.PostAsync(msGraphUser, null, token);
```
**UPD:** Without Automapper, the issue can be reproduced as well like this:
```
var msGraphUser = new User
{
    AccountEnabled = true,
    PasswordProfile = new PasswordProfile
    {
        ForceChangePasswordNextSignIn = true,
        Password = Guid.NewGuid().ToString()
    },
    DisplayName = entity.DisplayName,
    MailNickname = entity.ExternalId,
    UserPrincipalName = entity.UserName
};
msGraphUser.MySite = null; // BackingStore still triggers that and causes the error
var adUser = await _graphClient.Users.PostAsync(msGraphUser, null, token);
```

**Expected behavior**
null properties after mapping with Automapper/assigning manually should not be triggered and causing issues for requests

**Comment by andrueastman** [comment]
Thanks for raising this @OrestLegin 

The tracking of null values by the backing store in the SDK is documented at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#backing-store in order for values to be included in the final payload. 

See more at https://learn.microsoft.com/en-us/openapi/kiota/backing-store

To resolve the compatibility with using AutoMapper, it may be useful to look into conditional mapping as documented at https://docs.automapper.org/en/stable/Conditional-mapping.html#conditional-mapping or reset the store with something like this.

```cs
msGraphUser.BackingStore.InitializationCompleted = false; 
```
