### ISSUE TITLE
GraphServiceClient.Me.Messages.SendMail.PostAsync ignores setting messageId via SingleValueExtendedProperties

### ISSUE THREAD

**Issue by 6heads** [microsoftgraph/msgraph-sdk-dotnet#2320]
**Describe the bug**
Setting the message Id using graph explorer like this works:
![grafik](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/46749895/c1c81633-dad6-4b12-872e-c0b202d28662)
![grafik](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/46749895/ee336ba8-c1a4-4f68-bd5f-dc3a5f4c8a57)

If I however do the same using the api the message id isn't set.

**To Reproduce**

1. Configure application in azure, set delegated permission for microsoft graph "Mail.Send" and grant admin consent
![grafik](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/46749895/a2d3c867-c30c-4e9d-a0d8-2e7a5af2b803)

2. Set values for UsernamePasswortCredential:

            var options = new TokenCredentialOptions { AuthorityHost = AzureAuthorityHosts.AzurePublicCloud };
            var credentials = new UsernamePasswordCredential(configuration.EmailAddress, configuration.Password, 
                configuration.TenantId, configuration.ClientId, options);

3. initialize GraphServiceClient:

            var graphClient = new GraphServiceClient(credentials, new[] { "https://graph.microsoft.com/.default" });

4. Set body with message id 

            var body2 = new Microsoft.Graph.Me.SendMail.SendMailPostRequestBody
            {
                Message = new Message
                {
                    Subject = "Meet for lunch (from sdk)?",
                    Body = new ItemBody
                    {
                        ContentType = BodyType.Text,
                        Content = "The new cafeteria is open."
                    },
                    ToRecipients = new List<Recipient> 
                    {
                        new Recipient 
                        { 
                            EmailAddress = new EmailAddress { Address = "some@mail.com" }
                        } 
                    },
                    SingleValueExtendedProperties = new List<SingleValueLegacyExtendedProperty> //this should set message id
                    {
                        new SingleValueLegacyExtendedProperty
                        {
                            Id = "String 0x0135",
                            Value = "DUBR48WV7MU4.2NENKIJQD4NK3@mydomain.com"
                        }
                    }
                }
            };

5. Send mail:

            await graphClient.Me.SendMail.PostAsync(body2);

**Expected behavior**
SendMail should have a custom message id set.

**Screenshots**
![grafik](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/46749895/0debe0ff-e9bb-4018-af4c-29dd0007d792)

**Client version**
5.41.0

**Desktop (please complete the following information):**
N/A

**Additional context**
If this is a bug on your side I'd be interested in a workaround.

**Comment by andrueastman** [comment]
Thanks for raising this @6heads, 

The payload generated by the SDK for the given example is as below
```json
{
    "Message": {
        "@odata.type": "#microsoft.graph.message",
        "body": {
            "content": "The new cafeteria is open.",
            "contentType": "text"
        },
        "singleValueExtendedProperties": [
            {
                "id": "String 0x0135",
                "value": "DUBR48WV7MU4.2NENKIJQD4NK3@mydomain.com"
            }
        ],
        "subject": "Meet for lunch (from sdk)?",
        "toRecipients": [
            {
                "emailAddress": {
                    "address": "some@mail.com"
                }
            }
        ]
    }
}
```

Any chance you can confirm that the payload above results in the same issue if you try send it via graph explorer?

**Comment by 6heads** [comment]
Sorry for wasting your time.
I used 0x0135 where 0x1035 was needed.

Maybe an extension would be nice to get rid of these magic strings.

**Comment by andrueastman** [comment]
Thanks for double checking. Closing this for now.
