### ISSUE TITLE
SDK 5 C# Users's fields in select and filters are ignored even though Graph Explorer it works fine.

### ISSUE THREAD

**Issue by mkgn** [microsoftgraph/msgraph-sdk-dotnet#2322]
In brief, the query simply returns the default fields.

**To Reproduce**

Make sure you have some values for each user in your tenant for below $select fields

First try below in Graph Explorer 

    https://graph.microsoft.com/v1.0/users?$count=true&$expand=manager&$filter=accountEnabled eq true&$select=employeeId,employeeType,accountEnabled,userPrincipalName,department,displayName,givenName

In Graph explorer the select provides values for properties if they exists for users.

Then get the c# code and do a simple test. The code I used is below

            var graph = await GetGraphServiceClientAsync(["User.Read"]);

            var response = await graph.Users.GetAsync(userReqOpt =>
            {
                userReqOpt.Headers.Add("ConsistencyLevel", "eventual");
                userReqOpt.QueryParameters.Count = true;
                userReqOpt.QueryParameters.Expand = new string[] { "manager" };
                userReqOpt.QueryParameters.Filter = "accountEnabled eq true";
                userReqOpt.QueryParameters.Select = new string[] { "employeeId", "employeeType", "accountEnabled", "userPrincipalName", "department", "displayName", "givenName" };

            });

             //Serialized the incoming response just to check the json
            response.BackingStore.InitializationCompleted = false;
            var jsonString = KiotaJsonSerializer.SerializeAsString(response);

See the JSON output screenshot below

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/8392595/5ac895fd-00e8-4543-bfa8-89c3a467f16d)

As you see only the default properties are there. The other requested properties accountEnabled, EmployeeType, Department not available and it has not filtered by accountEnabled either.

**Expected behavior**
It should honor Select & Filter clauses.

**Desktop (please complete the following information):**
 - OS: Windows 10 latest
 - Browser latest Edge

**Additional context**
The Graph Explorer this works fine but the code provided by the Graph Explorer doesn't work..

**Comment by MartinM85** [comment]
Maybe it's related to the scope

`var graph = await GetGraphServiceClientAsync(["User.Read"]);`

with `User.Read` delegated permission, you are able to read only small subset of properties.

Try to use `User.Read.All` if it will work.
