### ISSUE TITLE
Using Delegated Permission for Search Graph API in .Net C#

### ISSUE THREAD

**Issue by ayushhhCSharp** [microsoftgraph/msgraph-sdk-dotnet#2324]
Hi, 
I am making making Graph API calls in my WebAPI solution, for which we are granting Application permissions.
One of the Graph API we are calling is the Search Graph API, where in we are able to get the response for entity types, ListItem and Site. 
But when we make call for entity types, Person and Messages, we encounter the following exception:
"Application permission is only supported  for the following entity types: site, list, listitem, drive and driveitem."
Can someone guide me on how we can make for other entity types.
If we can use delegated permission in any way or if there is anyway to capture the current user context for Microsoft and then use delegated permissions.
Any help is appreciated.
Thank You.

**Comment by andrueastman** [comment]
Thanks for raising this @ayushhhCSharp 

Any chance using the `$search` query parameter on the `users` and messages endpoints work out for you? You can find more info at the link below. 
https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-message-collections
https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http#using-search-on-person-collections
