### ISSUE TITLE
Invalid JSON Response ('{' is invalid after a value) when Making Multiple Calls to Microsoft Graph API with .NET Graph API v4.50.0

### ISSUE THREAD

**Issue by dikshaparodkar** [microsoftgraph/msgraph-sdk-dotnet#2328]
**Issue Description**

When utilizing the .NET Graph API v4.50.0 to interact with the Microsoft Graph API, I intermittently encounter the following error message:

**'{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.value | LineNumber: 0 | BytePositionInLine: 82600422.**

**Steps to Reproduce**

1. Auto reply to email received using Microsoft Graph API.
2. When sending single email - **no issue**.
3. When we send multiple emails at same time - **I m getting error** - (separate API calls are made as we want to maintain same email thread).

**Expected Behavior**
The email should be sent successfully without encountering any errors, regardless of whether single email is send or multiple emails simultaneously.

**Actual Behavior**
Encounter an error when sending multiple emails at same using Microsoft Graph API, specifically when separate API calls are made to maintain the same email thread.

**Comment by andrueastman** [comment]
Thanks for raising this @dikshaparodkar 

Any chance you could share the API call(sample code) you are making when the error occurs? 
Also, are you by any chance able to capture the response body when the error occurs (it looks like the API may be returning invalid JSON)
