### ISSUE TITLE
Need support for composable functions in the client library

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#233]
The Excel workbook range functionality is broken beyond working with the range object. All navigation properties on the the Range object are not accessible with our request builders. 

### Expected behavior

var fontPatchObject = new WorkbookRangeFont { Italic = true }
..Worksheets[worksheetId].Range("A1").Format.Font.Request().PatchAsync(fontPatchObject);

### Actual behavior

await _client.Me.Drive.Items[fileId]
    .Workbook
    .Worksheets[worksheetId]
    .Range("A1")
    .Request()
    .PatchAsync(range);

### Steps to reproduce the behavior

https://stackoverflow.com/questions/48439317/can-change-style-of-the-excel-cell/48450006#48450006

1987284
 
[AB#7342](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7342)

**Comment by darrelmiller** [comment]
@MIchaelMainer This just got higher on our priority list because we are now publishing snippets that say this is possible.

**Comment by JuhaOl** [comment]
When will these functions be available? These are documented in Microsoft Graph Api but not available in SDK - asked about 2 years ago with no update in this issue.

**Comment by Filipowicz251** [comment]
Hi - btw, where are we with This issue ? :) First request about issue with it i saw somewhere on 2019....

**Comment by MIchaelMainer** [comment]
Thank you for reminding us that this is still important. I appreciate these bumps.

@ddyett

**Comment by ddyett** [comment]
thank you.  i've added this to the broader planning backlog.  i'll see what we can do.

**Comment by MIchaelMainer** [comment]
Related https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/291/files

**Comment by Filipowicz251** [comment]
@ddyett @MIchaelMainer  - nice it is added for JAVA. Will it be also added for c#? I've downloaded newest version and still have:

![obraz](https://user-images.githubusercontent.com/21036476/97496058-b510c380-1968-11eb-95b6-687ba7c7b5f3.png)

**Comment by MIchaelMainer** [comment]
@Filipowicz251 This is now supported in 3.22.0+

```
    await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                                        .Range()
                                                                        .Format
                                                                        .Fill
                                                                        .Request()
                                                                        .UpdateAsync(workbookRange);
```
