### ISSUE TITLE
Missing the delete function on deleted items

### ISSUE THREAD

**Issue by Ntenhove** [microsoftgraph/msgraph-sdk-dotnet#2340]
In the previous minor version i was able to permanently delete deteled items by using the following code: this.client.Directory.DeletedItems[id].DeleteAsync(); 

It looks like this isn't working anymore with the latest stable version. Is there any prospect of this being adjusted?

**Comment by andrueastman** [comment]
Thanks for raising this @Ntenhove 

This looks to be a regression caused by updates in the conversion library via https://github.com/microsoft/OpenAPI.NET.OData/issues/483. This should be resolved in the coming update once https://github.com/microsoftgraph/msgraph-metadata/issues/566 is closed
