### ISSUE TITLE
[Need assistance] Typecasting a DeviceConfiguration to a Windows10CustomConfiguration

### ISSUE THREAD

**Issue by dansmitt** [microsoftgraph/msgraph-sdk-dotnet#2343]
Hey,

I'm maybe completely wrong, but wasn't there a possibility to cast a parent object to its derived one? I thought that this was possible with the backingstore which holds all the properties.

For example, we want to offer an Interface which accepting all kind of DeviceConfigurations to stay generic, but in the second step, we want to copy a specific Windows10CustomConfiguration to another tenant, but with the same configurations. In that case, it would be easy if we just cast the DeviceConfiguration to the derived object, remove unnassacary properties and hit the specific creation endpoint.

Maybe I think to complex, but I thought this was possible.

**Comment by andrueastman** [comment]
Thanks for raising this @dansmitt 

If the payload is received from the API, the serializers should automatically downcast the types and you should be able to use simple casting/pattern matching as you suggested. 

```cs
var deviceConfig = // value received from API.
switch (deviceConfig)
{
    case Windows10CustomConfiguration customConfiguration:
        // do something with the downcast type.
    break;
}
```

For the various derived types of DeviceConfiguration, they can also be distinguished using the `OdataType` property which should match the values here.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/3de1dba3d0eb8b122ace08c9e7a13f03231fcff2/src/Microsoft.Graph/Generated/Models/DeviceConfiguration.cs#L148

 and you should be able to use that information as type parameter to pass to the serializer.

Let me know if this is helpful.

**Comment by dansmitt** [comment]
@andrueastman thanks for the fast reply. Its alwas a pleasure to discuss problems with you.

Good that I remember this.

Actual implementation:
```cs

    public async Task<DeviceConfiguration?> CreateDeviceConfigurationTenantDependentAsync(TenantEnvironment tenantEnvironment, DeviceConfiguration deviceConfiguration)
    {
        GraphServiceClient graphServiceClient = GetGraphServiceClientByEnvironment(tenantEnvironment);

        var deviceConfig = deviceConfiguration;

        switch (deviceConfig)
        {
            case Windows10CustomConfiguration customConfiguration:
                break;
        }

        return await graphServiceClient.DeviceManagement.DeviceConfigurations.PostAsync(deviceConfiguration);
    }
```

Breakpoint at the "break" will not be hit because it seems that the parsing was not successful.

Watch view: 
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/62943030/83bc527f-66b2-4e93-961c-fb1458da4c47)

**Comment by andrueastman** [comment]
Just to confirm @dansmitt 

Does the implementation of `GetGraphServiceClientByEnvironment` make a call to the API that invokes the serializer? Any chance you can share more details on where it builds the object from?

**Comment by dansmitt** [comment]
@andrueastman if you want we can schedule a short meeting and we will paste the result on here in the issue. How about this?

**Comment by dansmitt** [comment]
@andrueastman I simplified this in a plain project. 

```cs

        public async Task<IActionResult> CreateDeviceConfigurationTenantDependent([FromBody] DeviceConfiguration? deviceConfiguration)
        {
            var deviceConfig = deviceConfiguration as Windows10CustomConfiguration;

            return StatusCode(StatusCodes.Status200OK, deviceConfig );
        }
```

deviceConfig is null, so the cast was nut successful.

**Comment by andrueastman** [comment]
Apologies for the delayed response @dansmitt

I think the issue here is that the received response won't use the KiotaJsonSerializer and therefore downcasting won't happen. 

Any chance you can change your controller to something like this so that you can take advantage of the downcasting the serializer  from kiota will do.

```cs
        public async Task<IActionResult> CreateDeviceConfigurationTenantDependent([FromBody] JsonElement jsonElement)
        {
            var deviceConfiguration = new JsonParseNode(jsonElement).GetObjectValue<DeviceConfiguration>(DeviceConfiguration.CreateFromDiscriminatorValue);
            var deviceConfigCast = deviceConfiguration as Windows10CustomConfiguration;
            return StatusCode(StatusCodes.Status200OK, deviceConfigCast);
        }
```

**Comment by dansmitt** [comment]
@andrueastman thx for the answer,

deviceConfigCast is still null 😒

**Comment by andrueastman** [comment]
Thanks for confirming @dansmitt 

I did test out the suggestion before though and it did work out from my end. Any chance you can share the payload received by the controller? Is the `@odata.type` property present in the payload (This is what the serializer uses for downcasting)?

**Comment by dansmitt** [comment]
@andrueastman 

This is the payload i use:

``` json
{
    "@odataType": "#microsoft.graph.windows10CustomConfiguration",
    "description": "Test",
    "displayName": "Testconfig",
    "version": 1,
    "omaSettings": [
        {
            "description": null,
            "displayName": "Create LocalAdmin Account",
            "@odataType": "#microsoft.graph.omaSettingString",
            "omaUri": "./Device/Vendor/MSFT/Accounts/Users/myLocalAdmin/Password"
        }
    ]
}
```
Here the autos:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/62943030/9fb91306-277d-434d-97e5-35d25835e6fc)

**Comment by andrueastman** [comment]
The property `@odataType` should be `@odata.type`. Any chance you can fix that and confirm if it works out?

**Comment by dansmitt** [comment]
@andrueastman 

If we do something like this it works fine:

```csharp

        [HttpPost("deviceConfigurations")]
        public async Task<IActionResult> CreateDeviceConfigurationTenantDependent([FromBody] JsonElement jsonElement)
        {
            var deviceConfiguration = new JsonParseNode(jsonElement).GetObjectValue<DeviceConfiguration>(Windows10CustomConfiguration.CreateFromDiscriminatorValue);
            var deviceConfigCast = deviceConfiguration as Windows10CustomConfiguration;
            return StatusCode(StatusCodes.Status200OK, deviceConfigCast);
        }
```

So we need to create a specific ``Windows10CustomConfiguration.CreateFromDiscriminatorValue``

Is there a reason why the ``@odataType`` is not set if we just use  ``DeviceConfiguration.CreateFromDiscriminatorValue``?

**Comment by andrueastman** [comment]
The issue really is the payload. If you take a look at the payload and the code below. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/f4e50079f97016ada52c9a43d7d9a41a05c537a9/src/Microsoft.Graph/Generated/Models/DeviceConfiguration.cs#L146

The property in the payload should not be `@odataType` but should be `@odata.type`. The parser is defaulting to the `DeviceConfiguration` because it cannot find the correct discriminator property.

I'm not sure why the property name has been altered though. Any chance you could confirm from your end what is changing it?

**Comment by dansmitt** [comment]
@andrueastman sorry was blind... 

May payload now corrected:
```json
{
    "@odata.Type": "#microsoft.graph.windows10CustomConfiguration",
    "description": "Test",
    "displayName": "Testconfig",
    "version": 1,
    "omaSettings": [
        {
            "description": null,
            "displayName": "Create LocalAdmin Account",
            "@odataType": "#microsoft.graph.omaSettingString",
            "omaUri": "./Device/Vendor/MSFT/Accounts/Users/myLocalAdmin/Password"
        }
    ]
}
```

Actual code:
```csharp
        public async Task<IActionResult> CreateDeviceConfigurationTenantDependent([FromBody] JsonElement jsonElement)
        {
            var deviceConfiguration = new JsonParseNode(jsonElement).GetObjectValue<DeviceConfiguration>(DeviceConfiguration.CreateFromDiscriminatorValue);
            var deviceConfigCast = deviceConfiguration as Windows10CustomConfiguration;
            return StatusCode(StatusCodes.Status200OK, deviceConfigCast);
        }
```

Result: ``deviceConfigCast`` is still null

**Comment by andrueastman** [comment]
> @odata.Type"

Its case sensitive I believe. Try changing the casing of the `T` first.

**Comment by dansmitt** [comment]
@andrueastman concentration not the best today.

This works for me. Thanks for your help! Until next time.

**Comment by dansmitt** [comment]
Hey @andrueastman  I think we have here a serialization problem of the ``DeviceConfiguration``. This was also the reaseon why ``odataType`` was typed like it was.

Before  we serialize it, ``OdataType`` is ``Windows10CustomConfiguration`` and when we dezerialize it ``OdataType`` is null. Also 

Before:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/62943030/a5af2fa5-8418-4acb-a18b-4eb7ee5ac18d)

After:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/62943030/27525e54-2aeb-4d81-b246-d5884e46f8ce)

**Comment by andrueastman** [comment]
Any chance you can share a sample of the json when it is serialized as well as a sample of the code that performs the serialization?

**Comment by dansmitt** [comment]
@andrueastman thanks for your reply.

This is the code which serialize the ``DeviceConfiguration`` client side:
```csharp
var response = await _httpClient.PostAsJsonAsync($"someUrl", deviceConfiguration);
```
So ``deviceConfiguration`` will be automatically serializes by ``PostAsJsonAsync``.

This is the JSON anonymized:
```json
{
    "Description": "Test",
    "DeviceSettingStateSummaries": null,
    "DeviceStatuses": null,
    "DeviceStatusOverview": null,
    "DisplayName": "SomeDisplayname",
    "UserStatuses": null,
    "UserStatusOverview": null,
    "Version": 13,
    "OdataType": "#microsoft.graph.windows10CustomConfiguration"
}
```
This looks good so far.

But when it will be deserialized with the method you mentioned, the OdataType is null. This is totally strange because when i transfer the payload with swagger or postman, and name the OdataType property in the JSON to @odata.type, it works.

**Comment by andrueastman** [comment]
Since the `DeviceConfiguration` does not have the `System.Text.Json` annotations, the `OdataType` property is serialized incorrectly. The payload should ideally be deserialized with `KiotaJsonSerializer`

Any chance the following works out for you now?

```cs
deviceConfig.BackingStore.InitializationCompleted = false; // you may need this line if the object was deserialized from the API.
                                                           // Otherwise only changed values/properties will be serialized.
var serializedPayload = KiotaJsonSerializer.SerializeAsString(deviceConfig);
var httpContent = new StringContent(serializedPayload, System.Text.Encoding.UTF8, "application/json");
var responseMessage = httpClient.PostAsync("someurl", httpContent);
```

**Comment by dansmitt** [comment]
Hey I implemented it for the serilization part.
At the ``var serializedPayload = KiotaJsonSerializer.SerializeAsString(deviceConfiguration);`` part, I get an ``System.InvalidOperationException: Content type application/json does not have a factory registered to be parsed`` exception. Do I need to register something?

**Comment by andrueastman** [comment]
Hey @dansmitt. 

The registration to be performed automatically if you have the GraphServiceClient initialized somewhere in you code. Simply calling the constructor. 
 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/148f1ef380baedb27f7adb3c93b45f194f5c3e16/src/Microsoft.Graph/Generated/BaseGraphServiceClient.cs#L393

If not, you may perform the registration manually by calling the line 

```cs
ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>(); 
```

**Comment by dansmitt** [comment]
Hey @andrueastman 

its not depending to the GraphClient, we serialize the object client side which calls then our webservice which then calls the graph client. So we can't handle the graph client on our client side.

**Comment by andrueastman** [comment]
@dansmitt If you do not have the graph client, I believe you only need to add this line somewhere your initialization code to register the json serializer. 

```cs
SerializationWriterFactoryRegistry.DefaultInstance.ContentTypeAssociatedFactories.TryAdd("application/json", new JsonSerializationWriterFactory());
```
> System.InvalidOperationException: Content type application/json does not have a factory registered to be parsed exception. 

This should get rid of this error and serialize the model as expected. 

Do you still use the model from the SDK from the client side? Or do you have custom models?

**Comment by dansmitt** [comment]
@andrueastman I use the models from the SDK client side as well api side . 

Depending to your approach, this works for the serialization. From the API side we use (works also fine):

```csharp
public async Task<IActionResult> CreateDeviceConfigurationTenantDependent(TenantEnvironment tenantEnvironment, [FromBody] JsonElement jsonElement)
{
    if (tenantEnvironment != TenantEnvironment.NotDefined)
    {
        var deviceConfiguration = new JsonParseNode(jsonElement).GetObjectValue<DeviceConfiguration>(Windows10CustomConfiguration.CreateFromDiscriminatorValue);

        var test = await _deviceManagementLobEngine.CreateDeviceConfigurationTenantDependentAsync(tenantEnvironment, deviceConfiguration!);
        return StatusCode(StatusCodes.Status200OK, test );
    }
    return StatusCode(StatusCodes.Status400BadRequest);
}
```

Won't it be better if we could work typesafe here with `DeviceConfiguration` instead of an `JsonElement? I mean even for an open api approach that the example body will be rendered automatically.

I'm still up to a meeting. It's really interesing, diving deeper into this. You can also give me a chat in Teams, I'll write a conclusion on here for the community.

**Comment by andrueastman** [comment]
>Won't it be better if we could work typesafe here with DeviceConfiguration instead of a JsonElement? I mean even for an open api approach that the example body will be rendered automatically.

This is true. This really depends on the scenario that is being used but we would need to explore how to hook up the `KiotaJsonSerializer` in the middleware of the API as an alternative to default of System.Text.Json. 

> I'm still up to a meeting. It's really interesing, diving deeper into this. You can also give me a chat in Teams, I'll write a conclusion on here for the community

Just to confirm, does the solution now work out for you? If you can send me the contact and I'll send out a message.

**Comment by dansmitt** [comment]
>> Just to confirm, does the solution now work out for you? If you can send me the contact and I'll send out a message.
> Solution is working 50:50 for me, it is blowing up the code on both sides. Serializing from client side, dezerializing on api side, serializing the result on server side to transport it in an ActionResult and deserializing on client side the ActionResult which is at this point not really working.

**Comment by MichaMican** [comment]
To give a little bit more context what we (@dansmitt and I) have done (maybe someone finding this issue will find it usefull):

We endet up implementing Text Formatters that allow as to Add the KiotaSerializer in a similar way as other serailizers (e.g. Newtonsof.Json)
```csharp
builder.Services.AddControllers().AddKiotaSerializer()
```

`AddKiotaSerializer()` is an extensionmethod of `IMvcBuilder` that we created:
```csharp
public static class KiotaFormatterExtensions
{
    public static IMvcBuilder AddKiotaSerializer(this IMvcBuilder mvcBuilder)
    {
        return mvcBuilder.AddMvcOptions(options => { 
            options.InputFormatters.Insert(0, new KiotaInputFormatter());
            options.OutputFormatters.Insert(0, new KiotaOutputFormatter());
        });
    }
}
```

`KiotaInputFormatter` and `KiotaOutputFormatter` are implementations of `TextInputFormatter` and `TextOutputFormatter` that we implemented with the helpful insights and comments from this thread (thx @andrueastman ❤️)
`KiotaInputFormatter.cs`:
```csharp
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Graph.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using Microsoft.Net.Http.Headers;
using System.Reflection;
using System.Text;

namespace MyAwesomeProject.Formatter
{
    public class KiotaInputFormatter : TextInputFormatter
    {
        public KiotaInputFormatter()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("application/json"));

            SupportedEncodings.Add(Encoding.UTF8);
            SupportedEncodings.Add(Encoding.Unicode);
        }

        protected override bool CanReadType(Type? type)
        {
            return typeof(IParsable).IsAssignableFrom(type);
        }

        public override Task<InputFormatterResult> ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
        {
            var httpContext = context.HttpContext;

            if (httpContext.Request.Body.CanRead)
            {
                var targetType = context.ModelType;

                #region Reflection to define Generic type T of KiotaJsonSerializer.Deserialize<T> dynamically
                var methodInfo = typeof(KiotaJsonSerializer).GetMethod("Deserialize", BindingFlags.Public | BindingFlags.Static, [typeof(Stream)]);
                if (methodInfo == null)
                {
                    //This means Microsoft changed the KiotaJsonSerializer.Deserialize Function - which would be kinda sad :(
                    throw new Exception("KiotaJsonSerializer.Deserialize changed. Please update implementation");
                }

                // This line types the KiotaJsonSerializer.Deserialize<T> to T equals to targetType
                var methodWithForcedTargetType = methodInfo.MakeGenericMethod(targetType);

                // obj is null because KiotaJsonSerializer.Deserialize is a static function
                // This function is analog to KiotaJsonSerializer.Deserialize<T>(httpContext.Request.Body) -> Where T = targetType
                var deserializedObject = methodWithForcedTargetType.Invoke(null, [httpContext.Request.Body]);

                var backingStoreProperty = (deserializedObject?.GetType().GetProperty("BackingStore"));
                var backingStoreValue = backingStoreProperty?.GetValue(deserializedObject);

                backingStoreValue?.GetType().GetProperty("InitializationCompleted")?.SetValue(backingStoreValue, false);

                #endregion

                return Task.FromResult(InputFormatterResult.Success(deserializedObject));
            }

            return Task.FromResult(InputFormatterResult.Failure());

        }

    }
}
```
> Note: We had to use reflection to get the correct Function overload, as unfortunately Kiota doesn't provide a `Deserialize<T>()` function where you can specify the type as a parameter. Hence we have to use reflection to get the right generic type

`KiotaOutputFormatter.cs`
```csharp
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Graph.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using Microsoft.Net.Http.Headers;
using System.Text;

namespace MyAwesomeProject.Formatter
{
    public class KiotaOutputFormatter : TextOutputFormatter
    {
        public KiotaOutputFormatter()
        {
            SupportedMediaTypes.Add(MediaTypeHeaderValue.Parse("application/json"));

            SupportedEncodings.Add(Encoding.UTF8);
            SupportedEncodings.Add(Encoding.Unicode);
        }

        protected override bool CanWriteType(Type? type)
        {
            return typeof(IParsable).IsAssignableFrom(type);
        }

        public override Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
        {
            var httpContext = context.HttpContext;
            var objectAsIParsable = context.Object as IParsable;

            if(objectAsIParsable == null)
            {
                return Task.CompletedTask;
            }

            if (objectAsIParsable is IBackedModel backedModel)
            {
                backedModel.BackingStore.InitializationCompleted = false;
            }
            
            var responseBody = KiotaJsonSerializer.SerializeAsString(objectAsIParsable);

            return httpContext.Response.WriteAsync(responseBody, selectedEncoding);
        }
    }
}
```

With this we can simply use the native Kiotaserializer at our endpoints, and the best thing: Thanks to the implementation of `CanWriteType()` / `CanReadType()` the serializer only serializes actual Kiota objects (`IParsable`) and leaves other objects, e.g. custom Models and Dtos, to the standard `System.Text.Json` serializer
