### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by RickL1234** [microsoftgraph/msgraph-sdk-dotnet#2347]
I just updated Visual Studio 2022 to:

Microsoft Visual Studio Enterprise 2022 (64-bit) - LTSC 17.8
Version 17.8.7

NuGet manager said there was an update to Microsoft.Graph.  Attempting to install the update and I am getting this error:

NU1605: Warning As Error: Detected package downgrade: Microsoft.Graph.Core from 3.1.7 to 3.1.5. Reference the package directly from the project to select a different version. 
 QualtricsSurveyImport -> Microsoft.Graph 5.42.0 -> Microsoft.Graph.Core (>= 3.1.7) 
 QualtricsSurveyImport -> Microsoft.Graph.Core (>= 3.1.5)

How do I fix this error?

Let me know if you need any more information.

Thanks,
Rick L.

**Comment by andrueastman** [comment]
Thanks for raising this @RickL1234 

Any chance you can confirm if you a reference to `Microsoft.Graph.Core` in your project? If so you would need to update that first to the latest version then update the  `Microsoft.Graph` package.

Alternatively, you can remove the `Microsoft.Graph.Core` reference and then install/update `Microsoft.Graph` as this already implicitly brings in the core library.

**Comment by RickL1234** [comment]
That cleared up the error.  I was able to update both Microsoft.Graph and Microsoft.Graph.Core to the latest versions.

Thanks,
Rick L.
