### ISSUE TITLE
Microsoft graph api getSchedule sdk return error while graph explorer works as expected.

### ISSUE THREAD

**Issue by yundatsai** [microsoftgraph/msgraph-sdk-dotnet#2349]
**Describe the bug**
Microsoft graph api getSchedule sdk return error while graph explorer works as expected.
Status Code: BadRequest
      Microsoft.Graph.ServiceException: Code: ErrorInvalidTimeInterval
      Message: The time duration specified for FreeBusyViewOptions.TimeWindow is invalid.
      ClientRequestId: 96fbdfd5-3cf1-42ff-93b1-5a1be5d91190

**To Reproduce**
```
schedule = ["test@example.com"];
start = {
    "dateTime": "2019-03-15T09:00:00",
    "timeZone": "Pacific Standard Time"
};
end = {
    "dateTime": "2019-03-15T18:00:00",
    "timeZone": "Pacific Standard Time"
};
availabilityViewInterval = 15;

return graphServiceClient.Users[BotAddress]
    .Calendar
    .GetSchedule(schedule, start, end, availabilityViewInterval)
    .Request()
    .PostAsync();
```

**Expected behavior**
Return the scedule correctly.

**Screenshots**
![Screenshot 2024-02-21 070342](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/54813149/0cc9b730-f304-40fa-bdcd-364036af005e)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 4.45.0

**Additional context**
Client request ID: 96fbdfd5-3cf1-42ff-93b1-5a1be5d91190

**Comment by andrueastman** [comment]
Thanks for raising this @yundatsai 

Any chance you are able to capture a fiddle trace when the request is made to compare the json body sent to the 
API with the version sent by Graph explorer?
