### ISSUE TITLE
Microsoft graph api get online meeting with meeting_id but get :No application access policy found for this app.

### ISSUE THREAD

**Issue by j40903272** [microsoftgraph/msgraph-sdk-dotnet#2350]
**Describe the bug**
Microsoft graph api get online meeting with meeting_id but get :No application access policy found for this app.
Status Code: Forbidden
Microsoft.Graph.ServiceException: Code: General
Message: No application access policy found for this app.
Inner error:
	AdditionalData:
	request-id: f9e21413-6913-4db4-be2e-90bebaf721b7
	date: 2024-02-20T23:12:03
	client-request-id: f9e21413-6913-4db4-be2e-90bebaf721b7
ClientRequestId: f9e21413-6913-4db4-be2e-90bebaf721b7

**To Reproduce**
return graphServiceClient.Users["64c53a6c-0e0f-4d06-a32f-d050d8578abd"]
    .OnlineMeetings["MSo0Yjc1MTg5Yi1jMTk1LTQwM2ItYmFjNC1iZjAzZjIyOTVlYmMqMCoqMTk6bWVldGluZ19PREkzWTJNNVkyRXRNakZtTVMwME1qVmhMV0psTVRZdE4yRm1NakU0T1RJeFltRTRAdGhyZWFkLnYy"]
    .Request()
    .GetAsync();

**Expected behavior**
return the meeting object

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 4.45.0

**Additional context**
ClientRequestId: f9e21413-6913-4db4-be2e-90bebaf721b7

**Comment by andrueastman** [comment]
Thanks for raising this @j40903272 

I believe the 403 error suggests that the application registration is not configured correctly to make the specific request. Any chance you are able to go through the documentation at the link below to configure the application access to online meetings?

https://learn.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy
