### ISSUE TITLE
[Client bug]: cannot patch CustomSecurityAttributes using the SDK

### ISSUE THREAD

**Issue by davidebonifacio** [microsoftgraph/msgraph-sdk-dotnet#2352]
**Describe the bug**
When patching an user for a CustomSecurityAttributes, it gave an exception like "Invalid property {propertyName}" but when using the http call it works as expected.

**To Reproduce**
1. Just follow the example on the documentation at: https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=csharp

**Expected behavior**
It should update the CustomSecurityAttributes

**Client version**
5.43

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by andrueastman** [comment]
Thanks for raising this @davidebonifacio 

There is an issue with the generated example for this scenario as it will result to incorrectly seriliazing the odata.type property. 

Any chance the following example works for you?

```cs
            var dict = new Dictionary<string, object>
            {
                { "@odata.type","#Microsoft.DirectoryServices.CustomSecurityAttributeValue" },
                { "ProjectDate", "2022-10-01" },
            };

            var attribute = JsonSerializer.SerializeToElement(dict);

            var user = new User
            {
                CustomSecurityAttributes = new CustomSecurityAttributeValue
                {
                    AdditionalData = new Dictionary<string, object>()
                    {
                        { "Engineering", attribute }
                    }
                }
            };

            await graphClient.Users["user-id"].PatchAsync(user);
```

**Comment by davidebonifacio** [comment]
Thanks, it works

**Comment by andrueastman** [comment]
Thanks for confirming. We'll close this for now in favour of the issue in the snippet generator at https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1751
