### ISSUE TITLE
[Client bug]: Bookings Business StaffMembers GetAsync returns base class instead of regular class

### ISSUE THREAD

**Issue by theblindprophet** [microsoftgraph/msgraph-sdk-dotnet#2354]
**Describe the bug**
The method located here:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/f4e50079f97016ada52c9a43d7d9a41a05c537a9/src/Microsoft.Graph/Generated/Solutions/BookingBusinesses/Item/StaffMembers/StaffMembersRequestBuilder.cs#L55

Operates only with the base StaffMembers response class, `BookingStaffMemberBaseCollectionResponse`.
Therefore, when querying for staff members, you only get the default entity properties instead of all the properties on a staff member, as you would get using the REST API via Postman.

This class is used, `BookingStaffMemberBase`, instead of `BookingStaffMember`. I cannot find another way to get all the staff member properties.

I tried using `Select` to ask for `emailAddress, displayName` and it throws:

```
A problem occurred while processing your request. Microsoft.Graph.Models.ODataErrors.ODataError: Parsing OData Select and Expand failed: Could not find a property named 'displayName' on type 'microsoft.graph.bookingStaffMemberBase'
```

**To Reproduce**

```
var result = await _graphServiceClient.Solutions.BookingBusinesses["someid"].StaffMembers.GetAsync(x => {
            x.QueryParameters.Skip = skip;
            x.QueryParameters.Top = take;
});
```

**Expected behavior**

I expect to receive all the other properties the REST API provides such as email address, display name, etc..

**Screenshots**

REST API

<img width="716" alt="Screenshot 2024-02-21 at 8 01 22 PM" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/7903413/6414751d-29d1-4f2b-b210-d0438c371d85">

**Client version**
Provide the client version number from the NuGet package.

5.42.0

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser chrome
 - Version 121.0.6167.160

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @theblindprophet 

For context, The API description states that the endpoint returns the base class meaning that the API could return any of the derived types. As much as this is the case, the SDK will attempt to downcast the returned value to the derived type if the `odata.type` property is present in the payload.

If this is present, you should be able to use pattern matching in C# to get the derived type as below.

```cs
var members = await _graphServiceClient.Solutions.BookingBusinesses["someid"].StaffMembers.GetAsync(x => {
            x.QueryParameters.Skip = skip;
            x.QueryParameters.Top = take;
});

foreach(var member in members.Value)
{
    if(member is BookingStaffMember bookingStaffMember)
    {
        //access the derived type properties though
        Console.WriteLine(bookingStaffMember.Id)
    }
}
```

**Comment by theblindprophet** [comment]
@andrueastman Interesting, thank you. I was not aware of that, maybe it should be called out more specifically in the documentation (or I missed it). Regardless, this did work:
```
var resultBase = await _graphServiceClient.Solutions.BookingBusinesses[bookingsParentId ?? _options.DefaultBookingParentId].StaffMembers.GetAsync(x => {
            x.QueryParameters.Skip = skip;
            x.QueryParameters.Top = take;
});
var result = resultBase.Value.Select(x => x as BookingStaffMember).ToList();
```

And this explanation was helpful: https://stackoverflow.com/questions/1524197/downcast-and-upcast
