### ISSUE TITLE
Pipelines compliance

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet#2355]
ADO pipelines need to move to the compliant 1ES templates. 

Similar to these PRs 
- https://github.com/microsoft/OpenApi.ApiManifest/pull/70
- https://github.com/microsoft/kiota/pull/4137
- https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1797

We should start with the abstractions lib and then replicate this issue across the repos once the first pipeline is setup aligned.

**Comment by petrhollayms** [comment]
@andrueastman Could you please involve @MIchaelMainer for a review as well? Thanks!
