### ISSUE TITLE
User City property null

### ISSUE THREAD

**Issue by No1e** [microsoftgraph/msgraph-sdk-dotnet#2356]
**Describe the bug**
When using GraphServiceClient to query users, I am getting null for City for every user. I already checked if my registered application have required permissions in Azure Entra Id, and it has, both application permission and delegated permissions. Delegated permissions are granted.

I also tried to specify QueryParameters.Select by explicitly including properties, but without success.
Also, I already checked if users have City property set, and that is true.

**To Reproduce**
1. Create GraphServiceClient 
2. Perform query by calling GraphServiceClient .Users.GetAsync

**Expected behavior**
City property should have correct value.

Is this bug, or I am doing something wrong?

Best regards,
Nole

**Comment by andrueastman** [comment]
Thanks for raising this @No1e 

The API will return a limited number of properties by default according to the docs. 
https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp#optional-query-parameters

If you wish for more properties added, please try out the select parameter as described at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#query-parameter-options
