### ISSUE TITLE
In SDK 5, retryHandlerOption not working ASP.NET 6 core app

### ISSUE THREAD

**Issue by jimbarrett33** [microsoftgraph/msgraph-sdk-dotnet#2357]
**Describe the bug**
The retryHandlerOption is not working -- the retry never happens. I simulated 500 errors locally using [devProxy](https://github.com/microsoft/dev-proxy) tool and the retries never happen.

My code is verbatim to the code below and is the exact example from your docs [https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#per-request-options](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#per-request-options)

I am using the `Microsoft.Identity.Web.GraphServiceClient`. The retries never occur so it seems maybe the `GetAsync(requestConfiguration =>` is not setting the configuration correctly?

```
var retryHandlerOption = new RetryHandlerOption
{
    MaxRetry = 7,
    ShouldRetry = (delay,attempt,message) => true
};
var user = await graphClient.Me.GetAsync(requestConfiguration => requestConfiguration.Options.Add(retryHandlerOption));
```

**To Reproduce**
Use your example code in an ASP.NET core app.

**Expected behavior**
Retries should occur. I looked at the code in the  [Kiota middleware RetryHandler](https://github.com/microsoft/kiota-http-dotnet/blob/main/src/Middleware/RetryHandler.cs#L152) and I don't see anything that would prevent the handler being called for a t 500 error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - .NET Core 6
 - Visual Studio 2022

**Comment by jimbarrett33** [comment]
@andrueastman I have confirmed that manually configuring graph client does indeed result in the retry handler working using this code:
```
var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);
var scopes = new[] { "https://graph.microsoft.com/.default" };
GraphServiceClient graphServiceClient = new GraphServiceClient(clientSecretCredential, scopes);

var retryHandlerOption = new RetryHandlerOption
{
    MaxRetry = 5,
    ShouldRetry = (delay,attempt,message) =>
    {
        Console.WriteLine($"Retrying attempt = {attempt}");
        return true;
    }
};

var user = await graphServiceClient
    .Users[userId]
    .GetAsync(requestConfiguration => requestConfiguration.Options.Add(retryHandlerOption));
```

However, I'm giving up and reverting back to the previous SDK and will implement retry with that code (I've been working on trying to solve this for over 2 days now). The problem is that I use this code in `program.cs:` 
```
builder.Services.AddMicrosoftIdentityWebApiAuthentication(builder.Configuration)
    .EnableTokenAcquisitionToCallDownstreamApi()
    .AddMicrosoftGraph(builder.Configuration.GetSection("DownstreamApi"))
    .AddInMemoryTokenCaches();
```

which is used to easily create the graph client, and with the OBO flow. This code snippet is used in many places in the Microsoft docs, code examples etc. and is probably used out in the wild in many production apps. I don't want to change this code in my app but I still want to implement retries and I will with the previous version of the SDK. This may be a small use case but I would add it to the list of reasons why developers won't want to upgrade to SDK 5 (in addition to all the other breaking changes noted in the upgrade guide).

I don't even know which MS team/code base this bug belongs or where to file it. I believe it would be titled something like "the .NET Core builder service pipeline creates and injects a GraphServiceClient object (for DI) that does not allow the use of the RetryHandlerOptions in per-request options" and reference [Per-Request Options](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#per-request-options)

**Comment by andrueastman** [comment]
Thanks for the information here. I'll close this issue for now so that we may follow it up at https://github.com/AzureAD/microsoft-identity-web/issues/2684 so that this may be fixed in the `Microsoft.Identity.Web.*` library.
