### ISSUE TITLE
Field creationOptions for Group api

### ISSUE THREAD

**Issue by ayblanchet** [microsoftgraph/msgraph-sdk-dotnet#2359]
### Discussed in https://github.com/microsoftgraph/msgraph-sdk-dotnet/discussions/2342

<div type='discussions-op-text'>

<sup>Originally posted by **ayblanchet** February 16, 2024</sup>
Hi,
Could you say me how to get creationOptions field from Group api? I have no "creationOptions" property on group object and it's not present in additionalData.

I use Microsoft.graph 5.4.0.

Thank you</div>

**Comment by andrueastman** [comment]
Thanks for raising this @ayblanchet 

Any chance you can confirm where the property is coming from? Taking a look at the documentation, the Group object does not have the property existing. 

https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties
