### ISSUE TITLE
Add support for /groups/{id}/team

### ISSUE THREAD

**Issue by Daniel-DNC** [microsoftgraph/msgraph-sdk-dotnet#236]
Can you please add support for the (beta) Microsoft Teams functionality as found here: [https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/teams_api_overview](url)

I'm not sure if you can and will support the beta reference of MS Graph...

Thanks, Daniel

**Comment by MIchaelMainer** [comment]
Hello @Daniel-DNC 

We currently don't publish. See #108. With that said, you can use the beta API with the current Graph client library. If you go to this [Microsoft Graph Community Call 1-2-18](https://www.youtube.com/watch?v=WF9FY6aJRwQ) video @ 13:30 onwards, there is a description of how to make beta models that you can use with the production API. The steps for doing this are also included in this repo: https://github.com/MIchaelMainer/msgraph-sdk-dotnet-beta.

**Comment by Daniel-DNC** [comment]
Thanks Michael!!

Daniel
