### ISSUE TITLE
Excessive acquiring of Graph access token

### ISSUE THREAD

**Issue by LiamWarnes** [microsoftgraph/msgraph-sdk-dotnet#2360]
Hi,

I am responsible for development of an Azure Function that accesses and updates email data for various user mailboxes within an organization. The Azure Function, acting as a service principal within the organization's Microsoft tenancy, leverages the Graph SDK to make calls to the Graph API to process the email data. 

Recently, a customer has reported to us that they have received an automatic alert regarding a large number of service principal sign in requests (~100k+ sign ins per day among an organization of ~60 people). These can be found within the "Service Principal" tab on the "Sign In Logs" blade of the related Enterprise Application within Microsoft Entra ID in Azure.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/61216957/7a97cddd-eda6-4959-8daa-78202bf960af)

In my investigation, I have established a direct correlation between each sign in request log and a dependency in Application Insights telemetry for the call to the login.microsoftonline.com token endpoint. This call is facilitated by use of a ClientSecretCredential that was provided when instantiating a GraphServiceClient object. Here is how that would look in the latest version of the SDK (5.43) as at this date (27th Feb 2024):

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/61216957/e8087a00-6c13-46c2-958f-ba9b9539f1f2)

The above is called in wrapper service that is injected as a singleton within the Azure Function instance. As such, I have proven with telemetry that only one GraphServiceClient instance exists per Azure Function instance. The application as a whole utilizes queues to process multiple requests as quickly as possible, and the capability of Azure Functions to scale out does come into play. Still, the number of Azure Function hosts that exist when processing data does not meet the amount of dependency calls to acquire a new token. My expectation is that a single Azure Function host should cache the token once and re-use it as necessary, but this is not the case. Going through the various sign in logs and related telemetry, I have failed to establish a pattern for why certain calls to the Graph API via the GraphSDK request a new token beforehand and other calls will not. You can see in the following screenshot the result of two examples of the same code being executed, but one has the dependency to the token endpoint and the other does not:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/61216957/f6470dc1-737f-440c-b61d-445de5a39153)

So, with all this information now in your hands - I would like to know:

1. Is this by design?
1a. If so, what is the reason that the SDK requires a new token? -> I want to communicate this reason back on to our customer.
1b. If not, is the SDK deficient with the way it caches tokens and there is room for improvement here? -> I want to communicate to our customer that a bug/improvement is to be addressed then we can fix up the excessive sign in logs when it is available.

Possibly related articles I've reviewed from other repos:

https://github.com/Azure/azure-sdk-for-js/issues/27846

https://github.com/Azure/azure-sdk-for-net/issues/38601

Awaiting your reply.

Thanks, 
Liam

**Comment by andrueastman** [comment]
Thanks for raising this @LiamWarnes 

The fetching of the token is really handled by the `Azure.Identity` library which essentially a wrapper for MSAL.NET. As long as the same instance of the `ClientSecretCredential` is used, token fetched will be cached in memory by default. The only reason for fetching new tokens would really be the expiry of an existing token in this scenario.

From the issue description, it seems that most likely the clients created are not being re-used in subsequent invocations but being recreated and thus needing to fetch the token again. 
Any chance its possible to try out with a static/shared instance? 
Do the tenantId/clientId parameters change across instances (This would possibly force the fetching of a new token as well)?

**Comment by LiamWarnes** [comment]
hi @andrueastman 

I previously mentioned that **The above is called in wrapper service that is injected as a singleton within the Azure Function instance. As such, I have proven with telemetry that only one GraphServiceClient instance exists per Azure Function instance.** I had verified this in telemetry - that we do get multiple GraphServiceClient instances in telemetry, but only one per host.

To be extra sure of this, I converted usage of the GraphSDK to static and re-ran the test - the results are the same.
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/61216957/42724423-4499-45a6-92a9-f0abbce87f2f)

The tenant/client id is injected from the Azure Function configuration and does not change for the lifetime of the application

**Comment by pschaeflein** [comment]
A couple of thoughts:
- Just because an object is a singleton in Azure Functions does not guarantee it is used for every invocation of a function. The function runtime manages instances, which could be in different processes/servers.
- Have you reviewed [Token cache serialization guide](https://learn.microsoft.com/en-us/entra/msal/dotnet/how-to/token-cache-serialization?tabs=aspnetcore) to see if there is a better way to configure your confidential client application?

**Comment by LiamWarnes** [comment]
Hi @pschaeflein 

1. I indicated in my previous response that several hosts are being used to manage requests to the azure function. This has scaled out automatically. I have also verified that there is only a single instantiation of the Graph SDK and ClientSecretCredential per host following this documentation https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp. If your question here is to highlight that an instance of the SDK injected as a singleton may not be the only instance used processing requests to the azure function, then I should have already ruled this out as a concern. If there is some further consideration required here, then please elaborate.

2. I have not previously reviewed this guide, but again I was only following the documentation provided https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp. I do no configuration of any MSAL application on startup. Further documentation https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md indicates that in-memory caching is supported by default for this authentication provider. This is supported by the telemetry I have seen around these Graph dependencies (not acquiring a token for every call). However, after some unspecified amount of dependencies or time any Graph dependency will decide it needs to acquire a new token. There is no consistency here as to why - I would like to know why.
