### ISSUE TITLE
Creating attachment just after event creation throws exception while succeeding.

### ISSUE THREAD

**Issue by shoter** [microsoftgraph/msgraph-sdk-dotnet#2362]
**Describe the bug**
Creating an attachment for an event just after event creation in delegated calendar results in exception while operation in reality succeeds and attachment is correctly added.

Cannot reproduce for personal calendar. Bug seems to happen only on calendars with delegated access

**To Reproduce**
1. Have [delegate access](https://support.microsoft.com/en-us/office/allow-someone-else-to-manage-your-mail-and-calendar-41c40c04-3bd1-4d22-963a-28eafec25926) to someone's calendar. ( Do not mistake with delegated permissions )
2. With delegated permissions in your application create an event in such calendar  
```csharp
var created = await graphClient.Me.Calendars[calendar.Id]
    .Events.PostAsync(
        new Event()
        {
            AllowNewTimeProposals = true,
            Subject = "Test meeting",
            Body = new ItemBody()
            {
                ContentType = BodyType.Text,
                Content = "Test"
            },
            Start = start,
            End = end,
        });
 ```
3. Just immediately after create such event proceed to attachment creation (attachement is simple json object that after serialization weights around 500B)
```csharp
    var attachment = new FileAttachment()
    {
        ContentBytes = bytes,
        ContentType = "application/json",
        IsInline = false,
        Name = "metadata.json",
        Size = bytes.Length
    };

    await graphClient.Me.Calendars[calendar.Id]
        .Events[created!.Id]
        .Attachments.PostAsync(attachement);
```
4. You receive `ODataError` exception and **!! attachment is successfully created!!**  
5. Error message:
> The specified object was not found in the store.

**Expected behavior**
1. Error should not happen at all because event is created
2. If error happens then it should mean that attachment is not created

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 5.42.0
 
**Stack Trace**
```
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Calendars.Item.Events.Item.Attachments.AttachmentsRequestBuilder.PostAsync(Attachment body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\programming\misc\003_calendar\003_calendar\Program.cs:line 99
```

**Error object within ODataError :**

```json
{
  "AdditionalData": {},
  "BackingStore": {
    "ReturnOnlyChangedValues": false,
    "InitializationCompleted": true
  },
  "Code": "ErrorItemNotFound",
  "Details": null,
  "InnerError": null,
  "Message": "The specified object was not found in the store.",
  "Target": null
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @shoter 

Do you by any chance get different results if you add a delay between creating the event and the attachment? 

As the error is generated by the API, and this repo is mainly intended for SDK related issues, I would suggest creating an issue at the link to give feedback to the API owners so that this may be looked into. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by andrueastman** [comment]
> As the error is generated by the API, and this repo is mainly intended for SDK related issues, I would suggest creating an issue at the link to give feedback to the API owners so that this may be looked into.
> 
> https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

Thanks for the info here. Would you be willing to submit feedback to the API owners here? Otherwise, we'll close this issue as there is nothing action from the SDK side.
