### ISSUE TITLE
Issue when uploading a file to a SharePoint library with Column validation enabled

### ISSUE THREAD

**Issue by mrebuffet** [microsoftgraph/msgraph-sdk-dotnet#2363]
**Describe the bug**
Files fail to upload to SharePoint libraries with column validation. 
<img width="150" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3445077/3be5a73f-25e9-426d-aa83-b36a723d5a68">

**To Reproduce**
1. Go to a SharePoint Online document library
2. Create a new text column and populate the column validation section
<img width="274" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/3445077/20972ec1-0d26-4e53-a103-1559f889c057">

3. Use the Graph API to upload a new file to this library with a call like this:

```cs
string filePath = "{path/to/file}";
MemoryStream fileContent = {fileStream};
Option[] options = new Option[] { new QueryOption("@microsoft.graph.conflictbehavior", "replace") };
IDriveItemContentRequest request = this.GraphServiceClient
					.Drives[{drive-id}]
					.Root
					.ItemWithPath($"/{filePath}")
					.Content
					.Request(options);
await request.PutAsync<DriveItem>(fileContent);
```
These other calls should also fail in a similar manner. 
https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online#http-request-to-upload-a-new-file

4. The Graph API returns a HTTP 500 - Internal Server Error exception
5. Remove the column or just the validation options
6. Try the API call again and the file is uploaded this time

**Expected behavior**
The file is uploaded to SharePoint and left checked out which is what SharePoint does when uploading the same file using the web UI.

**Additional details**
SharePoint REST has an option called `AutoCheckoutOnInvalidData` to obtain the desired behaviour.

```cs
{siteUri}/_api/Web/GetFolderByServerRelativePath(DecodedUrl=@a1)/Files/AddUsingPath(DecodedUrl=@a2,Overwrite=true,AutoCheckoutOnInvalidData=true)
```

Could the Graph API provide a similar option allowing us to upload files to a library with column validation?
Is there another way to achieve the desired result? 
Thanks

**Comment by andrueastman** [comment]
Thanks for raising this @mrebuffet 

As this questions relates to API side functionality, and this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners on whether its possible to have an option  similar to Sharepoint REST on the Graph API side? It would be great if you could post the link of the created question here as a comment so that anyone who comes accross this may also find the answer. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by mrebuffet** [comment]
Thank you for your reply @andrueastman 
I wasn't sure what would be the best way to raise this issue. 
Here is the link to the new ticket if anyone would like to track this issue or upvote :-)
https://learn.microsoft.com/en-us/answers/questions/1608501/how-to-upload-a-file-to-a-sharepoint-library-with

I'll mark this issue as won't fix. 
Thanks again
