### ISSUE TITLE
Create Contact failed with set BusinessAddress,HomeAddress or OtherAddress to null

### ISSUE THREAD

**Issue by idiotsky** [microsoftgraph/msgraph-sdk-dotnet#2368]
` 
var contact = new Contact
                      {
                          GivenName = "Talbott",
                          Surname = "Cady",
                          BusinessAddress = null
                      };
await graphServiceClient.Me.Contacts.PostAsync(contact);
`
if we run the post contact with set either BusinessAddress,HomeAddress or OtherAddress to null, we get Microsoft.Graph.Models.ODataErrors.ODataError : An internal server error occurred. The operation failed.

**Comment by andrueastman** [comment]
Thanks for raising this @idiotsky 

This is because of the backingStore which allows the setting and sending of null values in the request made to the API. If you do not need or should not set a value to null the property should ideally not be. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#backing-store

**Comment by andrueastman** [comment]
Any chance the code below works out? This way you do not need to have if statements and can set only when needed instead of setting null properties. 

```cs
        public Contact ConvertContact(ContactEntity contactEntity, Contact contact = default)
        {
            contact ??= new Contact();
            foreach (PostAddress postAddress in contactEntity.PostAddresses)
            {
                if (postAddress.Label == "Business")
                {
                    contact.businessAddress = new PhysicalAddress { Street = postAddress.Street };
                }
            }
            return contact;
        }
```

**Comment by idiotsky** [comment]
> Any chance the code below works out? This way you do not need to have if statements and can set only when needed instead of setting null properties.
> 
> ```cs
>         public Contact ConvertContact(ContactEntity contactEntity, Contact contact = default)
>         {
>             contact ??= new Contact();
>             foreach (PostAddress postAddress in contactEntity.PostAddresses)
>             {
>                 if (postAddress.Label == "Business")
>                 {
>                     contact.businessAddress = new PhysicalAddress { Street = postAddress.Street };
>                 }
>             }
>             return contact;
>         }
> ```
the use case is when the customer remove business address, I have to remove it, that's why I set to to null, as alterative now, I set it to new PhysicalAddress() instead of null. to skip this bug. but I still think set to null should be the right way deal with it.
