### ISSUE TITLE
Upload user profile picture not working

### ISSUE THREAD

**Issue by BenAffleckIsBatman** [microsoftgraph/msgraph-sdk-dotnet#237]
- [X] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behaviour
Uploading a User profile picture using the library should have Content-Type image/jpeg.

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/profilephoto_update#request-body 

### Actual behavior
Can't upload a user profile picture. Fiddler shows content-type application/octet-stream
```

PUT /v1.0/me/photo/$value HTTP/1.1
SdkVersion: Graph-dotnet-1.7.0
Cache-Control: no-store, no-cache
Authorization: bearer //removed//
Content-Length: 1051534
Content-Type: application/octet-stream
Host: graph.microsoft.com
Connection: Keep-Alive
```

Result is strange as I think its miss interpreted by graph
```
{
  "error": {
    "code": "ErrorInternalServerError",
    "message": "An internal server error occurred. The operation failed., The value is set to empty\r\nParameter name: smtpAddress",
    "innerError": {
      "request-id": "5b549f03-1ce5-4c8c-a393-27aef3ed1a75",
      "date": "2018-02-07T12:32:26"
    }
  }
}

```

### Steps to reproduce the behaviour
```
            if (_selectedPhoto != null)
            {
                using (IRandomAccessStream raStream = await _selectedPhoto.OpenReadAsync())
                {
                    await graphClient.Me.Photo.Content.Request().PutAsync(raStream.AsStream());
                }
            }
```

I addition I cloned the repository and ran the Unit Test UserUpdatePhoto with the same negative result. 
The corresponding method as below. Changing content type to image/jpeg does result in a 503 unkown error. Not sure what the root cause is here.

```
        /// <summary>
        /// PUTs the specified stream.
        /// </summary>
        /// <param name="content">The stream to PUT.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <param name="completionOption">The <see cref="HttpCompletionOption"/> to pass to the <see cref="IHttpProvider"/> on send.</param>
        /// <returns>The updated stream.</returns>
        public System.Threading.Tasks.Task<Stream> PutAsync(Stream content, CancellationToken cancellationToken, HttpCompletionOption completionOption = HttpCompletionOption.ResponseContentRead)
        {
            this.ContentType = "application/octet-stream";
            this.Method = "PUT";
            return this.SendStreamRequestAsync(content, cancellationToken, completionOption);
        }
```

**Comment by MIchaelMainer** [comment]
Hello @BenAffleckIsBatman 

Thank you for reporting this. Are you still seeing this issue? I just ran UserUpdatePhoto and it was successful. 

The error you code you got is strange. That looks like a service issue. I'll follow up on this and get back to you here. In the meantime, let me know if you still see this issue?

MIchael

**Comment by MIchaelMainer** [comment]
Was this working before and then stopped, or is this your first time trying this feature?
Can you confirm that the account that is trying to access this feature has a mailbox? 
What type of account is trying to access this feature?

**Comment by BenAffleckIsBatman** [comment]
@MIchaelMainer 

You are right! We checked one of the affected mailboxes and there was an issue with its provisioning. After recreating the mailbox the call went straight through. thanks a lot!
