### ISSUE TITLE
[Client bug]: Parsing OData Select and Expand failed

### ISSUE THREAD

**Issue by JannisBrauer** [microsoftgraph/msgraph-sdk-dotnet#2376]
**Describe the bug**
Hi there. I am currently trying to load some data from a Sharepoint list into my C# application. For this I am using the Microsoft.Graph Client Library Version 5.36.0.
In Sharepoint I have a list, to which I added some custom columns. E.g. I added a `string` column with the header `Description`. Now I want to get all list items from that list. I only require the `id` and the `Description` columns and for performance reasons, I only want those two values to be returned by the request, not the complete `fields` collection. Testing with the Graph Explorer, it suggested the following code:

```
var result = await graphClient.Sites["{site-id}"].Lists["{list-id}"].Items.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Select = new string []{ "id" };
	requestConfiguration.QueryParameters.Expand = new string []{ "fields(select=Description)" };
});
```

However, when executing the given code in my application, I receive the following exception:
```
:Microsoft.Graph.Models.ODataErrors.ODataError
:Parsing OData Select and Expand failed: Term '(select=Description)' is not valid in a $select or $expand expression.
```

What am I doing wrong? Is there a way to resolve that issue? And is that an issue that is already known? So far I have not found anything here on GitHub or other known sites.
Thanks in advance.

**To Reproduce**
1. Create a minimal C# project.
2. Include the MS Graph Client Library version 5.36.0
3. Create a Sharepoint list with additional columns that are contained in the `fields` collection
4. Copy the code above an execute
5. The given error should occure

**Expected behavior**
I want to receive a `ListItemCollectionResponse` that contains the `id` value and the `fields/Description` value.
I do not expect an error to be thrown, because I used the suggested code from the Graph Explorer.

**Client version**
Version 5.36.0

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version 10.0.22631

**Comment by MartinM85** [comment]
I think it's related to the endpoint itself. The `select` inside the `expand` should start with `$` => `$select`. Some sites endpoints work without `$` others with `$`

`requestConfiguration.QueryParameters.Expand = new string []{ "fields($select=Description)" };`

**Comment by JannisBrauer** [comment]
Thanks a lot Martin. That resolved the problem!
