### ISSUE TITLE
Microsoft Graph OneDrive can't filter by file type - drives search filter doesn't support "endsWith" or filter by file extension

### ISSUE THREAD

**Issue by jimbarrett33** [microsoftgraph/msgraph-sdk-dotnet#2377]
**Describe the bug**
`/drives/<id>/items/root/children?$filter=endsWith%28name%2C%20%27.xlsx%27%29`

This may not be the place for this issue but I created SO issue [https://stackoverflow.com/questions/38461833/how-do-you-filter-by-file-type-extension-using-microsoft-graph-api](https://stackoverflow.com/questions/38461833/how-do-you-filter-by-file-type-extension-using-microsoft-graph-api) about 7 years ago and seem the MS Graph API still doesn't support filtering by file type.

Maybe (hopefully) I'm missing something and it IS supported somehow but I can't find it in the docs and trying the below code results in a an exception:

            var searchResult = await graphServiceClient
                    .Drives[userDriveId]
                    .Items["root"]
                    .Children
                    .GetAsync(requestConfiguration =>
                    {
                        requestConfiguration.QueryParameters.Filter = $"endsWith(name, '.xlsx')";
                    });

BTW. `startsWith" DOES work.

**To Reproduce**
Try the above...

**Expected behavior**
A way to filter graph by file type or `endsWith`. `endsWith` is part of oData spec and appears still not support in Graph API for drive items?

**Comment by andrueastman** [comment]
Thanks for raising this @jimbarrett33 

This isn't supported by the API at the moment as far as I know. You can however create a feature request for the API team at the link below to give feedback on this. IT would be great if you could post back the link to the same as a comment so that anyone who comes across this can upvote it. 

https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by jimbarrett33** [comment]
@andrueastman Thanks for the response. Here is the feature request I created.


[Enable filtering OneDrive by file type with either endsWith filter or a custom filter on "fileType" or "extension"](https://feedbackportal.microsoft.com/feedback/idea/af0c180e-f0df-ee11-a73d-6045bdbdc092)

**Comment by andrueastman** [comment]
Thanks @jimbarrett33.

Closing for now so this may be followed up from there
