### ISSUE TITLE
Clone Team method doesn't have a return result

### ISSUE THREAD

**Issue by avanadrichem** [microsoftgraph/msgraph-sdk-dotnet#2378]
**Describe the bug**
Clone Team method doesn't have a return result.

**To Reproduce**
Try the following code in C#.

```
var body = new Microsoft.Graph.Teams.Item.Clone.ClonePostRequestBody
{
// params
};
var response = await GraphClient.Teams[team.Id].Clone.PostAsync(body);

```
The Clone method doesn't have a return result as described in the documentation.

**Expected behavior**
The documentation states: If successful, this method returns a 202 Accepted response code with a Location: header pointing to the [operation](https://learn.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0) resource. When the operation is complete, the operation resource tells you the ID of the created team.

**Client version**
Latest Graph 5 SDK for .NET

**Comment by andrueastman** [comment]
Thanks for raising this @avanadrichem 

Any chance the response here is helpful in your scenario? https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2344#issuecomment-1961346824

The SDK does not support monitoring long running operations as described in the docs below, (this is tracked via https://github.com/microsoftgraph/msgraph-sdk-design/issues/83)
https://learn.microsoft.com/en-us/graph/long-running-actions-overview?tabs=http

**Comment by avanadrichem** [comment]
It does help, but still I think the SDK should provide some support for creating and cloning Teams.

**Comment by andrueastman** [comment]
Thanks for the feedback. 
We'll close this and track this via https://github.com/microsoftgraph/msgraph-sdk-design/issues/83 and have this added once the implementation specification is ready.
