### ISSUE TITLE
Unable to perform large file uploads via GraphServiceClient when authenticating using an app role

### ISSUE THREAD

**Issue by 978735987345345** [microsoftgraph/msgraph-sdk-dotnet#2379]
When trying to perform a large file upload to a SharePoint Drive (Document Library) through the current version of the C# SDK for Graph, using an app role, `fileUploadTask.UploadAsync()` gives this error:

```
Unhandled exception. Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException: IDW10502: 
An MsalUiRequiredException was thrown due to a challenge for the user.
See https://aka.ms/ms-id-web/ca_incremental-consent.
```

The code below is derived from this [official example](https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp).

The `uploadSession` has been created with a call to `PostAsync()` configured with `r => r.Options.WithAppOnly()`. This call succeeds.

The `uploadSession` is used to construct a `LargeFileUploadTask`, resulting in `fileUploadTask`, and `fileUploadTask.UploadAsync()` fails because it can't authenticate with the app role.

`LargeFileUploadTask.UploadAsync()` does not offer the opportunity to configure the call with `WithAppOnly()`, per the documention: https://learn.microsoft.com/en-us/dotnet/api/microsoft.graph.largefileuploadtask-1.uploadasync?view=graph-core-dotnet

Why does the `fileUploadTask` not use the authenticated session when performing the upload under the app role? Is there a workaround?

```csharp
static async Task UploadDriveItem(GraphServiceClient graphServiceClient, Drive drive, string filePath, string itemPath)
{
	Console.WriteLine($"Uploading {filePath} to {itemPath}");
	using var fileStream = File.OpenRead(filePath);


	var uploadSessionRequestBody = new DriveUpload.CreateUploadSessionPostRequestBody
	{
		Item = new DriveItemUploadableProperties
		{
			AdditionalData = new System.Collections.Generic.Dictionary<string, object>
			{
				{ "@microsoft.graph.conflictBehavior", "replace" },
			},
		},
	};

	// Create the upload session
	// itemPath does not need to be a path to an existing item
	// var myDrive = await graphServiceClient.Me.Drive.GetAsync(r => r.Options.WithAppOnly());
	var uploadSession = await graphServiceClient.Drives[drive.Id]
		.Items["root"]
		.ItemWithPath(itemPath)
		.CreateUploadSession
		.PostAsync(uploadSessionRequestBody, r => r.Options.WithAppOnly());

	// Max slice size must be a multiple of 320 KiB
	int maxSliceSize = 320 * 1024;
	var fileUploadTask = new LargeFileUploadTask<DriveItem>(
		uploadSession, fileStream, maxSliceSize, graphServiceClient.RequestAdapter);

	var totalLength = fileStream.Length;
	// Create a callback that is invoked after each slice is uploaded
	IProgress<long> progress = new Progress<long>(prog =>
	{
		Console.WriteLine($"Uploaded {prog} bytes of {totalLength} bytes");
	});

	try
	{
		// Upload the file
		var uploadResult = await fileUploadTask.UploadAsync(progress);

		Console.WriteLine(uploadResult.UploadSucceeded ?
			$"Upload complete, item ID: {uploadResult.ItemResponse.Id}" :
			"Upload failed");
	}
	catch (Microsoft.Graph.Models.ODataErrors.ODataError ex)
	{
		Console.WriteLine($"Error uploading: {ex.Error?.Message}");
	}
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @978735987345345 

The issue may lie with how the `graphServiceClient` is initialized. Any chance you see a different result if you do not pass the requestAdapter parameter to the task as below?

```cs
	var fileUploadTask = new LargeFileUploadTask<DriveItem>(
		uploadSession, fileStream, maxSliceSize);
```

**Comment by 978735987345345** [comment]
Omitting the requestAdapter parameter successfully uploads the file. Thank you!

Why does this work?

**Comment by andrueastman** [comment]
Thanks for confirming this @978735987345345 

As it looks like you are using the client is initialized by the `Microsoft.Identity.Web` library, the issue lies with how the library is initializing the client. 
As requests to the `UploadUrl`(which is not a graph url) in the `UploadSession` are not authenticated, the custom `IAuthenticationProvider` used by the library should not be trying to acquire a token for the upload session. Removing the parameter makes the SDK internally initialize a client that will not try to authenticate these requests. 

We've created the bug at the link below so that this may be followed up from the Microsoft.Identity.Web library. 
https://github.com/AzureAD/microsoft-identity-web/issues/2710

We'll close this for now so that it may be followed up there.
