### ISSUE TITLE
Graph SDK and SchemaExtensions

### ISSUE THREAD

**Issue by riccardobecker** [microsoftgraph/msgraph-sdk-dotnet#238]
Hi there,
thanks for sharing the Microsoft Graph as an SDK!

I use the SDK to create a schema extension on the object type User. That works fine. Also setting the value from within C# code works fine.

The issue is with retrieving this extension property. THe name of the schema extension is ext0bhczrqa_userProfile

Using the Graph Explore with the following GET:

https://graph.microsoft.com/v1.0/me?&$select=displayName,id,description,ext0bhczrqa_userProfile

Shows me the schema extension property value I just created.

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(displayName,id,description,ext0bhczrqa_userProfile)/$entity",
    "id": "fead7350-13b8-4984-81b3-eda742354bb2",
    "displayName": "Riccardo Becker",
    "ext0bhczrqa_userProfile": {
        "@odata.type": "#microsoft.graph.ComplexExtensionValue",
        "manufacturer": "audi"
    }
}

The big question is, how do I get the 'userProfile' extension from with my C# code using the Graph SDK?

Many thanks,
Riccardo

**Comment by MIchaelMainer** [comment]
Take a look at this test code: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.Test/Requests/Functional/SchemaExtensionTests.cs#L56

Let us know whether this is helpful.

**Comment by riccardobecker** [comment]
Michael, thanks for replying. I think I wasn't clear enough. It's about getting the schema extension values from a specific user. So after creating the schema extension on the "User" object and adding them to a specific user,  the issue is to get those extension values and put them in a set of claims during authentication.

I have a webapi that will filter data from a db based on these values in the schema extension properties of that specific logged in user.

thanks

**Comment by MIchaelMainer** [comment]
I think this is what you want:

                var query = new List<Option>()
                {
                    new QueryOption("$select", "ext0bhczrqa_userProfile")
                };

                var userWithSchemaExt = await graphClient.Me.Request(query).GetAsync();

**Comment by MIchaelMainer** [comment]
I haven't heard back so I hope this helped, and I'm closing this issue.

**Comment by MaciejWanat** [comment]
@MIchaelMainer I have exactly the same problem which is described here. I tried your solution. I am able to read extensions by calling REST API manually, but when I use SDK query result ends up being mapped into `Microsoft.Graph.User` entity which doesn't contain my extension field, therefore I don't get information I need. Is there any solution for this?

**Comment by darrelmiller** [comment]
@MaciejWanat   Have you looked in the AdditionalData dictionary?   All properties in the payload that do not map to the strong type are stored in the AdditionalData property.

**Comment by MaciejWanat** [comment]
@darrelmiller AdditionalData is null aswell.

**Comment by MaciejWanat** [comment]
I see what the problem is - my request is not `await graphClient.Me.Request(query).GetAsync();` but `await graphClient.Users.Request(query).GetAsync();`, I assumed that the behavior should be the same, but it's not. For Me endpoint it returns correct data. Is there any way to achieve the same goal with `Users` - that is to get all the users along with ext?

**Comment by darrelmiller** [comment]
Glad you solved your problem.  Thanks for letting us know.

**Comment by ibm-garage-nice** [comment]
Hi @MaciejWanat I'm facing the same problem. `AdditionalData` is always null. Could you please elaborate on the permissions you had to give to solve the problem ?
Thanks.

**Comment by jmereaux** [comment]
Hi @MaciejWanat I'm facing the same problem. `AdditionalData` is always null. Could you please elaborate on the permissions you had to give to solve the problem ?
Thanks.
