### ISSUE TITLE
V5.44 Get List and ListItem not works with relativepath url of site

### ISSUE THREAD

**Issue by rajeshpatil74** [microsoftgraph/msgraph-sdk-dotnet#2381]
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/4305331/0737ac61-ac52-47a2-afee-6320ea16dd7c)

    ```
    public async Task<IEnumerable<ListItem>?> GetItems(string siteName, string listName)
        {

            var site1 = (await GraphClient.Sites[siteName].GetAsync());

            var list2 = await GraphClient.Sites[site1.Id].Lists.GetAsync();

            var items2 = (await GraphClient.Sites[site1.Id]
                            .Lists[listName].Items
                            .GetAsync())?.Value;


            **var list1 = await GraphClient.Sites[siteName].Lists.GetAsync();

            var items = (await GraphClient.Sites[siteName]
                            .Lists[listName].Items
                            .GetAsync())?.Value;**

            if (items == null)
                return null;

            return items;
        }
```
Fetching list and list items with siteName fails. SiteName is relativePath like "contoso.sharepoint.com:/sites/mysite".
But getting site by relativePath works and using that Id later to retrive site lists and listitem works.
What is wrong with the code when fetching list and list item using site relative path. The code marked in red color.?

**Comment by andrueastman** [comment]
Thanks for raising this @rajeshpatil74 

According to the docs it doesn't look possible to list lists using the relative path. https://learn.microsoft.com/en-us/graph/api/list-list?view=graph-rest-1.0&tabs=http#http-request

Any chance you can post the question at the link below to et feedback from the API owners on whether this is a supported API senario? 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph
