### ISSUE TITLE
Filtering OneDrive items is not working properly

### ISSUE THREAD

**Issue by xDDDx** [microsoftgraph/msgraph-sdk-dotnet#2389]
**Describe the bug**
I try to find some special folder in sharepoint, that are exists and are unique. But the results are not korrekt. Some of the filter request gives me multiple results for the same folder (same ID) and for other filter I don't get any results although it should be one. 

If I change the page size by setting the Top parameter the results differs to. So my fealing is, that the pointer of the skiptoken is not right. I tried it also with PageIterator and got same results

**To Reproduce**
My code looks like this
``` C#
var page = await ExecuteGraphQuery(graphClient, async client =>
                await client.Drives[myDriveId].Items
                    .GetAsync(c =>
                    {
                        c.QueryParameters.Filter = $"endswith(name, '_{id}')";
                    }));
var items = page.Value ?? new List<DriveItem>();
while (page.OdataNextLink != null)
{
     page = await ExecuteGraphQuery(graphClient, async client =>
                  await client.Drives[myDriveId]
                        .Items
                        .WithUrl(page.OdataNextLink)
                        .GetAsync());
    items.AddRange(page.Value ?? Enumerable.Empty<DriveItem>());
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @xDDDx 

I believe the API doesn't support the `endwith` filter well at the moment. Please checkout https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2377 and upvote the linked feature request for the API owners to look into supporting this. 

We'll close this for now as this isn't an SDK related issue.
