### ISSUE TITLE
Add support for ItemAttachment to API

### ISSUE THREAD

**Issue by EricZimmerman** [microsoftgraph/msgraph-sdk-dotnet#239]
I can deal with FileAttachment, but ItemAttachments remain unavailable. Please expose a way to get to these items, or provide a sane way to do it via some REST endpoint from a Graph object vs manually building a URL.

**Comment by MIchaelMainer** [comment]
Please reopen this issue with the information requested in the issue template.

**Comment by EricZimmerman** [comment]
all that for you to take a look at not having the ability to interact with an ItemAttachment in graph and get its content vs metadata? the json is right in the docs already. =/

**Comment by MIchaelMainer** [comment]
I think the ability to interact with an ItemAttachment is there. It is obscure and there isn't any documentation for the client library so I can't say for sure.

```csharp
// Get information about attachments on the first message that has attachments.
var attachments = await graphClient.Me.Messages[messageCollection[0].Id]
                                        .Attachments
                                        .Request()
                                        .GetAsync();

// Get an attachment.
var attachmment = await graphClient.Me.Messages[messageCollection[0].Id]
                                        .Attachments[attachments[0].Id]
                                        .Request()
                                        .GetAsync();

if (attachmment.ODataType == "#microsoft.graph.itemAttachment")
{
    var expandQuery = new List<Option>()
    {
        new QueryOption("$expand", "microsoft.graph.itemattachment/item")
    };

    var itemAttachment = (ItemAttachment) await graphClient.Me.Messages[messageCollection[0].Id]
                                                            .Attachments[attachments[0].Id]
                                                            .Request(expandQuery)
                                                            .GetAsync();

    OutlookItem item = itemAttachment.Item;
    // TODO: Inspect for OutlookItem type.
}
```

**Comment by EricZimmerman** [comment]
i shall try this! thank you much!

**Comment by MIchaelMainer** [comment]
You're welcome. Let us know if it works.

**Comment by EricZimmerman** [comment]
i tried incorporating this, but ended up getting an error about not having a valid token when getting the Result of the await. this is after i have used other graph API calls to get the email, etc. strange

**Comment by MIchaelMainer** [comment]
That is strange. Are you consistently getting that error? 

Another thought I just had was to replace the `if` with the following:

```
    var outlookItem = (OutlookItem) await graphClient.Me.Messages[attachment.Id]
                                                            .Request()
                                                            .GetAsync();
```

**Comment by EricZimmerman** [comment]
yea it happened every time i tried it.

will try your second suggestion now

**Comment by EricZimmerman** [comment]
GOOD NEWS

i got it working. i had to change what you posted to:

graphClient.Users[emailAccount].

as i am not looking at MY stuff. i got back the info once i changed this. =)
