### ISSUE TITLE
Microsoft booking - Booking business does not show up in the portal when created via the sdk

### ISSUE THREAD

**Issue by Clapla** [microsoftgraph/msgraph-sdk-dotnet#2390]
**Describe the bug**
When creating new booking businesses and publishing it. I can see that the booking business is created when getting it by id. But when I go in the microsoft booking portal using the master account that I assigned as a staff member in it I just don't see my booking business. What am I missing?

**To Reproduce**
Here is the code I am using:
`

        try
        {
            var x = await Client.Solutions.BookingBusinesses.PostAsync(bookingBusiness);
            await Client.Solutions.BookingBusinesses[x.Id]
               .Publish.PostAsync();

            var bookingStaffMember = new BookingStaffMember()
            {
                DisplayName = _configuration.Username,
                EmailAddress = _configuration.Username,
                Role = BookingStaffRole.Administrator
            };
            var bookingStaffMemberBase = await Client.Solutions.BookingBusinesses[x.Id]
               .StaffMembers.PostAsync(bookingStaffMember);
        }
        catch (Exception ex)
        {
            return Result.Invalid(ex.Message);
        }`

**Expected behavior**
To see the booking business in my user microsoft booking portal

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/159572385/6e2045cb-fd5d-482b-9aa5-a70faf8291f4)

**Comment by andrueastman** [comment]
Thanks for raising this @Clapla 

Just to help understand if this issue is SDK or API related, do you still see the same issue if you create the business using a different method like the [Graph Explorer](http://aka.ms/ge) or Postman?
