### ISSUE TITLE
Enable Upload Speed Cap when using LargeFileUploadTask

### ISSUE THREAD

**Issue by lavinir** [microsoftgraph/msgraph-sdk-dotnet#2397]
Currently when uploading large files to OneDrive there is no way to limit the amount of bandwidth used. For lower bandwidth connections and large files, this can result in "choking" the full capacity of the upload speed.

**Describe the solution you'd like**
It would be nice to have a configuration property that can be set to limit the maximum speed the task should use and have it throttle back the transfer speed when necessary.

**Describe alternatives you've considered**
I guess this can be done manually by using the API directly with the SDK but that's not ideal.

**Comment by andrueastman** [comment]
> I guess this can be done manually by using the API directly with the SDK but that's not ideal.

Thanks for raising this @lavinir.

Any chance you may know of a mechanism to limit the upload speed/bandwidth when the httpClient is perfoming an operation?

**Comment by lavinir** [comment]
Hi @andrueastman,

I'm not aware of a way to do this directly in HttpClient. I assumed that the LargeFileUploadTask is splitting the file into chunks and uploading those requests individually. 
Then you can impose a speed limit when sending the chunks taking their size into consideration.

**Comment by andrueastman** [comment]
> Then you can impose a speed limit when sending the chunks taking their size into consideration.

Would this mean adding a kind of delay?

Is this already possible by passing a custom `chunksize` parameter to the task and leveraging the progressCallback function that is called on every chunk to work out for your scenario?

**Comment by lavinir** [comment]
Sorry @andrueastman  I missed this. 
I initially tried using the progressCallback for this but it (correctly) makes those calls asynhronously and you cannot delay the next chunk by introducing a delay in the progress callback. It will have to be added internally.
