### ISSUE TITLE
January Release?

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#240]
Why didn't it happen? 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/221

**Comment by MIchaelMainer** [comment]
The simple answer is that when we generated the client library from the Report API metadata, we discovered that the metadata didn't describe the actual API. We weren't able to use the API from the generated request builders. 
Additionally, there is a redirect and our generated request builders doesn't follow redirects by default. 

With that stated, here is how you can use the Report API with this library:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.Test/Requests/Functional/ReportTests.cs

**Comment by christophwille** [comment]
This begs the question: Is there no process in place (on the Graph API side, not SDK) to properly validate the metadata? Wasn't expecting to hear time and again that metadata is wrong.

**Comment by MIchaelMainer** [comment]
In this case, I'm unaware of a way to specify in metadata that you must support a redirect and expect a csv file. I'm not familiar with this API but I'd guess that it was designed before the Graph API and then onboarded to Graph later. The Microsoft Graph first APIs do not seem to have this issue. 

Regarding validation, yes, there is, but we could do more on the SDK side to confirm that new APIs are going to work as expected.

**Comment by christophwille** [comment]
So the Jan release didn't happen for this reason - what is the timeline this is fixed so the SDK can ship?

I asked that way back already: is there any "plan" (communicated) as to what is coming next with rough timelines? Is this what the 1-5 labels are meant to be?

**Comment by MIchaelMainer** [comment]
No one has given me a timeline on when to expect changes in the Reporting API. Regardless, the Reporting API is accessible from the SDK, just not in request builders. 

The client libraries roughly follow the release patterns for the Graph API itself. The 1-5 labels are relative priorities across just this library.
