### ISSUE TITLE
[Client bug]: C# QueryParameters.Filter doesn't work

### ISSUE THREAD

**Issue by IvoryFeng** [microsoftgraph/msgraph-sdk-dotnet#2401]
**Describe the bug**
I want to use filter to retrieve items on a SharePoint list in a .Net 8 console app using C#. In the RequestConfiguration, I can use Select and Expand. However, whenever I added the Filter, I got the error: "The expression cannot be evaluated.  A common cause of this error is attempting to pass a lambda into a delegate". I tried many different ways to set the Filter.

**To Reproduce**
            var res = await _graphServiceClient.Sites[siteId].Lists[listId].Items.GetAsync((requestConfiguration) =>
            {
                requestConfiguration.QueryParameters.Filter = "name eq 'Cyber Security'";
                requestConfiguration.QueryParameters.Select = ["name", "id", "webUrl", "parentReference"];
                requestConfiguration.QueryParameters.Expand = ["DriveItem", "Fields"];
            });

**Screenshots**
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/110053734/0986f253-ea1b-47a8-879b-1c6639840d07)

**Client version**
Provide the client version number from the NuGet package.
Microsoft.Graph 5.45.0

**Desktop (please complete the following information):**
Windows 11

**Comment by andrueastman** [comment]
Thanks for raising this @IvoryFeng 

Any chance you are able to perform the same query on [the graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)? I suspect the API may not support that query.

**Comment by IvoryFeng** [comment]
In Graph Explorer, I got an error. The same filter works on another endpoint. 
    "error": {
        "code": "generalException",
        "message": "General exception while processing"

**Comment by andrueastman** [comment]
Any chance you can share a sample of the query that works and does not work on the graph explorer to help understand this better?

**Comment by abhi-shukla** [comment]
Facing the same issue, is there a plan to fix this ?

**Comment by asith-w** [comment]
I also got same issue for below code, is it sdk issue? works well in graph explore  

**//DOES NOT WORK** 
```
var resultq = await _appClient.Me.Messages.GetAsync((requestConfiguration) =>
{
     requestConfiguration.QueryParameters.Filter = "from/emailAddress/address eq 'mssecurity-noreply@microsoft.com'";
});
```

**//WORKS**
```
var resultw = await _appClient.Users.GetAsync((requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Filter = "NOT(imAddresses/any(i:i eq 'admin@contoso.com'))";
    requestConfiguration.QueryParameters.Count = true;
    requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
});
```

**Comment by ardonjr** [comment]
I run into the same issue.
When I do a search query like below on a site with a specific list

```
var requestBody = new Microsoft.Graph.Search.Query.QueryPostRequestBody()
        {
            Requests =
            [
                new SearchRequest()
                {
                    EntityTypes = [EntityType.List],
                    Query = new SearchQuery()
                    {
                        QueryString = $"/sites/ThisIsTheSiteName/ThisIsTheListName",
                    }
                }
            ]
        };

        var response = await _graphServiceClient.Search.Query.PostAsQueryPostResponseAsync(requestBody);
```

I get a valid response with the list object.
However when I do request the .Listst object with applied filter it return an error
```
var lists = await _graphServiceClient.Sites[site.Id].Lists.GetAsync(
 (requestConfiguration) =>
{
    requestConfiguration.QueryParameters.Filter = $"name eq ThisIsTheListName";
    
});
```

**Invalid filter clause: Could not find a property named 'ThisIsTheListName' on type 'microsoft.graph.list'.**
