### ISSUE TITLE
[Client bug]: Miscrsoft.Graph 4.46.0  return a wrong drive 

### ISSUE THREAD

**Issue by charliewyf** [microsoftgraph/msgraph-sdk-dotnet#2402]
I have a file fileName1 under driveA. I have an empty driveB under root as well.
When I request the DriveItem using GraphServiceClient, I set param:
_client.Drives[driveId].Items[graphId].Request().GetAsync();

The issue is, it will return the DriveItem although I use a wrong drive Id, driveB Id.
the return value contain a property, ParentReference, with DriverId I transfer to client.
It really confuse that actually the file is just under driveA.
My packege version is 4.46.0.
It happen from 3/19/2024.

Should I must update package to v5 to resolve this issue?

**Comment by andrueastman** [comment]
Thanks for raising this @charliewyf 

Just to confirm, did this happen after a code change of the SDK version? Are you able to replicate the behavior when using the [graph explorer](http://aka.ms/ge)?

**Comment by charliewyf** [comment]
@andrueastman Thanks for your reply!
This issue happen without any code change. We used v4.46.0 for a long time. It happen after 3/19/2024. I have no test on graph explorer due to security policy.

**Comment by andrueastman** [comment]
> Should I must update package to v5 to resolve this issue?

I don't believe so. 
This sounds like API related behavior which we may not be best placed to give answer as this repo is mainly for SDK related issues. Any chance you can post the same query at the link below to get feedback from the API owners? It would be great if you could post the link to the created question as a comment here a well. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

**Comment by charliewyf** [comment]
https://learn.microsoft.com/en-us/answers/questions/1647294/api-return-wrong-drive-when-request-have-a-drive

**Comment by andrueastman** [comment]
Thanks for this @charliewyf 

We'll close this for now so that this may be followed up there.
