### ISSUE TITLE
Adding skiptoken to query parameters for graph api v5 requests 

### ISSUE THREAD

**Issue by sant2006** [microsoftgraph/msgraph-sdk-dotnet#2404]
### Issue
I'm trying to add skiptoken query parameter to various graph apis like list users, list sharepoint sites, list sharepoint lists in a site, list notebooks, list sections in a notebook, list channels in a team, get drive delta changes etc. I'm using  Graph v5 .NET Client Library (dotnet sdk). None of the RequestBuilderGetQueryParameters have skiptoken option which was supported in graph api v4 based SDK code.
 
### What I've tried 
I've tried below workaround  
``` 
var listsRequestBuilder = GraphServiceClient.Sites[siteId].Lists;
var requestInfo = listsRequestBuilder.ToGetRequestInformation();
// requestInfo.UrlTemplate = requestInfo.UrlTemplate.Insert(requestInfo.UrlTemplate.Length - 1, ",%24select,%24expand,%24skiptoken");
requestInfo.QueryParameters.Add("%24select", "system,*");
requestInfo.QueryParameters.Add("%24expand", "drive");
if (!string.IsNullOrWhiteSpace(token))
   {
         requestInfo.QueryParameters.Add("%24skiptoken", token);
   }
```

But request is not accepting skiptoken, response has all items. When I enabled the commented out line above,  got Kiota Api exception **"Microsoft.Kiota.Abstractions.ApiException: The server returned an unexpected status code and no error factory is registered for this code: 400"**

### Expected behaviour
 All graph apis returning pages of results and nextLink having skiptoken should have an option to accept skiptoken in the request to get response like below 

var listsRequestBuilder = GraphServiceClient.Sites[siteId].Lists;
await  listsRequestBuilder.GetAsync(rc => rc.QueryParameters.SkipToken = "token");

**Client version**
5.37 and 5.46

**Additional context**
This is true for all graph apis not just for the ones I've listed above.

**Comment by andrueastman** [comment]
Thanks for raising this @sant2006 

Any chance the documentation at the link below is helpful?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests

**Comment by sant2006** [comment]
@andrueastman thanks for responding to my query. In the above provided graph v5  upgrading documentation, sorry  I don't see any option to add skiptoken to the first request making to get 1st pages of changes in groups delta request.  

Graph v4 we had query option to add skip token to the first request we making to the graph endpoints  (sorry my example is about sharepoint lists, but v4 had this query option to all apis which returns pages of items)
```
var listsRequest = GraphServiceClient.Sites[siteId].Lists.Request();
listsRequest.QueryOptions.Add(new QueryOption("$skiptoken", token));
```

**Comment by andrueastman** [comment]
Where do you get the `$skiptoken` from? Do you get it from parsing the odata.nextLink of a previous response? 
As the `nextLink` url is opaque, the metadata used to generate the sdk will not contain this parameter and the expectation is to pass the entire url to the request object

```cs
GraphServiceClient.Sites[siteId].Lists.WithUrl("https://graph.microsoft.com/v1.0/xxxxxxx/delta?$skiptoken=xxxxx);
```

**Comment by sant2006** [comment]
@andrueastman  you are right, `$skitoken` we get from parsing  the odata.NextLink  of  previous response. This was supported in sdk v4. Is this true for all graph api calls including the delta api to track changes in  a drive?
Thanks

**Comment by sant2006** [comment]
@andrueastman could you give an update on this? 
thanks

**Comment by andrueastman** [comment]
> Is this true for all graph api calls including the delta api to track changes in a drive?

Yes. As highlighted in the link below, the `$skiptoken` parameter isn't part of the api metadata as the `odata.NextLink` is an opaque url and therefore should not be parsed out to get the individual parameters from it. The implication here is that the API could change the URL format to something else and use a different parameter and should therefore be used as is as whole.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#skiptoken-and-deltatoken-query-parameters-in-delta-requests

The correct thing to do therefore is to use the entire url and pass it over to the `WithUrl` method as advised above.

**Comment by sant2006** [comment]
@andrueastman thanks for clarifying. Documentation provided above do not have an example of first request taking nextLink, it's  explaining first request without any skipToken, deltaToken, then making subsequent requests with nextLink/delta link url.
For any request builders can I make first request with `requestBuilder.WithUrl(rawUrl)` ?  For example  below code would return all sites in a tenant ? 
```
var sites = await GraphServiceClient.Sites.WithUrl(rawUrl).GetAsync();
```
How about delta changes in a drive? Does it support token in the request instead of url?
```
var deltaWithTokenGetResponse = await  GraphServiceClient.Drives[driveId].Items["root"].DeltaWithToken(token).GetAsDeltaWithTokenGetResponseAsync();
```
Is this call work with the token from nextLink or only with deltaLink token? Please clarify.
Thanks

**Comment by andrueastman** [comment]
Ideally, you would make the first call as `var sitesResponse = await graphClient.Sites.GetAsync();` and if the `OdataNextLink` property exists, this means there is another page of data. You would then use it to fetch the next page of data. Something close to this. 

```cs
            // make first request
            var sitesResponse = await graphClient.Sites.GetAsync();
            while (!string.IsNullOrEmpty(sitesResponse.OdataNextLink))// next link exists
            {
                // make next request
                sitesResponse = await graphClient.Sites.WithUrl(sitesResponse.OdataNextLink).GetAsync();
            }
```

This is can also be done using the PageIterator which abstracts this for you. https://learn.microsoft.com/en-us/graph/sdks/paging?tabs=csharp

For the case of the drive api, this is a special case as it supports the `token` parameter in the path and not the query(which is not really the same as skipToken or deltaToken. See example 2 at https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http#example-2-last-page-in-a-set). So it ends up having a url like `xxxx/delta(token='ddd')` which can cause confusion and will be cleaned up via https://github.com/microsoftgraph/msgraph-metadata/issues/431

The recommended pattern at the end of the day is to use the PageIterator or something close to the code sample above and not really parse out the tokens from the URL in either scenario.

**Comment by sant2006** [comment]
@andrueastman thanks for clarifying.  I'm aware of `await graphClient.Sites.GetAsync();`.  
My question is based on a different context. First request could be very first request or a restart request.Let's say I'm enumerating a SharePoint list to get millions of items and at the last page for some reason enumeration crashed. In that case I would like to restart from the page where  it crashed/stopped working. 

This question is applicable for all graph calls returning a collection. If anything goes wrong in the middle of enumeration, how to restart? using `.WithUrl()` with last nextLink ?  

About drive delta,  your recommendation is to get delta token using `GET /me/drive/root/delta?token=latest `instead of parsing the delta token from the deltaLink url ?
Thanks

**Comment by andrueastman** [comment]
> This question is applicable for all graph calls returning a collection. If anything goes wrong in the middle of enumeration, how to restart? using .WithUrl() with last nextLink ?

Yes. Using the same/last nextLink should give you the same results that was expected of the page.

**Comment by sant2006** [comment]
@andrueastman   thanks for the help, this ticket can be closed.

**Comment by andrueastman** [comment]
Thanks for confirming!
