### ISSUE TITLE
Content type text/html does not have a factory registered to be parsed

### ISSUE THREAD

**Issue by TarasKovalenko** [microsoftgraph/msgraph-sdk-dotnet#2407]
I am trying to update the user outlook message category and after sending the request to the GraphSDK I got the next  exception:

```
ystem.InvalidOperationException: Content type text/html does not have a factory registered to be parsed
   at Microsoft.Kiota.Abstractions.Serialization.ParseNodeFactoryRegistry.GetRootParseNode(String contentType, Stream content)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetRootParseNode(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.Messages.Item.MessageItemRequestBuilder.PatchAsync(Message body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

Example of the implementation:
```
var graphClient = new GraphServiceClient(new HttpClient
{
	DefaultRequestHeaders = { Authorization = new AuthenticationHeaderValue("Bearer", authorizationToken) }
});
...
await graphClient.Me.Messages[InternetMessageId].PatchAsync(Message, cancellationToken: token);
```

I can read messages but can't update them.
Any idea how to solve this issue?

**Comment by ontur00** [comment]
Hello, I have the same problem but with the mail Forward method, it returns an error **{"Content type text/html does not have a factory registered to be parsed"}**

` public async Task<bool> ForwardMail(Guid emailId, int tenantid, EmailAccountSettingCacheItem emailAccountSettings, EmailMessage emailMessage, bool isHtml, IFormFileCollection formFiles, string emaildAccountId = "")
 {
     try
     {
         if (String.IsNullOrEmpty(emaildAccountId))
         {
             Logger.Error($"Failed GraphAPIConnector SendEmail tenantId: {tenantid} emailAccountSettingsId: {emailAccountSettings.Id} emaildAccountId is null");
             return false;
         }
         List<Attachment> tet = getFileAttachments(formFiles);

         var requestBodyForward = new ForwardPostRequestBody
         {
             Message = new Message
             {
                 Subject = emailMessage.Subject,
                 Body = new ItemBody
                 {
                     ContentType = isHtml ? Microsoft.Graph.Models.BodyType.Html : Microsoft.Graph.Models.BodyType.Text,
                     Content = emailMessage.Body,
                 },
                 ToRecipients = convertJObjectToRecipeintByKey(emailMessage.To, MailRecipients.To),
                 CcRecipients = convertJObjectToRecipeintByKey(emailMessage.Cc, MailRecipients.Cc),
                 BccRecipients = convertJObjectToRecipeintByKey(emailMessage.Bcc, MailRecipients.Bcc),
                 Attachments = getFileAttachments(formFiles)
             }
         };

         var graphClient = GraphAPIConnect(emailAccountSettings.E365TenantId, emailAccountSettings.E365ClientId, emailAccountSettings.E365ClientSecret);

         await graphClient.Users[emaildAccountId].Messages[emailMessage.MessageId].Forward.PostAsync(requestBodyForward);
		 
		 return true;
     }
     catch (ODataError ex)
     {
         Logger.Error($"GraphAPIConnector ForwardMail tenantId: {tenantid} emailAccountSettingsId: {emailAccountSettings.Id} " + ex.Message);
         return false;
     }
     catch (Exception ex)
     {
         Logger.Error($"GraphAPIConnector ForwardMail tenantId: {tenantid} emailAccountSettingsId: {emailAccountSettings.Id} " + ex.Message);
         return false;
     }
 }`

**Comment by jgauffin** [comment]
This error should not happen at all. The graph client should always return JSON. Imho this issue should not have been closed.

**Comment by dseph** [comment]
You can get an html response but not due to reaching Graph on the server end but rather because you did not.  Get a network trace and check what's in it.  Next, you need to recheck your call.  There is something wrong in getting authenticated or the Graph call or something in between is causing the issue.  Network traces and logs are CRITICAL to debugging and need to be considered in the planning stage of an application.
