### ISSUE TITLE
Can't patch the message partially. (Set action is invalid for property.)

### ISSUE THREAD

**Issue by TarasKovalenko** [microsoftgraph/msgraph-sdk-dotnet#2408]
I'm trying to update the message partially, in my case I need to update only message categories.
Example:
```
var result = await graphClient.Me.MailFolders["Inbox"].Messages.Delta.GetAsDeltaGetResponseAsync(requestConfiguration =>
{
	requestConfiguration.QueryParameters.Top = 200;
	requestConfiguration.QueryParameters.Select = ["internetMessageId"];
	requestConfiguration.Headers.Add(MSGraphHeaders.Prefer, MSGraphHeaders.ODataRequestTop201Items);
}, cancellationToken: token);

var msg = result.Value.First();
// update message categories...
// ...

await graphClient.Me.Messages[msg.Id].PatchAsync(msg, cancellationToken: token);
```

in this case, I will catch the `Set action is invalid for property` with status code 400 
`Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse`

As a workaround, I can get a message one more time and the update will work well.
```
var msg2 = await graphClient.Me.Messages[msg.Id].GetAsync(configuration =>
{
	configuration.QueryParameters.Select = ["categories"];
}, cancellationToken: token);

// update message categories...
// ...

await graphClient.Me.Messages[msg2.Id].PatchAsync(msg2, cancellationToken: token);
```

The only difference that I see between the msg and msg2 is that msg2 contains AdditionalData -> @odata.context:

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/2806803/d944ca3b-391e-4bd4-8e88-01f17d3ab6d2)

The question if @odata.context is required to patch the message, and if yes, how I can get it in the scope of GetAsDeltaGetResponseAsync?

**Comment by andrueastman** [comment]
Thanks for raising this @TarasKovalenko 

Any chance you are able to call `KiotaJsonSerializer.SerializeAsString` on the two message objects and share a diff of the serialized json values to help understand the issue better?

**Comment by TarasKovalenko** [comment]
> Thanks for raising this @TarasKovalenko
> 
> Any chance you are able to call `KiotaJsonSerializer.SerializeAsString` on the two message objects and share a diff of the serialized json values to help understand the issue better?

msg2 (which I can use to update message):
`{}`
msg (which I can't use to update message):
`{"id":"xxxxxxxxxxAQGa7ZPAAA=","@odata.type":"#microsoft.graph.message","@odata.etag":"W/\u0022xxxxxxxxxxkrTi3BFRo\u002Bv37MxxxxxxxxxxOdmw\u0022","internetMessageId":"\u003CIA2PR1xxxxxxxxxx@xxxxxxxxxx.prod.outlook.com\u003E"}`

**Comment by andrueastman** [comment]
Just to confirm, is this before or after you update the message categories?

**Comment by andrueastman** [comment]
What about after? It would be interesting to see what value is being sent to the server to cause the error. 

Also, any chance you can share the error message and code if you follow the guidance at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

**Comment by TarasKovalenko** [comment]
> What about after? It would be interesting to see what value is being sent to the server to cause the error.
> 
> Also, any chance you can share the error message and code if you follow the guidance at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library

seems like if I create a new instance of the message class and set only the categories array then everything works well.
```
await graphClient.Me.Messages[Message.Id].PatchAsync(new Message
{
	Categories = Message.Categories
}, cancellationToken: token);
```
I guess we can close this issue.

**Comment by TarasKovalenko** [comment]
seems like if I create a new instance of the message class and set only the categories array then everything works well.
```
await graphClient.Me.Messages[Message.Id].PatchAsync(new Message
{
	Categories = Message.Categories
}, cancellationToken: token);
```
