### ISSUE TITLE
Microsoft Graph 5.46.0 Message Forward create exception Content type text/html does not have a factory registered to be parsed

### ISSUE THREAD

**Issue by ontur00** [microsoftgraph/msgraph-sdk-dotnet#2411]
Hello, I have problem with mail Forward method, it returns an error **{"Content type text/html does not have a factory registered to be parsed"}**  

To authenticate i am using ClientSecret
```
 var clientSecretCredential = new ClientSecretCredential(
     e365tenantId, e365clientId, e365clientSecret, options);
```

I am using SendMail works fine 
`await graphClient.Users[emaildAccountId].SendMail.PostAsync(requestBody);`

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/11216422/4616b09c-6467-4471-9dd5-43b13a95e0bd)

**Comment by andrueastman** [comment]
Thanks for raising this @ontur00 

The error seems to suggest that the API is returning a content type of `text/html` which the SDK does not support. Furthermore, according to the API documentation, the API should respond with a 202 Http response code with no response body which is unusual.

Any chance you can change 

```cs
await graphClient.Me.Messages["{message-id}"].Forward.PostAsync(requestBody);
```

to

```cs
var requestInfo =  graphClient.Me.Messages["{message-id}"].Forward.ToPostRequestInformation(requestBody);
var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> {
    {"XXX", ODataError.CreateFromDiscriminatorValue},
};
var responseStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping);
var streamReader = new StreamReader(responseStream);
var responseString = await streamReader.ReadToEndAsync();
```

and share if the response content is expected xml?

**Comment by ontur00** [comment]
Hi i made changes but i got error **System.InvalidOperationException: 'Content type text/html does not have a factory registered to be parsed'**
![gapiE](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/11216422/fcfb3eb3-d919-4273-8c3b-2b485e9aae4d)
![changes](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/11216422/1dddaf2c-e475-40e8-8f25-50582f6ca664)

**Comment by andrueastman** [comment]
Any chance you can share the stack trace property of the exception? Does the error occur at the line of code with the call to `SendPrimitiveAsync`?

**Comment by ontur00** [comment]
Problem on this line `var responseStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping);`
StackTrace Value: 

>    at Microsoft.Kiota.Abstractions.Serialization.ParseNodeFactoryRegistry.GetRootParseNode(String contentType, Stream content)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<GetRootParseNode>d__30.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at AseeVT.Email.GraphAPIConnector.<ForwardMail>d__20.MoveNext() in C:\Users\artur\source\agarbacik\src\AseeVT.Application\Email\GraphAPIConnector.cs:line 564

**Comment by andrueastman** [comment]
Out of curiosity, do you get a different error if you do not pass the errorMapping parameter?
The SDK should not be trying to deserialize the response for the scenario where the response is set to a stream 


```cs
var responseStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo);
```

**Comment by ontur00** [comment]
Paste code `var responseStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo);` 
Error **{"The server returned an unexpected status code and no error factory is registered for this code: 400"}**
Stack Strace **   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at AseeVT.Email.GraphAPIConnector.<ForwardMail>d__20.MoveNext() in C:\Users\artur\source\agarbacik\src\AseeVT.Application\Email\GraphAPIConnector.cs:line 565**

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/11216422/ad0f994d-2950-4448-a27d-35fa67514ed8)

**Comment by andrueastman** [comment]
The status code of `400` suggests that there is something wrong with the parameters of the email being sent. 

Any chance you can capture a trace using fiddler of the request /response cycle to understand the payload being sent over to graph as well as the html response from the API?
