### ISSUE TITLE
Why is error checking so bad?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-sdk-dotnet#2415]
I have a program that is attempting to load drive items in a group, sometimes those groups are deleted so I've added exception handling for ignoring certain errors, but it seems like every few months the error format is changed slightly so it breaks my error handling code, e.g. I now have to check for 4 magic strings

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/137350/5e40f3f9-9bde-413b-a7d6-3186883a14e8)

Is there a better way to check for "item is missing" type errors and just ignore them?

**Comment by andrueastman** [comment]
Thanks for raising this @catmanjan 

For these scenarios, the API should ideally return a HTTP 404 status code. This can be done by using the StatusCode property in the ServiceException class(looks you're on an older version of the SDK).

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/6381c3af3f329ddcc1b1aa0ee162ea5171e67f01/src/Microsoft.Graph.Core/Exceptions/ServiceException.cs#L72

The properties `code` and `message` properties which are being matched are deserilized from the response bodies of the API responses which the SDK will have no control over. 

Let us know if this is helpful.

**Comment by catmanjan** [comment]
If graph is unavailable momentarily won't this also return a 404

**Comment by andrueastman** [comment]
I don't believe it will. It will return return a 502 or 503 which will be handled by the retry handler. The 404 error code is if the requested resource does not exist.

https://learn.microsoft.com/en-us/graph/best-practices-concept#handling-expected-errors
