### ISSUE TITLE
Message mime content; Attachments empty if defender is scanning them

### ISSUE THREAD

**Issue by MAlabaster** [microsoftgraph/msgraph-sdk-dotnet#2416]
**Describe the bug**
If the entire message content is obtained as a MIME format. Attachments which are being scanned by Defender are empty.
messages are saved using this code and the stream is copied to a filestream and saved with an .eml extension

Stream theMessageContent = await graphClient
    .Users[targetAccount]
    .Messages[theMessage.Id]
    .Content    //The message content in mime format
    .GetAsync();

We access customers' email inboxes, including GMail and IMAP and want a single process to process the messages so the MSGraph messages  _were_ saved in MIME format as EML files and processed with MimeKit library to get the attachments. When getting the attachments from the mime message they were sporadically empty. After changing the service to use MSGraph to obtain the attachments I noticed they were named "Safe Attachments Scan In Progress" which points to them being locked by Defender and explains the  sporadic nature of problem, only ones that happen to be locked when the content was obtained are affected. If the EML file is opened using Outlook, the attachents and their names appear OK , but on closer inspection they are only a few hundred bytes in size.

**To Reproduce**
Send multiple emails to the inbox, if they are processed immediately after arriving then attachments in the mime content file may be empty. if they are left long enough for Defender to have scanned them then they are not empty

**Expected behavior**
If attachments are locked by Defender Safe Attachments scan when obtaining MIME content, rename them to "Safe Attachments Scan In Progress" as happens when trying to obtain the attachments using MSGraph calls AND/OR throw an error on the MSGraph call to indicate an incomplete mime message if any attachments (or other mimeparts) are locked by email scanners.

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
 - Not applicable, process runs as windows service on 2012 & 2022
**Smartphone (please complete the following information):**
 -Not Applicable
**Additional context**
Workaround: When we process email attachments, any error results in the email being moved to an exceptions folder to prevent it being processed again. Using an MSgraph call to get the attachments I check the name and if it is "Safe Attachments Scan In Progress" then I exit the process leaving the email in the inbox to be picked up by the next poll interval, by which time Defender has probably unlocked all attachments.  This means having a separate process for MSGraph messages which we want to eliminate to save maintenance so we need some indication that the mime content is incomplete. So far this is very specific to Defender scans, I do not know if other email virus scanners will similarly lock email attachments.

**Comment by andrueastman** [comment]
Thanks for raising this @MAlabaster 

Unfortunately, we in the Microsoft Graph SDK team do not have any ownership of the APIs to add the functionality you need. If you share your idea in the Microsoft 365 Developer Platform forum, it will be possible for others to add upvote and get routed to the appropriate team for them to triage.

https://aka.ms/requestgraph

**Comment by MAlabaster** [comment]
Understood, thanks. I will raise it on the forum. I can't see it being a popular request but you never know.
