### ISSUE TITLE
Xamarin Form for android, how to sign in without Chrome app.

### ISSUE THREAD

**Issue by cansado2930** [microsoftgraph/msgraph-sdk-dotnet#242]
Hello,
### Expected behavior and Actual behavior
I have a question or an improvement if there are solution. I have implemented on my Xamarin form app to sign in with MS Graph and it works correctly. But various users have found a problem, they deleted/blocked Chrome app in order to use MS Edge on their android devices, so when MS Graph SDK tries to open the activity with login page, it fails because it can’t find Chrome. So, Are there other way in order to sign in MS Account using the available browser?
Thank you

### Steps to reproduce the behavior
Go to app list on settings and detele/block the chrome app (I have tried with Android 6). Then, install any Xamarin Form sample app for Android of MS Graph and then try to do login.

**Comment by MIchaelMainer** [comment]
This is interesting. This doesn't sound like it is specific to the Microsoft Graph scenario. Can users from an Android application on a phone with only Edge sign in using other OAuth flows? I highly suggest that you post this to StackOverflow.

**Comment by cansado2930** [comment]
Yes, I think that it isn't problem of SDK but I have asked here because I tried to use a embedded webview but I couldn't do it or I doesn't know to do it. My same app has project Rome with embedded WebView and this works correctly to sign in without Chrome. Could I do the sign in with a WebView for Ms Graph instead of open a new browser activity?
Ok, I'm going to ask it on StackOverflow.
Thank you

**Comment by cansado2930** [comment]
An user has found the problem on [StackOverflow](https://stackoverflow.com/questions/48908508/ms-graph-cant-open-a-new-browser-activity-when-chrome-is-disabled-deleted-of-de/48909874), the MSAL sdk search Chrome activity and this is the problem. I will open the issue on the correspond GitHub if they can search an alternative.
Very thank you!
