### ISSUE TITLE
Calendar ID is not consistent

### ISSUE THREAD

**Issue by woodzee89** [microsoftgraph/msgraph-sdk-dotnet#2423]
**Describe the bug**
Application permissions are being used with the GraphAPI.
User's select a calendar which is stored in the application by the ID attribute.
Once the user has selected a calendar, events in the application are synced over to the user's calendar. 

This all works and for the majority of the users and we have no issues. There are a subset of users across multiple tenants that we begin to see the follow error code after some time (days or months) have elapsed : ErrorItemNotFound

On investigation, the ID of the calendar is not the same. These users are connecting to their default calendar, noted by the Default flag and the immutable name "Calendar."

_**What would cause the calendar ID to change?**_

This bug is being submitted after consulting with Microsoft's support team.

**To Reproduce**
We have not been able to reproduce this in a sandbox environment. Audit logs from our partners do not show significant modifications to their tenants and being that these are the default calendars, the user has not deleted or changed calendars.

**Expected behavior**
The calendar ID would be static for the default (or any calendar).

**Additional context**
Code to retrieve Calendars and is the source of the calendarId in the code below. 
Note: This code may execute days apart. These are not back to back operations.
```
var userCalendars = await _graphClient.Users[credentials.AccountExternalKey].Calendars.Request().GetAsync();
...
var calendarId = calendar.Id.ToString(); // value is stored in the database for use in calls to retrieve events.
```

Request (one example) that is failing for the error above. Note again, this works for other users.
```
var request = _graphClient.Users[accountExternalKey].Calendars[calendarId].Events.Request();
var eventsPage = await request.Select(x => new
{
    x.Id,
    x.Subject,
    x.Start,
    x.End,
    x.TransactionId,
})
    .Top(maxPageSize)
    .GetAsync();

var events = new List<Event>();
var pageIterator = PageIterator<Event>.CreatePageIterator(_graphClient, eventsPage, (e) =>
{
    events.Add(e);
    return true;
});
```

**Comment by andrueastman** [comment]
Thanks for raising this @woodzee89 

As this behaviour is API related and this repo is mainly intended for SDK related issues, we may not be best placed to give this information. Any chance you can create a question ticket at the link below to get feedback from the API teams?

https://developer.microsoft.com/en-us/graph/support

**Comment by woodzee89** [comment]
> Thanks for raising this @woodzee89
> 
> As this behaviour is API related and this repo is mainly intended for SDK related issues, we may not be best placed to give this information. Any chance you can create a question ticket at the link below to get feedback from the API teams?
> 
> https://developer.microsoft.com/en-us/graph/support

This is where I initially opened a support request and was directed here after support was not able to assist.
