### ISSUE TITLE
Double bookings on room calendar is not rejected

### ISSUE THREAD

**Issue by cristiancaballerocib** [microsoftgraph/msgraph-sdk-dotnet#243]
Hi there,

I am using the Microsoft Graph API to create events in a room calendar. When I create an event at a certain time in this room calendar there is no problem. 
When I create a second event at the same time than the first one I expect that the event will be rejected (same time, same location) but, instead of being rejected, the room is double booked.

I have ensured that the "Allow conflicts" property is set to false:
                                AutomateProcessing    : AutoAccept
                                AllowConflicts              : False

Therefore, I understand that this second event should be rejected automatically and it is not.

**Comment by MIchaelMainer** [comment]
Can you show the results of the Get-Mailbox command?
Can you  show the results of a get calendar view to show that the two events are double booked?
Please post the results in this thread.

**Comment by cristiancaballerocib** [comment]
We are using the .NET GraphServiceClient to create the event. The following is an example (not production code):

    const string roomId = "Room user GUID";
    var client = GetClient(tenantKey, applicationKey, applicationSecret);

    var startDate = Convert(new DateTime(2018, 2, 21, 14, 0, 0, DateTimeKind.Utc));
    var endDate = Convert(new DateTime(2018, 2, 21, 15, 0, 0, DateTimeKind.Utc));

    var firstEvent = new Event
    {
        Subject = "First Event",
        Start = startDate,
        End = endDate
    };

    var firstresponse = client.Users[roomId].Events.Request().AddAsync(firstEvent).Result;

    var secondEvent = new Event
    {
        Subject = "Second Event",
        Start = startDate,
        End = endDate
    };

    var secondresponse = client.Users[roomId].Events.Request().AddAsync(secondEvent).Result;

    List<QueryOption> options = new List<QueryOption>
    {
        new QueryOption("startDateTime", startDate.DateTime),
        new QueryOption("endDateTime", endDate.DateTime)
    };

    var bookings = client.Users[roomId]
        .CalendarView
        .Request(options)
        .GetAsync()
        .Result
        .ToList();

    Debug.Assert(bookings.Count > 1, "We should not have been allowed to double book.");

Also attached is the output of the Get-Mailbox command (sanitised a bit). Thanks

[Get-Mailbox.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/1747670/Get-Mailbox.txt)

**Comment by cristiancaballerocib** [comment]
I attach the sanitised output of the Get-CalendarProcessing command. Thanks.

[Get-CalendarProcessing.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/1749007/Get-CalendarProcessing.txt)

**Comment by bateau** [comment]
Cristian, what's the SMTP address of the room? We'll pull logs and check it out.

**Comment by MIchaelMainer** [comment]
You are setting the event directly on the room, as if the room 'user' is setting their calendar. Just like how you and I  can double book our own time. 

Some other user is not trying to book the room resource.  I'm fairly sure that the calendar processing rules do not apply in this scenario.

**Comment by cristiancaballerocib** [comment]
Thank you for the confirmation that this is the expected behaviour by design. We will find an alternative method of conflict detection.
