### ISSUE TITLE
[Client bug]: Custom security attributes can not be assigned by SDK

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-dotnet#2434]
**Describe the bug**
When trying to use the code snippet from [the documentation](https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=csharp#assign-custom-security-attributes) for setting/updating custom security attributes - the request fails, because Kiota serializer serializes the innerest Object incorrectly (See Additional Context for more info)

**To Reproduce**
1. Create a Custom Security Set / Attribute
2. Try to set the value via DotNet Graph SDK as explained [here](https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=csharp#assign-custom-security-attributes) (Make sure to switch to the C# tab)
3. See Error beeing thrown (Not finding the Attribute)

**Expected behavior**
The Custom Security Attribute has to be set

~**Screenshots**~
~If applicable, add screenshots to help explain your problem.~

**Client version**
5.48.0

~**Desktop (please complete the following information):**~

**Additional context**
I did some digging - The reason why it fails is that the internal serializer doesn't serialize the innerest Object corretly (see [the documentation](https://learn.microsoft.com/en-us/graph/custom-security-attributes-examples?tabs=csharp#assign-custom-security-attributes) for the full example:
```cs
new  {
        OdataType = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue",
        ProjectDate = "2022-10-01",
    }
```
This is beeing serialized to 
```json
{
    "OdataType": "#Microsoft.DirectoryServices.CustomSecurityAttributeValue",
    "ProjectDate": "2022-10-01"
}
```
Note that the Property name is `OdataType` and not `@odata.type` as in the http example. This is likely because the C# Object is not an Kiota object (not an `IParsable`) hence the OdataType is not beeing named correctly. To be fully honest i am a little bit clueless how to fix this issue. I tried to replace this object with a <string, string> dictionary but unfortunately this started throwing very weird serialization errors.

Maybe I am missing something obvious. Any help or advise is much appreciated

A possible solution that got in my mind is to have a typed abstract `CustomSecurityAttributeValue` class that can be inherited from. By this it should be possible to cover a custom naming and have the ODataType beeing correctly set by the Kiota Serializer

**Comment by MichaMican** [comment]
For context this is what i used to get the serialized body that Kiota (likely) uses internally:
```cs
var serializedBody = KiotaSerializer.SerializeAsString("application/json", requestBody);
```

**Comment by andrueastman** [comment]
Thanks for raising this @MichaMican 

This is an issue with the generated snippets in the documentation. We'll close this for now as a duplicate to be tracked via https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1751
