### ISSUE TITLE
 Lightweight version of SDK for faster startup times on Azure Functions/Azure Static Web Apps

### ISSUE THREAD

**Issue by danbasszeti** [microsoftgraph/msgraph-sdk-dotnet#2435]
**Is your feature request related to a problem? Please describe.**
We use Azure Functions & Azure Static Web Apps pretty much exclusively. I have been doing some performance work recently (.NET 8 & Isolated made cold start much worse) so I went through and upgraded all the libraries. Microsoft.Graph was already taking a quarter of the package size at 10 mb, and the latest version was 30mb. This was substantially slowing the cold start times as it has to copy the whole DLL into the container before it can start, to the point that requests were failing due to the 40 second timeout on Azure Static Web Apps. 

I removed the library and replaced the two methods I was using with raw http requests and now there's no failed requests and cold start time is much faster. 

**Describe the solution you'd like**
I'd like a Microsoft.Graph.Lite or something, that only contains auth and wrapper structs for the HTTP requests - I'm not a library author so there may be a better way of doing it. 

**Describe alternatives you've considered**
Just highlight that the library is large and to consider not using it in a Serverless environment and provide sample code instead to write your own raw http requests. 

**Additional context**
This is just an idea for a problem I've recently had - totally understand if its not priority for the team. Just thought you'd like to know that I had to spend time stripping out this library from my work and the reason why so that you can decide whether its worth tackling or not.

**Comment by andrueastman** [comment]
Thanks for raising this @danbasszeti 

This issue is brought about by the large surface are of the graph api having a large number of endpoint which the SDK tries to cover. 

Given that you have identified the paths you are trying to call, any chance you can try out the docs below to generate your own client? This would end up being a small size relative to the paths you decided to use. 

https://learn.microsoft.com/en-us/graph/sdks/generate-with-kiota#generating-a-client

**Comment by danbasszeti** [comment]
Hi,

Yeah it absolutely makes sense from a sheer size perspective, thank you for the quick response and suggestion. 

I've tried out kiota, but I'm struggling to narrow it down to just one request (could as ever be user error). I issue this command: 

kiota generate --openapi https://aka.ms/graph/v1.0/openapi.yaml --include-path "/users#GET" --language CSharp --class-name TaskClient --namespace-name MyTaskApp.Client

and the folder I get is still very large, 15.5 mb and that doesn't include the list of 7 libraries it tells me it needs. It seems to have a vast number of classes - i wonder if that's because its possible to pass $select etc into the API and therefore it needs lots of options even for just one API endpoint. Or, more likely, whether I'm accidentally selecting /users and all its child api paths in my selector rather than just the intended /users endpoint.

**Comment by danbasszeti** [comment]
To give an idea of what my actual code does, it just goes and grabs the email address of the logged in user as my Static Web App doesn't return that as part of the ClaimsPrincipal when using AAD B2C:

`            public async Task<string> GetUserEmailAddressAadB2c(ClaimsPrincipal claimsPrincipal)
        {
            if (!string.IsNullOrWhiteSpace(this.localOnlyAdminIdOverride)) return this.localOnlyAdminIdOverride;

            var tenantId = Environment.GetEnvironmentVariable("TENANT_ID");
            var clientId = Environment.GetEnvironmentVariable("CLIENT_ID");
            var clientSecret = Environment.GetEnvironmentVariable("CLIENT_SECRET");

            var httpClient = httpClientFactory.CreateClient();
            var tokenResponse = await httpClient.PostAsync("https://login.microsoftonline.com/" + tenantId + "/oauth2/v2.0/token", new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("grant_type", "client_credentials"),
                new KeyValuePair<string, string>("client_id", clientId),
                new KeyValuePair<string, string>("client_secret", clientSecret),
                new KeyValuePair<string, string>("scope", "https://graph.microsoft.com/.default")
            }));
            var tokenResponseString = await tokenResponse.Content.ReadAsStringAsync();
            var tokenResponseObject = JsonSerializer.Deserialize<MicrosoftLoginOauthTokenResponse>(tokenResponseString);
            var token = tokenResponseObject.access_token;
            httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
            var userResponse = await httpClient.GetAsync("https://graph.microsoft.com/v1.0/users/" + claimsPrincipal.FindFirst(ClaimTypes.NameIdentifier).Value + "?$select=identities,displayName,id,mail");
            var userResponseContent = await userResponse.Content.ReadAsStringAsync();
            var userResponseObject = JsonSerializer.Deserialize<MicrosoftGraphUserResponse>(userResponseContent);
            var correctIdentity = userResponseObject.identities.FirstOrDefault(i => i.signInType == "emailAddress");
            return correctIdentity.issuerAssignedId;
        }`

I then have 3 records to represent the token response, user response and identity object. Obviously I should cache my bearer token and reuse it etc. I have a slightly altered version for plain AAD as well.

**Comment by andrueastman** [comment]
Thanks for trying this out @danbasszeti 

It looks like the user type is indirectly referencing a bunch of other types that is causing a large number of models to be generated. 

Do you get a better result using the smaller openapi description at the link below instead? 
https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/openApiDocs/v1.0/Users.yml

Could you also submit an issue at https://github.com/microsoft/kiota to help us investigate if the models generated are indeed necessary and should be trimmed away? It would be great if you could add information on what models you expect don't expect.
