### ISSUE TITLE
Adding a teams tab to a channel fails in graph sdk 5 for dotnet with error "The navigation bind for the teamsApp was missing in request"

### ISSUE THREAD

**Issue by sant2006** [microsoftgraph/msgraph-sdk-dotnet#2448]
### Describe the bug

Adding a teams tab to a channel fails with error  `The navigation bind for the teamsApp was missing in request. HttpStatusCode=400 ErrorCode=BadRequest` with graph sdk 5. 
Below is sample code
```  
var tabToWrite = new TeamsTab
{
     DisplayName = DisplayName,
     WebUrl = WebUrl,
     Configuration = new TeamsTabConfiguration
     {
           ContentUrl = ContentUrl,
           WebsiteUrl = WebsiteUrl,
           RemoveUrl = RemoveUrl,
           EntityId = EntityId,
           AdditionalData = new Dictionary<string, object>
           {
               {
                     "teamsApp@odata.bind" , $"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/{teamsAppId}"
               },
           },
     },
  };
var newTab = await GraphServiceClient.Teams[teamId].Channels[channelId].Tabs.PostAsync(tabToWrite);
```

Same code was working in sdk4 and created tabs successfully.

### Expected behavior

1) Adding a tab to a channel should not throw error.
2) New changes if any  in sdk 5 should be well documented. Upgrade guide is not very useful.
3)  If possible update the code snipptet here https://learn.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0&tabs=csharp and graph explorer with right code.

### How to reproduce

Kindly see the code  I've given in the bug description to reproduce this error.

### SDK Version

5.37

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @sant2006 

Any chance you can share a sample of the working code when using v4 of the SDK to help understand the discrepancy better?

**Comment by sant2006** [comment]
@andrueastman  here is sample v4 code
``` 
var newTabToWrite = new TeamsTab
{
   DisplayName = displayName,
   WebUrl = webUrl,
   Configuration = new TeamsTabConfiguration
   {
      ContentUrl = contentUrl,
      WebsiteUrl = websiteUrl,
       RemoveUrl = removeUrl,
       EntityId = entityId,
   },
  ODataBind = $"{TeamsConstants.TeamsTabTeamsAppBindUrl}{teamsAppId}",
 };
  var newTab = await GraphServiceClient.Teams[teamId].Channels[channelId].Tabs.Request().AddAsync(newTabToWrite);
```

**Comment by andrueastman** [comment]
Thanks for confirming @sant2006 

Any chance it works out if you use an example like in the docs? https://learn.microsoft.com/en-us/graph/api/channel-post-tabs?view=graph-rest-1.0&tabs=csharp

```cs
var requestBody = new TeamsTab
{
	DisplayName = "My Contoso Tab",
	Configuration = new TeamsTabConfiguration
	{
		EntityId = "2DCA2E6C7A10415CAF6B8AB6661B3154",
		ContentUrl = "https://www.contoso.com/Orders/2DCA2E6C7A10415CAF6B8AB6661B3154/tabView",
		WebsiteUrl = "https://www.contoso.com/Orders/2DCA2E6C7A10415CAF6B8AB6661B3154",
		RemoveUrl = "https://www.contoso.com/Orders/2DCA2E6C7A10415CAF6B8AB6661B3154/uninstallTab",
	},
	AdditionalData = new Dictionary<string, object>
	{
		{
			"teamsApp@odata.bind" , "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/06805b9e-77e3-4b93-ac81-525eb87513b8"
		},
	},
};
```

When I compare this and the one you provided, the `AdditionalData` property is in the `TeamsTabConfiguration` instead of the parent `TeamsTab` object. This means the `"teamsApp@odata.bind"` will be in the wrong object and possibly cause an API error.

**Comment by sant2006** [comment]
@andrueastman thanks for looking at this.  Tested with the changes suggested and it worked. This issue can be closed. Thanks.
