### ISSUE TITLE
Wrong serialization for batch response

### ISSUE THREAD

**Issue by manufz** [microsoftgraph/msgraph-sdk-dotnet#2450]
### Describe the bug

When creating a batch request containing managed device requests the returned properties are not accessible. All properties are empty, the data is visible in the AdditionalData.value property as an Microsoft.Kiota.Abstractions.Serialization.UntypedArray.

### Expected behavior

Properties should be populated same as for single requests:
```
RequestInformation request = graphClient.DeviceManagement.ManagedDevices.ToGetRequestInformation(requestConfiguration =>
{
    requestConfiguration.QueryParameters.Select = ["id", "azureADDeviceId", "serialNumber"];
    requestConfiguration.QueryParameters.Filter = $"azureADDeviceId eq '{id}'";
});
```
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/30493494/237295ba-5096-429b-a377-ec04c123af9d)

### How to reproduce

```
List<BatchRequestContent> batches = new();
BatchRequestContentCollection batchRequestContent = new(graphClient);

RequestInformation request = graphClient.DeviceManagement.ManagedDevices.ToGetRequestInformation(requestConfiguration =>
{
    requestConfiguration.QueryParameters.Select = ["id", "azureADDeviceId", "serialNumber"];
    requestConfiguration.QueryParameters.Filter = $"azureADDeviceId eq '{id}'";
});

var managedDeviceRequestMessage = await graphClient.RequestAdapter
    .ConvertToNativeRequestAsync<HttpRequestMessage>(request);

batchRequestContent.AddBatchRequestStep(new BatchRequestStep(id, managedDeviceRequestMessage));

BatchResponseContentCollection returnedResponse = await graphClient.Batch.PostAsync(batchRequestContent);

ManagedDevice? managedDevice = returnedResponse.GetResponseByIdAsync<ManagedDevice>(id).Result;
```

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/30493494/47448eea-f018-46a5-b63e-87ea64f8f07d)

### SDK Version

5.49.0 and 5.71.0-preview

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @manufz 

As the request `graphClient.DeviceManagement.ManagedDevices.ToGetRequestInformation` is made to a collection endpoint, I believe you are deserializing the response to the incorrect object.

As the response will be a collection, you should ideally deserialize this to a `ManagedDeviceCollectionResponse` object. Any chance it works out if you change the last line to be something like this? 

```cs
ManagedDeviceCollectionResponse? managedDeviceCollectionResponse = await returnedResponse.GetResponseByIdAsync<ManagedDeviceCollectionResponse>(id);
```

**Comment by manufz** [comment]
@andrueastman Of course, how can I be so blind. Using the correct type ManagedDeviceCollectionResponse makes it work. Thank you so much!
