### ISSUE TITLE
Chat system message incorrect when installing app with app-only permissions

### ISSUE THREAD

**Issue by bcage29** [microsoftgraph/msgraph-sdk-dotnet#2454]
### Describe the bug

When using the SDK or the Rest API to install an app into a group chat there is an unexpected system message in the chat. The app is installed correctly, but the Teams system message says that an individual user added the app to the chat. The app was added using App-only permissions and not using delegated authentication. It seems to be random which user Teams will display that installed the app.

<img width="1154" alt="InstallAppCode" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/13458224/0666e1e8-fdd6-4860-8744-68324a7d6506">

![ChatAppView](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/13458224/ab680027-5c93-4df6-8ea8-dcb72c54192d)

### Expected behavior

The Teams system message should list the Entra Application that installed the app because it was installed with App-only permissions.

### How to reproduce

Using an App-only auth token, run this code.

```c#
public static async Task InstallAppInChat()
    {
        _ = _appClient ??
                throw new System.NullReferenceException("Graph has not been initialized for app-only auth");
     
        var chatId = "19:....@thread.v2";
        var appId = "1542629c-01b3-4a6d-8f76-1938b779e48d"; // Polly App
        var requestBody = new TeamsAppInstallation
        {
            AdditionalData = new Dictionary<string, object>
            {
                {
                    "teamsApp@odata.bind" , $"https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/{appId}"
                },
            },
        };

        // To initialize your graphClient, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=csharp
        await _appClient.Chats[chatId].InstalledApps.PostAsync(requestBody);
        return;
    }
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @bcage29 

As this is an issue related to functionality of the API, we may not be best placed to answer this as this repo is mainly intended for SDK related issues/requests. 
Any chance you can post the feedback to the Api teams at the link below? It would be great if you can post back the link here as a comment so that anyone who comes across this can also upvote it and follow the response.

https://aka.ms/graphfeedback

**Comment by andrueastman** [comment]
Thanks for confirming @bcage29. We'll close this for now as this is followed up there.
