### ISSUE TITLE
Typo in explanation summary of GroupRequestBuilder

### ISSUE THREAD

**Issue by NRG-Drink** [microsoftgraph/msgraph-sdk-dotnet#2455]
In `Microsoft.Graph.Groups.Item.GroupItemRequestBuilder` there is a misspelled words: 'thethe' instead of 'the'.

Class:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/Groups/Item/GroupItemRequestBuilder.cs
On line: 340 and 404

**Comment by andrueastman** [comment]
Thanks for raising this @NRG-Drink and pointing this out.

The comments for the generated code are pulled from the microsoft graph repository based on the relevant API paths. These will be resolved in the following SDK update once the following fixes are merged into the documentation.

- https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9329
- https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9328

**Comment by andrueastman** [comment]
Resolved with https://github.com/microsoftgraph/microsoft-graph-docs-contrib/pull/9329
