### ISSUE TITLE
Warning	NU1608	Detected package version outside of dependency constraint:

### ISSUE THREAD

**Issue by zipswich** [microsoftgraph/msgraph-sdk-dotnet#246]
I get the following warning when building a UWP app:
`Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.Graph.Core 1.3.1 requires Newtonsoft.Json (>= 6.0.1 && < 10.0.0) but version Newtonsoft.Json 10.0.3 was resolved.				
`
I am wondering if it is relevant here.  It is not a big deal because the app appears to run fine.  However, it has mysterious crashes occasionally.  I am examining all possible factors now.

**Comment by MIchaelMainer** [comment]
Do you have any more information on the crashes?

**Comment by zipswich** [comment]
@MIchaelMainer Unfortunately,   .Net native has essentially made stack traces useless.  The following is an example:
```
Class not registered Class not registered
SharedLibrary!<BaseAddress>+0x4a0ad0
My App!<BaseAddress>+0x13d9a68
My App!<BaseAddress>+0x13d99a4
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)
``` 
Most likely, these crashes have nothing to do with this SDK.  I am just trying to remove these warnings as much as I can to narrow my investigation.

**Comment by MIchaelMainer** [comment]
Does this issue persist with later versions of the package? Please reopen if this is still an issue for you.
