### ISSUE TITLE
Unable to set custom CSS branding

### ISSUE THREAD

**Issue by i-am-shodan** [microsoftgraph/msgraph-sdk-dotnet#2463]
### Describe the bug

I want to set Custom CSS branding with the MS Graph API. The branding object has setters for a byte[] containing css but I get an exception when trying to set this. See below for example code

### Expected behavior

* Working example code
* Calling PatchAsync with the CustomCss byte[] set should result in success

### How to reproduce

```
// code to get GraphServiceClient with OrganizationalBranding.ReadWrite.All scope
var branding = await service.Organization[tenantId].Branding.GetAsync();
branding.CustomCSS = someCssFileAsByteArray;
await service.Organization[tenantId].Branding.PatchAsync(branding);
// Exception Unexpected contents in request body, error 400
```

```
// code to get GraphServiceClient with OrganizationalBranding.ReadWrite.All scope
var ms = new MemoryStream(someCssFileAsByteArray);
ms.Position = 0;
await service.Organization[tenantId].Branding.CustomCSS.PutAsync(ms);
// Exception Uri is invalid for a PUT operation. The URI must refer to an entity., error 405
```

### SDK Version

5.30.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

.net6

**Comment by andrueastman** [comment]
Thanks for raising this @i-am-shodan 

Any chance you can post the question at the link below? Unfortunately, as this repo is mainly intended for SDK related issues and as there is no REST API documentation as to how to update this property, we may need guidance of the API owners here. It would be great if you could post back the link of the same so that anyone who comes across this may also follow it up. 

https://aka.ms/askgraph

**Comment by i-am-shodan** [comment]
Looking at this it does look like the SDK is using the wrong logic https://learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-1.0&tabs=http

**Comment by i-am-shodan** [comment]
```
using (var ms = new MemoryStream(requestBody.CustomCSS))
{
  var req = service.Organization[tenantId].Branding.CustomCSS.ToPutRequestInformation(ms);
  var uri = req.URI;
}
```
Then the URI I get out it is https://graph.microsoft.com/v1.0/organization/[tenant]/branding/customCSS

The [docs ](https://learn.microsoft.com/en-us/graph/api/organizationalbranding-update?view=graph-rest-1.0&tabs=http)say to use the following URI for stream types - which customcss is. Which also matches what the error message is saying.
```
PUT /organization/{organizationId}/branding/localizations/{organizationalBrandingLocalizationId}/{Stream object type such as backgroundImage}
```

So I think this is a SDK problem

**Comment by i-am-shodan** [comment]
Yes this is a SDK problem. Here is the code required. Note this is almost exactly the same issue as https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/653. The SDK is sending:
* The wrong content type
* using the wrong URL

```
using (var ms = new MemoryStream(requestBody.CustomCSS))
{
  var req = service.Organization[tenantId].Branding.CustomCSS.ToPutRequestInformation(ms);
  req.URI = new Uri($"https://graph.microsoft.com/v1.0/organization/{tenantId}/branding/localizations/0/customCSS");

  req.Headers.Remove("Content-Type");
  req.Headers.Add("Content-Type", "text/css");
  var res = await service.RequestAdapter.SendPrimitiveAsync<Stream>(req);
}
```

**Comment by andrueastman** [comment]
Thanks for the extra information, could you confirm that the following works out? It looks like the latest versions of the SDK have the relevant request builders to make the request as below.

```cs
            using var ms = new MemoryStream();
            var response = await graphClient.Organization["tenantId"].Branding.Localizations["0"].CustomCSS.PutAsync(ms, "text/css");
```
