### ISSUE TITLE
Unable to set QueryParamters/Format

### ISSUE THREAD

**Issue by GrahamSnee** [microsoftgraph/msgraph-sdk-dotnet#2465]
### Describe the bug

I am wanting to use the GraphServiceClient to get the reports GetM365AppUserDetailWithPeriod. I want to use the format of the return to be in JSON, so using the example from the MS documents I have tried to pass the requestConfiguration query parameters format, but the code will not compile. The complier indicates a missing using statement, but the code matches the examples.  (https://learn.microsoft.com/en-us/graph/api/reportroot-getm365appplatformusercounts?view=graph-rest-1.0&tabs=csharp)

### Expected behavior

The code to compile, or documents be updated to reflect required usings within the examples

### How to reproduce

Create a simple app and add the code

// Code snippets are only available for the latest version. Current version is 5.x

// To initialize your graphClient, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=csharp
await graphClient.Reports.GetM365AppPlatformUserCountsWithPeriod("{period}").GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Format = "application/json";
});

### SDK Version

 nuget package 5.49.0

### Latest version known to work for scenario above?

Unkownn

### Known Workarounds

None

### Debug output

Compiler Error	CS1061	'DefaultQueryParameters' does not contain a definition for 'Format' and no accessible extension method 'Format' accepting a first argument of type 'DefaultQueryParameters' could be found (are you missing a using directive or an assembly reference?)		

### Configuration

Windows 11

**Comment by GrahamSnee** [comment]
I have tried this, but the client thrown an exception stating ‘{"Message":"JSON format is not supported."}’

**Comment by andrueastman** [comment]
Thanks for getting back to this. It looks like the API may not support the json type for this scenario(Which suggests that the documenation is invalid/incorrect).

Are you by any chance able to replicate this using[ the Graph explorer](https://aka.ms/ge)?

**Comment by GrahamSnee** [comment]
With Graph explorer it does not work, but neither does the getting of the information in CSV work either
