### ISSUE TITLE
Microsoft Graph API Exception failing to deserialize and is thrown as ApiException instead of ODataError

### ISSUE THREAD

**Issue by gabrielav1599** [microsoftgraph/msgraph-sdk-dotnet#2468]
### Describe the bug

We are using the DriveItemRequestBuilder.GetAsync method. From our logs, the MS Graph API returned a 503 on the request. We have a try catch around the DriveItemRequestBuilder.GetAsync method with a catch for ODataError, but this catch wasn't executed. The method threw an ApiException instead and we got the following stack trace:

Microsoft.Kiota.Abstractions.ApiException: The server returned an unexpected status code and the error registered for this code failed to deserialize: 503\r\n   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)\r\n   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)\r\n   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)\r\n   at Microsoft.Graph.Shares.Item.DriveItem.DriveItemRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)\r\n

The error message is coming from Kiota: https://github.com/microsoft/kiota-http-dotnet/blob/c1c295d3b0ebb2182b66d9a6858241117b59b540/src/HttpClientRequestAdapter.cs#L415C1-L416C1

Please let me know if there is any additional I can provide. Thanks!

### Expected behavior

We would expect the 503 to return as an OData Error, or confirm whether the intended behavior instead is for errors to throw an ApiException instead.

### How to reproduce

The repro would involve calling the DriveItemRequestBuilder.GetAsync method and mocking a 503 response from Graph API.

### SDK Version

5.41.0

**Comment by andrueastman** [comment]
Thanks for raising this @gabrielav1599 

The 503 error should ideally be handled by the `RetryHandler` and should be show up as a different error. Any chance you can share how you are initializing your graphclient? As well as a code sample when executing the request that fails?

**Comment by gabrielav1599** [comment]
Hi @andrueastman, thanks!

Here's how we're initializing the client:
`var graphClient = new GraphServiceClient(httpClient, credential, scopes: _scopes, baseUrl: endpoint);
`

And a code sample executing the request that fails:
```
return await graphClient.Shares[shareId].DriveItem.GetAsync(
    requestConfiguration =>
    {
        ...    },
    cancellationToken: cancellationToken);
```

Also an update, we've observed the deserialization error when the API returns 503 and 404, so it's not specific to 503.

**Comment by andrueastman** [comment]
Any chance you can share how you are initializing the `httpClient`? Does it have a handler for 503 errors? Could you also share the error trace for the 404 error? Ideally this should throw an odataError either way.

**Comment by andrueastman** [comment]
The error seems to suggest that the response body isn't being deserialized appropriately despite the error factory being present.

Out of curiosity are you able to replicate this consistently? Do you get a different result if you initialize a client as below?

```cs
 var httpClient = GraphClientFactory.Create();
```
