### ISSUE TITLE
Updating a users contacts results in an error

### ISSUE THREAD

**Issue by faso** [microsoftgraph/msgraph-sdk-dotnet#247]
This is my code, quite similar to the samples on the Collections page of the docs:

```
var userContacts = graphClient.Users[email].Contacts.Request();
var emailRecord = new Contact()
{
    EmailAddresses = new List<EmailAddress> { new EmailAddress() { Name = "Contact Email", Address = "test@whatever.com" } }
};
await userContacts.AddAsync(emailRecord);
```

And what I'm getting is a "ServiceException: Code: UnknownError"

I assume I'm using the library wrong? Any pointers to what I need to change?

**Comment by jberd126** [comment]
You are creating a contact without a given name.

If you replicate the request in [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) you can see precisely the behaviour of Graph API.

`POST` to [https://graph.microsoft.com/v1.0/me/contacts](https://graph.microsoft.com/v1.0/me/contacts) using request body

`
{
  "emailAddresses": [
    {
      "address": "test@whatever.com",
      "name": "Contact Email"
    }
  ]
}
`

results in the response

`
{
    "error": {
        "code": "ErrorInvalidProperty",
        "message": "The property 'GivenName' is required when creating the entity."
    }
}
`

**Comment by faso** [comment]
Thanks, that solves it! 

Would be great if these errors would show up when using the library.

**Comment by faso** [comment]
Reopening because I am still having issues. I thought it was fine now, but I judged the situation too fast.

Even from the Graph Explorer I am still getting `Unknown Error` and it says I might have a problem with my permission. I can't even execute  `GET https://graph.microsoft.com/v1.0/me/contacts`

Here are my permissions: 

![image](https://user-images.githubusercontent.com/19239918/36896175-458ef46a-1e1a-11e8-9d77-7529b0c7e58a.png)

I checked out the docs and it says `Contacts.ReadWrite` should be sufficient. Is there something missing? The issue also persists when I'm programmatically using both a regular (Delegated Permissions) client and an Admin (Application Permissions) client.

**Comment by jberd126** [comment]
If you are having problems with Microsoft Graph specifically (and not the .NET SDK), refer to 
[Microsoft Graph Development Support](https://developer.microsoft.com/en-us/graph/support)

**Comment by MIchaelMainer** [comment]
Please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
