### ISSUE TITLE
NuGet <-> Graph.dll: System.Net.Http min version difference

### ISSUE THREAD

**Issue by krasnor** [microsoftgraph/msgraph-sdk-dotnet#248]
Redirected from https://stackoverflow.com/questions/49067891/nuget-graph-dll-system-net-http-min-version-difference to here.

When installing the dotNet Graph sdk v1.7.0.0 over NuGet, a System.Net.Http.dll (NuGet-Version 4.3.1, dll version 4.1.0) is installed with it as a dependency.

When looking into the Graph.dll the assembly seems only dependent on System.Net.Http (v4.0.0). 
It seems like the minimum requirements of System.Net.Http.dll of Graph does not match the one stated in NuGet. I could not find any information about the dependencies in the documentation.

![](https://i.stack.imgur.com/fQTg0.png)

### Expected behavior
Minimum version of dependencies in Graph (v1.7.0.0) NuGet  should be the same as the Graph.dll and Graph.Core.dll 
E.g both 4.0.0 or 4.1.0 but not different.

### Actual behavior
Graph.dll and Graph.Core.dll accepts System.Net.Http.dll with versions 4.0.0
But In NuGet the minimum System.Net.Http version is  4.3.1 (dll version 4.1.0).
-> Version mismatch between NuGet and actually provided dlls

### Steps to reproduce the behavior
Compare Graph NuGet minumum versions with the minimum version stated in the Graph.dll and Graph.Core.dll.

**Comment by MIchaelMainer** [comment]
That is the way that the Nuget package owners generated their dlls and Nuget packages. For example, the Microsoft.Graph Nuget package references the System.Net.Http 4.3.1 package (see the [csproj](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Microsoft.Graph.csproj#L50)). That's the same package that was used to build Microsoft.Graph. Inside the  System.Net.Http 4.3.1 Nuget package, the System.Net.Http assembly manifest has a file version of 4.6.x, and an assembly version of 4.1.x. Confusing as hell.

When looking at the assembly metadata for Microsoft.Graph, you see 4.0.0.0 for System.Net.Http. I assume that mean's that Microsoft Graph can depend on any version of System.Net.Http where major version = 4. To be honest, my understanding is all conjecture as I haven't found out the firm answer on why this is the way it is. 

For more info on System.Net.Http: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/dir.props

**Comment by krasnor** [comment]
Im a bit confused, but if i am understanding it correctly it is currently unclear if this version difference is wanted and its unclear if it is fixable?

**Comment by MIchaelMainer** [comment]
Your understanding is correct.

**Comment by cbales** [comment]
Could you explain the problem you are running into? Are you looking for clearer documentation into the dependencies for using this library?

**Comment by krasnor** [comment]
I am currently integrating the GraphSdk into an existing Product which requires System.Net.Http v4.0.0.0.

I can't use two different Http versions at the same time as,
during initialization the main Program needs to pass an HTTPClientHandler (for Proxy) to the Graph API.
This will result in an error as the Graph sdk running on an higher version of System.Net.Http cannot parse/recognize the object, due to version differences.

Problem the upgrade to an higher HTTP version will happen in a few months.
As a solution for the meantime I wanted to use v4.0.0 for the GraphSdk, but I'm unsure if the sdk can safely handle this as in NuGet the minimum version is v4.1.0.

**Comment by MIchaelMainer** [comment]
I don't know how well the Microsoft Graph client library will work with 4.0.0. I can't think of why it wouldn't. And since we are at the same major version, there shouldn't be a breaking change between the versions.

You can use a [binding redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions) to allow you to use a different version of System.Net.Http.

**Comment by MIchaelMainer** [comment]
Please reopen this issue if you have a proposed action for us to take on this issue.

**Comment by HermannGruber** [comment]
I assume that this is fixed with Microsoft.Graph 1.12.0? In the release notes, it says "Removed System.Net.Http package reference for .Net target". The according PR was the following, I suppose: https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/287
