### ISSUE TITLE
add release please configuration

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#2480]
reflection of https://github.com/microsoftgraph/msgraph-beta-sdk-java/issues/940 on this repository. We want:
- [x] release please header file (yaml .github/release-please.yml)
- [x] release please manifest (json .release-please-manifest.json)
- [x] release please config (json release-please-config.json)
- [x] release please workflow to trigger on main branch (.github/workflows/release-please.yml)
- [x] install the [release please GitHub app](https://github.com/apps/release-please) to the repository
- [ ] changelog keep a changelog header and unreleased information to be removed
- [x] contributing to be updated with commit formatting instructions
- [x] version bump script to be deleted (and removed from the weekly generation process)
- [x] files where the version needs to be updated to be ammended with the special comments for release please

**Comment by andrueastman** [comment]
Re - opening for now as some tasks are still to be completed.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2593
