### ISSUE TITLE
Paging in Microsoft.Graph.DirectoryObjects.GetByIds

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/msgraph-sdk-dotnet#2483]
We're adapting our V5 code to remove the use of obsolete classes/methods. One of the things flagged was our way of getting a list of directory objects. I'm wondering - if this is my first request

```
            var payload = new Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostRequestBody
            {
                Ids = ids, 
                Types = objectTypes 
            };
            var req = graphServiceClient.DirectoryObjects.GetByIds.ToPostRequestInformation(payload);
            if (attributeList != null)
                req.URI = new Uri($"{req.URI}?$select={string.Join(",", attributeList.Select(o => o.FirstCharToLower()))}");
            //var items = await graphServiceClient.RequestAdapter.SendAsync(req, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsResponse.CreateFromDiscriminatorValue);
            var items = await graphServiceClient.RequestAdapter.SendAsync(req, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse.CreateFromDiscriminatorValue);
```

and `items.OdataNextLink` is not null, what would be the correct API call to get the next page?

I've not found any method on `GetByIdsPostRequestBody` that would take a url.

**Comment by andrueastman** [comment]
Thanks for raising this @ssteiner 

I believe it may be possible to use the pageIterator to collect all the items as below.

```cs
var collectedItems = new List<DirectoryObject>();
var pageIterator = PageIterator<DirectoryObject, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse>.CreatePageIterator(graphClient, items, (item) => { collectedItems.Add(item); return true; });
await pageIterator.IterateAsync();
```

alternatively, you can use the `WithUrl` to create a new request information instance and modify it as below

```cs
            var nextRequest = graphServiceClient.DirectoryObjects.GetByIds.WithUrl(items.OdataNextLink).ToPostRequestInformation(new Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostRequestBody
            {
            });
            nextRequest.HttpMethod = Microsoft.Kiota.Abstractions.Method.GET;

            var nextItems = await graphServiceClient.RequestAdapter.SendAsync(req, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse.CreateFromDiscriminatorValue);
```

**Comment by trust11** [comment]
This exception will occur when you request more than 1000 IDs.

> Microsoft.Kiota.Abstractions.ApiException: 'The server returned an unexpected status code and no error factory is registered for this code: 400'

It appears to me that there is no built-in pagination.

**Comment by andrueastman** [comment]
I suspect the API may have a limit as to many Ids can be passed as a parameter. 

Any chance you can share the error if you pass the errorMapiing parameter as below?

```cs
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> 
            {
                { "XXX", ODataError.CreateFromDiscriminatorValue}
            };
            var items = await graphServiceClient.RequestAdapter.SendAsync(req, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse.CreateFromDiscriminatorValue, errorMapping);
```

**Comment by trust11** [comment]
Here is the result -> Number of included identifiers cannot exceed '1000'

Exception in GetDirectoryObjects: **Number of included identifiers cannot exceed '1000'.** at    at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at AzureADMsGraph.AzureADClient.GetDirectoryObjects(List`1 ids, List`1 objectTypes, List`1 attributeList, IOperationContainer container)

So it has no paging, I'm wrong?

**Comment by andrueastman** [comment]
I believe what this means is that you can't pass more than 1000 items at a time as a parameter. 

However, if the response has a nextLink you can page through it as suggested above. 

> Thanks for raising this @ssteiner
> 
> I believe it may be possible to use the pageIterator to collect all the items as below.
> 
> ```cs
> var collectedItems = new List<DirectoryObject>();
> var pageIterator = PageIterator<DirectoryObject, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse>.CreatePageIterator(graphClient, items, (item) => { collectedItems.Add(item); return true; });
> await pageIterator.IterateAsync();
> ```
> 
> alternatively, you can use the `WithUrl` to create a new request information instance and modify it as below
> 
> ```cs
>             var nextRequest = graphServiceClient.DirectoryObjects.GetByIds.WithUrl(items.OdataNextLink).ToPostRequestInformation(new Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostRequestBody
>             {
>             });
>             nextRequest.HttpMethod = Microsoft.Kiota.Abstractions.Method.GET;
> 
>             var nextItems = await graphServiceClient.RequestAdapter.SendAsync(req, Microsoft.Graph.DirectoryObjects.GetByIds.GetByIdsPostResponse.CreateFromDiscriminatorValue);
> ```
