### ISSUE TITLE
Outlook Throttling response headers not included in 429 HTTP exception

### ISSUE THREAD

**Issue by Danthar** [microsoftgraph/msgraph-sdk-dotnet#250]
Current when using the Graph SDK. While using the MAIL api's when you receive a 429 exception, indicating that your requests are being throttled. The Throttling response headers from underlying outlook api, are not communicated back through the Graph SDK.

This makes debugging issues, or diagnosing which throttling issues, practically impossible. And forces us to fallback to the Outlook REST API.

**Comment by MIchaelMainer** [comment]
Thank you @Danthar. Let me see what I can find on this.

**Comment by MIchaelMainer** [comment]
The approach here is if you get a 429 with a retry-after, use it. If you get a 429 without a retry-after header, use an exponential retry pattern. 

This is a known issue. Please use UserVoice to let us know how this affects you:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/32797489-consistent-retry-after-information-accross-differe

**Comment by Danthar** [comment]
We are already using retry's. However it only makes things worse. Every retry seems to reset the duration we need to wait, before the throttling stops. We haven't seen the retry-after header though.
Currently we need to wait around 30 minutes before trying again. 

But ill upvote the uservoice issue

**Comment by MIchaelMainer** [comment]
Ugh, that's not a good perception + experience. Thank you for upvoting that uservoice issue. I'd really like to see the Microsoft Graph have a more cohesive throttling story.
