### ISSUE TITLE
Content type application/octet-stream does not have a factory registered to be parsed Error when getting PDF from File

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-dotnet#2500]
### Describe the bug

```
                var stream = await _graphClient.Drives[drive.Id].Items[driveItem.Id].Content.GetAsync((requestConfiguration) =>
                {
                    requestConfiguration.QueryParameters.Format = "{'pdf'}";
                });
```
Throws "Content type application/octet-stream does not have a factory registered to be parsed" 

### Expected behavior

Using "Microsoft.Graph" Version="5.53.0" and the sample from [here](https://learn.microsoft.com/en-us/graph/api/driveitem-get-content-format?view=graph-rest-1.0&tabs=csharp#tabpanel_1_csharp) 
I expect to get a  a 302 Found response with Location.
But instead I get this error

### How to reproduce

Get a  GraphServiceClient
Get a site ID
Get a Drive from the SharePoint Library
Get the file DriveItem to convert to PDF
Use the code sample.

### SDK Version

5.53.0 

### Debug output

<details><summary>Click to expand log</summary>
```

[2024-05-18T15:41:07.620Z] Host lock lease acquired by instance ID '00000000000000000000000006CA2F1E'.
[2024-05-18T15:41:12.458Z] Executing 'Functions.PDFaFile' (Reason='This function was programmatically called via the host APIs.', Id=3deb339d-1118-4c8a-9d04-d9290819ed42)
[2024-05-18T15:41:12.787Z] Starting Job: T002.128-2
[2024-05-18T15:41:31.879Z] Content type application/octet-stream does not have a factory registered to be parsed

```
</details>

### Configuration

Windows Visual Studio 2022

**Comment by andrueastman** [comment]
Thanks for raising this @Ofer-Gal 

I don't believe the Format string should be having curly braces.

Any chance you can confirm if the error is replicated by making the request as below?

```cs
   var stream = await _graphClient.Drives[drive.Id].Items[driveItem.Id].Content.GetAsync((requestConfiguration) =>
  {
      requestConfiguration.QueryParameters.Format = "pdf";
  });
```

**Comment by Ofer-Gal** [comment]
Yes you are right. the curly braces caused the error. 😒
It works fine now.
