### ISSUE TITLE
$select clause not respected while retrieving users mailbox settings with batch request

### ISSUE THREAD

**Issue by felpel** [microsoftgraph/msgraph-sdk-dotnet#2511]
### Describe the bug

1. Have a list of user IDs
2. For each ID, create a batch request step to retrieve mailbox settings and apply a `$select` filter (e.g. `timeZone`)
3. Send the batch request to the Graph API
4. On success, iterate on all responses by status codes, then find all responses with `200 OK` as their status
5. Inspect the payload of the returned response 👉 all mailbox settings properties will be returned.

### Expected behavior

The `$select` clause shall be fulfilled and return only the requested fields.

### How to reproduce

```csharp
string[] selectedFields = { "timeZone" }; // This can be any combination of fields, doesn't matter 
List<string> userIds = ... // Some list provided as an input
CancellationToken cancellationToken = ... // Also provided as an input
GraphServiceClient client = ... // Instantiate your client with appropriate app permissions
var batch = new BatchRequestContentCollection(client);

foreach (var userId in userIds) 
{
     await batch.AddBatchRequestStepAsync(
                    client
                        .Users[userId]
                        .MailboxSettings
                        .ToGetRequestInformation(rc =>
                        {
                            rc.QueryParameters.Select = selectedFields;
                        }));
}

// 👇 this call will return all fields per response object
await client.Batch.PostAsync(batch, cancellationToken);
```

### SDK Version

5.49.0

### Known Workarounds

We may continue fetching all fields, but it is undesirable.

### Debug output

N/A

### Configuration

- OS: Windows 11
- Arch:  N/A

**Comment by MartinM85** [comment]
Seems like server related issue. The similar query in the Graph Explorer returns all properties

`GET https://graph.microsoft.com/v1.0/me/mailboxSettings?$select=timeZone`

**Comment by andrueastman** [comment]
Thanks for confirming @MartinM85 

@felpel Would you be willing to submit feedback for the Api team with regards to this at the link below? As this issue isn't SDK related, we may not best placed to resolve this.

https://aka.ms/graphfeedback
