### ISSUE TITLE
System.MissingMethodException "System.Collections.Generic.IList`1<System.Net.Http.DelegatingHandler> Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.CreateDefaultHandlers()"

### ISSUE THREAD

**Issue by DarthSonic** [microsoftgraph/msgraph-sdk-dotnet#2520]
### Describe the bug

We upgraded from 5.5.2 to 5.5.4 and upgraded all Kiota packages and now get this exception:

```
                var authenticationProvider = new BaseBearerTokenAuthenticationProvider(tokenProvider);
                var msGraphClient = new GraphServiceClient(authenticationProvider);
```

System.MissingMethodException
  HResult=0x80131513
  Message=Methode nicht gefunden: "System.Collections.Generic.IList`1<System.Net.Http.DelegatingHandler> Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.CreateDefaultHandlers()".
  Source=Microsoft.Graph.Core
  StackTrace:
   at Microsoft.Graph.GraphClientFactory.CreateDefaultHandlers(GraphClientOptions graphClientOptions)
   at Microsoft.Graph.BaseGraphRequestAdapter..ctor(IAuthenticationProvider authenticationProvider, GraphClientOptions graphClientOptions, IParseNodeFactory parseNodeFactory, ISerializationWriterFactory serializationWriterFactory, HttpClient httpClient)
   at Microsoft.Graph.GraphServiceClient..ctor(IAuthenticationProvider authenticationProvider, String baseUrl)
   at CleverMatch.Core.Services.MSGraph.MsGraphService.<GetAuthenticatedClientAsync>d__14.MoveNext() in C:\Source\Repos\CleverMatch\CleverMatch.Core\Services\MsGraph\MsGraphService.cs:line 320

### Expected behavior

It worked before upgrading packages and there was no breaking change.

### How to reproduce

Create new GraphServiceClient().

### SDK Version

5.5.4

### Latest version known to work for scenario above?

Microsoft.Graph.5.52.0
Microsoft.Kiota.Abstractions.1.9.1
Microsoft.Kiota.Authentication.Azure.1.1.5
Microsoft.Kiota.Http.HttpClientLibrary.1.4.1
Microsoft.Kiota.Serialization.Form.1.2.0
Microsoft.Kiota.Serialization.Json.1.3.0
Microsoft.Kiota.Serialization.Multipart.1.1.4
Microsoft.Kiota.Serialization.Text.1.2.0

### Known Workarounds

Downgrading to:
Microsoft.Graph.5.52.0
Microsoft.Kiota.Abstractions.1.9.1
Microsoft.Kiota.Authentication.Azure.1.1.5
Microsoft.Kiota.Http.HttpClientLibrary.1.4.1
Microsoft.Kiota.Serialization.Form.1.2.0
Microsoft.Kiota.Serialization.Json.1.3.0
Microsoft.Kiota.Serialization.Multipart.1.1.4
Microsoft.Kiota.Serialization.Text.1.2.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

- OS: Windows 11 Pro, Windows Server 2019
- x64

**Comment by DarthSonic** [comment]
I investigatged further after downgrading Ms.Graph and Kiota packages. Issue starts when uppgrading Microsoft.Kiota.Http.HttpClientLibrary from 1.4.1 to 1.4.3 (did not test 1.4.2).

**Comment by stefanboerner** [comment]
We are facing the same issue.

**Comment by DarthSonic** [comment]
I don't know which is the right place for this issue. Some other user opened an issue for kiota-http-dotnet project here: https://github.com/microsoft/kiota-http-dotnet/issues/261

**Comment by andrueastman** [comment]
Thanks for raising this. This looks to be possiblly caused by conflicting references in from the core pacakge.

Any chance you can confirm this is still an issue when referencing the latest core package at https://www.nuget.org/packages/Microsoft.Graph.Core/3.1.12

**Comment by derekreynolds882** [comment]
Issue is resolved for me when referencing the latest core package 
https://www.nuget.org/packages/Microsoft.Graph.Core/3.1.12
