### ISSUE TITLE
Support for Room Delegate Approvals via Microsoft Graph API

### ISSUE THREAD

**Issue by bryandellingeredu** [microsoftgraph/msgraph-sdk-dotnet#2523]
### Is your feature request related to a problem? Please describe the problem.

I would like to request the addition of features to the Microsoft Graph API that support room delegate approvals. Specifically, the ability to programmatically manage room bookings that require delegate approval. This includes:
1. The ability to set and retrieve room booking policies for room resources.
2. The ability to programmatically approve or reject room booking requests as a room delegate.
3. Enhanced API endpoints to manage room resource settings related to booking approvals.

This feature would greatly enhance automation capabilities for organizations managing room resources and streamline the approval process for room delegates. Thank you for considering this request.

### Describe the solution you'd like.

I would like to request the addition of features to the Microsoft Graph API that support room delegate approvals. Specifically, the ability to programmatically manage room bookings that require delegate approval. This includes:
1. The ability to set and retrieve room booking policies for room resources.
2. The ability to programmatically approve or reject room booking requests as a room delegate.
3. Enhanced API endpoints to manage room resource settings related to booking approvals.

This feature would greatly enhance automation capabilities for organizations managing room resources and streamline the approval process for room delegates. Thank you for considering this request.

**Comment by andrueastman** [comment]
Thanks for raising this @bryandellingeredu 

As this repo is mainly intended for SDK related issues, we may not be best placed to help with API related queries/request. Any chance you can post the same at the link below to get feedback from API owners?(It would be great if you could post back a link for the same here as a comment so that anyone who comes accross this can find and upvote it.) 

https://aka.ms/graphfeedback
