### ISSUE TITLE
IdentityGovernance.EntitlementManagement.Catalogs[catalogId] generates incorrect URL

### ISSUE THREAD

**Issue by alvicode** [microsoftgraph/msgraph-sdk-dotnet#2527]
### Describe the bug

A call to IdentityGovernance.EntitlementManagement.Catalogs[catalogId]  generates the following URL:

https://.......u.p.azurewebsites.net/api/v1/catalogs('458538bc-bfcd-4654-83e8-0d837baa833c')/accessPackages

<img width="998" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/105916663/7bb1028b-e7e7-4f04-89bc-bea63d34bea5">

### Expected behavior

The correct url should be

https://.......u.p.azurewebsites.net/api/v1/identityGovernance/entitlementManagement/catalogs('458538bc-bfcd-4654-83e8-0d837baa833c')/accessPackages

### How to reproduce

Authenticate and execute the call GraphClient
                .IdentityGovernance
                .EntitlementManagement
                .Catalogs[catalogId]
                .AccessPackages
                .GetAsync()

### SDK Version

5.55.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @alvicode 

Any chance you can confirm if the error occurs on the first request when fetching the `reponse` variable? Or does this occur while the SDK is paging through the data? According to this, the URL template looks to be okay.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/9e373512659c4f8fa31e460ad035620d35be82d5/src/Microsoft.Graph/Generated/IdentityGovernance/EntitlementManagement/Catalogs/Item/AccessPackages/AccessPackagesRequestBuilder.cs#L43

**Comment by andrueastman** [comment]
Thanks for the info @alvicode 

Any chance you can also share details on how you are setting/changing the baseUrl of the graphClient?

From my end, I get the correct url when I try to check it as below as `https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/catalogs/catalogId/accessPackages`

```cs
            var requestInfo = graphClient.IdentityGovernance
                                    .EntitlementManagement
                                    .Catalogs["catalogId"]
                                    .AccessPackages
                                    .ToGetRequestInformation();

            Console.WriteLine(requestInfo.URI.OriginalString);// 
```

**Comment by alvicode** [comment]
Hi

For information, some requests work just fine. Some dont.
For example,  the following code to read all Catalogs works fine.

<img width="901" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/105916663/440fed1f-4db1-4543-9a68-fbc2821d4f77">

For completeness, here is how the graph client is created:

<img width="779" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/105916663/709c736b-5eb0-46c4-8175-3dca17af819c">

**Comment by alvicode** [comment]
> Thanks for the info @alvicode
> 
> Any chance you can also share details on how you are setting/changing the baseUrl of the graphClient?
> 
> From my end, I get the correct url when I try to check it as below as `https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/catalogs/catalogId/accessPackages`
> 
> ```cs
>             var requestInfo = graphClient.IdentityGovernance
>                                     .EntitlementManagement
>                                     .Catalogs["catalogId"]
>                                     .AccessPackages
>                                     .ToGetRequestInformation();
> 
>             Console.WriteLine(requestInfo.URI.OriginalString);// 
> ```

I tested this and the value of `requestInfo.URI.OriginalString` is correct.

**Comment by andrueastman** [comment]
Are you able to identify the differences when the call fails vs when its successful? The original error seems to suggest that a baseUrl with `azurewebsites.net` is used somewhere. Is this a scenario you are currently working with?

**Comment by alvicode** [comment]
So I got some further information.
Reading all the catalogs works fine and we get the catalog id. I also checked in Entra ID that the catalogs exist and the id's are correct. It all looks good. 
I also did some further debugging and I can see that the SDK does generate the correct URL and that the request that goes out  is correct.

It's what ever happens on the Graph API side that seems to be the problem.
The catalog does exists and the Id is correct. We can see it in Entra.

See bellow the Graph Explorer.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/105916663/aedf1616-07b2-4b9b-bec5-b9b3c00b7b40)

**Comment by andrueastman** [comment]
Thanks for the extra information here. 

Just to confirm again. 
Does this happen on all requests or specific catalogs. Are you able to create a support ticket for this at with you substcription/tenant info using instruction at https://developer.microsoft.com/en-us/graph/support? (As this team is mainly intended for SDK related issues, we may not be best placed to help with API related issues)

**Comment by alvicode** [comment]
This happens for all requests to 
https://graph.microsoft.com/v1.0/identityGovernance/entitlementManagement/catalogs/{catalogId}/accessPackages

We did find a workaround though:

```
        var result = await GraphClient
            .IdentityGovernance
            .EntitlementManagement
            .Catalogs[catalogId]
            .GetAsync(requestConfiguration =>
            {
                    requestConfiguration.QueryParameters.Expand = ["accessPackages"];
            });
```
this works.
