### ISSUE TITLE
graphClient.Users[userId].LicenseDetails.GetTeamsLicensingDetails.GetAsync() generate error 404 "Requested API is not supported. Please check the path"

### ISSUE THREAD

**Issue by VianneyDoleans** [microsoftgraph/msgraph-sdk-dotnet#2528]
### Describe the bug

A call to await graphClient.Users[userId].LicenseDetails.GetTeamsLicensingDetails.GetAsync(); generate an exception 404 error - message "Requested API is not supported. Please check the path.".

In debug mode of Visual Studio, the URL request indicated in the event viewer is "https://graph.microsoft.com/v1.0/users/{userId}/licenseDetails/getTeamsLicensingDetails()"

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/b1d87b2b-bf25-468a-899e-7a0357a0b505)

### Expected behavior

graphClient.Users[userId].LicenseDetails.GetTeamsLicensingDetails.GetAsync() should return 200 with a response or 404 user id not found.
Documentation of this endpoint : https://learn.microsoft.com/en-us/graph/api/licensedetails-getteamslicensingdetails?view=graph-rest-1.0&tabs=http

### How to reproduce

Authenticate and execute the call GraphClient.Users[userId].LicenseDetails.GetTeamsLicensingDetails.GetAsync();

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/52690cd4-0fce-472f-a2bc-407258987bd9)

### SDK Version

5.55.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @VianneyDoleans 

Are you by any chance able confirm with by making a similar call(both failure and successful) on [the Graph Explorer](https://aka.ms/ge)? 

`GetTeamsLicensingDetails` is documented as an Odata Function in the metadata and should typically bring no issue with the presence/abscence of `()` charater as it is parameter less.

**Comment by VianneyDoleans** [comment]
After some tests on Graph explorer. I think maybe the problem is because of the version used by the SDK ?
The documentation specify beta in the URL but the SDK specify v1 on the URL : 

visual studio debug :
<img width="180" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/a19f6a9e-ae39-4c2f-b9b9-249531546819">

documentation :
<img width="443" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/bd02b883-f5ae-41e8-87b4-a1f49687d098">

I tried on Graph Explorer, it gives : 

beta : 
<img width="921" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/e9601881-4e94-4e85-99ab-611600679413">

v1 :

<img width="907" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/14938664/b1928271-85ec-4a05-9fd9-b9317e7d59d8">

**Comment by andrueastman** [comment]
Thanks for the extra information, 

does this mean that the api call works now if you pass a different baseUrl when creating the client as below for the call? This may suggest that the v1.0 api does not support this yet. 

```cs
var graphClient = new GraphServiceClient(tokenCrendential,baseUrl:"https://graph.microsoft.com/beta");
```

**Comment by VianneyDoleans** [comment]
By adding ` ,baseUrl:"https://graph.microsoft.com/beta"` on the `GraphServiceClient`, I receive error "Requested API is not supported in application-only context" which doesn't help me because I need to automate the creation of Teams meetings, but at least the response seems consistent and is probably right.
So I supposed the v1.0 doesn't support this endpoint.

**Comment by andrueastman** [comment]
Taking a look at the graph changelog, I do not believe this API is supported yet in v1.0 but only in beta. 

https://developer.microsoft.com/en-us/graph/changelog?search=getTeamsLicensingDetails

Any chance you can create a question at https://aka.ms/askGraph to get feedback from the API owners on the relevant information on v1.0 support as well as application permissions. As this repo is mainly intended for SDK related issues, we may not be best placed to answer this.
