### ISSUE TITLE
graphClient.Drives[driveId].Items[driveItemId].Children.GetAsync(config => { config.QueryParameters.Expand = ["listItem"]; }) does not include custom fields in the list item response

### ISSUE THREAD

**Issue by DGV1995** [microsoftgraph/msgraph-sdk-dotnet#2532]
### Is your feature request related to a problem? Please describe the problem.

Hello, I have noticed that when calling https://graph.microsoft.com/v1.0/drives/[driveId]/items/[itemId]/children?expand=listItem, the response includes list item custom fields, but when using the Graph SDK in the next way:

```c#
graphServiceClient.Drives[driveId].Items[itemId].Children.GetAsync(requestConfiguration =>
{
    requestConfiguration.QueryParameters.Expand = ["listItem"];
});
```
The response includes the list item, but not the list item custom fields.
Is it possible to have that custom fields in the response?

Thanks!

### Describe the solution you'd like.

I would like to have the custom fields (like a custom column in a Sharepoint document) in the ListItem property of the DriveItem response, please. 
The only alternative that currently works for me in the next one:
````c#
driveItem.ListItem = await graphServiceClient!.Drives[driveId].Items[driveItemId].ListItem.GetAsync(requestConfig =>
{
    requestConfig.QueryParameters.Expand = ["fields"];
});
````
but this approach requires an additional graph api call for every drive item.

**Comment by andrueastman** [comment]
Thanks for raising this @DGV1995 

Are you by any chance able to resolve this if you use a nested expand statement for the fields with code that looks like this?

```cs
var result = await graphClient.Drives["{drive-id}"].Items["{driveItem-id}"].Children.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Expand = new string []{ "listItem($expand=fields)" };
});
```

**Comment by DGV1995** [comment]
Hi,

Yes, it actually works with that code. Thanks a lot :D
