### ISSUE TITLE
Generating latest client logs errors

### ISSUE THREAD

**Issue by Balkoth** [microsoftgraph/msgraph-sdk-dotnet#2537]
### Describe the bug

```
fail: Kiota.Builder.KiotaBuilder[0]
      OpenAPI error: #/paths/~1identity~1authenticationEventsFlows~1{authenticationEventsFlow-id}~1graph.externalUsersSelfServiceSignUpEventsFlow~1onAttributeCollection~1graph.onAttributeCollectionExternalUsersSelfServiceSignUp/get/responses/2XX/description - The field 'description' in 'response' object is REQUIRED.
fail: Kiota.Builder.KiotaBuilder[0]
      OpenAPI error: #/paths/~1identity~1authenticationEventsFlows~1{authenticationEventsFlow-id}~1graph.externalUsersSelfServiceSignUpEventsFlow~1onAuthenticationMethodLoadStart~1graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/get/responses/2XX/description - The field 'description' in 'response' object is REQUIRED.
```

### Expected behavior

No errors.

### How to reproduce

Generate Graph client with latest kiota bits.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @Balkoth 

Just to confirm, do the errors prevent the generation of a client? Or is the client still generated? 
I believe the errors generated are from the[ Open API parsing library](https://github.com/microsoft/openAPI.NET) which suggests an issue with the graph metadata or metadata conversion tool.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-metadata/issues/646 and https://github.com/microsoft/OpenAPI.NET.OData/issues/546

Closing this one for now as this was resolved via https://github.com/microsoft/OpenAPI.NET.OData/pull/547
