### ISSUE TITLE
Azure.Identity 1.11.4: how to use WebView2 control?

### ISSUE THREAD

**Issue by WolfgangHG** [microsoftgraph/msgraph-sdk-dotnet#2542]
This is a problem that came up with the Azure.Identity update to 1.11.4 (which updated from "Microsoft.Identity.Client" 4.60.3 to 4.61.3): previously, it used "Microsoft.Web.WebView2" and the azure login screen was shown in a WebView2 embedded browser as a modal dialog.
Now, the default system browser opens as a separate application, which is less comfortable for users.

I have no idea how to bring back the old behavior.

I create the GraphServiceClient this way (using classes from "Azure.Identity"):

```c#
InteractiveBrowserCredentialOptions options = new InteractiveBrowserCredentialOptions
{
  TenantId = myTenant,
  ClientId = myClientId,
  AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
  RedirectUri = new Uri("http://localhost")
};

InteractiveBrowserCredential interactiveCredential = new InteractiveBrowserCredential(options);

GraphServiceClient graphClient = new GraphServiceClient(interactiveCredential, new List<string>() { "myScope" });
```

I tried to force the WebView2 control:

```c#
BrowserCustomizationOptions customizationOptions = new BrowserCustomizationOptions();
customizationOptions.UseEmbeddedWebView = true;

InteractiveBrowserCredentialOptions options = new InteractiveBrowserCredentialOptions
{
  ...
  BrowserCustomization = customizationOptions,
};
```

But this code results in an exception:

`InteractiveBrowserCredential authentication failed: To enable the embedded webview on Windows, reference Microsoft.Identity.Client.Desktop and call the extension method .WithWindowsEmbeddedBrowserSupport().`

Adding the package "Microsoft.Identity.Client.Desktop" does not bring me further, as the extension method "PublicClientApplicationBuilder.WithWindowsEmbeddedBrowserSupport" requires an application builder, and I have not idea how to use this application builder with a GraphServiceClient. This probably happens internally?

**Comment by andrueastman** [comment]
Thanks for raising this @WolfgangHG 

As this issue is with the `Azure.Identity` library, any chance you can post the same issue at https://github.com/Azure/azure-sdk-for-net/issues/new/choose for the library authors to resolve?

**Comment by WolfgangHG** [comment]
Thanks, I also thought that it is probably not related to Microsoft.Graph, but I started here, as your Api is the entry point.

I created [https://github.com/Azure/azure-sdk-for-net/issues/44550](https://github.com/Azure/azure-sdk-for-net/issues/44550) and hope for some feedback.

Could we keep this issue open for a few days, until I receive feedback from Azure.Identity - just in case there is some change in your api required. I promise to close it after one week if nothing happens.

**Comment by andrueastman** [comment]
> Could we keep this issue open for a few days, until I receive feedback from Azure.Identity - just in case there is some change in your api required. I promise to close it after one week if nothing happens.

No worries. Thanks for following up on this.

**Comment by WolfgangHG** [comment]
Yes, we can close this one. Currently it is suggested in the linked Azure.Identity issue that I have to code a workaround myself (and avoid Azure.Identity), as Azure.Identity has no API to plugin in the necessary call to "PublicClientApplicationBuilder.WithWindowsEmbeddedBrowserSupport".

So far, no change to Microsoft.Graph seems to be required.
