### ISSUE TITLE
Delta request for sites does not return the correct ID for a site in graph

### ISSUE THREAD

**Issue by Admiral-Skye** [microsoftgraph/msgraph-sdk-dotnet#2543]
### Describe the bug

I am trying to retrieve a delta of sites for my application using the following code:

```CSHARP
var sharePointSites = Graph.Sites
  .Delta
  .GetAsDeltaGetResponseAsync((requestConfiguration) =>
  {
    requestConfiguration.QueryParameters.Select = ["displayName", "id"];
  }).Result;
```
Which returns a set of sharepoint sites from Graph however the Ids included are not valid ids for use in further Graph requests and are instead guids that match the WebId included in sharePointIds.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/38347874/45889ad3-ded2-4ca8-abb8-b1563fbbe0e1)

this id should be of the format:

`icognitiondev.sharepoint.com,{siteId},{WebId}`

### Expected behavior

Requesting the sites delta should include the full sharepoint site id in the responses to allow for further requests to be possible,

### How to reproduce

Requesting a delta without deltalink url with the following code will demonstrate the issue:

```CSHARP
var sharePointSites = Graph.Sites
  .Delta
  .GetAsDeltaGetResponseAsync((requestConfiguration) =>
  {
    requestConfiguration.QueryParameters.Select = ["displayName", "id"];
  }).Result;
```

### SDK Version

5.56.0

### Known Workarounds

It is possible to reassemble the sharepoint id by requesting the properties sharepointIds and siteCollection and then assembling it as such from the result.

```CSHARP
var sharePointSites = Graph.Sites
    .Delta
    .GetAsDeltaGetResponseAsync((requestConfiguration) =>
    {
        requestConfiguration.QueryParameters.Select = ["displayName", "id", "sharepointIds", "siteCollection"];
    }).Result;

foreach (var site in sharePointSites.Value)
{
  var graphId = $"{site.SiteCollection.Hostname},{site.SharepointIds.SiteId},{site.SharepointIds.WebId}";
  // [...]
}
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

- Windows x86

**Comment by andrueastman** [comment]
Thanks for raising this @Admiral-Skye 

Just to confirm, any chance you can confirm if this is the behaviour when you make a similar query using [the Graph Explorer](https://aka.ms/ge)?

**Comment by Admiral-Skye** [comment]
Hi @andrueastman, I haven't been able to get the graph explorer to perform the same request as it keeps telling me its unauthorised even though i have the requisite permissions already consented.

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/38347874/1cb90052-c9fb-48bb-b8c6-16331dbdff0a)

I also tried using /sites/delta and got the same error.

interestingly the msdn article for this request here https://learn.microsoft.com/en-us/graph/api/site-delta?view=graph-rest-1.0&tabs=http#response-1 shows the correct ids being responded with.

**Comment by andrueastman** [comment]
> interestingly the msdn article for this request here https://learn.microsoft.com/en-us/graph/api/site-delta?view=graph-rest-1.0&tabs=http#response-1 shows the correct ids being responded with.

The second example though has the ids in the alternative format though.

As this regards API related behavior and this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the API owners with regards to what is expected? Another alternative would be to create a support ticket with you subscription information at https://developer.microsoft.com/en-us/graph/support

https://aka.ms/askgraph

**Comment by Admiral-Skye** [comment]
Hi @andrueastman I have raised a question on the Q&A site here https://learn.microsoft.com/en-us/answers/questions/1708943/what-is-the-correct-way-to-get-the-site-delta-quer

**Comment by plachance-q1** [comment]
We had the same issue and I asked this question:  
https://learn.microsoft.com/en-us/answers/questions/1696494/https-graph-microsoft-com-v1-0-sites-delta-return
Based on the answer I got, this is By-Design.
Workaround described in my question.

**Comment by andrueastman** [comment]
Thanks for confirming this. 

As this is an API related feedback and this repo is mainly intended for SDK related issues, we'll close this issue for now. Please feel free to open/upvote an issue at https://aka.ms/graphfeedback so that the relevant API owners.
