### ISSUE TITLE
Missing programmatic endpoint for a team's root site

### ISSUE THREAD

**Issue by Admiral-Skye** [microsoftgraph/msgraph-sdk-dotnet#2544]
### Describe the bug

I am trying to find the root site for my teams group however it is not possible to get the root site from the graph sdk. 

I am able to make the following http request in the graph explorer:
`https://graph.microsoft.com/v1.0/groups/{group-id}/sites/root`

However there is no corresponding request in the C# sdk under `Graph.Groups[group.Id].Sites`, this is also missing from the MSDN article which when looking at examples in C# and other languages suggest to use `Graph.Groups[group.Id].Sites[site.id]` which is only possible if the root site's id is known ahead of time.

Attempting the following code which does compile:
```CSHARP
var site = Graph.Groups[group.Id].Sites["root"].GetAsync().Result
```

results in an exception: "Invalid object identifier 'sites'"
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/38347874/41cfbb9f-a413-4a2a-a3bb-92cea855b2d1)

### Expected behavior

A method to request the root site for a group exists. 

`Graph.Groups[group.Id].Sites.Root`

### How to reproduce

using the SDK to try and retrieve the root site of a group will show that it is functionally impossible without knowing the site's id ahead of time. 

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

- Windows x86

**Comment by andrueastman** [comment]
Thanks for raising this @Admiral-Skye 

Any chance you can confirm if the url is as expected when running the code below?

```cs
            var requestInformation = graphClient.Groups[group.Id].Sites["root"].ToGetRequestInformation();
            Console.WriteLine(requestInformation.URI.OriginalString);
```

Do you still get the error once you paste and make the request using [the Graph Explorer?](https://aka.ms/ge)

**Comment by Admiral-Skye** [comment]
Oh thanks @andrueastman! I see where I was going wrong, the request info helped me find the issue, apparently my group query was not including the id in its response which was causing an invalid request to be generated. 

Correcting that issue further upstream means that 

```CSHARP
var site = Graph.Groups[group.Id].Sites["root"].GetAsync().Result;
```

works as expected.

I still think an explicit `.Root` would be welcome as other graph sdk calls for things like DriveItems include it explicitly

```CSHARP
var rootDriveItem = Graph.Drives[drive.Id].Root.GetAsync().Result;
```

**Comment by andrueastman** [comment]
Thanks for confirming this @Admiral-Skye 

At the moment, we won't be adding this due to related path expansion limitations documented at https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#drive-item-paths. As this is working, we'll close this issue for now.
