### ISSUE TITLE
Are there any plans to support authentication for .NET Core?

### ISSUE THREAD

**Issue by ivannp** [microsoftgraph/msgraph-sdk-dotnet#256]
The UI used for authentication seems to be Windows based.

**Comment by MIchaelMainer** [comment]
I think you meant to ask this question in the repo for the authentication libraries. 

Please see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/ADAL-.NET-Q-&-A#what-platforms-does-each-version-of-adal-net-support.

Please reopen this issue if I misunderstood you.
