### ISSUE TITLE
User Patch request fails if 'displayName' is not present

### ISSUE THREAD

**Issue by bolt-io** [microsoftgraph/msgraph-sdk-dotnet#2561]
### Describe the bug

I am trying to update a user's surname but forced to provide a value for displayName for any patch requests. This is not a required field from the Microsoft Graph API.

Response error:

```
  Message: 
Microsoft.Graph.Models.ODataErrors.ODataError : A value is required for property 'displayName' of resource 'User'.

  Stack Trace: 
HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
UserItemRequestBuilder.PatchAsync(User body, Action`1 requestConfiguration, CancellationToken cancellationToken)
GraphUserRepository.UpdateUserAsync[TInput](String id, TInput user) line 126
GraphUserRepositoryTests.UpdateUserAsync_WhenUserExists_ReturnsTrue(String userId) line 173
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
BeforeTestCommand.Execute(TestExecutionContext context)
<>c__DisplayClass3_0.<PerformWork>b__0()
<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
ContextUtils.DoIsolated(ContextCallback callback, Object state)
ContextUtils.DoIsolated[T](Func`1 func)
SimpleWorkItem.PerformWork()

```

### Expected behavior

The user is updated without the forced requirement of `displayName` being provided.

### How to reproduce

Run the following code snippet against the Graph Service Client with a valid user ID

```csharp
User updatedUser = new() { GivenName = "someValue" };

await _graphServiceClient.Users["{userId}"].PatchAsync(updatedUser).ConfigureAwait(false);
```

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @bolt-io.

As this is an issue related to the functionality of the API and this repo is mainly intended for SDK related issues, any chance you can post the question at the link below to get feedback from the relevant API owners? 

https://aka.ms/askGraph

**Comment by bolt-io** [comment]
@andrueastman it would look to me like the issue is _somewhere_ in the SDK as running directly against the Graph API results in a success response (see below)

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/10209663/af173c8e-4391-4a75-b246-0a5a2f21787d)

**Comment by MartinM85** [comment]
If the request body (in Graph Explorer) is 
```
{
    "givenName": "Dee",
    "displayName": null
}
```
It returns the exception mentioned above: `A value is required for property 'displayName' of resource 'User'.`

**Comment by andrueastman** [comment]
Thanks for confirming @bolt-io. Closing this one for now.
