### ISSUE TITLE
The repo cannot be cloned. Downloaded zip file is invalid

### ISSUE THREAD

**Issue by AlexBeyd** [microsoftgraph/msgraph-sdk-dotnet#2564]
Hello

I was trying to clone the repository and getting the below error because path is too long, even when cloning to c:/
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6156494/33e661cf-acbd-48d5-a939-3a853b18930b)

When downloaded zip file, the file is invalid

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/6156494/8c133e12-e055-4ac3-8cd1-a075bcac506b)

**tried both on two different machines**

**Comment by andrueastman** [comment]
Thanks for raising this @AlexBeyd 

Any chance you can try out the options in the end of this section of the Readme?

https://github.com/microsoftgraph/msgraph-sdk-dotnet?tab=readme-ov-file#building-library-locally

**Comment by remoal-tc** [comment]
Thanks Andrew. It worked
