### ISSUE TITLE
Filter "Endswith" results in "The query filter contains one or more invalid nodes." Error

### ISSUE THREAD

**Issue by vknht** [microsoftgraph/msgraph-sdk-dotnet#2572]
### Describe the bug

I am trying to filter Messages where the subject ends with a certain value but i am getting the error in the title.

### Expected behavior

not getting an error

### How to reproduce

```c#
var foo = await _graphClient
   .Users[USER_ID]
   .MailFolders[MAIL_FOLDER_ID]
   .Messages
   .GetAsync(cfg =>
   {
	   cfg.QueryParameters.Filter = "endswith(subject, 'FooBar')";
	   cfg.Headers.Add("ConsistencyLevel", "eventual");
	   cfg.QueryParameters.Count = true;
   });
```

i read here https://stackoverflow.com/a/67876119 that "ConsistencyLevel" and "Count" must be included in the query to make "endswith" work but it did not.

"startswith" works without problems.

### SDK Version

5.54.0

### Latest version known to work for scenario above?

unknown

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

- OS: Windows 10
- x64

**Comment by andrueastman** [comment]
As this question relates to functionality of the API and this Repo is mainly intended for SDK related issues, Any chance you can post the question at the link below to get feedback from the API owners?

https://aka.ms/askGraph

**Comment by vknht** [comment]
Done.

https://learn.microsoft.com/en-us/answers/questions/1806017/filter-endswith-results-in-the-query-filter-contai

**Comment by andrueastman** [comment]
Closing this here one for now so that it may be followed up there.
