### ISSUE TITLE
`user@odata.bind` Field Missing Error in Microsoft Graph API /chats POST Request

### ISSUE THREAD

**Issue by julianmaurice** [microsoftgraph/msgraph-sdk-dotnet#2577]
### Describe the bug

I am encountering an issue with the Microsoft Graph API when attempting to create a new chat using the /chats POST request. The request fails with the following error message:

```csharp 
Microsoft.Graph.Models.ODataErrors.ODataError: 'user@odata.bind' field is missing in the request.
```

Despite ensuring that the user@odata.bind field is correctly formatted and included in the request, the API still returns this error. This problem has only recently started occurring, and the same code was functioning correctly before.

### Expected behavior

The chat should be created successfully, with the members specified in the Members list being correctly added to the chat.

### How to reproduce

1. Use the Microsoft Graph SDK for C# to create a new chat.
2. Format the request as follows:

```csharp


var chatRequestBody = new Chat
        {
            ChatType = ChatType.OneOnOne,
            Members = new List<ConversationMember>
            {
                new AadUserConversationMember
                {
                    Roles = new List<string>
                    {
                        "owner",
                    },
                    AdditionalData = new Dictionary<string, object>
                    {
                        {
                            "user@odata.bind" , $"https://graph.microsoft.com/v1.0/users('{Environment.GetEnvironmentVariable("SupportAccount")}')"
                        },
                    },
                },
                new AadUserConversationMember
                {
                    Roles = new List<string>
                    {
                        "owner",
                    },
                    AdditionalData = new Dictionary<string, object>
                    {
                        {
                            "user@odata.bind" , $"https://graph.microsoft.com/v1.0/users('{userId}')"
                        },
                    },
                },
            },
        };
        
        
        var chat = await _graphServiceClient
            .Chats
            .PostAsync(chatRequestBody);

```

3. Execute the request and observe the error.

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @julianmaurice 

Any chance you can confirm again the version of the SDK you are using? The issue mentions `5.56.0` however `Request()` methods were removed in 5.x.x versions of the SDK...

**Comment by julianmaurice** [comment]
Ah, sorry for the confusion. I updated the post to clarify that the issue is with the request body. Specifically, I am including user@odata.bind in the AdditionalData, but the API responds with the error.

**Comment by andrueastman** [comment]
Thanks for confirming

Are you able to get the json response payload and use it to make a similar request on the [Graph Explorer](https://aka.ms/ge)? 
Do you still get the same error?

```cs
var jsonString = KiotaJsonSerializer.SerializeAsString(chatRequestBody);
```

**Comment by julianmaurice** [comment]
Ah, very nice! This snippet allowed me to see that the request sent by the client was correctly formatted. I realized that the mistake was in my code. Thank you for your help!
