### ISSUE TITLE
Gallatin: Parsing OData Select and Expand failed: Could not find a property named 'singleValueExtendedProperties' on type 'microsoft.graph.message'

### ISSUE THREAD

**Issue by KaichengHuang** [microsoftgraph/msgraph-sdk-dotnet#2578]
### Describe the bug

Based on https://learn.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties?view=graph-rest-1.0&tabs=http and https://learn.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-get?view=graph-rest-1.0&tabs=http, create and get singleValueExtendedProperties is supported in Gallatin which is "China operated by 21Vianet". But I test it in following way, it hits error.

Get:
https://microsoftgraph.chinacloudapi.cn/v1.0/me/mailfolders/sentitems/messages/AAMkADZiNDY2NDgzLWEyNjctNDc0Mi04Y2UzLWRmYWU5ZTlkNzczMwBGAAAAAAAsuDXm95qTQaO8H_G1D9NnBwCRMYEyJn9sS7hvpWi4TRRTAAAAAAEJAACRMYEyJn9sS7hvpWi4TRRTAACjl5j6AAA=?$select=internetMessageId,subject,from,sender,toRecipients,ccRecipients,bccRecipients,sentDateTime,id&$expand=singleValueExtendedProperties($filter=Id eq 'string 0x4038')

response:
{
    "error": {
        "code": "BadRequest",
        "message": "Parsing OData Select and Expand failed: Could not find a property named 'singleValueExtendedProperties' on type 'microsoft.graph.message'.",
        "innerError": {
            "date": "2024-07-10T09:16:05",
            "request-id": "e96fe6f2-1d55-47d4-a326-24c1ae585438",
            "client-request-id": "e96fe6f2-1d55-47d4-a326-24c1ae585438"
        }
    }
}

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/142395186/18c5d63a-929b-46c2-b6c0-40e7fc98c35f)

patch:
https://microsoftgraph.chinacloudapi.cn/v1.0/me/mailfolders/sentitems/messages/AAMkADZiNDY2NDgzLWEyNjctNDc0Mi04Y2UzLWRmYWU5ZTlkNzczMwBGAAAAAAAsuDXm95qTQaO8H_G1D9NnBwCRMYEyJn9sS7hvpWi4TRRTAAAAAAEJAACRMYEyJn9sS7hvpWi4TRRTAACjl5j6AAA=

body:
{
    "singleValueExtendedProperties": [
        {
            "id": "String {cf7f4a25-a4ec-4d56-99cd-74c698a57ddc} Name LatestRecallTime",
            "value": "03:16:57.228 AM 9/18/2023"
        }
    ]
}

response:
{
    "error": {
        "code": "RequestBodyRead",
        "message": "The property 'singleValueExtendedProperties' does not exist on type 'Microsoft.OutlookServices.Message'. Make sure to only use property names that are defined by the type or mark the type as open type.",
        "innerError": {
            "date": "2024-07-10T09:18:00",
            "request-id": "608917d1-2038-414a-99c6-0e334906f991",
            "client-request-id": "608917d1-2038-414a-99c6-0e334906f991"
        }
    }
}

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/142395186/b4b80063-44cf-4f9a-8572-1d6e74d80b84)

### Expected behavior

I test this in Dod which is US Government L5, it works for both get and create operation.
So, it is Gallatin environment issue.

Get:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/142395186/f5926e88-1e5b-4c8b-8f4c-ef2787c63596)

Patch:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/142395186/cf499227-cd95-436c-8004-173f2f3acd56)

Get the patch value:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/142395186/ad833e80-c458-49c1-a160-c81a206713fc)

### How to reproduce

Just use postman with correct user token.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @KaichengHuang 

As this repo is mainly intended for SDK related issues,  we may not be best placed to handle issues with regards to the API side functionality. 

Any chance you can post a question at https://aka.ms/askGraph to confirm if this is expected? Otherwise, you can also provide feedback at https://aka.ms/graphFeedback for the relevant API owners to look into this.

**Comment by KaichengHuang** [comment]
Sure, also ask here:
https://learn.microsoft.com/en-us/answers/questions/1806387/gallatin-parsing-odata-select-and-expand-failed-co

**Comment by andrueastman** [comment]
Thanks for this @KaichengHuang.

We'll close this here for now so that is may be followed up there.

**Comment by KaichengHuang** [comment]
Update:

Sandeep Reddy sent a PR to fix this issue for Gallatin: [Pull request 10460063: Updated Message schema to add singleValueExtendedProperties. - Repos (azure.com)](https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullrequest/10460063)
