### ISSUE TITLE
GetAsDeltaGetResponseAsync hangs for a particular mailbox, no exception thrown

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/msgraph-sdk-dotnet#2582]
### Describe the bug

I am trying to get a delta for a mailbox, the following line of code hangs, it never returns - worked fine in v4

```
var mailFolders = Graph.Users["ba-teams@icognition.cloud"].MailFolders
    .Delta
    .GetAsDeltaGetResponseAsync().Result;
```

### Expected behavior

Returns something, whether thats a delta response or an exception.

### How to reproduce

See code above.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @catmanjan 

Any chance the code works if you use an await call?

https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

```cs
var mailFolders = await Graph.Users["ba-teams@icognition.cloud"].MailFolders
    .Delta
    .GetAsDeltaGetResponseAsync();
```

**Comment by catmanjan** [comment]
This mysteriously started working today, I am wondering if the API was self
throttling? Is that a thing? Anyway way to tell if that was the case?

**Comment by andrueastman** [comment]
One thing you could do is look into the docs at the link below. 
By enabling custom logging you can know where the issue is from in the failed response/request cycle. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md
