### ISSUE TITLE
Can't get list of frequently used SharePoint sites

### ISSUE THREAD

**Issue by dzebas** [microsoftgraph/msgraph-sdk-dotnet#2583]
### Describe the bug

Hi,

Recently updated Microsoft Graph to version 5 which broke almost everything we had. In old version we had this code to get list of frequently used sites (similar to what you get in Excel or Word):

```
var sites = await graphClient.Me.Insights.Used
                        .Request()
                        .Filter( "ResourceVisualization/Type eq 'spsite'" )
                        .OrderBy( "lastUsed/lastAccessedDateTime desc" )
                        .GetAsync();
```

In version 5 we are trying to achieve same with this code:

`var sites = await graphClient.Me.Insights.Used.GetAsync();`

Problem is it only returns used files, not sites. Adding filter doesn't help either.

### Expected behavior

Should list frequently used sites.

### How to reproduce

Execute this code, it won't return sites, just files:

`var sites = await graphClient.Me.Insights.Used.GetAsync();`

### SDK Version

5.5.6

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @dzebas 

I believe the equivalent of the v4 requests is as below

```cs
var result = await graphClient.Me.Insights.Used.GetAsync((requestConfiguration) =>
{
	requestConfiguration.QueryParameters.Filter = "ResourceVisualization/Type eq 'spsite'";
	requestConfiguration.QueryParameters.Orderby = new string []{ "lastUsed/lastAccessedDateTime desc" };
});
```

Any chance this works out for you?

**Comment by dzebas** [comment]
@andrueastman Thanks a lot, it works! :)
