### ISSUE TITLE
ItemNotFound for some messages when notified via webhhook

### ISSUE THREAD

**Issue by bokmadsen** [microsoftgraph/msgraph-sdk-dotnet#259]
I have an multi-tenance application, that uses app-only tokens to access the graph API using the SDK. I've setup webhooks to cacth mails when the tenant is sending emails. Sometimes however, I'm unable to find the message in the store. The Graph API throws 

`    Code: ErrorItemNotFound Message: The specified object was not found in the store., The process failed to get the correct properties.
`

I've tried to get it from EWS too, without luck. 

This is not consistent for any tenant. It's different tenants and not always.

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. This repo is for the .Net client library. Please post your questions to StackOverflow with the microsoftgraph tag. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
* How often do you see this error?

For example, we'd need more information about which notifications are being called, how often this happens, what other actors are there on the objects in Exchange, etc.
