### ISSUE TITLE
Serialization Issues for Null values of Graph Event Objects

### ISSUE THREAD

**Issue by visnikam** [microsoftgraph/msgraph-sdk-dotnet#2607]
### Describe the bug

We have observed a serialization issue when using from Microsoft.Graph version 5.56.0 in our .NET 6 project.  In Update event, patch method it adds Null values to priorities that or not assigned. we've noticed that some fields are missing in the response from event patch call e.g. attendees. We have used System.Text.Json for sterilization and also tried JsonIgnoreCondition but it didn't work while passing event object to SDK method. Microsoft Graph API team mentioned that failure or issues due to additional properties in patch request. Please suggest.

JsonSerializerOptions options = new()
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
            };

URL : https://graph.microsoft.com/v1.0/users/{useremail}/events/{eventId}
Http Method : Patch
SDK Method : graphClient.Users[delegatedUserEmail].Events[eCreated.Id].PatchAsync(updateEvent);
UpdateEvent Request Object:
{
	"AllowNewTimeProposals": null,
	"Attachments": null,
	"Attendees": [
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "abc@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		},
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "xyz@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		}
	],
	"Body": {
		"AdditionalData": {},
		"BackingStore": {
			"ReturnOnlyChangedValues": false,
			"InitializationCompleted": true
		},
		"Content": "<table> <tbody><tr><td><strong>Test Event</strong></td> </tr> </tbody> </table>",
		"ContentType": 1,
		"OdataType": null
	},
	"BodyPreview": null,
	"Calendar": null,
	"End": null,
	"Extensions": null,
	"HasAttachments": null,
	"HideAttendees": null,
	"ICalUId": null,
	"Importance": null,
	"Instances": null,
	"IsAllDay": null,
	"IsCancelled": null,
	"IsDraft": null,
	"IsOnlineMeeting": null,
	"IsOrganizer": null,
	"IsReminderOn": true,
	"Location": null,
	"Locations": null,
	"MultiValueExtendedProperties": null,
	"OnlineMeeting": null,
	"OnlineMeetingProvider": null,
	"OnlineMeetingUrl": null,
	"Organizer": null,
	"OriginalEndTimeZone": null,
	"OriginalStart": null,
	"OriginalStartTimeZone": null,
	"Recurrence": null,
	"ReminderMinutesBeforeStart": 1532,
	"ResponseRequested": null,
	"ResponseStatus": null,
	"Sensitivity": null,
	"SeriesMasterId": null,
	"ShowAs": null,
	"SingleValueExtendedProperties": null,
	"Start": null,
	"Subject": null,
	"TransactionId": null,
	"Type": null,
	"WebLink": null,
	"Categories": null,
	"ChangeKey": null,
	"CreatedDateTime": null,
	"LastModifiedDateTime": null,
	"AdditionalData": {},
	"BackingStore": {
		"ReturnOnlyChangedValues": false,
		"InitializationCompleted": true
	},
	"Id": null,
	"OdataType": "#microsoft.graph.event"
}

### Expected behavior

Update Event Request Object for Patch call expected below
{
	"Attendees": [
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "abc@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		},
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "xyz@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		}
	],
	"Body": {
		"AdditionalData": {},
		"BackingStore": {
			"ReturnOnlyChangedValues": false,
			"InitializationCompleted": true
		},
		"Content": "<table> <tbody><tr><td><strong>Test Event</strong></td> </tr> </tbody> </table>",
		"ContentType": 1,
		"OdataType": null
	}
}

### How to reproduce

URL : https://graph.microsoft.com/v1.0/users/{useremail}/events/{eventId}
Http Method : Patch
SDK Method : SDK Method : graphClient.Users[delegatedUserEmail].Events[eCreated.Id].PatchAsync(updateEvent);
UpdateEvent Request Object :
{
	"AllowNewTimeProposals": null,
	"Attachments": null,
	"Attendees": [
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "abc@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		},
		{
			"ProposedNewTime": null,
			"Status": null,
			"Type": 0,
			"AdditionalData": {},
			"BackingStore": {
				"ReturnOnlyChangedValues": false,
				"InitializationCompleted": false
			},
			"EmailAddress": {
				"AdditionalData": {},
				"Address": "xyz@test.com",
				"BackingStore": {
					"ReturnOnlyChangedValues": false,
					"InitializationCompleted": false
				},
				"Name": null,
				"OdataType": null
			},
			"OdataType": "#microsoft.graph.attendee"
		}
	],
	"Body": {
		"AdditionalData": {},
		"BackingStore": {
			"ReturnOnlyChangedValues": false,
			"InitializationCompleted": true
		},
		"Content": "<table> <tbody><tr><td><strong>Test Event</strong></td> </tr> </tbody> </table>",
		"ContentType": 1,
		"OdataType": null
	},
	"BodyPreview": null,
	"Calendar": null,
	"End": null,
	"Extensions": null,
	"HasAttachments": null,
	"HideAttendees": null,
	"ICalUId": null,
	"Importance": null,
	"Instances": null,
	"IsAllDay": null,
	"IsCancelled": null,
	"IsDraft": null,
	"IsOnlineMeeting": null,
	"IsOrganizer": null,
	"IsReminderOn": true,
	"Location": null,
	"Locations": null,
	"MultiValueExtendedProperties": null,
	"OnlineMeeting": null,
	"OnlineMeetingProvider": null,
	"OnlineMeetingUrl": null,
	"Organizer": null,
	"OriginalEndTimeZone": null,
	"OriginalStart": null,
	"OriginalStartTimeZone": null,
	"Recurrence": null,
	"ReminderMinutesBeforeStart": 1532,
	"ResponseRequested": null,
	"ResponseStatus": null,
	"Sensitivity": null,
	"SeriesMasterId": null,
	"ShowAs": null,
	"SingleValueExtendedProperties": null,
	"Start": null,
	"Subject": null,
	"TransactionId": null,
	"Type": null,
	"WebLink": null,
	"Categories": null,
	"ChangeKey": null,
	"CreatedDateTime": null,
	"LastModifiedDateTime": null,
	"AdditionalData": {},
	"BackingStore": {
		"ReturnOnlyChangedValues": false,
		"InitializationCompleted": true
	},
	"Id": null,
	"OdataType": "#microsoft.graph.event"
}

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by visnikam** [comment]
@andrueastman Could you please help us to understand where exactly model should be serialization as we pass Event object to SDK Patch method

URL : https://graph.microsoft.com/v1.0/users/{useremail}/events/{eventId}
Http Method : Patch
Code Sample : 
updateEvent = new Event
{
    Attendees = attendees,
    Body = new ItemBody { Content = @event.Body.Content.Replace("##teamslink##", eCreated.OnlineMeeting?.JoinUrl), ContentType = BodyType.Html },
    ReminderMinutesBeforeStart = reminderMinutes,
    IsReminderOn = true
};

var eGraphUpdatedResponse = await graphClient.Users[delegatedUserEmail].Events[eCreated.Id]
           .PatchAsync(updateEvent, requestConfiguration => requestConfiguration.Headers.Add("client-request-id", updateGuid));

**Comment by andrueastman** [comment]
Apologies for not being clearer earlier, but could you share the value of the `jsonString` variable? It will help understand if there is an issue with the payload being sent to the API.

```cs
var jsonString = await KiotaJsonSerializer.SerializeAsStringAsync(updateEvent );
```

**Comment by visnikam** [comment]
@andrueastman  Please find below jsonString value of Event object with KiotaJsonSerializer 

{
	"@odata.type": "#microsoft.graph.event",
	"attendees": [
		{
			"emailAddress": {
				"address": "abc@test.com"
			},
			"@odata.type": "#microsoft.graph.attendee",
			"type": "required"
		},
		{
			"emailAddress": {
				"address": "xyz@test.com"
			},
			"@odata.type": "#microsoft.graph.attendee",
			"type": "required"
		}
	],
	"body": {
		"content": "<table><tr><td><strong>Test Event</strong></td> </tr></table>",
		"contentType": "html"
	},
	"isReminderOn": true,
	"reminderMinutesBeforeStart": 507
}

**Comment by andrueastman** [comment]
Thanks for confirming this @visnikam 

It looks like the `attendees` property is present here in the payload. Does this update the event successfully?

To confirm, do you mean existing attendees are removed from the list when the response comes back?

**Comment by visnikam** [comment]
@andrueastman Yes, attendees property is present here in the payload. We do get success as response from the SDK/Graph API but sometimes attendees are null/empty in the response and in that case attendee doesn't get the invite update. Microsoft team told us that it's due to additional properties in payload passed by SDK. Please suggest

**Comment by andrueastman** [comment]
>Microsoft team told us that it's due to additional properties in payload passed by SDK. Please suggest

Are you able to share a sample of the additional properties that are passed? Any chance you've taken a look at the guidance at https://learn.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#notes-for-updating-specific-properties

**Comment by John-HLC** [comment]
I stumbled across this -- it is also happening to our project as well.
