### ISSUE TITLE
Specifying 'ReplyTo' is not working

### ISSUE THREAD

**Issue by thevlf** [microsoftgraph/msgraph-sdk-dotnet#2613]
### Describe the bug

We recently noticed that email that is sent from our automated processes no longer displayed the correct 'Reply To' address when hitting reply.

### Expected behavior

When an email came from our info@company.com address and a user hits reply, we expect it to then go to a specified mailbox, like IDS@company.com <-- this information is specified in our automation (which is a .net framework app written in C#).

### How to reproduce

Using Microsoft.Graph version 4x (latest version repros the issue).
Send email with code where you have specifyied the Reply-To property.
Once the email is received, hit reply in Outlook and you will notice it is not sending the email to the ReplyTo address, rather the address of the service account that sent the email.

### SDK Version

4.29.0

### Latest version known to work for scenario above?

This did work on 4.29.0 until recently (last couple of weeks)

### Known Workarounds

I am unable to get this to work.  I have tried upgrading the Microsoft.Graph NuGet package to 4.29.0 and I still see the issue.

I was able to figure out how to update my code to get the mail to send when using the latest 5x Microsoft.Graph code, but I still do not see the ReplyTo values I specified when the mail arrives.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Windows 11 x64

### Other information

We noticed that this started happening withing that past couple of weeks (by looking at old emails that were sent that had the correct Reply-To address configured).

**Comment by JustinRustin** [comment]
Confirming that I can also replicate this issue

**Comment by Zei33** [comment]
This is occurring with our organisation as well. This is a serious issue. Microsoft needs to pay attention to this ASAP.

**Comment by wpo365** [comment]
Yes, I am experiencing this issue as well and with me many of the users of my WordPress plugin WPO365 | MICROSOFT GRAPH MAILER. Please also check https://learn.microsoft.com/en-us/answers/questions/1855228/graph-api-replyto-not-set-when-sending-e-mails. I have also created a Microsoft Support Ticket (ID 2408081420001576) for this.

**Comment by flyExclusiveIT** [comment]
Our Airtable automations are having this same issue when send emails through our exchange online service.
Need a resolution as soon as possible.

**Comment by joshchretien** [comment]
Experiencing the same issues.

**Comment by chayes60** [comment]
This appears to have been resolved, as updated here: https://learn.microsoft.com/en-us/answers/questions/1855228/graph-api-replyto-not-set-when-sending-e-mails?comment=answer-1638187&page=2#answers

Tested and confirmed it's working for us.

**Comment by andrueastman** [comment]
Thanks for confirming @chayes60 

We'll close this one for now.
