### ISSUE TITLE
Listing calendars - Error : {"Content type text/html does not have a factory registered to be parsed"}

### ISSUE THREAD

**Issue by Hantse** [microsoftgraph/msgraph-sdk-dotnet#2630]
### Describe the bug

I try to used background process with this code to authenticate graph client :

```
var clientId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
var tenantId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
var clientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxx";
var scopes = new[] { "https://graph.microsoft.com/.default" };

var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);
var graphClient = new GraphServiceClient(clientSecretCredential, scopes);

var calenders = await graphClient.Users["azeerty@hotmail.com"].Calendars.GetAsync();
```

And at every call i receive :

`Erreur lors de l'appel à Microsoft Graph : Content type text/html does not have a factory registered to be parsed`

### Expected behavior

When i query all user calenders, i want to get the list of all calendars of user to do a background sync.

### How to reproduce

- Create a Console application
- Create Entra ID & Register application
- Add permission in application
- Add code in top
- Install Azure Identity & Graph package
- Try to read user calendars (outlook)

### Latest version known to work for scenario above?

5.50.0

### Debug output

<details><summary>Click to expand log</summary>
When i query all user calenders, i want to get the list of all calendars of user to do a background sync.
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @Hantse 

Are you able to make a successful response if you make the request as below? 

```cs
var calendersRequest = graphClient.Users["azeerty@hotmail.com"].Calendars.ToGetRequestInformation();
var responseStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(calendersRequest);
var responseString = new StreamReader(responseStream).ReadToEnd();
```

**Comment by Hantse** [comment]
I've test and the response :

The server returned an unexpected status code and no error factory is registered for this code: 401

**Comment by andrueastman** [comment]
Thanks for the feedback. 

```cs
var clientId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
var tenantId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
var clientSecret = "xxxxxxxxxxxxxxxxxxxxxxxxx";
var scopes = new[] { "https://graph.microsoft.com/.default" };
```
As the http status code here is a 401, any chance you can double check you authentication credentials above? A 401 response usually means that the credentials used to setup the client are invalid.

**Comment by Hantse** [comment]
If i test another request like, GetUser it's work.
In application permission "Calendar" is check for all.

**Comment by andrueastman** [comment]
Are the users in the two scenarios the same? Or are they different users from different tenants? 
If this was a permission issue I believe you should get a 403 error not a 401..

**Comment by Hantse** [comment]
Same user, same tenant.

**Comment by andrueastman** [comment]
Please share the same if you can

**Comment by Hantse** [comment]
The id you mean ?
This : 1a5024cb-0761-4cd0-8e1c-cc02da973e3c

**Comment by andrueastman** [comment]
@Hantse 

Are you also able to share the response body contents as well? You should be able to capture this as below by sending a native request.

```cs
            var httpClient = new HttpClient();
            var userRequest = graphClient.Users["user-id"].Calendars.ToGetRequestInformation();
            var nativeRequest = await graphClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(userRequest);
            var response = await httpClient.SendAsync(nativeRequest);

            Console.WriteLine(response.StatusCode);
            Console.WriteLine(await response.Content.ReadAsStringAsync());
```

**Comment by Hantse** [comment]
The response :

`{"error":{"code":"OrganizationFromTenantGuidNotFound","message":"The tenant for tenant guid 'xxxxxxx-xxxx-4395-8477-bc0a396f494d' does not exist.","innerError":{"oAuthEventOperationId":"xxxxxx-xxxx-4d36-b61c-19bd35ac5b8b","oAuthEventcV":"ah5NH0e92jbNe2M28et+2Q.1.1","errorUrl":"https://aka.ms/autherrors#error-InvalidTenant","requestId":"c3ec4c0b-72d8-44b7-98a4-64dae4ec7b14","date":"2024-08-22T08:05:13"}}}`

**Comment by worthy7** [comment]
@Hantse  What was the issue in the end?
