### ISSUE TITLE
"Status" in scheduledItem in Graph API, returns integer values, whereas should be returning string

### ISSUE THREAD

**Issue by Md-husain0522** [microsoftgraph/msgraph-sdk-dotnet#2636]
In Graph API, getSchedule action - According to documentation, the "Status"  should be as string with possible values {free, tentative, busy, oof, workingElsewhere, unknown}, whereas
our response contains an integer with values 1-5. 

https://learn.microsoft.com/en-us/graph/outlook-get-free-busy-schedule  , 
https://learn.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http 
and https://learn.microsoft.com/en-us/graph/api/resources/scheduleitem?view=graph-rest-1.0

Please assist and point us to the correct documention.

Request:
<img width="205" alt="image" src="https://github.com/user-attachments/assets/885f347b-1795-42e7-a215-6a9682dbbe91">

Response:
<img width="282" alt="statuserror" src="https://github.com/user-attachments/assets/a7ec225d-478b-48dd-9338-cabf06160092">

**Comment by andrueastman** [comment]
Thanks for raising this @Md-husain0522 

Just to confirm here, are you parsing the response using the SDK? Do you get an error or incorrect mapping on the reading the response using the SDK?

**Comment by Md-husain0522** [comment]
I'm using these SDKs, and not parsing the result from the API, as it is traversable  : 
using Microsoft.Graph;
using Microsoft.Graph.Models;
using Microsoft.Graph.Users.Item.Calendar.GetSchedule;

And the below API call:
<img width="557" alt="image" src="https://github.com/user-attachments/assets/150a75df-0dbf-4487-87e9-401e0065b9d8">

This gives me a response of value array with scheduleditem collection. There is no error in the API response, but according to the documentation, the "status" for every item should be a text field, but the API response has it as an integer, hard to map which integer represents what status {free, tentative, busy, oof, workingElsewhere, unknown}.

**Comment by andrueastman** [comment]
How are you serializing the `result` object to get the json string? Are you using the serialization helpers? 

https://learn.microsoft.com/en-us/openapi/kiota/serialization?tabs=csharp#serialization-helpers

This should look something like

```cs
var jsonString = await KiotaSerializer.SerializeAsStringAsync("application/json", result, false);
```

**Comment by Md-husain0522** [comment]
Hi. I am not serializing the result. The properties in the result from the API are accessible without serialization. 
When you access through "result.Value", all other properties are accessible in the IDE , without knowing the format of the response. 

There is no serialization in the code. I am using the exact response that I get from the GetSchedule API. No parser, or format in between.

**Comment by andrueastman** [comment]
![image](https://github.com/user-attachments/assets/c136db9e-6fa2-4fe5-9ad6-e703a5313a4e)

Out of curiosity, how do you get this?

**Comment by Md-husain0522** [comment]
This is the exact result from the GetSchedule API, and also my question, that why "status" is an integer value, when the documentation says, it's a text field. Instead of 2, The API should be returning the mapped text value for this "2".

**Comment by andrueastman** [comment]
I don't think the API returns properties like `odataType` and `backingStore`. These will typically show up if you use an incompatible serializer to serialize the returned object to a string. The serializer may also serialize enums incorrecty to numbers rather than strings if not configured correctly.

Do you get a different result if you follow the guidance to use the helpers?

**Comment by andrueastman** [comment]
Let us know how this works out. This is the recommended approach as the Graph SDK is generated by Kiota. 

```cs
var jsonString = await KiotaSerializer.SerializeAsStringAsync("application/json", result, false);
```

**Comment by shambhaviQuest** [comment]
@Md-husain0522  can you let me know which .Net/ .Net Framework version you are using?
