### ISSUE TITLE
Subject received as null, in getSchedule API response when requested for multiple emails

### ISSUE THREAD

**Issue by Md-husain0522** [microsoftgraph/msgraph-sdk-dotnet#2637]
In Graph API, getSchedule action - When the request is sent for multiple emails,  other than the first emailid in the list, the subject of the scheduled Items for other emailIds are reseived as null in response.

Request:
<img width="205" alt="image" src="https://github.com/user-attachments/assets/a58add39-2c0b-4f4d-a9af-15de4936b5f9">

Response:
<img width="270" alt="image" src="https://github.com/user-attachments/assets/d6ed0f68-e867-466d-8894-fe2dab048d5c">

**Comment by andrueastman** [comment]
Thanks for raising this @Md-husain0522 

Any chance you can share a full code sample of the request and how you are reading the response in this scenario?

**Comment by andrueastman** [comment]
How are you serializing the `result` object to get the json string? Are you using the serialization helpers? 

https://learn.microsoft.com/en-us/openapi/kiota/serialization?tabs=csharp#serialization-helpers

This should look something like

```cs
var jsonString = await KiotaSerializer.SerializeAsStringAsync("application/json", result, false);
```

**Comment by metametadata** [comment]
I see the same issue using MS Graph Java SDK. Could it be related to some Outlook calendar privacy constraints?
