### ISSUE TITLE
PATCH null - impossible to disable recurrence on event

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#264]
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/event_update)** you used to determine the expected behavior. 
- [x] Actual behavior.
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
I'd expect disabling the recurrence on an event to work properly without having to patch it manually (sending 2 emails).

### Actual behavior
Because the only way to disable recurrence is to [set the property to null](https://stackoverflow.com/questions/49578497/microsoft-graph-api-cancel-recurring-events) and [the update async method sends a patch](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/EventRequest.cs#L121) and the serializer will [ignore null properties](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L278) the events recurrence property will never be set to null.

### Steps to reproduce the behavior

```CS
var event = new Event {
    Subject = "graph rocks",
        Location = new Location {
            DisplayName = "Building 92, Redmond"
        },
        Start = new DateTimeTimeZone {
            DateTime = DateTime.Now.AddHours(1), Timezone = "Eastern Standard Time"
        },
        End = new DateTimeTimeZone {
            DateTime = DateTime.Now.AddHours(2), Timezone = "Eastern Standard Time"
        },
        Body = new ItemBody {
            Content = "hi", ContentType = BodyType.Html
        },
        ShowAs = FreeBusyStatus.Busy,
        Reccurence = new PatternedRecurrence {
            Range = new RecurrenceRange {
                    StartDate = new Date(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day),
                        RecurrenceTimeZone = "Eastern Standard Time"
                },
                Pattern = new RecurrencePattern {
                    Interval = 1,
                        Type = RecurrencePatternType.Daily
                }
        }
}
var newEvent = await client
    .Me
    .Events
    .Request()
    .AddAsync(event);

var updatedEvent = await client
    .Me.Events[newEvent.Id]
    .Request()
    .UpdateAsync(new Event { Recurrence = null });

updatedEvent.Recurrence; // hasn't changed
```
### Workaround
```CS
using(var httpClient = new HttpClient())
using(var message = request.GetHttpRequestMessage()) {
    message.Method = new HttpMethod("PATCH");
    message.Content = new StringContent("{'recurrence': null}", Encoding.UTF8, "application/json");
    message.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("bearer", "token");
    await httpClient.SendAsync(message);
}
```
### comment
I'm not sure if this has a bigger impact than just the recurrence pattern or if it's a global serialization issue and there should be a way to generically tag which properties should get serialized even when null on PATCH requests.  

The later would probably cause issues when people don't want to update some properties, so I think UpdateAsync should have an optional lambda parameter allowing to "tag" which properties are null but we want to send along. Something like:

```CS
await client
    .Me
    .Events["id"]
    .Request()
    .UpdateAsync(event, x => x.Recurrence);
```

 
[AB#7345](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7345)

**Comment by MIchaelMainer** [comment]
This is a known issue and does have a larger impact than disabling recurrence patterns. Having this concrete example for your scenario is helpful to us. Thank you for providing the details!
450978

**Comment by baywet** [comment]
as a follow up, here is how I worked it around while you guys figure out the solution. I thought others might be interested.
```CS
var request = client.Users[Settings.SkypeUserEmail].Events[series.SchedulingId].Request();
 using (var httpClient = new HttpClient())
                using (var message = request.GetHttpRequestMessage())
                {
                    message.Method = new HttpMethod("PATCH");
                    message.Content = new StringContent("{'recurrence': null}", Encoding.UTF8, "application/json");
                    message.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("bearer", "the token I generated and passed to the graph client");
                    await httpClient.SendAsync(message);
                }
```

**Comment by jbiversen** [comment]
What is the status on this feature request?

**Comment by MIchaelMainer** [comment]
With Core 1.x, we can use AdditionalData to set property to null. We will need to investigate how to do this with System.Text.Json in core 2.x.

**Comment by andrueastman** [comment]
Closing this one for now. With the latest kiota preview version, we have enabled the backing store which enables dirty tracking of the objects. This means that one can send null properties without using the additionData workaround as below and outlined in the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#backing-store). 

```cs
// get the object
var @event = await graphServiceClient
    .Me.Events["event-id"]
    .GetAsync();

// the backing store will keep track that the property changes and send the updated null value.
@event.Recurrence = null;// set to null 

// update the object
await graphServiceClient.Me.Events["event-id"]
    .PatchAsync(@event);
```
