### ISSUE TITLE
Readme links to several 404's

### ISSUE THREAD

**Issue by church365** [microsoftgraph/msgraph-sdk-dotnet#2654]
### Describe the bug

The link to https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md returns a 404. Several of the other associated documentation links also fail.

### Expected behavior

Expect published links to actually link to something useful and relevant.

### How to reproduce

Click the link.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Apologies for this @church365 

This is a sideffect of the branch alignement work done recently to rename the default branch to main. Authored https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/2655 to resolve this.
