### ISSUE TITLE
Info on 401 in Batch.PostAsync

### ISSUE THREAD

**Issue by adryone** [microsoftgraph/msgraph-sdk-dotnet#2660]
I'm using the Batch.PostAsync to retrieve the CalendarView in a user Calendar.

When the token provided to the API is wrong, the AddBatchRequestStepAsync return a RequestId without error, but getting the GetResponseByIdAsync on the BatchResponseContentCollection returned, on that RequestId there's null value.

Inspecting the BatchResponseContentCollection in Visual Studio (debug) I can see the StatusCode (Unauthorized), the Content, and so on; well, but these fields are "internals" in the BatchResponseCollection.

My question is: how can I retrieve these info on the response so that I can understand why there's a null value on the GetResponseByIdAsync for that RequestId? What I'm wrong?

Thanks

**Comment by andrueastman** [comment]
Thanks for raising this @adryone 

Any chance you can share a code sample of the code you are using to help us understand this better? 

Out of curiosity are you calling `GetResponseByIdAsync`  or `GetResponseByIdAsync<T>`?

**Comment by adryone** [comment]
Sure @andrueastman 

// --- Start code
var requestDic = new Dictionary<string, string>();
var batchRequestContent = new BatchRequestContentCollection(_graphClient);
foreach (var calendarId in calendarsId)
{
    var calendarViewRequest = _graphClient.Me
        .Calendars[calendarId]
        .CalendarView
        .ToGetRequestInformation(requestConfiguration =>
        {
            requestConfiguration.QueryParameters.StartDateTime = fromUtc;
            requestConfiguration.QueryParameters.EndDateTime = toUtc;
            requestConfiguration.QueryParameters.Expand = new string[] { expand };
            requestConfiguration.QueryParameters.Top = 1000;
            requestConfiguration.Headers.Add("Prefer", $"outlook.timezone=\"{TIME_ZONE}\"");
            requestConfiguration.QueryParameters.Select = new string[] {
                "Id",
                "Calendar",
                "Start",
                "End",
                "IsAllDay",
                "Subject",
                "BodyPreview",
                "SingleValueExtendedProperties",
                "WebLink",
                "Categories",
                "Attendees",
            };
            requestConfiguration.QueryParameters.Orderby = new string[] { "start/dateTime" };
        });

    var requestId = await batchRequestContent.AddBatchRequestStepAsync(calendarViewRequest);
    requestDic.Add(calendarId, requestId);
}

var returnedResponse = await _graphClient.Batch.PostAsync(batchRequestContent);

Dictionary<string, EventCollectionResponse> results = new();
foreach (var requestItem in requestDic)
{
    string calendarId = requestItem.Key;
    string requestId = requestDic[calendarId];

    var result = await returnedResponse.GetResponseByIdAsync<EventCollectionResponse>(requestId);

// --- End code

The line of code
var returnedResponse = await _graphClient.Batch.PostAsync(batchRequestContent);
goes in my MSGraphAuthProvider class (derived from IAccessTokenProvider), where I provide (for testing purpose) a wrong AccessToken.
The result is a 401 (not error raising) "inside" the returnedResponse (BatchResponseContentCollection); i see the 401 "inspecting" (debug Visual Studio) the BatchResponseContentCollection.

The line of code
var result = await returnedResponse.GetResponseByIdAsync&lt;EventCollectionResponse&gt;(requestId);
return NULL.
The NULL value is correct, becasue the (httpresponsemessage)content in the returnedResponse refer to a 401, as the following:
{"error":{"code":"InvalidAuthenticationToken","message":"IDX14310: JWE authentication tag is missing.","innerError":{"date":"2024-09-06T12:10:56","request-id":"5afb1f7f-6f9c-4663-befa-a8462d430aa0","client-request-id":"5b131f4c-332d-4dc4-9018-a080c3913fad"}}}

The issue is that I have no ways to obtain the 401, because is in internal properties.
Follows a screenshot of the returnedResponse inspection

![image](https://github.com/user-attachments/assets/4f43dbc4-bb25-40dd-a8ff-15c27808bc32)

Providing a correct AccessToken, its all OK, as the following screenshot:
![image](https://github.com/user-attachments/assets/88121790-3041-4346-a229-f2de036a8663)


Thanks

**Comment by andrueastman** [comment]
Thanks for the extra information here @adryone 

Just to confirm here, do you get an exception thrown at this line of code? 

> var returnedResponse = await _graphClient.Batch.PostAsync(batchRequestContent);


I believe the real issue here is that the code should be also be checking the reponse status code of the larger batch reponse before allowing you to call `var result = await returnedResponse.GetResponseByIdAsync<EventCollectionResponse>(requestId);`

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/6eb564892b0b417cd6b49341af77448aae65cf0e/src/Microsoft.Graph.Core/Requests/BatchRequestBuilder.cs#L61

This means that we need to validate the status code is successful once the native responseHandler gives us a response here as the nested values won't be valid either way ...

**Comment by adryone** [comment]
Hi @andrueastman,

no, the line of code
var returnedResponse = await _graphClient.Batch.PostAsync(batchRequestContent);
doesn't throw any exception (the line of code is inside a try-catch construct).

I suppose your suggestion "... validate the status code is successful..." is right; there may be various errors conditions from the PostAsync request.

Thanks

**Comment by andrueastman** [comment]
Thanks for confirming this @adryone 

I believe the postAsync should have thrown an error due to the failed status code message here. We'll be following up with a fix on this as there's a similar/related issue at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2661
