### ISSUE TITLE
Response time has increased (from v4 to v5 )while getting attachments of a particular message

### ISSUE THREAD

**Issue by hbhange** [microsoftgraph/msgraph-sdk-dotnet#2669]
### Describe the bug

with Microsoft Graph SDK 4.x, it took around 5-6 sec to get attachment of an email, now with Graph SDK 5.x, it is taking around 70 sec to get attachment of message
Graph API:

Message result = graphclient.Users[userId].MailFolders[mailFolderId].Messages.GetAsync((requestConfiguration) =>
					requestConfiguration.QueryParameter.Filter = "hasAttachments eq true";
					requestConfiguration.QueryParameter.Expand = new string[] {"attachment"};
					requestConfiguration.QueryParameter.Skip = 0;
					requestConfiguration.QueryParameter.Top = 10;
		}).Result;

### Expected behavior

Performance should be equal to or better than v4 C# GRAPH SDK

### How to reproduce

Use API in v4 and v5

Graph API:

Message result = graphclient.Users[userId].MailFolders[mailFolderId].Messages.GetAsync((requestConfiguration) =>
					requestConfiguration.QueryParameter.Filter = "hasAttachments eq true";
					requestConfiguration.QueryParameter.Expand = new string[] {"attachment"};
					requestConfiguration.QueryParameter.Skip = 0;
					requestConfiguration.QueryParameter.Top = 10;
		}).Result;

### SDK Version

5.54.0

### Latest version known to work for scenario above?

4.26.0

### Known Workarounds

NA

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Windows 22 x64

**Comment by andrueastman** [comment]
Thanks for raising this @hbhange 

Any chance you can confirm if the issue replicates with the latest package version of https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/5.58.0?

I believe version 5.54.0 was released about 4 months ago and we've made some improvements in this area such as https://github.com/microsoft/kiota-dotnet/pull/337 and https://github.com/microsoft/kiota-dotnet/pull/328
