### ISSUE TITLE
Batch Request & Azure App Service

### ISSUE THREAD

**Issue by PatrickKelley2112** [microsoftgraph/msgraph-sdk-dotnet#2681]
### Describe the bug

I have a batch request that works flawlessly when I'm debugging on IIS Express, but as soon as I publish to an Azure App Service the batch returns error 400 for every request in the batch.

The max number of user calendars I'm requesting is around 10, but it fails even if I just add 1 to the batch. I can pull individual calendars using CalendarView.GetAsync locally or on the app service so it's definitely something with the batch request.

### Expected behavior

Returns user calendar events.

### How to reproduce

```
 foreach (var user in users)
 {
     var eventRequest = graphClient.Users[user.UserPrincipalName].CalendarView
                    .ToGetRequestInformation(requestConfiguration =>
                    {
                        requestConfiguration.QueryParameters.StartDateTime = startTime.ToString();
                        requestConfiguration.QueryParameters.EndDateTime = endTime.Value.ToString();
                    });

     eventRequests.Add(await batchRequestContent.AddBatchRequestStepAsync(eventRequest, user.UserPrincipalName));

 }
 
 var returnedResponse = await graphClient.Batch.PostAsync(batchRequestContent);

List<Event> events = [];
foreach (var r in eventRequests)
{
    var response = await returnedResponse
      .GetResponseByIdAsync<EventCollectionResponse>(r);

    var pageIterator = PageIterator<Event, EventCollectionResponse>
   .CreatePageIterator(graphClient, response, (evt) =>
   {
       events.Add(new Event(evt));
       return true;
   });

    await pageIterator.IterateAsync();
}


return events;
```

### SDK Version

5.58

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @PatrickKelley2112 

Any chance you are able to share the details of the 400 response message you receive?

I believe the code below should throw an error/exception if the response is 400 that could be handled as shown in the doc 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/main/docs/errors.md
```
    var response = await returnedResponse
      .GetResponseByIdAsync<EventCollectionResponse>(r);
```

**Comment by PatrickKelley2112** [comment]
It's not throwing an exception. I can only see what's happening by running returnedResponse.GetResponsesStatusCodesAsync(), and that only shows me that it's returning error 400 but no information about why.

Is there a way to see the data that is sent using graphClient.Batch.PostAsync(batchRequestContent)? If so, I can compare that data between the local client and the Azure app service.

**Comment by andrueastman** [comment]
@PatrickKelley2112 

I believe you can read the response content for the individual reponse as below

```cs
            HttpResponseMessage response = await returnedResponse.GetResponseByIdAsync("2");

            var responseBodyString = await response.Content.ReadAsStringAsync(); 
```

Also, could you add a reference to https://www.nuget.org/packages/Microsoft.Graph.Core/3.1.22 as well to validate this was not resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/916
