### ISSUE TITLE
"Unable To Find Target Address" when creating community in an application registration context using [POST]/employeeExperience/communities

### ISSUE THREAD

**Issue by vincent-preuvot** [microsoftgraph/msgraph-sdk-dotnet#2697]
### Describe the bug

I've performed some test on the recently released GRAPH endpoint [/employeeExperience/communities](https://learn.microsoft.com/en-us/graph/api/employeeexperience-post-communities?view=graph-rest-beta&tabs=http).

Communities creations using delegated or direct account permissions are working fine (tested via GRAPH explorer) :

![Capture d'écran 2024-10-02 075738](https://github.com/user-attachments/assets/3e650586-0fa5-44f9-9c3f-752aa3f42dad)

But when i try to create a community using an authentication done via Application Registration + Certificate, i have the following error :

![Capture d'écran 2024-10-02 075949](https://github.com/user-attachments/assets/2101bd40-378f-444b-b05d-8d8886a7aba9)

Here is the full code of the method :

![Capture d'écran 2024-10-03 141134](https://github.com/user-attachments/assets/b3a8f746-1303-4773-bec7-bfa1c92c3305)

Remark : i'm not using the last version of the C# graph library since i have in my project a dependency to PnP.PowerShell wich is not compatible with the 5.x versions of the graph library (even if PnP.PowerShell should support versions of graph >= 3.33). That's why i do "raw" http requests to this graph endpoint.

### Expected behavior

The community should be created with the specified owner

### How to reproduce

Call the [POST]/employeeExperience/communities GRAPH API to create a community with specific owner(s) using a context/authentication done through Application Registration.

### SDK Version

3.33.0 (also tested with last version)

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @vincent-preuvot 

To help narrow things down, with the example at the link below, are you able to capture the error information of the request with the latest version of the SDK? 
https://learn.microsoft.com/en-us/graph/api/employeeexperience-post-communities?view=graph-rest-1.0&tabs=csharp#example-2-application-permissions

Are you able to capture the RequestId and ClientRequestId properties of the nested error object? 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/main/docs/errors.md

**Comment by vincent-preuvot** [comment]
Hi @andrueastman and thank you for your answer.

During my tests i tried with the latest SDK and i had the same issue.

I relaunched my code this morning and it works without changing anything ... do you know if there was a recent update on the GRAPH API endpoints ?

**Comment by andrueastman** [comment]
> I relaunched my code this morning and it works without changing anything ... do you know if there was a recent update on the GRAPH API endpoints ?

I can't say for sure TBH. I'm not sure if there's something that changed from the API side.

If its okay, we can close this one and you can re-open incase this happens/re-occurs?
