### ISSUE TITLE
Setting the segment for deletedItems

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#271]
SDK version 1.9 supports [List deleted items](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/directory_deleteditems_list) via `graphClient.Directory.DeletedItems.Request()`. 

However, what is not supported is setting the segment as per the documentation, eg

``` http
https://graph.microsoft.com/v1.0/directory/deleteditems/microsoft.graph.group
```

777660

**Comment by darrelmiller** [comment]
@christophwille Yes, the AppendSegmentToRequestUrl method was added to BaseRequest so that you can add arbitrary segments to the end of a RequestURL.

**Comment by MIchaelMainer** [comment]
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.10.0 adds arbitrary segment append support.
