### ISSUE TITLE
Proxy in TokenCredentialOptions.Transport not being used

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/msgraph-sdk-dotnet#2714]
### Describe the bug

I recently ran into [this issue with Token requests not going through the proxy](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2032). I was using the same code, with one exception: Instead of providing an instance of ` ClientSecretCredentialOptions` to the `ClientSecretCredential`, I had a `TokenCredentialOptions` instance. 

I was then getting a timeout every time I was trying to access any API method on a machine that only allowed internet access through a proxy - it was the login that was timing out. `Netstat -a` showed that a connection was attempted directly to login.microsoftonline.com, instead of through the proxy.

Because the code at first glance looked just like the code in the linked issue, I didn't even register that I was doing something different. It seems weird to me that `TokenCredentialOptions` has the same Transport property, but in that case, the proxy config is not heeded.

### Expected behavior

I would have expected the request to get the token to also pass through the proxy I provided.

### How to reproduce

Instantiate the GraphServiceClient as follows:

var proxy = GetWebProxy();
var handler = new HttpClientHandler
{
    Proxy = proxy,
    UseProxy = proxy != null
};
var options = new TokenCredentialOptions 
{
  AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
  Transport = new HttpClientTransport(handler)
};
var credential = new ClientSecretCredential(config.TenantId, config.ClientId, config.ClientSecret, options);
var httpClient = GraphClientFactory.Create(proxy: proxy);
graphServiceClient = new GraphServiceClient(httpClient, new Microsoft.Kiota.Authentication.Azure.AzureIdentityAuthenticationProvider(credential));

### SDK Version

5.60.0

### Known Workarounds

if I define `options` in the code above as follows, things work out just fine

var options = new ClientSecretCredentialOptions
{
    Transport = new HttpClientTransport(handler)
};

### Configuration

OS: Win11 Pro 23H2 64bit on .NET 8.0.10

**Comment by andrueastman** [comment]
Thanks for raising this @ssteiner 

The `ClientSecretCredentialOptions` and the `TokenCredentialOptions` are unfortunately not part of this library. But part of the Azure.Identity library.

Any chance you can create the issue at the link below so that the library authors can take a look into this? You may need to include the version of the `Azure.Identity` you are using as well. 

https://github.com/Azure/azure-sdk-for-net/issues/new

**Comment by ssteiner** [comment]
I refiled the issue [in the Azure SDK Repo](https://github.com/Azure/azure-sdk-for-net/issues/46731).
