### ISSUE TITLE
Graph - Semantic Label iconUrl is registered as unknownFutureValue

### ISSUE THREAD

**Issue by bosteelsd** [microsoftgraph/msgraph-sdk-dotnet#2716]
### Describe the bug

I am trying to set a schema for our custom external connector in Microsoft Graph but the semantic label iconUrl (which is required for information to be available to copilot) is registered as unknownFutureValue.
![2024-10-17_09-50-49](https://github.com/user-attachments/assets/c18216b0-f5e9-4036-9ca2-1cd0f43dcfb7)
![image](https://github.com/user-attachments/assets/c9f0340d-6f22-48cb-9ba5-fca59a5851c8)

### Expected behavior

the Label setup in code (iconUrl) should be the one that is in the schema afterwards.

### How to reproduce

Create an externalConnection, and register a schema with the label iconUrl.
When you check the schema (for example with the graph api), the semantic label iconUrl will be registered as unknownFutureValue.

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by MartinM85** [comment]
You need to add the request header `prefer:include-unknown-enum-members`

Check description of the `labels` property

https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-1.0#properties

**Comment by bosteelsd** [comment]
If you know how much time I spent on the documentation and never went on that page...
Thanks for the answer !
