### ISSUE TITLE
schemaExtension paging is not working. It always returns with "The continuation token specified in the request is malformed." error.

### ISSUE THREAD

**Issue by bajzat** [microsoftgraph/msgraph-sdk-dotnet#272]
HI,

I'm currently trying to use the schemaExtensions in my project but I'm facing a really strange issue. The paging is not working for schemaExtensions, I've tested the paging functionality on other resources(like  
Users) and they are working as expected.

Thanks,

Tamas

### Expected behavior

The API should accept the link which is in the "@odata.nextLink" part of the response and returns the next X elements.

https://developer.microsoft.com/en-us/graph/docs/concepts/paging

### Actual behavior

If I try to use the nextLink to query schemaExtensions then the API always return with the following error: 
        
"code": "InternalServerError",
        "message": "Message: {\"Errors\":[\"The continuation token specified in the request is malformed. Please re-run the query without it and iterate.\"]}\r\nActivityId: 7dd096e6-4800-4492-a8f9-78ec6f40f51a, Request URI: rntbd://sn4prdddc07-docdb-1.documents.azure.com:14108/apps/3967e85b-4707-48a6-b107-5bff0707b450/services/8b5418e9-b3aa-45c3-8360-6fd93e350e2c/partitions/4a27b929-2dcd-40bf-a03f-c8cd457bb30a/replicas/131721422507549173s/",

### Steps to reproduce the behaviour
In Visual Studio

```cs
            List<SchemaExtension> result = new List<SchemaExtension>();
            var pageReq = Client.SchemaExtensions.Request().Top(5);
            IGraphServiceSchemaExtensionsCollectionPage pages = await pageReq.GetAsync();

            result.AddRange(pages);

            while(pages.NextPageRequest != null)
            {
                pages = await pages.NextPageRequest.GetAsync();
                result.AddRange(pages);
            }
```

In postman: 

1. Get the first five extensions https://graph.microsoft.com/v1.0/schemaExtensions?$top=5
2. Try to get the next five with the skiptoken like: "https://graph.microsoft.com/v1.0/schemaExtensions?$top=5&$skiptoken=%7b%22token%22%3a%22+RID%3aF7weAMEoXABYAAAAAAAAAA%3d%3d%23RT%3a1%23TRC%3a5%23FPC%3aAgEAAABsAFiABoAAgAvADsADAABAEAzgBwACgDCAOQIAiCJBCBaAEgATAGAIEQAMyhSAGIAHgA7AXAECgAEAQgAEJAAAUgKAAAAABCkBQAAQIQZlACUACCEQAAOAQYCAhBgAUAgC7IMqEADwNgBBAQRAAQ%3d%3d%22%2c%22range%22%3a%7b%22min%22%3a%22%22%2c%22max%22%3a%22FF%22%7d%7d"

**Comment by MIchaelMainer** [comment]
Thank you for reporting this. I've got a question out about this. I'll report back when I have more info.

**Comment by bajzat** [comment]
I just would like to inquire about this case. Do you have any update?

**Comment by MIchaelMainer** [comment]
@bajzat Let me check again.

**Comment by MIchaelMainer** [comment]
@bajzat An investigation is under way. In the meantime, to mitigate this issue, can you remove the top=5 or set it to 999? Would this mitigate your scenario?

**Comment by peombwa** [comment]
Please reopen if you are still experiencing this issue.
