### ISSUE TITLE
chat subscription not working

### ISSUE THREAD

**Issue by j40903272** [microsoftgraph/msgraph-sdk-dotnet#2766]
### Describe the bug

I followed this document https://learn.microsoft.com/en-us/graph/teams-changenotifications-chatmessage#subscribe-to-changes-at-the-user-level

and created a subscription with '/users/{user-id}/chats/getAllMessages' as resource. The subscription is created successfully and and can see it with a running status and a valid expiration date. However, i cannot recieve notification when new chat message arrives. I can recieve one message once in a while (several hours) but most of the notification did not send to me.

### Expected behavior

I can receive all message notifications that are send to a user.

### How to reproduce

I followed this document https://learn.microsoft.com/en-us/graph/teams-changenotifications-chatmessage#subscribe-to-changes-at-the-user-level

and created a subscription with '/users/{user-id}/chats/getAllMessages' as resource. The subscription is created successfully and and can see it with a running status and a valid expiration date. However, i cannot recieve notification when new chat message arrives. I can recieve one message once in a while (several hours) but most of the notification did not send to me.

### SDK Version

4.54.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by andrueastman** [comment]
Thanks for raising this @j40903272 

Any chance you can post the same question at the link below to see if there may be feedback on this issue from the API owners? As this repo is mainly intended for issues with the C# SDK, we may not be best placed to answer if the missing notifications are due to something happening on the back end.

https://aka.ms/askGraph
