### ISSUE TITLE
IMessageRequestBuilder.ReplyAll does not take Message type parameter

### ISSUE THREAD

**Issue by davidshen84** [microsoftgraph/msgraph-sdk-dotnet#278]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

`Microsoft.Graph.IMessageRequestBuilder.ReplyAll` should be able to take a parameter of `Message` type, which is documented at [here][1]

[1]: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/message_replyall

### Actual behavior

`Microsoft.Graph.IMessageRequestBuilder.ReplyAll` only takes a **string** parameter.

### Steps to reproduce the behavior

Review the code at [here][2]

[2]: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/3ce3546551033a302655acd1c37fff24c183fd7b/src/Microsoft.Graph/Requests/Generated/MessageRequestBuilder.cs#L176

**Comment by MIchaelMainer** [comment]
Thank you for bring this to our attention. You are correct, it should take a message and comment. Our metadata description for this action is incorrect.

Actual
```
<Action Name="replyAll" IsBound="true">
<Parameter Name="bindingParameter" Type="microsoft.graph.message"/>
<Parameter Name="Comment" Type="Edm.String" Unicode="false"/>
</Action>
```

Expected
```
<Action Name="replyAll" IsBound="true">
<Parameter Name="bindingParameter" Type="microsoft.graph.message"/>
<Parameter Name="Message" Type="microsoft.graph.message"/>
<Parameter Name="Comment" Type="Edm.String" Unicode="false"/>
</Action>
```

**Comment by davidshen84** [comment]
Similar issues exist in other *Reply* methods as well.

In addition, I found `Microsoft.Graph.MessageReplyAllRequestBuilder`'s constructor **only** takes *Comment* as a string, and it has no override that can take a `Message` type parameter. I think the `MessageReplyAllRequestBuilder` class and other related classes need update as well.

**Comment by darrelmiller** [comment]
@davidshen84 Unfortunately the documentation that you referenced is in the Microsoft Graph beta endpoint.  Currently the .NET SDK only supports the [V1.0 endpoint](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_replyall).  We are working towards being able to generate an SDK for beta endpoints also, but currently it is not available.
