### ISSUE TITLE
Updating a user fails sometimes

### ISSUE THREAD

**Issue by StuartMeeks** [microsoftgraph/msgraph-sdk-dotnet#28]
Please see [http://stackoverflow.com/questions/38321069/json-serialization-error-when-updating-user-in-azure-ad-via-graph](http://stackoverflow.com/questions/38321069/json-serialization-error-when-updating-user-in-azure-ad-via-graph)

For some specific users,
`await graphServiceClient.Users[user.UserPrincipalName].Request().UpdateAsync(user);`
fails with JSON response:
```
{
  "error": {
    "code": "InternalServerError",
    "message": "Can not add property department to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.",
    "innerError": {
      "request-id": "b82c4098-6031-40c4-ac6a-4f43746e7b48",
      "date": "2016-07-12T05:55:08"
    }
  }
}
```

**Comment by shiftylogic** [comment]
Can you attempt this same operation on the failing user using the [Graph Explorer](https://graph.microsoft.io/en-us/graph-explorer)? I'd likely to isolate the SDKs out of the picture to see if the problem still exists.

Thanks!

**Comment by StuartMeeks** [comment]
I attempted the same operation using Graph Explorer using the requests extracted from Fiddler when using the SDK. They failed in Graph Explorer with the same error.

Upon further inspection, I can see the JSON from the SDK has some duplicate keys. I have attached a good request/response and a bad request/reponse. I've also cleansed some of the values but left the JSON schema intact.

If I remove the errant duplicate keys from the JSON payload, the request executes as expected in Graph Explorer.
[SuccessfulRequest.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/360634/SuccessfulRequest.txt)
[FailedRequest.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/360635/FailedRequest.txt)

**Comment by shiftylogic** [comment]
Can you send a full fiddler trace for a good and bad user? If you want to keep it private, send me a private email (robert dot anderson at Microsoft dot com).

I haven't yet been able to reproduce this.

**Comment by StuartMeeks** [comment]
Hi shiftylogic. I've been away the last few days. I hope to get some time tomorrow to repro the issue and I'll send through the trace. Thanks!

**Comment by StuartMeeks** [comment]
Hi Robert, I have emailed the Fiddler trace to you as requested.

**Comment by StuartMeeks** [comment]
Hi Robert, I have identified a common theme amongst the users that won't update. They were created with a PowerShell script. I have emailed you with the script. Thanks!

**Comment by shiftylogic** [comment]
This bug is a result of how we are de-serializing objects into their model classes. When a <null> value is returned in the JSON payload, the de-serializer does not touch the correct property on the model but instead injects that value into the AdditionalData dictionary. As a result, when the object is serialized again on the update call, the resulting JSON text contains duplicate entries (one being the null value).

The fix for this bug will be released with the next SDK update.

**Comment by NelsonLamprecht** [comment]
Hit this same thing today. Does this problem happen using the standard httpclient and issuing a patch? (going to find out today...)

**Comment by NelsonLamprecht** [comment]
Answering my own question...the problem does not appear to happen if you control the serialization when sending the patch:

            var objectToSend = JsonConvert.SerializeObject(value, Formatting.None, new JsonSerializerSettings {NullValueHandling = NullValueHandling.Ignore});
            return objectToSend;

**Comment by MIchaelMainer** [comment]
This has been fixed. This is currently available in master branch and will be available in Nuget package 1.2.0

**Comment by NelsonLamprecht** [comment]
When is the 1.2.0 package predicted in being available?

**Comment by MIchaelMainer** [comment]
We've updated the client library. We will release a Microsoft.Graph 1.1.1 and Microsoft.Graph.Core 1.2.1 today.
