### ISSUE TITLE
Use custom HttpMessageHandler with HttpProvider

### ISSUE THREAD

**Issue by dominik-weber** [microsoftgraph/msgraph-sdk-dotnet#285]
Hi there,

why does the public constructor of HttpProvider require `HttpClientHandler `instead of `HttpMessageHandler`? I wasn't able to find any reference in the source code except for this constructor.
Please note that on iOS we use the NSUrlSessionHandler, which does not derive from HttpClientHandler but from HttpMessageHandler directly (see https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSUrlSessionHandler.cs).

Thank you!

**Comment by darrelmiller** [comment]
@dominik-weber It should be HttpMessageHandler.  There is another internal method that accepts HttpMessageHandler.  We are reviewing the impact of exposing that method, but I believe it should be made public.

**Comment by dominik-weber** [comment]
@darrelmiller this is not included in the 1.10.0 release, right?

**Comment by darrelmiller** [comment]
@dominik-weber Correct.  It will only make it into our next release, which is likely a couple of weeks away.
