### ISSUE TITLE
API Surface Changes Question for /dev Branch

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#29]
Samples taken from 

https://github.com/OfficeDev/PnP/tree/dev/Samples/MicrosoftGraph.Office365.DotNetSDK

eg

            var filteredUsers = await graphClient.Users.Request()
                .Select("DisplayName,UserPrincipalName,Mail")
                .Filter("department eq 'IT'")
                .GetAsync();

Neither .Select nor .Filter are there (applies to Groups & a couple more). Are these not here temporarily or is that related to the a change in the API surface? (I saw a commit message) Or am I missing something blatantly obvious?

**Comment by shiftylogic** [comment]
There is currently an issue with the way annotations are being processed. There is a fix coming in VIPR that will resolve this issue.
