### ISSUE TITLE
Checking membership of a user in a group throws exception when member is not in the group

### ISSUE THREAD

**Issue by twsouthwick** [microsoftgraph/msgraph-sdk-dotnet#290]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

An empty list.

See https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_memberof

### Actual behavior

Throws a `ServiceException` with `StatusCode==HttpStatusCode.NotFound`

### Steps to reproduce the behavior

Using VS 2017, SDK v1.10.0

```csharp
IGraphServiceClient client = /* appropriate setup */;

var query = client.Users[userId].MemberOf.Request().Filter($"id eq '{groupId}'");

try
{
  var result = await query.GetAsync();
  return true;
}
catch (ServiceException e) when (e.StatusCode == HttpStatusCode.NotFound)
{
  return false;
}
```

I would expect `result` to be an empty list if no group members were found, but it throws an exception. This is problematic because it is a common use case for someone not to be a member of a group, but exception handling is an order of magnitude slower than simply returning values. I attempted to hook into the `client.HttpProvider.SendAsync` to manually handle the error code, but it appears to be handled before that returns.

I would like to some sort of API to handle these errors so it either:

1) Returns an empty list
2) By default throws, but the error handling logic can be overridden

I'm happy to submit a PR to enable this if someone can let me know which option is preferred, and if there is an ideal location to put it.

**Comment by MIchaelMainer** [comment]
I agree, this is not optimal at all. The service is returning a 404 when the filter doesn't have a match.

```
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource '60ea65d4-ca13-493d-8db8-94ce164cb55a' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "request-id": "0b249643-3fd2-4889-a507-3b27fe22e94b",
            "date": "2018-08-06T17:44:30"
        }
    }
}
```

Out client library handles all 4xx errors as ServiceExceptions. You'll need to make this call outside of the client library to make. Here's an [example ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md#send-http-requests-with-the-net-microsoft-graph-client-library)you may want to consider.

**Comment by twsouthwick** [comment]
This works, although not ideals. I can keep this issue open to track adding handlers for these scenarios, or it cn be closed.

**Comment by MIchaelMainer** [comment]
@twsouthwick Here's where we are discussing how we may add the middleware. Take a look and provide your thoughts. 
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md
