### ISSUE TITLE
Unknown Error while generating a sharing link for one-drive for business

### ISSUE THREAD

**Issue by rahchau** [microsoftgraph/msgraph-sdk-dotnet#293]
**Issue**: We are using Microsoft.Graph ver. 1.10.0 in Xamarin Forms PCL and same version in iOS and Android platforms but while creating sharing link or sending invitation, graph APIs are throwing an unknown error.

**Code snippet causing a problem** - Permission permission = await graphClient.Me.Drive.Items[id].CreateLink("view").Request().PostAsync();

var invite = graphClient.Me.Drive.Items[id].Invite(recipients, true, new List() { "write", "read" }, true, $"Inviation from {sender}");
var permissions = await invite.Request().PostAsync();

**Comment by MIchaelMainer** [comment]
Can you show us the error? Does the request get sent? Can you capture the request and response and share it with us?

**Comment by MIchaelMainer** [comment]
Please reopen this if you still encounter this issue.
