### ISSUE TITLE
Unable to update birthday or hireDate property using C# SDK

### ISSUE THREAD

**Issue by trevonmckay** [microsoftgraph/msgraph-sdk-dotnet#296]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
The **birthday** and **hireDate** property are updated to the specified values per the documentation at https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_update

### Actual behavior
A ServiceException occurs with the following message

> Code: -1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException
> Message: Attempted to perform an unauthorized operation.
> Response headers: {Cache-Control: private
Transfer-Encoding: chunked
request-id: 1db2c8eb-f278-4ea8-b4b4-2676e31f753e
client-request-id: 1db2c8eb-f278-4ea8-b4b4-2676e31f753e
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"003","Host":"AGSFE_IN_21","ADSiteName":"EUS"}}
Duration: 316.5214
Strict-Transport-Security: max-age=31536000
Date: Mon, 10 Sep 2018 13:33:54 GMT
}
> ### HTTP Request RAW 
> PATCH https://graph.microsoft.com/beta/users/_removed_ HTTP/1.1
SdkVersion: Graph-dotnet-1.10.0
Authorization: Bearer _removed_
Cache-Control: no-store, no-cache
Request-Context: appId=cid-v1:29b7ab5f-5ccc-4bf3-b79d-b65876a3afce
Request-Id: |JATG8TgkLxk=.9e51a323_423.
Content-Type: application/json
Content-Length: 79
Host: graph.microsoft.com
> 
> {"birthday":"1995-07-30T04:00:00+00:00","hireDate":"2018-08-20T04:00:00+00:00"}

### Steps to reproduce the behavior
Make an authenticated UpdateAsync request against a user object using Visual Studio 15.8.0 Preview 5 and Microsoft Graph 1.10.0 .NET SDK

```
var patchValues = new Microsoft.Graph.User()
{
   Birthday = userRequest.Birthday.Value.ToUniversalTime(),
   HireDate = userRequest.HireDate.Value.ToUniversalTime()
};
var request = _graphClient.Users[graphUser.Id].Request();
await request.UpdateAsync(patchValues);
```

**Comment by trevonmckay** [comment]
Based on the request values and my seperate testing using the Graph Explorer the issue appears to be with the formatting of the date. The Graph Explorer accepted the request when the date was formatted as 1995-07-30T04:00:00Z whereas the Graph SDK client sends the request value as "1995-07-30T04:00:00+00:00"

**Comment by vikyding** [comment]
@trevonmckay Hi, thanks for bringing this issue to us. Both formattings should work on Graph SDK. I agree with Michael, it seems that the serializer isn't correctly handling the edm.dateTimeOffset. Would you be able to check that or give us more info for that? Thanks.

**Comment by vikyding** [comment]
@trevonmckay Btw, I saw the error message is "Attempted to perform an unauthorized operation". May I know do you set a right scope?

**Comment by vikyding** [comment]
@trevonmckay Hi, may I know how is going with this problem? Do you solve it or would you need more help from us?

**Comment by trevonmckay** [comment]
@vikyding the problem is still occurring. According to the documentation my app requires the following permissions to update those properties User.ReadWrite.All, Directory.ReadWrite.All which I have enabled and granted for the application 
![image](https://user-images.githubusercontent.com/18320804/45760475-29a89e00-bbf8-11e8-9113-3cbc0396ff26.png)

**Comment by trevonmckay** [comment]
@vikyding what exactly do you need from me regarding the serializer?

**Comment by vikyding** [comment]
@trevonmckay Thank you for offering them. Could you try to decode the accessToken to check if it includes both of User.ReadWrite.All and Directory.ReadWrite.All permissions? And may I know where do you create the application, is on the Azure portal or  Microsoft App Registration Portal? For serializer do you use custom serializer for graph client?

**Comment by trevonmckay** [comment]
@vikyding I will work on the decoding and provide an update. The application was created in the Azure Portal and I'm using the Graph client for serialization, nothing custom.

**Comment by trevonmckay** [comment]
@vikyding the decoded token returns 

> {
  "aud": "https://graph.microsoft.com/",
  "iss": "https://sts.windows.net/.../",
  "iat": 1537912760,
  "nbf": 1537912760,
  "exp": 1537916660,
  "aio": "...",
  "app_displayname": "...",
  "appid": "...",
  "appidacr": "1",
  "e_exp": 262800,
  "idp": "https://sts.windows.net/.../",
  "oid": "...",
  "roles": [
    "User.ReadWrite.All",
    "Group.Read.All",
    "Directory.ReadWrite.All",
    "Contacts.ReadWrite",
    "Group.ReadWrite.All",
    "User.Invite.All",
    "User.Read.All",
    "Calendars.ReadWrite",
    "MailboxSettings.ReadWrite",
    "Member.Read.Hidden"
  ],
  "sub": "...",
  "tid": "...",
  "uti": "T8vKJ-F0iE2YmEYjOTWWAA",
  "ver": "1.0",
  "xms_tcdt": "1501520181"
}

@MIchaelMainer this is an application making the call, specifically an Azure function that runs daily

**Comment by MIchaelMainer** [comment]
Have you attempted any other calls? If so, which ones and are they successful? 

Going back to the raw response, that code: Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException is not in an expected form. This may be a service issue.

**Comment by trevonmckay** [comment]
@MIchaelMainer yes, this app is responsible for synchronizing our employees from our HR system to Azure AD. We've been able to successfully create, update and disable ~30K accounts daily, it's only been the birthDate and hireDate properties that have given us trouble to date.

**Comment by MIchaelMainer** [comment]
@trevonmckay Does this happen with all requests to PATCH these two proprerties? Does this also occur when you POST a new user with these properties?

@dkershaw10 PATCHing https://graph.microsoft.com/beta/users/{id} birthday and hire date is returning a error code: Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException, which is not in the expected form. Can you investigate this as a service issue when updating a user?

**Comment by MIchaelMainer** [comment]
Strange. I'm sorry as I'm not going to be able to help fix this situation. I'll raise this issue to service owners. Many of those folks are at the Ignite conference so I'm expecting delayed responses. I'll keep you abreast of anything I hear offline, and I ask that you update this issue with anything you find.

**Comment by trevonmckay** [comment]
Thanks @MIchaelMainer. I'm at Ignite as well so I'll stop by their booth and bring this up.

**Comment by trevonmckay** [comment]
Hi @MIchaelMainer, l'm looking for an update on this issue. Are service bugs tracked here or somewhere else?

**Comment by nlakamsany** [comment]
The problem appears in flow too with delegated permissions. I haven't tried with others. In graph api, if I call just hire data and Birthday, everything works. If I add more parameters to PATCH in Graph api, it fails.

**Comment by agaonkar-cleo** [comment]
Even I am facing same issue.
{
  "error": {
    "code": "-1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException",
    "message": "Attempted to perform an unauthorized operation.",
    "innerError": {
      "request-id": "0fe9e7f6-da6a-4ac9-9ae1-296db3657eb8",
      "date": "2019-10-03T12:31:08"
    }
  }
}

Any solution for this please.

**Comment by nlakamsany** [comment]
This affects Powershell and MS flow too.

**Comment by agaonkar-cleo** [comment]
Any solution for this issue. I am also facing same error wherein I am not able to update the hireDate, birthday of an user. I get some SharePoint exception. Any pointers will be highly appreciated.

**Comment by jeff-knurek** [comment]
Based on the other feedback here, I seem to have the same issue.

When making a PATCH request via https://developer.microsoft.com/en-us/graph/graph-explorer to update the Birthday, there is no problem, and the birthday is updated.
`https://graph.microsoft.com/v1.0/users/{USER_ID}`
```
{"birthday":"1900-01-22T00:00:00Z"}
```

However when making the same PATCH request via the API from an App, I get the error:
```
{
  "error": {
    "code": "-1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException",
    "message": "Attempted to perform an unauthorized operation.",
    "innerError": {
      "request-id": "06067e00-06ba-45e5-aadf-47b9ed8aea59",
      "date": "2020-01-15T12:39:05"
    }
  }
}
```
The token my app uses has the following roles configured:
```
{
  "aud": "https://graph.microsoft.com",
  "app_displayname": "my-test-app",
  "appid": "12345",
  "roles": [
    "User.ReadWrite.All",
    "Directory.ReadWrite.All"
  ],
  "ver": "1.0",
}
```

------
there's other StackOverflow questions with the same problem and no solution:
* https://stackoverflow.com/a/57693598
* https://stackoverflow.com/q/52263490

**Comment by emilkhamitov** [comment]
Same here. Can't update birthday and hireDate via Graph SDK. 

Code: BadRequest
Message: The request is currently not supported on the targeted entity set
Inner error:
	AdditionalData:
	request-id: f3e71b20-b242-4c4e-bc99-df8b54f42850
	date: 2020-02-20T11:09:06
ClientRequestId: f3e71b20-b242-4c4e-bc99-df8b54f42850

**Comment by jeff-knurek** [comment]
@darrelmiller  @MIchaelMainer  @peombwa  
Is there anything that can be done externally to move this issue along?

**Comment by San-Jeevan** [comment]
this is not solved as of today. we are unable to update user properties!

**Comment by nlakamsany** [comment]
Its been 572 days since this issue has been acknowledged and opened by Microsoft.

**Comment by jsiegmund** [comment]
I seem to be having the same issue trying to update the `Skills` property of a user. Following this issue.

**Comment by MIchaelMainer** [comment]
Anyone that sees this issue, or finds other user properties that cannot be updated with app only context, please vote on the following user voice:

[Add support for additional user properties update with app only context](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35395435-bug-unable-to-update-birthday-or-hiredate-using-g)

Documentation update addressed by https://github.com/microsoftgraph/microsoft-graph-docs/pull/8461.

Closing as this is now a feature request for the service API and there isn't an action for the client SDK.

**Comment by tfrancois** [comment]
Simply unacceptable.
