### ISSUE TITLE
Why are the search results from Microsoft Graph APIs (OneDrive Search driveItem.search) and Sharepoint Online Web different?

### ISSUE THREAD

**Issue by huaminhquang** [microsoftgraph/msgraph-sdk-dotnet#297]
Hi all,

We are using Microsoft Graph APIs (driveItem.search) to search the files those user can access on Sharepoint Online. But when we open the Sharepoint Online site and search at that site, the search's result from Sharepoint Online site and the search's result from API return is different. Example:

The keyword that we are testing is "safety access" (including parenthesis)
Here is the result from Sharepoint Online site:
![screen shot 2018-09-13 at 1 21 33 pm](https://user-images.githubusercontent.com/5069797/45470469-0ee9ab80-b758-11e8-811e-7f4e2dfec49e.png)

Here is the result from APIs: 
<img width="1104" alt="screen shot 2018-09-12 at 9 58 39 am" src="https://user-images.githubusercontent.com/5069797/45399735-6bbf6600-b673-11e8-8b0a-a0ec82fbe706.png">

Can anyone tell me why is it different like that?

**Comment by huaminhquang** [comment]
Hello,

Do we have any update on this issue?

**Comment by MIchaelMainer** [comment]
I suggest that you post this question to StackOverflow with the microsoft-graph, OneDrive, and SharePoint tags. We don't have an answer for you.

**Comment by darrelmiller** [comment]
I suspect the difference is related to the fact that in the first query, "access" is spelled incorrectly.
