### ISSUE TITLE
Fields not populated in search API response even after specifying them with $select

### ISSUE THREAD

**Issue by kdhindsa** [microsoftgraph/msgraph-sdk-dotnet#303]
I am calling Graph API via .NET SDK like so:

```
var searchResult = graphClient
                .Drives["my-drive-id"]
                .Search("some search query")
                .Request(searchOptions)
                .GetAsync()
                .GetAwaiter()
                .GetResult();
```

`searchOptions` is a list of optional parameters I am passing in:

```
List<QueryOption> searchOptions = new List<QueryOption>();
            searchOptions.Add(new QueryOption("$select", "name,id,createdBy,file"));
            searchOptions.Add(new QueryOption("$top", "1000"));
```

The search result is returning a few items, but only their "name" and "id" fields are populated. Everything else is null. For e.g., "createdBy" and "file" fields are not set.

This used to work a few weeks ago and I haven't made any changes to it since then.

Platform details:
.NET, Windows 10, Visual Studio Enterprise 2017
Microsoft.Graph version: 1.9.0
Microsoft.Graph.Core version 1.9.0

The expected behavior is fields that are included in $select parameter, should be populated. 
[AB#7346](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7346)

**Comment by MIchaelMainer** [comment]
Thank you for letting us know. I'll pass it on as a service issue. @dkershaw10 Can you find someone to investigate this?

**Comment by kdhindsa** [comment]
Hello, any update on this? The issue still persists. Any idea when this will be worked on?

Thank you

**Comment by MIchaelMainer** [comment]
@ificator Drive search behavior has been reported as changed. Do you have more info on this?

**Comment by ificator** [comment]
I'm not aware of any change that would account for this - is it possible to get a the value of the `request-id` and `date` headers of the response?

**Comment by MIchaelMainer** [comment]
Please reopen if this issue persists.
