### ISSUE TITLE
Upload large file got invalidRequest with personal account

### ISSUE THREAD

**Issue by zsybupt** [microsoftgraph/msgraph-sdk-dotnet#305]
### Expected behavior
Upload large file to personal OneDrive

### Actual behavior
upload small file to personal account is ok when use:
`await client.Drives[driveId].Items[driveItemId].Content.Request().PutAsync<DriveItem>(stream).ConfigureAwait(false);`
but when upload a large file to personal OneDrive account, it shows:
**Microsoft.Graph.ServiceException: Code: invalidRequest
Message: File name not provided in url**
`   var uploadSession = await client.Drives[driveId].Items[driveItemId].CreateUploadSession().Request().PostAsync();`

but it is ok with business account, it is not work with large file of personal account,
and I found a same issue here: [61](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/61#issuecomment-358282608)

### Steps to reproduce the behavior
Upload large file to a personal account

**Comment by MIchaelMainer** [comment]
@zsybupt That linked issue has many issues reported in it. You will need to be more specific so we can help you.
* What issue are you experiencing?
* What version of the client library are you using? I know that we were sending an unexpected header in an earlier version of the client that was causing personal OneDrive large file upload to fail.
* Please provide the repro information that should include at a minimum:
---------- Error codes
---------- Your code that resulted in the error
---------- What you've tried

**Comment by zsybupt** [comment]
@MIchaelMainer 
The link is to pratik-c‘s comment on issue 61:

POST /v1.0/drives/{drive-id}/items/{item-id}/createUploadSession
Authorization: bearer <token>
Content-Type: application/json

without any body

_Originally posted by @pratik-c in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/61#issuecomment-358282608_

### Issue
Can not upload large file to personal account OneDrive

### SDK Version
1.8.1

### ErrorCode
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: File name not provided in url

### Code of Upload large file
it is very simple:
```cs   
 var graphSrvClient = new GraphServiceClient(baseUrl, new UserTokenProvider(token), httpProvider);
 var uploadSession = await graphSrvClient.Drives[driveId].Items[driveItemId].CreateUploadSession().Request().PostAsync();
 var provider = new ChunkedUploadProvider(uploadSession, graphSrvClient, (MultiBufferMemoryStream)stream);
 return await provider.UploadAsync(3).ConfigureAwait(false);
```
### Things I tried
This code is work for business account, **but not work for personal account.** And I found that @pratik-c got a workaround by using {path} instead of {item-id} in this [stackoverflow question](https://stackoverflow.com/questions/48300672/how-to-upload-a-large-file-to-onedrive-using-microsoft-graph), but I need to use {item-id}, and there is no document of this error.

**Comment by zsybupt** [comment]
And I have tried both:
POST /drives/{driveId}/items/{itemId}/createUploadSession
POST /me/drive/items/{itemId}/createUploadSession

not work for personal account

@MIchaelMainer

**Comment by zsybupt** [comment]
![image](https://user-images.githubusercontent.com/3711046/46712347-319db000-cc83-11e8-88a2-f521e97cf046.png)

checkout graph explorer

**Comment by MIchaelMainer** [comment]
It looks like you are missing the file name specified like this:

Can you try this and tell me if it works:
`var uploadSession = await graphClient.Drive.Items["01KA5JMEBZ7FQ7QYBXKJE3X3THBVZLQIUS"].ItemWithPath("_hamilton.png").CreateUploadSession().Request().PostAsync();`

**Comment by zsybupt** [comment]
@MIchaelMainer 
according to [this document](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driveitem_createuploadsession)
these requests should work:
**POST /drives/{driveId}/items/{itemId}/createUploadSession**
POST /groups/{groupId}/drive/items/{itemId}/createUploadSession
**POST /me/drive/items/{itemId}/createUploadSession**
POST /sites/{siteId}/drive/items/{itemId}/createUploadSession
POST /users/{userId}/drive/items/{itemId}/createUploadSession


I have tried using path, it works, but my point is that:
**POST /drives/{driveId}/items/{itemId}/createUploadSession** is work for business account, but failed when there is a personal account, and the document does not specify it either. It may be some differences between personal account OneDrive and business account OneDrive, but if there is one uniform graph sdk for all kind of accounts, I think the exposed interfaces or apis should also work for all kinds of accounts.😀

**Comment by MIchaelMainer** [comment]
@zsybupt Okay, I'm following you now. Yes, I agree, these two interfaces should work the same, and the document should reflect the actual behavior of the API.

@ificator Should createUploadSession action work the same for both personal and business?

**Comment by ificator** [comment]
Yeah, ideally both services should behave the same and realistically the name requirement should only be for creation scenarios. If the item already exists, and you have its id, there's no reason we shouldn't allow it to be updated by only id - whether it's a session based upload or a put to content.

**Comment by prrvchr** [comment]
Hello,
I have exactly the same problem with a file of 26 bytes.
This is not related to the size of the file as the title of the issuse says.

Still no solution! Correct the documentation or the API ... please.

**Comment by MIchaelMainer** [comment]
@prrvchr Thank you for insisting on us addressing this. We've informed the API owner to take a look at this issue.

**Comment by zsybupt** [comment]
I have tested, it works now, Thanks

**Comment by masahiro-ikemoto** [comment]
I have similar problem via shares request, eg:
POST /shares/{shareId}/items/{itemId}/createUploadSession

Above request returns the same result (invalid request: File name not provided in url).

And,
POST /shares/{shareId}/items/{itemId}:/{fileName}:/createUploadSession
PUT /shares/{shareId}/items/{itemId}:/{fileName}:/content
are returns BadRequest: Unsupported segment type. ODataQuery...

But,
PUT /shares/{shareId}/items/{itemId}/content
is success.

Are these right behavior?

**Comment by ificator** [comment]
There are two issues here:
1. The fix for this issue did NOT resolve it for "shares" as that's a special code path - we're working on that as we speak but cannot comment on timelines.
2. Graph itself is not handling providing a path relative to an "items" request when done via `shares` so it might be worth creating a new issue for this one.

**Comment by masahiro-ikemoto** [comment]
Thanks for your reply.

I'll wait the fix or creating new issue.
