### ISSUE TITLE
return=representation not working for PATCH requests

### ISSUE THREAD

**Issue by ordinaryorange** [microsoftgraph/msgraph-sdk-dotnet#306]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [X] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
When executing a `PATCH` request to update an order hint, the [documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/planner_order_hint_format) indicates the entity and therefore service calculated order hint can be returned in the response through the use of `return=representation`
Whilst the docs are not clear on where exactly to put this in the `PATCH` request, I've tried the headers and as a query string, but neither work.
The client SDK further supports the documentation by virtue of a returned entity from the `UpdateAsync()` method call on the entity to which the order hint is being updated.

### Actual behavior
The returned object in the SDK is `null`

### Steps to reproduce the behavior
An inspection of the `PATCH` call with fiddler shows a response code of 204
Testing of the `PATCH` request in Graph Explorer also returns a 204
Both V1.0 and beta endpoints update the order hint successfully, but neither return the updated entity.

**Comment by darrelmiller** [comment]
The `return=representation` is a preference that is applied using the prefer header.  See [spec](https://tools.ietf.org/html/rfc7240#section-4.2)

```
     PATCH /item/123 HTTP/1.1
     Host: example.org
     Content-Type: application/example-patch
     Prefer: return=representation

```

**Comment by MIchaelMainer** [comment]
To add on to what Darrel states, you'll set the header like this:

                var preferOption= new QueryOption("Prefer", "return=representation");
                var options = new List<QueryOption>();
                options.Add(preferOption);

                var result = await graphClient.Me.Request(options).UpdateAsync(aUserPatchObject);

**Comment by MIchaelMainer** [comment]
Please reopen this issue if we haven't addressed your issue.

**Comment by ordinaryorange** [comment]
Thankyou gentlemen! Docs clearly written by someone with more of an understanding of the specifications than me,
