### ISSUE TITLE
Planner: Write requests are only supported on contained entities

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#307]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/plannerplan)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
dotnet SDK not to provide a fluent API for a non-existing POST /v1.0/groups/<id>/planner/plans endpoint.
I think the fluent API provided by the SDK should not suggest something is available here when it is actually not.

### Actual behavior
It's possible to write the following code, have it compile but get the following error at runtime.
```CS
var createdPlan = await _client.Groups[groupId].Planner.Plans.Request().AddAsync(new PlannerPlan
                {
                    Owner = groupId,
                    Title = planName
                });
```
```
Write requests are only supported on contained entities
```

### Steps to reproduce the behavior
Write above code and run it.
 
[AB#7347](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7347)

**Comment by darrelmiller** [comment]
We are working on this right now.  Currently the SDK is not taking advantage of the capability annotations in the metadata.  We hope to have this resolved soon.

**Comment by darrelmiller** [comment]
@baywet This is a different issue than I thought.  We need to do some additional investigations to identify where in our codegen pipeline this needs to get fixed.

**Comment by MIchaelMainer** [comment]
902788

**Comment by AndyCJ** [comment]
@darrelmiller Sorry to directly ping you, but did the investigations get anywhere?

Would it be more correct for me to open a new issue?

**Comment by AndyCJ** [comment]
@baywet I just got a reply on SO and it looks like I was doing something slightly different, and that's what was wrong. So I should have created a new issue for this because it was something different. Then again, I now know the problem is with my code, and not with the planner API, so I probably shouldn't have posted here on github at all.

Oh well, I'm glad it's resolved, and I hope the issue you're encountering is resolved soon too!

**Comment by darrelmiller** [comment]
@AndyCJ Thanks for following up.  Sorry, I didn't see the GitHub mention.  I'm trying to find a way out of GitHub notification bankruptcy at the moment.  Glad to hear that you found your issue.

**Comment by mbratukha** [comment]
Any updates on this issue?
I'm having the same problem.

**Comment by krisrok** [comment]
just for the record, if anyone else struggles with e.g. planner task creation.

at the moment you have to post to planner/tasks, _not_ directly to a plan or a bucket. you'll reference them instead via their ids:
```
var newTask = new PlannerTask
{
	Title = "Very new Task!",
	PlanId = planId,
	BucketId = bucketId
};

await graph.Planner.Tasks.Request().AddAsync(newTask);
```

**Comment by jasonclamb** [comment]
Thank you @krisrok , I was trying to use New-MgPlannerPlanTask and New-MgPlannerBucketTask without success; I kept getting the error "Write requests are only supported on contained entities".  based on your code above I switched to New-MgPlannerTask and had success creating new tasks in a Planner Plan.

**Comment by MIchaelMainer** [comment]
We need annotations support for this, this is tracked by #458. Let's address this in Kiota for generation support.
