### ISSUE TITLE
Unable to update MobilePhone field of Azure AD 

### ISSUE THREAD

**Issue by ashosb** [microsoftgraph/msgraph-sdk-dotnet#309]
We are facing an issue with our application which relies on Graph api to update user properties of the AD. The update works for all the properties except for the MobilePhone field.
It throws Microsoft.Graph.ServiceException ( More details below ). If the update request passes a NULL for mobile number it works. We have tried multiple combinations of mobile number 'with space, without space ...etc' , none seems to work. Different Country location was also tried.

Our solution is using Microsoft.Graph & Microsoft.Graph.Core dll ( 1.8.0.0 ). We have also tried to upgrade to 1.11.0.0, same issue. 

Could you help ?

Exception details:
at Microsoft.Graph.HttpProvider+<SendAsync>d__19.MoveNext (Microsoft.Graph.Core, Version=1.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)

### Steps to reproduce the behavior

var user = new User()
            {
                GivenName = pendingRegistration.GivenName,
                Surname = pendingRegistration.SurName,
                StreetAddress = pendingRegistration.Address,
                PostalCode = pendingRegistration.PostalCode,
                City = pendingRegistration.City,
                State = pendingRegistration.State,
                Country = pendingRegistration.Country,
                MobilePhone = pendingRegistration.Mobile,
                JobTitle = pendingRegistration.JobTitle
            };
_client.Users[userId].Request().UpdateAsync(user);

**Comment by ashosb** [comment]
Quite strange that I end up with "Insufficient Privilege" just for that property after trying with the format that you had given. The other properties work fine. Do you have any additional grants on the Azure AD app?

![untitled](https://user-images.githubusercontent.com/44170706/46978021-06292400-d0ce-11e8-9262-74086bb36d83.png)

**Comment by MIchaelMainer** [comment]
Yes, I have many more scopes selected. I'm using an app registration that has most of the delegated scopes selected. I use it for ad hoc testing.

**Comment by MIchaelMainer** [comment]
I'm glad that you found a resolution. Thank you for the follow up and link.
