### ISSUE TITLE
BUG: create drive item (DriveItemRequest class)

### ISSUE THREAD

**Issue by VitorX** [microsoftgraph/msgraph-sdk-dotnet#31]
**CreateAsync** method should use **POST** instead of **PUT**. 

// Microsoft.Graph.DriveItemRequest
public async Task<DriveItem> CreateAsync(DriveItem driveItemToCreate, CancellationToken cancellationToken)
{
	this.ContentType = "application/json";
	this.Method = "PUT";
	DriveItem driveItem = await this.SendAsync<DriveItem>(driveItemToCreate, cancellationToken, HttpCompletionOption.ResponseContentRead).ConfigureAwait(false);
	this.InitializeCollectionProperties(driveItem);
	return driveItem;
}

**Comment by shiftylogic** [comment]
This appears to be a bug in the generator templates. A fix has been [submitted to the code generator](4c10e293161f2ef460b22bd85b07356eba2b16cc). repo. The SDK will be updated in the next release.

Thanks for reporting.

**Comment by englertibor** [comment]
Hi Guys, was the updated version already publicated?
I'm using the newest version (1.8.1)
and on request:
`    var folderToCreate = new DriveItem { Name = "Fold", Folder = new Folder() };
                var createdFolder = await graphClient.Users[user.Id]
                          .Drive
                          .Root
                          .ItemWithPath("0_CloudHW")
                          .Request()
                          .CreateAsync(folderToCreate);`
I still get the error "Request invalid or mallformed" no matter how I place the slashes in relative path.

**Comment by MIchaelMainer** [comment]
@englertibor Please open a new issue and fill in the new issue template. Make sure you add the trace information.
