### ISSUE TITLE
No generic way to access AdditionalData from Graph responses 

### ISSUE THREAD

**Issue by dev-tim** [microsoftgraph/msgraph-sdk-dotnet#310]
Hello!
Currently, I'm trying to integrate with Planner using Microsoft Graph. 
But there is one thing that I found a bit difficult. 

In our system, we are recording HTTP calls telemetry based on some headers, HTTP status code, etc. 
I could find this information in the `AdditionalHeaders` field and it would be very convenient to access this information from Graph response in some generic way. 

At the moment `CollectionResponse` and `Entity` classes don't share a common interface that people could use to extract raw HTTP information about the response. 
Here is an example: 
Base type for Graph `Entity` 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Models/Generated/Entity.cs
and `CollectionResponse` class
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/PlannerPlanTasksCollectionResponse.cs

Would you consider creating a base class for instance property for handling `AdditionalHeaders`? 
[AB#7349](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7349)

**Comment by Rusty-Shackleford** [comment]
Would this be why I cannot access alert entity specific details for things like "LogonIP" and "LogonLocation"?  For example there is an alert for "Impossible Travel" that triggers when someone has two logins from very distant locations, and the alert contains information for "First Login IP" and "Second Login IP" but these never show up even when do something like:

```
string requestUrl = _gsc.Security.Alerts[pageId].Request().RequestUrl;
```

**Comment by MIchaelMainer** [comment]
This is addressed in v4 where we provide the entire response envelope for all requests. Please provide feedback in this issue: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graph-response
