### ISSUE TITLE
why I cannot access alert entity specific details for things like "LogonIP" and "LogonLocation"?

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#311]
Would this be why I cannot access alert entity specific details for things like "LogonIP" and "LogonLocation"?  For example there is an alert for "Impossible Travel" that triggers when someone has two logins from very distant locations, and the alert contains information for "First Login IP" and "Second Login IP" but these never show up even when do something like:

```csharp
            string requestUrl = _gsc.Security.Alerts[pageId].Request().RequestUrl;
            HttpRequestMessage reqMsg = new HttpRequestMessage(HttpMethod.Get, requestUrl);
            await _gsc.AuthenticationProvider.AuthenticateRequestAsync(reqMsg);
            HttpResponseMessage response = await _gsc.HttpProvider.SendAsync(reqMsg);
            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                Alert alert = _gsc.HttpProvider.Serializer.DeserializeObject<Alert>(content);
            }
```

_Originally posted by @Rusty-Shackleford in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/310#issuecomment-430404117_

**Comment by MIchaelMainer** [comment]
@Rusty-Shackleford Your missing alerts have nothing to do with the OP issue.  Perhaps there are more alerts than what is contained in the page. Is the result a round number? If so, you probably have more alerts on another page. Mind you, I don't know anything about the nature of the alerts API. @Mounika-Chillamcherla can you help us?

**Comment by Rusty-Shackleford** [comment]
I'm seeing all the entities (alerts) themselves I'm expecting to see.  What's missing is some data within the payload of the entity I would expect.  There are fields available, but they are null.

I can post some screenshots if that helps.

**Comment by MIchaelMainer** [comment]
Can you provide a Fiddler trace?

**Comment by MIchaelMainer** [comment]
Yes, that is very helpful. We need someone on the Security Alerts API team to help with this one. @Mounika-Chillamcherla

**Comment by Mounika-Chillamcherla** [comment]
@Rusty-Shackleford. The information you provided is really helpful. We are looking into the issue and will get back to you soon

**Comment by Rusty-Shackleford** [comment]
FYI this is still in progress and a ticket is being opened internally with the dev team.  I've recreated this call with Graph Explorer and it doesn't return the right results either, even with admin privileges it only returns a single userState (which has the location and ip address).

**Comment by Rusty-Shackleford** [comment]
FYI IcM opened with the product group, and accepted.

So far product group confirms that userStates should have more than one entry for some alerts.  When they put in an update I will test the SDK again and update this issue with the outcome.

**Comment by MIchaelMainer** [comment]
@Rusty-Shackleford Thank you for updating this issue with the state of the service issue.

**Comment by Rusty-Shackleford** [comment]
Update: The Product Group just released an update and now we get two userStates back from Alert Entities when it is appropriate, so this issue appears to be resolved!  It wasn't an issue with this SDK at all and it doesn't look like any changes are needed to this library in order to utilize the update.  Thanks for your help everyone!

**Comment by MIchaelMainer** [comment]
Thank you @Rusty-Shackleford for the update!
