### ISSUE TITLE
Desktop Framework applications should not use System.Net.Http from nuget

### ISSUE THREAD

**Issue by bussemac** [microsoftgraph/msgraph-sdk-dotnet#312]
See https://github.com/dotnet/corefx/issues/29622, in particular https://github.com/dotnet/corefx/issues/29622#issuecomment-388199236 ... "In most cases, we don't advise people use the separate System.Net.Http NuGet package anymore. See #11100 and #17522."

This can be done by changing the csproj, as per the examples in
https://github.com/IdentityModel/IdentityModel2/issues/76

The DLL hell that System.Net.Http is, even with >= 4.3.3 and Net Framework 4.7.2 is just such a nightmare, that there's no good reason to depend on the nuget version instead of the Framework version. Users installing Graph SDK into netstandard can use the nuget version, because the csproj modification will only require the nuget package for them, not the full framework projects.

**Comment by MIchaelMainer** [comment]
Thank you for providing this guidance. I'll look to make this change is the next update.
