### ISSUE TITLE
Graph API "search" is not returning any results

### ISSUE THREAD

**Issue by kdhindsa** [microsoftgraph/msgraph-sdk-dotnet#314]
I have an application that is using MS Graph SDK (.NET) to search for user's documents. It has suddenly stopped returning results altogether. When I inspected the object during debugging, it showed the Count = 0.

I then went on to Microsoft Graph Explorer tool and saw the same result: empty list.

See the attached screenshot for the graph explorer.
![image](https://user-images.githubusercontent.com/707427/47661525-76b45400-db56-11e8-9b6c-4ef4beac2a4e.png)

 
[AB#7350](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7350)

**Comment by kdhindsa** [comment]
I know for a fact the above query is supposed to return many results as it was working till a few days ago. I tried the same search query in OneDrive, and it returned many results.

**Comment by kdhindsa** [comment]
The issue still exists as of today. Is anyone looking into this?

**Comment by HerraHak** [comment]
From what I understand in your issue, it is the graph API that doesn't return anything, not the .net SDK.
You may have better luck on stackoverflow.

**Comment by MIchaelMainer** [comment]
Are you still seeing this issue?
