### ISSUE TITLE
Key Info Loss in Error & Exception Analyzing, please refine your Classes.

### ISSUE THREAD

**Issue by crazygao** [microsoftgraph/msgraph-sdk-dotnet#316]
1. When Error Occurs, there are often error status codes, these are very important for error analysis. However when Exception happens, it returns a default null object and return and omit the error.

2. HttpProvider Class SendAsync method, when error occurs, it drop out the response and customize some hand-made errors, Graph with send some analysis messages in the response body along with status code when error happens, if you drop out these messages, these error details are dropped out!

### Expected behavior

1. Append raw response into ServiceException, and let it pop up to user level.

### Actual behavior

1. call api will always return a good value or a null value.

### Steps to reproduce the behavior

1. Every call to api

**Comment by MIchaelMainer** [comment]
@crazygao Thank you for taking your time to bring this to our attention. We are aware of these current limits around error reporting. It would be a useful option to append the raw response to the ServiceException class. 

@darrelmiller We should consider a configurable exception handler middleware.
