### ISSUE TITLE
Unauthorized when calling GetOneDriveActivityFileCounts

### ISSUE THREAD

**Issue by isc30** [microsoftgraph/msgraph-sdk-dotnet#317]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

Returns the report. [Official Documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/reportroot_getonedriveactivityfilecounts)

```csharp
var activities = await client.Reports.GetOneDriveActivityFileCounts("D7").Request().GetAsync();
```
via REST:
`https://graph.microsoft.com/v1.0/reports/getOneDriveActivityFileCounts(period='D7')`

### Actual behavior

Returns unauthorized error

```json
{
  "error": {
    "code": "S2SUnauthorized",
    "message": "Invalid scope claims/roles.",
    "innerError": {
      "request-id": "9bcd8f9c-7422-4721-9b48-eb49429f39c7",
      "date": "2018-11-06T10:40:05"
    }
  }
}
```

### Steps to reproduce the behavior

* Use Application Authentication
* Have administrator permissions in Application
* Have role `Reports.Read.All`
* Call the API, still "no permissions" error

Thanks

**Comment by MIchaelMainer** [comment]
Thank you for reporting this issue. This appears to be an issue with either your configuration or the service API. This repository is specific to the .Net client library. Questions about the service API or configuration should be posted to StackOverflow and tagged with microsoft-graph.

Please post this to StackOverflow and then provide a link in this issue to your post.

**Comment by isc30** [comment]
Thanks, link to StackOverflow: https://stackoverflow.com/questions/53170589/unauthorized-when-calling-getonedriveactivityfilecounts
