### ISSUE TITLE
Performance Limitation in current design | template requests 

### ISSUE THREAD

**Issue by crazygao** [microsoftgraph/msgraph-sdk-dotnet#318]
Hi,

When we use graph as our client library, we often needs to open a list of files.
Book1.xlsx, Word1.docx, Book2.xlsx etc.

However, when we generate this query, we often needs to write something like this.

graphClient.Me.Drive.Root.ItemWithPath(Book1.xlsx)
graphClient.Me.Drive.Root.ItemWithPath(Word1.docx)
graphClient.Me.Drive.Root.ItemWithPath(Book2.xlsx)

Maybe you will ask me to save some variable like graphClient.Me.Drive.Root. and reuse it, but be careful, there are not always only 1 thing I need to replace.

This is quite inefficient because it is actually at least 4 calls before I come to the final request.
Request itself is only an url like this.

/me/drive/root/:/Book.xlsx ....

If I make a template like this
/me/drive/root/:$1

Every time I call this, it just generate something like
template.call(Book1.xlsx)
Of course it should also support types you define in your library.
This library should allow me to replace this $1 with proper filepath, which is easy standard string interpolation. And I could reuse it. It saves code and performance I think.

**Comment by MIchaelMainer** [comment]
@crazygao  Thank you for taking the time to provide this feedback. It sounds like an arbitrary request builder object would be helpful here.

I suggest that you fall back to HttpRequestMessage in the meantime.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md#send-http-requests-with-the-net-microsoft-graph-client-library 

935900

**Comment by MIchaelMainer** [comment]
You can do this with

```
var fileName = "Book1.xslx";
var templatedcall = graphClient.Me.Drive.Root;
await templatedcall.ItemWithPath(fileName).GetAsync();
```
