### ISSUE TITLE
NextPageRequest always returns an exception

### ISSUE THREAD

**Issue by HerraHak** [microsoftgraph/msgraph-sdk-dotnet#319]
Hi,

I connect to a sharepoint online list.  The first request returns 200 elements and the NextPageRequest isn't null.
I try to run the following code but when calling NextPageRequest it always exits with this exception : 

`One or more errors occurred. (Code: -1, Microsoft.SharePoint.Client.InvalidClientQueryException Message: The parameter name path is not valid. Inner error ) - Code: -1, Microsoft.SharePoint.Client.InvalidClientQueryException Message: The parameter name path is not valid. Inner error `

I run this code : 
![image](https://user-images.githubusercontent.com/39991942/48257899-1ce44180-e414-11e8-8473-a7e17248b309.png)

When debugging I look into the NextPageRequest.RequestUrl and I see this.  I have no idea if this is correct : 
`https://graph.microsoft.com:443/v1.0/sites/root/getByPath(path='pathValue')/lists/{listid}/items`
I replace the real listid by {listid} in the preceding url.

The code is run in a Razor page app using .net core 2.1
These are the dependencies : 
![image](https://user-images.githubusercontent.com/39991942/48258054-7fd5d880-e414-11e8-8209-0f083e4151fb.png)

Is there something I'm doing wrong ?

**Comment by MIchaelMainer** [comment]
The NextPageRequest.RequestUrl does not look correct. I'd expect a [$skip or $skiptoken](https://developer.microsoft.com/en-us/graph/docs/concepts/paging). What I don't know yet is whether this is a client or service issue. Do you have access to a Fiddler trace of that initial request and response? Does the response contain a `@oadata:nextlink`?

**Comment by HerraHak** [comment]
Hi Michael,

I used fiddler to check what was sent back by the service and in the big Json here's what I get : 
`"@odata.nextLink": "https://graph.microsoft.com/v1.0/sites/root/getByPath(path='pathValue')/lists/[ID]/items?$skiptoken=UG...MQ"`
While in the debugger here is what I get from the sdk : 
`https://graph.microsoft.com:443/v1.0/sites/root/getByPath(path='pathValue')/lists/[id]/items`

I don't know a lot about graph api but it seems to me that there might be a bug in the SDK.

**Comment by HerraHak** [comment]
I don't know if that helps but I found out that when instantiating ListItemsCollectionRequest, there's a call to the base controller which is in class BaseRequest.
Then in the constructor, a call to the method 
` private string InitializeUrl(string requestUrl)`
and the NextRequestLink is passed to this method as parameter.

Now the method decomposes the query string in a QueryOptions list and that is correctly done.
But it returns this line : 
`return new UriBuilder(uri) { Query = string.Empty }.ToString();`
Knowing that this is going to be the value of `this.RequestUrl` which is going to be used to build the HttpRequest, it seems to me that this might be the issue.

What do you think?

**Comment by MIchaelMainer** [comment]
Yeah, that's a service issue. Can you share the request-id so I can open an incident on this?

**Comment by HerraHak** [comment]
umm, I'm going to need a little help to find the request id.  Is it in the returned json?

**Comment by MIchaelMainer** [comment]
It is returned in the JSON. It is in the innerError. You replaced it with `"ID"` when you shared your reply. See your comment from [4 days ago]([url](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/319#issuecomment-437846614)).

**Comment by HerraHak** [comment]
Hi,

Here's the request ID : a42a9240-7831-4662-9cb4-dcfd67e5c201

**Comment by MIchaelMainer** [comment]
Thank you. This issue has been raised.

93568500

**Comment by HerraHak** [comment]
Hi, 

Is there a place where I can see how the resolution of this issue progresses?

Thanks

**Comment by MIchaelMainer** [comment]
I'm sorry to say that there isn't. I was talking about this over lunch today -- our communication needs to improve a lot for service API issues. The best I can do is look into the state of this. It looks like a fix has been applied, I'm not sure when you will see this fix in live site.

**Comment by darrelmiller** [comment]
@HerraHak Are you still seeing this issue or could we close the issue?

**Comment by HerraHak** [comment]
I'm going to test it and let you know.

**Comment by HerraHak** [comment]
Hey there, 

Just tested NextPageRequest.GetAsync() and it worked so for me the issue is fixed.
Even if this was a service bug I'd like to thank you for your help.

**Comment by darrelmiller** [comment]
@HerraHak Thanks for letting us know.  Great to hear that this issue is resolved for you.
