### ISSUE TITLE
The scope for getMemberObjects is not described as the document.

### ISSUE THREAD

**Issue by VitorX** [microsoftgraph/msgraph-sdk-dotnet#33]
The scope `User.Read; User.ReadWrite;` doesn't work request below:
POST /users/<id | userPrincipalName>/getMemberObjects

[Here](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_getmemberobjects) is the document for your reference.

**Comment by MIchaelMainer** [comment]
Opened issue for the documentation.
