### ISSUE TITLE
Create schema extension is failing - Insufficient privileges exception

### ISSUE THREAD

**Issue by ashwineev** [microsoftgraph/msgraph-sdk-dotnet#333]
I have created a daemon application in azure ad registered applications and given below permissions to the application

1. Directory.Read.All
2. Directory.ReadWrite.All
3. User.Invite.All
4. User.Read
5. User.Read.All
6. User.ReadWrite.All
7. Group.Read.All
8. Group.ReadWrite.All

I have referred this link _https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/238

I get below error:-
{"Code: Authorization_RequestDenied\r\nMessage: Insufficient privileges to complete the operation.\r\n\r\nInner error\r\n"}

Below is the code

```
var schema = new SchemaExtension()
                    {
                        Id = "Location",
                        TargetTypes = new List<string> { "User" },
                        Description = "DescribesLocation",
                        Properties = new List<ExtensionSchemaProperty>() { new ExtensionSchemaProperty { Name = "LocationCode", Type = "String" } }
                    };

                    var result = graphClient.SchemaExtensions.Request().AddAsync(schema).Result;
```

I have also posted the question on stackoverflow for this:-
https://stackoverflow.com/questions/53778888/extension-attributes-for-ad-user-in-azure-active-directory-using-microsoft-graph

Could you please let me know if there is any step I am missing here for giving permissions?

**Comment by MIchaelMainer** [comment]
Thank you for your question about Microsoft Graph. Please post your questions to StackOverflow with the microsoft-graph and microsoft-graph-sdks tags. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings

**Comment by ashwineev** [comment]
@MIchaelMainer Thanks.I have posted on stackoverflow and have modified my post.

**Comment by MIchaelMainer** [comment]
Answered on SO.
