### ISSUE TITLE
How can I get listitems shown as driveitems?

### ISSUE THREAD

**Issue by julienFlexsoft** [microsoftgraph/msgraph-sdk-dotnet#336]
Hi,
I want to do this (works in the Graph Explorer):
`https://graph.microsoft.com/v1.0/sites/[SITE-ID]/lists/[LIST-ID]/items/1/driveitem`

I tried to do this:
`var data = await graphClient
                    .Sites[SITE-ID]
                    .Lists[LIST-ID].Items.Request().Top(1).DriveItem.GetAsync();`

But this doesn't exist.
This works perfectly though:
`var data = await graphClient
                    .Sites[SITE-ID]
                    .Lists[LIST-ID].Items.Request().Top(1).GetAsync();`

How can I do the same call as the graph Explorer with the SDK? I thought to ask it here since it might be a bug, because it works in the explorer.
+ If there is a fix for my issue, is there also a way to get the whole list as a drive?
Thanks and good day to you!

**Comment by MIchaelMainer** [comment]
Thank you for your question about the Microsoft Graph. Please post your questions to StackOverflow with the microsoft-graph-sdks tag. StackOverflow is indexed better than GitHub issues. After you've posted your question on StackOverflow, please provide a link here back to your post. That way, the question will be found by more people -- plus it gives back to the dev community on StackOverflow. 

Make sure you include the following information in your post on StackOverflow:
* What you've tried, your repro steps
* A trace of both the request and response
* Any error messages
* Any settings
