### ISSUE TITLE
NuGet package out of date

### ISSUE THREAD

**Issue by chrispatrick** [microsoftgraph/msgraph-sdk-dotnet#34]
I'm attempting to move from using the OneDrive SDK to the Graph SDK and I'm running into issues with NuGet packages.

Currently I'm using the OneDriveSDK Auth package (https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter) which references the Graph.Core package. However, the main Graph package seems to have been last updated in April, which looks like before Graph.Core was introduced. This means I can't use both Graph.Core and Graph because they both define some of the same classes.

Is there a plan to update the NuGet package to something newer?

**Comment by chrispatrick** [comment]
Having looked at the build, it looks like the path to the nuspec file needs updating in the build script.

**Comment by shiftylogic** [comment]
There is an update coming. The date is TBD.

Can you please be move specific where the bad path is? I'm not seeing what you mean.

**Comment by chrispatrick** [comment]
https://ci.appveyor.com/project/OneDrive/msgraph-sdk-dotnet/branch/master/job/xm6s2mh9kac29qi8

**Comment by chrispatrick** [comment]
Do you have any idea of the timescale? Weeks? Months?

It just seems odd to have Microsoft.Graph.Core built a week or so ago but Microsoft.Graph hasn't been updated since April.

**Comment by chrispatrick** [comment]
Any idea when this might get done? I'm just trying to decide whether to wait or whether to work on an alternative approach for now.

**Comment by shiftylogic** [comment]
There is an update coming very soon with a fix for this issue as well as some new functionality and other bug fixes.

**Comment by chrispatrick** [comment]
Any update on this? I've just run into #21 as well, so it would be great to be able to update soon. 😸

**Comment by MIchaelMainer** [comment]
@chrispatrick We've updated the Microsoft.Graph package on Nuget.
