### ISSUE TITLE
Question: how to create group with team and members?

### ISSUE THREAD

**Issue by thorstenschroeder** [microsoftgraph/msgraph-sdk-dotnet#341]
Can you please show an example how to create a group with members and team with the recent build?
Can they be created in one request? What's the right way to do it.
I could not get it to work:
```
 Group group = new Group
        {
            DisplayName = "TestGroup",
            Description = "test",
            MailNickname = "testgroup",
            Visibility = "Private",
            SecurityEnabled = false,
            MailEnabled = true,
            GroupTypes = new List<string> { "Unified" },
            Owners = {},
            Members = {},
            Team = {} 
        };

```
Thank you.

**Comment by MIchaelMainer** [comment]
> Can you please show an example how to create a group with members and team with the recent build?

I don't have an example on how to do that.

> Can they be created in one request?

No. I found the following [information in the documentation](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&viewFallbackFrom=graph-rest-v1.0) that indicates that the group must be created first then a team created under it.

What have you tried?
What information are you using?
What errors are you encountering?
What type of app is this?

Please provide more information.

I suggest that you start by reading the documentation and then use [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to see how to get the results you want. Then try this with the client library.

**Comment by thorstenschroeder** [comment]
Hello,

here is what I tried to create the team after the group got created (console application).

```
   var createdGroup = await _graphServiceClient.Groups.Request().AddAsync(group);
         
            foreach (var item in groupMembers)
            {
                await _graphServiceClient.Groups[createdGroup.Id].Members.References.Request().AddAsync(item);
                await _graphServiceClient.Groups[createdGroup.Id].Owners.References.Request().AddAsync(item);
            }
			
            Team team = new Team();
			// create team from group NOT Working
            var createdTeam = await _graphServiceClient.Groups[createdGroup.Id].Team.Request().CreateAsync(team);
```
The group is created and members/owners are added. But creating the team fails.

This is the request that got created from the CreateAsync method:
```
request	{Method: POST, RequestUri: 'https://graph.microsoft.com/v1.0/groups/81ca5d40-975a-41be-bdbd-07228c0c3bea/team', Version: 2.0, Content: <null>, Headers:
{
  SdkVersion: Graph-dotnet-1.13.0
}}	System.Net.Http.HttpRequestMessage
```

Error:
```
{Microsoft.Graph.ServiceException: Message: No HTTP resource was found that matches the request URI 'https://api.teams.skype.com/v1.0/groups('81ca5d40-975a-41be-bdbd-07228c0c3bea')/team'.

Inner error

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.TeamRequest.CreateAsync(Team teamToCreate, CancellationToken cancellationToken)
```

What am I doing wrong?

Thanks.

**Comment by thomasgassmann** [comment]
@thorstenschroeder I was having the same problem. I suppose this a bug in the MS Graph SDK. It is trying to access `https://api.teams.skype.com/v1.0/groups('81ca5d40-975a-41be-bdbd-07228c0c3bea')/team`, whereas the correct request would be `PUT /groups/{id}/team`. 

In order to solve your problem temporarily, you could create the request manually using the `HttpProvider`:
```var teamCreationRequestMessage = graphService.Groups.Request().GetHttpRequestMessage();
teamCreationRequestMessage.Content = new StringContent(JsonConvert.SerializeObject(new Team()), Encoding.UTF8, "application/json");
teamCreationRequestMessage.Method = new HttpMethod("PUT");
teamCreationRequestMessage.RequestUri = new Uri(teamCreationRequestMessage.RequestUri, $"groups/{createdGroup.Id}/team");
await _graphServiceClientFactory.SignRequest(teamCreationRequestMessage);
await graphService.Groups.Request().Client.HttpProvider.SendAsync(teamCreationRequestMessage)```

**Comment by thorstenschroeder** [comment]
@thomasgassmann  thank you. Based on your example I was able to create a Team with the HttpClient.

**Comment by MIchaelMainer** [comment]
@thomasgassmann Thank you for providing a workaround.

@darrelmiller @pwombwa The generator makes an assumption that all contained entities are added with POST. This scenario uses a PUT ([docs](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0)). There isn't a generation hint in the metadata to specify that we should be using a PUT (there is a generation hint in the documentation). 

It also appears that most contained non-collection entities are created at the same time as the group and that Teams may be a special case (still a case we need to support). OneNote, Drive, and Calendar. A fix requires a customer request builder.

**Comment by MIchaelMainer** [comment]
@thorstenschroeder I'm going to release a preview later today/tomorrow a fluent API that should work as you expect. Would you be a to verify it once I provide it?

**Comment by MIchaelMainer** [comment]
@thomasgassmann @thorstenschroeder Here's a preview you can use to make the call with the fluent API.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.13.0-preview.2

`graphClient.Groups[groupPage[8].Id].Team.Request().PutAsync(team)`

**Comment by thomasgassmann** [comment]
@MIchaelMainer It works as expected for me. Thank you for the quick response! Will the new version also be available on NuGet?

**Comment by thorstenschroeder** [comment]
@MIchaelMainer @thomasgassmann  I can also confirm that it works with the new preview version.

### One more thing:
I tried **cloning** an existing team with below code and this request URL got created:
`"https://graph.microsoft.com/v1.0/teams/34a08d91-d47a-49b8-ab33-1214b2c46913/microsoft.graph.clone"`

```
var x = _graphServiceClient.Teams[id].Clone(TeamVisibilityType.Private, ClonableTeamParts.Channels,
                                    displayName: "testClone1", description: "testDesc", mailNickname: "testClone1", classification: "private");

```

But I also get a bad request if I try cloning with the HttpClient like so:
```
   Uri UriClone = new Uri("https://graph.microsoft.com/v1.0/teams/34a08d91-d47a-49b8-ab33-1214b2c46913/clone");

                    var cloneTeam = await _httpServiceClient.PostAsync(UriClone, new StringContent(
                        JsonConvert.SerializeObject(
                                (displayName: "Clone Team", description: "descr", mailNickname: "testClone2",
                                    TeamVisibilityType.Private
                                )), Encoding.UTF8, "application/json")
                        );

```
What is wrong with this request?

Thank you.

**Comment by MIchaelMainer** [comment]
@thorstenschroeder It appears that the service endpoint does not accept the fully qualified name of the clone action. The client emits that final segment as a fqn. It really should accept it. Yep, separate issue.
