### ISSUE TITLE
Cannot install Newtonsoft.Json 12.0.1 with Microsoft.Graph 1.12.0

### ISSUE THREAD

**Issue by vontangen** [microsoftgraph/msgraph-sdk-dotnet#345]
Output from Package Manager

Attempting to gather dependency information for package 'Newtonsoft.Json.12.0.1' with respect to project 'IncidentIQ.Apps.MicrosoftAzureSso', targeting '.NETFramework,Version=v4.7'
Gathering dependency information took 1.1 sec
Attempting to resolve dependencies for package 'Newtonsoft.Json.12.0.1' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Newtonsoft.Json 12.0.1' is not compatible with 'Microsoft.Graph 1.12.0 constraint: Newtonsoft.Json (>= 6.0.1 && < 12.0.0)', 'Microsoft.Graph.Core 1.12.0 constraint: Newtonsoft.Json (>= 6.0.1 && < 12.0.0)'.
Time Elapsed: 00:00:01.1448457

We're attempting to upgrade our solution to Newtonsoft.Json.12.0.1, but Microsoft.Graph is holding us back. The upper-bound requirement only applies to .NETFramework and not to .NETStandard. Is this intentional?

**Comment by MIchaelMainer** [comment]
Not intentional. We'll fix in the next release.

**Comment by MIchaelMainer** [comment]
@vontangen I'm going to release a preview later today/tomorrow without the upper bounds restriction. Would you be a to verify it once I provide it?

**Comment by MIchaelMainer** [comment]
@vontangen Here you go: https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.13.0-preview.2

**Comment by vontangen** [comment]
@MIchaelMainer - thanks! I installed the packages alongside Newtonsoft.Json 12.0.1 and ran a user sync + SSO signin. No issues!

**Comment by fgroen** [comment]
@MIchaelMainer When looking at the preview package, I'm seeing an upperbound for the v4.5 framework:
