### ISSUE TITLE
Skip method generating error

### ISSUE THREAD

**Issue by Mike-tech** [microsoftgraph/msgraph-sdk-dotnet#348]
Hi there

I'm using the Microsoft Graph client library within a API service project of mine. I'm trying to do paging and trying to use the Skip option that comes with the api. When i used this i get an error as shown below:

{"Code: Request_BadRequest\r\nMessage: '$skip' is not supported by the service.\r\n\r\nInner error\r\n"}

StackTrace: BadRequest

Any suggestion when this can be fixed???

Many thanks

**Comment by MIchaelMainer** [comment]
This may be by design depending on the functionality. This issue has nothing to do with the client. What call are you trying to make?

**Comment by Mike-tech** [comment]
I'm performing a search query matches. The below works fine until i added skip then i started getting bad request:

```
async Task<IGraphServiceUsersCollectionPage> FindUserBySurname(GraphServiceClient graphClient, string searchterm, string fields, int skipValue)  
{
            string filter = string.Format("startswith(surname, '{0}')", searchterm);
            return await graphClient.Users.Request().Select(fields).Filter(filter).Skip(skipValue).GetAsync();
        }
```

**Comment by MIchaelMainer** [comment]
Got it. Skip must not be supported. You'll have to use the skipToken to page through results larger than the page size. Use [NextPageRequest](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/collections.md) to make the next call.

**Comment by Mike-tech** [comment]
Ok i see. Will explore that. Will close this thread then.
