### ISSUE TITLE
IsInline property is always false for attachments in EventMessages.

### ISSUE THREAD

**Issue by vijaysuryaj95** [microsoftgraph/msgraph-sdk-dotnet#349]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
IsInline property is should be true for inline attachments in EventMessages and should be false for attachments which are not inline. 

### Actual behaviour
IsInline property is always false for attachments in EventMessages. In event messages, the IsInline property is always false when the image is attached inline either in body or attached to the message. Is it the way it works or is it an issue? Can someone help me out on this?

### Steps to reproduce the behavior
1. Create a meeting invite.
2. Attach two images one in the body and one to the meeting.
3. Send it to the recipient and make a graph call to fetch that event and expand attachments.
4. The inline property is false for both of the attachments. Ideally it should be true for one attachment.

**Comment by MIchaelMainer** [comment]
@nimeesh-msft Can you have someone take a look at this?

**Comment by vijaysuryaj95** [comment]
Hi, Is someone looking into this? I have a dependency on this property at work and if someone can please confirm if it is a bug or let me know if my perception of this property is wrong, I will have to work on a workaround to replicate this inline property for event messages.

**Comment by nimeesh-msft** [comment]
i'll look into it and update the issue with investigation.

**Comment by nimeesh-msft** [comment]
If you are using Graph API to create attachment and if you set Inline = true in the post body of attachment request payload, then you should get the appropriate response back.  i tried from outlook also, insert image or some shape and if i read that data using graph api, it returns inline = true.

**Comment by vijaysuryaj95** [comment]
I have tried it from outlook, the steps I followed is create a meeting (so that event message is created), add an attachment to the meeting and send the meeting. On the recipient's mail box, when I get the mails, and expand the attachments, I find the property is set to false.

Attached are the Graph Response for attachments for an Event Message and the Meeting invite mail with inline attachment that is received by the recipient: 

![outlook meeting invite](https://user-images.githubusercontent.com/16381640/50902897-3de00780-1442-11e9-895c-7769cb81e93b.PNG)
![graph response](https://user-images.githubusercontent.com/16381640/50902898-3e789e00-1442-11e9-875c-1fd04af2636b.PNG)

Please have a look at them and let me know if I missed something.

**Comment by nimeesh-msft** [comment]
It may be related to older version of outlook. I'm able to create event and add image using "insert" option and graph is able to return isInline : true fag for that attachment so i dont see any SDK or platform issue here.

**Comment by vijaysuryaj95** [comment]
I have used the outlook web to attach the inline attachment. How is the web related to versioning?. Ideally, the web should be in the latest version right?

**Comment by vijaysuryaj95** [comment]
And I have also tried it with the latest version of outlook. The version of outlook that I have is the latest one, I have tried checking for updates and I found no updates to it.
![outlook version](https://user-images.githubusercontent.com/16381640/50947646-34e44a00-14c5-11e9-9846-164e18c8f8aa.PNG)

**Comment by vijaysuryaj95** [comment]
Can you please re open this issue as I see that this is not solved!?

**Comment by nimeesh-msft** [comment]
@vijaysuryaj95 , This is SDK repo and it's not SDK issue so we don't want to track this issue here.  Please report issue on stackoverflow and tag with microsoft-graph.
Also, i have tested this in both Outlook desktop and web and i'm able to get inline attachment true in both cases.

**Comment by nimeesh-msft** [comment]
@vijaysuryaj95 , can you please validate graph service response using https://developer.microsoft.com/en-us/graph/graph-explorer for the given event?

**Comment by vijaysuryaj95** [comment]
@nimeesh-msft @MIchaelMainer - I have validated the graph service response, and the issue is arising when the sender and recipient are in different organizations. On the sender mailbox, the inline property is being returned as true but on the receiver's mailbox, who is in a different organization, is receiving the inline property as false for event messages. For normal emails, the behaviour is as expected. Can you please give me any info on this scenario or possible contacts for getting this issue addressed?
