### ISSUE TITLE
System.IO.FileNotFoundException 

### ISSUE THREAD

**Issue by EthernetIp** [microsoftgraph/msgraph-sdk-dotnet#351]
I have recently installed Microsoft.Graph and Graph.Core version 1.12.0.  It would not let me upgrade Newtonsoft from version 11.0.2  (Yes I do see a ticket about this, but I am not sure this is the issue in my case).
I use Graph in a Windows Service on Windows Server 2016.
I can run the same code as an EXE , not as a service with no issues.

When I do run it as a Service, I get the following error what I believe is serialization:

Application: MyProgram.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException Exception Info: System.IO.FileNotFoundException at Microsoft.Graph.Serializer..ctor() at Microsoft.Graph.BaseClient..ctor(System.String, Microsoft.Graph.IAuthenticationProvider, Microsoft.Graph.IHttpProvider) at Microsoft.Graph.GraphServiceClient..ctor(Microsoft.Graph.IAuthenticationProvider, Microsoft.Graph.IHttpProvider) at GraphAPIwrapper.AzureGA.getGraphServiceClient(GraphAPIwrapper.AzureADmodel) at GraphAPIwrapper.AzureGA.POSTinviteUser(GraphAPIwrapper.AzureADmodel, System.String, System.String ByRef, System.String ByRef) at MyProgram.Work.CheckStuff(System.String, System.String, System.String) at MyProgram.Service1.WorkerThreadFunc() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

**Comment by MIchaelMainer** [comment]
Microsoft.Graph.Serializer..ctor() uses a settings object from Newtonsoft. This may be the same issue.

971133

**Comment by MIchaelMainer** [comment]
@EthernetIp I've removed the upper bounds of Newtonsoft package reference. Can you try it out:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.13.0-preview.2

And let me know if this solves your issue. If it does, I'll be publishing this update on NuGet next Monday.

**Comment by EthernetIp** [comment]
Ill try to do this today, sry didn't notice your reply.

**Comment by EthernetIp** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'Newtonsoft.Json 12.0.1' is not compatible with 'Microsoft.Graph 1.13.0-preview constraint: Newtonsoft.Json (>= 6.0.1 && < 12.0.0)', 'Microsoft.Graph.Core 1.13.0-preview constraint: Newtonsoft.Json (>= 6.0.1 && < 12.0.0)'.				

You removed it from .NetStandard,Version=v1.1   not from .NETFramework,Version=v4.5

**Comment by MIchaelMainer** [comment]
You are still looking at 1.13.0-preview (from NuGet), instead of 1.13.0-preview.2 from the release.

**Comment by EthernetIp** [comment]
So installed the preview2, but notice that there is 1.13 stable release already out.  Ill test with that as it also has not upper limit for Newtonsoft.   
(5 min later :) )
It works like a charm. 
Thank you.
