### ISSUE TITLE
Update NuSpec to include Xamarin.iOS and Xamarin.Android.

### ISSUE THREAD

**Issue by pierceboggan** [microsoftgraph/msgraph-sdk-dotnet#36]
Currently, the .nuspec doesn't include support for Xamarin projects. We would love if the Microsoft Graph API SDK for .NET had first-class Xamarin support, as we have many users using the HTTP Graph APIs now that would love to consume the APIs via the SDK.

Should be as simple as [adding Xamarin as target frameworks](https://developer.xamarin.com/guides/cross-platform/advanced/nuget/). 👍 Please don't hesitate to let me know if you need anything on our end.

**Comment by pierceboggan** [comment]
Specifically, I had issues adding this to a `Profile78` PCL.

**Comment by MIchaelMainer** [comment]
Thank you for the feedback. We'll look into this for the next update.

**Comment by pierceboggan** [comment]
Awesome!

Let us know when the update drops; we'll update our [update our documentation](https://developer.xamarin.com/guides/cross-platform/azure/active-directory/graph/) and [previous blog posts](https://blog.xamarin.com/enable-graph-functionality-xamarin-forms-apps/) on the Graph API as well to use the SDK. 👍

**Comment by MIchaelMainer** [comment]
This is now in the [nuspec](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/master/src/Microsoft.Graph/Microsoft.Graph.nuspec). Tested this against https://github.com/microsoftgraph/xamarin-csharp-snippets-sample, works fine. Nuget package will be updated to 1.2.0. It should be available either today or Monday.
