### ISSUE TITLE
Subscription no longer works

### ISSUE THREAD

**Issue by sherlock1982** [microsoftgraph/msgraph-sdk-dotnet#365]
### Expected behavior
Create subscription should work

### Actual behavior
Create subscription returns:

```
Code: ExtensionError
 Message: Operation: Create; Exception: [Status Code: Forbidden; Reason: Forbidden]

 Inner error
```

### Steps to reproduce the behavior

I doubt it's my issue or client issue but I'm a bit desperate to get help on stackoverflow. Here's a link to [stackoverflow question](https://stackoverflow.com/questions/53725426/microsoft-graph-users-subscription-no-longer-works)
We're using Microsoft.Graph to read /users and get notifications. I use an application token from Azure 2.0 with permissions Calendars.Read, Contacts.Read and Directory.Read.All.

This is the example on how to subscribe:
```
 var result = await _client.Subscriptions.Request().AddAsync(new Subscription() {
            ChangeType = "updated,deleted",
            NotificationUrl = /* skipped */,
            ExpirationDateTime = DateTimeOffset.UtcNow.AddMinutes(10),
            Resource = "/users",
        }, token);
```

I see that notification url validation is done and I properly answer.

Approximately on 6th of December 2018 it stopped working. Than it get back to normal.
Some days ago it stopped working again.
Is there any interpretation of this error? Is this service anyhow stable?

**Comment by darrelmiller** [comment]
@sherlock1982 Would you be able to email me at darrel.miller@microsoft.com with the requestId that comes back in the error payload.  With that I can start investigating why you are seeing this change in behavior.

**Comment by RobinHerbots** [comment]
@darrelmiller, 

A bit off-topic, but why is the **created changetype** not supported for the **users resource**?
Is there another way to get notified when a new user gets created?

Btw, I have no problem with the subsciptions.  I can subscribe and get notified on update. (delete not tested)

**Comment by sherlock1982** [comment]
Thanks, It started working today. Looks like last two weeks many services of Office365 experienced issues and yesterday even Azure wasn't working.
