### ISSUE TITLE
Improvement: Extensions methods for DateTime and DateTimeOffset to DateTimeTimeZone

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#366]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.
- [x] Improvement suggestion, no reproduction provided

### Expected behavior
The DateTimeTimeZone entity is widely used accross the Graph and reflected in the dotnet SDK.
However it's properties are pure strings which allows for little validation and requires the consumer to do the serialization of these properties.
It'd be very interesting to have two extension methods to make people's lives simpler (and less prone to errors)
```CS
public static ToDateTimeTimeZone(this DateTime dateTime, TimeZone timezone): DateTimeTimeZone;
public static ToDateTimeTimeZone(this DateTimeOffset dateTimeOffset):DateTimeTimeZone;
```

**Comment by pwombwa** [comment]
@baywet Thanks for suggesting this improvement. We have added this to our backlog and we will enable it soon.

#952289

**Comment by michael-hawker** [comment]
It'd also be nice to have things go the other way where a `DateTimeTimeZone` object can become a `DateTimeOffset` value.  This makes it easier to format the result with ToString formatters.

```
public static DateTimeOffset ToDateTimeOffset(this DateTimeTimeZone dateTimeTimeZone);
```
