### ISSUE TITLE
Insight Used API

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/msgraph-sdk-dotnet#368]
The user Insights Used API is in preview for over 1,5 years now.
(https://docs.microsoft.com/en-us/graph/api/resources/insights-used?view=graph-rest-beta)
Any idea when this is going to production (v1.0)?

**Comment by MIchaelMainer** [comment]
I don't have an idea about when this API goes to the v1.0 endpoint.

**Comment by darrelmiller** [comment]
@ferronsw It is there in V1.0 also.  The docs just haven't be updated.

**Comment by ferronsw** [comment]
@darrelmiller that would be nice. I'm not seeing it yet, but I would keep an eye on it.

https://docs.microsoft.com/en-us/graph/api/resources/insights?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0

**Comment by darrelmiller** [comment]
@ferronsw Just a word of warning.  As it was never officially announced, it is quite likely to go away. fairly soon
