### ISSUE TITLE
Unhandled exception on a 401 response

### ISSUE THREAD

**Issue by alexfelton** [microsoftgraph/msgraph-sdk-dotnet#37]

**Comment by MIchaelMainer** [comment]
Thank you @alexfelton for bringing this to our attention.

**Comment by MIchaelMainer** [comment]
You can handle 401 errors by catching Microsoft.Graph.ServiceException, and checking the error.code. For example, if an invalid token was sent, you'd check for error.code == InvalidAuthenticationToken. 401s should be handled based on your implementation.
