### ISSUE TITLE
No way to clone all parts of an existing Team

### ISSUE THREAD

**Issue by dander11** [microsoftgraph/msgraph-sdk-dotnet#370]
### Expected behavior
Allow me to clone multiple parts of an existing Team to the new Team.

`var x = _graphServiceClient.Teams[id].Clone(TeamVisibilityType.Private, new[] {ClonableTeamParts.Channels, ClonableTeamParts.Apps, ClonableTeamParts.Settings},
                                    displayName: "testClone1", description: "testDesc");`

### Actual behavior
Only one part of the existing Team can be cloned.

`var x = graphServiceClient.Teams[id].Clone(TeamVisibilityType.Private,  ClonableTeamParts.Channels,
                displayName: "testClone1", description: "testDesc");`

It would be very helpful to specify all of the parts of the existing Team that we would like to clone. Just like you can with the http api here: [https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0#example](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0#example)

**Comment by MIchaelMainer** [comment]
@dander11 you can select the different enum flag parts like this:

```csharp
var x = _graphServiceClient.Teams[id].Clone(TeamVisibilityType.Private, ClonableTeamParts.Channels | ClonableTeamParts.Apps | ClonableTeamParts.Settings, displayName: "testClone1", description: "testDesc");
```
