### ISSUE TITLE
Sharepoint list item attachments

### ISSUE THREAD

**Issue by sergioacortes** [microsoftgraph/msgraph-sdk-dotnet#375]
Hi, 

We are facing a problem when we try to get the files / documents (attachments) to a Sharepoint List Item.
Is there any way to make the request, it is sopported or not?

If we expand the fields the property Attachments, the only thing we get as result is a property indicating that the Sharepoint list item has an attachments.

Is there any solution or workaround?

Hoping your kind answer.

**Comment by MIchaelMainer** [comment]
Please post this question to StackOverflow and use the microsoft-graph tag. Please make sure you add references to the documentation you used, code that you have tried, what  you expect to get, and what you actually observed. Please provide an http capture using a tool like Fiddler. After you post on StackOverflow, please provide a link in this issue to the StackOverflow issue.
