### ISSUE TITLE
DriveItem resource does not include checkout/checkin methods

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/msgraph-sdk-dotnet#379]
Per this stackoverflow post: https://stackoverflow.com/questions/54633802/how-do-you-check-out-and-check-in-listitems it appears that there are REST methods for DriveItem files missing from the SDK.

There may be others, of course, but in this 'Issue', I am requesting that the implementation team add the necessary methods for "checkout" and "checkin" that are apparently already available from the SharePoint Online service.

Checkout and Checkin functionality is required when editing files in a SharePoint library/list that has the "Require Check Out" setting.  Furthermore, explicit checkout/checkin is functionally required in some content management cases.

One would think these should be on ListItem objects, but the feedback thus far is that they are more relevant to the DriveItem object.  I would leave this up to the maintainers here, so long as the functionality becomes available.

Please don't hesitate to contact me for any details and/or further information.

**Comment by darrelmiller** [comment]
Hi @ajweber Those actions are currently only defined in the beta version of Graph.  The SDKs we generate are for the v1.0 release of Graph.  We are currently working on producing beta versions of the SDK also, but they are not available on a regular basis yet.  You will find a fairly recent beta release in the Releases section in GitHub.

**Comment by ajweber** [comment]
Thanks for the quick feedback on this, Darrel.  Is there any public info on timelines for the SDK and when the beta version of Graph will be promoted to production?  I'll update my stackoverflow post so others can find the info.

(Obviously, if there are some links with this info, I'll RTFM.)

Thanks again.

**Comment by ajweber** [comment]
I'm sorry for the tangent-post...I looked in Graph Explorer at the beta APIs and object/json information.  There appears to be a driveitem.ItemActivity property that can be selected/expanded in beta.  This has a lot of valuable information regarding edits.  However, it's missing actions specific to checkout/checkin/locking.

Some of it can be inferred, but it would be great if the (SharePoint) actions of CheckOut and CheckIn (and maybe even Cancel CheckOut) had explicit actions.  i.e. added here: https://docs.microsoft.com/en-us/graph/api/resources/itemactionset?view=graph-rest-beta

**Comment by darrelmiller** [comment]
@daspek  Do you know if there are any plans to add these actions to the ItemActivity?

**Comment by peombwa** [comment]
@ajweber To address your original question, this is now supported in our beta SDK https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Requests/Generated/DriveItemCheckinRequest.cs.

**Comment by ajweber** [comment]
I'm not clear on two things with this change:
1) How would we explicitly Check OUT the driveItem?  And how would you Cancel the Check Out instead of CheckIn?
2) How does the REST beta endpoint get promoted to production, and how does the beta of the SDK match-up with that?  Or is the beta of the SDK just new/updated code for the Prod endpoint at all times?
