### ISSUE TITLE
When will Version 1.13.0 released in NuGet?

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/msgraph-sdk-dotnet#382]
When will the version "1.13.0" released as a NuGet package?

The latest available package on NuGet is still the "1.13.0-preview".

**Comment by darrelmiller** [comment]
@habex-ch Unfortunately we had to rollback 1.13.0 due to a backward compatibility issue.  Expect to see a 1.14.0-preview this week and we plan to have a final release by the end of the month.  Is there a specific feature that you are waiting for?

**Comment by habex-ch** [comment]
Thank you for the Information. The release date is fine for me.

I'm creating a new Microsoft Team with a website-tab to the general channel. 

The best way would be the new create Team feature, but this is still beta. So I have to 
1. Create a Group
2. Create a Team for the Group
3. Get the Channel
4. Create a Tab in the Channel 

But for this workaround, I need the 1.13.0/1.14.0 release.
