### ISSUE TITLE
does it support beta version API?

### ISSUE THREAD

**Issue by lhp620** [microsoftgraph/msgraph-sdk-dotnet#39]
re

**Comment by ArieJones** [comment]
Yes, you just have to set the graph endpoint to https://graph.microsoft.com/beta it'll work. I already have a project that I am working on that utilizes it.

**Comment by MIchaelMainer** [comment]
Arie is correct that it will support the beta endpoint to the extent that the beta endpoint API intersects the v1.0 endpoint. With that said, the diff between the beta and v1.0 endpoint is not currently supported in this client library.
