### ISSUE TITLE
[Question] - Did Issue #184 Get implemented - Allow paging on Expand()?

### ISSUE THREAD

**Issue by chassq** [microsoftgraph/msgraph-sdk-dotnet#392]
Just wanted to know if the Expand() method ever got paging capabilities to allow us to bypass the 20 record limit? See #184  	

If not is this on the road map?

Thanks!!

**Comment by MIchaelMainer** [comment]
I think the linked question is more about whether the service API returns paging information. I just verified that the default page size for groups/expand is larger than 20. ttps://graph.microsoft.com/v1.0/groups?$expand=members

Additionally, I'm seeing the nextLink set when there are paged results still to be returned after this query:
https://graph.microsoft.com/v1.0/groups?$expand=members&$top=25

Now, what I don't know is whether all resources have same behavior.

**Comment by chassq** [comment]
Thanks @MIchaelMainer! We are currently working with beta and still see the 20 row limit for the Expand() function for the Users in Groups. Would you think this would be lifted once beta goes to v2.0 (or whatever the next version may be)?

**Comment by MIchaelMainer** [comment]
I'm not seeing the same results as you when targeting the beta endpoint. Can you confirm whether we are looking at the same issue.

![image](https://user-images.githubusercontent.com/8527305/53753721-c8ebe580-3e66-11e9-9b9e-cd28549cb6c4.png)

**Comment by chassq** [comment]
Hmmm, that API call would pull back 25 groups but how many members were you limited too, per group, would be the question as the Expand was on Members I think.

**Comment by MIchaelMainer** [comment]
Aww, thank you for clarifying. I don't think it is reasonable to page through expansion results.  A paged expansion would result in each expanded /members collection requiring its own nextLink. The best way to approach this would be to get the collection of /groups, then access the /members collection on each group with a separate call and also follow the nextLink to get additional pages of members.

**Comment by chassq** [comment]
Thanks Michael, I would like to suggest you reconsider allowing a TOP on the Expand and implementing paging. The reason is that a good number of calls might get away with one call to the Graph server vs several, unless of course separate calls are being made under the covers anyway. I would liken this to doing an Include in the Entity Framework Core world whereby I could pull thousands of records for a child table for instance if I so chose (my call based on perf and the workload). Maybe the graph world is different but I think it is the developer who should be able to determine how many trips to the server vs the number of records returned performance ratio. In any case a arbitrary number of 20 max records is way too small of a limit. Consider raising the limit at least please!

Thanks for your help and time. Much appreciated!

**Comment by MIchaelMainer** [comment]
Thank you for your feedback. I see where the benefit would be to at least see which groups don't require further expansion on the members in a single call. I don't kow if OData supports paging on expansions. 

The best place for requesting changes to the service APIs are on https://officespdev.uservoice.com/. 
Again, thank you for your feedback.

**Comment by chassq** [comment]
OK and thanks Michael! Much appreciated!
