### ISSUE TITLE
Is there a version of this nuget package for the beta Graph API?

### ISSUE THREAD

**Issue by jnevins-gcm** [microsoftgraph/msgraph-sdk-dotnet#396]
I can see there is a branch with updated models, but is there a nuget package for it published anywhere? nuget.org or myget?

**Comment by MIchaelMainer** [comment]
We will add one to a feed soon. I'm working on it here: https://github.com/MIchaelMainer/msgraph-sdk-dotnet-beta. This is up to date as of a week ago. 

Go ahead and clone it and `dotnet pack` to get a package.

**Comment by jnevins-gcm** [comment]
Thanks! Is there an appveyor NuGet feed url I can point to directly in the meantime?

**Comment by MIchaelMainer** [comment]
No, there isn't. There's also this beta package from December.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.12.0-beta

**Comment by MIchaelMainer** [comment]
Now there is. 

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet
https://www.nuget.org/packages/Microsoft.Graph.Beta/0.1.0-preview
