### ISSUE TITLE
ServiceException.StatusCode internal

### ISSUE THREAD

**Issue by ksikorsk** [microsoftgraph/msgraph-sdk-dotnet#401]
Currently the ServiceException.HttpStatus is internal:
```cs
public System.Net.HttpStatusCode StatusCode { get; internal set; }
```
We would like to leverage this type in our extensions for Calling scenarios.  Can the setter be made pubic?

**Comment by ksikorsk** [comment]
Same with headers please:
```cs
public System.Net.Http.Headers.HttpResponseHeaders ResponseHeaders { get; internal set; }
```

**Comment by darrelmiller** [comment]
I don't see any harm in allowing this.  /cc @MIchaelMainer

**Comment by MIchaelMainer** [comment]
We can do.

**Comment by darrelmiller** [comment]
@ksikorsk If you wanted to send a PR with that change, it might land faster  ;-)

**Comment by ksikorsk** [comment]
Easy enough... sounds good.  When do you plan on releasing another version containing this change?

**Comment by ksikorsk** [comment]
Done!

**Comment by ksikorsk** [comment]
Thanks for the review on the PR.  It doesn't appear that I can merge, I assume that only you guys can do this?  When do you plan on releasing another version containing this change?

**Comment by pwombwa** [comment]
@ksikorsk, we have included this change as part of [Microsoft.Graph.Core v1.15.0-preview.1](https://www.nuget.org/packages/Microsoft.Graph.Core). You can verify the same before we close this issue.

**Comment by ksikorsk** [comment]
Thanks... will validate today!

**Comment by ksikorsk** [comment]
Perfect... thanks all!
