### ISSUE TITLE
Microsoft.Graph.User not being populated by synchronous call to Microsoft.Graph.GraphServiceClient

### ISSUE THREAD

**Issue by adamasmar** [microsoftgraph/msgraph-sdk-dotnet#402]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

Microsoft.Graph.User should be populated by synchronous call to a Microsoft.Graph.GraphServiceClient.

https://docs.microsoft.com/en-us/graph/overview#popular-requests

### Actual behavior

Microsoft.Graph.User is not being populated since upgrading Microsoft.Graph/Microsoft.Graph.Core to versions 1.13.0-preview or 1.14.0-preview from 1.12.0.

### Steps to reproduce the behavior

Graph client is created:
```csharp
_graphClient = new GraphServiceClient(
    "https://graph.microsoft.com/v1.0/",
    new DelegateAuthenticationProvider(
        async requestMessage =>
        {
            requestMessage.Headers.Authorization =
                new AuthenticationHeaderValue("bearer", await GetTokenForUserAsync());
        }));
return _graphClient;
```

Token is returned for `GetTokenForUserAsync()`: 
```csharp
var app = App.PublicClientApp;
var accounts = await app.GetAccountsAsync();
var enumerable = accounts as IAccount[] ?? accounts.ToArray();
_userToken = app.AcquireTokenSilentAsync(App.Scopes, enumerable.FirstOrDefault())
    .Result.AccessToken;
```

User is never populated (application hangs when it is called synchronously):
```csharp
var userInfo = _graphClient.Me.Request().GetAsync().Result;
```

Again, this behavior did not exist in version 1.12.0.

**Comment by darrelmiller** [comment]
This is an unfortunate side-effect of using .Result within certain syncronization contexts, combined with the fact that we now do authorization in a delegating handler.  I believe you can resolve the problem by doing await on app.AcquireTokenSilentAsync inside the GetTokenForUserAsync.

This whole process should get a lot easier once our [Authorization Providers](https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth) come out of preview.

**Comment by adamasmar** [comment]
Unfortunately, that hangs as well.

**Comment by MIchaelMainer** [comment]
What type of application and in which framework are you using? I'm using https://github.com/microsoftgraph/console-csharp-connect-sample with 1.14.0-preview and can get back the user:

var user = graphClient.Me.Request().GetAsync().Result; [link](https://github.com/microsoftgraph/console-csharp-connect-sample/blob/master/console-csharp-connect-sample/Program.cs#L36).

Can you capture Fiddler trace of the request and response for the /GET user call?

**Comment by adamasmar** [comment]
This is a WinForms application in .NET Framework 4.7.1.

Request:
```
GET https://graph.microsoft.com/v1.0/me HTTP/1.1
SdkVersion: Graph-dotnet-1.13.0
Cache-Control: no-store, no-cache
Authorization: [bearer .......]
Host: graph.microsoft.com
```
Response:
```
HTTP/1.1 200 OK
Cache-Control:private
Transfer-Encoding:chunked
Content-Type:application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
request-id:901c023c-d62b-4817-ae06-bdf2e82eb29f
client-request-id:901c023c-d62b-4817-ae06-bdf2e82eb29f
x-ms-ags-diagnostic:
{
      "ServerInfo":{
          "DataCenter":"South Central US",
          "Slice":"SliceC",
          "Ring":"5",
          "ScaleUnit":"003",
          "RoleInstance":"AGSFE_IN_3",
          "ADSiteName":"SCU"
      }
}
OData-Version:4.0Duration:73.4876Strict-Transport-Security:max-age=31536000
Date:Wed,
13Mar 2019 18:46:46GMT

16d{
   "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users/$entity",
   "businessPhones":[

   ],
   "displayName": "[Returns Display Name]",
   "givenName":"[Returns Given Name]",
   "jobTitle":null,
   "mail":"[Returns E-mail Address]",
   "mobilePhone":null,
   "officeLocation":null,
   "preferredLanguage":"en-GB",
   "surname":"[Returns Surname]",
   "userPrincipalName":"[Returns User Principal Name]",
   "id":"[Returns GUID]"
}0
```

**Comment by darrelmiller** [comment]
@adamasmar  I suggest getting rid of the .Result in the originating call.  The call is being made on the UI thread which is being blocked by the .Result and when MSAL tries to show the Login dialog it will hang because the UI thread is blocked.  I don't know why this worked in 1.12.0.

**Comment by adamasmar** [comment]
OK, that worked! There was some logic in our code that is using information obtained from the .Result part of the call in the Load method. But refactoring everything around the execution of the UI thread did the trick.

Well I am happy this is solved, I am still baffled as to how this worked in 1.12.0? Oh well ... thanks anyways!

**Comment by darrelmiller** [comment]
@adamasmar Thanks for letting us know you were able to resolve the problem.  We will definitely keep our eyes open for what might have changed in 1.12.0 to make this issue surface.
