### ISSUE TITLE
[Question] How to get content type of user photo?

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoftgraph/msgraph-sdk-dotnet#403]
I use msgraph SDK to get user photo but seems can only get an Stream typed photo without content type. Here is the following code:
public async Task<string> GetPhotoAsync()
        {
            var photoRequest = this._graphClient.Me.Photos["48x48"].Content.Request();
            var originalPhoto = await photoRequest.GetAsync();
            var photoUrl = Convert.ToBase64String(ReadFully(originalPhoto));
            return string.Format("data:{0};base64,{1}", ***contentType**?*, photoUrl);
        }

which content type equals:
![image](https://user-images.githubusercontent.com/16643193/54258940-2090fc00-459f-11e9-84c1-886d10144fd4.png)

I expect the result string looks like the following:
"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAEB..."

Is there any API to get content type of this photo?

**Comment by darrelmiller** [comment]
Will be resolved by #457
