### ISSUE TITLE
[Question or issue] Cannot retrieve specific sized contact photo

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoftgraph/msgraph-sdk-dotnet#404]
Issue:
Could not get a 48x48 sized photo for a target contact with GET /me/contacts/{id}/photos/{size}. But the GET /me/contacts/{id}/photo works.
URL: https://graph.microsoft.com/v1.0/me/contacts/AAMkAGEwMDg4MTVlLTVjYzUtNGRmNS1hYTJkLTI3NjNmM2Q3MDA3ZABGAAAAAABw-WbciOIvSZejmvtHK98CBwCa0ISfUgx1RYIZgSZZYh9LAAAAAAEOAACa0ISfUgx1RYIZgSZZYh9LAAAAtIe3AAA=/photos/48x48/$value
Error:
{
"error": {
"code": "BadRequest",
"message": "Unsupported segment type. ODataQuery: /users/6f7a186f-e0fd-44aa-966a-0df25e14b99d/contacts/AAMkAGEwMDg4MTVlLTVjYzUtNGRmNS1hYTJkLTI3NjNmM2Q3MDA3ZABGAAAAAABw-WbciOIvSZejmvtHK98CBwCa0ISfUgx1RYIZgSZZYh9LAAAAAAEOAACa0ISfUgx1RYIZgSZZYh9LAAAAtIe3AAA=/photos/48x48/$value",
"innerError": {
"request-id": "ed0807bd-6541-4900-930b-b31ac31f8d3c",
"date": "2019-03-13T10:16:13"
}
}
}
Could you help me find out whether there will be a way to get specific sized contact photo with msgraph SDK?

**Comment by MIchaelMainer** [comment]
The client library current doesnt support requesting a photo of a specific size. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/404

**Comment by FiromsaA** [comment]
@DingmaomaoBJTU you can only specify the size of photos for users and groups stored in Azure Active Directory, it wont work for contacts in an outlook mailbox.
https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0

**Comment by FiromsaA** [comment]
@MIchaelMainer the client library does support requesting a photo of a specific size for active directory users and groups, see below example.

```csharp
  static async Task<Stream> GetSpecificPhoto(GraphServiceClient graphServiceClient)
        {
            var stream = await graphServiceClient.Me.Photos["48x48"].Content.Request().GetAsync();
            return stream;
        }
```
