### ISSUE TITLE
Assign User to Application (AppRoleAssignment)

### ISSUE THREAD

**Issue by miyavidechu** [microsoftgraph/msgraph-sdk-dotnet#406]
We need to be able to assign a user to an application.
Earlier we've used the Azure AD Graph (Microsoft.Azure.ActiveDirectory.GraphClient) with servicePrincipal and appRoleAssignment.

We can see it's currently in the beta version of Graph API but want to know if there is any way to do this in the current version of Microsoft Graph (using this library)? 
Or do we have to wait for it to be released? In that case, how long might that be?

**Comment by MIchaelMainer** [comment]
Can you try this out https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet and give us feedback?

**Comment by miyavidechu** [comment]
I've switched to using the beta, but I'm running into an error; "Object reference not set to an instance of an object" when I try to add the appRoleAssignment to the user.

I've been troubleshooting and it looks to me as if user.AppRoleAssignments is throwing a NullReferenceException.


Code below;

    public async Task AddUserToApplication(string appId, string roleId, User user)
    {
        try
        {
            var req = _graphClient.Users[user.Id].Request();

            var appRole = new AppRoleAssignment()
            {
                ResourceId = Guid.Parse(appId),
                PrincipalId = Guid.Parse(user.Id),
                AppRoleId = Guid.Parse(roleId)
            };

            user.AppRoleAssignments.Add(appRole);

            await req.UpdateAsync(user);
        } catch (Exception e)
        {
            _log.Log(LogLevel.Error, "Error when adding user to application; " + e.Message);
        }
    }

Should I post this as a new issue on https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet instead?

**Comment by MIchaelMainer** [comment]
Yes, for beta only client library issues, please post in the beta repo. The issue you see is because AppRoleAssignments property is null. You'll need to assign an IUserAppRoleAssignmentsCollectionWithReferencesPage to that property before you add the appRole. Any questions about AppRoleAssignments in particular I won't be able to answer. That might be a better question posted to StackOverflow.

**Comment by miyavidechu** [comment]
Thank you, I'll try it out and if I run into more problems I'll post the issue on the beta page.
