### ISSUE TITLE
Lack of Filter and Expand

### ISSUE THREAD

**Issue by ArieJones** [microsoftgraph/msgraph-sdk-dotnet#41]
Using the latest batch of code it looks like there are missing instances of Filter and Expand that deviate from the previous version. 

For instance, I can no longer perform something simple like 

var usersQuery = await graphService.Users.Request().Filter("startswith(displayName, '" + id + "')").GetAsync();

Filter is no longer available on the Users object. I see that most of these object are generated... so is this going to be corrected before this next release... which I would hope would be soon. 

Thanks
AJ

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. Are you using the code from the Nuget package, or from this master branch?

**Comment by ArieJones** [comment]
We're using the code from master branch as there was an issue with the nuget package previously and we are working with some of the beta api features.

**Comment by shiftylogic** [comment]
Are you strictly using the code checked into this repo or generating your own code using the code generator?

**Comment by ArieJones** [comment]
Just building the checked in code....nothing more than that.

**Comment by shiftylogic** [comment]
Latest commit? If not, what is the commit id you are on?

**Comment by ArieJones** [comment]
I'll ping the people working on it to see what they are on..

**Comment by ArieJones** [comment]
Looks like 090e48a7b5e9df59571240c64dba2ec5e162d8cb is what we are currently using... from master..

**Comment by MIchaelMainer** [comment]
I've added a test case where this works:
`var usersQuery = await graphClient.Users.Request().Filter("startswith(displayName,'A')").GetAsync();`

This is now working as expected. Code generation has incorrectly masked filter and expand. Please update to the latest commit of master.
