### ISSUE TITLE
AuthenticaionProvider is ignored if it's passed along with HttpProvider

### ISSUE THREAD

**Issue by kdmojdehi** [microsoftgraph/msgraph-sdk-dotnet#417]
### Expected behavior

When you pass in an authentication provider to the GraphServiceClient constructor along with a custom HttpProvider, it should still invoke the passed down authenticaion provider.

### Actual behavior

No calls to your authenticaion provider is made in this scenario (unless you manually invoke it in your custom Http Provider!)

### Steps to reproduce the behavior

Initialize a new instance of GraphServiceClient with both a custom IAuthenticationProvider and a custom IHttpProvider. Then, put a break point at AuthenticateRequestAsync of your IAuthenticationProvider. Now try to get list of users (or basically make any request). You will note that your IAuthenticationProvider has been totally ignored.

If you look at the implementation of the source code of HttpProvider (which is used by default when you don't pass and HttpProvider to the GraphServiceClient) you will note that it will add a message handler in its pipeline that extracts the IAuthenticationProvider from the HttpRequest! I believe that the the library should make no assumptions/constraints on how a custom HttpProvider is implemented.

**Comment by pwombwa** [comment]
Thank you for reporting this issue. We have found what's causing the issue and are working on a fix to support this scenario.

**Comment by pwombwa** [comment]
@kdmojdehi , We have released a fix for this issue as part of [release 1.14.1](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.14.1). Give it a try and let us know if addresses your scenario.
