### ISSUE TITLE
Missing DeleteAsync() for Attachments in Messages / Events

### ISSUE THREAD

**Issue by Coster** [microsoftgraph/msgraph-sdk-dotnet#418]
### Actual behavior

in Microsoft.Graph 1.14 we doesn't found a function for deleting attachments from events or messages. 

we are searching for something like the existing function for messages itself or event => Request().DeleteAsync() 

is this feature still missing?

**Comment by darrelmiller** [comment]
Hi Coster, 

Can you show us exactly which entity you are trying to delete?  The is a method on an attachement to delete it.

```csharp
  graphServiceClient.Me.Messages["someid"].Attachments["someid"].Request().DeleteAsync()
```

**Comment by Coster** [comment]
Thanks - thats works!

i used this path => client.Users["MailAddr"].Calendar.Events["EventId"].Attachments.Request().AddAsync("attachment");
for adding a attachment. 

and so i try with this =>
client.Users["MailAddr"].Calendar.Events["EventId"].Attachments.Request() ... ? 
but this has not DeleteAsync() method. 

my mistake, sorry.

**Comment by darrelmiller** [comment]
Yes, unfortunately we don't have support for deleting an entire collection.  You need to loop through the attachments and delete each one.
