### ISSUE TITLE
Upload error picture user with application permission

### ISSUE THREAD

**Issue by jodur** [microsoftgraph/msgraph-sdk-dotnet#424]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

I used the application persmission flow for autentication, with API persmissions User.ReadWrite.All

I am using to following code to upload a picture in a picturebox (Sorry i am an old VB-guy, still building small tools with old windows forms)

```
Dim pic = New MemoryStream
        PictureBox1.Image.Save(pic, Imaging.ImageFormat.Jpeg)

        Dim Photo = Await graphServiceClient.Users(TxtEmail.Text).Photo.Content.Request().PutAsync(pic)
```

When executing this code is get the following exception:

```
Microsoft.Graph.ServiceException: 'Code: ErrorItemNotFound
Message: The specified object was not found in the store., No photo with class 'IPM.UserPhoto.Preview' exists.

```
### Actual behavior

Exception occurs:

```
Microsoft.Graph.ServiceException: 'Code: ErrorItemNotFound
Message: The specified object was not found in the store., No photo with class 'IPM.UserPhoto.Preview' exists.

```

### Steps to reproduce the behavior

I am able to read the user picture and display it on the form with the following code:

 ```
Dim Photo = Await graphServiceClient.Users(TxtEmail.Text).Photo.Content.Request().GetAsync()
'Show retrieved picture
PictureBox2.Image = System.Drawing.Image.FromStream(Photo)
```

Writing back the stream result, i got from reading it, results in the same exception, so a faulty stream could be excluded.

**Comment by jodur** [comment]
Is this perhaps related to  :[https://github.com/microsoftgraph/microsoft-graph-docs/issues/3751](https://github.com/microsoftgraph/microsoft-graph-docs/issues/3751)

**Comment by jodur** [comment]
Why is this closed? Issue is still there!

**Comment by peombwa** [comment]
@jodur This is a service issue and it's already being tracked in https://github.com/microsoftgraph/microsoft-graph-docs/issues/3751.
