### ISSUE TITLE
User Insights Used "ErrorAccessDenied"

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/msgraph-sdk-dotnet#425]
I'm trying to access https://graph.microsoft.com/v1.0/me/insights/used/, but when I do that I get an ErrorAccessDenied error. 

```
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again.",
        "innerError": {
            "request-id": "048a39a8-db66-4f04-ba0c-5d52d79bb709",
            "date": "2019-04-09T06:59:13"
        }
    }
}
```
I've granted delegated permissions like described in the docs:

> Delegated (work or school account) | Sites.Read.All,

**Comment by MIchaelMainer** [comment]
Thank you for reporting this issue. This appears to be an issue with either your configuration or the service. This repository is specific to the .Net client library. Questions about the service API or configuration should be posted to StackOverflow and tagged with microsoft-graph. Please reopen if we have closed this issue in error.
