### ISSUE TITLE
Not able to load the file for the latest version SDK(1.1.0.0)

### ISSUE THREAD

**Issue by VitorX** [microsoftgraph/msgraph-sdk-dotnet#43]
FileName=Microsoft.Graph, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  FusionLog=""
  HResult=-2146233318
  Message=Could not load file or assembly 'Microsoft.Graph, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by chrispatrick** [comment]
I'm getting a similar issue, except with the core libarary: 

`Could not load file or assembly 'Microsoft.Graph.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.`

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. We are working on getting this fixed now.

**Comment by NelsonLamprecht** [comment]
Same issue after installing the ms.graph 1.1.0 package (which installed the 1.2.0) core.
Bump.

**Comment by MIchaelMainer** [comment]
Updated the client libraries, and the containing nuget package, to address this. Please reopen this issue if this isn't resolved.
https://www.nuget.org/packages/Microsoft.Graph/1.1.1
https://www.nuget.org/packages/Microsoft.Graph.Core/1.2.1
