### ISSUE TITLE
Telemetry handler

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#430]
[spec pr](https://github.com/microsoftgraph/msgraph-sdk-design/pull/11/files), [spec](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/TelemetryHandler.md) 	 
[AB#7332](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7332)

**Comment by peombwa** [comment]
This should capture pipeline order #440 and accurately capture feature flags #439.

**Comment by MIchaelMainer** [comment]
Consider https://devblogs.microsoft.com/dotnet/opentelemetry-net-reaches-v1-0/
