### ISSUE TITLE
Compression handler

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#431]
https://github.com/microsoftgraph/msgraph-sdk-design/pull/12

**Comment by pwombwa** [comment]
Add in [Microsoft.Graph.Core v1.15.0-preview.1](https://www.nuget.org/packages/Microsoft.Graph.Core).
https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/v1.15.0-Preview.1
