### ISSUE TITLE
Refactor core into its own GitHub repo

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#433]
Microsoft.Graph and Microsoft.Graph.Core are in the same solution. Microsoft.Graph has a project reference to Microsoft.Graph.Core. We want to decouple these versions and the corresponding tests as we expect to update them independently. 

More info to follow.

**Comment by anubi** [comment]
Yeah, I'm new to this library. I didn't think I'd need Microsoft.Graph package to use Microsoft.Graph.Core, but you definitely do.

**Comment by MIchaelMainer** [comment]
Hello @anubi 

You don't need Microsoft.Graph to use Microsoft.Graph.Core. Microsoft.Graph.Core does not have a dependency on Microsoft.Graph.

https://www.nuget.org/packages/Microsoft.Graph.Core.

Now then, Microsoft.Graph **does have** a dependency on Microsoft.Graph.Core.

**Comment by peombwa** [comment]
We will also deprecate MSTests in favor of XUnit tests.
