### ISSUE TITLE
Department property not populated even though value exists

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/msgraph-sdk-dotnet#434]
### Expected behavior
Returns the department field correctly when querying users filtered by givenName.

### Actual behavior
Department property is not populated on User. The displayName and givenName is correctly.

### Steps to reproduce the behavior
version 1.10.0 . I updated to 1.14.0 and still see same issue.

`var userResults = await graphClient.Users.Request().Select("displayName, givenName, department").Filter("givenName eq '" + givenName + "'").GetAsync();`

Also tried it with as per @darrelmiller  suggestion. it does remove the spaces in the requestUri output, but still null for department.
`var userResults = await graphClient.Users.Request().Select(u=>new { u.DisplayName, u.Department, u.GivenName }).Filter("givenName eq '" + givenName + "'").GetAsync();` 

When breaking in and using GetHttpRequestMessage() on it the Request Uri is. In Graph Explorer signed in as this user it returns a department.

`RequestUri = {https://graph.microsoft.com/v1.0/users?$select=displayName, givenName, department&$filter=givenName eq 'megan'}`

When I inspect the user collection returned and the user object the department is null. But in additional data its there...but no value for it.
```
AdditionalData = Count = 1
[0] = {[department, ]}
```

Can also repo this with other properties like Job Title too.

**Comment by jthake-msft** [comment]
This could be a permissions thing. I have these permissions 
`Mail.Read Mail.Send openid profile User.Read User.ReadBasic.All People.Read.All`

As unforutnately I cannot repo this and maybe the app when I updated to use `User.ReadBasic.All People.Read.All` from `User.Read` hadn't taken effect straight away.

**Comment by MIchaelMainer** [comment]
This is strange. I wonder if department was serialized in the response as `null`, we don't deserialize `null` into a property, but then since the property exists, we stuff it into AdditionalData. You wouldn't happen to have a capture of this would you?

**Comment by darrelmiller** [comment]
@jthake-msft Good call on the ReadBasic thing.  I wonder if that is the issue with the Javascript issue.
