### ISSUE TITLE
Retry handler returns http status code 415 for POST requests

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet#435]
### Expected behavior
Retry handler should return http status 202 for POST requests after retrying 429 responses.

### Actual behavior
Retry handler returns http status 415 - missing or empty content type header - when retrying 429 responses.

### Steps to reproduce the behavior
Send multiple post requests (~30) to graph service.

**Comment by Misiu** [comment]
@pwombwa I have the exact same behavior when trying to send multiple emails.
Here is my test code:

```
var mails = new List<Message>();

for (int j = 0; j < 50; j++)
{
    var email = new Message
    {
        Body = new ItemBody
        {
            Content = "TEst mail",
            ContentType = BodyType.Html,
        },
        Subject = "Test",
        ToRecipients = recipientList,
        Attachments = att
    };
    mails.Add(email);
}

var tasks = new List<Task>();
foreach (var message in mails)
{
    tasks.Add(SendMail(graphClient, message));
}

await Task.WhenAll(tasks.ToArray());

private async Task SendMail(IGraphServiceClient graphClient, Message message)
{
    await graphClient.Users["test@example.onmicrosoft.com"].SendMail(message, true).Request().WithMaxRetry(10).PostAsync();
}
```

Im Fiddler I get `202`, then `429` and finally `415`:
![graph_exception2](https://user-images.githubusercontent.com/1741838/56194951-4002c500-6034-11e9-8c31-6710c4fa65a9.png)

I'm adding `WithMaxRetry` to each request, shouldn't this handle throttling and retrying?

**Comment by pwombwa** [comment]
@Misiu, our retry handler ignores the `Content-Type` header when retrying 429 responses. This has been fixed and it will be available in v1.15.0.

**Comment by Misiu** [comment]
@pwombwa when is 1.15.0 expected? I don't see any milestone with that number.
1.14.0 was released in the middle of March.

**Comment by pwombwa** [comment]
@Misiu We've released [Microsoft.Graph.Core v1.15.0-preview.1](https://www.nuget.org/packages/Microsoft.Graph.Core) which fixes this issue. Try it out and let us know if it addresses your scenario before we close this issue,

**Comment by Misiu** [comment]
@pwombwa I've tried the new version, but when I tried sending 40 emails at once I got 202 for some requests, 429 for some and 408 for some:
![graph_408](https://user-images.githubusercontent.com/1741838/56562865-bc545580-65aa-11e9-87f6-ac9b18d05c4f.png)

**Comment by darrelmiller** [comment]
@Misiu Thanks for the detailed feedback, we have a theory on why this is happening and are working on a fix.

**Comment by pwombwa** [comment]
@Misiu We've fixed this issue as part of [Microsoft.Graph.Core 1.15.0-preview.2](https://www.nuget.org/packages/Microsoft.Graph.Core/1.15.0-preview.2) and all requests should now succeed with status 202. Give it a try and let us know if it addresses your scenario.

**Comment by Misiu** [comment]
@peombwa sorry for the late reply. I've tested the latest release and in my case, it works fine. Thank You  😉
