### ISSUE TITLE
HttpProvider working only with "1.0"

### ISSUE THREAD

**Issue by VKAlwaysWin** [microsoftgraph/msgraph-sdk-dotnet#438]
[HttpProvider.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph.Core/Requests/HttpProvider.cs) ignores Base Url that we set for GraphServiceClient and works only with v1.0.

Please respect Base url from GraphServiceClient or add extra property for HttpProvider.cs to pass beta inside.
### Expected behavior
1. It should work with /beta endpoint as well.

### Actual behavior
1. Forcing 1.0 in next row:
this.httpClient = GraphClientFactory.Create("v1.0", GraphClientFactory.Global_Cloud, handlers);

**Comment by pwombwa** [comment]
@VKAlwaysWin All requests should be sent to the specified base url in [GraphServiceClient](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs#L50).
 
The base url set on httpClient in HttpProvider is not being used at the moment - it's part of an ongoing wotk to full intergrate [GraphClientFactory ](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/GraphClientFactory.md) in our SDK. We set absolute urls on HttpRequestMessage with the base url set on GraphServiceClient and call HttpProviders's SendAsync method.

**Comment by VKAlwaysWin** [comment]
Thank you for a response, I had feeling that we are missing support for beta. Closing now.

FYI, 
For particular my case I was able to sent request to Beta using BaseRequest.cs, because we are using https://docs.microsoft.com/en-us/graph/api/channel-post-chatmessage?view=graph-rest-beta .

Code snippet:
`var baseRequest = new BaseRequest($"https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages", _graphServiceClient) { Method = "POST", ContentType = "application/json" };`
_graphServiceClient is GraphServiceClient with provided DelegateAuthenticationProvider.

and then:
`var result = await baseRequest.SendRequestAsync(message, cancellationToken);`
