### ISSUE TITLE
Add extension method for managing featureflags

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#439]
We need to be able to incrementally add feature flags. Assignments clears existing flags.

`featureFlags = FeatureFlag.RetryHandler` will clear existing flags like `FeatureFlag.RedirectHandler`

`featureFlags = featureFlags.Add(FeatureFlag.RetryHandler)` should result in adding the flag to the existing flag set.

- [ ] Add the FeatureFlagExtension.Add extension method for adding feature flags.
- [ ] Update existing flag assignments to use the extension.

**Comment by peombwa** [comment]
This is covered by #430.
