### ISSUE TITLE
Capture handler pipeline order

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#440]
We should consider what happens once developers start adding their own handlers or changing the order of our default handlers. Handler order can impact the client, as well as misbehaving handler. To help us understand the environment when customers report bugs we need a mechanism to capture:

- [ ] information on handler order.
- [ ] the existence of custom handlers in the pipeline.

**Comment by peombwa** [comment]
This is covered by #430.
