### ISSUE TITLE
RetryHandler use time limit instead of count limit

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#441]
Per Darrell B. -- Retry counts results in widely differing experiences based on the length of the retry-after value returned from the server. This means, 3 retries of one second results in a different outcome versus 3 retries of 10 minutes. '

User experiences are affected by time of, not counts of the retry.

**Comment by peombwa** [comment]
Introduce retry time variance per request.
