### ISSUE TITLE
Build and release pipeline automation for .Net

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#444]
- [ ] Gated release for core service library.
- [ ] Gated release for v1.0 service library.
- [ ] Gated release for beta service library.
- [ ] Release notes extracted from commit messages since last release.
- [ ] Insert package release notes from build pipeline.

998924 
[AB#7328](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7328)

**Comment by peombwa** [comment]
Build and release pipeline will be automated using yaml files that will reside in core and service library repositories.
