### ISSUE TITLE
Tracking changes to users/groups

### ISSUE THREAD

**Issue by mscherban-mars** [microsoftgraph/msgraph-sdk-dotnet#446]
Hi guys,
I call delta queries for this objects and it works well.
But how can I get changes when Group's membership collection is changed? For example, user added to the group. I have no changes to group and no changes to user.

Do you have any solutions?
Thanks a lot

 
[AB#7324](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7324)

**Comment by darrelmiller** [comment]
@mscherban-mars Are you saying that your delta query is not returning those changes after they happen, or are you asking how you can be notified of changes?  The notification can be done via a webhook subscription https://docs.microsoft.com/en-us/graph/webhooks

**Comment by MIchaelMainer** [comment]
Closing due to no response.
