### ISSUE TITLE
HttpProvider is not thread safe.

### ISSUE THREAD

**Issue by ksikorsk** [microsoftgraph/msgraph-sdk-dotnet#449]
The HttpProvider uses a singleton to store the DefaultHttpHandler factory.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/492188c7137c57b61e59559294347c3b0bf89f0c/src/Microsoft.Graph.Core/Requests/HttpProvider.cs#L64

So if I create multiple instances concurrently with different `HttpMessageHandler` parameters HttpProvider does not guarantee that the right one is added to the underlying HttpClient.

### Expected behavior

The specified `HttpMessageHandler` should be used at all times.  Singletons are not friendly for concurrency, so should be avoided at all costs.

### Actual behavior

There is a race condition between setting the DefaultHttpHandler and creating the underlying HttpClient with the correct pipeline.

### Steps to reproduce the behavior

Here is a unit test I used to verify the behaviour.  In this unit test I set the authorization header to match the users name.  I then expect that the validation message handler has the same authorization header that I provided in the authentication provider.

What I see is a `Assert.AreEqual(entity.DisplayName, message.Headers?.Authorization?.Parameter);` failure.

```cs
/// <summary>
/// HTTP provider should work with custom message handlers concurrently.
/// </summary>
/// <returns>
/// A <see cref="Task"/> representing the asynchronous unit test.
/// </returns>
[Test]
public async Task HttpProviderShouldWorkConcurrentlyAsync()
{
    var tasks = Enumerable.Range(1, 50).Select(index =>
    {
        return Task.Run(async () =>
        {
            var entity = new User
            {
                Id = index.ToString(),
                DisplayName = Guid.NewGuid().ToString(),
            };

            var authProviderTriggered = 0;
            var authProvider = new DelegateAuthenticationProvider(message =>
            {
                authProviderTriggered++;
                message.Headers.Authorization = new AuthenticationHeaderValue("bearer", entity.DisplayName);
                return Task.CompletedTask;
            });

            var validationHandlerTriggered = 0;
            var validationHandler = new MockMessageHandler(message =>
            {
                validationHandlerTriggered++;
                Assert.AreEqual(entity.DisplayName, message.Headers?.Authorization?.Parameter);
                Assert.AreEqual("https://test/users", message.RequestUri.AbsoluteUri);
            });

            var httpProvider = new HttpProvider(
                validationHandler, // breaking change required after version >= 1.13
                true,
                new CommsSerializer(pretty: true));

            var client = new GraphServiceClient("https://Test", authProvider, httpProvider);

            var resultingCall = await client.Users.Request().AddAsync(entity).ConfigureAwait(false);
            Assert.IsNull(resultingCall);
            Assert.AreEqual(1, validationHandlerTriggered);
            Assert.AreEqual(1, authProviderTriggered); // For some reason auth provider is raised twice.
        });
    });

    await Task.WhenAll(tasks).ConfigureAwait(false);
}
```

**Comment by ksikorsk** [comment]
Also version 1.15.0-preview.1

**Comment by darrelmiller** [comment]
@ksikorsk Thank you for reporting this.  While I accept that that this is a scenario we should protect against, can you confirm that it isn't a normal scenario for you to be rapidly creating GraphServiceClient instances with different message handler pipelines?  GraphServiceClient is intended to be a long lived service and not frequently created.

Unfortunately we are in an awkward transitional state trying to move away from the HttpProvider design whilst trying to also take advantage of the new factory and middleware and maintain backward compatibility.  Sadly we dropped the ball on backward compatibility on some of the extensibility scenarios.

Peter has a pending PR to address some of the issues you have reported.  I need to verify the impact on this scenario.

**Comment by ksikorsk** [comment]
Our unit tests all run concurrently, and many of them create an instance of GraphServiceClient with it's own ValidationMessageHandler (so we can mock response).  It's going to be a fairly big hit to make them all run synchronously.  You're saying you're in a transition period?  Is there an alternate mechanism I should be using to inject a message handler into the HttpClient?  This was working a couple versions ago, why the change?

I will create our own implementation of IHttpProvider to mitigate this issue and the other.  I'm surfacing these issues so you are aware of the limitations.

**Comment by darrelmiller** [comment]
@ksikorsk That scenario makes a lot of sense and reassures me that it isn't actually a production scenario :-)
Peter and I just discussed this and we are going to move the static properties into an optional properties of the static create method.  

We are trying to get to the point where if you want to customize the internal behavior of GraphServiceClient you can use the GraphClientFactory to create a HttpClient instance and then pass that instance into a constructor of GraphServiceClient.  Getting there will take a take a little while as all the generated code is currently dependant on the IHttpProvider interface.

**Comment by ksikorsk** [comment]
Thanks for the info @darrelmiller, the approach of passing an HttpClient into the GraphServiceClient makes a lot of sense.  It removes the extra layer of architecture, and supports what I want to be passing in anyway (the HttpClient).  Looking forward to this change rolling out.

**Comment by pwombwa** [comment]
@ksikorsk, Thanks for the valuable feedback. We've fixed this issue as part of [Microsoft.Graph.Core 1.15.0-preview.2](https://www.nuget.org/packages/Microsoft.Graph.Core/1.15.0-preview.2). Give it a try and let us know if it addresses your scenario.
