### ISSUE TITLE
roles collection not returned for remote items (except owner)

### ISSUE THREAD

**Issue by ajweber** [microsoftgraph/msgraph-sdk-dotnet#452]
I have tested a number of driveItems that were "shared with me", and the Permissions that are returned by default on the driveItem (which includes a RemoteItem) have the correct list of Permission objects - including the GrantedTo/User info.  However, they all have an **empty Roles collection**.  Thus, I can tell who has some form of access to the item, but not what level of access they have.  This, in turn, makes it impossible to determine what the user can actually do with the item.

I have also tried fetching the explicit, remoteItem (via ParentReference driveId and item Id), and expanding the Permissions on that object.  It returns the same details...no Roles???

As mentioned in the title, the lone, consistent info returned is for the owner's Permission.  All others have User details, but no Roles.

This SO seems similar to what I am seeing, but it is pretty old and indicates it may have been fixed already? https://stackoverflow.com/questions/44135569/roles-and-permissions-issue-from-onedrive-api-sdk
(I am testing with a OD Business account)

This is my first try to get info on SO: https://stackoverflow.com/questions/55797880/how-do-you-get-the-permissions-of-a-remote-driveitem

Is something broken here? 
[AB#7329](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7329)

**Comment by MIchaelMainer** [comment]
I don't have insights into this scenario. I did tag your SO post with the OneDrive tag so hopefully the service API owner can see and address your question.

**Comment by ajweber** [comment]
Thanks, Michael.

**Comment by MIchaelMainer** [comment]
Issues appears to be fixed be StackOverflow post.
