### ISSUE TITLE
AADSTS700016: Application with identifier 'ENTER_YOUR_CLIENT_ID' was not found in the directory

### ISSUE THREAD

**Issue by chanmmn** [microsoftgraph/msgraph-sdk-dotnet#454]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Login to Office 365

### Actual behavior
AADSTS700016: Application with identifier 'ENTER_YOUR_CLIENT_ID' was not found in the directory

### Steps to reproduce the behavior
Run uwp-csharp-connect-sample-master sample.

**Comment by MIchaelMainer** [comment]
If you're referencing https://github.com/microsoftgraph/uwp-csharp-connect-sample, that sample is archived and is no longer updated. Questions about samples should be asked in the sample repo. That error means that you didn't provide a clientId. The instructions are in the repo readme.txt.
