### ISSUE TITLE
Support capability annotations

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#458]
#307  
[AB#7325](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7325)

**Comment by andrueastman** [comment]
This is  now resolved by Kiota as the openApi reference used in generation is generated by use of the annotations generated at the link below
https://github.com/microsoftgraph/msgraph-metadata/blob/master/clean_v10_metadata/cleanMetadataWithDescriptionsAndAnnotationsAndErrorsv1.0.xml
