### ISSUE TITLE
Question: How should we instantiate GraphServiceClient for multiple access token

### ISSUE THREAD

**Issue by andrew-vdb** [microsoftgraph/msgraph-sdk-dotnet#460]
Use Case: I have multiple tenants. Every tenant have multiple users. Every user have different access token.

My Situation:
GraphServiceClient is hosted on azure function.
Every graph api call, I have to create new GraphServiceClient in order to pass the different access token (depending on which user)

Question:
- Is this approach correct? or is there any better way to do it?
- If I create new GraphServiceClient a lot of times, will GraphServiceClient reuse the HttpClient?
- My gut feeling keep saying that I should create my own HttpClient and call graph api manually (do not use GraphServiceClient), GraphServiceClient is better for use case when there is only one access token, but I hope my gut feeling is wrong...

**Comment by peombwa** [comment]
@andrew-vdb, you can use a static instance of `GraphServiceClient` on Azure function as such:
```cs
private static GraphServiceClient graphClient = new GraphServiceClient(null);

public static async Task<IActionResult> Run(HttpRequest req, string graphToken,  ILogger log){
// set AuthenticationProvider property.
    graphClient.AuthenticationProvider = new DelegateAuthenticationProvider(async (request) => {
        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", graphToken);
        await Task.FromResult<object>(null);
    });
    // Make request. 
    User me = await graphClient.Me.Request().GetAsync();
}
```

**Comment by andrew-vdb** [comment]
@peombwa cmiiw, that will only work on single thread, but that won't work concurrently. Limiting concurrency on my function also not an option.

**Comment by peombwa** [comment]
@andrew-vdb You are right, my initial example only works on a single thread. Actually, as of `Microsoft.Graph 1.15.0`, you can pass an authorization header directly to a GraphServiceClient request as such:
```cs
private static GraphServiceClient graphClient = new GraphServiceClient(null);

public static async Task<IActionResult> Run(HttpRequest req, string graphToken,  ILogger log){
    List<HeaderOption> requestHeaders = new List<HeaderOption>() { new HeaderOption("Authorization", "Bearer " + graphToken) };

    User me = await graphClient.Me.Request(requestHeaders).GetAsync();
    var messages = await graphClient.Me.Messages.Request(requestHeaders).GetAsync();
}
```
**Note:**
This will only work with `Microsoft.Graph 1.15.0` and GraphServiceClient will not handle token refresh for you if expired.

Does this example work for your scenario?

We will also accommodate this scenario in our SDK design.

**Comment by andrew-vdb** [comment]
@peombwa thanks, that should work for my scenario,
In regard of your code sample, for Upload session
```csharp
var uploadSession = await graphClient.Drives[driveId].Root.ItemWithPath(driveFileName).CreateUploadSession(properties).Request(requestHeaders).PostAsync();

var uploader = new ChunkedUploadProvider(uploadSession, graphClient, fileStream.BaseStream);

result = await uploader.UploadAsync();//Should I put authorization headers too in this line? or this is good enough
```

**Comment by peombwa** [comment]
@andrew-vdb Awesome! Yes you should, you can pass the authorization header as a named parameter:
```cs
await uploader.UploadAsync(options: requestHeaders);
```
The same applies to `uploader.GetUploadChunkRequests` just in-case you need to use it.

**Comment by andrew-vdb** [comment]
@peombwa Thank you for your help, everything should be good now

**Comment by Norfolc** [comment]
> We will also accommodate this scenario in our SDK design.
Is there any improvements in the recent SDK versions? Do you plan to support this feature in more convenient way?

**Comment by MIchaelMainer** [comment]
I suggest that you take a look at https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp. 

It demonstrates how to get a token for each user from a token cache.
