### ISSUE TITLE
 Enable service integration tests

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet#462]
[AB#7326](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7326)

**Comment by MIchaelMainer** [comment]
The idea here would be to allow us to run E2E functional tests that hit the service. This is somewhat similar to how GE runs the GET samples as a test run. 

We need a design on how we can enable this for our SDKs during validation. 

Considerations:
* protect the access token during CI from malicious tests.
* demo tenant data state - how do we do this continuously across SDKS without degrading the test data.
* We don't want service issues to be blocker.
* Phase 1 - non-destructive calls only.

**Comment by pschaeflein** [comment]
I would suggest multiple Auth providers, so that both Delegated and Application permissions can be tested. I've had success with xUnit fixtures and an in-memory token cache.

**Comment by darrelmiller** [comment]
This is a potentially big task, so we are going to break it down into smaller objectives:

1) Create a EXE that compiles all generated .Net code snippets against specific versions of Microsoft.Graph.Core and Microsoft.Graph and reports errors. Allow pointing to folder of snippets.
2) Provide command line switch to enable execution of all GET requests and report errors.  Pass auth credentials via command line.  (Username/password and/or client credentials).  Report 4XX as failures but 5XX as warnings (except for 501 Not implemented).
3) Build infrastructure to provision well known demo tenant and execute all requests against tenant and verify responses are as expected.  (We need a way of determining the test execution order)

**Comment by andrueastman** [comment]
Closing this for now. This work is tracked and currently ongoing on the [Raptor Repo](https://github.com/microsoftgraph/msgraph-sdk-raptor).
