### ISSUE TITLE
Logging provider

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet#464]
[spec](https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/providers/LoggingProvider.md) 
[AB#7331](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7331)

**Comment by andrueastman** [comment]
Guidance for SDK users on logging requests can be found [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md)
