### ISSUE TITLE
NullReferenceException for BatchRequestContent

### ISSUE THREAD

**Issue by dscpinheiro** [microsoftgraph/msgraph-sdk-dotnet#470]
Hi!

I'm trying to use the new _BatchRequestContent_ and _BatchResponseContent_ classes to send batch requests, but I'm getting an odd _**System.NullReferenceException: Object reference not set to an instance of an object**_ when sending the data to the Graph API.

I used test as a starting point: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/BatchRequestTests.cs

Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior.
- [x] Actual behavior. Provide error codes, stack information, and a capture of the request and response
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Batch request is sent successfully to the Graph API.

### Actual behavior
NullReferenceException is thrown on this line:
`var response = await httpClient.PostAsync("https://graph.microsoft.com/v1.0/$batch", batchRequestContent);`

Stack trace:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.FinishAsync()
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationTok
en cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MyApp.Program.Main() in /Users/dscpinheiro/MyApp/Program.cs:line 21
   at MyApp.Program.<Main>()
```

### Steps to reproduce the behavior
Package version: [1.15.0](https://www.nuget.org/packages/Microsoft.Graph.Core/1.15.0)
Sample code: 

```
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Graph;

namespace MyApp
{
    class Program
    {
        static async Task Main()
        {
            var token = "REPLACE_ME";

            var httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);

            var httpRequestMessage1 = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/v1.0/me/");

            var batchRequestContent = new BatchRequestContent();
            batchRequestContent.AddBatchRequestStep(new BatchRequestStep("1", httpRequestMessage1));

            var response = await httpClient.PostAsync("https://graph.microsoft.com/v1.0/$batch", batchRequestContent);
            var batchResponseContent = new BatchResponseContent(response);
            var responses = await batchResponseContent.GetResponsesAsync();

            System.Console.WriteLine(responses.Count);
        }
    }
}
```

Sample csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="1.15.0" />
  </ItemGroup>
</Project>
```

**Comment by MIchaelMainer** [comment]
And just to confirm, are you seeing the error in a console app? If you run the test with your own token, do you see the same error?  I took your example and ran it and can't repro the error. I get the expected behavior. Same with the test.

**Comment by peombwa** [comment]
@MIchaelMainer you can repro this by targeting .NetCore 2.1 and above. However, it runs as expected with previous versions of .NetCore (2.0 and below) - our test targets .NetCore 1. Also, the `NullReferenceException` thrown by .NetCore is misleading, as it should be `ObjectDisposedException`. Let me look into this.

@dscpinheiro, For now, you can target .NetCore 2.0 as we address this issue.

**Comment by dscpinheiro** [comment]
@MIchaelMainer Yes, I can see this error in a console app with my own token (that's how I got the stack trace from `Actual behavior`).

@peombwa Thanks for taking a look.

**Comment by wintondeshong** [comment]
@peombwa when is this fix going to make it into a build?

**Comment by peombwa** [comment]
@wintondeshong @dscpinheiro, we've just release [Microsoft.Graph.Core 1.16.0-preview.1](https://www.nuget.org/packages/Microsoft.Graph.Core/1.16.0-preview.1) on nuget which has a fix for this.

**Comment by wintondeshong** [comment]
Thank you @peombwa
