### ISSUE TITLE
[Query] User's proxyAddresses property not getting populated

### ISSUE THREAD

**Issue by sanjaydebnath** [microsoftgraph/msgraph-sdk-dotnet#471]
I am trying to get all proxy addresses for users from AAD by hitting this url

[https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'xxxx')&$select=**proxyAddresses**,id,displayName,firstName,lastName,userPrincipalName,companyName,jobTitle,scoredEmailAddresses](url)

But the api returning all columns except 'proxyAddresses'. Do we need any special permission in the AAD App we are using?

I have given delegated permission to "Read all users' basic profiles" but not to "Read all users' full profiles" because that needs admin consent. 

To generate the OBO token, I am simply using steps described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow).

**Comment by sanjaydebnath** [comment]
Actually I just saw [this](https://docs.microsoft.com/en-us/graph/permissions-reference#user-permissions). So i have permission to get the green color coded properties only it seems. Let me try by adding the full permission. 

![image](https://user-images.githubusercontent.com/28987981/57565536-cbe6e300-738d-11e9-9d05-54d6ce922a24.png)

**Comment by peombwa** [comment]
@sanjaydebnath `User.Read.All` should yield the proxyAddresses property. Did it work for your scenario?
