### ISSUE TITLE
Enhance retry handler to retry on 504 gateway timeout errors

### ISSUE THREAD

**Issue by CameronDwyer** [microsoftgraph/msgraph-sdk-dotnet#476]
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
I expect the retry handler to attempt a retry on 504 (gateway timeout error). Why? Because the Graph API expects to encounters these issues internally and the caller has no way to avoid them. Here's the definition of a 504 from the Graph error code documentation https://docs.microsoft.com/en-us/graph/errors

'504 | Gateway Timeout | The server, while acting as a proxy, did not receive a timely response from the upstream server it needed to access in attempting to complete the request. May occur together with 503.'

This has led us to have to develop our own retry handling code outside of the SDK for this error code.

I suggest an incremental backoff with max retry limit as we won't have a retry-after header for these errors.

### Actual behavior
504 errors do not result in a retry

### Steps to reproduce the behavior
This can't be reliably reproduced due to the nature of the internal timeout.

**Comment by peombwa** [comment]
@CameronDwyer Thank you for taking your time to bring this to our attention. We will add this to our backlog and update the retry handler to retry on 504.

**Comment by peombwa** [comment]
This has been fixed as part of https://www.nuget.org/packages/Microsoft.Graph.Core/1.16.0-preview.2.
