### ISSUE TITLE
Custom query options with multiple parameters

### ISSUE THREAD

**Issue by Alfetta159** [microsoftgraph/msgraph-sdk-dotnet#488]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Return both jobTitle and department when using provided options with the `$select` parameter similar to ODATA syntax with REST API

```https://graph.microsoft.com/v1.0/me?$select=department,jobTitle```

which returns:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(department,jobTitle)/$entity",
    "department": "Finance",
    "jobTitle": "Auditor"
}
```
### Actual behavior
throws ```Microsoft.Graph.ServiceException```

message:

> Code: BadRequest
> Message: Syntax error: character ',' is not valid at position 8 in 'jobTitle, department'.
> 
> Inner error

### Steps to reproduce the behavior
Running following code in .NET Standard 2.0 lib proj.

```
	List<QueryOption> options = new List<QueryOption>
	{
		 new QueryOption("$search", "jobTitle,department")
	};

	var me = await client.Me.Request(options).GetAsync();
```
I did try adding two separate QueryOptions, but it doesn't like to see the ```$search``` key twice.

**Comment by darrelmiller** [comment]
The URI you show uses "$select" but the sample code use "$search".  Which one are you trying to use?

**Comment by Alfetta159** [comment]
I am using $search, but I should be using "$select".
