### ISSUE TITLE
Cannot call .VisibleView() on a Range, method does not exist?

### ISSUE THREAD

**Issue by pheuter** [microsoftgraph/msgraph-sdk-dotnet#489]
Based on [these SDK docs](https://docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&tabs=cs#sdk-sample-code) I should be able to get the visible view of a range, such as when filtering a table and retrieving the filtered rows, but for some reason the SDK complains there is no such method. Using v1.15.0. 
[AB#7287](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7287)

**Comment by darrelmiller** [comment]
@MIchaelMainer Does codegen not handle bound functions?  The metadata contains VisibleView but I confirmed that it does not exist in IWorkbookWorksheetRequestBuilder

**Comment by MIchaelMainer** [comment]
Codegen handles bound functions, it doesn't yet support composable functions, which I believe is what this scenario is.

**Comment by MIchaelMainer** [comment]
Related to #233

**Comment by pheuter** [comment]
Realize it may be difficult to provide an accurate estimate but any chance of getting a rough eta of when one can expect this issue to be fixed and deployed? Need to be able to filter tables for an app.

**Comment by MIchaelMainer** [comment]
@pheuter That method that we didn't implement wasn't going to work as I think you'd expect as it is applicable to a single range, and there isn't a way to get the range across all of those table rows in a single call from what I see (I could easily be wrong, I added an inline comment below about where it may be done and I think is worth investigating). The API only returns a single range for a single table row at a time. 

```
var workbookTableRows = await graphClient.Me.Drive.Items[excelFileId]
                                .Workbook
                                .Worksheets["WorksheetId"]
                                .Tables["TableId"]
                                .Rows
                                .Request()
                                .GetAsync();


foreach (var workbookTableRow in workbookTableRows)
{
    var workbookTableRowRange = await graphClient.Me.Drive.Items[excelFileId]
                .Workbook
                .Worksheets["WorksheetId"]
                .Tables["TableId"]
                .Rows[workbookTableRow.Id]
                .Range()
                .Request()
                .GetAsync();

    var httpRequestMessage = graphClient.Me.Drive.Items[excelFileId]
                .Workbook
                .Worksheets["WorksheetId"]
                .Range(workbookTableRowRange.Address) // Important: I think you can construct a range from all of the workbookTableRowRange so that this could be done in a single call, instead of for each workbookTableRowRange. I'm not too familiar with the Excel API so you'd want to play with this to make it work.
                .Request()
                .GetHttpRequestMessage();

    httpRequestMessage.RequestUri = new Uri(httpRequestMessage.RequestUri, "VisibleView");

    await graphClient.AuthenticationProvider.AuthenticateRequestAsync(httpRequestMessage);

    var httpResponseMessage = await graphClient.HttpProvider.SendAsync(httpRequestMessage);

    var responseContent = await httpResponseMessage.Content.ReadAsStreamAsync();

    WorkbookRangeView rowRangeView = graphClient.HttpProvider.Serializer.DeserializeObject<WorkbookRangeView>(responseContent);
}
```

@peombwa 

Note to us, written in terms of OData:

The VisibleView OData function is composable off a workbookRange entity. workbookRange entity is only returned by a function (there are many) so we need the generator to support composable functions to make this a first class scenario. 

VisibleView will only work on a single workbookRange entity. The function to return the workbookRange is only applicable to a single workbookTableRow, not a collection of workbookTableRow (this means we need to make snippet generator respect bindings to collections or single items). So when we have the generator correctly respecting composability, VisibleView will still need to be called on each workbookTableRow.

TODO: Snippet generator is incorrectly generating the .Net and JS calls for getting a list of table rows. The VisibleView function is not demonstrated in the topic example. @andrueastman 

TODO: Composable functions need to be supported in the generator.

**Comment by pheuter** [comment]
@MIchaelMainer I was actually able to get the desired table filter functionality by following the API calls suggested in [this SO response](https://stackoverflow.com/a/47305406), which do a `columns/filter/apply` and a `tables/range/visibleView/rows` to read.

**Comment by MIchaelMainer** [comment]
Thank you for the heads-up. It looks like Excel uses composable functions a lot more than the last time I looked deeply at the API.

**Comment by MIchaelMainer** [comment]
This scenario is now supported in versions greater than 3.22.0.

```csharp
    await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                                        .Range()
                                                                        .VisibleView()
                                                                        .Request()
                                                                        .GetAsync();
```
