### ISSUE TITLE
Is support for .netStandard near ?

### ISSUE THREAD

**Issue by abdulrehmangill** [microsoftgraph/msgraph-sdk-dotnet#49]

**Comment by MIchaelMainer** [comment]
@abdulrehmangill Thank you for bringing this up. We haven't defined a time table for moving from PCL to .NET Standard. I'll keep this issue open to keep this on our radar for now.

**Comment by byatis** [comment]
Is there any way (some workaround?) using this client currently in .Net Core projects?

**Comment by grahamehorner** [comment]
@MIchaelMainer any update on this, looking to develop a booking system using asp core with a O365 graph for the backend

**Comment by lpmeunier** [comment]
pull request for support seems to be in progress, any idea when we could get this merged?

**Comment by cbales** [comment]
We are currently code reviewing these changes. You can expect to see this functionality soon.

**Comment by lpunderscore** [comment]
I see it's been merged, but build is failing, any idea when we might get a new nuget version with these changes available?

**Comment by cbales** [comment]
This is in the works, we are still moving forward with this and need to update our build configurations as well as publish the new NuGet package. These changes will be available soon.

**Comment by luigledr** [comment]
Is there any deadline for the publishment of the NuGet packages?

**Comment by grahamehorner** [comment]
any update? I'm finding that more and more aspnetcore projects are looking to use the Microsoft Graph API and the fact that netcoreapp is not yet published as a nugget package is proving a blocker for us.

**Comment by MIchaelMainer** [comment]
We're looking to get this update published soon. We can't give any specific dates but are well aware of the ask for this. Thank you for making sure we hear you 👍.

**Comment by MIchaelMainer** [comment]
Support is in the .Net client library for .NetStandard. Thank you all for your raising your voice for this request.
