### ISSUE TITLE
Missing Calls: Insert Range, Delete Range, Get

### ISSUE THREAD

**Issue by DeanMauro** [microsoftgraph/msgraph-sdk-dotnet#490]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. 
    - The SDK should have methods corresponding to all API calls in the Graph documentation. 
- [ ] Actual behavior. 
    - [Insert Range](https://docs.microsoft.com/en-us/graph/api/range-insert?view=graph-rest-1.0&tabs=cs), [Delete Range](https://docs.microsoft.com/en-us/graph/api/range-delete?view=graph-rest-1.0&tabs=cs), and [Get Range Format](https://docs.microsoft.com/en-us/graph/api/rangeformat-get?view=graph-rest-1.0&tabs=cs) are all missing.
- [ ] Steps to reproduce the behavior. 
    - Create a new project and use the latest stable version of the SDK.
    - Copy the code samples from each of the 3 pages linked above. For example, to delete a range:
<pre>
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var shift = "shift-value";

await graphClient.Me.Drive.Items["{id}"].Workbook.Names["{name}"]
	.Range()
	.Delete(shift)
	.Request()
	.PostAsync();
</pre>

### Expected behavior

The Delete method should exist and compile with no issues.

### Actual behavior

An error is given:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IWorkbookNamedItemRangeRequestBuilder' does not contain a definition for 'Delete' and no accessible extension method 'Delete' accepting a first argument of type 'IWorkbookNamedItemRangeRequestBuilder' could be found (are you missing a using directive or an assembly reference?)

Note: An issue acknowledging the missing Insert Range method was opened in 2017 and was closed, but has not been resolved yet. #216  
[AB#7289](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7289)

**Comment by MIchaelMainer** [comment]
Related to #233 and #489 - requires support for composable functions in the generator.

**Comment by MIchaelMainer** [comment]
@darrelmiller @peombwa  Looks like composable function work is bubbling up

**Comment by zengin** [comment]
@MIchaelMainer, it looks like this is addressed by your composable function changes. There seems to be other issues linked in this thread that can be closed as well.

**Comment by MIchaelMainer** [comment]
This scenario is expected to work now in versions greater than 3.22.0.

```csharp
await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                               .Range()
                                                               .Delete("shift")
                                                               .Request()
                                                               .PostAsync();

await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                               .Range()
                                                               .Insert("shift")
                                                               .Request()
                                                               .PostAsync();

await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                               .Range()
                                                               .Format
                                                               .Request()
                                                               .GetAsync();
```
