### ISSUE TITLE
Large file with upload session

### ISSUE THREAD

**Issue by anurag2994** [microsoftgraph/msgraph-sdk-dotnet#493]
I'm trying to upload a large file (5 GB) creating an UploadSession as specified in the documentation.
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-beta

The SDK contains class to achieve this.

    //
    // Summary:
    //     Use this class to make resumable uploads or to upload large files. This class
    //     allows the client to control the size of chunks uploaded (for example, can be
    //     useful to use small chunks if the connection is slow). Also allows the client
    //     to pause an upload and resume later.
    public class ChunkedUploadProvider

I'm using Microsoft.Graph v1.15.0
### Expected behavior

The file should be uploaded and should be readable.

### Actual behavior

The file is uploaded but is not readable.

### Steps to reproduce the behavior

1. Set upload stream to length of the size of the file i.e. 5GB 
MemoryStream memStream = new MemoryStream();
 memStream.SetLength(sizeoffile);
public ChunkedUploadProvider(UploadSession session, IBaseClient client, Stream uploadStream, int maxChunkSize = -1);
2. Start reading the file in chunks from local disk.
3. Start uploading the file in chunks using GetChunkRequestResponseAsync
4. Continue till the upload succeeds.
5. Download the file from OneDrive.
6. Try to open the file. It displays error that the file is damaged.
 
[AB#7291](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7291)

**Comment by peombwa** [comment]
Thanks for taking your time to open this issue.

I'm not able to repro this issue on my end using the repro steps above. What's the content type of the file you are working with? Also, is this issue present when you upload a smaller file size, say 250 MB?

Could you also try uploading the file using [this sample](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs#L57) in our functional test

**Comment by anurag2994** [comment]
I'm unable to perform the below mentioned scenario using the SDK methods:

**I do not want to read the whole file in one go. File size can go into GBs.
I want to read the file in chunks and peform upload in chunks with the same upload session created.**

See the code below for better clarity. I'm able to perform the same operation using explicit HTTP calls.
```
var rootItem = client.Users[email].Drive.Root.Request().GetAsync().Result;
UploadSession uploadSession =  client.Users[email].Drive.Items[rootItem.Id].ItemWithPath("filename").CreateUploadSession().Request().PostAsync().Result;
                var filestr = new FileStream(@"somefile", FileMode.Open);
                int i = 0;
                long lOffset = 0;
                long lNumBytes = 0;
                long bytesRemaining = filestr.Length;
                int fragSize = 5 * 1024 * 1024;
                int numFragments = Convert.ToInt32(filestr.Length / fragSize);
                int lastChunkSize = Convert.ToInt32(filestr.Length % fragSize);
                if (lastChunkSize > 0)
                {
                    numFragments++;
                }
                long fileSize = filestr.Length;
                filestr.Close();

                while (i < numFragments)
                {
                    HttpRequestMessage reqMessage = new HttpRequestMessage(HttpMethod.Put, uploadSession.UploadUrl);
                    var httpCLient = new HttpClient();
                    long lchunkSize = 5 * 1024 * 1024;
                    
                    if (bytesRemaining < lchunkSize)
                    {
                        lchunkSize = bytesRemaining;
                    }

                    lOffset = 0;
                    lOffset = (i * fragSize);
                    lNumBytes = 0;
                    lNumBytes = (lchunkSize);
                    //Read chunks from a file from a drive and upload.
                    var byteToSend = (StreamChunkFromFile("", ref lOffset, ref lNumBytes));
                    long end = lOffset + lNumBytes - 1;
                    
                    reqMessage.Content = new ByteArrayContent(byteToSend);
                    reqMessage.Content.Headers.Add("Content-Range", "bytes " + lOffset + "-" + end + "/" + fileSize);
                     var httpResponse = httpCLient.SendAsync(reqMessage).Result;
                    if (httpResponse.StatusCode == HttpStatusCode.Created)
                    {
                        var driveItem = JsonConvert.DeserializeObject<DriveItem>(
                                    httpResponse.Content.ReadAsStringAsync().Result);
                    }
                    bytesRemaining = bytesRemaining - lchunkSize;
                    i = i + 1;
                }
            }
```

**Comment by MIchaelMainer** [comment]
@anurag2994 Are you still dealing with this issue?

**Comment by anurag2994** [comment]
Yes I am.

**Comment by MIchaelMainer** [comment]
Could you also try uploading the file using this [sample ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs#L57)in our functional test and tell us did it work for your scenario?

**Comment by anurag2994** [comment]
That doesn't work for me. 

`var provider = new ChunkedUploadProvider(uploadSession, graphClient, stream, maxChunkSize);`

In the above code snippet, the 3rd parameter as defined in sdk is:
  
  **uploadStream:**
  _Readable, seekable stream to be uploaded. Length of session is determined via uploadStream.Length_

  

- I do not want to read the file in one go as it would consume a lot of memory. But as the length of 
  session is deteremined by **"uploadSTream.Length"**. 
- It is forcing me to read the whole file. Files can go upto 15 GB (maximum size supported by OneDrive).

**Comment by MIchaelMainer** [comment]
What you want to do is what our client should do. With that said, I don't why the file is corrupt after uploading. Have you compared the bytes of the file before uploading, and the uploaded file after you download it from OneDrive? I don't have insight into what is going on with OneDrive.

[Uploading bytes doc](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#upload-bytes-to-the-upload-session)

**Comment by anurag2994** [comment]
If I read the whole file in one go and upload it using the client it works perfectly. The file is created and it's readable.

But if I follow the below process. The file is created but it's not readable.

Set upload stream to length of the size of the file i.e. 8348705 in bytes.
`
MemoryStream memStream = new MemoryStream();
                memStream.SetLength(8348705);
 var rootItem = client.Users[email].Drive.Root.Request().GetAsync().Result;
                UploadSession uploadSession = client.Users[email].Drive.Items[rootItem.Id].ItemWithPath("abc.zip").CreateUploadSession().Request().PostAsync().Result;
var maxChunkSize = 5*1024*1024;
var provider = new ChunkedUploadProvider(uploadSession, client, memStream, maxChunkSize);
var chunkRequests = provider.GetUploadChunkRequests();
const int chunkSize = 5*1024*1024; // read the file by chunks of 1KB
using (var file = System.IO.File.OpenRead(@"D:\" + "abc.zip"))
          {
           byte[] buffer = new byte[chunkSize];
           file.Seek(0, SeekOrigin.Begin);
           int bytesRead = file.Read(buffer, 0, chunkSize);
           while (bytesRead > 0)
                    {
                        Stream stream = new MemoryStream(buffer);
                        Upload(uploadSession, stream, provider, chunkRequests.ElementAt(0));
                        byte[] buffer1 = new byte[3105825];
                        bytesRead = file.Read(buffer1, 0, 3105825);
                        Stream stream1 = new MemoryStream(buffer1);
                        Upload(uploadSession, stream1, provider, chunkRequests.ElementAt(1));
                    }   
           }
`

**Comment by anurag2994** [comment]
Compared the bytes of two files, both were same but the file is corrupt. @MIchaelMainer

**Comment by rbulkool** [comment]
@anurag2994 Have you already found a solution? I have the same problem but still dont't know how to use SDK to send large files in chunks!

**Comment by anurag2994** [comment]
Yes I have found a workaround for the same.

**Comment by anurag2994** [comment]
> @anurag2994 Have you already found a solution? I have the same problem but still dont't know how to use SDK to send large files in chunks!

I made explicit http calls to achieve the same. I used SDK for just creating the upload session.

**Comment by rbulkool** [comment]
Thank you, @anurag2994! I'm going to do the same!

**Comment by andrueastman** [comment]
@anurag2994 @rbulkool 
Hey, Have you tried using the LargeFileUploadTask?
You can see how to use it in the description of this PR.
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/65

**Comment by rbulkool** [comment]
Yes @andrueastman , my first code was with LargeFileUploadTask, and it worked perfectly fine, but this class encapsulates all the logic of breaking the file into chunks and sending them. In my project, the backend is a WEB API (REST) that receives the chunks sent by the frontend, but in order not to "rebuild" the file, I need to send the chunks directly to OneDrive.

**Comment by kimselim** [comment]
Did you solve it? I have the same problem.
If you have solved it, would you please share the solution?

**Comment by MIchaelMainer** [comment]
Large file uploads should use the LargeFileUploadTask. See https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp.
