### ISSUE TITLE
Remove / Delete Owner: wrong Request URL 

### ISSUE THREAD

**Issue by HenningBertsch** [microsoftgraph/msgraph-sdk-dotnet#494]
When trying to remove an owner from a group the [referenced call](https://docs.microsoft.com/de-de/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=cs) if not created correctly by the MS GraphClient.

**Used Lib Version:**
Microsoft.Graph 1.15.0
Microsoft.Graph. Core 1.15.0

**Error Message**
"code": "BadRequest",
"message": "Write requests are only supported on contained entities"

**Expected URL:**
https://graph.microsoft.com:443/v1.0/groups/{id}/owners/{id}/$ref (this is working in [Graph Explorer ](https://developer.microsoft.com/en-us/graph/graph-explorer)Demo)

**Actual URL created by the Graph Client:**
https://graph.microsoft.com:443/v1.0/groups/{id}/owners/{id} (this is not working in [Graph Explorer ](https://developer.microsoft.com/en-us/graph/graph-explorer)Demo and reports the same error as in application)

**Code Used (copied from the [reference](https://docs.microsoft.com/de-de/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=cs)):**
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.Groups["{id}"].Owners["{id}"]
    .Request()
    .DeleteAsync();

**Comment by MIchaelMainer** [comment]
Thank you for the feedback. It should look like:

`await graphClient.Groups[""].Owners[""].Reference.Request().DeleteAsync();`

@andrueastman $ref scenarios should look like this.

**Comment by pschaeflein** [comment]
> `await graphClient.Groups[""].Owners[""].Reference.Request().DeleteAsync();`
> 
> @andrueastman $ref scenarios should look like this.

This should be in the wiki/docs/faq, IMO.

**Comment by andrueastman** [comment]
Closing this as the example in the docs was resolved.
