### ISSUE TITLE
CreateUploadSession() fails on request from IE11 and Edge

### ISSUE THREAD

**Issue by bengansukh** [microsoftgraph/msgraph-sdk-dotnet#495]
Error message: 
Code: BadRequest Message: Found a function 'microsoft.graph.createUploadSession' on an open property. Functions on open properties are not supported. Inner error.

I am confused as to what it's referring to as 'open property'.

**Comment by MIchaelMainer** [comment]
This doesn't sound like an issue with the .Net SDK. Please open your question on StackOverflow and provide more information about what you are trying to do, including repro steps.

**Comment by bengansukh** [comment]
Will do, thank you

**Comment by bengansukh** [comment]
It turns out IE and Edge post files with the filenames being the fullpath to the file, which was the reason why the post to Microsoft.Graph failed with the above error message.

If you're sending your files via FormData, here's a quick fix https://stackoverflow.com/a/45066287/11504672
