### ISSUE TITLE
Issues with adding schema exension to a group

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/msgraph-sdk-dotnet#497]
I am trying to add a schema extension to a group via de Graph SDK for .NET, but the values always seem to be null.

### Expected behavior
Values of the custom schema extension set during group creation.

### Actual behavior
The values always of the schema extension always seem to be null.  

### Steps to reproduce the behavior
Add the extension to the AdditionalData property of a group. I am using the same method as in the functional SchemaExtensionTests of the Graph SDK. https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/fc2116b4ad335ab25f8df8f4b0dce8c9950eda78/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/SchemaExtensionTests.cs

I do think this unit test is a bit limited, since the actual values of the schema extension are not compared with the expected values.

```
Models.Group group = new Models.Group(request);
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add("xxxxxxxx_YYYTeamsProvisioning", new OneProvisioningSchemaExtensions("123","123","123"));
group.AdditionalData = extensionInstance;
     
await Task.Delay(15000); // It takes some time for the schema extension def to be available for the creation of a group.
var createdGroup = await graphClient.Groups.Request().AddAsync(group);
```

The result when requesting the group using the following URL
https://graph.microsoft.com/v1.0/groups/xxxx-xxxxx-xxxxx-xxxxx?$select=id,displayName,"xxxxxxxx_YYYTeamsProvisioning

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups(xxxxxxxx_YYYTeamsProvisioning)/$entity",
    "id": "c6f05a7e-2c42-43f6-8876-284e3657bbcf",
    "xxxxxxxx_YYYTeamsProvisioning": {
        "@odata.type": "#microsoft.graph.ComplexExtensionValue",
        "entityType": null,
        "entityId": null,
        "source": null
    }
}
```

### Working behavior
For your reference, adding the exension via PostMan is working as expected:
```
{
	"displayName": "Jack123",
	"description": "Jack123",
	"groupTypes": ["Unified"],
	"mailEnabled": true,
	"mailNickname": "Jack123",
	"securityEnabled": false,
	"xxxxxxxx_YYYTeamsProvisioning": {
        "entityType": "123",
        "entityId": "123",
        "source": "123"
        }
}
```

**Comment by peombwa** [comment]
@adrichema Using the same unit test, I'm able to add a schema to a group and retrieve it from a group using the SDK. What version of the SDK are using?

**Comment by peombwa** [comment]
Here is a simplified snippet of our unit test that yields the results as expected. I'm using [version 1.15.0](https://www.nuget.org/packages/Microsoft.Graph/1.15.0) of the .Net SDK.
```cs
// Create schema extension.
SchemaExtension schemaExtension = await CreateSchemaExtenion();

// Create a group with the schema extension defined earlier.
IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
extensionInstance.Add(schemaExtension.Id, new MyCustomExtension { EntityId = "123", EntityType = "123", Source = "123" });

Group group = new Group()
{
    DisplayName = $"{name} - {Guid.NewGuid().ToString()}",
    Description = "This group was created with a schema extension",
    MailEnabled = false,
    MailNickname = "nickname", // silly requirement since this isn't mail enabled.
    SecurityEnabled = false,
    GroupTypes = new List<string>() { "Unified" },
    AdditionalData = extensionInstance
};

await Task.Delay(15000); // It takes some time for the schema extension def to be available for the creation of a group.

try
{
    group = await graphClient.Groups.Request().AddAsync(group);

    Group createdGroup = await graphClient.Groups[group.Id].Request().Select($"id,displayName,{schemaExtension.Id}").GetAsync();

    if (createdGroup.AdditionalData.ContainsKey(schemaExtension.Id))
        Console.WriteLine(createdGroup.AdditionalData[schemaExtension.Id]);
}
catch (Exception ex)
{

    throw ex;
}
```

**Comment by adrichema** [comment]
I am able to get the extension but all values in it seem to be null. Could you please share your MyCustomExtension class? 

I am also using 1.15.0.

**Comment by peombwa** [comment]
Here you go : 
```cs
public class MyCustomExtension
{
    // You must serialize your property names to camelCase if your SchemaExtension describes as such.
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "entityType", Required = Newtonsoft.Json.Required.Default)]
    public string EntityType { get; set; }

    [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "entityId", Required = Newtonsoft.Json.Required.Default)]
    public string EntityId { get; set; }

    [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "source", Required = Newtonsoft.Json.Required.Default)]
    public string Source { get; set; }
}
```
Note that [`SchemaExtension`](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/fc2116b4ad335ab25f8df8f4b0dce8c9950eda78/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/SchemaExtensionTests.cs#L42) property names are case sensitive and you must serialize them to the right case when adding custom extensions to a group. This is why I've added `JsonProperty` annotation to the properties of `MyCustomExtension` class to serialize them to `camelCase` since my `SchemaExtension` describes it's property names in `camelCase`. Without the annotations, the model properties will be treated as `PascalCase`.

**Comment by MIchaelMainer** [comment]
This issue appears to be resolved so we are closing this issue. Please reopen if this has been closed in error.

**Comment by adrichema** [comment]
@MIchaelMainer and @peombwa, did you change anything from your side? I switched to Open Extensions which are working fine.

**Comment by MIchaelMainer** [comment]
@adrichema No, we made no changes on the client. We can't speak to the service API.
