### ISSUE TITLE
Planner Plan creation succeeds (Plan created) but Library throws an Exception

### ISSUE THREAD

**Issue by OliverUlm** [microsoftgraph/msgraph-sdk-dotnet#504]
Since this weekend upon creation of a Planner Plan the library throws an Exception: "You do not have the required permissions to access this item, or the item may not exist." The plan is however created and fully functional.

Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior

Plan is created and no exception is thrown. This was the behavior prior to this weekend.

### Actual behavior

Plan is created but an exception is thrown.

You do not have the required permissions to access this item, or the item may not exist.

```Inner error

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Steps to reproduce the behavior

.Net Framework 4.7
Visual Studio 2017
Microsoft.Graph 1.15.0

```var user = await graphClient.Users[ownerEmail].Request().GetAsync();
var svcUser = await graphClient.Users[usr].Request().GetAsync();

var groupReq = graphClient.Groups.Request();
Group newGrp = await groupReq.AddAsync(new Group()
{
  DisplayName = planName,
  MailEnabled = false,
  MailNickname = planName.Replace(' ', '_'),
  SecurityEnabled = true,
  GroupTypes = new List<string>() { "Unified" }
});

await graphClient.Groups[newGrp.Id].Members.References.Request().AddAsync(svcUser);
await graphClient.Groups[newGrp.Id].Members.References.Request().AddAsync(user);

PlannerPlan newPlan = await graphClient.Planner.Plans.Request().AddAsync(new PlannerPlan() { Title = planName, Owner = newGrp.Id });```

**Comment by MIchaelMainer** [comment]
Are you still experiencing this issue? Was it working as expected before and for how long? What was the exception?

**Comment by OliverUlm** [comment]
It had been working for 1 week befor the issues started. 3 days later it started working again. I therefore assume that it was an issue with the underlaying Graph API and not the library. Sorry, I don't remember the type of exception that has been thrown during that timeframe - this was the exception message: 

> You do not have the required permissions to access this item, or the item may not exist.

**Comment by MIchaelMainer** [comment]
Got it. Okay, sounds like a transient error. Please reopen if this is not the case.
