### ISSUE TITLE
Supports $skiptoken for paging in version 1.0.1?

### ISSUE THREAD

**Issue by itabo** [microsoftgraph/msgraph-sdk-dotnet#51]
I tried to implement paging for Drive prop. I can´t find the way to append $skipToken to the request.

**Comment by MIchaelMainer** [comment]
You can use the QueryOption.

```
var query = new List<Option>()
 {
  new QueryOption("$skiptoken", "sometoken")
 };

graphClient...Request(query).GetAsync();
```

**Comment by itabo** [comment]
Great!. Thanks!

**Comment by MIchaelMainer** [comment]
@itabo You're welcome. I was wondering whether you can give us some feedback on the .Net client library for .Net. 

What is your experience using this library? What features are you using?

Is it intuitive to use? What challenges do you have while using it? Does this client design make sense to you as a .Net developer?

What would be on your wishlist for a .Net client library (this library, or some other form)?

**Comment by itabo** [comment]
Of course, my pleasure.
I think is very intuitive library, since the moment it follows the shema of Microsoft Graph Api. 
We use most of the drive feature in our project. And let me say it help us  a lot in development. Great experience to us.

One of the great feature that me and my team think will be great to have, is the  support “contains” filter. Today is not enough with "startWith" or "equal" to increase the experience of the users.

I thinks all of .net developers should using this kind of SDK´s in our project, because we win a lot of time and less resources to get the goals.

Congrats and thanks for this.
