### ISSUE TITLE
Querying external users using UPN GraphServiceClient.Users

### ISSUE THREAD

**Issue by christopher-walker** [microsoftgraph/msgraph-sdk-dotnet#512]
- [x ] Expected behavior.
entering a get request "https://graph.microsoft.com/v1.0/users/<upn>" should return the user details
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/users.md

- [x] Actual behavior
This works fine for internal users and has been working fine for external users (guests) for the last 2-3 years however now only works for internal users.

```
Code: Request_BadRequest
Message: Bad Request - Error in query syntax.
Inner error
```

> Microsoft.Graph.ServiceException:
>    at Microsoft.Graph.HttpProvider+<SendAsync>d__19.MoveNext (Microsoft.Graph.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.Graph.BaseRequest+<SendRequestAsync>d__36.MoveNext (Microsoft.Graph.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.Graph.BaseRequest+<SendAsync>d__32`1.MoveNext (Microsoft.Graph.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at Microsoft.Graph.UserRequest+<GetAsync>d__6.MoveNext (Microsoft.Graph, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>    at MyApplication.Controllers.WorkflowController+<EnsureUser>d__41.MoveNext (MyApplication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)

- [x] Steps to reproduce the behavior.
It is possible to reproduce this behaviour using the Graph Explorer (therefor I think this is a change in the GraphAPI itself but cannot find anywhere to report it):

https://developer.microsoft.com/en-us/graph/graph-explorer

if you find a guest user in Active Directory then copy and its id and append it to the following:
https://graph.microsoft.com/v1.0/users/
i.e. https://graph.microsoft.com/v1.0/users/USERGUID

you will get a response including the UPN.

if you then url encode the upn (if it is an guest/external user it should have #EXT# in it) you basically replace the #'s with %23  and the @ with %40

It will not allow you to search for an external user with its upn

### Expected behavior

It should resolve the user via its upn

### Actual behavior

you get an error back 

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Bad Request - Error in query syntax.",
        "innerError": {
            "request-id": "160e8118-b1a4-4b16-9b5b-ba38661f7d53",
            "date": "2019-07-09T14:46:44"
        }
    }
}
```

### Steps to reproduce the behavior

This is already include above

After looking at our logging I can see that this issue started to occur after 2019-06-28 (this was the last successful resolution of an external user).

The issue was reported to me on Friday 2019-07-05.

**Comment by MIchaelMainer** [comment]
@christopher-walker Thank you for reporting this issue. Just to clarify, are you searching for an external user using the $search query parameter or are you requesting the user information with the encoded UPN like /users/{url encoded external user's upn}?

Let's see if I can find more info on this.

**Comment by MIchaelMainer** [comment]
@dkershaw10 customer reports breaking change when querying external users. Can you take a look at this?

**Comment by christopher-walker** [comment]
> /users/{url encoded external user's upn}

@MIchaelMainer I am using the second one /users/{url encoded external user's upn} it works fine for external users (guests) if you use their Active Directory ID but not if you use their UPN's

**Comment by christopher-walker** [comment]
Hi,
 It seems as though the service is now working as expected again so I am closing the issue :) ... thanks for your help.

Chris
