### ISSUE TITLE
Cloning a team using teams/clone creates sharepoint site but is not creating a team

### ISSUE THREAD

**Issue by POFerro** [microsoftgraph/msgraph-sdk-dotnet#516]
Hi,

I'm trying to clone a team by using teams/clone graph method:
https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0
The behavior I get is the SharePoint site gets created, all the api responds as if there was a team associated with the Group but the team is not visible in Teams.
This behavior is quite new, I've used this method before and everything was fine but now I get this weird behavior, at first I thought it was a timing issue and waited for a day to my team to appear but nothing happened, I also tried the beta version of the api and the behavior is the same.
Also when I go to the SharePoint Group site a banner appears in the lower left corner saying the group doesn't have a team and has an option to create a team, when clicking it says there was an error creating the team.
Can you help me? This method is the core of my project provisioning system in the company so this is quite blocking.

Thanks in advance
POFerro

**Comment by POFerro** [comment]
Hi, I just realized that in fact the team was created, it took all weekend to appear in Teams app but finally (today) it came to live. Is this behavior expected?

**Comment by darrelmiller** [comment]
Any guidance here?  /cc @nkramer

**Comment by POFerro** [comment]
Hi guys,

I don't know if it's related but now I'm getting a status 400: BadRequest as response:
HTTP/1.1 400 Bad Request
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json
request-id: 3ce9e4bd-042d-4ca8-b05c-f6ab688cd0e3
client-request-id: 3ce9e4bd-042d-4ca8-b05c-f6ab688cd0e3
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_39","ADSiteName":"WEU"}}
Duration: 3123.0201
Strict-Transport-Security: max-age=31536000
Date: Mon, 22 Jul 2019 23:32:46 GMT

212
{
  "error": {
    "code": "BadRequest",
    "message": "Failed to execute settings store request: https://settings.teams.skype.com/emea/v1.0/settings/teams/teams/19:f6e80ba0d5de4536ac3edd3bbf0241ca@thread.skype/templateprovisioning, StatusCode: 400, ReasonPhrase: Schema validation errors, X-MSEdge-Ref: Ref A: 44BEA7B483FC419E92FB06F2851519BB Ref B: DB3EDGE1613 Ref C: 2019-07-22T23:32:47Z",
    "innerError": {
      "request-id": "3ce9e4bd-042d-4ca8-b05c-f6ab688cd0e3",
      "date": "2019-07-22T23:32:47"
    }
  }
}
0

The team gets created but is incomplete, only has the Channel general and standart tabs, no channels or tabs get cloned from the template team.
Can you help?

Best regards
POFerro

**Comment by POFerro** [comment]
Hi again, I figured out about the 400 Status response, it happens when my template tab includes a yammer Tab. I opened a new issue #518 regarding that behavior.
As of this issue I'm closing it since it never happend again.

Thanks and best regards.
