### ISSUE TITLE
Weird Visual Studio messages in Xamarin.iOS project

### ISSUE THREAD

**Issue by tipa** [microsoftgraph/msgraph-sdk-dotnet#517]
VS 16.1.6
Xamarin.iOS 12.10.0.157

Nuget:
Microsoft.Graph1.16.0
Microsoft.Graph.Core 1.16.0

### Expected behavior
No warnings

### Actual behavior
Getting plenty of Visual Studio warnings/messages
![image](https://user-images.githubusercontent.com/2863198/61153518-c58af980-a4eb-11e9-964c-e4fc92548752.png)

### Notes
The issue does not happen in a UWP or Android project

**Comment by peombwa** [comment]
Thanks for bring this to our attention. We will look into it and see if there is something we can do on our end to address these warnings.

**Comment by tipa** [comment]
Doesn't seem to happen any more with the latest nuget package
