### ISSUE TITLE
Deadlock in async code

### ISSUE THREAD

**Issue by atorresGit** [microsoftgraph/msgraph-sdk-dotnet#52]
In BaseRequest class, SendAsync method, around line 132, when the response its being read, should be calling configureAwait(false).
We are using the library in a website with legacy sync code and we are having a deadlock because of this. Please can you put a tag in the code, signaling version 1.0.1, so we can fork that code and fix this in our solution. We can't use the latest version, because we need to keep using json.net 6.0.2.
I tried to create a pull request, but I don't have permissions.
Thanks!

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. I'll take a look at this. By the way, you should be able to update to the latest Nuget package. Nuget's default behavior is to use the earliest version of dependencies. Since you already have 6.0.2 installed, I expect that Nuget will keep that dependency if you update. Let us know if it behaves any differently.

**Comment by MIchaelMainer** [comment]
Under what circumstances did you encounter the deadlock? What call were you making?

**Comment by atorresGit** [comment]
This is not the real code, but will give you an idea on how its being used:
`public void ProcessProfile()
{
	...
	var user = GetCurrentUser().Result; // change ProcessProfile() to async will imply a big refactor
	DoThingsWithUser(user);
	...
}

public async Task<GraphUser> GetCurrentUser()
{
	...
	var me = await graphServiceClient.Me
									 .Request()
									 .GetAsync()
									 .ConfigureAwait(false); // here we have the deadlock...
	...                                 
	return me;
}`

All this is used in a controller of a MVC3 website (ASP.NET synchronizationContext)

**Comment by MIchaelMainer** [comment]
@atorresGit What exactly is the change that you'd like to get in BaseRequest.cs? I see the missing COnfigureAwait, but what else do you want to add in there?

**Comment by MIchaelMainer** [comment]
Fixed with 837cd1f
