### ISSUE TITLE
Support ImmutableId

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/msgraph-sdk-dotnet#522]
The immutable ID is in preview - https://docs.microsoft.com/en-us/graph/outlook-immutable-id
Please consider adding support for it in this library.
I'd like to send mail and create subscriptions using the new format.

If there is a workaround to get this behavior please share it.

**Comment by MIchaelMainer** [comment]
It looks like this support is already in the beta SDK. https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Models/Generated/UserTranslateExchangeIdsRequestBody.cs

All you need to do is add the header as specified in the documentation.

**Comment by Misiu** [comment]
@MIchaelMainer thanks for the link, I didn't know about beta SDK.
How can I set `Prefer: IdType="ImmutableId"` for other requests? For example when creating WebHooks, to get notifications with immutable identifiers.

When this (ImmutableId) will be added to the normal graph endpoints?
It was announced on September 14 2018 and was added to beta on January 15 2019 - https://developer.microsoft.com/en-us/office/blogs/announcing-immutable-id-for-outlook-resources-in-microsoft-graph/

**Comment by MIchaelMainer** [comment]
I have no idea when immutable ID will be supported in the v1.0 endpoint. Here is how you can set the header.

                            var headerOptions = new List<HeaderOption>()
                            {
                                new HeaderOption("Prefer", "IdType=\"ImmutableId\"")
                            };

                            var permission = await graphClient.Me.Drive
                                                                 .Items[driveItem.Id]
                                                                 .Permissions[driveItem.Permissions[0].Id]
                                                                 .Request(headerOptions)
                                                                 .UpdateAsync(perm);

**Comment by Misiu** [comment]
@MIchaelMainer thank You for the example :)
In blog post I linked (https://developer.microsoft.com/en-us/office/blogs/announcing-immutable-id-for-outlook-resources-in-microsoft-graph/) is this info:

> UPDATE (Jan 15, 2019): This feature is now available in Microsoft Graph v1.0 and beta as an “opt-in”. Graph will continue to return regular IDs by default.

So when I add required header graph should return `ImmutableId`. I'll check that.

Ideally, there should be a property to set on graphClient to use ImmutableIds or at least extension method `WithImmutableId()` for request, similar to `WithMaxRetry()`

```
var permission = await graphClient.Me.Drive
                                           .Items[driveItem.Id]
                                           .Permissions[driveItem.Permissions[0].Id]
                                           .Request()
                                           .WithImmutableId()
                                           .UpdateAsync(perm);
```

**Comment by MIchaelMainer** [comment]
This would be really useful. For the now, you can add something like this as an extension in the Microsoft.Graph namespace to enable it.

```csharp
public static T WithImmutableId<T>(this T baseRequest) where T : IBaseRequest
{
     baseRequest.Headers.Add(new HeaderOption("Prefer", "IdType=\"ImmutableId\"");
}
```

**Comment by pschaeflein** [comment]
Excellent suggestion @MIchaelMainer ! 

I've added this to the [Graph.Community library](https://www.nuget.org/packages/Graph.Community/1.16.1): 

```csharp
var messages = 
  graphServiceClient.Me.Messages.Request()
      .GetAsync();

var messagesI = 
  graphServiceClient.Me.Messages.Request()
      .WithImmutableId()
      .GetAsync();

/*
  messages.CurrentPage[0].Id = "AAMkAGRlMmUwYzU3LTljYzAtNGY1ZS05MWY2LTA3ZTMxODc0NTQ0MgBGAAAAAACTdm_EL3wkQL67J0YAoaqyBwD_kS0bRwm1Qa1z_mGcEREtAAAAAAEMAAD_kS0bRwm1Qa1z_mGcEREtAAA_pBpMAAA="
  messagesI.CurrentPage[0].Id = "AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A-pEtG0cJtUGtc-phnBERLQAAPqQr4AAA"
*/
```

**Comment by MIchaelMainer** [comment]
Or even better yet, use the Graph community library championed by Paul as he's already added it and other potentially useful extensions.

**Comment by Misiu** [comment]
@MIchaelMainer thank You for the code. Ideally, this extension should be added here.

Will same header work for subscriptions? If I want to get emails in notifications with immutable id's I should add that header to subscription request?
```
var subscription = await graphClient.Subscriptions.Request().WithImmutableId().AddAsync(new Subscription
{
    Resource = $"me/mailFolders('Inbox')/messages",
    ChangeType = "created, updated",
    NotificationUrl = "https://example.com/api/notifications",
    ClientState = Guid.NewGuid().ToString(),
    ExpirationDateTime = DateTimeOffset.UtcNow + new TimeSpan(0, 0, 5, 0)
});
```

**Comment by MIchaelMainer** [comment]
@Misiu  I suspect that it should for mail, contacts, and events.

**Comment by darrelmiller** [comment]
Hey @svpsiva do we have an ETA on ImmutableId making it into V1.0?

**Comment by pschaeflein** [comment]
It already is. I posted a bug on the docs page:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/5374

**Comment by Misiu** [comment]
@darrelmiller can you reopen this? this should be added to this lib

**Comment by Misiu** [comment]
@darrelmiller @MIchaelMainer ImmutableId is in docs: https://docs.microsoft.com/en-us/graph/outlook-immutable-id, so maybe [this ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/522#issuecomment-517396733)extension method could be added here?

**Comment by Misiu** [comment]
any updates?

**Comment by Misiu** [comment]
ping

**Comment by MIchaelMainer** [comment]
@Misiu I respect your persistence. I'm sorry we haven't gotten back to you sooner.

I have a couple of concerns with this solution. 
1. The extension constraint is too broad. The immutableId support is only supported on Exchange based APIs. IBaseRequest applies to all requests so it is too broad a constraint. I don't want to add another client API signature that is overly broad and not supported by many of the service APIs. Of course you could argue why start being concerned now.... ;) well, we do plan to restrict our generated client API surface at some point.
2. There currently isn't a mechanism in the metadata for us to trigger the generation for just the Exchange APIs. Eventually, we should have this. 

cc:/ @ddyett @zengin We should consider this scenario when we devise a annotation term nomenclature so that APIs can be marked as supporting a specific header+values.

**Comment by Misiu** [comment]
@MIchaelMainer thanks for the update.
The extension method that you provided before works really well.
Recently I returned to Graph development and I remembered about this issue. That's the reason I added `ping` 🙂

You are right, if only the Exchange based APIs support this header then there should be some way to restrict adding it to other requests. But on the other hand, if someone adds it to request and the backend (API) doesn't support it then nothing should break.

**Comment by danarcher** [comment]
For readers coming to this issue looking for a way to request immutable IDs with SDK, a word of caution that [the WithImmutableId() extension method above](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/522#issuecomment-517396733) does not work well with paging, at least with 1.0.0-preview.5.

This may be very obvious to people more familiar with the SDK, but I found out the hard way that adding headers to the initial Request() this way does not add them to subsequent requests for multiple pages. So the first page of messages' IDs will be immutable, but not the remainder.

This can lead to some very confusing bugs in client code, where IDs for the same message appear to change depending on e.g. the date range of a query, if that influences the number of messages received, and so interacts with paging.

My workaround was to instead create a custom IHttpProvider which mostly delegates to the standard HttpProvider, but always adds the "prefer immutable" header to relevant requests. I pass this to the GraphServiceClient constructor, and now all pages have immutable IDs.

**Comment by MIchaelMainer** [comment]
@danarcher Are you using the PageIterator? If so, the [Add delegate to PageIterator to allow consumers to configure next page request](https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/853) PR by the esteemed @pschaeflein can be used to configure the BaseRequest.

**Comment by pschaeflein** [comment]
Thanks @MIchaelMainer ! You're too kind.

**Comment by danarcher** [comment]
@MIchaelMainer I am and thanks, that sounds ideal! I hadn't seen that in the docs. Thanks @pschaeflein for your work 👍
