### ISSUE TITLE
Add overload for Select(Expression<>selectExpression) to DeltaRequests as well

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet#524]
(*)DeltaRequest classes currently do not seem to support the Select(Expression<>selectExpression) overload while the normal entity request classes do.
A good example is the ContactRequest which has two overloads for select i.e. Select(string value) and Select(Expression<Func<Contact, object>> selectExpression).
However, looking at the ContactDeltaRequest class we only have the Select(string value).
It would be great if all the (*)DeltaRequest classes supported the Select(Expression<>selectExpression) overload as well.
[AB#6092](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6092)

**Comment by MIchaelMainer** [comment]
This needs to go in the generator. First check if there is a common base class for Delta query that could support this.

**Comment by andrueastman** [comment]
Looking at the SDK generator source, the difference I can infer is that the  `Select(Expression<Func<Contact, object>> selectExpression)` overload is currently generated for entity types using the EntityRequest template [here ](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/29d268b7fb11ca4dcfe53c0f71f84be023f6b08e/Templates/CSharp/Requests/EntityRequest.cs.tt#L62)then [here](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/29d268b7fb11ca4dcfe53c0f71f84be023f6b08e/Templates/CSharp/Base/EntityRequest.Base.template.tt#L496).

However, Delta queries are generated using the MethodRequest template which only generates the string overload [here](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/29d268b7fb11ca4dcfe53c0f71f84be023f6b08e/Templates/CSharp/Requests/MethodRequest.cs.tt#L513).

**Comment by andrueastman** [comment]
Closing this for now. 
Kiota already addresses consistent generation of Select expressions and is shown/decribed here. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#query-options
