### ISSUE TITLE
ParentWindow causing AcquireTokenInteractive to fail

### ISSUE THREAD

**Issue by robiharid** [microsoftgraph/msgraph-sdk-dotnet#527]
Issue:
On Xamarin.Android, you have to specify the current Activity from which the browser pop-up will be displayed using the WithParentActivityOrWindow method.

Code (App.xaml.cs):
`
        public static object ParentWindow { get; set; }

        public App()
        {
            InitializeComponent();

            IdentityClientApp = PublicClientApplicationBuilder
                .Create(ClientID)
                .WithAuthority(AzureCloudInstance.AzurePublic, TenantID)
                .WithRedirectUri(RedirectUri)
                .Build();`

The code that throws the exception:
`
                    authResult = await App.IdentityClientApp
                        .AcquireTokenInteractive(App.Scopes)
                        .WithParentActivityOrWindow(App.ParentWindow)
                        .ExecuteAsync();`

Debugging it, App.ParentWindow is null, even though I set it to this in MainActivity.cs.
I put a break point on the MainActivity.cs and the App.ParentWindow isn't being called in the OnCreate method.

It seems like XamarinForms has a different OnCreate() method in MainActivity and it is missing "Instance = this;"
`
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            
            LoadApplication(new App());
            App.ParentWindow = this;
        }`

**Comment by MIchaelMainer** [comment]
Please use github.com/microsoftgraph/msgraph-sdk-dotnet-auth to get a provider for getting access tokens. Use the InteractiveAuthorizationProvider.
