### ISSUE TITLE
how to create event and how to create task?

### ISSUE THREAD

**Issue by lhp620** [microsoftgraph/msgraph-sdk-dotnet#53]
anyone could provide the code sample for using the SDK? Thanks.

**Comment by lhp620** [comment]
anyone could provide the code sample for using the SDK? Thanks.

**Comment by MIchaelMainer** [comment]
There are many code samples at github.com/microsoftgraph that you can use for reference. Here's a link to how to create an event: https://github.com/microsoftgraph/uwp-csharp-snippets-sample/blob/master/Microsoft-Graph-Snippets-SDK/Users/UserSnippets.cs#L186

Tasks is in preview and is not currently available in the .Net client library.
