### ISSUE TITLE
Can't find TeamsTab property sortOrderIndex in sdk

### ISSUE THREAD

**Issue by POFerro** [microsoftgraph/msgraph-sdk-dotnet#530]
Hi,

As documented in listTabs method here: https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0 there should be a sortOrderIndex Property in teamsTab object. Using the c# sdk I can't seem to see it or even OrderBy it (throws an exception saying it doesn't exist).
Can anyone help?

Thanks and best regards

**Comment by ddyett** [comment]
check additionalproperties.
