### ISSUE TITLE
WithMaxRetry doesn't work when creating subscriptions (graph is returning 400)

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/msgraph-sdk-dotnet#531]
I'm trying to create Azure Function App that will be responsible for creating subscriptions and second that will handle notifications.
Because of Azure Function Apps have "cold start" I have the following problem:

I'm creating subscription like so:

```
var newSubscription = new Subscription
{
    ChangeType = "updated",
    NotificationUrl = "https://abstest.azurewebsites.net/api/MailNotifications",
    Resource = $"users/{mailbox}/mailFolders('sentitems')/messages",
    ExpirationDateTime = DateTimeOffset.UtcNow.AddHours(1),
    ClientState = Guid.NewGuid().ToString()
};

await _graphClient.Value.Subscriptions
    .Request()
    .WithMaxRetry(10)
    .AddAsync(newSubscription);
```

but when my notification function was inactive it has no instances and I get this error:

> [2019-08-23 10:18:11] System.Private.CoreLib: Exception while executing function: RefreshSubscriptions. Microsoft.Graph.Core: Code: InvalidRequest
> [2019-08-23 10:18:11] Message: Subscription validation request timed out.

I've run my function locally and I saw in Fiddler that the request responsible for creating the subscription (/v1.0/subscriptions) gets 400 in response and this body:
```
{
  "error": {
    "code": "InvalidRequest",
    "message": "Subscription validation request timed out.",
    "innerError": {
      "request-id": "6b37129f-3ffd-4e68-ae1f-373068f5d1ef",
      "date": "2019-08-23T10:27:12"
    }
  }
}
```

I thought that `WithMaxRetry` should help in solving this problem, but as it looks it isn't.

Should `WithMaxRetry` work for request returning 400 status code? If yes, then this is a bug, if no then this is a feature request.

I'm aware I can use tools like Polly to retry invalid request's but I'd like to have this retry logic build in.

**Comment by MIchaelMainer** [comment]
MaxRetry works on 429 - this is not a retry issue. Your service at https://abstest.azurewebsites.net/api/MailNotifications is not returning a 200 response. That is the missing validation. 

Please take a look at this content for guidance.
https://docs.microsoft.com/en-us/graph/webhooks#notification-endpoint-validation

**Comment by Misiu** [comment]
@MIchaelMainer my endpoint is returning 200, but because it is Azure Function App it needs some time to spin up, because of "cold start".
I know that first request is with `validationToken` param and I have correctly implemented logic for that. When I call my Function App after deployment it needs about 5 seconds to get a response, but Graph isn't waiting that long and it is returning 400 with error I pasted above.

I hope this clears things up :)

I'll try looking at retry middleware, maybe I figure something out.

**Comment by pschaeflein** [comment]
Because of this 5 second validation requirement, Azure Functions is not the best choice for hosting a subscription listener. (Unless you run in an AppService plan or premium with always on.)

**Comment by Misiu** [comment]
@pschaeflein I wanted to give Azure Function App a try. I guess it's not that ideal as I thought.
I can add retry logic when I create a new subscription, but do You know what is the timeout on the MS Graph when my endpoint is called?
I'm creating a subscription for sendmail folder, so when mail is sent graph will call my endpoint. Will graph resend the same request when the first request got a timeout? Is there a retry policy on Graph?

**Comment by Misiu** [comment]
> No, I don't think there is a retry on timeout for sending notifications from the Graph service.
 
I found [this on StackOverflow](https://stackoverflow.com/a/36871875/965722):

> Graph Webhook will try to send the events a number of times within 4 hours window. If the client does not come back online after 4 hours, then these events will be deleted.

but I must find the same (official) info in MS documentation.

> You would need to replace the retry handler in the client library with your own retry handler that will retry on 400 only when calling the subscription endpoint.

Currently, I used Polly with RetryPolicy for that. After some tests, it works fine, but I'll take a look at creating a custom retry handler.
It looks like I need to override [this function](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/b901700751d1d72357584e08a4b1f9eff3ad94f3/src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs#L184), sadly it is private, so I must copy a lot of code.
