### ISSUE TITLE
Support User.MailboxSettings with only MailboxSettings.Read

### ISSUE THREAD

**Issue by matt-sullivan** [microsoftgraph/msgraph-sdk-dotnet#538]
There is currently no .Net way to read users' MailboxSettings with only (Application) MailboxSettings.Read permissions.

client.Users[id].Request().Select("MailboxSettings").GetAsync()
calls https://graph.microsoft.com/v1.0/users/xxx?$select=mailboxSettings
and gets an access denied error. This seems like a bug in the graph service, but I'm not sure of that and not sure where to report it.

It is possible to query https://graph.microsoft.com/v1.0/users/xxx/mailboxSettings with only those permissions, however I don't think this library has any way to query that url.

Should a MailboxSettings property be added to IUserRequestBuilder?

https://stackoverflow.com/questions/54750940/access-denied-when-trying-to-get-my-mailboxsettings-using-select-with-mailboxset relates to this issue. 
[AB#7299](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7299)

**Comment by MIchaelMainer** [comment]
Marked your initial concern as a service issue which we will discuss with service owner a bit later today. 

We are aware that our generated library doesn't provide navigation to the mailboxsettings resource. We have plans to provide a generic way to address this issue. Adding a partial for IUserRequestBuilder for Mailboxsettings would provide the functionality to access MailboxSettings. That would require a few other files as well.

**Comment by MrTantum** [comment]
Please also add a possibility to only load specific settings of the mailbox settings. E.g. by directly using the endpoint for the mailboxsettings language:

GET https://graph.microsoft.com/v1.0/me/mailboxSettings/language

as described [here](https://docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&tabs=http).

**Comment by pschaeflein** [comment]
@matt-sullivan As an interim measure, the UserSettings resource has been added to the community library.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/master/test/UserMailboxSettingsRequestTests.cs

**Comment by MIchaelMainer** [comment]
Here's how you can use the SDK in its current state to get mailboxsettings.

```csharp
async Task GetMailboxSettings(GraphServiceClient client)
{
	var mailboxSettingsUrl = client.Users["adelev@contoso.onmicrosoft.com"].RequestUrl + "/mailboxsettings";
	HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Get, mailboxSettingsUrl);
	
	await client.AuthenticationProvider.AuthenticateRequestAsync(hrm);
	
	HttpResponseMessage response = await client.HttpProvider.SendAsync(hrm);

	if (response.IsSuccessStatusCode)
	{
		// Deserialize into OneNotePage object.
		var content = await response.Content.ReadAsStringAsync();
		MailboxSettings mailboxSettings = client.HttpProvider.Serializer.DeserializeObject<MailboxSettings>(content);
	}
}
``` 

You can append individual settings to the end of mailboxSettingsUrl. You will need to change the deserializaton target.

**Comment by LeightonSean** [comment]
I've been following this thread because I was experiencing the same issue but today I discovered it is working and I can get the MailboxSettings with just MailboxSettings.Read. Was there any update that resolved this?

**Comment by andrueastman** [comment]
This was fixed silently on the API side. Closing this as it is now resolved.
