### ISSUE TITLE
Encoding of pound character for external users

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#539]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
Dotnet SDK to encode pound character so queries to external users work.

### Actual behavior
Dotnet SDK doesn't encode pound character which results in a null return value.

### Steps to reproduce the behavior
1. Invite an external user to your organization (in my case I invited the user vincent@2tolead.com to the org baywet.onmicrosoft.com)
2. Try to query the external user like this
```CSharp
var user = await client.Users["vincent_2tolead.com#EXT#@baywet.onmicrosoft.com"].Request().GetAsync(); // this will not return the user
var user2 = await client.Users["vincent_2tolead.com%23EXT%23@baywet.onmicrosoft.com"].Request().GetAsync(); // this will return the user
``` 
[AB#7300](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7300)

**Comment by MIchaelMainer** [comment]
Thank you @baywet for bringing this up.

**Comment by stewartadam** [comment]
@MIchaelMainer any updates on this? I'm running into this as well with the encoding for mailbox extensions (foo+bar@domain.tld). The query fails, if I run trace it via App Insights and run the Graph query manually replacing `+` for `%2B` it works.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1515

Closing this one for now as this is resolved with V5 of the SDK which uses URL templates that automatically encode the URL segments based on the HTTP specification
