### ISSUE TITLE
Right way to use NextPageRequest? Perhaps I'm doing it wrong, because it fails (never ending loop)

### ISSUE THREAD

**Issue by horacioj** [microsoftgraph/msgraph-sdk-dotnet#54]
Is this the right way to use **NextPageRequest**? 
(and don't tell me "use await instead .Result", I know...)

``` c#
var driveItems = new List<DriveItem>();

var items = graphClient.Me.Drive.Root
            .ItemWithPath("/Many Items/Lots of items/1280 items") 
            .Children.Request().Top(1000).GetAsync().Result;

driveItems.AddRange(items.CurrentPage);

var next = items.NextPageRequest;

while (next != null)
{
    items = graphClient.Me.Drive.Root
            .ItemWithPath("/Many Items/Lots of items/1280 items") 
            .Children.Request(next.QueryOptions).GetAsync().Result;

    driveItems.AddRange(items.CurrentPage);

    next = items.NextPageRequest;
}

return driveItems;
```

I guess I'm doing it wrong, because it fails: Never ending loop (the 'while...') - **but just sometimes, not always** - the exact same code and exact same data. 
It doesn't matter if I use the default page size (200), or 1000, or whatever.
Sometimes, at some point, for every request, NextPageRequest is always returning the same $skiptoken.
This is driving me crazy...

Unrelated question: is the SDK implementing [largefile uploads](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_createuploadsession)? 

Many thanks!

**Comment by MIchaelMainer** [comment]
Thank you for contacting us. We typically direct questions about the API to StackOverflow -- use the [microsoftgraph] tag for questions about the API. Questions about the API should include a trace of the request/response. With that being said, here's a response.  

I'm seeing some strange behavior in the nextlink that is returned in a response. I'm going to verify that the nextlink value is correct. It may cause the problem with the forward paging. You are probably alright -- there may be an issue with the service API. I'll loop back with more info.

**Comment by horacioj** [comment]
Thanks, MIchael.
If it is confirmed to be a problem, would it be in the API (server side - no workaround,) or the .NET SDK (workaround: skip it and use REST directly)?

**Comment by MIchaelMainer** [comment]
You can still use Top and Skip to do the paging instead of the NextPageRequest (nextLink). You'll just need to manage the paging yourself instead of using the nextLink.

**Comment by horacioj** [comment]
Ok. I'll try this approach. 
In terms of performance, would it be the same? The current implementation (the code in the first post) is actually pretty slow. 
Many thanks.

**Comment by horacioj** [comment]
Sorry to bother again, and I'll post this in StackOverflow too, but $skip doesn't seem to work at all, or I don't understand [what it is supposed to do](http://graph.microsoft.io/en-us/docs/overview/query_parameters#skip). 

Even testing it from the [Graph Explorer](https://graph.microsoft.io/en-us/graph-explorer#). $skip is ignored. With or without including also a $top parameter ($top does work fine).

Example:

````
https://graph.microsoft.com/v1.0/me/drive/root:/myFolde/subFolder:/children?$skip=4
````

or

````
https://graph.microsoft.com/v1.0/me/drive/root:/myFolde/subFolder:/children?$skip=4&top=4
````

or

````
https://graph.microsoft.com/v1.0/me/drive/root:/myFolde/subFolder:/children?$skip=2&top=4
````

It always start from the first item (as if $skip wasn't specified).

**Comment by MIchaelMainer** [comment]
My bad, skip isn't supported. Now, I've tried the nextLink (NextRequestPage), and it is **now** working as expected. It seems like it was a transient issue. Can you confirm that it is working on your side?

                var driveItems = new List<DriveItem>();
                var driveItemsPage = await graphClient.Me.Drive.Root.Children.Request().GetAsync();
                driveItems.AddRange(driveItemsPage.CurrentPage);
                while (driveItemsPage.NextPageRequest != null)
                {
                    driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();
                    driveItems.AddRange(driveItemsPage.CurrentPage);
                }

**Comment by horacioj** [comment]
Today, I tried running it many times, and all succeeded. Yesterday some succeeded, and some failed. I hope it stays stable... A never-ending loop could be a big issue.

Notice your version of the code works fine for the root only. If I want to get the items of a not-root folder:
```c#
var driveItemsPage = await GraphClient.Me.Drive.Root.ItemWithPath(path).Children 
                                  .Request().Top(500)
                                  .GetAsync();
```

Then  "driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();" (within the while)  doesn't work. It returns items from the root, not the folder I was querying.
I don't know if there is a more elegant way, but this (apparently)  works (inside the while):
```c#
driveItemsPage = await GraphClient.Me.Drive.Root.ItemWithPath(path).Children
                              .Request(driveItemsPage.NextPageRequest.QueryOptions)
                              .GetAsync();
```

driveItemsPage.NextPageRequest.QueryOptions includes both the skiptoken and the original top (page size) setting.

**Comment by MIchaelMainer** [comment]
@horacioj Sorry for the late follow up on this. I repro that issue when using the ItemWithPath request builder. 

Another option is to use this form to get the first page.
`
var driveItemsPage = await graphClient.Me.Drive.Items["015U5LKCS34Q6NKSEKZVDZMNVKDTXJ4CUR"].Children.Request().Top(1).GetAsync();` 

NextPageRequest works as expected with this

So, there is an issue in the templates where ItemWithPath method isn't appending the itemPath segment when using Root..

**Comment by horacioj** [comment]
Thanks, Michael. I switched everything to be done by ID, instead of by path.

**Comment by MIchaelMainer** [comment]
This is an issue with the service returning an invalid nextLink when using the ItemWithPath form. The client library is functioning as expected. I've opened an issue with the service owner to get this fixed. Please open another issue if there is a bug with this library.

**Comment by sk-** [comment]
This seems to be a problem with how Microsoft implements and documents their APIs. We were recently a victim of this (starting around June 16, 2019), in which the Graph APIs started to always return the same `nextLink`, which caused us to be stuck in a loop.

**Comment by darrelmiller** [comment]
@sk- Could you provide the details of the particular resource that was providing an invalid next link?  The behaviour of specific resources is dependent on a individual service team. nextlink creation is not a Graph wide behaviour.  Thanks.

**Comment by sk-** [comment]
This happened with the endpoint `https://graph.microsoft.com/v1.0/me/messages`. Note that this was not happening before and changed without notice.

**Comment by Mrcl1450** [comment]
Same here with graphClient.Me.People.Request().GetAsync();
```
while (GraphUsers.NextPageRequest != null)
{
  GraphUsers = await GraphUsers.NextPageRequest.GetAsync();
  AllGraphUsers.AddRange(GraphUsers.CurrentPage);
}
```
Stuck in a infinite loop where CurrentPage always retrieve the same results

**Comment by MIchaelMainer** [comment]
@Mrcl1450 Was this previously working for you?

**Comment by Mrcl1450** [comment]
Yes

**Comment by VictorioBerra** [comment]
What is `InitializeNextPageRequest` do we need this? Should we use this in the loop? I would highly appreciate a working code snippet with beta showing looping through pages until no more are found.

**Comment by chrisdbishop** [comment]
I tried the code mentioned above:

```
var driveItems = new List<DriveItem>();
var driveItemsPage = await graphClient.Me.Drive.Root.Children.Request().GetAsync();
driveItems.AddRange(driveItemsPage.CurrentPage);
while (driveItemsPage.NextPageRequest != null)
{
  driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();
  driveItems.AddRange(driveItemsPage.CurrentPage);
}
```
But it was an infinite loop.

I solved it with 
```
var top = 5;
var skip = top;
var driveItems = new List<DriveItem>();
var driveItemsPage = await graphClient.Me.Drive.Root.Children.Request().Top(top).GetAsync();
driveItems.AddRange(driveItemsPage.CurrentPage);
while (driveItemsPage.NextPageRequest != null)
{
  var skipOption = driveItemsPage.NextPageRequest.QueryOptions.Single(w => w.Name.Equals("$skip"));
  driveItemsPage.NextPageRequest.QueryOptions.Remove(skipOption);
  driveItemsPage.NextPageRequest.QueryOptions.Add(new QueryOption("$skip", skip.ToString()));
  driveItemsPage = await driveItemsPage.NextPageRequest.GetAsync();
  driveItems.AddRange(driveItemsPage.CurrentPage);
  skip += top;
}
```

Basically, the skip value was not getting updated. I had to manually update the skip value.  And I couldn't just call Request.Skip(nextSkip). Because it just adds this value to the list inside of replacing the existing value.

Version: 1.21.0.0 (Microsoft.Graph)
