### ISSUE TITLE
Subscriptions - List / Delete - Incorrect or Outdated Data Response

### ISSUE THREAD

**Issue by TylerJoaquinCrawford** [microsoftgraph/msgraph-sdk-dotnet#545]
### **Issue**

- A few days ago, `graphServiceClient.Subscriptions.Request().GetAsync()` stopped working for me. The data response was returning null (despite having successfully created one or two test Subscriptions).
- `graphServiceClient.Subscriptions.Request().GetAsync()` is now returning data again, but the data seems to be out of date (I had deleted these subscriptions) and is not returning the ClientState property.
- When I attempt to delete the subscriptions that are returned by `graphServiceClient.Subscriptions.Request().GetAsync()`, the SDK request returns an "object not found" error. So I have these active subscriptions that I now cannot delete.
- I am assuming this may be more of a server issue rather than an SDK one, but my application using these calls is registered as a confidential Active Directory application (for background automation items), so I cannot easily test these calls outside the scope of the SDK.
- Additional info: I am only using the _Messages_ Graph resource.

### **Expected Behavior**
     
- `graphServiceClient.Subscriptions.Request().GetAsync()`
  - Should return data enumeration with valid / up-to-date client subscriptions
- `graphServiceClient.Subscriptions[subscriptionId].Request().DeleteAsync()`
  - Should delete the targeted, active subscription

 ### **Actual Behavior**
     
- `graphServiceClient.Subscriptions.Request().GetAsync()`
  - Returns data enumeration (IGraphServiceSubscriptionsCollectionPage) with client subscriptions that I had deleted
   - **ClientState** property value returns NULL despite having explicitly set it
- `graphServiceClient.Subscriptions[subscriptionId].Request().DeleteAsync()`
  - Attempting to delete one of the subscriptions returned from ''.GetAsync() returns an "Object not found" error

 ### **Screenshots**
_Subscriptions GetAsync()_
![graph_subscriptions_get_sdk_blurred](https://user-images.githubusercontent.com/20195136/65080622-98791e00-d956-11e9-9237-0cf90f0a28f2.png)

_Subscriptions GetAsync() Result_
![graph_subscriptions_get_blurred](https://user-images.githubusercontent.com/20195136/65079783-bd6c9180-d954-11e9-8f2d-3a99ddfa6e73.png)

_Subscription DeleteAsync() Result_
![graph_subscriptions_getbyid_error](https://user-images.githubusercontent.com/20195136/65079784-bd6c9180-d954-11e9-8bb0-f23433533221.png)

### Steps to reproduce the behavior
- Using the Dotnet Graph SDK v1.17.0

- Given pre-existing / active subscriptions registered with a Messages resource

- `var subscriptionsResult = await graphServiceClient.Subscriptions.Request().GetAsync() .ConfigureAwait(false);`

- `var subscriptionToDelete = subscriptionResult.CurrentPage[2];`

- `await graphServiceClient.Subscriptions[subscriptionToDelete .Id].Request().DeleteAsync().ConfigureAwait(false);` 
[AB#7303](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7303)

**Comment by andrueastman** [comment]
Closed per resolution of microsoftgraph/microsoft-graph-docs#4644
