### ISSUE TITLE
Add Owner and ADGroups to AAD Application

### ISSUE THREAD

**Issue by huajunzhao** [microsoftgraph/msgraph-sdk-dotnet#547]
Hi,

I need to implement to add owner and AD groups into the existing AAD application  with C# code.

After some investigation, it looks like we can only use Microsoft Graph SDK or libraries. https://blogs.aaddevsup.xyz/2018/11/how-to-add-an-owner-to-an-azure-ad-application/

Then I found an API reference https://docs.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&tabs=http,

However, it seems graphClient.Applications[] seem only available in beta version: msgraph-beta-sdk-dotnet: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/df000933e84b585d26cc6ab4e3984741853c280a/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs.  I don't see it in https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/3f594675b03a1144c9c065428cc79f24c81573e1/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs

Cloud you please help
- Confirm if i'm using the correct way (Microsoft Graph libraries) to create the owners to an existing aad application? Any other recommendations?
- It's risky to use beta in my production environment. Is there any alternative way to achieve the same functionality if we don't use the Microsoft Graph SDK in beta?

Thanks,
Kevin

**Comment by darrelmiller** [comment]
Hi Kevin,

You don't need to use the Graph SDK to make this call.  You can make a standard HTTP call.  If you do want to use the SDK, you will need to install the beta .NET SDK as the Application API is still only in Beta.

It is not recommended to use Beta APIs in production, but currently, I am not aware of another approach.

**Comment by huajunzhao** [comment]
Thanks @darrelmiller.

If you can direct me some quick example/link on how to make the HTTP call in the C# code to achieve these, that would be much appreciated. We want to achieve two things:
- Add owners
- Join AD groups.
