### ISSUE TITLE
Deserialization exception when adding group to lifecycle policy in Azure Active Directory

### ISSUE THREAD

**Issue by paul-ciobanu** [microsoftgraph/msgraph-sdk-dotnet#549]
- [x] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [x] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [x] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

I'm trying to add a group to a lifecycle policy and the call to
`await Client.GroupLifecyclePolicies[lifecyclePolicyId].AddGroup(groupId).Request().PostAsync(ct);` is throwing exception:
`Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: {. Path '', line 1, position 1.'`

### Expected behavior
The call should not throw

### Actual behavior
The call is throwing

### Steps to reproduce the behavior
Create an Office365 group in Azure Active Directory and add it to a lifecycle policy
and then call 
`await Client.GroupLifecyclePolicies[lifecyclePolicyId].AddGroup(groupId).Request().PostAsync(ct);`

I'm using Microsoft.Graph 1.17.0 from a .NET Framework 4.6.1 project

[addGroupToLifecyclePolicyRequest.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/3657538/addGroupToLifecyclePolicyRequest.txt)
[callstack.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/3657539/callstack.txt)

**Comment by BigEaseGueldi** [comment]
Can confirm this. Using Graph SDK 1.16.0 and .NET 4.7.1.

**Comment by MalteJohansson** [comment]
Is there any update on this exception? 
Still get this exception as of Feb 11, 2020 with Graph SDK 1.21 and .NET Core 2.2.8

**Comment by MIchaelMainer** [comment]
I think I know what is going on here. The AddGroup action returns  boolean. The deserializer expects an object. It can't handle:

```json
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#Edm.Boolean","value":true}
```

This issue may impact any action that returns a primitive.

**Comment by MIchaelMainer** [comment]
related to https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/134

**Comment by MIchaelMainer** [comment]
Release will occur with the following releases:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/800
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/160
