### ISSUE TITLE
Fetching all groups does not return properties of the group

### ISSUE THREAD

**Issue by codecrasher99** [microsoftgraph/msgraph-sdk-dotnet#554]
On trying to fetch all the groups in my tenant
```
var groups = await _graphclient.GetAuthenticatedClient().Groups.Request().Top(998)
                .Select("id,displayName,description,visibility,resourceProvisioningOptions")
               .GetAsync();
```

I noticed that only the id and description of the group is returned. The other properties of the group are returned as null. The AdditionalData property also returns null. The same query works fine in graph explorer
https://graph.microsoft.com/v1.0/groups?$select=id,displayName,description,visibility,resourceProvisioningOptions

This looks like a bug in the client sdk.

**Comment by pschaeflein** [comment]
If you want to see the requests/response that the SDK generates, you can use the Logging handler from the Community library. 

[This sample](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/master/samples/ImmutableIds.cs) shows how to wire it up.

**Comment by MIchaelMainer** [comment]
I can't repro this issue. Are you still seeing this, if so, please reopen.
