### ISSUE TITLE
Provide batch support for curd operation with Microsoft graph API

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/msgraph-sdk-dotnet#558]
**Is your feature request related to a problem? Please describe.**
As JSON batching is already supported in Microsoft graph api it should also supported with Microsoft graph sdk as well. 

**Describe the solution you'd like**
For bulk operation or depending request call batch api will boost performance for CRUD operation.

**Comment by MIchaelMainer** [comment]
This is currently supported. I'm sorry that we don't have documentation support for this yet. Please checkout this Ignite session at minute 27:25, https://myignite.techcommunity.microsoft.com/sessions/82963?source=sessions
