### ISSUE TITLE
how to get today's event?

### ISSUE THREAD

**Issue by lhp620** [microsoftgraph/msgraph-sdk-dotnet#56]

**Comment by MIchaelMainer** [comment]
This is more or less what you want.

                // http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list_calendarview
                var queryOptions = new List<QueryOption>()
                {
                    new QueryOption("startDateTime", DateTime.Today.ToUniversalTime().ToString()),
                    new QueryOption("endDateTime", DateTime.Today.AddDays(1).ToUniversalTime().ToString())
                };


                var todaysEvents = await graphClient.Me.CalendarView.Request(queryOptions).GetAsync();
