### ISSUE TITLE
Ability to retrieve the size of a Message's MIME content

### ISSUE THREAD

**Issue by michael-celani-relativity** [microsoftgraph/msgraph-sdk-dotnet#564]
Currently, there is no way to get the size of a `Message` entity's MIME content before downloading the entire message. 

Some libraries such as [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) need the size of the written stream to function properly, and without being able to find the size I would need to load the entire object into memory to count the number of bytes. I'm currently working in a low memory environment, so emails with large attachments can cause issues. Ideally, the data is directly streamed instead of buffered.

The Graph service endpoint that [gets the MIME content of a Message](https://docs.microsoft.com/en-us/graph/outlook-get-mime-message) is not guaranteed to send a `Content-Length` header depending on the accepted content encodings. Even then, I can't use a `HEAD` request to get the value of that header before downloading because it returns an `HTTP 405` response.

Ideally, there is an endpoint or functionality that would allow me to get the size of the MIME content before it is downloaded.

**Comment by svpsiva** [comment]
Hi Michael,

This capability doesn't exist today and delivering the same is not a trivial task. We can add this to our backlog, but I cannot commit to a timeline at this time. Can you pls create a uservoice request for the same? https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359602 

Thanks
Sivaprakash

**Comment by michael-celani-relativity** [comment]
Hi Sivaprakash,

I've duplicated this issue to a UserVoice request.

https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38884858-create-a-property-containing-the-size-of-an-outloo

Thank you,
Michael

**Comment by MIchaelMainer** [comment]
Thank you @michael-celani-relativity
