### ISSUE TITLE
Improve directoryObject returned by /manager endpoint

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/msgraph-sdk-dotnet#571]
**Is your feature request related to a problem? Please describe.**
When requesting a user's manager (`/me/manager`) a [directoryObject](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0) is returned. The aforementioned docs & entity in the SDK only expose the `id` property.

However, the REST response includes much more data:

![image](https://user-images.githubusercontent.com/2068657/67808195-96819f00-fa6c-11e9-832b-88efbf829284.png)

**Describe the solution you'd like**
Entity in the SDK that represents the REST object returned

**Describe alternatives you've considered**
Using REST to eliminate the need for an additional call.

**Comment by pschaeflein** [comment]
At runtime, using the SDK for .Net, the object returned is a Microsoft.Graph.User object, and the properties that you see in the REST response are populated.

![image](https://user-images.githubusercontent.com/8008013/67859190-f453cc80-fae8-11e9-8dd2-8fc9e7632be1.png)

**Comment by andrewconnell** [comment]
That exact same code, in .NET Core 3, throws an error when you try to access `manager.DisplayName`.

**Comment by darrelmiller** [comment]
The SDK has a [type converter](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs#L63) that will use the OData.Type to determine the correct class to instantiate.  So, even though the Manager property is declared as DirectoryObject, you should be able to cast it to a User if the object is a user.  

Why this fails in .NET core 3 is  a mystery?  We will investigate.

**Comment by pschaeflein** [comment]
Sorry, I missed seeing that you were using .Net Core 3.

**Comment by andrewconnell** [comment]
Following up, this doesn't work (accessing `DisplayName` on the returned object):
![image](https://user-images.githubusercontent.com/2068657/67861406-8d3d1480-faf6-11e9-8a1c-e24cc3a62e9e.png)

But as @darrelmiller says, casting it will work:
![image](https://user-images.githubusercontent.com/2068657/67861435-9d54f400-faf6-11e9-9a99-07eda5d7440e.png)

**Comment by tucane** [comment]
Have the same issue with application owner. Following...

**Comment by MIchaelMainer** [comment]
By design.
