### ISSUE TITLE
RequestBuilder is NOT returning results

### ISSUE THREAD

**Issue by AntLaC** [microsoftgraph/msgraph-sdk-dotnet#573]
Building a request to get list of user membership returns no results in code.

`var groups = await GraphServiceClient.Me.MemberOf.Request().GetAsync().ConfigureAwait(true);`

Using Fiddler to monitor the traffic I see an instant return of the expected values. While stepping through the code with the debugger it hangs once I pass this line (again, even though Fiddler shows a return of the data).

The code is within a try..catch statement and nothing is erroring.

This is in an ASP.NET MVC .NET4.7 web application.

Also, running the query in the Graph API explorer works as expected.

**Comment by MIchaelMainer** [comment]
I'm unable to repro your issue. I'm able to successfully run that code and get the page of results in the `groups` object. You may need to provide more context around this call. If this is still an issue, please provide more information by providing the method that contains this call.
