### ISSUE TITLE
[Client bug]: Getting same group multiple times when using delta query on groups.

### ISSUE THREAD

**Issue by anurag2994** [microsoftgraph/msgraph-sdk-dotnet#574]
**Describe the bug**
I am trying to list groups in my organisation using the Microsft Graph dotnet SDK.
There is a dynamic group which contains around 9993 members. Performing a delta query results in listing of that group multiple times. It is listed 20 times.

**To Reproduce**
Use the below snippet:
```
                var groups = client.Groups.Delta().Request().Select("*").GetAsync().Result;
                List<Group> GroupsList = new List<Group>();
                GroupsList.AddRange(groups);
                while (groups.NextPageRequest != null)
                {
                    groups = groups.NextPageRequest.GetAsync().Result;
                    _GroupsList.AddRange(groups);
                }
```
Have attached logs for clarity.

**Expected behavior**
The group should be listed just once.

**Client version**
Microsoft.Graph -> 1.16.0

**Desktop (please complete the following information):**
 - OS: Windows
[groupdata2.txt](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/3808684/groupdata2.txt)
 
[AB#7307](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7307)

**Comment by XLENTPirre** [comment]
This can happen if the number of members in a group is very large. The following link describe how to handle those instances.

[https://docs.microsoft.com/en-us/graph/delta-query-groups#paging-through-members-in-a-large-group](https://docs.microsoft.com/en-us/graph/delta-query-groups#paging-through-members-in-a-large-group)

**Comment by anurag2994** [comment]
Thanks for the information @XLENTPirre . But that doesnot solve the problem in a scenario where I have a large number of groups (say 1K). The processing of data will take a large amount of time. Is there a better option to do that?

**Comment by XLENTPirre** [comment]
@anurag2994 None that I'm aware of. What kind of times are you getting? What kind of times are you aiming for?

**Comment by MIchaelMainer** [comment]
Is it possible that you are getting multiple instances of the groups because the groups are changing during the delta sync? This doesn't strike me as a client bug as the service is providing multiple instances in the responses.

**Comment by anurag2994** [comment]
@MIchaelMainer The group is not changing during delta sync. It's just that the group has large number of members so I am getting multiple instances of the group. For less number of members it works fine.

**Comment by andrueastman** [comment]
Hey @anurag2994,
The [link](https://docs.microsoft.com/en-us/graph/delta-query-groups#paging-through-members-in-a-large-group) provided earlier should help. 
If the group is very large and cannot fit in one response, the next page will return the same group but with a different list of members. Most likely, the group appearing 20 times is just a large group that was received in 20 different responses/pages.
