### ISSUE TITLE
How to clone a team using SDK?

### ISSUE THREAD

**Issue by spotnick** [microsoftgraph/msgraph-sdk-dotnet#575]
**Is your feature request related to a problem? Please describe.**
I cannot find any proper documentation about how to clone a team. Digging through the models I can find that Team, TeamCloneRequest and TeamCloneRequestBody exists. I can of course manage it with a custom http client but using the Graph SDK would be more suitable for moe.

Also its not possible to the TeamCloneRequestBody to a instance of new Team(); 

**Describe the solution you'd like**
Can you please provide a proper example on how to clone teams with Graph SDK? That would be great.

Thanks,
Tom

**Comment by spotnick** [comment]
Hi again!

Anybody can help?

Thanks a lot!

**Comment by MIchaelMainer** [comment]
Pardon the late reply. Here is how it should work.

`await client.Teams["teamId"].Clone(TeamVisibilityType.Public, ClonableTeamParts.Members, "", "", "", "").Request().PostAsync();`
