### ISSUE TITLE
Get a user by email

### ISSUE THREAD

**Issue by ahmadizm** [microsoftgraph/msgraph-sdk-dotnet#577]
**Is your feature request related to a problem? Please describe.**
Often we want to invite users into an active directory, only to realize that the user is already there under a different UserPrincipalName. To avoid that in Graph api, it would be nice to first check if a user with that email already exists. Currently, a user can only be retrieved with id or userprincipalname.

**Describe the solution you'd like**
Enable developers to get users by their email address. 

**Describe alternatives you've considered**
Currently, need to get all users and check if there is one with matching email.

**Additional context**

**Comment by pschaeflein** [comment]
This capability is available using the $filter parameter:

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var users = await graphClient.Users
	.Request()
	.Filter("mail eq 'DiegoS@M365x214355.onmicrosoft.com'")
	.Select( e => new {
			 e.DisplayName,
			 e.Mail 
			 })
	.GetAsync();
```

If you are trying raw REST (in graph explorer for example), you will need to URLEncode the address.
```
https://graph.microsoft.com/v1.0/users?$select=displayName,mail&$filter=mail eq 'DiegoS%40M365x214355.onmicrosoft.com'
```

**Comment by ahmadizm** [comment]
Thank you, this is great information.
As far as I remember, the filters are case-sensitive in odata. So I guess we should use tolower(mail) and compare it to lower-case email. Is this right? Also, what if multiple emails are linked to the same user principal name? I couldn’t get contains() to work in graph. Thanks for your help.
