### ISSUE TITLE
Application Owners always null

### ISSUE THREAD

**Issue by tucane** [microsoftgraph/msgraph-sdk-dotnet#578]
**Describe the bug**
MSGraph Application endpoints owner attribute is always null

**To Reproduce**
graphServiceClient.Applications.Request(options).GetAsync()
The applications returned have an owner attribute, but it's always null
This is with the expand owners query option

**Expected behavior**
It should return the same result asgraphServiceClient.Applications[id].Owners.Request().GetAsync()

**Desktop (please complete the following information):**
MSGraph Beta client

**Additional context**

**Comment by tucane** [comment]
Actually, this might be for the beta client. https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet
However, doesn't seem like there are anyone doing bug triaging recently ...

**Comment by darrelmiller** [comment]
I tested this with Graph Explorer and this does actually work 

    https://graph.microsoft.com/v1.0/applications?$expand=owners

So, the collection of owners should be present in the model objects.  We will investigate.

**Comment by MIchaelMainer** [comment]
This should work for your purposes:

`var applications = await client.Applications.Request().Expand(a => a.Owners).GetAsync();`

**Comment by tucane** [comment]
Thanks for the help! Closing this one since the expand=owners query works for me now.
