### ISSUE TITLE
Recommended lifetime for a GraphServiceClient instance

### ISSUE THREAD

**Issue by guilmori** [microsoftgraph/msgraph-sdk-dotnet#58]
What is the recommended lifetime for a GraphServiceClient instance ?

Should we create new instances for each usage or re-use the same instance ?

**Comment by shiftylogic** [comment]
The Graph client object is thread-safe and re-entrant. It is a container containing configuration, providers, and helpers for constructing request objects via a builder pattern.

If you are using the client from an web service or any other system where your user context can change from call to call, you will need to create a client instance per user context (i.e. the authentication provider you supply is tied to your user) or an authentication provider supplied to the client needs to be intelligent enough to be able to switch user context and supply / acquire an access token for the appropriate user.

If you are using the client in a stand-alone application running in the context of a single user, you are free to re-use the client or create a new instance on each call. At that point, it is really up to how you want to manage the client instances.

Hope that helps.
