### ISSUE TITLE
Unable to retrieve user's mysite url.

### ISSUE THREAD

**Issue by anurag2994** [microsoftgraph/msgraph-sdk-dotnet#580]
**Describe the bug**
Unable to retrieve user's mysite url using the Graph C# SDK. Select query was used to retrieve the user's mysite.

**To Reproduce**

1.  Used the below code to get user's mysite url:
```
var user = client.Users["{ID}"].Request().Select("mysite").GetAsync().Result;

```
2. Fails with the error
**{Code: -2147467259, Microsoft.SharePoint.SPException
Message: Cannot complete this action.
Please try again.
Inner error
}**

**Expected behavior**
The request should return user's mysite without any failure.

**Desktop:**
 - OS: Windows 
[AB#7309](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7309)

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/83
