### ISSUE TITLE
User.Identities property stored as AdditionalData on the User object

### ISSUE THREAD

**Issue by piquet-h** [microsoftgraph/msgraph-sdk-dotnet#583]
**Describe the bug**
The User object per the REST interface as a collection of objectidentities under the Identities property. This is persisted as AdditionalData keys in the SDK.

**To Reproduce**
Query the /me endpoint using the SDK. The directory principal is in AdditionalData keys, and there is no Identities property on the User object

**Expected behavior**
Identities collection property should exist, matching the REST endpoint, allowing the addition, modification and deletion of identities

**Comment by darrelmiller** [comment]
The Identities property only exists in the Beta API.  We have not yet released the beta API nuget package with updates from Sept and Oct.  Once that release is available, Identities will appear as a native property on the object.
