### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by Zenuka** [microsoftgraph/msgraph-sdk-dotnet#585]
We're using  [Renovate](https://renovatebot.com/) to automatic update some of our nuget packages and it would be great if the releases of the `Microsoft.Graph` nuget package would use [Semantic Versioning](https://semver.org/).

**Comment by darrelmiller** [comment]
@Zenuka Could you clarify what requirements of Semantic Versioning you believe are currently not being met by the released of the Microsoft.Graph package?

**Comment by Zenuka** [comment]
Oh wow, I'm sorry. I had a feeling that this package wasn't using semantic versioning because that the package was at version 1 and that the minor versions are high (20) but that is very valid of course.
