### ISSUE TITLE
[Client bug]: FileAttachement odata type not serialized properly on sendMail

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#586]
**Describe the bug**
The following works
```CSharp
await client.Users["user@contoso.com"].SendMail(new Message
            {
                ToRecipients = new List<Recipient> {  new Recipient
                {
                    EmailAddress = new EmailAddress
                    {
                        Address = "user2@contoso.com"
                    }
                } },
                Subject = "some subject",
                Body = new ItemBody
                {
                    ContentType = BodyType.Html,
                    Content = "some html content"
                },
                Attachments = new MessageAttachmentsCollectionPage
                {
                    new FileAttachment
                    {
                        ODataType = "#Microsoft.OutlookServices.FileAttachment",
                        Name = "logo.png",
                        ContentId = "logo",
                        ContentBytes = Convert.FromBase64String(pngByteArray),
                    }
                }
            }, false).Request().PostAsync()
```
if you remove `ODataType = "#Microsoft.OutlookServices.FileAttachment",` you get an exception saying the the Attachement type doesn't have a "contentid" property.

**Expected behavior**
The FileAttachement class to serialize to the default odata type `#Microsoft.OutlookServices.FileAttachment` without requiring me to add it explicitly.

**Client version**
Microsoft.Graph.Beta 0.8.0-preview

**Desktop (please complete the following information):**
 - OS: windows 10 1903, ubuntu 18.04
 - Browser N/A
 - Version azure functions sdk 1.0.29

**Comment by MIchaelMainer** [comment]
Thank you Vincent. Yeah, this will be fixed in the next generation of beta client.

**Comment by baywet** [comment]
Thanks for the quick answer! Let me know when the fix is out, I should be able to test it fairly quickly.

**Comment by Misiu** [comment]
@MIchaelMainer any updates on the next generation of the beta client? I'm trying to send emails with large attachments. According to [docs ](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=csharp), it is possible, but those methods aren't in the lib. I hope they will be added in next beta.

**Comment by MIchaelMainer** [comment]
This was done: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Models/Generated/FileAttachment.cs#L30


https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/219
