### ISSUE TITLE
[Client bug]: UpdateAsync() on GraphServiceClient.Applications returns null.

### ISSUE THREAD

**Issue by karok2m** [microsoftgraph/msgraph-sdk-dotnet#595]
**Describe the bug**
`UpdateAsync(...)` method for updating application registration always returns `null` instead of updated application. I am using it for either updating KnownClientApplication or RedirectUris, and in both cases returned value is `null`. 

Here are code snippets that I am using:

```csharp
        public async Task<Application> AddAsKnownClientApplicationAsync(
            Application serviceApplication,
            Application clientApplication,
            CancellationToken cancellationToken = default
        ) {
            try {
                var updatedServiceApplication = await _graphServiceClient
                    .Applications[serviceApplication.Id]
                    .Request()
                    .UpdateAsync(
                        new Application {
                            Api = new ApiApplication {
                                KnownClientApplications = new List<Guid> {
                                    new Guid(clientApplication.AppId)
                                }
                            }
                        },
                        cancellationToken
                    );

                return updatedServiceApplication;
            }
            catch (Exception ex) {
                Log.Error(ex, $"Failed to add {clientApplication.DisplayName} as " +
                    $"knownClientApplications for application: {serviceApplication.DisplayName}");
                throw;
            }
        }

        public async Task<Application> UpdateRedirectUrisAsync(
            Application application,
            IEnumerable<string> redirectUris,
            CancellationToken cancellationToken = default
        ) {
            try {
                var updatedApplication = await _graphServiceClient
                    .Applications[application.Id]
                    .Request()
                    .UpdateAsync(
                        new Application {
                            Web = new WebApplication {
                                RedirectUris = redirectUris
                            }
                        },
                        cancellationToken
                    );

                return updatedApplication;
            }
            catch (Exception ex) {
                Log.Error(ex, $"Failed to update RedirectUris of application: {application.DisplayName}");
                throw;
            }
        }
```

**To Reproduce**
Use code snippets above.

**Expected behavior**
`GraphServiceClient.Applications[application.Id].Request().UpdateAsync(...)` should return updated application definition as its documentation states.

**Screenshots**
N/A

**Client version**
`<PackageReference Include="Microsoft.Graph.Beta" Version="0.8.0-preview" />`

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (1909)
 - Browser: N/A
 - Version: **Microsoft.Graph.Beta** NuGet version **0.8.0-preview**. My application is using **.Net Core 3.0**.

**Additional context**
Microsoft Visual Studio Enterprise 2019, version 16.3.10
.Net Core 3.0 
[AB#7305](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7305)

**Comment by MIchaelMainer** [comment]
The generated client request builders incorrectly return an application object when it shouldn't since the documentation states that this API doesn't return a response payload. The returned null is expected in this case.

https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http#response

**Comment by karok2m** [comment]
@MIchaelMainer, thank you for the clarification. I guess, the client library still needs to be fixed. And just to clarify, the documentation that I was referring to was the documentation in the library code itself. It does mention returning updated application, which is incorrect then.

**Comment by MIchaelMainer** [comment]
This is really a generation issue that requires us to have a custom annotation that supports us discovering that this call does not return an object.

**Comment by MIchaelMainer** [comment]
This is resolved in the next major version of the client library where we return a GraphResponse object. You will check the httpstatuscode for `204 No Content` so as to not expect an Application object in the response.

Please try out the next version -- we expect to make it generally available and supported soon. 

This won't be fixed in the current generation pipeline for this library.

**Comment by broomfn** [comment]
I'm experiencing a similare issue with the Users endpoint, i'm guessing this is the same issue, e.g the following seems to return null:

await graphClient.Users[user.Id]
                          .Request()
                          .UpdateAsync(user);

**Comment by robertbravery** [comment]
I'm experiencing a similar thing using the GraphClient SDK

var user = await GetUserById(userId);
            user.AccountEnabled = false;
            var b2cUser = await GraphClient.Users[userId]
                .Request()
                .UpdateAsync(user);
b2cUser is always null.

Document from the Graph SDK
Assembly Microsoft.Graph, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        //
        // Summary:
        //     Updates the specified User using PATCH.
        //
        // Parameters:
        //   userToUpdate:
        //     The User to update.
        //
        //   cancellationToken:
        //     The System.Threading.CancellationToken for the request.
        //
        // Returns:
        //     The updated User.
        //
        // Exceptions:
        //   T:Microsoft.Graph.ClientException:
        //     Thrown when an object returned in a response is used for updating an object in
        //     Microsoft Graph.
        `Task<User> UpdateAsync(User userToUpdate, CancellationToken cancellationToken = default);`

**Comment by mahit777** [comment]
@robertbravery  the issue you are facing is a bit different you are updating the same object that you have received via the get user call, You need to create a new user and update that attribute only. 

According to the docs you only need to pass the attribute to be updated

`In the request body, supply the values for relevant fields that should be updated. Existing properties that are not included in the request body will maintain their previous values or be recalculated based on changes to other property values. For best performance, You shouldn't include existing values that haven't changed.`

you can look at the examples for updating here.
https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http
