### ISSUE TITLE
Planner: PlannerTask.PreviewType has a setter but "This field cannot be modified"

### ISSUE THREAD

**Issue by krisrok** [microsoftgraph/msgraph-sdk-dotnet#596]
**Describe the bug**
PlannerTask.PreviewType has a public setter but we get an ServiceException "This field cannot be modified" when sending the request.

**To Reproduce**
```
var updatedTask = new PlannerTask
{
	Title = "Modified title",
	PreviewType = PlannerPreviewType.NoPreview
};

var updateTaskResult = await graph.Planner.Tasks[addTaskResult.Id].Request().Header("If-Match", addTaskResult.GetEtag())
	.UpdateAsync(updatedTask);
```

**Expected behavior**
If we can set the field, we should be able to sync modifications to it with the service.

**Additional context**
Microsoft.Graph v1.20.0

I doubt this is the only instance of a non-syncable field in the API though. I've only just started using it. Should we still creates issues for findings like this?

Seemingly the correct way is to modify PlannerTask.Details.PreviewType.

**Comment by MIchaelMainer** [comment]
This is an artifact of our code file generation process and OData. We cannot determine whether a property is RW or RO, so we make it all RW. This is OData.
