### ISSUE TITLE
I'm getting an "InternalServerError - Error while processing response" when retrieving tabs from a channel

### ISSUE THREAD

**Issue by POFerro** [microsoftgraph/msgraph-sdk-dotnet#598]
Hi,

When attempting to retrieve the list of tabs from a channel I get the following exception:
Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: InternalServerError
Message: Error while processing response.
Inner error:
	AdditionalData:
	request-id: e9009d16-6116-46d9-abe2-7120e37535a7
	date: 26/11/2019 16:15:35
ClientRequestId: e9009d16-6116-46d9-abe2-7120e37535a7

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.ChannelTabsCollectionRequest.GetAsync(CancellationToken cancellationToken)

The method I'm calling is:
                var tabs = await graph.Teams[team.Id].Channels[channel.Id].Tabs.Request()
                    .Expand(t => t.TeamsApp)
                    .GetAsync();

Can anyone help?
Thanks and best regards
POFerro 
[AB#7262](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7262)

**Comment by mikael-eventful** [comment]
I'm experiencing the same issue (both using the .NET SDK and the graph explorer) after I've added a tab using the .NET SDK (application authentication if it matters).

If I add the tab using the Graph Explorer or the team GUI everything works correctly (I can list tabs using both the .NET SDK and Graph Explorer).

Here is how I added the tab with the .NET SDK (link was a fully functional https url)
```
Microsoft.Graph.TeamsTab teamsTab = new Microsoft.Graph.TeamsTab()
{
    DisplayName = "TabTest",
    AdditionalData = new Dictionary<string, object>()
    {
         {"teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web"}
    },
    Configuration = new TeamsTabConfiguration() {
        ContentUrl = "{fully functional https url}",
        WebsiteUrl = "{fully functional https url}"
    }
};
await _client.Teams[team.Id].Channels[generalChannelId].Tabs.Request().AddAsync(teamsTab);
```

And through the graph explorer:
```
POST https://graph.microsoft.com/v1.0/teams/{teamId}/channels/{channelId}/tabs
{
  "displayName": "TabTest",
  "teamsApp@odata.bind": 'https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web',
  "configuration": {
    "contentUrl": "{fully functional https url}",
    "websiteUrl": "{fully functional https url}"
  }
}
```

The tab exists and is working inside the teams client in both scenarios.

**Comment by mikael-eventful** [comment]
I "solved" my issue. Graph couldn't handle sending the "@odata.type" on the configuration object. So I had to unset it before posting the channel, like this:

```
Microsoft.Graph.TeamsTab teamsTab = new Microsoft.Graph.TeamsTab()
{
    DisplayName = "TabTest",
    AdditionalData = new Dictionary<string, object>()
    {
         {"teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web"}
    },
    Configuration = new TeamsTabConfiguration() {
        ContentUrl = "{fully functional https url}",
        WebsiteUrl = "{fully functional https url}"
    }
};
teamsTab.Configuration.ODataType = null;
await _client.Teams[team.Id].Channels[generalChannelId].Tabs.Request().AddAsync(teamsTab);
```

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/993 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
