### ISSUE TITLE
Error (memory overflow) downloading a file big enough

### ISSUE THREAD

**Issue by horacioj** [microsoftgraph/msgraph-sdk-dotnet#60]
Debugging the code, I see the [Download Contents](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_downloadcontent) API method is processed by accessing the DriveItem's download url (@microsoft.graph.downloadUrl property), and redirecting the request to it.

All starts in 

    baserequest.cs =>public async Task<Stream> SendStreamRequestAsync() 

which does the "GET /drives/items/{item-id}/content". 

This goes to 

    baserequest.cs => public async Task<HttpResponseMessage> SendRequestAsync() 

and then to 

    httpprovider.cs => public async Task<HttpResponseMessage> SendAsync()

to finally do

    httpprovider.cs => internal async Task<HttpResponseMessage> HandleRedirect()

which crashes when doing the

    var response = await this.SendRequestAsync(redirectRequest, completionOption, cancellationToken);

for the the DriveItem's download url. This is, a request like

    https://mycompany.sharepoint.com/personal/mycompany_onmicrosoft_com/_layouts/15/download.aspx?guestaccesstoken=....&docid=...&expiration=...&userid=6&authurl=True&NeverAuth=True

The crash stack trace is:

```
   at System.IO.MemoryStream..ctor(Int32 capacity)
   at System.Net.Http.HttpContent.LimitMemoryStream..ctor(Int32 maxSize, Int32 capacity)
   at System.Net.Http.HttpContent.CreateMemoryStream(Int64 maxBufferSize, Exception& error)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize)
   at System.Net.Http.HttpClient.StartContentBuffering(HttpRequestMessage request, CancellationTokenSource cancellationTokenSource, TaskCompletionSource`1 tcs, HttpResponseMessage response)
   at System.Net.Http.HttpClient.<>c__DisplayClass55_0.<SendAsync>b__0(Task`1 task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Evotiva.Microsoft.Graph.HttpProvider.<SendRequestAsync>d__21.MoveNext() in \Requests\HttpProvider.cs:line 262
```

I think the problem happens because the the code is trying to load the file's full contents into a MemoryStream, instead of doing a streamed download (returning the file stream in chunks, instead of all at once).

EDIT: 

This could be solved using the API's [Partial range downloads](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_downloadcontent) via the Range header.

Is it possible in the current SDK to specify the Range header and perform a streamed download?

**Comment by MIchaelMainer** [comment]
Yes, you can use the current SDK to specify the Range header. The only issue here is that setting the Range header is only possible with the constructor. We need to update Option.cs to support updating the Range value. Here's some code and pseudo code of what you'll have to do to make it work as of now:

```
long startByteRange = 0;
long endByteRange = 1023;
var byteRangeChunkSize = 1024;
var rangeHeaderValue = $"bytes={startByteRange}-{endByteRange}"; 

var rangeHeader = new HeaderOption("Range", rangeHeaderValue);

List<HeaderOption> headers = new List<HeaderOption>() {
    rangeHeader
};

// Check that the endByteRange is not greater than item.Size
// Do a loop around this call and increment the Range header with the next byte range.
var partialStream = await graphClient.Me.Drive.Items[item.Id].Content.Request(headers).GetAsync();
// Call a function to concatenate this partial stream.
// Check whether the next call will download the end of the stream. 
// Update the byte range for the next download chunk and call the above call again.
// As the SDK is now, you'll have to remove the current HeaderOption object, and add
//   a new one with the updated byte range as the setter is currently private.
//   we may need to make the header setter public to better support this scenario.
```

**Comment by horacioj** [comment]
>I think the best course is to use the @microsoft.graph.downloadUrl property and create the web requests that will download the partial streams. 

What if it expires before the download is completed?
Because 

>Pre-authenticated download URLs are only valid for a short period of time (a few minutes) [[ref](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_downloadcontent).]

And for a big file, and depending on the network speed, the download could take more than a few minutes.

What do you think?

**Comment by shiftylogic** [comment]
@horacioj One you have submitted the HTTP request and are consuming the response stream, the URL no longer matters and that call should continue to completion. If a URL expires before you ask for the next range though, you will likely need to acquire a new URL and then just start at the range values you left off on.

Is this issue resolved for you now?

**Comment by horacioj** [comment]
Using the code posed in my "EDIT", it seems to work fine. I'm not using the range approach,
Thanks
