### ISSUE TITLE
Client library using wrong endpoint? for users/delta causing duplicates results

### ISSUE THREAD

**Issue by martinstenhoff** [microsoftgraph/msgraph-sdk-dotnet#600]
IGraphServiceClient.Users.Delta().Request() seems to be using the following graph endpoint:
* https://graph.microsoft.com/v1.0/users/microsoft.graph.delta
This endpoint seems to be behaving differently to the one listed in the documentation:
* https://graph.microsoft.com/v1.0/users/delta

I noticed that I was receiving duplicate user objects when paging through the delta endpoint on the users resource where the code I'm using is more or less as follows:
```
public async Task<IList<User>> GetDeltaUsers(IGraphServiceClient graphServiceClient)
{
	var list = new List<User>();
	IUserDeltaCollectionPage page = null;
	do
	{
		if (page is null)
		{
			page = await graphServiceClient.Users.Delta().Request().GetAsync().ConfigureAwait(false);
		}
		else
		{
			page = await page.NextPageRequest.GetAsync().ConfigureAwait(false);
		}
		
		list.AddRange(page.CurrentPage);
		var duplicates = list.GroupBy(u => u.UserPrincipalName).Where(g => g.Count() > 1).Count();
		$"Retrieved {page.CurrentPage.Count()} users ({duplicates} duplicates)".Dump();
	}
	while (page.NextPageRequest != null);
	
	return list;
}
```
Running the above code in our dev tenant will produce the following output:
```
Retrieved 200 users (0 duplicates)
Retrieved 200 users (0 duplicates)
Retrieved 158 users (158 duplicates)
```

This is not an issue in the client library as I can reproduce this using the Microsoft Graph Explorer:
* https://developer.microsoft.com/en-us/graph/graph-explorer/preview

With graph explorer I get the expected result if I use _/v1.0/users/delta_, but the same duplicate result as in the dotnet sdk if I enter _/v1.0/users/microsoft.graph.delta_.

Question is why is the dotnet sdk using /users/microsoft.graph.delta instead of /users/delta (the sdk seems to be using /microsoft.graph.delta instead of /delta for all supported resources)?

The 3 request ids corresponding to the above requests are
```
36c61aae-741b-4d87-b6fd-e8db67ab6c58
ec2458f5-8cfe-47ec-92c3-488a10af9ead
cb894ca5-46df-4903-ae4e-5fa45df90641
```

**Comment by MIchaelMainer** [comment]
@martinstenhoff The .NET SDK generates the fully-qualified name of OData actions in case we ever add another namespace in addition to the default microsoft.graph namespace. This is a service issue.

**Comment by darrelmiller** [comment]
@dkershaw10  Do you have any history on why there is different behavior on the fully qualified delta function versus the non qualified one?

**Comment by ddyett** [comment]
closing as no action. tagged for service question.
