### ISSUE TITLE
Do you plan to use the pipeline from Azure.Core?

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#602]
**Is your feature request related to a problem? Please describe.**
I meant to ask earlier, but https://www.youtube.com/watch?v=0tKXe1wOqI8 reminded me - this pipeline is super-useful. Do you plan to also use it?

**Describe the solution you'd like**
Build on top of the pipeline in Azure.Core

**Comment by darrelmiller** [comment]
No, we will not be using the pipeline from Azure Core as it is a duplicate of the DelegatingHandler pipeline that is native in HttpClient that we already use.
