### ISSUE TITLE
Problem with sending Graph Message with couple of file attachments

### ISSUE THREAD

**Issue by biniu-shockit** [microsoftgraph/msgraph-sdk-dotnet#603]
I have prepared a function C# in Visual Studio to sending emails using draft messages and file attachments.

var draft = _client.Users[_graphUser].MailFolders.Drafts.Messages.Request().WithImmutableId().WithMaxRetry(10).AddAsync(message).GetAwaiter().GetResult();
_client.Users[_graphUser].Messages[draft.Id].Send().Request().WithImmutableId().WithMaxRetry(10).PostAsync().GetAwaiter().GetResult();

There are two ways of attaching files to Graph Message:
- create email with MessageAttachmentsCollectionPage (sum of sizes of all files should be less than 4 MB, in other way is error);
- using Graph Beta SDK- I can create draft of Message and upload files by createUploadSession (each file should by bigger than 3MB, in other way is error).

I want to send Message with 5 files (o.e. PFD's) and size each of them is 1 MB.
I can’t use both of methods to send 5 files in single Graph Message.

Is there other way to send email without divide message to couple messages or using archives (o.e. ZIP)?

**Comment by Zombaya** [comment]
You should be able to add multiple attachments using [Add attachment](https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0&tabs=http).

At least, using PHP this works.  I don't know about the dotnet-sdk, but the API does support it.

**Comment by biniu-shockit** [comment]
Thank you for your answer. I was checked this out- there is function added to Beta Graph Library and its working fine.
`var uploadedAttachemnt = await BetaGraphClient
                     .Value
                     .Users[user]
                     .Messages[message.Id]
                     .Attachments
                     .Request()
                     .AddAsync(attachment);`
