### ISSUE TITLE
Issues with AccessReview and ProgramControl

### ISSUE THREAD

**Issue by chadcarlton** [microsoftgraph/msgraph-sdk-dotnet#607]
Receiving errors using the Client SDK and AccessReview and Program Control.

**To Reproduce**
Use the SDK to Create a new Access Review;
Receive errors:
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
 ("Message: The request is invalid.
	Inner error:
		Message: accessReview : An error has occurred.
		AdditionalData:
			request-id: f62fcafa-562f-41ac-bd22-8769e55df16b
			date: 12/9/2019 5:58:22 PM
		ClientRequestId: f62fcafa-562f-41ac-bd22-8769e55df16b
 ")
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
 ("Message: The request is invalid.
	Inner error:
		Message: accessReview : An error has occurred.
		AdditionalData:
			request-id: f62fcafa-562f-41ac-bd22-8769e55df16b
			date: 12/9/2019 5:58:22 PM
		ClientRequestId: f62fcafa-562f-41ac-bd22-8769e55df16b
 ") 

For Program Control:
Error involving Null Control  (sorry I dont have a error message)

**In both cases making direct rest Calls to graph, succeeds**.

**Expected behavior**
Access Review created
Program Control created.

**Client version**
Microsoft.Graph.Beta v0.9.0
Microsoft.Graph.Beta v0.10.0

**Comment by MIchaelMainer** [comment]
Thank you for the issue. 

Can you share with us the call you made with the SDK? 
Can you capture the request and response with a tool like Fiddler and share with us what goes over the wire?
