### ISSUE TITLE
ResponseHeaders is returned from properties serialized requests

### ISSUE THREAD

**Issue by andrew-vdb** [microsoftgraph/msgraph-sdk-dotnet#615]
24-04-2018
Response Header added to the serialized requests
https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/260

09-04-2019
Response Header is removed from serialized requests (which is good)
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/426

Now its back again in version 1.17.0

Can we remove response headers for good?
 
[AB#7266](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7266)

**Comment by darrelmiller** [comment]
If you check #426 I don't think we actually removed them.  That was the plan, but it would have been a breaking change for folks who are actually reading the headers.  So we just added a check that throws if you try and send them.

We need to introduce a major version change to make this change and we currently don't have a way to generate multiple major versions of our service library.

What is the problem that the headers are causing you?  Maybe we can find another solution.

**Comment by andrew-vdb** [comment]
Strange, because for a year I don't expect the responseHeaders being returned at all

```
await graphClient.Sites[siteId].Lists[listId].Items[itemId].Fields.Request(Options(accessToken)).GetAsync()

should return FieldValueSet like this

{
    "Name": "Widget",
    "Color": "Blue",
    "Quantity": 2357
}

but what I get
{
    "Name": "Widget",
    "Color": "Blue",
    "Quantity": 2357,
   "responseHeaders:"xxxxx",
   "statusCode:"OK"
}

```

maybe an option when we build the request to not return the responseHeaders?

**Comment by andrueastman** [comment]
Closing this as this is resolved through the GraphResponse work. More information can be found in [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graph-response)
