### ISSUE TITLE
Add Application permission to support AppCatalog.ReadWrite.All

### ISSUE THREAD

**Issue by lxf310** [microsoftgraph/msgraph-sdk-dotnet#616]
**Problem & Requirement**
According to https://docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-beta, only delegated permission is supported to manipulate Teams AppCatalog which means a sign-in user is needed when taking use of those APIs. However, the Application permission can provide the ability to make related actions more automatically and support more meaningful and realistic use-cases.

For example, my use-case is to provided an application to automatically install a new Bot, created in Azure, to Teams. So I really think the Application permission is needed. 
[AB#7267](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7267)

**Comment by MIchaelMainer** [comment]
Please submit this feature request at https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests. After you post the feature request, please add a link in this issue so that other folks can find your feature request.

**Comment by lxf310** [comment]
Hi,
I raised a feature request on https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39290491-add-application-permission-to-support-appcatalog-r. 
Thanks.

**Comment by andrueastman** [comment]
Closing this for now. This feature request is tracked via https://docs.microsoft.com/en-us/answers/questions/401577/add-application-permission-to-support-appcatalogre.html as uservoice is no longer active.

**Comment by andrueastman** [comment]
Feature Request submitted at https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-application-permission-to-support-appcatalog-readwrite-all/idi-p/2371635#M89
