### ISSUE TITLE
Add Application permission to support Presence.Read, Presence.Read.All

### ISSUE THREAD

**Issue by mindncz** [microsoftgraph/msgraph-sdk-dotnet#617]
Graph Beta API already supports Delegated (work or school account) permission for Presence.Read, Presence.Read.All. However, we need to get people's presence on behalf of an application instead of a signed-in user. 

Could Graph supports "Application permission to support Presence.Read, Presence.Read.All"?

I saw there is similar voice raised https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39219637-application-permission-for-presence

**Comment by mindncz** [comment]
Hi Team,
Is there any plan to support this feature?

**Comment by MIchaelMainer** [comment]
Anyone finding this issue who wants this feature, please go vote for this feature on the Microsoft Graph User Voice.

**Comment by bradbamford** [comment]
Now that the Microsoft Graph UserVoice site is gone, where do we keep track of this request ?

**Comment by andrueastman** [comment]
Hey @bradbamford,
You can now submit new idea requests at this link

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

For this specific issue, I believed it is tracked via

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/graph-api-presence-should-support-application-permissions/idi-p/2276109
