### ISSUE TITLE
Retrieving Single Value Extended Properties

### ISSUE THREAD

**Issue by rbaryolo** [microsoftgraph/msgraph-sdk-dotnet#618]
I am trying to get events that have a string-typed single-value extended property specifying a filter like I see in the documentation ([Get event by extended property filter](https://docs.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-get?view=graph-rest-1.0&tabs=http#request-2))

Mi request looks like the following, replacing {id|userPrincipalName} by the correct value:
https://graph.microsoft.com/v1.0/users/{id|userPrincipalName}/events?$filter=singleValueExtendedProperties%2FAny(ep%3A%20ep%2Fid%20eq%20'String%20{66f5a359-4659-4830-9070-00047ec6ac6e}%20Name%20Fun'%20and%20ep%2Fvalue%20eq%20'Food')

I created the event using this example from the documentation ([Create event with Single Value Extended Property](https://docs.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties?view=graph-rest-1.0#request-1))

I was expecting my get request to return the event obeying the filter specified, but instead it is returning an empty set of events, here the response, replacing {id|userPrincipalName} by the correct value:

`{
    "@odata.context": https://graph.microsoft.com/v1.0/$metadata#users('{id|userPrincipalName}')/events",
    "value": []
}`

**Comment by peombwa** [comment]
@rbaryolo, questions like this should be posted on StackOverflow with the microsoft-graph tag. This repo is only for questions relating to the Microsoft Graph DotNet client.

To answer your question, the signleValueExtendedProperties  `id` value in your filter is different from the one the event was created with as per the documentation ([Create event with Single Value Extended Property](https://docs.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties?view=graph-rest-1.0#request-1)). The expected id should be: 

> 66f5a359-4659-4830-9070-000**40**ec6ac6e

 yet what you are using is: 

> 66f5a359-4659-4830-9070-000**47**ec6ac6e

The complete filter should be `https://graph.microsoft.com/v1.0/me/events?$filter=singleValueExtendedProperties/Any(ep: ep/id eq 'String {66f5a359-4659-4830-9070-00040ec6ac6e} Name Fun' and ep/value eq 'Food')`

**Comment by rbaryolo** [comment]
Thank you very much @peombwa, I am sorry for asking here.
