### ISSUE TITLE
[Bug] Role IDs aren't resolvable by Group[id] 

### ISSUE THREAD

**Issue by hausec** [microsoftgraph/msgraph-sdk-dotnet#619]
**Describe the bug**
According to the documentation here:
https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=csharp
If I wanted to gather the members that belong to a role, the following should work:
```
var groups = await graphClient.Groups.Request().GetAsync();
                    foreach (var group in groups)
                    {
                    Console.WriteLine("Group Name - " + group.DisplayName);
                    Console.WriteLine("Users: ");
                    var users = await graphClient.Groups[group.Id].Members.Request().GetAsync();
                                foreach (var user in users)
                                {
                                    var currentUser = await graphClient.Users[user.Id].Request().GetAsync();
                                    Console.WriteLine(currentUser.UserPrincipalName);
                                }}
```

**Expected behavior**
This code works when group IDs are passed in, however it errors when a Role ID is passed in.

**Screenshots**
https://imgur.com/lnn1KOY

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by MIchaelMainer** [comment]
You should query the directoryRoles instead of groups. Our generated snippet is incorrect. The correct snippet should look something like this (I havent tried it yet.:

```csharp
var dirRoles = await client.DirectoryRoles.Request().GetAsync();
//Foreach directory role
var dirRoleMembership = await client.DirectoryRoles[dirRoles[0].Id].Members.Request().GetAsync();

```

**Comment by andrueastman** [comment]
Sample resolved via this PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/6990
