### ISSUE TITLE
Change for CreateAsync ( Fixing a bug in base entity create operations), cause it to fail

### ISSUE THREAD

**Issue by ronilse** [microsoftgraph/msgraph-sdk-dotnet#62]
After the change from PUT to POST it fails on CreateAsync, according to [Items in the OneDrive SDK for C#](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/items.md#create-a-folder) it is POST on AddAsync and PUT on CreateAsync

**Comment by shiftylogic** [comment]
The documentation you link to is for the OneDrive library. In the Microsoft Graph library, scenario #2 and #3 can be achieved slightly different. The Microsoft Graph REST documentation states that [creating a folder](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_post_children) is done by POST to the children collection of the containing folder. Thus, they should be ...ItemWithPath("folder").Children.Request().AddAsync(folderToCreate);

Hope that helps.
