### ISSUE TITLE
Question: expand thumbnails along getting DriveItems

### ISSUE THREAD

**Issue by sven5** [microsoftgraph/msgraph-sdk-dotnet#620]
Hi,

the doc says that expanding thumbnails together with getting driveitems is currently not supported in OneDrive for Business. 
Source: https://docs.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-1.0&tabs=http#remarks

However, I do think that it's possible.

I tried through MS graph explorer the following query against my business OneDrive
using a question mark for parameters (**?** )
**GET https://graph.microsoft.com/v1.0/me/drive/root:/{someFolder}:/children?expand=thumbnails**
the returning json data contains thumbnail information.
But when using a dollar sign ($) for the parameter separator an error is thrown:
**GET https://graph.microsoft.com/v1.0/me/drive/root:/{someFolder}:/children$expand=thumbnails**
returns InvalidClientQueryException.

The DriveItemRequest class uses **$ instead of ?** for creating the query parameter:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/bba9ef86750678844bb8364517904d89f098ff72/src/Microsoft.Graph/Requests/Generated/DriveItemRequest.cs#L136

Now I wonder what's going on here. Is this a hidden feature currently not supported? I would like to see that the SDK can fetch the thumbnails.

**Comment by MIchaelMainer** [comment]
Thank you for sharing this with us. This is a bug. The first time a query option is added, we need to emit a '?'. I'm surprised that this is being discovered now. 

We should be emitting https://graph.microsoft.com/v1.0/me/drive/root:/{someFolder}:/children?$expand=thumbnails

**Comment by andrueastman** [comment]
The core library already ensures the first '?' character is inserted in place and any other succeeding query options appended with a '&' character before them. (See [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/77e0bab1ab5355ef35ec2b4116a3c77a4247100b/src/Microsoft.Graph.Core/Requests/BaseRequest.cs#L338).)
Furthermore, appending the '$' before the 'expand' is optional as of services running Odata 4.01 and above. (See [here](https://docs.microsoft.com/en-us/odata/concepts/queryoptions-overview#system-query-options). )

Working queries should therefore either be 
GET https://graph.microsoft.com/v1.0/me/drive/root/children?expand=thumbnails
or
GET https://graph.microsoft.com/v1.0/me/drive/root/children?$expand=thumbnails

The latter query can be successfully be achieved with the SDK by the following example.

```cs
var children = await graphServiceClient.Me.Drive.Root.Children.Request().Expand("thumbnails").GetAsync();
//access items of children driveitems
foreach (var item in children.CurrentPage)
{
    Console.WriteLine(item.Thumbnails.Count);//Access inner thumbnail property
}
```

I do not think this is a client bug. 
@sven5 Possibly this is a misunderstanding with the optional '$' character?

cc @darrelmiller @MIchaelMainer

**Comment by sven5** [comment]
Hi @andrueastman 

thanks for your post. I agree - you're right, this was a misunderstanding. 
I already changed my query to the one you suggested and it works now. 
Sometimes it's a little tricky to get the correct property chain for the API query. :sweat_smile:

**Comment by andrueastman** [comment]
No worries 😄 

Marking this as closed for now.
