### ISSUE TITLE
[Client bug]: client sdk issues delta requests to /microsoft.graph.delta and not /delta

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-dotnet#622]
**Describe the bug**
The sdk seems to be sending delta requests to /microsoft.graph.delta and not /delta.
Context:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/6609
https://github.com/microsoftgraph/microsoft-graph-docs/issues/6907#issuecomment-578879364

**To Reproduce**
https://gist.github.com/chenmach/6d7a78210ee33a40a456280577ccd39e

**Expected behavior**
requests to be sent to /delta

**Client version**
latest v1

**Comment by MIchaelMainer** [comment]
This is expected client behavior. OData endpoints are supposed to support fully qualified function names so we can support functions of the same name but in different namespaces, i.e. microsoft.graph.delta and microsoft.graph2.delta. 

Services that don't support fully qualified names should consider this a bug.

**Comment by baywet** [comment]
thanks for the quick answer!
The only drawback I can see is that if users compare what the SDK is sending with what's in the docs they'll see a difference.

**Comment by MIchaelMainer** [comment]
Yeah, I agree that will cause issues. We should consider adding doc validation to enforce the use of FQN for functions and actions in the docs.

**Comment by baywet** [comment]
thanks! closing this one

**Comment by baywet** [comment]
FYI https://github.com/microsoftgraph/microsoft-graph-docs/pull/6958
