### ISSUE TITLE
Injection Attack Prevention - Parameterisation / Escaping Helpers for Query Options 

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/msgraph-sdk-dotnet#626]
Many graph APIs take query options that may contain user input - eg. "$filter" - but the client library doesn't provide anything to help ensure this is safe against injection attacks. If a user enters a single quote suddenly queries will fail or worse. 

There are several possible improvements:
* Bare minimum: Add an escaping function and use it consistently in all the samples - [from the docs](https://docs.microsoft.com/en-us/graph/query-parameters#escaping-single-quotes) it appears that this would just need to be `string.Replace(param, "'", "''")`, but it would be great to confirm this.
* Better: Some sort of parameterisation method. This could be using `FormattableString`/custom string interpolation, but [that's pretty tricky](https://github.com/dotnet/efcore/issues/10996).
* Best: something like #166, to remove all temptation of building strings manually.

Thanks =)

**Comment by peombwa** [comment]
The service handles injection attacks. The client is just a pass through to the HttpClient that sends requests to the REST service.

**Comment by fowl2** [comment]
@peombwa could you elaborate slight on how the service handles this? I understand client is just a pass through that's why it's dangerous. You could say that `SqlClient` is "just a pass through" too - where SQL injection is definitely a thing - which is why the industry has spent decades trying to get people to parameterise their SQL!.

For an example of how the current behaviour very easily leads to the most obvious straightforward code being wrong.

Here's a slightly contrived example - imagine an app that shows some data from your direct reports and accepts a department filter as user input. 

The user enters `IT` and app concatenates or formats the request like this:

`.Where($"manager eq '{currentUser.UserName}' and department eq '{formData.DepartmentFilter}'")`

`/users?$filter=manager eq 'The.User' and department eq 'IT'`

But what if the user/attacker enters `IT' or manager eq 'CEO` as the "department"?

`/users?$filter=manager eq 'The.User' and department eq 'IT' or manager eq 'The.Board'`

And suddenly sees more than they should!

Yes this is a bug in the app, but the client doesn't promote a 'pit of success' or at least provide the tools to use it safely.
