### ISSUE TITLE
Upgrading from 1.20.0 to 1.21.0

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#631]
Are there any code breaking changes upgrading my Nuget package for Microsoft Graph from 1.20.0 to 1.21.0?

![Graph](https://user-images.githubusercontent.com/7985331/74381400-4217ea80-4de3-11ea-9267-3bc0ecb8cf8c.png)
 
[AB#7272](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7272)

**Comment by peombwa** [comment]
We don't expect breaking changes, however if you run into issues with teams calls, please let us know.

**Comment by WhitWaldo** [comment]
Is there any documentation explaining what changed between version 1.21.0 and the jump to 3.0.1, much less to 3.2.0 since then?

**Comment by MIchaelMainer** [comment]
The breaking changes between 1.21 and 3.0.1 are described here:
https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-net-sdk-updates/

The diff can be reviewed here:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/3.0.1...3.2.0

**Comment by WhitWaldo** [comment]
@MIchaelMainer Thank you very much! 

Might I suggest though that the project README be updated to include that blog link under the Documentation and Resources header, as that should absolutely have more visibility.

**Comment by andrueastman** [comment]
Closing this as it is resolved via #665
