### ISSUE TITLE
[Bug] Token not being passed to GraphServiceClient

### ISSUE THREAD

**Issue by isaacrlevin** [microsoftgraph/msgraph-sdk-dotnet#633]
**Which Version of MSAL are you using ?**
4.8.2

**Which Version of Graph SDK are you using ?**
Microsoft.Graph.Beta 0.11.0-preview

**Platform**
net472 WPF

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X] Interactive
    * [ ] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Is this a new or existing app?**
This is a new app or experiment

**Repro**

```csharp
// Provider I created to get interactive token
        public async Task AuthenticateRequestAsync(HttpRequestMessage request)
        {
            AuthenticationResult authResult = null;
            var accounts = await _application.GetAccountsAsync();
            var firstAccount = accounts.FirstOrDefault();

            try
            {
                authResult = await _application.AcquireTokenSilent(_scopes, accounts.FirstOrDefault())
                .ExecuteAsync();
            }
            catch (MsalUiRequiredException ex)
            {
                    authResult = await _application.AcquireTokenInteractive(_scopes)
                       .WithParentActivityOrWindow(new WindowInteropHelper(Application.Current.MainWindow).Handle)
                       .ExecuteAsync();               
            }
            if (authResult != null)
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("bearer", _authToken);
            }
        }
}

// code that calls the Presence Graph API
var graphResult = await _graphServiceClient.Me.Presence.Request().GetAsync();
```

**Expected behavior**
I would expect the token obtained by the provider to be attached to any GraphServiceClient call and I get presence status

**Actual behavior**
 I get a 401 when calling the Presence API because there is no token in the header

**Possible Solution**
I can call the Presence Api via a Token added HttpClient (samples do this) but the fact I am able to do my preferred approach with other providers (DeviceCodeFlow for instance) makes me think this should be supported behavior

**Additional context/ Logs / Screenshots**
Here is a repo with code that has a working DeviceCodeFlow working as expected
https://github.com/isaacrlevin/PresenceLight/blob/master/src/PresenceLight.Core/Graph/DeviceCodeFlowAuthorizationProvider.cs

**Comment by darrelmiller** [comment]
Hey @isaacrlevin  Can you show how you create the GraphServiceClient?

Is AuthenticateRequestAsync getting called?

**Comment by isaacrlevin** [comment]
I do it very similar to this, except I pass the name provider I created

https://github.com/isaacrlevin/PresenceLight/blob/master/src/PresenceLight.Core/Graph/GraphService.cs

**Comment by darrelmiller** [comment]
@isaacrlevin  If your setup is similar and the DeviceCodeFlowProvider does work, then they only thing I can think is that the call to get the token in the AuthenticateRequestAsync is not getting a token.

**Comment by isaacrlevin** [comment]
I add it to the request object like


request.Headers.Authorization = new AuthenticationHeaderValue("bearer", _authToken); 

I am able to get a token and add it to header, but the subsequent call with the Graph SDK does not have it.

**Comment by isaacrlevin** [comment]
I resolved this myself, got stuck in async hell
