### ISSUE TITLE
Outlook To-do (Tasks) question

### ISSUE THREAD

**Issue by nikolaytashev** [microsoftgraph/msgraph-sdk-dotnet#635]
Currently Outlook Tasks are not available in the release version of Microsoft Graph sdk, Is there an expected release date or roughly when it is going to be available?

**Comment by MIchaelMainer** [comment]
This is only available with the beta endpoint. See here: https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Models/Generated/OutlookTask.cs.

https://www.nuget.org/packages/Microsoft.Graph.Beta

I don't know when this will be released to v1.0.
