### ISSUE TITLE
Deadlock in async code 

### ISSUE THREAD

**Issue by horacioj** [microsoftgraph/msgraph-sdk-dotnet#64]
Similar to [issue 52](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/52), I found other deadlock conditions, solved (I hope so) by adding ".ConfigureAwait(false)" to all "**await**" calls in:

- Requests\HttpProvider.cs => 7 edits
- Requests\UploadChunkRequest.cs => 1 edit
- Requests\Helpers\ChunkedUploadProvider.cs => 4 edits

**Comment by adamsipos** [comment]
+1 for the bugreport. I'm looking into using the OneDrive API from a UI context, and deadlocks pop up all the time, I traced more than one of them back to HttpProvider.

**Comment by cbales** [comment]
Resolved in commit #70
