### ISSUE TITLE
Can't figure out how to use the beta devices/{id}/commands request

### ISSUE THREAD

**Issue by jevansaks** [microsoftgraph/msgraph-sdk-dotnet#643]
**Describe the bug**
I'm trying to use the Project Rome device relay APIs through the graph. I can get the list of devices through `Me.Devices` but I can't figure out how to invoke the commands correctly. The nearest I could figure was:

```c#
 graphClient.Me.Devices[deviceId].Commands.Request().GetAsync()
```

But this seems to produce a URI like:
`https://cdpcs.microsoft.com/odata/users('<my email>')/devices('<my device id>')/commands`

Which is not the correct graph API.

It's possible that using the indexer on the Devices object isn't right but there's no other documentation on this so I'm fumbling around in the dark. Any help would be appreciated.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jevansaks** [comment]
Interestingly, I see that the request that got built seems correct. The full error is:

```
Message: No HTTP resource was found that matches the request URI 'https://cdpcs.microsoft.com/odata/users('<my email>')/devices('<my device id>')/commands
```

I *think* this might be because the request needs to be sent as POST. If I run the URL (`https://graph.microsoft.com:443/beta/me/devices/<id>/commands`) through the Graph Explorer with POST then it works.

Maybe my question is -- how do I do a "POST" query with the graph SDK?

**Comment by pschaeflein** [comment]
Typically, you use the PostAsync() method instead of GetAsync().

**Comment by MIchaelMainer** [comment]
@jevansaks Can you provide a link to the documentation that you are using?

**Comment by jevansaks** [comment]
I haven't been able to find any documentation that says how to use the Graph .NET SDK to do this. The REST API I'm trying to call from the Graph is: https://docs.microsoft.com/en-us/graph/api/send-device-command?view=graph-rest-beta

**Comment by jevansaks** [comment]
> Typically, you use the PostAsync() method instead of GetAsync().

I agree and that would be awesome... but I don't see such a method in the Graph .NET SDK anywhere.

**Comment by jevansaks** [comment]
FWIW I did fumble my way through to creating a Post call with a json body but it is not pretty. I'd love any suggestions for how to simplify it:

```c#
            var request = new Dictionary<string,object>
            {
                {  "type",  "LaunchURI" },
                { "payload", new Dictionary<string, object>
                    {
                        { "uri", "https://bing.com" }
                    }
                }
            };

            var body = graphClient.HttpProvider.Serializer.SerializeObject(request);

            var message = graphClient.Me.Devices[deviceId].Commands.Request().GetHttpRequestMessage();
            message.Method = HttpMethod.Post;
            message.Content = new StringContent(body, Encoding.UTF8, "application/json");
            await graphClient.AuthenticationProvider.AuthenticateRequestAsync(message);
            var response = await graphClient.HttpProvider.SendAsync(message);

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var command = graphClient.HttpProvider.Serializer.DeserializeObject<Command>(content);
                return command;
            }
```

**Comment by MIchaelMainer** [comment]
I assume that you are using Microsoft.Graph.Beta instead of Microsoft.Graph. It would be better to put questions about it in https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet.

Does the following work for you:

```csharp
var command = new Command(); // TODO: set properties
graphClient.Me.Devices[deviceId].Commands.Request().AddAsync(command);
```

**Comment by jevansaks** [comment]
> I assume that you are using Microsoft.Graph.Beta instead of Microsoft.Graph. It would be better to put questions about it in https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet.

Sorry, yes I am. Do you want me to move my issue to that repo?

I haven't tried AddAsync but how would would I use that to change the HttpMEthod from Get to Post?

**Comment by MIchaelMainer** [comment]
AddAsync submits a POST request since we are adding a command per the metadata. Let us know how it works and please reopen this issue if that didn't resolve it.
