### ISSUE TITLE
[Client bug]: VSTO Outlook Plugin fails with GraphClient

### ISSUE THREAD

**Issue by neoprogger** [microsoftgraph/msgraph-sdk-dotnet#644]
**Describe the bug**
When using the graphserviceclient our outlook vsto plugin fails.
when using version 1.21> FindRibbons task failed unexpectedly...

when using version <= 1.17 it compiles correct - but the ribbon fails midway starting 
when this line is used: Client = New GraphServiceClient(New MyAuthenticationprovider)
without any exception

**Desktop (please complete the following information):**
 - OS: windows 10 / outlook 2016 2002 12527.20242

 
[AB#7274](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7274)

**Comment by MIchaelMainer** [comment]
Can you provide any further information on this? Can you show how you are implementing MyAuthenticationProvider?
