### ISSUE TITLE
Use CreateUploadSesssion to upload file but the server always returns Code: InternalServerError

### ISSUE THREAD

**Issue by AnVH-FPT** [microsoftgraph/msgraph-sdk-dotnet#646]
Yesterday, my application can upload files into OneDrive, SharePoint normally.
Today, I saw many exceptions when uploading files via UploadSesssion.
I implement follow: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs

Exception at: 
var uploadSession = await graphClient.Drive.Items["01KGPRHTV6Y2GOVW7725BZO354PWSELRRZ"].ItemWithPath("_hamilton.png").CreateUploadSession().Request().PostAsync();

Status Code: InternalServerError
Microsoft.Graph.ServiceException: Code: InternalServerError
Message: Object reference not set to an instance of an object.
Inner error:
	AdditionalData:
	request-id: b3ab4fbb-e3c2-4e07-a353-4e2a73b5bf67
	date: 3/10/2020 4:25:56 AM
ClientRequestId: b3ab4fbb-e3c2-4e07-a353-4e2a73b5bf67

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)

**Comment by mneuwohner** [comment]
Same issue here, customers started complaining today

**Comment by Andreas-Hjortland** [comment]
I also got the same issue today. If we in the graph explorer change the url from `https://graph.microsoft.com:443/v1.0/me/drive/items/[folderId]:/[fileName]:/microsoft.graph.createUploadSession`... to `https://graph.microsoft.com:443/v1.0/me/drive/items/[folderId]:/[fileName]:/createUploadSession` it will work.

If you really need this to work ASAP in the client library whilst we are waiting for Microsoft to triage and fix this issue, you can use the following reflection *hack* to work around the issue:

```c#
var regex = new Regex(@"/microsoft\.graph\.createUploadSession$");
var reqUrl = uploadSessionReq.RequestUrl;
typeof(DriveItemCreateUploadSessionRequest)
	.GetProperty(nameof(DriveItemCreateUploadSessionRequest.RequestUrl))
	.GetSetMethod(nonPublic: true)
	.Invoke(
		uploadSessionReq,
		new[]
		{
			regex.Replace(reqUrl, "/createUploadSession")
		}
	);
```

**Comment by mneuwohner** [comment]
This saved my day! Thanks very much, I'm using the Java SDK but could easily adopt this approach.

**Comment by Andreas-Hjortland** [comment]
Happy to be of help. Just remember that this is a hack and I cannot guarantee that it won't break in the future =)

**Comment by mneuwohner** [comment]
ofc, this will be temporary, I was already prepared to use the simple PUT upload and tell our customers that they can't upload files > 4MB, but this is definitely better

**Comment by MIchaelMainer** [comment]
Same issue https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/560

**Comment by darrelmiller** [comment]
The owning team has told me that this issue has been mitigated.  I have been watching for errors and currently I'm seeing it fixed in everywhere except North Europe.  Please let me know if you are still seeing the issue.

**Comment by AnVH-FPT** [comment]
Thanks darrelmiller,
It was worked normally.
