### ISSUE TITLE
Error when updating a single extended property

### ISSUE THREAD

**Issue by thezero** [microsoftgraph/msgraph-sdk-dotnet#65]
I have the following code:
```csharp
string userId;
string contactId;
string propertyId;

var expandContact = await client.Users[userId].Contacts[contactId].Request().Expand($"singleValueExtendedProperties($filter=id eq '{propertyId}')").GetAsync();
var property = expandContact.SingleValueExtendedProperties.CurrentPage.First();

// try to update whole contact
property.Value = "a-value";
await client.Users[userId].Contacts[contactId].Request().UpdateAsync(expandContact);

// try to update property only
property.Value = "new-value";
var requestBuilder = client.Users[userId].Contacts[contactId].SingleValueExtendedProperties[propertyId];
await requestBuilder.Request().UpdateAsync(property);
```

The first update works fine, but I know I only want to update the property which [should be possible (Request 2)](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/singlevaluelegacyextendedproperty_post_singlevalueextendedproperties#example)

The second update ends with `{Code: ErrorInvalidRequest Message: The OData request is not supported. Inner error }`.

As far as I can tell, the main issue is that `SingleValueLegacyExtendedPropertyRequest` actually appends property id to request URL, which is wrong. I tried creating custom request:
```csharp
var contact = client.Users[userId].Contacts[contactId];
var request = new SingleValueLegacyExtendedPropertyRequest(contact.RequestUrl, contact.Client, null);
await request.UpdateAsync(property);
```
And this is executed without any exception, however it also doesn't actually update the property. 

(Maybe I'm just missing how this should be done correctly, but in that case some example how to use extended properties would be nice. I found only [this one](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/master/tests/Microsoft.Graph.Test/Requests/Functional/ContactTests.cs))

**Comment by shiftylogic** [comment]
The request builder you are using in the second call is incorrect and not supported. That builder is an artifact of the fact that the libraries are generated from the CSDL. In this particular case, that pattern is blocked (i.e. an error) at the server level.

If you just want to update the single property, you can likely just create a new instance of the contact model, create a new ContactSingleValueExtendedPropertiesCollectionPage and set it on the previously created contact, add the property to the collection that you want to set, then make the patch call using you first call you labelled "whole contact". This should patch just the part you want.
