### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by ADNewsom09** [microsoftgraph/msgraph-sdk-dotnet#651]
**Describe the bug**
Unable to add the NuGet Package on .NET Core on Mac

**To Reproduce**
1. try to add package using VS on Mac
2. Error

**Desktop (please complete the following information):**
 - OS: Mac using dot net core 2.2 (or 3.1)

**Additional context**
Didn't see anything in the readme about requiring .net framework- the dependency list shows .Net Standard

Can we get some clarity on this in the readme?

**Comment by Misiu** [comment]
@ADNewsom09 what error? Could you paste it here?

**Comment by ADNewsom09** [comment]
it works from cli (dotnet add package Microsoft.Graph) just not from vs studio for mac package manager. I switched to vs code on my mac and no trouble now, can close
