### ISSUE TITLE
Migration 1.21.0 - 3.0.1

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#652]
I don't know where to ask about this. All of a sudden when I use Microsoft Visual Studio Nuget Package Manager it says there is an update for Microsoft Graph.

It reports 1.21.0 to 3.0.1

I always check regularly yet this seems a large leap. I am concerned about code breaking changes if I perform this update.

Please advise. Thank you.

**Comment by darrelmiller** [comment]
The blog post here https://developer.microsoft.com/en-us/graph/blogs/ covers the details on why this change was made.  There are breaking changes, but they should be detected by the compiler if they affect you and they should be easy to fix.

**Comment by ajtruckle** [comment]
I updated my package and now I can't get it due compile and it is not because of a code breaking change:

1>D:\My Programs\2019\OutlookCalIFConsole\OutlookCalIFConsole\Outlook.cs(49,32,49,50): error CS1705: Assembly 'Microsoft.Graph' with identity 'Microsoft.Graph, Version=3.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Net.Http' with identity 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

What do I do?
