### ISSUE TITLE
What is the official dependency for Graph v3 -  Newtonsoft.Json? v12.x?

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#653]
My Google API packages just downloaded v12.0.3.

But I see in my Outlook packages app.config:

```
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>

```

Do I need this binding redirect any more? Can I just compile with v12.0.3 newston?

Thanks.

**Comment by fowl2** [comment]
It looks like v12 is supported since Jan 2019 with PR #352

**Comment by darrelmiller** [comment]
As @fowl2 mentioned, we removed the restriction in 1.13, so you should be able to use any of the more recent versions of Newtonsoft.JSON.   Be aware that we have started down the path to try and move to System.Text.Json so that we no longer have a dependency on Newtonsoft.JSON
