### ISSUE TITLE
UserType of Graph.User could be null

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/msgraph-sdk-dotnet#654]
We want a list of all internal users so we tried to filter on UserType eq 'Member'. This works but we were missing quite some of our employees.  We then tried to simply exclude External users but the "not equals" operator is not supported for this field. 

When inspecting these users in the Azure AD Portal we found out that these users don't have a User Type value set. The SDK is reflecting this error by returning a null value for the Usertype which does not match the documentation. 

Since we cannot filter for external users via de $filter parameter directly on the Graph, we tried to retrieve all users and then filter in our own application. We found out that the Graph SDK also returns null values for the UserType field for some of the users. According to the documentation this is not possible (it's a string value).

We solved this by using the following code.

```
 bool isGuest = false;
            if (graphUser.UserType != null)
            {
                if (graphUser.UserType.Equals("Guest"))
                {
                    isGuest = true;
                }
            }
```

However we believe that this is something that should be fixed in the Graph or at least the Graph SDK. 
[AB#7276](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7276)

**Comment by andrueastman** [comment]
This will need some investigation on how to best handle this on the SDK. This could be related to how the DeltaResponseHandler does some of it work.

**Comment by ghelyar** [comment]
Just for additional information, we had this exact problem in the past and had to solve it in the same way, null `userType` occurs for users that were created before ~2014 but this is not well documented, and it seems to be impossible to create a filter to include both `member` and `null` but exclude `guest`, so you have to pull every user down and then filter the results in the application.

**Comment by bingjing-xiaozhao** [comment]
May I know if this issue has been fixed or not ? I have same question and due to our framework is 4.6.1, I can only use the package version 3.35.0. And I found that not only userType is null, but also AccountEnabled, MailNickName, etc

actually on properties like below have value, all others are null. This is not good experience.
![image](https://user-images.githubusercontent.com/105236096/170250688-07445c07-0286-4e06-a5f9-6da0e06657dd.png)

![image](https://user-images.githubusercontent.com/105236096/170251074-f58ee90e-c561-45e0-8ea5-7e8c872a5d89.png)

**Comment by andrueastman** [comment]
Hey @bingjing-xiaozhao,

In your scenario, have you included the properties you wish to see the values of in the select statement?
According to the documentation [here](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http), the API only returns a set of values if you do not specify the properties in the select statement.

![image](https://user-images.githubusercontent.com/6464005/170256171-31fe0238-cd7b-4991-9210-366b78c27d3f.png)

You may therefore need to do something like below to make sure the property is returned from the API if it exists.

```cs
var user = await graphClient.Users["{user-id}"]
	.Request()
	.Select("displayName,givenName,postalCode,identities")
	.GetAsync();
```

**Comment by bingjing-xiaozhao** [comment]
@andrueastman May I know your microsoft alias? I have some more questions, can I ping you on teams ?

**Comment by andrueastman** [comment]
Hey @bingjing-xiaozhao,

I'll reach out to you directly so that I can follow up.

**Comment by ddyett** [comment]
Closing as this seems to have been resolved.
