### ISSUE TITLE
Functionality regarding OneDrive suddenly stopped working

### ISSUE THREAD

**Issue by teradevel** [microsoftgraph/msgraph-sdk-dotnet#658]
My script that worked earlier suddenly stopped working.

The following script suddenly started returning:
`Error uploading file to drive: Code: generalException
Message: An error occurred sending the request.`

```
public async Task<DriveItem> UploadFileToDrive(string driveId, DriveItem folder, string fileName, MemoryStream stream)
{
    try
    {
        return await graphClient.Drives[driveId].Items[folder.Id].ItemWithPath(fileName).Content.Request().PutAsync<DriveItem>(stream);
    }
    catch (ServiceException ex)
     {
        Console.WriteLine($"Error uploading file to drive: {ex.Message}");
        return null;
     }
}
```

This is very weird as the script worked perfectly earlier and I am using the v.1.0 API which should not just change. 

Has anyone else experienced this? Is this some kind of limitation introduced because of the special situation. 
[AB#7277](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7277)

**Comment by MIchaelMainer** [comment]
@teradevel This sounds like a service issue. Do you have request-id you can share from the response? 
@ificator Is there a current incident with this API?

**Comment by ificator** [comment]
I'm not aware of any issues - is this targeting a consumer or business user?

**Comment by teradevel** [comment]
@MIchaelMainer Unfortunately I don't know how to get the request-id when using the SDK. 
I tried with printout 
`
Console.WriteLine($"Error uploading file to drive: {ex.Message} | {ex.RawResponseBody} | {ex.ResponseHeaders} | {ex.Error} | {ex.StatusCode}");
`
But all I get is:
```
Error uploading file to drive: Code: generalException
Message: An error occurred sending the request.
 |  |  | Code: generalException
Message: An error occurred sending the request.
 | 0
```
I wonder why the response is empty.


@ificator I got O365 E5 trial license and have registered the app there. So I guess a trial business user.

**Comment by teradevel** [comment]
Seems like there is some kind of throttling applied.

I tried the following code:
```
public static async Task<DriveItem> UploadFileToDriveRoot(string fileName, MemoryStream stream)
{
    try
    {
        return await graphClient.Drives["<---REDACTED--->"].Root.ItemWithPath(fileName).Content.Request().PutAsync<DriveItem>(stream);
     }
     catch (ServiceException ex)
     {
        Console.WriteLine($"Error uploading file to drive: {ex.Message}");
        return null;
    }
}

...

// test uploading 25 times
for (int i = 0; i<25; i++) {
        GraphHelper.UploadFileToDriveRoot("test.txt-" + i, new MemoryStream(System.IO.File.ReadAllBytes("test.txt"))).Wait();
}
```
The size of "test.txt" is about 1KB.

It succeeds sometimes but sometimes it fails. After succeeding once the failure rate grows fast, which makes it feel like there is some kind of cooldown after each upload.

I am doing the upload synchronously.

Looking at the throttling limits [here](https://docs.microsoft.com/en-us/graph/throttling) it looks like only PUTting beta endpoint is being throttled. However I am using 1.0 endpoint here.

**Comment by ificator** [comment]
@teradevel if you're on a Windows box you could use Fiddler to capture the requests being made to the Graph endpoint - that would let us see the request being made how how the service is responding. When it fails does it take a long time or is it quick? I'm trying to understand whether you're seeing an actual 429 / 503 from the service, or some kind of 504 being driven by a longer than expected upload time.

**Comment by teradevel** [comment]
I fiddled around a bit and got the following result:
![fiddle](https://user-images.githubusercontent.com/62008536/78334892-423b9780-7595-11ea-8146-bd0cfe696137.PNG)

So the upload requests succeed, until the token requests between the PUT's throw errors.
The errors return the following json:
```
{
  "error": "invalid_grant",
  "error_description": "AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor.\r\nTrace ID: 7839e20f-2cea-4643-8b67-5bf5068b0200\r\nCorrelation ID: 98f95902-1619-4004-bcef-a92d6f8e27e6\r\nTimestamp: 2020-04-03 07:11:16Z",
  "error_codes": [
    50196
  ],
  "timestamp": "2020-04-03 07:11:16Z",
  "trace_id": "7839e20f-2cea-4643-8b67-5bf5068b0200",
  "correlation_id": "98f95902-1619-4004-bcef-a92d6f8e27e6",
  "error_uri": "https://login.microsoftonline.com/error?code=50196"
}
```

**Comment by teradevel** [comment]
Funnily, if I save the JWT token and use it in the requests like so:

```
public async Task AuthenticateRequestAsync(HttpRequestMessage requestMessage)
{
    if(_token != null) {
        requestMessage.Headers.Authorization =
            new AuthenticationHeaderValue("bearer", _token);
    } else {
        requestMessage.Headers.Authorization =
            new AuthenticationHeaderValue("bearer", await GetAccessToken());
    }
}
```

I can upload as much as I want. So it seems like the problem is with GetAccessToken() asking before each call whether the current JWT token is valid.

I would like to be able to refresh the token though, any ideas?

**Comment by teradevel** [comment]
Funnily, if I save the JWT token and use it in the requests like so:

```
public async Task AuthenticateRequestAsync(HttpRequestMessage requestMessage)
{
    if(_token != null) {
        requestMessage.Headers.Authorization =
            new AuthenticationHeaderValue("bearer", _token);
    } else {
        requestMessage.Headers.Authorization =
            new AuthenticationHeaderValue("bearer", await GetAccessToken());
    }
}
```

I can upload as much as I want. So it seems like the problem is with GetAccessToken() asking before each call whether the current JWT token is valid.

I would like to be able to refresh the token though, any ideas?

**Comment by ificator** [comment]
What implementation of `IAuthenticationProvider` are you using? If it's the `DelegateAuthenticationProvider` could you provide the code in the delegate so we can see how you're obtaining auth? Remove any secrets, client ids, etc :)
