### ISSUE TITLE
MemberOf can return different results than Expand("memberOf")

### ISSUE THREAD

**Issue by frankfralick** [microsoftgraph/msgraph-sdk-dotnet#66]
Hello! Apologies if this has been covered elsewhere.  During development we have been doing something like this to get a user's groups:

`var user = await GraphClient.Users[userId].Request().Expand("memberOf").GetAsync();`

The result of which was fed to a method that would use the presumably returned "NextPageRequest" object to get results beyond the current page.  Our fake development user accounts, as well as early real users never had enough group memberships to require the NextPageRequest logic, and testing of it was forgotten about.  

After getting users with 20+ groups it eventually became clear that making a request as detailed above returns one page worth of memberships but does not return a NextPageRequest to use in the options of subsequent requests.  Your documentation around collections makes it seem like this is how it should be done.

As I'm sure you already know, a way that does work is like this:

`List<Group> userGroups = await GraphClient.Users[userId].MemberOf.Request().GetAsync().CurrentPage.Where(p => p.GetType() == typeof(Microsoft.Graph.Group)).Cast<Microsoft.Graph.Group>().ToList();`

This, as far as we have seen, returns all of the user's group memberships.  If the intent is that Expand not be used with "memberOf", then it shouldn't work at all.  Right now the old code worked fine for around 760 of the 800 users in the tenant, the remainder being the ones that write the checks :).  If we were doing .Expand("memberOf") incorrectly, let me know please.  

Also, GetMemberGroups works differently than MemberOf.  What's the intent?  Maybe doing something like `GetMemberGroups(securityEnabledOnly = false, expandGroupInfo = false)` might be clearer.  

Sorry if I'm way off base or missing something!  Thanks!

**Comment by shiftylogic** [comment]
This is an issue in the service layer and not specific to the .NET library.

Can you please post a question to StackOverflow with the 'microsoftgraph' tag and we can route it to the appropriate team for an answer? A post exactly as above with the tag would be more than sufficient.

**Comment by frankfralick** [comment]
[Here ](http://stackoverflow.com/questions/41285268/access-user-memberof-with-microsoft-graph-client-library)is the question on stackoverflow.
