### ISSUE TITLE
Where is Outlook.Tasks ?

### ISSUE THREAD

**Issue by maddinthegreat** [microsoftgraph/msgraph-sdk-dotnet#661]
Hello,

I use the Microsoft.Graph library version 3.2.0, but i cannot get this code to work:

`GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var tasks = await graphClient.Me.Outlook.Tasks
	.Request()
	.GetAsync();`

Outlook.Tasks are not found.

Regards
Martin

**Comment by MIchaelMainer** [comment]
You will need to use the Microsoft.Graph.Beta NuGet package to get that type.
