### ISSUE TITLE
General question about the graph library (authetication)

### ISSUE THREAD

**Issue by maddinthegreat** [microsoftgraph/msgraph-sdk-dotnet#662]
I currently port my old Exchange software to the MS.Graph library.

Is it correct that when I want get the Exchange (Outlook) contacts i.e., I MUST use the **PublicClientApplicationBuilder** to initiate an authentication?

**ConfidentialClientApplicationBuilder** with client secret is NOT allowed?

Is this correct? 
The consequence is that a user of my background software always needs to login (at least once per day when i save the token for later use)?

Regards
Martin

**Comment by MIchaelMainer** [comment]
You can use both builders. There is documentation here:
https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=CS

**Comment by maddinthegreat** [comment]
Hi,
have Desktop (background) app want to call Outlook APIs i'll get:

**Microsoft.Graph.ServiceException: 'Code: BadRequest
Message: Current authenticated context is not valid for this request. This occurs when a request is made to an endpoint that requires user sign-in.** 

ConfidentialClientApplicationBuilder + ClientCredentialProvider in use.

I'm stuck.

Regards

**Comment by wimvanhouts** [comment]
As @MIchaelMainer pointed out, you can use both builders, but, when you look in the documentation you will see that not all permissions are able to set for application as well as for users. Sometimes the permissions can only be set for an application, sometimes only for a user, sometimes for both. Probably you are authenticating as an app and trying to access something that is not possible to configure permissions for as an app, so you must log in as the user. That must be done using one of the authentication flows where you let the user log in once (at install time of your background application and refresh the token later on) or you use the username/password provider https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=CS but then it is up to you to store the credentials of the user (and, the user must trust you to provide his credentials to your application), which is not advised. Each function of the Graph API starts by saying which permissions are needed and whether they can be set for an application and/or a user.
