### ISSUE TITLE
Collection error

### ISSUE THREAD

**Issue by maddinthegreat** [microsoftgraph/msgraph-sdk-dotnet#663]
`   var contacts = await graphClient.Me.Contacts.Request().GetAsync();
`

ends up in:

**System.NotSupportedException: 'The collection type 'Microsoft.Graph.IUserContactsCollectionPage' on 'Microsoft.Graph.UserContactsCollectionResponse.Value' is not supported.'**

"Microsoft.Graph" 3.2.0
"Microsoft.Graph.Auth" preview.4
"Microsoft.Graph.Core" 2.0.0-preview.2
"Microsoft.Identity.Client" 4.11.0
"Newtonsoft.Json" 12.0.3

What may be the cause?

Regards

**Comment by MIchaelMainer** [comment]
Please use Microsoft.Graph.Core 1.20.1 at this time. The preview Microsoft.Graph.Core cannot be used with Microsoft.Graph at this time.
