### ISSUE TITLE
Outlook scope

### ISSUE THREAD

**Issue by maddinthegreat** [microsoftgraph/msgraph-sdk-dotnet#664]
Hello,

shouldn't be "Me.Contacts" moved to "Me.Outlook.Contacts" like tasks (events also etc.)?
It seems to me that Outlook items are in "global" Azure scope here.

Regards

**Comment by MIchaelMainer** [comment]
Tasks are temporarily under Outlook as we consolidate the different types of tasks that exist across the Microsoft ecosystem. Eventually they will be under me/tasks.
