### ISSUE TITLE
Where is system.http.net 4.2.0.0?

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#666]
Ever since I downloaded the latest graph .net my c# app is throwing exceptions about the system.http.net     version. 

Your docs say you compile against 4.2.0.0 so how do I get it?

I installed latest system.http.net vía NuGet and when I examine this dll it says 4.6. 

I have had no problems for years with your graph library until I upgraded to this edition. I wanted to upgrade because of newson conflicts. 

I am desperate here because my tool is now broken. 

I am using latest visual studio 2019 community edition.  
[AB#7278](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7278)

**Comment by MIchaelMainer** [comment]
Which version of Microsoft.Graph and Microsoft.Graph.Core are you using?

**Comment by ajtruckle** [comment]
> Which version of Microsoft.Graph and Microsoft.Graph.Core are you using?

3.2.0

I got it to work by using 4.6 framework and using a bind redirect that encompassed 4.2.0.0 but used the 4.6 version of the dll:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.0.0.0"/>
      </dependentAssembly>
```

I no longer get conflicts.

**Comment by andrueastman** [comment]
@ajtruckle I am closing this issue as it seems you have resolved the problem. Feel free to open an issue incase something comes up.
