### ISSUE TITLE
Create unifiedRoleDefinition fails with OData error

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/msgraph-sdk-dotnet#667]
**Describe the bug**
I wrote the following code to create a [unifiedroleDefinition ](https://docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-beta)in C#

                        ```
            try
            {
                IList<Beta.UnifiedRolePermission> rolePermissions = new List<Beta.UnifiedRolePermission>() { new Beta.UnifiedRolePermission() { AllowedResourceActions = new string[] { "microsoft.directory/applications/basic/read" } } };

                newRoleDefinition = await _graphServiceClient.RoleManagement.Directory.RoleDefinitions.Request().AddAsync(new Beta.UnifiedRoleDefinition
                {
                    Description = "Update basic properties of application registrations",
                    DisplayName = "Application Registration Support Administrator",                     
                    RolePermissions = rolePermissions,
                    IsEnabled = false
                });
            }
            catch (ServiceException e)
            {
                Console.WriteLine("We could not add a new UnifiedRoleDefinition: " + e.Error.Message);
                return null;
            }
```

This addressing is following the documentation for [create unifiedRoleDefinition](https://docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-beta&tabs=http)

I received the following error:

```
> {
>   "error": {
>     "code": "Request_BadRequest",
>     "message": "A type named 'microsoft.graph.unifiedRolePermission' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.",
>     "innerError": {
>       "request-id": "29e5a84a-2acb-4c50-9ed1-fff240173f88",
>       "date": "2020-04-10T10:04:07"
>     }
>   }
> }
> 
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] N/A

**Smartphone (please complete the following information):**

**Additional context**
 
[AB#7279](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7279)

**Comment by MIchaelMainer** [comment]
This is the OData.Type issue where workloads aren't accepting the odata.type instance annotation that the client emits in requests. The service API should gracefully ignore unknown OData instance annotations. 

The mitigation is to set the `UnifiedRolePermission.OdataType = null` to mitigate this until the service API gracefully ignores unexpected instance annotations.

@psignoret Is this a known issue in the RolePermissions API?

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/993 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
