### ISSUE TITLE
User Object Missing CreatedDateTime

### ISSUE THREAD

**Issue by npruessner** [microsoftgraph/msgraph-sdk-dotnet#669]
**Describe the bug**
The graph explorer allows me to select on CreatedDateTime when querying users. However, when using this library, I do not find the CreatedDateTime property on the User object. 

**To Reproduce**
1. Go to https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/0b735c27d99d8bd1ff6d9d244e65f9e85ba10499/src/Microsoft.Graph/Models/Generated/User.c 
2. Notice the lack of a CreatedDateTime.
3. Go to https://developer.microsoft.com/en-us/graph/graph-explorer
4. Run the following query on the Users collection: users?$filter=userType eq 'Member'&$select=createdDateTime
5. Notice the response of various createdDateTimes. 

**Expected behavior**
I would expect the library to accurately represent the API. If I receive a createdDateTime from the API, I should also see that property on the class in your library.

**Comment by MIchaelMainer** [comment]
@darrelmiller This is missing metadata in our v1.0 metadata, hence it isn't getting generated into our models. We see this is in the beta metadata.

You will need to access this property via User.AdditionalData until we get this into our model.

**Comment by MIchaelMainer** [comment]
@dkershaw10 Is this is a known issue?

**Comment by MIchaelMainer** [comment]
This doesn't work
`https://graph.microsoft.com/v1.0/users?$select=createddatetime`

This does
`https://graph.microsoft.com/v1.0/users?$select=createdDateTime`

**Comment by npruessner** [comment]
Closing the issue. Thanks for the info!

**Comment by msereda** [comment]
@MIchaelMainer  Hi, is this on the roadmap to add to the 1.0 endpoint fairly soon?  This issue is closed but createdDateTime is still not part of the 1.0 model.  Unfortunately with the way we serialize/map our graph calls in our apps the AdditionalData property requires a lot of extra effort to consume.  Therefore if it'll be added within the next month we'll wait as opposed to spending the time on consuming it from AdditionalData.

**Comment by MIchaelMainer** [comment]
@msereda Reopened until this is resolved. I don't have roadmap info on this. I can only suggest that additionalData used until they make this fix.

**Comment by msereda** [comment]
Okay, thank you for the reply.

**Comment by chsauget** [comment]
Hello, thanks a lot for working on this ! During this time, can you point to an example of retrieving this information using additionalData ? (The only node information I succeed to extract from additionalData was $type)

Regards,

**Comment by msereda** [comment]
CreatedDateTime has been added to the sdk in Graph v3.13.

**Comment by MIchaelMainer** [comment]
This is now resolved. CreatedDateTime has been added to the schema.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/model/User.cs#L101
