### ISSUE TITLE
SDK allows creating upload session using folder and/or item ID only, but the REST API requires "path syntax"

### ISSUE THREAD

**Issue by danyoel** [microsoftgraph/msgraph-sdk-dotnet#67]
`IDriveItemRequestBuilder` declares a method `CreateUploadSession` which only works if the builder was created with `IUserRequestBuilder.ItemWithPath()`. It does not work if the builder was created with the `Me.Drives[driveId].Items[itemId]` method. The reason is that the underlying REST API requires the "path syntax" rather than folder/item ID syntax. The SDK should not create a URI that is not acceptable to the REST endpoint.

If the incorrect syntax is used, the REST API returns:
```{json}
{
  "error": {
    "code": "invalidRequest",
    "message": "A valid path must be provided.",
    "innerError": {
      "request-id": "b1a3e21c-59e9-42e9-bf6e-6eae92d77cfa",
      "date": "2016-12-01T22:43:17"
    }
  }
}
```

**Comment by shiftylogic** [comment]
Thanks for reporting this. The library is generated based on the CSDL metadata provided by the Graph REST service endpoints. This issue you report is an artifact of how OneDrive works which is not 100% expressed in the CSDL for the service. Thus, a general purpose code generation occasionally introduces builders that are not valid / compliant with the REST services.

We are considering various ways to solve these problems for future iterations of the library.
