### ISSUE TITLE
[Client bug]: File with "&#"  characters in the filename can`t be uploaded

### ISSUE THREAD

**Issue by PatrykBobak** [microsoftgraph/msgraph-sdk-dotnet#671]
**Describe the bug**
File with "&#"  characters (next to each other) in the filename,e causes errors when requesting or uploading the item
Example filename: 屜丯愛金—―〜～‖∥−－¦￤№ 鷗㐀葛渚噓&#x2000B.pptx

Adding a separator between characters allows to successfully send a request. 
Example filename:  屜丯愛金—―〜～‖∥−－¦￤№ 鷗㐀葛渚噓&-#x2000B.pptx

**Code to reproduce issue**

```
string path = "file%26%23.pptx"
GraphClient.Users[msUserID].Drives[driveID].Root.ItemWithPath("/" + path).Request().GetAsync().Result;
```

**Expected behavior**
The request should be successful 

**Client version**
1.21.0
 
[AB#7280](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7280)

**Comment by GerjanVlot** [comment]
#700 Maybe related

**Comment by ddyett** [comment]
Closing older stale issues. Please reopen if occurs with v5.
