### ISSUE TITLE
Ability to use Linq Select method when querying properties and schema extensions properties of graph users

### ISSUE THREAD

**Issue by TechWatching** [microsoftgraph/msgraph-sdk-dotnet#672]
**Is your feature request related to a problem? Please describe.**
I want to use the Linq `Select` method to select which properties I need to get for a microsoft graph users query. However there is not way to use this method with a schema extension as one of the properties I want  to select like on the sample below :

```csharp
IGraphServiceUsersCollectionPage? currentUsersPage = await _graphClient.Users
    .Request()
    .Select(u => new
    {
        u.DisplayName,
        u.UserPrincipalName,
        u.MyExtensionName
    })
    .GetAsync();
```
The sample above does not compile.

**Describe the solution you'd like**
I want to be able to use the following syntax or a similar syntax with the extension name.

**Describe alternatives you've considered**
I know that I can use the `Select` method that takes a string in parameter but that is less elegant and I would loose type safe.

**Additional context**
The graph explorer preview suggest the following snippet when selecting an extension but obviously this does not compile.
![image](https://user-images.githubusercontent.com/15186176/79558964-47283d00-80a5-11ea-8e93-09c137693e31.png)

**Comment by MIchaelMainer** [comment]
You will need to use the overload that has the comma-delimited list of property names. This won't be possible with Linq since we don't have the property names at code time.
