### ISSUE TITLE
Cannot update mailbox settings with SDK

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-dotnet#673]
Attempts to update mailbox settings with the SDK fail with `Code: ErrorInvalidRequest
Message: The OData request is not supported.` This was reported via the docs repo in https://github.com/microsoftgraph/microsoft-graph-docs/issues/5007

```
var userId = "some user id";
var user = new User();

//setup mailbox settings object
var mailboxSettings = new MailboxSettings
{
    AutomaticRepliesSetting = new AutomaticRepliesSetting()
    {
        Status = AutomaticRepliesStatus.AlwaysEnabled,
        InternalReplyMessage = "something",
        ExternalReplyMessage = "something",
    }
};
user.MailboxSettings = mailboxSettings;

await _graphServiceClient
    .Users[userId]
    .Request()
    .UpdateAsync(user);
```

Currently you can workaround this using the underlying HTTP provider ([Gist](https://gist.github.com/jasonjoh/f4d9ec4c9eae01c23bad12eadf409088))

**Comment by jasonjoh** [comment]
The problem is caused by the SDK sending the PATCH to the user endpoint, which isn't what's specified in the documentation.

Bad: `PATCH /v1.0/users/{user-id}`

Good: `PATCH /v1.0/users/{user-id}/mailboxsettings`

**Comment by MIchaelMainer** [comment]
Duplicate issue. Keep open for us to add custom request builders for this functionality.
