### ISSUE TITLE
Documentation Bug: Missing Information on REST-C# API Mapping

### ISSUE THREAD

**Issue by iUnknwn** [microsoftgraph/msgraph-sdk-dotnet#674]
**Describe the bug**
All existing documentation only explains how to provide calls on the Me C# object, but there is no information given on how to make alternate requests, nor any information on how the REST api should map to the C# calls. 

For example, if I wanted to make a call to `https://graph.microsoft.com/v1.0/users/[guid]/`, there's no documentation explaining how the rest call should be translated into the C# call. 

Additionally, the Me object is undocumented. For example, there are examples on how to use Me to get a user photo, but no information on how to get simple subqueries, like me/memberOf.

**Comment by darrelmiller** [comment]
The GraphServiceClient provides an object hierarchy that maps largely to the URL path.  Therefore to access /users/{id} you would use code that looks like this.

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var user = await graphClient.Users[{id}]
	.Request()
	.GetAsync();
```

**Comment by iUnknwn** [comment]
@darrelmiller Thank you for answering my question, but this doesn't solve the documentation issue; there's currently no API doc for the graph client, and there's only two examples of REST to C# calls, both using the same style call. To illustrate this, if you hadn't given the example with Users, it would be impossible to determine users was a dictionary expecting a key.
