### ISSUE TITLE
Users API - how to get the custom properties of a user.

### ISSUE THREAD

**Issue by thchuong-x11** [microsoftgraph/msgraph-sdk-dotnet#678]
**Is your feature request related to a problem? Please describe.**
When editing my profile on my company Sharepoint, I see that there is the section "Custom properties" where I can specify Division, Report To, My Bio.

![image](https://user-images.githubusercontent.com/9824504/80066728-ce116580-853c-11ea-8522-53605c6048c1.png)

These information is then shown in the User profile view in MS Delve.

I would like to extract these information, using the Graph API on .NET.
I have taken a look at the documentation of Users API in v1.0 and beta, but there is no mention of custom properties.
I have also looked the new Profile API (Preview) but again there is no mention either.

**Describe the solution you'd like**
I would like to know, how can I use Graph API to get these information ? 
Ideally, I would expect I can do this with Users API or Profile API

**Describe alternatives you've considered**
No alternative that I know

**Comment by MIchaelMainer** [comment]
Thank you for your feature request. Please post feature requests for the service API to the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).
