### ISSUE TITLE
[Client bug]: Error calling SharePoint DocLib items via SDK

### ISSUE THREAD

**Issue by messerke** [microsoftgraph/msgraph-sdk-dotnet#681]
**Describe the bug**
I'm trying to get items from SharePoint using the Graph API in the name of the user, all these done inside a .net core 3.1 web app using oauth2. When I request for specific items in a SharePoint document library I get the following ServiceException:
```
ex = {"Code: itemNotFound\r\nMessage: The resource could not be found.\r\nInner error:\r\n\tAdditionalData:\r\n\trequest-id: 7605d475-5967-481e-a16c-ab1fad610ef9\r\n\tdate: 2020-04-15T21:27:48\r\nClientRequestId: 7605d475-5967-481e-a16c-ab1fad610ef9\r\n"}
```
If I call the API using the Graph explorer with the same user in the same time using the same Item identifier, it gives back its children well. Needless to say, the user can login to the SPS site and do whatever she wants. :)

**To Reproduce**
My calling function is the following:
```
var searchResult = await graphServiceClient
                    .Sites[$"{SharePointSiteId}"]
                    .Drives[$"{SharePointDocumentLibraryId}"]
                    .Items[$"{InvoicesFolderId}"]
                    .Children
                    .Request()
                    .GetAsync();
```

where:

- SharePointSiteId is a fully qualified SPS site Id
- SharePointDocumentLibraryId id of the document library
- InvoicesFolderId id of the folder in which I'd like to enumerate the children elements

The strange is that until I request for the Drive only:
```
var searchResult = await graphServiceClient
                    .Sites[$"{SharePointSiteId}"]
                    .Drives[$"{SharePointDocumentLibraryId}"]
                    .Request()
                    .GetAsync();
```
everything goes fine. I get no errors, but the expected Drive.

**Expected behavior**
Even if the API with Item with identifier is called, the result should be a DriveItem.

**Screenshots**
N/A

**Client version**
Microsoft.Graph 3.3.0

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Chrome-newest

**Additional context**
I've posted this on [Stackoverflow ](https://stackoverflow.com/questions/61239182/calling-microsoft-graph-api-from-dotnetcore-app-returns-notfound)as well, one guy could reproduce it, so maybe it could be a bug.
 
[AB#7281](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7281)

**Comment by BrianTJackett** [comment]
I am able to reproduce this issue as well using the steps provided.  Taking the query URL from Graph SDK and submitting it via Graph Explorer / Postman is successful though.  Leads me to believe this is only an issue with SDK submitting the query.

**Comment by ddyett** [comment]
Closing this older issue as it's stale.  Please reopen if happens on v5 or greater
