### ISSUE TITLE
ChunkedUploadProvider.UploadAsync says "exponential backoff" but implements quadratic backoff

### ISSUE THREAD

**Issue by jnm2** [microsoftgraph/msgraph-sdk-dotnet#682]
Exponential backoff means multiplying the previous delay on each try by a constant factor. E.g  `initialDelay * Math.Pow(factor, previousTryCount)` where `factor` > 1. If `factor` is 2, it could be implemented as `initialDelay << previousTryCount`. The delay could also be stored in a variable and multiplied by a constant after each wait.

This, however, is the equivalent of `initialDelay * Math.Pow(currentTryCount, 2)` which makes it quadratic (x<sup>2</sup>) rather than exponential (e.g. 2<sup>x</sup>):

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/a9219fc2da8ba1d8b85e8124ccfb017859ecb2e2/src/Microsoft.Graph/Requests/Helpers/ChunkedUploadProvider.cs#L148-L149
 
[AB#7283](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7283)

**Comment by MIchaelMainer** [comment]
We need to investigate this backoff-retry code as the default retry handler should handle backoff scenarios before it gets back to the this.

**Comment by andrueastman** [comment]
The ChunkUpload provider is deprecated in the next version of the sdk. 
Please check out the LargeFileUploadTask [here](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?view=graph-rest-1.0&tabs=csharp).
