### ISSUE TITLE
Category is missing inside Event

### ISSUE THREAD

**Issue by Blackleones** [microsoftgraph/msgraph-sdk-dotnet#685]
**Describe the bug**
The Category property is missing inside Event.cs even if it is reported inside the [documentation](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0)

**To Reproduce**
Look at [Event.cs](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/a9219fc2da8ba1d8b85e8124ccfb017859ecb2e2/src/Microsoft.Graph/Models/Generated/Event.cs)

**Comment by MIchaelMainer** [comment]
The Categories property is in the base OutlookItem class.
