### ISSUE TITLE
Add Custom request option

### ISSUE THREAD

**Issue by marekbuban** [microsoftgraph/msgraph-sdk-dotnet#686]
I've noticed java sdk allows to make "Custom request"
https://github.com/microsoftgraph/msgraph-sdk-java/wiki/Custom-Requests

It would be great if .net sdk allows the same. Any plan to add it or reason why not? 
[AB#7284](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7284)

**Comment by MIchaelMainer** [comment]
We discussed this before. The conclusion is that we want people to either use the generated client when possible, and if not, you use the httpClient to submit requests via the httpProvider: 

GraphServiceClient.HttpProvider.SendAsync(httpRequestMessage)

There is a response handler for deserializing the response objects.

To anyone seeing this post, please 👍 if you want a Custom Request option in the client.

**Comment by ddyett** [comment]
Closing this stale issue.
