### ISSUE TITLE
MailboxNotHostedInExchangeOnline error when trying to retrieve user profile photo

### ISSUE THREAD

**Issue by heshansp** [microsoftgraph/msgraph-sdk-dotnet#688]
Graph API spits out the following error when I'm trying to retrieve a user's profile photo
```json
{
  "error": {
    "code": "MailboxNotHostedInExchangeOnline",
    "message": "Mailbox is hosted by an on-premise or non-Exchange server, which is not supported.",
    "innerError": {
      "request-id": "eabab56f-4b8f-4a51-9e0a-159ac6150e57",
      "date": "2020-05-03T05:34:37"
    }
  }
}
```

API endpoint used [https://graph.microsoft.com/beta/users/0f9f44ab-3e62-4ac4-9936-a566342afb7d/photo/$value](url)

More importantly this USED to work about a week ago. Not it is just giving this irrelevant error message.

**Comment by MIchaelMainer** [comment]
Can you verify that the user's mailbox has not been migrated back to an on-premise server?

**Comment by heshansp** [comment]
Hi,
The user's mailbox was never on cloud. We have never used exchange online. But this endpoint use to work before.

**Comment by MIchaelMainer** [comment]
AFAIK, this wasn't supposed to work in the first place. The Graph API is intended for use against mailboxes hosted in Microsoft 365 / Exchange Online. Let me see if I can find more information.

**Comment by heshansp** [comment]
Are you sure? Because we have our Active  Directory synced to cloud. All other user related graph api endpoints work except for this.

**Comment by MIchaelMainer** [comment]
No, I wasn't sure. This looks like a regression in the service.

**Comment by heshansp** [comment]
Hi Michael,
I think I figured it out. It is due to a restriction MS implemented recently.

https://docs.microsoft.com/en-us/graph/known-issues#photo-restrictions

It means if there in no Exchange Online account, graph is not going to spit-out user's profile photo. Although I do not know why MS decided to do something like that. Even our Teams desktop app cannot get profile images now.

**Comment by b3hrus** [comment]
The profile picture belongs to the AAD user and not exchange. Therefore, the picture should be also accessible via an API like any other AAD property of the user's profile.

**Comment by heshansp** [comment]
Can someone please explain how this started working all of a sudden?

**Comment by MIchaelMainer** [comment]
@heshansp We fixed the regression on the backend.
