### ISSUE TITLE
Cannot create booking customer with name

### ISSUE THREAD

**Issue by sidlovskyy** [microsoftgraph/msgraph-sdk-dotnet#689]
**Describe the bug**
Sample code for creating booking customer using Microsoft Graph doesn't work.
Similar to [documentation](https://docs.microsoft.com/en-us/graph/api/bookingbusiness-post-customers?view=graph-rest-beta&tabs=csharp):

**To Reproduce**
`await graphClient.BookingBusinesses[id].Customers.Request().AddAsync(new BookingCustomer { DisplayName = "My Customer", EmailAddress = "my@customer.com", });`

The customer is created but email is used as name.

**Expected behavior**
Customer name should be stored.

**Screenshots**
![image](https://user-images.githubusercontent.com/1065322/81015051-a4bed680-8e66-11ea-80d1-dd5cef97d128.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Microsoft.Graph.Beta 0.17.0-preview
 - .NET Core 3.1 
[AB#7285](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7285)

**Comment by MIchaelMainer** [comment]
Can you share with us a sanitized captured response using Fiddler?
