### ISSUE TITLE
Can't submit GraphApi bug to Azure Portal.

### ISSUE THREAD

**Issue by sirmrowa** [microsoftgraph/msgraph-sdk-dotnet#692]
I can't submit GraphApi bug to Azure Portal as described in instruction. When login to Azure Portal, can't choose issue type as "Technical" because this type don't exist.
 
[AB#7286](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7286)

**Comment by mariusstaub** [comment]
Any updates on this? 
I had the same problem. Then when my account got sufficient privileges to ask a "Technical" question it was answered by a Technical Adviser of Office 365 with this: "Unfortunately, the support request you have raised is not a Unified or Premier Support request and is not entitled to developer support (including Graph support). Developer support for desktop technologies and the Office 365 suite is currently offered to Microsoft Unified Support and Premier customers."

The instructions should be clarified with a hint ("only for Microsoft Unified Support and Premier customers") or the link "Open a ticket" on https://developer.microsoft.com/en-us/graph/support should be removed.

**Comment by andrueastman** [comment]
This is a documentation issue for the service bug report template. 
We will need to update this template to give some instructions in scenarios where it's not possible to submit a request through the portal.

**Comment by ddyett** [comment]
page has been updated with different steps so closing this stale issue.
