### ISSUE TITLE
Correct way to implement retry?

### ISSUE THREAD

**Issue by IB38** [microsoftgraph/msgraph-sdk-dotnet#696]
I need to implement retry to handle expired access tokens.
So i made a wrapper of HttpProvider that implements SendAsync like this:
```        
public async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request,
            HttpCompletionOption completionOption,
            CancellationToken cancellationToken)
        {
            try
            {
                return await baseHttpProvider.SendAsync(request, completionOption, cancellationToken).ConfigureAwait(false);
            }
            catch (ServiceException e)
            {
                if (e.Error.Code != "InvalidAuthenticationToken" || authProvider.RefreshCallback == null)
                    throw;

                authProvider.Token = authProvider.RefreshCallback.Refresh();
                await authProvider.AuthenticateRequestAsync(request).ConfigureAwait(false);
                
                return await baseHttpProvider.SendAsync(request, completionOption, cancellationToken).ConfigureAwait(false);
            }
        }
```
_authProvider_ is my implementation of IAuthenticationProvider that sets Authorization header to Bearer + Access token
_authProvider.RefreshCallback.Refresh_ return new AccessToken

My problem is that HttpProvider throw exception when attempting to send same request a second time.
I looked around, but looks like request cloning is internal only.
What would be the correct way to implement retry in this case?

Im using Microsoft.Graph 3.0.1 and Microsoft.Graph.Core 1.20.0.

**Comment by darrelmiller** [comment]
MSAL.NET will automatically refresh tokens for you.  We have auth providers for all the common flow here https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth These should show how to incorporate MSAL.NET into the Graph SDKs.

**Comment by IB38** [comment]
> 
> 
> MSAL.NET will automatically refresh tokens for you. We have auth providers for all the common flow here https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth These should show how to incorporate MSAL.NET into the Graph SDKs.

Unfortunately, its not an option for me. Also i have no issues refreshing tokens, i just need a way to retry sending request.

**Comment by darrelmiller** [comment]
I'm curious as to why you can't use MSAL.NET.  But, to address your concerns.  Feel free to just copy the request cloning code from our Retry handler so that you can create a new request to retry with.

**Comment by IB38** [comment]
Yeah, i guess i will resort to that. Thanks.
