### ISSUE TITLE
Inconsistencies between the results from Graph SDK and the Teams User Activity Report

### ISSUE THREAD

**Issue by roygarbriceno** [microsoftgraph/msgraph-sdk-dotnet#697]
According to documentation for Teams User Activity Report (https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report) **Meetings organized** is the number of scheduled meetings a user organized during the specified time period and **Meetings participated** is the number of scheduled meetings a user participated in during the specified time period. However, when requesting events for the same user using the Graph SDK (https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http) (by page until we get all result) we get a completely different number. For example:

Meetings organized (user activity report):  132

Meetings participated (user activity report): 56 

Total events from graph: 67

We tried testing with other users, and we see the same behavior. If the meetings being count in the report are the ones that were scheduled, shouldn’t all appear through the Graph SDK? If there a data retention issue? Or the Teams report is considering something more besides the scheduled meetings? 

I'm not sure if its exactly a bug, or maybe there're some details missing in the documentation, but any clarification about this would be greatly appreciated

 
[AB#7238](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7238)

**Comment by MIchaelMainer** [comment]
Can you share with us your code and a sanitized Fiddler trace if you have it?
