### ISSUE TITLE
The Prefer header for Immutable Id is not working when the $search query parameter is used

### ISSUE THREAD

**Issue by g-tomov** [microsoftgraph/msgraph-sdk-dotnet#698]
**Describe the bug**
When using the $search query parameter with the request header `Prefer: IdType="ImmutableId"` the response returns not immutable id. In the response there is a header that indicates that the request immutable id header is taken into account. We have this problem in Windows Forms application. We have this problem only with $search query parameter. Any other query parameter like $filter, $expand and etc. is working correctly.

**To Reproduce**
Here some code from the request which is build:
```
graphServiceClient.Me
        .MailFolders[folderId]
        .Messages
        .Request(new[] { new QueryOption("$search", "Polo") })
        .Top(50)
        .Header("Prefer", "IdType=\"ImmutableId\"")
        .GetAsync();
```
Result:
The message id is not immutable:
`AAMkADJjOGUyZTdkLTMwMDMtNGU4NC05NGJlLTY1ZjYzMTkyYmNhNgBGAAAAAADDjnIM2SVjSaOrbBpUPML8BwCAAdJ9boFvTagruNDHEilBAAKYvfiIAACAAdJ9boFvTagruNDHEilBAAK1ieECAAA=`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.138

**Additional context**
Application: Windows Forms 
NuGet Package: Microsoft.Graph 3.6.0 
[AB#7239](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7239)

**Comment by MIchaelMainer** [comment]
@svpsiva Does search support immutable ID?

**Comment by MIchaelMainer** [comment]
It appears that the immutableId is not supported with $search query parameters when targeting messages. You'd need to make a secondary call to translate those IDs to immutable ids using the translateExchangeIds API.

Another investigation would be to try immutableIds header with the search API: https://docs.microsoft.com/en-us/graph/search-concept-messages
