### ISSUE TITLE
Filter doesn't work with #

### ISSUE THREAD

**Issue by GerjanVlot** [microsoftgraph/msgraph-sdk-dotnet#700]
When calling this request with dotnet it gives a error.
https://graph.microsoft.com/v1.0/me/messages?$filter=contains(subject, '#')

`
client.Users[adUserIdOrEmail].MailFolders.Inbox
                .Messages.Request().Filter('contains(subject, '#')')
`

Workaround is 
`
client.Users[adUserIdOrEmail].MailFolders.Inbox
                .Messages.Request().Filter('contains(subject, '%23')')
`

It would be nice if it replaces hashtags with the html encoded text.

 
[AB#7240](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7240)

**Comment by MIchaelMainer** [comment]
Dependency on work for Odata URL validation.

**Comment by andrueastman** [comment]
This is resolved via microsoftgraph/msgraph-sdk-dotnet-core#255 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
