### ISSUE TITLE
Add support for requesting only one type of object.

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/msgraph-sdk-dotnet#701]
**Is your feature request related to a problem? Please describe.**
When using the Graph REST API manually, I can construct request URLs that look like this:

https://graph.microsoft.com/v1.0/groups/fc64dfac-9a45-42eb-8037-dd6932f19654/transitiveMembers/microsoft.graph.user

Which will get only the users that are transitive members of the group fc64dfac-9a45-42eb-8037-dd6932f19654, filtering out the groups and other directory objects on the server side.

**Describe the solution you'd like**
I can see either a generic parameter on the request or request builder like this:

```
var members = await _graphServiceClient.Groups[objectId.ToString()].TransitiveMembers.Request()
    .SelectType<User>()
    .Select("id,displayName")
    .GetAsync();
```

Or even taking the entity name:
```
var members = await _graphServiceClient.Groups[objectId.ToString()].TransitiveMembers.Request()
    .SelectType("microsoft.graph.user")
    .Select("id,displayName")
    .GetAsync();
```

**Describe alternatives you've considered**
I've considered opening the request object and modifying the request URL in there, but I'm not sure how well that would work. For now, I'm simply filtering out all the types I don't care about on the client side with a foreach loop and a pattern match.

 
[AB#7241](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7241)

**Comment by MIchaelMainer** [comment]
This is a related issue. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/239

We need to support type filter / cast.

**Comment by andrueastman** [comment]
With the latest V5 preview version, this should now be possible to do with code similar to this.

```cs
var usersInGroup = await graphServiceClient.Groups["group-id"].TransitiveMembers.User.GetAsync();
```

More information is also available in the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#support-for-odata-casts-in-request-builders).
