### ISSUE TITLE
unable to upload attachments more than 4MB using Microsoft.Graph.SendMail

### ISSUE THREAD

**Issue by seemanambiar** [microsoftgraph/msgraph-sdk-dotnet#702]
We are trying to upload attachments more than 4MB using Microsoft.Graph SendMail

Following are the steps we are following: 
1.	Create the message (sample: https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=csharp#request-1)
2.	Add the large file attachment which follows the two step process of: 
a.	Create the upload session (sample: https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=csharp#request)
b.	Upload the file attachment using LargeFileUploadTask<FileAttachment> (sample: see the FileAttachment support section of the following PR for the MS Graph dotnet core SDK library:  https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/65)
3.	Send the message (sample: https://docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=csharp#request)

 
I am getting a request timed out error with the following stack trace at the  largeFileUploadTask below. On further analysis it 
was found that  the endpoint was looking at the MS Graph token rather than the auth token supplied in the URL. 

Code snippet: 
 

         IAuthenticationProvider authProvider = new DelegateAuthenticationProvider(async (requestMessage) =>
            {

                // Retrieve an access token for Microsoft Graph (gets a fresh token if needed).
                var authResult = await confidentialClient
                    .AcquireTokenForClient(scopes)
                    .ExecuteAsync();
                // Add the access token in the Authorization header of the API request.
                requestMessage.Headers.Authorization =
                 new AuthenticationHeaderValue("Bearer", authResult.AccessToken);
            });
	    graphClient.AuthenticationProvider = authProvider; 

 
           UploadSession uploadsession= graphClient.Users[email].Messages[createdMessage.Id]
                                               .Attachments.CreateUploadSession(attachmentItem)
                                               .Request().PostAsync().GetAwaiter().GetResult();
		
            LargeFileUploadTask<FileAttachment> largeFileUploadTask = new LargeFileUploadTask<FileAttachment>(uploadsession, fileStream, fragSize, graphClient);
            Task.Run(() => MainAsync(largeFileUploadTask,fileSize)).ConfigureAwait(false).GetAwaiter().GetResult();

            graphClient.Users[email]
                        .SendMail(message, true)
                        .Request()
                        .PostAsync().GetAwaiter().GetResult();

            //This method is called from the console application main method
        static void MainAsync(LargeFileUploadTask<FileAttachment> largeFileUploadTask,int len)
        {
            try
            {
              //ERROR HERE
                **UploadResult<FileAttachment> uploadResult = largeFileUploadTask.UploadAsync().ConfigureAwait(false).GetAwaiter().GetResult();**
                if(!uploadResult.UploadSucceeded)
                {
                    Console.WriteLine("not succeeded");
                }
            }
            catch (ServiceException e)
            {
                Console.WriteLine(e.Message);
            }
        }
 `

Stacktrace:
 
at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.UploadSliceRequest`1.<SendRequestAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.UploadSliceRequest`1.<PutAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.LargeFileUploadTask`1.<UploadSliceAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.LargeFileUploadTask`1.<UploadAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SendEmailConsole.Program.MainAsync(LargeFileUploadTask`1 largeFileUploadTask, Int32 len) in C:\Temp\SendEmailConsole\SendEmailConsole\Program.cs:line 281
 
[AB#7242](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7242)

**Comment by MIchaelMainer** [comment]
You didn't mention the large file upload documentation which contains an example that you can follow. https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp

Please take a look at that documentation and let us know whether it helps you implement large attachment upload.

**Comment by andrueastman** [comment]
@seemanambiar Any chance the instructions worked out for you?

**Comment by seemanambiar** [comment]
@andrueastman actually no. it was not straightforward. We had to use the delegated authenticationprovider 
graphClient.AuthenticationProvider = authProvider;
 UploadSession attachmentUploadSession = await graphClient
                                                                     .Users[mailMessage.From.EmailAddress.Address.ToString()]
                                                                     .Messages[createdMessage.Id]
                                                                     .Attachments.CreateUploadSession(attachmentItem)
                                                                     .Request().PostAsync();

After this we used LargeFileUploadTask.UploadAsync Task to upload the large file attachment. Subsequently we had to 
add "graphClient.AuthenticationProvider = null;" and then the following statement to send the email.

graphClient.AuthenticationProvider = authProvider;
                    await graphClient.Users[mailMessage.From.EmailAddress.Address.ToString()]
                         .Messages[createdMessage.Id]
                         .Send().Request().PostAsync();

**Comment by andrueastman** [comment]
@seemanambiar Thank you for the feedback regarding this.

To avoid this, you can call the `LargeFileUploadTask` constructor without passing in the graphClient parameter(as is done in the example). This way the task will use its own graphClient that will not be sending an auth Header(setting the auth header is not allowed when calling the upload urls).

There is however value to make this clear in the example.  I will therefore close this issue and create a separate issue  to have the docs updated to make things clearer.

**Comment by Sn3akyP3t3** [comment]
@andrueastman did documentation ever get updated?  I don't see any documentation referencing `LargeFileUploadTask` at https://docs.microsoft.com/en-us/graph/outlook-large-attachments

**Comment by Sn3akyP3t3** [comment]
@MIchaelMainer using the link to the `LargeFileUploadTask` I was able to successfully upload, but I used a `MemoryStream` instead.  However, due to that I encountered errors when trying to reference for updates on progress with the error `"Cannot access a closed Stream"`.  I'm trying to avoid File based I/O keeping in memory only, but I haven't found a solution to avoiding this error.  An exception is also thrown on `Console.WriteLine($"Upload complete, item ID: {uploadResult.ItemResponse.Id}");` because ItemResponse appears to be null.

Any recommendation to get around this while using MemoryStream?

To recreate just change this in the example:
`using (var fileStream = System.IO.File.OpenRead(filePath))`
to something like this
`using (MemoryStream memoryStream = new MemoryStream(fileBytes))`
where fileBytes is of type byte[].

**Comment by andrueastman** [comment]
> Console.WriteLine($"Upload complete, item ID: {uploadResult.ItemResponse.Id}");

According to the [docs](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#example-final-upload-to-the-message) for the outlook attachments, the upload of the final chunk will only return the Location header. So you should do this.

```cs
 Console.WriteLine($"Upload complete, item ID: {uploadResult.Location}");
```

Then you can use the location header to obtain the item itself to by making a call as shown in [step 4](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http#step-4-optional-get-the-file-attachment-from-the-outlook-item).

**Comment by andrueastman** [comment]
> However, due to that I encountered errors when trying to reference for updates on progress with the error "Cannot access a closed Stream"

Are you able to share more details/sample code on how you are trying to reference the updates?
