### ISSUE TITLE
Pagination doesn't work for child mail folder & confusing documentation

### ISSUE THREAD

**Issue by IB38** [microsoftgraph/msgraph-sdk-dotnet#706]
### Expected behavior
I was expecting MailFolder.ChildFolders pagination throught NextPageRequest to work.

### Actual behavior
Pagination doesn't work, ChildFolders only returns 10 child folders and NextPageRequest is null, even tho i have 11 child folders.

Also im confused about SDK documentation, [here](https://docs.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&tabs=csharp) it gives following example:
```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var childFolders = await graphClient.Me.MailFolders["{id}"].ChildFolders
	.Request()
	.GetAsync();
```
But in Microsoft.Graph 3.6.0 + Microsoft.Graph.Core 1.20.1, the API of MailFolder.ChildFolders is different, there is no Request method, only CurrentPage and NextPageRequest properties.

### Steps to reproduce the behavior
My snippet:
```
public class MailFolderWrapper {
        public MailFolderWrapper(string folderId, GraphServiceClient graphClient)
        {
            this.graphClient = graphClient;

            graphFolder = graphClient.Me.MailFolders[folderId].Request().Expand("childFolders,messages").GetAsync().AsSync();
        }

        private MailFolderWrapper[] GetChildFolders()
        {
            var folderList = new List<MailFolderWrapper>();

            var folderPage = graphFolder.ChildFolders;
            folderList.AddRange(folderPage.Select(folder => new MailFolderWrapper(folder.Id, graphClient)));
            
            while (folderPage.NextPageRequest != null)
            {
                folderPage = folderPage.NextPageRequest.GetAsync().AsSync();
                folderList.AddRange(folderPage.Select(folder => new MailFolderWrapper(folder.Id, graphClient)));
            }

            return folderList.ToArray();
        }

        private GraphServiceClient graphClient;
        private GraphMailFolder graphFolder;
}
```

Here in GetChildFolders folderPage.NextPageRequest is always null, even tho i have 11 child folders.

What am i doing wrong?

**Comment by IB38** [comment]
Anyone?

**Comment by MIchaelMainer** [comment]
Pagination is not supported through the expansion. You have to page directly through each mailfolder. There isn't a deep folder traversal option. Please upvote this [feature request](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35061616-enable-deep-folder-expansion-for-microsoft-graph). 

`var page = await graphClient.Me.MailFolders[folderId].Request().GetAsync();`
