### ISSUE TITLE
Is there any way to watch/subscribe OOF (out of office) settings changes in SDK?

### ISSUE THREAD

**Issue by Code2Life** [microsoftgraph/msgraph-sdk-dotnet#709]
Hi, I'm developing an app to sync user's status, so I want to get realtime OOF state, I know calendar events (include OOO event) could be subscribed, but **how about mailbox settings** (automatic replies), could it be watched/subscribed and got push notifications in realtime ?

![image](https://user-images.githubusercontent.com/14833440/83742272-cc82a380-a68b-11ea-8f71-56a46b59c300.png)

**Comment by MIchaelMainer** [comment]
Mailbox setting change notifications are not a currently (supported resource[)[https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#supported-resources] for change notifications. You will need to create a polling mechanism for this. You can create or support a feature request for this at (Microsoft Graph User Voice)[https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests].
