### ISSUE TITLE
[Client bug]: Owners and Members collection not populated

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/msgraph-sdk-dotnet#711]
**Describe the bug**

When the query parameters are provided to expand or select members and owners, the response payload has the data, but the `Owners` and `Members` collections of the following classes are not populated.
1. IGraphServiceGroupsCollectionPage
1. IGroupDeltaCollectionPage
 
**To Reproduce**
Executed the following two lines of code and captured responses using Fiddler and double checked using GE.

`groupspage = await _graphServiceClient.Groups.Request().Expand("members").GetAsync();
`
which resulted in the following call

`https://graph.microsoft.com/beta/groups?$expand=members
`
and for delta query

`await _graphServiceClient.Groups.Delta().Request().Select($"Id,DisplayName,MailNickname,MailEnabled,SecurityEnabled,OnPremisesSamAccountName,AllowExternalSenders,Visibility,CreatedDateTime,GroupTypes,Classification,Description,preferredDataLocation,members,owners").GetAsync();`

which resulted in the following call

`https://graph.microsoft.com/beta/groups/microsoft.graph.delta?$select=Id,DisplayName,MailNickname,MailEnabled,SecurityEnabled,OnPremisesSamAccountName,AllowExternalSenders,Visibility,CreatedDateTime,GroupTypes,Classification,Description,preferredDataLocation,members,owners`

Captured the response 

**Expected behavior**
I was expecting that the Groups extracted from IGraphServiceGroupsCollectionPage and IGroupDeltaCollectionPage would have their members, owners or both populated as the response contains those collections. But this is not the case.

This means a round trip is required for SDK users to fetch the members and owners seperately

**Screenshots**

**Client version**

"Microsoft.Graph" version="3.6.0"
"Microsoft.Graph.Auth" version="1.0.0-preview.4" 
"Microsoft.Graph.Beta" version="0.18.0-preview" 
"Microsoft.Graph.Core" version="1.20.1" 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] N/A

**Additional context**

**Comment by peombwa** [comment]
The SDK returns owners and members of a group as `IGroupOwnersCollectionWithReferencesPage` and `IGroupMembersCollectionWithReferencesPage`. These are collection of `DirectoryObject` that can be casted to any derived type of `DirectoryObject` e.g `User`.
``` cs
var groups = await _graphServiceClient.Groups.Request().Expand("members").GetAsync();
foreach (var group in groups)
{
        // Do stuff.
	foreach (var member in group.Members)
	{
		if (member.ODataType.Contains("microsoft.graph.user")){
			var user = member as User;	
		}
                // Do stuff.
	}
}
```

 Also, which permission(s) are you using to make the call?

**Comment by kalyankrishna1** [comment]
thanks
