### ISSUE TITLE
SharePoint Search - Last Modified Date in Graph Response is not updated

### ISSUE THREAD

**Issue by mahesh2005** [microsoftgraph/msgraph-sdk-dotnet#714]
**Describe the bug**
I have a sharepoint online tenant. I am using Graph to search for sites with a keyword. I am using the last modified date in the response to identify my sites that have been recently modified.
Following query is used to search for sites:

`https://graph.microsoft.com/v1.0/sites?search='testSite'`

i get the correct sites in the response, but the problem is that the last modified date is incorrect.
Ideally the last modified date should have had 2020-06-08 date because i added and modified few documents, add lists and libraries and also updated indexed property bag values on 2020-06-08 but still graph response displays an old date.

This is the response i got, check the lastModifiedDate, it is not showing my current modified date :
```
{
            "createdDateTime": "2020-05-26T18:25:47Z",
            "id": "xxyyzz.sharepoint.com,400f88c1-c370-4940-acff-b9337500198f,ffc2a00a-ac69-4ea8-8c0b-de7ae3ace9c2",
            "lastModifiedDateTime": "2020-06-04T14:38:52Z",
            "name": "testSite abc1",
            "webUrl": "https://xxyyzz.sharepoint.com/sites/testsiteabc1",
            "displayName": "testSite abc1",
            "root": {},
            "siteCollection": {
                "hostname": "xxyyzz.sharepoint.com"
            }
        },
```
But now if I get the site directly using this query:

`https://graph.microsoft.com/v1.0/sites/xxyyzz.sharepoint.com,400f88c1-c370-4940-acff-b9337500198f,ffc2a00a-ac69-4ea8-8c0b-de7ae3ace9c2`

then i see the correct date in the response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites/$entity",
    "createdDateTime": "2020-05-26T18:25:47.513Z",
    "description": "",
    "id": "xxyyzz.sharepoint.com,400f88c1-c370-4940-acff-b9337500198f,ffc2a00a-ac69-4ea8-8c0b-de7ae3ace9c2",
    "lastModifiedDateTime": "2020-06-08T17:32:59Z",
    "name": "testsite abc1",
    "webUrl": "https://xxyyzz.sharepoint.com/sites/testsiteabc1",
    "displayName": "testsite abc1",
    "root": {},
    "siteCollection": {
        "hostname": "xxyyzz.sharepoint.com"
    }
}
```
Can anyone please let me know if this is a known issue? if yes, then any other way I can retrieve the last modified date of sites?

**Comment by MIchaelMainer** [comment]
@ificator

**Comment by mahesh2005** [comment]
Hi Team,
Is my observation valid? or am I using the wrong Graph API endpoint for my use case?

**Comment by darrelmiller** [comment]
Hi Mahesh,

Thank you for the detailed bug report.  The issue you raise appears to be an issue with the service.  As the SDK team, we are not able to support issues with the service.  The different options for reporting service issues are detailed on our [support page](https://developer.microsoft.com/en-us/graph/support).
