### ISSUE TITLE
Microsoft.Graph.Group doesn't have resourceProvisioningOptions property

### ISSUE THREAD

**Issue by mRWSEI** [microsoftgraph/msgraph-sdk-dotnet#716]
Hello, like topic says I can use postman to call
`https://graph.microsoft.com/v1.0/groups?$select=id,deletedDateTime,createdDateTime,description,displayName,mail,mailEnabled,mailNickName,visibility,**resourceProvisioningOptions**`

But there's no property inside Microsoft.Graph SDK
```
                var teamsG = await graphClient.Groups.Request().Top(998)
                    .Select(g => new
                    {
                        g.Id,
                        g.DeletedDateTime,
                        g.CreatedDateTime,
                        g.Description,
                        g.DisplayName,
                        g.Mail,
                        g.MailEnabled,
                        g.MailNickName,
                        g.Visibility,
                        **g.ResourceProvisioningOptions**
                    });
                g.Classification,
                g.Mail, g.MailEnabled, g.MailNickname, g.OnPremisesLastSyncDateTime, g.OnPremisesSecurityIdentifier,
                g.IsArchived, g.OnPremisesDomainName, g.OnPremisesNetBiosName, g.OnPremisesSamAccountName, g.OnPremisesProvisioningErrors //dodane
                g.OnPremisesSyncEnabled, g.PreferredDataLocation, g.RenewedDateTime, g.SecurityEnabled, g.SecurityIdentifier, g.Visibility
                }).GetAsync();

```
If I use 
`var teamsGroups = await graphClient.Groups.Request().Top(998)                    .Select("id,deletedDateTime,createdDateTime,description,displayName,mail,mailEnabled,mailNickName,visibility,resourceProvisioningOptions").GetAsync(); 
`
It will be returned as "additionalData" property

**Comment by ddyett** [comment]
this is an open type property basically meaning the SDK cannot know about resourceProvisioningOptions.  The only way to retrieve this is through the additionalData dictionary.
