### ISSUE TITLE
Graph SDK 3.x - Production Ready?

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/msgraph-sdk-dotnet#721]
All of the 3.x releases here on GitHub are marked as "Pre-release" but are *not* marked as such on the [published packages on NuGet](https://www.nuget.org/packages/Microsoft.Graph).

The major version number has been bumped, so I came here looking for some sort of documentation about upgrading - but didn't find any. If it is production ready, what are the changes?

If there aren't any breaking changes / it's "just" a version number change, 1 line in the readme would be appreciated mentioning this. 

Thank you 🙏

**Comment by MIchaelMainer** [comment]
3.x releases on GitHub are intended for production. We have a bug in our release task that automates the GitHub release. It should not be marked as pre-release.

**Comment by MIchaelMainer** [comment]
Next release will not occur with the pre-release designation.

**Comment by fowl2** [comment]
@MIchaelMainer any guidance on breaking changes/upgrading/migration?

**Comment by MIchaelMainer** [comment]
The issue with the erroneous pre-release designation is no longer present. [3.9.0](https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/3.9.0) went out without it. 

@fowl2 I realized that we didn't communicate (or at least I can't find it) the changes from the 1.x to 3.x update. This update was for updating the minimum .NET Standard and .NET Framework versions. net45 -->  net461 and netStandard1.3 --> netstandard2.0. Additionally, there were the following changes:
- class name change of ParticipantInfo class to InvitationParticipantInfo
- a change in enum order for GiphyRatingType
- CallRecordRequestBody became CallRecordResponseRequestBody

The diff is here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/compare/1.21.0...3.0.0

Unless you use those types, it should just work.
