### ISSUE TITLE
IGraphServiceUsersCollectionRequestBuilder does not include a Messages property of type IUserMessagesCollectionRequest

### ISSUE THREAD

**Issue by thomasrea0113** [microsoftgraph/msgraph-sdk-dotnet#724]
**Describe the bug**
`IGraphServiceUsersCollectionRequestBuilder` does not include a `Messages` property of type `IUserMessagesCollectionRequest`

**Expected behavior**
The property should exist. My guess is that all other 'Me' properties should exist as well, so that privilaged APIs can perform actions for other users.

**Client version**
3.8.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
My current workaround is as follows:

```csharp
            var queryOptions = new QueryOption[] { new QueryOption("$top", "100") };
            var newUri = client.Users.AppendSegmentToRequestUrl("<user_email>/messages");
            var mailRequest = new UserMessagesCollectionRequest(newUri, client, queryOptions).Select(m => new { m.Subject, m.Sender });
            var res = await mailRequest.GetAsync();
```

This works, but is cumbersome. Hopefully these properties can be added soon.

**Comment by pschaeflein** [comment]
Are you specifying the user for which you want messages in the request chain? If you are looking at `IGraphServiceUsersCollectionRequestBuilder`, then I'm guessing no.

```csharp
var m = await graphServiceClient.Users["userid"].Messages.Request().GetAsync();
\\                                     ^^^^^^^^
\\  index into the Users collection by id or upn  
```

**Comment by thomasrea0113** [comment]
Ah... I was indeed not. Glad there was a simple solution
