### ISSUE TITLE
graphClient.Sites[site.Id].Lists[list.Id].Subscriptions[sub.Id].Request().UpdateAsync(subscription); does not work

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-dotnet#725]
**To Reproduce**
1. create console app using "Microsoft.Graph" Version="3.8.0"
2. Look for a list with Subscription await graphClient.Sites[site.Id].Lists[list.Id].Subscriptions.Request().GetAsync()
3. Update the ExpirationDateTime 
4. See error:   <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>

**Expected behavior**
new ExpirationDateTime  assigend to the Subscription 

**Desktop (please complete the following information):**
 - OS: Windows 10 
**Additional context**
App running with a certificate and has all applicable API permissions ( there is only Subscription.Read.All)
The code:
` Subscription subscription = new Subscription
         {
                                  ExpirationDateTime = DateTimeOffset.Parse("2020-11-01T00:00:00.9356913Z")  
           };
       var newSub = await graphClient.Sites[site.Id].Lists[list.Id].Subscriptions[sub.Id].Request().UpdateAsync(subscription);`

**Comment by pschaeflein** [comment]
The maximum length of a subscription for a list is [4230 minutes (under 3 days)](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#maximum-length-of-subscription-per-resource-type). If you use an expiration date within that timeframe (instead of 2020-110-01), do you get a success?

**Comment by Ofer-Gal** [comment]
According to https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks#expiration it is 180 days maximum.
Other place https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/webhooks-reference-implementation#work-with-webhook-renewal say 6 months (180 days too)

Should I not use Graph for this?

**Comment by pschaeflein** [comment]
On the pages you reference, the URL for creating the webhook subscription is `/_api/web/lists('list-id')/subscriptions`. That is a SharePoint URL, not Microsoft Graph.

This is a candidate for the Graph.Community library. I've resisted coding it because I'm not sure how much it would be used.

Would be nice to get feedback on whether to add it to the community library from @baywet / @jthake-msft.

**Comment by baywet** [comment]
Thanks Paul for flagging this. See the [answer](https://stackoverflow.com/a/62642975/3808675) I provided earlier for the different API paths in the SDK.

As for SharePoint webhooks (on SharePoint rest API), we recommend using Microsoft graph and not a product specific API whenever possible. MS graph is the way forward as an API for Microsoft, it provides a number of enhancements and it is the API Microsoft is committed to support in the long run.

**Comment by Ofer-Gal** [comment]
So who do I notify that the [Update subscription](https://docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&tabs=http) does not work?
Using Graph explorer, (using Graph right?), `Get https://graph.microsoft.com/v1.0/sites/095d2e24-1326-4268-a698-18299d78437e/Lists/1901ee28-87ec-4b27-89c3-bbffa9a38f3c/Subscriptions/5eff9ca2-48d9-46f6-ac83-93c58c97c237` brings me the subscription I am familiar with (Call it SharePoint if you want )
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity",
    "clientState": "DPC Documents",
    "expirationDateTime": "2020-08-09T22:47:13.5815218Z",
    "id": "5eff9ca2-48d9-46f6-ac83-93c58c97c237",
    "notificationUrl": "https://ecghandlespwebhooks.azurewebsites.net/api/HandleHooks?code=TZe57ge0J2ZFIpFBrbnszpgM5zvy1bq4rqxRS01jtyj4ryYgFnrMJg=="
}
So I expect 
`PATCH {"expirationDateTime":"2020-10-09T22:47:13.5815218Z"} to https://graph.microsoft.com/v1.0/sites/095d2e24-1326-4268-a698-18299d78437e/Lists/1901ee28-87ec-4b27-89c3-bbffa9a38f3c/Subscriptions/5eff9ca2-48d9-46f6-ac83-93c58c97c237` to work but it returns 500 
and 
`PATCH {"expirationDateTime":"2020-10-09T22:47:13.5815218Z"} https://graph.microsoft.com/v1.0/Subscriptions/5eff9ca2-48d9-46f6-ac83-93c58c97c237 ` returns (as I expected)     "error": {
        "code": "ResourceNotFound",
        "message": "The object was not found.", 
If Microsoft   wants us to use graph, please fix it :-)
If I go the `/_api/web/lists('list-id')/subscriptions` , is it the same Id?
Thank you

**Comment by baywet** [comment]
If your intent is to use webhooks (which I believe it is given the fact you're using a client state and a notification URL), you should be doing ALL your subscriptions operations (Create, Update, Get) on `graphClient.Subscriptions` (`/subscriptions`) NOT `graphClient.Sites[site.Id].Lists[list.Id].Subscriptions` (`/sites/{id}/lists/{id}/subscriptions`). So you need to update your code at this point.

**Comment by Ofer-Gal** [comment]
So how do I create A web hook to a library in a site with graphClient.Subscriptions ?
Is https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http what you mean? where the site/list is the resource? 
If so, I will give it a try.

**Comment by baywet** [comment]
yep!

**Comment by pschaeflein** [comment]
@Ofer-Gal - keep in mind that the [maximum length of subscription](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#maximum-length-of-subscription-per-resource-type) is under 3 days. (You keep posting a payload with an expiration dateTime quite longer than that...)

**Comment by Ofer-Gal** [comment]
What is the value in under 3 days? That will result in people having to extend the ExpirationDateTime every other day.
Is this Microsoft's way to make us consume more Azure cycles? :-)

**Comment by baywet** [comment]
> What is the value in under 3 days? That will result in people having to extend the ExpirationDateTime every other day.
> Is this Microsoft's way to make us consume more Azure cycles? :-)

No it's our way to make sure you're still interested in getting notifications and we're not send notifications for no reason. :)

**Comment by Ofer-Gal** [comment]
This part of Graph is a double-edged sword for me. 
Now with `ChangeType = "created"` I get Invalid 'changeType' attribute: 'created'. 
with  `ChangeType = "updated"`  and `ExpirationDateTime = DateTimeOffset.Parse(DateTime.Now.AddMinutes(4220).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))`
I get Access denied. You do not have permission to perform this action or access this resource.]
I know my app registration has Sites.ReadWrite.All and much more in Graph and SharePoint. 

Every step you take there are issues. 
I am Going back to SharePoint REST for the subscription. Maybe Graph will mature in a year 👎 

Thanks for your help guys.

**Comment by baywet** [comment]
Just as a last attempt: are you sure you didn't give an app-only permission when you need a delegated one or vice versa?

**Comment by Ofer-Gal** [comment]
All my attempts are with the app-only credentials (certificate)

**Comment by baywet** [comment]
And the permissions you granted are for app only as well? (Just to double check)

**Comment by Ofer-Gal** [comment]
yes
