### ISSUE TITLE
GetActivitiesByInterval return "Item Not Found"

### ISSUE THREAD

**Issue by ahamedfazil** [microsoftgraph/msgraph-sdk-dotnet#726]
We are trying to get site activity by using graph and referred to this documentation - https://docs.microsoft.com/en-us/graph/api/itemactivity-getbyinterval?view=graph-rest-beta&tabs=csharp

Unfortunately we get Item not found as a response. Previously we used to get 500 Internal server error but now we get 404. I have tried this with various site in my tenant.

**Screenshots**
![image](https://user-images.githubusercontent.com/21005625/86123601-14a1b400-bada-11ea-8c96-dbb547be9e55.png)

I have tried the same with Graph Explorer and its still the same(item not found). :( 
![image](https://user-images.githubusercontent.com/21005625/86124101-d658c480-bada-11ea-9783-0244952a7245.png)

Any help on this is highly appreciated, thank you in advance.  

**Reference Issue**
https://github.com/microsoftgraph/microsoft-graph-docs/issues/6387

**Comment by gggjtgxing** [comment]
404 is expected if this item doesn't have any analytics data

**Comment by ahamedfazil** [comment]
How do we know whether the site has analytics data or not? Is there any way to check without the help of API?

**Comment by MIchaelMainer** [comment]
This doesn't appear to be a client library issue. Please post questions about the product and the service APIs to StackOverflow with the microsoft-graph tag.

**Comment by ahamedfazil** [comment]
The item has analytics data, when I checked from admin portal -> site usage. For the same date I can't get the value through the API.

**Comment by ahamedfazil** [comment]
The issue has been resolved, after providing the sites values in a way explained here -> https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta#id-property 
_(tenant-sharepoint-url, site collection GUID, site(web) GUID)_
![image](https://user-images.githubusercontent.com/21005625/87041011-d9963380-c1f1-11ea-9c4a-17f13c22ee35.png)

**Comment by shrirampophali** [comment]
I am getting Object reference error even after providing id like this.
