### ISSUE TITLE
The collection type 'Microsoft.Graph.IGraphServiceGroupsCollectionPage' on 'Microsoft.Graph.GraphServiceGroupsCollectionResponse.Value' is not supported."

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-dotnet#729]
**Describe the bug**
`var groups = await graphClient.Groups.Request().GetAsync();`

fails with "The collection type 'Microsoft.Graph.IGraphServiceGroupsCollectionPage' on 'Microsoft.Graph.GraphServiceGroupsCollectionResponse.Value' is not supported."

**To Reproduce**
1. Nuget Microsoft.Graph 3.8.0
2. Get a client with certificate
3. `var groups = await graphClient.Groups.Request().GetAsync();`

**Expected behavior**
A list of groups should return

**Desktop (please complete the following information):**
 - OS: windows 10 (Azure Function emulator)

BTW, I down graded to "Microsoft.Graph" Version="3.7.0" and my code works fine!! the issue is just in version 3.8.0
 
[AB#7247](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7247)

**Comment by wadstromdev** [comment]
Experiencing the same.

**Comment by Ofer-Gal** [comment]
3.8.0 is still the "Latest stable" 👎

**Comment by MIchaelMainer** [comment]
I'm not able to repro this. I'm using 3.8.0 and can make successfully make that call. Can you share with me a sanitized HTTP response capture?

I'm making the call using Linqpad and ClientCredential flow.
![image](https://user-images.githubusercontent.com/8527305/88696719-709b3080-d0b8-11ea-9704-08e8292bc91d.png)
Fiddler:
![image](https://user-images.githubusercontent.com/8527305/88696917-b6f08f80-d0b8-11ea-976e-5ef45e9579e4.png)

**Comment by magnello** [comment]
For what it is worth, I was receiving this same error querying Calendars and Contacts.  I was using the 2.0.0 Pre-release version of Microsoft.Grahp.Core.  When I swapped it out for the latest stable version 1.20.1 as shown in the capture, it worked fine.

**Comment by MIchaelMainer** [comment]
Microsoft.Graph.Core 2.0.0 prerelease will not work with the generated Microsoft.Graph. We will need to update Microsoft.Graph to no longer use Newtonsoft.Json (and start to use System.Text.Json) so that it works as expected.

**Comment by michael-hawker** [comment]
@MIchaelMainer is there a separate issue tracking the `System.Text.Json` migration? When is that expected to be completed?

We've moved to `System.Text.Json` for the Windows Community Toolkit, so our graph controls now would be pulling in both dependencies.

**Comment by andrueastman** [comment]
@michael-hawker For the service library we are tracking the migration here https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/80 and we should have preview packages of the service libraries pretty soon. 

I will close this issue since the 3.x.x versions of the service library is not compatible with versions 2.x.x of the core library. 3.x.x versions should be used with versions 1.x.x of the core package since those versions use Newtonsoft.Json.
