### ISSUE TITLE
Resource not found for the segment 'root:' when uploading file to OneDrive

### ISSUE THREAD

**Issue by saf-itpro** [microsoftgraph/msgraph-sdk-dotnet#730]
When working on [this tutorial][1] on `Uploading File to OneDrive` from Microsoft Graph OneDrive team, I'm getting the following error at the last line of the code shown below:

**Remarks**: There are some posts online with a related issue, (such as: [This][2], or [this][3], or [this][4] or [this][4] or [this][5]). But they all seem to have a different context or do not have a response.

**Question**: What could be the issue, and how can we resolve it
>>Resource not found for the segment 'root:'

**Relevant Code**:

    GraphServiceClient graphClient = ProviderManager.Instance.GlobalProvider.Graph;
    
    var picker = new Windows.Storage.Pickers.FileOpenPicker();
    ....
    picker.FileTypeFilter.Add("*");
    
    Windows.Storage.StorageFile file = await picker.PickSingleFileAsync();
    if (file != null)
    {
        // Application now has read/write access to the picked file
        // request 1 - upload small file to user's onedrive
    
      Stream fileStream = await file.OpenStreamForReadAsync();
      DriveItem uploadedFile = await graphClient.Me.Drive.Root
                                    .ItemWithPath(file.Path)
                                    .Content
                                    .Request()
                                    .PutAsync<DriveItem>(fileStream);
    }

  [1]: https://docs.microsoft.com/en-us/learn/modules/msgraph-access-file-data/5-exercise-upload-files-onedrive
  [2]: https://stackoverflow.com/q/44975760/1232087
  [3]: https://stackoverflow.com/q/42147060/1232087
  [4]: https://stackoverflow.com/q/61537747/1232087
  [5]: https://stackoverflow.com/q/35878044/1232087

**Comment by MIchaelMainer** [comment]
@jasonjoh

**Comment by jasonjoh** [comment]
Not sure off the top of my head, I didn't write that particular Learn module. @andrewconnell any ideas?

@saf-itpro did you try doing a GET /me/drive/root using [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) with this same user?

**Comment by saf-itpro** [comment]
@jasonjoh Per your suggestion, I tried GET /me/drive/root using Graph Explorer with this same user. And it did return the expected (json) output. The code I am referencing in the post above is in regard to `POST` (uploading file), and [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) does not have a such a `POST` demo under their `OneDrive` menu on the left pane.

**Comment by andrewconnell** [comment]
We didn't have any issues when we refreshed this module in the last cycle.

**Comment by srazasyed** [comment]
@saf-itpro I think, in you code, you want `.ItemWithPath(file.Name)` and NOT `.ItemWithPath(file.Path)`. Please note that `.ItemWithPath(file.Path)` is not the path to the file you're uploading, it is the destination path.

**Details**:
When uploading file you need to use either just the name of the file (if you are uploading it to the root folder of the `OndeDrive`) or if you want to upload it to a `OneDrive` folder (e.g., a builtin folder `Documents`, `Attachments`, or `Pictures`) then you'll you use the `URL safe drive path` (e.g., `/Documents/MyFile.txt`).

If you intend to upload the file to the root folder of `OneDrive`, in your code line `.ItemWithPath(file.Path)` replace `file.Path` with the name of the file you want uploaded (although the name does not have to be the same but most likely you would like to keep the same name as the name of the file you want uploaded from your host drive so you remember which file you had uploaded). If you want it uploaded to, say, `URL safe drive path` (e.g., `/Documents/`), then replace `file.Path` with `/Documents/MyFile.txt` where `MyFile.txt` would be whatever file name you have.

**Comment by saf-itpro** [comment]
@srazasyed Your suggestion worked (thank you).
