### ISSUE TITLE
DriveItem class question (subject of change or not ?)

### ISSUE THREAD

**Issue by a-martynov** [microsoftgraph/msgraph-sdk-dotnet#731]
We extremely use Microsoft.Graph.DriveItem class.

We request files by this code first:
`IDriveSharedWithMeRequest driveItemsRequest = _graphClient.Client.Me.Drive.SharedWithMe().Request(queryOptions);`
and by this
```
IDriveItemChildrenCollectionRequest request = _graphClient.Client.Sites[siteId].Lists[listId].Items[itemId].DriveItem
                    .Children.Request().Expand("listItem($expand = fields)");
```

then, using this dictionary inside, we parse ListId(2a044c52-6558-43bf-8111-a373e6edbda5) and ItemId (21006)

DriveItem.ListItem.AdditionalData["fields@odata.context"]=
"https://graph.microsoft.com/v1.0/$metadata#sites('7e405b95-e0dd-482d-97f7-b04ea6b57ed0')/lists('2a044c52-6558-43bf-8111-a373e6edbda5')/items('21006')/driveItem/children('01MULKCAVQSFNWRJ6JKJC3EQKBC326BPQ2')/listItem/fields/$entity]}"

we save them in our DB to get this file later  by this code:
```
var listItemsRequest = _graphClient.Client.Sites[siteId]
                                                       .Lists[listId]
                                                       .Items[itemId]
                                                       .Request(new List<QueryOption>()
                                                                    {
                                                                        new QueryOption("expand", "driveItem"),
                                                                    });
```

Its critical part of our application, so can we expect AdditionalData["fields@odata.context"] string with ids will be here in future ?

**Comment by MIchaelMainer** [comment]
This is a great question to ask on StackOverflow. Please tag your post with [microsoft-graph] and [onedrive].

**Comment by a-martynov** [comment]
https://stackoverflow.com/questions/62847387/microsoft-graph-sdk-is-driveitem-class-subject-to-change

**Comment by MIchaelMainer** [comment]
Gave an answer on the post. It is unlikely to change. Note, I'm not an expert on that API.

**Comment by a-martynov** [comment]
> Gave an answer on the post. It is unlikely to change. Note, I'm not an expert on that API.

May be you now the place where I can ask authors of these APIs ?

**Comment by MIchaelMainer** [comment]
@a-martynov StackOverflow is the best place to post these type of questions.
