### ISSUE TITLE
Removing application owner results in "Write requests are only supported on contained entities"

### ISSUE THREAD

**Issue by smaine** [microsoftgraph/msgraph-sdk-dotnet#736]
**Describe the bug**
When attempting to remove an Application Owner by ID using the following code against version 3.8 of the Microsoft.Graph SDK for .NET, requests to remove the owner relationship fail with the server error 'Write requests are only supported on contained entities'.

```
IDirectoryObjectWithReferenceRequest request = TargetTenantGraphClient.Applications[application.Id].Owners[ownerToRemove.Id].Request();
                await request.DeleteAsync().ConfigureAwait(false);
```
Looking at this in the debugger, it looks like the SDK is generating delete requests of the form
`DELETE /applications/{id}/owners/{id}`

However, according to the REST API docs for the Remove Owner operations at https://docs.microsoft.com/en-us/graph/api/application-delete-owners?view=graph-rest-1.0&tabs=http, the correct request should have a '$ref' segment at the end of the URI, like so:

```
DELETE /applications/{id}/owners/{id}/$ref
```

 
[AB#7250](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7250)

**Comment by darrelmiller** [comment]
Hey Steve,

The Reference property should give the URL you are looking for.

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.Applications["{id}"].Owners["{id}"].Reference
	.Request()
	.DeleteAsync();
```

**Comment by andrueastman** [comment]
@smaine Did you try out the suggestion? Did it work out for you?
