### ISSUE TITLE
Exception is not helpful: "NotFound"

### ISSUE THREAD

**Issue by kevonh** [microsoftgraph/msgraph-sdk-dotnet#737]
I am trying to get a list of channels from Teams.
The TenantID, ClientID, and ClientSecret are copy/paste from another application which DOES work.  I've checked permissions on my app and it has the correct permissions, and is authorized.  

It would be nice if the exception had a bit more information about exactly what the problem was.  

The exception happens at client.Teams[TenantID].Channels.Request() 
 
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Code: NotFound
Message: Not Found
Inner error:
	AdditionalData:
	date: 2020-07-13T21:25:49
	request-id: 2bcbf6c5-9f0c-4ef5-b28e-2244ebf5d9fc
ClientRequestId: 2bcbf6c5-9f0c-4ef5-b28e-2244ebf5d9fc
)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TeamsNotification.Program.Main(String[] args) in D:\Code\Spikes\TeamsMessageSend\TeamsNotification\TeamsNotification\Program.cs:line 31

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ServiceException: Code: NotFound
Message: Not Found
Inner error:
	AdditionalData:
	date: 2020-07-13T21:25:49
	request-id: 2bcbf6c5-9f0c-4ef5-b28e-2244ebf5d9fc
ClientRequestId: 2bcbf6c5-9f0c-4ef5-b28e-2244ebf5d9fc

The entirety of the code:

			namespace TeamsNotification
			{
				class Program
				{
					static void Main(string[] args)
					{

						string TenantID = "SECRET";
						string ClientID = "SECRET";
						string ClientSecret = "SECRET";

						IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
								.Create(ClientID)
								.WithTenantId(TenantID)
								.WithClientSecret(ClientSecret)
								.Build();

						ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

						GraphServiceClient client = new GraphServiceClient(authProvider);

						var channels = client.Teams[TenantID].Channels.Request().GetAsync().Result;
						foreach (var c in channels)
							Console.WriteLine(c.DisplayName);

						Console.ReadLine();
					}
				}
			}

**Comment by ddyett** [comment]
it seems like you may have incorrectly put the TenantID as the team.

var channels = client.Teams[**TenantID**].Channels.Request().GetAsync().Result;

**Comment by kevonh** [comment]
I'll take that.  How does one find the TeamID?  The ultimate goal is to send a message to a channel.  Reading the docs, it seems that you have to get a TeamID and a ChannelID in order to do this, but there are no examples on how to get a list of teams using the GraphServiceClient.

I've tried:
var teams = client.Teams.Request().GetAsync().Result;
this returns a 404 error.

I have used successfully:
var groups =  client.Groups.Request().GetAsync().Result;
but when inspecting the result, all of the groups.Team objects are NULL. 

If I use the result from the above, find the ID of the group which matches the name of the Team I'm trying to message to and substitute that in the next call to get the channel id, this actually does return a list of channels.

var channels = client.Teams[teamId].Channels.Request().GetAsync().Result.ToList();

But, then when I extract the Channel ID

var channelID = channels[0].Id;
and send it to the channel...

var chatMessage = new ChatMessage
{
	Body = new ItemBody
	{
		ContentType = BodyType.Html,
		Content = "Hello World!"
	}
};
client.Teams["{teamId}"].Channels["{channelId}"].Messages.Request().AddAsync(chatMessage);

nothing happens.
