### ISSUE TITLE
Timezone gets lots in translation in user events.

### ISSUE THREAD

**Issue by cdibbs** [microsoftgraph/msgraph-sdk-dotnet#741]
When creating all-day events and then immediately finding them, the events have the correct, original times (midnight) for Start and End but the zone comes back as "UTC" instead of the original "Central Standard Time."

```c#
result = _client.Users[CurrentUser.Id].Events.Request().AddAsync(ev);
```

Hovering over the `ev` variable's `End` property above in debug mode, I see:

![image](https://user-images.githubusercontent.com/314147/87809414-fa2d4180-c820-11ea-955e-8d789ef5f76d.png)

And when I query for the event (confirming its the same event by its id) like so, the timezone has changed, but not the time.

```c#
var userEvents = _client.Users[CurrentUser.Id].Events;
var results = (await userEvents
                    .Request(options)
                    .GetAsync()).CurrentPage.ToArray();
```
![image](https://user-images.githubusercontent.com/314147/87809163-855a0780-c820-11ea-8206-40bc15a58931.png)

This is with the latest 3.8.0 of the SDK, and the project is in .NET Core 3.1.

**Comment by darrelmiller** [comment]
I wasn't able to repro this behavior from the service using Graph Explorer. The TimeZone would change to UTC, but also the DateTime changed. The original timezone is stored in originalTimezone.

**Comment by MIchaelMainer** [comment]
I can't repro either.

**Scenario 1 with DateTime set as Zulu time**

If I submit this request body:

```

{"subject":"My event","start":{"dateTime":"2020-07-23T14:24:31.367Z","timeZone":"Pacific Standard Time"},"end":{"dateTime":"2020-07-23T14:54:31.367Z","timeZone":"Pacific Standard Time"}}
```

I get this in the create response:

```
    "start": {
        "dateTime": "2020-07-23T14:24:31.3670000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2020-07-23T14:54:31.3670000",
        "timeZone": "UTC"
    },
```

**Scenario 2**

If I set this request body on creation:

```
{"subject":"My event","start":{"dateTime":"2020-07-23T14:24:31.367","timeZone":"Pacific Standard Time"},"end":{"dateTime":"2020-07-23T14:54:31.367","timeZone":"Pacific Standard Time"}}
```

I see this in the create response:

```
    "start": {
        "dateTime": "2020-07-23T14:24:31.3670000",
        "timeZone": "Pacific Standard Time"
    },
    "end": {
        "dateTime": "2020-07-23T14:54:31.3670000",
        "timeZone": "Pacific Standard Time"
    },
```

The following client code is the same as scenario 2:

```csharp
	var appointment = new Event();
	appointment.Subject = "MyEvent from lib";
	appointment.Start = new DateTimeTimeZone();
	appointment.Start.DateTime = "2020-07-23T14:24:31.367";
	appointment.Start.TimeZone = "Pacific Standard Time";
	appointment.End = new DateTimeTimeZone();
	appointment.End.DateTime = "2020-07-23T14:54:31.367";
	appointment.End.TimeZone = "Pacific Standard Time";

	var result = client.Users["adelev@M3651111.onmicrosoft.com"].Events.Request().AddAsync(appointment);
```

When I get the item created in scenario 2, TimeZone is UTC and the DateTime has changed to reflect that fact,just like what Darrel found.  Same behavior if I set the end DateTime to midnight.

**Comment by cdibbs** [comment]
@darrelmiller and @MIchaelMainer thanks for looking into this. It looks like you might be missing two parts, `isAllDay: true` and time == midnight. I was able to replicate this using the Graph Explorer with a JSON body as follows:

```json
{
    "subject": "My event",
    "isAllDay": true,
    "start": {
        "dateTime": "2020-07-24T00:00:00",
        "timeZone": "Central Standard Time"
    },
    "end": {
        "dateTime": "2020-07-25T00:00:00",
        "timeZone": "Central Standard Time"
    }
}
```

I `POST`ed to `https://graph.microsoft.com/v1.0/me/calendar/events` and the returned values seemed correct. Then, I copied the `id` from the response and used that to create a `GET` request to `https://graph.microsoft.com/v1.0/me/calendar/events/{id}`. In that, I get original start and end time zone == UTC (not true), and:

```json
    "start": {
        "dateTime": "2020-07-24T00:00:00.0000000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2020-07-25T00:00:00.0000000",
        "timeZone": "UTC"
    }
```

Hope that helps. Am I missing something? Thanks, again.

**Comment by MIchaelMainer** [comment]
@cdibbs Did you set prefer header on the GET?
https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http#support-various-time-zones

**Comment by cdibbs** [comment]
Nope, in Graph Explorer I didn't. And in the SDK of course I didn't think about headers (I assumed it would manage that).

I just reran it with that header in Graph Explorer, and it changed both the original time zone, and the start/end ones. No matter what timezone I use, it stays at midnight in that time zone. That could be what hides this bug from clients like outlook.

**Comment by MIchaelMainer** [comment]
@cdibbs This is likely an intended behavior since this is an all day event. I think the behavior is if I make an event `allday = true` for a date, then it is all day in my time regardless of timezone, as it will be all day in my coworkers calendar in Kenya, regardless of timezone. There isn't an accounting for timezone. That way Christmas is set as the 25th in PST as well as EAT time zone. If we need that an event is AllDay in one time zone, and those same 24 hours are mirrored in Kenya,  then set AllDay to false, and then set the start and end time like you did.

**Comment by cdibbs** [comment]
@MIchaelMainer That makes sense to me, I think, minus the originalStart/EndTimeZone fields changing. Beyond that, from the perspective of how I've been using the SDK so far, it seems like it would be nice if an Outlook-like behavior were the default (automatically sending a header for the local timezone), but I don't know quite enough to request that as a feature.

Thanks for all your help!
