### ISSUE TITLE
ConfidentialClientApplicationBuilder should work anywhere

### ISSUE THREAD

**Issue by MhAllan** [microsoftgraph/msgraph-sdk-dotnet#742]
I have registered Client app to Manager users of Azure AD B2C. Now I want to use that app to manage users through a UWP application. but this code is not working

```csharp
 var app = ConfidentialClientApplicationBuilder
                        .Create(config.ClientId)
                        .WithClientSecret(config.ClientSecret)
                        .WithTenantId(config.Tenant)
                        .Build();
```

Throwing `'Confidential Client flows are not available on mobile platforms or on Mac`

I should be able to do whatever I want even this exposes a secret in devices, that should be my decision.

### Workaround
Create your own `IAuthenticationProvider` and refresh token manually using REST calls

**Comment by MIchaelMainer** [comment]
The confidential client flow is not intended to be used on a client. This is by design. You can ask questions like this at https://docs.microsoft.com/en-us/answers/topics/azure-ad-authentication.html.
