### ISSUE TITLE
Could a way to send a draft message without saving to the "Sent Items" folder be added?

### ISSUE THREAD

**Issue by damptoe** [microsoftgraph/msgraph-sdk-dotnet#743]
The "saveToSentItems" flag to prevent saving sent emails to the "Sent Items" folder looks like it is only available from the "sendMail" endpoint at the moment.

When I use Graph, I don't use the "sendMail" endpoint because the only way to get around the attachment file size limit is to create a draft and add attachments smaller than 3 MB to it or create an upload session for files larger than 3 MB.

However, when you call the "send" endpoint for messages, it will always save a copy to the "Sent Items" folder.

You have to go through the hassle of setting an immutable ID on the draft before sending it and attempt to delete the message afterwards. Then you have to do another workaround to prevent deleting the message before it's sent because there's a slight delay before it actually gets sent.

Could the "saveToSentItems" flag just be added to the "send" endpoint as well? It seems too difficult to achieve such a simple task for what seems to be the standard endpoint for sending emails due to the "sendMail" endpoint's limitations.

**Comment by MIchaelMainer** [comment]
Can you please make this feature request in the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests)?

**Comment by troplin** [comment]
@MIchaelMainer The User Voice is no longer available, can this ticket be reopened?
