### ISSUE TITLE
GraphServiceClient can't find Identity with plus sign (+) in the IssuerAssignedId

### ISSUE THREAD

**Issue by MhAllan** [microsoftgraph/msgraph-sdk-dotnet#744]
In my **Azure AD B2C**, I created users where phone numbers are their usernames. Here is how the ```ObjectIdentity``` looks like

```csharp
 var identity = new ObjectIdentity
            {
                Issuer = "my AD B2C domain",
                IssuerAssignedId ="+1 xxxx", //the phone number or anything has (+)
                SignInType = "userName"
            };
```

**MSAL** can acquire token using username and password for this identity.

**But**  ```GraphServiceClient``` can't find such a user when I try to find if the user with this phone number is registered or not.

So this code will return null

```csharp
var graph = new GraphServiceClient( ... )
 var filter = $"Identities/any(x:x/Issuer eq '{b2cDomain}' and x/IssuerAssignedId eq '{phoneNumber}')";
var req = await graph.Users.Request().Filter(filter).GetAsync(ct);
```

Not only **MS Graph** fails, but also **AD Graph** fails, so this filter still doesn't return the user using AD Graph REST calls
```csharp
var filter = "$filter=signInNames/any(x:x/value eq '{username}') or otherMails/any(x:x eq '{username}')";
```

I tried to use ```emailAddress``` instead of ```userName``` when creating the user. same issue happened. Whenever there is plus sign (+) in the email address, filters can't find the user even though you can sign in.

**To Reproduce**
1. Set up Azure AD B2C and Managing client App
2. Use GraphServiceClient to create user with identity that has a plus sign (+)
3. Make sure MSAL can aquire token by username and password for the user you just created
3. Use GraphServiceClient to find that user using this filter:  $"Identities/any(x:x/Issuer eq '{b2cDomain}' and x/IssuerAssignedId eq '{phoneNumber}')";
4. MSAL will sign in, but GraphServiceClient can't find the user

**Expected behavior**
GraphServiceClient to return the user that it's identity has plus sign

 
[AB#7253](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7253)

**Comment by MIchaelMainer** [comment]
Can you try URL encoding the '+' character in the IssuerAssignedId and let us know whether that works?

**Comment by andrueastman** [comment]
@MhAllan Did the suggestion work out for you?

**Comment by MhAllan** [comment]
The suggestion has nothing to do with my problem, please re-open
