### ISSUE TITLE
IUserRequest.Expand is not working

### ISSUE THREAD

**Issue by MhAllan** [microsoftgraph/msgraph-sdk-dotnet#745]
**Describe the bug**
Using Azure AD B2C, This code
```csharp
_graph.Users[UserId].Request().Expand(x => x.Extensions).GetAsync()
```
throws error **Unexpected exception returned from the service**. It will work if you remove Expand.

**Comment by ddyett** [comment]
RawResponseBody [string]:"{\"@odata.context\":\"https://graph.microsoft.com/v1.0/$metadata#users(extensions())/$entity\"{\r\n  \"error\": {\r\n    \"code\": \"InternalServerError\",\r\n    \"message\": \"The entity instance value of type 'microsoft.graph.user' doesn't have a value for property 'id'. To compute an entity's metadata, its key and concurrency-token property values must be provided.\",\r\n    \"innerError\": {\r\n      \"date\": \"2020-07-23T19:54:44\",\r\n      \"request-id\": \"3507c77c-ccb5-45e1-a633-5f282d01f5c6\"\r\n    }\r\n  }\r\n}"

**Comment by MIchaelMainer** [comment]
This issue repros for B2B. The response is a 500 ISE. This expansion may not be supported in this form on the user. I'm not seeing an example in this topic:

https://docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&tabs=http

GET /v1.0/users/adelev@M36.onmicrosoft.com?$expand=extensions 

If we there is documentation that supports this scenario, then this is a service bug. Otherwise, I suggest you open a feature request on https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests.

**Comment by MIchaelMainer** [comment]
Closing due to no response. Please reopen if you think this is still an issue with the client library.

**Comment by RaphaelSilv** [comment]
FWIW I am facing the same issue at the moment.

**Comment by RaphaelSilv** [comment]
The following piece of code gets rid of the internal error/exception, however, does not return the Extension fields as expected as the **Extension [IUserExtensionsCollectionPage]** property does not return any of the extension attributes my user have.

```c#
var user = await graphClient.Users["{user-id}"]
                .Request()
                .Select(u => new {
                    u.DisplayName,
                    u.JobTitle,
                    u.GivenName,
                    u.PostalCode,
                    u.Identities,
                    u.Id // My assumptions is that you must select the user Id before use Expand
                })
                .Expand(x => x.Extensions)
                .GetAsync();
````

- Related to:  https://stackoverflow.com/questions/70682313/graphserviceclient-select-control-not-working-as-expected

--
@MIchaelMainer can this issue be reopened?

**Comment by MIchaelMainer** [comment]
@RaphaelSilv  
I don't think expanding extensions is supported on this API (both v1.0 and beta endpoints). I think you'll need to make two calls: 1) for the user information, and 2) to get the extensions available on a user.

There are quite a few relationships that are not supported. Best way to validate is to check the documentation to see if it shows examples. In this case I find no examples, so it is safe to assume that it is not supported.

That may leave you asking: why is the API in the client library? We generate library signature from metadata and the metadata isn't rich enough to describe what is and isn't supported in different scenarios.
