### ISSUE TITLE
Will IConfidentialClientApplication auto refresh access token?

### ISSUE THREAD

**Issue by nvliumang** [microsoftgraph/msgraph-sdk-dotnet#751]
Hi,

I am using client credentials flow to get token to access MS graph api. so I choose  IConfidentialClientApplication as the provider of [GraphServiceClient.](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#ClientCredentialsProvider) 

![image](https://user-images.githubusercontent.com/24580166/88907658-772dd180-d28b-11ea-81f9-30e1dd4df5c0.png)

But There is a question, if the token gets expired, will it auto refresh? I know auth code flow will return refresh token but client credentials flow does not. 

Can you help to explain it?

**Comment by ddyett** [comment]
@darrelmiller do you know this one?

**Comment by MIchaelMainer** [comment]
When the token expires, a new token is acquired without a refresh token when using client credential flow. It will auto-refresh.
