### ISSUE TITLE
How to get email address for user?

### ISSUE THREAD

**Issue by sam-wheat** [microsoftgraph/msgraph-sdk-dotnet#756]
The email address I want to obtain is the one where the verification token is sent.

Steps to reproduce:

Log into Azure portal.
Go to the application you use for validating users.
Go to API permissions, make sure User.ManageIdentities.All, and User.ReadWrite.All permisssions are present.

Go to your web application and log in, creating a new user:

		const auth: MSAL.Configuration = new MSALConfig();
        const userAgentApplication = new MSAL.UserAgentApplication(auth as MSAL.Configuration);

        userAgentApplication.loginPopup(AppConfig.loginScopes).then(response => {
            globalSettings.UserName = response.account.name;
            globalSettings.UserID = response.account.accountIdentifier;
            globalSettings.Token = response.idToken;
            localStorage.setItem('globalSettings', JSON.stringify(globalSettings));
            result = true;

        }).catch(err => {
            alert('The login attempt was not successful.')
        });

Note the UserID of the user that is created (In preparing this question I used my GitHub credentials to create a new user).

Login to Azure Portal, select B2C tenant.
Locate the user created in the steps above.

Note that users email address is shown as User Principal Name.  This appears to be incorrect.

In the profile page note the email address is blank.

Note also that alternate email is set to the users primary email address.  This also appears to be incorrect.

Click the Authentication Methods menu item.  On the Authentication Methods page note email is blank.

Retrieve the user using `GraphServiceClient`.

		GraphServiceClient client = GetGraphServiceClient();
		User user;
		
		try
		{
			user = await client.Users[userID].Request().GetAsync(); // mail is null
			user = await client.Users[userID].Request().Select(x => x.Mail).GetAsync(); // mail is null
			user = await client.Users[userID].Request().Select(x => x.Identities).GetAsync(); // Identities do not show email address
		}
			
Note mail is always null even though [this document](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http) indicates it is returned as one of the default properties: "Getting a user returns a default set of properties only ... mail, ...".
Identities do not reflect email address:

		Issuer	"github.com"	string
		IssuerAssignedId	"16885210"	string
		ODataType	"microsoft.graph.objectIdentity"	string
		SignInType	"federated"	string

			 
[AB#7255](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7255)

**Comment by MIchaelMainer** [comment]
@cmatskas, Darrel said you may enjoy this GitHub issue :)

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/755

**Comment by sam-wheat** [comment]
>  @cmatskas, Darrel said you may enjoy this GitHub issue :)

This is a fair question and one that I think deserves an answer.  If I am missing something obvious please let me know because I still find the way the data is presented to be confusing.
