### ISSUE TITLE
conversationId filter

### ISSUE THREAD

**Issue by iainlennox** [microsoftgraph/msgraph-sdk-dotnet#757]
in javascript there is this .filter(`conversationId eq '${id}'`)

How can that be done with dot net?

.Filter("conversationId eq " + myMessageID) 

Thanks 
[AB#7256](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7256)

**Comment by MIchaelMainer** [comment]
Have you tried: `await client.Me.Messages.Request().Filter($"conversationId eq '${id}'").GetAsync();`

**Comment by iainlennox** [comment]
Thanks, query now runs but wont accept messageId, says its malformed.

my messageId: "AAQkAGFiZTk0MWMyLWNjZGItNDMxMi1hNzQyLTdmNDFmNzdiZTllZgAQAPoEb-CARORBssfDrjHxHLA="

{"Code: ErrorInvalidIdMalformed\r\nMessage: Id is malformed.\r\nInner error:\r\n\tAdditionalData:\r\n\tdate: 2020-08-13T09:59:40\r\n\trequest-id: e9ee5773-dc83-49b1-9dfd-a76a666768ab\r\nClientRequestId: e9ee5773-dc83-49b1-9dfd-a76a666768ab\r\n"}

**Comment by MIchaelMainer** [comment]
ConversationId is a different than message ID. You will need to get the conversationId from a message.

**Comment by andrueastman** [comment]
Closing this as this is confirmed to be working on the latest version (v4.3.0) as follows

```cs
            var conversationId = "{conversationId}";
            var messages = await graphServiceClient.Me.Messages.Request().Filter($"conversationId eq '{conversationId}'").GetAsync();
```
