### ISSUE TITLE
Question: How to get profile photo binary using SDK?

### ISSUE THREAD

**Issue by mhomol** [microsoftgraph/msgraph-sdk-dotnet#759]
I am asking here because I can't find this information anywhere.  How can I pull the binary for the profile photo in the graph sdk?

I know how to do this from the API:
https://graph.microsoft.com/v1.0/users/87d349ed-44d7-43e1-9a83-5f2406dee5bd/photo/$value

But I cannot figure out how to put this together in the SDK.  Hopefully I'm just missing something simple.  Any help you can provide would be amazing!

This code is what I originally had for getting the `ProfilePhoto` but that is just the metadata:

```csharp
return await client.Users[userId].Photo.Request().GetAsync();
```

I've played around with it alot but can't figure out how to modify the `Request()` to place $value in there as well as getting it to return the binary instead.

Thank you in advance.

**Comment by MIchaelMainer** [comment]
You want to use this: `var result = await client.Users[userId].Photo.Content.Request().GetAsync();`

**Comment by TejendraPrasad** [comment]
@MIchaelMainer -

We are using Application token to get user details by Email.. and we need user photo as well to show in our application.

var profilePhoto = await _graphServiceClient.Users[userId].Photos.Request().GetAsync();

or

var profilePhoto = await _graphServiceClient.Users[userId].Photo.Content.Request().GetAsync()


We still get below error



 "code": "ResourceNotFound",

  "message": "Resource could not be discovered.",

Thank you!
Tej

**Comment by MIchaelMainer** [comment]
@TejendraPrasad Are you certain that the user has a photo? I also don't know whether this will work if the account a consumer account. 

https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0

**Comment by TejendraPrasad** [comment]
@MIchaelMainer  thank you for response.

Yes, user has a photo in MS teams, Sharepoint online ... what is consumer account? My understand is we are part of enterprise and its enterprise account not public exposed AD.

My Sample Code

            `IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder.Create(clientId: _clientId) .WithClientSecret(clientSecret: _clientSecret).WithAuthority(AadAuthorityAudience.AzureAdMyOrg, true).WithTenantId(tenantId: _tenantId).Build();

            ClientCredentialProvider authenticationProvider = new ClientCredentialProvider(confidentialClientApplication);

            _graphServiceClient = new GraphServiceClient(authenticationProvider);

             var users = await _graphServiceClient.Users.Request().Filter($"mail eq '{emailAddress}'").GetAsync();`

Get User iD from Object - here also profile object is null

` var profilePhoto = await _graphServiceClient.Users[userId].Photos.Request().GetAsync();`

Again Error as stated in previous comment.

So do i need to use HTTP requested as stated in https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0 and not Graphclient SDK?

thank you!
Tej
