### ISSUE TITLE
How to create Team with team members and team name ?

### ISSUE THREAD

**Issue by dnyaneshwar-surywanshi** [microsoftgraph/msgraph-sdk-dotnet#761]
below is my Code 

Team newTeam = new Team()
{
GuestSettings = new TeamGuestSettings
{
AllowCreateUpdateChannels = false,
AllowDeleteChannels = false,
ODataType = null
},
MemberSettings = new TeamMemberSettings
{
AllowCreateUpdateChannels = false,
ODataType = null
},
MessagingSettings = new TeamMessagingSettings
{
AllowUserEditMessages = true,
AllowUserDeleteMessages = true,
ODataType = null
},
FunSettings = new TeamFunSettings
{
AllowGiphy = true,
GiphyContentRating = GiphyRatingType.Strict,
ODataType = null
},
DisplayName = teamGroup.teamName,
ODataType = null
};

            //var groupId = graphClient.Groups.RequestUrl;
            await graphClient.Groups[teamGroup.groupId].Team
                .Request()
                .PutAsync(newTeam);

Now I want to pass team members as parameter to team object and added them in to team .
So can some one please help me how can i add  members in team object ?

**Comment by MIchaelMainer** [comment]
You have to create a team first, get the team ID, and then you can add members to the team.
