### ISSUE TITLE
Missing property AllowCreatePrivateChannels in Microsoft.Graph.TeamMemberSettings

### ISSUE THREAD

**Issue by bondet-c2s** [microsoftgraph/msgraph-sdk-dotnet#763]
The class Microsoft.Graph.TeamMemberSettings has got a property allowCreateprivateChannels in official API : https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http

In the client .net 3.10.0 , there is no such property :
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var team = new Team
{
	MemberSettings = new TeamMemberSettings
	{
		AllowCreateUpdateChannels = true
               //Missing AllowCreatePrivateChannels
	},
	MessagingSettings = new TeamMessagingSettings
	{
		AllowUserEditMessages = true,
		AllowUserDeleteMessages = true
	},
	FunSettings = new TeamFunSettings
	{
		AllowGiphy = true,
		GiphyContentRating = GiphyRatingType.Strict
	}
};

await graphClient.Groups["{id}"].Team
	.Request()
	.PutAsync(team);

 
[AB#7258](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7258)

**Comment by MIchaelMainer** [comment]
Missing metadata. Will follow up on this.

**Comment by andrueastman** [comment]
It looks like this property now exists in the SDK. See [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/ba67106c8f59c0a3fff0c2e7d27dff1681d95b21/src/Microsoft.Graph/Generated/model/TeamMemberSettings.cs#L45)
Closing this issue for now.
