### ISSUE TITLE
How to add domain name to External access lets your Teams and Skype for Business users communicate with other users that are outside of your organization using Graph APi

### ISSUE THREAD

**Issue by dnyaneshwar-surywanshi** [microsoftgraph/msgraph-sdk-dotnet#765]
I want to add domain name to access external users in Teams using Graph API
Can someone please tell me is it possible ?

**Comment by MIchaelMainer** [comment]
Thank you connecting with us in the Microsoft Graph .Net SDK repo. This question will get more attention if you post to StackOverflow. Please provide a link to your question in this issue.
