### ISSUE TITLE
Copying a driveItem on Sharepoint using PostAsync does not return a result

### ISSUE THREAD

**Issue by Kalle4242** [microsoftgraph/msgraph-sdk-dotnet#768]
Expected or Desired Behavior
In my c# app I want to copy a file from one folder in a Sharepoint document library to another folder in the library.
I'm using the graph.api:
Task<DriveItem> copyDriveItemTask = graphClient.Sites.Root.Lists[_nameOfDocLib].Drive.Root.ItemWithPath(_pathToItemLocation) .Copy(newName, parentReference).Request().PostAsync();  copyDriveItemTask.Wait();
The copyDriveItemTask should return after the file was copied with a DriveItem object referencing the new file as a result object.
In case the file could not be copied (e.g. the source file does not exist or the desination file does already exist), it should throw a corresponding exception.
I need to know whether the copy process was completed and I can access the new file.
Or I need to know that the copy process did not complete of a certain reason.
I want to add a conflictBehaviour = "replace" to replace an occasionally already existing file.
Observed Behavior
After the copyDriveItemTask returns, its result is null! Trying to access the new file does not work. I think copying the file has not been finished at this time.
If I walkthrough step by step in debug mode it works properly, giving the Sharepoint server enough time to complete his copy actions.
Futher research in the documentation confused me:
According to Graph.Api's http documentation the PostAsync call should return with a response containing a link to retrieve the progress of the copy process. Or it returns an error.
In the c# example such a result is missing. The PostAsync here is called with simple (void) await!
According to the Graph.Api's IDriveItemCopyRequest interface PostAsync should return a Task.
I think the c# PostAsync call does not wait until the file is entirely copied. It returns immediately as it is described for the http variant (missing the link to retrieve the progress). But at this time there is no DriveItem that can be returned. So it ends up with a result that equals null.
Whether my explanation is correct or not, in the c# variant I have no chance to determine, if the copy process has terminated or not.
I already posted this to stackoverflow. Going on with my work I had to find out, that no error message is thrown if the destination file does not exist. Furthermore I found a not good documented option called "conflictBehaviour" which should be available at all places where such conflicts can occur. In the current c# implementation of "Copy" I cannot add a conflictBehaviour, because there are only the two parameters "name" and "parentReference". In other implementions a "NewDriveItem" is used, where the conflictBehaviour can be added as "AdditionalData".
All this together I think someone should again have a look on it!
Meanwhile I tried pfresnay's workarounds for sending and polling in issue #226: I got a monitor uri that works in the browser.
Unfortunately in polling method, the call of _graphClient.HttpProvider.SendAsync method throws a NullReferenceException at Microsoft.Graph.HttpProvider.d__18.MoveNext(),
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
I read something nebulous about missing credentials. Do I have to add some scopes to the azure enterprise application? This HttpRequest does not call the Graph Rest Api but in my case the Sharepoint Rest Api.
Scopes "User.Read", "Sites.Manage.All" are set.
Thank you.
[AB#5872](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5872)

**Comment by snebjorn** [comment]
Same problem here.

```cs
// <PackageReference Include="Microsoft.Graph" Version="3.10.0" />
var copiedDriveItem = await client
                .Drives[_driveId]
                .Items[sourceItemId]
                .Copy(destinationName)
                .Request()
                .PostAsync(); // should return Task<DriveItem>
```

copiedDriveItem is null.

The documentation states that I at least should get a location URL.

https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=csharp

**Comment by andrueastman** [comment]
@Kalle4242 @snebjorn 
Please check out the workaround suggested in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/871

In the meantime we are working on currently exposing the header info though the GraphResponse object

**Comment by andrueastman** [comment]
Closing this as the new v4 previews provide direct access to the response headers and status codes. More info in the guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graph-response) and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935.

Ideally, in this scenario, SDK users can now make a call that looks something like this.
```cs
var copyResponse = await graphServiceClient.Me.Drive.Items["{driveItem-id}"]
    .Copy(name, parentReference)
    .Request()
    .PostResponseAsync();

if (copyResponse.HttpHeaders.TryGetValues("Location", out var headerValues))
{
    string locationString = headerValues?.First();
}
```
