### ISSUE TITLE
No public constructor for OpenShiftChangeRequestObject class

### ISSUE THREAD

**Issue by QinglongLuo** [microsoftgraph/msgraph-sdk-dotnet#769]
**Describe the bug**
No public constructor for OpenShiftChangeRequestObject class

**To Reproduce**
var request = await client.Teams["91a937df-41f5-44e1-9d4e-9c434f292cc7"]
                            .Schedule.OpenShiftChangeRequests.Request().AddAsync(new OpenShiftChangeRequestObject())

**Expected behavior**
Provide a public constructor for OpenShiftChangeRequestObject class

 
[AB#7261](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7261)

**Comment by MIchaelMainer** [comment]
This appears to be an issue in our metadata. This is incorrectly defined as an abstract base.

**Comment by QinglongLuo** [comment]
Thanks, @MIchaelMainer 
I can use raw http request for now, and replace it with sdk when it is available.

**Comment by maisarissi** [comment]
Hi @QinglongLuo.

The public constructor is now available and you can check it at [OpenShiftChangeRequest](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Generated/model/OpenShiftChangeRequest.cs#L26).

Thanks.
