### ISSUE TITLE
[Client bug]: provide a descriptive title here

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/msgraph-sdk-dotnet#772]
**Describe the bug**
Graph Service Client Get User Returns Null User Identities.

**To Reproduce**
1. Using Azure AD B2C and C# Project
2. var createdUser = await client.Users.Request().AddAsync(user); or
3. var user= await client.Users[user.Id].Request().GetAsync();
4. View the Identities Collection returned by MS Graph.

**Expected behavior**
A list of Identities to be returned and not be null as per [documentation](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=csharp#example-1-create-a-user)

**Client version**
v3.11.0

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser N/A
 - Version N/A

**Additional context**
Per documentation, I should be returned a list of Identities. Instead, I am returned a null value. 

I have tested this with Create and Get requests. Other data such as display name is populated. 

Was running v 3.10.0, upgraded to 3.11.0 no difference. 
 
[AB#7217](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7217)

**Comment by pschaeflein** [comment]
The documentation link you provided is for "Example 1" which does not specify identities. Did you try "Example 2" (https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=csharp#example-2-create-a-user-with-social-and-local-account-identities)? 

(I understand this may just be a mistaken url - just want to clarify.)

**Comment by Norrch2** [comment]
Thank you for the update. Yes, Example #2.

**Comment by MIchaelMainer** [comment]
Can you verify that the service is returning an empty response by capturing, sanitizing, and sharing with us the HTTP response?

**Comment by Norrch2** [comment]
Hi MIchael, 

here are the http responses.

### Create User
HTTP/1.1 201 Created
Cache-Control: private
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Location: https://graph.microsoft.com/v2/ebfbfe0f-d2d6-42b5-8de3-1af464afd9c3/directoryObjects/393bd45d-774c-4210-a06a-568a1f668e5f/Microsoft.DirectoryServices.User
request-id: 8ac31115-ee28-4531-9f16-8410be293e12
client-request-id: 8ac31115-ee28-4531-9f16-8410be293e12
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"South Central US","Slice":"SliceC","Ring":"3","ScaleUnit":"000","RoleInstance":"AGSFE_IN_7"}}
OData-Version: 4.0
Strict-Transport-Security: max-age=31536000
Date: Thu, 27 Aug 2020 20:32:22 GMT
Content-Length: 377

{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users/$entity","id":"393bd45d-774c-4210-a06a-568a1f668e5f","businessPhones":[],"displayName":"Unknown","givenName":null,"jobTitle":null,"mail":null,"mobilePhone":null,"officeLocation":null,"preferredLanguage":null,"surname":null,"userPrincipalName":"393bd45d-774c-4210-a06a-568a1f668e5f@flirb2cdev.onmicrosoft.com"}

### Get User
HTTP/1.1 200 OK
Cache-Control: private
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
request-id: 862f43e5-8332-41fd-8815-472ae98237d0
client-request-id: 862f43e5-8332-41fd-8815-472ae98237d0
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"South Central US","Slice":"SliceC","Ring":"3","ScaleUnit":"000","RoleInstance":"AGSFE_IN_7"}}
OData-Version: 4.0
Strict-Transport-Security: max-age=31536000
Date: Thu, 27 Aug 2020 20:32:22 GMT
Content-Length: 366 

@odata.context: "https://graph.microsoft.com/v1.0/$metadata#users/$entity"
  []
  displayName: "Unknown"
  givenName: null
  jobTitle: null
  mail: null
  mobilePhone: null
  officeLocation: null
  preferredLanguage: null
  surname: null
  userPrincipalName: "393bd45d-774c-4210-a06a-568a1f668e5f@flirb2cdev.onmicrosoft.com"
  id: "393bd45d-774c-4210-a06a-568a1f668e5f"

**Comment by andrueastman** [comment]
It looks like the identities property is not returned in the payload by default. 

You should be able to include it with a request as follows
```cs 
var user = await graphClient.Users["user-id"]
	.Request()
	.Select("identities")
	.GetAsync();
```

@Norrch2 Closing this issue for now. Feel free to reopen if there are any issues.

**Comment by Norrch2** [comment]
Thank you.

Please forgive any grammatical errors as I am sending this message from my phone.
________________________________
