### ISSUE TITLE
Error with Invoking HTTP with Azure in Power Automate Using Graph API

### ISSUE THREAD

**Issue by mouseman85** [microsoftgraph/msgraph-sdk-dotnet#776]
Hi,

I'm getting an intermittent error with Invoking a HTTP request to Azure. I've created a group and using the invoke HTTP to create a team for that group, but randomly getting the below error. I had posted the same issue to the Power Automate community but couldn't get any help there as it looks like it is an issue with the Graph request and not the connector. 

The HTTP request is a call to the Graph API to put a team to a group, authorization on this is done through the connector login, it is not in the Header of the request i.e no bearer key in the header is required:

### Expected behavior

`https://graph.microsoft.com/v1.0/groups/@{body('Create_group')?['id']}/team

content-type - application/json
{  
  "memberSettings": {
    "allowCreateUpdateChannels": false,
"allowCreatePrivateChannels": false 
  },
  "messagingSettings": {
    "allowUserEditMessages": true,
    "allowUserDeleteMessages": true
  },
  "funSettings": {
    "allowGiphy": true,
    "giphyContentRating": "strict"
  }
}`

### Actual behavior

Same request above fails intermittently with the below error: 

`{
  "error": {
    "code": "NotFound",
    "message": "Failed to execute MS Graph backend request GetGroupInternalApiRequest. The server failed to respond correctly. Response Code: NotFound, Reason: Reason: Not Found, Correlation headers: request-id: b5b6ec94-cd5d-43ed-bfe2-5b68d9e49416\r\nclient-request-id: b5b6ec94-cd5d-43ed-bfe2-5b68d9e49416\r\nx-ms-ags-diagnostic: {\"ServerInfo\":{\"DataCenter\":\"UK South\",\"Slice\":\"SliceC\",\"Ring\":\"4\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AGSFE_IN_20\"}}\r\nDate: Thu, 27 Aug 2020 08:59:08 GMT\r\n",
    "innerError": {
      "date": "2020-08-27T08:59:09",
      "request-id": "860af499-7f40-40c2-814c-6f97110e5ce8"
    }
  }
}`

### Steps to reproduce the behavior

Intermittent problem can't recreate on a regular basis, and haven't noticed a pattern. 

 
[AB#7218](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7218)

**Comment by MIchaelMainer** [comment]
Did you make the group immediately before this call? You may need to wait 15 minutes before creating a team from a group when using the v1.0 API. There is a new API in beta to create a team without having a group.

**Comment by mouseman85** [comment]
Thanks Michael, someone else mentioned the wait for 15mins before creating and posted a link to some information about the graph request in the manual, i've enable a retry process that waits 10 secs between each retry as this is the suggested fix from the manual. We had a process run this morning that went through with no issues.

With the API in beta to create a team without a group does this have any limitations ? Do you still get a standard sharepoint site etc with the same permissions etc as well use both the site and the team for the way we are handling this client teams.

**Comment by andrueastman** [comment]
Hey @mouseman85, 

Please reopen this is if this still an issue.
