### ISSUE TITLE
Outlook Event: Updating Start and End datetime issue

### ISSUE THREAD

**Issue by saf-itpro** [microsoftgraph/msgraph-sdk-dotnet#777]
I'm using [Microsoft Graph .NET SDK][1] to update outlook events. Following code updates the dates correctly, but it updates the `Start` and `End` times as four hours behind. When I go to my Outlook Calendar, it shows the changed times as `04:30` for Start and `05:30` for End `instead of` showing `08:30` for Start and `09:30` for End. **Question**: Why? **Remark**: I'm in US East time zone but I don't think this code has anything to do with it unless I'm missing something here.

**Code**: 

The values of `authProvider` and `"{id}"` varibles are not that relevant to the issue as the code with the real values works fines as it does update the event without error.

    .....
    GraphServiceClient graphClient = new GraphServiceClient( authProvider );
        
    var @event = new Event
    {
    	Subject = "Test subject",
        Body= new ItemBody { Content = "Test body content"}
        Start = new DateTimeTimeZone { DateTime = "2020-08-29T08:30:00.0000000", TimeZone = "UTC" }
        End = new DateTimeTimeZone { DateTime = "2020-08-29T09:30:00.0000000", TimeZone = "UTC" }
    };
    await graphClient.Me.Events["{id}"]
    	.Request()
    	.UpdateAsync(@event);

  [1]: https://docs.microsoft.com/en-us/graph/sdks/sdk-installation

**Comment by MIchaelMainer** [comment]
The client doesn't make any changes to the time zone you submit. Have you tried setting the time zone like this example:

https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#request

Set both the prefer header and the timezone property.

**Comment by saf-itpro** [comment]
@MIchaelMainer  What if in your client app (say, .NET Core app) you are creating a calendar event and you give user a choice to select a date and time (via .NET Calendar control) like we do in `Outlook`. A user in New Your using your app and selects a date and time for an event, one would think that MS Graph (used in your app) would schedule the event according to the `Start` and `End` date time based on New Your (US ET) time. But in my code (shown above where date and time would be not hard coded but would be coming from the user selection via a Calendar control) the time shown is 4 hours behind the time user selected. That means either I am missing something here, or MS Graph is not doing something right. I tend to think I'm missing something but I don't know how to fix it.

**Comment by MIchaelMainer** [comment]
@saf-itpro Please check your UTC value, I think you may be trying to set the time incorrectly. Try updating the meeting with your local time zone and UTC. Make sure you calculate the UTC time correctly (+5 from EST). Here's an example of two equivalent event create and updates using UTC and PST:

```csharp
static async Task CreateAndUpdateEvent(Microsoft.Graph.GraphServiceClient client, string user)
{
	var @event = new Event
	{
		Subject = "Test subject - Created with PST",
		Body = new ItemBody { Content = "Test body content" },
		Start = new DateTimeTimeZone { DateTime = "2020-09-16T18:00:00.0000000", TimeZone = "Pacific Standard Time" },
		End = new DateTimeTimeZone { DateTime = "2020-09-16T18:30:00.0000000", TimeZone = "Pacific Standard Time" }
	};

	var result = await client.Users[user].Events.Request().AddAsync(@event);

	var patchEventObject = new Event
	{
		Start = new DateTimeTimeZone { DateTime = "2020-09-16T19:00:00.0000000", TimeZone = "Pacific Standard Time" },
		End = new DateTimeTimeZone { DateTime = "2020-09-16T19:30:00.0000000", TimeZone = "Pacific Standard Time" }
	};
		
	var result2 = await client.Users[user].Events[result.Id].Request().UpdateAsync(patchEventObject);
}

static async Task CreateAndUpdateEventUTC(Microsoft.Graph.GraphServiceClient client, string user)
{
	var @event = new Event
	{
		Subject = "Test subject - Created with UTC",
		Body = new ItemBody { Content = "Test body content" },
		Start = new DateTimeTimeZone { DateTime = "2020-09-17T01:00:00Z", TimeZone = "UTC" },
		End = new DateTimeTimeZone { DateTime = "2020-09-17T01:30:00Z", TimeZone = "UTC" }
	};

	var result = await client.Users[user].Events.Request().AddAsync(@event);

	var patchEventObject = new Event
	{   // UTC is 8 hours ahead of PST

		Start = new DateTimeTimeZone { DateTime = "2020-09-17T02:00:00.0000000", TimeZone = "UTC" },
		End = new DateTimeTimeZone { DateTime = "2020-09-17T02:30:00.0000000", TimeZone = "UTC" }

		// This format works as well
		//Start = new DateTimeTimeZone { DateTime = "2020-09-17T02:00:00Z", TimeZone = "UTC" },
		//End = new DateTimeTimeZone { DateTime = "2020-09-17T02:30:00Z", TimeZone = "UTC" }
		
	};

	var result2 = await client.Users[user].Events[result.Id].Request().UpdateAsync(patchEventObject);
}
```
