### ISSUE TITLE
Permissions issue for /me/memberOf request

### ISSUE THREAD

**Issue by Shama-K** [microsoftgraph/msgraph-sdk-dotnet#778]
User.Read permission can retrieve the groups and directory roles that the user is a direct member of.
Also there is a permission mismatch in documentation for **List memberOf**. 

Issue 1: As per [documentation](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http), the Permissions required to get the groups and directory roles are: **Directory.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All** but we can retrieve the details by using **User.Read** permission.
**To Reproduce**
I have tested it through postman with request URL "https://graph.microsoft.com/v1.0/me/memberOf". After passing Access Token that has "scp": "openid profile User.Read email", it returned all the groups and directory roles.

Issue 2: [Document](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http) does not mention "GroupMember.Read.All" permission. But Access Token in Graph Explorer has the specified scope.
**To Reproduce**
Go to https://aka.ms/ge and sign-in
Endpoint: https://graph.microsoft.com/v1.0/me/memberOf
Access Token has scp: "GroupMember.Read.All openid profile User.Read User.ReadBasic.All email"
 
[AB#7219](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7219)

**Comment by MIchaelMainer** [comment]
Issue #1 seems to be a bug in the scope of the user.read permission. We will need to verify.

Issue #2 May be a doc bug where we need to specify that GroupMember.Read*.All provides access to group information (but not directory roles). Can you verify that you only see group membership and no directory roles in the response?

https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#delegated-permissions-24

**Comment by MIchaelMainer** [comment]
@Jackson-Woods Do you have insight to either of these questions? 
@davidmu1 Is it possible that issue one is a doc issue - we may need to add User.Read to https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http.

**Comment by Shama-K** [comment]
> Issue #1 seems to be a bug in the scope of the user.read permission. We will need to verify.
> 
> Issue #2 May be a doc bug where we need to specify that GroupMember.Read*.All provides access to group information (but not directory roles). Can you verify that you only see group membership and no directory roles in the response?
> 
> https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#delegated-permissions-24

For Issue 2, I can retrieve directory roles with **GroupMember.Read.All** permission.
As for "scp": "GroupMember.Read.All openid profile User.Read email", one of the value in response is:  
"@odata.type": "#microsoft.graph.directoryRole"

**Comment by andrueastman** [comment]
> Issue #1 seems to be a bug in the scope of the user.read permission. We will need to verify.

With regards to clarifying this, it will be followed up here by the users api team.
https://docs.microsoft.com/en-us/answers/questions/438922/mememberof-can-be-retrieved-with-just-userread-sco.html

> Issue #2 May be a doc bug where we need to specify that GroupMember.Read*.All provides access to group information (but not directory roles). Can you verify that you only see group membership and no directory roles in the response?

This will be followed up here
https://github.com/microsoftgraph/microsoft-graph-docs/issues/13157

Closing this here as this is for client library issues only.
