### ISSUE TITLE
Support for AzurePPE environment in GraphServiceClient

### ISSUE THREAD

**Issue by dineshreddy007** [microsoftgraph/msgraph-sdk-dotnet#779]
**Is your feature request related to a problem? Please describe.**
Our team is using Graph SDK to do operations on Azure AD application. We were able to use Graph SDK in public cloud, but could not use it in AzurePPE. AzureAD powershell module supports AzurePPE environment.
E.g. Connect-AzureAD -AzureEnvironmentName AzurePPE

**Describe the solution you'd like**
I see GraphClientFactory supports below 4 environments. Can we have AzurePPE along with it?
        public const string Global_Cloud = "Global";
        //
        public const string USGOV_Cloud = "US_GOV";
        //
        public const string China_Cloud = "China";
        //
        public const string Germany_Cloud = "Germany"; 

**Describe alternatives you've considered**
I have tried using below constructor of GraphServiceClient but it is failing with invalid api version.
new GraphServiceClient("https://graph.ppe.windows.net/v2", authProvider);

 
[AB#7220](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7220)

**Comment by MIchaelMainer** [comment]
We should support arbitrary endpoints to allow internal test scenarios and other clouds.

**Comment by andrueastman** [comment]
Hey @rajadineshmurugesan-microsoft,

Are you able to provide info about the errors you are receiving and the SDK version in use?

Furthermore, are you able to make successful calls if you setup your app like this?

```cs
IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(CLIENT_ID)
                .WithTenantId(TENANT_ID)
                .WithAuthority("https://login.windows-ppe.net", TENANT_ID)
                .WithCertificate(CERTIFICATE)
                .Build();
```

**Comment by andrueastman** [comment]
Closing this as ithis is indeed possible to do with the SDK by passing a custom base URL to the GraphServiceClient with something like this

```cs
IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(CLIENT_ID)
                .WithAuthority(CUSTOM_AUTHORITY, TENANT_ID)
                .WithTenantId(TENANT_ID)
                .WithCertificate(CERTIFICATE)
                .Build();

// Also ensure the scopes match the custom authority if its url bases
string[] scopes = new[] { $"{CUSTOM_AUTHORITY}/.default"};

ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication, scopes);
GraphServiceClient graphClient = new GraphServiceClient(CUSTOM_URL, authProvider);

```
