### ISSUE TITLE
Unable to get calendar invite in attachments of message

### ISSUE THREAD

**Issue by roboza** [microsoftgraph/msgraph-sdk-dotnet#781]
I am working in .NET and trying to get a calendar invite within a message. When I do a query

_client.Users.me.Messages["aaa..."].Attachments.Request().GetAsync()

The result does not have the invite in the list of attachments. 

If I call

_client.Users.me.Messages["aaa..."].Request().Expand("attachments".GetAsync()

I still get no attachments excep the invite information is in in AdditionalData collection

I have no idea how to get the attachment into the attachment list and every tutorial and code snippet I have seen have told me to access the attachment directly using the .Attachments["ID"] but I don't have the ID so can't access it.

Anyone else having a similar problem? 
[AB#7221](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7221)

**Comment by MIchaelMainer** [comment]
Is the calendar invite an .ics attachment? Can you demonstrate whatyou want to happen in [Graph Explorer](https://aka.ms/ge)?

Can you provide more information:
- Link to documentation you're using.
- **Sanitized** http request and response capture.

**Comment by andrueastman** [comment]
Ping @roboza

**Comment by andrueastman** [comment]
@roboza Closing this for now due to inactivity. Please reopen if need be.
