### ISSUE TITLE
Add CodeQL validation

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet#783]
https://github.com/microsoftgraph/msgraph-beta-sdk-java/commit/3efceba8c310f47c3ffe44564da1c63f17d4d549 
[AB#7222](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7222)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1375
