### ISSUE TITLE
DateTimeTimeZone format doesn't match documentation?

### ISSUE THREAD

**Issue by JaykeBird** [microsoftgraph/msgraph-sdk-dotnet#79]
Greetings!

I'm building a calendar app with Microsoft Graph support in mind, and while attempting to use the Microsoft Graph SDK, I came across something that didn't quite match up.

When getting an event, and trying to determine its start time, it returns the datetime in the format "MM/DD/YYYY HH:MM:SS" (such as "01/25/2017 11:00:00". This in itself isn't that bad, but it raises a few questions:

1. This doesn't match the documentation at https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/datetimetimezone.htm. Granted, the documentation doesn't really detail the specific format, but it at least signifies the character "T" being present.
2. How does this work in other cultures? I plan to have my program be available in other countries/cultures; is the "MM/DD/YYYY HH:MM:SS" format used there too? Is it dependent upon the MSAL account's region? Or is it dependent upon the computer the code is running on?

Here is my code for getting the events:

```C#
        public async Task<List<MyApp.Event>> GetEventsInPeriod(DateTime start, DateTime end)
        {
            var cvr = await graphClient.Me.Calendars[calendarId].CalendarView.Request(
                 new List<Option>{
                    new QueryOption("startDateTime", start.Year.ToString() + "-" + start.Month.ToString() + "-" + start.Day.ToString() + "T00:00:00.0000000"),
                    new QueryOption("endDateTime", end.Year.ToString() + "-" + end.Month.ToString() + "-" + end.Day.ToString() + "T00:00:00.0000000")
                 }).GetAsync();

            foreach (Microsoft.Graph.Event item in cvr)
            {
                // the time should be in UTC already
                Console.WriteLine(item.Start.DateTime);
            }

            return null;
        }
```

While I realize this may be an issue above the .NET SDK itself, I didn't know where else to report this. And as well, I am utilizing this client library in this case. I hope this isn't much of an inconvenience!

**Comment by MIchaelMainer** [comment]
Greetings to you @JaykeBird!

Thank you for bringing this to our attention. The client library is deserializing the response date time values differently than the wire protocol definitions, as you have pointed out in the link to the documentation.

I think the value for `item.Start.DateTime` should have the same format as the value you entered for the query options. I'm going to consider this a bug as I believe the client should pass through the format as sent over the wire.
 
With regards to how will this work in other cultures, the format used in the client library will be the same across cultures as we don't do culture specific formatting.

**Comment by JaykeBird** [comment]
Okay, awesome! Thank you for the response.

If possible, I'd like to ask a question. What is the query option for defining the format? Or does it use the format entered through the query options for "startDateTime" and "endDateTime"? (I used the format mentioned in the [documentation for calendarView](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list_calendarview).)

For now, I'll have my program parse the "MM/DD/YYYY HH:MM:SS" format that I'm being returned until any further news comes along.

**Comment by MIchaelMainer** [comment]
@JaykeBird I'm not  if I understand your question. If you mean defining the format of the dateTime, there isn't  a way to change the format of the date time. It is returned in a single format, in either local or UTC. You can specify the timezone and the service will calculate for you the local time.

**Comment by JaykeBird** [comment]
Okay, I think your explanation helped. I'm sorry if I confused you. I was asking about the format string for the datetime, such as "MM/DD/YYYY HH:MM:SS". Like I said, though, I think you answered that question for me.

Thank you!

**Comment by MIchaelMainer** [comment]
Closing this as changing this would be breaking. Please reopen if we're missing anything from our consideration.
