### ISSUE TITLE
[Client bug]: Copying a DriveItem on SharePoint using PostAsync doesn't work on unique fields

### ISSUE THREAD

**Issue by snebjorn** [microsoftgraph/msgraph-sdk-dotnet#790]
**Describe the bug**
If there is a unique constraint on a custom field in a document library in SharePoint then if you copy that item it'll fail if it was copied to the same list. This is the default behavior.
There appears to be no way to add/remove/alter custom fields during a copy.

**To Reproduce**
1. Go to document library
2. Add a custom field
3. Make it unique
4. Try to copy a file inside the document library

**Expected behavior**
Today an exception is thrown
> One or more fields with unique constraints already has the provided value

This is the correct behavior. However there is no way to change this field during the copy. So it's impossible to copy the file.

`PostAsync()` should accept an object that have the `AdditionalData` property so we can change "stuff" (like fields) during the copy.

```cs
var changeFields = new SomeGraphObject
{
    AdditionalData = new Dictionary<string, object>
    {
        { "MyUniqueField", myNewValue }
    }
};
await client
   .Drives[_driveId]
   .Items[sourceItemId]
   .Copy(destinationName)
   .Request()
   .PostAsync(changeFields);
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1266245/92739701-72c20180-f37d-11ea-8b43-3afc17e88dbf.png)

**Client version**
Microsoft.Graph 3.10.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser huh?
 - Version huh?

**Additional context**
There is also issues with uploading files.
I haven't found a way to set fields on `CreateUploadSession().Request().PostAsync()` or `LargeFileUploadTask.UploadAsync()`, which will cause problems with required fields. 
[AB#7223](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7223)

**Comment by MIchaelMainer** [comment]
Can you point me at the documentation that demonstrates that this scenario is supported by the service? You may also want to cross post this to StackOverflow so that we have more eyes on this scenario. Please post the link here if you do.

**Comment by snebjorn** [comment]
> Can you point me at the documentation that demonstrates that this scenario is supported by the service?

I don't think this is documented, or at least I can't navigate the documentation to find anything related to this limitation.
I cannot remember the error type but I couldn't find a matching description in the listed errors https://docs.microsoft.com/en-us/graph/errors

> scenario is supported by the service

I tried to copy a file via the online UI and got this error
![image](https://user-images.githubusercontent.com/1266245/92926599-8da77b00-f43c-11ea-8e5b-f215e8854f1d.png)
So that could indicate that it isn't supported.

> You may also want to cross post this to StackOverflow so that we have more eyes on this scenario. Please post the link here if you do.

https://stackoverflow.com/questions/63847261/copying-file-on-sharepoint-using-graph-api-sdk-doesnt-work-with-unique-fields

**Comment by snebjorn** [comment]
https://docs.microsoft.com/en-us/answers/questions/501323/copying-a-driveitem-on-sharepoint-using-postasync.html
