### ISSUE TITLE
The collection type 'Microsoft.Graph.IUserAppRoleAssignmentsCollectionPage' on 'Microsoft.Graph.User.AppRoleAssignments' is not supported. 

### ISSUE THREAD

**Issue by rykon3007** [microsoftgraph/msgraph-sdk-dotnet#791]
I got this error trying to call Graph from an API.
What does it means?

**Comment by MIchaelMainer** [comment]
Can you provide more information like which documentation you've used, repro steps, code snippets, and any other references that would be helpful.

**Comment by rykon3007** [comment]
### Environment
- Visual Studio 2019
- .Net Core Console App
- installed library from Nuget
-- Microsoft.Graph (ver 3.12.0)
-- Microsoft.Graph.Auth (ver 1.0.0-preview.5)  

### Overview
I wanna get our AAD B2C User info with Client credentials provider.But, an error has occurred.
Is it because of msgraph sdk? or another library?

error message 
`An exception of type 'System.NotSupportedException' occurred in System.Private.CoreLib.dll but was not handled in user code
The collection type 'Microsoft.Graph.IUserAppRoleAssignmentsCollectionPage' on 'Microsoft.Graph.User.AppRoleAssignments' is not supported.`

### Code snippets
`
var graphServiceClient = CreateGraphServiceClient();
await ShowUserAsync(graphServiceClient, targetUserObjectId); //

private static GraphServiceClient CreateGraphServiceClient()
{
    var confidentialClientApplication = ConfidentialClientApplicationBuilder
        .Create(AppId)
        .WithTenantId(TenantId)
        .WithClientSecret(ClientSecret)
        .Build();

    var authProvider = new ClientCredentialProvider(confidentialClientApplication);

    return new GraphServiceClient(authProvider);
}

private static async Task ShowUserAsync(GraphServiceClient graphServiceClient, string objectId)
 {
    var user = await graphServiceClient.Users[objectId]
        .Request()
        .Select(u => new { u.DisplayName, u.Id, u.OfficeLocation, u.Identities })
        .GetAsync();

    Console.WriteLine(JsonSerializer.Serialize(user, JsonSerializerOptions)); // Error is here.
}


private static readonly JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions
{
    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
    WriteIndented = true,
    IgnoreNullValues = true
};

`
### References
- https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS

**Comment by MIchaelMainer** [comment]
You are trying to use the System.Text.Json.JsonSerializer which we don't support yet. We are still using Newtonsoft.

Try:

`client.HttpProvider.Serializer.SerializeObject(user);`

On a different note, the error message you share doesn't make sense in the context of this issue.

**Comment by Reverendheat** [comment]
Having the same error, happening before I try to serialize/deserialize.

**Comment by MIchaelMainer** [comment]
@Reverendheat Are you using System.Text.Json.JsonSerializer?

**Comment by udlose** [comment]
> You are trying to use the System.Text.Json.JsonSerializer which we don't support yet. We are still using Newtonsoft.
> 
> Try:
> 
> `client.HttpProvider.Serializer.SerializeObject(user);`

@MIchaelMainer This issue needs to be re-opened.  When is support for `System.Text.Json` coming?  I'm using version 3.27.0 (the latest) and it's still not supported?

**Comment by MIchaelMainer** [comment]
@udlose We have a preview out that supports System.Text.Json. https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.1.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md

Please provide us feedback in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935
