### ISSUE TITLE
Permissions mismatch when using Me.Manager.Request().GetAsync()

### ISSUE THREAD

**Issue by thomo03** [microsoftgraph/msgraph-sdk-dotnet#795]
Hello everyone. 

This is my first time in raising an issue, I've read the contributing guidelines and searched other sources, however, if this post is not appropriate here, I'm happy for suggestions. Thank you.

### Expected behavior
I expected the Graph library to allow access to see my manager when calling 
`_graphClient.Me.Manager.Request().GetAsync()` only needing the following scopes to get access to the logged in user's manager, as shown at [https://developer.microsoft.com/en-us/graph/graph-explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

![image](https://user-images.githubusercontent.com/266475/93311166-8cd86580-f7fd-11ea-91aa-0305d46320af.png)

I believe it is the above permission (User.ReadWrite) which gives me access to see my manager in the Graph Explorer? The only other scope I have on the Graph Explorer is 'User.Read' and I don't have access to grant any of the 'Admin Consent Required'.

### Actual behavior

When I called the method, I received the following error message, displayed in the browser.

`ServiceException: Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.`

### Steps to reproduce the behavior

I've injecteda GraphServiceClient into my controller, with the following scopes. 

`"User.Read",
 "User.ReadWrite",
 "Mail.ReadBasic",
 "Mail.Read",
 "Calendars.Read",
 "MailboxSettings.Read",`

To ensure the user does have these permissions before calling Me.Manager.Request().GetAsync(), I decorated my IActionResult with the following
`[AuthorizeForScopes(Scopes = new[] { "User.ReadWrite" })]` which allows me to continue.

I've logged into the Azure app and checked the permissions, going to 

**API Permissions -> Add a Permission**
Under 
**Request API Permissions**
I select **Microsoft Graph -> Delegated Permissions**, I scroll to **User** and I can see the permission 'User.ReadWrite' is selected

![image](https://user-images.githubusercontent.com/266475/93313034-d9bd3b80-f7ff-11ea-861d-b48c7eb633d3.png)

Kind regards

 
[AB#7224](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7224)

**Comment by MIchaelMainer** [comment]
@thomo03 This should just work. I'm guessing that this user has never made these calls before. I'm seeing something similar to this here: https://github.com/microsoftgraph/msgraph-cli/issues/18#issuecomment-693606624

Can you call `_graphClient.Me.Request().GetAsync()` successfully?

**Comment by thomo03** [comment]
Thank you for your response @MIchaelMainer The user who is calling the method is the same user who is logged into the Graph explorer where everything works okay (not sure if this is helpful) I've been able to make other calls successfully, out of all the ones I have tried.

I can call `_graphClient.Me.Request().GetAsync()` perfectly well, everything works as expected, it's as soon as I change it to `_graphClient.Me.Manager.Request().GetAsync();` I get the issue.

![image](https://user-images.githubusercontent.com/266475/93446158-1c971600-f8c9-11ea-96cc-856feff697a9.png)


To try start a fresh, I navigated to the user's applications in Azure Active Directory and removed the access, my understanding is, this revokes the permissions, so should ask the user to grant these permissions again?

![image](https://user-images.githubusercontent.com/266475/93445149-d5108a00-f8c8-11ea-963b-2f8fb030de55.png)


I opened a new private browser and navigated to the page, but I wasn't asked for permissions again, it sailed through to this action without asking for any permissions to be granted and again threw the `ServiceException: Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation` at the same point

![image](https://user-images.githubusercontent.com/266475/93446158-1c971600-f8c9-11ea-96cc-856feff697a9.png)

**Comment by MIchaelMainer** [comment]
Are you still seeing this issue? I thought this wasn't working for me yesterday, appears to work fine today.

**Comment by thomo03** [comment]
Hi @MIchaelMainer. It wasn't working when I sent that message this morning, I did check again. I'm happy to look again tomorrow, I'll update this and let you know. 

Thanks again

**Comment by thomo03** [comment]
Hello @MIchaelMainer apologises for my late response, something always seems to crop up at the best of times! I did test this the other day, and again today, and I'm still receiving the same issue unfortunately. 

Kind regards

**Comment by MIchaelMainer** [comment]
Hi @thomo03 can you inspect the access token and verify that it has the expected scope on it?

**Comment by thomo03** [comment]
@MIchaelMainer I will. I'll come back to you after the weekend if not before. Thank you

**Comment by thomo03** [comment]
Sorry @MIchaelMainer, do you know if there is an end point for me to check the permissions with a token? I've read what I can find, but to no avail. 

Thanks for your help on this.

**Comment by MIchaelMainer** [comment]
You can capture the token using Fiddler, and inspect it at jwt.ms to verify whether it contains the permission as expected. 

This isn't an issue with the Microsoft Graph client library, it appears the issue is with requesting the correct scopes.

**Comment by thomo03** [comment]
Hi @MIchaelMainer, thank you for jwt.ms, that is really very helpful. I've captured the token, and for the scopes, they display as this:

![image](https://user-images.githubusercontent.com/266475/94706044-9c959500-0339-11eb-9d98-0dc8c5083ae5.png)

I've checked that I'm still not able to get my manager, which is still the case 

![image](https://user-images.githubusercontent.com/266475/94706131-b8993680-0339-11eb-956d-0e86ef55c327.png)

Many thanks

James

**Comment by MIchaelMainer** [comment]
Just so I'm clear, you can log in with the user in Graph Explorer and get the manager information, but when signed in to the web application, the user cannot get their manager information, correct?

Can you change this call: `_graphClient.Me.Manager.Request().GetAsync();` to `_graphClient.Users["useremailaddressORid"].Manager.Request().GetAsync();` and will it work?

**Comment by thomo03** [comment]
Hello again @MIchaelMainer. Thanks for the response. You're correct, if I log into my Graph Explorer account, I'm able to retrieve the information about my manager. (Just so I'm clear, they are the same email I use, it's a work one, but it's the same when logging into Graph and my application) Sadly, the code change you provided still stated `ServiceException: Code: Authorization_RequestDenied`.

But given you provided me a link to JWT.ms, I copied the token from the Graph Explorer 
![image](https://user-images.githubusercontent.com/266475/94780548-87b01480-03c0-11eb-9f54-7f0ea3b79ead.png)

(obviously not showing the entire token here)

and pasted into JWT.ms and the permission are displayed as such:

`Calendars.ReadWrite Contacts.ReadWrite DeviceManagementApps.Read.All DeviceManagementApps.ReadWrite.All DeviceManagementConfiguration.Read.All DeviceManagementConfiguration.ReadWrite.All DeviceManagementManagedDevices.PrivilegedOperations.All DeviceManagementManagedDevices.Read.All DeviceManagementManagedDevices.ReadWrite.All DeviceManagementRBAC.Read.All DeviceManagementRBAC.ReadWrite.All DeviceManagementServiceConfig.Read.All DeviceManagementServiceConfig.ReadWrite.All Files.ReadWrite.All Mail.ReadWrite Notes.ReadWrite.All openid People.Read profile Sites.ReadWrite.All Tasks.ReadWrite User.Read User.ReadBasic.All User.ReadWrite email`

I've taken all these, and added them to my permissions scope in my application:

![image](https://user-images.githubusercontent.com/266475/94780895-073de380-03c1-11eb-8097-1d85a3b09feb.png)

I've also logged into AAD portal and updated my API permissions (non-admin consented ones)

![image](https://user-images.githubusercontent.com/266475/94782282-ea0a1480-03c2-11eb-805b-a713f9b64339.png)


Reloaded my application, and it goes off to log me in, and then I receive this issue:

![image](https://user-images.githubusercontent.com/266475/94781140-55eb7d80-03c1-11eb-88f1-3b5df8c8fdba.png)

Like I mentioned in my first post, I don't have permission to grant admin rights to the application, so I'm surprised to see that the Graph Explorer either appears to be letting me do things that I shouldn't be allowed to do, or my application is preventing me from making calls I should be allowed to make, that's what I take from this, unless you can see a different reason?

Kind regards as always

**Comment by thomo03** [comment]
Hello everyone.

I'm just wondering if there are any ideas out there as to why this may be behaving in such a manner?

**Comment by MIchaelMainer** [comment]
Took another look. All of the permissions in the [docs for getting a manager](https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http) require admin consent. Did your admin consent to Graph Explorer? 

You may want to try joining the [dev program to get a free demo tenant](https://developer.microsoft.com/en-US/office/dev-program). That way you have full control of AAD.

Another thing to check is login to your corp portal.azure.com, go to AAD, and then Enterprise Applications and look at **Graph explorer (official site)**. Under permissions, you should see whether an admin has consented to scopes for Graph Explorer. That may explain why you have access via Graph Explorer but not in your in development app.
