### ISSUE TITLE
VS 20019 UnitTest in Debug mode leads to exception, Newtonsoft.Json being the culprit!?

### ISSUE THREAD

**Issue by artvize** [microsoftgraph/msgraph-sdk-dotnet#797]
Greetings,
I am working with a solution having multiple projects in it.  Two newly added projects work with MS.Graph API and UnitTest project for the first one.
First project interacts with MS Graph (create teams, channels, etc...).  We have a tenant, MS 365, all is good... when debugging this project through Web api endopoints - we can create teams, create channels, etc...
The Second one, UnitTest project builds fine, and I can get the debugger start at any TestMethod, and I am able to step into calls.  The issue comes up when I step over the line where **var graphClient = new GraphServiceClient(...);** runs.  In the modules window I can observe that latest Netwonsoft.Json (v 12.0.3) is loaded right before 'step over'/F10.  There is an attempt to load the Newtonsoft.Json(v 6.0.0), with the following exception details:

`=== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/SLN/code/server/TeamsService.Test/Server/bin/Debug
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Graph.Core, Version=1.19.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\TestPlatform\testhost.x86.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///C:/Dev/SLN/code/server/TeamsService.Test/Server/bin/Debug/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.`

thank you,
Art
P.S.  Newtonsoft.Json was installed prior to Microsoft.Graph in the first project 
[AB#7225](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7225)

**Comment by artvize** [comment]
My colleague helped with the fix by adding the following into the project file (the UnitTest prj file):
`<PropertyGroup>
  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
</PropertyGroup> `
Since I was not able to find out exactly what module 'requires' the Newtonsoft.Json 6.0.. version that had the exception thrown, I consider this issue not closed.  Any additional insight will help.
Thanks, Art

**Comment by andrueastman** [comment]
@artvize 
I believe the Newtonsoft dependency comes from the [core library](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core)(see [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/015f3761f2357ebd439936e6c278d350fc8646ec/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L70)) which is is a dependendency of this library.
It might be helpfult to also know that the plan is to move over to System.Text.Json in future versions of the library and not to upgrade the Newtonsoft dependency (see https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/80)

If this is helpful enough, please feel free to close this issue.
