### ISSUE TITLE
Intune managed device list enrolled by user data.

### ISSUE THREAD

**Issue by maartengrassmid** [microsoftgraph/msgraph-sdk-dotnet#802]
**Is your feature request related to a problem? Please describe.**
Our team is using the Graph SDK to retrieve information about Intune managed devices.
In the azure portal it shows two users on a managed device page. The primary user and the enrolled by user.
We can't find any way of retrieving this data.

**Describe the solution you'd like**
Add fields for the enrolled by user. 
string enrolledByUserId;
string enrolledByUserPrincipalName;
string enrolledByUserDisplayName;

Here a link to my StockOverflow post: https://stackoverflow.com/questions/64208372/microsoft-graph-intune-how-to-get-the-enrolled-by-user-data

**Additional context**
![image](https://user-images.githubusercontent.com/62875225/94924548-03dc5200-04be-11eb-8ef9-650ebc28744d.png)

**Comment by MIchaelMainer** [comment]
@maartengrassmid 

Thank you for asking this question. This issue list is for the Microsoft Graph client library. If you find an issue in the use of this client library, please post them here. General questions about the Intune API should be posted to StackOverflow and tagged with [microsoftgraph] and [intune]. Make sure you state what you've tried thus far, the results, and the [documentation](https://docs.microsoft.com/en-us/graph/api/resources/intune-graph-overview?view=graph-rest-1.0) you referenced.

Please add a link to your StackOverflow post here in this issue.

**Comment by maartengrassmid** [comment]
I have updated the my issue with the StackOverflow post link.

**Comment by MIchaelMainer** [comment]
Thank you Maarten. This looks like a feature request for the Microsoft Graph API and not for the Microsoft Graph client library as there isn't documentation to support that the Microsoft Graph API supports it. You can make feature requests here:
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests
