### ISSUE TITLE
Clear range not supported by nuget Microsoft.Graph

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-sdk-dotnet#816]
Clear range is not supported by Microsoft.Graph nuget.
Interface IWorkbookWorksheetRangeRequest does not contain any Clear() method.
The latest version 3.15.0.0 of the nuget has only following methods:

```
public interface IWorkbookWorksheetRangeRequest : IBaseRequest
    {
        IWorkbookWorksheetRangeRequest Expand(string value);
        Task<WorkbookRange> GetAsync();
        Task<WorkbookRange> GetAsync(CancellationToken cancellationToken);
        Task<WorkbookRange> PatchAsync(WorkbookRange workbookrange);
        Task<WorkbookRange> PatchAsync(WorkbookRange workbookrange, CancellationToken cancellationToken);
        Task<WorkbookRange> PutAsync(WorkbookRange workbookrange);
        Task<WorkbookRange> PutAsync(WorkbookRange workbookrange, CancellationToken cancellationToken);
        IWorkbookWorksheetRangeRequest Select(string value);
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3097be-d21b-76a9-64f6-4422c84cf357
* Version Independent ID: 8e70e4e6-0eb0-dcea-6fa3-262252374740
* Content: [Range: clear - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/range-clear?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/range-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/range-clear.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam** 
[AB#6381](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6381)

**Comment by MIchaelMainer** [comment]
This requires composable function support.

**Comment by andrueastman** [comment]
This is tracked via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/233

**Comment by MIchaelMainer** [comment]
This scenario is now supported in versions greater than 3.22.0.

```csharp
    await client.Users[Chambele.Beta.User1].Drive.Items["{id}"].Workbook.Names["{name}"]
                                                                        .Range()
                                                                        .Clear("Formats")
                                                                        .Request()
                                                                        .PostAsync();
```
