### ISSUE TITLE
 Uploading large files using an upload session

### ISSUE THREAD

**Issue by kimselim** [microsoftgraph/msgraph-sdk-dotnet#824]
I'm trying to upload a large file just like the one shown in the tutorial below.
(graph API Beta)
https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-beta

**Upload Complete**
After uploading the file, you should be able to check it.

**Situation after actual upload**
The file has been uploaded but cannot be read.

**Steps to perform upload**

1. Create an upload session
var ms = new MemoryStream();
            files.CopyTo(ms);

            var filebyte = ms.ToArray();
            var content = new ByteArrayContent(filebyte);

            var response = await _client.PutAsync("users/" + upn + "/drives/" + driveId + "/root:/Files/" + fileName + ":/content", content);

2. File Upload
            int idx = 0;
            int fileSize = Convert.ToInt32(files.Length);
            int fragSize = 320 * 1024; //4MB => 4 * 1024 * 1024;
            var byteRemaining = fileSize;
            var numFragments = (byteRemaining / fragSize) + 1;

            while (idx < numFragments)
            {
                var chunkSize = fragSize;
                var start = idx * fragSize;
                var end = idx * fragSize + chunkSize - 1;
                var offset = idx * fragSize;

                if (byteRemaining < chunkSize)
                {
                    chunkSize = byteRemaining;
                    end = fileSize - 1;
                }

                var contentRange = " bytes " + start + "-" + end + "/" + fileSize;
                byte[] file = new byte[chunkSize];
                using (var client = new HttpClient())
                {
                    var content = new ByteArrayContent(file);
                    content.Headers.Add("Content-Length", chunkSize.ToString());
                    content.Headers.Add("Content-Range", contentRange);

                    var response = client.PutAsync(url, content);
                }
                byteRemaining = byteRemaining - chunkSize;
                idx++;
            }
3. Download files from OneDrive
4. The file is corrupted 
[AB#7227](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7227)

**Comment by MIchaelMainer** [comment]
Please try this example and tell us whether this solves your problem:
https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp

**Comment by kimselim** [comment]
@MIchaelMainer When using the sdk I get the error below.

Id = 3560, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"

**Comment by kimselim** [comment]
@MIchaelMainer 
I tried using sdk. The file uploads well, but if the size is large, it does not upload... Even 40mb is not uploaded..

**Comment by kimselim** [comment]
@MIchaelMainer 
How to fix the slow speed?

**Comment by kimselim** [comment]
> 이 예제를 시도하여 문제가 해결되는지 알려주십시오.
> [https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest -1.0 & tabs = csharp](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp)


How to fix the slow speed?
