### ISSUE TITLE
Privileged Identity Management Code Base Update

### ISSUE THREAD

**Issue by bullipauline** [microsoftgraph/msgraph-sdk-dotnet#831]
I am currently working in a cloud only Identity & Access Management environment with a privileged identity management scenario.
I have some questions about the Privileged Identity Management Code Base Update [https://aka.ms/PIMFeatureUpdateDoc](https://aka.ms/PIMFeatureUpdateDoc): When is the Privileged Identity Management Code Base Update available in the C# Client SDK?

**Comment by MIchaelMainer** [comment]
I'm unfamiliar with the PIM service API so I suggest you try the contact in that document after posting to [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/index.html).

This [API is available](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/search?q=privileged) in the client SDK. Use the Microsoft.Graph.Beta NuGet package.

https://docs.microsoft.com/en-us/graph/api/privilegedrole-get?view=graph-rest-beta&tabs=csharp
