### ISSUE TITLE
Consider migration from JSON.NET (Newtonsoft) to System.Text.Json

### ISSUE THREAD

**Issue by udlose** [microsoftgraph/msgraph-sdk-dotnet#832]
The new implementation of System.Text.Json (added in .NET Core 3.0) is now being implemented widespread by the .NET Core team as a replacement for Newtonsoft (JSON.NET).  From [How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to)

> **System.Text.Json focuses primarily on performance, security, and standards compliance**. It has some key differences in default behavior and doesn't aim to have feature parity with Newtonsoft.Json. For some scenarios, System.Text.Json has no built-in functionality, but there are recommended workarounds.

The motivation behind development of this is described here: [The future of JSON in .NET Core 3.0](https://github.com/dotnet/runtime/issues/27761)

It would seem that migration should be considered since this is the direction of MS and the feature-set and capabilities of `System.Text.Json` will only grow moving forward.  I appreciate your consideration.

**Comment by ddyett** [comment]
this work is planned and under way with our 2.0 preview version.   We hope to complete the work soon.

**Comment by udlose** [comment]
> this work is planned and under way with our 2.0 preview version. We hope to complete the work soon.

@ddyett  2.0? The latest version is 3.19. Am I missing something?

**Comment by ddyett** [comment]
apologies.  i meant the .NET core preview below.  The work for the files in this repo will get under way shortly.

https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.0-preview.3
