### ISSUE TITLE
GraphServiceClient in a multitenant app with authentication provider for app credential

### ISSUE THREAD

**Issue by guru98** [microsoftgraph/msgraph-sdk-dotnet#838]
Hi,
i have an azure function that call microsoft graph. It'is  multitenant. I would like to have a single GraphServiceClient to manage the different request for the different domain. Technically i can create an authentication provider where i do not specificy tenant in the ConfidentialClientApplicationBuilder and then i can specify it in the AcquireTokenForClient but the Authentication provider in the GraphServiceClient creation have just a method that have been invoked that have HttpRequestMessage as a parameter and doesn't contain Tenant info. This scenario is valuable, in my mind, becouse i can use token cache. Any best practice?  
[AB#7231](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7231)

**Comment by pschaeflein** [comment]
If you look at the Microsoft.Identity.Web.MicrosoftGraph project, you will see that they [extend the BaseRequest,](https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web.MicrosoftGraph/BaseRequestExtensions.cs) putting an Options object in a property bag of the request. The authentication provider [can then pull that object off the request ](https://github.com/AzureAD/microsoft-identity-web/blob/00fc7c31f915ecde4fcf7131c0d00ff921a27b47/src/Microsoft.Identity.Web.MicrosoftGraph/TokenAcquisitionAuthenticationProvider.cs#L31)and act accordingly.

Using this pattern, you can have a method similar to `WithAppOnly` that can pass the tenant data to the auth provider.

**Comment by guru98** [comment]
@pschaeflein  Thanks i worked in the way you have suggest and it works. Thanks a lot

**Comment by andrueastman** [comment]
@guru98 I am closing this issue as it seems the question has been resolved.
