### ISSUE TITLE
[Client bug]: C#, GraphApi multiple file attachments >4MB

### ISSUE THREAD

**Issue by tim1970** [microsoftgraph/msgraph-sdk-dotnet#840]
I have the following issue, everything up until this point is working but the final bit (below) is causing an exception and I can't work out why.
Essentially, I am getting the mail attachments, totaling their size and then making a decision on whether to attach as normal or use the large file chunking method.
The problem I have is that after creating a draft email and then creating the attachment (zipped as it may be many little files), I create the upload session (which works), I get the chunkrequests using GetUploadChunkRequests() and the in a foreach loop I do the following:
`var result = await chunkedUploadProvider.GetChunkRequestResponseAsync(chunk, trackedExceptions);`
and this is where it causes an exception saying:
```
"Code: generalException\r\nMessage: An error occurred sending the request.\r\n"

{"Stream does not support reading."}”
```
I have checked and `myStream `is both readable and writeable, the uploadUrl in the response from CreateUploadSession is different from the documentation eg:
Documentation: https://outlook.office.com/api/v2.0/Users......
What I get returned: https://outlook.office.com/api/gv1.0/Users....

Do you have any ideas as to why this happening?
Thanks
tim

**Comment by tim1970** [comment]
gave up and have used HttpRequestMessage instead. Works fine.

**Comment by Sn3akyP3t3** [comment]
For anyone that stumbles across this and needs to find the root cause rather than just failing over to something else try using the [debug settings in VS as described here](https://stackoverflow.com/questions/67165974/microsoft-graph-httpprovider-error-on-file-upload) and look over the inner exception.

**Comment by Sn3akyP3t3** [comment]
Alternatively, use LargeFileUploadTask here https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp
