### ISSUE TITLE
Search From GraphServiceClient Results don't match results from Graph Explorer 

### ISSUE THREAD

**Issue by j-winter-c42** [microsoftgraph/msgraph-sdk-dotnet#841]
**Describe the bug**
When using the SDK's GraphServiceClient with the following request we get no results back.
`graphClient.Drives[driveUid].Search(itemName).Request()`

However, when we grab the request URL from this request we get a URL like
`https://graph.microsoft.com/v1.0/drives/[driveUid]/microsoft.graph.search(q='[itemName]')`
and when we paste this into the Graph Explorer we get our expected result of a handful of files. 

We also manually called the api via a HttpClient and got our expected result just like using the graph explorer. 

It looks like to us there is a bug in the .Search method in the SDK.

**Expected behavior**
We expect that making the request through the SDK, Graph Explorer, and from an HttpClient should all return the same result. 
 
[AB#7232](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7232)

**Comment by pschaeflein** [comment]
One thing to check: the token used by the SDK has the same scopes are the token used by GE.

**Comment by MIchaelMainer** [comment]
What Paul said is the first check. 

I couldn't reproduce your issue. The following call works as expected.
Did you mean to use `await client.Users["user"].Drives["id"].Search("itemname").Request().GetAsync();`?

**Comment by ddyett** [comment]
if the token isn't correct shouldn't an appropriate error code have been returned instead of no results?

**Comment by pschaeflein** [comment]
In GE, the call is delegated with the context of the logged-in user.

In the code, the context could be app-only or a different user. Both can return 'success', but with different results.

**Comment by MIchaelMainer** [comment]
Please reopen if this is still an issue. No repro.
