### ISSUE TITLE
PutAsync methods are not generated for EntityRequest classes.

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-dotnet#844]
If `CanUpdate` is true, we get `PutAsync` for `EntityReferenceRequest` classes, but not for `EntityRequest` classes.

In comparison, Java SDK blindly generates `put()` methods.

As per our conversation with @MIchaelMainer, there is no deterministic way of checking whether a service endpoint supports PUT.

I am creating this issue to investigate whether we can find a signal to generate `PutAsync` methods.

If not, maybe we should be in sync with Java and generate them for every `EntityRequest`. The implication of that would be having a method that may not function with the service, but available in the SDK. And if we find the signal later on, removing non-functioning `PutAsync`s will be a breaking change. 
[AB#6805](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6805)

**Comment by zengin** [comment]
Example scenario:
https://docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-beta&tabs=csharp#request-3

**Comment by zengin** [comment]
In the past, we seem to have added a partial to support one particular scenario:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/1c33ddf3c5d3295ee3c349bf13c3d3af2e38ac59/src/Microsoft.Graph/Requests/Extensions/TeamRequestExtensions.cs

**Comment by MIchaelMainer** [comment]
So, our choices really are:
1) Generate PUT for all update scenarios (like Java) even though it most of the generated APIs won't do anything.
2) We add a custom annotation that triggers the generation of the PUT method signatures. Means we maintain annotations to support this behavior.
3) Continue to add custom partials to support the PUT scenarios.

**Comment by ddyett** [comment]
@andrueastman can we look at this in the March milestone?

**Comment by andrueastman** [comment]
Sure thing.
