### ISSUE TITLE
Where is the documentation that describes how to create different types of users?

### ISSUE THREAD

**Issue by sam-wheat** [microsoftgraph/msgraph-sdk-dotnet#847]
[Overview of user accounts in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-overview)  gives us three kinds of accounts:

## Work account 

- A work account can access resources in a tenant, and with an administrator role, can manage tenants.

## Guest account

 - A guest account can only be a Microsoft account or an Azure Active Directory user that can be used to access applications or manage tenants.
## Consumer account

 - A consumer account is used by a user of the applications you've registered with Azure AD B2C. Consumer accounts can be created by:

[Overview of user accounts in Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-overview)  also tells us how each can be created:

- The user going through a sign-up user flow in an Azure AD B2C application
- Using Microsoft Graph API
- Using the Azure portal

Click on [Manage Azure AD B2C user accounts with Microsoft Graph](https://docs.microsoft.com/en-us/azure/active-directory-b2c/manage-user-accounts-graph-api)

Click on [Create a User](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http)

[Example 1](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=csharp) - of the three types of accounts described above, which one are we creating here?

[Example 2](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=csharp) - of the three types of accounts described above, which one are we creating here?

> the following table lists the properties that are required when you create a user. 

What kind of user?  Where is the table that shows what properties I need to set when creating a work account?  A guest account? A consumer account?

> For a B2C local account identity, only passwordProfile is required,

Is "B2C local account identity" a work account, a guest account, a consumer account, all the above, or none of the above?

**Comment by MIchaelMainer** [comment]
Hello @sam-wheat 

These are some really good questions for which I don't have an answer. Please x-post to https://docs.microsoft.com/en-us/answers/questions/topics/single/128354.html and link back to here. We should get more eyes on your question in that forum.

Thank you.
