### ISSUE TITLE
Inconsistent test results

### ISSUE THREAD

**Issue by sam-wheat** [microsoftgraph/msgraph-sdk-dotnet#850]
This design is worthy of a major award guys.  It cost me about 5 days to track down.    

       [TestMethod]
        public async Task CreateUserTest4()
        {
	        // Manually delete user first if necessary
            string myDomain = "myDomain.onmicrosoft.com";

            var user = new User { DisplayName = "John Smith" };
            user.Identities = new List<ObjectIdentity>()
            {
                    
                    new ObjectIdentity
                    {
                        SignInType = "emailAddress",
                        Issuer = myDomain,
                        IssuerAssignedId = "jsmith@yahoo.com"
                    }
            };

            user.PasswordProfile = new PasswordProfile
            {
                Password = "ABC12345!!",
                ForceChangePasswordNextSignIn = false
            };
            user.PasswordPolicies = "DisablePasswordExpiration";
            User addedUser = await graphService.CreateUser(user); // Passes.  User can log in as jsmith@yahoo.com.
        }

        [TestMethod]
        public async Task CreateUserTest5()
        {
	        // Manually delete user first if necessary
            string myDomain = "myDomain.onmicrosoft.com";

            var user = new User { DisplayName = "John Smith" };
            user.Identities = new List<ObjectIdentity>();
            user.PasswordProfile = new PasswordProfile();

            user.Identities.Append(new ObjectIdentity
                    {
                        SignInType = "emailAddress",
                        Issuer = myDomain,
                        IssuerAssignedId = "jsmith@yahoo.com"
                    });

            user.PasswordProfile = new PasswordProfile
            {
                Password = "ABC12345!!",
                ForceChangePasswordNextSignIn = false
            };
            user.PasswordPolicies = "DisablePasswordExpiration";
            User addedUser = await graphService.CreateUser(user); // Property accountEnabled value is required but is empty or missing.
        }

	    [TestMethod]
        public async Task CreateUserTest6()
        {
            string myDomain = "myDomain.onmicrosoft.com";

            var user = new User { DisplayName = "John Smith" };
            user.Identities = new List<ObjectIdentity>();
            user.PasswordProfile = new PasswordProfile();

            user.Identities.Append(
                    new ObjectIdentity
                    {
                        SignInType = "userName",
                        Issuer = myDomain,
                        IssuerAssignedId = "johnsmith"
                    });

            user.Identities.Append(new ObjectIdentity
            {
                SignInType = "emailAddress",
                Issuer = myDomain,
                IssuerAssignedId = "jsmith@yahoo.com"
            });

            user.PasswordProfile = new PasswordProfile
            {
                Password = "ABC12345!!",
                ForceChangePasswordNextSignIn = false
            };
            user.PasswordPolicies = "DisablePasswordExpiration";
            user.AccountEnabled = true;
            User addedUser = await graphService.CreateUser(user); // Property mailNickname value is required but is empty or missing.
        }
		
		[TestMethod]
        public async Task CreateUserTest7()
        {
            string myDomain = "myDomain.onmicrosoft.com";

            var user = new User { DisplayName = "John Smith" };
            user.Identities = new List<ObjectIdentity>();
            user.PasswordProfile = new PasswordProfile();

            user.Identities.Append(
                    new ObjectIdentity
                    {
                        SignInType = "userName",
                        Issuer = myDomain,
                        IssuerAssignedId = "johnsmith"
                    });

            user.Identities.Append(new ObjectIdentity
            {
                SignInType = "emailAddress",
                Issuer = myDomain,
                IssuerAssignedId = "jsmith@yahoo.com"
            });

            user.PasswordProfile = new PasswordProfile
            {
                Password = "ABC12345!!",
                ForceChangePasswordNextSignIn = false
            };
            user.PasswordPolicies = "DisablePasswordExpiration";
            user.AccountEnabled = true;
            user.MailNickname = "someUser";
            User addedUser = await graphService.CreateUser(user); // Property userPrincipalName value is required but is empty or missing.
        }

        [TestMethod]
        public async Task CreateUserTest8()
        {
            string myDomain = "myDomain.onmicrosoft.com";

            var user = new User { DisplayName = "John Smith" };
            user.Identities = new List<ObjectIdentity>();
            user.PasswordProfile = new PasswordProfile();

            user.Identities.Append(
                    new ObjectIdentity
                    {
                        SignInType = "userName",
                        Issuer = myDomain,
                        IssuerAssignedId = "johnsmith"
                    });

            user.Identities.Append(new ObjectIdentity
            {
                SignInType = "emailAddress",
                Issuer = myDomain,
                IssuerAssignedId = "jsmith@yahoo.com"
            });

            user.PasswordProfile = new PasswordProfile
            {
                Password = "ABC12345!!",
                ForceChangePasswordNextSignIn = false
            };
            user.PasswordPolicies = "DisablePasswordExpiration";
            user.AccountEnabled = true;
            user.MailNickname = "someUser";
            user.UserPrincipalName = user.MailNickname + "@" + myDomain;
            User addedUser = await graphService.CreateUser(user); // Passes but user cannot log in with eamil account.  Error message = We can't seem to find your account.
					
        }
		
		

        public async Task<User> CreateUser(User user)
        {
            var result = await client.Users.Request().AddAsync(user);
            return result;
        }

**Comment by sam-wheat** [comment]
Looks like I'm the one who deserves the major award.

`user.Identities.Append(new ObjectIdentity)` should be something like `user.Identities = user.Identities.Append(new ObjectIdentity)`

**Comment by sam-wheat** [comment]
This can be closed.  Issue was I was assigning to Identities incorrectly.

**Comment by zengin** [comment]
Thanks @sam-wheat for letting us know.
