### ISSUE TITLE
[Client bug]: C# Does not allow .Range() on a .Rows.ItemAt(x)

### ISSUE THREAD

**Issue by Benexx** [microsoftgraph/msgraph-sdk-dotnet#851]
**Describe the bug**
The `IWorkbookTableRowItemAtRequestBuilder` interface doesn't support support the Range() option. The API does support it and the generated documentation (from the [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)) states it is possible.

Working API request:
[GET] https://graph.microsoft.com:443/v1.0/me/drive/items/{driveItemId}/workbook/tables/{tableId}/rows/microsoft.graph.itemAt(index=0)/range

**To Reproduce**
Build the following request with a valid graphClient:
```
var result = await graphClient
    .Me
    .Drive
    .Items[driveItemId]
    .Workbook
    .Tables[tableId]
    .Rows
    .ItemAt(0)
    .Range() // Not supported
    .Request()
    .GetAsync();
```

**Expected behavior**
A result with a model of type `WorkbookRange`

**Client version**
NuGet package: Microsoft.Graph (3.20.0)
 
[AB#7234](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7234)

**Comment by MIchaelMainer** [comment]
This is being worked on in this PR: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/283
