### ISSUE TITLE
Missing required property 'Name'

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-dotnet#854]
I cloned the repo on my computer to study the code but when I open the project I get the following error from the Package Manager.

Error occurred while restoring NuGet packages: Invalid restore input. Missing required property 'Name'. Input files: C:\_xxxxxxxx\Produits\msgraph-sdk-dotnet\src\Microsoft.Graph\Microsoft.Graph.csproj.

Any hint ?
 
[AB#7233](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7233)

**Comment by pschaeflein** [comment]
I saw that as well. I used the dotnet cli to restore all the packages. At that point it would build.  I never actually resolved the error, but **Go To Definition (F12)** works, so I moved on. 

```shell
cd src\Microsoft.Graph
dotnet restore
```

**Comment by baywet** [comment]
which version of Visual Studio are you using? this can happen if you are using Visual Studio 2017 or 2019 but missing some updates.

**Comment by pschaeflein** [comment]
16.7.1 for me. I'll kick off an update tonight and test tomorrow.

**Comment by pschaeflein** [comment]
Updated to 16.8.2. Still get the error. 

Again, just an entry in the build log. The build succeeds.

**Comment by baywet** [comment]
interestingly I was running into the same issue as well. And commenting out the [VersionSuffix lines](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Microsoft.Graph.csproj#L26) + reloading the project all made it work.
