### ISSUE TITLE
Add support for C# 8 Nullable Reference Types

### ISSUE THREAD

**Issue by ascott18** [microsoftgraph/msgraph-sdk-dotnet#856]
**Is your feature request related to a problem? Please describe.**
When using this library in a project with C# nullable reference types, properties that can be null are not annotated and such and therefore induce a false sense of security around nulls.

See "Mail is not null here" when in fact it absolutely can be null for users who have no mailbox configured.
![image](https://user-images.githubusercontent.com/5017521/101194216-898d9280-3612-11eb-9892-6df5e9879c03.png)

**Describe the solution you'd like**
All public properties on public classes in this library should have nullability annotations that mirror the behavior of the graph API.

 
[AB#6865](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6865)

**Comment by MIchaelMainer** [comment]
Thank you @ascott18 

I totally agree that it would be appropriate to make this and a lot of other types nullable by definition. Our source metadata that we use to generate these models will need to have annotations.

At my team, let's discuss models and setting properties as nullable.

**Comment by MIchaelMainer** [comment]
We will need to target .NET Standard 2.1 to support this. We will need to update the generator.

**Comment by naamunds** [comment]
This would be useful for my team as well.  Note that C# 10 introduced [some attributes](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis) to help the compiler perform null-state static analysis; these are useful in adopting nullable context.

Any updates on when this might be available for this SDK?

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1628
