### ISSUE TITLE
Onedrive Personal not working due to different scopes

### ISSUE THREAD

**Issue by krackinDev** [microsoftgraph/msgraph-sdk-dotnet#86]
So when I was trying to figure out how to authenticate properly on the OneDrive for business , i came across the graph sdk and it works great. However when i now tried to point it to my original personal onedrive  i get the following error **Message: Must be authenticated to use '/drive' syntax**. Then after some digging and trial and error i found this [https://github.com/OneDrive/onedrive-api-docs/issues/369](url). however graph API only supports files.readwrite and not onedrive.readwrite. and vice versa for onedrive personal. Do we know when they are going to sync them up to support both? through the graph sdk? Unless I am missing something completely...

Im guessing because this is very new that hasnt been gotten around to it yet. I am able to use the onedrive sdk for personal and graph sdk for business for now but would prefer to have one onedrive service class.

**Comment by MIchaelMainer** [comment]
You can use files.readwrite to access personal OneDrive files. I've got this working with a couple of samples.
I've got a pull request that updates the sample to upload a file. https://github.com/microsoftgraph/uwp-csharp-snippets-sample/pull/16
