### ISSUE TITLE
[Client bug]: Group creation with members fails

### ISSUE THREAD

**Issue by zvrba** [microsoftgraph/msgraph-sdk-dotnet#860]
**Describe the bug**
I am trying to create a group that is prepopulated with members and owners; this is supported by the API as per https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http

**To Reproduce**
```
            var u = await graphClient.Users["EXISTING-USER-GUID"].Request().GetAsync();
            var p = await graphClient.ServicePrincipals["EXISTING-SP-GUID"].Request().GetAsync();
            var g = new Group {
                DisplayName = "StianTest - DELETEME",
                MailEnabled = false,
                MailNickname = "qc-stiantest-deleteme",
                SecurityEnabled = true,
                Members = new GroupMembersCollectionWithReferencesPage { u }
            };
            g = await graphClient.Groups.Request().AddAsync(g);
```

This fails with the following exception:

Microsoft.Graph.ServiceException
  HResult=0x80131500
  Message=Code: Request_BadRequest
Message: A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.

Is there a workaround?

**Client version**
Assembly version 3.19.0

**Desktop (please complete the following information):**
 - Windows 10, Edge

EDIT: The use case is relevant as this concerns application permissions. Some admins are fine with granting Group.Create permission, but not Group.ReadWrite.All permission which would be needed to add owners/members after the fact.

**Comment by MIchaelMainer** [comment]
I created an extension method to help with this missing scenario. 

```csharp
var u = await client.Users["EXISTING-USER-GUID"].Request().GetAsync();

var g = new Microsoft.Graph.Group
{
	DisplayName = "StianTest - DELETEME",
	MailEnabled = false,
	MailNickname = "qc-stiantest-deleteme",
	SecurityEnabled = true
};

g.AddMember(u.Id);	
g = await client.Groups.Request().AddAsync(g);
```

```csharp
public static class GroupExtension
{
	public static void AddMember(this Microsoft.Graph.Group group, string userId)
	{
		if (group.AdditionalData == null)
		{
			group.AdditionalData = new Dictionary<string, object>();
		}

		string[] membersToAdd = new string[1];
		membersToAdd[0] = $"https://graph.microsoft.com/v1.0/users/{userId}";
		group.AdditionalData.Add("members@odata.bind", membersToAdd);
	}

	public static void AddOwner(this Microsoft.Graph.Group group, string userId)
	{
		if (group.AdditionalData == null)
		{
			group.AdditionalData = new Dictionary<string, object>();
		}

		string[] ownersToAdd = new string[1];
		ownersToAdd[0] = $"https://graph.microsoft.com/v1.0/users/{userId}";
		group.AdditionalData.Add("owners@odata.bind", ownersToAdd);
	}
}
```

**Comment by zvrba** [comment]
This worked. Thanks for the quick reply.

**Comment by pschaeflein** [comment]
Hey @MIchaelMainer  - I've added this to the Community Library. Thanks for providing it!

I'm guessing this is the approach for other collections that have an *@odata.bind property. (Teams has a few of those.)
