### ISSUE TITLE
Unique Body of emails is null when queried using GraphServiceClient

### ISSUE THREAD

**Issue by thisisjagan** [microsoftgraph/msgraph-sdk-dotnet#862]
**Describe the bug**
I am trying to get the UniqueBody of all emails in an User's Inbox using C# Graph Service Client. But it is always null. However the same field is non-null when queried using Postman or Graph Explorer.

**To Reproduce**
1. Create a Graph Service Client.
2. Query the Email Messages as below.

IMailFolderMessagesCollectionPage MessagesCollectionPage = GraphClient
                    .Users[_config.GraphAPIConfig.UserId]
                    .MailFolders
                    .Inbox
                    .Messages
                    .Request()
                    .Header("Prefer", "outlook.body-content-type='text'")
                    .OrderBy("receivedDateTime")
                    .GetAsync()
                    .Result;

3. All messages in MessagesCollectionPage are missing Unique Body.

**Expected behavior**

The UniqueBody element represents an HTML fragment or plain text which represents the unique body of every conversation/email.

The same field is available when queried via Postman/Graph Explorer.

**Screenshots**

![image](https://user-images.githubusercontent.com/41620595/102075478-4f02d180-3e2c-11eb-88f7-d2ea3379d208.png)

![image](https://user-images.githubusercontent.com/41620595/102075569-70fc5400-3e2c-11eb-846e-7a3a08158ca8.png)

Visual Studio: 2019
.NET Core Console App.
Version of Graph SDK: 3.21.0

**Comment by MIchaelMainer** [comment]
I'm not seeing the same behavior with Graph Explorer. I don't see the UniqueBody unless I explicitly select it. 

It looks like that property needs to be explicitly selected.

```csharp
	IMailFolderMessagesCollectionPage MessagesCollectionPage = client
	.Users[Chambele.V1.user]
	.MailFolders
	.Inbox
	.Messages
	.Request()
	.Header("Prefer", "outlook.body-content-type='text'")
	.Select(m => m.UniqueBody)
	.OrderBy("receivedDateTime")
	.GetAsync()
	.Result;
```

**Comment by thisisjagan** [comment]
Thank you so much. I have validated and it works when selecting explicitly. Appreciate the help.

![image](https://user-images.githubusercontent.com/41620595/102320344-2c92c480-3fa2-11eb-995d-763f8becc83e.png)
