### ISSUE TITLE
Documentation: Add request example for something other than GraphServiceMe

### ISSUE THREAD

**Issue by dli9431** [microsoftgraph/msgraph-sdk-dotnet#866]
on https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/overview.md under "Request calls" please include an example that calls something other than the "Me" endpoint.

IE:
`var usersRequest = await graphServiceClient.Users.Request().Filter("startsWith(jobTitle, 'Some Job')").GetAsync();`

**Comment by MIchaelMainer** [comment]
Thank you for contacting us!

We generate examples for our client libraries in our core API documentation. Please use the API documentation as your primary source for code examples. 

https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp#request-1
https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp#request-2
https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=csharp
