### ISSUE TITLE
Retrieving, saving user object results in an error

### ISSUE THREAD

**Issue by sam-wheat** [microsoftgraph/msgraph-sdk-dotnet#868]
In the test method below I retrieve a user, make no changes, then save it back to the db with an update statement. 
The problem here is that I need to be able to update some columns on my own schema (see `USER_FIELDS` below).  How do I do that?

Thanks

See also:
https://github.com/MicrosoftDocs/azure-docs/issues/53168
https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http

### Expected behavior

The un-modified user object is saved.

### Actual behavior

Message: 
    Test method UpdateUserTest threw exception: 
    Microsoft.Graph.ServiceException: Code: Request_BadRequest
    Message: Adding a non-federated user signInType is not permitted if the user only has social/federated identities or no identities set. Please recreate the user with a non-federated identity along with existing identities if any.
    Inner error:
    	AdditionalData:
    	date: 2021-01-05T02:57:58
    	request-id: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
    	client-request-id: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
    ClientRequestId: 046d86a3-9e8f-4bd1-9d4f-e2c7e8e6a03d
	

### Steps to reproduce the behavior

        [TestMethod]
        public async Task UpdateUserTest2()
        {
            string userID = "a00afd9b-af51-4206-bd9f-2621343bc70d";
            User user = (await graphService.FindUser(userID)).First();
			// Don't modify anything.  Just save it again.
            await graphService.UpdateUser(user);
        }
		
		
		
		
		
		private string USER_FIELDS = $"id, userprincipalname, mail, displayname, mailnickname, accountenabled, identities, othermails, {UserAttributes.BillingID}, {UserAttributes.IsBanned}, {UserAttributes.IsCorporateAdmin}, {UserAttributes.IsOptIn}, {UserAttributes.PaymentProviderCustomerID}, {UserAttributes.SuspendedUntil}";
		
        public async Task<List<User>> FindUser(string id)
        {
            var page = client.Users.Request()
                 .Select(USER_FIELDS);

            if (!string.IsNullOrEmpty(id))
                page = page.Filter($"id eq '{id}'");

            List<User> users = null;
            try
            {
                users = (await page.GetAsync())?.ToList();
            }
            catch (Microsoft.Graph.ServiceException)
            {

            }
            return users;
        }
		
		
		
        public async Task UpdateUser(User user)
        {
            var result = await client.Users[user.Id]
            .Request()
            .UpdateAsync(user);
        }

Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [X ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ X] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ X] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

**Comment by sam-wheat** [comment]
See also [this question](https://stackoverflow.com/questions/65660374/use-azure-ad-graph-to-update-values-on-the-additionalvalues-dictionary-for-a-u).

**Comment by MIchaelMainer** [comment]
Hello again @sam-wheat 

Thank you for asking this question and cross-posting to StackOverflow. I don't have an answer for this service API question. I'm interested to see what the answer may be on StackOverflow. 

I'm not familiar with `{UserAttributes.BillingID}, {UserAttributes.IsBanned}, {UserAttributes.IsCorporateAdmin}, {UserAttributes.IsOptIn}, {UserAttributes.PaymentProviderCustomerID}, {UserAttributes.SuspendedUntil}`. What are these?

**Comment by sam-wheat** [comment]
Hi @MIchaelMainer , {UserAttributes.BillingID} etc.. are extension properties.  The question on StackOverflow relates to Azure AD.

**Comment by MIchaelMainer** [comment]
Per documentation https://docs.microsoft.com/en-us/graph/extensibility-open-users, you'll need to update the extension properties separate from the user properties. You'll need to define your extension class.

```csharp
	// Create your extension class derived from Microsoft.Graph.Extension.
	// Define your properties on DerivedFromExtension with serialization instructions. Otherwise,
	// you can set the properties via AdditionalData property.
	var extension = new Microsoft.Graph.DerivedFromExtension();
	
	await client.Me.Extensions["extensionName"].Request().UpdateAsync(extension);
```

**Comment by sam-wheat** [comment]
@MIchaelMainer 
>  Per documentation https://docs.microsoft.com/en-us/graph/extensibility-open-users, you'll need to update the extension properties separate from the user properties. You'll need to define your extension class.

1.) Please copy/paste text from the link you cited that states or implies "you'll need to update the extension properties separate from the user properties".

2.) Please provide a link to the documentation or code for `Microsoft.Graph.Extension`.

3.) Should this test pass?

	    // UserAttributes.BillingID is just a string constant:
	    // extension_b0d39858f7814b429dcf4e52d243296a_
		
	    [TestMethod]
        public async Task UpdateUser()
        {
            string userID = "33c2780f-b5c6-41d5-bd03-98668c36b0d8"; 
            User user = (await graphService.FindUser(userID)).First();
            await graphService.UpdateUser(user); // No change, no error.

            if (user.AdditionalData == null)
                user.AdditionalData = new Dictionary<string, object>();

            // Set a user attribute and an extended attribute and update
            // both at the same time
            user.DisplayName = "Bob";
            user.AdditionalData[UserAttributes.BillingID] = "ABC";
            await graphService.UpdateUser(user);
            // Get the user again
            user = (await graphService.FindUser(userID)).First();
            // Verify the change
            Assert.IsNotNull(user.AdditionalData);
            Assert.AreEqual("Bob", user.DisplayName);
            Assert.AreEqual("ABC", user.AdditionalData[UserAttributes.BillingID]);

            // Set a user attribute and an extended attribute and update
            // both at the same time
            user.AdditionalData[UserAttributes.BillingID] = null;
            user.DisplayName = "Sam";
            await graphService.UpdateUser(user);
            // Get the user again
            user = (await graphService.FindUser(userID)).First();
            // Verify the change
            Assert.IsNull(user.AdditionalData); // Nothing to retrieve
            Assert.AreEqual("Sam", user.DisplayName);
        }

Thank you.
