### ISSUE TITLE
[Client bug]: Creating a new Team (Teams.Request().AddAsync) always returns null

### ISSUE THREAD

**Issue by gunner13** [microsoftgraph/msgraph-sdk-dotnet#871]
**Describe the bug**
The "AddAsync" method of Teams always returns NULL value, I was trying to get the ID of the new team after creating it.

My code was like:

            string ownerID = ConfigurationManager.AppSettings["DefaultChannelOwnerID"];
            var members = new TeamMembersCollectionPage();
            members.Add(new AadUserConversationMember()
            {
                Roles = new List<String>()
                        {
                            "owner"
                        },
                AdditionalData = new Dictionary<string, object>()
                        {
                            {"user@odata.bind", "https://graph.microsoft.com/v1.0/users('"+ ownerID +"')"}
                        }
            });

            var team = new Team()
            {
                DisplayName = teamName,
                Members = members,
                AdditionalData = new Dictionary<string, object>()
                {
                    {"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"}
                }
            };

            var result = await graphClient.Teams.Request().AddAsync(team);

            return result.Id;

I even tried this: 

            var team = new Team()
            {
                DisplayName = teamName,
                Members = members,
                AdditionalData = new Dictionary<string, object>()
                {
                    {"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"}
                }
            };

            await graphClient.Teams.Request().AddAsync(team);

            return team.Id;

In both cases, I could not retrieve the team id.

 
[AB#7236](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7236)

**Comment by MIchaelMainer** [comment]
This [POST API doesn't return the created Team information in the body](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http) so there is no team to deserialize from the response. And since we don't have an object to return, we haven't provided access to the information in the response headers which does have the team identifier in it. 

@andrueastman If you haven't already, as part of the 2.0 work, we should consider returning a GraphResponse<T> object that provides access to the header and status information, in addition to the type defined by T.

@gunner13 As a workaround, you'll need to do something like this:

 ```csharp

        #var result = await graphClient.Teams.Request().AddAsync(team);

	var httpRequestMessage = client.Teams.Request().GetHttpRequestMessage();
	httpRequestMessage.Content = client.HttpProvider.Serializer.SerializeAsJsonContent(team);
	var httpResponseMessage = await client.HttpProvider.SendAsync(httpRequestMessage);

	if (httpResponseMessage.IsSuccessStatusCode)
	{
		IEnumerable<string> headerValues;
		if (httpResponseMessage.Headers.TryGetValues("Content-Location", out headerValues))
		{
			string teamid = headerValues.First().Split('/', 2, StringSplitOptions.RemoveEmptyEntries)[1];
		}
	}
```

**Comment by andrueastman** [comment]
@MIchaelMainer This has already been done 
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/eb8ce364eb9c95b027a77ec83166bd402b80d50f/src/Microsoft.Graph.Core/Requests/GraphResponse.cs#L42

**Comment by jnborche** [comment]
@MIchaelMainer Facing the same problem as gunner13 I tried to replace my AddAsync(team) call with your workaround code but unfortunately "await client.HttpProvider.SendAsync(httpRequestMessage)" never returns even when trying to create a basic name-only Team.

**Comment by MCKRUZ** [comment]
Any update as to the status of this bug?  I'm still experiencing this exact issue on the current version of the product.

**Comment by andrueastman** [comment]
Closing this as the new v4 previews provide direct access to the response headers and status codes. More info in the guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graph-response) and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935.

Ideally, in this scenario, SDK users can now make a call that looks something like this.
```cs
var team = new Team()
{
    DisplayName = "teamName",
    Members = new TeamMembersCollectionPage(),
    AdditionalData = new Dictionary<string, object>()
    {
        {"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"}
    }
};

var teamResponse = await graphClient.Teams.Request().AddResponseAsync(team);
if (teamResponse.HttpHeaders.TryGetValues("Location", out var headerValues))
{
    var teamId = headerValues?.First().Split('\'', StringSplitOptions.RemoveEmptyEntries)[1];
}
```
