### ISSUE TITLE
filter endswith

### ISSUE THREAD

**Issue by hannespreishuber** [microsoftgraph/msgraph-sdk-dotnet#872]
in graph explorer something works like 
https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(userPrincipalName,'ppedv.de')
https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(mail,'ppedv.de')
using the .net sdk 

doesnt work
= Await graphClient.Users.Request.Filter("endsWith(mail, 'e')").GetAsync

Microsoft.Graph.ServiceException
  HResult=0x80131500
  Nachricht = Code: Request_UnsupportedQuery
Message: Unsupported Query.

works with startsWith Filter

 
[AB#7237](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7237)

**Comment by MIchaelMainer** [comment]
I can't get this to work with Graph Explorer with the default demo user. Do you have a query you can share that works with that default user?

https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(userprincipalname%2C'.com')&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com

**Comment by hannespreishuber** [comment]
did some research. You are right - endwiths doenst work, except adding header pair ConsistencyLevel eventual.

My guess is the header is in some others of the example querys - so it keeped for my endswith 

frist test with MSgraph SDK object add header value by .Header("ConsistencyLevel","eventual") still fails with unsuportedQuery

**Comment by Licantrop0** [comment]
@hannespreishuber [this .NET sample](https://github.com/microsoftgraph/dotnet-aad-query-sample) will clarify the usage of the .NET SDK with the advanced query capabilities, let me know if you have any further questions.

**Comment by hannespreishuber** [comment]
ok, after reverse engineering the wpf sample . $count is mandatory + ConsistencyLevel

working sample

`  
 
      
        Dim options = New List(Of [Option])

        options.Add(New QueryOption("$filter", "endsWith(mail, 'e')"))

        options.Add(New HeaderOption("ConsistencyLevel", "eventual"))

        options.Add(New QueryOption("$count", "true"))

        Dim uuu = Await graphClient.Users.Request(options).GetAsync

`
