### ISSUE TITLE
BatchRequest Prefer header

### ISSUE THREAD

**Issue by kudecha** [microsoftgraph/msgraph-sdk-dotnet#874]
Hi

I am using API v3.9.0 in my C# asp.net web app to communicate with O365 data, Active Directory User Events to be specific.

I could successfully retrieve Events data in NZ timezone instead of default UTC, using a 'Prefer' header with value 'outlook.timezone="New Zealand Standard Time"' for each request.

However while trying to pull Events for multiple Users using Batch request, adding 'Prefer' header to following cases does not return data with NZ Timezone.
  a. IBatchRequest headers add feature does not help.
  b. adding Prefer to individual BatchRequestStep within BatchRequestContent - which is posted to BatchRequest - does not help either.

Request body which contains array of requests.
Each request has 3 properties only, 'id', 'url' and 'method'.

Would you please suggest how to pass 'Prefer' header?

Thanks,
Jay

 
[AB#7592](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7592)

**Comment by andrueastman** [comment]
Hey kudecha!
Any chance you could share a snippet of code you are using to create a batch request step?

According to [this](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/015f3761f2357ebd439936e6c278d350fc8646ec/src/Microsoft.Graph.Core/Requests/Content/BatchRequestContent.cs#L208), you should probalby have something looking like this.
```cs
HttpRequestMessage httpRequestMessage1 = new HttpRequestMessage(HttpMethod.Get, "https://graph.microsoft.com/v1.0/me/events?$select=subject,organizer,attendees,start,end,location");
httpRequestMessage1.Content = new StringContent("");
httpRequestMessage1.Content.Headers.Add("Prefer", "outlook.timezone=\"New Zealand Standard Time\"");

// Add batch request steps to BatchRequestContent.
BatchRequestContent batchRequestContent = new BatchRequestContent();
batchRequestContent.AddBatchRequestStep(httpRequestMessage1);

// Send batch request with BatchRequestContent. 
HttpResponseMessage response = await httpClient.PostAsync("https://graph.microsoft.com/v1.0/$batch", batchRequestContent);
```

If this is helpful, please feel free to close this issue.

**Comment by kudecha** [comment]
Hi Eastman,

Thanks for your help. Yes it worked.

I was adding Prefer header to the main request header, similar to requesting it individually.
Adding Prefer header to each HttpRequestMessage's content worked, as suggested.

Thanks again!!!
