### ISSUE TITLE
No way to call https://graph.microsoft.com/v1.0/users/$count 

### ISSUE THREAD

**Issue by ascott18** [microsoftgraph/msgraph-sdk-dotnet#875]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to use the SDK to call `https://graph.microsoft.com/v1.0/users/$count`.

**Describe the solution you'd like**
A method, something like `client.Users.CountAsync()`

**Describe alternatives you've considered**
If this is already possible, documentation that explains how to do so. A search of the source code of this repo for "$count" yielded zero results, so I suspect it isn't.

**Additional context**
I was able to achieve a somewhat similar result with this query, but its less than ideal because I still have to pull back one user that I don't actually need. The actual code is also just not very clean and feels very circuitous for something simple:
![image](https://user-images.githubusercontent.com/5017521/104767679-6a117b80-5721-11eb-9b16-6915c875ba49.png)

 
[AB#7618](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7618)

**Comment by andrueastman** [comment]
Hi @ascott18, Thanks for raising this issue. 

At the moment it seems you might not be able to make the request in a fluent way as you described. You can however avoid fetching the extra user by doing something like this. 
```cs
GraphServiceClient graphClient = new GraphServiceClient(delegatingAuthProvider);
string requestUrl = graphClient.Users.AppendSegmentToRequestUrl("$count");
Option [] options = new Option[] { new HeaderOption("ConsistencyLevel", "eventual") };
HttpResponseMessage responseMessage = await new UserRequest(requestUrl, graphClient, options)
                                        .SendRequestAsync(null,CancellationToken.None);
string userCount = await responseMessage.Content.ReadAsStringAsync();
```

**Comment by NCC1701M** [comment]
@andrueastman 
It's not just the count it self whats problematic. Without those headers the following request throws an exception:
```csharp
var users = await client.Users.Request(options).Filter("startswith(surname, 'Smith')").OrderBy("displayName").GetAsync();
```

The request would fail with the following error message:
> Code: Request_UnsupportedQuery
> Message: Sorting not supported for current query.

My suggestion would be to add a Count() method like: 
```csharp
var users = await client.Users.Request(options).Count().Filter("startswith(surname, 'Smith')").OrderBy("displayName").GetAsync();
```
To retrieve a filtered list and maybe
```csharp
var users = await client.Users.Request(options).Count().GetAsync();
```
to perform a real count request (`https://graph.microsoft.com/v1.0/users/$count`)

**Comment by andrueastman** [comment]
This a totally valid suggestion and we shall work towards adding support for the [CountSegment ](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingtheCountofaCollection) in the SDK

**Comment by pschaeflein** [comment]
I've considered adding a Count method to the [Graph.Community library](https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib). My concern is that the Count segment is not universally supported by the constituent services on Microsoft Graph. 

In theory, an extension could be added for requests that support it, but at first glance I didn't see common ancestor/interface and I don't currently have the bandwidth to find them all. 

Is native support in the SDK a semester or two away? Would hate to code it just to remove it...

**Comment by andrueastman** [comment]
@pschaeflein We would have to first investigate if the Count segment is not indeed universally supported so that we update the generator with the appropriate calls. 
Once this is done, I believe we can come back with a reasonable estimate of when this can be accomplished.

**Comment by NCC1701M** [comment]
@andrueastman 
I would suggestion to use more "base" interfaces. Please take a look at the feature request I've created (#880)

More abstract interface could also help you with this issue.

**Comment by andrueastman** [comment]
@NCC1701M Thanks for this.

**Comment by andrueastman** [comment]
Closing this for now, with the latest Kiota based previews you should be able to make a call as shown below as outlined in th upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#support-for-count-in-request-builders).

```cs
var count = await graphServiceClient.Users.Count.GetAsync(requestConfiguration => requestConfiguration.Headers.Add("ConsistencyLevel","eventual"));
```
