### ISSUE TITLE
Will two calendar events have the same id in one calendar? 

### ISSUE THREAD

**Issue by hxt1994** [microsoftgraph/msgraph-sdk-dotnet#879]
Will two calendar events have the same id in one calendar?
It seems that we got the same calendar event id in one calendar, so we want to know if it is possible to generate the same event id with graph way.

 
[AB#7696](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7696)

**Comment by andrueastman** [comment]
Hey @hxt1994,
I believe the id field should be unique. Any chance you could share more info on how this came to pass? Did you create the events via the graph api?

**Comment by hxt1994** [comment]
@andrueastman  thanks, I have got the two ids from the customer. and I found there is only one different character in a different case.(W and w). The developers do the judge with no case sensitive.

**Comment by andrueastman** [comment]
Thanks for clearing that up.
I believe we can close this issue now. Yes?

**Comment by hxt1994** [comment]
@andrueastman  yes, thanks
