### ISSUE TITLE
More base interfaces

### ISSUE THREAD

**Issue by NCC1701M** [microsoftgraph/msgraph-sdk-dotnet#880]
Although you use Interface for example for requests, there are at least some interface which could extend a more abstract interface.

Let's take `IGraphServiceUsersCollectionRequest` and `IGraphServiceGroupsCollectionRequest` for example. Both extends `IBaseRequest` but if you have a closer look at the implementation of both interfaces you will see the following:

IGraphServiceUsersCollectionRequest is defined as:
```csharp
public interface IGraphServiceUsersCollectionRequest : IBaseRequest
{
  Task<User> AddAsync(User user);
  Task<User> AddAsync(User user, CancellationToken cancellationToken);
  IGraphServiceUsersCollectionRequest Expand(string value);
  IGraphServiceUsersCollectionRequest Expand(Expression<Func<User, object>> expandExpression);
  IGraphServiceUsersCollectionRequest Filter(string value);
  Task<IGraphServiceUsersCollectionPage> GetAsync();
  Task<IGraphServiceUsersCollectionPage> GetAsync(CancellationToken cancellationToken);
  IGraphServiceUsersCollectionRequest OrderBy(string value);
  IGraphServiceUsersCollectionRequest Select(string value);
  IGraphServiceUsersCollectionRequest Select(Expression<Func<User, object>> selectExpression);
  IGraphServiceUsersCollectionRequest Skip(int value);
  IGraphServiceUsersCollectionRequest Top(int value);
}
```

Whereas IGraphServiceGroupsCollectionRequest is defined as:
```csharp
public interface IGraphServiceGroupsCollectionRequest : IBaseRequest
{
  Task<Group> AddAsync(Group group);
  Task<Group> AddAsync(Group group, CancellationToken cancellationToken);
  IGraphServiceGroupsCollectionRequest Expand(string value);
  IGraphServiceGroupsCollectionRequest Expand(Expression<Func<Group, object>> expandExpression);
  IGraphServiceGroupsCollectionRequest Filter(string value);
  Task<IGraphServiceGroupsCollectionPage> GetAsync();
  Task<IGraphServiceGroupsCollectionPage> GetAsync(CancellationToken cancellationToken);
  IGraphServiceGroupsCollectionRequest OrderBy(string value);
  IGraphServiceGroupsCollectionRequest Select(string value);
  IGraphServiceGroupsCollectionRequest Select(Expression<Func<Group, object>> selectExpression);
  IGraphServiceGroupsCollectionRequest Skip(int value);
  IGraphServiceGroupsCollectionRequest Top(int value);
}
```

As you can see, both interfaces provide the same methods with only minor changes and those changes could be also implemented by using generics like this:
```csharp
public interface IGraphServiceBaseCollectionRequest<T> : IBaseRequest
{
  Task<T> AddAsync(T T);
  Task<T> AddAsync(T T, CancellationToken cancellationToken);
  IGraphServiceBaseCollectionRequest<T> Expand(string value);
  IGraphServiceBaseCollectionRequest<T> Expand(Expression<Func<T, object>> expandExpression);
  IGraphServiceBaseCollectionRequest<T> Filter(string value);
  Task<IGraphServiceBaseCollectionRequest<T>> GetAsync();
  Task<IGraphServiceBaseCollectionRequest<T>> GetAsync(CancellationToken cancellationToken);
  IGraphServiceBaseCollectionRequest<T> OrderBy(string value);
  IGraphServiceBaseCollectionRequest<T> Select(string value);
  IGraphServiceBaseCollectionRequest<T> Select(Expression<Func<T, object>> selectExpression);
  IGraphServiceBaseCollectionRequest<T> Skip(int value);
  IGraphServiceBaseCollectionRequest<T> Top(int value);
}

public interface IGraphServiceUsersCollectionRequest : IGraphServiceBaseCollectionRequest<User> {}

public interface IGraphServiceGroupsCollectionRequest : IGraphServiceBaseCollectionRequest<Group> {}
```

The problem now is, although both interface support the same methods and also the same extension methods you have to implement methods for both of them. You can't reduce it into a single method.

# Example
I can't just write a single method like this because there is no common base interface
```csharp
private IGraphServiceBaseCollectionRequest<T> ApplyFilter<T>(IGraphServiceBaseCollectionRequest<T> query, IFilterModel filter, string property)
{
  if (!string.IsNullOrEmpty(filter.Pattern))
    query = query.Filter($"startsWith({property}, '{filter.Pattern}')");
  
  if (filter.PageSize != null)
    query = query.Top(filter.PageSize.Value);
  
  if (filter.Sorting != null && filter.Sorting.Count() > 0)
  {
    var columns = string.Empty;
    foreach (var sort in filter.Sorting)
    {
      if (!string.IsNullOrEmpty(columns))
      columns += ",";
      
      columns += sort.Column;
    }
    query = query.OrderBy(columns);
  }
  
  return query;
}
```

To use the same algorithm I have to implement it twice one method to filter users and one to filter groups. But this should not be the goal. It's copy & paste and every developer learned, that this is an absolute no go.

So my feature request is to provide more abstract base interface to reduce "Copy&Paste" to a minimum. 
[AB#7697](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7697)

**Comment by khellang** [comment]
This problem has become much more prevalent with the move to Kiota. Take `CountRequestBuilder` as an example:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/582487/226296940-df33d0f5-3e8a-4c0f-ba8a-a369cabc4446.png">

There's now hundreds (!) of `CountRequestBuilder` types in scope. This is probably related to #1702 and #511 as well.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoft/kiota-abstractions-dotnet/pull/75

**Comment by olivermue** [comment]
We found the same issue (but already in V4) when it came to iterate all pages of an collection. While all these collection share a common base class `BaseCollectionPaginationCountResponse`, the concrete type of the `Value` property is explicitly implemented in every derived class. That avoid writing a generic extension for using `PageIterator<TItem, TCollection>`. To circumvent the code duplication for every type we wrote a text template like this:

```
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="NetStandard" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a text template.
//     Creation date: <#= DateTime.Now #>
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Graph;
using Microsoft.Graph.Models;

namespace MySolution.Extensions
{
    public static class GraphServiceCollectionResponseExtensions
    {
<#
    var pageTypes = new List<string>
    {
        "Device",
        "DirectoryObject",
        "DirectoryRole",
        "DriveItem",
        "Group",
        "List",
        "ListItem",
        "ManagedDevice",
        "User",
    };

    foreach (var type in pageTypes)
    {
#>
        public static async Task<IReadOnlyList<<#= type #>>> GetAll(this Task<<#= type #>CollectionResponse> collectionTask, GraphServiceClient serviceClient, int maxCount = int.MaxValue)
        {
            if (collectionTask == null)
                throw new ArgumentNullException(nameof(collectionTask));

            var response = await collectionTask;
            var items = new List<<#= type #>>();

            var iterator = PageIterator<<#= type #>, <#= type #>CollectionResponse>.CreatePageIterator(serviceClient, response,
                item => { items.Add(item); return items.Count < maxCount; });

            await iterator.IterateAsync();

            return items;
        }

<#
    }
#>
    }
}
```
If there is another collection type to iterate, we simply add the type to the `pageTypes` collection and everything else will be auto-generated. Not ideal, but works very well. Could be an approach also for the other mentioned types here if a common generic interface wouldn't be possible in Kiota (for whatever reasons).

Example of usage of the above generated extension method:
```csharp
var groupMembers = await serviceClient.Groups[groupId.ToString()].Members.GetAsync().GetAll(serviceClient);
```

**Comment by baywet** [comment]
Hi everyone,
Thank you for your patience on this matter, it was brought to my attention during the Microsoft MVP summit.
You might want to read [this lengthy answer](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1702#issuecomment-1998508499) to get additional context here.

## Interfaces

We decided to pull them back since:
1. they added to the size of the SDK
2. they were an easy way to source break anybody who implemented them whenever a new operation gets added.

## Base for extensibility 

The request builders now inherit the BaseRequestBuilder class. Using this to define an extension method means that method is going to be everywhere (not ideal). We currently don't have a great solution other than layering on top of the generated code for extensibility. Please join the conversation here https://github.com/microsoft/kiota/issues/908

## Repetition of request builder names in v5

I've provided detailed explanation in the other thread.

Please let us know if you have further questions/concerns
