### ISSUE TITLE
Wrong NextPageRequest URL when using German Umlauts

### ISSUE THREAD

**Issue by michaelmairegger** [microsoftgraph/msgraph-sdk-dotnet#881]
**Describe the bug**
If the initia request url contains German umlauts like ÜÖÄüäö then when executing the URL returned for NextPageRequest results in an empty result. By executing the same query within Graph Explorer then everything works.

**To Reproduce**
1. Go to 'https://developer.microsoft.com/en-us/graph/graph-explorer'
2. Query for subject that contains `über` e.g. `https://graph.microsoft.com/v1.0/me/messages?$filter=contains(subject,'Überweisung')`
3. Run Query
4. "@odata.nextLink" is `...=contains(subject%2c%27%C3%9Cberweisung%27)...`
5. This behavior is correct, since the Ü is encoded correctly.

Run the same query on C#:

    graphServiceClient.Me.Messages.Request().Filter($"contains(subject,'Überweisung')").GetAsync();

then the `NextPageRequest` is `...=contains(subject%2c%27%25u00dcberweisung%27)...`

Check the encoded value for Ü from `@odata.nextLink` and `NextPageRequest` which is completely different. Therefore `.NextPageRequest.GetAsync()` returns no value since the resulting query searches not for `Überweisung` but `%u00dcberweisung`.

If we decode the url returned from Graph Exporer and C# client then we have the following situation:

||Envoded Value|Decoded value|
|-|-|-|
|Graph Explorer|...=contains(subject%2c%27%C3%9Cberweisung%27)...|...=contains(subject,'Überweisung')...|
|C#|...=contains(subject%2c%27%25u00dcberweisung%27)...|...=contains(subject,'%u00dcberweisung')...|

Since the decoded value in C# is wrong, the next query searches for `%u00dcberweisung` instead of `Überweisung`

**Expected behavior**
C# should return a working url so that I can query for the next page

**Client version**
3.22.0

**Current workaround**
Omit the Umlaut and search for `berweisung`
 
[AB#7788](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7788)

**Comment by andrueastman** [comment]
@michaelmairegger Thanks for raising this issue and giving the detailed info. We shall investigate this and work towards implementing a fix.

**Comment by andrueastman** [comment]
This is resolved via microsoftgraph/msgraph-sdk-dotnet-core#255 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
