### ISSUE TITLE
NextPageRequest doesn't work when used with the ConsistencyLevel header

### ISSUE THREAD

**Issue by antonGritsenko** [microsoftgraph/msgraph-sdk-dotnet#884]
- SDK version 1.20.1
- OS: Windows 10

I want to get all users with specific email domain. Regarding docs, I have to use ConsistencyLevel set to eventual to do that.
Here is my code:
```
               var confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(adOptionsAccessor.Value.ClientId)
                .WithTenantId(adOptionsAccessor.Value.TenantId)
                .WithClientSecret(adOptionsAccessor.Value.ClientSecret)
                .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

            _graphClient = new GraphServiceClient(authProvider);

                var paged = await _graphClient
                .Users
                // $count required, otherwise you will get error "Unsupported query"
                .Request(new List<QueryOption>()
                {
                    new QueryOption("$count", "true")
                })
                // required
                .Header("ConsistencyLevel", "eventual")
                .Filter($"endsWith(mail,'{emailPostfix}')")
                .GetAsync();
            users.AddRange(paged.CurrentPage);

            while (paged.NextPageRequest != null)
            {
                var pageQuery = paged.NextPageRequest;
                paged = await pageQuery.GetAsync();
                users.AddRange(paged.CurrentPage);
            }
```

The query itself works fine, but as soon as I want to fetch next page using ```NextPageRequest.GetAsync();``` I got the error:
> Code: Request_UnsupportedQuery
> Message: Unsupported Query.
> Inner error:
>        AdditionalData:
>        date: 2021-01-27T12:19:20
>        request-id: c73df20e-1cff-439c-8bbe-3834a8cfaade
>        client-request-id: ***

I **does** work when I do all requests manually in the Postman. 
[AB#7815](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7815)

**Comment by antonGritsenko** [comment]
I have found the reason: NextPageRequest do not respect Headers of initial query. Workaround:
```
_graphClient = new GraphServiceClient(authProvider);

                var paged = await _graphClient
                .Users
                // $count required, otherwise you will get error "Unsupported query"
                .Request(new List<QueryOption>()
                {
                    new QueryOption("$count", "true")
                })
                // required
                .Header("ConsistencyLevel", "eventual")
                .Filter($"endsWith(mail,'{emailPostfix}')")
                .GetAsync();
            users.AddRange(paged.CurrentPage);

            while (paged.NextPageRequest != null)
            {
                var pageQuery = paged.NextPageRequest;
                // workaround!
                pageQuery.Header("ConsistencyLevel", "eventual");
                paged = await paged.NextPageRequest.GetAsync();
                users.AddRange(paged.CurrentPage);
            }
```

Have to be fixed in the SDK itself IMHO.

**Comment by pschaeflein** [comment]
Starting in v3.21, the PageIterator takes a delegate that  you can use to configure subsequent requests. An example is in the Test project: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/ca0fa346cf50db978d6d0db16d359d9d79103b1c/tests/Microsoft.Graph.DotnetCore.Test/Tasks/PageIteratorTests.cs#L368

**Comment by dondeetan** [comment]
I'll refactor the code to make sure of NextPageRequest call and pass headers. Will get back. Thank you!

**Comment by andrueastman** [comment]
We will not be fixing this as it is possible to configure subsequent requests with the PageIterator. Reference example can be found [here](https://docs.microsoft.com/en-us/graph/sdks/paging?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp#iterate-over-all-the-messages)
