### ISSUE TITLE
How to check status code 429 with graphserviceclient

### ISSUE THREAD

**Issue by ravicse23** [microsoftgraph/msgraph-sdk-dotnet#885]
Hi,

I am using below code to send email
await graphClient.Me.SendMail(message, true).Request().PostAsync()

in documentation, its mentioned that throttling behavior might occur if request is too high. So i want to check status code 429 and handle accordingly . 
Since PostAsync doesnt return anything, how do i check status code.

Thanks 
[AB#7823](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7823)

**Comment by ravicse23** [comment]
in case of 429(throttling) , will await graphClient.Me.SendMail(message, true).Request().PostAsync() throw any exception?

**Comment by MIchaelMainer** [comment]
No need to check status for 429 as they are automatically retried. A ServiceException is thrown if there are too many retries.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/Middleware/RetryHandler.cs#L126

**Comment by ravicse23** [comment]
Thanks..is this feature available for microsoft.Graph standard sdk too?

**Comment by MIchaelMainer** [comment]
@ravicse23 It is.
