### ISSUE TITLE
Deleting calendar events for a date range

### ISSUE THREAD

**Issue by ajtruckle** [microsoftgraph/msgraph-sdk-dotnet#889]
I have also asked this [here](https://stackoverflow.com/questions/64581283/deleting-a-range-of-calendar-events-with-microsoft-graph-is-not-including-the-a).
I am trying to purge a set of calendar events using Microsoft Graph.

This is my filter string:

`start/dateTime ge '2020-10-26T00:00' and end/dateTime le '2020-11-01T23:59'`

I noticed that in some instances any calendar event on the Sunday was not being deleted in that week.

On further inspection this only happens when the event has the "All Day" flag set.

So, when my events have a start / end time it picks up all the events within that complete week. But if (and it does happen) the user sets the Sunday event as a "all day" event with no time range, it does not get picked up and deleted.

This is my current delete routine:

```
    public async Task<bool> DeleteCalendarEvents(SettingsBase oSettings)
    {
        try
        {
            //var oCalendar = await _graphClient.Me.Calendars[oSettings.CalendarID].Request().GetAsync();
            //string strName = oCalendar.Name;

            var oEvents = await _graphClient
                                    .Me
                                    .Calendars[oSettings.CalendarID]
                                    .Events
                                    .Request()
                                    .Select("Start,Subject,Id") // TODO: Is there any point doing this?
                                    .Top(50)
                                    .Filter(oSettings.GetFilterString())
                                    .OrderBy("start/DateTime")
                                    .GetAsync();

            //Program.file.WriteLine($"Calendar {strName}");
            List<Event> listEvents = new List<Event>();

            listEvents.AddRange(oEvents);
            while (oEvents.NextPageRequest != null)
            {
                oEvents = await oEvents.NextPageRequest.GetAsync();
                listEvents.AddRange(oEvents);
            }

            foreach (Event oEvent in listEvents)
            { 
                //Program.file.WriteLine($"Event Data: {oEvent.Start.DateTime} Id: {oEvent.Id} Subject: {oEvent.Subject}");
                await _graphClient.Me.Events[oEvent.Id].Request().DeleteAsync();
            }

            //Program.file.WriteLine($"Count: {listEvents.Count}" + Environment.NewLine);
        }
        catch (Exception ex)
        {
            SimpleLog.Log(ex);
            Console.WriteLine("DeleteCalendarEvents: See error log.");
            return false;
        }

        return true;
    }

```
 need it to factor in these all day events too because I am now getting duplicates.

I am using Microsoft Graph 3.2 with Visual C# on VS2019.

Note: This method for deleting events was originally discussed and answered here but I was not aware of this glitch with "all day" events on the limit. 
[AB#6995](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6995)

**Comment by ajtruckle** [comment]
I asked this such a long time ago now. I don't have the test calendar events any more.

**Comment by MIchaelMainer** [comment]
It sounds like the all day event ending on Sunday isn't getting picked up. This may be caused be the filter window having an end time less than  '2020-11-01T23:59'. Perhaps it should be '2020-11-02T00:00' to make this work appropriately. This is question about the underlying calendar API and isn't about the client library. Still need to confirm the above. Leaving this open until confirmed and also in case someone else encounters this issue.

**Comment by ajtruckle** [comment]
@MIchaelMainer This code no longer compiles with 5.3.0.

        public async Task<bool> DeleteCalendarEvents(SettingsBase oSettings)
        {
            try
            {
                var oEvents = await _graphClient
                                        .Me
                                        .Calendars[oSettings.CalendarID]
                                        .Events
                                        .Request()
                                        .Select("Start,Subject,Id") // TODO: Is there any point doing this?
                                        .Top(50)
                                        .Filter(oSettings.GetFilterString())
                                        .OrderBy("start/DateTime")
                                        .GetAsync();

                List<Event> listEvents = new List<Event>();

                listEvents.AddRange(oEvents);
                while (oEvents.NextPageRequest != null)
                {
                    oEvents = await oEvents.NextPageRequest.GetAsync();
                    listEvents.AddRange(oEvents);
                }

                foreach (Event oEvent in listEvents)
                {
                    await _graphClient.Me.Events[oEvent.Id].DeleteAsync();
                }
            }
            catch (Exception ex)
            {
                SimpleLog.Log(ex);
                Console.WriteLine("DeleteCalendarEvents: See error log.");
                return false;
            }

            return true;
        }

If I delete the `.Reguest()` line of code the n it does not like the `Select` line.

**Comment by ajtruckle** [comment]
@MIchaelMainer 
Got this far:

        public async Task<bool> DeleteCalendarEvents(SettingsBase oSettings)
        {
            try
            {
                var oEvents = await _graphClient
                        .Me
                        .Calendars[oSettings.CalendarID]
                        .Events
                        .GetAsync(requestConfiguration =>
                        {
                            requestConfiguration.QueryParameters.Select = new string[] { "Start", "Subject", "Id" };
                            requestConfiguration.QueryParameters.Top = 50;
                            requestConfiguration.QueryParameters.Filter = oSettings.GetFilterString();
                            requestConfiguration.QueryParameters.Orderby = new string[] { "start/DateTime" };
                        });

                List<Event> listEvents = new List<Event>();

                listEvents.AddRange(oEvents.Value);
                while (oEvents.NextPageRequest != null)
                {
                    oEvents = await oEvents.NextPageRequest.GetAsync();
                    listEvents.AddRange(oEvents.Value);
                }

                foreach (Event oEvent in listEvents)
                {
                    await _graphClient.Me.Events[oEvent.Id].DeleteAsync();
                }
            }
            catch (Exception ex)
            {
                SimpleLog.Log(ex);
                Console.WriteLine("DeleteCalendarEvents: See error log.");
                return false;
            }

            return true;
        }

But, it does not like the `oEvents.NextPageRequest` calls.

**Comment by ajtruckle** [comment]
@MIchaelMainer If I understand the docs correctly, this is now what I should do?

        public async Task<bool> DeleteCalendarEvents(SettingsBase oSettings)
        {
            try
            {
                var oEvents = await _graphClient
                        .Me
                        .Calendars[oSettings.CalendarID]
                        .Events
                        .GetAsync(requestConfiguration =>
                        {
                            requestConfiguration.QueryParameters.Select = new string[] { "Start", "Subject", "Id" };
                            requestConfiguration.QueryParameters.Top = 50;
                            requestConfiguration.QueryParameters.Filter = oSettings.GetFilterString();
                            requestConfiguration.QueryParameters.Orderby = new string[] { "start/DateTime" };
                        });

                List<Event> listEvents = new List<Event>();

                var pageIterator = PageIterator<Event, EventCollectionResponse>.CreatePageIterator(
                                        _graphClient, 
                                        oEvents, (Event) => { listEvents.Add(Event); return true; });

                await pageIterator.IterateAsync();

                /*
                listEvents.AddRange(oEvents.Value);
                while (oEvents.NextPageRequest != null)
                {
                    oEvents = await oEvents.NextPageRequest.GetAsync();
                    listEvents.AddRange(oEvents.Value);
                }
                */

                foreach (Event oEvent in listEvents)
                {
                    await _graphClient.Me.Events[oEvent.Id].DeleteAsync();
                }

            }
            catch (Exception ex)
            {
                SimpleLog.Log(ex);
                Console.WriteLine("DeleteCalendarEvents: See error log.");
                return false;
            }

            return true;
        }

**Comment by ajtruckle** [comment]
@andrueastman Thanks for confirming.

**Comment by andrueastman** [comment]
No worries @ajtruckle. As you originally created the issue a while back, any objections to closing the issue for now?

**Comment by ajtruckle** [comment]
@andrueastman Sure! I’ll close it now.
