### ISSUE TITLE
Delta Query Support?

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/msgraph-sdk-dotnet#89]
I know that delta is currently beta, but what are the plans (if any) to support in this library? (if not, a sample like with differential query in AAD graph?)

**Comment by MIchaelMainer** [comment]
Currently, we do not support the beta endpoint in the client library. We plan on updating the client library to support changes to v1.0 endpoint. I can't comment on specific beta features as I'm uncertain of 1) their current state (as in whether there are more changes to come), and 2) when beta features move to the v1.0 endpoint.

**Comment by kspearrin** [comment]
@MIchaelMainer Any update on delta support here yet? I see the `.Delta()` option but not really sure how to use it.

**Comment by MIchaelMainer** [comment]
We do have delta support. Here are some examples:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.Test/Requests/Functional/DeltaQueryTests.cs

**Comment by kspearrin** [comment]
@MIchaelMainer Thansk for the test case example.

Is it possible to `InitializeNextPageRequest` with a delta link without having a previous `IGroupDeltaCollectionPage` already available? I am coming back with no previous page context in my implementation. My user case kinda looks like:

```
...

var groupRequest = _graphClient.Groups.Delta().Request().Select("id,displayName");
IGroupDeltaCollectionPage groups = null;

if(storedDeltaLink != null)
{
    groups = null;
    // How should I InitializeNextPageRequest from storedDeltaLink since
    // I have not done GetAsync() yet?
}
else
{
    groups = await groupRequest.GetAsync();
}

...
```

**Comment by kspearrin** [comment]
I was able to solve this by parsing out the `$deltatoken` query string from the `@odata.deltaLink`, persisting that, and then building a `_graphClient.Groups.Delta().Request()` with `QueryOptions.Add(new QueryOption("$deltatoken", storedDeltaToken))` for the next time I need to request.
