### ISSUE TITLE
The collection type 'Microsoft.Graph.IListItemsCollectionPage' is abstract, an interface, or is read only, and could not be instantiated and populated

### ISSUE THREAD

**Issue by salilpune1** [microsoftgraph/msgraph-sdk-dotnet#891]
I am trying to access all SharePoint List Items using Graph Client.

 GraphServiceClient graphClient = new GraphServiceClient(authProvider);
            var queryOptions = new List<QueryOption>()
            {
                new QueryOption("expand", "Items")
            };

            var site = Task.Run(() => graphClient.Sites.GetByPath("/sites/sitecollection/", "domain")
            .Request()
            .WithUsernamePassword(UserName, pwd)
            .GetAsync()).Result;

            Microsoft.Graph.List list = Task.Run(() => graphClient.Sites[site.Id].Lists["largeone"]
            .Request(queryOptions)
             .WithUsernamePassword(UserName, pwd)
            .GetAsync()).Result;

But getting below error
The collection type 'Microsoft.Graph.IListItemsCollectionPage' is abstract, an interface, or is read only, and could not be instantiated and populated. The unsupported member type is located on type 'System.Collections.Generic.List`1[Microsoft.Graph.ListItem]'. Path: $.items | LineNumber: 0 | BytePositionInLine: 1224.  Inner Exception 2: NotSupportedException: The collection type 'Microsoft.Graph.IListItemsCollectionPage' is abstract, an interface, or is read only, and could not be instantiated and populated.

**Comment by andrueastman** [comment]
@salilpune1 Any chance you could share info on what version of the sdk you are running? Please also check the version of Microsoft.Graph.Core. 
Please note that 3.x.x versions of the service library is not compatible with versions 2.x.x of the core library(Microsoft.Graph.Core still in preview) since we are in the process of moving to System.Text.Json. 
3.x.x versions should only be used with versions 1.x.x of the core package since those versions use Newtonsoft.Json.

**Comment by salilpune1** [comment]
I am using Microsoft.Graph 3.4 and Microsoft.Graph.Core 2.0 Preview 4

**Comment by andrueastman** [comment]
For now you will need change to Microsoft.Graph.Core 1.x.x. However, we will be releasing preview versions of the service library that are compatible with System.Text.Json soon. 

I will close this issue for now. Please feel free to create an issue if anything arises.
