### ISSUE TITLE
ConversationMemeber Model missing UserId and Email values

### ISSUE THREAD

**Issue by Harkole** [microsoftgraph/msgraph-sdk-dotnet#898]
**Describe the bug**
Querying the Graph Explorer for a list of members in a Team returns 5 values, but only three are available through the SDK. The request is correctly created and executed but the results lose data

**To Reproduce**
```csharp
            // Get the existing team data.
            collectionPage = await graphClient.Teams[teamId].Members
                .Request()
                .GetAsync(cancellationToken)
                .ConfigureAwait(false);
```

![image](https://user-images.githubusercontent.com/3703699/107759912-e13a2f80-6d20-11eb-8fc5-35ee37923d6e.png)

No properties for accessing `UserId` or `Email`

**Expected behavior**
Results should have the following (confirmed from Graph API Explorer but taken from https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http)

![image](https://user-images.githubusercontent.com/3703699/107760032-0dee4700-6d21-11eb-9408-d2cea73d1fd1.png)

**Screenshots**
dev branch, incorrect model:
![image](https://user-images.githubusercontent.com/3703699/107760111-2b231580-6d21-11eb-86a7-588ac51f51c1.png)
 
[AB#8125](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8125)

**Comment by zengin** [comment]
This can be achieved by casting after the response is received as below. Unfortunately, we don't have OData cast support to allow us to run `Select` on subtypes at query time.

```csharp
foreach (var member in collectionPage)
{
	if (member is AadUserConversationMember aadMember)
	{
		Console.WriteLine(aadMember.UserId);
	}
}
```

**Comment by Harkole** [comment]
Thanks @zengin I will implement this on Monday

**Comment by andrueastman** [comment]
@Harkole Did this work out for you?

**Comment by Harkole** [comment]
@andrueastman yes casting the result provided access to the values I was looking for

**Comment by andrueastman** [comment]
Thanks for getting back to this. Happy to hear that it worked out for you.

I will close this issue for now so that we may track support for odata casts via https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/701 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/239
