### ISSUE TITLE
How can I save a downloaded file to a specified path?

### ISSUE THREAD

**Issue by CMNico** [microsoftgraph/msgraph-sdk-dotnet#90]
When using `files = await graphClient.Me.Drive.Root.ItemWithPath(Path).Children.Request().GetAsync();`
the file downloaded get saved in the C:\Users\someone\AppData\Local\Packages\4a9bc9b3-6484-4443-9a65-f36f7519b1d5_9b10f1p8kdmhr\AC\INetCache\3HUY71XE 

`public static async Task<System.IO.Stream > GetCurrentUserFileAsync(string Path, string FileName)
{
            IDriveItemChildrenCollectionPage files = null;

            try
            {
                var graphClient = AuthenticationHelper.GetAuthenticatedClient();
                files = await graphClient.Me.Drive.Root.ItemWithPath(Path).Children.Request().GetAsync();
                foreach (DriveItem item in files)
                {

                    Debug.WriteLine("Got file: " + item.Name);
                    if (item.Name == FileName )
                    {
                        var fileContent = await DownloadFileAsync(item.Id);
                        return fileContent ;
                    }
                }

                return null;

            }

            catch (ServiceException e)
            {
                Debug.WriteLine("We could not get user files: " + e.Error.Message);
                return null;
            }

        }`

How can we specify to save it to a specified path?

**Comment by MIchaelMainer** [comment]
Thank you for asking this question. We use the issues here for tracking work items and bugs. Please post your question to StackOverflow with the [microsoftgraph](https://stackoverflow.com/questions/tagged/microsoftgraph). This way, more people can find your question and the answer. After you have posted to StackOverflow, provide a link to the StackOverflow post from this issue and we'll take a look.

**Comment by CMNico** [comment]
Thank you
here is the link to it:
[](https://stackoverflow.com/questions/42566490/how-can-i-save-a-downloaded-file-to-a-specified-path)
