### ISSUE TITLE
InvalidModel error when posting new Todo Task 

### ISSUE THREAD

**Issue by deankinane** [microsoftgraph/msgraph-sdk-dotnet#909]
**Describe the bug**
When attempting to post a new TodoTask item to a Todo list via the SDK the result is always an error that reads: 
"A type named 'microsoft.toDo.todoTask' could not be resolved by the model. When a model is available, each type name must resolve to a valid type."

**To Reproduce**
Steps to reproduce the behaviour:
_Assuming you have already created the required GraphServiceClient_
1. Create a new TodoTask object
2. Initialise whichever properties you require (I have tried with only the Title property and also initialising every property including empty lists for resources etc.)
3. Using the GraphServiceClient, post the new TodoTask object to a valid todo list via the GraphServiceClient.Users[o365Userid].Todo.Lists[todoListId].Tasks.Request.AddAsync method
4. Error response received with the error described above

```
 var newTask = await client.Users[o365UserId]
                    .Todo
                    .Lists[taskListId]
                    .Tasks
                    .Request()
                    .AddAsync(task);
```

**Expected behaviour**
The new Todo Task will be created on the specified Todo List and a reference to it will be returned from the AddAsync method.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS 2019
 - .NET Core 2.2
 - Graph SDK Version 3.24.0

**Additional context**
There is a thread on the Answers forum here:
https://docs.microsoft.com/en-us/answers/questions/174930/unable-to-create-todo-task-using-graph-api-v10.html
As suggestion was that the issue relates to this:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/10824
 
[AB#8219](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8219)

**Comment by andrueastman** [comment]
This looks to be related to this https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/312. 

At the moment, you can workaround the error by doing this.

```cs
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var todoTaskList = new TodoTaskList
{
        ODataType = null, // unset this value
	DisplayName = "Travel items"
};

await graphClient.Me.Todo.Lists
	.Request()
	.AddAsync(todoTaskList);
```

**Comment by deankinane** [comment]
Hi @andrueastman 

Thanks for this.

Setting the ODataType property to null on the TodoTask object, and also on any properties of the TodoTask that also derive from the Entity class, is a workable workaround for the issue.

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/993 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
