### ISSUE TITLE
Add signInNames property to User.

### ISSUE THREAD

**Issue by JonJam** [microsoftgraph/msgraph-sdk-dotnet#91]
When querying User data from Azure AD B2C, I would like to get the usernames for registered users which are contained in the signInNames property.

Currently User does not contain the signInNames property.

**Comment by MIchaelMainer** [comment]
Hello @JonJam, thank you for contacting us. You're asking a question about the [Azure AD Graph API](https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/signed-in-user-operations). This repo is for the Microsoft Graph API, and specifically, for the .Net client library. I suggest that you post your question to [StackOverflow and tag it with azure-ad-graph-api](https://stackoverflow.com/questions/tagged/azure-ad-graph-api). It is a bit confusing. I don't currently see the signInNames property on either the beta or v1.0 metadata for the Microsoft Graph API.
https://graph.microsoft.com/beta/$metadata
https://graph.microsoft.com/v1.0/$metadata

**Comment by MIchaelMainer** [comment]
@Mardoxx I'm sorry about the confusion caused by the lack of documentation. You are referencing the Azure AD Graph service API metadata in your post. This repo is for the Microsoft Graph client API that targets the Microsoft Graph service API. The User entity for the Microsoft Graph service API still does not have the signInNames property. 

That note in the M.A.A.GraphClient package description should also state that the Microsoft Graph service API does not currently expose all of the Azure AD Graph services APIs. There are still scenarios that aren't covered by Microsoft.Graph and still require the Azure AD Graph client.

**Comment by Mardoxx** [comment]
Ahh! Thank you.

And also worth noting that, which I wrongly assumed, graph.windows.net is not just an alias for graph.microsoft.com

**Comment by turowicz** [comment]
@Mardoxx which SDK did you end up using or did you consume the endpoint "by hand"?

**Comment by devsales** [comment]
Has there been any progress regarding this issue?

I see that the issue has been closed but I tried to get the signInNames somehow with the Microsoft Graph API but it seems like the property is still not available for the User entity.

**Comment by darrelmiller** [comment]
@devsales Unfortunately, we can only provide support in the SDKs for features that are supported by the services.  You would need to raise this issue with the AAD team to get the functionality added to the Graph.  Either StackOverflow or UserVoice would be more successful avenues to get this capability added.

**Comment by devsales** [comment]
@darrelmiller thank you! I'll try those instead.
I was just wondering how can I get to the email address of a user without the signInNames property. I mean there is the "mail" property but in my case it is null. This seems like a basic functionality and it is surprising if it is not yet supported.

**Comment by mavdi** [comment]
"In the Microsoft Graph API, both local and federated identities are stored in the user identities attribute, which is of type objectIdentity. The identities collection represents a set of identities used to sign in to a user account. This collection enables the user to sign in to the user account with any of its associated identities."

https://docs.microsoft.com/en-us/azure/active-directory-b2c/manage-user-accounts-graph-api#user-properties
