### ISSUE TITLE
[Client bug]: .NET library doesn't url encode arguments in Filter() properly

### ISSUE THREAD

**Issue by lewinskimaciej** [microsoftgraph/msgraph-sdk-dotnet#914]
When filtering, for example, identities, Filter() method doesn't properly encode string given to it. If we filter using an email that contains a '+' character, it won't return any results.

This is kind of an unexpected behavior which is not described anywhere. I think from user's position it's safe to assume that everything in filter clause will get passed to B2C/AD API as-is, yet it's distorted.

Original issue that was closed due to inactivity: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/744

**Steps to reproduce the behavior**:
1. Setup B2C and .NET/.NET Core based app
2. Add B2C Users with '+' character in their identity IssuerAssignedId
3. Call GraphServiceClient to retrieve all users that have identity with email containing a + sign.

**Actual behavior**
No users are returned with OK response.

**Expected behavior**:
Arguments are properly encoded and actually work when filtering or documentation(either on Github or method doc) clearly mentions this behavior.

**Example**:
```csharp
await _graphServiceClient
                .Users
                .Request()
                .Filter($"identities/any(c:c/issuerAssignedId eq '{email}' and c/issuer eq '{_graphConfig.Tenant}')")
                .GetAsync();
```
This will not return any users if email property contains a '+' character.

```csharp
await _graphServiceClient
                .Users
                .Request()
                .Filter($"identities/any(c:c/issuerAssignedId eq '{HttpUtility.UrlEncode(email)}' and c/issuer eq '{_graphConfig.Tenant}')")
                .GetAsync();
```
This will work properly.

**Client version**
```xml
<PackageReference Include="Microsoft.Graph" Version="3.8.0" />
```

Used in `.netcoreapp3.1` project.
 
[AB#8281](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8281)

**Comment by MIchaelMainer** [comment]
This has also been encountered by ICM 238464926

**Comment by MIchaelMainer** [comment]
@mairissi @andrueastman I think we should prioritize this.

**Comment by andrueastman** [comment]
This is resolved via microsoftgraph/msgraph-sdk-dotnet-core#255 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
