### ISSUE TITLE
UnsupportedApiVersion error when updating TodoTask

### ISSUE THREAD

**Issue by deankinane** [microsoftgraph/msgraph-sdk-dotnet#923]
When calling the UpdateAsync method for a TodoTask we are getting the following errors:

No route providing a controller name with API version '1.0' was found to match request URI 'https://substrate.office.com:444/todo/graph/v1/users('xxxxxxx)/todoApp/lists('xxxxxx')/tasks'.

The HTTP resource that matches the request URI 'https://substrate.office.com:444/todo/graph/v1/users('xxxxxx')/todoApp/lists('xxxxxx')/tasks' does not support the API version '1.0'.

```
 task = await client.Users[o365UserId]
                    .Todo
                    .Lists[taskListId]
                    .Tasks[taskId]
                    .Request()
                    .UpdateAsync(task);
```

Using latest SDK version 3.26.0. 
[AB#8454](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8454)

**Comment by andrueastman** [comment]
@deankinane Any chance you could provide more information about how exactly you are making the request?

I am unable to replicate this using the following code. It updates the Task without any errors
```cs
IPublicClientApplication publicClientApplication = PublicClientApplicationBuilder
    .Create(clientId)
    .WithRedirectUri("http://localhost:1256")
    .Build();

InteractiveAuthenticationProvider authProvider = new InteractiveAuthenticationProvider(publicClientApplication, scopes);

GraphServiceClient client = new GraphServiceClient(authProvider);

var todoTaskUpdate = new TodoTask()
{
    Title = "A New name",
};

var updatedTask = await client
                .Users["abc@xyz.com"]
                .Todo
                .Lists["listId"]
                .Tasks["taskId"]
                .Request()
                .UpdateAsync(todoTaskUpdate)
```

**Comment by deankinane** [comment]
Hi @andrueastman 

```
var app = ConfidentialClientApplicationBuilder
            .Create(_appId)
            .WithRedirectUri(_redirectUri)
            .WithClientSecret(_clientSecret)
            .Build();

var account = await app.GetAccountAsync(accountEmail);
await app.AcquireTokenSilent(_scopes, account).ExecuteAsync();
var authProvider = new AuthorizationCodeProvider(app, _scopes);

var client = new GraphServiceClient(authProvider);

task = await client.Users[accountEmail]
                    .Todo
                    .Lists[taskListId]
                    .Tasks[taskId]
                    .Request()
		    .UpdateAsync(task);
```

**Comment by andrueastman** [comment]
@deankinane Are you also able to capture and share a fiddler trace as the request is made?

**Comment by deankinane** [comment]
Hi @andrueastman 

I discovered that the task ID was not being set correctly for the request, after resolving that issue I am now receiving a 500 error.

Here is the capture form Fiddler (sensitive info redacted).

REQUEST
-------------

PATCH https://graph.microsoft.com/v1.0/users/xxxx/todo/lists/xxxx/tasks/xxxx HTTP/1.1
SdkVersion: Graph-dotnet-1.24.0
FeatureFlag: 0000004F
Cache-Control: no-store, no-cache
Authorization: Bearer xxxx
Accept-Encoding: gzip
Content-Type: application/json
Content-Length: 434
Host: graph.microsoft.com

{"body":{"content":"Test meeting - updated ","contentType":"text"},"dueDateTime":{"dateTime":"2021-04-23T15:00:00.0000000","timeZone":""},"importance":"normal","isReminderOn":false,"status":"inProgress","title":"Meeting","extensions":[],"linkedResources":[],"id":"xxxx"}


RESPONSE
-------------

HTTP/1.1 500 Internal Server Error
Date: Thu, 22 Apr 2021 13:33:00 GMT
Content-Type: application/json
Cache-Control: no-cache
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 9fa8959e-9ab1-450f-8877-43fe68ef4329
client-request-id: 9fa8959e-9ab1-450f-8877-43fe68ef4329
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"4","ScaleUnit":"002","RoleInstance":"LO1PEPF0000017D"}}
Content-Length: 291

{
  "error": {
    "code": "generalException",
    "message": "Internal Server Error",
    "innerError": {
      "date": "2021-04-22T13:33:01",
      "request-id": "9fa8959e-9ab1-450f-8877-43fe68ef4329",
      "client-request-id": "9fa8959e-9ab1-450f-8877-43fe68ef4329"
    }
  }
}

**Comment by andrueastman** [comment]
@deankinane 
It looks like the request payload has the [extensions](https://docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&tabs=http) and [linkedResources ](https://docs.microsoft.com/en-us/graph/api/linkedresource-update?view=graph-rest-1.0&tabs=http)attributes are set which is causing the issue. These are navigation properties that are updated/created in a separate way as shown in the links above.

You should therefore have created the object to update as follows
```cs
var todoTaskUpdate = new TodoTask()
{
    Title = "A New name",
    Body = new ItemBody()
    {
        Content = "Test meeting - updated ",
        ContentType = BodyType.Text
    },
    DueDateTime = new DateTimeTimeZone()
    {
        DateTime = "2021-04-23T15:00:00.0000000",
        TimeZone = ""
    },
    Importance = Importance.Normal,
    IsReminderOn = false,
    Status = TaskStatus.InProgress,
    // Ensure you don't set this as we can't update navigation properties via patch
    // LinkedResources = new TodoTaskLinkedResourcesCollectionPage(),
    // Extensions = new TodoTaskExtensionsCollectionPage()
};
```
