### ISSUE TITLE
How to get localized (translated) column name from a SharePoint List?

### ISSUE THREAD

**Issue by StefH** [microsoftgraph/msgraph-sdk-dotnet#926]
I'm currently providing the `Accept-Language` header with value `nl` like this:

``` c#
var options = new List<Option>
{
  new HeaderOption("Accept-Language", "nl")
};

var graphRequest = client.Sites[siteId]
  .Lists[listName]
  .Request(options);
```

Because the columns are in Dutch format:
![image](https://user-images.githubusercontent.com/249938/110612110-2ae73000-8190-11eb-92fe-7319e6400183.png)

But the response is still English:
![image](https://user-images.githubusercontent.com/249938/110612570-9cbf7980-8190-11eb-8673-1a8dbb47f90c.png)

**Notes** 
- using `nl-NL` does also not work.
- using Microsoft.Graph Version=3.2.0.0
 
[AB#8528](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8528)

**Comment by MIchaelMainer** [comment]
I don't think this is supported from what I read in the documentation.
https://docs.microsoft.com/en-us/graph/api/list-get?view=graph-rest-1.0&tabs=http

This appears to be a a feature request. Please use the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) to search for existing feature requests, and to open new feature requests. Provide a link to your feature request in this issue.
