### ISSUE TITLE
Try out the preview of the next major version! 📢 📢 

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet#935]
The Microsoft Graph .NET SDK v4.0.0 is now available for [preview](https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.4)!

This new version features a large number of changes including:
- Replacing Newtonsoft.Json with System.Text.Json for serialization/de-serialization
- Support for the GraphResponse object to access native Http response info(headers,status code,content)
- Support for TokenCredential instances from Azure.Identity for authentication
- Upgrading Microsoft.Graph.Core dependency to version 2.0.0
- .NET Standard minimum version bumped from netstandard1.3 to netstandard2.0
- .NET Framework minimum version bumped from net45 to net462
- PutAsync methods added for Entity types
- Page Iterator moved to core and shared in both V1 and Beta

You can go to the [upgrade guide](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md) for more detailed information on the changes. 
 
[AB#8671](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8671)

**Comment by ondfisk** [comment]
In the upgrade guide you write:

> The `IGraphServiceClient` interface is not really an interface because it continues to change with metadata changes. This makes it not ideal to mock or inherit. The interface has therefore been removed and no longer exists.

How do you propose we test a service class which depends on the `GraphServiceClient` then?

**Comment by zachcwillson** [comment]
Please return `IGraphServiceClient` to the NuGet. This breaks all of our unit tests on Graph.

**Comment by darrelmiller** [comment]
@ondfisk @zachcwillson  We recommend that users of the SDK to create a wrapper service that exposes just the functionality that is being used from Graph.  That wrapper service can have a stable interface.  The wrapper also centralizes the application's dependencies on the Graph SDK.  

Using the IGraphServiceClient will cause tests to break whenever we add new top level path segments.  It also potentially requires generating mocks for thousands of request builders.

@zachcwillson Are you currently using some automatic mocking tool?  Does your application use a large number of Graph endpoints?

Alternatively you can inject a mock delegating handler into the GraphServiceClient and return canned results.  The ChaosHandler can be configured with predefined results.

**Comment by cmenzi** [comment]
I somehow missed this big step from `0.XX-preview` to `v4` (three major versions) of the Graph package and just to be honest, there are so many versions now. Could you please create page with a clarification:

APIs:
- Graph v1.0
- Graph Beta

SDKs
- Microsoft.Graph.Beta
  - 0.43.0-preview
  - ... 3 major versions ❓ 
  - 4.0.1-preview 
  - everything is preview, but also major version are available

![image](https://user-images.githubusercontent.com/1763806/115445316-fe561780-a215-11eb-8c17-bfa9e73c7b91.png)

- Microsoft.Graph (Same issue)

![image](https://user-images.githubusercontent.com/1763806/115445481-2f364c80-a216-11eb-84b2-457bec87fd41.png)

It would be really helpful to understand all this beta, preview, api beta, api v1, ...

This not really SemVer and also Nuget Package Explorer is also showing updates, etc.

**Comment by andrueastman** [comment]
@cmenzi 
Apologies for any confusion that may have arisen. 
We are currently making some breaking changes in the client library itself through the introduction of System.Text.Json, updated .Net Standard etc hence the major version updates. These changes are still in preview at moment though.

The beta library is unique though since the beta API itself is not meant to be used in any production environment and is normally updated with breaking api changes week by week. To signal this to the SDK user we will always keep the beta packages in preview because of this. The major version update is therefore intended to signal that there is a breaking change in the client library itself (e.g by dropping NewtonSoft for System.Text.Json) as opposed to the API.

The V1 does indeed follow SemVer and when we get the service library package out of preview, we shall stop making metadata updates on the 3.x.x(v1) and 0.x.x(beta) channels. In the meantime, we are still supporting these versions with metadata updates as we move towards general availability of the 4.x.x versions.

**Comment by DerGuru** [comment]
Hi ,

> Using the IGraphServiceClient will cause tests to break whenever we add new top level path segments. It also potentially requires generating mocks for thousands of request builders.
> @zachcwillson Are you currently using some automatic mocking tool? Does your application use a large number of Graph endpoints?

I have the same issue here. I am using Moq with the IGraphServiceClient, which does the mocking of subsequent mocks on its own, allowing me to have something like.

`graphMock.Setup(g => g.DeviceManagement.ManagedDevices[id].Request().GetAsync()).ReturnsAsync(new ManagedDevice{...}).Verifiable();`

The matching is done automatically by the deviceId and the Mock Returns a hand crafted ManagedDevice or Mock. As a benefit, I can also check, whether this setup was called at all.

> Alternatively you can inject a mock delegating handler into the GraphServiceClient and return canned results. The ChaosHandler can be configured with predefined results.

This will force me to **create real objects**,, putting them into HttpResponse Messages an have them serialized to JSON and deserialized to objects again.
The matching could be done by the HttpRequestMessages URL yet still, I'd prefer the Mocks.
If the Methods and Properties of GraphServiceClient would be virtual, Moq could also be used, but this is not true so far.
Is this at leastr possible?

**Comment by darrelmiller** [comment]
@DerGuru I hear you.  Would it possible for you to share an example test where you use this mock?

@baywet @andrueastman @ddyett  @MIchaelMainer We should discuss the impact of making the methods virtual.

**Comment by DerGuru** [comment]
> @DerGuru I hear you. Would it possible for you to share an example test where you use this mock?
> 
> @baywet @andrueastman @ddyett @MIchaelMainer We should discuss the impact of making the methods virtual.

There are already encapsulations in place, but those need to be tested, to call the right API, which is here. A Factory that creates ServiceObjects from ManagedDevices.

```csharp
    var graph = new Mock<IGraphServiceClient>();
    ManagedDevice md = new ManagedDevice
    {
        Id = "1",
        DeviceType = DeviceType.AndroidForWork
    };

    graph.Setup(g => g.DeviceManagement.ManagedDevices["1"].Request().GetAsync()).Returns(Task.Run(() => md)).Verifiable();

    var factory = new ServiceDeviceFactory(moqs.Graph.Object, moqs.Logger.Object);
    var dev = await factory.Create("1"); //here is the graph call
    Assert.AreEqual(md.Id, dev.Id);

    graph.Verify();
```

This test will guaranty, that the Graph call will take place (verifiable and verify). It will also make sure, that the right ID is requested and the end product (serviceobject) will have the same id.

**Comment by DerGuru** [comment]
Since I am using quite a lot of different API Endpoints, bulding some kind of facade is not really feasable. I already tried and the code is more readable this way.
Also I think, the tests are better understandable.

**Comment by andrueastman** [comment]
Hey @DerGuru, 
We've now made methods/properties of GraphServiceClient virtual from V1 version [4.0.0-preview.7](https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.7) and beta version [4.5.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.5.0-preview).
Using Moq you should be able to mock the GraphServiceClient as you described and shown in the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graphserviceclient-no-longer-implements-the-igraphserviceclient).

**Comment by DerGuru** [comment]
> Hey @DerGuru,
> We've now made methods/properties of GraphServiceClient virtual from V1 version [4.0.0-preview.7](https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.7) and beta version [4.5.0-preview](https://www.nuget.org/packages/Microsoft.Graph.Beta/4.5.0-preview).
> Using Moq you should be able to mock the GraphServiceClient as you described and shown in the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graphserviceclient-no-longer-implements-the-igraphserviceclient).

This is great news! I will still have to adjust my code a little, but the basic mechanic will work.

Thank You!
