### ISSUE TITLE
@microsoft.graph.downloadUrl behavior for personal accounts

### ISSUE THREAD

**Issue by horacioj** [microsoftgraph/msgraph-sdk-dotnet#94]
Hi,

Is there an ETA for a fix to this issue?
[@microsoft.graph.downloadUrl behavior for personal accounts](http://stackoverflow.com/questions/40623017/microsoft-graph-api-microsoft-graph-downloadurl-behavior-for-personal-accounts)

i.e. consistent behavior regardless of being a business or personal account

Thanks

**Comment by MIchaelMainer** [comment]
Hi @horacioj, we don't have any status on this scenario. Please monitor that StackOverflow thread for updates on that scenario.
