### ISSUE TITLE
I cant seem to figure out why I am having an issue with getting the Microsoft Graph SDK for C# to use the system default proxy

### ISSUE THREAD

**Issue by DamienTehDemon** [microsoftgraph/msgraph-sdk-dotnet#941]
I am having alot of issues trying to get the MIP SDK for C# to use the systems default proxy. I currently have it working but after about an hour it seems to start giving an 407 error again. I know that the URL's are whitelisted for the proxy as it works for the first hour of the software running. As you can see below I am creating the graph client using a custom HttpProvider, along with the authentication builder. I am not sure why it would be happening so randomly? I have updated the version hoping that will fix it and it did not seem to fix the issue. If anyone has ran into a similar issue and can point me in the right direction that would be great.

    public async Task SetGraphServiceClient()
            {
                try
                {
                    IConfidentialClientApplication daemonClient;
                    //Creates a daemon service.
                    daemonClient = ConfidentialClientApplicationBuilder.Create(_settings.ClientId)
                    .WithHttpClientFactory(new SystemProxyHttpClientFactory())
                    .WithAuthority(string.Format(_authorityFormat, _settings.Tenant))
                    .WithClientSecret(_settings.ClientSecret)
                    .Build();
                    //Gets auth token.
                    AuthenticationResult authResult = await daemonClient.AcquireTokenForClient(new string[] { _msGraphScope })
                    .ExecuteAsync();
                    ClientCredentialProvider authProvider = new ClientCredentialProvider(daemonClient);
    
                    //Sets the graph client
                    var httpProvider = new HttpProvider(
                        new HttpClientHandler
                        {
                            UseProxy = true,
                            Proxy = WebRequest.DefaultWebProxy
                        }, false // Setting disposeHandler to true does not affect the behavior
                    )
                    {
                        OverallTimeout = TimeSpan.FromHours(1)
                    }; 
    
                    _graphClient = new GraphServiceClient(authProvider, httpProvider);
    
                    // Attempts to set up the MIP engine
                    var mipInfo = await new ApiProxy().GetMipAzureInformation(new CancellationToken());
                    try
                    {
                        _mipEngine = new Engine(mipInfo.ClientSecret, mipInfo.ApplicationId, mipInfo.Tenant, "ClassiDocs", Assembly.GetExecutingAssembly().GetName().Version.ToString(), false);
                    }
                    catch (Exception ex)
                    {
                        _logService?.TraceWarn(ex, "Can not setup MIP engine. Not configured.");
                    }
                }
                catch (HttpRequestException ex)
                {
                    _logService.TraceError(ex, "Could not make the request to the Graph API. Please ensure that the machine that this software is running on, and the user, are able to resolve the DNS and make the connection. ( If using proxies please check the configuration of those proxies)");
                }
                catch (Exception ex)
                {
                    _logService?.TraceError(ex);
                }
    
            }

**Expected behavior**
It to use the proxy.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

 
[AB#8744](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8744)

**Comment by DamienTehDemon** [comment]
Well it is getting this error

 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'uatemiratesnbd-my.sharepoint.com'

And the way the proxy is setup is that it requires authentication unless a URL is whitelisted, then it just allows it through automatically. We were getting 407 errors before but we arent getting those anymore

**Comment by MIchaelMainer** [comment]
Are you uploading or downloading files? If so, what is happening is that when working with files, and graph API is returning a redirect. We remove the `Authorization` header from redirects that use a different host or scheme ([see redirecthandler](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/Middleware/RedirectHandler.cs#L108)). We don't remove a `Proxy-Authorization` header.

Is 'uatcompanyname-my.sharepoint.com' whitelisted at the proxy?
Can you verify that `Proxy-Authorization` header is set?
You mention that this error happens randomly. What calls is your application making?

What is your reason for adding your own HttpProvider? We now encourage folks to use our [GraphClientFactory](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs) to configure HTTP client. I also encourage you to [add logging](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/feature/2.0/docs/logging-requests.md).

**Comment by DamienTehDemon** [comment]
We are downloading AND uploading files. I will take a look at the Proxy-Authorization header, but the way that the proxy is setup, is that it blocks all traffic and requires authentication except what is whitelisted, the whitelist includes all of the microsoft urls that we are using. 

@MIchaelMainer 

I have implemented the GraphClientFactory to setup the proxy with our MIP SDK intergation. You can see the code snippet of what I have written to do so, I couldnt find much documentation on it, but it seems like its being used correctly based off some sample snippets i have seen.


                IConfidentialClientApplication daemonClient;
                //Creates a daemon service.
                daemonClient = ConfidentialClientApplicationBuilder.Create(_settings.ClientId)
                .WithAuthority(string.Format(_authorityFormat, _settings.Tenant))
                .WithClientSecret(_settings.ClientSecret)
                .Build();
                //Gets auth token.
                AuthenticationResult authResult = await daemonClient.AcquireTokenForClient(new string[] { _msGraphScope })
                .ExecuteAsync();
                ClientCredentialProvider authProvider = new ClientCredentialProvider(daemonClient);
                GraphClientFactory.Create(authProvider, proxy: WebRequest.DefaultWebProxy);
                var handlers = GraphClientFactory.CreateDefaultHandlers(authProvider);
                handlers.Add(new LoggingHandler(_logService));
                var httpClient = GraphClientFactory.Create(handlers);
                _graphClient = new GraphServiceClient(httpClient);


After implementing this change, it worked find on my local environment which is not using a proxy, but in the production environment it still is having an issue with the proxy, now it cant even make the first request successfully.

```
2021-04-02 20:28:15.9967 TRACE Start to process external documents... 
2021-04-02 20:28:24.3337 INFO Sending Graph request https://graph.microsoft.com/v1.0/sites 
2021-04-02 20:28:24.4899 TRACE Sending Graph request {
  "Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Content": null,
  "Method": {
    "Method": "GET"
  },
  "RequestUri": "https://graph.microsoft.com:443/v1.0/sites",
  "Headers": [
    {
      "Key": "SdkVersion",
      "Value": [
        "Graph-dotnet-1.22.0"
      ]
    },
    {
      "Key": "FeatureFlag",
      "Value": [
        "00000047"
      ]
    },
    {
      "Key": "Cache-Control",
      "Value": [
        "no-store, no-cache"
      ]
    },
    {
      "Key": "Authorization",
      "Value": [
        "Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjR6WUprZWJfVjNzT1ExQ0c4Rllnek8tZHBmQnd5M2JxMU9PbWM4X0wtM0kiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85NWI0ZDI3MS0xZTc0LTRiM2ItODliNy1lODIzOWQxZjQ4ZGUvIiwiaWF0IjoxNjE3MzgwNTk3LCJuYmYiOjE2MTczODA1OTcsImV4cCI6MTYxNzM4NDQ5NywiYWlvIjoiRTJaZ1lIaHhiNTVucnFCc1MxM2pkMTNyV2NIM0FBPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJDbGFzc2lkb2NzIiwiYXBwaWQiOiI2MjZiMzBmMC0yYjRhLTRmZTAtYjhiMi1jMjgyYTAyYzI4ZmMiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85NWI0ZDI3MS0xZTc0LTRiM2ItODliNy1lODIzOWQxZjQ4ZGUvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiI4MjhiNmI0Zi1iYzAyLTRlZmItODM1NS1mMDhkNmEwODlhMzEiLCJyaCI6IjAuQVZ3QWNkSzBsWFFlTzB1SnQtZ2puUjlJM3ZBd2EySktLLUJQdUxMQ2dxQXNLUHhjQUFBLiIsInJvbGVzIjpbIlNpdGVzLlJlYWRXcml0ZS5BbGwiLCJGaWxlcy5SZWFkV3JpdGUuQWxsIl0sInN1YiI6IjgyOGI2YjRmLWJjMDItNGVmYi04MzU1LWYwOGQ2YTA4OWEzMSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6Ijk1YjRkMjcxLTFlNzQtNGIzYi04OWI3LWU4MjM5ZDFmNDhkZSIsInV0aSI6ImZDd2N6SC1EWDBtRlpnUUZ0c05KQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfdGNkdCI6MTU4NzAyMTIwNH0.Ntdnuu30VkTGhr4USuVLy17t2qFDIbrlqfrUMPGAsxsyqYtSq-v3fAv_htGOwe9Hf22D2J09hZ18dYXCIcmHjRsbA4Kazt9JLsLksvrWTJeKz48l6bxg6xjhDq_tdHDPDWgveJIrFUHBkHlEz7o8wxW3eV5cctjsRWB-0TsqxsJZhagNE4Yn-U3YP2gjFtud5fYb3sXjqnHMlqUd7AJWSzz3MB2BBETiUV5Htb67zngMFk2sYsPJstL8sKa9GioSSz6iHxRW8s8aa--4k09gRxt_R5sYaZj9ptZ0u36_A868qtqd15VKh2KrI2vl7MMSQPXvMJBerlWYQsx50ecljw"
      ]
    },
    {
      "Key": "Accept-Encoding",
      "Value": [
        "gzip"
      ]
    }
  ],
  "Properties": {
    "Microsoft.Graph.GraphRequestContext": {
      "ClientRequestId": "e1889d06-d065-49dd-a27c-60e09884a377",
      "MiddlewareOptions": {
        "Microsoft.Graph.AuthenticationHandlerOption": {
          "AuthenticationProviderOption": null
        }
      },
      "CancellationToken": {
        "IsCancellationRequested": false,
        "CanBeCanceled": false,
        "WaitHandle": {
          "Handle": {
            "value": 3280
          },
          "SafeWaitHandle": {
            "IsInvalid": false,
            "IsClosed": false
          }
        }
      },
      "FeatureUsage": 0,
      "User": null
    }
  }
} 
2021-04-02 20:28:24.5055 ERROR Code: generalException
Message: An error occurred sending the request.
 
2021-04-02 20:28:24.8181 INFO Sending Graph request https://graph.microsoft.com/v1.0/sites 
2021-04-02 20:28:24.8181 TRACE Sending Graph request {
  "Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "Content": null,
  "Method": {
    "Method": "GET"
  },
  "RequestUri": "https://graph.microsoft.com:443/v1.0/sites",
  "Headers": [
    {
      "Key": "SdkVersion",
      "Value": [
        "Graph-dotnet-1.22.0"
      ]
    },
    {
      "Key": "FeatureFlag",
      "Value": [
        "00000047"
      ]
    },
    {
      "Key": "Cache-Control",
      "Value": [
        "no-store, no-cache"
      ]
    },
    {
      "Key": "Authorization",
      "Value": [
        "Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6Ilo4c2cwVktGeXQ4Z1E0ZHlKaWZZR3hfUlNPanlaSjFoNHNMTTRpWEc2cEEiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85NWI0ZDI3MS0xZTc0LTRiM2ItODliNy1lODIzOWQxZjQ4ZGUvIiwiaWF0IjoxNjE3MzgwNjAxLCJuYmYiOjE2MTczODA2MDEsImV4cCI6MTYxNzM4NDUwMSwiYWlvIjoiRTJaZ1lEaW1McEgwTSt5QTk5NmczbWZUUXlYN0FBPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJDbGFzc2lkb2NzIiwiYXBwaWQiOiI2MjZiMzBmMC0yYjRhLTRmZTAtYjhiMi1jMjgyYTAyYzI4ZmMiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85NWI0ZDI3MS0xZTc0LTRiM2ItODliNy1lODIzOWQxZjQ4ZGUvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiI4MjhiNmI0Zi1iYzAyLTRlZmItODM1NS1mMDhkNmEwODlhMzEiLCJyaCI6IjAuQVZ3QWNkSzBsWFFlTzB1SnQtZ2puUjlJM3ZBd2EySktLLUJQdUxMQ2dxQXNLUHhjQUFBLiIsInJvbGVzIjpbIlNpdGVzLlJlYWRXcml0ZS5BbGwiLCJGaWxlcy5SZWFkV3JpdGUuQWxsIl0sInN1YiI6IjgyOGI2YjRmLWJjMDItNGVmYi04MzU1LWYwOGQ2YTA4OWEzMSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6Ijk1YjRkMjcxLTFlNzQtNGIzYi04OWI3LWU4MjM5ZDFmNDhkZSIsInV0aSI6IjZ1WkRXVHhZTzB5a2xIQmt1bnRLQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfdGNkdCI6MTU4NzAyMTIwNH0.aMi5BukwGAtaHiZPZGvMSoZGh1lgVvJ3sGuIRQig6qqRmX1Xm2kOfp1VxRUZ93T19vR85mxLhrE9vFGebxNhIP0pM0InDqE5vVD1CosUe_DtxUj1pl9wCuTd3bLKhGfbbCouAjpEp53BvaYCdLU75jxSDL6UNfUtK_kLO7f1TsvkAclQoAOGkIUfDjcjRv3JJGvgjltmZjmYOSJpkgxPi_NBzZ1aFo1WqnyQmY2iRKfwfflkrTCvU7ttyo_txr_C8LB8yxCTkPSFHB1dhlWYRfbfT_r5TNFtygbModbio9xZr6PcP9uY77E2gOt5VNTdGIv4G8TcJ3w_i0k0B01mkw"
      ]
    },
    {
      "Key": "Accept-Encoding",
      "Value": [
        "gzip"
      ]
    }
  ],
  "Properties": {
    "Microsoft.Graph.GraphRequestContext": {
      "ClientRequestId": "cb88c561-01a4-48bb-9465-3a4ce4df3f19",
      "MiddlewareOptions": {
        "Microsoft.Graph.AuthenticationHandlerOption": {
          "AuthenticationProviderOption": null
        }
      },
      "CancellationToken": {
        "IsCancellationRequested": false,
        "CanBeCanceled": false,
        "WaitHandle": {
          "Handle": {
            "value": 3280
          },
          "SafeWaitHandle": {
            "IsInvalid": false,
            "IsClosed": false
          }
        }
      },
      "FeatureUsage": 0,
      "User": null
    }
  }
} 
2021-04-02 20:28:24.8181 ERROR Code: generalException
Message: An error occurred sending the request.
 
2021-04-02 20:28:24.8962 TRACE External documents processed successfully 

```


```

**Comment by MIchaelMainer** [comment]
Looks like we forgot to set the proxy here: `var httpClient = GraphClientFactory.Create(handlers,,, IWebProxy  );`. That's likely why the first call fails. 

Do you have the download and upload hosts set in your whitelist? For example, is `uatcompanyname-my.sharepoint.com` on your whitelist? They are the URLs in the Location header in the redirected response.  If not, you will need to add them to your whitelist.

**Comment by DamienTehDemon** [comment]
@MIchaelMainer 
Ok so now I am back the point I was at before. They have confirmed that the URL's are whitelisted in the environment, and we have tested it using powershell to make web requests. I do have some more detailed logs though now. It looks like its timing out which I have not seen happen in the previous logs, so this may be a new issue. Is there a way to configure a maximum timeout time? Im thinking maybe its something happening with the proxy limiting the amount of requests? I do not have a full layout of how everything is setup at the moment.

Debug Logs - https://pastebin.com/VsR6gdxH
Trace Logs - https://pastebin.com/NXR9NUHG

**Comment by MIchaelMainer** [comment]
It looks like two problems. Yes, configure timeout for the GraphServiceClient with `GraphServiceClient.HttpProvider.OverallTimeout`.  It currently has 100s timeout. I'm curious whether this is actually happening before 100s. A stopwatch could help here.

Now, looking at your debug log, that the WebException comes from `Microsoft.Identity.Client` HttpClient. Do you have `login.microsoftonline.com` whitelisted? I don't have access to your trace logs, set private.

**Comment by DamienTehDemon** [comment]
I have it whitelisted, if it wasnt whitelisted it would be giving a 407 error if it was running through the proxy, as it asks for authentication if the URL isnt whitelisted and is going through the proxy. From the testing I have done if it isnt running through the proxy it cant resolve the DNS and thats when we get this error.  I cant

Also heres a new log for the trace logs.
https://pastebin.com/duPUnigr

**Comment by DamienTehDemon** [comment]
Looks like the times match up for the time out error, im going to increase it and see if that resolves the issue.

**Comment by DamienTehDemon** [comment]
Well I resolved that particular issue, but I still am not seeing these requests run through the proxy as expected. The log is a little large for the trace file so i threw them into a google drive folder. There is no proxy-authorization header being set on the requests though. We dont have to authenticate with the proxy in order to use it though, the way that it is set up is that urls that are whitelisted skip authentication, and ones that are not, require authentication. Should this header be set regardless though if we are using a proxy? 
https://drive.google.com/drive/folders/19W5tZUwFQql4iYnIG0WFryP3xkUrL1eb?usp=sharing

**Comment by DamienTehDemon** [comment]
So I setup my environment with Fiddler to check and see if the requests were making it to the proxy, which they werent. I updated to the latest version for the MIP SDK, Graph SDK, and Graph Core SDK.  I went from 4 of the dozens of requests showing up in the proxy to dozens. I am thinking this will resolve the issue.

**Comment by DamienTehDemon** [comment]
The client is still getting name resolution error, I have confirmed that its a name resolution error because by logging the status of the WebException.

**Comment by MIchaelMainer** [comment]
> Should this header be set regardless though if we are using a proxy?

Probably not. I misunderstood the proxy requirements when I made that statement.

Are the POST requests making through and making changes to the objects through Microsoft Graph? 

On name resolution, I won't be much help on that.

**Comment by DamienTehDemon** [comment]
You helped alot, appreciate it, resolved all of the actual software requirments, just flakey client environment, so much fun! Appreciate the help Michael.

**Comment by MIchaelMainer** [comment]
You're welcome!

**Comment by DamienTehDemon** [comment]
@MIchaelMainer One last question, the upload sessions for resumable uploads would show up as a post request right?

**Comment by MIchaelMainer** [comment]
It does result in a POST.
