### ISSUE TITLE
Downgrade of System.Diagnostics.DiagnosticSource dependency in version 2 preview versions

### ISSUE THREAD

**Issue by alfisdad** [microsoftgraph/msgraph-sdk-dotnet#948]
Hi.

Is it deliberate that the version of System.Diagnostics.DiagnosticSource being targeted by the newer version 2 preview versions (4.6.0) is lower than the version of the dependency in the current live version (4.7.1)?

This is causing me an issue as I am trying to use the Microsoft.Graph.Beta package and this package targets the latest Microsoft.Graph.Core version 2 preview version. In my project I have a reference to System.Numerics.Vectors v4.1.4 and, when attempting to make a call to one of the methods in the Microsoft.Graph.Beta package, I get the following error:

> Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

I notice that System.Numerics.Vectors is a dependency of System.Memory, which in turn is a dependency of System.Diagnostics.DiagnosticSource.

When I use the Microsoft.Graph package, which targets Microsoft.Graph.Core 1.25.1, which in turn targets version 4.7.1 of System.Diagnostics.DiagnosticSource the call to the Microsoft.Graph method works fine. 
[AB#8814](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8814)

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/240
