### ISSUE TITLE
Docs on Exceptions? 

### ISSUE THREAD

**Issue by jaycdave88** [microsoftgraph/msgraph-sdk-dotnet#95]
I was wondering if there is a location where there is information about the exceptions that the Graph SDK would throw? (i.e. AdalServiceException).

**Comment by MIchaelMainer** [comment]
Hello @jaycdave88,

We don't have documentation on the exceptions thrown by the .Net Graph client library. With that said, there is a single ServiceException used for all 400 and 500 errors. We don't pass through errors from the service. The ServiceException class is also used for client exceptions (I know, this is no bueno, but it is the current state, and I hope to change this). With that stated, search this repo for "new ServiceException" to find all scenarios where we throw this exception.
