### ISSUE TITLE
KeyNotFoundException in Users Collection Page deserialization

### ISSUE THREAD

**Issue by vascofernandes** [microsoftgraph/msgraph-sdk-dotnet#955]
Version: 4.0.0-preview.2

I am trying to read all users in a directory and I get this exception for each user.

`System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'`

It seems that it is trying to read "@odata.type" in a User object.

![image](https://user-images.githubusercontent.com/10337953/113707096-53067800-96d7-11eb-8f9e-fce7fe246195.png)

![image](https://user-images.githubusercontent.com/10337953/113706874-10dd3680-96d7-11eb-8802-a3a5479d00ae.png)

 
[AB#8866](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8866)

**Comment by andrueastman** [comment]
@vascofernandes I am unable to replicate the situation. 
Could you provide more information on the version of Microsoft.Graph.Core that you are using?

The exception `System.Collections.Generic.KeyNotFoundException` has been handled [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/ba5eb6825f9de8e12707907ade8d548314688574/src/Microsoft.Graph.Core/Serialization/DerivedTypeConverter.cs#L47)(You can see the catch block in your screenshot as well). 

Is there any chance that your debugger setting in Visual Studio has been set to break on that particular exception? You can check this by going to **(Debug > Windows > Exception Settings)** 
Then go to **(Common Language Runtime Exceptions >System.Collections.Generic.KeyNotFoundException)**

**Comment by vascofernandes** [comment]
I left out the main pain point of this, my bad sorry.

I know that the exception is being catched. I don't see exception in my app. 

The problem I see is slowness. 
All these exceptions being thrown during JSON parsing makes deserialization really slow, and consequently, reading the directory really, really slow.
I reading a directory with ten's of thousands of users. I takes several minutes...

On a quick glance, It seems that exceptions are being used as control flow (correct me if I am wrong). 
I think there could be a major potential performance improvement here.

Regards

**Comment by andrueastman** [comment]
@vascofernandes Thanks for the clarifying and for the feedback and trying out the preview. It is really appreciated.

It was not really expected for the payload to come without the `@odata.type` especially at such a high frequency as you reported. I agree we could really do better here by replacing the catching of the `KeyNotFoundException` with using something like 
```
if (!jsonDocument.RootElement.TryGetProperty(CoreConstants.Serialization.ODataType, out type))
{
    type = default;
}
```

We shall make this update accordingly.

**Comment by andrueastman** [comment]
This should now be resolved in Microsoft.Graph 4.0.0-preview.3
