### ISSUE TITLE
Microsoft Graph SDK - issue with creating upload session

### ISSUE THREAD

**Issue by TomaszCekala** [microsoftgraph/msgraph-sdk-dotnet#962]
When creating an upload session in MS Graph I get the error "Object reference not set to an instance of an object".
The code I execute:

```
var uploadProps = new DriveItemUploadableProperties
{
     ODataType = null,
     AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "fail" } }
 };

UploadSession uploadSession = Task.Run(() => { return graphClient.Sites[siteId]?.Lists[listId]?.Drive?.Items[folderId]?.ItemWithPath(sharepointPath)?.CreateUploadSession(uploadProps)?.Request()?.PostAsync(); })?.Result;
```

StackTrace:

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
at System.Threading.Tasks.Task`1.get_Result()

The solution stopped working without tampering with the code. Before that, everything was working fine.

I will add that when the request is sent without the "uploadProps" parameter everything works fine.

Could someone help to solve the problem? I have no idea what could be the reason. 
[AB#8950](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8950)

**Comment by baywet** [comment]
Hi @TomaszCekala,
Thanks for reaching out. I have transferred your issue to the dotnet repository as the code snippet you shared is in CSharp. (you posted on the java repo).

**Comment by andrueastman** [comment]
@TomaszCekala Any chance you could provide more information on the version of the SDK you are using?

**Comment by TomaszCekala** [comment]
Hi @andrueastman 

Microsoft.Garph - version 3.8.0.0, runtime version - v4.0.30319
Microsoft.Graph.Auth - version 1.0.0.0, runtime version - v4.0.30319
Microsoft.Graph.Core - version 1.20.1.0, runtime version - v4.0.30319

I would like to add that with each query sent to MS Graph, I get an exception "Object reference not set to an instance of an object" without detailed information about the error, in case an error occurred.

eg if the library does not exist
when called: `var list = Task.Run (() => {return _client.Sites[_site.Id].Lists[listName].Request().GetAsync();}).Result;`
it only receives the information "Object reference not set to an instance of an object" in the catch (Exception ex) {} block.

I will be grateful for your help.

**Comment by andrueastman** [comment]
>"Object reference not set to an instance of an object"

There is the possibility that the issue was closed in later versions of the sdk. Could you try pulling the Microsoft.Graph 3.30.0 version and confirm if this is the same?

**Comment by TomaszCekala** [comment]
It works. Thank you very much for help!
