### ISSUE TITLE
Property Caller.Identity not available in SDK for a callRecord even though the data is present in the Caller object

### ISSUE THREAD

**Issue by julienFlexsoft** [microsoftgraph/msgraph-sdk-dotnet#964]
Hi!

I am trying to get a user Id from a caller in a callRecord, but there seems to be no property "Identity" in the Caller endpoint.
I want to do this:
```
Session session = /* session I got from a callRecord through the SDK */;
string userId = session.Caller.Identity.User.Id;
```

But Caller has no property "Identity" which gives an error in Visual Studio. This is weird because if I set a breakpoint on the session and navigate to the user id in the debugger I can perfectly see the Identity data just sitting there.

For now I fixed it this way:
```
var caller = session.Caller;
var prop = caller.GetType().GetProperty("Identity");
var identity = (IdentitySet)prop.GetValue(caller);
string userId = identity.User.Id;
```

and this works perfectly. I get the user id without any issues.
Is it a bug that there is no Identity property available or am I missing something here? 
[AB#9005](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9005)

**Comment by andrueastman** [comment]
@julienFlexsoft Any chance you could provide more information on the version of the SDK you are currently using?

**Comment by julienFlexsoft** [comment]
Ah yes, of course. I'm using the latest version 3.29.0.

**Comment by andrueastman** [comment]
@julienFlexsoft Thanks for the info. I am unable to find an issue in the deserialization of the Session object. Any chance you could share how you got the Session from the SDK to help narrow down the issue?

**Comment by julienFlexsoft** [comment]
Yes, here it is:
```
// Get callRecord
CallRecord callRecord = await graphServiceClient.Communications.CallRecords[notification.ResourceData.Id]
    .Request()
    .Expand("sessions")
    .GetAsync();

// Get all the sessions
ICallRecordSessionsCollectionPage sessionsRequest = callRecord.Sessions;
IList<Session> allSessions = sessionsRequest.CurrentPage;
while (sessionsRequest.NextPageRequest != null)
{
    sessionsRequest = await sessionsRequest.NextPageRequest.GetAsync();
    allSessions = allSessions.Union(sessionsRequest.CurrentPage).ToList();
};
```

**Comment by andrueastman** [comment]
Thanks for this. 
Can you also confirm for me what the `OdataType` is set to in the Session objects as well? 
(The serializer uses this as the hint to know what type to use for deserialization and if this isn't set correctly, we might witness what you reported)

**Comment by julienFlexsoft** [comment]
The ODataTypes are:

- CallRecord: "microsoft.graph.callRecords.callRecord"
- Session: "microsoft.graph.callRecords.session"
- Caller: "#microsoft.graph.callRecords.participantEndpoint"
- Identity: "microsoft.graph.identitySet"

I cannot use Caller.Identity in the code, but this is a screenshot of what I see in the debugger:
![image](https://user-images.githubusercontent.com/43599122/115213402-c1006580-a101-11eb-993c-8758a6f8c546.png)

**Comment by andrueastman** [comment]
@julienFlexsoft It looks like the deserialization is working as expected. 

However, the Caller property is defined as the base type i.e `Endpoint` in the metadata as shown below. While the properties you wish to access belong to the derived type.

Session type
![image](https://user-images.githubusercontent.com/6464005/115218446-3d4d7580-a10f-11eb-80ae-eeee5d3f133b.png)

ParticipantEndpoint type
![image](https://user-images.githubusercontent.com/6464005/115219558-53a80100-a110-11eb-8994-f8e8d9650ae6.png)

To access properties of the derived type i.e. `ParticipantEndpoint` you will therefore have to do some casting that looks something like this.

```cs
var caller = session.Caller as ParticipantEndpoint;
string userId = caller.Identity.User.Id;   
```

**Comment by julienFlexsoft** [comment]
Perfect, I updated my code and it works perfectly fine!
Thank you!
