### ISSUE TITLE
Group delta is not returning members

### ISSUE THREAD

**Issue by andrew-sumner** [microsoftgraph/msgraph-sdk-dotnet#973]
**Describe the bug**
Group delta is not returning members

**To Reproduce**
PackageReference Include="Microsoft.Graph" Version="3.30.0"

var result = serviceClient.Groups
    .Delta()
    .Request()
    .Filter($"id eq 'xxxx'")
    .Select("id,displayName,members")
    .GetAsync().Result;

**Expected behavior**
I expect the result.CurrentPage[0].AdditionalData or result.CurrentPage[0].Members property to be populated with a list of members.

Using Graph Explorer with this query returns exactly what I would expect to see
https://graph.microsoft.com/v1.0/groups/delta?$filter=id eq 'xxxx'&$select=id,displayName,members

This was working but at somewhere along the line it's stopped returning the members, I haven't figured out which version that was yet.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
 
[AB#9104](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9104)

**Comment by andrueastman** [comment]
Hey @andrew-sumner. Thanks for opening the issue. Are you able to determine if this was working in previous versions. i.e 3.29.0 or before?

**Comment by andrew-sumner** [comment]
I've been trying to get back to a working version but haven't been able to find the right combination yet.

**Comment by andrueastman** [comment]
Could you try using Fiddler to log the requests and identify if the request parameters match the one made out using Graph Explorer?
