### ISSUE TITLE
Headers Prefer IdType="ImmutableId" and outlook.body-content-type="text" are seemingly ignored after a time?

### ISSUE THREAD

**Issue by beausmyth1990** [microsoftgraph/msgraph-sdk-dotnet#975]
I am observing some odd behaviour with the .NET Graph SDK client v3.26. I make a simple request to a User's mailbox for all messages. I add the following header/s to the request - `Prefer: IdType="ImmutableId",outlook.body-content-type="text"`. For a time the request will return all messages with their ImmutableId and Body.ContentType as text, as expected. But, for some reason, after a while it just stops working. Unsure why. Could it be a bug?

**To Reproduce**
Not sure how as I cannot determine when this will happen... I observe the correct functionality for a time but it then ceases to function as expected after this indeterminate period of time has elapsed.

**Expected behavior**
I expect that, which the aforementioned headers applied, the messages I receive from the User's mailbox will return with their respective ImmutableId and Body.ContentType as text every time, without fail.

**Screenshots**
This will unlikely be helpful, but this is my code for requesting all messages.

![image](https://user-images.githubusercontent.com/70828495/115824861-f8e21280-a44b-11eb-9157-56284976ebbb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 90.0.4430.85 (Official Build) (64-bit)
 
[AB#9146](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9146)

**Comment by andrueastman** [comment]
Hey @beausmyth1990,

I believe this could be related to the request made in this issue (see https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/884). Since the pageIterator does not currently forward the header information in the next request. You can take advantage of the requestConfigurator option provided in the SDK to configure all requests.

**Comment by beausmyth1990** [comment]
Hi @andrueastman,

Ahah! Nice :)

Thank you for pointing me in the right direction. I believe that you are correct. Thinking back, I did notice that after I'd sent a certain number of emails (say like 8-10) the ContentType and ImmutableIds weren't coming through in the request to retrieve all messages. I thought that it was certainly weird but I couldn't make the connection, so thank you again.

Kind regards,

**Comment by andrueastman** [comment]
No worries about that @beausmyth1990. Happy to help. For now, I will close this issue and let the feature request be tracked via #884.
