### ISSUE TITLE
How to use Proxy for every request in GraphClient?

### ISSUE THREAD

**Issue by TejendraPrasad** [microsoftgraph/msgraph-sdk-dotnet#982]
Hi Team,

I am trying to use Proxy server to send request and get user details or upload files.

Below Code works fine without Proxy servers

                  IConfidentialClientApplication confidentialClientApplication =
               ConfidentialClientApplicationBuilder
                   .Create(clientId: _clientId)
                   .WithCertificate(GetCertificateByThumbprint(certificateThumbprint: _applicationThumbprint))
                   // .WithClientSecret(clientSecret: _clientSecret)
                   .WithAuthority(AadAuthorityAudience.AzureAdMyOrg, true)
                   .WithTenantId(tenantId: _tenantId)
                   .Build();

	var authenticationProvider = new ClientCredentialProvider(confidentialClientApplication);
	
	
	var _graphServiceClient = new GraphServiceClient(authenticationProvider);
	
	var users = await _graphServiceClient.Users.Request()
                    .Filter("mail eq 'test.test@test.com'").GetAsync();`

However, when i am trying to connect via Proxy - in IIS - i get **407 error proxy authentication required** 

         IConfidentialClientApplication confidentialClientApplication =
               ConfidentialClientApplicationBuilder
                   .Create(clientId: _clientId)
                   .WithCertificate(GetCertificateByThumbprint(certificateThumbprint: _applicationThumbprint))
                   // .WithClientSecret(clientSecret: _clientSecret)
                   .WithAuthority(AadAuthorityAudience.AzureAdMyOrg, true)
                   .WithTenantId(tenantId: _tenantId)
                   .Build();

	var authenticationProvider = new ClientCredentialProvider(confidentialClientApplication);
	
	
                var credentials = new NetworkCredential("username", "password");
               
                var webProxy = new WebProxy("http://proxyserver:8080");
                webProxy.Credentials = credentials;
	
	
	var httpClient = GraphClientFactory.Create(authenticationProvider,"", GraphClientFactory.Global_Cloud, webProxy);
	
	var users = await _graphServiceClient.Users.Request()
                    .Filter("mail eq 'test.test@test.com'").GetAsync();

How to make Graph client use Proxy server. Kindly help.

thank you!
Tej 
[AB#9248](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9248)

**Comment by MIchaelMainer** [comment]
Is `graph.microsoft.com` and `login.microsoftonline.com` on the allow list for the proxy to bypass proxy authentication?

You set the proxy for GraphServiceClient, but not for authentication. Take a look at [ConfidentialClientApplicationBuilder.WithHttpClientFactory(obj)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.confidentialclientapplicationbuilder?view=azure-dotnet) for setting the proxy.

Please let us know if that works.

**Comment by TejendraPrasad** [comment]
Hi @MIchaelMainer, thank you! 

Its working local IIS express, but not working when hosted via IIS.

I tried above code still 407 proxy authentication issue... Do i need to encode if pass contains special character as follow ^ ??

Meanwhile check via wireshark what is going wrong...

**Comment by TejendraPrasad** [comment]
Hi @MIchaelMainer, thank you :)

It worked for me, in out Squid proxy server both authentication was enabled

Both Kerberos and password authentication were enabled in the config – it should be one or the other. We kept only password enabled. and its working.
