### ISSUE TITLE
Unable to get attachments from a group conversation

### ISSUE THREAD

**Issue by olivierowp** [microsoftgraph/msgraph-sdk-dotnet#988]
**Describe the bug**
I want to get the attachments of a post that is part of a group conversation.
The application has the following permissions: Type: Application, Group.Read.All, Group.ReadWrite.All

**To Reproduce**
1.  Client credential provider    
```
//  config.Authority = "https://graph.microsoft.com/{tenanId}",
app = ConfidentialClientApplicationBuilder.Create(config.ClientId)
                 .WithClientSecret(config.ClientSecret)
                 .WithAuthority(new Uri(config.Authority))
                 .Build();
```
2.  Get token
```
// config.ApiUrl = "https://graph.microsoft.com/"
string[] scopes = new string[] {$"{config.ApiUrl}/.default"};
AuthenticationResult result = null;
var uri = await app.GetAuthorizationRequestUrl(scopes).ExecuteAsync();
result = await app.AcquireTokenForClient(scopes);
                    .ExecuteAsync();
```
3. Get group
```
var httpClient = new HttpClient();
var apiCaller = new ProtectedApiCallHelper(httpClient);

await apiCaller.CallWebApiAndProcessResultASync($"{config.ApiUrl}v1.0/groups/{groupId}", result.AccessToken,
                    Display);
```
4. Get threads
```
await apiCaller.CallWebApiAndProcessResultASync($"{config.ApiUrl}v1.0/groups/{groupId}/threads", result.AccessToken,
                     Display);
```
5. Get posts
```
await apiCaller.CallWebApiAndProcessResultASync($"{config.ApiUrl}v1.0/groups/{groupId}/threads/{threadId}/posts, result.AccessToken,
                     Display);      
```
6. Get attachments
```
await apiCaller.CallWebApiAndProcessResultASync($"{config.ApiUrl}beta/groups/{groupId}/threads/{threadId}/posts/{postId}/attachments", result.AccessToken,  Display);
```
Exception:
```
Failed to call the web API: Forbidden
Content: {"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}
```

**Expected behavior**
Unable to get attachments from a group conversation

According to the documentation, if I have the rights to the posts and the group then I should have the rights to the attachments.
https://docs.microsoft.com/en-us/graph/api/post-list-attachments?view=graph-rest-1.0&tabs=http

Why don't I have the rights?

**Screenshots**
![93566-capture-decran-2021-05-04-a-120743](https://user-images.githubusercontent.com/50320762/117143072-b526cb80-adb0-11eb-8c1e-19f0cbca9eff.png)

Client version
v3.30.0
 
[AB#9284](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9284)

**Comment by andrueastman** [comment]
Hey @olivierowp. Thanks for opening the issue.

Is there a specific reason that the attachements call is targeting the beta api instead of the v1.0 api? All the other requests target the v1.0 api.

**Comment by olivierowp** [comment]
No, I just did a test with the beta version. But with the 2 versions, I did not succeed.

**Comment by andrueastman** [comment]
Looking at the docs, [for fetching an attachment for a post](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#permissions), the document cites that application permissions are not supported. 

Because this doc says you can't get a post attachement with app permissions, but the other doc says that you can get a list of post attachements with app permissions, I am unsure if the API supports app permissions on this resource. @dkershaw10 Any chance you can provide any insights on this?

@olivierowp Are you able to look in the response headers and provide us with the client-request-id header to enable us to look further into the request?
