### ISSUE TITLE
Cannot get response header in c# Microsoft graph api request

### ISSUE THREAD

**Issue by jigneshyadav049** [microsoftgraph/msgraph-sdk-dotnet#992]
I am trying to do [File Copy](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http) operation in c# .net core using Microsoft graph API.
It is an asynchronous operation, and by doc, it says it returns a location in the [response header](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http#response) to check the status of the operation,
Now the issue is I need its response header so that I can check the status of file copy operation but every time I am getting 'null' as value, I have tried following code,
```
DriveItem response = await graphServiceClient.Sites[siteId].Drive.Items[itemId]
                                      .Copy(fileName, parentReference)
                                      .Request()
                                      .PostAsync();
```

The response is null but I think at least it should have returned the additional data-carrying response status and location as per document.
And another thing is in the background file copy operation completes and in case i give fileName which already exists it throws exception too.

When I use online [graph api](https://developer.microsoft.com/en-us/graph/graph-explorer) it just works fine returning response and location, but it doesn't with graph client service.

I am using Microsoft.Graph stable version 3.6
and for  online [graph api](https://developer.microsoft.com/en-us/graph/graph-explorer) i used v1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d887c2a6-40ba-675b-7b09-a7a3fffe17f5
* Version Independent ID: 03692ea1-b802-f768-a3bc-04a846b6771a
* Content: [Copy a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-copy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-copy.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley** 
[AB#9324](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9324)

**Comment by andrueastman** [comment]
This is resolved in v4 of the SDK using the [GraphResponse](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#graph-response) object which enables you to now read the response header information.
v4 is still in preview and tracked [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).
