### ISSUE TITLE
Root property from SharePoint site throws Bad Request

### ISSUE THREAD

**Issue by ivancavlek** [microsoftgraph/msgraph-sdk-dotnet#994]
Upon using the Root Property of Sites.GetByPath(...).Drive, I get a _Bad Request_. 

```C#
var bla = await _graphServiceClient
  .Sites
  .GetByPath($"teams/{GetSharePointTeamsSite()}", "mySharepoint.sharepoint.com")
  .Drive
  .Root
  .Request()
  .GetAsync()
  .ConfigureAwait(false);
```

This client code points to the URL https://graph.microsoft.com/v1.0/sites/mySharepoint.sharepoint.com:/teams/myTeam:/drive/root and this URL throws a _Bad Request - Url specified is invalid_.

I am using Blazor WASM in Microsoft Edge 90.0.818.51
I am authenticated in app via Azure AD.
Token included for GraphServiceClient is _Sites.ReadWrite.All_.
I am the _Owner_ of this SharePoint Online site and other queries considering the site (rename, upload etc.) work fine. 
I am using v3.31.0 of Microsoft.Graph Client.
[AB#9345](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9345)

**Comment by pschaeflein** [comment]
You've discovered the hard way that Drives cannot be accessed by relative path. :(

You can get a Drive for a site (`GET /sites/{siteId}/drive`) or for a Group/Team (`GET /groups/{groupId}/drive`). 

Sadly, the shortcut you are attempting won't work.
